### ISSUE TITLE
Server "randomly" starts up in lockdown mode

### ISSUE THREAD

**Issue by andrewgazelka** [ViaVersion/ViaVersion#1025]
Players sometimes cannot join when the server is first booted up. Sometimes one or two players will be able to join, but after that no one else will be able to regardless if their version is the same as the native server (1.8.8). After ViaVersion is disabled, all players can join.

### What is the output link of /viaversion dump? 

https://dump.viaversion.com/b88113256ade223fd04bdcbdf2098afdb2321d714f1055efd21260e878561e0e

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

- BungeeCord version git:BungeeCord-Bootstrap:1.13-SNAPSHOT:9886021:1356 by md_5

### How does this error happen? login? Using an item? 

- Happens somewhat randomly when a server is booted up. Usually will only occur one out of every 30 or so boot ups. It might be related to the startup time or possibly plugin load order.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

No.

**Comment by BestMark** [comment]
I have same problem

**Comment by BestMark** [comment]
@MylesIsCool it works in each case with ViaVersion and BungeeCord.

**Comment by Duartteno** [comment]
same issue here.

**Comment by MylesIsCool** [comment]
@Duartteno Are you able to provide a crash log?

**Comment by andrewgazelka** [comment]
@MylesIsCool for me there is no crash. The server is just in lockdown mode. If there is actually is a _crash log_ he can provide, this might be a different issue.

**Comment by andrewgazelka** [comment]
Also @MylesIsCool I am confused why the server is still in lockdown mode _until_ ViaVersion is disabled. I can't test with other configurations because this only occurs on the production server. However, I can give you nearly any other data you need.

**Comment by andrewgazelka** [comment]
@BestMark @Duartteno out of interest are either of you using zPermissions?

**Comment by MylesIsCool** [comment]
According to discussion with Andrew over Discord, this should now be resolved in the latest builds 🥳
