### ISSUE TITLE
String#toLower/UpperCase() without locale may break turkish servers

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaVersion#1126]
https://github.com/MylesIsCool/ViaVersion/blob/8bfcc550f7119c9b65bc915b705ebf7c5ab15fdd/common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/providers/PaintingProvider.java#L48
https://github.com/MylesIsCool/ViaVersion/blob/73dccbaf2428dcc5675730cc6d1cd48e37983047/common/src/main/java/us/myles/ViaVersion/commands/ViaCommandHandler.java#L36
https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#toLowerCase()

**Comment by MylesIsCool** [comment]
Should be fixed in latest build - http://mattryall.net/blog/2009/02/the-infamous-turkish-locale-bug
