### ISSUE TITLE
Switching potions on hotbar makes you lose 1 potion

### ISSUE THREAD

**Issue by Ronaldinho12** [ViaVersion/ViaVersion#1179]
**Describe the bug, provide any errors**
When you drink potion and in the last moment you switch to another you will drink both of them but gain effect from 1.

**How can we reproduce it?**
When you drink potion and in the last moment you switch to another you will drink both of them but gain effect from 1.

**Expected behaviour**
Drink 1 potion and dont drink another.

**Screenshots**
not needed

**ViaVersion Dump:**
not needed

**Additional server info**
bungeecord

**Comment by MylesIsCool** [comment]
You need to provide further information like the versions it happens on, Dump is also relevant unless you can replicate on vanilla.

**Comment by MylesIsCool** [comment]
See above, we need more info
