### ISSUE TITLE
1.13 client on 1.12.2 server crashes when block connections are enabled

### ISSUE THREAD

**Issue by Legobuilder0813** [ViaVersion/ViaVersion#1195]
**Describe the bug, provide any errors**
https://hastebin.com/vezunepufe.cs
When connecting to a server running 1.12.2 with a 1.13.2 client (through the latest version of BungeeCord at the time of writing: build 1396), with the latest public version of ProtocolLib, ProtocolSupport and the latest CI version of ViaVersion with 1.13 block connections enabled, sometimes the player crashes. The above hastebin link shows the full stacktrace of errors. The client only crashes when joining away from the spawn of the world. In the above example, the player joined at -78, 64, 2942 (far from spawn), however joining at -80, 65, 2421 (close to spawn) doesn't cause the player to crash. The stacktrace seems to hint that perhaps some math related to storing chunks in HashMaps is being done incorrectly.

**How can we reproduce it?**
1. Connect to a 1.12.2 server using MC 1.13.2 (perhaps at the specific coordinates -78, 64, 2942?)

**Expected behaviour**
Connecting to the server with no issues.

**Screenshots**
N/A

**ViaVersion Dump:**
https://dump.viaversion.com/a1fadbb4ceae03b300590e34b33af65e72711478423bbb0559d5f2cdd3a7665c

**Additional server info**
Running latest Spigot for 1.12.2 (git-Spigot-e8ded36-acbc348), BungeeCord build 1396, ProtocolLib 4.4.0, ProtocolSupport 4.28, WorldEdit and WorldGuard

**Comment by MylesIsCool** [comment]
I'd assume this is because of block-connections accessing a chunk while it's being modified. Unsure of the direct solution at the moment as I suspect moving it to sync loading will slow down connections / impede server load quite a bit.

**Comment by MylesIsCool** [comment]
Just as a note, we'll look into fixing this but for the release we're suggesting packet block-connections as the primary method as in some cases we're seeing this issue. There's definitely a server factor going on as not everyone has it though.

**Comment by TNTUP** [comment]
Same issue as here, getting reports of players getting kicked randomly and I need that block-connections thing, guess I'll live with it until it gets fixed when you have time^^

**Comment by MylesIsCool** [comment]
> Same issue as here, getting reports of players getting kicked randomly and I need that block-connections thing, guess I'll live with it until it gets fixed when you have time^^

Use packet mode

**Comment by TNTUP** [comment]
Ok thanks!

**Comment by TNTUP** [comment]
Well it still happens even in packet mode, keeping an eye on updates. They get "Lost connection to the proxy" message

**Comment by MylesIsCool** [comment]
@TNTUP Can you confirm if this happens with block-connections completely disabled cause this doesn't sound related to this issue

**Comment by TNTUP** [comment]
@MylesIsCool Will try on next server reboot^^ I decided to update ViaVersion to the latest commit, I'll let you know

**Comment by FormallyMyles** [comment]
I'm going to close this issue as a won't fix, for now, the reasoning being that world is unstable but the battle of modifying stuff through reflection isn't worth the time (mostly needs to be integrated into the server to reduce race conditions).

Using packet is a pretty viable option (but slow), world is definitely fine on quite a few implementations but obviously mileage may vary.
