### ISSUE TITLE
Forge breaks sword blocking without shield

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaVersion#1203]
**Describe the bug, provide any errors**
Sword blocking doesn't work when Forge is installed on client and shield blocking isn't enabled

**How can we reproduce it?**
1. Disable shield blocking
2. Enter the server
3. Try to block with sword
4. Forge client ignores the sword blocking

**Expected behaviour**
It should block correctly like vanilla does

**Additional server info**
Forge 1.12.2-14.23.5.2815 client
1.8 server

**Comment by creeper123123321** [comment]
There is a way to workaround, using replacing swords with potions

**Comment by MylesIsCool** [comment]
Don't really think this is worth looking into because it's most likely down to how forge handles it.
