### ISSUE TITLE
CommandBlock bugg

### ISSUE THREAD

**Issue by RuudSchutten** [ViaVersion/ViaVersion#1212]
Server version: 1.12.2
ViaVersion: ViaVersion-2.0.0-SNAPSHOT.jar

If I join in 1.13.2 and I want to put something in a command block, it does not give output. 
So I can't see what's in a command block.

**Comment by Speentie8081** [comment]
Haha, this has been an issue with ProtocolSupport for ages, so I've just come to live with not having command block output. I just test the command before putting it in the command block, problem solved.

**Comment by sannielollie** [comment]
Same issue here, i just play in 1.12 for now if i need to do something with commandblocks..

**Comment by MylesIsCool** [comment]
Should be fixed in latest dev build, thanks to @creeper123123321  :)
