### ISSUE TITLE
1.7 players get kicked

### ISSUE THREAD

**Issue by InvixYT** [ViaVersion/ViaVersion#1214]
**The error**
The error is caused by me if i log on with 1.7 on a 1.7 travertine bungeecord. I have installed viaversion and viarewind. Before i could log in with 1.7 and after the dev viaversion i couldnt. 
https://hastebin.com/bejuxozoqu.bash

**Steps to reproduce the behavior:**
1. Make sure you have the newest viaversion in your server.
2. Make sure your server is running Travertine the newest version.
3. Login on 1.7
Thats it. Your getting disconected from the server with the error in the console.

**Expected behaviour:**
I expected to just join but ihve got disconnected after like 3 seconds.

**ViaVersion Dump:**
https://dump.viaversion.com/a5c437dcb795b75c167afa63b14eb3ce997e5959c012844d8afd7843a82cc94a

**Additional server info**
I use a Travertine proxy with the plugins: Antibotdeluxe, AntiBungeePluginSteal, BungeeOnlineTime, ClientStats, EzQueue, PixelHub, ViaRewind, ViaVersion

**Comment by krusic22** [comment]
You need to use ViaRewind-Dev.

**Comment by InvixYT** [comment]
I am so stupid, I should have thought about that before. Thank you!
