### ISSUE TITLE
Entity trackers don't receive the new entity id when changing servers in BungeeCord

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaVersion#1215]

**Comment by creeper123123321** [comment]
Workaround for users: use Waterfall and enable ``disable_entity_metadata_rewrite`` in Waterfall config

**Comment by creeper123123321** [comment]
https://github.com/ViaVersion/ViaBackwards/issues/26 seems to be related

**Comment by MylesIsCool** [comment]
Fixed in latest build
