### ISSUE TITLE
Visual glitch on approaching chest

### ISSUE THREAD

**Issue by sannielollie** [ViaVersion/ViaVersion#1216]
**Describe the bug, provide any errors**
visual glitch/bug - when approaching a double chest next to a wall with stairs. Opening the chest solves it temporarily - if you come back later to the same chunk again the visual glitch/bug appears again.

**How can we reproduce it?**
I dont know exactly, i think it has something to do with the stairs that where in my structure.

**Expected behaviour**
A double chest showing up normally

**Screenshots**
No screenshots, but i got a short video: https://www.youtube.com/watch?v=j1e3pnDC-NU

**ViaVersion Dump:**
- https://dump.viaversion.com/659f5c5a6bddcc304497a8bd597b5f8bbc40f6fdb92f4f039c38eb06c564c508

**Additional server info**
Bungeecord, Spigot 1.12.2.
Plugins (119): PlayTimeRewardsRecoded, PlugMan, AutoShutdown, ConsoleSpamFix, InfiniteDispenserX, Minator, CustomPolls, RecipeBookDupePatch, DynamicBungeeAuth, MySQLWhitelist, ChatControl, AdvancedBan, AutoCrafters, VoidSpawn, DeathMessagesPrime, MVdWPlaceholderAPI, VotingPlugin, VoidGenerator, 3DManeuverGear, mcMMO, ElytraPlus, SimpleSit, GroupManager, Winter, EntityDetection, Sinterklaas, InfinityDispensers, Emoti, Sudo, NoteBlockAPI, WorldBorderPearlBlock, SantaClaus, ChatColor, CoreProtect, dynmap, Wild, WorldEdit, AutoSapling, Essentials, PacketListenerApi, AnimatedNames, ClearLag, Elevator, BannerBoard, BlockParty, Votifier, NightVision, JsonMessageMaker, SimpleBossBar, Vault, MassiveCore, EnjinMinecraftPlugin, FishyDispensers, LWC, PlayerPoints, XRayHunter, AddLight, ViaVersion, ViaBackwards, Banknotes, ProtocolLib, Citizens, CrazyAuctions, EssentialsChat, GAListener, Superpickaxe, Dynmap-Essentials, Trading, PlotSquared, TrailGUI, HideAndCustomPlugins, WorldGuard, Factions, ASkyBlock, UltraBar, EssentialsSpawn, WorldGuardExtraFlags, ChangeSkin, HeadDatabase, LibsDisguises, ChopTree3, React, HideAndSeek, iControlU, CombatTagPlus, Parties, AAC, Quests, CustomEnchantments, PremiumVanish, GadgetsMenu, SilkSpawners, Multiverse-Core, FactionsDynmap, MiniaturePets, BossShopPro, Multiverse-Inventories, BungeeTabListPlus, HeadsPlugin, DiscordSRV, HeavySpleef, ConditionalCommands, GriefPrevention, HolographicDisplays, ChristmasPlus, BierfietsMuziekspeler, HolographicScoreboard, CorpseReborn, RedstoneCommand, HeadsInventory, ProtectionLib, CratesPlus, AdvancedMobArena, FurnitureLib, DiceFurniture, PluginLibrary, Statz, Autorank, HorseTpWithMe

**Comment by sannielollie** [comment]
Found another visual glitch - this time with fence. 

1.12 client: https://cdn.discordapp.com/attachments/459661086145380353/554412892577857545/unknown.png

1.13.2 client: 
https://cdn.discordapp.com/attachments/459661086145380353/554412691461242930/2019-03-10_22.17.20.png

**Comment by creeper123123321** [comment]
What's the coordinates of the blocks?

**Comment by sannielollie** [comment]
I do not know if it is useful to show the coordinates, because I do not think it has anything to do with the problem.

**Comment by MylesIsCool** [comment]
We're unable to replicate this, we'll reopen it if you can provide us:
A .zip of a world where this happens (as few plugins as possible please)

And we'll look into sorting it if it still happens, though we may of fixed it in the latest builds.
