### ISSUE TITLE
Server in 1.8 (players that connect with 1.13 can't type in chat) 

### ISSUE THREAD

**Issue by ricardoborsato** [ViaVersion/ViaVersion#1218]
Hello Guys.
I have a bungeecord, but I don't have any chat plugin in bungeecord.
I also have others 3 servers in 1.8 spigot version
All the servers have Viaversion plugin
But who connect with 1.13 version simply can't talk on chat. 
(Sorry English Errors)
Have a blessed day ♥
- Ricardo M. Borsato

**Comment by MylesIsCool** [comment]
See config option for 1.13 auto complete.

**Comment by krusic22** [comment]
If you are using AuthMe and AuthMeBungee, update them to the latest Dev versions.

**Comment by ricardoborsato** [comment]
I need set "disable-1_13-auto-complete" to "true"?

**Comment by MylesIsCool** [comment]
Yeah

**Comment by krusic22** [comment]
If you can't chat at all on 1.13.2 then update AuthMe and AuthMeBungee to the latest dev builds (if you are using them).

**Comment by ricardoborsato** [comment]
Ok thanks ♥

**Comment by ricardoborsato** [comment]
Sorry to reopen guys, but I tried to set disable 1_13 autocomplete to true and not works =/

**Comment by ricardoborsato** [comment]
@krusic22 I don't have authmebungee in my server
