### ISSUE TITLE
Blocks Connect on 1.12.2 also need a fix

### ISSUE THREAD

**Issue by mkcoldwolf** [ViaVersion/ViaVersion#1224]
**Describe the bug, provide any errors**
Block connection on 1.12.2 is still somewhere weird
but 1.13.2 is fixed
on 2.0.0-Snapshot where SERVERSIDE-BLOCKCONNECTION is true
Assume that all blocks on #1151 have also affected on here

**How can we reproduce it?**
1. Login on 1.12.2
2. Place some iron bars by Cylinder like
3. and, player will stuck inside those air gap if they walk into it

**Expected behaviour**
it should look like the same as the 1.13.2 and 1.8.9

**Screenshots**
![image](https://user-images.githubusercontent.com/32544898/54821686-f39ac280-4cdd-11e9-9c43-111a5d425911.png)
![image](https://user-images.githubusercontent.com/32544898/54822350-c2bb8d00-4cdf-11e9-9937-1f0bf1018270.png)
![image](https://user-images.githubusercontent.com/32544898/54822294-addef980-4cdf-11e9-8dab-0fdff3d3b5d3.png)
![image](https://user-images.githubusercontent.com/32544898/54821721-07debf80-4cde-11e9-9404-bd5c5dc73550.png)

**ViaVersion Dump:**
https://dump.viaversion.com/9d3622962030dc8c23f2a2eb0ba8d1a22c7c6482af71e19091e1941d1caf35ff

**Additional server info**
BungeeCord, plugins are listed on Dump, dont think its related to plugin

**Comment by MylesIsCool** [comment]
Unfortunately, it's not possible in prior versions to display the different connecting states as they're calculated by the client.

**Comment by mkcoldwolf** [comment]
> Unfortunately, it's not possible in prior versions to display the different connecting states as they're calculated by the client.

Then im thinking how do 1.13.2 works by calculate those connection on server side 🤔

**Comment by MylesIsCool** [comment]
> > Unfortunately, it's not possible in prior versions to display the different connecting states as they're calculated by the client.
> 
> Then im thinking how do 1.13.2 works by calculate those connection on server side 🤔

Because Mojang changed the blockstates in 1.13.2 to be fully encoded by the server (allowing the server to send 1000s more different blockstates than previously possible).

**Comment by mkcoldwolf** [comment]
> > > Unfortunately, it's not possible in prior versions to display the different connecting states as they're calculated by the client.
> > 
> > 
> > Then im thinking how do 1.13.2 works by calculate those connection on server side 🤔
> 
> Because Mojang changed the blockstates in 1.13.2 to be fully encoded by the server (allowing the server to send 1000s more different blockstates than previously possible).

oh i see, thanks!
