### ISSUE TITLE
ViaVersion with block connections enabled crashing server

### ISSUE THREAD

**Issue by Bestle** [ViaVersion/ViaVersion#1231]
Happens on a 1.8.9 server, may happen on other versions too. Similar to #1195 except the server is actually crashing.

Can be difficult to reproduce but is caused by asynchronous calls to getChunkAt removing chunks from the unloadQueue in ChunkProviderServer.

This causes an ArrayIndexOutOfBoundsException if the server is unloading chunks at the same time.

https://gist.github.com/Bestle/ab229dc990a1d2ba2a4593cf68c9358b

**Comment by MylesIsCool** [comment]
This is caused by the same issue, so follow #1195 for progress, my advice would be to try packet level block-connections or disable it.
