### ISSUE TITLE
ViaVersion "no key for" 1.13.2 server version with last build

### ISSUE THREAD

**Issue by BoBsmil3Y** [ViaVersion/ViaVersion#1232]
Hey !

Just reworking on a server, and I have put the latest dev of ViaVersion on a 1.13.2 PaperSpigot server, and that what append : https://pastebin.com/hF2vxFPP
Plugins : ProtocolLib, Socket4MC, Vault, viaBackward (3.0.0 Snapshot) and ViaVersion (2.0.0 Snapshot)

**Comment by MylesIsCool** [comment]
ViaBackwards versions are dev versions hence the debug
