### ISSUE TITLE
Pair{PLAY, -1} already registered!

### ISSUE THREAD

**Issue by BoBsmil3Y** [ViaVersion/ViaVersion#1238]
**Describe the bug, provide any errors**
Log : https://pastebin.com/5ZnH12Me

**How can we reproduce it?**
When server start

**ViaVersion Dump:**
- https://dump.viaversion.com/907fcf78708d30b74edfd919fa06735a9a9e60831c71cb487eab9800f3b06c46

**Additional server info**
PaperSpigot 1.13.2
Using a bungeecord (but viaversion are set on individually server)
ViaBackwards v3.0.0-SNAPSHOT (with lot of error on startup)

**Comment by MylesIsCool** [comment]
This is something that we'll need to resolve with ViaBackwards (also because it's a DEV build it doesn't have this).
