### ISSUE TITLE
Logs turn to stone 1.13.2 client on a 1.12.2 server

### ISSUE THREAD

**Issue by Smartjer123** [ViaVersion/ViaVersion#1243]
**Describe the bug, provide any errors**
Logs turn to stone even when they exist in 1.12.2

**How can we reproduce it?**
1. Go one 1.13.2
2. Try to get a spruce log
3. Turns to stone

**Expected behaviour**
It should give you the log and allow you to place it down

**Screenshots**

**ViaVersion Dump:**
https://dump.viaversion.com/25da884911456e8b687292815f78f9339cc12c929d3eb64abc986fb72f41a837

**Additional server info**
Bungeecord. Paper spigot.

**Comment by MylesIsCool** [comment]
This is because there are new blocks, Spruce Wood is new.
