### ISSUE TITLE
Can't connect lower than what server is running at

### ISSUE THREAD

**Issue by Paperboypaddy** [ViaVersion/ViaVersion#1251]
**Describe the bug, provide any errors**
So on my 1.12 server with the latest viaversion build 2.0.0 304 I connect with anything lower than my servers version and it doesn't let me connect. I just tested to see if it was a via version problem and it is, on 1.6.0 it works like it should. But as much as I like my compatibility I like to have 1.13 to work right like the dev builds have. here's a pretty big error, I put my server in debug https://hastebin.com/nasozevici.md

Edit: Its a really bad issue because I've been having players lately that can't connect because of this.

**How can we reproduce it?**
1. Join server on lower version that what its running
2. You should get an error if you have bungee

**Screenshots**
![Screen Shot 2019-04-10 at 9 03 54 AM](https://user-images.githubusercontent.com/35149493/55894752-9624c380-5b6f-11e9-8404-f353650227d2.png)

**ViaVersion Dump:**
https://hastebin.com/nasozevici.md

**Additional server info**
I use the bungee with 2 1.12 spigot severs, here are all the plugins I'm running on the server with the issue: PluginConstructorAPI, VIPJoinMessage, JumpPads, PlaceholderAPI, EasySetSpawn, WorldResourcepacks, HolographicDisplays, Friends3_0, Images, SuperTrails, ViaVersion, SimpleAPI, ViaBackwards, LightAPI, PluginManagerReloaded, DamageUtility, FlyUtility, AdvancedPortals, FastAsyncWorldEdit, VoidGenerator, DeluxeMenus, Parkour, Vault, ServerRestorer, ChairStairs, LightSource, ViaRewind, BKCommonLib, WorldEdit, TNTRun_reloaded, Essentials, HeadDatabase, Citizens, EssentialsChat, BuildBattle, PlotSquared, WorldGuard, SkyWars, EssentialsProtect, EssentialsGeoIP, EssentialsAntiBuild, CommandNPC, NetworkManager, Multiverse-Core, BedwarsRel, HeavySpleef, ItemJoin, MineResetLite, ChestShop, SurvivalGames, CommandSigns. BKCommonLib seems to not work when I installed it.

**Comment by MylesIsCool** [comment]
ViaVersion supports newer versions, otherwise, if you use dev builds you need the right build of each via plugin.

https://ci.viaversion.com/view/All/job/ViaVersion/
https://ci.viaversion.com/view/All/job/ViaBackwards/
https://ci.viaversion.com/view/All/job/ViaRewind-DEV/

**Comment by Paperboypaddy** [comment]
ooh makes sense
