### ISSUE TITLE
Bug scoreboard colours for 1.13.2 clients

### ISSUE THREAD

**Issue by Quentixx** [ViaVersion/ViaVersion#1255]
I'm working on a 1.8 server and the colors in the scoreboards are bugged. This bug is only valid for 1.13.X clients

![image](https://user-images.githubusercontent.com/11049729/56228887-fdafa700-6078-11e9-84f9-393dd76cd03f.png)

I have already set the configuration "fix-teams-colours" to true

My viaversion dump : https://dump.viaversion.com/e684964c00c9c9662792d5d80f4dadc706595b978370eebde6fdf97a66aade4e

Thanks

**Comment by Matocolotoe** [comment]
Déjà signalé il me semble
_I think it has already been reported_

**Comment by MylesIsCool** [comment]
Would you be able to provide a plugin or something similar so we can replicate this to fix it?

**Comment by TheMonDon** [comment]
I am using QuickBoard on a 1.12.2 server, clients in 1.13.2/1.14 after 14 characters (it seems) The rest of the line turns white. I am using the option fix-team-colours. 

Here is my scoreboard config: https://paste.helpch.at/vaqapewawo.diff

I'm unable to give a viaversion dump.

![image](https://user-images.githubusercontent.com/11539895/56673064-381ed280-667d-11e9-9233-e388071cc922.png)

The top line has 14 chars while the bottom is 16 (for testing)

**Comment by Xernium** [comment]
I was able to reproduce this with text that uses the *non-flicker* refresh hack. This doesn't happen on re-sending the objective. Probably related to the max text component length

**Comment by Niall7459** [comment]
![Screen Shot 2019-09-27 at 11 16 08](https://user-images.githubusercontent.com/9781846/65762562-3a4bf800-e119-11e9-99bf-f6ceffe4cb52.png)
![Screen Shot 2019-09-27 at 11 19 07](https://user-images.githubusercontent.com/9781846/65762565-3c15bb80-e119-11e9-9b15-3ca2d4e42fd1.png)
Also seeing this issue, doesn't matter what colour I send at the start of the suffix, but its always displayed as white.

**Comment by krusic22** [comment]
Looks like the text gets reset after 16 chars.

**Comment by Niall7459** [comment]
Hey, is there any progress on this issue @MylesIsCool ?
Thank you.
