### ISSUE TITLE
1.13.2 client disconnect from 1.12.2 server when sending Chat score w/ tellraw/title command

### ISSUE THREAD

**Issue by zedwick** [ViaVersion/ViaVersion#1256]
**Describe the bug, provide any errors**
When sending chat json containing a score element to a client, the client is disconnected.
the following is shown in the server console when sending an offending tellraw command:

> [13:23:20] [Server thread/INFO]: Zedwick issued server command: /tellraw @a {"score":{"name":"Zedwick","objective":"score"}}
[13:23:20] [Server thread/INFO]: Zedwick lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

**How can we reproduce it?**
1. Login with a 1.13.2 client to 1.12.2 server
2. send the command `/tellraw @a {"score":{"name":"Zedwick","objective":"score"}}`
3. You will be disconnected.

**Expected behaviour**
With a 1.12.2 client, you will see the player/name's score for the given objective 'score' (if one exists, or a blank message if not).

**Additional server info**
MC Server: git-paper-1209
Viaversion: 2.0.0-SNAPSHOT (build 304)

**Comment by creeper123123321** [comment]
Related with https://github.com/SpigotMC/BungeeCord/commit/5aaccd2e9ec554f8f769aa0eb11a7393236aad85

**Comment by zedwick** [comment]
I've updated to git-paper-1613, which now yields a slightly different message in the console on disconnect:

> [18:25:04] [Server thread/INFO]: Zedwick lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.google.gson.JsonParseException: A score component needs at least a name and an objective

**Comment by MylesIsCool** [comment]
Notes from creeper when we get around to fixing this:

Need to shade a new version of BungeeCord chat api, relocating and ensuring it doesn't interfere with anything else

**Comment by MylesIsCool** [comment]
Should be fixed in the latest build, though if you use any other Via plugins you may need to update them too.
