### ISSUE TITLE
Failed to initialize a channel

### ISSUE THREAD

**Issue by Bakalexis** [ViaVersion/ViaVersion#1264]
**Describe the bug, provide any errors**
You can check on the screenshot below 

**How can we reproduce it?**
1. Install ViaVersion on your BungeeCord

**Expected behaviour**
No error message should be shown

**Screenshots**
https://prnt.sc/nf2xz0

**ViaVersion Dump:**
https://dump.viaversion.com/08858b70f142854d56ae2699cd8895413371407fe4c9ffa09e5e43585e419802

**Additional server info**
I'm on BungeeCord, also i'm using spigot version of ViaVersion but I don't know if there is a link with this error.

**Comment by MylesIsCool** [comment]
You can update to builds from ci.viaversion.com or ignore the error
