### ISSUE TITLE
1.14 Crash when changing servers with bungeecord

### ISSUE THREAD

**Issue by PureGero** [ViaVersion/ViaVersion#1268]
**Describe the bug, provide any errors**
When changing servers in BungeeCord on 1.14, the client crashes.

Crash report:
https://hastebin.com/semogisoci.makefile

**How can we reproduce it?**
1. Login on 1.14
2. Join a BungeeCord network
3. Connect to another server within the BungeeCord network
4. Client crashes

**Expected behaviour**
Client shouldn't crash

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.

That command ^ disconnects me from the server in both 1.13.2 and 1.14, so that can be an issue for another time.
The ViaVersion version is as at commit [34b0db5](https://github.com/ViaVersion/ViaVersion/commit/34b0db57ae4288b60c945bbe8953032afe59eadb)

**Additional server info**
Latest 1.13.2 version of BungeeCord and Spigot

**Comment by MylesIsCool** [comment]
See https://github.com/ViaVersion/ViaVersion/issues/1215 (you need to use Waterfall for now)
