### ISSUE TITLE
The rain passes through solid blocks.

### ISSUE THREAD

**Issue by Patbox** [ViaVersion/ViaVersion#1269]
**Describe the bug, provide any errors**
The rain passes through solid blocks.

**How can we reproduce it?**
1. Join 1.13.2 server on 1.14
2. Wait for rain or use /rain command.
3. Go underground/make a roof.

**Expected behaviour**
Rain stops on blocks

**Screenshots**
![image](https://user-images.githubusercontent.com/39821509/56598272-8045e280-65f4-11e9-94f8-5b10306c3276.png)
![image](https://user-images.githubusercontent.com/39821509/56598583-0bbf7380-65f5-11e9-8642-b26d7e72d5bb.png)

**ViaVersion Dump:**
https://dump.viaversion.com/04da73533f1404648ea6a1a046e47187185036818cef0f86332df5e31ac67a89

**Comment by SmallSansSerif** [comment]
I can confirm this is happening too.

**Comment by MylesIsCool** [comment]
Great news, you'll no longer need your umbrella indoors. We've fixed this in latest dev thanks to Gerrygames. Will push it to a release soon(tm)
