### ISSUE TITLE
1.14 The 'Sneak Animation' is displayed wrong

### ISSUE THREAD

**Issue by BOOM21** [ViaVersion/ViaVersion#1270]
1. Login on 1.14'
2. Sneak
3. The 'Sneak' is not displayed for others

**Expected behaviour**
People should visibly be sneaking

**Screenshots**
unnecessary 

**ViaVersion Dump:**
Due to issue with that command not possible to attach

**Additional server info**
Waterfall

**Comment by MylesIsCool** [comment]
Should be fixed in latest build
