### ISSUE TITLE
IOException: Packet 0/55 (me) was larger than I expected, found 41 bytes extra whilst reading packet 55

### ISSUE THREAD

**Issue by mibby** [ViaVersion/ViaVersion#1271]
Paper dev 624 (Spigot 1.13.2)
Waterfall dev 278 (Bungee w/ 1.14 protocol)
ProtocolSupport dev 377
ViaVersion dev 314

When trying to connect with a 1.14 client, I get disconnected with this message. 
![link](https://i.imgur.com/SRUssV7.png)

In my client logs, all I see is;

```
[13:19:28] [Netty Client IO #4/ERROR]: Could not deserialize minecraft:nbt
[13:19:28] [Netty Client IO #4/ERROR]: Could not deserialize minecraft:nbt
[13:19:28] [Netty Client IO #4/ERROR]: Could not deserialize minecraft:nbt
```

Nothing in either the Bungee or Server logs indicate any errors or problems.

**Comment by mibby** [comment]
Any ideas? @MylesIsCool :(

**Comment by MylesIsCool** [comment]
Have you enabled entity rewrite for Waterfall?

**Comment by mibby** [comment]
@MylesIsCool I disabled the rewrite since the Waterfall commit recommended doing so. Should it be enabled?

```
disable_entity_metadata_rewrite: true
```

**Comment by MylesIsCool** [comment]
Yeah that's fine, try latest build otherwise

**Comment by mibby** [comment]
With dev 318 and ``disable_entity_metadata_rewrite: false``, I seem to be able to login with 1.14 now! Thanks. :)
