### ISSUE TITLE
Viaversion says I am outdated on version 2.0.0

### ISSUE THREAD

**Issue by dzlandis** [ViaVersion/ViaVersion#1273]
After updating Viaversion to 2.0.0 I get this message in chat that says it is outdated. This is incorrect though.
![Viaversion_Bug_Picture](https://user-images.githubusercontent.com/49926644/56622198-f7bf4600-65e3-11e9-8be1-5c639de3c5ea.png)

**Comment by dzlandis** [comment]
If you need anymore information I am happy to provide :)

**Comment by MylesIsCool** [comment]
You should complete https://github.com/ViaVersion/ViaVersion/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by electronicboy** [comment]
How did you manage to pull ViaVersion out of that?

**Comment by MylesIsCool** [comment]
If you have issues outside of the message, please fill in the full issue template so we can work out what's going on and we'll take a look.
