### ISSUE TITLE
Exception joining on 1.14

### ISSUE THREAD

**Issue by Artuto** [ViaVersion/ViaVersion#1274]
**Describe the bug, provide any errors**
I joined on 1.14 with build 318 and got this https://hastebin.com/zivamosawe.md

**How can we reproduce it?**
1. Login on 1.14
2. Have something on your inventory? (Says something about json so i'm guessing its about NBT)

**Expected behaviour**
Be able to login

**Screenshots**
https://artuto.s-ul.eu/X4WAWJVd

**ViaVersion Dump:**
- https://dump.viaversion.com/d9e0f6036a00fc55bcbbc51daa2c993164e1772e45e6b9b1d4525213de8d11bd

**Additional server info**
Using WaterDog (Waterfall fork - https://github.com/yesdog/Waterdog)

**Comment by MylesIsCool** [comment]
Pretty sure this isn't a big in ViaVersion, and is something inventive talent needs to look into. Unsure though but we don't remove stuff from the pipeline.

**Comment by Artuto** [comment]
Then what I should I do?

**Comment by MylesIsCool** [comment]
Report it to her or don't use the plugin?

**Comment by Artuto** [comment]
I mean i dont know what ViaVersion is using of Inventive talent tbh

**Comment by MylesIsCool** [comment]
It's the plugin that uses PacketListenerApi

**Comment by Artuto** [comment]
I removed PacketListenerApi and the same issue persists, no console output this time tho.

**Comment by MylesIsCool** [comment]
Yeah so the other issue is probably caused by something in your world with invalid JSON, unfortunately there's no way to tell what because it's the client rejecting it. 

It might be a case of testing with no plugins / wiping scoreboards

**Comment by Artuto** [comment]
Guess i'll do a binary search or something
