### ISSUE TITLE
Client Crash with ViaBackwards

### ISSUE THREAD

**Issue by Tomographix** [ViaVersion/ViaVersion#1276]
**Describe the bug, provide any errors**
I am running a bungee setup with 4 servers running paperspigot 1.13.
I have installed ViaBackwards onto the bungee to allow for 1.14 clients to connect.
On connecting to a server the first time the client will crash with an error like this:
https://hastebin.com/fiyonemota.cs

Interestingly, once you restart your MC client you can login fine.

**How can we reproduce it?**
1. Login on 1.14'
2. Change servers with /server {name}
3. Client crashes

**Expected behaviour**
Move between servers.

**Screenshots**
N/A

**ViaVersion Dump:**
Does not seem to work for via backwards.

**Additional server info**
BungeeCord

**Comment by DDuart** [comment]
Same issue here, i'm using:
- newest Waterfall with `disable_entity_metadata_rewrite: true`
- latest non-dev ViaRewind, ViaBackwards, ViaVersion

**Comment by MylesIsCool** [comment]
Gonna close as the initial issue was fixed by updating, if you have a similar issue etc make a new issue.
