### ISSUE TITLE
us.myles.ViaVersion.protocols.base.BaseProtocol$1 (Anonymous)

### ISSUE THREAD

**Issue by x1p** [ViaVersion/ViaVersion#1277]
**Describe the bug, provide any errors**
https://hastebin.com/ferobayuju.php

**How can we reproduce it?**
I'm not sure what caused it. Its probably a ping from somewhere. It's not from anyone joining. The ip is not know to me. It's a test server, so the one causing it should be known to me, but it's not.

**ViaVersion Dump:**
https://dump.viaversion.com/66e0a01d5ec7bd38d0a0ab426eefdba0b2e9a95ac9c942d9aec433fb074925d1

**Additional server info**
BungeeCord-Bootstrap:1.14-SNAPSHOT:4cef6d1:1405
ViaVersion v 2.0.1 build 318

**Comment by MylesIsCool** [comment]
This is a client sending bad info to your server, we can't really do much about this. I'd suggest firewalling them if it's a huge issue.
