### ISSUE TITLE
Lighting bug - visual bug: stairs slabs beacons

### ISSUE THREAD

**Issue by x1p** [ViaVersion/ViaVersion#1280]
**Describe the bug, provide any errors**
When joining with 1.14 I've noticed several visual issues

**How can we reproduce it?**
1. Login with 1.14 client on a 1.13.2 server'
2. place stairs/slab/beacon
3. disconnect
4. join again

**Screenshots**
1.13.2 client on the left, 1.14 client on the right.
![Screenshot_20190424_163403](https://user-images.githubusercontent.com/28690790/56668130-4ede1d00-66af-11e9-8ff0-f6b73607b79c.png)

**ViaVersion Dump:**
https://dump.viaversion.com/66e0a01d5ec7bd38d0a0ab426eefdba0b2e9a95ac9c942d9aec433fb074925d1

**Additional server info**
BungeeCord-Bootstrap:1.14-SNAPSHOT:4cef6d1:1405
ViaVersion v 2.0.1 build 318

**Comment by MylesIsCool** [comment]
As suggested by someone on out discord, smooth lighting seems to be a workaround.

**Comment by ishland** [comment]
The same issue

**Comment by computerfreund03** [comment]
Same here

**Comment by Patbox** [comment]
![image](https://user-images.githubusercontent.com/39821509/59433173-4077cc00-8de9-11e9-91c4-7b72be5ea9c2.png)
The same

**Comment by computerfreund03** [comment]
So there is still no Fix?

Am Do., 13. Juni 2019 um 14:41 Uhr schrieb Patbox <notifications@github.com

**Comment by MylesIsCool** [comment]
If anyone is able to compile and test, Kenny has PR'd a fix :)

**Comment by x1p** [comment]
I think I managed to get that version compiled. It looks better, but not quite as real as 1.13.x
![Screenshot_20190730_005558](https://user-images.githubusercontent.com/28690790/62088233-f6498d80-b264-11e9-996c-623ada560bc9.png)

**Comment by KennyTV** [comment]
Can you pull and compile again? Should work now.

Also, it'd be great if you could test the following: place stairs/slabs/walls somewhere where skylight would theoretically be able to reach it, place a light source (torch, glowstone, etc.) near to it, set the time to midnight (+ relog if you just placed the light source) -> destroy the light source and see if there is block light even though the light source is destroyed

**Comment by x1p** [comment]
It all looks natural now.
Left = version 2.1.4 build 361, Right = your latest version
![Screenshot_20190730_172558](https://user-images.githubusercontent.com/28690790/62142834-4b31e600-b2ef-11e9-9e16-2a0d77f3f783.png)

**Comment by Kvosty** [comment]
Where i Can download 2.1.4 ?

**Comment by x1p** [comment]
I don't know If this is 100% correct, but the way I did it was:
git clone -b non-full-light https://github.com/KennyTV/ViaVersion.git
cd ViaVersion
mvn clean package install

**Comment by x1p** [comment]
This patch works fine only farmland is still dark
![Screenshot_20190829_214603](https://user-images.githubusercontent.com/28690790/63971537-fed0f600-caa6-11e9-814a-302e9490096f.png)

Hope this patch will be released some day

**Comment by KennyTV** [comment]
When exactly did you pull the pr last? On July 30th I added those to the fix.
And thanks for the feedback 😄

**Comment by x1p** [comment]
My pull was from 30th July 17:00 CEST.
I will try once more.
Looking forward to the day this gets merged.

**Comment by x1p** [comment]
Redid the test.
Existing farms are dark
New farms are light until the player leaves the server and rejoins. Then it's dark again.
![Screenshot_20190829_235022](https://user-images.githubusercontent.com/28690790/63978902-d3a2d280-cab7-11e9-916a-6f77de17ddf5.png)

**Comment by KennyTV** [comment]
Used a `<` instead of `<=`, so this one specific farmland block wasn't checked 🤔 - it's now fixed, thanks for reporting it
