### ISSUE TITLE
HolographicDisplays - Vehicle NullPointerException

### ISSUE THREAD

**Issue by DDuart** [ViaVersion/ViaVersion#1285]
**Describe the bug, provide any errors**
I have two server with the same plugins and configuration. The only difference is other world.
Everything works fine on first server but after join to second server i get instantly crash.
https://hastebin.com/lenohijazu.coffeescript

**ViaVersion Dump:**
lastest ViaVersion, ViaRewind, ViaBackwards

**Additional server info**
Waterfall

**Comment by MylesIsCool** [comment]
For us to debug this you're gonna have to send us the chunk file which causes the crash
