### ISSUE TITLE
Chunk loading crash

### ISSUE THREAD

**Issue by Getblock** [ViaVersion/ViaVersion#1286]
**Describe the bug, provide any errors**
https://pastebin.com/C0k3FUpi

**How can we reproduce it?**
1. Login on 1.14'
2. Load chunks
3. It will disconnect the client

**ViaVersion Dump:**
https://dump.viaversion.com/d366a5e71d37785fb43bccc62d5c791c32c5dbc4d045ffe441a38c0b2b8c81ac

EDIT: Updated bungee to latest version, the problem still occurs.

**Comment by Getblock** [comment]
it seems like OP players are the only ones having the error problem and all of my players are not encountering it... weird?

**Comment by Getblock** [comment]
It's happening to some players now...

**Comment by MylesIsCool** [comment]
Could you indicate which client versions this happens on? And also test latest build from ci.viaversion.com?

**Comment by Getblock** [comment]
issue persist: https://pastebin.com/urstUtu3 latest dev build.

**Comment by Getblock** [comment]
1.14 client version connecting to 1.13.2 server

**Comment by MylesIsCool** [comment]
Could you confirm whether this happens in the latest dev build? https://ci.viaversion.com/job/ViaVersion/

**Comment by Getblock** [comment]
Still happens on latest dev build or the one posted on spigot website (1.14.1)

**Comment by MylesIsCool** [comment]
You're gonna need to copy your server and test with no plugins / different map so we can isolate the issue.

**Comment by MylesIsCool** [comment]
I believe this is fixed in latest builds
