### ISSUE TITLE
Husks appearing as Guardians to 1.14 clients

### ISSUE THREAD

**Issue by aeonlamb** [ViaVersion/ViaVersion#1287]
**Describe the bug, provide any errors**
For some reason, Husks look like Guardians to clients using 1.14. Found this out while testing on a 1.13.2 server. They make guardian flopping noises when they move, but husk groaning noises as their idle noise. They are husks server-side, can be confirmed by switching back to 1.13.2 client, or just getting hit by them and seeing that they give you hunger.

**How can we reproduce it?**
1. Install Viaversion 2.0.1 on Paper 1.13.2 server
2. Join using 1.14
3. Spawn a husk using a spawn egg
4. Observe that it looks like a guardian

**Expected behaviour**
Husks should look like husks!

**Screenshots**
![2019-04-24_13 37 27](https://user-images.githubusercontent.com/20532513/56692212-8a202200-6696-11e9-90d7-0ecca7128870.png)

**ViaVersion Dump:**
https://dump.viaversion.com/34cf8fbed4bab392c3fbe70cf5e917957a0c2040c09aefe6373480ea8229b582

**Additional server info**
Tested this with Paper 1.13.2, build 624.

**Comment by MylesIsCool** [comment]
Fixed in latest dev
