### ISSUE TITLE
Visual: "Jumping" Fencegate on 1.14

### ISSUE THREAD

**Issue by Patbox** [ViaVersion/ViaVersion#1290]
[https://www.youtube.com/watch?v=e_tBwoH2z9Q&feature=youtu.be](https://www.youtube.com/watch?v=e_tBwoH2z9Q&feature=youtu.be)

**ViaVersion Dump:**
https://dump.viaversion.com/f0d26bbf40944d7e31399a04defaf4a1335a6caabbcf9d0a4d9bdc718ddd19f9

**Comment by MylesIsCool** [comment]
Could you confirm whether this is fixed in the latest build https://ci.viaversion.com/job/ViaVersion/ ?

**Comment by Patbox** [comment]
This bug is fixed (tested on 1.14.1)

**Comment by MylesIsCool** [comment]
Thanks :)
