### ISSUE TITLE
Villager gui title bug

### ISSUE THREAD

**Issue by successed** [ViaVersion/ViaVersion#1294]
i have 1.13 latest paper spigot and vivaversion plugin.

check this out: http://prntscr.com/ngzdss

this img is 1.14 version seeded.

**Comment by MylesIsCool** [comment]
Also happens with tool_smith

**Comment by BlackBeltPanda** [comment]
The mappings are wrong. Should be "entity.minecraft.villager.toolsmith" and "entity.minecraft.villager.weaponsmith"

**Comment by MylesIsCool** [comment]
Should be fixed in next dev
