### ISSUE TITLE
Unable to connect to the end with Waterfall

### ISSUE THREAD

**Issue by Mario359** [ViaVersion/ViaVersion#1298]
**Bugs**
With Waterfall by connecting to a server (lobby) and then to a server where I was in the Ender (/server survival), the game loads forever
No crash, no error, for the server I am correctly connected
To unlock, I use Multiverse-Core with the command /mv tp Mario359 world and the game finishes loading

**How can we reproduce it?**
1. Login with MC 1.13.2 or 1.14 to a Waterfall and Paper 1.13.2 servers with ViaVersion 2.0.1
2. Go to the end and disconnect
3. Reconnect, if the bug does not appear, go to another server with /server and then return to the old one

**Expected behaviour**
The game must be able to load the end

**Screenshot**
![image](https://user-images.githubusercontent.com/20285750/56832170-80034c80-686b-11e9-9b67-058d6d1506fc.png)
_Building terrain_

**ViaVersion Dump**
https://dump.viaversion.com/e6fe71976a9f14fc8b7dc2a41f3c15cf2fc8012e5f65490ed9cce2494912d8ca

**Additional server info**
Warerfall # 279 & Paper 1.13.2 # 614 on all servers
In Waterfall config.yml: disable_entity_metadata_rewrite: true

**Comment by MylesIsCool** [comment]
disable_entity_metadata_rewrite: false

Pretty sure it's a bug in Waterfall afaik
