### ISSUE TITLE
Server 1.8  Viaversion 1.8<x error in console

### ISSUE THREAD

**Issue by supermem99** [ViaVersion/ViaVersion#1299]
**Describe the bug, provide any errors**
I have a 1.8 Server with the lastest Version of Viaversion. When a user with 1.12 or 1.13 in example joins on my server, the console get errors. Here is the error
https://hastebin.com/ugaqejaqap.cs

**ViaVersion Dump:**
https://dump.viaversion.com/b1690afcec48f939732a376d1b61d49d7a4d465a9fc26696061a1904f0c64b03

**Additional server info**
I have a cloudnet server. Proxy

**Comment by MylesIsCool** [comment]
You have something interfering with ViaVersion, most of the time it's something like protocollib debug mode, you'll need to work out what's causing it.
