### ISSUE TITLE
[ViaVersion]: An error occurred with entity meta data for FALLING_BLOCK OldID: 31

### ISSUE THREAD

**Issue by kajahofman** [ViaVersion/ViaVersion#1300]
**Describe the bug, provide any errors**
https://hastebin.com/semilegoru.md

**How can we reproduce it?**
1. Login on 1.14'
2. Find a mob
3. The server is overloaded and players are being disconnected.

**Expected behaviour**
Nothing wrong will happen.

**Screenshots**
Not neccessary.

**ViaVersion Dump:**
https://dump.viaversion.com/7455020ab6c3ad42dc1cc07a2fb7143221184fe1001d72da18fc71e7c0d8a736

**Additional server info**
ViaVersion 2.0.2-SNAPSHOT on Waterfall latest.

**Comment by MylesIsCool** [comment]
You're using some plugin sending invalid plugin data. You can suppress these under suppress metadata in the config.

If your server crashes from this i'd suggest a new server.
