### ISSUE TITLE
Error on server start

### ISSUE THREAD

**Issue by Noiknez** [ViaVersion/ViaVersion#1301]
Hi, I launched the server and get an error message. The 1.14 don't work

Error show on the console : https://pastebin.com/ax5HHY2a

Full server log : https://pastebin.com/V04EkEpm

Server version : CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT) 

**ViaVersion Dump:**
- /viaversion dump --> Don't work

**Additional server info**

BungeeCoord version : 1408
BungeeCoord plugin : 
- BungeeAdminTools-1.4.3-basics.jar
- BungeeTabListPlus-2.8.10.jar
- SlashServer.jar
- Yamler-Bungee-2.4.0-SNAPSHOT.jar

**Comment by krusic22** [comment]
Update all your Via plugins.

**Comment by Noiknez** [comment]
It work thanks
