### ISSUE TITLE
Could not pass event ConnectionOpenEvent to ViaVersion v2.0.1

### ISSUE THREAD

**Issue by Noiknez** [ViaVersion/ViaVersion#1304]
Hi, when trying to change server on a bungee network (ex: /server lobby) there is an error :
https://pastebin.com/pWNfB3Mh

**ViaVersion Dump:**
- Type /viaversion dump --> Nothing happen when executing the command

**Additional server info**
BungeeCoord version : 1408
BungeeCoord plugin :

    BungeeAdminTools-1.4.3-basics.jar
    BungeeTabListPlus-2.8.10.jar
    SlashServer.jar
    Yamler-Bungee-2.4.0-SNAPSHOT.jar

**Comment by MylesIsCool** [comment]
Use Paper spigot or put via on bungee and manually set protocol number in the config for your PS servers
