### ISSUE TITLE
Resource pack change in 1.14

### ISSUE THREAD

**Issue by soshimee** [ViaVersion/ViaVersion#1306]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?
https://hastebin.com/oberaqamet.coffeescript
**How can we reproduce it?**
1. Login on 1.14'
2. Press 'ESCAPE'
3. Click on 'Options'
4. Click on 'Resource Packs'
5. Click on any resource pack
6. Press 'Done'

**Expected behaviour**
Only change resource pack.
**Screenshots**

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/fd7a0a7ec4d0c9c87bfa3cbad4aa55ff8bb844387e6d9b3cfa3b0e832473903e
**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
Spigot, No proxy.

**Comment by MylesIsCool** [comment]
We're unable to replicate this, can you provide further info? Texture pack? Video instructions?

**Comment by MylesIsCool** [comment]
See above

**Comment by soshimee** [comment]
No, I can't provide further info, but I will try sending video instructions.
Video: https://mega.nz/#!wp0hWCwa!yKdIBnUkVem4TfnUE5ZYSToygT923a8_VjU2kLIyHIs

**Comment by kyhet0739** [comment]
i have same happens
