### ISSUE TITLE
1.14 on 1.8.8 Disconnect

### ISSUE THREAD

**Issue by Fluxty** [ViaVersion/ViaVersion#1308]
**Describe the bug, provide any errors**
**With ViaVersion + ProtocolLib**
User Fluxty has disconnected, reason: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.

**Without ProtocolLib**
User Fluxty has disconnected, reason: Internal Exception: io.netty.handler.codec.DecoderException: The received string length is longer than maximum allowed (21 > 20)

**How can we reproduce it?**
1. Login to TacoSpigot 1.8.8 server on 1.14

**ViaVersion Dump:**
- https://dump.viaversion.com/f9b1a0a5166017c34496aafa2ea846448369f6704192f2f09d9c88ae88ad3327

**Additional server info**
_Using latest version of Travertine._
Maybe it's our lobby build on this server? I remember a similar issue when a 1.8.8 server had 1.9+ blocks present, newer versions would crash. I'm sure the builders of our lobby accidentally had some 1.13 blocks in the schematic.

**Comment by MylesIsCool** [comment]
This is one of those issues where it's a pain to find the cause, it'll be one of the following:

- Scoreboard data
- Something in the world like a Sign
- A plugin

So the best way is to copy the server with no other plugins and see if it happens then work from there, but it's something sending a string that's too long.

**Comment by Fluxty** [comment]
I'll dig in

**Comment by Fluxty** [comment]
Turns out it was at the Bungee level from one of our own plugins that does a ton of wonky stuff via plugin messaging. The plugin was outdated, untidy, and we can just remove it off our network without issue. Everything is working fine after isolating and removing that bungee plugin :)
