### ISSUE TITLE
Invalid plugin identifiers aren't cancelled before server send Join Game packet - PS|KeepAlive

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaVersion#1326]
The protocol pipeline is only changed when Join Game is received https://github.com/SpigotMC/BungeeCord/blob/1b34a16c097d23bb89b5cdd5f7a6d52ff37e3798/proxy/src/main/java/net/md_5/bungee/ServerConnector.java#L179
When an invalid identifier is received from 1.12 server while the pipeline is 1.13.2, ViaVersion doesn't cancel the packet

**Comment by creeper123123321** [comment]
https://cdn.discordapp.com/attachments/316206679014244363/576480411362787359/unknown.png kick suspect to be caused by this issue

**Comment by MylesIsCool** [comment]
I'm going to close this issue, I've reviewed a few possible solutions and to negate the issue at hand they seem not worth it (considering the breakage they could cause in the future).

One solution is a custom packet handler on the Bungee pipeline to rewrite these packets - There's no BungeeCord proxy artifact so it's gonna be ugly to build.

Another is just rewriting the channel name by overriding - https://github.com/SpigotMC/BungeeCord/blob/af10f82d14ef4f052b5179cff2bd94603ddb8cb1/protocol/src/main/java/net/md_5/bungee/protocol/packet/PluginMessage.java#L26

But really, ProtocolSupport 1.12.2 shouldn't be used as it's an old version and ViaBackwards still works on that version. The issue only occurs in old PS versions (older than 1.13), so the best solution, if you have this issue, is just to use ViaBackwards/ViaRewind instead and delete ProtocolSupport.
