### ISSUE TITLE
Can't use chair function on 1.12.2 server.

### ISSUE THREAD

**Issue by smartmadio** [ViaVersion/ViaVersion#1327]
I've used a plugin that could use stairs as chairs and players could sit on it.

When I updated to viaversion 2.0.1,players could no more sit on stairs.

Seems something wrong,need help.

Server version:Spigot 1.12.2

Viaversion version: 2.0.1

**Comment by MylesIsCool** [comment]
Please fill in the bug report completely https://github.com/ViaVersion/ViaVersion/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

A video / screenshots + the dump is pretty vital for this kind of bug report.

**Comment by MylesIsCool** [comment]
See above
