### ISSUE TITLE
glass pane bug

### ISSUE THREAD

**Issue by computerfreund03** [ViaVersion/ViaVersion#1328]
I already seen, that this was reported in 2016, but it still happens. Is there a way to fix this? 

The Server is 1.8.8, it happens on 1.14. It is using Bungee.

![2019-05-11_22 23 47](https://user-images.githubusercontent.com/41758175/57574586-fc855600-743b-11e9-8c03-dae1a07bc0d9.png)

**Comment by MylesIsCool** [comment]
Enable serverside-blockconnections in the config
