### ISSUE TITLE
1.14.1 on 1.13.2 server_resourcepack disconnecting

### ISSUE THREAD

**Issue by Rosstail** [ViaVersion/ViaVersion#1334]
**Describe the bug, provide any errors**
Use the server resourcepack of the server make the user disconnect with a local error.
https://pastebin.com/08RjqU2M
https://pastebin.com/E6ipFKb1

**How can we reproduce it?**
1. Login on 1.14.1
2. Download the server resourcepack
3. disconnect
4. Login again
5. Still use the downloaded server resourcepack
6. Move some distance.
7. You may be disconnected with an error message, and a loadscreen (to unload the server)

**Expected behaviour**
This bug just make the player disconnected, but no player want to be disconnected, hm ? ^^

**ViaVersion Dump:**
https://dump.viaversion.com/77f9c2f234cb9281bc5f0f3e828c2f31880b4408f4feae2e4c3b8c71be35ecba

**Additional server info**
Spigot 1.13.2 Latest build
No error on starting/server side
Server doesn't crash when the problem has occured
It just say the player as an internal error: 
`> [20:11:35 INFO]: Rosstail lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.`

**Comment by MylesIsCool** [comment]
Can you enable debug=true in server.properties and post the full exception

**Comment by Rosstail** [comment]
Yes, I've set it to true and here is the full log. I update the first post too.

[https://pastebin.com/E6ipFKb1](server log)

**Comment by MylesIsCool** [comment]
Can you test without su.nightexpress.quantumrpg.libs.packetlistener?

**Comment by Rosstail** [comment]
Of course, I have removed QuantumRPG from my server for this test, and restarted him (you can see the plugin list)

https://pastebin.com/CX7sNtni

**Comment by MylesIsCool** [comment]
Are you able to copy your server and test with no other plugins? Trying to work out what causes this

**Comment by Rosstail** [comment]
Ok, I gonna test it on local server.

Log with Viaversion only:
[](https://pastebin.com/J2v8rENq)

Log with viaversion + Resourcepackdownloader + protocollib (RPD dependencies)
[](https://pastebin.com/HThWmcVu)

It seems to be one of my plugins.

**Comment by MylesIsCool** [comment]
Going to close as it's most likely another plugin doing something strange, if it's something we can fix let us know. But usually, it's something sending strange data.
