### ISSUE TITLE
Holographic Displays crash

### ISSUE THREAD

**Issue by DDuart** [ViaVersion/ViaVersion#1338]
**Describe the bug, provide any errors**
Player on version 1.14/1.14.1 can't join to server 1.12.2. Instantly get crash.
I tried to remove the plugins one by one and i found it. It's caused by Holographic Displays.
After delete Holographic Displays players doesn't get crash and they can play normally.

https://hastebin.com/atilikovov.coffeescript

**Additional server info**
Waterfall

**Comment by krusic22** [comment]
Would you mind posting the Holographic Displays database.yml, as I cannot recreate the crash myself.
Also please include /viaver dump

**Comment by DDuart** [comment]
It's caused by Holographic Display's api. I'm using for this Skript addon (Skellett)
```
create holo object "test;test" with id "test" at player
```
https://github.com/TheLimeGlass/Skellett-Legacy/search?p=1&q=holo&unscoped_q=holo
