### ISSUE TITLE
Implement bStats with a custom graph

### ISSUE THREAD

**Issue by Sprax2013** [ViaVersion/ViaVersion#1343]
**Describe the solution you'd like**
I'd like to see _ViaVersions_ using _bStats_, as suggested in #658 (and #659) about 2 years ago. Additionally, it would great to see a custom graph showing the used client versions.

As @MiniDigger said, it can easily be disabled for the whole server, so most administrators using plugins from SpigotMC should already know about it and disabled it if they don't like _bStats_.

I think a graph showing the used client versions vs. the used server versions from _bStats'_ global stats would not only be great for developers but for everyone that is interested in the versions that are used (YouTube, server administrators, developers).

In the past few years, _bStats_ has been implemented in a lot of huge and great plugins, so it is mostly known to administrators. Plus it is anonymous.
I don't mind doing a PR (I think the one in #659 is outdated?) but only if you would like to implement it.

**Which versions is this for?**
Any upcoming release. It is version independent

**Comment by Tsoccerguy3** [comment]
> **Describe the solution you'd like**
> I'd like to see _ViaVersions_ using _bStats_, as suggested in #658 (and #659) about 2 years ago. Additionally, it would great to see a custom graph showing the used client versions.
> 
> As @MiniDigger said, it can easily be disabled for the whole server, so most administrators using plugins from SpigotMC should already know about it and disabled it if they don't like _bStats_.
> 
> I think a graph showing the used client versions vs. the used server versions from _bStats'_ global stats would not only be great for developers but for everyone that is interested in the versions that are used (YouTube, server administrators, developers).
> 
> In the past few years, _bStats_ has been implemented in a lot of huge and great plugins, so it is mostly known to administrators. Plus it is anonymous.
> I don't mind doing a PR (I think the one in #659 is outdated?) but only if you would like to implement it.
> 
> **Which versions is this for?**
> Any upcoming release. It is version independent
Reading through the privacy policy , as you know privacy policy , is not privacy law and not binding in most countries. The broad scope of your data collection is in fact to be considered contrary to the laws in most countries . This is why we custom compile our servers plugins and server jar. 
I'm saying a big No , to installing this tracking software .

**Comment by Sprax2013** [comment]
> Reading through the privacy policy , as you know privacy policy , is not privacy law and not binding in most countries. The broad scope of your data collection is in fact to be considered contrary to the laws in most countries . This is why we custom compile our servers plugins and server jar.
> I'm saying a big No , to installing this tracking software .

Sorry but I don't understand what you are trying to say...

Looking at the privacy policy at https://bstats.org/privacy-policy I can't see anything that could be against law or worrying in any way. They collect only basic stuff about the server like some settings and the version. The IP too but for rate limiting, as they state. To be fair, a plugin author can send some custom data too.
plus it can easily be disabled in a configuration file.

**Comment by Tsoccerguy3** [comment]
There would need to be a way for the player to have access to delete personally identifiable information including IP address . There is also the possibility that the player is under 18 years old and can not legally consent . No one wants this liability and no contract will protect the host or server owner  . This is why we remove any grey area code and custom compile everything .

**Comment by KennyTV** [comment]
There would certainly not be a privacy issue...
Though my unqualified opinion is that it would neither get us (all versions have to be supported anyway) nor users (the data is **very** different for any given server and pretty much useless if conducting it for specific cases) any world changing input.
The global stats (https://bstats.org/global/bukkit) are probably just as, if not more informative for that matter.
A nice thing to have for sure, but not really worth it... imo

**Comment by Sprax2013** [comment]
> access to delete personally identifiable information including IP address

You can always contact bStats to delete them but there should not be any data a player can delete because it is from the server. The IP you mention is the one making the requests. Idc if bStats stores the IP of my server that everyone is using to join.


> pretty much useless

Thanks to your post I just realized that you would have to collect users centrally before telling bStats how many users are using version X or Y because multiple servers can have the same player... So that graph is not possible as far as I know.


> A nice thing to have for sure

Yeah, ... I would have loved to have a graph documenting the used version by players on a global scale instead of my server with a few players.

Since the graph is not possible the devs are mostly the only ones having an interest in seeing how many server/players are using ViaVersion and which version of the plugin they are running on.

Maybe a custom graph to represent how many players are using ViaVersion feature.
Example:
Spigot 1.8.8 Server - 10 players online
8 players are using 1.13.2 and 2 are using 1.8.9
So the graph would show (live) that 80% are using a different version that the server supports

**Comment by Tsoccerguy3** [comment]
here is an example of the kind of abuse possible , https://minecraft-statistic.net/en/
data scraped from bStats . We found out years ago that sites like this existed . bStats may have beneficial uses , but most of the time abuse is inevitable .  The authors of the plugin will make up their own minds , if we find anything we consider grey code we strip it out.

**Comment by MiniDigger** [comment]
How exactly is bstats abuseable?

**Comment by DoNotSpamPls** [comment]
> There would need to be a way for the player to have access to delete personally identifiable information including IP address 

This is pure bullshit, as no information about the players itself (other than their total count) is sent to bStats, let alone PII about them.

> There is also the possibility that the player is under 18 years old and can not legally consent

Again, there is no need to consent, as all information that is identifiable is coming from the server itself and has no relation to the players, so only the server owner has to agree to send information to bStats

> here is an example of the kind of abuse possible , https://minecraft-statistic.net/en/

There is no proof to show that website gets its information from bStats (that would be impossible with scraping anyway, as bStats does not show server IPs to end users). It's more likely that they scrape from bigger server lists like Minecraft-MP, PMC or

**Comment by md678685** [comment]
@Sprax2013 On the actual topic:
> Thanks to your post I just realized that you would have to collect users centrally before telling bStats how many users are using version X or Y because multiple servers can have the same player... So that graph is not possible as far as I know.

You could have a chart split by version showing numbers of servers where the version has been used at least once. That way you don't need to worry about counting users twice across different servers.

**Comment by Bastian** [comment]
bStats does not collect any data that is considered personal data by the EU's  GDPR (which is probably one of the strictest privacy laws).

About https://minecraft-statistic.net/en/:
This site does not use data from bStats.
I don't know the page, bit looking at it, it seems like
- At first someone has to add the server manually (https://minecraft-statistic.net/en/add_server.html)
- Afterwards it queries the information directly from the server (there's a setting in the server config to prevent queries. However some data should still be available as the Minecraft client also has to query it for the server list). 

If you are using a popular Minecraft server host, it is likely that the server is in this list, even if you just bought the server, because the IP belonged to another server before. Server IPs are no secret data and are reused by hosters (everything else would be insane).

**Comment by drtshock** [comment]
No dog in this fight but the argument that Bstats is sending PII is just not true.

As a server owner that uses ViaVersion, I 100% support this being implemented and would leave it enabled.

**Comment by Sprax2013** [comment]
@Bastian from the bStats-repo answered to my issue I opened today and I made a mistake in thinking that bStats would not delete/update when a player or server shuts down. Applying my false thoughts on the 'Players online' graph the numbers would be rising continuously, but that's not the case!

>     It will significantly increase the load of the bStats server
>     I don't think that it is worth implementing it. In the overall data it should not matter if a player gets counted twice occasionally. Players are usually not on multiple servers at the same time. As it can also happen that a player does not get counted at all (because the servers only report the player count at a given time), the error gets even less as the average is still correct.
> 
> A Drilldown Pie chart (like the Operating System one) should fit perfectly for this use-case.

It would be possible just to send the versions and because a player is mostly only online on one server at a time, the graph would represent more or less the live player count on a given version.

**Comment by MylesIsCool** [comment]
I'm going to close this PR, I'm not currently looking into adding this to ViaVersion. If the project was still early stages I'd consider it. But otherwise, I'd rather not add it as for a lot of servers ViaVersion is the only plugin which many for security reasons wouldn't consider metrics.
