### ISSUE TITLE
Bug with protocolsupport

### ISSUE THREAD

**Issue by Mariodn775** [ViaVersion/ViaVersion#1347]
I have a small server and i want to use version from 1.8 to 1.14 on my 1.13.2 server. So, i installed ViaVersion and protocolsupport, but if i start the server with spigot, the versions up to 1.13.2 don't work, if i start the server with craftbukkit, protocolsupport crash and the server close. Please help.
P.S. sorry for my bad english.

**Comment by MylesIsCool** [comment]
ViaVersion only works with PS on paper
