### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by Xayanix** [ViaVersion/ViaVersion#1350]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?

**How can we reproduce it?**
1. Create 1.8.8 server
2. Install ViaVersion
3. Look at fence or glass pane etc. (you have to be on newer version, like 1.14)
4. Done

**Expected behaviour**
-

**Screenshots**
https://i.imgur.com/rVmHebJ.png

**ViaVersion Dump:**
https://dump.viaversion.com/6e1f68efb2e4f4d06c52f77a4bcce2d470c73f42d2254410f5b0aee9b8c3d6eb

**Additional server info**
Using BungeeCord

**Comment by MylesIsCool** [comment]
Enable blockconnections in the ViaVersion config.

**Comment by Xayanix** [comment]
https://hastebin.com/mepeqiqeze.py

This happened after turning it on.

**Comment by MylesIsCool** [comment]
enable debug=true in server.properties and post full error
