### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by AlexNova1555** [ViaVersion/ViaVersion#1353]
**Describe the bug, provide any errors**
https://pastebin.com/VP0Uf6x2

**How can we reproduce it?**
start the server and it just showing the error

**ViaVersion Dump:**
https://dump.viaversion.com/e8133359ddc53abd8bf1bebf694104523c79ff0461ad9c5779a21af1b7285efa

**Additional server info**
 This server is running CraftBukkit version git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT

**Comment by MylesIsCool** [comment]
Don't use -DEV builds of VB or ignore the error as they're incomplete
