### ISSUE TITLE
Exception whilst joining

### ISSUE THREAD

**Issue by Artuto** [ViaVersion/ViaVersion#1357]
**Describe the bug, provide any errors**
https://hastebin.com/obojecixet.php

**How can we reproduce it?**
1. Login in 1.13 [?

**Expected behaviour**
Allow the login.

**ViaVersion Dump:**
https://dump.viaversion.com/ed98f884572d38a35d7f863ceebf314ae6cca8159755c4faba1fc985dc83b9f4

**Additional server info**
Waterfall fork that adds PE support.

**Comment by MylesIsCool** [comment]
Does it happen without PE support?

**Comment by Artuto** [comment]
Yes

**Comment by MylesIsCool** [comment]
So you can provide a dump + error from normal waterfall?

**Comment by Artuto** [comment]
Can not repro consistently (sometimes it happens, sometimes it doesnt). Cant also use server software without PE support because that would disrupt service for PE players.

**Comment by MylesIsCool** [comment]
It's fixable our end but it doesn't make sense. The error is because your server is telling ViaVersion the wrong kind of NBT tag (ByteTag). Where it should just be a compound tag which causes it to read incorrectly.

**Comment by Artuto** [comment]
The PE changes do not modify Java packets or whatever.

**Comment by MylesIsCool** [comment]
What is the real version of your servers?

**Comment by Artuto** [comment]
1.13.2 Paper

**Comment by MylesIsCool** [comment]
Can you specify what servers it happens on? If all etc?

Also according to your dump

--> 

"bungee-servers": {
            "default": 404,
            "creative": 340,
            "auth": 340
        },

Are these protocol versions correct?

**Comment by Artuto** [comment]
It happens on a Towny 1.13 server (default). Yes they're correct.

**Comment by Plysm** [comment]
I am also experiencing the same issue as @Artuto. I am running a1.13.2 Paper with the problem occurring on all of my servers minus my server running waterfall.

**Comment by MylesIsCool** [comment]
@Plysm can you provide versions, as well as /ViaVersion dump then? And also the exception with debug=true in server.properties

**Comment by Artuto** [comment]
According to the user, they were trying to join in 1.14 to a 1.13.2 server.

**Comment by Artuto** [comment]
I moved Via to all the paper servers and the issue never happened again.

**Comment by MylesIsCool** [comment]
This sounds like some weird edgecase, I'm going to close the issue but if you / anyone has it in the future with public builds we'll happily investigate.
