### ISSUE TITLE
I played on version 1.14.1 disconnect

### ISSUE THREAD

**Issue by rts7771** [ViaVersion/ViaVersion#1358]
Describe the bug, provide any errors
https://pastebin.com/ppcAzrgw

How can we reproduce it?

Login in 1.14.1
Expected behaviour
Allow the login.

ViaVersion Dump:
https://dump.viaversion.com/53295846a3cf3708acfda7df1dda86f3b5f850c6a00b8058ab270330a00564e3

Additional server info
Bungeecord, plugins (ProtocolLib.jar, ChangeSkin.jar, ServerListPlus-3.4.8-Universal.jar)

**Comment by MylesIsCool** [comment]
Fill in the issue template: https://github.com/ViaVersion/ViaVersion/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by rts7771** [comment]
> Заполните шаблон выпуска: https://github.com/ViaVersion/ViaVersion/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Made look above

**Comment by MylesIsCool** [comment]
Fixed in latest dev build from ci.viaversion.com
