### ISSUE TITLE
Kicked on joining

### ISSUE THREAD

**Issue by TapGGat** [ViaVersion/ViaVersion#1360]
As soon as anyone on my server joins it kicks us.

1. Login on 1.14-1.14.2'
2. Kicked

I get kicked and get and error message

**Screenshots**

**ViaVersion Dump:**
https://dump.viaversion.com/b32af598807b4eceafc73679574a0a77b1544cc1276222894f52d389fc2ed692

I use Bungeecord and Spigot\

"03.06 20:20:47 [Disconnect] User TapGG has disconnected, reason: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
03.06 20:20:47 [Server] INFO {Type: MetaData List, Source #0: us.myles.ViaVersion.protocols.protocol1_14_1to1_14.packets.EntityPackets$3 (Anonymous), Data: [Pair{Type|VarInt, 284}], Packet ID: 67}
03.06 20:20:47 [Server] INFO Actual Error: "

**Comment by TapGGat** [comment]
http://prntscr.com/nx8ueo

**Comment by MylesIsCool** [comment]
Can you enable debug=true in server.properties and repost the error?

**Comment by RedAlphard** [comment]
Hello,
I debugged but there are sensitive data like IP and UUID which is better not to make public how can I send them to you? I tried to send you in Private Chat on SpigotMC.org

**Comment by MylesIsCool** [comment]
For debug, I just need debug=true in server.properties (not ViaVersion dump), Spigot PM is fine but we're just looking for the expanded error. :)

**Comment by RedAlphard** [comment]
I debugged as you requested and sent you logs on SpigotMC PM

**Comment by MylesIsCool** [comment]
Debug based on Spigot leads me to the conclusion it's down to another plugin.
