### ISSUE TITLE
disconnect.spam

### ISSUE THREAD

**Issue by NNorbertPL** [ViaVersion/ViaVersion#1362]
1. Login on 1.14.2 (spigot ver. 1.8.8)
2. start typing on chat and pressing "tab" button
3. You will be kicked for "disconnect.spam"

When writing on chat and tabbing players are sometimes thrown out with the reason "disconnect.spam"

**Comment by krusic22** [comment]
Taken from Discord:
If it's for spam then you can (choose one):
1. Disable tab complete for 1.13.x and up users in the ViaVersion config disable-1_13-auto-complete: true,
2. Update ViaVersion (pinned) and delay the tab complete (5 is suggested) in the ViaVersion config 1_13-tab-complete-delay: 5,
3. If you are using Paper 1.12.2 or higher, you can change the spam limits in the paper.yml config.

**Comment by NNorbertPL** [comment]
thanks, working :)
