### ISSUE TITLE
Player gets disconnected on join

### ISSUE THREAD

**Issue by Montimedici** [ViaVersion/ViaVersion#1364]
**Describe the bug, provide any errors**
https://hastebin.com/xabojozuku.rb

**How can we reproduce it?**
1. Login with 1.13

**Expected behaviour**
The player just tried to join and got disconnected. I guess this shouldn't happen ;^)

**Screenshots**
Got no screenshots of the screen or smth. Only the stacktrace (hastebin above)

**ViaVersion Dump:**
https://dump.viaversion.com/3fa7bb1a6c8f5d5c384f92fb680493dec63c95655e33b47722b8ff827dfb5395

**Additional server info**
I use 2 proxies and they are connected with my own jedis plugin. Both proxies got viaversion installed and some plugins which are coded by myself.

**Comment by MylesIsCool** [comment]
Does this happen on every server or specific servers?

**Comment by Montimedici** [comment]
Only on the proxies.

**Comment by MylesIsCool** [comment]
So you have ViaVersion installed on proxy and backend?

**Comment by Montimedici** [comment]
Only on the Proxies - has it to be on both? (spigot and proxy)

**Comment by MylesIsCool** [comment]
So can you test without the proxy? It's one or the other. I asked what servers it happens on through the proxy.

**Comment by Montimedici** [comment]
What do u mean without the proxy? 
The stacktrace gets printed into the proxy-console/log.
On the spigot-server I cant see any errors or smth

**Comment by krusic22** [comment]
Could you test running ViaVersion on backend servers instead of the proxy?

**Comment by Montimedici** [comment]
So I should remove viaversion from my proxies and just run it on the spigot servers?

**Comment by krusic22** [comment]
Yes.

**Comment by Gerrygames** [comment]
Can you test #1367?
