### ISSUE TITLE
Explosions desync the client (1.14.2 client on 1.13.2 server)

### ISSUE THREAD

**Issue by Brokkonaut** [ViaVersion/ViaVersion#1365]
**Describe the bug, provide any errors**
When there is an explosion (for example creepers or tnt) that destroys blocks, the client often will see some blocks as destroyed that are not destroyed. When trying to move into these blocks the client will be bugging.

**How can we reproduce it?**
1. Use 1.14.2 for the client, 1.13.2 for the server
2. Use a creeper to destroy some blocks
3. Try to jump around in the hole created by the creeper to see the desync (if you are bugging in an invisible block and click there you will often see the block reappear on the client)
4. If it did not work repeat at step 2

**Expected behaviour**
You see exactly those blocks destroyed that got destroyed by the explosion.

**ViaVersion Dump:**
https://dump.viaversion.com/2c1b064362b9fd3d58a96af4945e44620b5e440ad0a218e90acbdfc4afec768e

**Additional server info**
- BungeeCord
- Paper git-Paper-624

**Comment by MylesIsCool** [comment]
Can you provide a video?

**Comment by Brokkonaut** [comment]
https://www.youtube.com/watch?v=MhtdYy5cDzc&feature=youtu.be

**Comment by JHarris12345** [comment]
I have this exact issue on my server and it is becoming increasingly annoying on factions. This needs to be fixed ASAP

**Comment by Benedani** [comment]
Also happens on my server, I reported it in the #support channel, they blamed other plugins for it. Someone came saying they tested it without other plugins, but that response was ignored. 
Anyway, in my testing this happens to literally any explosion, so creepers, ghasts, TNT, etc.

**Comment by MylesIsCool** [comment]
> Also happens on my server, I reported it in the #support channel, they blamed other plugins for it. Someone came saying they tested it without other plugins, but that response was ignored.
> Anyway, in my testing this happens to literally any explosion, so creepers, ghasts, TNT, etc.
> 
> Quick edit: maybe it could be possible to just intercept the explosion packet and instead of an explosion, it sends the server's results? Might use more data but better than forcing users to either rejoin or right click everywhere.
> Also, it would reduce lag on the client side. I'm not sure why the client even has its own explosion calculation when the server already does the same, it seems like it was done on purpose to lag people out when they try to lag the server.

As far as I'm aware nobody blamed plugins.

Unfortunately, there isn't infinite time in the world, so these issues can take time to fix. After a discussion with Kenny, we're unable to replicate the issue. So if anyone can either post on discord or a file website a minimal server configuration that causes it, it would be appreciated so we can solve this one.

It might be worth also trying optimize-explosions off in paper.yml to see if that changes anything if it's enabled (would also like to know if you have this on or off).

**Comment by Benedani** [comment]
I've tested it, turning off optimize-explosions doesn't seem to affect the issue.

**Comment by JHarris12345** [comment]
I have a dev server where I have tested with 0 plugins at all. The set up is the latest viaversion (with no viabackwards or viarewind) and no other plugins installed at all. I am running paper spigot 1.13.2. But the issue definitely exists without any plugins installed and no changes to default paper spigot, spigot and bukkit config.

**Comment by MylesIsCool** [comment]
> You must join in the 1.14.3 client, blow up blocks with creepers or tnt and just run around in the explosion crater.

Unable to replicate, again we're gonna need a zip of the server.

**Comment by JHarris12345** [comment]
Is there a place I can send you the zip

**Comment by MylesIsCool** [comment]
> Is there a place I can send you the zip

You're welcome to use a provider like mediafire.com and post a link here.

Spigot Private Message also works, or share me a link (myles[at]myles.us)

**Comment by Benedani** [comment]
Tried it with just ViaVersion, looks like there's some other plugin interfering, because explosions aren't broken.

**Comment by JHarris12345** [comment]
Then we need to get to the bottom of the plugin thats causing it. I am assuming it is worldguard or essentials. Try it with them

**Comment by Benedani** [comment]
I've packed literally the following plugins into the server:
CoreProtect, EssentialsX, Matrix (anticheat), ProtocolLib, Vault, ViaVersion, WorldEdit, WorldGuard

Explosions still work correctly. The rest of the plugins I've got literally shouldn't mess with explosions, but I'll continue adding more and more plugins until the issue appears.

**Comment by JHarris12345** [comment]
I will have to do my own testing as well and start deleting the config files to see if it is the default config of any plugins that have been messed with

**Comment by Benedani** [comment]
Alright, I've started to have my doubts with ViaVersion being related to this issue at all. So I've tested a 1.13.2 client. However, explosions work correctly on the public server (with all the plugins).
The journey continues...

**Comment by JHarris12345** [comment]
I will get to the bottom of it today dont worry. We will sort this out

**Comment by Benedani** [comment]
Ok, so I haven't managed to find the plugin that causes the issue.

Also, just a note: apparently, if optimize-explosions is turned off, there's a small delay after the explosion and then the crater slightly changes.

**Comment by JHarris12345** [comment]
Ok I cant lie to you, I have regenerated the entire server and JUST put in the latest essentials and via version and the issue stands. I am not sure what you are doing differently to not get these issues. If you join in a 1.13 client, its fine. It's only when you join in a 1.14 client its bugged. I will have to send a zip file of my server and you can see for yourself. All the files are default, we are running paper spigot 1.13.2

**Comment by JHarris12345** [comment]
Here is the file to my dev server. That server is small, no other plugins and the issue is on it. Join in 1.14 client https://www.mediafire.com/file/j2k7nphg3hidlp7/Dev+Server.zip

**Comment by Gerrygames** [comment]
Can someone test https://github.com/ViaVersion/ViaVersion/pull/1419?
