### ISSUE TITLE
Emit Achievements event

### ISSUE THREAD

**Issue by detobel36** [ViaVersion/ViaVersion#1368]
**Is your feature request related to a problem? Please describe.**
Achievement event (spigot) is not all the time call. `PlayerAchievementAwardedEvent`

**Describe the solution you'd like**
Emit the `PlayerAchievementAwardedEvent` for every player version

**Describe alternatives you've considered**
Try to do it my self... :stuck_out_tongue: 

**Which versions is this for?**
Server on 1.10 (and thus player version on 1.11, 1.12, 1.13 and 1.14)

**Comment by MylesIsCool** [comment]
This isn't related to Via.

**Comment by detobel36** [comment]
Isn't viaversion that ignore packet of achivement ?
Like here:
https://github.com/ViaVersion/ViaVersion/blob/master/common/src/main/java/us/myles/ViaVersion/protocols/protocol1_12to1_11_1/TranslateRewriter.java

**Comment by MylesIsCool** [comment]
> Isn't viaversion that ignore packet of achivement ?
> Like here:
> https://github.com/ViaVersion/ViaVersion/blob/master/common/src/main/java/us/myles/ViaVersion/protocols/protocol1_12to1_11_1/TranslateRewriter.java#L12

That doesn't change events, nor anything else apart from translations.

**Comment by detobel36** [comment]
Ho... Ok my bad   
So I will try to understand why bukkit event isn't called for the higher versions.

Thanks for your reply
