### ISSUE TITLE
Infested blocks are unbreakable.

### ISSUE THREAD

**Issue by Aurelien30000** [ViaVersion/ViaVersion#1370]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?
When I want to break a monster_egg block with a pickaxe, it doesn't work, the action is "cancelled".

**How can we reproduce it?**
1. Login with 1.13.x or 1.14.x version on a 1.12.2 server (perhaps 1.8.8-1.12.2, I don't really know)'
2. Take a pickaxe (iron, diamond)
3. Try to break a monster_egg block (which spawns silverfish)

**Expected behaviour**
The block should be broken.

**Screenshots**

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/d4a7c1b503e0019f8268b46a13f41fdb5a7786afb6b0f31a906c9cce2966c22f

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
Paper 1.12.2-b1615

Thanks in advance for your answer :)

Aurélien

**Comment by MylesIsCool** [comment]
Fixed in latest dev

**Comment by Aurelien30000** [comment]
Thanks :)
