### ISSUE TITLE
TAB Reborn and ViaVersion problem 1.8.8

### ISSUE THREAD

**Issue by Fundryi** [ViaVersion/ViaVersion#1372]
**Describe the bug, provide any errors**
https://hastebin.com/arugudekax.shell
Happens when you join with the Plugin [TAB](https://www.spigotmc.org/resources/tab-1-8-x-1-14-2-reborn.57806/)

**How can we reproduce it?**
1. Login on 1.8.9 to the server
2. Look at the console.

Plugins Used:
Look at ViaVersion Dump*

**Expected behaviour**
No error xD

**Screenshots**
not needed

**ViaVersion Dump:**
https://dump.viaversion.com/4c0a7bf7260bb0a5f9b6d70b47c5cf5a852f04f9d715bb8f3d4f80c5081c5c20

**Additional server info**
HexaCore ( Bungeecord )
PaperSpigot ( Spigot )

**Comment by MylesIsCool** [comment]
This is a ProtocolSupport issue, but older versions of PS aren't supported.

I'd suggest ViaRewind / Backwards instead.

**Comment by Fundryi** [comment]
Your right removing ProtocolSupport-1.8 Fixed it!
