### ISSUE TITLE
Issue with spigot 1.13.2

### ISSUE THREAD

**Issue by MrLava13** [ViaVersion/ViaVersion#1373]
**Describe the bug, provide any errors**
When joining, I get the message: https://hastebin.com/sitizuvuke.pl

**How can we reproduce it?**
1. Login on 1.14.2
2. Join the server that is running 1.13.2 and has ViaVersion 2.1.1 installed

**Expected behaviour**
The server allows me to join.

**Screenshots**
![error](https://user-images.githubusercontent.com/24940520/59782966-561f4280-927c-11e9-9ef8-fe92882be64f.PNG)

**ViaVersion Dump:**
https://dump.viaversion.com/89a5a8847b90101884478495e4110b5c0a602c6045178135f314f62d46d1ce56

**Additional server info**
I use WorldEdit, LiteBansGUI, UltraPermissions, ProtocolSupport, ViaVersion, ProtocolLib, LiteBans.
The version of the server is 1.13.2 and ViaVersion is 2.1.1
I also use BungeeCord.

**Comment by MylesIsCool** [comment]
ProtocolSupport only works with ViaVersion on 1.13.2 with Paper.
