### ISSUE TITLE
Load but not working in Glowstone Server

### ISSUE THREAD

**Issue by MalexTP** [ViaVersion/ViaVersion#1374]
ViaVersion loads in Glowstone version 2018.9.0.e83d836 (MC: 1.12.2) but when I try to enter to server with 1.13>, it kicks me and sents me the Outdated server message.
Log (Console Spam):
https://pastebin.com/ipJS6ysX

**Comment by MylesIsCool** [comment]
There is no current support for glowstone, unless there is demand it's unlikely for us to implement it.

You can workaround this if you use either BungeeCord or Velocity and install ViaVersion to the proxy.
