### ISSUE TITLE
Players unable to join on any version, Error thrown

### ISSUE THREAD

**Issue by darkbro100** [ViaVersion/ViaVersion#1376]
**Describe the bug, provide any errors**
Whenever a player logs onto our 1.8.8 server with a version (1.8, 1.13, and 1.14 tested) an error is thrown in console and the player is unable to join the server.

Full error:
https://pastebin.com/K9Gbhutn

**How can we reproduce it?**
1. Login on any version

**Expected behaviour**
Every single time a player logs in on any version (no player has been able to join regardless so I assume this is happening across all versions), consistent everytime, although I do believe a different error is produced depending on which version players connect with

**Screenshots**
https://smplive.net/media/73608c8.png
https://smplive.net/media/8522226.png

**ViaVersion Dump:**
https://dump.viaversion.com/1db3125345e26ef692c6ee5ce553a2161596b6484d4704f90cbab69a753ed3c8

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
Do use a fork of spigot, but it does pull the latest upstream, and nothing network related has been touched in the fork, also running bungeecord as well (git:BungeeCord-Bootstrap:1.14-SNAPSHOT:8eb5683:1414)

**Comment by darkbro100** [comment]
It is worth noting that this error does not happen on a normal spigot 1.8 build, however we weren't getting this error before updating to 2.1.2 and 2.1.1 on our custom fork

**Comment by MylesIsCool** [comment]
Could you confirm which build you were running before the issue occured?

**Comment by darkbro100** [comment]
After some more testing, issue seems to be protocollib. Removing viaversion still produces the same result, but it's weird because the only thing that was updated was literally viaversion. /shrug oh well
