### ISSUE TITLE
Timeout on most recent version of VV

### ISSUE THREAD

**Issue by MayusYT** [ViaVersion/ViaVersion#1377]
**Describe the bug, provide any errors**
Any player on 1.14.2 who joins my 1.8.8 server is experiencing a time out after a couple of seconds.

**How can we reproduce it?**
1. Login on 1.14.**2** to the server that is 1.8.8
2. Wait a couple of seconds
3. Time Out

**Expected behaviour**
No time out

**Screenshots**
Screenshot of the server log:
![](https://i.imgur.com/ZZjHyMd.png)

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/2df5f98529aa8afe820ffe7b8b6a0de3b9e2b2a2cadb0b861608f7101762c0e9

**Additional server info**
I use the latest BungeeCord.

**Comment by MylesIsCool** [comment]
Unless you can provide a minimalistic server that can replicate this, I suspect this is probably down to your network.

**Comment by MayusYT** [comment]
I'll try to setup one.

**Comment by MylesIsCool** [comment]
Hi, was there any update on this?

**Comment by MayusYT** [comment]
Hi, it works now. Sorry that I didn't inform you earlier.
