### ISSUE TITLE
Can't open inventory for 1.14 player!

### ISSUE THREAD

**Issue by cloakfox** [ViaVersion/ViaVersion#1378]
**Describe the bug, provide any errors**
Basicly users can sometimes not connect to the server when on 1.14.3 version.

A huge error get's printed in the proxy console
https://pastebin.com/5hvE7WuK

**How can we reproduce it?**
Doesn't 100% happen all the time when joining I'd say it happens 1/3 times

**Expected behaviour**
I expect nothing as it's a free product <3

**Screenshots**
Check attached file for mc client disconnect screen

**ViaVersion Dump:**
Viaversion: 2.1.2
https://dump.viaversion.com/524a64b5089a878ffc0de1e3afd81c797586f893e614d836ca480a5021b56c57

**Additional server info**
Running on Waterfall build 284 with disable_entity_metadata_rewrite: false
![Knipsel](https://user-images.githubusercontent.com/3696645/60036427-81a49180-96af-11e9-8e25-570bfa98b33a.PNG)

**Comment by MylesIsCool** [comment]
As handled via Discord, down to another plugin on bungee most likely :)
