### ISSUE TITLE
Hologram Problem

### ISSUE THREAD

**Issue by THGamer2002** [ViaVersion/ViaVersion#1380]
**Describe the bug, provide any errors**
Holograms in 1.8 are lower than those in 1.12.2. with hologram-patch: true and HolographicDisplays last version

**How can we reproduce it?**
1. Login on 1.12.2
2. Make an hologram on spigot 1.8 with viaversion/holographicdisplays with 1.12.2 client
3. Disconnect from the server and join with 1.8 client
4. Login on 1.8
5. Check the hologram,  are lower than those in 1.12.2

**Screenshots**
1.8 https://imgur.com/a/gS4gDEK -> 1.12 https://imgur.com/a/AIxzqYZ

**ViaVersion Dump:**
https://dump.viaversion.com/66440059c9ae58842d3f43b4b150c83dbe620f2f57e8ff87e827a969a25cfcf9

**Additional server info**
I use TacoSpigot 1.8 but that bug works and for paperspigot

**Comment by MylesIsCool** [comment]
Have you tried changing the offset in the config?

**Comment by THGamer2002** [comment]
No, but how much do I have to put to the same height on both versions?

**Comment by MylesIsCool** [comment]
It would be a case of trying different heights

**Comment by THGamer2002** [comment]
I've changed many times, the same thing....

**Comment by THGamer2002** [comment]
Nothing changes

**Comment by MylesIsCool** [comment]
I can't replicate this - https://imgur.com/yDpl2xy

I'm going to close this issue as it's obvious that you need support faster than what we can give you (https://imgur.com/Y1Tzyem). If anyone in the future has this issue and can provide a minimal build to replicate, we'll happily investigate in a new issue.
