### ISSUE TITLE
Unsupported Protocol Version 

### ISSUE THREAD

**Issue by FeroxDrood** [ViaVersion/ViaVersion#1383]
### **Describe the bug, provide any errors**
When I attempt to join my 1.13.2 server on my Bungee network it does not allow me to join and gives me the error as seen in the screenshots below.

This is the only line that appears in the console of the bungee when attempting to join the 1.13.2 server.
_09:31:04 [WARNING] [Drood] <-> ServerConnector [survival2] - bad packet ID, are mods in use!? Unsupported protocol version_

### **How can we reproduce it?**
Run the latest version of Bungee _(#1416)_ and the latest version of Via version on the Bungee _(2.1.2)_. Then run the latest build of 1.13.2 paper spigot on the server you are trying to join _(paper-636.jar)_ and attempt to join.

### **Expected Behavior**
It should just let me join the server.

### **Screenshots**
Chat Error that appears in the lobby when you try to join 1.13.2 server.
https://i.imgur.com/hIBB4uk.jpg
Bungee Plugins
https://i.imgur.com/OyYq6ti.jpg
1.13.2 Plugins
https://i.imgur.com/YYqqZgS.jpg

### **ViaVersion Dump:**
https://dump.viaversion.com/3649a54887ee02e91521e8a8f60c87b27581a97487de6f1239e58040aa05aa00

### **Additional server info**
I've check my bungee conf, for ip-forwarding, checking that the ip's match, checked my spigot,yml for bungee enabled and check my properties for offlinemode off.
If you require and aditional information please let me know.

Sorry if this has nothing to do with ViaVersion I just though it might seen as though it handles server versions.

**Comment by MylesIsCool** [comment]
You aren't running latest Bungee. Your dump says the build and it's not 1416.
