### ISSUE TITLE
Failed to get an item to create a window click packet

### ISSUE THREAD

**Issue by M0dii** [ViaVersion/ViaVersion#1384]
**Describe the bug, provide any errors**
https://0bin.net/paste/fizn+E9-9Wq2fmxd#sSzmIXei887qJwl52jFsAD5pSwwLTEDaliMV7ven9K9
0bin since can't paste in on hastebin for some reason.

**ViaVersion Dump:**
https://dump.viaversion.com/f7d091bc602137f5488d2da79c88f89e09b4de05e93329621aed5602f6ab53e9

**Comment by MylesIsCool** [comment]
Are you able to specify what you're doing to cause it?

**Comment by M0dii** [comment]
I've seen this in logs, but not exactly sure what's the cause of it. Players are using some commands and I've many commands with GUIs. The issue seems to be gone right now, but there may be another issue, not with ViaVersion.
