### ISSUE TITLE
Sneaking player lists are a bit wrong

### ISSUE THREAD

**Issue by Benedani** [ViaVersion/ViaVersion#1386]
Previously, a bug regarding suffocation has been "fixed". Quote "fixed", because damage is still received if you release the sneak key, but you're still sneaking (because there is not enough space to stand up). It seems that `playerToggleSneak` is called even if the client doesn't immediately unsneak the player.

**Steps to reproduce the behavior**
1. Login on 1.14 to a <=1.13 server with the 1.14 sneak fix enabled.
2. Place an upper slab one block above the ground.
3. Sneak under it.
4. As you're under the slab, release the sneak button. You should still receive suffocation damage.

**Expected behavior**
The player should be unable to "toggle" suffocation damage by pressing and releasing the sneak key.

**Video**
[I can still receive damage by releasing the sneak button.](https://dl.dropboxusercontent.com/s/t1cnv0kni1goyzd/broke.mp4)

[**ViaVersion dump**](https://dump.viaversion.com/3e98750126bcd0b98184fa5f111e1606073ec37480ce688e6f1a7481c82dbf0e)

**Additional server info**
The 1.13 server is running on Paper. There aren't any other plugins installed that should interfere with suffocation damage (Matrix anticheat simply detects and undoes weird movement, and the "phase" check has already been disabled).

**Comment by KennyTV** [comment]
In that specific case, the server thinks you're no longer sneaking + your head is in a solid block, so I don't think a fix for that is possible

**Comment by Benedani** [comment]
I've been thinking, and I think collision checking with slabs and repeatedly checking until the player exits would be the way to fix it. Kind of complicated, but yeah, something has to be done to fully allow 1.14 clients on 1.13 servers. I might try something out later today.

**Comment by FormallyMyles** [comment]
I'm going to close this, we're welcome to Pull Requests but I wouldn't count this as a high priority feature because it's hard to implement new features perfectly.
