### ISSUE TITLE
issue on server join

### ISSUE THREAD

**Issue by LizzyTheOne** [ViaVersion/ViaVersion#1387]
WHen a player joins my 1,14 server, they instantly get kicked with this error message showing up.

https://cdn.discordapp.com/attachments/593609938404900864/595397739760582656/image0.jpg

**Comment by MylesIsCool** [comment]
Please fill out the issue template fully - https://github.com/ViaVersion/ViaVersion/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

As we're unable to help you otherwise.

**Comment by MylesIsCool** [comment]
See above, then we'll reopen
