### ISSUE TITLE
The server you were on previously went down...

### ISSUE THREAD

**Issue by FeroxDrood** [ViaVersion/ViaVersion#1389]
### **Describe the bug, provide any errors**
Players just get randomly kicked, this error appears in the bungee console... https://pastebin.com/vRuj9faU

### **How can we reproduce it?**
Latest version of Via Version, latest bungee build, latest 1.13.2 paper spigot build

### **Expected behavior**
Players should not get kicked.

### **Screenshots**
N/A

### **ViaVersion Dump:**
https://dump.viaversion.com/3ef8031f7242d4867805c1625efb7998b90cf7d5a36f9eef9d530407ff53baa4

### **Additional server info**
N/A if you need anymore information let me know but this is very hard to replicate as from what i've found so far it is completely random.

**Comment by MylesIsCool** [comment]
Can you try with no bungee plugins?

**Comment by FeroxDrood** [comment]
> Can you try with no bungee plugins?

Will try now, it might not be related to via version as players are reporting it only happens when they type /home which is essentials but I will give it a try, also looking at latest essentials github issues to see if anyone has reported it there.

**Comment by FeroxDrood** [comment]
> Can you try with no bungee plugins?

The kicks are still persisting. I've found out its whenever people teleport via a warp, /back or /home etc.

**Comment by MylesIsCool** [comment]
I suspect this is some how down to some plugin conflict (maybe bad data).

I'm going to close this issue otherwise, though if there's anything we need to do let us know.

**Comment by dextonanderson** [comment]
I am occasionally getting this as well. I have to use ViaVersion both on bungeecord and the spigot server.

**Comment by FeroxDrood** [comment]
> I am occasionally getting this as well. I have to use ViaVersion both on bungeecord and the spigot server.
> 
> bungee: https://dump.viaversion.com/8a467b9c15694a1e5e1ebde48c981d96822414cc60c271feb3a7646c69694c3c
> 
> spigot: https://dump.viaversion.com/8f36261e72e500d0a9c234e9310705aad748c707b82c8520b90404dc5c878066

Does having via version on your spigot servers aswell fix this issue for you?

**Comment by dextonanderson** [comment]
@FeroxDrood It does not, thats the setup I use and it happens

**Comment by KennyTV** [comment]
@dextonanderson you should use Via only on either Bungee or Spigot, not both

**Comment by dextonanderson** [comment]
@KennyTV I need to be able to use ping passthrough and domain forwarding in Bungee

**Comment by Logics4** [comment]
In that case you should use ViaVersion in BungeeCord only.

**Comment by dextonanderson** [comment]
I removed ViaVersion from Bungee and only have it on Spigot, same issue occurs.
