### ISSUE TITLE
Unable to inject ViaVersion

### ISSUE THREAD

**Issue by variananora** [ViaVersion/ViaVersion#1391]
**Describe the bug, provide any errors**
Unable to inject ViaVersion
Error Logs: https://pastebin.com/XC2bsBmb

**How can we reproduce it?**
1. Install Waterfall 287
2. Install ViaVersion 2.1.2
3. The error shows up

**Expected behaviour**
All the player that aren't using native version of the server can't join in.

**ViaVersion Dump:**
- https://dump.viaversion.com/c762e770d543a86416dab93f8d05433000ae25af792985bb1810f77706b9affb

**Additional server info**
Waterfall 287
ViaVersion 2.1.2
BTLP
NuVotifier
SkinsRestorer
StaffChats
EasyBackup

**Comment by MylesIsCool** [comment]
Can you test with no other bungee plugins (copy your server)?

**Comment by variananora** [comment]
I tried, and it still spits the error.
It has been fixed tho, by reverting from Java 12 to Java 11.
Sorry for the trouble.
