### ISSUE TITLE
Falling Through Blocks

### ISSUE THREAD

**Issue by EazyFTW** [ViaVersion/ViaVersion#1395]
**Describe the bug, provide any errors**
I have a Skyblock plugin that sets blocks, and when it resets an island, for some reason, players in 1.14.x (for sure in 1.14.3) get teleported through the blocks, and they cannot see the blocks.

The server is 1.13.2, and if you're in 1.13, it works fine. Setting the island's blocks uses NMS according to the plugin author.
If you go into gmc, and try to middle click the blocks, they're not there, but you can see them.
This happens when you make another island and it affects the other players.
If you're in survival, you go through the blocks.

**How can we reproduce it?**
1. Get the skyblock plugin SuperiorSkyblock2 (Paid)
2. The server has to be 1.13.2 (I use PaperSpigot)
3. Join in 1.14.x. (Happens for sure in 1.14.3)
4. Try making/removing an island with someone else on a different island.

**Expected behaviour**
You don't fall through the floor.

**ViaVersion Dump:**
Bungee: https://dump.viaversion.com/c3f40a11a34476ce250ab2b0bd1329398d1783593620919a24bc064ef7506914
Spigot: https://dump.viaversion.com/6cc3a4024f8e33129a83b43b95b043182783739683d953116e2b8f6f8b6dde8f

**Additional server info**
Using BOTH Bungee and Spigot.

**Comment by MylesIsCool** [comment]
Use ViaVersion on only bungee OR spigot

**Comment by EazyFTW** [comment]
> Use ViaVersion on only bungee OR spigot

I put it on both because if you only put it on spigot, fences don't work properly, and on the 1.13.2 server, corals are dandelions if you're in 1.14. I have removed it from bungee and installed ViaVersion on every server. I will get back to you if it has fixed it, I need some players to test it.

**Comment by EazyFTW** [comment]
> Use ViaVersion on only bungee OR spigot

Looks like it still happens.

**Comment by MylesIsCool** [comment]
I'd probably suspect that there is something weird going on when the author sets the blocks. I don't really get why they're using NMS instead of Bukkit. I don't own the plugin so I can't really test that one, unless you can replicate with an alternative plugin I don't think we can solve this. 

If you can provide alternative plugin etc or show that a normal skyblock world or worldedit can cause it I'll happily investigate.

**Comment by EazyFTW** [comment]
They use NMS or use FAWE (depending if it's installed or not). It happens on both so I don't think it has anything to do with NMS.
