### ISSUE TITLE
1.14 Chest Bug

### ISSUE THREAD

**Issue by SkylixMC** [ViaVersion/ViaVersion#1396]
**Describe the bug, provide any errors**
There is a feature in Minecraft where if 3 chests are placed in a row, it combines to become one large chest. This  feature is sometimes used by servers and plugin makers (such as my own) to create extra large chests. However on version 1.14, instead of opening this extra large chest, a beacon GUI is opened.

**How can we reproduce it?**
1. Setup a via version server with on spigot 1.12.2 (not sure about other versions)
1. Log on on 1.14.x.
2. /setblock x y z chest on any 3 blocks in a row.
3. Open the middle chest.
4. You will see the opening the middle chest will open a beacon GUI.

**Expected behaviour**

**Screenshots**
I have included two videos of my replicating this bug. On the first video, I am seen setting up a triple chest on version 1.12. As you will see in the first video, the triple chest works. However, in the second video, the same triple chest is opened. But instead of opening a triple chest GUI, a beacon GUI is opened.

https://youtu.be/lQBdMi-sKw4
https://youtu.be/JZPDask3USU

**ViaVersion Dump:**
https://dump.viaversion.com/2c3675fe40161a3a1fc6fa78dce151484a9dd188027ecd1f8ea82f4a91176d74

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
The server was a waterfall server running only viaversion and viabackwards.

**Comment by MylesIsCool** [comment]
Extra large chests do not exist in newer versions, so it's not possible to solve.
