### ISSUE TITLE
Bug - [ViaVersion] Pair{PLAY, -1} already registered!

### ISSUE THREAD

**Issue by giuliotoplad** [ViaVersion/ViaVersion#1397]
Minecraft Server: Paper 1.12.2

ViaVersion: ViaVersion-2.1.3-SNAPSHOT #356 (28-june-2019 21.03.09)

Bug: https://paste.ubuntu.com/p/RssKjCppyV/

Server Log: https://paste.ubuntu.com/p/wT2p7xSmDP/

Every time I start my Server this strange Warning appears.

In addition to annoying every start I don't know if you can refer to a serious Bug or not, however it's very annoying to see it every start.

**Comment by MylesIsCool** [comment]
Not a ViaVersion bug, ViaBackwards is still in development
