### ISSUE TITLE
1.8 server problem

### ISSUE THREAD

**Issue by Heron4gf** [ViaVersion/ViaVersion#1398]
I'm using viaversion on bungeecord server, i have got this 1.8 server (others are 1.12 and i use protocolsupport) that works perfectly as can i see from console, but when i try to join server with 1.12.2 it do not let me giving me Connection reset by peer, and i get from console viaversion error that says to report here

**Comment by MylesIsCool** [comment]
You need to fill out the issue template fully

https://github.com/ViaVersion/ViaVersion/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Otherwise for this kind of issue I'd suggest using discord if you're able to. It's most likely you can use builds of ViaRewind / ViaBackwards instead.
