### ISSUE TITLE
Move animation not working

### ISSUE THREAD

**Issue by Xayanix** [ViaVersion/ViaVersion#1406]
Server version: 1.12.2
Client version: 1.14.4
Viaversion version: 2.1.3

Reproduce:
1. join 1.12.2 server with 1.14.4 version
2. look at player movement

Video:
https://youtu.be/HkrAwlTR8EI

**Comment by MylesIsCool** [comment]
Please fill in the issue template fully - https://github.com/ViaVersion/ViaVersion/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Xayanix** [comment]
dump: https://dump.viaversion.com/e14a2d222f86014c3e221ae47ac530493d267f2e6b310b853b00d392530ca322

BungeeCord: yes

**Comment by MylesIsCool** [comment]
Are you able to test with a simpler setup eg. No bungee and see if it occurs? As this isn't seen on other servers

**Comment by Grabsky** [comment]
Can confirm, using BungeeCord aswell.

**Comment by Puremin0rez** [comment]
I'm having this same issue - it applies to mobs as well. They will slide around and not animate properly.

I am NOT using BungeeCord.

Server is Paper 1.12.2, Client is Vanilla 1.14.4.

**Comment by Grabsky** [comment]
Uh, I forgot to add that It exists also on 1.13.2 server version. It seems to be broken only for 1.14.X players as I'm using 1.13.2 and everyting looks fine.

**Comment by Puremin0rez** [comment]
Confirmed Fixed. Thank you :)
