### ISSUE TITLE
ViaVersion 1.14 broke - can't log into server on 1.14.1+

### ISSUE THREAD

**Issue by xShqdow** [ViaVersion/ViaVersion#1407]
Interal Exception us.myles.ViaVersion.exception.InformativeException 
{Type: MetaData List, Source #0: us.myles.ViaVersion,protocols.protocol1_14_1to1_14.packets.EntityPackets$3

**Comment by MylesIsCool** [comment]
https://github.com/ViaVersion/ViaVersion/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Please fill out the template fully.

**Comment by MylesIsCool** [comment]
See above
