### ISSUE TITLE
Error with ProtocolSupport API.

### ISSUE THREAD

**Issue by GrantisJ** [ViaVersion/ViaVersion#1409]
**Describe the bug, provide any errors**
I'm running my minecraft spigot server on 1.12. I've installed ProtocolSupport for spigot server 1.12. I've also installed latest(2.1.3) ViaVersion version. And when I'm trying to enter with minecraft's latest version(1.14.4) I can't even connect to my server. Here is the error that I get while the server is starting `24.07 09:22:41 [Server] INFO [ViaVersion] Loading ViaVersion v2.1.3
24.07 09:22:41 [Server] WARN us.myles.viaversion.libs.javassist.NotFoundException: protocolsupport.api.Connection$PacketListener
24.07 09:22:41 [Server] WARN at us.myles.viaversion.libs.javassist.ClassPool.get(ClassPool.java:452)
24.07 09:22:41 [Server] WARN at us.myles.ViaVersion.bukkit.classgenerator.ClassGenerator.makePSConnectListener(ClassGenerator.java:184)
24.07 09:22:41 [Server] WARN at us.myles.ViaVersion.bukkit.classgenerator.ClassGenerator.generate(ClassGenerator.java:51)
24.07 09:22:41 [Server] WARN at us.myles.ViaVersion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:88)
24.07 09:22:41 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:303)
24.07 09:22:41 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205)
24.07 09:22:41 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
24.07 09:22:41 [Server] WARN at java.lang.Thread.run(Thread.java:748)
24.07 09:22:41 [Server] INFO [ViaVersion] ViaVersion 2.1.3 is now loaded, injecting!`

**How can we reproduce it?**
1. Install ProtocolSupport for spigot 1.12
2. Install ViaVersion 2.1.3
3. Start the server
4. And that's it!

**Expected behaviour**

**Screenshots**
Some screenshots:
![image](https://user-images.githubusercontent.com/46791072/61797605-605ece80-ae30-11e9-85d3-ab6129a155e9.png)
![image](https://user-images.githubusercontent.com/46791072/61797630-710f4480-ae30-11e9-8acc-d05f4743888b.png)

**ViaVersion Dump:**
url: https://dump.viaversion.com/a611c4c727988b84b9c60b3fd3489d934dd01fa9a7c0bd5da3433f8e576ca70e

I hope that you can help me with this issue. Thank you.

**Comment by MylesIsCool** [comment]
As discussed on discord.
