### ISSUE TITLE
[1.13.2] Lots of java.lang.IllegalArgumentException: java.lang.ClassCastException errors

### ISSUE THREAD

**Issue by RalphORama** [ViaVersion/ViaVersion#1410]
**Describe the bug, provide any errors**

https://hastebin.com/ulogulehez.shell

I keep getting hundreds of `io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: java.lang.ClassCastException` errors, the only lead I have on them is `at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.exceptionCaught` in the stack trace.

**How can we reproduce it?**

1. PaperMC build \#639 server
2. Have players play on the server
3. Error appears

**Expected behaviour**

No errors in console.

**Screenshots**

I've included a hastebin link above.

**ViaVersion Dump:**

- https://dump.viaversion.com/bdb8f8a2557fa3fc2309fc41e360b453c4c97b53baf7e719576d6f2891c40f8b

**Additional server info**

Plugins can be found in viaversion.  I recently disabled ProtocolSupport (1.13.2 build from Jenkins) for causing performance issues as well.

**Comment by MylesIsCool** [comment]
Can you copy server and test with no other plugins?

**Comment by MylesIsCool** [comment]
See above
