### ISSUE TITLE
[1.8] Invisibility Potion Effect still shows Nametag.

### ISSUE THREAD

**Issue by ItzVinex** [ViaVersion/ViaVersion#1412]
What version of ViaVersion are you using? Type /ver viaversion
2.1.3

What version of Spigot are you using? Type /ver
PaperSpigot-1.13.2

What plugins are you using? Type /plugins
Custom plugins developed by myself and ViaVersion/ViaBackwards-DEV/ViaRewind

Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No Proxy/External Software

How does this error happen? login? Using an item?
Only occurs when the game starts with invisible players. Only occurs on 1.8 clients.

Screenshot:
https://gyazo.com/264e228871b00f640e9588f9e3a55f44

**Comment by MylesIsCool** [comment]
ViaVersion allows newer clients, so your bug report is probably for ViaRewind
