### ISSUE TITLE
ViaVersion & ViaBackwards & ViaRewind Lingering Potion Problem

### ISSUE THREAD

**Issue by MrDarkness462** [ViaVersion/ViaVersion#1413]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?
https://pastebin.com/3HdGkJDe

**How can we reproduce it?**
1. Join 1.8 (not sure if this is also on 1.9-1.10)
2. Get Lingering Potion
3. Throw it and I'm kicked (Here's the kick message: https://gyazo.com/8d811be97a22954db94838bb826b47dd)
4. Join again and you can't join because it's saying the same thing (the lingering potion is still there)

**Expected behaviour**
This shouldn't happen (if possible spawn some particles like on 1.11 +)

**Screenshots**
https://gyazo.com/8d811be97a22954db94838bb826b47dd

**ViaVersion Dump:**
https://dump.viaversion.com/6a78c4cd85d78a4fb5a81501748f374bd5d0f6a0575f2a52510fd2939b64d3aa

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
I'm not using BungeeCord, I use Latest Paper Spigot Build of 1.14.4
(Using all ViaVersion plugins from the jenkins, snapshots of it)

Plugins (13): CMI, CratesPlus*, Multiverse-Core, PlaceholderAPI*, PlugMan, ShopGUIPlus, Vault, ViaBackwards*, ViaRewind*, ViaRewind-Legacy-Support*, ViaVersion*, WorldEdit, WorldGuard

**Comment by MylesIsCool** [comment]
You should open this issue on ViaBackwards

**Comment by MrDarkness462** [comment]
The error said here so that's why posted here
