### ISSUE TITLE
1.14+ Feature Request: To add a hack/fix that prevent players on 1.14+ clients from taking suffocation damage when at 1 block high and crawling in older server versions

### ISSUE THREAD

**Issue by axemwa** [ViaVersion/ViaVersion#1416]
The title explains it all, just a feature request to remove suffocation damage when using a 1.14+ client in older server versions when crawling in 1 block spaces.

Also if possible to allow 1.14+ clients to be able to crouch under 1.5 block high blocks when joining older server versions cause atm something prevents the player from moving forward underneath the block

I understand if this is not possible but you don't know if you don't ask right?

**Comment by Benedani** [comment]
Can confirm this is an issue. However, for me, that seems to only happen when you toggle sneaking, and you keep taking damage until you exit the 1 block space.

**Comment by KennyTV** [comment]
There's already an option to have them sneak under blocks of 1.5 block height (`change-1_14-hitbox`), but I don't think it is possible to make players not suffocate while lying without just removing any suffocation damage

**Comment by axemwa** [comment]
> 
> 
> Can confirm this is an issue. However, for me, that seems to only happen when you toggle sneaking, and you keep taking damage until you exit the 1 block space.

It takes damage using the trapdoor trick to get in the 1 block space as well
> 
> 
> There's already an option to have them sneak under blocks of 1.5 block height (`change-1_14-hitbox`), but I don't think it is possible to make players not suffocate while crawling without just removing any suffocation damage
 Oh thanks I completely missed the hitbox option, as for suffocation damage @ 1 block high hmm your right it would be tricky to find a way around that

**Comment by axemwa** [comment]
Maybe changing the players hitbox size to the size of an endermite or silverfish when crawling might work?

**Comment by KennyTV** [comment]
Well, changing it isn't the problem, but knowing when they are crawling.

**Comment by axemwa** [comment]
True, I think I've found a way around it for now. If a half slab is above your head in the 1 block space you're crawling in, then you won't take suffocation damage

**Comment by KennyTV** [comment]
You can make tunnels with that or glass (or other non-solid blocks) to avoid damage, but else there is no way of knowing it a player is crawling to always prevent suffocation.

**Comment by axemwa** [comment]
Very true lol hopefully they can think of something, I just realized I can even fit in a 3/4 block gap using a trapdoor on the ground as well without taking suffocation damage

![image](https://user-images.githubusercontent.com/37608633/62042545-81af2880-b23d-11e9-9217-c39ea8044810.png)

**Comment by axemwa** [comment]
> 
> 
> You can make tunnels with that or glass (or other non-solid blocks) to avoid damage, but else there is no way of knowing it a player is crawling to always prevent suffocation.

Maybe if they add a listener?
Eg: If block exists 1 x, y or z space from each side of player (top, left, right, bottom) and is movable then to temporarily remove suffocation damage (or like i suggested before to change to a 1 block high entitys hitbox)

**Comment by KennyTV** [comment]
The 1.14 sneaking hitbox change was implemented because it made 1.14 clients experience setbacks in places where sub 1.14 players wouldnt. Supporting crawling without suffocation would essentially just be **adding** a 1.14 feature without any particular reason behind it

**Comment by MylesIsCool** [comment]
I'm going to close this as a won't solve, see what Kenny has said above for the reasoning :)

**Comment by axemwa** [comment]
> 
> 
> The 1.14 sneaking hitbox change was implemented because it made 1.14 clients experience setbacks in places where sub 1.14 players wouldnt. Supporting crawling without suffocation would essentially just be **adding** a 1.14 feature without any particular reason behind it

I could come up with many reasons as why it would be useful, particularly in parkour games, minigames etc but if it's more hassle than it's worth then don't worry about it


> 
> 
> I'm going to close this as a won't solve, see what Kenny has said above for the reasoning :)

There is a reason behind it but like I said if it's more trouble than it's worth dw I was thinking more for parkour events, minigames etc. But sounds like it's gonna be too hard for u anyway seeing as u have given up already so nvm

**Comment by KennyTV** [comment]
It's not about what is fun or useful, but whether if it is actually a fix for 1.14 clients on older servers - which it is not, but rather actually an advantage for those, which does not exist on the server on its own. Since Via's goal is on enabling client conversion - not creating features that don't actually exist in the server version's intent - it won't be added

**Comment by axemwa** [comment]
Fair enough but that's why I put it as a feature request rather than an issue or something that needed fixing

**Comment by HauserGrim** [comment]
""	public void onDamage(EntityDamageEvent e) {
		if (e.getEntity() instanceof Player && e.getCause() == DamageCause.SUFFOCATION) {
			Player p = (Player)e.getEntity();
			if(p.getLocation().getBlock().isPassable()) {
			e.setCancelled(true);
""
Maybe someone will come in handy
