### ISSUE TITLE
1.14.4 Client crash while editing book (1.13.2 server)

### ISSUE THREAD

**Issue by aeonlamb** [ViaVersion/ViaVersion#1417]
**Describe the bug, provide any errors**
While editing a book and quill, it's possible to create a book that crashes the client every time the client tries flipping to a certain page in the book.
In my testing I've found it to happen on the second page of a book quite a lot, although I'm not quite sure what text causes it. This only happens for clients using 1.14.4 (possibly other 1.14.x versions too), if a player is using the same version as the server (1.13.2 in this case) they don't crash while reading the book.

**How can we reproduce it?**
1. Join 1.13.2 server with 1.14.4 client (I was using optifine, but it affects vanilla clients too)
2. Pull out a book & quill, start typing random junk into the book
3. Make lots of line breaks, write text that goes just barely onto the next line
4. Click "done" on the book a lot so it saves your progress, then keep typing if you don't get a crash
5. Eventually there'll be some combination that makes you crash, I had it occur within ~3 minutes of just typing random junk into the book

**Expected behaviour**
No crash

**Screenshots**
![MinecraftLauncher_2019-07-30_14-28-34](https://user-images.githubusercontent.com/20532513/62166704-562c4c80-b2d6-11e9-9288-fe188f9ed33d.png)

**ViaVersion Dump:**
https://dump.viaversion.com/9de1a8f2e250ebefae6e25cfc6302d568a68362d2e274d3fe733b0cdb7aeb27d

**Additional server info**
Using Paper 1.13.2, build 641

**Comment by KennyTV** [comment]
See https://bugs.mojang.com/browse/MC-149792

**Comment by MylesIsCool** [comment]
See above :)
