### ISSUE TITLE
1.8-1.12.2 clients cannot connect to other servers

### ISSUE THREAD

**Issue by juancruzdal** [ViaVersion/ViaVersion#1418]
**Describe the bug, provide any errors**
the only clients that can connect to another server are 1.13.2-1.14, the previous versions cannot do it, if I want 1.8-1.12.2 clients to connect to other servers I must do it with bungeecord commands like /send or /server

**How can we reproduce it?**
1. Login on 1.8-1.12.2
2. Try to connect to other server with some command like /lobby or throught a gui
3. I can connect to other servers only with 1.13-1.14 versions 

**Expected behaviour**
Use 1.13.2-1.14

**ViaVersion Dump:**
- https://dump.viaversion.com/5ec052460dd43cff8e1772e386927880cf915a546dd37a1fc1f39e359697fa92

**Additional server info**
Waterfall version git:Waterfall-Bootstrap:1.14-SNAPSHOT:7e452f0:288 by md_5

**Comment by MylesIsCool** [comment]
ViaVersion allows newer versions not older.
