### ISSUE TITLE
1.14.4 Players getting instantly disconnected

### ISSUE THREAD

**Issue by AnonymousOG** [ViaVersion/ViaVersion#1420]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?
https://pastebin.com/Zip3hQnA
**How can we reproduce it?**
1. Login on 1.12'
3. The '....' is displayed wrong

Step 1, log onto 1.14.4
Step 2, log into a specific game mode (fine on my hub servers)
Step 3, you will get sent to the server, but instantly disconnected
Step 4, rejoin that same gamemode and it will work fine again.

**Expected behaviour**
I expected users to be able to just simply join the network on 1.14.4 and not have any sort of issues.
**Screenshots**
Whenever someone joins with 1.14.4 they instantly get kicked for "disconnected" As soon as they attempt to rejoin again it works fine. 
**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/dc32b67f50b7daa7ea41d5224723d86da45b381c682b717e11548e419f630450

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
I use bungeecord and I use the following plugins on my bungee.
BungeeList
BungeeMOTD
BungeeReload
BungeeReport
BungeeStaffChat
LiteAnnouncer
NuVotifier-universal
RandomHub
SlashServer
ViaVersion

**Comment by MylesIsCool** [comment]
You'll need to copy your bungee and test with no other bungee plugins.

**Comment by AnonymousOG** [comment]
> You'll need to copy your bungee and test with no other bungee plugins.

Okay I can attempt to do this, however, I don't have a spare place to stick the server

**Comment by AnonymousOG** [comment]
Fixed - update your bungeecord if you are having this issue!
