### ISSUE TITLE
Disconnection on 1.8.9

### ISSUE THREAD

**Issue by Elikill58** [ViaVersion/ViaVersion#1422]
Hello,

My server is on 1.8.9 and there was 2 players on my server : one on 1.8.9 and a second on 1.14.4.
```
Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: Integer, Source #0: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.packets.WorldPackets$9 (Anonymous), Data: [], Packet ID: 36}
```

This error appear when show "blockcrack_3_0" effect.
All player have been kicked.

**Comment by Xernium** [comment]
Please submit the proper issue form filled out entirely.

**Comment by MylesIsCool** [comment]
If it happens on both versions then it is probably another plugin, there's not enough into to do anything else.
