### ISSUE TITLE
Can't connect to 1.14 server with 1.14.4

### ISSUE THREAD

**Issue by iiNugget** [ViaVersion/ViaVersion#1423]
Whenever I try and join the server, I get this message "Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: MetaData List, Source #0: us.myles.ViaVersion.protocols.protocol1_14_1to1_14.packets.EntityPackets$3(Anonymous), Data: [Pair{TypeelVarInt, 5059}], Packet ID: 67}
Actual Error: "

1. Login to 1.14.4
2. Join a 1.14 server with ViaVersion
3. (Not sure, a creeper blew up a witch and a skeleton at the same time and it kicked me and now I have this message)

I expect to be able to join the server

We use clearlagg and I'm not sure about anything else

**Comment by MylesIsCool** [comment]
Can you test with no other plugins? (Copy your server)

**Comment by iiNugget** [comment]
nvm fixed it, I just joined the server on 1.14
