### ISSUE TITLE
viabackwards protocol EntityPackets$3 error

### ISSUE THREAD

**Issue by LoXR** [ViaVersion/ViaVersion#1425]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?
Error on my WaterFall server of an protocol exception.

**How can we reproduce it?**
Unsure how to re-produce the error, just shows up at times in my console when a player disconnects.

**Expected behaviour**
Not to occur?

**Screenshots**
N/A

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/f384edb06d04b3ae4b7109ea4a3724d184251c792d8436cdaeeb160b1f4dacc0
**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
Yes, latest WaterFall

**Comment by MylesIsCool** [comment]
This report doesn't provide any information on replication. I'd suggest trying without other plugins first otherwise posting the error when you have it.
