### ISSUE TITLE
Multiple Kick Issues

### ISSUE THREAD

**Issue by LoXR** [ViaVersion/ViaVersion#1427]
**Describe the bug, provide any errors**

1. Players being kicked for Dragon Particle on 1.13.2
2. Players being kicked for some unknown reason on 1.14.4
**How can we reproduce it?**

1.13.2
1. Join with 1.12
2. Go to the end
3. Fingers cross the dragon doesnt kick you for the particles

1.14.4
1. Join on any version
2. Throw trident
3. Disconnect

**Expected behaviour**

Hopefully everything is remapped to fix these issues.
**Screenshots**
Issues 1: https://pastebin.com/jS7LqGsF
Issue 2: https://pastebin.com/Vm64Rt84
**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/222b6540e54b9fa12042f40f2fe01ae9fed4b614ea1e5e01e22f6eb4c5877a61
**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
Will show all this in the dump ^

**Comment by MylesIsCool** [comment]
These are both ViaBackwards issues and should be reported on the GitHub.
