### ISSUE TITLE
Fatal Crash while using ProtocolSupport

### ISSUE THREAD

**Issue by Sukram28** [ViaVersion/ViaVersion#1428]
**System details**
- Papermc1.13.2-Lastes / Spigot1.13.2-Latest
- Viaversion 2.1.4-SNAPSHOT / Viaversion 2.1.3
- ProtocolSupport 1.13.2-Lastest

**Bug Describtion**
I tried to combined ViaVersion and ProtocolSupport on 1.13.2.
Everything seems to work for some days but then this error appears.
The Excption appears while pining the Server, joining, running, and so on..

**How can we reproduce it?**
I'm not really sure. Since this those crashes appeared randomly and now it seems not longer fixable.

**LOG**
[log.txt](https://github.com/ViaVersion/ViaVersion/files/3548940/log.txt)

**Expected behaviour**
Hopefully this is somehow fixable.

**ViaVersion Dump:**
https://dump.viaversion.com/809510656fb3885b28992f7da2ff20e33799e359acd06c93acfc55fe8560586c

Edit: ViaVersion Dump shows also 2 other plugins but this issue appears whithout them too. Even generating a new viaversion config does not fix this Problem :/

**Comment by MylesIsCool** [comment]
ViaVersion is only compatible with ProtocolSupport on paper.
