### ISSUE TITLE
Not showing avaible to join 1.9.4

### ISSUE THREAD

**Issue by Troldepus2005** [ViaVersion/ViaVersion#1429]
the bug is that it does not show i can join the server on 1.12 (its on 1.9.4)
![image](https://user-images.githubusercontent.com/54365043/63963043-66317a80-ca94-11e9-84ed-6e5ccc48d513.png)

**How can we reproduce it?**
1. make a server with these plugins: WorldEdit, Tabfixes, Questioner, WorldBorder, WorldGuard, Hibernate, PermissionsEx, KeepChunks, ConditionalCommands, mcMMO, ViaVersion, Vault, ChestShop, AreaShop, Essentials, CompatNoCheatPlus, Towny, Jobs, SilkSpawners, ProtocolLib, NoCheatPlus, BestViewDistance, TownyChat, MobStacker, EssentialsProtect, CustomShop, EssentialsChat, TownyNameUpdater, EssentialsSpawn, BuycraftX
2. start the server
3. Login on 1.12'
4. see it shows "Server Out Of Date" which is wrong

**Expected behaviour**
it shows out of date

**Screenshots**
![image](https://user-images.githubusercontent.com/54365043/63963043-66317a80-ca94-11e9-84ed-6e5ccc48d513.png)

**ViaVersion Dump:**
https://dump.viaversion.com/2a83c69355882475d253e9c7d8bb1a64f910bff76ae0bd98e58cd94accefac95

**Additional server info**
it is paper 1.9.4
30 plugins

**Comment by Xernium** [comment]
Did you restart the server or only reload it? Reloading it instead of restarting it will create this bug. I can also imagine Tabfixes causes this.

**Comment by Xernium** [comment]
Also Hibernate causes this when it's activated. Try it without please.

**Comment by Troldepus2005** [comment]
i reloaded the entire server (stopped and then started it)

**Comment by Troldepus2005** [comment]
and its not hibernate

**Comment by Xernium** [comment]
@Troldepus2005 Regardless. Please remove the plugins one by one till it stops happening. I am sorry but the dev team doesn't have the time to replicate your setup to test for the probability that there is an incompatibility. I would suggest removing ProtocolLib and the plugins that rely on it first.

**Comment by Xernium** [comment]
You could also try to see if the current development build of ViaVersion fixes it for you https://ci.viaversion.com/job/ViaVersion/

**Comment by MylesIsCool** [comment]
I'd suggest testing without other plugins to locate the issue, otherwise if it's something we can fix let us know.
