### ISSUE TITLE
[1.14.4] Decoder exception

### ISSUE THREAD

**Issue by Letter01** [ViaVersion/ViaVersion#1436]
Hello! I have 1 problem. I start using ViaVersion, ViaBackwards, ViaRewind and when I open my creative invetory it's kick me out. 
PrintSc: https://prnt.sc/p1uq6k

**Comment by Xernium** [comment]
Do you have ViaBackwards-dev? Is it the latest version? Are ViaRewind and ViaVersion the latest versions? What is your server version? Please next time fill the issue sheet properly, this way contributors won't have to ask questions, thanks.

**Comment by Letter01** [comment]
Yes, everything is latest.

**Comment by MylesIsCool** [comment]
There isn't enough info here to solve this - https://github.com/ViaVersion/ViaVersion/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

We'll reopen after this is filled in, if you're also able to copy and test with no plugins it would be useful.
