### ISSUE TITLE
1.13.2 Server Properly installed Via Version + Rewind (Rewind works fine)

### ISSUE THREAD

**Issue by TxSKywars** [ViaVersion/ViaVersion#1437]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?

**How can we reproduce it?**
1. Login on 1.14'
2. Outdated server I'm still on 1.13.2 Spigot
3. Server only displays as Spigot 1.13.2, but connects with as low as 1.7

**Expected behaviour**

**Screenshots**

**ViaVersion Dump:**
https://dump.viaversion.com/e552d77ce712300573eaaf2a8641cd1978536397d57ce7a319bd61fbfd818f52

**Additional server info**
ProtocolSupport

**Comment by MylesIsCool** [comment]
PS + Via only work with Papet
