### ISSUE TITLE
Elytra doesnt work on a version lower than 1.14

### ISSUE THREAD

**Issue by JHarris12345** [ViaVersion/ViaVersion#1442]
**Describe the bug, provide any errors**
On a 1.13.2 client, elytra flight doesnt work

**How can we reproduce it?**
1. Login on 1.13.2 or lower
2. Try and fly with elytra

**Expected behaviour**
You just fall

**ViaVersion Dump:**
https://dump.viaversion.com/97db7d2c07a44b02b079a3ad7aaa13159349844342be137cb3329315cbe88576

**Additional server info**
Latest 1.14.4 bungeecord

**Comment by MylesIsCool** [comment]
ViaVersion supports newer versions, your issue should be on ViaBackwards/Rewind.
