### ISSUE TITLE
Bug al poner bloque

### ISSUE THREAD

**Issue by RodrigocouV2** [ViaVersion/ViaVersion#1445]
Hola, el problema es que al poner bloques los jugadores se le bugea y sale un error en la consola, esto pasa al entrar con la version 1.14.4 o con la version origianal 1.8 en adelante,
Cuando pones bloques como si hicieras una torre hacia arriba te bugeas en dicho bloque por unos segundos y salta un error en la consola: 

Foto del error:

https://prnt.sc/p3v9gf

**Comment by MylesIsCool** [comment]
This is unrelated to ViaVersion

**Comment by RodrigocouV2** [comment]
> Esto no está relacionado con ViaVersion

Como sabes eso?

**Comment by RodrigocouV2** [comment]
Es decir empezo a ocurrir cuando puse el complemento

**Comment by MylesIsCool** [comment]
Sounds like an issue with PAC

**Comment by RodrigocouV2** [comment]
ALV, como sabes que tengo ese plugin xd, lo estoy sacando para probar si ahora va todo bien

**Comment by RodrigocouV2** [comment]
> Sounds like an issue with PAC

Amigo sos un genio, saque ese plugin y ahora va bien, gracias y perdona por culpar a tan buen plugin, que buen servicio contestaste al instante:D, crees que alla forma de tener los 2 plugins a la vez ?

**Comment by MylesIsCool** [comment]
I'd suggest showing the error to the creator of PAC and they should be able to catch it so it's ignored.
