### ISSUE TITLE
Explosion causes ghost blocks

### ISSUE THREAD

**Issue by JHarris12345** [ViaVersion/ViaVersion#1446]
**Describe the bug, provide any errors**
Any explosion will cause ghost blocks

**How can we reproduce it?**
1. Login on to ANY version
2. Blow stuff up and walk around, you will get caught in ghost blocks

**Expected behaviour**
There shouldnt be glitches

**Screenshots**

**ViaVersion Dump:**
- https://dump.viaversion.com/8a8403360852243c5f16e624dbede3036e088e6bc33ecb804e93563629088aae

**Additional server info**
Bungeecord 1.14.4, paperspigot 1.13.2, LATEST viaversion (2.1.4 snapshop)

**Comment by MylesIsCool** [comment]
See the dump, this isn't 2.1.4
