### ISSUE TITLE
It won't let me in...

### ISSUE THREAD

**Issue by NienteNessuno** [ViaVersion/ViaVersion#1453]
![image](https://user-images.githubusercontent.com/55293728/64883003-a11fda80-d65e-11e9-8d9e-6634f262302d.png)

**Comment by MylesIsCool** [comment]
We can't help you if you don't tell us enough

https://github.com/ViaVersion/ViaVersion/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by NienteNessuno** [comment]
I killed all anti ties and somehow it worked

**Comment by NienteNessuno** [comment]
I remember that there was a creeper with speed 5 and as it exploded it kicked me out
