### ISSUE TITLE
Can't place blocks

### ISSUE THREAD

**Issue by DanielAlves123** [ViaVersion/ViaVersion#1459]
**Describe the bug, provide any errors**
Can't place block when building upwards or when building a bridge.
It was reported before but hasnt been fixed.

**How can we reproduce it?**
1. Login on 1.14' or different version
2. Build upwards or build a bridge when shifting.

**Expected behaviour**
Should be able to build upwards while holding rmb and build bridges when shifting.

**ViaVersion Dump:**
- newest version of viaversion

**Additional server info**
latest hexacord, 1.8 server version

**Comment by Xernium** [comment]
Can't reproduce. If your anticheat is at fault then there is nothing ViaVersion can do about it.

**Comment by DanielAlves123** [comment]
@Xernium it happens because ViaVersion is trying to block placing blocks inside your own location.

**Comment by Xernium** [comment]
How is ViaVersion blocking that? Is Via installed on your bungee or your servers? I tried to reproduce your setup and wasn’t able to. You have to keep in mind that 1.14 hit boxes get smaller when crouching so it happens that the old hit boxes collide. However I haven’t noticed this as an issue. We need more info about your setup.

**Comment by MylesIsCool** [comment]
This is because of a spectator bug in paper afaik

**Comment by DanielAlves123** [comment]
@MylesIsCool how can we fix that?

**Comment by MylesIsCool** [comment]
Switch from paper or work out how to fix it

**Comment by DanielAlves123** [comment]
@MylesIsCool what should i change in paper to fix that? Wont this cause any other problems?
