### ISSUE TITLE
NoCheatPlus setback 'cancel' method blocks players in 1 place and kick for flying

### ISSUE THREAD

**Issue by DanielAlves123** [ViaVersion/ViaVersion#1460]
**Describe the bug, provide any errors**
When you set 'setback method' in NoCheatPlus to 'cancel' it will block players in 1 place after it detects them for using survivalfly. Without VIaVersion this isnt happening.

**How can we reproduce it?**
1. Login on any version
2. Set 'setback method' to cancel in NoCheatPlus.
3. Enable fly or trigger survivalfly.
4. Get blocked/bugged in 1 place then get kicked for flying.

**Expected behaviour**
Not being bugged in 1 place.

**Screenshots**
-

**ViaVersion Dump:**
latest versions of ViaVersion and NoCheatPlus

**Additional server info**
latest hexacord, 1.8 server

**Comment by MylesIsCool** [comment]
Nothing we can do about this, also you're missing ViaVersion dump. But it's a case of configuring the anti-cheat.

**Comment by DanielAlves123** [comment]
> Nothing we can do about this, also you're missing ViaVersion dump. But it's a case of configuring the anti-cheat.
Dump: https://pastebin.com/raw/Vh7hCRnQ
I think there's something you can do, it doesnt happen with ViaVersion and wasnt happening with ProtocolSupport.

**Comment by DanielAlves123** [comment]
@MylesIsCool

**Comment by MylesIsCool** [comment]
ViaVersion isn't ProtocolSupport, there are several movement changes which can't be fixed without insane amounts of code.

**Comment by DanielAlves123** [comment]
@MylesIsCool what do you mean by 'insane amounts of code'? The main problem is that, when someone trigger a fly when falling down, it will drag him back to the top. With 'setback cancel method' it will not drag him back to the top.

**Comment by Xernium** [comment]
@DanielAlves123 This happens because movement works differently in newer versions. The client expects data other than the provided. Myles is right, without insane amounts of code or stupidly complex workarounds there is no way VV knows that's what just happened

**Comment by Xernium** [comment]
That is especially considering this has to work being run from a bungeecord. ViaVersion isn't PS- we can't rely on the direct server logic to fix this

**Comment by DanielAlves123** [comment]
@Xernium i use VV for spigot. How to fix this problem then?
