### ISSUE TITLE
viaversion  Cannot get data for not block LEGACY_SIGN

### ISSUE THREAD

**Issue by leoncp9** [ViaVersion/ViaVersion#1461]
Hello i get this error
https://pastebin.com/2Q6vU54Y
the plugin is
https://www.spigotmc.org/resources/zombies-minigame-1-8-1-14-4.46148/
if i try to use protocolsupport i don't get anymore this error
so the problem is by viaversion, viarewind-legacy-support-1.3.2#4, viarewind-all-1.4.6#25 or viabackwards-all-3.0.0#180?

**Comment by KennyTV** [comment]
Not a Via issue and has nothing to do with packet translation, the given check is `Preconditions.checkArgument(material == null || material.isBlock())` and is most likely an issue on the plugin's side (either wrong checks or because of using legacy materials).

**Comment by leoncp9** [comment]
ok thank
