### ISSUE TITLE
1.13 swimming hitbox suggestion

### ISSUE THREAD

**Issue by soshimee** [ViaVersion/ViaVersion#1466]
**Is your feature request related to a problem? Please describe.**
I keep getting pushed back when I try to swim into 1 block wide gap.

**Describe the solution you'd like**
I want a option to allow players to swim into 1 block wide gap on config.yml.

**Describe alternatives you've considered**
Disabling move check.

**Which versions is this for?**
Does the feature apply to any specific versions? If so put them here.
1.13~1.14.4

**Comment by MylesIsCool** [comment]
Modifying the hitbox would require integration with each platform which obviously we could support it just on Bukkit however the changes are pretty deep in the source code to do this only on swimming (and would cause further anti-cheat issues).

I would suggest modifying the server for this kind of functionality, or updating and using backwards compatibility.

**Comment by soshimee** [comment]
1. I do not care about anti-cheats
2. I can't compile using mvn clean install/package even though I have maven and JDK
3. I was also searching for a reliable way to allow noclip

**Comment by Xernium** [comment]
1. That’s on you.    
2. OS? Version? Java version ? If applicable (w32) shell type?    
3. You’ll have to edit the Minecraft server source code for that. That is not something ViaVersion should ever be able to do.

**Comment by soshimee** [comment]
1. OK
2. Microsoft Windows 10 [Version 10.0.16299.1087] JDK 13 x64 Git Bash

**Comment by Xernium** [comment]
Okay I suggest you attempt to compile it again with openjdk-8 which you can download directly here: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u232-b09/OpenJDK8U-jdk_x64_windows_hotspot_8u232b09.msi
