### ISSUE TITLE
1.14 trident enchant book disconnection

### ISSUE THREAD

**Issue by soshimee** [ViaVersion/ViaVersion#1467]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?
You get disconnected for having a trident enchantment book.
`28.09 01:01:33 [Disconnect] User soshimee has disconnected, reason: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.`

**How can we reproduce it?**
1. Set your gamemode to creative
2. Grab one of the trident enchantment books.
3. You get kicked for no reason.

**Expected behaviour**
The enchantment book turning into stone or disappearing.

**Screenshots**
![2019-09-28_14 02 49](https://user-images.githubusercontent.com/45235204/65811781-b5d0a680-e1f8-11e9-8c6d-243388a5268b.png)

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/a91a11e8bd67127cbe8416e13dea9ee4080c5a157526d08df0a4e18328c6fcc8

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
No proxy
![2019-09-28_14 03 55](https://user-images.githubusercontent.com/45235204/65811804-d00a8480-e1f8-11e9-8de7-f221512db56d.png)
Paper 1.8

**Comment by MylesIsCool** [comment]
Please enable debug=true in the server.properties then recreate the issue and post the full error

**Comment by MylesIsCool** [comment]
See above
