### ISSUE TITLE
Can't eat

### ISSUE THREAD

**Issue by DanielAlves123** [ViaVersion/ViaVersion#1468]
**Describe the bug, provide any errors**
Try rightclicking while holding a sword then fast switch to golden apple for example and try to eat. It often blocks eating because it thinks that player is shield blocking. Disabling blocking is not helping because if you right click you slow down but shield doesnt appear.

**How can we reproduce it?**
Try rightclicking while holding a sword then fast switch to golden apple for example and try to eat. It often blocks eating because it thinks that player is shield blocking. Disabling blocking is not helping because if you right click you slow down but shield doesnt appear.

**Expected behaviour**
Eating should be possible.

**Screenshots**
-

**ViaVersion Dump:**
https://pastebin.com/raw/Vh7hCRnQ

**Additional server info**
latest hexacord, 1.8 server

**Comment by MylesIsCool** [comment]
As per https://github.com/ViaVersion/ViaVersion/issues/1082
