### ISSUE TITLE
Advancements

### ISSUE THREAD

**Issue by TheCompieter** [ViaVersion/ViaVersion#1471]
**Describe the bug, provide any errors**
Advancements dont show on 1.12.2

**How can we reproduce it?**
1. Login on 1.12.2'
2. Click on 'Advancements'
3. It won't load

**Expected behaviour**
it should load and show the advancements

**Screenshots**
https://i.imgur.com/XxXuyju.png

**ViaVersion Dump:**
https://dump.viaversion.com/f0818e06d492843622d23318c847f11f2fb590b03746a67d54132e3e67182c0f

**Additional server info**
i use an proxy with the viaversion,viabackwards,viarewind installed

**Comment by MylesIsCool** [comment]
Client version? server version?

**Comment by TheCompieter** [comment]
Client 1.12.2 Server 1.12.2

**Comment by MylesIsCool** [comment]
ViaVersion doesn't modify data for the same version.
