### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by TheCompieter** [ViaVersion/ViaVersion#1472]
**Describe the bug, provide any errors**
when trying too open statistics on 1.12.2 it won't load

**How can we reproduce it?**
1. Login on 1.12'
2. Click on 'Statistics'
3. It wont load :/

**Expected behaviour**
it should load the stats of the player

**Screenshots**
https://i.imgur.com/FynQEIn.png

**ViaVersion Dump:**
https://dump.viaversion.com/f0818e06d492843622d23318c847f11f2fb590b03746a67d54132e3e67182c0f

**Additional server info**
i also use viaversion, viabackward,viarewind on my proxy.

**Comment by MylesIsCool** [comment]
Client version? server version?

**Comment by TheCompieter** [comment]
Client 1.12.2 Server 1.12.2

**Comment by MylesIsCool** [comment]
ViaVersion doesn't modify data for the same version.

**Comment by TheCompieter** [comment]
do you maby then know what's causing this i just joined on an normal 1.14.4 client and it only load the advencements and not the statistics

**Comment by TheCompieter** [comment]
ok found the issue it was the viaversion, viabackward,viarewind on my waterfall proxy messing with it for some reason very wierd it shoudn't do that it i have one issue still the stastistics won't load on 1.14.4 with server version 1.12.2
