### ISSUE TITLE
Statistics not loading on 1.14.4

### ISSUE THREAD

**Issue by TheCompieter** [ViaVersion/ViaVersion#1473]
**Describe the bug, provide any errors**
when trying too open statistics on 1.14.4 it won't load

**How can we reproduce it?**
1. Login on 1.14.4'
2. Click on 'Statistics'
3. It wont load :/

**Expected behaviour**
it should load the stats of the player

**Screenshots**
https://i.imgur.com/8oxUM6p.png

**ViaVersion Dump:**
https://dump.viaversion.com/327dab8f9edf3eafa0434e767124774f6eb33c27e9a6e25bb72c00b73e5c5740

**Additional server info**
I dont use viaversion, viabackward,viarewind on my proxy anymore cause it was causing wierd bugs

**Comment by soshimee** [comment]
That happens to me too, I would like to see it getting fixed.
