### ISSUE TITLE
Own blockmappings

### ISSUE THREAD

**Issue by H4kt** [ViaVersion/ViaVersion#1485]
I would like to see a way in your API to add my own blockmappings like: somebody takes andesite wall and it translates not to stone, but to cobblestone wall. I know that I can add it thru reflection but it is rather complicated. While reseaching your code I found out that it would be very easy for you and extremely useful for pluginmakers.

**Comment by MylesIsCool** [comment]
Would a request like this not be more suitable for ViaRewind/ViaBackwards?

**Comment by H4kt** [comment]
No, because they provide support for older versions of the client. By the way I need to remap the new ones: 1.13+ and 1.14+ blocks.

**Comment by MylesIsCool** [comment]
This isn't a feature that many would use, I'd suggest using reflection / proposing a suitable API (we're open to this if it's just making certain fields accessible). Or implementing your own packet hooks.

**Comment by H4kt** [comment]
Like I used to think. You just don't care about developers. The same with docs.

**Comment by MylesIsCool** [comment]
You're more than welcome to pull request a suitable API as previously stated. Most people fork ViaVersion for features like what you stated as it's generally done for a specific server.

In regards to docs, we're open to feedback on what could be improved.

**Comment by H4kt** [comment]
Well, sorry for being rude. Just a bad day :)
