### ISSUE TITLE
ViaVersion Lag

### ISSUE THREAD

**Issue by UnDabber** [ViaVersion/ViaVersion#1488]
**Describe the bug, provide any errors**
Whenever a player joins, the WHOLE server lags for about 5-10 seconds, Also when a player tp to someone or somewhere

**How can we reproduce it?**
1. Login in with any version other than 1.8 versions, you will experience the lag for 5-10 seconds, also when you tp to someone or somewhere.

**Expected behaviour**
A lag free experience for the whole server

**Screenshots**
A Screenshot can not explain this

**ViaVersion Dump:**
- https://pastebin.com/qjfk1gTG

**Additional server info**
I use Bungeecord, and I only have 2 plugins (AdvancedBan and HubConnector), And all the servers that are connected to bungeecord are Spigot server mc version 1.8.8

**Comment by MylesIsCool** [comment]
Unless you can provide a .zip with minimalistic plugin setup, we're gonna be unable to solve this. There are lots of servers using ViaVersion fine, it might be down to the specs of your server as protocol translating isn't free but shouldn't stutter a decent server.
