### ISSUE TITLE
Protocol, ProtocolPipeline, UserConnection and PacketWrapper classes need redesign

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaVersion#1490]

**Comment by creeper123123321** [comment]
[ ] Deprecate outgoing and incoming packets terms in project code, use clientbound and serverbound

**Comment by FormallyMyles** [comment]
I'm going to close this as Abstraction has pretty much touched quite a bit of this.

For specific changes probably worth opening issue per change so we can track what needs doing.
