### ISSUE TITLE
Players on 1.14 can't see other players correctly.

### ISSUE THREAD

**Issue by soshimee** [ViaVersion/ViaVersion#1492]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?
There is no errors on the console,
Players on 1.14 using spectator mode can't see other players' arms/legs/body
**How can we reproduce it?**
1. Login on 1.14.x
2. Switch to spectator mode
3. Look at other players

**Expected behaviour**
I expected spectator mode to show all the body.

**Screenshots**
![2019-10-20_09 46 24](https://user-images.githubusercontent.com/45235204/67153100-8bb56480-f31e-11e9-84e8-83879101e86e.png)

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/d578f204ba377aa6a0549ede27fe3e1ca0865e76aee8732f597268d996d5ee33
**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
No bungeecord, Paper, Plugins: screenshot
![2019-10-20_09 47 33](https://user-images.githubusercontent.com/45235204/67153118-b8697c00-f31e-11e9-84f5-92ff036f2a93.png)

**Comment by soshimee** [comment]
Hey, anybody here?

**Comment by KennyTV** [comment]
Try reproducing the error on a clean server with only Via installed (which I cannot reproduce). If the error does not occur, readd your plugins step by step to see which one might be causing it

**Comment by soshimee** [comment]
I'll try that in a minute

**Comment by soshimee** [comment]
Additional info: Server is running on Paper 1.8.8

**Comment by soshimee** [comment]
![2019-10-21_22 58 15](https://user-images.githubusercontent.com/45235204/67211824-5ca20e80-f456-11e9-87d1-8b6cbdea47f3.png)
Still only shows the head.

**Comment by KennyTV** [comment]
What plugin creates those nps (since they don't look real players)? And did you remove all other plugins?

**Comment by soshimee** [comment]
That's not a npc, that's fake bots connected using a bot program

**Comment by soshimee** [comment]
It seems to be my client.
