### ISSUE TITLE
1.14 ghost blocks

### ISSUE THREAD

**Issue by LIWKK** [ViaVersion/ViaVersion#1493]
**Describe the bug, provide any errors**
My server runs 1.8.8 spigot and there are ViaVersion when you place block on 1.14 it makes you go trought blocks when placing them.

**How can we reproduce it?**
1. Login on 1.14 on 1.8.8 server with viaversion'
2. Place blocks
3. And you will fall trought some of them and you will get inside them.

**Additional server info**
We use bungeecord and the Viaversion is only installed inside proxy server

**Comment by MylesIsCool** [comment]
Please fill out the template fully (preferably with a video and the dump)

https://github.com/ViaVersion/ViaVersion/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by LIWKK** [comment]
Fixed with installing ViaVersion to backend server
