### ISSUE TITLE
Doors glitched on 1.14 client

### ISSUE THREAD

**Issue by TheRealElonMusk** [ViaVersion/ViaVersion#1495]
When you open & close doors, the door gets glitched & half-open half-closed.

1. Place a door.
2. Open it from the top hitbox.
  
The door is supposed to open & close as normal, but doesn't. The door instead gets glitched & half-open half-closed.

**Comment by soshimee** [comment]
just use serverside block connection in config.yml, there is already a fix

**Comment by MylesIsCool** [comment]
See what soshimee wrote
