### ISSUE TITLE
1.14.4 cannot connect to Spigot 1.13.2 server.

### ISSUE THREAD

**Issue by justnohacks** [ViaVersion/ViaVersion#1500]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?
https://pastebin.com/pPEi7EjB

**How can we reproduce it?**
Steps to reproduce the behaviour:
1. Start a 1.13.2 server.
2. Attempt to login using 1.14.4.

**Expected behaviour**
The user using the 1.14.4 client should be able to login and ping the server without the error occurring. The client also sees the red connection icon indicating an incompatible version in the multiplayer server list. This occurs with 2.1.3 and development builds of 2.1.4.

**Screenshots**
N/A

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/26f744e94c005815b346845fbe32bb42746889ae75ff2ea8a83ab2b9d312e153

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
No proxy.
Plugins listed in the dump.

**Comment by MylesIsCool** [comment]
ViaVersion only works with ProtocolSupport on paper.
