### ISSUE TITLE
Crawling animation for clients <1.14

### ISSUE THREAD

**Issue by HauserGrim** [ViaVersion/ViaVersion#1509]
In 1.14, the ability to crawl was added, but for versions <1.14 this appears as a simple walk through blocks. Also, the crawling player takes damage.

Set glide animation for crawling players.

Perhaps this will be even the best solution. Set glide for all players stuck in 1 block. This will remove the imbalance between players 1.14, which can crawl and players <1.14.

For all versions >=1.9

I used a translator due to problems with English.

**Comment by MylesIsCool** [comment]
I would suggest updating your server to take advantage of newer features, crawling won't function properly due to block collision issues as it is and gliding could introduce further issues as the hitbox is different.
