### ISSUE TITLE
Java 13: Bungee fails to inject properly

### ISSUE THREAD

**Issue by cloakfox** [ViaVersion/ViaVersion#1512]
**Describe the bug, provide any errors**
https://pastebin.com/1jipynZv

**How can we reproduce it?**
1. Waterfall: https://papermc.io/ci/job/Waterfall/296/
2. Java 13
3. ViaVersion 2.1.3

**Expected behaviour**
Normal load

**Screenshots**
See pastebin

**ViaVersion Dump:**
https://dump.viaversion.com/3b22d7fa375abc2dc068a7c45251744b00b056b9417e23d94dc5de17e603ce99

**Additional server info**
We use Waterfall (bungeecord fork) with java 13

**Comment by cloakfox** [comment]
Tried latest dev build, same error: https://pastebin.com/LtZTkj2c

**Comment by cloakfox** [comment]
Update: Switched to java 8 that was made before ww2, and everything works now

**Comment by MylesIsCool** [comment]
It's been a while since I looked at this, but reflection changed in Java 9 and I suspect with how Bungee is built. It might be very hacky/impossible to get this working nicely.

**Comment by cloakfox** [comment]
> It's been a while since I looked at this, but reflection changed in Java 9 and I suspect with how Bungee is built. It might be very hacky/impossible to get this working nicely.

Fair enough!

**Comment by KennyTV** [comment]
I think this is the operation that is not allowed by default anymore: https://github.com/ViaVersion/ViaVersion/blob/47819180c492f10e5df0dbe85dd884f7f59cddbd/bungee/src/main/java/us/myles/ViaVersion/bungee/platform/BungeeViaInjector.java#L27
If you still want to use Java 9 or higher, you can look into the flag `permit-illegal-access` to allow those again (iirc internally nothing really changed, just that the value was different in 8 by default).
