### ISSUE TITLE
Chunk bugs on spigot 1.8.8 server

### ISSUE THREAD

**Issue by lixfel** [ViaVersion/ViaVersion#1516]
**Describe the bug, provide any errors**
Multiple block changes in one tick (guess: MultiBlockChangeUpdate, maybe chunk update) result in a buggy chunk for all connected players with minecraft version >= 1.9. All air blocks are replaced with an updated block. Players playing 1.8.x or joining after the chunk bug occurs stay unaffected.

**How can we reproduce it?**
1. Login on any version >= 1.9 on an 1.8-spigot or paper server
2. Trigger multiple block changes in one chunk in one tick (eg. placing a water block with a bucket)
3. Air blocks are showed as some other block.

**Expected behaviour**
Air blocks should stay air blocks :).

**Screenshots**
![2019-11-12_07 53 15](https://user-images.githubusercontent.com/26159085/68649086-30901f80-0522-11ea-986e-a2a3246ae5cf.png)
Here I started to load a tnt cannon.

![grafik](https://user-images.githubusercontent.com/26159085/68649815-e6a83900-0523-11ea-9470-f69caa752d8a.png)
Here a picture with multiple bugged chunks.

**ViaVersion Dump:**
https://dump.viaversion.com/ce3162d2d57aa5c8788068aa9a64fbafa02fd06d6582b7f3db4f142db21a23b1

**Additional server info**
The error occurs also without WatchCat (the anticheat) running.
My own plugins do not produce the bugs.
When WorldEdit / FastAsyncWorldEdit pastes a schematic (multiple chunk updates), the bug does not occur.
The Server is running behind a bungee (without viaversion).

**Comment by creeper123123321** [comment]
What's the exact client version?

**Comment by lixfel** [comment]
Tested with 1.12.2 (optifine) and 1.9.4 client.

**Comment by MylesIsCool** [comment]
Would you be able to test with minimal amount of plugins to cause the issue?

**Comment by lixfel** [comment]
I did some research in my plugins (step by step). I found out, that the bug only appears in Chunks modified by FAWE (FastAsyncWorldEdit) after pasting a schematic/clipboard (couldn't reproduce it with simple //set). I found a correlating bug report for FAWE:
https://github.com/boy0001/FastAsyncWorldedit/issues/1191
Now its a question if this bug can be fixed in ViaVersion or if this bug needs to be fixed in FAWE (what seems not to happen currently).

**Comment by creeper123123321** [comment]
Does this bug only affect Bukkit platform?

**Comment by lixfel** [comment]
I didn't test it with other platforms than bukkit/spigot/paper.

**Comment by FormallyMyles** [comment]
This would seem directly related to bad FAWE updating so gonna close, if there is something we can fix let us know :)
