### ISSUE TITLE
Just Me? ( [Proxy] Lost Connection to Server)

### ISSUE THREAD

**Issue by ccorp2002** [ViaVersion/ViaVersion#1517]
**Almost all Players are getting the error: [Proxy] Lost Connection to Server**
Hastebin: https://hastebin.com/fojuyexago.md

**How can we reproduce it?**
1. Login with 1.12.2 Client on 1.12.2 Hub/Any-other linked Server'
2. World (tries to) load/render.
3. Player (me and others) "kicked" with the error of: `[Proxy] Lost Connection to Server`
4. Checked bungee-config/spigot.yml
**Expected behaviour**
Everything works perfectly fine, Players can join with 1.12.2 and Newer.

**Screenshots**
http://imgur.com/WqB6Lail.png

**ViaVersion Dump:**
ViaVer Dump:
https://dump.viaversion.com/8c330cbc8630701bcbb2a4d3f750809462d63670342b44726527cdacfbb4f772

**Additional server info**
I use a Waterfall proxy, (without ViaVersion installed on it), and I run 1.12.2 paper-spigot servers behind the *Waterfall* Proxy with LuckPerms, a MySQL Database, and ViaVersion Installed on them

**Comment by MylesIsCool** [comment]
Could you test without ViaVersion?

**Comment by ccorp2002** [comment]
I'll see if that changes anything, thank you for your support

**Comment by creeper123123321** [comment]
How many allocated heap do you have in your servers?

**Comment by ccorp2002** [comment]
Yes the allocated ram should definitely be enough, also I just tested without ViaVersion and the same exact error occurred. I am now utterly confused.

**Comment by ccorp2002** [comment]
I have given the Lobby/Hub Server up to 2 GB of RAM. Its definitely not a hardware issue, as far as I am concerned.

**Comment by ccorp2002** [comment]
[latest.log](https://github.com/ViaVersion/ViaVersion/files/3843836/latest.log)
Here is the latest log, from without ViaVersion Installed.

**Comment by MylesIsCool** [comment]
I'm going to close this issue as it's unrelated to ViaVersion but this is what I'd try if it was me:

- Copy your server and run it with no plugins, does it crash?

Assuming the previous doesn't crash, add half the plugins and test. I'd suspect this could be down to a plugin.

Worth noting your console also prints [14:57:57] [Server thread/WARN]: Debugging is enabled, performance maybe reduced! which will impact performance :)
