### ISSUE TITLE
Allocated RAM amount in /viaver dump

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaVersion#1519]
**Is your feature request related to a problem? Please describe.**
Yes. There may be some issues related to low RAM and block connections but we can't know if it is related to heap and issue managers may be confused with the "weird" issues

**Describe the solution you'd like**
Adding allocated and used heap to /viaver dump

**Describe alternatives you've considered**
No one

**Which versions is this for?**
All versions

**Comment by FlorianMichael** [comment]
Resolved in https://github.com/ViaVersion/ViaVersion/pull/2451
