### ISSUE TITLE
crash bug, port ignoring

### ISSUE THREAD

**Issue by DOGSLV2** [ViaVersion/ViaVersion#1524]
17.11 10:02:14 [Server] WARN [ViaVersion] Ignoring plugin channel in incoming REGISTER: legacy:fml|hs
17.11 10:02:14 [Connect] User thegamerslvfan1, IP **********
17.11 10:02:14 [Server] WARN [ViaVersion] Ignoring plugin channel in outgoing REGISTER: UUIDSpoofFix
17.11 10:02:14 [Server] WARN [ViaVersion] Ignoring plugin channel in outgoing REGISTER: RedisBungee
17.11 10:02:14 [Server] WARN [ViaVersion] Ignoring plugin channel in outgoing REGISTER: WECUI
screensshots: 
![image](https://user-images.githubusercontent.com/57896287/69043700-32635280-09fc-11ea-9f75-127df42d31af.png)
players need relog in server

**Comment by MylesIsCool** [comment]
Your plugins aren't compatible with 1.13+ plugin channels, this isn't something ViaVersion can fix. You'd need to update your plugins.
