### ISSUE TITLE
[Spigot 1.8.8] Crashes becouse of ViaVersion

### ISSUE THREAD

**Issue by kasdo** [ViaVersion/ViaVersion#1533]
Hello guys! I have problem with ViaVersion. SPigot 1.8.8
https://pastebin.com/sXq5F24L

My server have been crashing once-twice per day. Im using 2.1.3 version of ViaVersion (Before I was using 2.1.1, but I had been crashing before too).

How I can fix that?

**Comment by MylesIsCool** [comment]
This isn't related to ViaVersion. ViaVersion triggers player ticking, this is probably bad world entry / player corruption.
