### ISSUE TITLE
1.13+ Client on 1.12.2 Server gains jump boost type anomaly when exiting water source block at y255

### ISSUE THREAD

**Issue by MacTh3Mac** [ViaVersion/ViaVersion#1535]
**Describe the bug, provide any errors**
When a player in 1.13 and higher versions is at build limit on a 1.12.2 server if the submerge their head below the water (must be a source block) then exit onto a solid block placed at build limit they gain a Jump Boost Effect (this effect isn't shown in inventory view or is an actual effect). If is just a movement anomaly.

**How can we reproduce it?**
1. Login on 1.13+ to 1 1.12.2 PaperSpigot Server Build 1618
2. Stand on a block at Y255
3. Ensure that the block next to your is a water source block
4. Submerge the characters head below the source block of waters surface
5. Exit onto solid block
6. The player has an apparent Jump Boost Effect

**Expected behaviour**
The player not to gain an apparent jump boost

**Screenshots** (2 x videos of how to reproduce)
https://youtu.be/Q_wfw11pXrs 
https://youtu.be/8G2lXKQtJ4k

**ViaVersion Dump:**
https://dump.viaversion.com/e32735148426ea7fde0abc74c1bfa7644aad455a1d03d6e5108d90289b89d20f
(note this is on a test server and many plugins listed in dump)
However I can reproduce this on a server with no plugins except via version / backwards / rewind

**Additional server info**
Behind Waterfall (Latest)

**Comment by MylesIsCool** [comment]
Apologies for the delay in replying to this issue,

Are you aware if this issue works in vanilla 1.13?

**Comment by MacTh3Mac** [comment]
Sorry MylesIsCool we don't run any 1.13 servers anymore.  I only have 1.12.2 Servers with ViaVersion and 1.15.2 (no via version). 

Wish I could assist more.

**Comment by KennyTV** [comment]
I can reproduce this on a 1.15.2 server with a 1.15.2 client, so this actually seems to be a proper clientbug. I'd suggest reporting this on Mojang's issue tracker
