### ISSUE TITLE
Invisible fishing hook on 1.15-pre3

### ISSUE THREAD

**Issue by ishland** [ViaVersion/ViaVersion#1538]
**Describe the bug, provide any errors**
I cannot see the fishing hook when I am fishing. I can continue fishing but it is more difficult by hearing the sound.

**How can we reproduce it?**
1. Login on 1.15-pre3
2. Go fishing
3. No fishing hook

**Expected behaviour**
There should be a fishing hook.

**Screenshots**
![2019-11-29 (2)](https://user-images.githubusercontent.com/30385023/69876873-ad314500-12fb-11ea-80a0-9af4454fe9f9.png)
![image](https://user-images.githubusercontent.com/30385023/69876927-c508c900-12fb-11ea-9c0e-1d65c1d68ab6.png)

**ViaVersion Dump:**
https://dump.viaversion.com/3964044634fa3cee4796c3c39313c3ca97377e18b1b0ff12b891baa72bbd5bfa

**Additional server info**
This server is running Paper version git-Paper-226 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
![image](https://user-images.githubusercontent.com/30385023/69877070-26309c80-12fc-11ea-99ea-8cd624c8e024.png)

**Comment by KennyTV** [comment]
Fixed in #1557
