### ISSUE TITLE
BungeeCord shield when blocking

### ISSUE THREAD

**Issue by AwesomestCode** [ViaVersion/ViaVersion#1539]
When using ViaVersion on BungeeCord, shields don't show for 1.8-->1.12.2 clients

**How can we reproduce it?**
1. Download the latest version of bungeecord, run it and connect it to a spigot **1.8.8** server
2. Install ViaVersion on **BungeeCord**
2. Log on using 1.12.2
3. Get a diamond sword
4. Right Click

**Expected behaviour**
Shield shows on the client blocking

**Actual behavior**
Shield only shows on other clients, nothing occurs on client blocking.

**ViaVersion Dump:**
https://dump.viaversion.com/3abdedb2f24414d052157de4c047b9a075d155813684de32a4268e1372e1a51a

**Comment by MylesIsCool** [comment]
If you see the docs, you'll find this isn't a feature support on Bungee.
https://docs.viaversion.com/display/VIAVERSION/Configuration

**Comment by AwesomestCode** [comment]
Can this be changed to a feature request, then?

**Comment by MylesIsCool** [comment]
It's not something we'll implement as it requires full inventory tracking
