### ISSUE TITLE
ViaVersion does not specify an api-version + no keys for somes entities

### ISSUE THREAD

**Issue by x9nico** [ViaVersion/ViaVersion#1541]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?

https://hastebin.com/wutiqireya.md

**How can we reproduce it?**
Just start the server, and look logs

**Expected behaviour**

When I'm starting my 1.14.4 server, it says of there is no key for somes entities and the plugin does not specify any API version (warnings in logs)

**Screenshots**

See the hastebin's URL at the top.

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.

https://dump.viaversion.com/58cd3965a4fe7bb48eb8b4df01e87b215cb260e0a6db92ea4e2ec399218ce4a2

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

I'm using PaperSpigot in 1.14.4

**Comment by MylesIsCool** [comment]
Specifying an API version would break the plugin in older versions, hence we don't
