### ISSUE TITLE
Blaze show to 1.15 pre-3 as Pigs

### ISSUE THREAD

**Issue by TheMasterBlaster** [ViaVersion/ViaVersion#1542]
Proxy Type/Name - Waterfall | Build # - 297
   Running - ViaVersion-2.1.4-1.15-pre3.jar | Build #291

Server Type/Name - Paper | Build #230
   Not running ViaVersion

Client - 1.15 Pre-release 3
Client - 1.14.4 does not have this issue

Issue - Blaze show to 1.15 pre-3 client as Pigs

![PigBlaze](https://user-images.githubusercontent.com/9083212/69904235-34b99b00-1372-11ea-922c-144664519d1d.png)

**Comment by MylesIsCool** [comment]
Thank you! Fixed by Kenny in latest
