### ISSUE TITLE
Biomes on 1.14 server dont show on 1.15 pre 3 client

### ISSUE THREAD

**Issue by TheMasterBlaster** [ViaVersion/ViaVersion#1547]
Proxy Type/Name - Waterfall | Build # - 297
Running - ViaVersion-2.1.4-1.15-pre3.jar | Build #292

Server Type/Name - Paper | Build #230
Not running ViaVersion

Client - 1.15 Pre-release 3
Client - 1.14.4 does not have this issue

The Biome seems to always show as an Ocean biome. I have tested with multiple different areas and it seems to stay as that one specific type

**Comment by MylesIsCool** [comment]
Fixed in latest
