### ISSUE TITLE
Inject into client <-> Velocity and Velocity <-> server connections

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaVersion#1550]
Changing protocol versions on the flight on Velocity proxy is a bad idea and probably will break on 1.1.0 version which has 1.7 protocol.
An idea for dealing with that issue: select the closest protocol in client <-> Velocity and make the more 'agressive' transformations on Velocity <-> client connections, and never change ``ConnectedPlayer``'s version field.
Depends on #1536

**Comment by astei** [comment]
I've merged the required Velocity patch.

**Comment by creeper123123321** [comment]
Implemented
