### ISSUE TITLE
Permissions?

### ISSUE THREAD

**Issue by BlueDigPVP** [ViaVersion/ViaVersion#1551]
![2019-12-05_07 57 52](https://user-images.githubusercontent.com/58558570/70240078-9a26d680-173a-11ea-9c4c-7bf0b52600a9.png)
Hello! I am the owner of a server and i cant use the /viaversion commands even though console can but im op and have the * perm im using this on a bungee cord server with 1.8 to 1.14 is it a permission or am i going crazy can anyone help me? thanks - BlueDigPVP

**Comment by MylesIsCool** [comment]
viaversion.admin is the permission node, you'd need this on the bukkit side

**Comment by BlueDigPVP** [comment]
Thanks!
