### ISSUE TITLE
1.13.X weird disconnect.spam kick on any command execution

### ISSUE THREAD

**Issue by TukanDev** [ViaVersion/ViaVersion#1553]
**Describe the bug, provide any errors**
When user plays on 1.8 spigot server and joins on 1.13.2 (did not tested on other sub versions) and try to do any command it kicks them for disconnect.spam.

**How can we reproduce it?**
1. Login on 1.13.2
2. Try doing any command (be sure to have some plugins installed, i persoally got that error with a skyblock command /is <username>)
3. Boom you get kicked for disconnect.spam

**Expected behaviour**
Kicked from server with message "disconnect.spam" and console output of:
> [09:01:10 INFO]: <username> lost connection: disconnect.spam
> [09:01:10 WARN]: handleDisconnection() called twice

**Screenshots**
I think there is no need for screenshots.

**ViaVersion Dump:**
https://dump.viaversion.com/47093bb590ee2f139e97470b9241ae8eb36dc83344d3d70f1d10bbea59afed41

**Additional server info**
Normal spigot 1.8 with a lot of plugins if its rly needed i will send a screenshots since there are 104 of them (ik ik too much but they are all needed)

**Comment by MylesIsCool** [comment]
https://github.com/ViaVersion/ViaVersion/issues/891#issuecomment-417838235
