### ISSUE TITLE
internal error kick when joining 1.8 server with 1.9-1.14.4

### ISSUE THREAD

**Issue by PhanaticD** [ViaVersion/ViaVersion#1556]
**Describe the bug, provide any errors**
this first occurence of the error happens: https://pastebin.com/raw/bCu3P2X5
all subsequent logins from newer versions than 1.8 are kicked with: https://pastebin.com/raw/QuLxJcv6
**How can we reproduce it?**
this occurs completely randomly, a 1.8.8 minigame server restarts every 2 hours, and this issue happens maybe once every two weeks
**Expected behaviour**
for this error to not occur
**ViaVersion Dump:**
https://dump.viaversion.com/e5a307a5eecf53c3c2bec5c748df50a8b2834a65bd91bb7b99b295a842fd2e07
^ note this dump was taken after a restart and the server was working again, not while it was in a bugged state
**Additional server info**
I use travertine

**Comment by MylesIsCool** [comment]
LinkageError is down to versions not aligning / possible corrupt jar. I'd ensure your matching ViaVersion/ViaRewind/Legacy all to latest Dev builds.

**Comment by PhanaticD** [comment]
ive done that for months, it still happens

**Comment by MylesIsCool** [comment]
Do you use automatic scripts or similar? Because your server is doing something that leads to bad class loading then

**Comment by PhanaticD** [comment]
all i have is in crontab stop the server, then swap out the region folder for a new map and then start it a minute later
