### ISSUE TITLE
1.15 pre7 cant play discs in jukebox

### ISSUE THREAD

**Issue by TheMasterBlaster** [ViaVersion/ViaVersion#1560]
Proxy Type/Name - Waterfall | Build # - 300
Running - ViaVersion-2.1.4-1.15-pre7.jar | Build #298

Server Type/Name - Paper | Build #235
Not running ViaVersion

Client - 1.15 Pre-release 7
Client - 1.14.4 does not have this issue

When trying to use a jukebox to play a music disc in 1.15 Pre nothing seems to happen. The disc is still put into the jukebox but no music players and the actionbar does not show anything. The proxy throws error "[ViaVersion]: Missing 1.14 item for 1.13.2 item 851" once each time.

**Comment by Gerrygames** [comment]
Should be fixed by #1561 :)
