### ISSUE TITLE
Lantern Bug

### ISSUE THREAD

**Issue by JanisPlayer** [ViaVersion/ViaVersion#1564]
**How can we reproduce it?**
1. login with a 1.15 client on a 1.14.4-R0.1-SNAPSHOT Paper Server where ViaVersion-2.2.0 is installed.
2. Hit a lantern and it changes to a bell.

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/54918417/70571511-5c90d600-1b9e-11ea-830a-d3487a5c245c.png)

**Comment by TheMasterBlaster** [comment]
Can confirm this happens on 1.15 clients using latest ViaVersion on a 1.14 server via Waterfall

**Comment by JanisPlayer** [comment]
![ezgif-4-7481d72a68eb](https://user-images.githubusercontent.com/54918417/70574212-e0998c80-1ba3-11ea-9227-cda2f32e3958.gif)
I hit a lantern with a pickaxe and it turns into a bell.
The with the changing tool is normal, this is a plugin called multitool.

**Comment by TheMasterBlaster** [comment]
From my testing its only doing that client side(only the one that starts breaking it sees it that way). I have found right clicking it will make it show correctly.
