### ISSUE TITLE
Anvil client crash

### ISSUE THREAD

**Issue by theworldislonely** [ViaVersion/ViaVersion#1570]
**How can we reproduce it?**
1. Login on 1.15 on a 1.14 server
2. put an non-enchanted, full durability item into an anvil
3. The client crashes with:
"The game crashed whilst unexpected error
Error: java.lang.StackOverflowError: Unexpected error"

**Additional server info**
viaversion is running on bungeecord

**Comment by TheMasterBlaster** [comment]
Same issue here using The proxy Waterfall on a Paper 1.14.4 server

**Comment by KennyTV** [comment]
A client error that will apparently be fixed in 1.15.1 https://bugs.mojang.com/browse/MC-167530

**Comment by TheMasterBlaster** [comment]
Weird.. I can only get it to crash on a server using ViaVersion but Bukkit 1.15 is fine and so is Singleplayer.

**Comment by KennyTV** [comment]
Not sure about the specifics, but it is indeed fixed in 1.15.1-pre1 (on a lower server with ViaVersion)
