### ISSUE TITLE
1.8 players kicked on teleport

### ISSUE THREAD

**Issue by dnyferguson** [ViaVersion/ViaVersion#1571]
**Describe the bug, provide any errors**
Players on 1.8 get kicked when teleporting. For example by warping to different positions or switching worlds. The kick shows as '(player) lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.' in console.

**How can we reproduce it?**
I'm using the following versions on paper 1.12.2
- Viaversion: 2.2.1
- ViaBackwards 2.4.0-SNAPSHOT
- ViaRewind 1.4.5

**ViaVersion Dump:**
https://dump.viaversion.com/ddd13b52c5a6c0f5b431a243f7718d7902d6c30a9101f4697599866ed188233a

**Additional server info**
I have viaversion running on the proxy (waterfall build #303) and then I have viaversion, viabackwards and viarewind on my 1.12 servers.

**Comment by AlekseyTitov99** [comment]
Having the same issue, players reported it after latest viaversion was uploaded

**Comment by MylesIsCool** [comment]
Closing as solved on discord,

Solution: Update to ViaBackwards-DEV
