### ISSUE TITLE
Flickering Entity updates

### ISSUE THREAD

**Issue by tr7zw** [ViaVersion/ViaVersion#1574]
**Describe the bug, provide any errors**
When entities get updated/spawned (in the example Armorstands, but also happens with for example Anticheat invisible entities beeing shortly visible), the Entity Meta seems to be set a tick off causing flickering on the entity. This happens especially right after joining. Using 1.14 doesn't seem to have side effects like that.

**How can we reproduce it?**
1. 1.8 server with 1.15 client
2. Update (packet-based?) Holograms

**Screenshots**
[Gif](https://tr7zw.dev/u/flicker.gif)

**ViaVersion Dump:**
- Can be provided when asked via Discord

**Additional server info**
1.15 Bungee and a 1.8 paper(custom) server with ViaVersion 2.2.1

**Comment by KennyTV** [comment]
Not fixable, since Mojang removed the metadata in the spawn packet and (afaik) we have no way of *instantly* sending them behind each other
