### ISSUE TITLE
Version 1.15 players have no recoil when attacked by a lower version. (Server version 1.12.2-1.15)

### ISSUE THREAD

**Issue by chaikaa** [ViaVersion/ViaVersion#1577]
Version 1.15 players have no recoil when attacked by a lower version. (Server version 1.12.2-1.15)

**Comment by KennyTV** [comment]
Can't reproduce - please ensure you're running the latest version from the ci and follow the given issue template (and try removing other plugins to find if it's actually caused by ViaVersion, for example your anticheat).
