### ISSUE TITLE
Client crashes while sending equipment packets 

### ISSUE THREAD

**Issue by MeowMiaoMiao** [ViaVersion/ViaVersion#1581]
Test client version: 1.14 、1.15
Test server version: spigot 1.8.8

code:
` @Override
            public void onPacketSending(PacketEvent packetEvent) {
                if (packetEvent.getPacketType() == PacketType.Play.Server.ENTITY_EQUIPMENT) {
                    WrapperPlayServerEntityEquipment entityEquipment = new WrapperPlayServerEntityEquipment(packetEvent.getPacket());
                    WrapperPlayServerEntityEquipment rcEntityEquipment = findEquipmentRecord(entityEquipment.getEntityId());
                    if (rcEntityEquipment != null) {
                        if (entityEquipment.getSlot() == rcEntityEquipment.getSlot()) {
                            entityEquipment.setSlot((short) rcEntityEquipment.getSlot());
                            entityEquipment.setItem(rcEntityEquipment.getItem());
                        }
                    }
}`
![QQ截图20191213025646](https://user-images.githubusercontent.com/29674595/70740526-4f1d4c80-1d54-11ea-89e6-dba20bef515a.jpg)

**Comment by MylesIsCool** [comment]
Does this happen on 1.13?

**Comment by MeowMiaoMiao** [comment]
> Does this happen on 1.13?

No, the test results have the same problem in 1.13, 1.12 and 1.11.2.

**Comment by MylesIsCool** [comment]
This is down to you sending invalid equipment indexes, I'd suggest ensuring your sending the right IDs for the server version your on.

**Comment by MeowMiaoMiao** [comment]
> This is down to you sending invalid equipment indexes, I'd suggest ensuring your sending the right IDs for the server version your on.

But he works fine on the 1.8.8 client

**Comment by MylesIsCool** [comment]
> > This is down to you sending invalid equipment indexes, I'd suggest ensuring your sending the right IDs for the server version your on.
> 
> But it works fine on the 1.8.8 client

Just because it works on a 1.8.8 client doesn't mean it's valid
