### ISSUE TITLE
ERROR: Could not find type id 1940

### ISSUE THREAD

**Issue by andrewkm** [ViaVersion/ViaVersion#1582]
Getting spammed with:
https://pastebin.com/raw/QVQJtU4h

Using 2.2.2
Build 383
https://ci.viaversion.com/job/ViaVersion/383/

**Comment by andrewkm** [comment]
Happening with tons of other IDs as well.
https://i.imgur.com/kxmNICZ.png

**Comment by MylesIsCool** [comment]
I'd suggest debugging other plugins + ensuring your up to date otherwise as this isn't seen otherwise
