### ISSUE TITLE
Unknown command at position 1: /<--[HERE]

### ISSUE THREAD

**Issue by andrewkm** [ViaVersion/ViaVersion#1583]
I'm getting this when typing beginning to type any command:
https://i.imgur.com/6poELeE.png

Happens on 1.15 client connected to 1.14.4 server.
Cannot reproduce on 1.14.4 client connected to 1.14.4 server.

Using 2.2.2
Build 383
https://ci.viaversion.com/job/ViaVersion/383/

**Comment by hvrry** [comment]
Me too, latest Paper 1.14.4 and latest ViaVersion 2.2.2

**Comment by andrewkm** [comment]
Ultra annoying, lol if anyone finds a fix let me know :)

**Comment by soshimee** [comment]
1.13+ clients gets the preview of the answer of the command.
If you start typing a command, minecraft automatically searches for a preview, and the preview is "unknown command...." message.

**Comment by soshimee** [comment]
That does not happen to me, if there's no tab completion anymore to show, that happens.

**Comment by Xernium** [comment]
Yes it’s as @soshimee said. If you don’t send any possible tab completions this is what will happen on 1.15+. Since this is a specialized problem I don’t even know what to do about it because it doesn’t seem to be a bug to me... Another project member will have to have the last word on this

**Comment by USLeronus** [comment]
Same issue here, any solutions?

**Comment by USLeronus** [comment]
Even /help gives the error. The command does work however... Very annoying
