### ISSUE TITLE
[ViaVersion] Ignoring plugin channel in outgoing REGISTER: CostomChannel

### ISSUE THREAD

**Issue by frengor** [ViaVersion/ViaVersion#1589]
**Describe the bug, provide any errors**
I have a bungee network and on one server (1.8.7) one of my plugins registers an outgoing bungeecord channel called Control.
Then, everytime I login on that server ViaVersion sends me this message:

[ViaVersion] Ignoring plugin channel in outgoing REGISTER: Control

This happen also with others channels, like:

[ViaVersion] Ignoring plugin channel in incoming REGISTER: legacy:wdl|init

but the real problem is that without my cusotm channel that server won't work.

**How can we reproduce it?**
- Starts a server in 1.8.7 with a plugin that registers a custom outgoing channel
- Connect it to a bungeecord
- Connect with 1.14-1.15 to bungeecord and move to that server

**Expected behaviour**
You should see
[ViaVersion] Ignoring plugin channel in outgoing REGISTER: YouChannel
in the console

**Screenshots**
https://i.imgur.com/4sP6cc3.png

**ViaVersion Dump:**
https://dump.viaversion.com/474ab5de05f49757fcfa28e6c8d078b95701596c5c36823b8dea444c4907fb5e

**Additional server info**
I'm using BungeeCord, Spigot 1.8.7, VIaVersion, all to the latest version.

**Comment by MylesIsCool** [comment]
Channels need to be 1.13 compatible, 

eg. pluginname:test

We can't do this for you and it crashes clients/servers otherwise.

**Comment by SrLeojaco** [comment]
@MylesIsCool So in order to work they should follow the format xxxx:xxxx or it must be pluginname:channelname?

**Comment by MylesIsCool** [comment]
> @MylesIsCool So in order to work they should follow the format xxxx:xxxx or it must be pluginname:channelname?

Common use is pluginname:channel but the client doesn't care as long as it's xxx:yyy
