### ISSUE TITLE
Elytra bugged on 1.15

### ISSUE THREAD

**Issue by JHarris12345** [ViaVersion/ViaVersion#1592]
**Describe the bug, provide any errors**
If you use elytra in 1.15 client on a 1.14.4 client then it just glitches out. You get locked in glide mode and have to relog to fix it.

**How can we reproduce it?**
1) Login on 1.15 client
2) Enter 1.14.4 server
3) try to fly with elytra

**Expected behaviour**
It flies normally 

**ViaVersion Dump:**
https://dump.viaversion.com/8d2e00dce666fd20d25edc6c4716383a8f44de1f07c11543442eb7c80c00adb9

**Comment by KennyTV** [comment]
Can't reproduce on a clean server - please test your issues without any other plugins ,same for your VB issue, this is probably an AntiCheat issue (will reopen if we have a consistent method to reproduce it on a clean server)

**Comment by JHarris12345** [comment]
Ive just tested on a completely clean server. Only plugin was via version and the issue persists. My ViaVersion version is 2.2.2 and here is my jar

![image](https://user-images.githubusercontent.com/46936647/71023353-79775d00-20fa-11ea-9e80-cbc8d6ba9224.png)


This is 1000% an issue

**Comment by JHarris12345** [comment]
My server is part of my bungee network

**Comment by KennyTV** [comment]
"You have no new mail" definitely doesn't seem like there is no other plugin, you also run a modified server jar

**Comment by JHarris12345** [comment]
Thats just essentials which wont affect anything. And as you can see from my screenshot, that is not a modified jar in what I tested it on

**Comment by JHarris12345** [comment]
The issue is bungee. How do I solve the issue. On a normal server it's all fine but when connected to my bungee server it breaks

**Comment by KennyTV** [comment]
Hmm, I started up a Bungee behind a 1.14 server and still couldn't repro that 👀 your best bet is to start a testproxy, remove plugins one by one and see which one might be causing it I guess (and see if plain Bungee is on the latest version as well)

**Comment by JHarris12345** [comment]
If the bungee is 1.15, does it need a via version or anything? Or just the spigot servers on 1.14 needing viaversion?

**Comment by KennyTV** [comment]
Just on the Spigot servers

**Comment by JHarris12345** [comment]
Yeah it was the custom bungee jar
