### ISSUE TITLE
Crucial bug with quick-move-action-fix

### ISSUE THREAD

**Issue by FernandoLorenzo1337** [ViaVersion/ViaVersion#1594]
**Describe the bug, provide any errors**
When you shift + left click in enderchest it wont add some items. When you set quick-move-action-fix to false problem disappears.

**How can we reproduce it?**
1. On 1.14 client version open ender chest with items in it.
2. Try to grab them with shift + lpm.
3. It gets bugged and some of items are not added to inventory.

**Expected behaviour**
Should add all items.

**Screenshots**
-
**ViaVersion Dump:**
not needed

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Comment by KennyTV** [comment]
Closing this in favor of #2044, since it has a video showcase of the bug
