### ISSUE TITLE
Java versions 11 and Higher Support - ViaVersion Bungee Injection into childHandler

### ISSUE THREAD

**Issue by Justsnoopy30** [ViaVersion/ViaVersion#1597]
Can someone add a check to viaversion for if the java version is 11 or higher and if it is, don't use the setAccessible make non final method on childHandler (because it doesn't work anymore on java 11 and higher), instead use the method described here: https://stackoverflow.com/a/56043252 ?

**Comment by KennyTV** [comment]
We'll try the method you sent thanks! Progress will be tracked in #1512
