### ISSUE TITLE
Inventory bug

### ISSUE THREAD

**Issue by skipthevoid** [ViaVersion/ViaVersion#1598]
**Describe the bug, provide any errors**
1.8 client version.
https://www.youtube.com/watch?v=23BJeAjg1tI

**How can we reproduce it?**
1. Login on 1.8 or other version
2. Try changing slot of items on hotbar or somewhere else
3. Items are at the same slot on the client side but not server side. When you use player.updateInventory it will go back to the original slots. Maybe DiscoArmor plugin that send PacketPlayOutEntityEquipment to other players break that? 

**Expected behaviour**
Items should have correct slot.

**Screenshots**
-

**ViaVersion Dump:**
-

**Additional server info**
bungee

**Comment by MylesIsCool** [comment]
ViaVersion doesn't apply to 1.8 versions

**Comment by assasin541** [comment]
@MylesIsCool happened on 1.11

**Comment by MylesIsCool** [comment]
In your report you say client 1.8, if this is wrong you should modify your report and also provide more info like ViaVersion dump. If it happens on 1.8 it's not ViaVersion
