### ISSUE TITLE
Caused by: java.io.IOException: Unable to read type Byte, found Double

### ISSUE THREAD

**Issue by Dot-Rar** [ViaVersion/ViaVersion#1600]
**Describe the bug, provide any errors**
When using 1.8.9 on a 1.15(.0) server with ViaVersion on the BungeeCord proxy, sometimes the player receives a "Disconnected" message and the following stacktrace is dumped into the Bungeecord console: https://hasteb.in/ahijaciz.lua

I am using the following builds of plugins on Bungeecord, as I was told to in the ViaVersion Discord server to allow 1.7-1.15 clients to join:
https://ci.viaversion.com/job/ViaVersion-Abstraction/12/
https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-Abstraction/15/
https://ci.viaversion.com/view/ViaRewind/job/ViaRewind-DEV/60/

**How can we reproduce it?**
1. Run a Bungeecord server with the 3 plugins listed above
2. Run a 1.15(.0?) Spigot server
3. Join the server using Minecraft 1.8.9
4. Play for a while. It doesn't happen instantly, however I can't attribute it to a certain action.

**Expected behaviour**
N/A - The player should not be kicked

**Screenshots**
N/A - The player is just kicked with a message simply saying "Disconnected"

**ViaVersion Dump:**
https://dump.viaversion.com/0df9d75582e35801a9e22b4670cd185f18197b805b1c26c744ecd10812ed4095

**Additional server info**
Latest Bungeecord (not Waterfall) using:
https://ci.viaversion.com/job/ViaVersion-Abstraction/12/
https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-Abstraction/15/
https://ci.viaversion.com/view/ViaRewind/job/ViaRewind-DEV/60/

**Comment by MylesIsCool** [comment]
Please report this on ViaRewind, ViaVersion is only newer versions not older
