### ISSUE TITLE
Error with joining a world with custom skinned player heads

### ISSUE THREAD

**Issue by LeonTG** [ViaVersion/ViaVersion#1602]
**Describe the bug, provide any errors**
I believe this error happens whenever someone joins a world with custom skinned player heads, those who set the skin data of it but is not of an actual player. This started happening as soon as I added those kind of heads to the server spawn.

Here's the logs of someone trying to join on those versions, I tested it on 1.9 and 1.15 myself and I get the same error, same with anyone else that tries to join on a version that isn't the servers main version(1.8)
https://pastebin.com/raw/kR7YVYSB

I tested it out on a server that wasn't on BungeeCore and it worked like intended, I believe ViaVersion is sending a null packet whenever it can't read the head data, and BungeeCore hates null packets which is why it kicks anyone who tries to join in 1.9+

**Screenshots**
This is the kick message I get trying to join on 1.9+
https://cdn.discordapp.com/attachments/632660227900309554/657716475477622815/unknown.png

**ViaVersion Dump:**
https://dump.viaversion.com/b7bc04796093a502b5f3356c3d22d60b23d7fd7554323b12ae96b8d94d7c3252

**Additional server info**
I do use BungeeCore, let me know if there's any other information you need that could help

**Comment by FormallyMyles** [comment]
We've never had anyone able to replicate this, if you're able to replicate with no other plugins with vanilla heads (via the give command) we'll happy reinvestigate.
