### ISSUE TITLE
Item hovers incomplete when using 1.13+ on 1.12.2 server

### ISSUE THREAD

**Issue by PinkLolicorn** [ViaVersion/ViaVersion#1603]
1.13, 1.14, 1.15 clients are unable to see enchantments, item names and probably lore on items in chat.

**How can we reproduce it?**
Send message with BaseComponent#setHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_ITEM, hoverItem)); 

Where `hoverItem` is BaseComponent[]{new TextComponent(json)},
and `json` is from executing NMS ItemStack#save(NBTTagCompound) and then NBTTagCompound#toString

```json
{id:"minecraft:diamond_leggings",Count:1b,tag:{ench:[{lvl:4s,id:0s},{lvl:1s,id:34s}],display:{Name:"§cNogawice §6§lKrola"}},Damage:0s}
```

**Expected behaviour**
ViaVersion should rewrite packet to get valid item representation for higher version.

**Screenshots**
![image](https://user-images.githubusercontent.com/44551064/71312306-84e3c480-2429-11ea-9db5-7f40d116d7f8.png)
![image](https://user-images.githubusercontent.com/44551064/71312309-8f9e5980-2429-11ea-800b-38186666de44.png)

**ViaVersion Dump:**
Yes, `chat-nbt-fix` is enabled.

**Additional server info**
Paper 1.12.2 behind a Waterfall proxy. Using ViaVersion 2.2.2.

**Comment by PinkLolicorn** [comment]
Problem occurs also without proxy on my local test server. Here is a full json dump of BaseComponent[] created using md_5's ComponentSerializer#toString. It is a different item, but problem is present here too.

Formatted
```json
{
   "color":"white",
   "hoverEvent":{
      "action":"show_item",
      "value":[
         {
            "text":"{id:\"minecraft:diamond_pickaxe\",Count:1b,tag:{ench:[{lvl:5s,id:32s}]},Damage:10s}"
         }
      ]
   },
   "text":"Diamond Pickaxe"
}
```

Original
```json
{"color":"white","hoverEvent":{"action":"show_item","value":[{"text":"{id:\"minecraft:diamond_pickaxe\",Count:1b,tag:{ench:[{lvl:5s,id:32s}]},Damage:10s}"}]},"text":"Diamond Pickaxe"}
```

**Comment by disqetow** [comment]
Same problem at my server.

**Comment by LOOHP** [comment]
Same with my plugin, it is most likely due to nbt tags differences between client versions, as the item hover is parsed on the client, the server only provides the JSON
