### ISSUE TITLE
Candestroy oak_log nbt Incompatible in 1.12 via 1.13.

### ISSUE THREAD

**Issue by TNG-China** [ViaVersion/ViaVersion#1604]
Server ver: 1.13
client ver: 1.12

When I get an item has candestroy nbt with oak_log(1.13 material name), But it's can break log in 1.12 and show missingno:
![image](https://user-images.githubusercontent.com/21065884/71320491-15340f00-24e7-11ea-950c-d939c3203303.png)

But in 1.13 is right:
![image](https://user-images.githubusercontent.com/21065884/71320508-44e31700-24e7-11ea-9082-758cf9aca936.png)

Even I add two name: candestroy: log, oak_log, not working.

**Comment by MylesIsCool** [comment]
You need to open this on ViaBackwards issue tracker.

ViaVersion allows newer versions.
