### ISSUE TITLE
old version players slowly float upward

### ISSUE THREAD

**Issue by PhanaticD** [ViaVersion/ViaVersion#1605]
**Describe the bug, provide any errors**
players randomly start floating upwards

**How can we reproduce it?**
its hard to re-produce because it appears randomly, playing a while with a older version on the server. this ONLY started happening after updating to the latest abstraction builds for viaversion/viabackwards and removing protocolsupport, it is not caused by any plugins on my server, as everything worked fine for many months while using protocolsupport. So far it appears to only be happening on servers natively on 1.13.2

**Expected behaviour**
no floating

**Screenshots**
skip to 45 seconds https://www.youtube.com/watch?v=o34ezUEWN2Q
numerous people have reported it randomly happening to them, this one just happened to be recording

**ViaVersion Dump:**
https://dump.viaversion.com/8ffbdf065f618fd5f2fa1e75371e0ca38ab43e4c762ae5c473c64f359ed12574

**Additional server info**
I use travertine, it is a 1.13.2 server with i believe a 1.8 client

**Comment by MylesIsCool** [comment]
If this happens on 1.8 and not 1.9 you should open it on the ViaRewind issue tracker.
