### ISSUE TITLE
Problems with 1.14.4 mobs

### ISSUE THREAD

**Issue by MGlolenstine** [ViaVersion/ViaVersion#1607]
**Describe the bug, provide any errors**
Players are getting kicked when playing on 1.14.4 server with 1.8.9 client on entity spawn.

**How can we reproduce it?**
1. Login on 1.8.9'
2. Wait for Phantoms to spawn
3. There you go, a kick happens with the following error message in the console 
```
MGlolenstine lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: Byte, Source #0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.SpawnPackets$3 (Anonymous), Data: [Pair{Type|VarInt, 3922}], Packet ID: 44}
Actual Error: 
```

**Expected behaviour**
Normaly see the entities and not get kicked

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/baeafd8689c54cfde387a384f8e9849d7e4270d5ee4004973c9896cde1c8e9cc

**Additional server info**
Using Akarin Spigot for 1.14.4
Using velocity as a proxy, with following plugins: bungeequack, luckperms, msessentials, plan

**Comment by MylesIsCool** [comment]
This should be on the ViaRewind issue tracker.

**Comment by MGlolenstine** [comment]
@MylesIsCool why does the error message tell me to report it here?
