### ISSUE TITLE
I cant join to my server with report bug...

### ISSUE THREAD

**Issue by JamesCzBestrunCZ** [ViaVersion/ViaVersion#1608]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?

**How can we reproduce it?**
1. Login on 1.8.9 (All version is breaked)...'
2. Click on '/server SURVIVAL'
3. The '     20:52:53[INFO] MrKubaCZ3 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: String, Source #0: nl.matsv.viabackwards.protocol.protocol1_11_1to1_12.packets.ChatPackets1_12$1 (Anonymous), Data: [], Packet ID: 15}
Actual Error:       ' is displayed wrong

**Expected behaviour**

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
Yes.

**Comment by MylesIsCool** [comment]
You should post this error to ViaBackwards and also enable debug=true in server.properties and recreate to get the full error.
