### ISSUE TITLE
Send real server version to clients

### ISSUE THREAD

**Issue by Earthcomputer** [ViaVersion/ViaVersion#1609]
**Is your feature request related to a problem? Please describe.**
- Reasonably often when I am developing client-side mods, I find out one of my features doesn't work on a different server version than the mod was designed for, with no workaround. Normally, of course, this isn't a problem because players are only supposed to connect to servers on the same version as the mod, but they can also connect to ViaVersion servers. I can't be the only one who's had this problem.
- I am also developing a client-side connection proxy (something similar to ViaVersion but for the client) so that players can connect to servers on different versions even when the server owners won't install ViaVersion. Knowing the server's real version would help improve certain features of this mod, such as increasing the sneak height for 1.13- servers (which ViaVersion can't do without modifying the client). Worse, when the client's version isn't supported, the client doesn't know what version to connect with so the connection is refused anyway. In general, if the client could know the server's real version, it could make better informed decisions about how to connect.

**Describe the solution you'd like**
Ideally, the server should send its real version in a custom key in the JSON in the status response packet [here](https://github.com/ViaVersion/ViaVersion/blob/master/common/src/main/java/us/myles/ViaVersion/protocols/base/BaseProtocol1_7.java#L65). There should be an option to disable it in case server owners don't want clients to know the real server version, but it should be enabled by default to allow more players to benefit from it (up for discussion though).

**Describe alternatives you've considered**
- There already exists a similar opt-in method for clients to be able to tell which protocol versions the server supports, but this is not the same as knowing what version the server is actually on. For example, if the server reports that it supports versions 1.9 through 1.15, is the server actually on 1.9? Or 1.13? Or some other version not in that range at all?
- The server could send its real version when the client version is not supported, and the client version does not match the server version (thus refusing connection to vanilla clients). This is far from the solution I would ideally be looking for, but it would at least solve the problem that my connection mod can't connect to ViaVersion servers not supporting the latest version (currently 1.15.1).

I'd like to hear some feedback for my proposal first, but if people approve of the idea, I'm happy to do the dirty work in a PR :)

**Comment by MylesIsCool** [comment]
Technically you can just send -1 protocol to the server and it'll tell you what version it is (or one it doesn't support), if this doesn't work. I guess you could PR but I would suspect the number of people wanting this is very few, but as long as it's an option we'll merge.

**Comment by Earthcomputer** [comment]
Not sure how I missed that, thanks!
So I guess the scope of this request is now limited to when clients not specifically geared towards protocol stuff can get the server version.

**Comment by FormallyMyles** [comment]
I'm going to close this because using the above -1 is the best solution (that we support), an API would be nice but I suspect it would be sparsely used.
