### ISSUE TITLE
Versiontext option on config.yml

### ISSUE THREAD

**Issue by soshimee** [ViaVersion/ViaVersion#1610]
**Is your feature request related to a problem? Please describe.**

Currently, viaversion doesn't have versiontext option, but other versiontext plugins doesn't work with viaversion.
Players can't figure out what's the versions the server supports with only the default versiontext.

**Describe the solution you'd like**

Making versiontext option to change versiontext on config.yml

**Describe alternatives you've considered**

Somehow changing versiontext with protocollib (even though I don't know how to use it)

**Which versions is this for?**
Does the feature apply to any specific versions? If so put them here.

All

**Comment by Xernium** [comment]
I don’t think that’s up to ViaVersion to do. You can still get that info with a site like https://mcsrvstat.us but I’ll let another project member have the final word here.

**Comment by MylesIsCool** [comment]
Pretty sure any MOTD plugin allows this

**Comment by soshimee** [comment]
MOTD plugins' versiontext isn't compatible with viaversion

**Comment by MylesIsCool** [comment]
I have no idea what you mean, any decent plugin which allows the changing of the text is passed through with ViaVersion.

**Comment by soshimee** [comment]
I tried again but... an error (client-side)
`Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/38 (class_2678) was larger than I expected, found 16 bytes extra whilst reading packet 38`

**Comment by soshimee** [comment]
Probably because the versiontext plugin and viaversion is both trying to send supported versions

**Comment by MylesIsCool** [comment]
That sounds like you just have a bad plugin, ViaVersion doesn't change the text visible to the normal client for that.

**Comment by soshimee** [comment]
I mean, supported protocols

**Comment by MylesIsCool** [comment]
Can you provide more information? I have no idea what you mean

**Comment by PinkLolicorn** [comment]
He means option allowing custom unsupported protocol message in non-bungee environment:
![image](https://user-images.githubusercontent.com/44551064/72234313-a4a37e00-35cc-11ea-962b-a83747911fc9.png)

**Comment by MylesIsCool** [comment]
This is doable with external plugins eg. https://www.curseforge.com/minecraft/bukkit-plugins/serverlistmotd
