### ISSUE TITLE
ViaBackwards activates send() trap on Bungee+Velocity server change

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaVersion#1611]
https://github.com/ViaVersion/ViaVersion/blob/master/bungee/src/main/java/us/myles/ViaVersion/bungee/handlers/BungeeServerHandler.java#L150

Possible reproduction steps:
1.12.2 client, connect to a 1.13.2 subserver which uses bossbar, then connect to a 1.8 subserver

**Comment by FormallyMyles** [comment]
I've added a simple workaround to this issue for mean-time where if it's not 1.8 compatible it won't remove the packet.

Closing for now as this should work for now, but obviously may cause issues with certain bungee versions in the future.
