### ISSUE TITLE
Bug when lightning strikes /smite or any type of lightning they get kicked Everytime 

### ISSUE THREAD

**Issue by FuturePinger** [ViaVersion/ViaVersion#1613]
**Describe the bug, provide any errors**
Connection lost 
Type: Byte, Source #0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.SpawnPackets$ 3 (Anonymous), Data: [pair{Type:VarInt, 63198}], Packet ID: 44}
https://hastebin.com/zecexovagu.php

**How can we reproduce it?**
1. join with 1.18-1.13
2. do /smite on another account
3. you get kicked

**Expected behaviour**
You do /smite and you get kicked they shouldnt get kicked.

**Screenshots**
https://gyazo.com/d0eab96c07869c63c9802b39c5771cda

**ViaVersion Dump:**
https://dump.viaversion.com/3aa292ff85f4a3e0310a5f131ceb2ac5ecfd72826b61ee7a3690e5d687bb9b92

**Additional server info**
Spigot 1.15.1

**Comment by MylesIsCool** [comment]
You should post this to ViaRewind, since the error contains it.
