### ISSUE TITLE
Fences not working on 1.14.4 client connected to 1.12.2 server VV 2.2.2

### ISSUE THREAD

**Issue by MGlolenstine** [ViaVersion/ViaVersion#1614]
**Describe the bug, provide any errors**
Fences don't connect properly when connecting to 1.12.2 server with 1.14.4 client

**How can we reproduce it?**
1. Login on 1.14.4'
2. Connect to 1.12.2 server running viaversion 2.2.2
3. The fences don't connect correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/9406770/71753342-9f368d00-2e82-11ea-93d3-33e6bc059915.png)

**Additional server info**
I'm using Velocity for the proxy. It has few plugins, but none should interact with anything world-render related, as it's only for cross-server travel.

**Comment by MylesIsCool** [comment]
Enable block connections in the config
