### ISSUE TITLE
Shield break bug

### ISSUE THREAD

**Issue by lulu2002** [ViaVersion/ViaVersion#1618]
Server Version: 1.13.2
Viaver Version: 2.2.2

This problem only happens on 1.14 or 1.15 client, after your shield broken by other player, client side still can use it (display problem), so it will cause a player think he is blocking, but actually not.

video: https://youtu.be/Bql46OhJm5Q

**Comment by KennyTV** [comment]
This has been fixed in the 3.0.0 builds, you can either already use them or wait for the Spigot update
