### ISSUE TITLE
1.8 players kicked on Lightning Strike.

### ISSUE THREAD

**Issue by instaaftereffects** [ViaVersion/ViaVersion#1619]
Players on 1.8 are kicked upon lightning strike.

**Describe the bug, provide any errors**
https://hastebin.com/esebehikeq.css
https://hastebin.com/uhopoxoxux.php

**How can we reproduce it?**
1. Login on 1.12'
3. The '....' is displayed wrong

**Expected behaviour**
For players to not be kicked.

**Screenshots**
https://gyazo.com/c2a174a89160193e8db1c10bf6df5e66

**ViaVersion Dump:**
https://dump.viaversion.com/0d5cdab46251c62c0a128735149b6c1b8244cd4ab766d420b7b1df9cdd2d66bf

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Comment by MylesIsCool** [comment]
This is to do with ViaRewind
