### ISSUE TITLE
strikeLightningEffect Method causes older version to be kicked.

### ISSUE THREAD

**Issue by Fundryi** [ViaVersion/ViaVersion#1620]
**Describe the bug, provide any errors**
There are no errors in the console.

**How can we reproduce it?**
1. Login on 1.15.1/1.12.2/1.8.9'
2. Click on 'Check the video.'

**Expected behaviour**
It is just creating a Lightning effect when I Right Click with the Axe.
An example code is shown in video.

**Screenshots**
[VIdeo Link](https://streamable.com/4gcvl)

**ViaVersion Dump:**
[Via Dump](https://dump.viaversion.com/68ca4f8dbcb3ea1a67845d7cec6060550103b19468293214d0945bf098c0bb16)

**Additional server info**
none everything important is showen/in the dump

Regards

**Comment by MylesIsCool** [comment]
This is a ViaRewind bug, please see their issue tracker for progress
