### ISSUE TITLE
ViaVersion Bungee Proxy Throwing Exception on Received Packet

### ISSUE THREAD

**Issue by Qhucy** [ViaVersion/ViaVersion#1622]
On a bungee network on the bungee proxy server, ViaVersion is throwing this error when receiving a packet from a connection: https://hatebin.com/dpywonfgod

I have no idea how you would recreate this issue as it happens randomly with no correlation to why.

**Comment by MylesIsCool** [comment]
This happens when someone sends bad data to the Bungee, I'd suggest using ViaVersion on the backend if this bugs you. Or modifying ViaVersion as we're not able to detect if it was intentionally modified or a protocol change.
