### ISSUE TITLE
downgrade plugin for minecraft 1.5.2 to 1.15.1

### ISSUE THREAD

**Issue by Escanor2019** [ViaVersion/ViaVersion#1623]
what is the most related thing i would need to know to outdate this plugin for minecraft version 1.5.2?
I would like to develop this plugin but I don't know where to start
I would like to keep minecraft updates to older versions for my server.
Could you describe what you are looking for in each update to update?

**Comment by MylesIsCool** [comment]
I don't really understand what you're asking. But you're pretty much on your own for 1.5.2.

**Comment by Escanor2019** [comment]
but what do you look for in updates?

**Comment by Xernium** [comment]
@Escanor2019 let me break this down for you; Each update with ViaVersion adds a converter from the previous one to the new one. To backport this plugin to 1.5.2 would require you to completely rewrite the way ViaVersion injects into the server (the times back then were way different) as well as add converters from 1.5.2 to 1.6, 1.6 to 1.7 and 1.7 to 1.8. Impossible? No. Impractical? 100% yes. It’d take a tremendous amount of time and effort. Ontop of all that it will probably heavily impact server performance. I don’t get why people cling on to such hilariously outdated versions, regardless, here you have your answer.

**Comment by Escanor2019** [comment]
the minecraft client was better and simpler. In this version minecraft had much more players and players. and the plugins didn't have so many version incompatibilities.

In version 1.6 minecraft changed the client and started to change a lot of things.

**Comment by Escanor2019** [comment]
I think the difficulty of upgrading from 1.5 to 1.7 is the same as the difficulty of upgrading from 1.7 to 1.9. or am i wrong?

**Comment by Escanor2019** [comment]
I just wish I had an idea where to start and not end up wasting time learning unnecessary things.

**Comment by KennyTV** [comment]
If you don't know where to start, then you'll certainly not even make the 1.7->1.8 step.
If you don't want to waste your time learning/doing unnecessary things, then don't even think about achieving that 😅

**Comment by Escanor2019** [comment]
protocolsupport has support up to 1.5.

and if i want x1 and i need x2 which is not right with x3 then why do i need to learn x3 to run x1?

**Comment by Xernium** [comment]
@Escanor2019 ProtocolSupport does the polar opposite of ViaVersion. ViaVersion adds support for *newer* versions to an old server. ProtocolSupport adds support for old versions to a server. ViaVersion is also not as deeply woven into a server as to easily allow translation- since it can run from a bungeecord too it’s missing some vital info from the server sometimes. I’m sorry but you won’t get any help from neither us nor the people from ProtocolSupport in your endeavors to port the plugins to a 1.5 server. You complaining doesn’t change that.

**Comment by Escanor2019** [comment]
I'm not complaining, I'm just asking for help creating my own clean plugin
