### ISSUE TITLE
Can't see online players from main menu

### ISSUE THREAD

**Issue by Bublelift** [ViaVersion/ViaVersion#1624]
**Describe the bug, provide any errors**
In multiplayer menu there's shown an error about uncorrect version, although there is no problem to connect the server, the plugin works fine. I just want the server version and players online to be shown also to other people joining server than just the ones using 1.13.2.
![Przechwytywanie](https://user-images.githubusercontent.com/59811046/72229285-a9a50500-35ad-11ea-8021-ce4e6d71926e.JPG)

**How can we reproduce it?**
1. Login on 1.14.4
2. Click on 'Multiplayer'
3. The version and online players are displayed wrong

**Expected behaviour**
I need to know how can I change it, so there will be shown 1.13.2-1.15.1 and online players.

**ViaVersion Dump:**
https://dump.viaversion.com/f3aeaf169c505ae8a6a219ab1dd5ff56d8a8a6e264b45e19a60325ada38620a6

**Additional server info**
Paper 1.13.2
![1](https://user-images.githubusercontent.com/59811046/72229299-ce00e180-35ad-11ea-9a91-dbc2453d9f22.JPG)

**Comment by MylesIsCool** [comment]
If ViaVersion doesn't work you should debug this on our discord / spigot. Otherwise you need an motd plugin to change the version text
