### ISSUE TITLE
[ViaVersion] Received invalid biome id 50

### ISSUE THREAD

**Issue by GameFreakBaree** [ViaVersion/ViaVersion#1628]
**Describe the bug, provide any errors**
ViaVersion keeps spamming "[ViaVersion] Received invalid biome id 50" in the console. I use a custom Worldpainter map but i used it for 2 months and i only received bugs a couple of days ago.

**Screenshots**
/

**ViaVersion Dump:**
https://dump.viaversion.com/263fef0987eb15a42aa21914514ba93124cd2b665e926293d09497434839ab5f

**Additional server info**
- 1.12.2 Spigot
- 5GB RAM
- Latest Stable Viaversions

**Comment by MylesIsCool** [comment]
Biome 50 isn't a valid id, you can suppress conversion errors in the config.yml

**Comment by HowardZHY** [comment]
https://dump.viaversion.com/ba6a4ae4958d2abbce2c69b5fb43bb32299f1f7b0387c6338a05ba0c3db97bee
I had this on my 1.8.8 server too.
This only happen when a certain player join. It dosen't spam but I just wonder what was happening.
