### ISSUE TITLE
Exception on console / NullPointerException

### ISSUE THREAD

**Issue by nikeTion** [ViaVersion/ViaVersion#1632]
Exception: https://prnt.sc/qo9ekd

**ViaVersion Dump:**
https://dump.viaversion.com/8e91fd7a3a34faadbdb3ac18a6c9aabb756005100e6ee2cd9809294c04f2dc2b

**Additional server info**
I use the Travartine fork and a custom spigot for the faction server

**Comment by MylesIsCool** [comment]
Probably your custom fork, it's triggered by ViaRewind. But i'd suspect your server isn't compatible with VV.
