### ISSUE TITLE
Disconnect

### ISSUE THREAD

**Issue by Ninjablader101** [ViaVersion/ViaVersion#1635]
**Describe the bug, provide any errors**
That's my error
https://gist.github.com/Ninjablader101/d7b2fe4dbb9148953f36b5782af47ec8
**How can we reproduce it?**
1. Login on 1.8.9'
2. I got my server version on 1.12.2
3. Teleport to a island (Askyblock is what is use)

**Expected behaviour**
It sends u to the island

**Screenshots**

**ViaVersion Dump:**
- https://dump.viaversion.com/6f8fe3392bca889e5d61325910990660518a83e400d8f05aac79a328573332a2

**Additional server info**
Plugins
![image](https://user-images.githubusercontent.com/52899751/72698350-d8712d00-3b11-11ea-98d6-2f18c4b6a7ca.png)

**Comment by KennyTV** [comment]
Your ViaBackwards is outdated, you can join our Discord for help on the supported/current setup
