### ISSUE TITLE
Cannot load ViaVersion properly on 1.15.1

### ISSUE THREAD

**Issue by IzzelAliz** [ViaVersion/ViaVersion#1636]
**Describe the bug, provide any errors**
```
[00:32:41 INFO]: [ViaVersion] ViaVersion detected server version: 1.15.1(575)
[00:32:41 WARN]: [ViaVersion] ViaVersion does not have any compatible versions for this server version, please read our resource page carefully.
```

**How can we reproduce it?**
1. Download latest paper build(58)
2. Add ViaVersion latest build

**Expected behaviour**
Join with client 1.15

**Screenshots**
None.

**ViaVersion Dump:**
https://dump.viaversion.com/9d83915fbf7b08966161fb32067746bb8189ca1c2551372e7f4f273f85d4e8a2

**Additional server info**
`This server is running Paper version git-Paper-58 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)`

**Comment by MylesIsCool** [comment]
Read the resource page,

ViaVersion doesn't support older versions you need ViaVersion-abstraction, ViaBackwards-abstraction for this.
