### ISSUE TITLE
What is viaversion-abstraction and how can I download it?

### ISSUE THREAD

**Issue by Maratonec** [ViaVersion/ViaVersion#1639]
Hi,
I would like to use via version for my 1.14.4 server to be able join users from 1.13.x clients
On the version compatibility is written with viaversion abstraction and viabackwards abstraction.
I use aternos so can you upload the version on spigot?
And where can I download it?
And what the abstraction versions are?
Thanks

**Comment by MylesIsCool** [comment]
ci.viaversion.com contains the builds, join our discord for further support with these kind of issues.

Abstraction isn't done yet, hence it's not on spigot.

**Comment by Maratonec** [comment]
Thanks for support. I don’t have linked discord account so I cannot write messages l
