### ISSUE TITLE
Internal Exception: io.netty.handler.codec.DecoderException: r: Non[a-z0-9/._-] character in path of location: legacy:mclbrand

### ISSUE THREAD

**Issue by Pangamma** [ViaVersion/ViaVersion#1645]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?
https://hastebin.com/xucarebuco.cs

29.01 06:23:53 [Server] INFO {Type: Float, Source #0: us.myles.ViaVersion.protocols.protocol1_14to1_13_2.packets.WorldPackets$7 (Anonymous), Data: [Pair{Type|Float, 5.6497197E-37}], Packet ID: 28}
29.01 06:23:53 [Server] INFO Actual Error:  @ io.netty.handler.codec.MessageToMessageEncoder:107

**How can we reproduce it?**
1. Waterfall server + Viaversion + Via backwards
1. Login on 1.15.2

**Expected behaviour**
Connect to server. See hub which is currently on 1.13.2. Be able to access other servers as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/1046026/73367668-b0e23900-4264-11ea-8282-3ff2a2e36024.png)

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here. 
(I had to remove via backwards for the time being, so this log would not include that)
https://dump.viaversion.com/ed778fffe6d677e0cc195eb3a1c8da5b86991463743883b667e8fd3b27047fb7

**Additional server info**
Waterfall proxy build https://papermc.io/api/v1/waterfall/1.15/317/download
using ViaVersion 2.3.3 and via backwards

Proxy plugins: 
![image](https://user-images.githubusercontent.com/1046026/73366553-fef63d00-4262-11ea-96a1-a5c086a5a19d.png)

**Comment by FormallyMyles** [comment]
Move ViaVersion from proxy to backend, this happens when the brand gets set by another plugin most likely
