### ISSUE TITLE
Rain issue supposedly fixed on abstraction builds

### ISSUE THREAD

**Issue by johncsuti** [ViaVersion/ViaVersion#1649]
**Describe the bug, provide any errors**
Rain goes through 1 block 

**How can we reproduce it?**
1. Bungee cord has viaversion and viabackwards both abstraction builds 3.0.0-snapshot
2. Login to a 1.15.2 server using 1.15.2 build a roof of planks (didn't test other blocks)
3. Change weather to rain
4. Rain falls through the blocks

**Expected behaviour**
Rain will not go through

**Screenshots**
![2020-02-06_10 21 51](https://user-images.githubusercontent.com/22971404/73951080-081e8400-48cb-11ea-8fae-05fdc35f544d.png)

**ViaVersion Dump:**
https://dump.viaversion.com/fb226a2fb460b2ca9d66298645810022651fa2a56e4ff3df1c6b737471c48c97

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
All information needed is above

**Comment by johncsuti** [comment]
I also get this every time a player joins, could be related?
[10:26:13 WARN] [ViaVersion]: Ignoring plugin channel in outgoing REGISTER: WECUI
[10:26:13 WARN] [ViaVersion]: Ignoring plugin channel in outgoing REGISTER: RedisBungee

**Comment by toxamin** [comment]
"[ViaVersion]: Ignoring plugin channel in outgoing REGISTER: *" showing up in your console has absolutely nothing to do with this.
All abstraction builds have the version 3.0.0-SNAPSHOT.
Try downloading the latest version from https://ci.viaversion.com/job/ViaVersion-Abstraction/ and see if that fixes your issue.

**Comment by KennyTV** [comment]
https://bugs.mojang.com/browse/MC-149791
