### ISSUE TITLE
1.15.1 not compatible with 1.15.2 servers

### ISSUE THREAD

**Issue by R4zzerYT** [ViaVersion/ViaVersion#1651]
**Describe the bug, provide any errors**
My players can't connect with a 1.15.1 minecraft client on 1.15.2 servers.

**How can we reproduce it?**
1. Start Minecraft 1.15.1
2. Create a Server with spigot 1.15.2
3. Try to join the server with 1.15.1

**Expected behaviour**
You should be able to use all 1.15.x versions.

**ViaVersion Dump:**
https://dump.viaversion.com/8083e2a5ccc655014af1c2ef1025a703b0750d47903b8014f3d57c5e5ec813aa

**Additional server info**
BungeeCord - latest version (updatet a few minutes ago)
Lobby-Server with Spigot 1.8.8
and the spigot 1.15.2 server

**Comment by BuzzTheGamer23** [comment]
You need ViaBackwards to join with versions below your server version. ViaVersion lets versions above your server version join.

**Comment by MylesIsCool** [comment]
^^

Look into getting just ViaVersion-Abstraction, ViaBackwards-Abstraction from ci.viaversion.com

**Comment by R4zzerYT** [comment]
When i need this addons, you should edit the viaversion-spigot page.

"Note: ViaVersion only supports newer versions, even on subversions! Use ViaBackwards and ViaRewind to allow older versions to connect. Builds labelled with a dash (eg. -Abstraction, -DEV) are on our build server."
