### ISSUE TITLE
"serverside-blockconnections" when enabled, it blocks 1.13+ clients from joining.

### ISSUE THREAD

**Issue by Timo2157** [ViaVersion/ViaVersion#1655]
**Describe the bug, provide any errors**
Whenever I enable "serverside-blockconnections" in the config It disables 1.13+ clients from joining.

**How can we reproduce it?**
Server Jar: Spigot 1.8.8
Steps to reproduce the behaviour:
1. Enable "serverside-blockconnections" in config.yml
2. Then try to join the server with a 1.13+ client.

**Screenshots**
1.15.2: 
![Screen Shot 2020-02-10 at 10 45 21 PM](https://user-images.githubusercontent.com/55719870/74239025-04ad4300-4ca5-11ea-9ca7-f4779e96fb4b.png)
Console: 
![Screen Shot 2020-02-11 at 8 02 10 AM](https://user-images.githubusercontent.com/55719870/74239035-0aa32400-4ca5-11ea-9632-3fb383a4ef47.png)

**ViaVersion Dump:**
https://dump.viaversion.com/16d9a08bcdd1b5f896715062962c562e9e513f0751d345548efc468af51ce5a8

**Comment by MylesIsCool** [comment]
Can you post the error in your console when you join?

**Comment by Timo2157** [comment]
That is the error
![Screen Shot 2020-02-11 at 8 02 10 AM](https://user-images.githubusercontent.com/55719870/74239389-c2383600-4ca5-11ea-91a1-6423b0177407.png)

**Comment by Timo2157** [comment]
Wait
I can join now?
This doesn't make sense.I will close it.
Thanks for the help.
