### ISSUE TITLE
is possible viaversion for bungecoord?

### ISSUE THREAD

**Issue by Escanor2019** [ViaVersion/ViaVersion#1657]
There are plugins like ProtcoolSupportBungee, is there viaversion protocolsupport?

the legacy.craftlandia.com.br server has 1 viaversion for mc version 1.5.2, were you the ones who created it?

**Comment by Xernium** [comment]
ViaVersion and ProtocolSupport are separate projects. ViaVersion aims to make your outdated server support newer versions while ProtocolSupport allows people with older versions of the game to join the latest server version. That said- There are addons to ViaVersion such as ViaBackwards and ViaRewind which add what ProtocolSupport does to ViaVersion. You can run ViaVersion and it’s addons on any server or bungeecord that is running Minecraft 1.8-1.15.2 whereas ProtocolSupport only runs on the latest server version which is 1.15.2 at this time. With ViaVersion and it’s addons you can get 1.7.2-1.15.2 players to join your server. Running ProtocolSupport on a 1.15.2 server and the ProtocolSupportBungee addon on the bungeecord if you have one will allow 1.4.7-1.15.2 players to join. I hope this answers your question.

**Comment by Xernium** [comment]
Something to note: You CAN combine ViaVersion and ProtocolSupport on a papermc type server. But then again why would you need that ;)

**Comment by Escanor2019** [comment]
craftlandia does not use protocolsupport.
updating minecraft requires updating plugins and fixing possible bugs.
ViaVersion you don't worry about updates, you keep your server stable and forever the same version that attracted so many people.
Craftlandia is the largest server in Brazil, CraftLandia modified several public to private plugins,.
He had an average of 5 to 10 thousand players when the hypixel had 10 to 20 thousand.
Today the server closed and was bought by children who don't understand anything about pvp, and only maintain version 1.5.2 using viaversion.

**Comment by Escanor2019** [comment]
the server ip is legacy.craftlandia.com.br

**Comment by Escanor2019** [comment]
they had mini game servers, hunger games, but today they only have survival 1.5.2-1.15.2

**Comment by Escanor2019** [comment]
servers and pvp and with economy cannot be updated, there have been several item duplication bugs, and data loss that was fixed in 1.5 and that occurred in other versions that were tested.

it doesn’t pay to update the server whenever minecraft decides to add 1 different colored block.

**Comment by Xernium** [comment]
I don’t understand what you want from us. The earliest server/bungee version ViaVersion ever supported was 1.8

**Comment by Escanor2019** [comment]
I just wanted to know if you had it, but forget it, I'm going to buy 1 via version from 1 friend who had contact with the owners of craftlandia.

Paid plugins are more developed, nor is it worth making donations for free plugins.

It is the difference between windows and linux.

**Comment by Xernium** [comment]
Literally- there is no ViaVersion that supports 1.5.2 servers. Whatever they are using is not ViaVersion.

**Comment by Escanor2019** [comment]
enter in the server and type /viaversion.
the server always used viaversion.
they used protocolsupport in the network minigame, but never used it for survival 1.5.2

**Comment by Xernium** [comment]
Yes and no. Their server only needs to support 1.8 for that to work. You can run ViaVersion on the bungeecord for that to work. So you only need a Protocol hack for 1.5.2->1.8

**Comment by Shevchik** [comment]
CraftLandia however does use a thing called ProtocolSupport, that does 1.5.2 - 1.12.2. It has nothing in common with normal ProtocolSuppport tho, besides some basic stuff (I have written that version so i know what i'm saying).

**Comment by Escanor2019** [comment]
it would even be true, I thought that the owner may not have given the modified viaversion.
but for you to play pvp you need to use a modified client from craftlandia anticheat 1.5.2.

**Comment by Escanor2019** [comment]
craftlandia client anticheat 1.5.2 http://download.craftlandia.com.br/craftlandia.zip

**Comment by Escanor2019** [comment]
you can enter the server without anti cheat, however you cannot go pvp

**Comment by Escanor2019** [comment]
this is the craftlandia anticheat: https://dev.bukkit.org/projects/flockclient-server/files

**Comment by Escanor2019** [comment]
flockclient-server is complex, is needed to be 1.5.2

**Comment by Xernium** [comment]
Okay so this is simple. Take a Waterfall or Travertine bungeecord, add an old version of PSBungee, install a 1.12.2 papermc server, install ProtocolSupport (old version for 1.12.2 can be found at https://protocol.support/old ) and add install ViaVersion on it. That will allow you to support 1.4.7-1.15.2

**Comment by Shevchik** [comment]
As i said, CraftLandia did have that special ps version for 1.5.2 - 1.12.2 on the server, and viaversion on bungee (that does transform everything else to 1.12.2).

**Comment by Escanor2019** [comment]
This example of a network minigame is old.

They can't use papermc 1.12 with protocolsupport 1.12 and use anticheat

They had several servers in new versions of minecraft, today they only have 1.5 (500-700 players) and a separate server in 1.8 (100-300 players)
legacy.craftlandia.com.br (1.5.2-1.15.2)
chronus.craftlandia.com.br (1.8-1.15)

**Comment by Escanor2019** [comment]
There is no way to use anticheat flockclient 1.5.2 with protocolsupport in 1.12

**Comment by Shevchik** [comment]
Are you blind? We already said yo you, that the setup they use uses private plugins, that does actually support running on 1.5.2 server.

![ps 1.5.2](https://imgur.com/a/mhXDn11)

**Comment by KennyTV** [comment]
Take Shevchik's as the answer to your initial question, he describes it perfectly well (since the server obviously only supports 1.5-1.12, not 1.15). Else, if you want to pay money for ancient versions of private and unsupported versions, you're on your own.
