### ISSUE TITLE
CraftlandiaProtocolSupport

### ISSUE THREAD

**Issue by Escanor2019** [ViaVersion/ViaVersion#1658]
when do you want for Craftlandia ProtocolSupport?
and how much do you want to update it?

**Comment by Shevchik** [comment]
ViaVersion team has nothing to do with that special ProtocolSupport version. You are basically asking wrong people.

Also if you want to ask the price, you should be asking current CraftLandia owners anyway.

**Comment by Escanor2019** [comment]
but you're on the team, from CraftLandia ProtocolSupport #Shevchik
![image](https://user-images.githubusercontent.com/47899748/74279438-aeb6ba80-4cf9-11ea-8ede-383272b579d8.png)

**Comment by Shevchik** [comment]
However i'm not in ViaVersion team.

**Comment by Escanor2019** [comment]
and how would i get in contact with you?

**Comment by Shevchik** [comment]
You don't. You contant CraftLandia, because all rights for this special version is theirs.

**Comment by Xernium** [comment]
Se você quer a versão que o CraftLandia possui, você precisa falar com o dono do CraftLandia. O Shevchik assinou um contrato que não permite ele vender a versão que ele fez ou fazer versões similares para outros servidores.
