### ISSUE TITLE
Setting elytra flag to false does not work for 1.15 clients

### ISSUE THREAD

**Issue by DankPrison** [ViaVersion/ViaVersion#1659]
EntityToggleGlideEvent does not work properly in minecraft versions joined via ViaVersion.
My server is paper spigot 1.13.2
The code I'm using to test = https://i.imgur.com/lSFVOWJ.png

Results = playing server with 1.15.2 EntityToggleGlideEvent is not working correctly, cancelling the event allows you to have infinite glide...
https://imgur.com/nfO5wqG

playing server with 1.12.2 a version being supported by ProtocolSupport you can clearly see it does not let me glide.
https://imgur.com/LoES6Du

I've tested this with only ViaVersion and this code on server and it's repeatable. Please fix this bug. Thank You.

**Comment by Xernium** [comment]
Does this happen if you run ViaBackwards and ViaRewind instead of PS for old version support?

**Comment by DankPrison** [comment]
@Xernium umm did you miss the part where I said my server is 1.13.2 ? as far as i know neither ViaBackwards and ViaRewind work on 1.13-1.13.2...

**Comment by Xernium** [comment]
That’s news to me ;)    
Check the version diagram on https://www.spigotmc.org/resources/viaversion.19254/ and then you’re welcome to use the links below for the referenced versions.    
ViaVersion-Abstraction: https://ci.viaversion.com/job/ViaVersion-Abstraction/lastSuccessfulBuild/artifact/jar/target/ViaVersion-3.0.0-SNAPSHOT.jar  

ViaBackwards-Abstraction: https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-Abstraction/lastSuccessfulBuild/artifact/all/target/ViaBackwards-3.0.0-SNAPSHOT.jar

ViaRewind-dev: https://ci.viaversion.com/view/ViaRewind/job/ViaRewind-DEV/lastSuccessfulBuild/artifact/all/target/viarewind-all-1.5.0-SNAPSHOT.jar

**Comment by DankPrison** [comment]
@Xernium using those is not going to help me... smh

**Comment by Xernium** [comment]
My bad I missed the part you stated you tried this with only VV. I’ll get a look at it later on

**Comment by Xernium** [comment]
^ for context; since ViaVersion uses the PS injection when it’s present- I’ve seen a few issues arise there from time to time

**Comment by DankPrison** [comment]
@Xernium Tested with ViaVersion-Dev 3.0.0 Instead of it allowing you to glide around you now get infinite elytra flight with no movement speed but your still stuck permenantly gliding. It's clearly an issue that needs to be addressed https://i.imgur.com/jmKJDyC.png

**Comment by Xernium** [comment]
Could you do me a favor and see what actually happens? As in stand besides the event with a second game client open on 1.13.2. I want to see if it a actually makes the client stuck in this state or if it’s only for the 1.15.2 client side

**Comment by DankPrison** [comment]
@Xernium When you view the person stuck in perm elytra from another client they are standing normally.

**Comment by DankPrison** [comment]
@Xernium https://imgur.com/6O4J0jL

**Comment by Xernium** [comment]
Thanks! I assume there is a packet we are missing the right translation to end the flight/ we don’t have it correctly sent. The team/ me will take care of it.

**Comment by DankPrison** [comment]
Thank You!

**Comment by JHarris12345** [comment]
so was this fixed?

**Comment by DankPrison** [comment]
@JHarris12345 According to their commits on github not yet.

**Comment by bartyrealms** [comment]
Has this been resolved yet? The glide: deny flag does not seem to work at all with ViaVersion installed on the server.

**Comment by DankPrison** [comment]
@bartyrealms nope, doubt it's going to get fixed. I ended up just denying anyone in 1.15+ from PvP at this point. Here's a helpful snippet.
int version = ViaVersion.getInstance().getPlayerVersion(player.getUniqueId());
        if (version >= 573){
            cs.sendMessage("1.15+ is not allowed");
            return true;
        }

**Comment by KennyTV** [comment]
@DankPrison your code needs to check whether gliding is enabled - replace your if statement with
`if (event.isGliding() && PVPAPI.hasPvPTimer(player.getUniqueId()) {` since this event might actually fire when Spigot tries to disable the flight after a specific point of the toggle, and will then cancel the disable of the glide (even though they never actually glided)

**Comment by DankPrison** [comment]
@KennyTV That doesn't work in 1.15+ clients... The whole reason this is marked as a bug by the developer. Please Read before inputting useless info. You cannot cancel on glide event for 1.15+ clients it makes them glide infinitely.

**Comment by Xernium** [comment]
... You do realise that you are talking to the same project member that marked the issue as a verified known bug right?

**Comment by DankPrison** [comment]
@Xernium Nope, did not notice that lol... Seems like he doesn't care about getting it fixed anyways. Don't even know why I'm wasting time here.

**Comment by KennyTV** [comment]
I do in fact know how to fix this, but your responses don't really motivate me to do so. This will be fixed shortly, but you need to stop acting entitled/sassy if you want people to help you

**Comment by DankPrison** [comment]
I submitted this bug over 2 months ago... I've been patiently waiting. Apparently being entitles/sassy is what I needed to do to bring this issue to your attention?? Seems so
