### ISSUE TITLE
Incompatibility with world guard extra flags

### ISSUE THREAD

**Issue by JHarris12345** [ViaVersion/ViaVersion#1660]
**Describe the bug, provide any errors**
If you set a region to glide: deny (disable elytra flight) on a 1.14.4 server with the plugin worldguard extra flags, people in a 1.15 client can still elytra fly. To people not on 1.15 it will look like they are normal flying. They shouldnt be able to fly with elytra

**How can we reproduce it?**
1. 1.14.4 spigot server
2. Install worldguard extra flags
3. Set glide flag to deny
4. You can still elytra on 1.15 client

**ViaVersion Dump:**
https://dump.viaversion.com/60fd32614189bae8b557d82be6584edab718b6b5b252d91fa3e36f646f8f5c77

**Additional server info**
We do use bungee.

**Comment by KennyTV** [comment]
#1659
