### ISSUE TITLE
Outdated Server Message after ViaVersion install

### ISSUE THREAD

**Issue by Finnlife** [ViaVersion/ViaVersion#1663]
I cant join on my 1.14.4 CityBuild Server.
We installed the same Pluginversions on each Server.
We can you on the Lobby and on each other Server but cant join the CityBuild.
Its a Flamecord Network and we have the jar on each Server (inc. the Bungee)

Did anyone of you know if there is an known Plugin, tha causes the Error?

Screen of the Plugins:
http://prntscr.com/r3m9yw

ViaDump: https://dump.viaversion.com/9ec37997cb75a22b119db089cd8d6d2baeddafd8ad82b452bc5cb7809be06ca4

**Comment by MylesIsCool** [comment]
Flamecord isn't supported. More so ViaVersion can't get the right protocol id to work properly.

**Comment by MylesIsCool** [comment]
My suggestion would be to install ViaVersion on your backend server and not on Bungee

**Comment by Finnlife** [comment]
Same Error with Bungeecord.
And same Error, if i only install it on the Spigot/Paperspigot Servers.

**Comment by MylesIsCool** [comment]
Then you're either not using the right plugins or doing something very wrong. ViaVersion supports NEWER versions, eg. 1.12 on 1.8 server, 1.15 on 1.14 server.

**Comment by Finnlife** [comment]
Yeah i know that...
We using the 1.14.4 Server and trying it with a 1.15.2 Client.
I posted a Screenshot of the Plugins in the Issue....So idk what could be wrong...

**Comment by MylesIsCool** [comment]
Have you updated your Bungee?

**Comment by Finnlife** [comment]
Yes i have the last Version from https://ci.md-5.net/job/BungeeCord/

**Comment by MylesIsCool** [comment]
I'd suggest joining our discord for further help. Otherwise create a basic server setup with ViaVersion only on backend with Bungee and it'll work.

**Comment by Finnlife** [comment]
I found the Issue....It was ProtocolSupport
After uninstalling it, it works fine....
