### ISSUE TITLE
Bug with block placing in 1.8.8 server

### ISSUE THREAD

**Issue by MaxWgamer** [ViaVersion/ViaVersion#1665]
**Describe the bug, provide any errors**
The bug means that we can place blocks on us on versions 1.9 and +

**How can we reproduce it?**
With versions 1.9 or + trying to place blocks in front of us

**Screenshots**
https://youtu.be/iKg9crNvA-o

**ViaVersion Dump:**
https://dump.viaversion.com/d67149f16e2314f3fdeeccebd55ce4546d8809a8da19ef9ce9445e2d32c7962e

**Additional server info**
I use Waterfall and PaperSpigot 1.8.8 (It's my plugin)

PS : Sorry for my english I'm french.

**Comment by MaxWgamer** [comment]
I just retested with 1.9.4 and the bug is even more visible.

**Comment by MylesIsCool** [comment]
This is due to a bug in 1.8 paper, we attempt to fix it but it's not perfect.

**Comment by MaxWgamer** [comment]
Can you please send me where the error is in paper's code ? I will like to try to fix it myself.

**Comment by FormallyMyles** [comment]
#1098

**Comment by ArbETaperingsky** [comment]
What happened?

此致，
ArbETaperingsky

________________________________

**Comment by MaxWgamer** [comment]
It's good, I have fixed the problem, as I can remove the "Enabling Paper/TacoSpigot/Torch patch: Fixes block placement."
