### ISSUE TITLE
Bug in handling world data while player is joining server

### ISSUE THREAD

**Issue by userMacieG** [ViaVersion/ViaVersion#1668]
**Describe the bug, provide any errors**
Players cannot join server. 
Plugin broke somehow `Bukkit.getWorld()` function.
How error looks: https://hastebin.com/adimanecok.cs

**How can we reproduce it?**
1. Install Paper (1.15.2 or 1.14.4) and any client version (I tested this on 1.8.9, 1.14.4 and 1.15.2)
2. Install `ViaVersion-3.0.0-SNAPSHOT`, `ViaBackwards-3.0.0-SNAPSHOT` and `viarewind-all-1.5.0-SNAPSHOT`
3. Create plugin with this event:
```java
@EventHandler
public void onJoin(PlayerJoinEvent event) {
    final Player player = event.getPlayer();
    player.teleportAsync(new Location(Bukkit.getWorld().get(0), 0.0, 100.0, 0.0));
}
```
4. Try join server

**Expected behaviour**
Allow player to join server.

**Screenshots**
![image](https://user-images.githubusercontent.com/24211405/75813573-7eaa8680-5d90-11ea-912f-a72ecb3131e8.png)

**ViaVersion Dump:**
- Not possible to type command because of bug

**Additional server info**
Newest Waterfall
ViaVersion only on main server (on proxy via creating another error with handling a text from btlp)

**Comment by MylesIsCool** [comment]
ViaVersion doesn't modify packets for your server version. This will be something else on your server. Or an incompatibility with doing the teleport async / on join
