### ISSUE TITLE
Xray Patch not updating

### ISSUE THREAD

**Issue by LoXR** [ViaVersion/ViaVersion#1670]
**Describe the bug, provide any errors**
When having the Xray patch on for my 1.8.8 server, im on engine mode 2 for the anti-xray, even though through a hacked client testing to see what the xray looks like, when normal players are mining the random blocks will appear like the engine mode 2. But you are needing to right click to fix the ores.

**How can we reproduce it?**
1. Spigot or TacoSpigot 1.8.8 (unsure if any difference)'
2. Anti-Xray engine 2
3. Xray Patch: true

**Expected behaviour**
To be like the latest papers anti-xray and update to the actual visual for legit players.

**Screenshots**
Photo: http://prnt.sc/rct7vp
Photo 2: http://prnt.sc/rct9f3

**ViaVersion Dump:**
- https://dump.viaversion.com/f54a810173e777daba3f932824be65eb3e647fd728617915756274042f4d33be.

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
I do have the server behind a proxy, but it seemed the anti-xray patch didnt work behind the proxy, so needed to disable the server on the proxy and have it on the standalone server for the anti-xray to work.

**Comment by LoXR** [comment]
And thinking these: https://hastebin.com/folerubowi.css
Has something to do with this: https://hastebin.com/ipavelonun.coffeescript
Some players have reported they get kicked while trying to use the crafting table.
Their client versions vary.

**Comment by FormallyMyles** [comment]
Would you be able to repastebin these errors as the links no longer work?

+

Which versions does this issue happen on?

**Comment by LoXR** [comment]
Ah I see, and it occured on CannonSpigot 1.8.8, with engine mode 2.
