### ISSUE TITLE
why the viaversion src on github is updated randomly?

### ISSUE THREAD

**Issue by marinaluisa2020** [ViaVersion/ViaVersion#1672]
there are referenced files that don't exist.

look
![image](https://user-images.githubusercontent.com/61571165/76171738-6a3e0380-616d-11ea-9150-f281e2779774.png)

in dir
![image](https://user-images.githubusercontent.com/61571165/76171742-76c25c00-616d-11ea-8718-cd2bf288b067.png)

all branchs are how this

**Comment by krusic22** [comment]
You should look at: ViaVersion/common/src/main/java/us/myles/ViaVersion/api/
