### ISSUE TITLE
Can place blocks directly below you on 1.8 server

### ISSUE THREAD

**Issue by JHarris12345** [ViaVersion/ViaVersion#1673]
**Describe the bug, provide any errors**
If you join a 1.8 server in a higher version, then you can place a block directly on the block you are standing on and it will glitch you off. A lot of the time this is dangerous when mining as you just glitch yourself into a block by placing it on the block you are on

**How can we reproduce it?**
1. Login on 1.14 to a 1.8 server'
2. Place a block on the block you are standing on without jumping
3. It places and you glitch

**Expected behaviour**
You shouldnt glitch

**ViaVersion Dump:**
https://dump.viaversion.com/71efbe2d614606e7aafa3975c35cb9d056abd2647581b6bd3cec3fcb2efb700b

**Comment by MylesIsCool** [comment]
See response on discord.

**Comment by JHarris12345** [comment]
The server loads as taco spigot [server.jar:git-TacoSpigot-04511af6]

Yet it still has the glitch

**Comment by JHarris12345** [comment]
Even so, I would greatly appreciate your just adding a new line to make it load with the jar of "Stellar" because then I wouldnt have to fork it every time you guys update and I dont have ANY experience with forking plugins
