### ISSUE TITLE
Registry remapping failed:Received ID map for minecraft:sound_event contains IDs unknown to the receiver! 

### ISSUE THREAD

**Issue by KawaiiTamako** [ViaVersion/ViaVersion#1675]
1.14.4 fabric client join 1.15.2 fabric server with viaversions
plz! fix it
![76233466-32b18300-6263-11ea-901a-a5c68b74bcf8](https://user-images.githubusercontent.com/51044119/76400333-188ab880-63bb-11ea-9d6f-8273793d0d64.png)

**Comment by KennyTV** [comment]
Looks like a mod's doing - you also lack any client/server info for us to figure out more than that

**Comment by KawaiiTamako** [comment]
> Looks like a mod's doing - you also lack any client/server info for us to figure out more than that

1.14.4 fabric client join 1.15.2 fabric server. Delete the fabric-api of the 1.15.2 server to join.

**Comment by creeper123123321** [comment]
Related to #747

**Comment by creeper123123321** [comment]
You can workaround by removing fabric-registry-sync mod

**Comment by NeedNot** [comment]
> You can workaround by removing fabric-registry-sync mod from the server

How do I do that?
