### ISSUE TITLE
protocol block with viaversion 3.0.0

### ISSUE THREAD

**Issue by MonkeyBrize** [ViaVersion/ViaVersion#1678]
https://dump.viaversion.com/8da0bfddebed1f571776ce578e4ec3a92fd8b3adc008179f6f90c61cabed3d33

i'm using paper 1.15.2 and i tried to use protocol block for access only version 1.14-1.15.2 on my server but i doesn't work. I don't know why
- viaversion 3.0.0
already try with viabackward 3.0.0 and without viabackward 3.0.0 but the block protocol doen't work

**Comment by krusic22** [comment]
Remove ProtocolSupport.

**Comment by MylesIsCool** [comment]
^^
