### ISSUE TITLE
Chat Message (possibly too long) after translated to older versions kicks the client

### ISSUE THREAD

**Issue by LOOHP** [ViaVersion/ViaVersion#1681]
**Describe the bug, provide any errors**
I am using a plugin that converts [item] or [inv] to hover and clickable messages in chat, but if I replace the placeholder for let's say 50 times, 1.12.2 clients on 1.15.2 server gets kicked while 1.15.2 clients receive the message just fine. 

Error message when kicked: 
lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: String, Source #1: nl.matsv.viabackwards.api.rewriters.TranslatableRewriter$3 (Anonymous), Source #0: nl.matsv.viabackwards.api.rewriters.TranslatableRewriter$3$$Lambda$3297/585747302, Data: [], Packet ID: 14}
Actual Error:

**How can we reproduce it?**
1. Start a 1.15.2 spigot/paper server
2. Login on 1.12.2 (or with another account on 1.15.2)
3. Use an chat message plugin that adds hover and click events through modifying chat packets, in my case, [this one](https://www.spigotmc.org/resources/interactivechat-custom-keywords-display-items-and-inventories-in-chat-supports-custom-languages.75870/)
4. Spam 50 [item] placeholder in one chat message and send it
5. 1.12.2 client gets kicked, 1.15.2 client receives message just fine

**Expected behaviour**
The message with lots of [item] delivered to clients of all version as normal

**ViaVersion Dump:**
https://dump.viaversion.com/ed2772e98c1061e613dd642a84a6aaa29ec4de7e00c526f8aefb7daf78c7c065

**Additional server info**
No bungee/waterfall. Only on a 1.15.2 paper server

**Comment by KennyTV** [comment]
Can you set debug to true in your server.properties and recreate the error?

**Comment by FormallyMyles** [comment]
Going to need more info / this might need reporting on ViaBackwards :) 

Closing otherwise, we'll happily look if you can provide the error.
