### ISSUE TITLE
1.16 Early support?

### ISSUE THREAD

**Issue by iRayanKhan** [ViaVersion/ViaVersion#1682]
Hi here, sorry if this is obvious, but is there a 1.16 branch? 
I have a 1.15.2 Spigot/Bungeecord server and want to add 1.16 Anarchy. Would I have to just allow them to directly connect to that port, or is there a dev branch with 1.16 support?

Thanks!

**Comment by KennyTV** [comment]
Yep, the abstraction branch builds support clients using the latest snapshot (currently 20w12a). You can download them from https://ci.viaversion.com/job/ViaVersion-Abstraction/

**Comment by iRayanKhan** [comment]
Thank you so much!

**Comment by iRayanKhan** [comment]
One last question sorry if you don't know the answer since it's unrelated, but where can I find (if it exists), 1.16 spigot snapshots? I may just do pure vanilla tbh.

**Comment by KennyTV** [comment]
Spigot usually does not publish its source until the full release hits, so no

**Comment by Xernium** [comment]
@iRayanKhan For Bungeecord you also need a 1.16 compatible version- You can find my 1.16-Snapshot supported Travertine fork at https://github.com/Xernium/Travertine and ready-to-use builds at https://jenkins.krusic22.com/job/Travertine-Xernium/ ... as for Spigot stay tuned. Might be releasing a hacked-up snapshot compatible version soon

**Comment by Xernium** [comment]
*Keep in mind that this is the bleeding edge of bleeding edges so expect some issues to arise along the way*
