### ISSUE TITLE
Hologram patch wont work

### ISSUE THREAD

**Issue by JHarris12345** [ViaVersion/ViaVersion#1684]
**Describe the bug, provide any errors**
On all my server versions (1.15.2 and 1.8) the hologram patch does nothing for 1.8 clients despite changing the Y offset. In 1.8, holograms appear a couple blocks higher than they should be. I have even gone to lengths of making the offset -4.

**How can we reproduce it?**
1. Login on 1.9+
2. Create a hologram
3. Login on 1.8, the hologram is lower

**Expected behaviour**
Holograms should be at the same height

**ViaVersion Dump:**
https://dump.viaversion.com/74335738c18d2bb24dbb6e936ee88d8bae046dc89d50a3d80eabd9848ae4d21b

**Comment by MylesIsCool** [comment]
This issue should be opened on ViaRewind as ViaVersion doesn't control the packets for 1.8

**Comment by JHarris12345** [comment]
Can I ask how its related to via rewind if one of the servers it doesnt work on is a 1.8 server too?

**Comment by MylesIsCool** [comment]
It only modifies holograms in certain circumstances as the offset was modified multiple times. 
It's not clean detecting holograms so obviously might depend on the hologram plugin you use.
In the issue you stated you're using a 1.15.2 server, which only ViaRewind can modify.

**Comment by JHarris12345** [comment]
In the issue I stated I use both 1.15 and 1.8 though. Is there a way to fix this (I did post in VR github too). I use holographic displays and have seen other servers with the plugin get round the patch so was thinking I could too

**Comment by MylesIsCool** [comment]
"On all my server versions (1.15.2 and 1.8) the hologram patch does nothing for 1.8 clients"

ViaVersion doesn't do anything on 1.8, it would be 1.9 that changes. You'll need to post screenshots and the actual dump for your server if you want this checked out.

**Comment by JHarris12345** [comment]
Ok so here is the image of a hologram made with Holographic displays on a 1.14.4 client with the server versions 1.15.2 (latest paper jar). Notice the hologram height
![image](https://user-images.githubusercontent.com/46936647/77229089-9a30d200-6b83-11ea-9b20-0c39e5642a27.png)

Here is the same image but taken on a 1.8 client
![image](https://user-images.githubusercontent.com/46936647/77229125-c9474380-6b83-11ea-9cb8-72288e6fe517.png)


Dump:
https://dump.viaversion.com/11809c5cec1c6fd9be13b2c7de1d6d1e3d5bea2996fa47e4dda52f92388bc948

**Comment by MylesIsCool** [comment]
Again, this is only relevant to ViaVersion when on 1.8 server. Feel free to attach this to your ViaRewind issue

**Comment by JHarris12345** [comment]
Ok sure let me quickly do it on the 1.8 server

**Comment by JHarris12345** [comment]
Server version: 1.8.8

Here is the holograms taken on a 1.14.4 client:
![image](https://user-images.githubusercontent.com/46936647/77229171-3955c980-6b84-11ea-87f8-06a79dd8ea8c.png)


Here is the same image on a 1.8 client:
![image](https://user-images.githubusercontent.com/46936647/77229181-4377c800-6b84-11ea-9dc2-9652c1103512.png)


VV Dump:
https://dump.viaversion.com/afcf668c2144ad699e64407e2115cf79f364b6e126dbbe72d55f95515f7e4b4f

**Comment by MylesIsCool** [comment]
Would you also be able to provide a screenshot from 1.9? and maybe 1.11 (if you have the time)? As those are the versions where the height changed.

**Comment by JHarris12345** [comment]
Sure 2 secs

**Comment by JHarris12345** [comment]
Client 1.9 (server version 1.8.8). It seems the hologram patch works here but its a bit of a durastic Y level drop for just -0.96 value no?
![image](https://user-images.githubusercontent.com/46936647/77229415-b9c8fa00-6b85-11ea-8aff-ba5a0102e8f6.png)

In 1.11 the holograms are at the correct height we see in 1.14+:
![image](https://user-images.githubusercontent.com/46936647/77229431-d06f5100-6b85-11ea-9689-ca5790b0a17c.png)

**Comment by JHarris12345** [comment]
Actually the 1.9 client seems like it did move down -0.96 blocks (fair enough) but it also appears that it didnt need to be moved down? If it wasnt moved down 0.96, it would be correct

**Comment by toxamin** [comment]
Minecraft client version 1.8.0 does not support marker armor stands. In minecraft client version <1.9, marker armor stands are positioned lower than >=1.9.

**Comment by JHarris12345** [comment]
That doesnt really solve my issue though. In 1.9 they appear too low and 1.8 they appear high

**Comment by toxamin** [comment]
Don't use marker armor stands then?

**Comment by JHarris12345** [comment]
How do I do that. Ive seen other plugins use holographics displays and no issues

**Comment by toxamin** [comment]
You don't use holographic displays. It even says on the plugin's page it might not be compatible with protocol hack plugins...

**Comment by JHarris12345** [comment]
So what plugin is comptabile?

**Comment by JHarris12345** [comment]
And can ViaVersion not solve this issue in a new patch or something @MylesIsCool ?

**Comment by JHarris12345** [comment]
@toxamin Tested other holograms plugin and they all use armor stands yet many servers have this issue fixed. So not sure what to do here. Can VV not create a patch to make holograms lower on armor stands?

**Comment by ZombieAssassin** [comment]
I am also having this issue, 1.8 holograms are offset roughly 1 block above all other client protocols, no matter how much fiddling I've done with the hologram offset.

Using server version tacospigot 1.8.8.
Latest via version, latest 1.8 compatible holographic displays.

**Comment by JHarris12345** [comment]
NOTE: On 1.8.8 clients there is no issue. It is just 1.8

**Comment by toxamin** [comment]
What do you not understand about marker armor stands not existing in 1.8.0?

**Comment by JHarris12345** [comment]
What do you not understand by if other massive networks dont have this issue whilst using holographic displays, then there is a solution?

**Comment by toxamin** [comment]
It's not ViaVersion's problem, stop whining already.

**Comment by JHarris12345** [comment]
So why hasnt this been closed. Clearly an issue if other servers manage to get it to work. Seems like you just cant be bothered to come up with a legit argument

**Comment by KennyTV** [comment]
1.8.1 added marker armorstands to have less interaction ticking, also giving the armor stand a tiny hitbox, resulting in that shift for 1.8 clients (since they display normal sized armor stands). There is no fix for this, other than to tell your 1.8.0 players to at least use a less outdated version of the outdated versions.

**Comment by JHarris12345** [comment]
I want to re-open this because as time goes on I see more and more servers having correctly positioned holograms for 1.8 clients. Whereas on my server, with the hologram patch, 1.8 clients have badly positioned holograms. How are other servers doing this then if there is apparently no way for VV to fix this?

**Comment by KennyTV** [comment]
Then they don't use marker holograms, as already explained.

**Comment by JHarris12345** [comment]
Ive used every holograms plugin and they all use marker holograms. So what plugin wouldnt?
