### ISSUE TITLE
Java 1.13 Support

### ISSUE THREAD

**Issue by Tanju42** [ViaVersion/ViaVersion#1686]
**Describe the bug, provide any errors**
On Java 1.13 when a Player Joins a Error message appears
**How can we reproduce it?**
1. Run Debian
2. Install Java 1.13 64bit
3. Use spigot 1.8
4. Put in ViaVersion
5. Start everything
6. Join viola there is the bug

**Expected behaviour**
That it should work I guess?

**Screenshots**
Latest.log: https://pastebin.com/Y8ehDESw (Same thing happens when I dont reload)

**ViaVersion Dump:**
I tryed it but the error gets spammed every tick.

**Additional server info**
Latest Waterfall:
 This server is running Waterfall version git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326 by md_5
Spigot 1.8.8

**Comment by krusic22** [comment]
Set use-native-transport=false in server.properties.

**Comment by Tanju42** [comment]
Thankx worked perfectly fine!
