### ISSUE TITLE
Error change server with css.

### ISSUE THREAD

**Issue by colo13verdadeo** [ViaVersion/ViaVersion#1693]
**Describe the bug, provide any errors**
Console: 
Internal Exception: java.io.IOException: An established connection was aborted by the software in your host machine

**How can we reproduce it?**
1. Login on 1.12 and teleport server 1.8'
2. Click on 'npc teleport'
3. Kicked with is displayed wrong

**Expected behaviour**

**Screenshots**
https://cdn.discordapp.com/attachments/666367422307106827/692784047348514956/unknown.png

**ViaVersion Dump:**
Spigot: https://pastebin.com/tNdHD34M
Waterfall: https://pastebin.com/90DBDn1j

**Additional server info**
plugins spigot:
https://media.discordapp.net/attachments/666367422307106827/692784222926274590/unknown.png

Only spigot skywars. (because survival spigot normaly)

**Comment by KennyTV** [comment]
ViaBackwards 2.4.0 is outdated, its latest build are from the abstraction branch. Also, don't run Via on both Bungee and Paper, only on either one (backend servers preferred)

**Comment by colo13verdadeo** [comment]
How i can download viabackward lastversion? In spigot is 2.4.0.

**Comment by KennyTV** [comment]
https://ci.viaversion.com/job/ViaVersion-Abstraction/
https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-Abstraction/
(and if you need it, https://ci.viaversion.com/view/ViaRewind/job/ViaRewind-DEV/)

**Comment by colo13verdadeo** [comment]
Is it better in bungee or spigot?

**Comment by colo13verdadeo** [comment]
https://media.discordapp.net/attachments/666367422307106827/692802154351820861/unknown.png?width=1442&height=232

https://media.discordapp.net/attachments/666367422307106827/692802221447839824/unknown.png

I have the same problem.
