### ISSUE TITLE
Bug 1.12.2 in 1.8 css

### ISSUE THREAD

**Issue by colo13verdadeo** [ViaVersion/ViaVersion#1694]
Describe the bug, provide any errors
Console:
Internal Exception: java.io.IOException: An established connection was aborted by the software in your host machine

How can we reproduce it?

Login on 1.12 and teleport server 1.8'
Click on 'npc teleport'
Kicked with is displayed wrong
Expected behaviour

**Screenshots**
https://media.discordapp.net/attachments/666367422307106827/692802154351820861/unknown.png?width=1442&height=232

https://media.discordapp.net/attachments/666367422307106827/692802221447839824/unknown.png

**ViaVersion Dump:**
https://pastebin.com/iLPjELEu

**Additional server info error console**
https://pastebin.com/HfB0spXe

**Comment by KennyTV** [comment]
Known bug (https://github.com/ViaVersion/ViaVersion/issues/1611), you can workaround this by using Via on your Paper servers
