### ISSUE TITLE
Disconnected error

### ISSUE THREAD

**Issue by ItsyaboiDanny0** [ViaVersion/ViaVersion#1695]
When I try to join my server I get this error:

> 27.03 16:46:07 [Disconnect] User Zylocks has disconnected, reason: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
27.03 16:46:07 [Server] INFO {Type: MetaData List, Source #0: nl.matsv.viabackwards.protocol.protocol1_11_1to1_12.packets.EntityPackets1_12$3 (Anonymous), Data: [Pair{Type|VarInt, 2147483647}, Pair{Type|UUID, ff84203e-949a-4849-a7fb-52fe07dfe33c}, Pair{Type|Double, 0.0}, Pair{Type|Double, 100.0}, Pair{Type|Double, 0.0}, Pair{Type|Byte, 0}, Pair{Type|Byte, 0}], Packet ID: 5}
27.03 16:46:07 [Server] INFO Actual Error:

**Comment by KennyTV** [comment]
This seems to be a ViaBackwards error. Also, we can't help you if you don't follow the issue template
