### ISSUE TITLE
Kick for doing /region info

### ISSUE THREAD

**Issue by JHarris12345** [ViaVersion/ViaVersion#1696]
**Describe the bug, provide any errors**
When I do /region info on only ONE of my regions (it might be due to someones name who knows), it kicks me with a message screenshotted below

**How can we reproduce it?**
1. Honestly no clue, I can send the region config info so you can recreate it if you want

**Expected behaviour**
I should see worldguard region info

**Screenshots**
![image](https://user-images.githubusercontent.com/46936647/77831035-902f4600-7124-11ea-9f7d-2caba8dacb54.png)

**ViaVersion Dump:**
https://dump.viaversion.com/c63a4f8a954866ae73c541ec9a838631490bd23a6333baa8b565101b5f80e84d

**Comment by KennyTV** [comment]
Set debug=true in your server properties and send the full error printed in your console

**Comment by JHarris12345** [comment]
![image](https://user-images.githubusercontent.com/46936647/77831210-b6a1b100-7125-11ea-8e6b-004b72dfb414.png)

**Comment by KennyTV** [comment]
You cut off part of the error. Paste the entire thing with https://paste.gg/

**Comment by JHarris12345** [comment]
Accidetnally deleted latest.log. Is there a way to get it back without restart?

**Comment by JHarris12345** [comment]
![image](https://user-images.githubusercontent.com/46936647/77831492-6a577080-7127-11ea-8448-f6b2bb895042.png)

**Comment by KennyTV** [comment]
... That would be a string with more than 40.000 characters 🤔

**Comment by JHarris12345** [comment]
Its just a load of UUIDs that are added to a region... Ill send it here https://pastebin.com/xmWBUQWg

**Comment by KennyTV** [comment]
How does it look when you use the command with a 1.15.2 client?

**Comment by JHarris12345** [comment]
I can use the command fine on a 1.15.2 client
