### ISSUE TITLE
Error while connection with 1.15.2

### ISSUE THREAD

**Issue by charvyCZ** [ViaVersion/ViaVersion#1697]
When i connect to server, i got kicked with this message: https://pastebin.com/xMm0bcvE

**How can we reproduce it?**
1. Login on 1.15.2
2. do some jumps and other
3. kick with error msg

**Expected behaviour**
it shouldn't kick me

**Screenshots**
https://pastebin.com/xMm0bcvE

**ViaVersion Dump:**
https://dump.viaversion.com/4b569adc9275cb1286a03da3cfd3b0ca412dc29ba9f17c2c3de3fa8be853950f

**Additional server info**
Bungee

**Comment by KennyTV** [comment]
Please set debug=true in your server.properties file and recreate the error

**Comment by charvyCZ** [comment]
Ok, https://pastebin.com/cLkhVfYn

**Comment by KennyTV** [comment]
Sorry for the big delay - I would suspect faulty region data / FAWE. Does this happen for any 1.15 player logging in at any place?

**Comment by charvyCZ** [comment]
No, only at main spawn

**Comment by KennyTV** [comment]
Did you happen to use FAWE to edit the chunks there? 👀

**Comment by FormallyMyles** [comment]
Gonna close, gonna assume what Kenny said above.
