### ISSUE TITLE
How i can limit versions?

### ISSUE THREAD

**Issue by colo13verdadeo** [ViaVersion/ViaVersion#1698]
How i can limit versions join on a server, and other server, limit others versions?

ViaVersion Version: 3.0.0
ViaBackWard: 3.0.0
Viaallrewind: 1.5.0

**Comment by MylesIsCool** [comment]
block-protocols in the config. I'd suggest using discord / spigot for this kind of query.

**Comment by colo13verdadeo** [comment]
I cant block an server, because show it: 
https://cdn.discordapp.com/attachments/683513892303011930/694236833495646208/Captura_de_pantalla_471.png
