### ISSUE TITLE
Config encoding (charset) braking on Windows on ViaVersion enabling, so on next runnings of server ViaVersion don't start

### ISSUE THREAD

**Issue by iBars** [ViaVersion/ViaVersion#1699]
**Describe the bug, provide any errors**
ViaVersion config.yml has charset UTF-8 and support all symbols, server is starting well. But after starting, ViaVersion config.yml charset changing to ANSI. ViaVersion still working. But after next running of server, ViaVersion will be error this: https://mclo.gs/rKyXziX
And will not work. This problem only with ViaVersion, other plugins are fine.

**How can we reproduce it?**
1. Install [Crafty Panel](https://craftycontrol.com) on Windows
2. Add & launch server through it with ViaVersion installed
3. Check config.yml encoding. It's now ANSI instead of UTF-8

**Screenshots**
None

**ViaVersion Dump:**
Plugin don't starting due to described problem. But I will show it with first run of ViaVersion:
https://dump.viaversion.com/67085d695f0f4b1a00298ea6767a81adc99a67af98464c748f542aa60c5add57

**Comment by iBars** [comment]
Why config is overriding at all on server starting? If nothing to update in config.

Also I think it can help to fix:
https://www.spigotmc.org/threads/solved-utf-8-in-config-yml.57879/

**Comment by KennyTV** [comment]
Did you change any of the config's messages? This also sounds like it might be due to magic by your panel

**Comment by MylesIsCool** [comment]
See https://github.com/ViaVersion/ViaVersion/issues/1685 it uses your OS encoding
