### ISSUE TITLE
Cannot join 20w13b using 1.15.2 via BungeeCord

### ISSUE THREAD

**Issue by ishland** [ViaVersion/ViaVersion#1701]
**Describe the bug, provide any errors**
Cannot join a 20w13b server using BungeeCord using ViaVersion-Abstraction b50, ViaBackwards b122, ViaRewind b103.
Error:
```
20:53:09 [SEVERE] [ishland] <-> ServerConnector [lobby] - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during server login process!
1bc7017b227472616e736c617465223a
20:53:09 [INFO] [ishland] disconnected with: Exception Connecting:QuietException : Unexpected packet received during server login process!
1bc7017b227472616e736c617465223a
```

**How can we reproduce it?**
1. Login on 1.15.2
2. Get kicked by server

**Expected behaviour**
Join and play.

**ViaVersion Dump:**
https://dump.viaversion.com/5f5a6ae0fa365a76fbf7ce4bb91d951259e0079bb0faa1180823db428842b08c

**Additional server info**
Use BungeeCord with only ViaVersion-Abstraction b50, ViaBackwards b122, ViaRewind b103.
Server "lobby" is vanilla minecraft_server.20w13b.
Using Java 11.0.6 on Debian 10.

**Comment by MylesIsCool** [comment]
You need a bungee that supports the snapshot.

**Comment by ishland** [comment]
How can I get a bungee that supports the snapshot?

**Comment by Xernium** [comment]
I maintain a modified Travertine with snapshot support at https://github.com/Xernium/Travertine builds can be found at https://jenkins.krusic22.com/job/Travertine-Xernium/

**Comment by ishland** [comment]
> I maintain a modified Travertine with snapshot support at https://github.com/Xernium/Travertine builds can be found at https://jenkins.krusic22.com/job/Travertine-Xernium/

Great work. I will test it tomorrow.
