### ISSUE TITLE
Invalid display of glass panes and doors

### ISSUE THREAD

**Issue by TheMixaDev** [ViaVersion/ViaVersion#1702]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?

**How can we reproduce it?**
1. Login on 1.14.4-1.15.2
2. Place some glass panes in a row and doors with different facing
3. The glass panes and doors are displayed wrong

**Expected behaviour**
Normal glass panes and doors display

**Screenshots**
https://ibb.co/ZNqmWH6
https://ibb.co/ZWsKQkK
https://ibb.co/56ZgBYS
https://ibb.co/94FPH9C
https://ibb.co/nmwST63
https://ibb.co/xLbN0MC

**ViaVersion Dump:**
https://dump.viaversion.com/ad97de64eedf7e4ebeaa32baf51166dbf85e925749efb1a11ef260331d632cfe

**Additional server info**
Server: Paper Spigot 1.8.8

I've used the ViaVersion 2.2.3 and 3.0.0

**Comment by Jo0001** [comment]
Just set block-connections to true in the ViaVersion
