### ISSUE TITLE
Player Disconnects when switching world

### ISSUE THREAD

**Issue by 1Legend11** [ViaVersion/ViaVersion#1704]
User has disconnected, reason: Internal Exception: io.netty.handler.codec.EncoderException: java.util.NoSuchElementException: us.myles.ViaVersion.protocols.protocol1_11to1_10.Protocol1_11To1_10

Every time someone on 1.8* or lower version switches worlds they get disconnected.

The server runs on 1.12.2 and i am running latest versions of viabackwards, viaversions, and viarewind

**Comment by KennyTV** [comment]
Your ViaBackwards is ancient, replace the 3 plugins with these versions:
https://ci.viaversion.com/job/ViaVersion-Abstraction/
https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-Abstraction/
https://ci.viaversion.com/view/ViaRewind/job/ViaRewind-DEV/

**Comment by 1Legend11** [comment]
That worked thank you so much!
