### ISSUE TITLE
Connecting to Server in 1.15.2

### ISSUE THREAD

**Issue by catter1** [ViaVersion/ViaVersion#1708]
**General Info**
When I join a server in 1.15.2 (only a specific server, others work [does not replicate with other players]), it will not let me connect.

**How Can We Reproduce It?**
1. Login on 1.15
2. Click on Multiplayer
3. Select server and click "Join server"
3. Loads, but then displays error message

**Expected Behavior**
Joining the server

**Screenshot**
![unknown](https://user-images.githubusercontent.com/63272345/78621800-7216c380-7851-11ea-80fb-6b388a7deff4.png)

**Additional Server Info**
Vanilla/Slimefun Server

**Comment by Ziipen** [comment]
I can't connect either, with the newest snapshot

**Comment by MylesIsCool** [comment]
You need to include the dump from /viaversion dump. If your issue is from 1.15 on 1.15.2 open this issue with the dump on ViaBackwards github.
