### ISSUE TITLE
Placing blocks that turn into the wrong block (world and inv)

### ISSUE THREAD

**Issue by FeaturedSpace** [ViaVersion/ViaVersion#1710]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?
There is no error, but what's happening is we're simply trying to build in our 1.8 servers and the blocks that we have in our inventory are different when we place them down, IE, Spruce changes to oak, cobblestone slab changes to smooth stone slab, etc.

(note that this happened on both 2.1.3 and 2.2.3)

Here is a video recording of it happening:
https://streamable.com/cl5wpc

**How can we reproduce it?**
1. Login on any version (we used 1.8)'
2. Place a birch plank and watch it change to oak.
3. The plank literally changes to a different type

**Expected behaviour**
As I'm placing a birch plank, I expect a birch plank to be placed.

**Screenshots**
https://streamable.com/cl5wpc

**ViaVersion Dump:**
https://dump.viaversion.com/ad7759bf2a13082f1dce2e8c642ae771af116aeaa9220aad5b53d3eaf4f1d52d

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
We are on a Bungeecord proxy with ViaVersion running locally on each server. We use nearly no additional Softwares on Bungeecord, with that exception of our NetworkCore plugin which handles game requests, balancing, etc.

**Comment by KennyTV** [comment]
Try recreating the issue without any other plugins (Bungee included) - Via does not handle protocol for clients with the same version as the server is running.

**Comment by FeaturedSpace** [comment]
So you're saying this issue is most likely caused by a plugin other than ViaVersion?

**Comment by KennyTV** [comment]
That's my guess, yeah

**Comment by FeaturedSpace** [comment]
I wonder what could be causing it though, the only thing I can think of would be worldedit and I've had older versions of ViaVersion and nothing has broken afaik.

**Comment by FeaturedSpace** [comment]
I ended up finding the issue. I would go into detail, but I might relapse just explaining it. 

The point is to make sure you're not setting durability on items that are BLOCKS (I'm incredibly stupid please don't laugh at me xD)
