### ISSUE TITLE
Particle issue, players kicked for this:

### ISSUE THREAD

**Issue by InstaAEGH** [ViaVersion/ViaVersion#1711]
10.04 13:21:13 [Disconnect] User GraceTheFoxx has disconnected, reason:

Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
10.04 13:21:13 [Server] INFO {Type: FlatVarIntItem, Source #1: us.myles.ViaVersion.api.rewriters.BlockRewriter$5 (Anonymous), Source #0: us.myles.ViaVersion.api.rewriters.BlockRewriter$5$$Lambda$2232/198013946, Data: [Pair{Type|Integer, 24}, Pair{Type|Boolean, true}, Pair{Type|Float, -1097.1383}, Pair{Type|Float, 5.0}, Pair{Type|Float, -176.72665}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.0}, Pair{Type|Integer, 1}], Packet ID: 36}
10.04 13:21:13 [Server] INFO Actual Error:

**Comment by KennyTV** [comment]
Please follow the issue template
