### ISSUE TITLE
Particle Error

### ISSUE THREAD

**Issue by InstaAEGH** [ViaVersion/ViaVersion#1712]
Describe the bug, provide any errors
A clear and concise description of what the bug is. Can you https://hastebin.com the error?
Basically, we use the plugin PlayerParticles, I run a spigot 1.14.4 server. When a 1.8 player joins, they'll get kicked for this error message.
https://hastebin.com/inexohizul.cs

How can we reproduce it?

Install a paperspigot 1.14.4 server jar, install player particles and turn on the firework style with lava particles.

Screenshots
https://gyazo.com/be32b94ce8aa42f664be9feb508ce0bf

ViaVersion Dump:
https://dump.viaversion.com/590ece7757081aac24032a972af3e6a55e714998962a339c6f4a55b03fcd17fa

Additional server info
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
This is just a PaperSpigot 1.14.4 server.

**Comment by KennyTV** [comment]
You probably either have an outdated Version of ViaBackwards, or the plugin is invalidly sending particle packets. Try these downloads, and if the error still appears, report it on the ViaBackwards issue tracker.
https://ci.viaversion.com/job/ViaVersion-Abstraction/
https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-Abstraction/
