### ISSUE TITLE
Error on connecting with 1.8.9

### ISSUE THREAD

**Issue by Lunatik934** [ViaVersion/ViaVersion#1714]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?
https://hastebin.com/vowoyusexa.bash
**How can we reproduce it?**
1. Login on 1.8.9'
2. Look in logs

**Expected behaviour**

**Screenshots**

**ViaVersion Dump:**
- https://dump.viaversion.com/132a3d61c56df61ecbd09e73f6000982dd639bac189c354b6fa3ea12c1a8f1b4

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Comment by KennyTV** [comment]
Not a Via issue, a plugin of yours is loading too many textures/skull data, so your ip was blocked
