### ISSUE TITLE
Kicked every time I join my friend's server.

### ISSUE THREAD

**Issue by Magikorp3662** [ViaVersion/ViaVersion#1715]
**Describe the bug, provide any errors**
When I join my friend's MineHut server, I get kicked seemingly when I enter a new chunk. Not my server, but he provided me with a dump. When I first joined the server, however, it was fine. Not until a few hours later.
**How can we reproduce it?**
1. Login on 1.11.2 (The version I'm using.)
2. Join the server.
3. After walking for a few seconds, you get kicked.

**Expected behaviour**
To be able to move around, at least.
**Screenshots**
![image](https://user-images.githubusercontent.com/32024264/79057351-3c455680-7c26-11ea-9b46-6d6f470762bb.png)
(sorry if it's big)
Edit: Got a screen recording of the issue, it occurs when i cross random chunkborders (doesn't always happen, but frequently enough.) Link [here](https://youtu.be/MNv3rTvu-OA).

**ViaVersion Dump:**
- https://dump.viaversion.com/f4148f7962a70ccd472ad830499344d6fe51bf4e04134fbcbcc79a85ae1afa64

**Additional server info**
No proxy, server is on 1.15.2, hosted on MineHut.com. Plugin list: AdvancedBan, ArmorStandEditor, AuctionHouse, Backpack, BankNotes, Betternick(Disabled), BetterSleeping, BukkitCore, ChatFeelings, CS-CoreLib, CustomHeads, Essentials, Factions, GreatKits, Itemizer, NametagEdit, PlayerServer, QualityArmory(Probably removing), RankGrantPlus(Disabled), Skript, Slimefun, StaffPlus, TreysCommandBlocker, TrollBoss, TrollCommands++, Vault, ViaBackwards, ViaVersion, WorldEdit

**Comment by Magikorp3662** [comment]
I made a screen recording of the issue, it happens when i go through chunkborders into random chunks.

**Comment by MylesIsCool** [comment]
There is a plugin which sends invalid JSON. The best way to debug is to first test with no plugins as it might be a scoreboard.dat or in the world. Then remove half the plugins and test.
