### ISSUE TITLE
Client crashes after running a FastAsyncWorldEdit command. 1.15.2

### ISSUE THREAD

**Issue by JacobTyrrell** [ViaVersion/ViaVersion#1716]
**Describe the bug, provide any errors**
After I ran a FAWE command //visualize outline, I immediately got kicked with this error:
`Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: Chunk, Source #1: nl.matsv.viabackwards.protocol.protocol1_14_4to1_15.packets.BlockItemPackets1_15$3 (Anonymous), Source #0: nl.matsv.viabackwards.protocol.protocol1_14_4to1_15.packets.BlockItemPackets1_15$3$1 (Anonymous), Data: [], Packet ID: 33}
Actual Error:`

**How can we reproduce it?**
1. Login on 1.14.4 on a 1.15.2 Spigot server software.
2. Run command //visualize outline
3. Get kicked.

**Expected behavior**
Visualizing the outline of the selection

**Screenshots**

**ViaVersion Dump:**
https://dump.viaversion.com/1b395182d682b82a607b3c27632139a115c12c9f3b6c3867b57e598613bf7d6f

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
I use a Bungeecord network, plugins:
CoralStay, EssentialsX pack, FastAsyncWorldEdit, LuckPerms, Multiverse-Core, ProtocolLib, Vault, ViaBackwards, ViaRewind, ViaVersion Void Generator, VoidWorld*, WorldEdit.

**Comment by MylesIsCool** [comment]
This is a ViaBackwards issue please open it on ViaBackwards issues.
