### ISSUE TITLE
Performance issue (config reading)

### ISSUE THREAD

**Issue by Dymeth** [ViaVersion/ViaVersion#1720]
I dealt with the issue of the performance of my server and found out that ViaVersion uses a tangible share of CPU time. I found out that getting some values from the config takes almost 3% of the total CPU time. This is quite a lot, so I think it would be worth thinking about optimizing this.
I am talking about the call stack below.
Perhaps it’s worth preloading the necessary values in separate fields so that each time you do not get from the map.

Screenshot from JProfiler:
![image](https://user-images.githubusercontent.com/21080646/79076865-d92af100-7d05-11ea-8755-0b7a2524bac6.png)

Server build: Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
ViaVersion version: 2.2.3
The server is behind the BungeeCord proxy.

**Comment by KennyTV** [comment]
The config options have already been set into cached fields in the current dev versions. Until it's released, you can download them from the abstraction section on the ci
