### ISSUE TITLE
Spamm in console

### ISSUE THREAD

**Issue by BC-Senku** [ViaVersion/ViaVersion#1722]
**Describe the bug, provide any errors**
So whenever i start my server this error floods my console every 5-10 seconds
https://hastebin.com/izibuqilih.pl

**How can we reproduce it?**
1. start the server
2. console spam

**Expected behaviour**
I mean. Expect it to not spam my console

**Screenshots**
[https://ibb.co/d4NjvYX](url)

**ViaVersion Dump:**
- https://dump.viaversion.com/529cf7480f1e120e80a4b9c222ae92473a977c853bdccd484d1ac47050789309

**Additional server info**

**Comment by MylesIsCool** [comment]
ViaVersion doesn't work with ProtocolSupport unless using Paper instead of Spigot.

**Comment by BC-Senku** [comment]
oh ok
