### ISSUE TITLE
Kicked users 1.8 version

### ISSUE THREAD

**Issue by LestGiann** [ViaVersion/ViaVersion#1725]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?

**How can we reproduce it?**
1. Login on 1.8'
2. Write custom command
(The custom command execute the nexts commands:)
/lp user %player% meta setsuffix "&8[PER] "
3. The system kicked the player 1.8 for use the custom command (i created the command with MyCommand plugin) 

Message of Console:
> [02:54:53 INFO]: LestGiann lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: Item Array, Source #0: nl.matsv.viabackwards.protocol.protocol1_11_1to1_12.packets.BlockItemPackets1_12$3 (Anonymous), Data: [Pair{Type|Unsigned Byte, 1}], Packet ID: 20}

**Expected behaviour**

**Screenshots**
Don't have

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/dfd88fe616736cf518dd9e9bcf749c1430bcc5103717d50b7194521e3262e845

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
I don't use bungeecord, i use spigot 1.12.2, i use chestcommands, Mycommands, matrix

**Comment by MylesIsCool** [comment]
Open this issue on ViaBackwards if it happens on 1.9 or ViaRewind if only 1.8
