### ISSUE TITLE
EncoderException, my plugin tries sending a message to the player on join and I get this error

### ISSUE THREAD

**Issue by purplexdev** [ViaVersion/ViaVersion#1726]
io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
14.04 12:49:00 [Server] INFO {Type: String, Source #0: us.myles.ViaVersion.protocols.base.BaseProtocol1_7$2 (Anonymous), Data: [Pair{Type|String, {"extra":["You sent a packet!"],"text":""}}], Packet ID: 2}

**Comment by MylesIsCool** [comment]
This isn't a valid packet so ViaVersion can't translate it.

I'd suggest ensuring they're logged in / checking the ids you're using.

**Comment by purplexdev** [comment]
Alright, thank you, I was on 1.15.2 client anyways, I am not sure if it is fully supported.
