### ISSUE TITLE
1.12.2-->1.15.2 block connection

### ISSUE THREAD

**Issue by rafalohaki** [ViaVersion/ViaVersion#1729]
engine 1.12.2
client 1.15.2
i have problem with vanishing connections on plot and glass
![image](https://user-images.githubusercontent.com/20607107/79377656-4df76880-7f5c-11ea-9f66-1b6ccd99e05c.png)
![image](https://user-images.githubusercontent.com/20607107/79377666-50f25900-7f5c-11ea-9443-5543dd2f8a8f.png)

**Comment by krusic22** [comment]
Did you enable block connections in the ViaVersion config?

**Comment by rafalohaki** [comment]
> Did you enable block connections in the ViaVersion config?

![image](https://user-images.githubusercontent.com/20607107/79377789-84cd7e80-7f5c-11ea-8ae5-d63908612aff.png)

**Comment by krusic22** [comment]
Enable the first one.

**Comment by rafalohaki** [comment]
> Enable the first one.

thank you
