### ISSUE TITLE
Unsupported protocol version 578

### ISSUE THREAD

**Issue by GameFreakBaree** [ViaVersion/ViaVersion#1731]
**Describe the bug, provide any errors**
Error in Proxy: https://hastebin.com/eteridirar.bash
Im using the latest bungee version. And All my servers are paper 1.12.2. But one server (survival) is 1.15.2. And eveything runs fine. But when i want to join the survival server it does not work (ERROR: https://gyazo.com/9eddec628045d6b8640abbf33ddf1e8f ). ViaVersion is ONLY in the Proxy server.

Config: https://hastebin.com/zutemuruce.shell

**How can we reproduce it?**
1. Servers:
BungeeCord: build 1489
Hub: Paper 1.12.2 - build 1618
Survival: Paper 1.15.2 - build 183
2. Open Minecraft 1.15.2.
3. Go to the Hub and try to connect to Survival.

**Expected behaviour**

**Screenshots**
https://gyazo.com/9eddec628045d6b8640abbf33ddf1e8f

**ViaVersion Dump:**
https://dump.viaversion.com/d246f5b770cba01120d80907c54007a9257bd6e6e78740997cb7684119be89a9

**Additional server info**
Latest Bungeecord Version, 1.12.2 Hub and 1.15.2 Survival Server both running Paper (latest)
BungeeCord: build 1489
Hub: Paper 1.12.2 - build 1618
Survival: Paper 1.15.2 - build 183

**Comment by KennyTV** [comment]
Update BungeeCord to its latest version

**Comment by GameFreakBaree** [comment]
That is the latest version... https://ci.md-5.net/job/BungeeCord/

**Comment by KennyTV** [comment]
Yours is quite a few months old (git:BungeeCord-Bootstrap:1.15-SNAPSHOT:4cccf53:1426)

**Comment by GameFreakBaree** [comment]
owh i see. Pebblehost Loader said it was 1489. I now installed it manually.
