### ISSUE TITLE
Bungeecord Bug

### ISSUE THREAD

**Issue by Ironman2M** [ViaVersion/ViaVersion#1732]
**Describe the bug, provide any errors**
https://hastebin.com/goxixekesa.cs Hello, I am new here at github but I got this error on my bungeecord server. I am running client 1.14.4 and I just connected to the server after installing viaversion and this is happening.

**How can we reproduce it?**
1. Login on 1.14.4'
2. Connect to "server"
3. I dont know why it happens.

**Expected behaviour**
To normally join me to my server.

**Screenshots**
https://ctrlv.cz/UhDd

**ViaVersion Dump:**
Cant type when I cant join.

**Additional server info**
BungeeCord, and I am using ViaVersion + ViaRewind ( Newest )

**Comment by BuzzTheGamer23** [comment]
You can get your ViaVer dump from console

**Comment by FormallyMyles** [comment]
Since there's no reply here, gonna close this. Discord is the best way for this kind of issue if you're still stuck.
