### ISSUE TITLE
I cant join my server on versions above 1.8.9

### ISSUE THREAD

**Issue by 2006DW1** [ViaVersion/ViaVersion#1736]
higher versions than 1.8 on my spigot 1.8 server cannot join

the error is
![image](https://user-images.githubusercontent.com/63964725/79690878-df9bfa00-822a-11ea-9bf6-eea01dd10a2b.png)

The console error is
[Sun, 19. Apr 2020 10:23:19 EDT INFO] Unknown command. Type "/help" for help.
[Sun, 19. Apr 2020 10:23:21 EDT INFO] UUID of player 2006DW is 5de7252a-b282-4d36-972d-182db51ab4ed
[Sun, 19. Apr 2020 10:23:21 EDT INFO] [+] 2006DW
[Sun, 19. Apr 2020 10:23:21 EDT INFO] [DiscordSRV] Player 2006DW joined with silent joining permission, not sending a join message
[Sun, 19. Apr 2020 10:23:21 EDT INFO] 2006DW[/69.123.21.208:53376] logged in with entity id 72605 at ([testing]15.391530065199735, 20.529244848683412, 6.3285743044367235)
[Sun, 19. Apr 2020 10:23:22 EDT INFO] 2006DW lost connection: Disconnected
[Sun, 19. Apr 2020 10:23:22 EDT INFO] [-] 2006DW
[Sun, 19. Apr 2020 10:23:22 EDT INFO] [DiscordSRV] Player 2006DW quit with silent quitting permission, not sending a quit message

**Comment by MylesIsCool** [comment]
There isn't enough info here to do anything.

https://github.com/ViaVersion/ViaVersion/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
