### ISSUE TITLE
when i join my server on any version above 1.8.9 I get kicked 

### ISSUE THREAD

**Issue by 2006DW1** [ViaVersion/ViaVersion#1737]
When I join my server on any version above 1.8.9 I get kicked

How can we reproduce it? Steps to reproduce the behavior:

Login on any version above 1.8.9'
when you join the error is
![image](https://user-images.githubusercontent.com/63964725/79692409-0827f200-8233-11ea-9b9f-611265d7cec3.png)

Expected behaviour A clear and concise description of what you expected to happen.
You are supposed to be able to join the server
Screenshots If applicable, add screenshots to help explain your problem.

the console error is
[Sun, 19. Apr 2020 10:23:19 EDT INFO] Unknown command. Type "/help" for help.
[Sun, 19. Apr 2020 10:23:21 EDT INFO] UUID of player 2006DW is 5de7252a-b282-4d36-972d-182db51ab4ed
[Sun, 19. Apr 2020 10:23:21 EDT INFO] [+] 2006DW
[Sun, 19. Apr 2020 10:23:21 EDT INFO] [DiscordSRV] Player 2006DW joined with silent joining permission, not sending a join message
[Sun, 19. Apr 2020 10:23:21 EDT INFO] 2006DW[/69.123.21.208:53376] logged in with entity id 72605 at ([testing]15.391530065199735, 20.529244848683412, 6.3285743044367235)
[Sun, 19. Apr 2020 10:23:22 EDT INFO] 2006DW lost connection: Disconnected
[Sun, 19. Apr 2020 10:23:22 EDT INFO] [-] 2006DW
[Sun, 19. Apr 2020 10:23:22 EDT INFO] [DiscordSRV] Player 2006DW quit with silent quitting permission, not sending a quit message

ViaVersion Dump:
https://dump.viaversion.com/4bd9e9a246f40bb13a5bcac7101fd14e82ea88fa7ac2e454e7a6054bde32dd79

Additional server info Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
1.8 spigot

**Comment by MylesIsCool** [comment]
Can you replicate this with just ViaVersion installed? I suspect a plugin might be sending bad data.

**Comment by FormallyMyles** [comment]
See above, and we'll reinvestigate :)
