### ISSUE TITLE
ViaVersion.protocols.base.BaseProtocol$1 (Anonymous) Crash

### ISSUE THREAD

**Issue by LoXR** [ViaVersion/ViaVersion#1739]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?
https://hastebin.com/wegazazasi.php
**How can we reproduce it?**
No reproduction, unless you use a botting service.

**Expected behaviour**
Hopefully stop this spam that could be the possible issue of high CPU/Memory during an attack.

**Screenshots**
http://prnt.sc/s3gfrs
**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/9cf341e1b5719b3890b7a887764667a486279a4d11d902ca09cf7106a49ae7b2
**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
Aegis 7.5

**Comment by KennyTV** [comment]
Via doesn't have any means of validating incoming data and there's no way of feasibly preventing all exception generation. In general. such attacks should be dealth with above the server level / at least the proxy
