### ISSUE TITLE
#getDrops().clear not working

### ISSUE THREAD

**Issue by ItsVinnyX** [ViaVersion/ViaVersion#1744]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?

**How can we reproduce it?**
1. Kill a player

**Expected behaviour**
When a player dies their drops should not drop. With the use of #getDrops().clear

**Screenshots**
https://imgur.com/a/oF1G0xx

**ViaVersion Dump:**
https://dump.viaversion.com/5071eab87f7eff2c1620721444430b41fd747a303decb0dd91e0753e389349e7

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
Custom coded plugin, HexaCord (BungeeCord Fork)

**Comment by KennyTV** [comment]
Already tracked in a ViaBackwards issue (with more Informatik)
