### ISSUE TITLE
Java issue on every disconnect

### ISSUE THREAD

**Issue by JHarris12345** [ViaVersion/ViaVersion#1746]
**Describe the bug, provide any errors**
Everytime someone disconnects, there is this java issue https://pastebin.com/9Xi0zT7y

**How can we reproduce it?**
1. 1.8.8 paper server
2. 1.14 client has been tested on
3. Leave the server, watch console error

**Expected behaviour**
No error

**Screenshots**

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Comment by MylesIsCool** [comment]
You have some form of debug mode on. Look in your files and turn it off.

**Comment by JHarris12345** [comment]
Do you know which files are likely to contain it?
