### ISSUE TITLE
Right clicking armor causes client crash

### ISSUE THREAD

**Issue by JHarris12345** [ViaVersion/ViaVersion#1747]
**Describe the bug, provide any errors**
On 1 1.5.2 client on 1.8.8 server, if you right click with a piece of armor, you crash with the following:

![image](https://user-images.githubusercontent.com/46936647/80530429-e6481100-8990-11ea-8945-b462aeaea05a.png)

**How can we reproduce it?**
1. Login on 1.15.2 client
2. 1.8.8 spigot server
3. right click whilst holding armor

**Expected behaviour**
It should equip the armor and not crash you. Here it equips the armor but crashes you

**ViaVersion Dump:**
https://dump.viaversion.com/d35609d66b672e60575193c34054864cf93bacbd5d99e3a04962432ea837bb79

**Comment by KennyTV** [comment]
Can't reproduce, the error also seems unrelated to your description.
Try consistently reproducing it without any other plugins (or at least pin it down to one if it is plugin related) - if you can, we will reopen the issue
