### ISSUE TITLE
Is there any way to remove ViaVersion from any server

### ISSUE THREAD

**Issue by ValenBJs** [ViaVersion/ViaVersion#1748]
Hi! Today I had a little problem with BungeeCord, Bedwars, Survival and HCF 
on the HCF server already has a "ViaVersion" (LazarusSpigot) so I want to know if I can remove ViaVersion from that server

**Comment by Xernium** [comment]
We don’t support servers using custom Protocol hacks. That said where do you have ViaVersion installed? Please provide the output of /viaversion dump

**Comment by ValenBJs** [comment]
I would like to get the viaversion out of the hcf server ! and I have the viaversion in bungeecord

**Comment by MylesIsCool** [comment]
This isn't possible. We don't support this.

**Comment by ValenBJs** [comment]
https://dump.viaversion.com/c4779d9f338c5306279b94fe40f9569616e60726fbd4d0fb6036f54d0f633715

**Comment by Xernium** [comment]
In your Waterfall viaversion config.yml set bungee-ping-interval to -1
and set the Protocol ID of the server you want to bypass with Via to 999. Careful though using these settings will have you manually add new servers to the list with their appropriate version ID as per http://wiki.vg
