### ISSUE TITLE
high velocity on thrown items and arrows while on a ladder

### ISSUE THREAD

**Issue by PhanaticD** [ViaVersion/ViaVersion#1752]
**Describe the bug, provide any errors**
https://gyazo.com/94590ffa032c0e766e89c49f204845ed

you also dont take knockback while on the ladder

the only reason I am assuming this is a viaversion issue, is because it does not happen if I log on with a 1.8 client, only with newer clients

**How can we reproduce it?**
throw items while standing on the edge of a ladder

**Expected behaviour**
normal

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/b7f95d5f0e6f3524f714af811ca9f912297b25505714a0d712c1085e4c9e507a
**Additional server info**
I use travertine for bungee proxy

**Comment by KennyTV** [comment]
Can you reproduce this without any other plugins?

**Comment by PhanaticD** [comment]
idk

**Comment by KennyTV** [comment]
I don't either; Reopen it if you can, otherwise I doubt this is solely down to Via
