### ISSUE TITLE
Server Version 1.13.2. use 1.15.2 join and its kicked when moving

### ISSUE THREAD

**Issue by siwakorn2255** [ViaVersion/ViaVersion#1754]
![image](https://user-images.githubusercontent.com/24570605/80866108-2cfe7980-8cb7-11ea-94fc-00e95f1213a8.png)
my server version is 1.13.2 i use 1.15.2 to join my own server when i moving. Server is kicked me

**Comment by FormallyMyles** [comment]
https://github.com/ViaVersion/ViaVersion/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
