### ISSUE TITLE
Could not load hitbox fix

### ISSUE THREAD

**Issue by The-Fireplace** [ViaVersion/ViaVersion#1755]
**Describe the bug, provide any errors**
When the server loads, it says it cannot load the hitbox fix.
https://hastebin.com/atuxebemet.sql

**How can we reproduce it?**
1. Start the 1.12.2 server with ViaVersion
2. Check the logs

**Expected behaviour**
I expected the hitbox fix to work.

**ViaVersion Dump:**
https://dump.viaversion.com/39e34bc61a9bfec737bcf0eaabbf8bd0f2dbf6e519c9e1bfb876ab894b2b67d4

**Additional server info**
I am running a 1.12.2 server with Forge and Bukkit using CatServer-2e5ed82-async.
Mods:
![image](https://user-images.githubusercontent.com/5914284/80872320-be013080-8c76-11ea-82aa-a9d5c46d9425.png)
Plugins:
![image](https://user-images.githubusercontent.com/5914284/80872328-d2452d80-8c76-11ea-8fb2-672677b277ab.png)

**Comment by KennyTV** [comment]
Custom mapped server forks are not supported. Either use a standard CB/Spigot/Paper (or any other sane fork) or disable the setting
