### ISSUE TITLE
1.15.2 bug on 1.13.2 server.

### ISSUE THREAD

**Issue by SzurkeRoka** [ViaVersion/ViaVersion#1758]
1.15.2 bug on 1.13.2 server.

Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: Chunk, Source #1: us.myles.ViaVersion.protocols.protocol1_14to1_13_2.packets.WorldPackets$8 (Anonymous), Source #0: us.myles.ViaVersion.protocols.protocol1_14to1_13_2.packets.WorldPackets$8$1 (Anonymous), Data: [], Packet ID: 33}
Actual Error:

**Comment by KennyTV** [comment]
Set debug=true in your server.properties and try to recreate the error (and create a new issue following the issue template).
