### ISSUE TITLE
Swimming speed way faster then spigot water movement.

### ISSUE THREAD

**Issue by DocCodeSharp** [ViaVersion/ViaVersion#1759]
**Is your feature request related to a problem? Please describe.**
When a player goes into swim mode (1.13+), they are fast and not compared to the speed of a player in water with sprint in 1.12.2.

**Describe the solution you'd like**
1. Have a option in the config that will allow you to turn of the new swimming option in 1.13+. This will allow the clients to match from 1.12.2 - 1.15.2 and making water movement the same.
2. Have an option in the config to adjust the movement packet of the player while under water.

**Describe alternatives you've considered**
I don't think we can try other solution as it would require some heavy packet changing for the player.

**Which versions is this for?**
1.12.2 Spigot Server, 1.15.2 Client.

**Comment by KennyTV** [comment]
If you really want to, you can set the player's food level down to prevent the sprint swimming, and back to normal once they are out of water. Messing with (movement) packets is not a viable option.

**Comment by DocCodeSharp** [comment]
There are to many problems with that 

1. When we set it hunger that means we have to disable food so they can't eat and get hunger bars back.
2.  They could lose hunger so you would have to give them a set hunger and thus make it so they never have to eat.

There has to be a way to be able to stop it.

**Comment by KennyTV** [comment]
If you know any, let us know. At the moment, we don't have another way, since the client doesn't really care about being told not to sprint swim :p
