### ISSUE TITLE
Npc from citizens changes position on relog

### ISSUE THREAD

**Issue by kacperleague9** [ViaVersion/ViaVersion#1762]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?

**How can we reproduce it?**
1. Make a npc with citizens
2. Rejoin
3. You see the difference

**Expected behaviour**

I expected it to look as always.

**Screenshots**
![image](https://user-images.githubusercontent.com/34658474/81100274-90351980-8f0c-11ea-9a10-0f19a673f0bb.png)

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/372306d87cd352b1a722bcf2e99ee4c89b8c19b607e0ab6ec9d7fadf30b853cc
**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
1.12.2 viaversion

**Comment by FormallyMyles** [comment]
What versions does this happen on? Have you tested on 1.12.2?

**Comment by FormallyMyles** [comment]
We need more info on this, we'll reopen if you're happy to debug stuff like the above. Might just be something different per version
