### ISSUE TITLE
icompatibility with viaversion and PaperSpigot 1.8.8?

### ISSUE THREAD

**Issue by ValenBJs1** [ViaVersion/ViaVersion#1764]
Yes, I have PaperSpigot 1.8.8 and cannot link from BungeeCord with "HCF"

I'd like to solve it anyway

Deactivate some of that server's viaversion.

In the bungeecord I have Viaversion - 2.2.3, ViaRewind - 1.4.5 and ViaBackWards - 2.4.0

![image](https://user-images.githubusercontent.com/64873014/81123352-40a11e80-8f09-11ea-9f78-f72d705297d9.png)

**Comment by KennyTV** [comment]
Whoops sorry, linked the wrong issue here. You don't need ViaBackwards on a 1.8 server, so just remove it. If you have a server where you'd need it, you would have to download the -abstraction builds from the ci.

**Comment by ValenBJs1** [comment]
When I take out the ViaBackward directly I can't get into the Hub !
