### ISSUE TITLE
1.9+ Always interacts on right click

### ISSUE THREAD

**Issue by Bonista** [ViaVersion/ViaVersion#1766]
**Describe the bug, provide any errors**
1.9+ players are able to interact even when there is nothing to interact with, here is a a packet dump for each interaction:
https://pastebin.com/sjzgF9zp

**How can we reproduce it?**
1. Login on 1.9+
2. Interact (right click) with any block (tool tested)
3. Player interacts even with nothing to interact with

**Expected behaviour**
See the gif below, should not interact if there is nothing to interact.

**Screenshots**
https://i.imgur.com/7yrKRtB.mp4
(First one is on multiplayer with ViaVersion, second one is on single player (expected behaviour)).

**ViaVersion Dump:**
https://dump.viaversion.com/b7b8c3235e8834e57300cafc86ba31476cb81e7599302e307d83a64faea67832

**Comment by KennyTV** [comment]
This is default 1.8 server behaviour due to a response the client gets on interact.

**Comment by Bonista** [comment]
Does anything break if that response the client gets on interact is stopped?

**Comment by KennyTV** [comment]
No idea, but why would even want to do that? This isn't any sort of issue, this is... well, 1.8
