### ISSUE TITLE
Can place blocks inside player on Paper 1.8.8 server with 1.15.2 client

### ISSUE THREAD

**Issue by ch515** [ViaVersion/ViaVersion#1767]
When using the Paper 1.8.8 server, the Waterfall proxy (with ViaVersion), and a 1.15.2 client.  You can place blocks inside yourself (at your feet).

1. Login with a 1.15.2 client on the 1.8.8 server
2. Attempt to place a block directly below you

A block should appear inside you, and the player is forced to the side.

The ViaVersion plugin (latest version) is used on a Waterfall proxy (build 341) as mentioned above, and no other plugins (except a small custom one on the Paper server that doesn't do anything weird) are used.

**Comment by Xernium** [comment]
There is a patch for this in Via* if you installed it on the backend instead, but that patch doesn’t work if it’s run on the bungeecord. Thus this is a wontfix. Well for the time being anyway. If anything changes I’ll update this here

**Comment by Bonista** [comment]
Fork PaperSpigot and add:
                if (entity == entity1) {
                    return false;
                }
to the World.class block collision method (public boolean a(AxisAlignedBB axisalignedbb, Entity entity).

**Comment by FormallyMyles** [comment]
See above

**Comment by 7wOv6ySCjo** [comment]
> See above

"See adove" it's not a solution.
