### ISSUE TITLE
Blocks randomly appearing on server start

### ISSUE THREAD

**Issue by TechnoVisionDev** [ViaVersion/ViaVersion#1770]
**Describe the bug, provide any errors**
When using ViaVersion on my 1.8.8 server, everything is fine unless a user joins with a 1.13+ client. Something about the new rendering system from that update causes random "white concrete" blocks to respawn in the same location around my builds on every server start. Even if I break them, they reappear as soon as I reload the server. I know this is a ViaVersion problem because removing the plugin instantly fixed the problem. When the blocks are right clicked, they dissapear, as if they didn't event exist in the first place. Possibly a memory leak from the plugin??

**How can we reproduce it?**
1. Create a 1.8.8 spigot server with viaversion
1. Login to the server on a 1.13+ client

**Expected behaviour**
Pretty self explanatory

**ViaVersion Dump:**
https://dump.viaversion.com/4024e97e7044368998f7364dbef0ec33298e80af6b2637cdbbe1c0c4969f4db0

**Additional server info**
Spigot 1.8.8

**Comment by KennyTV** [comment]
"Reload" or full "restart"?

**Comment by userMacieG** [comment]
@TechnoVisionDev Are you using newest versions of Via plugins?

**Comment by TechnoVisionDev** [comment]
I am using the most recent version of ViaVersion (downloaded a week ago from the official spigot page) with a Spigot 1.8.8 server jar. The blocks reappear on a full server restart. I’ve been able to skirt around this issue by placing blocks in the location of the “white concrete” and restarting the server. Upon breaking these blocks, the server “forgets” and no longer loads them in. 

Considering my world and server is 1.8.8, “white concrete” isn’t a block that exists in the game. It could possibly be a problem with the schematic or maybe chunk corruption (I’m not rlly sure) but I figured it was better to post it here so other people know that this is something that is happening

**Comment by userMacieG** [comment]
Btw. issue is somewhere in loading chunks. I have same issue on my server with signs.
I have signs on main world to join areas, but sometimes signs from main word appears in another world. 
This issue is only visible on client side.
Imo its some bug in packet sending info about world.

**Comment by KennyTV** [comment]
Does that also happen for the same client version as is the server version?

**Comment by userMacieG** [comment]
> Does that also happen for the same client version as is the server version?

Yea.
![UcyXrftg1Q](https://user-images.githubusercontent.com/24211405/81813590-f121aa80-9527-11ea-8636-eb5d83a6fca5.gif)

**Comment by userMacieG** [comment]
Another version: (custom 1.8.8 client)
![NN0CBNmPZT](https://user-images.githubusercontent.com/24211405/81813911-570e3200-9528-11ea-8490-87faf1589905.gif)

**Comment by FormallyMyles** [comment]
I would highly suspect this might be down to another plugin / incompatibility with ViaVersion. Mainly because we don't modify data when your server version == client version
