### ISSUE TITLE
Villager doesn't let player to trade on 1.14+

### ISSUE THREAD

**Issue by Seanoo1** [ViaVersion/ViaVersion#1772]
1. Login on 1.14+ on tacospigot 1.8.8 server
2. Click the Villager'
3. try to trade items

**Expected behaviour**
should trade normally

**Videos**
https://youtu.be/oIjcSvHAAbc

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.

**Additional server info**
tacospigot(spigot didn't worked to) 1.8.8, tested with another bukkit that only have viaversion, shopkeepers

**Comment by KennyTV** [comment]
1.8 doesn't autofill trades, you have to manually put in (or shit click) the item.
