### ISSUE TITLE
Server does not accept connections

### ISSUE THREAD

**Issue by MedicOP** [ViaVersion/ViaVersion#1773]
**Describe the bug, provide any errors**
The issues described in https://github.com/ViaVersion/ViaVersion/issues/362 and https://github.com/ViaVersion/ViaVersion/issues/612 are still happening in 2020

If a player connects to the server during boot before ViaVersion has loaded+enabled, the player is able to log in and play but no other players can connect.

When other players try to connect, it just says "Logging in..." indefinitely until timing out.

**How can we reproduce it?**
1. Start up server
2. A player has to initiate a connection before ViaVersion has been loaded+enabled

**Additional server info**
ViaVersion 2.2.3
Spigot 1.8.8
ProtocolLib 4.2.0

**Comment by FormallyMyles** [comment]
You're going to need to provide a zip of an environment that can replicate this because when it was last tested it was never repeatable.

**Comment by MedicOP** [comment]
[Server.zip](https://github.com/ViaVersion/ViaVersion/files/4609349/Server.zip)
This has ProtocolLib, ViaVersion and a custom plugin that simply loads before ViaVersion and does Thread.sleep(5000).

Steps to reproduce:
1. Fire up server
2. Connect after server has binded to the IP, but before ViaVersion loads (you'll have plenty of time because of the custom plugin)
3. After successfully connecting, try re-logging.

**Comment by KennyTV** [comment]
Follow https://github.com/dmulloy2/ProtocolLib/issues/724 for updates on this
