### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by rafalohaki** [ViaVersion/ViaVersion#1774]
Hi,
My suggestion is, it could be more more easier where u could block protocols by number>going down or number<going up. I mean when u write protocol for 1.12.2 and add some symbol which could block all to down or to up versions.
ex. 
> block-protocols:
> - 320>*
> - 400<*

**Comment by FormallyMyles** [comment]
I'd suggest just using the generator at https://via.krusic22.com/, don't update ViaVersion if you don't want any newer versions

**Comment by rafalohaki** [comment]
> I'd suggest just using the generator at https://via.krusic22.com/, don't update ViaVersion if you don't want any newer versions

what about joining on blocked version 1.8.9 but in alternative version of snapshot?

**Comment by FormallyMyles** [comment]
I don't really understand. ViaVersion only supports those versions on spigot release. If you're on abstraction it'll support the latest snapshot, which the id is on the wiki.vg protocol numbers page.
