### ISSUE TITLE
viaversion is not working when plugin is became more then 49+ on tacospigot 1.8.8

### ISSUE THREAD

**Issue by Seanoo1** [ViaVersion/ViaVersion#1777]
**How can we reproduce it?**
1. open server with using plugin more then 49+
2. try to join server on 1.9+ client
3. You will see "Unsupported protocol version xxx"

**Expected behaviour**
Should join server normally

**ViaVersion Dump:**
https://dump.viaversion.com/2202a07a16c79f09e10868e8b44bbb2499909a3ec6dbf0abf32157e07aff1162

**Additional server info**
Server is tacospigot 1.8.8.

I can't add plugin because of this. Please fix this.

**Comment by Xernium** [comment]
Update your bungeecord.

**Comment by Seanoo1** [comment]
Im using tacospigot, not bungeecord

**Comment by FormallyMyles** [comment]
Can you fill out the issue template properly and provide /ViaVersion dump?

**Comment by Seanoo1** [comment]
edit the post, and same issue was occur when not using dev build too.

**Comment by FormallyMyles** [comment]
This is probably a plugin conflict with protocolsupport.

**Comment by Seanoo1** [comment]
ok I will try with removing protocolsupport

**Comment by Seanoo1** [comment]
it worked but... if I use this method then 1.5.2 can't join server...

**Comment by FormallyMyles** [comment]
There are ways of having Ps and 1.8.8 work but honestly it causes more issues than it's worth. 

It depends very much on server brand (usually paper or regular spigot for 1.8)

You can overlay ViaVersion at a bungee level. Or upgrade your server to 1.15.2 and just use ProtocolSupport. ProtocolSupport doesn't support older versions of their software.

**Comment by Seanoo1** [comment]
ok I'll try to change bukkit to paperspigot or spigot

**Comment by Seanoo1** [comment]
Failed :(  I think only the solution is using viarewind... thank for the advice

**Comment by Seanoo1** [comment]
wrong issue, it was other plugin Issue
