### ISSUE TITLE
Players kicked when switching worlds.

### ISSUE THREAD

**Issue by NiveryIGN** [ViaVersion/ViaVersion#1778]
My server is running on Craftbukkit 1.12.2 and I'm not gonna be switching to anything else so don't recommend that. Players get kicked whenever switching worlds and it's only when they play on a version below 1.12.2 (original server version). They get this message: "Disconnected".
Viaversion plugins: 

- ViaVersion-2.2.3.jar
- viabackwards-all-2.4.0-SNAPSHOT.jar

The error in the console whenever this happens: 
`nivery lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.util.NoSuchElementException: us.myles.ViaVersion.protocols.protocol1_11to1_10.Protocol1_11To1_10`

I'm also using Multiverse Core so it might interfere with that plugin as well, I'm not sure.
- Multiverse-Core-2.5.0.jar

**Comment by KennyTV** [comment]
Update both
ViaVersion - https://ci.viaversion.com/job/ViaVersion-Abstraction/lastSuccessfulBuild/artifact/jar/target/ViaVersion-3.0.0-SNAPSHOT.jar
ViaBackwards - https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-Abstraction/lastSuccessfulBuild/artifact/all/target/ViaBackwards-3.0.0-SNAPSHOT.jar
