### ISSUE TITLE
Internal server error on join

### ISSUE THREAD

**Issue by FarmVivi** [ViaVersion/ViaVersion#1779]
**Describe the bug, provide any errors**
After a while you can no longer join the server (for all people, even if you connect with another version) https://hastebin.com/jutodihoyi.md

**How can we reproduce it?**
1. Login on any version'

**Expected behaviour**
**screenshot done later with another minecraft client and with a different nickname**
![image](https://user-images.githubusercontent.com/19221621/82120525-14966080-9787-11ea-8a11-1a3549df5d70.png)
15s later:
![image](https://user-images.githubusercontent.com/19221621/82120531-2a0b8a80-9787-11ea-95ff-d4784b3bf040.png)
note that players already connected are not kicked

**ViaVersion Dump:**
https://dump.viaversion.com/0e23defe1fd79a08d1aa21f2fff88855fed9ed57fe0233a3cfe418ba373fc7be

**Additional server info**
I use Proxy (Travertine) logs: https://hastebin.com/sahicowuke.shell
GlobalLobby logs and dump inside: https://hastebin.com/ohogupemad.shell

after restarting the paper server we can connect again
It seems to me that the player "Itafi" connects in 1.9.4. But this problem arises however on the server "globallobby" while this one is in 1.8.
note that with winrar I modified the plugin.yml and bungee.yml files to replace the last 0 of 3.0.0-SNAPSHOT with the build number of the plugin for this case 3.0.83-SNAPSHOT (I need of this modification for my program which launches the minecraft server which before updates the plugins and for that it looks at the version in the file plugin.yml but for the developing versions of ViaVersion the value version: 3.0.0-SNAPSHOT does not change never)

**Comment by KennyTV** [comment]
The error is unrelated to Via, try removing other plugins to isolate the cause
