### ISSUE TITLE
[Abstraction] IOException: Packet 0/38 (oy) was larger than I expected, found 3 bytes extra whilst reading packet 38

### ISSUE THREAD

**Issue by apatuka** [ViaVersion/ViaVersion#1780]
**Describe the bug, provide any errors**
I did a checkout from abstraction branch and modified the supported protocols to support the snapshot version 20w20b, and show the error:
IOException: Packet 0/38 (oy) was larger than I expected, found 3 bytes extra whilst reading packet 38

**Additional server info**
Yes i use BungeeCord, added the same plugin on Auth Server and BungeeCord server

Looks like is not just to modifiy the protocol version support.

**Comment by KennyTV** [comment]
The version is not yet supported, there's an open pr

**Comment by Xernium** [comment]
Are you using a bungeecord that supports the snapshots even?
