### ISSUE TITLE
Told to post this here in the console

### ISSUE THREAD

**Issue by kwratone** [ViaVersion/ViaVersion#1781]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?
https://pastebin.com/LC2ay6bh

**How can we reproduce it?**
No clue, no one logged in, I looked at the console randomly and this popped up and it said to paste it here

**Expected behaviour**

**Screenshots**

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/2b9dc0089a53bcd77e929059b67db654381993fefe7c5275026a6ffd81a497a4

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
I have geyser installed

**Comment by FormallyMyles** [comment]
I believe this is an invalid ping packet or something like that and can be ignored.
