### ISSUE TITLE
Failed ID translations handled differently on 1.15 compared to other versions.

### ISSUE THREAD

**Issue by Steveice10** [ViaVersion/ViaVersion#1783]
I've been getting some issue tickets lately on my protocol library related to receiving -1 as the ID in Sound Effect packets. I've noticed that handling of sound effects that cannot be translated differs between 1.15 and older versions.

For example, here's 1.14 to 1.13.2, which uses a function that will warn and use 0 if a sound can't be translated: https://github.com/ViaVersion/ViaVersion/blob/master/common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/Protocol1_14To1_13_2.java#L294

By contrast, here's 1.15 to 1.14.4, which directly uses the SoundMapping function that can return -1: https://github.com/ViaVersion/ViaVersion/blob/master/common/src/main/java/us/myles/ViaVersion/protocols/protocol1_15to1_14_4/Protocol1_15To1_14_4.java#L37

While the client will silently accept this and use a default (I think), -1 technically is not a valid ID, and probably indicates a missing ID translation that should be fixed(?). I've also had an instance of a Spawn Mob packet with entity type -1, although I haven't delved into the entity packet code to figure out what the difference is there.

**Comment by KennyTV** [comment]
1.15 saw some sounds removed, so they are sent as -1. The referenced commit/pr will cancel sound packets with missing sound mappings
