### ISSUE TITLE
Crafting table recipes

### ISSUE THREAD

**Issue by SrLeojaco** [ViaVersion/ViaVersion#1785]
**I'M NOT REALLY SURE IF THIS CAN BE IMPLEMENTED, BUT IF POSSIBLE, I THINK IT WILL BE COOL**

**Describe the solution you'd like**
As known by everybody, in 1.12 the recipe book was introduced (https://minecraft.gamepedia.com/Recipe_book) which helps players crafting by using as guide. As requested by a player 1.12 on 1.8 server, would be possible to send **some kind of packet** whith all recipes when opening the crafting table (or the crafting inventory)?

When opening gui on server, the interface is shown, so it's only about of populating
![image](https://user-images.githubusercontent.com/16531305/82892269-7442f780-9f4f-11ea-9a1d-04971d8f63f2.png)

That way, if player is on 1.12, he could be able to use the "recipes".

**Which versions is this for?**
<1.12 servers

**Comment by FormallyMyles** [comment]
We don't really implement new features, if someone wants to make this we'll review it as an option. But otherwise it's better just to update your server and go backwards.

**Comment by JH3Y50N** [comment]
how implement it on a 1.8 server?

**Comment by DoctorMacc** [comment]
Actually, this is something that I've considered doing, as it would resolve a Geyser issue with pre-1.12 servers. From what I know about the ViaVersion structure, there's two things to consider:

- Do we store a JSON file of every recipe? Do we pull it from Spigot? If we store a JSON file, I suppose we'd need to categorize every recipe based on which protocol version it was available from.
- When do we send the packet? We'd likely have to call the function to send the packet after another packet is sent. Which packet should that be, for the cleanest implementation?

**Comment by Earthcomputer** [comment]
FYI, multiconnect does this, if you want a reference: https://github.com/Earthcomputer/multiconnect/blob/master/src/main/java/net/earthcomputer/multiconnect/protocols/v1_11_2/RecipeBookEmulator.java

**Comment by DoctorMacc** [comment]
Thank you!

**Comment by JH3Y50N** [comment]
> FYI, multiconnect does this, if you want a reference: https://github.com/Earthcomputer/multiconnect/blob/master/src/main/java/net/earthcomputer/multiconnect/protocols/v1_11_2/RecipeBookEmulator.java

Nice
