### ISSUE TITLE
desync issues

### ISSUE THREAD

**Issue by RemainingToast** [ViaVersion/ViaVersion#1786]
First things first, I use hacks, yes hacked client, cheats. I hope this doesn't affect the ability to fix this bug.
So the bug is desyncing issues so one of the hacks I use is auto totem this essentially places totem into your offhand every time you pop one. This works fine without via version but once via versions is installed the totem starts getting desynced, BUT this is not only an issue with client but even eating enchanted golden apples in vanilla is desynced and the only solution was removing this plugin. 

**How can we reproduce it?**
Idk how you would do it without hacks.... buts its the plugin causing the issue not the client.

**Expected behaviour**
No desync, golden apples and totems working as intended

**Additional server info**
Paper 1.12.2

**Comment by FormallyMyles** [comment]
Unless you can reproduce with a vanilla client there's gonna be no way for us to fix this.

Also, you're missing the dump + client version (for future issues or if you're able to replicate on vanilla)
