### ISSUE TITLE
[Suggestion]Disconnect.spam configs

### ISSUE THREAD

**Issue by CraftalotReloaded** [ViaVersion/ViaVersion#1789]
**Is your feature request related to a problem? Please describe.**
It's related to the disconnect.spam issue
This disconnect.spam has never worked correctly and can kick users for running a single command.

**Describe the solution you'd like**
Add a config to lower the likelihood of it kicking someone or completely disable this feature.

**Describe alternatives you've considered**
There are none i could find/think off.

**Which versions is this for?**
All from 1.8 to 1.15.2

**Comment by FormallyMyles** [comment]
There is a new config option, in the abstraction versions on ci.viaversion.com

**Comment by CraftalotReloaded** [comment]
Sry, but even with that version i cannot find a config for it, even after renewing the config.
