### ISSUE TITLE
Abstraction build doesn't include new config as stated in #1789

### ISSUE THREAD

**Issue by CraftalotReloaded** [ViaVersion/ViaVersion#1790]
The abstraction build(ViaVersion-3.0.0-SNAPSHOT.jar) doesn't generate any new configs even when renewing the config by deleting it so i cannot fix my issue i stated in https://github.com/ViaVersion/ViaVersion/issues/1789

**Comment by FormallyMyles** [comment]
Why are you creating new issues when you could have just replied to the last one?

https://github.com/ViaVersion/ViaVersion/blob/abstraction/common/src/main/resources/assets/viaversion/config.yml#L118

**Comment by CraftalotReloaded** [comment]
My apologies, i didn't know if you'd keep an eye on already closed issues so i made a new one to be safe.
With that said, that config does not solve this issue.

**Comment by FormallyMyles** [comment]
@CraftalotReloaded What have you tried? Have you considered joining our discord for support?

If it's for spam then you can (choose one):
1. Update ViaVersion (pinned) and delay the tab complete (5 is suggested) in the ViaVersion config 1_13-tab-complete-delay: 5,
2. Disable tab complete for 1.13.x and up users in the ViaVersion config disable-1_13-auto-complete: true,
3. If you are using Paper 1.12.2 or higher, you can change the spam limits in the paper.yml config.

**Comment by CraftalotReloaded** [comment]
1)ViaVersion is already latest
2)Tab complete is already disabled, the kick results from running commands, not the tab complete
3)We are not using 1.12.2 or higher or paper

**Comment by FormallyMyles** [comment]
Then you need to provide more info for what you're being kicked for

**Comment by CraftalotReloaded** [comment]
Running any command can result in this and will give disconnect.spam as the reason

**Comment by FormallyMyles** [comment]
> Running any command can result in this and will give disconnect.spam as the reason

You need to provide more info, /viaversion dump and steps to replicate on a clean server without other plugins.
