### ISSUE TITLE
Players get kicked when using version above or below 1.12

### ISSUE THREAD

**Issue by ItsAloof** [ViaVersion/ViaVersion#1791]
**Describe the bug, provide any errors**
Whenever players are on my server for a certain amount of time they get kicked or whenever they use a command to either go to spawn or an island they get kicked. The error given is: https://hastebin.com/rufakohupe.md

**How can we reproduce it?**
I am using Spigot-1.12.2
I am only using EssentialsX along with ViaVersion, ViaRewind, and ViaBackwards
It happens I suspect when players teleport to a different world it seems so far and according to some players when they stay connected to the server for a little while.

**ViaVersion Dump:**
https://dump.viaversion.com/3c528aedae9ec7855408b2c2458770d948d076f3ce7b097a868ed4317f38a24b

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
I am testing on a Test server running on my own PC using BungeeCord and just connecting to the Spigot server but have another server running with a host that has the same exact problem but runs using BungeeCord

**Comment by FormallyMyles** [comment]
The hastebin linked is blank for me, can you reupload?

What client versions does this happen on?

**Comment by ItsAloof** [comment]
I couldn't get Hastebin to work for some reason so here is a Pastebin link: 
https://pastebin.com/FfFJa3Zs

and I was using 1.8.9 Optifine_HD_U_17
but it seems to work fine with versions above 1.12 so I think it is just versions below 1.12 from what I can tell with testing different versions

**Comment by KennyTV** [comment]
Update all Via plugins to the following versions, specifically ViaBackwards is heavily outdated
ViaVersion - https://ci.viaversion.com/job/ViaVersion-Abstraction/lastSuccessfulBuild/artifact/jar/target/ViaVersion-3.0.0-SNAPSHOT.jar
ViaBackwards - https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-Abstraction/lastSuccessfulBuild/artifact/all/target/ViaBackwards-3.0.0-SNAPSHOT.jar
ViaRewind - https://ci.viaversion.com/view/ViaRewind/job/ViaRewind-DEV/lastSuccessfulBuild/artifact/all/target/ViaRewind-1.5.0-SNAPSHOT.jar
