### ISSUE TITLE
Getting kicked when switching between worlds

### ISSUE THREAD

**Issue by KillauraHacks** [ViaVersion/ViaVersion#1792]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?
Whenever I try to switch between my skyblock world and my spawn world I get disconnected: [](https://hastebin.com/esixuzajek.css )
**How can we reproduce it?**
1. Log in with 1.12 
2. Im using latest version of via version and an edited askyblock file: https://www.mediafire.com/file/ehsmj6dbpwjfeub/ViaVersionBug_Plugins.zip/file
3. Switch between the main world and the island world and you get kicked

**Expected behaviour**
I expect to be able to switch between my skyblock world and my spawn world without being disconnected 
**Screenshots**
![image](https://user-images.githubusercontent.com/29743840/83778329-2e251c80-a650-11ea-9a3b-5025986de102.png)

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/af4f284718eca29f3746794d94d2238c776f3fcfe8c87fd86bd43660e5fdd62b
**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
PaperSpigot (1.12-R0.1-SNAPSHOT)

**Comment by FormallyMyles** [comment]
Use the abstraction versions then test

ViaVersion - https://ci.viaversion.com/job/ViaVersion-Abstraction/lastSuccessfulBuild/artifact/jar/target/ViaVersion-3.0.0-SNAPSHOT.jar
ViaBackwards - https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-Abstraction/lastSuccessfulBuild/artifact/all/target/ViaBackwards-3.0.0-SNAPSHOT.jar
ViaRewind - https://ci.viaversion.com/view/ViaRewind/job/ViaRewind-DEV/lastSuccessfulBuild/artifact/all/target/ViaRewind-1.5.0-SNAPSHOT.jar

**Comment by KillauraHacks** [comment]
> Use the abstraction versions then test
> 
> ViaVersion - https://ci.viaversion.com/job/ViaVersion-Abstraction/lastSuccessfulBuild/artifact/jar/target/ViaVersion-3.0.0-SNAPSHOT.jar
> ViaBackwards - https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-Abstraction/lastSuccessfulBuild/artifact/all/target/ViaBackwards-3.0.0-SNAPSHOT.jar
> ViaRewind - https://ci.viaversion.com/view/ViaRewind/job/ViaRewind-DEV/lastSuccessfulBuild/artifact/all/target/ViaRewind-1.5.0-SNAPSHOT.jar

that worked thanks :)
