### ISSUE TITLE
Big error on Viaversion

### ISSUE THREAD

**Issue by HyCore** [ViaVersion/ViaVersion#1794]
**Describe the bug, provide any errors**
I was launching bungeecord to connect on my server. Player can join without any problem without the bungee. But when a player try to join. It's just not possible due to this error:
https://hastebin.com/ojabujoluf.bash

**How can we reproduce it?**
1. Use a 2bored2wait proxy to make player never disconnect if there is a client crash.'
2. Connect the player on this proxy on 1.14.4. Everything work fine. Disconnect normaly
3. Launch the bungee with viaversion though the proxy 2bored2wait, and you will get this error every time a player try to connect on the bungee.

**Expected behaviour**
Without problem. The player sucessfully connect, and can play, see chunk, interact...

**ViaVersion Dump:**
https://dump.viaversion.com/872082c24f291ee0d922ed032fe84afe0ccec2e638de0856088b36f35e4dce9b

**Additional server info**
bungeecord, no plugins exept viaversion, rex, everything work fine in 1.12.2 but in 1.14.4 it didn't.

**Comment by FormallyMyles** [comment]
Try abstraction builds https://ci.viaversion.com/job/ViaVersion-Abstraction/

Otherwise try moving from Bungee to backend servers.

**Comment by FormallyMyles** [comment]
Closing see above, otherwise gonna need error repastebin'd
