### ISSUE TITLE
abstraction branch: Clientside (1.15.2) entity attribute error connecting to 1.12.2 Sponge server thru Bungee

### ISSUE THREAD

**Issue by zml2008** [ViaVersion/ViaVersion#1803]
**Describe the bug, provide any errors**

On the client I'm getting https://paste.gg/p/anonymous/f0bc3941fa1640a79f5d56ba194a5fe8 spammed in my log. Most of the errors come through when I'm switching to the sponge server from another server on the proxy.

I'm not getting those errors connecting to a 1.15.2 server, or using a 1.12.2 client to connect to the Sponge server, so I'm suspecting Via's involved

**How can we reproduce it?**
1. Connect to the server, walk around.

**Expected behaviour**
no client error

**Screenshots**
n/a, nothing unexpected is visible

**ViaVersion Dump:**
https://dump.viaversion.com/0d7db7058ae7cb33b1505d7d377c484fc4291dbdd9574e1cc63ba76c154464c1
**Additional server info**

Proxy is Waterfall build 346 -- haven't tested without proxy

**Comment by KennyTV** [comment]
This is a client bug https://bugs.mojang.com/browse/MC-166607 when it receives attributes it doesn't know about/have no default set. It would be kind of noisy for us to fix this, adding a handler a few protocol transformer to filter out the non-defaults, or just mapping default attributes to every single entity in the first place.

It would probably be best to to that once in a Sponge mod through mixins before entity attributes are sent (check if the client is on a higher version and filter out custom attributes)... Or kill the mod sending those wrong?/custom attributes 😛

**Comment by zml2008** [comment]
ah fun -- i don't think i have any modded attributes that would cause trouble, but seeing as you've investigated the underlying issue and it's mitigated in 1.16 i'm satisfied -- thanks!
