### ISSUE TITLE
Server ping returning protocol -1

### ISSUE THREAD

**Issue by Baterka** [ViaVersion/ViaVersion#1804]
Server ping returning protocol -1, so many voting websites think, that server is running the lowest possible Minecraft Version (mostly 1.8)...

Can this be changed to the highest possible version? So voting/list sites will show always the newest possible version in their listings?

I am not sure where this stuff is happening in code.

**Comment by FormallyMyles** [comment]
It is up to the ping website to check the newest version etc. There are sites which do this, ViaVersion does this for compatibility with other protocol related software.

You can modify this, it's in BaseProtocol or just write a protocollib plugin / use a serverlist plugin.
