### ISSUE TITLE
Server crash | ConcurrentModificationException

### ISSUE THREAD

**Issue by Callahhh** [ViaVersion/ViaVersion#1811]
**Describe the bug, provide any errors**

A CME is thrown and instantly crashes the server, https://pastebin.com/CkJ4meHV. 

I updated a couple of servers from ViaVersion 2.2.3 to the new abstraction version & replaced an archaic ProtocolSupport version with ViaRewind in the process, no issues w/ crashing.  

However, I went to replace ViaVersion 2.2.3 to the new abstraction version on my Kit server without replacing the archaic ProtocolSupport version (having anticheat issues while using ViaRewind for some reason, no idea why 😢 ) and it instantly crashes upon logging in with the error above. Reverting back to ViaVersion 2.2.3 from the abstraction version fixed the issue.
 
**ViaVersion Dump:** 
https://dump.viaversion.com/74ec7c090546ba0732ff468278810ff4a2698a898b164c94289f27651b47feac
This is from a test server with the same setup, I had players waiting and I didn't think to run viaversion dump at the time.. sorry :(
**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
Yes, Travertine. also mServer which is a custom fork of "PaperSpigot" 1.8 with some optimizations/changes to fit our needs.

**Comment by KennyTV** [comment]
Should be fixed again with https://github.com/ViaVersion/ViaVersion/commit/b0816b1ce62adcda842e14d9b2004ad6da145b95
