### ISSUE TITLE
1.16 Player Skulls appear as Steve skin

### ISSUE THREAD

**Issue by Sneakometer** [ViaVersion/ViaVersion#1816]
**Describe the bug, provide any errors**
All Playerheads in the world (placed) show as Steve.
Skulls in inventories are not affected.
I'm Running a 1.8 Waterfall/Paper Server with latest ViaVersion. 

**How can we reproduce it?**
1. Start server on paper 1.8 with latest ViaVersion
2. Login on 1.16
3. Look at player Skulls.

**Expected behaviour**
Display Playerheads with thier skins.

**Screenshots**
First screenshot captured with 1.15
![Download](https://user-images.githubusercontent.com/50603525/85421928-4dd7a280-b575-11ea-80e8-489338099cb6.png)
Second screenshot captured with 1.16 (same server)
![Download (1)](https://user-images.githubusercontent.com/50603525/85421970-5c25be80-b575-11ea-893b-3ff915bd8877.png)

**ViaVersion Dump:**
https://dump.viaversion.com/7772a617930aa03d794be559f3084552c19bd0b3b887ab54885a36fd2ec2fd04

**Additional server info**
Waterfall version git:Waterfall-Bootstrap:1.15-SNAPSHOT:265e719:349 (latest)
PaperSpigot-4c7641d (MC: 1.8.8) (i think latest?)
ViaVersion 3.0.0 (latest)
Minecraft 1.16 (vanilla, no forge/mods)

**Comment by KennyTV** [comment]
I can't reproduce this with either uuid id or name, can you send us a command to get the skull so we might reproduce it as well (or even better dump its nbt)?

**Comment by Sneakometer** [comment]
I can a 100% reproduce this with every player skull. Tried it again on a non bungee setup, plain paper 1.8 and ViaVersion 3.0.0 and still the same issue.
Just use this command to give yourself a playerhead and place it somewhere:
`/give @p minecraft:skull 1 3 {SkullOwner: "player_name"}`
Maybe it has something todo with your/my configuration? If so, mine is in the dump above.

Also recorded a video showing the issue:
https://www.youtube.com/watch?v=QXxiKctEb0E

**Comment by alexmarkey** [comment]
We are also able to reproduce this bug on our network.
