### ISSUE TITLE
1.16 tellraw and bossbar,  scorebored selector visual bug

### ISSUE THREAD

**Issue by Tom12710** [ViaVersion/ViaVersion#1817]
**Describe the bug, provide any errors**
so i log on with 1.16, connect to 1.15.2 server and usualy have displays with selectors with scorebored ,boss bar , action, tellraw. would not display number used in selectors and did not and i move to single player it displayed but when on multiplayer server with viva version it does not display what it should.

**How can we reproduce it?**
login as 1.16 client and join 1.15 server 
/scoreboard objectives add hello minecraft.custom:minecraft.walk_one_cm
wall a bit,
run command /title @a actionbar ["",{"selector":"@a"},{"text":"    "},{"score":{"name":"@a","objective":"hello"}}]
number should display but does not when connect to 1.15.2 server on 1.16 client 	

**Expected behaviour**
Supposed of displayed scorebored number in boss bar 

**Screenshots**
![bug](https://user-images.githubusercontent.com/36133765/85422641-ba4ea380-b56d-11ea-8ab8-8a484c7f5e23.png)
Top is 1.16
Bottom is 1.15.2

**ViaVersion Dump:**
https://dump.viaversion.com/0f3ca98dcf93f62eca774ae405023e83b56d5d626974ef6940397ef22a7034e7

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
spigot 1.15.2

**Comment by KennyTV** [comment]
Hmm apparently the actual values have to be sent by the server within the chat component. A fix _could_ be possible with a bit of work to get them in the Bukkit module, but that's probably a bit further behind on the priority list
