### ISSUE TITLE
Changed message keys

### ISSUE THREAD

**Issue by SirKillian** [ViaVersion/ViaVersion#1818]
**Describe the bug, provide any errors**
Death messages are not displaying correctly.
No errors in the console

**How can we reproduce it?**
1. Login on 1.16
2. Join a 1.15.2 server
3. die from a mob

**Expected behaviour**
The entity name should be formatted properly.

**Screenshots**
![DeathMessage](https://user-images.githubusercontent.com/19877696/85423860-82e4f480-b577-11ea-95ff-429269ff1e69.png)

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/a0b0d3c0c6cf4fa7e0bb508af91d69664c38b48632273b967bd54dd9cc9f5e42

**Comment by KennyTV** [comment]
That's only for pigmen, right?

**Comment by SirKillian** [comment]
From my testing, yes.
I assume this is because "Zombie Pigman" has been renamed to "Zombified Piglin" in 1.16

**Comment by KennyTV** [comment]
Also changed: `block.minecraft.bed.set_spawn`
