### ISSUE TITLE
1.16 Client inventory click issue

### ISSUE THREAD

**Issue by Dablakbandit** [ViaVersion/ViaVersion#1823]
**Describe the bug, provide any errors**
When opening another inventory gui via clicking, a weird issue occurs where the client appears to attack click in the background.

Viaversion could be taking the inventory click and seeing an 'inventory isnt open' and causing an animation packet to be sent to the user?

**How can we reproduce it?**
1. Login to 1.16
2. Join au.minescape.me and go to world 1
3. Click the skills icon in your inventory

**Expected behaviour**
Inventory opens without hand moving

**Screenshots**
https://i.imgur.com/PeVSPRR.gif

**ViaVersion Dump:**
https://dump.viaversion.com/8868768b7da89ed5292e0a75b05fdf108fbdc8af3aa8eb52bc0759235dcd7793

**Additional server info**
Should all be in the dump for the bungeecord.

**Comment by KennyTV** [comment]
As far as I know client behaviour we cannot change.
