### ISSUE TITLE
ViaVersion not running properly with Paper and Protocol Support

### ISSUE THREAD

**Issue by ninjaman808** [ViaVersion/ViaVersion#1825]
We're currently running ViaVersion's Build #406 with Paper 1.15.2 Build #365 and Waterfall 1.16 Build #350. 

Here's our config: https://pastebin.com/raw/fMU2qF5m

We keep getting this error: https://pastebin.com/raw/drjL20F2

This is solved by removing ProtocolSupport Build #498. 

I understand that PS only works with Via on Paper, which is why I'm confused as to why we're getting this error, as we are currently running on Paper.

**Comment by FormallyMyles** [comment]
Can you provide `/viaversion dump` for this?

**Comment by Hyronymos1337** [comment]
same issue here

viaversion dump: https://dump.viaversion.com/fe6c1780d5a9889f1192b9b5dbcc8a9e4d519eb013abd1e01e19e011a0d6c1ca
