### ISSUE TITLE
Furnace Smelting on 1.16 Client Crashes Game 

### ISSUE THREAD

**Issue by TechnoVisionDev** [ViaVersion/ViaVersion#1827]
**Describe the bug, provide any errors**
Using a furnace when logged into a 1.16 client on a non-1.16 server causes the user's game to crash. This seems to happen to every single player on my server when they are on a 1.16 client. The issue does NOT seem to happen if you are on a <1.15.2 client.

**How can we reproduce it?**
1. Login on 1.16'
2. Smelt something in a furnace
3. The game will crash

**ViaVersion Dump:**
https://dump.viaversion.com/a17349af6cb17f6360ccc5d8d35acdee6348aa58caaa0b1f894632ba728a1f03

**Additional server info**
Using a Bungee fork called FlameCord as a proxy for a 1.8.8 ImanitySpigot2 server.
Currently on the newest ViaVersion 3.0.0 and ViaRewind 1.5.0

**Comment by KennyTV** [comment]
Update ViaVersion to its latest build on ci.viaversion.com
