### ISSUE TITLE
Error on player login

### ISSUE THREAD

**Issue by JohnS19** [ViaVersion/ViaVersion#1828]
I am using the 1.16 version and I seemed to have encountered an error when a player logged in. I believe this player logged in with version 1.14.4. The error told me to report it here.

**Describe the bug, provide any errors**
Player logged in and this error popped up. 
https://hastebin.com/ohivilorof.cs

**How can we reproduce it?**
Not completely sure, but related to 1.14.4 & 1.15

**Expected behaviour**
No error

**Additional server info**
Server Software: Tuinity

**Comment by KennyTV** [comment]
Update ViaBackwards to its latest build on ci.viaversion.com
