### ISSUE TITLE
Blocks modified (client sided)

### ISSUE THREAD

**Issue by Sikatsu** [ViaVersion/ViaVersion#1829]
**Describe the bug, provide any errors**
With a 1.16 client, my spawn is broken, with a 1.15.2 client everything looks fine.

**Screenshots**
This is how it looks on 1.16
![image](https://user-images.githubusercontent.com/5664135/85524227-431a1d80-b608-11ea-998d-389470d26209.png)

This is how it looks on 1.15.2
![image](https://user-images.githubusercontent.com/5664135/85524662-a7d57800-b608-11ea-838f-c9f4f075c245.png)

**ViaVersion Dump:**
https://dump.viaversion.com/24ec84f51418936a8751e322abda8fb930c0cd40724a5bf43409a3866060a6d6

**Additional server info**
ViaVersion is installed on the proxy only.

**Comment by FormallyMyles** [comment]
Would you be able to try ViaVersion just on the backend and see if the issue still happens?

**Comment by Sikatsu** [comment]
Same result:

![image](https://user-images.githubusercontent.com/5664135/85525793-b2dcd800-b609-11ea-8f9a-e71cdb4b83e1.png)

**Comment by KennyTV** [comment]
Can you try on a testserver without any other plugins, just not that?

**Comment by Sikatsu** [comment]
So, basically try to remove all plugins other then ViaVersion and see if it still happens?

**Comment by KennyTV** [comment]
Yep

**Comment by Sikatsu** [comment]
![image](https://user-images.githubusercontent.com/5664135/85539272-efaecc00-b615-11ea-9965-062008511396.png)

**Comment by KennyTV** [comment]
is that without Bungee plugins as well?

**Comment by Sikatsu** [comment]
That is correct. And as for what I can see, this only happens in this particular build. In other server builds it does not happen.

**Comment by KennyTV** [comment]
Well last thing to check would be using a standard Paper and a standard Waterfall build, else there's not really another trace since you seem to be the only person with that problem at the moment

**Comment by Sikatsu** [comment]
Isn't that what I am using? Both the latest version of paper and waterfall are installed. I am not sure why it happens, certain blocks look like the new blackstone walls too.

**Comment by KennyTV** [comment]
Oh I confused this with someone using Tuinity, sorry. But try the latest non-1.16 Waterfall build, since that's more of a temporary support thing

**Comment by Sikatsu** [comment]
Ah, I also mentioned this issue yesterday on the discord while I was still using the non 1.16 waterfall build, I was hoping the 1.16 waterfall build would make a change perhaps so I waited with making a github issue until then.

I can break it and it disappears, I can replace it just fine too with for example stone

**Comment by Sikatsu** [comment]
If I right click on all blocks that are wrong, they turn into what it should be...

**Comment by Sikatsu** [comment]
Noteblocks are trap doors or brick slabs
Stone slab are red sandstone walls
Air is blackstone walls?

**Comment by FormallyMyles** [comment]
If you schematic the build and paste it does it still happen?

Also, does this happen if you use blocks in the build (might need to relog to check this, as it might be a bug at chunk data level)?

**Comment by Sikatsu** [comment]
It seems to have the same affect when I repaste it, when I right click the blocks that are wrong, they turn into what it should be. It's client sided, and only in this build, no other builds are affected. I do not understand why it happens though. It looks kinda bad too, for any new player that joins our network.

**Comment by KennyTV** [comment]
Should be fixed with https://github.com/ViaVersion/ViaVersion/commit/50024b0602eed14b2afeca385c19e8b6ec489e3c in the -Dev builds
