### ISSUE TITLE
Server doesn't send all tags to the client

### ISSUE THREAD

**Issue by Earthcomputer** [ViaVersion/ViaVersion#1830]
**Describe the bug, provide any errors**
Server doesn't send all tags to the client, resulting in a client crash if ever a client-side mod tries to access them.

**How can we reproduce it?**
1. Install multiconnect on the client, which comes with an assertion that all vanilla tags are present on the client.
2. Connect to a 1.15.2 or earlier viaversion server.

**Expected behaviour**
The client does not crash

**Screenshots**
N/A

**ViaVersion Dump:**
N/A (aka too lazy, let me know if it's needed)

**Additional server info**
N/A

Clones https://github.com/Earthcomputer/multiconnect/issues/59

**Comment by KennyTV** [comment]
Eh wasn't too fond of adding every single tag since 1.9 up there, I suppose adding the ones listed in the crash as empty tags should suffice?

**Comment by Earthcomputer** [comment]
The ones listed in the crash are all the missing tags. Having them empty would be perfectly fine :)
