### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Volgeop** [ViaVersion/ViaVersion#1831]
**Describe the bug, provide any errors**
Hi, there is error when player with 1.16 join the 1.15.2 server. Look at this: https://pastebin.com/MHQGqjSv and https://imgur.com/a/4bTtlnd

**How can we reproduce it?**
1. Login on 1.16'
2. Join server
3. You will be kicked with following message and the following text will be printed into console

**Expected behaviour**
It should normally join player.

**Screenshots**
https://imgur.com/a/4bTtlnd

**ViaVersion Dump:**
https://dump.viaversion.com/53928acc1120e702cf4e126f4486d05ef6195e4c5c15130874d15d2270329203

**Additional server info**
I'm using Waterfall and plugins are in dump.

**Comment by KennyTV** [comment]
Update to the latest build on ci.viaversion.com
