### ISSUE TITLE
DecoderException: IOException: Packet 1/0 (PacketStatusInStart)

### ISSUE THREAD

**Issue by Schneidertm** [ViaVersion/ViaVersion#1832]
**Describe the bug, provide any errors**

https://hastebin.com/yowupiqaca.cs
Full serverlog: https://pastebin.com/VhUaHiBi

**How can we reproduce it?**
Once started with ViaVersion 3.0.0 the errors appear. So no real reproduction. 

**ViaVersion Dump:**
 https://dump.viaversion.com/3bbab454ec00f60850d7afc818f4343d99eab57b9fa5631179828e2e52ebc018

**Additional server info**

Java 1.8.0_211
git-Paper-371 (MC: 1.15.2)

Plugins:
AsyncWorldEdit, AutoMessage, bChatManager, ChunkSpawnerLimiter, ColoredSigns, CommandBook, CraftBook, DiscordSRV, dynmap, Fe, LogBlock, LogBlockQuestioner, LWC, MagicCarpet, MCBans, mcMMO, mcMMOAction, MiniGuard (private), MiniLog (private), Multiverse-Core, Multiverse-Portals, OpenInv, PandaWire, PermissionsEx, ProtocolLib, QuickShop, RedstoneClockDetector, SignRewards (private), Spartan, TitleManager, VanishNoPacket, Vault, Votifier, WorldBorder, WorldEdit, WorldGuard, xInventories, ZHorse

**Comment by KennyTV** [comment]
Not Via related, we only caused the printing of an otherwise suppressed Netty codec exception. We will limit the printing to only Via related errors in a future release.
