### ISSUE TITLE
1.15.2 clients stuck on loading terrain

### ISSUE THREAD

**Issue by calumari** [ViaVersion/ViaVersion#1834]
**Describe the bug, provide any errors**
1.15.2 clients stuck on "Loading terrain..." when changing servers to world with differing dimension. 

**How can we reproduce it?**
1. Login on 1.15.2
2. On server 2, position yourself in any dimension but the Nether. On server 1, position yourself in the Nether.
3. From either server, swap to the other.

**Expected behaviour**
Player should change to server 2. However, is stuck on "Loading terrain..." until they force quit their client.

**Screenshots**
https://streamable.com/1nl0x0

**ViaVersion Dump:**
https://dump.viaversion.com/bcee99e6938cdc2ef337f2ee3b5eb587d5cdae4346e01016cecb8b061c8686e2

**Additional server info**
Waterfall (build 357)
Conduit (Paper fork based on build 371)

Unable to replicate on a 1.16.1 client.

**Comment by calumari** [comment]
Unable to replicate when changing servers with dimensions nether to nether.

**Comment by calumari** [comment]
I noticed the issue wasn't happening on our creative server where we do some tricky with dimensions. 
```
        ProtocolLibrary.getProtocolManager().addPacketListener(new PacketAdapter(this, ListenerPriority.NORMAL, PacketType.Play.Server.LOGIN) {
            @Override
            public void onPacketSending(PacketEvent event) {
                event.getPacket().getDimensions().write(0, -1);
            }
        });
```
The code above negates this issue.

**Comment by KennyTV** [comment]
ViaVersion does not change protocol of the same server version, this is likely a bug in Bungee (since it's dimension handling has become quite bork when they tried to adapt it to 1.16)
