### ISSUE TITLE
Large Chest Visual Tearing 

### ISSUE THREAD

**Issue by TechnoVisionDev** [ViaVersion/ViaVersion#1836]
**Describe the bug, provide any errors**
When running a 1.8.8 server and connecting on any version 1.15.2 or higher, large chests (two chest next to each other) turn into two regular chests side by side. The actual inside of the chest is fine and store items great, but obviously this is not normal behavior and, when placing blocks near the chest, the texture starts to tear or become invisible.

**How can we reproduce it?**
1. Login from a 1.15.2 or greater client and place 2 chests next to each other'
3. You will notice the visual tearing and block placement issues.

**Expected behaviour**
Two chests next to each other should form a large chest.

**Screenshots**
https://imgur.com/a/3BPefTG

**ViaVersion Dump:**
https://dump.viaversion.com/51e2079ea2c2b00a2b06426fea69f894ff1e8a502d1dc16daac08f1683367261

**Additional server info**
FlameCord proxy, ImanitySpigot2 1.8.8 server using ViaVersion and ViaRewind

**Comment by KennyTV** [comment]
Enable `serverside-blockconnections`

**Comment by moribellamy** [comment]
IDK if this is related, but i was experiencing invisible chests on 1.15.2 server on the new 16.1 client. i _disabled_ serverside-blockconnections and it seemed to work. or maybe i just got lucky
