### ISSUE TITLE
Bed Spawn Point Message Displays Incorrectly

### ISSUE THREAD

**Issue by NikoEatsPancakes** [ViaVersion/ViaVersion#1837]
**Describe the bug, provide any errors**
When using a bed to change your respawn point using a 1.16.1 client on a 1.15.2 server, instead of the proper "Respawn point set" message, the chat shows "block.minecraft.bed.set_spawn"

**How can we reproduce it?**
1. Log in to a 1.15.2 server using a 1.16.1 client
2. Right click a bed to set your spawn point
3. The message will appear in chat

**Expected behaviour**
Proper respawn point message in chat

**Screenshots**
https://i.imgur.com/GaalDfv.png

**ViaVersion Dump:**
https://dump.viaversion.com/8c0e68b0ed1ee3a1c8d6ff6cac1955062f8d1b957bf2c5370df489033797acc7

**Additional server info**

No proxy, on a Tuinity build from March.

**Comment by KennyTV** [comment]
Related to #1818
