### ISSUE TITLE
1.12.2 Silverfish Stone Unbreakable on Newer Clients

### ISSUE THREAD

**Issue by jakkuh** [ViaVersion/ViaVersion#1841]
**Describe the bug, provide any errors**
When on a 1.12.2 base server, and connected with a 1.15.2 client (I think it happens on any 1.13+ clients), trying to mine silverfish stone with Efficiency 5 and Haste 2 will not work.

https://gfycat.com/enormousentirebarasingha

**How can we reproduce it?**
1. 1.12.2 base server, 1.15.2 client
2. haste 2 potion or beacon + efficiency 5 diamond pickaxe
3. Mine silverfish stone, and it will not break.

**Expected behaviour**
The stone should break.

**Screenshots**
https://gfycat.com/enormousentirebarasingha

**ViaVersion Dump:**
https://pastebin.com/raw/hktUh4P4

**Additional server info**
We use a Waterfall proxy, ViaVersion runs on the backend servers.

`fix-infested-block-breaking: true` in our confug

**Comment by KennyTV** [comment]
Sadly not possible, since the 1.15 client expects to instantly break infested stone. With the config option, it's remapped to normal stone, so that it at least works with simple tools/with the hand, otherwise we'd have to map it to something ridiculous like colored wool
