### ISSUE TITLE
You are running a newer version than is released!

### ISSUE THREAD

**Issue by Higgins4k** [ViaVersion/ViaVersion#1847]
So I'm working on updating everything and downloaded Via Version 3.0.1 when it was released and it gives me a warning that it is a newer version than is released while starting the server.

Works fine from what I can tell just wanted to put it in.
https://dump.viaversion.com/70dd8411942016dc4d1402d520e4ecff962e240ddd502a59df6b9223cc90ee89

**Comment by FormallyMyles** [comment]
This is just a cache issue with our updater
