### ISSUE TITLE
Error, Idk what caused it

### ISSUE THREAD

**Issue by daoshii** [ViaVersion/ViaVersion#1848]
**Describe the bug, provide any errors**
https://pastebin.com/y8fPCGaT

**How can we reproduce it?**
I have no idea

**ViaVersion Dump:**
https://dump.viaversion.com/fb6da54f191a752af8cf40290262edd749f8e63e2294dd424c3c69024578dabb

**Additional server info**
Paper 1.15.2 build 372 standalone, no bungee

**Comment by FormallyMyles** [comment]
This is someone sending bad data to your server most likely, you can firewall them if the errors are an issue.
