### ISSUE TITLE
ViaVersion 3.0.1 causing JVM crashes on Paper 1.12.2 using Java 11.

### ISSUE THREAD

**Issue by FrozenBeard** [ViaVersion/ViaVersion#1849]
**Describe the bug, provide any errors**
After lots of trial and error, I've figured out the JVM crashes ive been getting recently were after updating ViaVersion to 3.0.1 on my paper 1.12.2 server.

We released a mythic mobs/lib's disguises event, and we were getting thousands of errors with lib's disguises and packets (After updating ViaVersion to 3.0.1), so I removed both plugins and we were still getting JVM crashes, removed ViaVersion 3.0.1 and were fine.

**How can we reproduce it?**
1. Login on 1.12.2'
2. Play normally.
3. Will create a JVM crash.

**ViaVersion Dump:**
I removed ViaVersion to fix it.

**Additional server info**
I use Waterfall Bungee, My creative is still using ViaVersion 2.2.3, but survival I fully removed ViaVersion to see if that was the cause of the crashes.

After reading the forums, I notice people are having issues with ProtocolLib, which is required for Matrix/CMI/ChatControl Pro, is this the cause of the JVM crashes? incompatibility 

I do not feel comfortable having to send hs_err_pid/Crash reports Public, is there someone on the ViaVersion team I can send them directly?

**Comment by FormallyMyles** [comment]
There are plenty of people using Java 11 and ViaVersion together (even later versions) unless you can provide stack traces which directly reference to ViaVersion I suspect the conflict is elsewhere.

That being said there's not too many places where we could cause issues like this. You're welcome to send the crash report on Spigot but most of the time they're pretty complicated to diagnose the root cause.

**Comment by FrozenBeard** [comment]
@FormallyMyles I assume you assumed the issue based off the title, that is not what I reported at all, merely extra information. 
Nowhere even close to what I reported.

**Comment by krusic22** [comment]
You didn't prove a ViaVersion dump link nor a crash log, so it's really hard to get anything from that. 
Anyway you can send the logs directly to the devs on Discord.

**Comment by FormallyMyles** [comment]
> @FormallyMyles I assume you assumed the issue based off the title, that is not what I reported at all, merely extra information.
> Nowhere even close to what I reported.

In addition to what krusic said, we never have any reports of JVM crashes. You should ensure your ProtocolLib is up to date as there has been conflicts with them and us which have been recently resolved but not JVM crashing.

And again to reiterate what krusic said we don't have anything to go on without logs.

**Comment by FrozenBeard** [comment]
@FormallyMyles As I said in the original post, I need to know who to send them too, so there not public.

**Comment by FormallyMyles** [comment]
> @FormallyMyles As I said in the original post, I need to know who to send them too, so there not public.

krusic stated "Anyway you can send the logs directly to the devs on Discord."

and I originally wrote "You're welcome to send the crash report on Spigot but most of the time they're pretty complicated to diagnose the root cause."

**Comment by FrozenBeard** [comment]
Update I think this was because i was using an outdated version of protocollib, I updated to protocollib 4.5.1 and I havent had any crashes in the last 24h of re-enabeling ViaVersion, If im using 1.12.2 server what version of protocollib should I be using?

**Comment by FormallyMyles** [comment]
I'd suggest looking at their website for that. Unless specified probably the latest.
