### ISSUE TITLE
Major problem! Players cannot pickup items from ground

### ISSUE THREAD

**Issue by Baterka** [ViaVersion/ViaVersion#1850]
**Describe the bug, provide any errors**
From version 3.0.0 (or first version what supports 1.16) there is a problem with item pickups, tridents not returning etc...

Players randomly reporting that they are unable to pickup items from ground. This seems like major problem!

**How can we reproduce it?**
It does not matter if player using 1.15 or 1.16 client.
I was unable to reproduce it, because it seems completely random.
But I see that players stay on block and they are unable to pickup.

**Expected behaviour**
Obvious... Players should be able to pickup items from ground and tridents should return to inventory too.

**Comment by KennyTV** [comment]
Please follow the issue template. If this happens on the same client as server version, this is not a Via issue.

**Comment by Baterka** [comment]
I followed template and it is Via issue... Server running fine without Via...

**Comment by Baterka** [comment]
@KennyTV I added dump. Reopen this issue please it is surely ViaVersion/ViaBackwards problem.
On older versions it is not hapenning.

**Comment by KennyTV** [comment]
On older versions means it's actually modified by ViaBackwards, but since all of your servers are 1.15 and you say it happens with 1.15 clients, this will very likely be caused by Bungee/another plugin

**Comment by Baterka** [comment]
So tell me why older version of Via working fine and noone complaining?

**Comment by CarlCarlson97** [comment]
**Actually, I have same problem:**
Waterfall + ViaVersion 3.0.1 + ViaBackwards 3.0.1
PaperMC server on 1.15.2

Players are unable to pickup items once a while.

**Comment by KennyTV** [comment]
We need proper info; what client versins, what server version (+ dump) and a way to reproduce

**Comment by Skizzles** [comment]
Having same issue:
Waterfall + ViaVersion + ViaBackwards + ViaRewind

Using 1.16.1 paper, happens on 1.16 clients, 1.15.2 clients, 1.14.4 clients.

Servers are running on backend.

I do not believe its a ViaVersion issue but thought id post my findings as well.

**Comment by KennyTV** [comment]
https://github.com/PaperMC/Paper/issues/3632
