### ISSUE TITLE
1.8.9 client on 1.15.2 server - EncoderException

### ISSUE THREAD

**Issue by ZeProf2Code** [ViaVersion/ViaVersion#1851]
**Describe the bug, provide any errors**
![image](https://user-images.githubusercontent.com/32982428/85931063-a7b3d180-b8c1-11ea-9edf-2f4a67a26d44.png)

**How can we reproduce it?**
1. Login with a 1.8.9 client on a 1.15.2 server'
2. See the error

**Expected behaviour**
Not being kicked at connection.

**Screenshots**
![image](https://user-images.githubusercontent.com/32982428/85931076-c1edaf80-b8c1-11ea-90fb-9b616585bf5b.png)

**ViaVersion Dump:**
https://dump.viaversion.com/e92221bbcaae1db415140602f5a36e5538de459236a6aac9f05416dc70ba80e4

**Additional server info**
Using Waterfall and our custom plugins.

**Comment by KennyTV** [comment]
Paste the console error (https://paste.gg/)

**Comment by ZeProf2Code** [comment]
https://paste.gg/p/anonymous/437db88fc487467ba988ffdf6cc453a1

**Comment by KennyTV** [comment]
Thank you, fixed in the next ViaBackwards build.

**Comment by ZeProf2Code** [comment]
Wtf, fixed so fast :joy:
