### ISSUE TITLE
(1.12.2) (urgent) Invisible Entities with 1.12.2 on a 1.14.4 server with viaversion/backwards

### ISSUE THREAD

**Issue by ManO1234148** [ViaVersion/ViaVersion#1856]
Entities sometimes pop in and out of visibility without warning on the server. They are undetectable but still damageable, and they are not rendered but still exist. This issue is happening with and without a resource pack, with default entity-tracking in spigot. It affects all types of entities, hostile, non-hostile. The issue happens completely at random and is very game-breaking especially for a mob arena type gamemode. It **never occurs in vanilla, under any version**. Random Entities for texturepacks is disabled. Client renderdistance is 20+ and serverside is 10. Mob invisibility only seems to happen in certain areas although no specific area can be defined and replicated, so it is mostly at random.

https://gfycat.com/elatedobeseandalusianhorse

It also affects players

Bug was tested by both me and 2 other players, both also running optifine 1.12.2 HD U F5 and then tested using vanilla 1.12.2

## OptiFine Version
1.12.2 - HD U F5

**## Installation Method**
I used the standalone installer

**However it only happens on 1.12.2 optifine not 1.14.4**
SPIGOT version 1.14.4 non paper
BUNGEECORD version 1.15.2 with viaversion / backwards

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/29739282/85973728-984b8b80-b988-11ea-9f26-39c8c98aaf08.png)
Invisible entities screenshot
![image](https://user-images.githubusercontent.com/29739282/85973862-e6608f00-b988-11ea-9555-6d12b959e904.png)

This issue does not happen in vanilla minecraft, with or without our resourcepack, on 1.12.2

https://dump.viaversion.com/6a13873ddb7cfbd0a28ede85c13c3c643d5e329c3543ed1fcbd89876a088d359

I expected mobs to (not) go invisible?

**Comment by FormallyMyles** [comment]
You need to open this on the ViaBackwards issue tracker
