### ISSUE TITLE
[ViaBackwards] Unable to handle metadata Metadata java.lang.ClassCastException

### ISSUE THREAD

**Issue by Skizzles** [ViaVersion/ViaVersion#1857]
**Describe the bug, provide any errors**
https://hastebin.com/eligepaboj.md

**How can we reproduce it?**
Unsure its just spamming console

**Expected behaviour**
Not spam console

**Screenshots**
https://skizzles.me/KERU7/jeyibIQa70.png

**ViaVersion Dump:**
https://dump.viaversion.com/26addcd156c7f47b7bab46ca499f5d2d65aa0825d8e077c0c9f78e52abb2dc55

**Additional server info**
Yes Waterfall

**Comment by Skizzles** [comment]
Unsure if this is just Backwards or Viaversion as well, references both.

**Comment by KennyTV** [comment]
Fixed in the latest VB build
