### ISSUE TITLE
Hug error log

### ISSUE THREAD

**Issue by Loonyy** [ViaVersion/ViaVersion#1858]
**Describe the bug, provide any errors**
I keep getting these massive errors in console, now sure what's causing them.
https://pastebin.com/JSdGxPcM

**ViaVersion Dump:**
https://dump.viaversion.com/cfc4aa19a21ef0ce6cedf805b501ddfa666896f5b37325772456eb910e2e0938

**Additional server info**
I'm on Paper Spigot 1.15.2 using the latest ViaVersion and ViaBackwards.

**Comment by KennyTV** [comment]
Not a Via related error; Update to a build on ci.viaversion.com to suppress unrelated errors again

**Comment by Loonyy** [comment]
Is there dev builds for ViaBackwards too that I need?
