### ISSUE TITLE
Spigot plugin channel limits

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaVersion#1859]
FabricMC/fabric#849
We are currently passing through plugin channel names that Spigot <1.16 rejects, causing issues with Fabric clients.
Related to #1855

**Comment by Aurelien30000** [comment]
For information, works great on 1.15.2 but sadly not in 1.13.2 (maybe 1.14.4 also), here is my stacktrace, thanks for your help :)

https://mcpaste.io/252b84d1286172bf

Server version : Paper 1.13.2-build-652 -> Waterfall-build-366

**Comment by creeper123123321** [comment]
Where's viaversion installed? Waterfall proxy?

**Comment by Aurelien30000** [comment]
Viaversion is only installed on Minecraft server (paper). Indded is use a Waterfall proxy.

**Comment by KennyTV** [comment]
What was the client version you were connected with?

**Comment by Aurelien30000** [comment]
Minecraft 1.16.1 - Fabric Loader 0.9.0+build.204 - fabric-api-0.15.1+build.380-1.16.1

**Comment by Aurelien30000** [comment]
I also reproduced the issue on a fresh install with only ViaVersion.

**Comment by creeper123123321** [comment]
I found the issue: viaversion isn't reading Minecraft:register and
Minecraft:unregister contents

**Comment by KennyTV** [comment]
Fixed with the new build!

**Comment by Aurelien30000** [comment]
Fix confirmed, thank you both!
