### ISSUE TITLE
Moving Between Chunks sometime Disconnect you in 1.15+

### ISSUE THREAD

**Issue by lidanthedev** [ViaVersion/ViaVersion#1860]
**Describe the bug, provide any errors**
https://hastebin.com/iwocanarev.cs

**How can we reproduce it?**
1. Login on 1.15.2
2. Sometime when you change chunks and fly it will disconnect you

**Expected behaviour**
it shouldn't disconnect me

**ViaVersion Dump:**
https://dump.viaversion.com/0c0a25dfbf9e248f4f343e6dd2f381a5eaf7f0a471b28593bcdcfc98b375e499

**Additional server info**
I don't use bungeecord

**Comment by KennyTV** [comment]
Please try to reproduce this without other plugins / see if it is caused by a specific one (especially SkinsRestorer is known to mess with similar things)

**Comment by Jozznak** [comment]
Hi, Im having the same Issue with the last update. This didnt happend in early versions. 
DUMP: https://dump.viaversion.com/8d788f6ef4884e5d1af75a03d1bd20139b737a6063b6973d416eaf4645d30d16
MY CRASH: https://hastebin.com/derawaqeno.cs

**Comment by KennyTV** [comment]
As above; Please try to reproduce this without other plugins / see if it is caused by a specific one (especially SkinsRestorer is known to mess with similar things)

**Comment by Jozznak** [comment]
Its difficult to reporduce as it seems that is random. Nos every time happens. Dont know exactly what the user did to be Kicked.

**Comment by Jozznak** [comment]
Also, if the player is not kicked, its killed. But as I say, its random. If he does the same movements again through the same chunks don't happens.

**Comment by KennyTV** [comment]
I'm just going to take a guess to say its SkinsRestorer, since we have already had a very similar situation with another one of its updates.

**Comment by Incluuu** [comment]
After updating to new build:
- viaversion (Build - request -> 430)
- viarewind  (Build - request -> 45)
- viabackwards (Build - request -> 114)

Error mentioned above disappeared, but a new one appeared:
https://pastebin.com/HJXWycdw

[ViaVersion] ERROR IN Protocol1_7_6_10TO1_8 IN REMAP OF 0x33->0x33

PaperSpigot: 1.12.2 (latest)

**Comment by KennyTV** [comment]
@Incluuu your issue should be posted on the ViaRewind issue tracker (also update VV again to the latest ci build).
As for the original issue, definitely an SR issue of the .8 release.
