### ISSUE TITLE
Unable to connect to 1.16.1 server with 1.15.2

### ISSUE THREAD

**Issue by Baterka** [ViaVersion/ViaVersion#1863]
**Describe the bug, provide any errors**
I am unable to connect to 1.16.1 server with 1.15.2 client.
Stuck on: Loading terrain...
ViaVersion 3.0.2-SNAPSHOT

**How can we reproduce it?**
1. Login on 1.15.2
2. Join 1.16.1 server with ViaVersion
3. Stuck on: Loading terrain...
4. No error in server console

**Expected behaviour**
Should work same way as 1.8-1,15 client on 1.15 server.

**Screenshots**
![image](https://user-images.githubusercontent.com/3463591/86103769-7b64a480-babd-11ea-857c-bbddb2699479.png)

**ViaVersion Dump:**
https://dump.viaversion.com/f3ed140580297909d124a3d5946a341f417b7c975302ccd5d461836714d9ca4e

**Comment by FormallyMyles** [comment]
You should open this issue on ViaBackwards
