### ISSUE TITLE
String and hook not appearing of Fishing Rod on 1.16.1 client 1.15.2 server

### ISSUE THREAD

**Issue by rudde0** [ViaVersion/ViaVersion#1872]
**Describe the bug, provide any errors**
There is no any error just visual bug.

**How can we reproduce it?**
1. Right click with fishing rod to anywhere

**Expected behaviour**
should be seen like that https://prnt.sc/ta9zq2

**Screenshots**
https://prnt.sc/taa06z
https://prnt.sc/taa0ne

**ViaVersion Dump:**
- https://dump.viaversion.com/40dd5d80e9ab14926344c2f2fdd90274a440774a13f4f0df07a6542bdd95fda0

**Additional server info**
I'm using Aegis bungeecord

**Comment by KennyTV** [comment]
Can you reproduce this on a normal Paper and Bungee/Waterfall?

**Comment by rudde0** [comment]
I don't have bungeecord test server :(

**Comment by KennyTV** [comment]
Well otherwise we can't help you find out where the problem is - right now I can't reproduce this, neither with nor without Bungee 👀

**Comment by rudde0** [comment]
it wasn't viaversion's fault... sorry

**Comment by msmanui** [comment]
> it wasn't viaversion's fault... sorry

What was it? Im having the same exact issue

**Comment by rudde0** [comment]
> > it wasn't viaversion's fault... sorry
> 
> 
> 
> What was it? Im having the same exact issue

try change your bungeecord version

**Comment by MinecraftAdmin** [comment]
> > > it wasn't viaversion's fault... sorry
> > 
> > 
> > What was it? Im having the same exact issue
> 
> try change your bungeecord version

I am having the same issue. What do you mean by changing your Bungeecord version?
