### ISSUE TITLE
Viaversion error with diamond swords & NBT tags 1.8.9

### ISSUE THREAD

**Issue by haeiven** [ViaVersion/ViaVersion#1874]
**Describe the bug, provide any errors**
https://paste.soleria.eu/kadovisoyi.cs

**How can we reproduce it?**
I don't rly know and understand the error

**Expected behaviour**
No error

**Screenshots**
/

**ViaVersion Dump:**
https://dump.viaversion.com/2aeb70a0f60c0077cebf1fa087b92e1e6d4cfdbb90ce90794d5828495d634b57

**Additional server info**
/

**Comment by KennyTV** [comment]
Fixed with the next build here https://ci.viaversion.com/job/ViaVersion-DEV/
