### ISSUE TITLE
Disconnected from the server because of Heart particles

### ISSUE THREAD

**Issue by Hytashi** [ViaVersion/ViaVersion#1876]
**Issue**
When I spawn Heart Particles all the players are disconnected.
Here is the error sent in the console https://pastebin.com/YeywTxQP (sorry Hastebin didn't work)

**Steps to reproduce the behavior:**
1. Login on 1.8.9 or 1.9.4 or 1.14.4 (That's the versions the players used but I think it happens with all the versions)
2. Spawn Heart particles
3. You should be disconnected from the server

**Screenshots**
Client side error message : https://prnt.sc/tbaeqt

**ViaVersion Dump:**
https://dump.viaversion.com/f69dc265c2f587bbf34f38a3f2d15aa99fadc6ecd8411e12fe8979970df2b6ec

**Additional server info**
I use a BungeeCord with the lastest version and a Paper server running version 1.11.2 (version git-Paper-1104)

**Comment by KennyTV** [comment]
Update ViaVersion and ViaBackards to their -dev builds on https://ci.viaversion.com/
