### ISSUE TITLE
IllegalArugmentException : Team viaversion already exists in this scoreboard @ com.google.common.base.Preconditions:191

### ISSUE THREAD

**Issue by AdenGames** [ViaVersion/ViaVersion#1885]
**Describe the bug, provide any errors**
After updating to 1.16.1 now I can't go from my 1.16.1 survival server to my 1.8.8 hub while on 1.16.1
.
**How can we reproduce it?**
1. Login on 1.16.1'
2. Go to my survival server
3. Go back to the hub running viaversion

**Expected behaviour**
Just go to the hub server.

**Screenshots**
https://imgur.com/a/kxt7RK0

**ViaVersion Dump:**
https://dump.viaversion.com/cb6b6ac85e329ebf7f5b461d635b2d9a60ed9df85da96b8a71616cd0d4aac4ec

**Additional server info**
Bungee and paper spigot. This is the only plugin required to get this error I disabled the rest of them.

**Comment by KennyTV** [comment]
This boils down do Bungee's flawed server switch handlig, a workaround should be to set `auto-team` to false in the ViaVersion config

**Comment by AdenGames** [comment]
I disabled auto-team and im still getting the error.
https://imgur.com/a/SZ3twQH

**Comment by KennyTV** [comment]
https://github.com/PaperMC/Waterfall/issues/318#issuecomment-549006056

**Comment by AdenGames** [comment]
I deleted it and it's still doing it.

**Comment by AdenGames** [comment]
Updating bungeecord fixed it
