### ISSUE TITLE
Error 1.16 server 1.15 client

### ISSUE THREAD

**Issue by martijnpu** [ViaVersion/ViaVersion#1886]
**Describe the bug, provide any errors**
When a 1.15 player joins the spawn of our 1.16 server.
https://hastebin.com/kesafociye.rb

**How can we reproduce it?**
1. Login on 1.15'
2. Join a 1.16 server

**Expected behaviour**
You getting kicked

**ViaVersion Dump:**
https://dump.viaversion.com/639c4822bac294145d2d69f389448811e3e6057393462ff66a694227f0af2855

**Additional server info**
Bungeecord 1.16. Players join in a 1.16 server *no problems*, they go to another 1.16 server and getting kicked. Aleady redownloaded viaversion multiple times to see if I had the latest version. Problem is already there for a couple of days

**Comment by KennyTV** [comment]
Update ViaVersion and ViaBackwards to https://ci.viaversion.com/
