### ISSUE TITLE
Error in console spam

### ISSUE THREAD

**Issue by icansc187** [ViaVersion/ViaVersion#1887]
**Describe the bug, provide any errors**
https://hastebin.com/cicexeqaki.php

**How can we reproduce it?**
Paper 1.13.2

**Expected behaviour**
disconnect

**Screenshots**
https://ibb.co/Wv6P2tq

**ViaVersion Dump:**
https://dump.viaversion.com/84b8d27b545abb044b258569bc5f45fe934b3507354a35ab0c2eaedfcaab2174

**Additional server info**
i dont use bungecord

**Comment by KennyTV** [comment]
SkinsRestorer is not compatible with Via.

**Comment by icansc187** [comment]
What happened

**Comment by icansc187** [comment]
im using server crack

**Comment by icansc187** [comment]
can you helpme recommend viaversion compatible skinsrestore

**Comment by KennyTV** [comment]
There isn't, you can try downgrading SkinsRestorer to an older version, but that's your only option (unless they themselves change their behaviour again).

**Comment by icansc187** [comment]
thanks sir
