### ISSUE TITLE
Problem with connecting 1.16.1 through 1.15.2 viaversion

### ISSUE THREAD

**Issue by KiroxTV** [ViaVersion/ViaVersion#1888]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?

**How can we reproduce it?**
1. Login on 1.16.1
2. Click on join to server
3. The delayed "joining" and after that "timed out" with console log - KiroxTV Disconnected

**Expected behaviour**
When im trying to connect with 1.16.1 into my 1.15.2 paper server - I've got disconnected in console. Nothing else.

**ViaVersion Dump:**
- https://dump.viaversion.com/8e857696aea145ec363f5ee5c747d1bd6080588b6e07e585d101b6c7edb6cc6d

**Additional server info**
Im using Proxy Aegis - Fork of Bungee - I've got latest version which is available to join with 1.16.x

**Comment by KennyTV** [comment]
Can you try with a normal Bungee instead of Aegis?

**Comment by KiroxTV** [comment]
I did try on my main server without any Bungee - it was working fine, sure. So the problem is with Aegis?

**Comment by KennyTV** [comment]
I suppose so, we've had a few similar reports of problems with it in the past.
