### ISSUE TITLE
Console Spam on 1.12.2 based Servers

### ISSUE THREAD

**Issue by Skizzles** [ViaVersion/ViaVersion#1890]
**Describe the bug, provide any errors**
Constant console Spam from ViaVersion on 1.12.2 Paper Spigot. Have tried removing all plugins, have tested other ways and it just does not go away. https://screenshots.skizzles.me/xURO8/xEGaTujA93.png

**How can we reproduce it?**
1. Create a 1.12.2 Server
2. Install ViaVersion
3. Errors for every Version above 1.12.2

**Expected behaviour**
No Error Spam

**Screenshots**
https://screenshots.skizzles.me/xURO8/xEGaTujA93.png

**ViaVersion Dump:**
https://dump.viaversion.com/b8d12f15bfa397f76a338e57cf3cd5faff1a7168747f688a0ca2114f95cfac2f

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
Waterfall - https://screenshots.skizzles.me/xURO8/zOJAqIVE59.png

**Comment by KennyTV** [comment]
This should be one of your plugins sending invalid entity spawn packets, since it happens instantly in 1.12.2->1.13 before any of our proper magic happens. Remove a few plugins until you find the culprit, and report it to them.
