### ISSUE TITLE
1.16 client crash a 1.12.2 Paper server

### ISSUE THREAD

**Issue by Rubenicos** [ViaVersion/ViaVersion#1892]
**Describe the bug, provide any errors**
I have a 1.12.2 Paper server with ViaBackwards and ViaRewind, when a 1.16.1 player enters and do something sooner or later the server crash.
Here a little part of error: https://pastebin.com/eS0qWzVE (real error is 20 times bigger)

**How can we reproduce it?**
idk, i made another server with 1.12.2 Paper, ViaVersion, ViaRewind, ViaBackwards and test with some people but nothing happened.

**Expected behaviour**
A problem with a plugin

**ViaVersion Dump:**
https://dump.viaversion.com/6d450d14caa50efadf8f5d67d4eb444fef813a9a22247852c87efc61e316ed53

**Additional server info**
I use a bungeecord (Famecord) with ViaVersion

**Comment by KennyTV** [comment]
Update to https://ci.viaversion.com/job/ViaVersion/
