### ISSUE TITLE
1.15.2 Paper Spigot (WaterFall Sub-Server), Client 1.8

### ISSUE THREAD

**Issue by MackenzieMolloy** [ViaVersion/ViaVersion#1895]
**Describe the bug, provide any errors**
https://hastebin.com/eyoretugaf.bash

**How can we reproduce it?**
1. Login on 1.8'
2. Run this https://www.spigotmc.org/resources/simple-elevators-1-8-1-16.44462/ on 1.15 server
3. Use elevator

**Expected behaviour**
Should function without being kicked

**ViaVersion Dump:**
- https://dump.viaversion.com/46a7604c31f8d09ab91f3b2ac916d3166dd4f6f2e75d4e03c10bbb36fe1fcae9

**Additional server info**
- WaterFall Proxy, Sub-Servers paper. Lobby 1.12, Csurvival (Where the issue occurs) 1.15.2

- Proxy Plugins: BMSG, BungeeAlert, BungeeServerManager, BungeeTabListPlus, CraftingStore, LuckPerms, movemenow, Nuvotifier, ServerSwitcher, ServerListPlus, UltimateFriends, Via(Version [3.0.2], Backwards [3.0.2], Rewind [1.5.0])

**Comment by KennyTV** [comment]
Update ViaRewind to its ci build.
