### ISSUE TITLE
ERROR IN Protocol1_13To1_12_2 IN REMAP OF SPAWN_PLAYER (0x05)

### ISSUE THREAD

**Issue by llgava** [ViaVersion/ViaVersion#1897]
Hi, I'm getting crash when I try to spawn a Custom Player NPC with my plugin and I don't know what is it.

Here is the error: https://paste.gg/p/llgava/c01d73260e1c4530bafc5413346eed6d
And here is the actual code from the npc class: https://paste.gg/p/llgava/aebe760ca31f428ab54bd56e3d1d41e9

I'm using BungeeCord 1.16 with 2 servers:

- Lobby (1.12.2 with ViaVersion(3.0.1) to support 1.12.2 until 1.16.1) `< I'm trying to use my command here.`
- Survival (1.16.1 as default Minecraft Server - no plugins -)

Other plugins in Lobby server: EssentialsX, EssentialsXAntiBuild, EssentialsXChat, LuckPerms, Vault and my plugin in development.

**Comment by KennyTV** [comment]
Your custom EntityPlayer has invalid datawatcher data

**Comment by llgava** [comment]
And what would be the correct date that should be? I've tried everything, including some tips on the Spigot forum.

**Comment by KennyTV** [comment]
Sorry, you'll have to figure that out on your own, 1.12 is quite the old version.
