### ISSUE TITLE
Unknow console error reporting

### ISSUE THREAD

**Issue by Noiknez** [ViaVersion/ViaVersion#1898]
**Describe the bug, provide any errors**
An unknown error appear on the console. Full log : https://pastebin.com/wzmCKMiL

**How can we reproduce it?**
I don't know

**Expected behaviour**
No error

**ViaVersion Dump:**
https://dump.viaversion.com/01349ccc3a025446574bbbb311a537823c041eb3a0648fa12ad1632981ad8a6c

**Additional server info**
Bungeecoord but via is only on the server

**Comment by KennyTV** [comment]
Unrelated to Via.
