### ISSUE TITLE
1.16 Furnace crashing your game

### ISSUE THREAD

**Issue by ItsCryptic1** [ViaVersion/ViaVersion#1899]
**Describe the bug, provide any errors**
Furnaces will crash a player if they are in 1.16. It seems to be fine when you are opped but if you are a normal player however it indeed will crash you

**How can we reproduce it?**
1. Login on 1.16
2. Put coal in a furnace
3. Your game will crash due to an NBT tag error

**Expected behaviour**
Your game will crash

**Screenshots**
https://i.imgur.com/vUEAJju.png

**ViaVersion Dump:**
- https://dump.viaversion.com/74909ce18fe8bb1e012386448689477e28030f37cfbc66b29eb012c09b9e9596

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins? Yes we use Bungeecord and I'll take a screenshot of the other plugins https://i.imgur.com/5JVaFRL.png <-- screenshot of all my plugins

My servers main version is 1.12.2 if that information is needed

**Comment by KennyTV** [comment]
Update to a build on https://ci.viaversion.com/

**Comment by ItsCryptic1** [comment]
Issue seems to continue

**Comment by FormallyMyles** [comment]
> Issue seems to continue

Provide new `/viaversion dump` link

**Comment by ItsCryptic1** [comment]
https://dump.viaversion.com/4678dfb2a107b0bd27d74f4ae2a7c40d054b2ace0b2274e0aa4cffd563ce5d51 There you go!

**Comment by ItsCryptic1** [comment]
Had to temporarily block 1.16 from joining that server so people don’t crash there games

**Comment by FormallyMyles** [comment]
Have you updated BungeeCord recently?

**Comment by ItsCryptic1** [comment]
Not extremely recently but I did maybe a month ago

**Comment by FormallyMyles** [comment]
I'd suggest trying that

**Comment by ItsCryptic1** [comment]
Okay I’ll try it if that doesn’t work I’m coming back here
