### ISSUE TITLE
PacketPlayOutTileEntityData for signs does not work when the editor is open in 1.16

### ISSUE THREAD

**Issue by Symphonic3** [ViaVersion/ViaVersion#1900]
**Describe the bug, provide any errors**

When PacketPlayOutTileEntityData is sent to a client when they have a sign open, on 1.15 and below, this will change the text in their menu. On 1.16.x+ running a 1.15.2 server, clients will not recieve any text in their sign when it is sent using this packet.

**How can we reproduce it?**
0. Have a 1.15.2 server
1. Create some code that creates a clientsided sign, makes a player open it, and updates the data with PacketPlayOutTileEntityData 
2. Run the code on a logged in player on 1.16
3. Player's sign will not update
4. Run the code on a logged in player on 1.15
5. Player's sign will update

**Expected behaviour**

The sign text should update.

**ViaVersion Dump:**

https://dump.viaversion.com/62aca64336d7f441186672ae16594236eec018dfc864b5b28912e86f234ca165

**Additional server info**

All important info is in the above dump

**Comment by KennyTV** [comment]
This is a 1.16 client bug, which sadly isn’t too likely to be changed again (a dev marked it as a “feature request”).

**Comment by Symphonic3** [comment]
Sucks, I used this format of menu for a login plugin because it flows seamlessly with blocking PlayerMoveEvents and players never feel like they're "stuck" in one spot, they just have the menu open.. I guess I'll just have to opt for the old "Enter your password in the chat"
