### ISSUE TITLE
Login on 1.16.X instant kick

### ISSUE THREAD

**Issue by coolthom** [ViaVersion/ViaVersion#1902]
**Describe the bug, provide any errors**
When login on in 1.16.X you get instantly kicked. Usually without even seeing the world (rare occasions you see it for a few seconds then get kicked). Kick messages logged below. Login on with 1.15.X works fine.

https://hastebin.com/xevidutaro.md

**How can we reproduce it?**
1. Login on 1.16.X

**Expected behaviour**
Login onto the server and being able to play like other versions.

**Screenshots**
*kick messages*
![image](https://user-images.githubusercontent.com/36266785/87180590-1e4cc800-c2e1-11ea-802e-1b199ab2df68.png)
![image](https://user-images.githubusercontent.com/36266785/87180636-345a8880-c2e1-11ea-922f-83f86d0be6cc.png)
![image](https://user-images.githubusercontent.com/36266785/87180678-46d4c200-c2e1-11ea-88f0-5d3c36d0b2c1.png)

**ViaVersion Dump:**
- https://dump.viaversion.com/81d4d0c1b81b110f76b472270ca12c7593dcd50c36cefa26a32d032a3bc70e18

**Additional server info**
Waterfall

**Comment by KennyTV** [comment]
Update to https://ci.viaversion.com/job/ViaVersion/ and send the then full error again.

**Comment by coolthom** [comment]
https://hastebin.com/jedekocalu.cs

**Comment by KennyTV** [comment]
You have a plugin sending bad chunk data.
