### ISSUE TITLE
ERROR IN BaseProtocol IN REMAP OF 0x00->0x00

### ISSUE THREAD

**Issue by KuoadStaff** [ViaVersion/ViaVersion#1906]
**Describe the bug, provide any errors**
Many times, I leave the server open, but I control many times through the console, and I get a very large log every 5 minutes.
Many times I used ViaVersion, but it never gave me that problem. The record is: https://hastebin.com/wecibuguya.md

**How can we reproduce it?**
1. Login server on 1.8.8'
2. Click on '**nothing**'
3. The '**console**' is displayed wrong

**ViaVersion Dump:**
https://dump.viaversion.com/05175d61382fb8174970fde0f62872a55825ca7f5eafcd759e9274d25330b269

**Additional server info**
I use Spigot 1.8.8, and all publiges come from the spigot page. I don't use the Bungeecord.
And sorry, for my English.

**Comment by KennyTV** [comment]
Update to https://ci.viaversion.com/
