### ISSUE TITLE
Updated to ViaVersion-3.0.2-20w28a on BungeeCord

### ISSUE THREAD

**Issue by TheCleverGamer** [ViaVersion/ViaVersion#1907]
When I just now updated the ViaVersion on BungeeCord and join I get this error in mc launcher

![2020-07-11_20 51 46](https://user-images.githubusercontent.com/59615440/87231606-d5684280-c3b8-11ea-8688-d9bb94abc884.png)

**Comment by KennyTV** [comment]
Please follow the issue template.
