### ISSUE TITLE
1.15.2 Crash

### ISSUE THREAD

**Issue by HexedHero** [ViaVersion/ViaVersion#1908]
**Describe the bug, provide any errors**
The console gets spammed and crashes. (1.15.2 server allowing 1.16+)
https://pastebin.com/raw/na7RUy36

**How can we reproduce it?**
Very random, happened twice in the last week.

**Comment by FormallyMyles** [comment]
Update to dev builds

ViaVersion - https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/jar/target/ViaVersion-3.0.2-SNAPSHOT.jar
ViaBackwards - https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/lastSuccessfulBuild/artifact/all/target/ViaBackwards-3.0.2-SNAPSHOT.jar
ViaRewind - https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/lastSuccessfulBuild/artifact/all/target/ViaRewind-1.5.1-SNAPSHOT.jar
