### ISSUE TITLE
Item Pickup Bug

### ISSUE THREAD

**Issue by Weymouth87** [ViaVersion/ViaVersion#1909]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?
No console errors from what I can tell. Occasionally players cant see items theyve picked up in their inventories until they interact with a crafting table. 

Happens with all our servers running viaversion and hasnt been reported when we took the plugin out.
**How can we reproduce it?**
1. Login on 1.16.1 or 1.15.2
2. Try pick up items.
3. If items do not show in inventory, clicking a crafting table seems to fix.

**Expected behaviour**
Items should be picked up and visible.

**Screenshots**

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/08b9646bd4143108c87be83c57255f94eafcbaab75fd685136ebee00cae782e7 

**Additional server info**
Latest Paper Spigot, 1.15.2 server. 
Plugin list for server 1 with the issue:
Plugins (53): ActionHealth*, Advanced_Drop_Party, AdvancedAnnouncement*, AdvancedEnchantments, ArmorStandTool, AutoPickup, BentoBox, BookShelf, BuycraftX, ChatColor, ClearLag, CMI, CMIPaperLib, CrazyAuctions, CrazyCrates, CropClick*, DeluxeChat, DeluxeMenus, DeluxeTags*, EditableSign, Essentials, EssentialsChat, EssentialsSpawn, FlightControl, Graves, HolographicDisplays, HolographicExtension*, HolographicScoreboard*, InteractionVisualizer, LeaderHeadsRevamped, LightAPI, LuckPerms, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, NerfPhantoms, PlaceholderAPI, PlugMan, ProtocolLib, PvPManager, ShopGUIPlus, TabList, TreeGravity, Vault, ViaVersion, VoidGenerator, VoidTeleport, WildStacker, WildStackerMobsPatch, WolfyUtilities, WorldEdit, WorldGuard, zDiscord*

Plugin List for 2nd Server with the issue:
Plugins (77): ActionHealth*, Advanced_Drop_Party, AdvancedAnnouncement*, AdvancedEnchantments, AntiNetherRoof*, BetterBees, BetterEnd, BetterRTP, BlockQuest, BottledExp, BuycraftX, ChatColor, ChatReaction, Chunkmaster, ClearLag, ClickDye, CMI, Coins, CommandSigns, CrazyAuctions, CrazyCrates, CustomHeads*, CustomRecipeAPI, DeepStoragePlus, DeluxeChat, DeluxeMenus, DeluxeTags*, Disenchant-2, Doorbells, DragonTimer, EditableSign, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, EssentialsXMPP, FastCraft, FogusCore, FurnaceNotify*, Graves, GriefPrevention, HolographicDisplays, HolographicExtension*, HolographicScoreboard*, IngotBlock, LeaderHeadsRevamped, LibsDisguises, LuckPerms, LuckyBlock, MeltDown, Minepacks, MiniaturePets*, MiningBlocks, MoonGenerator, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, MyDog, MythicMobs, Parrots, PlaceholderAPI, PlugMan, ProtocolLib, PvPManager, RainbowBlocks*, Referral, ShopChest, TabList, TreeFeller, UltraCosmetics, Vault, ViaVersion, WorldBorder, WorldEdit, WorldGuard, XPBoost, zDiscord*

**Comment by FormallyMyles** [comment]
Could you confirm if both servers are running 1.15.2? and if the issue happened on both on 1.15.2?

**Comment by Weymouth87** [comment]
Both servers are running 1.15.2 and the users experiencing the bug have been joining on 1.15.2 and 1.16.1

**Comment by Weymouth87** [comment]
The issue occurs in both servers also

**Comment by FormallyMyles** [comment]
ViaVersion doesn't modify any data for your server, meaning if it happens on 1.15.2 it most likely is down to another plugin (perhaps an inventory-related one) but I don't know enough of the plugins listed to give you any pointers.

I can suggest the latest build of ours from the CI but I doubt it would fix the issue if it happens on 1.15.2 - https://ci.viaversion.com/job/ViaVersion/

**Comment by FormallyMyles** [comment]
See above, unless you're able to provide more info for us to replicate :)
