### ISSUE TITLE
Large amounts of block changes causes 1.16.1 clients to freeze

### ISSUE THREAD

**Issue by eirikh1996** [ViaVersion/ViaVersion#1910]
**Describe the bug, provide any errors**
In situations where large amounts of block changes occur, such as moving a ship on a Movecraft server or using WorldEdit to add/change/remove large amounts of blocks, players using 1.16.1 clients experience heavy FPS drops and eventually freezes, where the client will be "Not responding" an unresponsive for a good amount of time

**How can we reproduce it?**
1. Login on 1.16.1'
2. create a situation where large amounts of block changes occur, such as either WorldEdit away a large number of blocks or pilot a Movecraft ship atleast 10k blocks large and move it fast.
3. Notice how 1.16.1 clients will experience FPS drops and freezing

**Expected behaviour**
Clients should never freeze. Problem does not exist on 1.15.2 and below. Nor does it exist on 1.16.1 servers without ViaVersion

**Screenshots**
https://gyazo.com/a04dc5cefd9dd00025e8222bbbcc6658

**ViaVersion Dump:**
https://dump.viaversion.com/c7757fea83effd019acccf423f025f5d67555a9f98c01832f70468d09c72acbf

**Additional server info**
Proxy: Waterfall
Server software: SpigotMC 1.12.2
Plugins (41): Broadside, dynmap, PlaceholderAPI, ClearLag, CrackShot, PlugMan, WorldBorder, SmartSignEditor, Multiverse-Core, Space, OpenTerrainGenerator, iFill, FastAsyncWorldEdit, VoidGenerator, DeluxeMenus, MoonWorldGenerator, ViaVersion, Vault, UltraWorldGenerator, WorldEdit, Essentials, ProtocolLib, WorldGuard, Citizens, MythicMobs, EssentialsChat, BigDoors, NationCraft, EssentialsSpawn, Cannons, ChatInjector, Movecraft, StructureBoxes, Periscopes, NationCraftDynmap, dtlTraders, Afterburner, Movecraft-WorldBorder, APTurrets, Movecraft-Space, Cargo

**Comment by KennyTV** [comment]
FAWE doesn't send light updates, which means the 1.16 client will fully calculate all of that itself (which it does on its main thread).
