### ISSUE TITLE
MMOItems not working with ViaVersion 1.16.1

### ISSUE THREAD

**Issue by tntcurtis** [ViaVersion/ViaVersion#1915]
**Describe the bug, provide any errors**
Apparently a player told me he gets an error when his game crashes. https://hastebin.com/apomolavap.md It doesn't happen to me but it seems legit.

**Expected behaviour**
This issue I would expect not to make players crash with the possible use of one of the "MMO's" plugin provided below.

**Screenshots**
https://i.imgur.com/2TWbdix.png

**ViaVersion Dump:**
https://dump.viaversion.com/fe96ad9ce4d7d50bb5efd7c6829e6d148ad336727fdca902c3759316cf7dd619

**Additional server info**
I do use bungee cord and paperspigot. I am using MMOItems, MythicMobs, and MMOCore to start and I think one of those is interfering with via version.

If you have any more questions feel free to let me know thanks.

**Comment by KennyTV** [comment]
Update to a build on https://ci.viaversion.com/
