### ISSUE TITLE
WritingBlock exception ....

### ISSUE THREAD

**Issue by VVheyn** [ViaVersion/ViaVersion#1916]
https://media.discordapp.net/attachments/316208160232701955/733754449469767800/unknown.png?width=1288&height=428

https://hastebin.com/pogevawaqe.cs

https://dump.viaversion.com/037ead6c29078c6f12fd8db0af0f6c60dd6b375f50e9d22c5e7794b42b8693cf

**Comment by VVheyn** [comment]
update viaversion https://dump.viaversion.com/690fb0a21a7fb20f7b7f33f0b98215f4be1e97ef6d525edc3ab878ad35b6c1b0

**Comment by FormallyMyles** [comment]
Can you test with no other plugins?

**Comment by VVheyn** [comment]
no :D

**Comment by VVheyn** [comment]
I upgraded, I hope it gets better: D
