### ISSUE TITLE
ERROR VIAVERSION - java.lang.ArrayIndexOutOfBoundsException: 95

### ISSUE THREAD

**Issue by alexeses** [ViaVersion/ViaVersion#1917]
Describe the bug, provide any errors

The error happens "occasionally", it is not constant. It does, however, eject the user for the next error: 

10:36:31] [Server thread/INFO]: BlackCraft lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.ArrayIndexOutOfBoundsException: 95

Error#1: https://hastebin.com/ozugubowor.makefile
Error#2: https://hastebin.com/ojafoloyiw.sql

Additional server info
I use PapperSpigot 1.12.2 with ViaVersion, Backwards and Rewind. No big deal.

**Comment by FormallyMyles** [comment]
Ensure you follow the issue template fully, i.e provide the `/viaversion dump` output.

Otherwise you're using the world block-connection method which can cause errors, so changing it back to packet will probably fix it as world is unstable in some cases.
