### ISSUE TITLE
Unable to login with 1.13+ to 1.12 server

### ISSUE THREAD

**Issue by tomcraft** [ViaVersion/ViaVersion#1918]
**Describe the bug, provide any errors**
I can't connect to my server (1.12 paper) using 1.13+ versions
If u use 1.8 paper, it works
https://p.tomcraft.fr/511add2.log

**How can we reproduce it?**
1. Login on 1.13+ to 1.12 paper (with latest Via*-DEV)' (https://papermc.io/api/v1/paper/1.12.2/1618/download)
2. You can't

**Screenshots**
https://p.tomcraft.fr/3c45.gif

**ViaVersion Dump:**
- https://dump.viaversion.com/f829ac9d467eadac40ce57c4b1dcead20929b471f2187fe6a63babb929b80f36

**Additional server info**
No plugins, no proxy

**Comment by tomcraft** [comment]
Tested with 1.15.2 optifine, 1.12 paper, clean world, no plugins

**Comment by KennyTV** [comment]
Can you upload logs and screenshots to other sites? I can't resolve yours

**Comment by tomcraft** [comment]
logs: https://paste.gg/p/anonymous/8701561b22f6487a8fd94f93b02bfbac

**Comment by tomcraft** [comment]
![1oSGt3g5Q6](https://user-images.githubusercontent.com/936063/87873580-10730300-c9c3-11ea-9b6a-b25404a3c3a6.gif)

**Comment by KennyTV** [comment]
Thanks, fixed.

**Comment by tomcraft** [comment]
I confirm my issue is fixed, thanks for your work :)
