### ISSUE TITLE
ViaVersion reported an error and kicked the player out, others did not

### ISSUE THREAD

**Issue by mkwwmka5** [ViaVersion/ViaVersion#1919]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?

**How can we reproduce it?**
1. Login on 1.15'
2. Click on 1.8 spigot
3. The ViaVersion is displayed wrong

**Expected behaviour**

**Screenshots**
![05CL%8VX@@9S121%W~R1_4S](https://user-images.githubusercontent.com/59493751/87870289-fcd29700-c9d8-11ea-80ce-1e7ecfdcfe1d.png)

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/12e034ebdf3b68ddd65aa80c8bbf0e493d39f671ff45a62475573b260dadfe8a

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
yes, i am use BungeeCord

**Comment by FormallyMyles** [comment]
Test with latest builds of the Via plugins from ci.viaversion.com.

Otherwise can you test with no other plugins as nobody else has reported this one?

**Comment by mkwwmka5** [comment]
> Test with latest builds of the Via plugins from ci.viaversion.com.
> 
> Otherwise can you test with no other plugins as nobody else has reported this one?

hi,Thank you very much for your reply
This problem only appeared for me, other players did not

**Comment by mkwwmka5** [comment]
> Test with latest builds of the Via plugins from ci.viaversion.com.
> 
> Otherwise can you test with no other plugins as nobody else has reported this one?

To be precise, it is only for my ID
I used other IDs and found no abnormalities

**Comment by FormallyMyles** [comment]
What do you mean for your ID?

Your plugins / your player data?

**Comment by mkwwmka5** [comment]
> What do you mean for your ID?
> 
> Your plugins / your player data?

it is my Minecraft ID

**Comment by FormallyMyles** [comment]
Unless we can replicate this, we're not going to be able to fix it.
