### ISSUE TITLE
Random error message in console

### ISSUE THREAD

**Issue by RobZenTL** [ViaVersion/ViaVersion#1920]
**Describe the bug, provide any errors**
The error occured randomly in the console. No joins, no actions. One player with 1.14 online.
https://hastebin.com/ekuzokazey.bash

**ViaVersion Dump:**
https://dump.viaversion.com/8ad813a38f61de107c520f5b35328fe4ef60d83dab2aff4b059714eaeab3acf7

**Additional server info**
Spigot 1.13.2, ViaVersion 3.0.1

**Comment by FormallyMyles** [comment]
This is clients sending bad data, you can update to latest builds from ci.viaversion.com and these will be hidden.
