### ISSUE TITLE
Disconnects when logging into the server

### ISSUE THREAD

**Issue by TemaFlux** [ViaVersion/ViaVersion#1921]
**Describe the bug, provide any errors**
ViaVersion debug on join 1.16.1: https://hastebin.com/eqopolosul.md

**How can we reproduce it?**
1. Login on 1.16.1
2. Click on PaperSpigot-1.12.2-build1618
3. The in join to server is displayed wrong

**Expected behaviour**
Login into the server and being able to play like other versions.

**Screenshots**
![image](https://user-images.githubusercontent.com/67328970/87959119-14824c00-cabb-11ea-8e66-1511fd3580cb.png)

**ViaVersion Dump:**
PaperSpigot: https://dump.viaversion.com/0eb6295f57fc436b6162493e357484d9ec5d95a1c895d15a48bc3551d47ad2de
BungeeCord: https://dump.viaversion.com/1840a4bef815d6c36a320cb6ffb8fc0835443ffa770fd0fd2e0a6c84f4bbf9e0

**Additional server info**
Modified BungeeCord (BotFilter)

**Comment by KennyTV** [comment]
Only use Via on *either* Bungee or Paper (Paper preferred) and make sure everything is up to date.
