### ISSUE TITLE
newer client kick on 1.8.8 server (Packet out of range)

### ISSUE THREAD

**Issue by PhanaticD** [ViaVersion/ViaVersion#1924]
**Describe the bug, provide any errors**
players on newer client versions get kicked
bungee and server logs: https://pastebin.com/raw/TAh3N9cs
according to this particular player: "just using 1.14.4 and optifine"

it appears clients on 1.8 could still join, while clients on new versions could not

**How can we reproduce it?**
this issue occurs randomly on a server that restarts often, maybe once every 3 days on a server that restarts every 2 hours for map changes. Doing another restart usually fixes it since it only happens occasionally

**Expected behaviour**
no kick for newer version

**Screenshots**
players screen: https://cdn.discordapp.com/attachments/136595458259681280/735627543163568188/unknown.png

**ViaVersion Dump:**
https://dump.viaversion.com/26f54e8581856b16052db70668924e8f6a282f31f90917f5c4431d359fd152e0 (note this was made after a restart to fix was done)

**Additional server info**
travertine for proxy: Travertine version git:Travertine-Bootstrap:1.16-R0.3-SNAPSHOT:7b4f8ab:153

**Comment by PhanaticD** [comment]
this happened again just now and another players shows this kick:
[20:23:32 ERROR]: [/<ip>:51905|noorem] <-> DownstreamBridge <-> [kitpvp] - encountered exception
net.md_5.bungee.protocol.BadPacketException: VarInt too big
[20:23:32 INFO]: [/<ip>:51905|noorem] <-> DownstreamBridge <-> [kitpvp] has disconnected

**Comment by FormallyMyles** [comment]
I'm unable to replicate this, I'd guess that maybe it could be a bad client. Without steps, unfortunately, we can't really do anything :(
