### ISSUE TITLE
Item Attributes not shown to 1.16 clients on 1.15 servers

### ISSUE THREAD

**Issue by NickNackGus** [ViaVersion/ViaVersion#1925]
**Describe the bug, provide any errors**
Some/all attributes do not show up on items on 1.15 servers joined by 1.16 clients.

Attributes in 1.16 have been renamed to meet namespaced ID requirements. Any unknown attribute IDs are removed. I suspect these two changes are why attributes do not show up on 1.15 servers from 1.16 clients.

See the Minecraft wiki for this version, scroll down to Attributes for a list of changed IDs.
https://minecraft.gamepedia.com/Java_Edition_1.16#General_2

**How can we reproduce it?**
1. Log into 1.15 server using a 1.15 client.
2. Run `/give @p minecraft:stick{AttributeModifiers:[{Slot:"mainhand",UUIDMost:4746928367568897828L,UUIDLeast:-7226932790936962473L,Amount:5.0d,Operation:0,Name:"Modifier",AttributeName:"generic.maxHealth"}]} 1`
3. Note you have 2.5 extra hearts in survival/adventure mode with the stick in your main hand.
4. Note that the stick shows its attribute modifiers when hovered over in your inventory.
5. Log into the same server using a 1.16 client.
6. Note you still have 2.5 extra hearts in survival/adventure mode with the stick in your main hand.
7. Note that the stick no longer shows its attribute modifiers when hovered over in your inventory.

**Expected behaviour**
Attribute modifiers should be visible to 1.16 clients on a 1.15 server.

**Screenshots**
N/A

**ViaVersion Dump:**
https://dump.viaversion.com/29532251a666861f27d2464d5bf4dd5d7e9a8e920956741a7ee8ad18dd535a35

**Additional server info**
Using proxy BungeeCord-1518 with:
BungeeDisplay-1.2
BungeeTabListPlus-3.2.0
LuckPerms-Bungee-4.4.22
MonumentaBungeecord-6.5.1-20200718-071107 (custom plugin, no modifications to protocol or attributes)
MonumentaRedisSync_1.15.2_1.3-3-g440fdd1_20200716-001217 (custom plugin, no modifications to protocol or attributes)
nuvotifier-2.5.3
VentureChat-2.18.4
ViaVersion-3.0.1

Simplest server connected is paperclip-monumenta-2020-07-04-8046ed094-revert-spawner-light-breakage (modified Paper server, no modifications to protocol or attributes) with plugins:
CommandAPI_2.3a_official
PlaceholderAPI-2.10.4
ProtocolLib-4.5.0
MonumentaRedisSync_1.15.2_1.3-3-g440fdd1_20200716-001217 (custom plugin, no modifications to protocol or attributes)
Vault-1.7.2
VentureChat-2.18.4

**Comment by KennyTV** [comment]
Update to https://ci.viaversion.com/job/ViaVersion-DEV/
