### ISSUE TITLE
shulkerbox issue with 1.13+

### ISSUE THREAD

**Issue by disqetow** [ViaVersion/ViaVersion#1926]
**Describe the bug, provide any errors**
Not any error at console

**How can we reproduce it?**
1. run 1.12.2 server and install show item plugin
2. open 1.13 ~ 1.16.1 client and connect to server
3. put custom name item to shulkerbox
4. use show item plugin show shulkerbox

**Expected behaviour**
It should show custom item name in shulkerbox

**Screenshots**
https://imgur.com/a/Y24v0Xj.

**ViaVersion Dump:**
https://dump.viaversion.com/de37488a659b8bed8f6e82002e2dae6a091b9d6657989df1e1c8b3288ed4979f

**Additional server info**
Bungeecord and 1.12.2 paper

**Comment by KennyTV** [comment]
This is a won't-fix, see https://github.com/ViaVersion/ViaBackwards/issues/223#issuecomment-655351687
