### ISSUE TITLE
ERROR IN BaseProtocol IN REMAP OF 0x00->0x00

### ISSUE THREAD

**Issue by real2two** [ViaVersion/ViaVersion#1928]
**Describe the bug, provide any errors**
ERROR IN BaseProtocol IN REMAP OF 0x00->0x00
Error: https://hastebin.com/xawiwoboqo.md

**How can we reproduce it?**
I don't know. No one was on the server. It said to report the bug so I reported the error.

**Expected behaviour**
I shouldn't see this huge spam error message on my console.

**Screenshots**
None.

**ViaVersion Dump:**
https://dump.viaversion.com/a763e2d75eff89168b246c6b20cd06fdb2e8c9bc27c0d4a0e977cd9644bf887f

**Additional server info**
My server version is (PaperSpigot) 1.12.2.
Plugins (19): [AutoRespawnPlus](https://www.spigotmc.org/resources/autorespawnplus.14412/), [AutoRestart](https://www.spigotmc.org/resources/autorestart.2538/), [CratesPlus](https://www.spigotmc.org/resources/cratesplus-free-crates-plugin-1-7-1-14-2.5018/), [FastAsyncWorldEdit](https://www.spigotmc.org/resources/fast-async-worldedit-voxelsniper.13932/), [floodgate-bukkit](https://ci.nukkitx.com/job/GeyserMC/job/Floodgate/job/development/), [FloodgatePlaceholders](https://github.com/rtm516/FloodgatePlaceholders/), [Geyser-Spigot](https://github.com/GeyserMC/Geyser), [HealthBar](https://dev.bukkit.org/projects/health-bar), [HolographicDisplays](https://dev.bukkit.org/projects/holographic-displays), [OldCombatMechanics](https://www.spigotmc.org/resources/oldcombatmechanics-disable-1-9-hit-cooldown.19510/), [PlaceholderAPI](https://www.spigotmc.org/resources/placeholderapi.6245/), [PlugMan](https://dev.bukkit.org/projects/plugman), [SkQuery](https://dev.bukkit.org/projects/skquery), [Skript](https://dev.bukkit.org/projects/skript), SuperCore (a friend made this plugin, I don't think it's public), [ViaBackwards](https://www.spigotmc.org/resources/viabackwards.27448/), [ViaRewind](https://www.spigotmc.org/resources/viarewind.52109/), [ViaVersion](https://www.spigotmc.org/resources/viaversion.19254/), [WorldEdit](https://dev.bukkit.org/projects/worldedit) (WorldEdit version 6.1.7;dd00bb1)

**Comment by FormallyMyles** [comment]
Update to latest from ci.viaversion.com otherwise it's just a client sending bad data
