### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Momshroom** [ViaVersion/ViaVersion#1929]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?
I found this in my server logs - it said to report it, so... (It was 24 hours ago, and no issues were reported at the time.)

https://paste.gg/p/Momshroom/2a2209609ea04619a5725b4e0eb75cb2

**How can we reproduce it?**

No, clue, sorry

**Expected behaviour**
No console errors :3

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
 https://dump.viaversion.com/cff0515f4f565e08b361b51f14c0754639f66cf0fc87438e8bea595a2abbf01d

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

No proxies, Paper 92, plugin list is included in the dump above :3

**Comment by FormallyMyles** [comment]
This is something sending bad data to your server. You can ignore it or update to latest from ci.viaversion.com and it'll hide it.

**Comment by Momshroom** [comment]
Ty
