### ISSUE TITLE
Blocks/Particles Misalignment and Spam Teleportation when Mounting Horses (ProCosmetics)

### ISSUE THREAD

**Issue by Demeng7215** [ViaVersion/ViaVersion#1930]
**Describe the bug, provide any errors**
Block trails, particles, and other entities are misaligned with the horse. Additionally, when mounting any horse mount, you will be kicked off and then spam teleported to the entity's location until you press LSHIFT.

**How can we reproduce it?**
1. Create 1.8.8 server with ProCosmetics.
2. Log in using 1.16.1.
3. Mount any horse mount (Unicorn for example).
4. Give yourself the speed 2 potion and try to mount the horse.
5. After 3-5 times of being kicked off and spam teleported, you should be able to finally get on the horse.
6. Walk around the map for about a minute. You'll start the realize that the block trails are actually following beside your mount, not behind it. You can also see the unicorn's horn being completely misaligned with the horse's head.

**Expected behaviour**
Block trails, particles and other entities should be aligned with the entity. You should be able to instantly get on the horse, not have to be glitched 3-5 times before being able to.

**Screenshots**
http://i.demeng.dev/951575.gif
http://i.demeng.dev/89d04c.gif

**ViaVersion Dump:**
https://dump.viaversion.com/57c89fe0ae4b63bc3418fd2d25ff3623687b70697b9d867ecd4c26f8d50c8f41

**Additional server info**
TacoSpigot 1.8.8 on a Flamecord Proxy

**Comment by Demeng7215** [comment]
http://i.demeng.dev/0c8d72.png

**Comment by Xernium** [comment]
Please attempt to recreate this with a 1.9 or newer server just for reference. Since 1.8 player entity movement control changed very significantly and I just want to verify that this is 1.8 server specific

**Comment by Demeng7215** [comment]
> 
> 
> Please attempt to recreate this with a 1.9 or newer server just for reference. Since 1.8 player entity movement control changed very significantly and I just want to verify that this is 1.8 server specific
Tested on a 1.16 server using a 1.16 client, mounting works perfectly and misalignment does not seem to be happening.

**Comment by Xernium** [comment]
Me or someone else from the team will have a look but it will be difficult to recreate the shown scenario for us. Besides that, since the movement mechanic change seems to affect it- This may not get fixed or if it does, probably not soon

**Comment by Xernium** [comment]
Translating movement from and to the 1.8-1.9 border involves all kinds of hacks

**Comment by KennyTV** [comment]
Try with Paper instead of Tacospigot, Bungee instead of FlameCord, and no other plugins. If it starts working, add your things back in until it doesn't again.
