### ISSUE TITLE
EncoderException

### ISSUE THREAD

**Issue by Jack0217dev** [ViaVersion/ViaVersion#1931]
**Describe the bug, provide any errors**
https://hastebin.com/oxizeyeyof.nginx

**How can we reproduce it?**
1. Login on 1.15.2'
2. Join on server'

**Expected behaviour**
The player can join to server

**Screenshots**
https://imgur.com/a/PE38NXK

**ViaVersion Dump:**
https://dump.viaversion.com/6a2e571cf8536a2cc703a465f253c4e6bca6527ecfd99afdcb1039ef6da0f59e

**Additional server info**
Using waterfall

**Comment by KennyTV** [comment]
Update ViaVersion and ViaBackwards to the -Dev builds on https://ci.viaversion.com/
