### ISSUE TITLE
Issue when opening UC menu

### ISSUE THREAD

**Issue by Games4k** [ViaVersion/ViaVersion#1932]
**Describe the bug, provide any errors**
Error when clicking on the Ultimate Cosmetics chest: https://hastebin.com/fokaleqezi.js

**How can we reproduce it?**
1. Login on 1.16.1 server
2. Install Ultimate Cosmetics
3. Click on the chest
4. The error is displayed

**Expected behaviour**
The error should not happen

**Screenshots**

**ViaVersion Dump:**
- https://dump.viaversion.com/db6bd22945469e526795dab03b0cf3527de3528dca7d1cee3ec1d8e535b4eab9

**Additional server info**
I use the latest BungeeCord, PaperSpigot 1.16.1

**Comment by KennyTV** [comment]
This belongs on the ViaRewind issue tracker.
