### ISSUE TITLE
Player kicked when given written book in 1.8

### ISSUE THREAD

**Issue by Stixil** [ViaVersion/ViaVersion#1933]
**Describe the bug, provide any errors**
When giving the player a custom written book (a server rules book in this case), the player is kicked from the game.
Stacktrace: https://mcpaste.io/97a9009187dd554d

**How can we reproduce it?**
1. Login on 1.8'
2. Use a command to give the player a custom written book.
3. The player is kicked from the game.

**ViaVersion Dump:**
- https://dump.viaversion.com/6d6856217ed72c391f0c69f9d5006045467a3ffbbada147c8c5708b852894f3c

**Additional server info**
Waterfall-366
Paper 1.16.1 version 90
Running with ViaVersion, Rewind, and Backwards

**Comment by FormallyMyles** [comment]
Should be posted on ViaBackwards/Rewind depending on if it happens on 1.9 or just 1.8
