### ISSUE TITLE
Plugin that sends particle effects causes 1.15.2 clients to get kicked from the game

### ISSUE THREAD

**Issue by RalphORama** [ViaVersion/ViaVersion#1934]
## Describe the bug, provide any errors

I have a separate plugin, [EmotePlugin3](https://dev.bukkit.org/projects/emoteplugin3), that can send particle effects to players. Whenever someone does `/kiss` to one player, it kicks them from the server because of an error with ViaVersion.

## How can we reproduce it?

1. Setup PaperMC 1.16.1 server
2. Install [EmotePlugin3](https://dev.bukkit.org/projects/emoteplugin3) and ViaVersion 3.0.1
3. Connect to the server with a 1.16.1 client
4. Connect to the server with 1.15.2
5. In the 1.16.1 client, type `/kiss <1.15.2 client username>`
6. The 1.15.2 client will get kicked from the server

## Error Message

https://pastebin.com/bbNtSVqh

## ViaVersion Dump

https://dump.viaversion.com/cdfdbbec03febc2f0547f7a06e0ca7002855cea0c56993fb976cc18c4d8f287b

## Additional server info

EmotePlugin3: https://dev.bukkit.org/projects/emoteplugin3

**Comment by FormallyMyles** [comment]
This should be fixed in latest from ci.viaversion.com
