### ISSUE TITLE
encoder exception

### ISSUE THREAD

**Issue by mcgodbuild** [ViaVersion/ViaVersion#1935]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?

I am actually not sure what the bug is. It gave me an error message after the kick and tol me to post it on github.

**How can we reproduce it?**

I was playing with 1.12.2 on a 1.16 server like i do for weeks.
Teleported to a player with a particle trail on him. This got me kicked 2 times with the same bug error.
No idea what or how

**Expected behaviour**
Well normal gameplay i suppose. Not getting this error atleast

**Screenshots**
https://ibb.co/2SMP5rM

**ViaVersion Dump:**
Not allowed command sorry

**Additional server info**
paper spigot server, plugin list in picture
https://ibb.co/0MFYWnM

**Comment by KennyTV** [comment]
Please follow the issue template. A guess is to update to the -Dev builds https://ci.viaversion.com/
