### ISSUE TITLE
Won't let me into the server, "Broken pipe" error

### ISSUE THREAD

**Issue by BiggestPotato111** [ViaVersion/ViaVersion#1936]
**Describe the bug, provide any errors**
https://hastebin.com/noniyebovu.shell It just displays an error and doesn't let you join.

**How can we reproduce it?**
1. Login on 1.16'
2. Use a bungee cord proxy, CitzensCMD, and set the config to allow bungee connections in CitizensCMD config
3. It doesn't let you join. On 1.8, it does work *sometimes*.

**Expected behavior**
It letting me into the server

**Screenshots**
![image](https://user-images.githubusercontent.com/68661186/88719749-c5a76880-d0f1-11ea-932e-89936cd0a102.png)

**ViaVersion Dump:**
https://dump.viaversion.com/0e2434774cc94e0b2a90a661af754227cbea806647011bb29ece2dbc90baf7f2
**Additional server info**
I use BungeeCord, everything should be in the dump

**Comment by FormallyMyles** [comment]
You can disable ViaVersion auto-team in the ViaVersion config, which will solve this. Otherwise this is down to bungee not clearing teams correctly.
