### ISSUE TITLE
Kicked from server on join

### ISSUE THREAD

**Issue by speex1** [ViaVersion/ViaVersion#1937]
>.... [01:30:50 WARN]: [ViaVersion] ERROR IN Protocol1_14_4To1_15 IN REMAP OF WINDOW_ITEMS (0x15)
>.... [01:30:50 WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
>.... [01:30:50 WARN]: {Source 0: us.myles.ViaVersion.api.rewriters.ItemRewriter$1 (Anonymous)}
>.... [01:30:50 WARN]: Actual Error:
>.... [01:30:50 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
>.... [01:30:50 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
>.... [01:30:50 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
>.... [01:30:50 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
>.... [01:30:50 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
>.... [01:30:50 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
>.... [01:30:50 WARN]: at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
>.... [01:30:50 WARN]: at me.neznamy.tab.platforms.bukkit.Injector$1.write(Injector.java:99)
>.... [01:30:50 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
>.... [01:30:50 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
>.... [01:30:50 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
>.... [01:30:50 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
>.... [01:30:50 WARN]: at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
>.... [01:30:50 WARN]: at kernitus.plugin.OldCombatMechanics.utilities.packet.PacketInjector.write(PacketInjector.java:176)
>.... [01:30:50 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
>.... [01:30:50 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
>.... [01:30:50 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
>.... [01:30:50 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
>.... [01:30:50 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110)
>.... [01:30:50 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
>.... [01:30:50 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
>.... [01:30:50 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
>.... [01:30:50 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
>.... [01:30:50 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
>.... [01:30:50 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
>.... [01:30:50 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
>.... [01:30:50 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
>.... [01:30:50 WARN]: at net.minecraft.server.v1_15_R1.NetworkManager.lambda$b$6(NetworkManager.java:300)
>.... [01:30:50 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
>.... [01:30:50 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
>.... [01:30:50 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
>.... [01:30:50 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
>.... [01:30:50 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
>.... [01:30:50 WARN]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
>.... [01:30:50 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by KennyTV** [comment]
Please follow the issue template.
