### ISSUE TITLE
1.15.2 on 1.8 spigot server skulls are remapped wrongly

### ISSUE THREAD

**Issue by RaphiMC** [ViaVersion/ViaVersion#1939]
**Describe the bug, provide any errors**
If skulls with damage values higher than 5 are placed the 1.15.2 client will see random blocks and garbage and the 1.8 client sees skeleton skulls.

**How can we reproduce it?**
1. Login on a 1.8.8 spigot server with fabric 1.15.2 client'
2. Give yourself (on the 1.8 client) a head with damage: /give @p skull 1 60
3. Place it with the 1.8 client and then random blocks will appear on the 1.15.2 client instead of the skulls

**Expected behaviour**
No random blocks, skeleton skulls should be there instead.

**Screenshots**
https://prnt.sc/tq594q

Using latest ViaVersion-dev build and latest ViaFabric.

**Additional server info**
No plugins were present on the spigot 1.8.8 server.

**Comment by KennyTV** [comment]
See Discord discussion channel.
