### ISSUE TITLE
Doors broken

### ISSUE THREAD

**Issue by DumbGameMaker** [ViaVersion/ViaVersion#1941]
**Describe the bug, provide any errors**
When a door exists, it breaks. the top of the door gets misaligned with the bottom when a door is opened or placed on a certain side of a block. it gets really finicky, like sometimes it gets fixed when opening from the bottom block and the side of the block that breaks it is seemingly random.

**How can we reproduce it?**
1. server on pre-1.12
2. client on post-1.12
3. place a door and open it
4. door broken
**Expected behavior** << Shouldn't be 'behaviour'
Door works. simple. Doors should stay in one piece.
**Screenshots**
If applicable, add screenshots to help explain your problem
![2020-07-30_18 19 29](https://user-images.githubusercontent.com/61807031/88990233-4bfab080-d292-11ea-9943-a60815c4908d.png)
![2020-07-30_18 19 40](https://user-images.githubusercontent.com/61807031/88990234-4c934700-d292-11ea-94ff-06d2b9d26959.png)

**ViaVersion Dump:**
Wasn't on my own server when I decided to report this and I'm too lazy to set one up. Probably wouldn't be of much help anyway as there wouldn't be errors in logs or anything

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
I've seen the issue on literally every server on or below 1.12 so yes and no to proxy, pretty much all spigot-based software, all plugins.

**Comment by KennyTV** [comment]
Please follow the issue template. This has a config option, `serverside-blockconnections`.
