### ISSUE TITLE
Player can place block even player stand there on 1.9+

### ISSUE THREAD

**Issue by Seanoo1** [ViaVersion/ViaVersion#1942]
**How can we reproduce it?**
1. install viaversion on travertine
2. join, and try like this : https://youtu.be/W9o4JvRcnSs

**Expected behaviour**
Block should not place it.

**ViaVersion Dump:** https://dump.viaversion.com/cfe372e701c5bd400ba2426a981f051b569552efba2dedef74966e01b3143945

**Additional server info**
Use travertine bungee.

Also, I think it is fault by serverside, block placing like that doesn't when when server lagged.

**Comment by FormallyMyles** [comment]
Not fixable, install ViaVersion on your source server and we'll apply a fix.
