### ISSUE TITLE
1.9.4 client on 1.8.8 spigot server no enderdragon death sound

### ISSUE THREAD

**Issue by RaphiMC** [ViaVersion/ViaVersion#1943]
**Describe the bug, provide any errors**
If playing with a 1.9.4 client on a spigot 1.8.8 server and killing the enderdragon there is no sound on the 1.9.4 client but a 1.8.8 client will hear the normal sound.

**How can we reproduce it?**
1. Login on a spigot 1.8.8 server with a 1.9.4 client
2. Kill the enderdragon
3. No sound when beating the enderdragon

**Expected behaviour**
A sound when killing the enderdragon

**ViaVersion Dump:**
- https://dump.viaversion.com/4c1bd9544ae82da5624ac90e2427735d7fcb863e06e97cf1cef3044fc105582b

**Additional server info**
Only 1 plugin: ViaVersion latest dev build

**Comment by RaphiMC** [comment]
I have found a fix for this: Adding these two lines to us.myles.ViaVersion.protocols.protocol1_9to1_8.sounds.Effect in the static block
- addRewrite(1013, 1023);
- addRewrite(1018, 1028);
Seems like VV forgot to remap serverwide / global SFX.

**Comment by KennyTV** [comment]
Thank you, fixed!
