### ISSUE TITLE
A bug related with the plugin "Golden Enchants".

### ISSUE THREAD

**Issue by EnergyREX** [ViaVersion/ViaVersion#1944]
https://pastebin.com/3bvV52jb Gives this error. It happens when you use the Golden Enchants plugin with the enchant: Vampire. The Enchant shows particles. Maybe, it's by the particles.

To reproduce this, you only must do the following steps;
Enchant any weapon with the enchant.
Hit a mob or a player
See how it kicks the player.
It gives the following reasons too.
"Disconnected"
"Internal Exception: java.io.IOException: An existing connection  was forcibly closed by the remote host".

![unknown (1)](https://user-images.githubusercontent.com/40529173/89068235-22fd1d00-d371-11ea-997e-132c973d79c2.png)

**Comment by KennyTV** [comment]
Follow the issue template (and be sure to try builds and -dev builds from ci.viaversion.com).
