### ISSUE TITLE
Players kicked when teleported.

### ISSUE THREAD

**Issue by johncraft46** [ViaVersion/ViaVersion#1945]
Whenever a player on my server dies or gets teleported to spawn, they get kick with an error message along the lines of "readerIndex(12) + length(1) exceeds writerIndex(12): PooledUnsafeDirectByteBuf(ridx: 12, widx: 12, cap: 256)"

This also spams the console, most likely related.

31.07 16:05:30 [Server] WARN Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
31.07 16:05:30 [Server] WARN {Type: byte[], Source #1: nl.matsv.viabackwards.protocol.protocol1_13_2to1_14.Protocol1_13_2To1_14$3 (Anonymous), Source #0: nl.matsv.viabackwards.protocol.protocol1_13_2to1_14.Protocol1_13_2To1_14$3$1 (Anonymous), Data: [], Packet ID: -1}
31.07 16:05:30 [Server] WARN Actual Error: 
31.07 16:05:30 [Server] WARN Caused by: java.lang.IndexOutOfBoundsException: readerIndex(12) + length(1) exceeds writerIndex(12): PooledUnsafeDirectByteBuf(ridx: 12, widx: 12, cap: 256)
31.07 16:05:30 [Server] WARN at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1477)
31.07 16:05:30 [Server] WARN at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:731)
31.07 16:05:30 [Server] WARN at us.myles.ViaVersion.api.type.types.VarIntType.readPrimitive(VarIntType.java:18)
31.07 16:05:30 [Server] WARN at us.myles.ViaVersion.api.type.types.ByteArrayType.read(ByteArrayType.java:20)
31.07 16:05:30 [Server] WARN at us.myles.ViaVersion.api.type.types.ByteArrayType.read(ByteArrayType.java:7)
31.07 16:05:30 [Server] WARN at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:144)
31.07 16:05:30 [Server] WARN at nl.matsv.viabackwards.protocol.protocol1_13_2to1_14.Protocol1_13_2To1_14$3$1.handle(Protocol1_13_2To1_14.java:167)
31.07 16:05:30 [Server] WARN at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
31.07 16:05:30 [Server] WARN at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:127)
31.07 16:05:30 [Server] WARN at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:419)
31.07 16:05:30 [Server] WARN at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:432)
31.07 16:05:30 [Server] WARN at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:81)
31.07 16:05:30 [Server] WARN at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:323)
31.07 16:05:30 [Server] WARN at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:301)
31.07 16:05:30 [Server] WARN at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:64)
31.07 16:05:30 [Server] WARN at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
31.07 16:05:30 [Server] WARN at sun.reflect.GeneratedMethodAccessor113.invoke(Unknown Source)
31.07 16:05:30 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
31.07 16:05:30 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
31.07 16:05:30 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:473)
31.07 16:05:30 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
31.07 16:05:30 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:243)
31.07 16:05:30 [Server] WARN at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
31.07 16:05:30 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
31.07 16:05:30 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
31.07 16:05:30 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
31.07 16:05:30 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
31.07 16:05:30 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
31.07 16:05:30 [Server] WARN at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
31.07 16:05:30 [Server] WARN at com.gmail.olexorus.witherac.Xi.write(ze:533)
31.07 16:05:30 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
31.07 16:05:30 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
31.07 16:05:30 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
31.07 16:05:30 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
31.07 16:05:30 [Server] WARN at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
31.07 16:05:30 [Server] WARN at com.gmail.olexorus.witherac.Xi.write(ze:533)
31.07 16:05:30 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
31.07 16:05:30 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
31.07 16:05:30 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
31.07 16:05:30 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
31.07 16:05:30 [Server] WARN at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
31.07 16:05:30 [Server] WARN at me.neznamy.tab.platforms.bukkit.Injector$1.write(Injector.java:99)
31.07 16:05:30 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
31.07 16:05:30 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
31.07 16:05:30 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
31.07 16:05:30 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
31.07 16:05:30 [Server] WARN at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110)
31.07 16:05:30 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
31.07 16:05:30 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
31.07 16:05:30 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
31.07 16:05:30 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
31.07 16:05:30 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
31.07 16:05:30 [Server] WARN at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
31.07 16:05:30 [Server] WARN at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
31.07 16:05:30 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
31.07 16:05:30 [Server] WARN at net.minecraft.server.v1_15_R1.NetworkManager.lambda$b$6(NetworkManager.java:300)
31.07 16:05:30 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
31.07 16:05:30 [Server] WARN at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
31.07 16:05:30 [Server] WARN at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
31.07 16:05:30 [Server] WARN at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
31.07 16:05:30 [Server] WARN at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
31.07 16:05:30 [Server] WARN at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
31.07 16:05:30 [Server] WARN at java.lang.Thread.run(Thread.java:748)
31.07 16:05:30 [Server] WARN io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues

**How can we reproduce it?**
1. Login on any version to our server. (cubex.network)
2. Teleport to spawn or die to a mob.
3. You will get kicked with a complex message.

**Expected behaviour**
I expected the player to just go back to spawn, not be kicked.

**ViaVersion Dump:**
https://dump.viaversion.com/6b8c7236f7c496b747bd11445a7b0708c8db58724a631745c754d67bfd9da6c2

**Additional server info**
We do use bungee cord, our server is 1.15.2, and we have a list of 106 plugins.

**Comment by FormallyMyles** [comment]
You should open this on the viabackwards issue tracker. You should also try the latest -DEV builds from ci.ciaversion.com if you haven't already.
