### ISSUE TITLE
Random Error In Console

### ISSUE THREAD

**Issue by NightRiider** [ViaVersion/ViaVersion#1946]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?
Not sure what the problem is/was just randomly saw this error in console that told me to report it here.

**How can we reproduce it?**
No idea it happened randomly not sure what made it happen

**Expected behaviour**
Nothing

**Screenshots**
Just the error
https://pastebin.com/P4gk6ZvG

**ViaVersion Dump:**
https://dump.viaversion.com/f645445069f4f39f965ea08bbbc4104375281697d6dea818de40fc47ac341974

**Additional server info**
Don't use bungeecord, this is a list of all my plugins:
https://imgur.com/a/o0QcPNz

**Comment by FormallyMyles** [comment]
This is a client sending bad data to your server. Update to ci.viaversion.com to hide these.
