### ISSUE TITLE
Disconnection in 1.15.2 on a 1.8.8 server

### ISSUE THREAD

**Issue by Matocolotoe** [ViaVersion/ViaVersion#1948]
**Describe the bug, provide any errors**
When a player logs in with 1.15.2 in a 1.8.8 server, he gets instantly disconnected.

**How can we reproduce it?**
See above.

**Expected behaviour**
The player should be able to connect.

**Screenshots**
None, but here is the stacktrace: https://pastebin.com/rnUwswaV

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/6e1fdb6420e6953d228b9b5f7b3908f0a401770a09ea71920284de5ab0920fe0

**Additional server info**
Using latest Spigot 1.8.8 built with BuildTools

**Comment by FormallyMyles** [comment]
Would you be able to copy your server and test with no other plugins?

**Comment by Matocolotoe** [comment]
Sorry for the late answer, the same error happens with no other plugins and the same config options.

**Comment by FormallyMyles** [comment]
Can you test with a clean world?

**Comment by Matocolotoe** [comment]
Well I tested with a brand new *server*

**Comment by FormallyMyles** [comment]
You can try latest from ci.viaversion.com otherwise something is up as it doesn't happen to other 1.8.8 users

**Comment by Matocolotoe** [comment]
Same error with latest build

**Comment by FormallyMyles** [comment]
Can you provide a viaversion dump of your clean server and the error?

**Comment by Matocolotoe** [comment]
Error : https://hastebin.com/viqezolepo.cs
/viaversion dump : https://dump.viaversion.com/63757e4caa67faf085ba32d038555239eaa3da3be4bc72adee925be01c4570cf

**Comment by FormallyMyles** [comment]
> Error : https://hastebin.com/viqezolepo.cs
> /viaversion dump : https://dump.viaversion.com/63757e4caa67faf085ba32d038555239eaa3da3be4bc72adee925be01c4570cf

Can you try with a fresh ViaVersion config?

**Comment by Matocolotoe** [comment]
The issue doesn't occur anymore with a fresh config

**Comment by FormallyMyles** [comment]
Closing as it's most likely the blockconnection method. 

If you have info otherwise on what causes it let us know, but I suspect it'd be that.
