### ISSUE TITLE
Player can place block even player stand there on 1.15.2 

### ISSUE THREAD

**Issue by MyPictureBed** [ViaVersion/ViaVersion#1950]
**Describe the bug, provide any errors**
1.Player can place block even player stand there on 1.15.2 

**How can we reproduce it?**
1. Login on 1.15.2 client
2. Connect to the server
3. I can place blocks inside me

**Expected behaviour**
I can not place blocks inside me

**ViaVersion Dump:**
https://dump.viaversion.com/d61f6595b6c4620f245b464087a64cc2322cecc2f301a8aa32e9de663bf1b157

**Additional server info**
When using the latest version Spigot 1.8.8 server (with ViaVersion), the BungeeCord proxy (with ViaVersion), and a 1.15.2 client.
The ViaVersion plugin (latest dev version) is used on a BungeeCord proxy (git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:15b5141:1529)
I'm sure no plugin will affect ViaVersion work

My english is not well , sorry about that.

**Comment by FormallyMyles** [comment]
#1087
