### ISSUE TITLE
all higher versions do not detect  entity damage event 

### ISSUE THREAD

**Issue by SharkblackFr** [ViaVersion/ViaVersion#1951]
Hello,
all higher versions do not detect entity damage event 
and I use that via version to allow the player to join with higher game versions

can you help me 

- **_here are the lines of my plugins that can detect if the players no longer have life :_**

` @EventHandler(priority=EventPriority.HIGHEST)
    public void onPlayerDamageNormal(EntityDamageEvent event) {
        if(killPlayer(event.getEntity(), event.getFinalDamage())) {
            event.setCancelled(true);
        }
    }
    
    @EventHandler(priority=EventPriority.HIGHEST)
    public void onPlayerDamageEntity(EntityDamageByEntityEvent event) {
        if(killPlayer(event.getEntity(), event.getFinalDamage())) {
            event.setCancelled(true);
        }
    }
    
    @EventHandler(priority=EventPriority.HIGHEST)
    public void onPlayerDamageBlock(EntityDamageByBlockEvent event) {
        if(killPlayer(event.getEntity(), event.getFinalDamage())) {
            event.setCancelled(true);
        }
    }
    
    private boolean killPlayer(Entity entity, Double damage) {
        if(entity instanceof Player) {
            Player player = (Player) entity;
            EntityLiving el = ((CraftPlayer)entity).getHandle();
            if(damage >= el.getAbsorptionHearts() + player.getHealth()) {
                return true;
            }
        }
        return false;
    }`

- **_and here is my viaversion configuration:_**

`# Thanks for downloading ViaVersion
# Ensure you look through all these options
# If you need help:
# Discord - https://viaversion.com/discord
# viaversion.com - Discussion tab
# Docs - https://docs.viaversion.com/display/VIAVERSION/Configuration
# 
# ----------------------------------------------------------#
#                     GLOBAL OPTIONS                       #
# ----------------------------------------------------------#
# 
# Should ViaVersion check for updates?
checkforupdates: true
# Send the supported versions with the Status (Ping) response packet
send-supported-versions: false
# Block specific Minecraft protocols that ViaVersion allows
# List of all Minecraft protocol versions: http://wiki.vg/Protocol_version_numbers or use a generator: https://via.krusic22.com
block-protocols:
- 404
- 401
- 393
- 340
- 338
- 335
- 316
- 315
- 210
- 110
- 109
- 108
- 107
- 47
- 5
- 4
# Change the blocked disconnect message
block-disconnect-msg: T'as version Minecraft n'est pas support?s, veuillez revenir
  en 1.14.4 ou versions sup?rieures!
reload-disconnect-msg: Les serveurs redemarre, pour plus d'informations https://play-full.fr
suppress-conversion-warnings: false
max-pps: 800
max-pps-kick-msg: Tu envoie trop de packets aus serveur, c'est pour cela que tu as
  ?t? kick!
tracking-period: 6
tracking-warning-pps: 120
tracking-max-warnings: 4
tracking-max-kick-msg: Tu envoie trop de packets aus serveur, c'est pour cela que
  tu as ?t? kick!
hologram-patch: false
hologram-y: -0.96
piston-animation-patch: false
chat-nbt-fix: true
quick-move-action-fix: false
team-colour-fix: true
disable-1_13-auto-complete: false
1_13-tab-complete-delay: 0
fix-low-snow-collision: false
fix-infested-block-breaking: true
truncate-1_14-books: false
change-1_9-hitbox: false
change-1_14-hitbox: false
fix-non-full-blocklight: true
fix-1_14-health-nan: true
use-1_15-instant-respawn: false
serverside-blockconnections: false
blockconnection-method: packet
reduce-blockstorage-memory: false
flowerstem-when-block-above: false
vine-climb-fix: false
prevent-collision: true
auto-team: true
suppress-metadata-errors: false
shield-blocking: true
simulate-pt: true
nms-player-ticking: true
bossbar-patch: true
bossbar-anti-flicker: false
use-new-effect-indicator: true
use-new-deathmessages: true
item-cache: true
anti-xray-patch: true
replace-pistons: false
replacement-piston-id: 0
force-json-transform: false
minimize-cooldown: true
left-handed-handling: true
`

**Comment by KennyTV** [comment]
Please follow the issue template (Via also does not modify server event handling - if the player receives damage, the server will do everything as usual).

**Comment by SharkblackFr** [comment]
The server will do everything as usual when the Player takes a damage that kills him
