### ISSUE TITLE
Increase weapon speed on 1.9+ clients

### ISSUE THREAD

**Issue by LinsaFTW** [ViaVersion/ViaVersion#1952]
On Spigot 1.8 with 1.9+ clients weapon cooldown indicator flashes everytime you make a hit.

![2020-08-03_05 52 34](https://user-images.githubusercontent.com/25271111/89164845-ffdb9480-d54d-11ea-865d-42fe6d4f723b.png)

Increase the weapon speed in 1.9+ clients on 1.8 servers to fix this.

**Comment by FormallyMyles** [comment]
There is a config option called "minimize-cooldown" for this.

**Comment by LinsaFTW** [comment]
> There is a config option called "minimize-cooldown" for this.

It's already true. Why making it a option tho?
