### ISSUE TITLE
1.16 client on 1.16.1 server

### ISSUE THREAD

**Issue by rur0** [ViaVersion/ViaVersion#1953]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?

**How can we reproduce it?**
1. create 1.16.1 server with paper on a Bungee proxy 
2. join 
3. Kicked whilst connecting to lobby: "Outdated client! Please use 1.16.1"

**Expected behaviour**
to be able to join with 1.16 client on a 1.16.1 server

**ViaVersion Dump:**
- https://dump.viaversion.com/24710477ede3c12fb360d06fa2e0bcf1210c3d57a7e2edf948727e97c384b235

**Comment by KennyTV** [comment]
ViaVersion allows newer clients to connect; you want ViaBackwards.
