### ISSUE TITLE
ViaVersion error

### ISSUE THREAD

**Issue by MBDEV13** [ViaVersion/ViaVersion#1956]
**Describe the bug, provide any errors**
I get this error when player joins: https://hastebin.com/oradukigah.cs

**How can we reproduce it?**
Unknown

**Expected behaviour**
No error

**ViaVersion Dump:**
https://dump.viaversion.com/5bcce8a7120fa0e918a7a21a6a6fb922fed58ff7d43bf8b527de2bd1ec79b300

**Additional server info**
Do you use a proxy (eg. BungeeCord)? Yes.
What software do you use and what plugins? Paper 1.16.1, latest build

**Comment by FormallyMyles** [comment]
Hastebin doesn't load for me, you should also try find additional information on what the cause might be. Try the latest builds from ci.viaversion.com. 

Otherwise repost the error and I'll reopen.

**Comment by MBDEV13** [comment]
https://pastebin.com/Qbred4KU

**Comment by MBDEV13** [comment]
> 
> 
> Hastebin doesn't load for me, you should also try find additional information on what the cause might be. Try the latest builds from ci.viaversion.com.
> 
> Otherwise repost the error and I'll reopen.

https://pastebin.com/Qbred4KU

**Comment by FormallyMyles** [comment]
Are you able to replicate this with just the Via plugins installed?

**Comment by MBDEV13** [comment]
> 
> 
> Are you able to replicate this with just the Via plugins installed? / A vanilla client?

I can't replicate it at all. It only happens on some rare players join.
