### ISSUE TITLE
1.15.2 kick bug

### ISSUE THREAD

**Issue by iAvearges** [ViaVersion/ViaVersion#1957]
**Describe the bug, provide any errors**
Server version: Paper 1.16.1 (Builder 130)
Client version: 1.15.2
Particles from 1.16 spawn (Not sure what ones) player is kicked and error in console (https://paste.danielraybone.com/opuwetujim.hs)

**How can we reproduce it?**
1. Login on 1.15.2
2. spawn x particles from 1.16 (This was from MMOCore when healing a player)
3. users on 1.15.2 are kicked with this error in console (Link above)

**Expected behaviour**
To not be kicked.

**ViaVersion Dump:**
https://dump.viaversion.com/2fad4459fc0086b17ae35757f96c9e4551472c694da88aef66436fa1f466c150

**Additional server info**
The server is under WaterFall
![image](https://dannn.net/FHhZX)

**Comment by FormallyMyles** [comment]
Use the -DEV versions from ci.viaversion.com
