### ISSUE TITLE
Bug when someone leave server

### ISSUE THREAD

**Issue by ArefyNetwork** [ViaVersion/ViaVersion#1958]
**Describe the bug, provide any errors**
http://arefy.net:7777/ibineletug.cs

**How can we reproduce it?**
When people leave server

**ViaVersion Dump:**
https://dump.viaversion.com/c3cf2bbfeb5d96cae9b036ecf2e15b54e1b05178340dcf4cf9d3dbff45abf314

**Comment by FormallyMyles** [comment]
This is a client sending bad data. If you download the latest from ci.viaversion.com these are hidden.

Usually server list pings
