### ISSUE TITLE
Teleport bug?

### ISSUE THREAD

**Issue by OrangeAY** [ViaVersion/ViaVersion#1962]
This bug occurred when someone request to teleport to me and it left a weird error message I did /tpaccept so that they would tp to me and I got this weird error message.
![10FBAC55-369D-40D3-9021-47E6B9BA0EA3](https://user-images.githubusercontent.com/69226647/89362476-59d88780-d711-11ea-801c-c3d69659c194.png)
![2106A695-F8CC-4760-8684-8845FAA6269B](https://user-images.githubusercontent.com/69226647/89362487-5fce6880-d711-11ea-951e-a74a3199436e.png)
![BF256D13-4D51-4225-AEA0-8C3B7CB6D7D0](https://user-images.githubusercontent.com/69226647/89362496-64931c80-d711-11ea-95f8-9617cb3a7caa.png)

**Comment by KennyTV** [comment]
Please follow the issue template.
