### ISSUE TITLE
json reader kicking players when opening shulkers. (possibly due to unicode character item names)

### ISSUE THREAD

**Issue by 22s** [ViaVersion/ViaVersion#1968]
**Describe the bug, provide any errors**
https://paste.gg/p/anonymous/d65cd2d444ad400ab7567aa389353be5

**Expected behaviour**
be able to open the shulker w/o getting kicked

**ViaVersion Dump**
https://dump.viaversion.com/1e9775b319db2d4663727594cfc004af3f2f8d39956550faf6eea61c59eeba0e

**Additional server info**
I use waterfall, with yatopia for 1.16.1

**Comment by 22s** [comment]
![image](https://user-images.githubusercontent.com/58058658/89489175-b8782280-d75e-11ea-941a-c1b943c3002f.png)
Opened the shulker and this was the only unusually named item.

**Comment by KennyTV** [comment]
Do you see any item called "Allah Kabar" (could also be the shulker box itself)?

**Comment by 22s** [comment]
Yes that was one of the names of a shulker with the exact same contents

**Comment by KennyTV** [comment]
Should be fixed in the latest -Dev build.
