### ISSUE TITLE
1.15.2 Server - Error when teleporting

### ISSUE THREAD

**Issue by BeastModeNinja** [ViaVersion/ViaVersion#1973]
One of my players (while using 1.8.9) runs into errors when teleporting to our spawn and elsewhere. He gets kicked from the server, then logs back on and has lost items out of his inventory. Here is a pastbin of the errors when he gets kicked and when he joins back - https://pastebin.com/K693ZLU4

**Expected behaviour**
I expect him to be able to teleport just fine and continue on without being kicked or losing items

**ViaVersion Dump**
https://dump.viaversion.com/fea385056748d5f0252ed5847c57565c7cefd345de0acea2d3a498b92b1dd7b9

**Additional server info**
We use bungeecord aswell as several other plugins. We run the latest version of Paper 1.15.2

**Comment by FormallyMyles** [comment]
This should be on ViaBackwards issue tracker (may even be ViaRewind if it only happens on 1.8)

**Comment by BeastModeNinja** [comment]
@FormallyMyles It is a lot of ViaVersion errors
