### ISSUE TITLE
Error with 1.8.8 client joining 1.16.1 server

### ISSUE THREAD

**Issue by Projecki** [ViaVersion/ViaVersion#1974]
**Describe the bug, provide any errors**
https://pastebin.com/5GV2UXkV
The error says to paste this here. The 

**How can we reproduce it?**
1. Login on 1.8.8 to 1.16.1 paper-131 server

**Expected behaviour**
The player does not get kicked off the server.

**ViaVersion Dump**
https://dump.viaversion.com/31d6d4fe4753b4e90f6d87c21fe6c197e176ccc0bc15b053d8925efdb05b04f5

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
Waterfall latest ver. Server is in offline mode.

**Comment by BuzzTheGamer23** [comment]
Try with these versions instead (make sure to delete the old jars, and to restart the server)
ViaVersion - https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/jar/target/ViaVersion-3.0.2-SNAPSHOT.jar
ViaBackwards - https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/lastSuccessfulBuild/artifact/all/target/ViaBackwards-3.0.2-SNAPSHOT.jar
ViaRewind - https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/lastSuccessfulBuild/artifact/all/target/ViaRewind-1.5.1-SNAPSHOT.jar
