### ISSUE TITLE
You tell me.

### ISSUE THREAD

**Issue by Relaxing9** [ViaVersion/ViaVersion#1976]
**Describe the bug, provide any errors**
Seems to be a run-time bug, server was running, no one was online, checked my console saw this, said to report...
[https://paste.gg/p/anonymous/bbd26016388f4006a17188e77efc910e](https://paste.gg/p/anonymous/bbd26016388f4006a17188e77efc910e) 

**How can we reproduce it?**
No idea

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.
[https://dump.viaversion.com/92f7491a0a8ce91739ca2d8500f01bacc9fdce6c004bf26ab12defed49354e3b](https://dump.viaversion.com/92f7491a0a8ce91739ca2d8500f01bacc9fdce6c004bf26ab12defed49354e3b)
**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
No bungee cord

**Checklist**
- [Yes ] I have included a Viaversion dump
- [ Yes] If applicable, I have included a paste (not a screenshot) of the error
- [No ] I have tried a build from https://ci.viaversion.com/ and the issue still persists (no idea how to reproduce)

**Comment by FormallyMyles** [comment]
Bad client sending data, update to latest build from ci.viaversion.com
