### ISSUE TITLE
[1.15.2] Shulker Box lores are missing information

### ISSUE THREAD

**Issue by Affixes** [ViaVersion/ViaVersion#1978]
**Describe the bug, provide any errors**
Using a PaperSpigot 1.12.2 server, mining Shulker Boxes on a non-native client (i.e. 1.15.2) will generate a lore that does not contain all of the items which are in the Shulker Box.

**How can we reproduce it?**
1. Create a Spigot server running version 1.12.2
2. Insert ViaVersion (tested using 3.0.1)
3. Login with version 1.15.2
4. Place down a Shulker Box with items, and mine this Shulker Box

**Expected behaviour**
The lore is expected to contain all of the items which are held in the Shulker Box.

**Screenshots**
- Client 1.12.2 (working): https://gyazo.com/2bb93761c26d90265b31518be067bd50
- Client 1.15.2 (not working): https://gyazo.com/a5f6f46363297c1ad40a0056959ff9a9

**ViaVersion Dump**
https://dump.viaversion.com/6c883d5355fba6ef729fb4e4190692131107001af5d046651804af6199f57a06

**Additional server info**
None.

**Checklist**
- [X] I have included a Viaversion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Sorry, but this is a won't fix due to it opening up your server for a lot of really enduring processing and might even be abused to 'attack' your server - so it is just not worth the penalty.
