### ISSUE TITLE
ERROR IN BaseProtocol IN REMAP OF 0x00->0x00

### ISSUE THREAD

**Issue by chris998** [ViaVersion/ViaVersion#1979]
**Describe the bug, provide any errors**
I have NO clue what this error means but its alot of error.....https://pastebin.com/bTYQRXKg

**How can we reproduce it?**
All i did was umm.... log off and didn't get onto the console next morning and see the error . So i don't think i can reproduce it.

**Expected behaviour**

**ViaVersion Dump**
 https://dump.viaversion.com/87fcaaf534d8bf7e9f8c65526f425f386e6e82f2216360e1a08987489b01e787

**Additional server info**
all plugins https://prntscr.com/tum7zx
running Spigot 1.15.2 

**Checklist**
- [ Yes ] I have included a Viaversion dump
- [ Yes ] If applicable, I have included a paste (not a screenshot) of the error
- [ No.. It was working fine until today when i saw that error. ] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
This is fixed with the 3.0.2/3.1.0 builds on  https://ci.viaversion.com/
