### ISSUE TITLE
Error with server selector

### ISSUE THREAD

**Issue by Higgins4k** [ViaVersion/ViaVersion#1989]
**Describe the bug, provide any errors**
https://hastebin.com/vajequpoko.cs

**How can we reproduce it?**
1. Login on 1.8.9
2. Server selector on Minestory (play.minestory.xyz) [Not sure why it happens so can't tell you to recreate it]

**Expected behaviour**
Opens server selector (worked fine before the 1.16.2 update)

**Screenshots**

**ViaVersion Dump**
https://dump.viaversion.com/edd42d810b3181b60a7d8c8b721872dfd85ab96991b925f10a281658fc877697

**Additional server info**
Waterfall

**Checklist**
- [ X] I have included a Viaversion dump
- [X ] If applicable, I have included a paste (not a screenshot) of the error
- [X ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Your ViaRewind is outdated.
