### ISSUE TITLE
AntiCheat thinks you hack when swimming in water on 1.13+ on a <1.12 server

### ISSUE THREAD

**Issue by Welcome234** [ViaVersion/ViaVersion#1993]
Hello, I am experencing an issue with my anticheat "NoCheatPlus" and ViaVersion on my 1.12.2 server, so when I am playing on 1.13+ Versions my anticheat thinks I am hacking because it thinks the movement is not normal due to it being on 1.12.2, if I swim in water on 1.12 and under there are no issues like this.

Is there anyway I can fix this and stop this from occuring

Here is the Screenshot of the hack it thinks it is
![image](https://user-images.githubusercontent.com/68016689/90189769-b09b2c80-ddb5-11ea-9d1c-b1eeebac19f0.png)

https://dump.viaversion.com/259affb74e8a8ebe34d85debaa37ad600388f49511ed2db46a24d1d6042a7a8b

I use a spigot 1.12.2 Server and has 65 plugins (including the NoCheatPlus)

**Comment by FormallyMyles** [comment]
Not fixable, you'd need to adjust your anti-cheat
