### ISSUE TITLE
Not possible to support RGB on MOTD for older and newer servers

### ISSUE THREAD

**Issue by jmanpenilla** [ViaVersion/ViaVersion#1999]
**Describe the bug, provide any errors**
When ViaVersion is installed, PaperServerListPingEvent.getClient().getProtocolVersion() returns the server's protocol version instead of the clients.

**How can we reproduce it?**
1. Listen to PaperServerListPingEvent
2. Call event.getClient().getProtocolVersion()
3. Clients from 1.8-1.16 will all report to be the protocol version of the server.

**Expected behaviour**
1. Listen to PaperServerListPingEvent
2. Call event.getClient().getProtocolVersion()
3. The returned int will be the protocol version of the client

**Additional context**
- Tested to happen on Paper 1.16.1 & 1.16.2
- I am using the returned protocol version to either give the client a motd with RGB colors if they are >=1.16, or one with downsampled colors if their version is before 1.16. Currently having ViaVersion installed breaks this, because all clients will report to be up to date. This causes gray colors when old clients get sent RGB colors.

**Comment by FormallyMyles** [comment]
Use ViaVersions API for this

**Comment by FormallyMyles** [comment]
I'll reopen but relabel this issue as it can probably be improved

**Comment by jmanpenilla** [comment]
I'll look into using the VV API to fix this for my plugin.

I do agree that it would be nice for the Paper API to continue reporting the correct version somehow, but again it's not a major issue for me to just use the VV API when available.
