### ISSUE TITLE
Random Frame Lag

### ISSUE THREAD

**Issue by BurnhamR** [ViaVersion/ViaVersion#2001]
**Describe the bug, provide any errors**
No error in the console, but the plugin ViaVersion will randomly cause players to have frame lag and freeze in the server, for other players it just looks like they stop moving for a second then catches back up.
I uninstalled all plugins, reset worlds, and more, continues to appear.

**How can we reproduce it?**
[Spigot 1.8.8](https://cdn.getbukkit.org/spigot/spigot-1.8.8-R0.1-SNAPSHOT-latest.jar)
[ViaVersion 3.1.0](https://www.spigotmc.org/resources/viaversion.19254/download?version=350151) also tried 3.1.1-SNAP
Run around, Jumping. On blocks like stairs, off edges, glass, ender chests seem to cause it the most.
Will randomly freeze for a second or two

**Expected behavior**
No lag, or freezing.

**ViaVersion Dump**
https://dump.viaversion.com/d2cc0ecda5650dc335c5e559506d7c047dc13ea9e5c1d07ad2028a689a1afe0a

**Additional server info**
On a proxy network, Custom Fork of [Waterfall](https://papermc.io/ci/job/Waterfall/lastSuccessfulBuild/artifact/Waterfall-Proxy/bootstrap/target/Waterfall.jar)

**Checklist**
- [Y] I have included a Viaversion dump
- [Y] If applicable, I have included a paste (not a screenshot) of the error
- [Y] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Clientlag isn't something we can fix. This might be due to the heavy lighting changes and/or just because of a slow client.

**Comment by BurnhamR** [comment]
> 
> 
> Clientlag isn't something we can fix. This might be due to the heavy lighting changes and/or just because of a slow client.

Being it happens in every single one of my servers running ViaVersion 3.1.0 and to every user, even a localhost user only when ViaVersion is installed, this is something to do with ViaVersion. I can run my servers perfectly with no frame lag when via version isn't installed. but the frame lag freeze the entire player in the server, and can cause invalid movement alerts.

**Comment by KennyTV** [comment]
ViaVersion does not modify protocol for players with the same client as server version whatsoever.

**Comment by BurnhamR** [comment]
At this time it would seem it doesn't affect players on the same client version as server, Server version is 1.8.8, but anything client wise newer seems to get the error.
