### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by AustinFRG** [ViaVersion/ViaVersion#2008]
**Describe the bug, provide any errors**
16.08 18:50:14 [Disconnect] User AustinFRG has disconnected, reason: Internal Exception: java.io.IOException: Error while write(...): Broken pipe

**How can we reproduce it?**
1. Login on 1.8.9 with SportPaper'

**Expected behaviour**
I expected to not crash and get an error. 🤔 

**Screenshots**
https://austinfrg.is-inside.me/aZZe0O0B.png

**ViaVersion Dump**
https://dump.viaversion.com/a2fccf36d9ed027d26c872aabfc74d375144486096cd762764d221f04ef8138b

**Additional server info**
ajQueue, AntiDisconnectSpam, BasicInfo, BileTools, Command4Bungee, CraftingStore, Matrix, PermissionsBukkit, PGM, ProtocolLib, Vault, VaultChatFormatter, ViaRewind, ViaVersion, VPNGuard

**Checklist**
- [✅] I have included a Viaversion dump
- [✅] If applicable, I have included a paste (not a screenshot) of the error
- [✅] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by AustinFRG** [comment]
**Note:** I also tried Paper and Spigot.

**Comment by KennyTV** [comment]
We need the full console error. And your dump says you're not even using ViaBackwards?
