### ISSUE TITLE
1.16 players in creative mode create ghost blocks if breaking with a sword

### ISSUE THREAD

**Issue by Govindass** [ViaVersion/ViaVersion#2009]
**Describe the bug, provide any errors**
When you a break a block while holding a sword and you're in creative gamemode, the block becomes invisible, while really it wasn't broken

**How can we reproduce it?**
1. Login on 1.16.1 on a 1.12.2 server with ViaVersion
2. Click on a block while holding a sword and being in creative mode
3. The broken block is displayed as broken, while it wasn't really broken, so if you walk into it, you'll be teleported back

**Expected behaviour**
For the block to re-appear instantly as they aren't supposed to be able to break it with a sword

**Screenshots**
None

**ViaVersion Dump**
https://dump.viaversion.com/fbd5d727ee990a7e3e75fcad2be0f2b70aee594a3de00fc6d5bdb45f6e371179

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
I use FlameCord with AntiBot, LimeworkProxy(custom plugin), LuckPerms, BungeeTablistPlus, spark, FastLogin, BungeeGuard, BuycraftX, PlayerTabComplete

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
You can't break blocks in creative with a sword (in 1.16)... Try without other plugins and with a normal Bungee please (and possibly no modded client). I will reopen this if you can actually reproduce this on a clean server.

**Comment by Govindass** [comment]
weird, but I couldn't break blocks anymore after relogging, while I had this issue for a while... xD
