### ISSUE TITLE
Tools attack damage information is wrongly display for 1.9+ players on 1.8 server

### ISSUE THREAD

**Issue by Seanoo1** [ViaVersion/ViaVersion#2010]
**Describe the bug, provide any errors**

**How can we reproduce it?**
1. Login with 1.9+ on 1.8 server
2. Open inventory
3. see the tools and then see attack damage info

**Checklist**
- [Not needed] I have included a Viaversion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [Yes] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
There was an open pr, but it's too ugly of a lore hack, sorry. (https://github.com/ViaVersion/ViaVersion/pull/1385)
