### ISSUE TITLE
Server Selector not allowing you to change servers

### ISSUE THREAD

**Issue by johncsuti** [ViaVersion/ViaVersion#2013]
**Describe the bug, provide any errors**
A new issue using 3.1.1-SNAPSHOT same issue as #1989 not sure what is causing it.

**How can we reproduce it?**
1. Login on to a velocity network using 1.16.1 while the server is on 1.16.1
2. Right click the selector
3. Choose a server it will close and say sending you to the server
4. Nothing happens...

**Expected behavior**
Sends you to the server you pick.

**Screenshots**
N/A

**ViaVersion Dump**
https://dump.viaversion.com/119fd4229976e9cd7da32261ed5d0a9c1b3b8d58632f73770b0c19a3bcb655eb

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
Velocity:
ViaVersion 3.1.1-snapshot
ViaBackwords 3.1.1-snapshot
Crafting Store
NuVotifier
Velocity Lobby Plugin

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
ViaVersion does not modify protocol of clients with the same version as the server.
