### ISSUE TITLE
Bug between viaversion, itemtochat, and silkspawners causes immediate disconnect from proxy.

### ISSUE THREAD

**Issue by pcisafox** [ViaVersion/ViaVersion#2014]
**Describe the bug, provide any errors**
When using itemtochat on a mob spawner gotten from the silkspawners plugin, the server is disconnected from proxy and kick everyone off the server. Here is the bug https://paste.gg/p/anonymous/e7a1c86529e04f809f275cfa1981d447.

**How can we reproduce it?**
1. Boot up a 1.12.2 server with itemtochat, silkspawners, and viaversion.
2. use /ss give (name) (spawner_type) 1
3. Do [Item] in chat while holding spawner

**Expected behaviour**
Normally, this would put the item in the chat where people can hover over the item to see details about the spawner.

**Screenshots**
![image](https://user-images.githubusercontent.com/60077717/90463037-059db200-e0d8-11ea-8fa4-0560183a0f1d.png)
![image](https://user-images.githubusercontent.com/60077717/90463075-14846480-e0d8-11ea-9356-78affe2e755f.png)
*Disconnect from proxy after*
![image](https://user-images.githubusercontent.com/60077717/90463174-45649980-e0d8-11ea-9d82-d507b45a4dfc.png)

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/d4091487c8495763c4e0c0f4eda8f6586368cebb297b240f1288390ea59cd29a

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
We use waterfall for proxy and paper for the server. In ss, i have posted a picture listing all the server plugins as well.

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Update to a ci build.
