### ISSUE TITLE
1.16.2 client 

### ISSUE THREAD

**Issue by VenixMC** [ViaVersion/ViaVersion#2015]
**Describe the bug, provide any errors**
https://paste.gg/p/anonymous/71231e9df29b4e52957569eef843a0cd/files/46eaa1c094704f7d9d360632f512598a/raw

**How can we reproduce it?**
1. Login on 1.16.2'
2. At moment later
3. The console show the error

**ViaVersion Dump**
- https://dump.viaversion.com/9f79da0633dc5ffc9d832457b7d501df1d287bd9edf11c343b735c13f7f8dafb

**Checklist**
- [✅ ] I have included a Viaversion dump
- [✅ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
This is very likely someone messing with chunk data. Try to reproduce this without other plugins / around what chunk that happens. If you can reproduce it on a clean setup, we will reopen this.
