### ISSUE TITLE
Giant Error x2

### ISSUE THREAD

**Issue by AlbertPallardo** [ViaVersion/ViaVersion#2017]
[ViaVersion] ViaVersion detected server version: 1.15.2(578)
> [10:07:15] [pool-31-thread-1/WARN]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
> [10:07:15] [pool-31-thread-3/WARN]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
> [10:07:15] [pool-31-thread-2/WARN]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
> [10:07:15] [pool-31-thread-2/WARN]: at sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
> [10:07:15] [pool-31-thread-2/WARN]: at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1967)
> [10:07:15] [pool-31-thread-2/WARN]: at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:331)
> [10:07:15] [pool-31-thread-2/WARN]: at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:325)
> [10:07:15] [pool-31-thread-2/WARN]: at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1688)
> [10:07:15] [pool-31-thread-2/WARN]: at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:226)
> [10:07:15] [pool-31-thread-2/WARN]: at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1082)
> [10:07:15] [pool-31-thread-2/WARN]: at sun.security.ssl.Handshaker.process_record(Handshaker.java:1010)
> [10:07:15] [pool-31-thread-2/WARN]: at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1079)
> [10:07:15] [pool-31-thread-2/WARN]: at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1388)
> [10:07:15] [pool-31-thread-2/WARN]: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1416)
> [10:07:16] [pool-31-thread-2/WARN]: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1400)
> [10:07:16] [pool-31-thread-2/WARN]: at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
> [10:07:16] [pool-31-thread-2/WARN]: at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
> [10:07:16] [pool-31-thread-2/WARN]: at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340)
> [10:07:16] [pool-31-thread-2/WARN]: at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315)
> [10:07:16] [pool-31-thread-2/WARN]: at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)
> [10:07:16] [pool-31-thread-2/WARN]: at com.elikill58.negativity.universal.utils.UniversalUtils.getContentFromURL(UniversalUtils.java:212)
> [10:07:16] [pool-31-thread-2/WARN]: at com.elikill58.negativity.universal.Stats.lambda$0(Stats.java:43)
> [10:07:16] [pool-31-thread-2/WARN]: at com.elikill58.negativity.universal.Stats$$Lambda$3733/000000002C030150.run(Unknown Source)
> [10:07:16] [pool-31-thread-2/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [10:07:16] [pool-31-thread-2/WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [10:07:16] [pool-31-thread-2/WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [10:07:16] [pool-31-thread-2/WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [10:07:16] [Server thread/INFO]: No expansions were registered!
> [10:07:16] [pool-31-thread-2/WARN]: at java.lang.Thread.run(Thread.java:823)
> [10:07:16] [pool-31-thread-2/WARN]: Caused by:
> [10:07:16] [pool-31-thread-2/WARN]: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
> [10:07:16] [pool-31-thread-2/WARN]: at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:380)
> [10:07:16] [pool-31-thread-2/WARN]: at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:285)
> [10:07:16] [pool-31-thread-2/WARN]: at sun.security.validator.Validator.validate(Validator.java:262)
> [10:07:16] [pool-31-thread-2/WARN]: at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)
> [10:07:16] [pool-31-thread-2/WARN]: at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:237)
> [10:07:16] [pool-31-thread-2/WARN]: at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
> [10:07:16] [pool-31-thread-2/WARN]: at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1670)
> [10:07:16] [pool-31-thread-2/WARN]: ... 20 more
> [10:07:16] [pool-31-thread-2/WARN]: Caused by:
> [10:07:16] [pool-31-thread-2/WARN]: java.security.cert.CertPathValidatorException: validity check failed
> [10:07:16] [pool-31-thread-2/WARN]: at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
> [10:07:16] [pool-31-thread-2/WARN]: at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:233)
> [10:07:16] [pool-31-thread-2/WARN]: at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:141)
> [10:07:16] [pool-31-thread-2/WARN]: at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:80)
> [10:07:16] [pool-31-thread-2/WARN]: at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)
> [10:07:16] [pool-31-thread-2/WARN]: at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:375)
> [10:07:16] [pool-31-thread-2/WARN]: ... 26 more
> [10:07:16] [pool-31-thread-2/WARN]: Caused by:
> [10:07:16] [pool-31-thread-2/WARN]: java.security.cert.CertificateExpiredException: NotAfter: Tue Aug 18 09:41:38 UTC 2020
> [10:07:16] [pool-31-thread-2/WARN]: at sun.security.x509.CertificateValidity.valid(CertificateValidity.java:277)
> [10:07:16] [pool-31-thread-2/WARN]: at sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:677)
> [10:07:16] [pool-31-thread-2/WARN]: at sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190)
> [10:07:16] [pool-31-thread-2/WARN]: at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
> [10:07:16] [pool-31-thread-2/WARN]: at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
> [10:07:16] [pool-31-thread-2/WARN]: ... 31 more
> [10:07:16] [pool-31-thread-2/INFO]: [Negativity] Error while updating stats, it seems to be a firewall that blocking the stats.
> [10:07:16] [pool-31-thread-3/WARN]: at sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
> [10:07:16] [pool-31-thread-3/WARN]: at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1967)
> [10:07:16] [pool-31-thread-3/WARN]: at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:331)
> [10:07:16] [pool-31-thread-3/WARN]: at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:325)
> [10:07:16] [pool-31-thread-3/WARN]: at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1688)
> [10:07:16] [pool-31-thread-3/WARN]: at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:226)
> [10:07:16] [pool-31-thread-1/WARN]: at sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
> [10:07:16] [pool-31-thread-1/WARN]: at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1967)
> [10:07:16] [pool-31-thread-1/WARN]: at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:331)
> [10:07:16] [pool-31-thread-1/WARN]: at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:325)
> [10:07:16] [pool-31-thread-1/WARN]: at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1688)
> [10:07:16] [pool-31-thread-1/WARN]: at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:226)
> [10:07:16] [pool-31-thread-1/WARN]: at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1082)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.security.ssl.Handshaker.process_record(Handshaker.java:1010)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1079)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1388)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1416)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1400)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1082)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.ssl.Handshaker.process_record(Handshaker.java:1010)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1079)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1388)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1416)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1400)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)
> [10:07:17] [pool-31-thread-3/WARN]: at com.elikill58.negativity.universal.utils.UniversalUtils.getContentFromURL(UniversalUtils.java:212)
> [10:07:17] [pool-31-thread-3/WARN]: at com.elikill58.negativity.universal.Stats.lambda$0(Stats.java:43)
> [10:07:17] [pool-31-thread-3/WARN]: at com.elikill58.negativity.universal.Stats$$Lambda$3733/000000002C030150.run(Unknown Source)
> [10:07:17] [pool-31-thread-3/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [10:07:17] [pool-31-thread-3/WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [10:07:17] [pool-31-thread-3/WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [10:07:17] [pool-31-thread-1/WARN]: at com.elikill58.negativity.universal.utils.UniversalUtils.getContentFromURL(UniversalUtils.java:217)
> [10:07:17] [pool-31-thread-1/WARN]: at com.elikill58.negativity.universal.utils.UniversalUtils.getContentFromURL(UniversalUtils.java:197)
> [10:07:17] [pool-31-thread-1/WARN]: at com.elikill58.negativity.universal.Stats.lambda$1(Stats.java:70)
> [10:07:17] [pool-31-thread-1/WARN]: at com.elikill58.negativity.universal.Stats$$Lambda$3732/000000002C02A8F0.run(Unknown Source)
> [10:07:17] [pool-31-thread-1/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [10:07:17] [pool-31-thread-1/WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [10:07:17] [pool-31-thread-1/WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [10:07:17] [pool-31-thread-1/WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [10:07:17] [pool-31-thread-1/WARN]: at java.lang.Thread.run(Thread.java:823)
> [10:07:17] [pool-31-thread-1/WARN]: Caused by:
> [10:07:17] [pool-31-thread-1/WARN]: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
> [10:07:17] [pool-31-thread-1/WARN]: at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:380)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:285)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.security.validator.Validator.validate(Validator.java:262)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:237)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1670)
> [10:07:17] [pool-31-thread-1/WARN]: ... 21 more
> [10:07:17] [pool-31-thread-1/WARN]: Caused by:
> [10:07:17] [pool-31-thread-1/WARN]: java.security.cert.CertPathValidatorException: validity check failed
> [10:07:17] [pool-31-thread-1/WARN]: at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:233)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:141)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:80)
> [10:07:17] [pool-31-thread-1/WARN]: at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:375)
> [10:07:17] [pool-31-thread-1/WARN]: ... 27 more
> [10:07:17] [pool-31-thread-1/WARN]: Caused by:
> [10:07:17] [pool-31-thread-1/WARN]: java.security.cert.CertificateExpiredException: NotAfter: Tue Aug 18 09:41:38 UTC 2020
> [10:07:17] [pool-31-thread-1/WARN]: at sun.security.x509.CertificateValidity.valid(CertificateValidity.java:277)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:677)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
> [10:07:17] [pool-31-thread-1/WARN]: at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
> [10:07:17] [pool-31-thread-1/WARN]: ... 32 more
> [10:07:17] [pool-31-thread-1/INFO]: [Negativity] Website is in maintenance mode.
> [10:07:17] [pool-31-thread-3/WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [10:07:17] [pool-31-thread-3/WARN]: at java.lang.Thread.run(Thread.java:823)
> [10:07:17] [pool-31-thread-3/WARN]: Caused by:
> [10:07:17] [pool-31-thread-3/WARN]: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:380)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:285)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.validator.Validator.validate(Validator.java:262)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:237)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1670)
> [10:07:17] [pool-31-thread-3/WARN]: ... 20 more
> [10:07:17] [pool-31-thread-3/WARN]: Caused by:
> [10:07:17] [pool-31-thread-3/WARN]: java.security.cert.CertPathValidatorException: validity check failed
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:233)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:141)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:80)
> [10:07:17] [pool-31-thread-3/WARN]: at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:375)
> [10:07:17] [pool-31-thread-3/WARN]: ... 26 more
> [10:07:17] [pool-31-thread-3/WARN]: Caused by:
> [10:07:17] [pool-31-thread-3/WARN]: java.security.cert.CertificateExpiredException: NotAfter: Tue Aug 18 09:41:38 UTC 2020
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.x509.CertificateValidity.valid(CertificateValidity.java:277)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:677)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
> [10:07:17] [pool-31-thread-3/WARN]: at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
> [10:07:17] [pool-31-thread-3/WARN]: ... 31 more

**Comment by KennyTV** [comment]
Not a Via issue.
