### ISSUE TITLE
bug notification

### ISSUE THREAD

**Issue by oguzhantanitmis** [ViaVersion/ViaVersion#2020]
**Describe the bug, provide any errors**
https://paste.gg/p/anonymous/6dd7f518ef8b46418cc6d2d07e7699bc/files/accfe853639c4626af43cbdad6fe43b2/raw

**ViaVersion Dump**
-  https://dump.viaversion.com/f97a04d7e15a5d9d5a7633c5f3d43167b1a2fa67381cdcc3f3ae0c98082f6f0a

**Additional server info**
I am using bungeecord, but viaversion is installed on spigot servers.

**Comment by KennyTV** [comment]
Update ViaVersion to a CI build.
