### ISSUE TITLE
Wrong Falling Block displayed

### ISSUE THREAD

**Issue by SkytAsul** [ViaVersion/ViaVersion#2022]
**Describe the bug, provide any errors**
When spawning custom Falling Blocks on an 1.15 server with ViaVersion, some blocks change when login with a 1.16 client.
For instance, _smooth_stone_ is displayed as an acacia trapdoor and _iron_block_ as a brick block.

**How can we reproduce it?**
1. Login on 1.16 on a 1.15 server.
2. Use this command: `/summon falling_block ~ ~ ~ {BlockState:{Name:"minecraft:iron_block"},Time:1}`
3. You can see a beautiful brick block being dropped.

**ViaVersion Dump**
- https://dump.viaversion.com/9baa909076a99c723ce9168eb5327a09fe4c871e3df73032f1f54ed2ff759808

**Additional server info**
Using a Waterfall proxy and a Paper server.

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
You forgot the last checkmark. 👀

**Comment by SkytAsul** [comment]
Sorry will try on local
