### ISSUE TITLE
The plug-in that caused the problem: AdvancedFood

### ISSUE THREAD

**Issue by betayanme** [ViaVersion/ViaVersion#2025]
FOOD NAME：elixir_of_life  （This error occurs when you use it）

**Comment by betayanme** [comment]
Internal Exception：io.netty.handler.codec.EncoderException：us.myles.ViaVersion.exception.InfomativeException：Please post this erro to http://github.com/ViaVersion/ViaVersion/issues {Type：FlaVarIntItem，Source #1 us.myles.ViaVersion.api.rewriters.BlockRewriter$5 (Anonymous)，Source #0： us.myles.ViaVersion.api.rewriters.BlockRewriter$5$$Lambda$3520/13051104，Data[Pair{Type丨Integer，32}，Pair{Type丨Boolean，false},
Pair{Type丨Double，375.98365090281817}，Pair{Type丨Double,74.62000000476837}，Pair{Type丨Double，-694.3784450562276},
Pair{Type丨Float，0.3}，Pair{Type丨Float，0.5}，Pair{Type丨Float，0.3},
Pair{Type丨Float，0.1}，Pair{Type丨Integer，5}],Packet ID：36 Actual Error：

**Comment by KennyTV** [comment]
Follow the issue template.
