### ISSUE TITLE
kicks me whenever I open a gui

### ISSUE THREAD

**Issue by CraftYun83** [ViaVersion/ViaVersion#2027]
BRUHH dump: https://dump.viaversion.com/93ee96b909b4fa22a8b264a0599a8cb14d4c558ffaef7653e046bcb363ce202c
![2020-08-21_12 38 23](https://user-images.githubusercontent.com/47018858/90852872-441ebf80-e3ab-11ea-8e25-4dd4fb3b21ea.png)

**Comment by CraftYun83** [comment]
Im pretty sure its whenever I open a gui

**Comment by KennyTV** [comment]
Follow the issue template.

**Comment by CraftYun83** [comment]
where is template?
