### ISSUE TITLE
[1.12.2 -> 1.16.2] /scoreboard players tag then space causes client to get "Disconnected"

### ISSUE THREAD

**Issue by andrew121410** [ViaVersion/ViaVersion#2035]
**Describe the bug, provide any errors**
So the server is on 1.12.2 and when I'm on 1.16.2 haven't tried any others version but when I do /scoreboard players tag THEN space causes the client to get "Disconnected"

"andrew121410 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured."

**How can we reproduce it?**
Sorry, I actually don't know how to reproduce it.

**Expected behaviour**
So after /scoreboard players tag IT should tablist the names of the players.

**Screenshots**
No screenshots but when I get disconnected in the console it says 
"andrew121410 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured."

**ViaVersion Dump**
https://dump.viaversion.com/ea907946027eae899477170a1b0ddcc6c19e6fcfa93f87dc691dcc45fbf37715

**Additional server info**
Not using Bunggecord and the server is on paper 1.12.2 latest.

**Checklist**
- [ ✅] I have included a Viaversion dump
- [ ✅] If applicable, I have included a paste (not a screenshot) of the error
- [ ✅] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Set debug=true in your server properties and send the full error (if you can't already see it in the console).

**Comment by andrew121410** [comment]
When turning on debug in the server.properties I get this error in the console https://sourceb.in/a1114cc88c

**Comment by KennyTV** [comment]
You either have an abnormal amount of scoreboards/scoreboard data, or some plugin is filling the tabcompletion list with junk, but Via shouldn't be the cause here (just 1.13+ clients always "tabcompleting" with every letter they write in a command)
