### ISSUE TITLE
I just got disconnected and it said to report it here

### ISSUE THREAD

**Issue by JackTMR** [ViaVersion/ViaVersion#2036]
**Describe the bug, provide any errors**
It just happened, and disconnected me. It was using the client mod or whatever and said to report it here.

**How can we reproduce it?**
I'm not sure to be honest.

**Expected behaviour**
Not disconnecting? I'm not sure what was really expected other than playing on a server.

**Screenshots**
![image](https://user-images.githubusercontent.com/58351403/91021155-b48d4100-e636-11ea-84c1-bec1192162af.png)

**ViaVersion Dump**
I don't have access since it was the module thing.

**Additional server info**
It was on a client with the ViaVersion mod thing.

**Checklist**
- [ ] I have included a Viaversion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
We need the full error and a dump, otherwise we can't fix it.
