### ISSUE TITLE
Connection issue (possibly related to viaversion after 1.16.2)

### ISSUE THREAD

**Issue by SpEeD11** [ViaVersion/ViaVersion#2037]
This happens randomly about once a day. 

All players will get kicked, CPU usage goes up for about 15-30 minutes during which time users are unable to log back in (no errors during this time and timings are normal so the CPU load isnt caused by things happening in-game).
Then this gets spammed in console thousands of times, CPU usage goes back to normal and users are able to connect again.
https://hastebin.com/ujagavipep.cs

dump: https://dump.viaversion.com/97c5d9f9b46e5d96bb79648bdc6cdd3e766d1ead5f1439fddae314c815f8ce26

**Comment by KennyTV** [comment]
You either have a plugin sending very faulty data, or the errors are an aftereffect of a server attack
