### ISSUE TITLE
[1.16.2 -> 1.8.8] Error when open Recipe Book

### ISSUE THREAD

**Issue by Wirlie** [ViaVersion/ViaVersion#2039]
**Describe the bug, provide any errors**
When I open the recipe book button while using a crafting table, I get disconnected with this error:
https://paste.gg/p/anonymous/a4fa664e09d54760a133a3c396593c4c

**How can we reproduce it?**
1. Make a server using 1.8.8
2. Login in 1.16.2
3. Open a crafting table 
4. Click on the recipe book button and also check that the button "show all" is disabled.
![image](https://user-images.githubusercontent.com/7508197/91215628-63cf2400-e6da-11ea-9e4e-1035cac8bbf1.png)
5. You will be disconnected with the provided error.

**Expected behaviour**
Recipe Book should be able to open without any issues.

**ViaVersion Dump**
- https://dump.viaversion.com/d65a5c207aadd5c0d1e1fa41006a9786b820b9559df0353619740ce3be987876

**Additional server info**
I am using Waterfall as proxy (git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:6496349:370) and PaperMC 1.8.8 (This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8))

Also I provide a paste containing all of my plugins:
https://paste.gg/p/anonymous/e1b84f8ea7c442f88844894fad12b55e

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by daronhudson** [comment]
+1 on this can confirm it happens on 1.16.1 too. It's even worse when the recipe book is open by default cause it causes you to instantly crash or go to a fallback server if you have it configured.
