### ISSUE TITLE
Screaming Bedwars Signs

### ISSUE THREAD

**Issue by AC3SSoccerball** [ViaVersion/ViaVersion#2040]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?

**How can we reproduce it?**
1. Login on 1.8 on a 1.16.1 server
2. Right Click a Screaming Bedwars Sign
3. Wait for the game to start and then right away it says that there was a internal exception

**Expected behaviour**
i thought i was just able to play screaming bedwars normally

**Screenshots**

**ViaVersion Dump**
- https://dump.viaversion.com/0a5dd5676da243e2ddd43e6bf8b117b2a99f620dd17026464502c26c83ca6cf2

**Additional server info**
i use paper 1.16.1 with 2 gigs of ram on a apex hosting server i have over 20+ plugins installed 

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by Blocksnmore** [comment]
That would be an issue with Screaming Bedwars, since it errors when the game starts

**Comment by AC3SSoccerball** [comment]
but when it happens it shows me to post a error here it showed the webstite here

**Comment by Blocksnmore** [comment]
Try updating all the viaver plugins then, only guess

**Comment by AC3SSoccerball** [comment]
they are all updated to the latest

**Comment by Blocksnmore** [comment]
They are not, viaversion is on 3.1.0 when the latest is 3.1.1

**Comment by AC3SSoccerball** [comment]
i am on the spiogt page for Viaversion and i see that the latest version is 3.1.0

**Comment by Blocksnmore** [comment]
As the checklist says, you get the most recent version on ci
ViaVersion - https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/jar/target/ViaVersion-3.1.1-SNAPSHOT.jar
ViaBackwards - https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/lastSuccessfulBuild/artifact/all/target/ViaBackwards-3.1.1-SNAPSHOT.jar
ViaRewind - https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/lastSuccessfulBuild/artifact/all/target/ViaRewind-1.5.1.jar

**Comment by AC3SSoccerball** [comment]
ok i will try that

**Comment by AC3SSoccerball** [comment]
it still dosent work

**Comment by AC3SSoccerball** [comment]
so what do i do then?

**Comment by Blocksnmore** [comment]
Not sure then

**Comment by AC3SSoccerball** [comment]
do i ask screaming bedwars or?

**Comment by FormallyMyles** [comment]
You should post this to viarewind or backwards depending if it happens only on 1.8 or on 1.9. You should also post any errors.
