### ISSUE TITLE
not sure what specifically caused this nor how to reproduce it, 1.15.2 Bungeecord proxy running viaversion 3.1.0, server that I was on at the time was running 1.12.2.

### ISSUE THREAD

**Issue by MHFDoge** [ViaVersion/ViaVersion#2042]
![image](https://user-images.githubusercontent.com/46448580/91492569-83ea1900-e87b-11ea-853b-51ff33481942.png)
[proxy log.txt](https://github.com/ViaVersion/ViaVersion/files/5138709/proxy.log.txt)
Proxy log with more info on the error if needed,

**Comment by KennyTV** [comment]
Follow the issue template.
