### ISSUE TITLE
Bug with quick-move-action-fix for 1.12+ players on 1.8.8 paperspigot/tacospigot servers

### ISSUE THREAD

**Issue by Seanoo1** [ViaVersion/ViaVersion#2044]
**Describe the bug, provide any errors**

**How can we reproduce it?**
1. Run server with 1.8.8 papespigot(or tacospigot)
2. stop server
3. Set quick-move-action-fix=true on viaversion config.yml
4. Run again server
5. just shift-click the item on chest(or enderchest) and this happen.
[https://youtu.be/yImz6CPFRLw](https://youtu.be/yImz6CPFRLw)

**Expected behaviour**
Should move item with no issue

**ViaVersion Dump**
https://dump.viaversion.com/9fc0801a0880e9e001160ff38dfcb29bc099930a4128ded48a9018f0088e13af

**Additional server info**

**Checklist**
- [Yes] I have included a Viaversion dump
- [Yes] If applicable, I have included a paste (not a screenshot) of the error
- [Yes] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
Above should fix, otherwise, if it happens really fast there is likely no solution as we're bound to performing it to the nearest tick.
