### ISSUE TITLE
Big inventory bug (editable only client side)

### ISSUE THREAD

**Issue by assasin541** [ViaVersion/ViaVersion#2045]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?
Very often it happens that no matter what you do with your inventory, it changes client side, but the server sees old inventory. It fixes only by relog. It can happen after some time or right away.

**How can we reproduce it?**
1. Login on 1.13/1.14/1.15/1.16 or other versions
2. [...]
3. Very often it happens that no matter what you do with your inventory, it changes client side, but the server sees old inventory. It fixes only by relog. It can happen after some time or right away.

**Expected behaviour**
Fixed inventory.

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.
newest viaversion, viarewind-all, viarewind-legacy-support and plib.

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
BungeeCord

**Checklist**
- [ ] I have included a Viaversion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Please properly follow the issue template (and elaborate on the description, it's very vague)

**Comment by assasin541** [comment]
@KennyTV what exactly?
Another thing is that you only can use items from the toolbar, you can't even drop other items.

**Comment by assasin541** [comment]
@KennyTV I added viaver dump, don't close this issue, this is very important.

**Comment by KennyTV** [comment]
What does "or other versions" mean? Does what you described just happen randomly when standing around? Do you also run Via on the proxy? Can you try reproducing it without other plugins?

**Comment by assasin541** [comment]
@KennyTV it happened on various version. I just thought about "late-bind" causing this? Yes it happens randomly. I run Via only on bukkit. I don't know how to reproduce, it happens often and randomly.

md_5 about late-bind:
"It may cause issues with ProtocolLib and other plugins, test before using."

**Comment by KennyTV** [comment]
No, late-bind is not the issue

**Comment by assasin541** [comment]
@KennyTV late-bind didn't fix that. I joined the server, the inventory was working, but after some time standing afk, the bug has happened.

**Comment by assasin541** [comment]
@KennyTV something with not opened inventory?

**Comment by assasin541** [comment]
@KennyTV any news?

**Comment by KennyTV** [comment]
As said, please try reproducing this without other plugins on your server and proxy.

**Comment by assasin541** [comment]
@KennyTV it's hard to reproduce it that way.

**Comment by assasin541** [comment]
@KennyTV you can give me version with debug mode or something, I can post results here.

**Comment by KennyTV** [comment]
No, reproduce it without other plugins or just a single one to see if that might be the plugin causing the issue.

**Comment by assasin541** [comment]
@KennyTV what's the issue if this happens randomly? Reproducing it without knowing how to to that and wihout plugins is nearly impossible.

**Comment by DoctorMacc** [comment]
Which implies it's a plugin issue. If you figure out that a certain plugin makes it happen more, then that'll give people context on what may be causing.

**Comment by assasin541** [comment]
@DoctorMacc @KennyTV how can it be plugin issue? It happened again, updating inventory brings items back to their original place, but only for the hotbar. You can't swap items, you can just use items from your toolbar.

**Comment by assasin541** [comment]
@DoctorMacc @KennyTV it still happens.

**Comment by KennyTV** [comment]
Please stop spamming this issue. We told you that you have to reproduce this without other plugins (removing half of them, see if it happens, repeat, else readd) to figure out which one causes it. This is highly unlikely to be Via's fault, we can't give you more than that with the little info you provided. Please only respond to this issue if you have done that.

**Comment by assasin541** [comment]
@KennyTV I don't have any special plugins so what can cause this? Give me version for debug and I will check it. Reproducing it without any plugins is useless, because it happens randomly.

**Comment by DoctorMacc** [comment]
Are you saying it happens without plugins?

**Comment by assasin541** [comment]
@DoctorMacc maybe. I'm saying that it happens randomly. Give me debug version with for example a command. When it will happen I will check if some packets are not processed or something.

**Comment by mygizli04** [comment]
You seem to really want a ‘debug version’. Why not try “/viaversion debug” instead?

**Comment by assasin541** [comment]
@mygizli04 I guess doing it without plugins doesn't make sense. I will try with /viaversion debug.

**Comment by BuzzTheGamer23** [comment]
Doing it without plugins does make since it is most likely a plugin issue.
Try this:
Remove half of your plugins (move it to a different folder), then if it fixes it, it is in the half you removed, or if it didn’t, it is in the half you didn’t remove. Repeat with the half it is in. Do this until you find the plugin causing the issue. Make sure to not remove the Via plugins during this.

**Comment by assasin541** [comment]
@BuzzTheGamer23 ye, but it happens really randomly. I can't spend hours while trying to reproduce this, I can test this on productive servers.

**Comment by BuzzTheGamer23** [comment]
Do you want the issue fixed or not?

**Comment by mygizli04** [comment]
Whatever just don’t come here for support if you need it if you’re just going to not take the support

**Comment by assasin541** [comment]
@BuzzTheGamer23 Sure, I will try /viaver debug when it will happen to me or someone else.
@mygizli04 if you don't want to help don't try wasting your keyboard life to post stupid things here.

**Comment by mygizli04** [comment]
Anyway this is not the right place to have an argument, so i won’t

**Comment by BuzzTheGamer23** [comment]
> mygizli04 if you don't want to help don't try wasting your keyboard life to post stupid things here.
No u

**Comment by KennyTV** [comment]
Last warning; you may open a new issue **if you are able to give us a way of reproducing this** and have done binary search as said in https://github.com/ViaVersion/ViaVersion/issues/2045#issuecomment-691520778. Also, please don't be disrespectful towards other people.
