### ISSUE TITLE
Inventory bug (can't drop/switch/modify items in the inventory)

### ISSUE THREAD

**Issue by assasin541** [ViaVersion/ViaVersion#2046]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?
Very often it happens that no matter what you do with your inventory, it changes client side, but the server sees old inventory. It fixes only by relog. It can happen after some time or right away. You can't change, drop, swtich slots items from the inventory, you can only drop/use items from your toolbar.

**How can we reproduce it?**
1. Login on 1.13/1.14/1.15/1.16 or other versions
2. [...]
3. Very often it happens that no matter what you do with your inventory, it changes client side, but the server sees old inventory. It fixes only by relog. It can happen after some time or right away. You can't change, drop, swtich slots items from the inventory, you can only drop/use items from your toolbar.

**Expected behaviour**
Fixed inventory.

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.
newest viaversion, viarewind-all, viarewind-legacy-support and plib.
https://pastebin.com/raw/GAp8r31j

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
BungeeCord

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Follow up on the old issue please
