### ISSUE TITLE
Error starting with Velocity 1.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by ishland** [ViaVersion/ViaVersion#2047]
**Describe the bug, provide any errors**
The titles says it all. 
Error: https://pastebin.com/Z6eMkuPn

**How can we reproduce it?**
1. Start velocity 1.1.0 with ViaVersion and ViaBackwards
2. See error

**Expected behaviour**
ViaVersion should load properly. 

**Screenshots**
Nope

**ViaVersion Dump**
https://dump.viaversion.com/7df7d0acd0f45d04ef0acc629122b6f2fbc25fe8a4523bef000221d45939f89b

**Additional server info**
I use Velocity and 2 Yatopia server. 
Both of them are 1.16.2. 

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by creeper123123321** [comment]
See #1723
