### ISSUE TITLE
Player name tags not showing on 1.16.X

### ISSUE THREAD

**Issue by FrankSchepers24** [ViaVersion/ViaVersion#2048]
**Describe the bug, provide any errors**
We can't see player's nametags above their heads on any 1.16 version, while if a player joins on 1.15 they can see it.

**How can we reproduce it?**
1. Login on 1.16 on two accounts
2. Look at the other account (or any other player really)
3. No nametags are shown

**Expected behaviour**
See the nametags, like on other versions and servers

**Screenshots**
http://prntscr.com/u865y7
http://prntscr.com/u8663s

**ViaVersion Dump**
https://dump.viaversion.com/d9fb0a01f926c64f38dee841e2d6357dfa6d4b88bc4dd26ba1c10287dd31aff2

**Additional server info**
We use bungee, on multiple servers the nametags are shown, just not in the lobby. Our plugin list: http://prntscr.com/u86els

**Checklist**
- [ X ] I have included a Viaversion dump
- [ X ] If applicable, I have included a paste (not a screenshot) of the error
- [ X ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Only mods can hide player names above heads.

**Comment by tomcraft** [comment]
Pretty sure there was a tag for nametag visibility on previous versions on scoreboard team

**Comment by FrankSchepers24** [comment]
> Only mods can hide player names above heads.

And how do I show them again??

And thanks TomCraft for helping but I never did anytjing with scoreboard ever in my life so I don't know how that couldve happened and how to fix it 😅
