### ISSUE TITLE
Iron Golem Spawner exception loading entity client log spam

### ISSUE THREAD

**Issue by Archy-X** [ViaVersion/ViaVersion#2049]
**Describe the bug, provide any errors**
While on a 1.16 client on a 1.12 server with Viaversion, minecraft client logs are being spammed with Exception loading entity errors and Skipping Entity with id minecraft:zombie_pigman

**How can we reproduce it?**
1. Login on 1.16 on a non 1.16 server
2. Stand near an iron golem spawner, not sure if it affects other spawners but this is the one that triggered the errors for me
3. Look in client logs for error spam

**Expected behaviour**
No errors in logs

**Screenshots**
Vanilla errors: https://pastebin.com/jEwxmduw
Sodium mod errors: https://pastebin.com/gadWQ7uR

**ViaVersion Dump**
https://dump.viaversion.com/6b5925f63cf55735b98252930adfbbb17bdea242db481b0bf8503017380082bf

**Additional server info**
No proxy, plugins shouldn't affect it.

**Checklist**
- [X] I have included a Viaversion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
This is a client bug. Use `/setblock ~ ~ ~ minecraft:spawner{SpawnData:{id:"minecraft:iron_golem"}}` in Vanilla/singleplayer and report it on https://bugs.mojang.com/projects/MC/summary
