### ISSUE TITLE
1.9+ client does not fully load chunks on 1.8.8 paperspigot/tacospigot server

### ISSUE THREAD

**Issue by Seanoo1** [ViaVersion/ViaVersion#2054]
**How can we reproduce it?**
1. Set view-distance to 2 that on server.propertise & spigot.yml
2. Join with 1.8 & 1.9+ and compare the chunk loading
This is 1.8.9 Video : https://www.youtube.com/watch?v=ksxOqqp2YOs&feature=youtu.be
This is 1.12.2 Video : https://www.youtube.com/watch?v=X3vWQkBVFlk&feature=youtu.be

**Expected behaviour**
Should fully load chunks like 1.8.9

**ViaVersion Dump**
https://dump.viaversion.com/f3d3bff36b48d72ff88505ae4c98955d70e60a58a7cf321471b1eea466a7c58d

I also tested with setting view distance with 3, 4 on server.propertise & spigot.yml, but on 1.12.2, it only load 2, 3 like on that video.

**Checklist**
- [Yes] I have included a Viaversion dump
- [Yes] If applicable, I have included a paste (not a screenshot) of the error
- [Yes] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
Your view distance is too low for things to work properly, we can't really support really low view distances because of client behaviours like this.

**Comment by FormallyMyles** [comment]
> @FormallyMyles This issue also happen with default serverside view distance(10). 1.9+ client only load 9 chunks even set render distance to 10 on client side

Can you provide steps to replicate on a clean server with view distance 10?

**Comment by Seanoo1** [comment]
Ok I will test it later if I have time.

**Comment by FormallyMyles** [comment]
cheese
