### ISSUE TITLE
ArmorStand hand and head positions

### ISSUE THREAD

**Issue by TerZer** [ViaVersion/ViaVersion#2055]
**Describe the bug, provide any errors**
1.8 version head and arms positions are a little bit off from the upper versions.

**How can we reproduce it?**
Create a plugin that creates ArmorStand with `DOUBLE_PLANT` as a head item and set head position (I am currently using `new EulerAngle(0, Math.toRadians(315), 0)`) and check if it's in the same position on 1.8 and 1.12 for example.

**Expected behaviour**
I expect for props (ArmorStands with items on head/in hand) to be exactly in the same position in every version

**Screenshots**
https://gyazo.com/58c249bd1d9858b8c80e6cf579f6c3f9

**ViaVersion Dump**
https://dump.viaversion.com/7ba3da9a612f8de502fdcf6a6ba6290fcaff95dbfa790cb2b8fa353968793dd8

**Additional server info**
Everything I am using can be seen in dump.

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by TerZer** [comment]
Some more information. Normal armorstands looks the same on every version. But once armorstand set to `entity.setMarker(true);` or `entity.setSmall(true);` (one of these I am not sure) they look different in other versions.

**Comment by FormallyMyles** [comment]
Marking as a won't fix for this reason:
```
To be precise they changed both the way stuff renders/doesn't render, and euler angles.
To make it worse the angles changed based on the item, so you can't simly just adjust all of them.
Which means that the issue falls under the same category as the vehicle movement control one
```

(Quote from Shev ❤️ )

PRs are welcome but I doubt this is solvable
