### ISSUE TITLE
***Player is getting an error code if he joins BedWars.***

### ISSUE THREAD

**Issue by Hissam1048v** [ViaVersion/ViaVersion#2056]
One of my players is getting an error code, the code is hard to type so I will be giving a screenshot of it. Whenever he joins the BedWars game, he just gets kicked out after a few minutes of seconds. 
The BedWars plugin is ScreamingBedWars.
And I am using an addon called "[Addon] SBAHypixelify for Screaming Bedwars | [1.9 - 1.16.2]".
Other 2-3 players aren't getting this error. If more information is needed, please contact me.
![JgPQeFpTTx_cZTJNGXeooQ](https://user-images.githubusercontent.com/70649701/91999389-2283e780-ed5e-11ea-8243-8cde13413cf4.png)

**Comment by KennyTV** [comment]
Follow the issue template.

**Comment by Hissam1048v** [comment]
Ah I need to see

**Comment by Hissam1048v** [comment]
@KennyTV  Can you please give me a link to the thread that I can use ? 
I am finding it quite difficult to find and I don't know how would people describe it .-.

**Comment by Hissam1048v** [comment]
Can you say how do I do that ?
I am new to github...

**Comment by DoctorMacc** [comment]
Make a new issue and fill out what it says.
