### ISSUE TITLE
Unusual bug.

### ISSUE THREAD

**Issue by Hissam1048v** [ViaVersion/ViaVersion#2057]
**Describe the bug, provide any errors**
The bug is anonymous. Quite rare.
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?
This happened to one of my players for the first time after I upgraded the server to 1.16.2 version. I updated the plugins. This issue happens when the player join the BedWars game. 
THE PASTE FILE: https://paste.gg/p/anonymous/760773abb00f4f85975891e0c74c9428/files/3c8afbe410f44c6693cd591b89a94dae/raw

**How can we reproduce it?**
1. Join a 1.16.2 server.
2. Add BedWars solo with an addon "[Addon] SBAHypixelify for Screaming Bedwars | [1.9 - 1.16.2]". (I am using ScreamingBedWars for the bedwars actual game).
3. Join the BedWars game

**Expected behaviour**
The player should have played normally like others.

**Screenshots**
![JgPQeFpTTx_cZTJNGXeooQ](https://user-images.githubusercontent.com/70649701/92005190-fc157a80-ed64-11ea-8cb5-bb81d1cab7c2.png)

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/483178d7098422fd7dd6cab00cd861fc519f32a649e35bca412ec4b1cc477dbe

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
I don't use BungeeCord. I am running PaperMC 1.16.2. The plugins I use are:

AntiCheatReloaded.jar
BedWars-0.2.12.jar <-- The name is like that in files, actual name is "ScreamingBedWars"
ChatControl-Free-5.8.9.jar
CustomOreGen.jar
EssentialsX-2.18.0.0.jar
GriefPrevention.jar
HolographicDisplays.jar
IridiumSkyblock-2.4.7.jar
LaggRemover-2.0.6.jar
LoginSecurity-3.0.2-Bukkit.jar
LuckPerms-Bukkit-5.1.93.jar
MinigamesLib-1.14.17.jar
Multiverse-Core-4.1.0.jar
Multiverse-Inventories-3.0.0.jar
NoPluginStealers.jar
PerWorldPlugins.jar
ProtocolLib.jar
SBAHypixelify-1.3.5.jar
Spigot-CommandSigns.jar
Vault.jar
ViaBackwards-3.1.0.jar
ViaVersion-3.1.0.jar
VoidGenerator-1.6.1.jar
WildTP.jar
worldedit-bukkit-7.2.0-beta-04.jar
worldguard-bukkit-7.0.4-beta1.jar
worldspawn-1.4.4.jar

**Checklist**
- [Yes] I have included a Viaversion dump
- [Yes] If applicable, I have included a paste (not a screenshot) of the error
- [No, because only original ones are available on Aternos, which is my host] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by FormallyMyles** [comment]
You should report this on the ViaBackwards issue tracker :)

**Comment by BuzzTheGamer23** [comment]
If you can’t put custom plugin jars on your host, I would recommend swapping hosts.
