### ISSUE TITLE
Player loses connection on login

### ISSUE THREAD

**Issue by 27chandler** [ViaVersion/ViaVersion#2058]
**Describe the bug, provide any errors**
A few players have been unable to log into the server. When logging in, the console outputs this message:  https://paste.gg/p/anonymous/88f6e5ba65144f139f2ffe12f8dea2d8

**How can we reproduce it?**
1. Login (I don't know what version they were on as they were unable to join the server and tell me)'

**Expected behaviour**
They log in with no errors and don't lose connection

**Screenshots**

**ViaVersion Dump**
https://dump.viaversion.com/d9709a44bc2e9d84211d502979adfaed93d0473bcaf89b54731911453b0cd02e

**Additional server info**
We use a bungeecord proxy, the server this error occurs on is a paper 1.16.2 server and is the HUB for our network.

**Checklist**
- [Yes] I have included a Viaversion dump
- [Yes] If applicable, I have included a paste (not a screenshot) of the error
- [Yes] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
They are likely using a modified client/something is sending bad data
