### ISSUE TITLE
i have no ideo what is wrong but this plugin simply will not work with other versions but 1.16

### ISSUE THREAD

**Issue by stephenblackbook** [ViaVersion/ViaVersion#2059]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?

**How can we reproduce it?**
1. Login on 1.12'
3. The '....' is displayed wrong

**Expected behaviour**

**Screenshots**

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Checklist**
- [ ] I have included a Viaversion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Follow the issue template. If you need help with setup, you can join our Discord server.
