### ISSUE TITLE
1.16.X Color Bug

### ISSUE THREAD

**Issue by ImperialCrise** [ViaVersion/ViaVersion#2060]
Hello !
You will find attached 2 screenshots of a scoreboard in 1.14.4 and 1.16 on a server using ViaVersion. The code of the scoreboard is the same but the display is not.

En 1.14.4 (Optifine Version):
![1 14 4](https://user-images.githubusercontent.com/16134489/92045231-5243e700-ed80-11ea-9b82-c220e5311fe2.png)

En 1.16.X (here its the 1.16.1 Vanilla version)
![1 16](https://user-images.githubusercontent.com/16134489/92045236-553ed780-ed80-11ea-869c-4d948a9fcb46.png)

**Comment by KennyTV** [comment]
Please follow the issue template.
