### ISSUE TITLE
1.16.X Color bug

### ISSUE THREAD

**Issue by ImperialCrise** [ViaVersion/ViaVersion#2061]
Hello!
It's a graphical bug (so Client side): the color codes §a-f&0-9 are really buggy. You will see below some screenshot of 2 versions of the mc client.

**Steps to reproduce the behavior:**
1. Put the latest build of ViaVersion on the latest Spigot 1.14.4
2. Display a complete scoreboard (i.e. each line must be at least 16 characters long and at least twice colored)
3. With a 1.14.4 client, the colors appear as written in the plugin code. But only in 1.16.X, the colors are "reset".

**ViaVersion Dump:**
https://dump.viaversion.com/39a9d98735e8bc892c8b3e9ec181f54f7a83b569d1699e3f686de5cea5b85547

**Screenshots;**
(in 1.14.4 the scoreboard expected)
![Sans titre](https://user-images.githubusercontent.com/16134489/92046009-45c08e00-ed82-11ea-836e-fc09e5bd4359.png)

(and in 1.16.X THE BAD SCOREBOARD)
![Sans titre](https://user-images.githubusercontent.com/16134489/92045907-f4b09a00-ed81-11ea-93d7-0bd12ebff9e0.png)

**Checklist**
[Yes] I have included a Viaversion dump
[Can't] If applicable, I have included a paste (not a screenshot) of the error
[Yes] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Code Exemple**
On the 4th line, the color of my name (Imperial_Crise) is cut while in the code nothing is stipulated here 
`setLine(4, "§6§l┝━ §c" + getPlayer().getName());`

**Comment by KennyTV** [comment]
You can just put more characters into either prefix or suffix instead of splitting stuff into prefix/suffix, it has been supporting a (practically) unlimited length since 1.13. Doing workaround hacks on our side would basically be wasting processing time
