### ISSUE TITLE
Error code bungeecord

### ISSUE THREAD

**Issue by Cengiouwe** [ViaVersion/ViaVersion#2063]
04.09 07:59:37 [Server] INFO Actual Error: 
04.09 07:59:37 [Server] INFO {Source 0: us.myles.ViaVersion.protocols.base.BaseProtocol$1 (Anonymous)}
04.09 07:59:37 [Server] INFO io.netty.handler.codec.DecoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues

I cant connect to my server

**Comment by FormallyMyles** [comment]
See issue template
