### ISSUE TITLE
Hi,Whenever I try to join VexedMC on Minecraft it pops up with (readcomment)

### ISSUE THREAD

**Issue by JaytheMCgamer** [ViaVersion/ViaVersion#2064]
![WeirdMCglitch](https://user-images.githubusercontent.com/70744994/92210967-09507780-eed3-11ea-895b-f67c3400fda2.JPG)

**Comment by FormallyMyles** [comment]
See issue template, there's no enough info here

**Comment by JaytheMCgamer** [comment]
Where is the issue template?

**Comment by JaytheMCgamer** [comment]
I'm new to this

**Comment by DoctorMacc** [comment]
Make a new issue and don't remove all the existing text.
