### ISSUE TITLE
1.9+ client does not fully load chunks on 1.8.8 paperspigot/tacospigot server

### ISSUE THREAD

**Issue by Seanoo1** [ViaVersion/ViaVersion#2065]
You told me test with 10 chunks, so I tested with it.

How can we reproduce it?

Join with 1.8 & 1.9+ and compare the chunk loading
This is 1.8.9 Video : https://www.youtube.com/watch?v=Y7VA7LQh1Yo
This is 1.12.2 Video : https://www.youtube.com/watch?v=fHfAf4APqtQ

White Gray wool = 8 chunks
Cyan wool = 9 chunks
Purple wool = 10 chunks

You see that it missing 1 chunks on 1.9+ even serverside view-distance is set to 10 on spigot.yml & server.propertise

Expected behaviour
Should fully load chunks like 1.8.9

ViaVersion Dump
https://dump.viaversion.com/f63d332e1b1aa91de90d8aa1d169044ed849c56a0b6a47a6c892fc4e5c60a9ff

Checklist

[Yes] I have included a Viaversion dump
[Yes] If applicable, I have included a paste (not a screenshot) of the error
[Yes] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
Thank you for doing this, it's a great help. We'll look into it further, unsure if it might just be some data we need to send differently or maybe some requirement for rendering the chunks.
