### ISSUE TITLE
can't connect to 1.12.2+

### ISSUE THREAD

**Issue by jisk4icek** [ViaVersion/ViaVersion#2066]
hello, can't connect to version 1.12.2+

**Comment by jisk4icek** [comment]
here https://paste.hostify.cz/?94963de21a51de8d#6HCf1zQs5SKDQJS8HigFevwKpYViUu7ysVtG1G2JHcJg

**Comment by KennyTV** [comment]
Follow the issue template.

**Comment by jisk4icek** [comment]
and where can I find it?
