### ISSUE TITLE
Console Error Spam 

### ISSUE THREAD

**Issue by ethanic17** [ViaVersion/ViaVersion#2067]
Every time a player uses a fishing rod the animation doesn't work and it also displays an error in the console. This happens every time you try to use/click on a fishing rod.  It should default to the regular vanilla animation when using a fishing rod (when the string/rod line goes into the water)

This was tested on both 1.16.1 and 1.16.2.

Console Error:
https://pastebin.com/zGq7DnYi

ViaVersion Dump:
https://dump.viaversion.com/96b001ecec43c52a116502a749a88c46bc274d3c4f4bb804e31eb48843cc87e8

Server Information:
Paper Spigot Build 179 (1.1.6.2)
ViaVersion + ViaBackwards + ViaRewind (All Latest Versions)

Plugins I'm Using:
![image](https://user-images.githubusercontent.com/41976386/92266914-d7b8bb80-ee94-11ea-9439-a2a24b63577b.png)

**Comment by KennyTV** [comment]
Please don't discard the checklist, it exists for a reason. :p

**Comment by ethanic17** [comment]
> Please don't discard the checklist, it exists for a reason. :p

Wait, by using a snapshot version? Since I have ViaVersion, ViaBackwards, and ViaRewind, would the other two plugins still work if I have a snapshot version of ViaVersion?

**Comment by KennyTV** [comment]
Download VV and VB from https://ci.viaversion.com/job/ViaVersion/ and https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/, the ViaRewind version doesn't have to change; that will fix your issue

**Comment by ethanic17** [comment]
> Download VV and VB from https://ci.viaversion.com/job/ViaVersion/ and https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/, the ViaRewind version doesn't have to change; that will fix your issue

Ok, thank you
