### ISSUE TITLE
I can't join with 1.12.2+ (server paper 1.12.2)

### ISSUE THREAD

**Issue by jisk4icek** [ViaVersion/ViaVersion#2068]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/p/anonymous/d1a1730f63f7444abf8b2a8e5078afd3

**How can we reproduce it?**
1. Login on 1.15.2'
3. The '....' is displayed wrong

**Expected behaviour**

**Screenshots**

**ViaVersion Dump**
- Type /viaversion dump, and put the link here https://dump.viaversion.com/20136d27e50e602cbdf52c2766b349cb93a87d4e2264ef853d69698fdd19aa26.  

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
You have something sending bad data/bad chunks, legacy FAWE and SkinsRestorer are good contenders of that.
