### ISSUE TITLE
ERROR 1.16.X KICK ON JOIN SERVER BEFORE RESTART

### ISSUE THREAD

**Issue by alexeses** [ViaVersion/ViaVersion#2069]
Hello!

I've been receiving complaints from some users (most of them play at 1.16.x) indicating that when the eggwars server starts (bungeemode arena) it throws them out and jumps an error from ViaVersion itself, I've tried to solve the error autonomously but it's been impossible.

I have attached the error logs: https://hastebin.com/vadipekaku.md

**How can we reproduce it?
1.- The reports that have arrived to me are from the 1.16.x 
2.- The server is restarted 
3.- Sometimes, when restarting the server if the user logs in he is kicked out.
4.- Skip this fault, if he enters again he will NOT be kicked out.

**Expected behaviour
If the error happens and you kick the player out of the server, I clearly hope that this does NOT happen and that the game continues.

**ViaVersion Dump**
- https://dump.viaversion.com/67cdd3b7f7d2e15c6a687c4d437dd65c2b33cb02a659cc3eb612f956ffbd68b5

**Additional server info
Yes, I use Flamecord, there is no "weird" plugin I use, here is a screenshot: https://prnt.sc/ucfqgh

**Comment by KennyTV** [comment]
Basically a won't-fix for the world blockconnection method; please change it to `packet`
