### ISSUE TITLE
ERROR IN Protocol1_13To1_12_2 IN REMAP OF CHUNK_DATA (0x20)

### ISSUE THREAD

**Issue by detobel36** [ViaVersion/ViaVersion#2070]
**Describe the bug, provide any errors**
Error: https://pastebin.com/hFNbK2yX

**How can we reproduce it?**
Don't know...
Connected in 1.16.2 on a server running in 1.10.2 with bungeecord.

**Expected behaviour**
No deconnection :stuck_out_tongue_closed_eyes: 

**Screenshots**
Just disconnected

**ViaVersion Dump**
https://dump.viaversion.com/af32cfe87a32292dc9b4b3f6140bd8ad3b9ced1a98681cc41d364d8768617faf

**Additional server info**
Using Bungeecord (`git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:e93c762:1532`)
Spigot: `git-Spigot-570526c-75a8885 (MC: 1.10.2)`
Plugin: PermissionsEx, Netherboard + custom plugin (self developped)

**Checklist**
- [v] I have included a Viaversion dump
- [v] If applicable, I have included a paste (not a screenshot) of the error
- [:x:] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
The "world" blockconnection method has concurrency issues, please use the "packet" option.
