### ISSUE TITLE
viaversion debug console spam

### ISSUE THREAD

**Issue by ArisDraws** [ViaVersion/ViaVersion#2071]
**Describe the bug, provide any errors**
When I start up the server, I type /viaver debug and this error spam floods
the console. I'm not sure how long it's been like that, but yesterday it was kicking players
and I think it stopped my GSit plugin from doing player stacking, not sure if they're connected.
Everything seems fine in the game but I think it's an error that I need to fix. Not sure yet

Console Log Paste:
https://paste.gg/p/anonymous/4ae2400ce7ea469c98923b03a0b40737

**How can we reproduce it?**
1. Start up the server'
2. Run /viaver debug'
3. Join the server
4. Console floods with OUTGOING PLAY, INCOMING PLAY, and lots of other stuff

**Expected behaviour**
Expected everything to be normal with no console spam and not kicking players.

**Screenshots**

**ViaVersion Dump**
https://dump.viaversion.com/4bd70e955c20827dadde74dd23c82eeb5c1957e6b09489156cc63417c28b3bc4

**Additional server info**
PaperSpigot 1.15.2
This server is running Paper version git-Paper-387 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Single server, 6 GB RAM
Plugins are included in the ViaVersion dump.

Running the latest version of ViaVersion and ViaBackwards (3.2.0 SNAPSHOT)
1.12 - 1.16

EDIT: forgot to mention that it involved packets a lot? not sure
when players were kicked it said stuff about packets in the kick messages and in the console log (without /viaver debug)
i had to restart the server and it stopped so idk if its gonna do it again or not

**Comment by KennyTV** [comment]
That's the point of the debug command - to give you debug?
