### ISSUE TITLE
viaversion kicking players + console spam

### ISSUE THREAD

**Issue by ArisDraws** [ViaVersion/ViaVersion#2072]
**Describe the bug, provide any errors**
We were playing on the server, then out of nowhere it started kicking players with a long error message.
Console started spamming with a lot of error messages and players can't join.
console log : https://paste.gg/p/anonymous/66fb084b208b4ee7a650fd66cafb1653

**How can we reproduce it?**
not sure how to reproduce it since
it happened out of nowhere
sorry ;-;

**Expected behaviour**

**Screenshots**
https://imgur.com/a/zLhhTZN

**ViaVersion Dump**
https://dump.viaversion.com/d18580204853a802208882d0674ca8d903f994431e74de83d80d2ac8bd486037

**Additional server info**
Single server, 6 GB RAM
ViaVersion 3.2.0 SNAPSHOT + ViaBackwards 3.2.0 SNAPSHOT (1.12 - 1.16)
PaperSpigot #372 (latest as of now)

idk what this error is but it had viaversion in the console spam so aaaaaa

**Comment by KennyTV** [comment]
Something is sending bad chunk data, try reproducing this without other plugins.
