### ISSUE TITLE
Join Error

### ISSUE THREAD

**Issue by Manu5656** [ViaVersion/ViaVersion#2073]
Hi, several players have reported this problem to me when they try to log into the server (If I'm not mistaken whoever had this problem was using version 1.8.x). How can this be solved? I am running ViaVersion, ViaBackwards, ViaRewind on PaperSpigot 1.16.2

Screenshot: https://imgur.com/a/4lYX4pM

**Comment by KennyTV** [comment]
Follow the issue template.

**Comment by Manu5656** [comment]
It says to report the problem here on Github and I did. So how does it work out?

**Comment by DoctorMacc** [comment]
You need to follow the issue template that is present that when you first create an issue report.
