### ISSUE TITLE
Join Problem

### ISSUE THREAD

**Issue by Manu5656** [ViaVersion/ViaVersion#2074]
**Describe the bug, provide any errors**
Several players have reported this problem to me when they try to log into the server (If I'm not mistaken whoever had this problem was using version 1.8.x).

**How can we reproduce it?**
Login with 1.8 in most cases

**Expected behaviour**
-

**Screenshots**
https://imgur.com/a/4lYX4pM

**ViaVersion Dump**
https://dump.viaversion.com/90f9ee24b7675e6ed153c4c017be4583c54fde2442668b77a3ecdf967ab24cc4

**Additional server info**
ViaVersion is installed on the Hub server on PaperSpigot 1.16.2

**Comment by KennyTV** [comment]
This is a ViaRewind issue, open an issue there. Also, we'd need the full console error there, nust just screenshots of the kick
