### ISSUE TITLE
Player Disconnect when running 1.8.9

### ISSUE THREAD

**Issue by Skizzles** [ViaVersion/ViaVersion#2075]
**Describe the bug, provide any errors**
When logging in the user can not join and instead an error is thrown: https://hastebin.com/unuyigasip.shell

**How can we reproduce it?**
1. Login on 1.8.9'
2. See error with user being disconnected

**Expected behaviour**
User should be able to connect properly

**ViaVersion Dump**
https://dump.viaversion.com/f37fac418d72fee0286b3cc989a451aa5e49071b388a3faf8cdb02992d393918

**Additional server info**
BungeeCord, 1.16.2 Paper. Have tried latest dev build and same issue, I also tried reverting back to this version and it has the same issue.

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
ViaRewind 1.5.1 is not compatible with ViaVersion 3.2.0, you have to wait for 1.5.2, or downgrade VV and VB.
