### ISSUE TITLE
1.8 lines of sign update packet are ignored in high version client

### ISSUE THREAD

**Issue by MeowMiaoMiao** [ViaVersion/ViaVersion#2076]
server: spigot1.8.8
viaversion: 3.1.0-latest
test client: 1.16.1

The lines in sign update packet will be ignored
Always empty in high version client

Use this plugin to reproduce: https://www.spigotmc.org/resources/editablesign.2502/

**Comment by KennyTV** [comment]
1.16.1 doesn't support this, it's only possible again with 1.16.2+

**Comment by MeowMiaoMiao** [comment]
> 1.16.1 doesn't support this, it's only possible again with 1.16.2+

Okay.. this is just a bug in 1.16.1.. Forgive my blindness
