### ISSUE TITLE
1.16.2 Login Error 

### ISSUE THREAD

**Issue by BobbyMere** [ViaVersion/ViaVersion#2078]
Login error of op individuals 
https://pastebin.com/U7G4y07Q
paper spigot 1.16.2 
viaversion 3.1.1

Step 1: Be OP
Step 2: Log in
Step 3: Observe error in console

**Expected behaviour**
No error to present itself on login

**ViaVersion Dump**
https://dump.viaversion.com/e64d420d9c73b52f34af3891f4b5063e45f6bfd27ba4fafbfd5d0b7d9e20eced

**Additional server info**
I was told that serverlistplus might be doing it. I removed that plugin and the error persists 
Removing the OP status also removes the error on login. 

**Checklist**
- [ x] I have included a Viaversion dump
- [ x] If applicable, I have included a paste (not a screenshot) of the error
- [x ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by Skizzles** [comment]
Experiencing as well. Same exact issue.

**Comment by KennyTV** [comment]
This is another plugin sending bad packets through ProtocolLib.
