### ISSUE TITLE
Shutting down mapping loader executor!

### ISSUE THREAD

**Issue by Bobcat00** [ViaVersion/ViaVersion#2081]
**Describe the bug, provide any errors**

Running a Spigot 1.16.2 server, the following message appears in the log file at the end of startup:
```
[INFO] [ViaVersion] Shutting down mapping loader executor!
```

**How can we reproduce it?**

Use Spigot 1.16.2 with the following plugin versions:
ViaBackwards-3.2.0-b166
ViaRewind-1.5.2-b61
ViaVersion-3.2.0-b465

Start the server and the message will be output.

**Expected behaviour**

Never saw this message before, so I expect to not see the message. (Although I don't even know what it means.)

**Screenshots**

N/A

**ViaVersion Dump**

https://dump.viaversion.com/7cdfa86a7c8c83e8d6dec702007e991f2b19425fdaecc073002cfcd7c11ddbc3

**Additional server info**

The problem also occurs without ViaBackwards and ViaRewind.
Spigot version git-Spigot-b5a13e6-b8ee6a8 (MC: 1.16.2)

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by DoctorMacc** [comment]
I've seen it too when updating to ViaVersion 3.2.0. I don't think it's anything to worry about - it's just the new block/item/etc mappings loading system, well, shutting down. (And it's labelled INFO). Do you have a concern about the message?

**Comment by Bobcat00** [comment]
I'm also seeing a 1.8.9 client crash when attempting to render an enderman.  I reported that to ViaRewind at https://github.com/ViaVersion/ViaRewind/issues/205
That involves a byte/short cast.  Just reporting this ViaVersion message in case it's related.

**Comment by DoctorMacc** [comment]
My installations do not include ViaRewind. I do not believe they are related.

**Comment by Bobcat00** [comment]
Just covering all the bases in case the mapping loader executor shutdown somehow causes a problem with ViaRewind.  And since I brought it up, I also see a recent ViaVersion commit that involved endermen: https://github.com/ViaVersion/ViaVersion/commit/0070485d2e3873b45623ad4eecb8ff7f3b4ea638

**Comment by Bobcat00** [comment]
The enderman problem is definitely the result of a ViaVersion commit.  Testing with 
ViaBackwards-3.1.1-b148
ViaRewind-1.5.1-b58
ViaVersion-3.1.1-b455
the problem does not occur.

Updating ViaVersion to build 456, and the enderman problem occurs.

There are two commits in built 456: https://github.com/ViaVersion/ViaVersion/commit/0070485d2e3873b45623ad4eecb8ff7f3b4ea638 and https://github.com/ViaVersion/ViaVersion/commit/cae5122d044f36ff3d206f281c3fa859f3710212

I don't know if the fix belongs in ViaVersion or Via Rewind.

**Comment by KennyTV** [comment]
It's nothing to worry about, just a helpful message for us. I believe the VR issue already has an open report on its tracker, otherwise you may open a new issue for that there.
