### ISSUE TITLE
Fire not extinguishable

### ISSUE THREAD

**Issue by Cypphi** [ViaVersion/ViaVersion#2085]
So basically, I have the latest Via Version, Backwards and Rewind. And they run on a 1.16.1 Paper-#138 server. People on versions below 1.16 are not able to extinguish fire. At least, they can't on 1.15.2. I'm pretty sure this has nothing to deal with the outdated paper version since it's the latest 1.16.1 build.

**Comment by KennyTV** [comment]
Follow the issue template.
