### ISSUE TITLE
Error when 1.8 version tries to join

### ISSUE THREAD

**Issue by DarkmcHERO** [ViaVersion/ViaVersion#2086]
Hello,
I have a 1.16.1 papermc server with viaversion + backwards and rewind to allow all versions (1.7+) to connect.
It was working perfect but today I had a couple of people who couldn't connect with 1.8 versions and it gave me an error that said to report it here.

This is a raw paste of the error:
[](https://pastebin.pl/view/b134b8c1)
This is also a screenshot of all plugins I currently have installed:
[](https://i.gyazo.com/1aa3b99a29acde5a544669fc4118c5aa.png)

Thanks in advance for the help!

**Comment by KennyTV** [comment]
Follow the issue template, and report this on the ViaRewind issue tracker.
