### ISSUE TITLE
When ENTITY_METADATA packets are sent, this plugin kick the player.

### ISSUE THREAD

**Issue by LemonCaramel** [ViaVersion/ViaVersion#2087]
First of all, I use a translator. I hope you can understand this bug report. 

**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?

https://paste.gg/p/anonymous/b04274747ef5415c8ca0e23107686b21

**How can we reproduce it?**
I don't know exactly what this is caused by.
First of all, my server operates around LibsDisguises and my game plugin.
My game plugin has the ability to add ENTITY_METADATA(add 0x20[Invisible]) to send packets to the player, an error that occurs only when this feature is enabled.

**Expected behaviour**
I think it's a problem that happens when 0x20 packets are sent when LibsDisguises is activated.

**Screenshots**
I don't have a screenshot.

**ViaVersion Dump**
- https://dump.viaversion.com/ **HIDE**

**Additional server info**
I use the Waterfall fork version.

**Checklist**
- [V] I have included a Viaversion dump
- [V] If applicable, I have included a paste (not a screenshot) of the error
- [V] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
What's the exact code around the feature?

**Comment by LemonCaramel** [comment]
Sorry It was my mistake! 
The packet listener changes from asynchronous to synchronous, and it works fine.
