### ISSUE TITLE
ERROR IN Protocol1_14_4To1_15 IN REMAP OF SPAWN_PARTICLE (0x24)

### ISSUE THREAD

**Issue by TheDoctor025** [ViaVersion/ViaVersion#2089]
Occurs randomly during gameplay on a 1.8 client. Not sure what's causing the error.
https://paste.gg/p/anonymous/5a1247e473ab440f9bdb7642688e3d83

1. Start 1.16.3 server
2. Log in with 1.8.9
3. Player is kicked randomly with this error

Dump:
https://dump.viaversion.com/d2bc164d49e8da818018951941005638772710d30ad69c66341678e77331802b

I do not use Bungee.

**Comment by KennyTV** [comment]
You either swapped the jar while your server was running or have a corrupted file.
