### ISSUE TITLE
I got this issue while doing things on RedditMC server

### ISSUE THREAD

**Issue by SonEfAdam** [ViaVersion/ViaVersion#2090]
![image](https://user-images.githubusercontent.com/65645141/93173847-27716f80-f73e-11ea-92b5-184444b44edb.png)

First I did /register (pass) (pass) and then it showed this error. I went back in, I got registered, then I did /daily to get daily rewards and this error came again.

Thank you!

**Comment by KennyTV** [comment]
Follow the issue template and report this on the ViaRewind issue tracker.

**Comment by SonEfAdam** [comment]
Ok Thank you
