### ISSUE TITLE
Boat too many packets kick

### ISSUE THREAD

**Issue by LucidAPs** [ViaVersion/ViaVersion#2093]
MC 1.16.3
ViaVersion build 468
https://dump.viaversion.com/5c4bb171c08645573587818b7a6e0f27f662c7bcd8544fea3e39c5b202580d67

If you get on a boat it will kick you after a while for too many packets.

**Comment by KennyTV** [comment]
Follow the issue template; otherwise just try setting the limit higher in the ViaVersion config.
