### ISSUE TITLE
Boat too many packets kick

### ISSUE THREAD

**Issue by LucidAPs** [ViaVersion/ViaVersion#2094]
**Describe the bug, provide any errors**
Sit on a boat and it will kick you for packets KennyTV

**How can we reproduce it?**
1. Login on 1.16.3'
2. Ride on a boat
3. Kicked for too many packets KennyTV

**Expected behaviour**
Not getting kicked when riding a boat

**ViaVersion Dump**
https://dump.viaversion.com/5c4bb171c08645573587818b7a6e0f27f662c7bcd8544fea3e39c5b202580d67

**Additional server info**
I am using waterfall , my backend is on Tuinity and plugins https://pastebin.com/raw/F6SzhMsA

**Checklist**
- [yes  KennyTV] I have included a Viaversion dump
- [yes  KennyTV ] If applicable, I have included a paste (not a screenshot) of the error
- [ yes  KennyTV] I have tried a build from https://ci.viaversion.com/ and the issue still persists

Don't close issues for no reason KennyTV

**Comment by FormallyMyles** [comment]
You can modify your config and increase / disable the packet limit.

**Comment by LucidAPs** [comment]
@FormallyMyles So you think there is nothing wrong with people using the default config with the default settings and getting kicked when riding boats? What is wrong with you people?!

**Comment by LucidAPs** [comment]
I know how to solve my problem i am not asking for personal assistance but there clearly a problem here and thats why i am reporting it.

**Comment by FormallyMyles** [comment]
Plugin messages and other server data is included in this count, the generous default packet limits take into account a balance between someone nuking your server and features like these.

If you use plugins which send messages to bungee (sync'ing or w/e) then you need to increase the limit.
