### ISSUE TITLE
1.8 client crash on 1.12.2 server

### ISSUE THREAD

**Issue by Vyzon** [ViaVersion/ViaVersion#2095]
**Describe the bug, provide any errors**
On our 1.12.2 server when older clients join sometimes when they render entities their clients crash (works fine on viaversion/viabackwards 3.10). The only error we have is from the client: https://pastebin.com/yX8zw19M

**How can we reproduce it?**
I'm not entirely sure, but the issue consistently happens on my server and fadecloud now. Its 100% related to rendering entities so I guess try spawning some entities on a 1.12.2 server and running around.

**ViaVersion Dump**
https://dump.viaversion.com/161769ff6e68784275db01d559b845cba40a6f080af619493a14eba7b5868c88

**Additional server info**
The server is running paper 1.12.2 and waterfall. We believe its an issue with ViaVersion/ViaBackwards 3.1.1 as it does not happen on the previous version.

**Comment by FormallyMyles** [comment]
If it happens on just 1.8 it should be on viarewind issue tracker

**Comment by Vyzon** [comment]
As far as I know it happens on all old clients and specifically happens when using ViaVersion/ViaBackward 3.1.1 works normal on 3.10

**Comment by Vyzon** [comment]
> If it happens on just 1.8 it should be on viarewind issue tracker

My bad I thought it was related to viaversion because it doesn't happen on 3.10.
