### ISSUE TITLE
MultiWorld and WorldEdit kicking me

### ISSUE THREAD

**Issue by PerchunPak** [ViaVersion/ViaVersion#2096]
When I tried do lobby in MultiWorld I typed "//set 1" and this start kicking me. I also tried join on server by 1.12,2 OptiFine, but its just do infinity "Joining to server"

**How can we reproduce it?**
1. Login on 1.15.2 or 1.12.2 (for infinity "Joining to server")
2. Click on try to join the server
3. The joining is displayed wrong

**Expected behaviour**
Kicking with error 'https://pastebin.com/8LPiAtFn'

**ViaVersion Dump**
https://dump.viaversion.com/e3b004626989fbf385eea23a7e3a508feb3f77419936715f22112791cb721d8e (joinged from another nick)

**Additional server info**
I use Mohist 1.12.2 build 34, and another you can see at ViaVersion Dump

**Checklist**
- [tick] I have included a Viaversion dump
- [tick] If applicable, I have included a paste (not a screenshot) of the error
- [no tick] I have tried a build from https://ci.viaversion.com/ and the issue still persists

I tried join server on fabric 1.16.3 with viaversion and its give this error
*writing tick*

**Comment by KennyTV** [comment]
You have weirdly changed chunks, and due to the nature of Forge hybrids being rather awful, we can't provide any support for them (or modded servers in general).
