### ISSUE TITLE
Bug found (Viaversion & AST)

### ISSUE THREAD

**Issue by Skogrin** [ViaVersion/ViaVersion#2099]
**Describe the bug, provide any errors**
https://paste.gg/p/anonymous/b8c3a44146134f5fa5b7817c18d249f1/files/75da2f6d884149bfa1064e08fb68da7b/raw

**How can we reproduce it?**
1. Login on 1.8.8'
2. Download ViaVersion & AST
3. Make /ast and spawn armor stand and you crash

**ViaVersion Dump**
- https://dump.viaversion.com/7c8081132a0fd13ca64ca67578395fa82918acd8bff2a52bc07d51f3af7378c8

**Additional server info**
Do you use a proxy (eg. BungeeCord)?
  - No
What software do you use and what plugins ?
  - Spigot 1.8.8, and Build plugin (BuildSystem, HeadsDatabase, etc..)

**Checklist**
- 

- [x] I have included a Viaversion dump

- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Please try reproducing this with only ArmorStandTools and no other plugins.
