### ISSUE TITLE
Can I reprint all your plugins, I will attach your github URL

### ISSUE THREAD

**Issue by xiaowine** [ViaVersion/ViaVersion#2100]
Can I reprint all your plugins, I will attach your github URL

**Comment by KennyTV** [comment]
If you mean desitributing the jar; if people want to download them, they can find them on Spigot and GitHub themselves.

**Comment by xiaowine** [comment]
> s

If you don’t use vpn, access to Spigot and GitHub will be slow, and many people don’t know

**Comment by toxamin** [comment]
viaversion is licensed under mit, you can modify, share, sell, reprint, without explicit permission, nor can they prevent you from doing this.

**Comment by xiaowine** [comment]
> viaversion is licensed under mit, you can modify, share, sell, reprint, without explicit permission, nor can they prevent you from doing this.

ok,thanks
