### ISSUE TITLE
Immediately kicked upon joining Minehut Server (1.16.2, 1.16.3)

### ISSUE THREAD

**Issue by NEmath09** [ViaVersion/ViaVersion#2104]
Error report:

us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues {Type: FlatVarIntItem, Data: [Pair{Type|Interger, 34}, Pair{Type|Boolean, false}, Pair{Type|Double, -104.5}, Pair{Type|Double, 197.5}, Pair{Type|Double, 226.5}, Pair{Type|Float, 0.0, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.1}, Pair{Type|Integer, 250}], Source 0: us.myles.ViaVersion.api.rewriters.BlockRewriter$6$$Lambda#134/266554246, Packet ID: 34, Source 1: us.myles.ViaVersion.api.rewriters.BlockRewriter$6 (Anonymous)}
Actual Errror:  @ io.netty.handler.codec.MessageToMessageEncoder:104

End of error report

Server I was trying to join: kitpvp39.minehut.gg I tried using 1.16.1, 1.16.2, and 1.16.3. With 1.16.1, it gave me a Java error (see below)

The Java error consists of:

Internal Exception: io.netty.handler.codeec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(51) + length(1) exceeds writerIndex(51): PooledUnsafeDirectByteBuf(ridex: 51, widx: 51, cap: 51)

End of Java error report

On 1.16.2 and 3, the error on the very top of the page is shown, and for all of the version, I get kicked 1 tick (1/20th of a second) after joining.

**Comment by KennyTV** [comment]
We can't fix this without the full error and a dump.
