### ISSUE TITLE
io.netty.handler.codec.DecoderException error in Servr log

### ISSUE THREAD

**Issue by Syping** [ViaVersion/ViaVersion#2105]
**Describe the bug, provide any errors**
https://paste.gg/p/anonymous/45c13b8f30c042eb923b73e82438b993
Can't say how it came up, it appeared when friends played on my Server and they can't tell me what they did when it happen.

**How can we reproduce it?**
Use 1.16.2 to play on 1.16.3 Paper Server, sadly i can't tell much about it but i still hope i can help in anyway.

**Expected behaviour**
A clear log

**Screenshots**
none

**ViaVersion Dump**
https://dump.viaversion.com/53e2f6eab72b288e6e39303565919187a36c2bb2c92fa9437cf1caeb06a8fb91

**Additional server info**
Plugins used are: dynmap, floodgate-bukkit, Geyser-Spigot, sleep-most, [Spawner](https://gitlab.com/rwr/spawner/), ViaBackwards, ViaVersion, WorldEdit, WorldGuard

**Checklist**
- [+] I have included a Viaversion dump
- [+] If applicable, I have included a paste (not a screenshot) of the error
- [+] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Someone is sending bad ping packets.
