### ISSUE TITLE
Players immediately get kicked upon login

### ISSUE THREAD

**Issue by ConstructorLeo** [ViaVersion/ViaVersion#2106]
**Describe the bug, provide any errors**
Sometimes when a player joins the server they immediately get kicked with a ViaVersion error showing up in console. Link to error: https://paste.gg/p/anonymous/20e86d0bdf0742e3bf66a2384823592c

A couple days ago we tried updating to the latest build from https://ci.viaversion.com/ (3.2.0) to see if it fixed it, but the error still occured. We've since gone back to version 3.1.1.

My alt account always gets kicked however my main does not. Our server logs show that some players login just fine whereas others get kicked immediately.

**How can we reproduce it?**

1. Login to any version from 1.15.2 to 1.16.3
2. Join a 1.15.2 Tuinity server

**Expected behaviour**
Players to not sometimes be kicked upon joining the servers.

**ViaVersion Dump**
https://dump.viaversion.com/b9dcac53dd29ca6d03b6a60cdceb2460b7e36cbbebe78fb1f2e10622bc963d5c

**Additional server info**
Our Spigot servers run Tuinity 1.15.2, ViaVersion is uploaded to these servers but not our proxy servers, running Waterfall.

**Comment by KennyTV** [comment]
Not a Via issue - either a plugin is sending custom packets, or it's a server concurrency issue (most likely a plugin doing black magic tho).
