### ISSUE TITLE
1.12 -> 1.13 Remapping error

### ISSUE THREAD

**Issue by JohnS19** [ViaVersion/ViaVersion#2108]
**Describe the bug, provide any errors**
Not sure what the actual implications are for this error but I get this spammed in console:
https://paste.gg/p/anonymous/fdad8d8bcba8455f8a4e3f9adfd46c38

**How can we reproduce it?**
1. Login on 1.12
2. Possibly go to a specific location? Not entirely sure..

**Expected behaviour**
No errors

**ViaVersion Dump**
https://paste.gg/p/anonymous/79b93150bdb24eefbdcee9ce68d72c5f

**Additional server info**
Tuinity 1.16.3, Waterfall

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Update ViaVersion.
