### ISSUE TITLE
Ability to send a custom block type to newer versions?

### ISSUE THREAD

**Issue by embeddedt** [ViaVersion/ViaVersion#2109]
**Is your feature request related to a problem? Please describe.**

I'm trying to implement a feature similar to Hypixel's colored beds in BedWars. In their game, 1.12+ clients can see a team bed as though it were a colored bed, even though the 1.8 server has no knowledge of colored beds.

**Describe the solution you'd like**

I'd like an API (or workaround) which allows a plugin to choose which block is sent to newer clients.

**Describe alternatives you've considered**

I have looked for documentation on how to do this and couldn't find any. My apologies if I missed it.

**Comment by KennyTV** [comment]
Sorry, but this is basically impossible with Via / any open protocol translator. You would need to spend the time to do your own solution for that.
