### ISSUE TITLE
Kick when Joining server

### ISSUE THREAD

**Issue by Skizzles** [ViaVersion/ViaVersion#2110]
**Describe the bug, provide any errors**
I have a player that joins the server and gets instant kicked, upon further investigation its due to entering the nether and causes a server kick every time on rejoin.

https://hatebin.com/kkjjtysjtn

**How can we reproduce it?**
Use a 1.12 server jar with latest version, attempt to join and receive kicks, attempt to go through the nether and have the server kick again.

**Expected behaviour**
Non server kicks

**Screenshots**
https://screenshots.skizzles.me/JIWA4/sIXowOqO38.png

**ViaVersion Dump**
https://dump.viaversion.com/414eade02771175ba5e0cad3aa2448ebd07f65ede90220d9d2c9cbed3ceeb148

**Additional server info**
Waterfall:
https://screenshots.skizzles.me/JIWA4/PODUlivU13.png

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
You're outdated.
