### ISSUE TITLE
Error Jurassik_09 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues {Type: FlatVarIntItem Array, Data: [Pair{Type|VarInt, 524}, Pair{Type|String, minecraft:piston}, Pair{Type|String, crafting_shaped}, Pair{Type|VarInt, 3}, Pair{Type|VarInt, 3}, Pair{Type|String, }, Pair{Type|FlatVarIntItem Array, [Lus.myles.ViaVersion.api.minecraft.item.Item;@586ecf80}], Source 0: us.myles.ViaVersion.protocols.protocol1_13_1to1_13.packets.InventoryPackets$2$$Lambda$1882/548778305, Packet ID: 84, Source 1: us.myles.ViaVersion.protocols.protocol1_13_1to1_13.packets.InventoryPackets$2 (Anonymous)} Actual Error:

### ISSUE THREAD

**Issue by YoYura** [ViaVersion/ViaVersion#2112]
Hello! I have a problem with viaversion 3.1.1 (English - not my main language, i can make mistakes.)
My server is:
Spigot 1.13
My plugins:
https://user-images.githubusercontent.com/72012379/94413785-3ca9bd80-0184-11eb-92de-21028f264a0c.png
https://user-images.githubusercontent.com/72012379/94413786-3d425400-0184-11eb-90c8-2fe62c76e471.png
https://user-images.githubusercontent.com/72012379/94413787-3d425400-0184-11eb-8488-5c8d467770c8.png
When I try to connect from minecraft 1.13.2 while i connect it give me a error.
https://user-images.githubusercontent.com/72012379/94414254-cbb6d580-0184-11eb-9c35-5e3ab86096bf.png.
Who know how i can solve this problem? (Thanks for answer)

**Comment by FormallyMyles** [comment]
Complete the issue template (when you create an issue)
