### ISSUE TITLE
can't join using aegis bungeecord fork on minecraft 1.16.1

### ISSUE THREAD

**Issue by Areanydd** [ViaVersion/ViaVersion#2114]
I can t use viaversion with aegis..this is the error:
13:08:35 [WARNING] [ViaVersion] ViaVersion does not have any compatible versions for this server version!
13:08:35 [WARNING] [ViaVersion] Please remember that ViaVersion only adds support for versions newer than the server version.
13:08:35 [WARNING] [ViaVersion] If you need support for older versions you may need to use one or more ViaVersion addons too.
13:08:35 [WARNING] [ViaVersion] In that case please read the ViaVersion resource page carefully or use https://jo0001.github.io/ViaSetup
13:08:35 [WARNING] [ViaVersion] and if you're still unsure, feel free to join our Discord-Server for further assistance.

**Comment by KennyTV** [comment]
Aegis is not supported, use Waterfall (or plain Bungee) or move Via to your backend servers.
