### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by AcesGamingUK** [ViaVersion/ViaVersion#2115]
**Describe the bug, provide any errors**
plugin causing instability with [RWG](https://www.spigotmc.org/resources/1-8-1-16-3-realisticworldgenerator.15905/)

**How can we reproduce it?**
Steps to reproduce the behaviour:
1. join server,
2. run /RWG regenerate
3. server takes a dump
https://pastebin.com/RbJGyHD5

**Expected behaviour**

**Screenshots**

**ViaVersion Dump**
- [dump](https://dump.viaversion.com/ba09a679ca1de1a8b4b7cbb4dfc42dfdbfb4bd6ebd9996247fb0226e52e78683)

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Checklist**
- [ ] I have included a Viaversion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
This has nothing to do with Via

**Comment by Xernium** [comment]
Also I may add- 
1: Running ViaVersion together with ProtocolSupport is only possible on a **Papermc** server.
2: You can't run ProtocolSupport and ViaBackwards/ViaRewind together as those replace each other.

Either remove ProtocolSupport and keep ViaBackwards/ViaRewind    

or    

change to a Papermc Server, keep ProtocolSupport and remove ViaBackwards/ViaRewind

**Comment by AcesGamingUK** [comment]
May I add that I do use paper,
I swapped to spigot to see if the issue was present there as per rwg
request,

**Comment by AcesGamingUK** [comment]
> This has nothing to do with Via

https://pastebin.com/05m9pgsB
are you sure?

**Comment by KennyTV** [comment]
As Five said, Via is not compatible with ProtocolSupport on Spigot, you have to run Spigot for that.

**Comment by Xernium** [comment]
This error happens when either ViaVersion is run with ProtocolSupport on a non papermc server or ViaBackwards/ViaRewind is combined with ProtocolSupport.   
The rest is not related to Via*.
I already mentioned the two ways you can fix in my previous message.
