### ISSUE TITLE
I have strange error please help i don't know how to fix it

### ISSUE THREAD

**Issue by Tr0janH0rs3** [ViaVersion/ViaVersion#2116]
> 16:27:00 [WARNING] [ViaVersion] ERROR IN Protocol1_16To1_15_2 IN REMAP OF CHUNK_DATA (0x22)
> 16:27:00 [WARNING] [Aegis] [elito_love33,/therewasaniphere:50480] <-> InitialHandler - Exception caught! us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Source 0: us.myles.ViaVersion.protocols.protocol1_16to1_15_2.packets.WorldPackets$2 (Anonymous)}
Actual Error: (To see details enable print-stacktraces)

**Comment by KennyTV** [comment]
Please follow the issue template, we also need a full error.
