### ISSUE TITLE
Issue on 1.8 server when 1.16.1 player tryies to spawn a wither

### ISSUE THREAD

**Issue by dino147** [ViaVersion/ViaVersion#2117]
**Describe the bug, provide any errors**
I've logged in with 1.16.1 on a 1.8.8 server with viaversion 3.1.1 from spigot and then spawned a wither (I've used /spawnmob command from essentials), this instantly kicked me and I can't join the server anymore.

Error link: [https://pastebin.com/wHsAmGa2](https://pastebin.com/wHsAmGa2)

**How can we reproduce it?**
1. Login on 1.16.1'
2. Spawn a wither
3. Get instantly kicked and being unable to join the server.

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.
[https://dump.viaversion.com/1264391cef64c436704fcc1b90bef18a6124a31112f954d2e13de2692eab4898](https://dump.viaversion.com/1264391cef64c436704fcc1b90bef18a6124a31112f954d2e13de2692eab4898)

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
I use Aegis bungeecord.

**Comment by FormallyMyles** [comment]
Can you provide the console error? / The error that happens?

**Comment by dino147** [comment]
Error link: [https://pastebin.com/wHsAmGa2](https://pastebin.com/wHsAmGa2)

**Comment by KennyTV** [comment]
Cannot reproduce; please try the same on a standard Paper and Bungee/Waterfall and without other plugins.
