### ISSUE TITLE
Spamming error while joining viaversion

### ISSUE THREAD

**Issue by GrimEpp** [ViaVersion/ViaVersion#2118]
When i join my 1.16.3 server with viaversion it just spams with errors

**How can we reproduce it?**
1. get a paper 1.16.3 server and log on with 1.16.3

Console will be spammed with errors

**Screenshots**
https://gyazo.com/a16c7fcd15a5cb9ed9bf7d7f4e190267

**ViaVersion Dump**
https://dump.viaversion.com/85b30f5b32cd6e651d5035e688fe2224b3b9cb0415c8b95d8a2afb2320f9ae09

**Additional server info**
Bungeecord normal

**Comment by GrimEpp** [comment]
Sorry a server issue found out

**Comment by KennyTV** [comment]
Not Via related, some other plugin is sending bad chat packets through ProtocolLib.
