### ISSUE TITLE
1.8 cannot use command blocks.

### ISSUE THREAD

**Issue by karmette** [ViaVersion/ViaVersion#2121]
**Describe the bug, provide any errors**
I use a 1.8.9 client on a Paper 1.16.3 server. As of 1.13, command blocks got a rewrite, so it is completely different from 1.7-1.12 command blocks. When I tried to input a command into a command block(1.8.9 client), the command would just disappear(Yes, I pressed Done). When tried in 1.16.3, the command would stay.

**How can we reproduce it?**
1. Login on 1.7.X-1.12.X With ViaRewind(and viaversion and viabackwards)
2. Produce a cmd block
3. When typing in a command, and pressing done, the command would disappear and not input.

**Expected behavior**
What is expected is that the command would input, and display a text saying "Command set to /give @p Minecraft:diamond"
I'm sure protocol support fixed this bug, but I will stick with viaversion since protocol support is laggy :)

**Screenshots**
![image](https://user-images.githubusercontent.com/48113149/95592605-bac85880-09fd-11eb-970d-def2608635d3.png)
typed a command in and pressed done
![image](https://user-images.githubusercontent.com/48113149/95592660-cf0c5580-09fd-11eb-82b5-ce25fd0687ca.png)
nothing explaining that the command was set to '/give @p Minecraft:diamond'
![image](https://user-images.githubusercontent.com/48113149/95592742-eb0ff700-09fd-11eb-8e15-1f07674790b5.png)
command block has been set to the previous command, which was set in 1.16.3

**ViaVersion Dump**
https://dump.viaversion.com/af0168011e5fe0c19a92ad769f4851695d55cdbc626c0c50fa1af4d0adbc4594

**Additional server info**
Using Paper 1.16.3 stable. Currently using about 14 plugins, as followed:
![image](https://user-images.githubusercontent.com/48113149/95592823-04b13e80-09fe-11eb-9360-67c981a6be21.png)
This was also tried in Spigot but also failed. Even without any plugins besides the Viaversion mods, the command blocks still wouldn't work.
Would be great if this was solved, command blocks are the life of what I want to do in my server right now.

**Checklist**
- [x] I have included a Viaversion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
Please report this on ViaRewind if it doesn't happen on 1.9 client otherwise ViaBackwards :)
