### ISSUE TITLE
[ViaVersion] ERROR IN Protocol1_13_2To1_14 IN REMAP OF ENTITY_EQUIPMENT (0x46)

### ISSUE THREAD

**Issue by KlenerTeufel96** [ViaVersion/ViaVersion#2122]
Some players lost connection to server and a big error occurs.

**How can we reproduce it?**
Login with latest Labymod on a 1.15.2 Server that handles versions with ViaVersion and ViaBackwards.
But this dont happen to all players!

**Screenshots**
Pastebin from error:
https://pastebin.com/7VLaLBKc

**ViaVersion Dump**
https://dump.viaversion.com/e09389bf76357d097c61812555d6e7665c4ba9e82e86dab36460eaaf3cd04ef2

**Additional server info**
- Proxy: Bungeecord
- Server Version: Paper-387 | MC 1.15.2 | Implemented API: 1.15.2-R0.1-SNAPSHOT
- Viaversion Version: 3.2.0-SNAPSHOT
- ViaBackwards Version: 3.2.0-SNAPSHOT

**Comment by FormallyMyles** [comment]
Test latest from ci.viaversion.com otherwise report on ViaBackwards
