### ISSUE TITLE
Random chunks of blocks spawn for some clients

### ISSUE THREAD

**Issue by UltraBlackLinux** [ViaVersion/ViaVersion#2123]
**Describe the bug, provide any errors**
Viaversion seems to spawn random chunks of blocks for some clients (mc ~1.9-1.12.2) whilst players/server places blocks  

**How can we reproduce it?**
1. Login on 1.12'
2. Join Blocksumo on bedwarspractice.club
3. Watch giant clientside chunks of fire/wool/... spawn

**Expected behaviour**
Nothing

**Screenshots**
![Screenshot_20201010_161517](https://user-images.githubusercontent.com/62404294/95657268-da51a500-0b13-11eb-963c-c4668aa4e42a.png)

**ViaVersion Dump**
https://dump.viaversion.com/dadbfebcc50c8435818500654ff463cc0ea5eb26f7ae4ae965ae9fe6b475f015

**Additional server info**
BungeeCord 1.16
Mc 1.8 Spigot

**Checklist**
- [x] I have included a Viaversion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by krusic22** [comment]
Since you didn't provide screenshots, they setting "blockconnection-method" to "world".

**Comment by UltraBlackLinux** [comment]
@krusic22 wdym *cough*

**Comment by FormallyMyles** [comment]
Does this still happen on ViaVersion 4.0.0 (as we removed the bulk chunk handler)? At the time did you try changing between world & packet?

**Comment by UltraBlackLinux** [comment]
> Does this still happen on ViaVersion 4.0.0 (as we removed the bulk chunk handler)? At the time did you try changing between world & packet?

Unfortunately I cannot reproduce this anymore, as version 1.12 got disabled after I notified the owner about this.

Will have to close this I guess.
