### ISSUE TITLE
Weird error told me to post here.

### ISSUE THREAD

**Issue by TheCyberShocker** [ViaVersion/ViaVersion#2127]
>.... [15:57:45 WARN]: io.netty.handler.codec.DecoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
>.... [15:57:45 WARN]: {Type: VarInt, Data: [], Source 0: us.myles.ViaVersion.protocols.base.BaseProtocol$1$$Lambda$3652/1463266620, Packet ID: 0, Source 1: us.myles.ViaVersion.protocols.base.BaseProtocol$1 (Anonymous)}
>.... [15:57:45 WARN]: Actual Error:
>.... [15:57:45 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
>.... [15:57:45 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:263)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
>.... [15:57:45 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
>.... [15:57:45 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
>.... [15:57:45 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at net.minecraft.server.v1_16_R2.LegacyPingHandler.channelRead(LegacyPingHandler.java:120)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:147)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
>.... [15:57:45 WARN]: at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
>.... [15:57:45 WARN]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
>.... [15:57:45 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
>.... [15:57:45 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
>.... [15:57:45 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [15:57:45 WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
>.... [15:57:45 WARN]: {Type: VarInt, Data: [], Source 0: us.myles.ViaVersion.protocols.base.BaseProtocol$1$$Lambda$3652/1463266620, Packet ID: 0, Source 1: us.myles.ViaVersion.protocols.base.BaseProtocol$1 (Anonymous)}
>.... [15:57:45 WARN]: Actual Error:
>.... [15:57:45 WARN]: Caused by: java.lang.RuntimeException: VarInt too big
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.type.types.VarIntType.readPrimitive(VarIntType.java:23)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.type.types.VarIntType.read(VarIntType.java:51)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.type.types.VarIntType.read(VarIntType.java:7)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:143)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.PacketWrapper.passthrough(PacketWrapper.java:193)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.protocols.base.BaseProtocol$1.lambda$registerMap$0(BaseProtocol.java:30)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:418)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.protocols.base.BaseProtocol.transform(BaseProtocol.java:89)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:431)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:81)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:328)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.data.UserConnection.transformIncoming(UserConnection.java:319)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:38)
>.... [15:57:45 WARN]: at sun.reflect.GeneratedMethodAccessor198.invoke(Unknown Source)
>.... [15:57:45 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [15:57:45 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [15:57:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:518)
>.... [15:57:45 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
>.... [15:57:45 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
>.... [15:57:45 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:263)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
>.... [15:57:45 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
>.... [15:57:45 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
>.... [15:57:45 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at net.minecraft.server.v1_16_R2.LegacyPingHandler.channelRead(LegacyPingHandler.java:120)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:147)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
>.... [15:57:45 WARN]: at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
>.... [15:57:45 WARN]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
>.... [15:57:45 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
>.... [15:57:45 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
>.... [15:57:45 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [15:57:45 WARN]: io.netty.handler.codec.DecoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
>.... [15:57:45 WARN]: {Type: String, Data: [Pair{Type|VarInt, 9}], Source 0: us.myles.ViaVersion.protocols.base.BaseProtocol$1$$Lambda$3652/1463266620, Packet ID: 0, Source 1: us.myles.ViaVersion.protocols.base.BaseProtocol$1 (Anonymous)}
>.... [15:57:45 WARN]: Actual Error:
>.... [15:57:45 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
>.... [15:57:45 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:263)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
>.... [15:57:45 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at net.minecraft.server.v1_16_R2.LegacyPingHandler.channelRead(LegacyPingHandler.java:120)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:147)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
>.... [15:57:45 WARN]: at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
>.... [15:57:45 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
>.... [15:57:45 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
>.... [15:57:45 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [15:57:45 WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
>.... [15:57:45 WARN]: {Type: String, Data: [Pair{Type|VarInt, 9}], Source 0: us.myles.ViaVersion.protocols.base.BaseProtocol$1$$Lambda$3652/1463266620, Packet ID: 0, Source 1: us.myles.ViaVersion.protocols.base.BaseProtocol$1 (Anonymous)}
>.... [15:57:45 WARN]: Actual Error:
>.... [15:57:45 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(99) exceeds writerIndex(11): PooledUnsafeDirectByteBuf(ridx: 3, widx: 11, cap: 256)
>.... [15:57:45 WARN]: at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405)
>.... [15:57:45 WARN]: at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1392)
>.... [15:57:45 WARN]: at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:946)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:32)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:9)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:143)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.PacketWrapper.passthrough(PacketWrapper.java:193)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.protocols.base.BaseProtocol$1.lambda$registerMap$0(BaseProtocol.java:31)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:418)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.protocols.base.BaseProtocol.transform(BaseProtocol.java:89)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:431)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:81)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:328)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.api.data.UserConnection.transformIncoming(UserConnection.java:319)
>.... [15:57:45 WARN]: at us.myles.ViaVersion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:38)
>.... [15:57:45 WARN]: at sun.reflect.GeneratedMethodAccessor198.invoke(Unknown Source)
>.... [15:57:45 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [15:57:45 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [15:57:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:518)
>.... [15:57:45 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
>.... [15:57:45 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
>.... [15:57:45 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:263)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
>.... [15:57:45 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at net.minecraft.server.v1_16_R2.LegacyPingHandler.channelRead(LegacyPingHandler.java:120)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:147)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>.... [15:57:45 WARN]: at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>.... [15:57:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>.... [15:57:45 WARN]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
>.... [15:57:45 WARN]: at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
>.... [15:57:45 WARN]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
>.... [15:57:45 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
>.... [15:57:45 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
>.... [15:57:45 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by KennyTV** [comment]
Follow the issue template.
