### ISSUE TITLE
Unable to connect to 1.13 server on 1.16.3

### ISSUE THREAD

**Issue by PixelMinecraft** [ViaVersion/ViaVersion#2128]
Here's the '/viaversion dump' URL :)
> https://dump.viaversion.com/acf565ae143b2573b79490fccce9ba5098d8233112f66d96ca6924b43a46de8b

I joined my server on 1.16.3 whilst the server is on 1.13.
The following error was posted:

> PixelSpookcraft lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
--
647 | {Type: FlatVarIntItem Array, Data: [Pair{Type\|VarInt, 524}, Pair{Type\|String, minecraft:piston}, Pair{Type\|String, crafting_shaped}, Pair{Type\|VarInt, 3}, Pair{Type\|VarInt, 3}, Pair{Type\|String, }, Pair{Type\|FlatVarIntItem Array, [Lus.myles.ViaVersion.api.minecraft.item.Item;@55d15b52}], Source 0: us.myles.ViaVersion.protocols.protocol1_13_1to1_13.packets.InventoryPackets$2$$Lambda$1464/861880873, Packet ID: 84, Source 1: us.myles.ViaVersion.protocols.protocol1_13_1to1_13.packets.InventoryPackets$2 (Anonymous)}

**Comment by FormallyMyles** [comment]
Please complete the rest of the issue template, and ensure you've tried latest from ci.viaversion.com
