### ISSUE TITLE
Error on connecting to sub-server, from sub-server

### ISSUE THREAD

**Issue by MackenzieMolloy** [ViaVersion/ViaVersion#2130]
**Describe the bug, provide any errors**
https://paste.gg/p/anonymous/fccff11a9f8c4f6d91b7bd4ce40b1fc2

**How can we reproduce it?**
1. Login on 1.15', connecting to 1.8 lobby sub-server
2. Connect to 1.16.3 sub-server

**Expected behaviour**
No errors?

**Screenshots**
Error

**ViaVersion Dump**
https://dump.viaversion.com/e6edcebae847d8f1d8c94a1f6375a3e4f741dcfc289c7335978eb3b902162529

**Additional server info**
Waterfall Proxy, StellarSpigot lobby and Trinity 1.16.3 sub-server

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Try reproducing it on a standard Paper/Waterfall, we don't support closed mcm forks, also try without other plugins. If you can still reproduce it after that, we will reopen the issue.
