### ISSUE TITLE
Error in particle spawn

### ISSUE THREAD

**Issue by Xayanix** [ViaVersion/ViaVersion#2131]
**Describe the bug, provide any errors**
Error in console + player's kicked from server.
https://hastebin.com/cawadixaqo.csharp

**How can we reproduce it?**
1. Login on 1.12'
3. The '....' is displayed wrong

**Expected behaviour**

**Screenshots**

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/1e0efd69ecc18d1e953e808ea6037cd27e73a915f64d72d353cf8b86c2f3fc5c

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
yes

**Checklist**
- [X ] I have included a Viaversion dump
- [X ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by Xayanix** [comment]
Also this happens:
[21:01:07] [Netty Epoll Server IO #1/WARN]: [ViaBackwards] Unknown named sound in 1.13->1.12 protocol: minecraft:random.orb

**Comment by KennyTV** [comment]
Completing the checklist will fix your issue.

**Comment by Xayanix** [comment]
Still got:
[ViaBackwards] Unknown named sound in 1.13->1.12 protocol: minecraft:random.orb

spam in logs
