### ISSUE TITLE
Error in Protocol1_9To1_8 in Rempa of Teams (0x3E)

### ISSUE THREAD

**Issue by Tauchet** [ViaVersion/ViaVersion#2132]
**Describe the bug, provide any errors**
Console log spam.
https://paste.gg/p/anonymous/a97ca546677f431baa8a4549859f2d8e

**How can we reproduce it?**
We don't know: c

**Expected behaviour**
It would be of great help to be able to solve it, since the failure occurs in the main server, you enter and exit, then everyone who comes to bungeecord for the first time and then expels it.

**Screenshots**
We don't know: c

**ViaVersion Dump**
https://dump.viaversion.com/5e044b2561ce98fb966378bc0c32576fd3ce98d6a02118d7d00a6a70a47d39c8

**Additional server info**
BungeeCord

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [-] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Probably a plugin sending bad packets.
