### ISSUE TITLE
Console error interact_entity

### ISSUE THREAD

**Issue by J4im3x0** [ViaVersion/ViaVersion#2133]
For any reason I get an error in the console, related to interact_entity
https://paste.gg/p/anonymous/256e5d2b6e884b22ac0c84979725569b

As far I know there is no way to reproduce it. I think that is a problem related on 1.9, due the error message.

https://dump.viaversion.com/cac4d2ff9362e556a6eb324a08450562317cb8e4700afefdb929ddfdba61ea25
I use a proxy, Travertine. My server is running 1.8.8 TacoSpigot

**Comment by KennyTV** [comment]
Very likely another plugin's fault. If you can reproduce this on a standard Paper + Bunge/Waterfall setup (and without other plugins after that), we will reopen the issue.
