### ISSUE TITLE
Can't Connect to a 1.12.2 Server with 1.8

### ISSUE THREAD

**Issue by Neilisop** [ViaVersion/ViaVersion#2134]
**I can't connect to my server that is in 1.12.2 and I'm connecting with 1.8**
I have "Via Version", "Via Backwards" and "Via Rewind" Running on my server

**Additional server info**
I'm using Bungeecord and I have all the plugins on there(I also tried removing the plugin on bungeecord and adding on the spigot/paper servers)

**Comment by KennyTV** [comment]
Follow the issue template. For this kind of question, it's best to join our Discord and ask there.
