### ISSUE TITLE
Players try to enter my server and are kicked

### ISSUE THREAD

**Issue by LordLucass** [ViaVersion/ViaVersion#2135]
Well, when players who are below version 1.12 try to enter my server (my server is a network and I use viaversion on everyone who is composed of it), they enter the desired minigame and end up being kicked and are faced with this error screen:

![err_image](https://user-images.githubusercontent.com/47451974/95929408-4f361080-0d9a-11eb-8497-b66b1498ab76.png)

**Comment by KennyTV** [comment]
Follow the issue template.
