### ISSUE TITLE
Playerstry try to enter on my server and are kicked-remake

### ISSUE THREAD

**Issue by LordLucass** [ViaVersion/ViaVersion#2137]
The problem is reproduced with any player who tries to get version 1.13 down, and the native version of my server is 1.12 and supports up to 1.8. It does not appear to send any error messages to the console.

**How can we reproduce it?**

1. Just entering the server, and you are automatically kicked because of this problem.

**Expected behaviour**

1. The players were expected to enter normally, but that didn't happen...

**Screenshots**

1. https://prnt.sc/uzc8l2

**ViaVersion Dump**

1. https://dump.viaversion.com/1910c90bdc4bc5382ade530d0711d7de7af0363fe13bd2235a54aca34f5b4b1b

**Additional server info**

1. I'm already using bungeecord w/ spigot.

**Checklist**
- [Y] I have included a Viaversion dump.
- [X] If applicable, I have included a paste (not a screenshot) of the error.
- [Y] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Actually try with the dev builds and send the full console error please.

**Comment by LordLucass** [comment]
Hello, sorry for the delay in replying, my day is busy. I have tried several versions of ViaVersion, ViaBackwards and ViaRewind and all tested cause the same error. I was able to pinpoint the error after a member was kicked for the problem. The complete log follows.


Log: https://ghostbin.co/paste/43h5x9



PS. Sorry my english. I'm brazilian.
