### ISSUE TITLE
getApi().getPlayerVersion(player) always returns version 404 regardless of version player is actually on

### ISSUE THREAD

**Issue by StrawberryOG** [ViaVersion/ViaVersion#2140]
**Describe the bug, provide any errors**
getApi().getPlayerVersion(player) always returns the server verison id regardless of client version player is on. I tested with client version 1.13.2 and it returns 404. Tested with client version 1.8.8 still same exact result return 404.
getApi().getPlayerVersion(player) used to work properly in previous versions of ViaVersion

**How can we reproduce it?**
https://i.ibb.co/SNCPTSh/Screenshot-from-2020-10-15-20-54-15.png
Use code ^ Join on any client version and use code above to view player Version always returns version id of server not client version of the player.
https://i.ibb.co/5nh7gPx/Screenshot-from-2020-10-15-20-54-26.png 

**Expected behaviour**
To return actual correct client version that the player is using.

**Screenshots**
https://i.ibb.co/SNCPTSh/Screenshot-from-2020-10-15-20-54-15.png
https://i.ibb.co/5nh7gPx/Screenshot-from-2020-10-15-20-54-26.png 

**Additional server info**
PaperSpigot 1.13.2, ViaVersion 3.1.1

**Comment by Xernium** [comment]
Follow the issue template. 
Also if I were to guess you:    
1: Either have the Via plugins installed both on your proxy (ie bungeecord or velocity) and your servers, in which case you’d need to remove them from there.   
2: You are running ProtocolSupport for older version support. In that case you’d need to use the ProtocolSupport API for all < 1.13.2 players.

**Comment by StrawberryOG** [comment]
No on #1
Thanks for #2 that answers what I needed.
