### ISSUE TITLE
Error occurs when killing a husk

### ISSUE THREAD

**Issue by vulpinefoxxo** [ViaVersion/ViaVersion#2141]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?

**How can we reproduce it?**
1. Login on 1.12.2
2. Kill a husk
3. ![image](https://user-images.githubusercontent.com/68159867/96261614-5727c780-0fc9-11eb-9d91-dc6f5f675e04.png)

**Expected behaviour**
Nothing happens.

**ViaVersion Dump**
https://dump.viaversion.com/3d26fdf45c04783d10bae3e8541ba076910dba18fd22e519db299347a9093d98

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Checklist**
- [X] I have included a Viaversion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

Edit: Error only occurs when it feels like it wants to

**Comment by KennyTV** [comment]
Complete the checklist.
