### ISSUE TITLE
Via version / via rewind bug when blocking 1.9+

### ISSUE THREAD

**Issue by Mitzythecat** [ViaVersion/ViaVersion#2142]
**Describe the bug, provide any errors**
When I join with 1.9+, it shows this error: https://paste.gg/p/anonymous/d71b02f6f3934db5ae7997f7929d79fe
I want to block 1.9+ and only support 1.7- 1.8 but if you join with 1.9+ it doesn't show the disconnect message.

**How can we reproduce it?**
Steps to reproduce the behaviour:
make this the protocol config:
https://prnt.sc/v0oqbd
make sure you have a 1.8 paper server
use flamecord as the proxy
join with 1.9+

**Expected behaviour**
It just always doesn't show me the 1.7-1.8 only supported message on 1.9+ and just times out with readout exception null

**Screenshots**
https://prnt.sc/v0ot51

**ViaVersion Dump**
https://dump.viaversion.com/e85de94d124135290df007adbccaa2242352544bf7e414d7e69073828e2d24c2

**Additional server info**
I use flamecord for proxy and paper 1.8.8 for the server version. I have viaversion and viarewind installed on all the paper servers.

**Checklist**
- [✅] I have included a Viaversion dump
- [✅] If applicable, I have included a paste (not a screenshot) of the error
- [✅] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Fixed in the dev-branch.
