### ISSUE TITLE
Decoder Exception

### ISSUE THREAD

**Issue by Ytnoos** [ViaVersion/ViaVersion#2143]
**Describe the bug, provide any errors**
When a player sent an invalid packet ViaVerson threw this exception: https://paste.gg/p/anonymous/df7a27a4b6e247d0b8c343f3935926b9

**How can we reproduce it?**
I don't have the invalid packet so I don't know

**ViaVersion Dump**
https://dump.viaversion.com/d099049beba576fa8988c765d87957c858e1ffa26287145d5d2e435d5f71aa80

**Additional server info**
git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Plugins (10): Essentials, EssentialsSpawn, LPX, LuckPerms, NoCheatPlus, PlugMan, spark, ViaBackwards, ViaRewind, ViaVersion

**Comment by KennyTV** [comment]
This is a ViaRewind issue, and probably caused by invalid NBT.

**Comment by Ytnoos** [comment]
> This is a ViaRewind issue, and probably caused by invalid NBT.

Should I open an Issue on ViaRewind?
