### ISSUE TITLE
armor is not visible

### ISSUE THREAD

**Issue by k0l0r3k99** [ViaVersion/ViaVersion#2145]
I'm not sure if it's ViaVersion issue, but I don't know how to debug it. I've custom proxy in C++ and custom PaperSpigot 1.8.8 + cloned ViaVersion-common as separate netty application. I don't see armor bar on 1.9 - 1.16.3.
![Screenshot 2020-10-19 at 22 06 28](https://user-images.githubusercontent.com/30705417/96506305-b1d65300-1257-11eb-9db6-9909943d3b2a.png)

**Comment by FormallyMyles** [comment]
Worth noting that ViaVersion running separately won't make armour work properly for the bar, it's a spigot listener for that reason as there's no inventory tracking. Otherwise, we're unable to help with custom software.

**Comment by k0l0r3k99** [comment]
Hi,

Thanks for your quick reply. I'd like to make sure - https://github.com/ViaVersion/ViaVersion/blob/master/bukkit-legacy/src/main/java/us/myles/ViaVersion/bukkit/listeners/protocol1_9to1_8/ArmorListener.java I must implement this by self, right?

**Comment by FormallyMyles** [comment]
Yep
