### ISSUE TITLE
Got error and told me to post this here?

### ISSUE THREAD

**Issue by AndrewDisco** [ViaVersion/ViaVersion#2147]
**Describe the bug, provide any errors**
Happens when using plugin https://www.spigotmc.org/resources/screamingbedwars-1-9-1-16.63714/ on paper mc 1.15.2

Error:
https://paste.gg/p/anonymous/a5b06fa6241646169f2932383d505de8

**How can we reproduce it?**
1. Install plugin
2. Login to the server
3. Setup a map
4. Start a game
5. Error appears

**Expected behavior**
It is expected that the game starts, instead, the players get kicked.

**Screenshots**
![image](https://user-images.githubusercontent.com/66111825/96688130-750a7900-1389-11eb-9348-34521b719d4f.png)

**ViaVersion Dump**
Response: **We've made a dump with useful information, report your issue and provide this url: https://dump.viaversion.com/57010ef046ed7cadae431ae75f973e8675a1e1ff90863a2d851e73353ccc6681**

**Additional server info**
Server info: PaperMC 1.15.2 connected to Waterfall
Plugins: BedWars, FastAsyncWorldEdit, JumpPads, LiteBans, Multiverse-Core*, PlaceholderAPI, ProtocolLib, SBAHypixelify, SkinsRestorer, Spartan, SpawnX*, SuperVanish, TabList, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard

**Checklist**
- [ ✔] I have included a Viaversion dump
- [ ✔] If applicable, I have included a paste (not a screenshot) of the error
- [ ✔] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
You cut off the important part, but updating to the ci builds (completing the checklist) will probably fix it.

**Comment by AndrewDisco** [comment]
I actually did that and got this error instead of last one:

Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Type: Chunk, Index: 0, Data: [Pair{Type|Chunk, us.myles.ViaVersion.api.minecraft.chunks.Chunk1_8@184d8ac5}], Packet ID: 33}
Actual Error:

**Comment by KennyTV** [comment]
Send the new viaver dump output please.

**Comment by AndrewDisco** [comment]
Sorry for late comment! 

**We've made a dump with useful information, report your issue and provide this url: https://dump.viaversion.com/5f191910cb04c433675223691cd05786507c91f3c76a4dcb64bd440124addbd4**

@KennyTV

**Comment by KennyTV** [comment]
No worries; you have to update ViaRewind to the 1.5.2-SNAPSHOT ci build.

**Comment by AndrewDisco** [comment]
I got my friend to try this again, still an error

![image](https://user-images.githubusercontent.com/66111825/96830990-ef4c0380-1444-11eb-8d2b-4017a1b08dd2.png)

@KennyTV

**Comment by AndrewDisco** [comment]
Dump: https://dump.viaversion.com/bf6d235752ad072c22d1b56ccc72a301e09eafb104f814dc1f69bb5b7104b892

**Comment by KennyTV** [comment]
We need the full error. Also, please try without SkinsRestorer and FAWE before that.
