### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by herrmannR** [ViaVersion/ViaVersion#2149]
I have a Minecraft Server on version 1.15.2. I have the ViaVersion, ViaBackwards and ViaRewinds plugins on the server. 

I can use Minecraft version 1.13. until 1.15.2. 
But when I use version 1.12.2 I get this error message:  > https://share-your-photo.com/6136c111e2?

/viaversion dump
https://dump.viaversion.com/072220b20420bb9c3b634e9cd4e35f3a8e7ec191eec86b78bab15695842af3b3

**Additional server info**
- Bungeecord 
- (CloudNet)
- Contabo (Hoster)

**Comment by KennyTV** [comment]
Follow the issue template (you didn't complete the checklist).
