### ISSUE TITLE
EncoderException : us.myles.viaversion.exception.informativeexception:

### ISSUE THREAD

**Issue by Vivamente** [ViaVersion/ViaVersion#2150]
**Describe the bug, provide any errors**

**How can we reproduce it?**
1. Version is 1.14.4
2. Running Optifine, Forge & MpM
3. Unsure as to the cause of the crash.

![image](https://user-images.githubusercontent.com/73279918/96847454-1b6a8300-144b-11eb-9cda-cdada20f5eac.png)

**Comment by KennyTV** [comment]
Follow the issue template.
