### ISSUE TITLE
Ran a command on a server I mod and I cant rejoin and im getting this msg

### ISSUE THREAD

**Issue by eatyba12** [ViaVersion/ViaVersion#2151]
![unknown](https://user-images.githubusercontent.com/16872642/96946189-7e343c80-1494-11eb-9615-17d8049d8187.png)

**Comment by Xernium** [comment]
We can’t help you if you don’t follow the issue template, it’s there for a reason.
If you still want help with this, please open a new issue and follow the issue template so we can help.
