### ISSUE TITLE
Server Crash & Console Spam

### ISSUE THREAD

**Issue by KleinWunder** [ViaVersion/ViaVersion#2153]
**Describe the bug, provide any errors**
We have not found a clear reason for the error to occur but the server crashes randomly with this error being spammed multiple times every second:
https://paste.gg/p/anonymous/1bc1c3270be1420d915abfa90efd5e0c

**ViaVersion Dump**
 https://dump.viaversion.com/4ad9fee92f65b7feeebb73d6c5297e9ecb4f3073e3d8802cf4ee5ae57fb22dc8

**Additional server info**
No BungeeCord.

**Checklist**
- [X] I have included a Viaversion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by Xernium** [comment]
Please try to replicate this with the latest version of ViaVersion found here https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/jar/target/ViaVersion-3.2.0-SNAPSHOT.jar

**Comment by KleinWunder** [comment]
How am I going to replicate it when the bug randomly occurs?
I just thought anyone could figue out what went wrong

**Comment by Xernium** [comment]
Then please update your ViaVersion using the URL I posted and if it occurs again then please open a new issue.
