### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Volgeop** [ViaVersion/ViaVersion#2154]
**Describe the bug, provide any errors**
Hi from some reason I got this error in console and players were kicked from server, don't know exactly what happened.

**How can we reproduce it?**
1. Players were logged probably with multiple versions, but most of them were using 1.16.3 (server is also on 1.16.3).
2. Then there tried to join so many players on the server, because I restarted proxy before.
3. Then it kicked them back to Lobby with this error probably.

**Expected behaviour**
Normally joining server without error.

**ViaVersion Dump**
https://dump.viaversion.com/42623072eafefa01ac54afe2e848baf6a1a51573a6a11729c0c8851c831ba67e

**Additional server info**
Yes, I use bungeecord - waterfall, the newest version, and I don't use there via version plugins, these I use just on sub servers.

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
You didn't provide the error / didn't test the builds from the ci. Please try that first

**Comment by Volgeop** [comment]
https://pastebin.com/Ku408cME

I have 475 build, and by changelog the build 476 didn't fix it.

**Comment by FormallyMyles** [comment]
You'd also need to update Rewind / Backwards. Also if the issue still happens you should put this in the ViaBackwards issues page.

**Comment by Volgeop** [comment]
But I downloaded viabackwards and viarewind at the same time, so they should be compatible.

**Comment by FormallyMyles** [comment]
> But I downloaded viabackwards and viarewind at the same time, so they should be compatible.

If you downloaded both then feel free to copy the issue on ViaBackwards but post a new /viaversion dump
