### ISSUE TITLE
Error on connecting with 1.13.2 to a 1.16.3 server

### ISSUE THREAD

**Issue by JGamesOficial** [ViaVersion/ViaVersion#2155]
**Describe the bug, provide any errors**
https://paste.gg/p/anonymous/6882400021cf4886809ac23396753390

**How can we reproduce it?**
1. create a paper 1.16.3 server with via version, viabackwards and viarewind
2. login to the server with 1.13.2 (1.14.4, 1.15.2 and 1.16.3 are working fine)

**Expected behaviour**
When you are connecting to the server it will kick you.

**ViaVersion Dump**
https://dump.viaversion.com/d0246eb38598ae8e8cae739925ac0c81fbf410560219152a1fe7c47c92be0791

**Additional server info**
im not using bungeecord and these are my plugins: 
ActionBarAPI, AdvancedClans*, AdvancedFood, AdvancedRegionMarket, AnimationLib, Announcer*, BannerBoard*, BlockBall*, BloodEffects*, CasinoPlugin, ChatManager, Citizens, CitizensText, CommandNPC*, CommandRegions*, CrazyAuctions, CubCustomDrops, CuffEm, DeathSpawnR*, DiceFurniture, dtlTradersPlus, Elevator, EntityTrackerFixer, EpicRename, Essentials, EssentialsChat, EssentialsSpawn, ExecutableItems, FogusCore, FurnitureLib, FurnitureMaker, GPS, HolographicDisplays, JukeBox, KiteBoard*, LagAssist, LaggRemover, LightAPI, LuckPerms, Marriage, McEventCore, Multiverse-Core*, MVdWPlaceholderAPI*, MyCommand, MysqlEconomyBank, NoCrafting*, NoteBlockAPI, OldCombatMechanics, OreRegenerator, PlaceholderAPI, PluginConstructorAPI, PluginHiderPlus*, PlugMan, ProtectionLib*, ProtocolLib, PsudoCommand, QualityArmory, QualityArmoryVehicles, Quests, ResourcePackDownloader*, ReviveMe, Robbery*, RPGChest, SalaryManager, ServerTutorialPlus*, SimpleSit*, SkinsRestorer, SurvivalMechanics, TAB, Telecom, Thirst, TouchscreenHolograms, TrMenu, Vault, ViaBackwards, ViaRewind, ViaVersion, WebConsole, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Checklist**
- [x] I have included a Viaversion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
If using ci builds doesn't fix it, a plugin is sending bad components.
