### ISSUE TITLE
Client got kicked from server because String is too big

### ISSUE THREAD

**Issue by NathZen** [ViaVersion/ViaVersion#2158]
**Describe the bug, provide any errors**
The server is running in 1.13.2. We have an RPG plugin that uses long lore string to describe it and an Item2Chat plugin. If the item have long String, and someone link it in chat, clients with version 1.14 and up got kicked from server, but clients with version 1.13.2 still remains inside server.

**How can we reproduce it?**
1. Server using 1.13.2
2. Client using 1.14 and up
3. Create a long string of lore
4. Link it using Item2Chat
5. Client with 1.14 will kicked, but 1.13.2 still remain on server

**Expected behaviour**
Does not kick clients with 1.14+

**Server Log**
[Log Link](https://paste.gg/p/anonymous/03de2a36ba0343d5bb97ab2a0f2b2282)

**ViaVersion Dump**
[Dump Link](https://dump.viaversion.com/14538afcdbed8dbe5c4f664ec0a7fa86ffd64365de4552e0c03da34e16cb0523)

**Additional server info**
> BungeeCord
> MMOItems 5.3.2
> MMOLib 1.0.8
> Item2Chat 4.2.0

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Use the ci build, as the checklist suggests.

**Comment by NathZen** [comment]
Okay.. tried again with the 3.2.0-SNAPSHOT version and still kicking clients
[ViaVersion Dump](https://dump.viaversion.com/cfb44732002287a094760c959c9ee1cc487ac43a26dfdf0569409c011d3f845a)
[Error Log](https://github.com/ViaVersion/ViaVersion/files/5450538/log.log)

**Comment by NathZen** [comment]
[Screenshot](https://media.discordapp.net/attachments/684671770543783958/770920244806025226/javaw.exe_Screenshot_2020.10.28_-_14.59.08.65.png?width=1204&height=677)

**Comment by NathZen** [comment]
Tried on Spigot 1.13.2 Server, it doesn't show the item in chat, but does not kick 1.14+ clients (Shows String is too big error in log)

Tried on Paper 1.13.2-655 Server, it show the item in chat (for 1.13.2 clients), but kicks 1.14+ clients (Shows String is too big error and the super-long-json-string of the item that chatlinked)

**Comment by KennyTV** [comment]
Thank you for the additional info; can you please try again with this build (and resend the new error in a paste if it still occurs)?
https://workupload.com/file/4G6JgF9zELV

**Comment by NathZen** [comment]
It can link the Item, but the lore does not show in chat and in inventory

Server: Paper 1.13.2-655
Client: Forge 1.16.3 + Optifine

![image](https://user-images.githubusercontent.com/61259322/97440677-5b090180-195a-11eb-885a-0caf95deeac5.png)
![javaw exe Screenshot 2020 10 28 - 20 13 58 08](https://user-images.githubusercontent.com/61259322/97440888-a6231480-195a-11eb-886c-c6a00f4169c4.png)
![javaw exe Screenshot 2020 10 28 - 20 17 57 45](https://user-images.githubusercontent.com/61259322/97441008-cce14b00-195a-11eb-94ba-f93aa1cce41a.png)

**Comment by KennyTV** [comment]
Whoops, try this one then https://workupload.com/file/UfTaFJWtKy3

**Comment by NathZen** [comment]
Eeh it works! Good job! :D 

Server: Paper 1.13.2-655
Client: Forge 1.16.3 + Optifine

![javaw exe Screenshot 2020 10 28 - 20 30 37 01](https://user-images.githubusercontent.com/61259322/97442860-e5526500-195c-11eb-96c5-bf89a12fe047.png)
![javaw exe Screenshot 2020 10 28 - 20 32 54 25](https://user-images.githubusercontent.com/61259322/97442873-e84d5580-195c-11eb-9094-f9ac2698c2f6.png)

**Comment by KennyTV** [comment]
Alright, perfect. :)

**Comment by NathZen** [comment]
So.. this is build 373 on DEV version and runs well, but the lore is in italic

But then I tried build 374 on DEV version, it gives same error "String is too big" and kicks again

**Comment by NathZen** [comment]
Tried version 3.2.0 Release and did the same problem: "String is too long"

**Comment by KennyTV** [comment]
Not really too much we can do (without starting to remove big chunks of text and doing lots of serialization and length checks), sorry :/

**Comment by NathZen** [comment]
Is it allowed to modify a bit the source for personal usage?

**Comment by KennyTV** [comment]
Of course
