### ISSUE TITLE
error by joining 1.13 server in 1.16

### ISSUE THREAD

**Issue by NielsCraft12** [ViaVersion/ViaVersion#2159]
Describe the bug, provide any errors
if I join my 1.13 server I get this error (see image)
![Capture](https://user-images.githubusercontent.com/47089232/97466957-f9d63380-1943-11eb-9f3e-a682d2e60188.PNG)

How can we reproduce it?
1. Login on 1.16.3'

Expected behavior
I can join my server

**Comment by KennyTV** [comment]
Follow the issue template.
