### ISSUE TITLE
Error in console whenever a 1.8.9 client clicks on a block on 1.15.2 server

### ISSUE THREAD

**Issue by IamMusavaRibica** [ViaVersion/ViaVersion#2160]
**Describe the bug, provide any errors**
Whenever a block is broken or is stopped breaking  this error appears in console https://paste.gg/p/anonymous/05f4ac8e199b4feb82f3648095ef859e
Note that it doesnt appear when someone starts breaking a block, it appears when he breaks that block or he stops breaking it

**How can we reproduce it?**
1. Login on 1.8.9 on a native 1.15.2 server'
2. Click on 'any block'
3. When you break the block or you stop breaking it an error appears

**Expected behaviour**
No errors should happen

**Screenshots**

**ViaVersion Dump**
https://dump.viaversion.com/1919b2aba3be8476353f4849325e30c1e1d9af268a40e8e4a32b7c0a501c7500

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
Please ensure you test latest builds from CI. Otherwise report on ViaRewind GitHub page
