### ISSUE TITLE
Waterfall Error

### ISSUE THREAD

**Issue by Hellohi3654** [ViaVersion/ViaVersion#2161]
**Describe the bug, provide any errors**
The error started happening after I set up my server to use waterfall all server's display this error
Viaversion still works just this error is displayed
I have tried updating and the error still occurs
https://paste.gg/p/anonymous/1007e4059b21481c97a1af0c0b52908d

**How can we reproduce it?**
1. Create a waterfall server
2. Create two spigot or paper server's
3. Error will occur on server startup

**Expected behaviour**
Error not to occur

**Screenshots**
![image](https://user-images.githubusercontent.com/57390764/97780126-cbbc5200-1bd6-11eb-8156-dc13892f614a.png)

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.
Waterfall server dump:
Other server dump: https://dump.viaversion.com/e7350ee2da6a7497113d2fcffa53b17afb85530aafb663e91651194674772efe
Other server dump: https://dump.viaversion.com/49085e05a623f4262b3a730424c279f61325964f3da0fea2f84c4780ad1313ce
Other server dump: https://dump.viaversion.com/c8b2703e63ea923d05993ea0603ae68b0e405c97562a1145cb76f0d24190cff0

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
I have one waterfall server and 3 upstream server's

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Yatopia is not supported, it's likely just someone sending bad pings otherwise.

**Comment by Hellohi3654** [comment]
I haven't had this problem with Yatopia until I made my server use waterfall

**Comment by KennyTV** [comment]
Don't use Via on both proxy and backend, only on either one (backend preferred).

**Comment by Hellohi3654** [comment]
oh ok thanks
