### ISSUE TITLE
Color Code Issues in Item Names [ViaVersion 3.2.0]

### ISSUE THREAD

**Issue by PizzaStyx** [ViaVersion/ViaVersion#2165]
**Describe the bug, provide any errors**
The reset (&r) color code no longer works in item names for any client that connects, including the native version (1.12.2).

Also, all renamed items are now italicized by default in any version above 1.12.2. I suspect these two issues are related, so I have chosen to report them together.

These bugs only occur on the latest release: ViaVersion 3.2.0. The previous release, ViaVersion 3.1.1, did not have this issue. 
There are no console errors upon either interaction.

**How can we reproduce it?**
Reset Color Code being broken:
1. Install ViaVersion 3.2.0 on a 1.12.2 server.
2. Login with any compatible client. (1.12.2 - 1.16.4)
3. Look at any renamed item with the reset (&r) color code in the name.

Item Names Italicized by Default:
1. Install ViaVersion 3.2.0 on a 1.12.2 server.
2. Login with any non-native compatible client. (1.13 - 1.16.4)
4. Look at any renamed item that is not supposed to be italicized.

**Expected behaviours**
Item names with the reset color code should work properly.
Item names with any color codes should not be italicized by default.

**Screenshots**
Broken Reset (&r) Code:
1.16.4 Client: https://i.imgur.com/XYKQbwi.png
1.12.2 Client: https://i.imgur.com/pjByY6N.png

Italic by Default:
1.16.4 Client: https://i.imgur.com/PBDGLBq.png
1.12.2 Client: https://i.imgur.com/AGM6HIP.png

**ViaVersion Dump**
https://dump.viaversion.com/13a722c3bc109533ca6a5234125ff6c47f951cbbda603915fcbc9eb07795a129

**Additional server info**
I am using Waterfall (build 381) and Paper 1.12.2 (build 1618). Another server with an identical setup running ViaVersion 3.1.1 is on the same network but does not have any of these issues.

**Comment by KennyTV** [comment]
Can you try with https://workupload.com/file/DJnFrKxPVjq please?

**Comment by PizzaStyx** [comment]
The italicized item names issue has been fixed in this build.

After some extensive investigation, the &r color code not working in item names has turned out to be a LuckPerms issue.

Thanks for the help! You may close this now.

**Comment by KennyTV** [comment]
Perfect, thank you.
