### ISSUE TITLE
Issue with torch block rotation

### ISSUE THREAD

**Issue by Dablakbandit** [ViaVersion/ViaVersion#2166]
**Describe the bug, provide any errors**
Issue with torch rotation on 1.16, seems to be the only block that is incorrectly rotated.

**How can we reproduce it?**
1. Use any 1.16.* version, screenshot is from 1.16.4
2. Join minescape.me
3. Use selector and pick world 1
4. Look around at the wrongly rotated torches

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/5752611/97971708-521ba280-1e28-11eb-813d-9d46596eea9b.png)

**ViaVersion Dump**
Not needed

**Additional server info**
Viaversion is installed only on the bungeecord.
Base server versions are 1.13.2

**Comment by KennyTV** [comment]
We need a server dump and a way of reproducing it locally.

**Comment by Dablakbandit** [comment]
https://dump.viaversion.com/01a94a5419faa5aa2eb193641f87871d971274cb91a9a1bfa99ae0bec3e2f249

Should be reproducible on any base server 1.13.2 and bungeecord with viaversion as far as I can tell.

**Comment by KennyTV** [comment]
Can't reproduce, also, FlameCord is not supported. Please try with a standard Bungee/Paper setup (and possibly try putting Via on the backend server instead of the proxy)

**Comment by Dablakbandit** [comment]
Able to reproduce on official BungeeCord:

https://dump.viaversion.com/3028878d62fe8bfa0e6cd3c4445b14c432f11645f33f995d4ad92d039ae73c79

**Comment by KennyTV** [comment]
I'm going to assume you have some funky client mods going on, since a torch's particles are 100% clientside and are at the correct position.

**Comment by Dablakbandit** [comment]
Using vanilla minecraft 1.16.4, requesting to be reopened

**Comment by KennyTV** [comment]
Sorry, will only reopen if you we have a way of reproducing this cleanly, especially given the *client-side* particles being at the correct position and nothing of this kind having ever happened with blockstates being pretty deterministic

**Comment by Dablakbandit** [comment]
Have you even followed the step to reproduce?

**Comment by Dablakbandit** [comment]
Just leave it I guess, thanks for your time

**Comment by KennyTV** [comment]
Yes, please fix your resourcepack :p

**Comment by Dablakbandit** [comment]
Apologies, again thanks for your time, have resolved the issue.
Was a little annoyed as with my last bug that I reported was also closed early as not a viaversion issue, then fixed at a later date

**Comment by KennyTV** [comment]
No worries, mishaps happen to everyone
