### ISSUE TITLE
Viaversion bugs away blocks

### ISSUE THREAD

**Issue by UltraBlackLinux** [ViaVersion/ViaVersion#2168]
**Describe the bug, provide any errors**
This should do it:
https://streamable.com/x2mnh1

**Expected behaviour**
Let the blocks stay in place

**ViaVersion Dump**
I don't know the server's viaversion - so I can't create a dump. This happens on pretty much any server with VV

**Additional server info**
mcplayhd.net

**Checklist**
- [ ] I have included a Viaversion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Not a Via issue.
