### ISSUE TITLE
Enderman's on 1.8 clients when server is on 1.15.2 crashes your game

### ISSUE THREAD

**Issue by orange0530** [ViaVersion/ViaVersion#2169]
**Describe the bug, provide any errors**
No, but the client gives a crash report https://paste.gg/p/anonymous/04111aba5394488ba88f7fda937153a7 . Endermans cant render and crashes the game.

**How can we reproduce it?**
1. Make a 1.15.2 server (Paper-372)
2. Install viarewind & viabackwards
3. Load a 1.8 client 

**Expected behaviour**
The enderman to render and not crash the game 
**Screenshots**
No.

**ViaVersion Dump**
https://dump.viaversion.com/8c56486bd1f685cf8d2e6d0bad0b1809833f086851bf69822d60552871fe5a8c

**Additional server info**
https://gyazo.com/df2b3b0647e108fba020b0c100b3c9b2

**Checklist**
- Viaversion dump
- Included Additional server info
- Said how to reproduce
- described the bug
- Gave a crash report. And there wasent an error in console

**Comment by KennyTV** [comment]
You're outdated.
