### ISSUE TITLE
ViaVersion error while connecting with 1.8 client

### ISSUE THREAD

**Issue by JeremyTorres235** [ViaVersion/ViaVersion#2171]
**Describe the bug, provide any errors**
Hello, here's the error https://paste.gg/p/anonymous/97120ca61f3a43abbf61eb1ebc22d279
1.16 and 1.12 is able to connect fine.

**How can we reproduce it?**
1. Login on 1.8
2. Connect to a network
3. Player get's kicked

**Expected behaviour**
Player should be able to connect to the network.

**Screenshots**

**ViaVersion Dump**
- https://dump.viaversion.com/67bb5ba9c30cf09e560d3d374a214e20994908567e6fe9a64bf5e41b667ee3b7

**Additional server info**
Waterfall, lastest version (updated it yesterday). This started when we updated our lobby to the lastest viaversion.

**Comment by FormallyMyles** [comment]
This should go on ViaRewind.

**Comment by KennyTV** [comment]
Your ViaRewind is outdated.
