### ISSUE TITLE
FastAsyncWorldedit 1.12.2 on 1.16.3 client is kicking

### ISSUE THREAD

**Issue by Govindass** [ViaVersion/ViaVersion#2172]
**Describe the bug, provide any errors**
I pasted a clipboard (just a line of sponge blocks) using 1.16.3 version on a 1.12.2 server and I got kicked. The clipboard was done above void, near some sky islands
Error: https://paste.gg/p/anonymous/80b31af215234f70af0866dfd5831498

**How can we reproduce it?**
1. Paste clipboard using FastAsyncWorldEdit with conditions like explained above
2. Observe yourself getting kicked

**Expected behaviour**
to not get kicked

**Screenshots**
None

**ViaVersion Dump**
https://dump.viaversion.com/75be6e65721ddad859e6384b6d45658097e4bdcd65ce5d910795247dbe47657b

**Additional server info**
Waterfall proxy (but I don't use ViaVersion on proxy), server software PaperBin

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Please use normal WorldEdit.
