### ISSUE TITLE
All players version shows 1.15 on 1.8 Paper server

### ISSUE THREAD

**Issue by ObeyBeastJj23** [ViaVersion/ViaVersion#2173]
**Describe the bug, provide any errors**
Simply, when players join the server (bungeecord redirects to hub which is on Paper 1.8) all players' versions are "1.15.2"

**How can we reproduce it?**
1. Login on any version
2. Check viaversion list
3. Version is simply displayed wrong.

**Expected behaviour**
Players versions to show as their actual version

**Screenshots**
Don't think this is needed

**ViaVersion Dump**
https://dump.viaversion.com/ebf1e12f5bdb5353f48bf509f1121db4cb4e7579cd65a4df816fa3a831497ede

**Additional server info**
We run on BungeeCord, which redirects you to a 1.8.8 PaperMC server. The plugins are listed in the dump above already ^

**Checklist**
- [Y] I have included a Viaversion dump
- [Y?] If applicable, I have included a paste (not a screenshot) of the error
- [Y] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
Do you run ViaVersion on Bungee and Paper?

**Comment by ObeyBeastJj23** [comment]
Both, I haven't tried the dev build/3.3.0 on my bungee though so i'll do so now

**Comment by KennyTV** [comment]
Only run Via on *either* one, preferably the backend.

**Comment by ObeyBeastJj23** [comment]
Better news, all clients get logged as 1.8 now, I'm running viaversion on bungee only now

**Comment by Seanoo1** [comment]
@ObeyBeastJj23 don't install viaversion on bungee if you have 1.8 server.
