### ISSUE TITLE
what the hell

### ISSUE THREAD

**Issue by ignJack** [ViaVersion/ViaVersion#2175]
07.11 20:44:48 [Server] WARN [ViaVersion] ERROR IN Protocol1_8TO1_9 IN REMAP OF 0x0C->0xFFFFFFFF
07.11 20:44:48 [Server] WARN us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
07.11 20:44:48 [Server] WARN {Type: JsonElement, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1$1 (Anonymous), Packet ID: -1, Source 1: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1 (Anonymous)}
07.11 20:44:48 [Server] WARN Actual Error: 
07.11 20:44:48 [Server] WARN Caused by: java.io.IOException: Unable to read type JsonElement, found String
07.11 20:44:48 [Server] WARN at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:156)
07.11 20:44:48 [Server] WARN at de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1$1.handle(PlayerPackets.java:58)
07.11 20:44:48 [Server] WARN at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
07.11 20:44:48 [Server] WARN at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
07.11 20:44:48 [Server] WARN at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)
07.11 20:44:48 [Server] WARN at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:449)
07.11 20:44:48 [Server] WARN at us.myles.ViaVersion.api.PacketWrapper.constructPacket(PacketWrapper.java:344)
07.11 20:44:48 [Server] WARN at us.myles.ViaVersion.api.PacketWrapper.send(PacketWrapper.java:301)
07.11 20:44:48 [Server] WARN at de.gerrygames.viarewind.utils.PacketUtil.sendPacket(PacketUtil.java:37)
07.11 20:44:48 [Server] WARN at de.gerrygames.viarewind.protocol.protocol1_8to1_9.storage.Cooldown.sendBossBar(Cooldown.java:108)
07.11 20:44:48 [Server] WARN at de.gerrygames.viarewind.protocol.protocol1_8to1_9.storage.Cooldown.showCooldown(Cooldown.java:69)
07.11 20:44:48 [Server] WARN at de.gerrygames.viarewind.protocol.protocol1_8to1_9.storage.Cooldown.tick(Cooldown.java:59)
07.11 20:44:48 [Server] WARN at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
07.11 20:44:48 [Server] WARN at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
07.11 20:44:48 [Server] WARN at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
07.11 20:44:48 [Server] WARN at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3566)
07.11 20:44:48 [Server] WARN at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
07.11 20:44:48 [Server] WARN at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
07.11 20:44:48 [Server] WARN at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
07.11 20:44:48 [Server] WARN at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
07.11 20:44:48 [Server] WARN at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
07.11 20:44:48 [Server] WARN at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
07.11 20:44:48 [Server] WARN at de.gerrygames.viarewind.utils.Ticker.lambda$init$0(Ticker.java:16)
07.11 20:44:48 [Server] WARN at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
07.11 20:44:48 [Server] WARN at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082)
07.11 20:44:48 [Server] WARN at de.gerrygames.viarewind.utils.Ticker.lambda$init$1(Ticker.java:15)
07.11 20:44:48 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
07.11 20:44:48 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
07.11 20:44:48 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
07.11 20:44:48 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
07.11 20:44:48 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
07.11 20:44:48 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
07.11 20:44:48 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by KennyTV** [comment]
Follow the issue template.
