### ISSUE TITLE
Clients got kicked from server because of Item name, lores, String(big)

### ISSUE THREAD

**Issue by OdnookeN** [ViaVersion/ViaVersion#2176]
Describe the bug, provide any errors
The server is running in 1.8.8. We have an Custom Enchants plugin that uses long lore string and names to describe it and an InteractiveChat plugin. If the item have long String, and someone link it in chat, clients with version 1.14 and up got kicked from server, but clients with version 1.13.2 still remains inside server.

How can we reproduce it?

Server using 1.8.8
Client using 1.14 and up
Create a long string of lore and name
Link it using Interactivechat ([item])
Client with 1.14 will kicked, but 1.13.2 still remain on server
Expected behaviour
1.8.8-1.13.2 versions will not be kicked.

Server Log
[Log Link](https://paste.gg/p/anonymous/d770a2c44a0b4d64a7498282d4c5dc2c)

ViaVersion Dump
[Dump Link](https://dump.viaversion.com/6f0b3f03e19cd343b09d05e045a2f2a4da169a20bcf560a2d4f972197b35c715)

Screenshot of Item Names:
![issue1](https://user-images.githubusercontent.com/74133423/98461443-1d706800-21e7-11eb-8d57-56f0759fd179.png)
![issue2](https://user-images.githubusercontent.com/74133423/98461444-1f3a2b80-21e7-11eb-9422-84ac3580a1fc.png)

Additional server info

StellarSpigot
AdvancedEnchantments Pre12.4
SimpleRename v13.8
InteractiveChat 3.2.2

Checklist

 I have included a Viaversion dump
 If applicable, I have included a paste of the error
 I have tried a latest build from https://ci.viaversion.com/ and DEV version. The issue still persists

**Comment by OdnookeN** [comment]
But it only fixed one part of it. For example if i link "\" called item in chat, it still it kicks for same logs. "\" (Special Character)
![issue2](https://user-images.githubusercontent.com/74133423/98462313-7e4f6e80-21ee-11eb-9ed3-96c10b1ea333.png)

**Comment by KennyTV** [comment]
New dump and logs please.

**Comment by OdnookeN** [comment]
[Dump Link](https://dump.viaversion.com/e4f0dfcf453afd480722708a98b27410ba114a6038ea71b1df2f792b93374abf)
[Log Link](https://paste.gg/p/anonymous/bf24b3c13b364fd99010f0f2951c64f7)

**Comment by KennyTV** [comment]
Sorry, this will probably a won't-fix, we don't intend to do any further fixes to legacy versions that make (shared) code for modern versions more annoying to deal with, which 1.8 nbt serialization definitely falls under.
