### ISSUE TITLE
Doesn't work for 1.15 and 1.16

### ISSUE THREAD

**Issue by LuckyGhost37** [ViaVersion/ViaVersion#2177]
My Server is 1.12 and i updated the plugin at the latest version. But i can't join my server in 1.15 and 1.16, what can I do?
Thanks. I leave an image of the error.
![BugServer](https://user-images.githubusercontent.com/64019586/98463199-e46dce80-21b9-11eb-92f9-fdb04cb41128.png)

**Comment by KennyTV** [comment]
Update BungeeCord.
