### ISSUE TITLE
Players crash and console get's this error. 

### ISSUE THREAD

**Issue by Porkason** [ViaVersion/ViaVersion#2179]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?

**How can we reproduce it?**
1. Have a server on 1.16.3
2. Use viaversion and viabackwards to supporto lder versions. 
3. login with 1.8 
4. use screaming bedwars and SBAHypixellyfe addon. 
5. Join a game and this error happens and 1.8 pLAYER CRASHES. 
The error: https://pastebin.com/UjHNJY9G

**ViaVersion Dump**
https://dump.viaversion.com/741d0063b954e1b0224e7611d44a1ccaca24c2df110b6e7a13908d8ac5e17647

**Comment by FormallyMyles** [comment]
Open on ViaRewind if it's a 1.8 issue
