### ISSUE TITLE
Viaversion error when calling packets

### ISSUE THREAD

**Issue by jusjus112** [ViaVersion/ViaVersion#2182]
**Describe the bug, provide any errors**
Error: https://paste.gg/p/anonymous/9ac20d33931f419186bdd5fb4964ce8e
This happened when I was calling the "PacketPlayOutCustomPayload" packet from one of my plugins.
It happened on Server Join.

**Expected behaviour**
When you join, a book is added to your inventory. Directly after that, a book is supposed to be opened with packets.

**Code**
https://paste.gg/p/anonymous/1a41a5e1ffa74dca91b2be31f9179e2c

**ViaVersion Dump**
https://dump.viaversion.com/a2565dc4abbde1ba2ffef437e8aab2aeb4a71eab7b7723b0729ee8d58e43c860

**Additional server info**
- Server Version Paper 1.12.2
- No external plugins

**Comment by KennyTV** [comment]
You are outdated, please update your Via plugin and correctly use the MC|BOpen channel (https://www.spigotmc.org/threads/tutorial-open-a-book-serverside.96101/)
