### ISSUE TITLE
NoClassDefFound error on SpongeVanilla

### ISSUE THREAD

**Issue by Willsr71** [ViaVersion/ViaVersion#2184]
When attempting to use the plugin on SpongeVanilla (all major api version between 7.3.0 and 7.1.10 tested), the plugin fails to initialize with the error https://hastebin.com/unepekafam.kotlin , all plugins except luckperms were removed for testing. ViaVersion versions 3.2.0 and 3.2.1 were tested.

The plugin still partially works, it lets you run most commands with the exception of dump, which results in the same error as above.

1. Launch SpongeVanilla with ViaVersion

**ViaVersion Dump**
N/A

**Checklist**
- [ ] I have included a Viaversion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Can't reproduce with 1.12.2-7.3.0 on the latest Via dev build, you possibly had broken/outdated builds.
