### ISSUE TITLE
20w46a ViaVersion DEV Test Bugs

### ISSUE THREAD

**Issue by RealRTTV** [ViaVersion/ViaVersion#2185]
**Describe the bug, provide any errors**
When using the creative menu and trying to get a 1.17 item which normally reverts to stone when clicking fast enough the item stays in your Inventory and makes a client-side server-side misplace allowing you to for example put 64 items into a bundle once the item receives an update like changing NBT or relogging the item reverts but if you put for example 64 iron ingots in it it will revert to stone but have the Items tag on it (When placing a 1.17 block down like copper it will revert to stone)
(The bug I've tested does not crash the server or make errors in console)

**How can we reproduce it?**
1. Start a server that supports plugins
2. Install the ViaVersion build linked in this issue
3. Start the server and join with a 20w46a client
4. Find 'bundle' from the creative menu
5. Hold down 1 when hovering over it until you see a bundle and not stone
6. Take anything that can be in a bundle and right click it over the bundle
7. The Process should be complete you can do /data get entity @s SelectedItem.tag to see the Bundle NBT

**Expected behaviour**
The stone has the bundles NBT Tags on the server-side and client-side illegally

**Screenshots**
![viaversiondevglitch](https://user-images.githubusercontent.com/72476111/98858866-4a16c080-242f-11eb-9485-5a0d4e436328.PNG)

**ViaVersion Dump**
https://dump.viaversion.com/10bb5a515feeab6db0a72d01c2ee443d2b85886b4750a543fcba9d5cee3f48d3

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
Well I don't think multiverse would do anything (Server runs spigot)

**Comment by KennyTV** [comment]
Won't fix, since the client can literally put any nbt there anyways.

**Comment by RealRTTV** [comment]
[ViaVersion-3.3.0-20w46a.jar.txt](https://github.com/ViaVersion/ViaVersion/files/5526491/ViaVersion-3.3.0-20w46a.jar.txt)
rename it from a txt :(

**Comment by RealRTTV** [comment]
RIP ok
