### ISSUE TITLE
Bug when a blocked version tried to join a server

### ISSUE THREAD

**Issue by Lunatik934** [ViaVersion/ViaVersion#2186]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?

**How can we reproduce it?**
1. Login on 1.13.2
2. Try to join a 1.8.8 server with block-protocols
3. Player don't receive a bad version message and I have this error on my logs

**Expected behaviour**
When 1.13.2+ players try to join the server with block-protocols they do not get a message that indicates the server version and I have this error in the logs

**Screenshots**
https://pastebin.com/J1zgPaz6

**ViaVersion Dump**
- https://dump.viaversion.com/40f617eb686ef12c82e6c758bbc7d3871a66c833a776d3e87f0a4ecffd9934ae

**Additional server info**
I use Waterfall for the proxy & Paperspigot 1.8.8 for spigot servers

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Your ViaVersion is outdated.
