### ISSUE TITLE
BUG: Protocol ossification in plugin channel names

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaVersion#2187]
https://en.wikipedia.org/wiki/Protocol_ossification
https://github.com/ViaVersion/ViaVersion/blob/692e53427b41f3f564e4e5701c38fa9b7553e7a0/common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/data/MappingData.java#L130
Fails to match these valid identifiers: "no_namespace_but_valid", "empty_path_but_valid:"
Empty namespace (like ":example") is parsed as "minecraft" ("minecraft:example")

**Comment by creeper123123321** [comment]
See #1448

**Comment by creeper123123321** [comment]
Prismarine web client uses "brand" with no "minecraft:"

**Comment by Gerrygames** [comment]
Is ``:`` a valid identifier?
