### ISSUE TITLE
Kicked whilst connecting to lobby: multiplayer.disconnect.incompatible

### ISSUE THREAD

**Issue by Palden150** [ViaVersion/ViaVersion#2189]
**Describe the bug, provide any errors**
Whenever I try to join my 20w45a fabric server, with viaversion and viabackwards on ANY version even 20w45a itself, it gives me an error saying "Kicked whilst connecting to lobby: multiplayer.disconnect.incompatible". 

**How can we reproduce it?**
1. Create a blank fabric 20w45a server
2. Create a waterfall 20w45a server with viaversion and viabackwards
3. Try to join from the proxy to the fabric server.
**Screenshots**
<img width="1920" alt="Capture" src="https://user-images.githubusercontent.com/18223237/98985145-fdd38b00-24d7-11eb-97d2-f65c8164cc01.PNG">

**ViaVersion Dump:**
https://dump.viaversion.com/d6e1579e002a6ef2b25d90b6d45de11bdebd9ab9d3e512eeedff523d2216dbcb

**Additional server info**
I am using the 20w45a dev builds of viaversion and viabackwards, and using https://github.com/Xernium/Waterfall/releases 20w45a build.

**Comment by KennyTV** [comment]
Does it work when you remove Via?

**Comment by Palden150** [comment]
I am able to connect with 20w45a without via.

**Comment by Palden150** [comment]
oops sorry

**Comment by ScriptJunkieMC** [comment]
Running into exact same issue. Any work being done on this or does it need more data / input?

**Comment by FormallyMyles** [comment]
I would suspect this is probably because your Bungee doesn't support the snapshot (there are very few forks which do), otherwise it is most likely a ViaBackwards issue.

**Comment by ScriptJunkieMC** [comment]
tested with 3.2.0 viaversion and fixes the problem. Its an issue with latest snapshot of via

**Comment by ScriptJunkieMC** [comment]
nice closed without resolution. thanks

**Comment by KennyTV** [comment]
We will unlikely do a fix for that soon anyways (unless I find time and motivation for that kind of low priority issue), since it's a setup that makes little sense running/supporting lower clients. It will work with the release tho.

**Comment by ScriptJunkieMC** [comment]
Cool np and i understand its low priority since its a custom setup. Just chuckled when he assumed i was using a non-snapshot support and just slammed door shut.

**Comment by quiquelhappy** [comment]
> I am able to connect with 20w45a without via.

Im having this exact issue when compiling bungeecord with prerelease support. Currently using vanillacord and its working great without viaversion, but when installing viaversion, I get this same message. Currently using 1.18 pre-1. I reopen this issue because I believe prereleases should be supported.

**Comment by FormallyMyles** [comment]
> > I am able to connect with 20w45a without via.
> 
> Im having this exact issue when compiling bungeecord with prerelease support. Currently using vanillacord and its working great without viaversion, but when installing viaversion, I get this same message. Currently using 1.18 pre-1.
> 
> [ME1312/VanillaCord#13](https://github.com/ME1312/VanillaCord/issues/13)

I would recommend joining our Discord for this kind of support, but if you're running a 20w45a server it won't work with 1.18 pre 1. While some builds do support pre-release/snapshot versions, only a single version is supported (usually the latest). Otherwise you'd need to provide the `/viaversion dump` if I've misread your message.
