### ISSUE TITLE
us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues {Type: Chunk, Index: 0, Data: [Pair{Type|Chunk, us.myles.ViaVersion.api.minecraft.chunks.Chunk1_8@f9ca7940}], Packet ID: 33} Actual Error:

### ISSUE THREAD

**Issue by Krestooov** [ViaVersion/ViaVersion#2193]
> [17:58:00 WARN]: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Type: Chunk, Index: 0, Data: [Pair{Type|Chunk, us.myles.ViaVersion.api.minecraft.chunks.Chunk1_8@f9ca7940}], Packet ID: 33}
Actual Error:
> [17:58:00 WARN]: Caused by:
> [17:58:00 WARN]: java.lang.IndexOutOfBoundsException: Index (0) is greater than or equal to list size (0)
> [17:58:00 WARN]: at us.myles.viaversion.libs.fastutil.ints.IntArrayList.getInt(IntArrayList.java:267)
> [17:58:00 WARN]: at us.myles.ViaVersion.api.minecraft.chunks.ChunkSection.getFlatBlock(ChunkSection.java:73)
> [17:58:00 WARN]: at de.gerrygames.viarewind.protocol.protocol1_8to1_9.types.ChunkSectionType1_8.write(ChunkSectionType1_8.java:38)
> [17:58:00 WARN]: at de.gerrygames.viarewind.protocol.protocol1_8to1_9.types.ChunkSectionType1_8.write(ChunkSectionType1_8.java:11)
> [17:58:00 WARN]: at de.gerrygames.viarewind.protocol.protocol1_8to1_9.types.Chunk1_8Type.write(Chunk1_8Type.java:92)
> [17:58:00 WARN]: at de.gerrygames.viarewind.protocol.protocol1_8to1_9.types.Chunk1_8Type.write(Chunk1_8Type.java:16)
> [17:58:00 WARN]: at us.myles.ViaVersion.api.type.PartialType.write(PartialType.java:24)
> [17:58:00 WARN]: at us.myles.ViaVersion.api.PacketWrapper.writeToBuffer(PacketWrapper.java:242)
> [17:58:00 WARN]: at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:411)
> [17:58:00 WARN]: at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:379)
> [17:58:00 WARN]: at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)
> [17:58:00 WARN]: at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)
> [17:58:00 WARN]: at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
> [17:58:00 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [17:58:00 WARN]: at java.lang.reflect.Method.invoke(Unknown Source)
> [17:58:00 WARN]: at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
> [17:58:00 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:458)
> [17:58:00 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:66)
> [17:58:00 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:232)
> [17:58:00 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
> [17:58:00 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:238)
> [17:58:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
> [17:58:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
> [17:58:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
> [17:58:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
> [17:58:00 WARN]: at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
> [17:58:00 WARN]: at me.neznamy.tab.platforms.bukkit.Injector$1.write(Injector.java:56)
> [17:58:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
> [17:58:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
> [17:58:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
> [17:58:00 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
> [17:58:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
> [17:58:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
> [17:58:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
> [17:58:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
> [17:58:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
> [17:58:00 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
> [17:58:00 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
> [17:58:00 WARN]: at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:200)
> [17:58:00 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:310)
> [17:58:00 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3$$Lambda$707.000000009D4D04E0.run(Unknown Source)
> [17:58:00 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> [17:58:00 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
> [17:58:00 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
> [17:58:00 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
> [17:58:00 WARN]: at java.lang.Thread.run(Unknown Source)

**Comment by KennyTV** [comment]
Follow the issue template.
