### ISSUE TITLE
io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues {Type: Chunk, Index: 0, Data: [Pair{Type|Chunk, us.myles.ViaVersion.api.minecraft.chunks.Chunk1_8@1f57426d}], Packet ID: 33} Actual Error:

### ISSUE THREAD

**Issue by MagicCode90** [ViaVersion/ViaVersion#2195]
> [03:52:35] [Netty Epoll Server IO #1/WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Type: Chunk, Index: 0, Data: [Pair{Type|Chunk, us.myles.ViaVersion.api.minecraft.chunks.Chunk1_8@1f57426d}], Packet ID: 33}
Actual Error:
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at me.RockinChaos.itemjoin.utils.protocol.TinyProtocol$PacketInterceptor.write(TinyProtocol.java:505)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at de.codingair.codingapi.player.data.PacketReader$1.write(PacketReader.java:72)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at net.minecraft.server.v1_16_R2.NetworkManager.lambda$4(NetworkManager.java:189)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at java.lang.Thread.run(Thread.java:748)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Type: Chunk, Index: 0, Data: [Pair{Type|Chunk, us.myles.ViaVersion.api.minecraft.chunks.Chunk1_8@1f57426d}], Packet ID: 33}
Actual Error:
> [03:52:35] [Netty Epoll Server IO #1/WARN]: Caused by: java.lang.IndexOutOfBoundsException: Index (0) is greater than or equal to list size (0)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at us.myles.viaversion.libs.fastutil.ints.IntArrayList.getInt(IntArrayList.java:267)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at us.myles.ViaVersion.api.minecraft.chunks.ChunkSection.getFlatBlock(ChunkSection.java:73)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at de.gerrygames.viarewind.protocol.protocol1_8to1_9.types.ChunkSectionType1_8.write(ChunkSectionType1_8.java:38)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at de.gerrygames.viarewind.protocol.protocol1_8to1_9.types.ChunkSectionType1_8.write(ChunkSectionType1_8.java:11)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at de.gerrygames.viarewind.protocol.protocol1_8to1_9.types.Chunk1_8Type.write(Chunk1_8Type.java:92)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at de.gerrygames.viarewind.protocol.protocol1_8to1_9.types.Chunk1_8Type.write(Chunk1_8Type.java:16)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at us.myles.ViaVersion.api.type.PartialType.write(PartialType.java:24)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at us.myles.ViaVersion.api.PacketWrapper.writeToBuffer(PacketWrapper.java:242)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:411)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:379)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:473)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:243)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at me.RockinChaos.itemjoin.utils.protocol.TinyProtocol$PacketInterceptor.write(TinyProtocol.java:505)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at de.codingair.codingapi.player.data.PacketReader$1.write(PacketReader.java:72)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at net.minecraft.server.v1_16_R2.NetworkManager.lambda$4(NetworkManager.java:189)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
> [03:52:35] [Netty Epoll Server IO #1/WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by KennyTV** [comment]
Follow the issue template.
