### ISSUE TITLE
[ViaVersion] Ignoring plugin channel in outgoing REGISTER: WECUI

### ISSUE THREAD

**Issue by PhantomRDM** [ViaVersion/ViaVersion#2197]
**Describe the bug, provide any errors**
If player join my server , console will show [ViaVersion] Ignoring plugin channel in outgoing REGISTER: WECUI
My server is paper 1.12.2 and player on 1.14.4, How to fix this error or will this affect the game?

**How can we reproduce it?**
1. player join server minecraft version 1.14.4
2. console will show [ViaVersion] Ignoring plugin channel in outgoing REGISTER: WECUI

**Expected behaviour**
Shouldn't show

**Screenshots**

**ViaVersion Dump**
https://dump.viaversion.com/5661993a7a66e7b776ed00e3b97385ef608f2f3b77439bcb631175acf8a593fa

**Additional server info**
Citizens, DiscordSRV, Essentials, LuckPerms, MythicMobs, Vault, ViaVersion, WorldEdit, WorldGuard

**Checklist**
- [x] I have included a Viaversion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by DoctorMacc** [comment]
This will not affect your game. This is WorldEdit trying to communicate with its client mod (from what I know) which doesn't work across versions. There's absolutely nothing to worry about - I get this all the time when I use ViaVersion and it does not affect me.

**Comment by PhantomRDM** [comment]
Thanks :)
