### ISSUE TITLE
you cant join a server

### ISSUE THREAD

**Issue by takipsizad** [ViaVersion/ViaVersion#2199]
you cant join a server with 1.9.1 

**How can we reproduce it?**
1. Login on 1.9.1'
it wont
small note that allows you but i used a multiconect mod 1.16.4 to 1.9.1

**Expected behaviour**
it should let you 

**Screenshots**
![image](https://user-images.githubusercontent.com/51132487/99218704-27e4c000-27ec-11eb-8273-e4a299972150.png)

**Additional server info**
bungeecord

**Checklist**
- [ ] I have included a Viaversion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Follow the issue template.
