### ISSUE TITLE
Fishing rod animation

### ISSUE THREAD

**Issue by ZedarYT** [ViaVersion/ViaVersion#2200]
Fishing rods are stuttering when used in 1.8

1. Login on 1.8
2. Use a fishing rod

**Expected behaviour**
Smooth usage of the fishing rod and no stuttering

**ViaVersion Dump**
https://dump.viaversion.com/42ef3359698ddcfbc144273baf2e3a28c4585852bb6b3654dd997ad80e5ffe42

**Additional server info**
Bungeecord

**Comment by FormallyMyles** [comment]
If it happens on 1.8, you should open this in ViaRewind. You should also provide a video to show the impact.
