### ISSUE TITLE
LOG ERROR

### ISSUE THREAD

**Issue by SheroxGG** [ViaVersion/ViaVersion#2202]
Hello guy! First thanks for your time and help. 
I wont give too much details as you dont need this for helping me. I have a modded server on 1.12.2 and obviously viaversion is ignoring them. But they are spamming all over my console. Id like to desactivate it. Thanks a lot.

>.... [07:54:33 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: Tropicraft
>.... [07:54:33 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: Tropicraft
>.... [07:54:33 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: Tropicraft
>.... [07:54:33 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: Tropicraft
>.... [07:54:33 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: Tropicraft
>.... [07:54:33 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: Tropicraft
>.... [07:54:33 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: Tropicraft
>.... [07:54:33 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: Tropicraft
>.... [07:54:33 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: Tropicraft
>.... [07:54:33 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: thebetweenlands
>.... [07:54:33 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: Tropicraft
>.... [07:54:33 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: thebetweenlands
>.... [07:54:33 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: Tropicraft
>.... [07:54:33 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: Tropicraft

**Comment by KennyTV** [comment]
Set `suppress-conversion-warnings` to false in the ViaVersion config.
