### ISSUE TITLE
Players invisible when using snapshot client 20w46a

### ISSUE THREAD

**Issue by ScriptJunkieMC** [ViaVersion/ViaVersion#2203]
Running a test with snapshot behind waterfall-20a46w. When i put viaversion on bungee/waterfall the players are invisible to others when using the snapshot 20w46a client. Removing viaversion and connecting to the server works just fine and players can see each other. However via is required for other servers as we all know and have come to love.

I also understand this is snapshot which is probably unsupported but figured i would throw this ticket out here anyway. 

**How can we reproduce it?**
1. Setup waterfall-20w46a and add viaversion (any above 3.2.0)
2. Configure snapshot server 20w46a using vanillacord from github.
3. Connect 2 players using snapshot client and they cant see each other no matter what server they are on.

My hub server is 1.16 and also produces the same results. If bungeecord has viaversion then snapshot clients just cant see anyone no matter the sub server version.

**Expected behaviour**
I expect to be able to see the other players. 

**Screenshots**
![invisible-players](https://user-images.githubusercontent.com/6124443/99609429-e287e480-29dd-11eb-89c2-8abf6c49e2df.PNG)

**ViaVersion Dump**
https://dump.viaversion.com/2ba60fc2eae227522d9aa0d4c94d41f2d91b9ba715ee614a7360f568280e5ca9
- my server is question is tcdev03 which is the snapshot server

**Additional server info**
Proxy is used to emulate network for players to be able to connect to different versions. 1.16 and snapshot.
waterfall-20w46a is used in this test case with above specs

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Unsupported setup.

**Comment by ScriptJunkieMC** [comment]
yet you roll out viaversion for 20w46a... how is it unsupported when clearly you support it?

**Comment by KennyTV** [comment]
Because you're not even using the ViaVersion 20w46a dev build (and ViaBackwards hasn't been pushed for that yet) 😛

**Comment by ScriptJunkieMC** [comment]
i did load that viaversion and same result as i noted bud

**Comment by KennyTV** [comment]
Then your Waterfall didn't account for meta changes or similar

**Comment by ScriptJunkieMC** [comment]
waterfall without via works though. How is that the same?

**Comment by ScriptJunkieMC** [comment]
Yeah did another test and get multiplayer.disconnect.incompatible when running the latest via-dev 20w46a. waterfall with 20w46a support and via on waterfall. Doesnt allow clients onto the snapshot server. but lets other clients work. very odd

**Comment by KennyTV** [comment]
Yeah sorry for the lack of explanation, but that is what I meant with "unsupported setup", see https://github.com/ViaVersion/ViaVersion/issues/2189#issuecomment-729150166 for reference.
