### ISSUE TITLE
Server crash after new players joined

### ISSUE THREAD

**Issue by Villmarksjenta** [ViaVersion/ViaVersion#2204]
**Describe the bug, provide any errors**

Error: https://hastebin.com/elerevasak.csharp
2 new players joined my server, and suddenly got kicked at the same time. After that they tried reconnecting quickly, and then the server crashed. 
**How can we reproduce it?**
An explanation on why it happened. A staff are suspicious if they tried hacking, or if something went wrong.

**Expected behaviour**
Not a server crash.

**ViaVersion Dump**
https://dump.viaversion.com/81627cc747dc55366c1948c960a61c14b7b1a4b0f249dc75407a826cd66a5d2c

**Additional server info**
I use proxy/Bungeecord, and have viaVersion, viaBackwards and viaRewind on almost all servers.

**Checklist**
- [ ] I have included a Viaversion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
Could you test the latest builds from ci.viaversion.com and then post this on ViaBackwards issue? 

Ensure you're only running ViaVersion on the backend (I'd doubt you're running it on both) + Are you able to say what kind of particles you're using?
