### ISSUE TITLE
Illusioner Disconnect

### ISSUE THREAD

**Issue by herobrick360** [ViaVersion/ViaVersion#2205]
Ok, I haven't written one of these things before but here it goes.

**Describe the bug, provide any errors**
Whenever I spawn a illusioner in Minecraft 1.12.2 or earlier, I get this error (On Console) User MinecrafterTime has disconnected, reason: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues

**How can we reproduce it?**
1. Log into server on 1.12.2 or lower
2. Spawn in Illusioner 
3. Get Disconnected!

**Expected behavior**
Nothing. The Illusioner should be coded in some way so it just shows as a villager in lower versions.

**Additional server info**
I use PaperMC (Vanilla > Bukkit > Spigot > Paper)

**Comment by DoctorMacc** [comment]
Can you please run `/viaversion dump` and provide the link here?
