### ISSUE TITLE
1.8.9 on 1.16.4 server

### ISSUE THREAD

**Issue by Magzypotato** [ViaVersion/ViaVersion#2207]
**Describe the bug, provide any errors**
I host a 1.16.4 bungeecord network. Me and my friends want to play on 1.8.9 since its just the best for bedwars and other mini-games. When i joined i got this message on my screen https://imgur.com/a/frv4yz4. This is also what i see in the server it doesnt work https://paste.gg/p/anonymous/19cf647e0ced4d12ba48d2c3277b4d58 . BTW i have to say that this does work in all the other server in my network, its just not working in this one.

**Expected behaviour**
Simply join the 1.16.4 with 1.8.9 minecraft version without any problems.

**ViaVersion Dump**
https://dump.viaversion.com/d0616fdd9af56ddb99a77f90eddb3c90313da2f11d1cf22f0aafc67cd910cb8b

**Additional server info**
I use Bungeecord. I use PaperMC 1.16.4 to host it. This is a photo of all my plugins inside the bungeecord folder https://imgur.com/a/UFMySbF . This is a photo of all my plugins inside the server i didnt manage to join https://imgur.com/a/pQ8zEFw .

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
Please post this to the viarewind GitHub page, otherwise it may be worth testing with no other plugins to check if it could be a conflict.
