### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by gyu6378** [ViaVersion/ViaVersion#2211]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?

**How can we reproduce it?**
1. Login on 1.12'
3. The '....' is displayed wrong

**Expected behaviour**

**Screenshots**
https://imgur.com/aLRtuZP

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.

**Additional server info**
paper spigot 1.13.2 not bungee server

**Checklist**
- [ ] I have included a Viaversion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Follow the issue template.
