### ISSUE TITLE
All users are kicked from the server when certain users enter

### ISSUE THREAD

**Issue by david160596** [ViaVersion/ViaVersion#2212]
**Describe the bug, provide any errors**
There are users who when trying to connect to the server all users are kicked. If this user who gives problems, reconnects, kick everyone again. Users are tired of being continuously kicked.
https://paste.gg/p/anonymous/5d14189cd58445a1a1666cac4fbb1fdf

**How can we reproduce it?**
1. Certain users connect to the server.
2. Everyone is kicked.

**ViaVersion Dump**
- Viaversion 3.2.0

**Additional server info**
We use waterfall #384 and spigot #288.

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
Please provide /viaversion dump, it is missing from your report. Also try without "oreocore"

**Comment by david160596** [comment]
The problem was indeed with OreoCore.

Thanks for the help!
