### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by SytheMC** [ViaVersion/ViaVersion#2215]
Hello there!
Recently, I changed my server jar to 1.14.4, installed ViaVersion, ViaBackwards, and ViaRewind.
When I join the game on 1.14.4, I join and everything is good. Though, if I join on 1.8.9, it doesn't work.
I opened a ticket (I host my server on pebblehost.com) And they debugged the issue and said to contact the author/developer.
Please reply with what information I would have to supply you with.
Thanks!

**Comment by DoctorMacc** [comment]
You should follow the issue template provided to you (open a new issue if you want to see an example) - some of the checkboxes may help you solve your issue. :)
