### ISSUE TITLE
Kick in chunk remap 1.13.2 -> 1.12.2 (after editing the world with MCEdit)

### ISSUE THREAD

**Issue by Govindass** [ViaVersion/ViaVersion#2216]
**Describe the bug, provide any errors**
I am kicked from the server with an error whenever specific blocks are broken (the ground that opens an area below) after having edited the world with MCEdit, it works fine on 1.12.2 (base server version), but if using 1.16.3, it kicks. Error: https://pastebin.com/raw/4UazX4xf
**How can we reproduce it?**
1. Edit the world with MCEdit, trimming chunks
2. explode the ground with explosion such as TNT, with a cave below it
3. kick
(not sure if reproducible, just happened on my server)

**Expected behaviour**
To not kick.

**Screenshots**
None

**ViaVersion Dump**
https://dump.viaversion.com/57a1ae936a595973b8cf85232616d4de0b7bc1a7ada35e9d50aea5ad8d64c8b3
**Additional server info**
FlameCord 1.16.4, 1.12.2 Paper (viaversion only on paper side)
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
We do not support external world editing tools, since they often break normal chunk formats (we also don't support FlameCord, but that's probably unrelated).

**Comment by Govindass** [comment]
> 
> 
> We do not support external world editing tools, since they often break normal chunk formats (we also don't support FlameCord, but that's probably unrelated).

I just got the same error again and getting kicked on a normal non-mcedit world.

**Comment by Govindass** [comment]
downgrading ViaVersion to latest spigotmc release instead of a dev build fixed the issue
