### ISSUE TITLE
1.16.4 server crash

### ISSUE THREAD

**Issue by DominatorRUS** [ViaVersion/ViaVersion#2217]
Tuinity version: git-Tuinity-"8056d13" (MC: 1.16.4)
ViaVersion: https://ci.viaversion.com/job/ViaVersion/487/
ViaBackwards: https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/196/

https://pastebin.com/ebBwwF3n

**Comment by KennyTV** [comment]
Follow the issue template.
