### ISSUE TITLE
Paper 1.16.4 recipe book is empty on 1.12.2 client

### ISSUE THREAD

**Issue by BredyAK** [ViaVersion/ViaVersion#2219]
**Describe the bug, provide any errors**
No errors. When you use 1.12.2 Vanilla client join a 1.16.4 paper server, you'll find your recipe book empty.

**How can we reproduce it?**
1. prepare a 1.12.2 Vanilla client and a 1.16.4 paper server (the version I'm using is the latest 298 build)
2. join your server and open your inventory, clicks the green book button (recipe book)
3. then you find the book is always empty

**Expected behaviour**
The recipes should load correctly.

**Screenshots**
![](https://i.ibb.co/gFdFXLg/Snipaste-2020-12-01-18-17-28.jpg)

**ViaVersion Dump**
- https://dump.viaversion.com/dd4e8595e7b3c8e968039335f03b8c443a315c436a6207c659c50e082c1f1083

**Additional server info**
The situation I've tested:
- Install ViaVersion and ViaBackwards only on BungeeCord
- Install ViaVersion and ViaBackwards only on Paper
Both of them have the same result, the reciptes isn't correctly loaded.
Tested ViaVersion versions: 3.2.0, 3.2.1-SNAPSHOT, 3.3.0-20w48a
Tested ViaBackwards versions: 3.2.0, 3.2.1-SNAPSHOT, 3.3.0-20w45a

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Due to major changes between recipes from 1.12 to 1.13 and it involving a lot of caching and processing to work, this is a won't-fix.
