### ISSUE TITLE
A lot of via versions errors in the console. Server version 1.8.8

### ISSUE THREAD

**Issue by shadowright123** [ViaVersion/ViaVersion#2221]
via version dump: https://dump.viaversion.com/02275353c94bef16203ad2d51b723eb10626efb30f78147f6e0dd40f3bda2cd4
My server version is 1.8.8

Console log:
https://hastebin.com/ucuduwahox.yaml
Theres always a lot of via version errors in the console, and players keep disconnecting randomly from the server idk if its cause of via versions.

**Comment by DoctorMacc** [comment]
Have you tried a build from https://ci.viaversion.com/ ?
