### ISSUE TITLE
1.7-1.15.2 Aegis proxy with ViaVersion Error

### ISSUE THREAD

**Issue by iskrentsbg** [ViaVersion/ViaVersion#2224]
Error: https://pastebin.com/QMM7ikeu

**How can we reproduce it?**
1. Login on 1.16'
2. Click on 'The survival 1.16'
3. First it displays "Loading Terrain and then it kicks me with "Disconnected", sometimes it let me join the servers but I can't do nothing and I ge the "Timed out" message!

**Expected behaviour**
I just joined the server

**Screenshots**
Disconnected: https://prnt.sc/vwvhie
Loading Terrain: https://prnt.sc/vwvhg6
Timed out: https://prnt.sc/vwvh9n

**ViaVersion Dump**
- Type /viaversion dump, and put the link here: https://dump.viaversion.com/eec7830583dbdad51288e375bb9521dbd769af44fc17862e35a71b861bfa5fae

**Additional server info**
BungeeCord (Aegis) 1.7-1.15.2:
Plugins: https://prnt.sc/vwvi4h

**Comment by KennyTV** [comment]
Aegis Bungee is not supported, especially with something on your setup hiding stacktraces. Try with a standard Bungee/Waterfall or moving Via to your backend servers.

**Comment by iskrentsbg** [comment]
If I use Bungee or Waterfall it kick players who join on 1.7.10 with Proxy [Lost Connection]

**Comment by Blocksnmore** [comment]
> If I use Bungee or Waterfall it kick players who join on 1.7.10 with Proxy [Lost Connection]

Use travertine for 1.7 support https://papermc.io/downloads

**Comment by iskrentsbg** [comment]
I tried Travertine too, it disconect my 1.7.10 players. Only the 1.7-1.15.2 doesn't disconnect 1.7 players... But I need 1.16 support.

**Comment by Blocksnmore** [comment]
Have you tried moving via to the backend?

**Comment by iskrentsbg** [comment]
The Survival is 1.16 Version, with ViaRewind (to have support from 1.7-1.16) in the Survival. I added ViaVersion to the bungeecord, to add the Aegis 1.16.4 support, I also added ViaVersion in survival, because when I add ViaRewind, it has some glitches with lillypads, ladders and etc. and I have to add ViaRewindLegacySupport (which is only spigot plugin). And I have ViaVersion in BungeeCord and in Survival too. The problematic server is kitmap (1.7.10) because if I add Bungee 1.7-1.16.2 it randomly disconnects players with [Proxy] Lost connection to the server. I tried FlameCord, Waterfall, Travertine and many more I tried even Aegis fork 1.7-1.16.4

**Comment by Blocksnmore** [comment]
Then thats probably your issue, you don’t want to mix via* on the proxy and backend only one of the 2

**Comment by iskrentsbg** [comment]
I removed ViaVersion from survival. And when I join ot 1.16.3 it displays me "Outdated Client! Please use 1.16.3"

**Comment by iskrentsbg** [comment]
If I don't have ViaVersion in survival and in proxy i can't join survival (bungee is outdated)

**Comment by Blocksnmore** [comment]
Then update bungee lmao
