### ISSUE TITLE
logs out of the server when entering the bedwars arena

### ISSUE THREAD

**Issue by vobshestve** [ViaVersion/ViaVersion#2225]
**Describe the bug, provide any errors**
crashes when trying to connect to Created bedwars arena.
Error: lost connection to the server
plugin bedwars: Screaming Bedwars

**How can we reproduce it?**
1. login on 1.8.*
2. create an arena
2. enter command: bw join arena
3. The Error: lost connection to the server is displayed wrong

**Expected behaviour**
Should have just launched into the arena

**Screenshots**
https://i.imgur.com/vay6v8q.png

**ViaVersion Dump**
https://dump.viaversion.com/ad459241bc71d14338a32d7e3d6807b352e06d04471f4418a336ff211418156b

**Additional server info**
bungeecord, papper spigot 1.12.2, version papper 16.18

**Checklist**
- [✓] I have included a Viaversion dump
- [✕] If applicable, I have included a paste (not a screenshot) of the error
- [✓] I have tried a build from https://ci.viaversion.com/ and the issue still persists
p.s. Sorry for mistakes. I am using translator

**Comment by Xernium** [comment]
Please attach both server and proxy (bungee) logs or we can't help.

**Comment by vobshestve** [comment]
> Please attach both server and proxy (bungee) logs or we can't help.

[latest.log](https://github.com/ViaVersion/ViaVersion/files/5653399/latest.log)

[proxy.log](https://github.com/ViaVersion/ViaVersion/files/5653415/proxy.log)

**Comment by Xernium** [comment]
First of all. ProtocolSupportBungee is clearly malfunctioning, and that's normal given that its currently unsupported. 
Secondly, you have Via installed on both bungee and spigot. Thats unsupported. Pick one, but not both. I recommend keeping it on spigot only. Please then also tend to the multiple dozen errors and warnings on your spigot server. At this point I can't even reasonably tell which one of these malfunctioning plugins could be influencing it.
