### ISSUE TITLE
1.16.4 Paper GUI color codes and json text's hover event "show_text" not work on 1.12.2 client

### ISSUE THREAD

**Issue by BredyAK** [ViaVersion/ViaVersion#2227]
**Describe the bug, provide any errors**
Two bugs:
1. On Paper 1.16.4 server, if you have any custom GUI(like server menus, etc.), the color codes on title are not displayed on 1.12.2 client. It looks like all color codes are just removed, and only texts are displayed.
2. Also tested on Paper 1.16.4 server with 1.12.2 client, json hoverable texts with "show_text" option, are not displayed on 1.12.2 client. I've found this happens on books, chats.

**How can we reproduce it?**
1. Prepare a 1.16.4 Paper server, and join game with 1.12.2 client.
2. Open a menu with colored title. Like the server menu with a custom title "§6§lServer §1§lMenu".

**Expected behaviour**
The title should keep its origin color codes. But it only displays texts, with no color codes.

**ViaVersion Dump**
https://dump.viaversion.com/f481b7a51f46826312a58c41cf8a2f4bb106e09b440b441a12e120bf6e93cb07

**Additional server info**
I install ViaVersion and ViaBackwards only on my BungeeCord proxy. Version info:
ViaVersion: 3.2.0
ViaBackwards: 3.2.0
Paper: build 318

**Checklist**
- [x] I have included a Viaversion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Already reported on the ViaBackwards issue tracker.
