### ISSUE TITLE
Error when sending a TextComponent with a custom plugin

### ISSUE THREAD

**Issue by jusjus112** [ViaVersion/ViaVersion#2228]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?
Error: https://paste.gg/p/anonymous/f672852a44164bdcb555b00134c58858
Code: https://paste.gg/p/anonymous/ba6e6763553b49e4b6f5f8b764e9d613

**How can we reproduce it?**
N/A

**Expected behaviour**
A message in chat that replaces the default chat message with a hover info box attached to it.

**Screenshots**
N/A

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/69f09e1ff5c5782341e2fba3460ef40ce699e04a5d0eddb38a292349ac0320c8

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
- Paper 1.12.2
- ViaVersion
- Custom Plugin (Provided With Code)

**Checklist**
- [x] I have included a Viaversion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
You can't do `baseComponent.addExtra(baseComponent);`
