### ISSUE TITLE
Packet channels

### ISSUE THREAD

**Issue by leytilera** [ViaVersion/ViaVersion#2230]
**Describe the bug, provide any errors**
I actually wouldn't call it an error, but is there a way to disable this "ignoring incoming plugin message" messages in the log? They are spamming the console full and increasing the size of the log when playing with modded clients.

**How can we reproduce it?**
1. Install Viaversion and Viabackwards on the server
2. Join with a modded 1.12.2 client with ImmersiveEngineering installed on the server

**Expected behaviour**
A way to disable the messages

**Screenshots**
![packets](https://user-images.githubusercontent.com/16227704/101525246-54bf6980-398b-11eb-96a1-9488fb372663.PNG)

**ViaVersion Dump**
https://dump.viaversion.com/fbfd72bfd886bea73866844deaec6b37d3c369436ab6ba1173ada4ff91757a9c

**Checklist**
- [X ] I have included a Viaversion dump
- [X ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Enable `suppress-conversion-warnings` in the ViaVersion config, modern servers require plugin channel names to be in a namespaced key format.
