### ISSUE TITLE
Console spam Ignoring incoming plugin channel

### ISSUE THREAD

**Issue by Sneakometer** [ViaVersion/ViaVersion#2231]
Hello,
i'm running paper servers with viaversion on 1.8.

Viaversion prints the following message 6-7 times everytime someone joins with a farbic client:
`[ViaVersion] Ignoring incoming plugin channel register of 'fabric-screen-handler-api-v1:open_screen', as it is longer than 32 characters
`
This results in ridiculous console spam on lobby servers where many people join and disconnect in small periods.

I'm using the (currently latest) version 3.2.1 snapshot of VV.
I tried toggling the "ignore-long-1_16-channel-names" in config but the console spam still persists.

How can i disable this message?
Thanks for help.

**Comment by FormallyMyles** [comment]
Enable suppress-conversion-warnings in the ViaVersion config

**Comment by Sneakometer** [comment]
That's easy, thank you!

Also, I read the entire config documentation (https://docs.viaversion.com/display/VIAVERSION/Configuration)
but there is no such option.
It would be nice to add it there so people like me don't create a github issue.

**Comment by FormallyMyles** [comment]
> That's easy, thank you!
> 
> Also, I read the entire config documentation (https://docs.viaversion.com/display/VIAVERSION/Configuration)
> but there is no such option.
> It would be nice to add it there so people like me don't create a github issue.

I'll get that looked into thanks, it got changed a while back and the documentation was never fixed
