### ISSUE TITLE
[Bug] Console Spam

### ISSUE THREAD

**Issue by medontknow** [ViaVersion/ViaVersion#2238]
**Describe the bug, provide any errors**
An [error message](https://pastebin.com/i0j0f8zG) was spammed in the console when a new player joined the game.

**How can we reproduce it?**
1. Let a new player join the game.
2. Wait for it to spam the console I guess?

**Expected behaviour**
The player will be able to join normally without any errors.

**ViaVersion Dump**
https://dump.viaversion.com/baac1a8f90a3b9c77d543d1d01001a1bfa1dfddd87d387f8b88e71eb3e653a5c

**Additional server info**
The server uses Paper as its server software and Waterfall as its proxy. 

Plugins list:
AntiVPN, AuthMe, BKCommonLib, BungeeGuard, BungeeTabListPlus, DiscordSRV, Essentials, eZProtector, HolographicDisplays, HolographicPlaceholders, LightCleaner, LuckPerms, LuckPermsChat, Multiverse-Core, PlaceholderAPI, ProtocolLib, QuickBoard*, ServerSelectorX, SimplePortals, Vault, ViaBackwards, ViaRewind, ViaVersion, VoidSpawn, WorldEdit, WorldGuard

**Checklist**
- [ /] I have included a Viaversion dump
- [ /] If applicable, I have included a paste (not a screenshot) of the error
- [x ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Update ViaRewind.
