### ISSUE TITLE
1.8 Client >> Paper(MC) 1.16.4 Server | Bug-Report | Error

### ISSUE THREAD

**Issue by TheFruxz** [ViaVersion/ViaVersion#2239]
**How can we reproduce it?**
1. Login on with 1.8.9 OptiFine on PaperMC 1.16.4 Server

**Expected behaviour**
Nothing happened, random exception

**Exception Stacktrace**
[WARNING] .... [ViaVersion] ERROR IN Protocol1_11_1To1_12 IN REMAP OF TITLE (0x47)

[WARNING] .... io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues

[WARNING] .... {Source 0: nl.matsv.viabackwards.protocol.protocol1_11_1to1_12.Protocol1_11_1To1_12$1 (Anonymous)}

[WARNING] .... Actual Error:

[WARNING] .... at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)

[WARNING] .... at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)

[WARNING] .... at kernitus.plugin.OldCombatMechanics.utilities.packet.PacketInjector.write(PacketInjector.java:176)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)

[WARNING] .... at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)

[WARNING] .... at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)

[WARNING] .... at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)

[WARNING] .... at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:303)

[WARNING] .... at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)

[WARNING] .... at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)

[WARNING] .... at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)

[WARNING] .... at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)

[WARNING] .... at java.lang.Thread.run(Thread.java:748)

[WARNING] .... Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues

[WARNING] .... {Source 0: nl.matsv.viabackwards.protocol.protocol1_11_1to1_12.Protocol1_11_1To1_12$1 (Anonymous)}

[WARNING] .... Actual Error:

[WARNING] .... Caused by: java.lang.IllegalStateException: zip file closed

[WARNING] .... at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)

[WARNING] .... at java.util.zip.ZipFile.getEntry(ZipFile.java:315)

[WARNING] .... at java.util.jar.JarFile.getEntry(JarFile.java:240)

[WARNING] .... at java.util.jar.JarFile.getJarEntry(JarFile.java:223)

[WARNING] .... at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:144)

[WARNING] .... at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216)

[WARNING] .... at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:122)

[WARNING] .... at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111)

[WARNING] .... at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

[WARNING] .... at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

[WARNING] .... at nl.matsv.viabackwards.protocol.protocol1_11_1to1_12.Protocol1_11_1To1_12$1.lambda$registerMap$0(Protocol1_11_1To1_12.java:54)

[WARNING] .... at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)

[WARNING] .... at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)

[WARNING] .... at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)

[WARNING] .... at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:449)

[WARNING] .... at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435)

[WARNING] .... at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75)

[WARNING] .... at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404)

[WARNING] .... at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:379)

[WARNING] .... at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)

[WARNING] .... at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)

[WARNING] .... at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)

[WARNING] .... at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)

[WARNING] .... at kernitus.plugin.OldCombatMechanics.utilities.packet.PacketInjector.write(PacketInjector.java:176)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)

[WARNING] .... at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)

[WARNING] .... at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)

[WARNING] .... at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)

[WARNING] .... at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:303)

[WARNING] .... at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)

[WARNING] .... at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)

[WARNING] .... at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)

[WARNING] .... at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)

[WARNING] .... at java.lang.Thread.run(Thread.java:748)

[WARNING] .... io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues

[WARNING] .... {Source 0: nl.matsv.viabackwards.protocol.protocol1_11_1to1_12.Protocol1_11_1To1_12$1 (Anonymous)}

[WARNING] .... Actual Error:

[WARNING] .... at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)

[WARNING] .... at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)

[WARNING] .... at kernitus.plugin.OldCombatMechanics.utilities.packet.PacketInjector.write(PacketInjector.java:176)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)

[WARNING] .... at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)

[WARNING] .... at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)

[WARNING] .... at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)

[WARNING] .... at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:303)

[WARNING] .... at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)

[WARNING] .... at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)

[WARNING] .... at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)

[WARNING] .... at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)

[WARNING] .... at java.lang.Thread.run(Thread.java:748)

[WARNING] .... Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues

[WARNING] .... {Source 0: nl.matsv.viabackwards.protocol.protocol1_11_1to1_12.Protocol1_11_1To1_12$1 (Anonymous)}

[WARNING] .... Actual Error:

[WARNING] .... Caused by: java.lang.IllegalStateException: zip file closed

[WARNING] .... at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)

[WARNING] .... at java.util.zip.ZipFile.getEntry(ZipFile.java:315)

[WARNING] .... at java.util.jar.JarFile.getEntry(JarFile.java:240)

[WARNING] .... at java.util.jar.JarFile.getJarEntry(JarFile.java:223)

[WARNING] .... at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:144)

[WARNING] .... at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216)

[WARNING] .... at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:122)

[WARNING] .... at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111)

[WARNING] .... at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

[WARNING] .... at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

[WARNING] .... at nl.matsv.viabackwards.protocol.protocol1_11_1to1_12.Protocol1_11_1To1_12$1.lambda$registerMap$0(Protocol1_11_1To1_12.java:54)

[WARNING] .... at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)

[WARNING] .... at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)

[WARNING] .... at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)

[WARNING] .... at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:449)

[WARNING] .... at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435)

[WARNING] .... at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75)

[WARNING] .... at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404)

[WARNING] .... at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:379)

[WARNING] .... at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)

[WARNING] .... at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)

[WARNING] .... at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)

[WARNING] .... at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)

[WARNING] .... at kernitus.plugin.OldCombatMechanics.utilities.packet.PacketInjector.write(PacketInjector.java:176)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)

[WARNING] .... at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)

[WARNING] .... at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)

[WARNING] .... at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)

[WARNING] .... at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)

[WARNING] .... at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:303)

[WARNING] .... at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)

[WARNING] .... at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)

[WARNING] .... at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)

[WARNING] .... at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)

[WARNING] .... at java.lang.Thread.run(Thread.java:748)

[INFO] .... Fruxz lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues

{Source 0: nl.matsv.viabackwards.protocol.protocol1_11_1to1_12.Protocol1_11_1To1_12$1 (Anonymous)}

Actual Error:

[INFO] .... Fruxz left the game

**ViaVersion Dump**
- https://dump.viaversion.com/2b80d3ebf72f27b9b6c408b4121b3dc7846065f99cbfc62ead4cf5b8f06659cb

**Additional server info**
- NoProxy
- PaperMC 1.16.4 Server

**Comment by Jo0001** [comment]
Don't mix versions
https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/jar/target/ViaVersion-3.2.1-SNAPSHOT.jar
https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/lastSuccessfulBuild/artifact/all/target/ViaBackwards-3.2.1-SNAPSHOT.jar
https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/lastSuccessfulBuild/artifact/all/target/ViaRewind-1.5.3.jar

**Comment by TheFruxz** [comment]
> Don't mix versions.

ViaVersion 3.2.1
ViaBackwards 3.2.1
ViaRewind _**1.5.3**_ xD

**Comment by TheFruxz** [comment]
Sorry, but in my attachments it is very clear that I have already installed the latest and therefore your listed version of all the plugins you just listed so nicely.

**Comment by mygizli04** [comment]
According to your dump you're using viaversion and viabackwards 3.2.0

**Comment by FormallyMyles** [comment]
This is due to a corrupt plugin, see links above
