### ISSUE TITLE
Java 11 and 1.8.8 error

### ISSUE THREAD

**Issue by FruitLabCBR** [ViaVersion/ViaVersion#2240]
**Describe the bug, provide any errors**
I switched from Java 8 to Java 11. Because Paper 1.8.8 doesnt Support Java 11 i need to disable "use-native-transport" in the server proerpties.. otherwhise the console is getting spammed with 150MB per second of errors..

I made a 1.8.8 Paper Server and for some reason viaversion is not working on my server.
https://dump.viaversion.com/ee5744b385f924e99287c3dc1a26379d0b0d7a47662882b28ecb6c0e78a5d77d
it says server protocol is -1 and enable-protocol is null

**Additional server info**
Its a Paper 1.8.8 Server with Viaversion, Luckperms, WorldEdit and Worldguard

**Checklist**
- [X] I have included a Viaversion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by Jo0001** [comment]
Using latest Via works fine for me with java 11.0.9
https://dump.viaversion.com/35f2c046d2fb09841ac7e282b81fdbb66c2f6b2a6681488f3898a26b5a32d734

**Comment by FruitLabCBR** [comment]
Can be deleted.. for some reason its working now..
