### ISSUE TITLE
MissingBlock-Block Particles

### ISSUE THREAD

**Issue by TheFruxz** [ViaVersion/ViaVersion#2242]
**Describe the bug, provide any errors**
When a player hits to hard the ground, particles of the block are showing on the bottom. These particles (for e.g. 1.8 Client on 1.16 Blocks) are bugged, like a bug block! 

**How can we reproduce it?**
Fall to hard at an 1.16 block via 1.8 client

**Expected behaviour**
Nice block particles, from the for the 1.8 compatible block

**Additional server info**
PaperMC 1.16 Server

**Comment by KennyTV** [comment]
Follow the issue template, also please try to rephrase and expand your description.
