### ISSUE TITLE
Vehicle quit issue 1.12 Server, 1.16 CLient

### ISSUE THREAD

**Issue by Bruce0203** [ViaVersion/ViaVersion#2243]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?

**How can we reproduce it?**
1. Login on 1.16.4'
2. Shift click with pig riding. (pig was no saddle, and has been passenger with entity.setPassenger(entity))
3. And i cancelled vehicle quit event. but player can get out of pig.

**Expected behaviour**
maybe can't cognizance vehicle quit event. or can't cancel vehicle quit event
and can't ride pig again a re-spawned pig with same method. no ride happened

**Screenshots**

**ViaVersion Dump**
https://dump.viaversion.com/e4083b7d3aea8d4fae0f425b515e575df695c51615dc8549bfce23cf6855b70d

**Additional server info**
PaperSpigot 1.12.2

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Seems to be a Vanilla client issue, sadly https://bugs.mojang.com/browse/MC-202202
