### ISSUE TITLE
Bug Report // 1.12.2

### ISSUE THREAD

**Issue by Kucatowsky** [ViaVersion/ViaVersion#2244]
**Describe the bug, provide any errors**
https://paste.gg/p/anonymous/36ab6e2ce3ab42409c65cb327a4a4ab0

**How can we reproduce it?**
Repair a plugin...

**Expected behaviour**
That's the log in the console, i did nothing.

**Screenshots**
https://paste.gg/p/anonymous/36ab6e2ce3ab42409c65cb327a4a4ab0
This logs lagging my server.

**ViaVersion Dump**
https://dump.viaversion.com/9b50928750fa14ec128a754cb83e41731e3272fea661036bef4428579bd8a0e2

**Additional server info**
Paper Spigot 1.12.2 // 8GB Ram

**Checklist**
- [x] I have included a Viaversion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Someone's sending invalid ping packets.
