### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by Aryajon86** [ViaVersion/ViaVersion#2246]
I was logging on to Minecraft on 1.8.9 and joined a server called fluxpvp. It let me in for a second then kicked me and gave me this 
error{String, data: [], Source 0:
de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.playerpackets
$22 (anonymous), packet id: 4}
![Screenshot 2020-12-13 205213](https://user-images.githubusercontent.com/75959273/102031929-75216680-3d85-11eb-9ed0-af7d8dd02ad2.png)

**Comment by KennyTV** [comment]
Follow the issue template and report this on the ViaRewind tracker.
