### ISSUE TITLE
Source 0: us.myles.ViaVersion.protocols.base.BaseProtocol1_7$1 (Anonymous), Packet ID: 0}

### ISSUE THREAD

**Issue by Kucatowsky** [ViaVersion/ViaVersion#2248]
**Describe the bug, provide any errors**
https://paste.gg/p/anonymous/ab500c2f8d2b4f948a15f668488c3498
Console error
Nobody was on the server so nobody sends the bad packets?

**How can we reproduce it?**
Repair the plugin or tell me how to remove this error from the console

**Expected behaviour**
This errors lagging my server.

**Screenshots**
No screenshots.

**ViaVersion Dump**
https://dump.viaversion.com/30ebe398cdeccc0789e3fdb27822737e622dc7cd3f13efcc9265c098b52bed05

**Additional server info**
Paper 1.12.2 

**Checklist**
- [X] I have included a Viaversion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
This will be a service like voting sending bad data.
