### ISSUE TITLE
Client leaves from server when dust particle occurs in 20w49a-20w51a / Wrong dust particle color shown when using 1.13+ client on 1.12 based server

### ISSUE THREAD

**Issue by LemonCaramel** [ViaVersion/ViaVersion#2249]
**How can we reproduce it?**
1. Login on 20w49a~20w51a client
2. Generate a (1.12)redDust, (1.13+)dust particle
3. You will be able to see the problem.

---

**Screenshots**

> Client leaves from server when dust particle occurs in 20w49a-20w51a

**Left 1.16.4 | Right 20w51a**

![particle-kick](https://user-images.githubusercontent.com/45729082/102460428-4dcee000-408a-11eb-8edb-b9a166890f02.gif)
 - The above picture is what happens to 20w49a+ clients when a particle is generated on a 1.16.4 based server.
 _I used Jenkins [#404(ViaVersion-DEV)](https://ci.viaversion.com/job/ViaVersion-DEV/404/) plugin_ 

![particle-edit](https://user-images.githubusercontent.com/45729082/102461456-bb2f4080-408b-11eb-8b3e-afb99457018d.gif)
 - The above picture is when I changed the Particle RGB value from double to float. (1.16.4 based server)
 - [Comment Link(It seems you haven't seen this comment)](https://github.com/ViaVersion/ViaVersion/commit/459e3e68b843cba7904e55dd74301b5d57877cab#r45055713) - _Is the `minecraft:dust_color_transition` written as doubles?_

![image](https://user-images.githubusercontent.com/45729082/102463951-16166700-408f-11eb-9a7d-a29f960d5614.png)
 - [unchanged - still float](https://wiki.vg/Pre-release_protocol)

> Wrong dust particle color shown when using 1.13+ client on 1.12 based server

**Top Left 1.16.4 | Top Right 20w51a**
**Bottom Left 1.12.2 | Bottom Right 1.13.2**

![particle-wrong-color](https://user-images.githubusercontent.com/45729082/102462662-6bea0f80-408d-11eb-92d5-e2fc6c6d24e4.gif)
 - I can't find a problem when there is only one particle (it looks the same color on all clients), but it happens when multiple particles occur.
 _I don't know if it's a bug or not because 1.12 clients and 1.13 processing methods are different._
---

**ViaVersion Dump**
https://dump.viaversion.com/d76e1b4c4e767278d5e799fae53d61892c66cc977d56543fd128d56216d3ca43

**Additional server info**
 - I used BungeeCord for testing, but the same problem also occurs in Paper and Spigot.

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Wiki.vg often does not update a lot of the under-the-hood changes, including the particle ones. A quick comparison of 1.16 code of DustParticleOptions https://i.imgur.com/eVRHVxS.png with the 1.17 equivalent https://i.imgur.com/aXdNaH5.png shows the change. But obviously *something* is wrong, I'll see what exactly that might be 😛

**Comment by KennyTV** [comment]
Riiight, so this is actually a Vanilla bug; they write as doubles, but read as floats... I'll keep it as is, until either writing or reading is changed again by Mojang.

**Comment by KennyTV** [comment]
https://bugs.mojang.com/browse/MC-208780

**Comment by LemonCaramel** [comment]
> Riiight, so this is actually a Vanilla bug; they write as doubles, but read as floats... I'll keep it as is, until either writing or reading is changed again by Mojang.

Thank you for your hard work!

+Is it impossible to solve the RGB problem that occurs when there are multiple dust Particles? _(I think this problem only occurs on servers below 1.12)_

**Comment by KennyTV** [comment]
Iirc that's just how the different client versions handle it (but we are also unlikely to put more time into such legacy server issues).

**Comment by LemonCaramel** [comment]
The same problem occurred in 21w03a. I think it's right to send the double value, not float.

I tried to reopen the issue, but I write it in the comments because I think I am giving you a hard time.

**Comment by KennyTV** [comment]
Yeah they fixed the inconsistency in 21w03, thanks for noting that. I overlooked your pr and pushed the fix already, sorry for that tho 😅
