### ISSUE TITLE
Skin layer not displayed normally on 20w51a client

### ISSUE THREAD

**Issue by LemonCaramel** [ViaVersion/ViaVersion#2250]
**How can we reproduce it?**
1. Login on 20w51a client (1.12.2, 1.16.4 based server)
2. Look at the other player.
3. You will be able to see the problem.

---

**Screenshots**

**Top Left 1.16.4 | Top Right 20w51a**
**Bottom Left 1.12.2 | Bottom Right 1.13.2**

![skin_layer](https://user-images.githubusercontent.com/45729082/102466187-064c5200-4092-11eb-9750-857aeaeacfff.gif)
- The skin layer is not updated on the 1.17 snapshot client.
---

**ViaVersion Dump**
 - https://dump.viaversion.com/d76e1b4c4e767278d5e799fae53d61892c66cc977d56543fd128d56216d3ca43

**Additional server info**
 - I used BungeeCord for testing, but the same problem also occurs in Paper and Spigot.

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Does this also happen on a 1.16 server with Via on the backend, not the proxy?

**Comment by LemonCaramel** [comment]
Yes, same thing happens on backend server (Paper)
![image](https://user-images.githubusercontent.com/45729082/102467053-2b8d9000-4093-11eb-8202-e64c6538cad3.png)

**Comment by LemonCaramel** [comment]
> Does this also happen on a 1.16 server with Via on the backend, not the proxy?

**Comment by LemonCaramel** [comment]
oh my mistake
