### ISSUE TITLE
ViaVersion continuously throwing long warnings in the server console every few minutes.

### ISSUE THREAD

**Issue by aBoredDev** [ViaVersion/ViaVersion#2253]
**Describe the bug, provide any errors**
ViaVersion throwing long warnings in the server console.  Identical warnings continue to be thrown every couple minutes.
Stacktrace: [https://paste.gg/p/anonymous/58cb5cd75ff143babf5c876f5bf7e242](https://paste.gg/p/anonymous/58cb5cd75ff143babf5c876f5bf7e242)

**How can we reproduce it?**
1. Start a 1.16.4 Paper server, running the most recent build of viaversion
2. Wait a couple minutes
3. Profit

**Expected behaviour**
No constant warnings, obviously

**Screenshots**

**ViaVersion Dump**
[https://dump.viaversion.com/989800cd37d949e3a7474361b39dd8f3c1af5ae68c818f233bcdace9348b1e63](https://dump.viaversion.com/989800cd37d949e3a7474361b39dd8f3c1af5ae68c818f233bcdace9348b1e63)

**Additional server info**
Paper build 323 (MC 1.16.4) - latest version as of Dec 17
Running a GeyserMC proxy (on a separate machine)
Plugins:
AdminGUI-1.4.5
ClearLag
HolographicDisplays
CommandPanels 3.14.2.4
EssentialsX and EssentialsXChat 2.19.0-dev+24-f320705 (latest version as of Dec 17)
DiscordSRV 1.21.0
Floodgate
SuperVanish 6.2.0
ProtocolLib
OpenInv
LuckPerms 5.2.31
WorldEdit 7.2.0
WorldGuard 7.0.4
WorldGuardExtraFlags
GriefPrevention

**Checklist**
- [Y] I have included a Viaversion dump
- [Y] If applicable, I have included a paste (not a screenshot) of the error
- [Y] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Someone is sending bad packets/pings to your server.
