### ISSUE TITLE
Client Kick when connecting with a 1.8.x client on 1.12.2

### ISSUE THREAD

**Issue by Chappy202** [ViaVersion/ViaVersion#2255]
**Describe the bug, provide any errors**
https://srcb.in/NrTzmMT7oN - Tested version 3.2.0 and everything works fine on that. Version 3.2.1 and above is throwing this error.

**How can we reproduce it?**
1. Create a 1.12.2 serverion running Viaversion 3.2.1 and above. (Possibly also need to install viarewind, and viabackwards)
2. Attempt to join the server with a 1.8.9 client.
3. The server should crash.

**Expected behaviour**
The 1.8.x clients should be able to connect like any other version.

**Screenshots**
https://i.imgur.com/aqEunmP.png

**ViaVersion Dump**
https://dump.viaversion.com/91ab29464435fe4ed108b9292b83e0486d79cbf3ae42e5b816b0402af2b58452

**Additional server info**
We use Flamecord 1.4.6 for our proxy.
Running Paperspigot 1.12.2 on the affected server.
Here is our plugins https://i.imgur.com/xp6H1FW.png

**Checklist**
- [✓] I have included a Viaversion dump
- [✓] If applicable, I have included a paste (not a screenshot) of the error
- [✓] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**More info**
I tried downgrading ViaVersion to an older version (3.2.0) and that works, the error disappears and 1.8 clients can connect, but this then in turn prevents 1.16.4 clients to connect due to the plugin then being outdated.

Using any version above 3.2.1 (Including dev builds), cause the error to occur and prevents 1.8.x clients from connecting.

**Comment by KennyTV** [comment]
Your ViaRewind is outdated (otherwise open the issue on the VR tracker).
