### ISSUE TITLE
Kick from the game

### ISSUE THREAD

**Issue by Kapitowa** [ViaVersion/ViaVersion#2256]
**Describe the bug, provide any errors**
https://paste.gg/p/anonymous/86d2a981c7a846638dee4c8f9d94414a

**How can we reproduce it?**
Use command: minecraft:give @a[distance=..20] stick{display:{Name:[{"text":"Палочка для царя горы","italic":false,"bold":true,"color":"gold"}]},Enchantments:[{id:knockback,lvl:2}]} 1

**ViaVersion Dump**
https://dump.viaversion.com/c8b62fb3d3cf89a1c2fc810cac988454640a24a2f031bb3f961f787d67a4554c

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
That's not valid nbt.
