### ISSUE TITLE
Bug Guardian on 1.16.4 from Server 1.14.4

### ISSUE THREAD

**Issue by ImperialCrise** [ViaVersion/ViaVersion#2258]
A visual problem. If I send Guardian Beam packets on a 1.14.4 server, people in 1.14.4 will see them well while people in 1.16.4 will only see bubbles.

My servers:
I use the normal Bungeecord from Spigot.
I installed the latest snapshot of ViaVersion on the spigot servers.

On 1.14.4 Client :
![image](https://user-images.githubusercontent.com/16134489/103050828-9bb97b80-4595-11eb-8453-f74bc2da639f.png)

On 1.16.4 Client:
![image](https://user-images.githubusercontent.com/16134489/103050837-a1af5c80-4595-11eb-812f-13b0338eefa1.png)

Bump: https://dump.viaversion.com/3fb1dc1dba99ffe8eebc03a3ed7393e2369158f730938b77d4dcff54d8598142

**Comment by Camotoy** [comment]
I tested with the latest dev version (you need to update, by the way - see an issue template) with a guardian and was able to see the beam.

Please update your ViaVersion, and if that doesn't work, please state how to replicate this.

**Comment by ImperialCrise** [comment]
Okey i just tested with real guardians, and the bug is still here :
![image](https://user-images.githubusercontent.com/16134489/103089057-1c579680-45ed-11eb-9e40-0a01980024e2.png)

How to reproduce : 
- Have a bungeecord (last version : 1.16-R0.4-SNAPSHOT:9c078b7:1539)
- Have a Spigot server connected to the bungeecord server (version of the spigot: final build for 1.14.4)
- And then connect to the server with a 1.16.4 client. The client will just see bubbles instead of the guardian beam

Dump (last snapsho) : https://dump.viaversion.com/3fb1dc1dba99ffe8eebc03a3ed7393e2369158f730938b77d4dcff54d8598142

**Comment by Camotoy** [comment]
Possibly related - have not tested after my previous comment: https://github.com/PaperMC/Paper/issues/4948

**Comment by ImperialCrise** [comment]
> Possibly related - have not tested after my previous comment: [PaperMC/Paper#4948](https://github.com/PaperMC/Paper/issues/4948)

What i said before : it's on Spigot this bug too, not on paper

**Comment by KennyTV** [comment]
It's a Vanilla bug, not Spigot or Paper related.
