### ISSUE TITLE
Can't open inventory for 1.14 player!

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaVersion#2259]
ViaVersion/ViaFabric#88:
Describe the bug, provide any errors
When opening some inventories in lower version than 1.16, we sometimes get an error:
[16:31:48] [Netty Client IO #0/WARN] (ViaVersion) Can't open inventory for 1.14 player! Type: Chest Size: 54

Is this happening specifically on ViaFabric?
I think this is due to ViaVersion but not entirely sure.

How can we reproduce it?
Use ViaFabric for 1.16, enable client-side version and use 1.9, join funcraft.net, try to open a menu by right-clicking any item.

Expected behaviour
It should still open the inventory, I guess.

**Comment by FormallyMyles** [comment]
A brief look makes me think that a plugin isn't using a valid namespace for the container type, see - https://wiki.vg/index.php?title=Inventory&oldid=8244

**Comment by RaphiMC** [comment]
![grafik](https://user-images.githubusercontent.com/50594595/109970012-dc034b80-7cf4-11eb-9c3f-cfc1fb2e03dd.png)
As seen here 1.13.2 clients will display a chest inventory if it doesn't match anything else, so the correct way of handling that packet would be to always send the 1.14 client a chest inventory if the containerId is invalid
