### ISSUE TITLE
Player using 1.16.4 in server 1.8.8

### ISSUE THREAD

**Issue by CheccoFT** [ViaVersion/ViaVersion#2260]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?

**How can we reproduce it?**
1. Login on 1.16
2. Click on blocks while you have an item as wheat, it will desapear, not work everytime...
3. The '....' is displayed wrong

**Expected behaviour**
I just wanna do a minecraft server 1.8.8 that work with alla clients 

**Screenshots**
[20:53:11 ERROR]: [ViaVersion] Failed to get an item to create a window click packet. Please report this issue to the ViaVersion Github: Too many inventory slots: slotId: 51 invSlotCount: 41 invType: CRAFTING topInvType: CRAFTING

**ViaVersion Dump**
https://dump.viaversion.com/1037fa0e5da13b9c8354b6c6ce40cc9b967deba72acf9c5f289d66448d87d826

**Additional server info**
I use waterfall with plugins : BungeeHub, BungeePerms, BungeeReport, CustomPayloadFixer, Nyx, ServerListPlus, SkinRestorer
Paper 1.8.8 with plugins: asCMD, BlockParticles, ChatGames, CMI, CrackShot, CrazyAuctions. DebugStick, DeluxeMenus, Fawe, LuckPerms, MultiverseCores, ObsidianBreaker, PlaceholderAPI, Plugman, protocolsupport, protocolLib, QuickClose, SaberFactions, Skinrestorer, vault, viaversion, worldedit, worldguard.

**Comment by FormallyMyles** [comment]
I'm unable to replicate this on the instructions given above, please test without other plugins to find the cause I suspect something is going wrong with a plugin.
