### ISSUE TITLE
ServerPing Base_Protocol Error

### ISSUE THREAD

**Issue by CorruptedCodes** [ViaVersion/ViaVersion#2261]
**Describe the bug, provide any errors**
Upon pinging the server in the multiplayer server list, ViaVersion produces an error and doesn't allow players to join. Server's MOTD simply shows the message "Can't connect to server". The error is caused by a plugin called "AdvancedNMotd", since the error is non-existant upon removing the plugin. This started happening after switching from Paper version 1.16.4 to 1.12.2
Error: https://pastebin.com/xC9aJPuE

**How can we reproduce it?**
1. Set your Minecraft server version to 1.12.2 (or initially start as 1.16.4, then switch to 1.12.2)
2. Install ViaVersion, ViaBackwards, and ViaRewind (unsure if others have to do with error, but for accuracy's sake).
3. Install AdvancedNMotd.
4. Launch any Minecraft version.
5. Open the 'Multiplayer' menu or refresh the server list page.
6. The console should have produced the error.

**Expected behaviour**
ViaVersion and other Via extensions work as normal, MOTD displays normally and players are able to join the server.

**Screenshots**
None needed.

**ViaVersion Dump**
https://dump.viaversion.com/25f1dd10194a0180bb171134ea6ad5e482f8d66dbc95bb582bd413311816dbaa

**Additional server info**
Single server, runs on Paper 1.12.2. 
Plugins: https://pastebin.com/kaPgzcG6

**Checklist**
- [X] I have included a Viaversion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
Given that this throws a NoSuchMethodException beforehand, I don't think the plugin is properly compatible with your server and most likely sends invalid MOTD data.

I'd suggest trying another plugin but doesn't look fixable our end. Will happily reopen if i'm mistaken.
