### ISSUE TITLE
GIANT Chunks of Stone generating at unloaded areas!!!

### ISSUE THREAD

**Issue by WolfyRed** [ViaVersion/ViaVersion#2264]
**Describe the bug, provide any errors**
Me and my family play on my server, it works fine for every client (Java client), EXCEPT for Bedrock clients!! Giant HUGE chunks of stone generate at unloaded parts of the world!!

**How can we reproduce it?**
1. Login on Bedrock edition (With Geyser + ViaVersion plugin on a 1.12 Bukkit/Spigot server)
2. MOVE FAR AWAY FROM THE SPAWN POINT
3. Giant chunks of stone is displayed!!! They even have collision!

**Expected behaviour**
I expected giant weird chunk errors to **not** occur, knowing I only have 4 Plugins in my server files!

**Screenshots**
Screenshots provided!!!
![Minecraft 12_29_2020 5_39_50 PM](https://user-images.githubusercontent.com/66114400/103318644-169eee00-49fd-11eb-8207-894bc2650be0.png)
![Minecraft 12_29_2020 5_17_08 PM](https://user-images.githubusercontent.com/66114400/103318650-1b63a200-49fd-11eb-9f49-be8a758ea891.png)

**ViaVersion Dump**
![stinky+dump](https://user-images.githubusercontent.com/66114400/103318920-eefc5580-49fd-11eb-80de-79d81d996120.PNG)

**Additional server info**
I use ViaVersion and Geyser plugins, no BungeeCord! (Spigot 1.12)
`((I also like the 1.12 world generation so that's why I use 1.12!!))`
`(And the server runs at 8 GB of RAM too!)`
`When using Geyser by itself, THIS ISSUE DOES NOT OCCUR!!!`

**Checklist**
- [X] I have included a Viaversion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by Camotoy** [comment]
If Java 1.16.4 generates these chunks correctly, this is not a ViaVersion issue, it is a Geyser issue.

**Comment by WolfyRed** [comment]
> If Java 1.16.4 generates these chunks correctly, this is not a ViaVersion issue, it is a Geyser issue.

Reread "**Additional server info**"

**Comment by WolfyRed** [comment]
> > If Java 1.16.4 generates these chunks correctly, this is not a ViaVersion issue, it is a Geyser issue.
> 
> Reread "**Additional server info**"

**Comment by WolfyRed** [comment]
How do I unclose I thought that was an undo comment button!
