### ISSUE TITLE
Internal Exception: io.netty.handler.codec.DecoderException

### ISSUE THREAD

**Issue by Strikeriino** [ViaVersion/ViaVersion#2268]
Okay, so when i wanna join a 1.8.x Server on 1.8.x version it still kicking me from server and every time it says this  
**"Internal Exception: io.netty.handler.codec.DecoderException: Chinesse Things...: Please post this error to "this site. {Source 0: Chinesse things...} Actual Error:**

**Comment by KennyTV** [comment]
Follow the issue template and include the actual error.
