### ISSUE TITLE
[1.8.9]

### ISSUE THREAD

**Issue by DarkyCat** [ViaVersion/ViaVersion#2269]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?

**How can we reproduce it?**
When I go to a server with kernel 1.16.4, from version 1.8.9 I get kicked with an error that is in the screenshot.

**Expected behaviour**

**Screenshots**
![изображение](https://user-images.githubusercontent.com/50515714/103442844-5d018080-4c7b-11eb-9796-673e618eeef8.png)

**ViaVersion Dump**
https://dump.viaversion.com/8a4e1f5773137f000dac2e698815ebf09cff70f6435a1ff4d98ec9bad4aabf0b

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Checklist**
- [ ] I have included a Viaversion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Use ViaRewind ci builds.

**Comment by DarkyCat** [comment]
![изображение](https://user-images.githubusercontent.com/50515714/103443151-13fefb80-4c7e-11eb-8b6c-47e237c9c160.png)
![изображение](https://user-images.githubusercontent.com/50515714/103443156-1bbea000-4c7e-11eb-9c9e-112bd97bdb86.png)
