### ISSUE TITLE
PlayerPackets - ERROR

### ISSUE THREAD

**Issue by alexeses** [ViaVersion/ViaVersion#2270]
**Describe the bug, provide any errors**
My console is full of this type of very similar errors, I do not know how to reproduce it since I imagine that it will be a compatibility error with the latest version of the game.

Error: https://paste.minebox.es/nezakiyogu.csharp

**Expected behaviour**
Obviously, this error should not happen

**ViaVersion Dump**
https://dump.viaversion.com/34bfe0ebc177ad1c7af80a32565d724053e5cfb4b3d4c8181814b402eb6d1702

**Additional server info**
Use waterfall latest version, no special plugin that may interfere with the error

I use the latest version of Via Rewind, ViaVersion and ViaBackwards, in the latest version of PapperSpigot updated today January 1st.

**Checklist**
- [X] I have included a Viaversion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Has already been reported on the VR tracker.

**Comment by alexeses** [comment]
I just got the latest version of Jenkings, ViaVersion-DEV, ViaBackwars-DEV and ViaRevind-DEV and the error keeps happening. Still not fixed?
