### ISSUE TITLE
ERROR IN Protocol1_9To1_8 IN REMAP OF 0x00->0x00

### ISSUE THREAD

**Issue by minecraft7net** [ViaVersion/ViaVersion#2278]
pastebin:
https://pastebin.com/dKSuPgac

i will try add more information later.

server version:
[03:48:43] [Server thread/INFO]: This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

protocollib:
[03:48:45] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.5.1

viaversion
[03:48:44] [Server thread/INFO]: [ViaVersion] Loading ViaVersion v3.2.1

**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?

**How can we reproduce it?**
1. Login on 1.12'
3. The '....' is displayed wrong

**Expected behaviour**

**Screenshots**

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Checklist**
- [ ] I have included a Viaversion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Follow the issue template.
