### ISSUE TITLE
Console spammed with error when many players are joining

### ISSUE THREAD

**Issue by Govindass** [ViaVersion/ViaVersion#2280]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?
ViaVersion spamming errors at a insane rate, resulting in my server going down (due to pterodactyl auto-turning off server when console is spammed) error: https://paste.gg/p/anonymous/3d20b844c64e4481ad2ba10b03e6f421
**How can we reproduce it?**
I don't know

**Expected behaviour**
Expected to not spam console
**Screenshots**

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/9b63fbe94309895b3f6993b27a5df2bb34e84176d788df508691b099050a4d3c

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
FlameCord, however ViaVersion is only on the spigot side, so this does not matter
**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by Seanoo1** [comment]
You didn't follow the third checklist. Redownload all three via plugins from that site.

**Comment by Govindass** [comment]
> 
> 
> You didn't follow the third checklist. Redownload all three via plugins from that site.
seeing that latest build of viaversion/viabackwards is from 2020-12-12, I think that I have the latest, but I've updated ViaRewind.

**Comment by FormallyMyles** [comment]
Pretty sure from experience this is some kind of chunk corruption, would you be able to isolate the chunk and test this?

**Comment by Govindass** [comment]
I think this can be closed, my builders built a new main lobby and the issue is gone, I was using the previous world for 5 years since 2016, so various things could've happened to it
