### ISSUE TITLE
A bug in a server 

### ISSUE THREAD

**Issue by DariusBadDev** [ViaVersion/ViaVersion#2284]
i was joining sky block on mew network when i got a error it said to report the error to here 
 
  no mods were used only a texture pack 
  version : 1.8.9 
  i tried to open sky block 3 times 
    -one wihout a texture pack 
    -one with texture pack nr 1 
    -one with texture pack nr 2 

![Screenshot (18)](https://user-images.githubusercontent.com/77202635/104096203-b123ea80-52a3-11eb-8b52-c8f7630e23dd.png)
  the game worked before so i is not a hardware issue

**Comment by KennyTV** [comment]
Follow the issue template (likely outdated versions).
