### ISSUE TITLE
Have a lot of warning erros when my 1.16.4 Paper server start

### ISSUE THREAD

**Issue by x9nico** [ViaVersion/ViaVersion#2285]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?
https://hastebin.com/uwinaqoxen.md

**How can we reproduce it?**
Start your server and check logs
I tried with a dev version too, it does the same errors.

**Screenshots**
N/A

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.
 https://dump.viaversion.com/2dfb25b4dbff4db80a34ee843defb4600670226100a775b5cb956a4eb1ccd1f7

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins? Paper 1.16.4

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
You're using ViaVersion and protocolsupport together which is pointless.
