### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Porkason** [ViaVersion/ViaVersion#2288]
**Describe the bug, provide any errors**
This error occurs when a player joins with the native server version. (seems to only affect staff and could be spread over multiple versions. https://pastebin.com/1f2bZQfa

**How can we reproduce it?**
1. Login on 1.16.4 in this case. 
2. Join a 1.16.4 server with viaversion, viabackwards, viarewind, viabackwardslegacysupport. All on the latest dev builds. 
3. Now it spamms this message in console. https://pastebin.com/1f2bZQfa

**Expected behaviour**
I expected the viaversion to not throw errors / warnings? 

**Screenshots**
No

**ViaVersion Dump**
https://dump.viaversion.com/4907519ab11e75837d4a866b7879612834b9fbaf01dbc2e0b0f9c1b09ed663b5

**Additional server info**
This is a bungeecord network. All servers under it use paper. 1.16.4 or 1.16.3 if relevant. 

**Checklist**
- [x ] I have included a Viaversion dump
- [x ] If applicable, I have included a paste (not a screenshot) of the error
- [x ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
That's another plugin sending incomplete chat packets with ProtocolLib.
