### ISSUE TITLE
1.16.5 says 1.16.4 in "/viaversion list"

### ISSUE THREAD

**Issue by Welcome234** [ViaVersion/ViaVersion#2290]
In 1.16.5 I logged into my server, the protocol number is the same as 1.16.4 so I didn't need to update the plugin.

But there is a bug that it shows "1.16.4" and it should show like "1.16.x" or "1.16.4-1.16.5".

**Comment by Logics4** [comment]
https://github.com/ViaVersion/ViaVersion/blob/c0fb81946e751ada0b6f6373ba13b5c1f07a4b1f/common/src/main/java/us/myles/ViaVersion/api/protocol/ProtocolVersion.java#L56

**Comment by KennyTV** [comment]
https://github.com/ViaVersion/ViaVersion/commit/2beed20f1b1dc11f4c8c53ca89ac1c4e3130709f
