### ISSUE TITLE
Spamming console with errors + disconnect

### ISSUE THREAD

**Issue by KickSquareMC** [ViaVersion/ViaVersion#2294]
**Describe the bug, provide any errors**
Server didn't let people rejoin and crashed, and absolutely spammed console with errors. When people tried to rejoin, it said "Disconnected". Logs: https://paste.gg/p/anonymous/cdc6c7c7b45943809c7235166914f236

**How can we reproduce it?**
I used paper 1.12.2, with viaversion, viabackwards, viarewind (1.8-1.16 can join)
I have geysermc and floodgate installed

**ViaVersion Dump**
-I did /viaversion dump after I restarted the server, also I removed the plugins list from the dump. https://paste.gg/p/anonymous/9347e72383c44cb0b899c5b6cc7c0923

**Checklist**
- [✔] I have included a Viaversion dump
- [✔] If applicable, I have included a paste (not a screenshot) of the error
- [❌] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
Without a valid plugin list, we can't help you (mainly cause it's usually a conflict). I'd suggest removing half the plugins and testing and narrowing down what the cause might be. If you can cause it with just ViaVersion and post what we need to replicate it we can happily reopen and investigate.
