### ISSUE TITLE
Nullpointer from Viaversion

### ISSUE THREAD

**Issue by Tobi-Jakka** [ViaVersion/ViaVersion#2295]
**Describe the bug, provide any errors**
I am simply getting a console error from Viaversion, I havent noticed anything not working
https://paste.gg/p/anonymous/00b3037cf4af4d6ab8a0df9c656dd14f

**How can we reproduce it?**
Not sure

**Expected behaviour**
No error in console log

**Screenshots**
No screenshots as its simply a console error

**ViaVersion Dump**
https://dump.viaversion.com/6b47031a89977ff55bad21373edbf6114060f81fe1cf15ebf533af284f5904a7

**Additional server info**
My server is a waterfall network & the server specifically is running paper-232 1.16.4
Viaversion version is 3.2.1

**Checklist**
- [true ] I have included a Viaversion dump
- [true ] If applicable, I have included a paste (not a screenshot) of the error
- [not true ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
This isn't a ViaVersion error, this is down to another plugin having incomplete packets.
