### ISSUE TITLE
Explosions cause ghost blocks to appear

### ISSUE THREAD

**Issue by avaruus1** [ViaVersion/ViaVersion#2296]
**Describe the bug, provide any errors**
Explosions cause ghost blocks to appear.

**How can we reproduce it?**
1. Log in with 1.16.5 client
2. Place down a few blocks of tnt
3. Ignite them

**Expected behaviour**
No ghost blocks should appear.

**ViaVersion Dump**
https://dump.viaversion.com/281acdfa5e9b8b71c4002bede179a6bfd8efdf536a9c951e68d2022fe27ad058

**Additional server info**
- The same issue does not occur with Spigot.
- Disabling `serverside-blockconnections` option seems to fix the issue.

**Comment by creeper123123321** [comment]
It seems that //cut command also causes it

**Comment by creeper123123321** [comment]
it seems related with the chunk update packet

**Comment by RaphiMC** [comment]
Works for me, finally this has been fixed
