### ISSUE TITLE
idk what is that

### ISSUE THREAD

**Issue by heywat** [ViaVersion/ViaVersion#2300]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?
it kicked me out of the server and gave me this error

**How can we reproduce it?**
1. Login on 1.12'
3. The '....' is displayed wrong

**Expected behaviour**
get me inside the server ?

**Screenshots**
![image](https://user-images.githubusercontent.com/74481108/105570855-bdf11580-5d5c-11eb-8c1d-6ff8be95c711.png)

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.
- dosent to anything

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
nothing

**Checklist**
- [ ] I have included a Viaversion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
We don't either! Follow the issue template.
