### ISSUE TITLE
Option to choose supported versions server by server.

### ISSUE THREAD

**Issue by Brasil150** [ViaVersion/ViaVersion#2303]
**Is your feature request related to a problem? Please describe.**
Yes, I looked for a way to block server-by-server versions. Ex: https://imgur.com/a/yjUvbAd

**Describe the solution you'd like**
A function to define supported versions server by server.

**Describe alternatives you've considered**
Search for a plugin.

**Which versions is this for?**
All

**Comment by FormallyMyles** [comment]
This isn't something we'll add, you can just generate a list of protocols to block and choose not to update ViaVersion - https://via.krusic22.com/
