### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by DominicFilice** [ViaVersion/ViaVersion#2304]
I use Geyser Spigot with its floodgate bukkit
https://paste.gg/p/anonymous/5d57efb03bd84a1a89f7fe55a54663fc
Dont know how to reproduce this as the server has had no one on it and I havent done anything on it.
If you need more info, ask.

**Comment by KennyTV** [comment]
Follow the issue template, likely just someone sending bad packets / an issue with floodgate tho.
