### ISSUE TITLE
Disconnect issue when on 21w03a in hub (Latest dev build 21 jan)

### ISSUE THREAD

**Issue by TheCompieter** [ViaVersion/ViaVersion#2311]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?
**How can we reproduce it?**
1. Login on 21w03a.
2. Unsure why it happens & it happens very often but only on 21w03a and not 1.16.5

**Expected behaviour**
No disconnect/crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/34034571/106505814-1e085a00-64c9-11eb-9e9b-42a60a12ccfd.png)

**ViaVersion Dump**
https://dump.viaversion.com/dee9612376ad5980856621e4a822fda27b6c7e12f069c2e2a089f3d2b2741a36

**Additional server info**
I use for snapshot support on the proxy the latest version of Waterfall-Xernium
https://jenkins.krusic22.com/job/Waterfall-Xernium/

**Checklist**
- [v] I have included a Viaversion dump
- [v] If applicable, I have included a paste (not a screenshot) of the error
- [v] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by Blocksnmore** [comment]
Use 👏 the 👏 template 👏 https://github.com/ViaVersion/ViaVersion/issues/new?assignees=&labels=&template=bug_report.md

**Comment by TheCompieter** [comment]
@Blocksnmore Updated
.

**Comment by KennyTV** [comment]
You're outdated.
