### ISSUE TITLE
Console Errors [1.16.5]

### ISSUE THREAD

**Issue by hamcoremusic** [ViaVersion/ViaVersion#2312]
**Describe the bug, provide any errors**
No clue what it is or if it is affecting my players, but this keeps coming up in my console every now and then: https://pastebin.com/bWQE9e8h

**How can we reproduce it?**
N/A

**Expected behaviour**
N/A

**Screenshots**
N/A

**ViaVersion Dump**
- https://dump.viaversion.com/ac5d455a43d450bb1e8fa97619d140cf4f3a1c7f87761c1eba39196572ece869

**Additional server info**
Plugins are listed in the dump

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by hamcoremusic** [comment]
Have not tried any dev builds yet. Just want to see if this is a knows issue.

**Comment by Blocksnmore** [comment]
Try using the latest viaversion plugins 
ViaVersion - https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/jar/target/ViaVersion-3.2.2-SNAPSHOT.jar
ViaBackwards - https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/lastSuccessfulBuild/artifact/all/target/ViaBackwards-3.2.1-SNAPSHOT.jar

**Comment by hamcoremusic** [comment]
Thank you! Will run these for a bit and see if it works!

**Comment by KennyTV** [comment]
It's likely someone sending bad ping packets

**Comment by hamcoremusic** [comment]
> It's likely someone sending bad ping packets

This happened for multiple different people just randomly. I have just switched to the latest dev versions, doing to see if it clears it up.
