### ISSUE TITLE
Unreadable description

### ISSUE THREAD

**Issue by adiantek** [ViaVersion/ViaVersion#2313]
Github added official dark theme and it's unreadable on dark theme:

![image](https://user-images.githubusercontent.com/13407885/106809445-f8678600-666b-11eb-8e64-00760ec7c8c5.png)

**Comment by KennyTV** [comment]
https://github.com/ViaVersion/ViaVersion/commit/9fbadc0ad50fe98c67b4c66bcf180254571f34d8
