### ISSUE TITLE
the use of the second hand.

### ISSUE THREAD

**Issue by AngeloNGL** [ViaVersion/ViaVersion#2317]
when i added the plugin, people started saying that they can no longer put objects in the second hand, please fix it because it is really hideous! server version: 1.16.4 / ViaVersion used for a range from 1.16 to 1.16.5.
No info in console, no warnings, no errors.

**Expected behaviour**
Only when i installed viaver and restarted the server, i setupped the blocked protocols for the server, i restarted and all of the people can't use the second hand anymore.

**ViaVersion Dump**
https://dump.viaversion.com/c8f249a4f70086b817e1e868991f95f7888ec70b4bc2ba064fa81b390387f50f

**Additional server info**
no, i don'use proxy, in the plugin list later i will remove multiverse core/inventories, deluxehub and perworldserver. I'm using Spigot 1.16.4

https://user-images.githubusercontent.com/78598666/107035212-20640000-67b8-11eb-9131-a279e2755a4a.mp4

**Checklist**
- [yes ] I have included a Viaversion dump
- [ yes] If applicable, I have included a paste (not a screenshot) of the error
- [no ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
Does this issue happen on 1.16.4?

**Comment by FormallyMyles** [comment]
See above, need a list of versions which are impacts. Also, can you test without other plugins? 

Once the above is provided, we'll reopen / transfer to ViaBackwards
