### ISSUE TITLE
EncoderException : us.myles.ViaVersion.exception.InformativeException

### ISSUE THREAD

**Issue by SkepsonSk** [ViaVersion/ViaVersion#2320]
Hey, got this error in flamecord console.
EncoderException : us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Source 0: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.Protocol1_13To1_12_2$8 (Anonymous)}

EncoderException : us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Type: Integer, Data: [], Source 0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.PlayerPackets$11 (Anonymous), Packet ID: 51}
Actual Error:  @ io.netty.handler.codec.MessageToMessageEncoder:104

**Comment by KennyTV** [comment]
Follow the issue template.
