### ISSUE TITLE
Every time I join on the server it says disconnected.

### ISSUE THREAD

**Issue by EmpPuli5** [ViaVersion/ViaVersion#2321]
I cant join my MC server.

**Expected behaviour**
I disconnect every time i join.

**Screenshots**
![image](https://user-images.githubusercontent.com/78647955/107119143-45c33d80-688e-11eb-9e0d-668e5f920edf.png)

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.

**Additional server info**
I use paper server and i have some basic plugins in it.

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Properly follow the issue template please.
