### ISSUE TITLE
us.myles.ViaVersion.exception.InformativeException

### ISSUE THREAD

**Issue by Big-Cake-jpg** [ViaVersion/ViaVersion#2324]
**Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException**

**How can we reproduce it?**
1. Login on 1.15.2
2. Playing 'Potato Games Remastered'
3. Lost connection

**Expected behaviour**

**ViaVersion Dump**
- https://dump.viaversion.com/33bd01a74a12944e75f9618b48539d3b8deafbe17ceec719fde1ae9b53941e11

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
No,I only use ViaVerison,MiniMOTD,Geyser and Yum

**Comment by KennyTV** [comment]
Remove ViaVersion from your proxy, it should only be on either backend or proxy.
