### ISSUE TITLE
Shulker Boxes become droppers on 1.16

### ISSUE THREAD

**Issue by JohnB17** [ViaVersion/ViaVersion#2325]
**Describe the bug, provide any errors**
I had 4 red shulker boxes in my inventory, I joined from 1.8 and everything was fine, but when I went back into 1.16, the shulker boxes were still droppers.

**How can we reproduce it?**
1. Login on 1.16
2. Get shulker boxes
3. Login on 1.8
4. Open the shulker boxes
5. Log out on 1.8
6. Log in on 1.16
7. Check shulker boxes

**Expected behaviour**
The shulker boxes to be shulker boxes and not droppers

**Screenshots**
Don't have any.

**ViaVersion Dump**
- https://dump.viaversion.com/8aa12ef8dd84132c39a4a48fa42d3ab8cba6b18e6afaf8c34c811e1eee6917b8

**Additional server info**
I am using BungeeCord, thinking of switching to waterfall though.

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
Can you provide a video?

Did you use Creative?

**Comment by JohnB17** [comment]
This happened in survival, I can make a video later.

**Comment by JohnB17** [comment]
Nope, it was just a fluke, I reset viaversion (deleted config and jar file) and put a new jar file on there, and the problem was gone.
