### ISSUE TITLE
Scoreboard colors are not the same on 1.8.9 and 1.16.5

### ISSUE THREAD

**Issue by lucaazalim** [ViaVersion/ViaVersion#2326]
**Describe the bug, provide any errors**
Scoreboard colors on 1.16.5 are different from 1.8.9.

**Expected behaviour**
Scoreboard text on 1.16.5 should be exactly the same as on 1.8.9

**Screenshots**

**1.8.9:**
![image](https://user-images.githubusercontent.com/10585881/107165028-3a583b00-6990-11eb-8b85-7979f68669c5.png)

**1.16.5:**
![image](https://user-images.githubusercontent.com/10585881/107165040-49d78400-6990-11eb-9471-00b8acaa5fb4.png)

**ViaVersion Dump**
- https://dump.viaversion.com/b4b596af8c3d62b2db4679975b49d6af38b633cb5e048cb79c306f515024679d

**Additional server info**
- Latest Waterfall version running our own plugins.

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
Test with team-colour-fix in the config disabled otherwise provide the code / source for the scoreboard. It may be you need to add additional colour codes due to how scoreboards have changed across versions.

**Comment by lucaazalim** [comment]
> Test with team-colour-fix in the config disabled otherwise provide the code / source for the scoreboard. It may be you need to add additional colour codes due to how scoreboards have changed across versions.

Thank you for your reply! Disabling `team-colour-fix` fixed the problem. Do you think disabling it is going to break the colors on another versions?

**Comment by FormallyMyles** [comment]
> > Test with team-colour-fix in the config disabled otherwise provide the code / source for the scoreboard. It may be you need to add additional colour codes due to how scoreboards have changed across versions.
> 
> Thank you for your reply! Disabling `team-colour-fix` fixed the problem. Do you think disabling it is going to break the colors on another versions?

It should be fine as the fix is only applied at one point in the pipeline.

**Comment by lucaazalim** [comment]
Disabling `team-colour-fix` fixes the scoreboard problem, but creates a new problem with player names:

**1.8.9:**
![image](https://user-images.githubusercontent.com/47063486/107522006-f92f7900-6b91-11eb-8729-31ed76ac39ab.png)

**1.16.5:**
![image](https://user-images.githubusercontent.com/47063486/107521942-e6b53f80-6b91-11eb-944c-4b86f73af237.png)

**Comment by KennyTV** [comment]
You can't, basically. There's no way for Via to know which way the plugin(s) in question want to use scoreboard team colors, so we can only offer an option to to either, but it looks like you have both kinds in scoreboard vs. tablist.

**Comment by toxamin** [comment]
enable team-colour-fix and put &f in front of the scoreboard lines
