### ISSUE TITLE
ViaVersion Kicking

### ISSUE THREAD

**Issue by Gertjan300** [ViaVersion/ViaVersion#2328]
**Describe the bug, provide any errors**
https://paste.gg/p/anonymous/da26b338e00542aaacfc7b64ef02c0af The error
This error is been given on every version when he joins
And i cant find it on his end

**How can we reproduce it?**
I cant it only happens to one player. And it happens everytime on every version to him

**Expected behaviour**

**ViaVersion Dump**
https://dump.viaversion.com/f1ff74b2c5b61d42bafb41ed50a00a3a25e7f075415789ea1a56bfc0976f58fd

**Additional server info**
I do use bungeecord, But i used viaversion first off on all backend servers.
Now i switched to bungeecord only since i thought then it could be only one thing
But its only the towny server since i have skyblock too

**Checklist**
- [Yes ] I have included a Viaversion dump
- [No] If applicable, I have included a paste (not a screenshot) of the error
- [Yes] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
Unfortunately, this is most likely down to chunk corruption as the server is sending invalid chunk data to the client. I would locate the chunk the user is in and regenerate it, or look into tools to repair the region file.
