### ISSUE TITLE
Allow us to control which versions are allowed

### ISSUE THREAD

**Issue by Sunni05** [ViaVersion/ViaVersion#2329]
**Is your feature request related to a problem? Please describe.**
Say you have all 3 of the plugins, but you only want to go back to 1.12.2, this could be a setting in the config or something
**Describe the solution you'd like**
Add a setting in the config
**Describe alternatives you've considered**
Make a separate plugin for each version I suppose
**Which versions is this for?**
Does the feature apply to any specific versions? If so put them here.
All of them

**Comment by FormallyMyles** [comment]
You can just generate a list of protocols to block for your ViaVersion config.yml with block-protocols - https://via.krusic22.com/.
