### ISSUE TITLE
kicks players

### ISSUE THREAD

**Issue by DenisJ9798** [ViaVersion/ViaVersion#2334]
Kicks players with the error disconnected connection, using bungeecord

https://paste.gg/p/anonymous/a57309031dd040d0a692ad8e7e443e95

https://dump.viaversion.com/d434482d8107e3914ab8fb039469df07b43b8b8eb7f31660a65e255ff7f0b635

**Comment by FormallyMyles** [comment]
You haven't provided enough information for us to look into this issue, please see the template when you create an issue.

As a guess I would say another plugin is sending wrong data-values for a certain version, you would need to test without other plugins to diagnose this.
