### ISSUE TITLE
Encoder Exception

### ISSUE THREAD

**Issue by Jzcob** [ViaVersion/ViaVersion#2335]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?
[Jzcob] disconnected with: EncoderException : us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
10.02 16:24:55 [Server] INFO {Type: Chunk, Index: 0, Data: [Pair{Type|Chunk, us.myles.ViaVersion.api.minecraft.chunks.Chunk1_8@c3da2a1}], Packet ID: 33}

**How can we reproduce it?**
1. Login on 1.8.9'
2. Click on 'The server'
3. I get kicked with the error: EncoderException : us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
10.02 16:24:55 [Server] INFO {Type: Chunk, Index: 0, Data: [Pair{Type|Chunk, us.myles.ViaVersion.api.minecraft.chunks.Chunk1_8@c3da2a1}], Packet ID: 33}

**Expected behaviour**
Not get kicked.

**Screenshots**
https://prnt.sc/z0iaa4

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.
I am not able to connect to the server to put that in.

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
I do use a proxy, and the proxy is running Flamecord. https://prnt.sc/z0ihq1
**Checklist**
- [ ] I have included a Viaversion dump
- [y] If applicable, I have included a paste (not a screenshot) of the error
- [y] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
There is not enough information here, provide the full error from the console and run the viaversion dump command.

Ensure ViaVersion is only on either your proxy or backend.

**Comment by Germandoe** [comment]
This is happening to me too. All latest ViaVersion/ViaRewind/ViaBackwards.

[](https://dump.viaversion.com/a65922deaf68d11918b658e31245337db049723fefa2ebbb8e907ebbac2d3f02)

lost connection: Internal Exception: io.netty.handler.codec.DecoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0

Seems like there are others with the same issue as well [](https://www.spigotmc.org/threads/player-kick.483069/)

**Comment by KennyTV** [comment]
Your ViaRewind is outdated.
