### ISSUE TITLE
ERROR IN Protocol1_12_2To1_13 IN REMAP OF SPAWN_PARTICLE

### ISSUE THREAD

**Issue by bobhenl** [ViaVersion/ViaVersion#2340]
**Describe the bug, provide any errors**
https://pastebin.com/3sAZvM5k

But I'm sorry, I don't know how it happened.

**Expected behaviour**
Any error 

**ViaVersion Dump**
https://dump.viaversion.com/3fd97b363cdefc57ee975495fb31229dc832d3e2340322708a68ed3336466a73

**Additional server info**
Yes

**Checklist**
- [ x] I have included a Viaversion dump
- [ x] If applicable, I have included a paste (not a screenshot) of the error
- [ x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Use dev builds (we also do not support Yatopia).
