### ISSUE TITLE
io.netty.handler.codec.MessageToMessageEncoder:104

### ISSUE THREAD

**Issue by xHyroM** [ViaVersion/ViaVersion#2344]
[general_kubo] disconnected with: EncoderException : us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Type: String, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.PlayerPackets$10$1 (Anonymous), Packet ID: 56, Source 1: de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.PlayerPackets$10 (Anonymous)}
Actual Error:  @ io.netty.handler.codec.MessageToMessageEncoder:104

**Comment by KennyTV** [comment]
Follow the issue template/report this on the ViaRewind tracker.
