### ISSUE TITLE
io.netty.handler.codec.DecoderException: us.myles.ViaVersion.exception.InformativeException

### ISSUE THREAD

**Issue by redalpha333** [ViaVersion/ViaVersion#2348]
Not gonna lie I have no clue my server just told me to report this here so here is my [.log file](https://github.com/ViaVersion/ViaVersion/files/5979335/latest.log) and I have my players use NGROK a tool that creates a tunnel on my local machine along with a public URL because port forwarding for some reason wont work, not sure if that makes difference or not so I put it here.

**Comment by KennyTV** [comment]
Please follow the issue template.
