### ISSUE TITLE
ViaRewind error on join

### ISSUE THREAD

**Issue by MartinGamesCZ** [ViaVersion/ViaVersion#2349]
Hi, i need help, if player join on my server and have version eg 1.9 it kick him without error, 1.12+ working normaly...

if you want to test it, i send you ip if you dm me on discord martingames#1422!

[Po, 15. Úno 2021 13:29:22 CET INFO] TomVirth[/xx.xx.x.170:49569] logged in with entity id 5323 at ([authme]0.0, 65.0, 0.0)
[Po, 15. Úno 2021 13:29:22 CET WARN] io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[Po, 15. Úno 2021 13:29:22 CET WARN] {Type: Chunk, Index: 0, Data: [Pair{Type|Chunk, us.myles.ViaVersion.api.minecraft.chunks.Chunk1_8@61aef2fa}], Packet ID: 33}
[Po, 15. Úno 2021 13:29:22 CET WARN] Actual Error:
[Po, 15. Úno 2021 13:29:22 CET WARN] at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[Po, 15. Úno 2021 13:29:22 CET WARN] at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
[Po, 15. Úno 2021 13:29:22 CET WARN] at .....

**Comment by Jo0001** [comment]
Please **follow the issue template**

**Comment by MartinGamesCZ** [comment]
oh, sorry
