### ISSUE TITLE
Error on join (kicking)

### ISSUE THREAD

**Issue by MartinGamesCZ** [ViaVersion/ViaVersion#2350]
**Describe the bug, provide any errors**
[Po, 15. Úno 2021 13:29:22 CET INFO] MartinGamesCZ[/hidden ip:49569] logged in with entity id 5323 at ([authme]0.0, 65.0, 0.0)
[Po, 15. Úno 2021 13:29:22 CET WARN] io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[Po, 15. Úno 2021 13:29:22 CET WARN] {Type: Chunk, Index: 0, Data: [Pair{Type|Chunk, us.myles.ViaVersion.api.minecraft.chunks.Chunk1_8@61aef2fa}], Packet ID: 33}
[Po, 15. Úno 2021 13:29:22 CET WARN] Actual Error:
[Po, 15. Úno 2021 13:29:22 CET WARN] at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) .....

**How can we reproduce it?**
1. Join to my server (idk if i post ip here) on 1.8-1.11
2. It will kick you without any message
3. Discord livechat send leave before join

**Screenshots**
![image](https://user-images.githubusercontent.com/73077301/107951528-c70a8680-6f98-11eb-961a-0a808bf91cc8.png)
i dont have any other

**ViaVersion Dump**
https://dump.viaversion.com/c08ff7b00b6b9eb78c62ff17671631b452ea4af4c20d2e451bad0111ca5625b0

**Additional server info**
Paper 1.15.2 with viaversion, backwards, rewind

**Comment by KennyTV** [comment]
Your ViaRewind is outdated
