### ISSUE TITLE
Error viaversion 1.12.2 in 1.16.5

### ISSUE THREAD

**Issue by istarengwa** [ViaVersion/ViaVersion#2352]
**Describe the bug, provide any errors**
Hello, I have a server in 1.16.5 and when I use viaversion / viabackwards it is impossible to connect to my annex servers at the hub via the bungee network, in the lower version of minecraft, I can connect to the hub in 1.12.2 and when I switch to semi-rpg my client crashes with a huge error in the bungee console.

https://paste.gg/p/anonymous/0d3966a1e9fc47b3b6ff5acba76869d7

**How can we reproduce it?**
1. Login on 1.12.2/1.12/1.13/etc'
2. I disable the server texture pack 1.16.5
3. I connect to the lobby everything is going well
4. I change server, whether it is survival in 1.16 or semi-rpg in 1.16.5 I am kicked

**Expected behaviour**
not to be kicked

**ViaVersion Dump**
- bungee : https://dump.viaversion.com/63230dab3fbc103d6a7cd59a2dd4d8c2fbb51cf6046c85e461250c35a6987413

**Additional server info**
I have more than 170 plugins on my servers, but on the bungee I use geyser, floodgate, skinrestorer, and other

**Checklist**
- [yes ] I have included a Viaversion dump
- [yes ] If applicable, I have included a paste (not a screenshot) of the error
- [yes ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Use dev builds.

**Comment by istarengwa** [comment]
new error in the bungee console : https://paste.gg/p/anonymous/1fe5aa1237fc40d0b4f53b1c624f021e

**Comment by KennyTV** [comment]
Update *all* plugins to dev builds

**Comment by istarengwa** [comment]
now my game gets stuck on "loading the map" when I switch from the hub to the semi-rpg but no problem connecting to the hub
and a constant warn in the bungee console

https://paste.gg/p/anonymous/e8882026a4584cdabc0f9a69205b93e4

**Comment by istarengwa** [comment]
and when I try to connect to survival always a big error message on the bungee console 

https://paste.gg/p/anonymous/b98b722c0ec64103b51be368513ec52a

**Comment by KennyTV** [comment]
Sounds like you have quite the cursed server setup 👀
The last error is fixed in the latest VB dev build (the second last is some plugin sending entity data for untracked entities), also try moving Via from your proxy to the backend servers.

**Comment by istarengwa** [comment]
I just removed all the via from the bungee server to put them on each server, and now everything works fine =) thanks for the help =)
