### ISSUE TITLE
Visual bug on 1.16.4 client on a 1.12.2 server

### ISSUE THREAD

**Issue by zannapzg** [ViaVersion/ViaVersion#2353]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?

**How can we reproduce it?**
1. Login on 1.12'
3. The '....' is displayed wrong

**Expected behaviour**

**Screenshots**

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Checklist**
- [ ] I have included a Viaversion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error

**Comment by KennyTV** [comment]
Fill out the issue template.
