### ISSUE TITLE
1.16 visive bug on a 1.12.2 server

### ISSUE THREAD

**Issue by zannapzg** [ViaVersion/ViaVersion#2354]
**Describe the bug, provide any errors**
Hi, I'm opening bedwars on my server .. and I have encountered a problem resetting the waiting lobby.. Instead in 1.16 some stairs/fences will appear, clicking with the right button will disappear ..
In short, a visual bug
I think this bug is also there with 1.13 or higher, I only tried with 1.16

**How can we reproduce it?**
1. Login with a 1.16 in a 1.12.2 server
2. Make a selection of block with WorldEdit (for example) and reset them
3. With 1.12.2 client or lower the selection will be clear, fine without any blocks..

**Screenshots**
The waiting lobby before the reset
![before](https://user-images.githubusercontent.com/61860483/108270148-55386580-716f-11eb-9175-28185742bd65.png)

The waiting lobby after the reset [with 1.12.2]
The lobby will appear perfectly reset
![after  1 12 2](https://user-images.githubusercontent.com/61860483/108270345-9c265b00-716f-11eb-9c26-c26a73a2686b.png)

The waiting lobby after the reset [with 1.16.4]
The lobby does not look good, buggy blocks remain
![after  1 16 4](https://user-images.githubusercontent.com/61860483/108270458-c37d2800-716f-11eb-989b-27f2b22b1921.png)

**ViaVersion Dump**
https://pastebin.com/RjZNWW6H

**Additional server info**
I use Waterfall

**Checklist**
- [ ] I have included a Viaversion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I don't have tried a build from https://ci.viaversion.com

- Sorry for my bad english

**Comment by Xernium** [comment]
Please follow the issue template. You didn’t do the checklist. Please follow the checklist and open a new issue if you still have your problem then.
