### ISSUE TITLE
loading terrain when swtich server

### ISSUE THREAD

**Issue by Dreeam-qwq** [ViaVersion/ViaVersion#2357]
**Describe the bug, provide any errors**
When player switchs to the main server(1.16.5) from the login server(1.12.2),the screen shows "loading terrain" for a long time.

**How can we reproduce it?**
1. Login on 1.12.2 login server
2. execute "/send player winds" in console to go to the main server(1.16.5)
3. The screen display "loading terrain" for a long time.

**Expected behaviour**
There is no error message in proxy and main server.
in the login server, there is one info when player login.
[18:26:31 WARN]: [ViaVersion] Ignoring plugin channel in incoming REGISTER: legacy:fml|hs

**Screenshots**

![loading rerrain.png](https://i.loli.net/2021/02/19/m3rjvbSk5dtsEX6.png)

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.
proxy viaver dump: https://dump.viaversion.com/1ef40ebf8a376c85d1e42558ebbb362fe99dd27aed9f45c1af676120994ec6c5

**Additional server info**
Proxy: Waterfall #395
login server: paper-1.12.2-1618
main server: purpur 1.16.5
all server have the viaversion,viarewind,viabackwards plugin
ViaBackwards-3.3.0-21w05b
ViaRewind-1.5.3
ViaVersion-3.3.0-21w05b

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Remove Via plugins from the proxy, it should only be on either proxy or backend
