### ISSUE TITLE
kicks from the server from the client 1.16+ on the core 1 12 2

### ISSUE THREAD

**Issue by DenisJ9798** [ViaVersion/ViaVersion#2359]
Describe the bug, provide any errors
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?

How can we reproduce it?

Login on 1.16+'
Join the server.
Expected behaviour
No error.

**Video**
https://drive.google.com/file/d/1SgTn8O69Ht2XHK0_Pb6cVyQsjMo0Wzbu/view?usp=sharing

ViaVersion Dump

https://dump.viaversion.com/b2b915fb6dec2c1529df8547f173cd003822049c2046ca8d14d7497856a5151c

Additional server info
Bungeecord but am not using it on the bungeecord itself the plugin just the hub and sub servers and it's the latest dev build as of 21 jan

Checklist

[ v] I have included a Viaversion dump
[ v] If applicable, I have included a paste (not a screenshot) of the error
[ v] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
We need the error.

**Comment by DenisJ9798** [comment]
> We need the console error.

there are no errors in the console, there is just disconnect

**Comment by KennyTV** [comment]
Then it likely comes down to a mistake in setup, you can join our Discord to get support with that https://viaversion.com/discord
