### ISSUE TITLE
1.16 visive block bug on 1.12.2 server

### ISSUE THREAD

**Issue by zannapzg** [ViaVersion/ViaVersion#2363]
**Describe the bug, provide any errors**
Hi, I'm opening bedwars on my server .. and I have encountered a problem resetting the waiting lobby.. Instead in 1.16 some stairs/fences will appear, clicking with the right button will disappear ..
In short, a visual bug
I think this bug is only for 1.16 clients

**How can we reproduce it?**
1. Login with a 1.16 in a 1.12.2 server
2. Make a selection of block with WorldEdit (for example) and reset them
3. With 1.8 / 1.9 / 1.10 / 1.11 / 1.12 / 1.13 / 1.14 / 1.15 client, fine without any blocks..

**Expected behaviour**
I expected to have the lobby cleared and without fence/stairs

**Screenshots**
The waiting lobby before the reset
![before](https://user-images.githubusercontent.com/61860483/108270148-55386580-716f-11eb-9175-28185742bd65.png)

The waiting lobby after the reset [with 1.12.2]
The lobby will appear perfectly reset
![after  1 12 2](https://user-images.githubusercontent.com/61860483/108270345-9c265b00-716f-11eb-9c26-c26a73a2686b.png)

The waiting lobby after the reset [with 1.16.4]
The lobby does not look good, buggy blocks remain
![after  1 16 4](https://user-images.githubusercontent.com/61860483/108270458-c37d2800-716f-11eb-989b-27f2b22b1921.png)

**ViaVersion Dump**
https://dump.viaversion.com/7675003fd06c786d6453b82cceabd4359fc4cef3039fc618b8033827bfe90e52

**Additional server info**
I'm using Paper 1.12.2 with ViaVersion, ViaRewind and ViaBackwards on a proxy with Waterfall!

**Checklist**
- [✅] I have included a Viaversion dump
- [✅] If applicable, I have included a paste (not a screenshot) of the error
- [✅] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by krusic22** [comment]
Solved by setting blockconnection-method to world.
