### ISSUE TITLE
"ViaUpdate" (Automatic ViaVersion Updater)

### ISSUE THREAD

**Issue by WolfyRed** [ViaVersion/ViaVersion#2366]
**Is your feature request related to a problem? Please describe.**
ViaVersion doesn't automatically update, you have to download updates from Jenkins server manually every Minecraft Java update.

**Describe the solution you'd like**
ViaVersion checking for updates automatically every few hours, optionally configurable within a `config.yml` file.

**Describe alternatives you've considered**
Downloading `ViaVersion-DEV` so the newer versions like 1.17 can join when 1.17 releases.   *(It disables ViaRewind from working in case you couldn't tell.)*

**Which versions is this for?**
1.17, 1.18, 1.19, 1.20, and 1.21

**Comment by FormallyMyles** [comment]
https://github.com/ViaVersion/ViaVersion/issues/317#issuecomment-211128526

**Comment by WolfyRed** [comment]
> [#317 (comment)](https://github.com/ViaVersion/ViaVersion/issues/317#issuecomment-211128526)

Do you know what the extra files in the Jenkins are for, if you're a moderator?  EX: "ViaVersion-gradle"

**Comment by FormallyMyles** [comment]
> > [#317 (comment)](https://github.com/ViaVersion/ViaVersion/issues/317#issuecomment-211128526)
> 
> Do you know what the extra files in the Jenkins are for, if you're a moderator? EX: "ViaVersion-gradle"

The extra files are just build outputs from other modules, they don't generally work properly because of how they're built. So you just want the ViaVersion-1.X.X.jar
