### ISSUE TITLE
Commands for which you don't have access are listed in auto-completion

### ISSUE THREAD

**Issue by ZeProf2Code** [ViaVersion/ViaVersion#2367]
**Describe the bug, provide any errors**
Commands for which you don't have access are listed in auto-completion.

**How can we reproduce it?**
1. Login on any version
2. Start typing /via
3. Sees that the commands are auto-completed even if you don't have the permission to execute them.

**Expected behaviour**
The commands are not shown in the auto-completion if you don't have the permission to execute them.

**Screenshots**
![image](https://user-images.githubusercontent.com/32982428/109170322-f5e6e080-7780-11eb-849d-5b3a98edb15c.png)

**Additional server info**
Waterfall - Paper

**Checklist**
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
This is down to whatever platform you're using to block it, you can disable tab complete in most platforms but it's a known thing that by default it's not checked for permissions unless i'm missing something.

**Comment by ZeProf2Code** [comment]
@FormallyMyles This can be easily fixed by putting `viaversion.admin` in the `permission` field of the Command constructor (https://github.com/ViaVersion/ViaVersion/blob/master/bungee/src/main/java/us/myles/ViaVersion/bungee/commands/BungeeCommand.java#L11). Why not using it? It's a required permission for all the subcommands, no?

**Comment by FormallyMyles** [comment]
> @FormallyMyles This can be easily fixed by putting `viaversion.admin` in the `permission` field of the Command constructor (https://github.com/ViaVersion/ViaVersion/blob/master/bungee/src/main/java/us/myles/ViaVersion/bungee/commands/BungeeCommand.java#L11). Why not using it? It's a required permission for all the subcommands, no?

While you're right that it is a good suggestion for Bungee, you understand that won't fix your issue because you have Via on Bukkit?

**Comment by ZeProf2Code** [comment]
Yes I know, for Bukkit you would have to put the permission directly in the `plugin.yml` file but I think that if you don't use it, there are reasons, aren't there?

**Comment by ZeProf2Code** [comment]
@FormallyMyles It seems that the modification of my message did not notify you. Sorry if you were notified twice.
