### ISSUE TITLE
viaversion error :/

### ISSUE THREAD

**Issue by captainJLM0815** [ViaVersion/ViaVersion#2370]
I have a 1.13 server with viaversion so that you can join with upper minecraft version but when i try to join on my server the server will say say and i dont knwo how to fix it.

PLZ help me :)

![Unbenannt](https://user-images.githubusercontent.com/79357120/109330396-e7b9c280-785b-11eb-84b7-8e7539084241.PNG)

**Comment by KennyTV** [comment]
Follow the issue template.

**Comment by captainJLM0815** [comment]
can i fix this error or am i only allowed to join with 1.13 ?

**Comment by KennyTV** [comment]
Create a new issue, don't remove the text that appears when creating the issue, fill out what it asks of you, and maybe we can help you.
