### ISSUE TITLE
ViaVersion breaking and throwing error to console upon start up. (21w08b / DEV branch)

### ISSUE THREAD

**Issue by xNitrate** [ViaVersion/ViaVersion#2373]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?
Paste: https://paste.gg/p/anonymous/020fbea88d5844fd9e8627ea533dae5f
I am trying to load the latest ViaVersion from the DEV branch onto my server. I load it in and it throws this error. It still "loads", but I cannot connect how I normally would with it from before 21w08a/b.

I suspect that it is due to the new 1.17 login system things that they added, but I do not know.

Via Dump: https://dump.viaversion.com/e290f629dcfb74268d2c69004024aa5f620a72c6927512f963cbae1fc9ca77c7

**How can we reproduce it?**
1. Download the most recent file (at the moment) from https://ci.viaversion.com/job/ViaVersion-DEV/
2. Put in plugins
3. Restart
4. Review problem.

**Expected behaviour**
I expected it to load properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/23089955/109402714-ff5d7d80-7925-11eb-8c6a-a2d7c67d9500.png)
Above you can see I cannot connect to via 1.16.5.

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
This is on BungeeCord and I use these plugins:
![image](https://user-images.githubusercontent.com/23089955/109402832-03d66600-7927-11eb-9a9f-f9a0f4d5f063.png)

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Fixed with https://github.com/ViaVersion/ViaVersion/commit/6e9e757294085a7bf0594f8a8295c6df46f39d16
