### ISSUE TITLE
Error 1.9.4 login on 1.16.5 server.

### ISSUE THREAD

**Issue by Divalo** [ViaVersion/ViaVersion#2377]
I cannot connect to my server in 1.9.4, my server is using Tuinity so version 1.16.5, ViaVersion and ViaBackwards are installed.

Here is the link to the error: https://paste.helpch.at/ayabozamay.md

Thanks you.

**Comment by KennyTV** [comment]
Please do not delete the text that appears when creating the issue and provide all the information it asks of you.

**Comment by Divalo** [comment]
There is no other information to give.

**Comment by Camotoy** [comment]
There actually is! Here's what would help the ViaVersion team out:

- Specifically when does this bug happen?
- How can someone else reproduce it?
- Type `/viaversion dump` in your server console, and paste the link it gives you here.
- Do you use BungeeCord?
- Have you tried a build from https://ci.viaversion.com/?
