### ISSUE TITLE
readme.md supported version unreadable in GitHub dark mode

### ISSUE THREAD

**Issue by xknat** [ViaVersion/ViaVersion#2379]
i don't use to light mode on github and and its hard to read supported versions because of it
![image](https://user-images.githubusercontent.com/10220139/109653010-c1986900-7b60-11eb-8532-25d3fe640e27.png)
Maybe you can lighten it a bit up? :P

**Comment by KennyTV** [comment]
Already did! ~~currently in the dev branch because effort:tm: tho~~, it will be visible to everyone with 1.17 https://github.com/ViaVersion/ViaVersion/tree/dev#viaversion---spigot-sponge-bungeecord-velocity
