### ISSUE TITLE
Merge all via projects into one

### ISSUE THREAD

**Issue by Milo123459** [ViaVersion/ViaVersion#2380]
**Is your feature request related to a problem? Please describe.**
no
**Describe the solution you'd like**
Merge `ViaVersion`, `ViaBackwards` and `ViaRewind` into `ViaVersion`.
**Describe alternatives you've considered**
installing all plugins
**Which versions is this for?**
Does the feature apply to any specific versions? If so put them here.
n/a

**Comment by KennyTV** [comment]
The 3 plugins have vastly different use cases as well as internals and aren't built to have independent loading (meaning just slapping them together would still load all ViaBackwards mappings and resources, even on a 1.9 server). They also all have a slightly  different set of maintainers.
