### ISSUE TITLE
1.12 -> 1.16.5

### ISSUE THREAD

**Issue by 849025143** [ViaVersion/ViaVersion#2381]
spigot+waterfall can work
spigot+BungeeCord can't work
paper+waterfall can't work
paper+BungeeCord can't work
[carsh.txt](https://github.com/ViaVersion/ViaVersion/files/6073489/carsh.txt)

**Comment by Xernium** [comment]
You need to actually fill out the issue template instead of deleting it. Please follow the issue template and open a new issue.
