### ISSUE TITLE
Shulker Remapp Error

### ISSUE THREAD

**Issue by FlorianMichael** [ViaVersion/ViaVersion#2385]
**Describe the bug, provide any errors**
If you try to give yourself a shulker with ViaFabric 1.16 on a 1.12 server (set in VV Protocol 1.12) then this shulker will be changed to Stone.

**How can we reproduce it?**
1. Start ViaFabric 1.16
2. Select 1.12 Protocol
3. Go On a 1.12 Server
4. Try to give Shulker in Creative

**Expected behaviour**
The shulker is then replaced to a stone

**Screenshots**
/

**ViaVersion Dump**
/

**Additional server info**
Spigot 1.12 Server without any Plugins

**Checklist**
- [ ] I have included a Viaversion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Colorless shulker boxes didn't exist in 1.12

**Comment by FlorianMichael** [comment]
https://ibb.co/F5yRfc4

They exist in 1.12

**Comment by KennyTV** [comment]
Those aren't colorless shulkers, but I got it the wrong way around anyways, sorry! Please use dev builds from the ci, as I can't reproduce this issue locally, otherwise please try with Via on the server instead of the client and create a new issue with a dump.

**Comment by FlorianMichael** [comment]
I have the latest Version, if you want i can show you what i mean on Discord: EnZaXD#6257
