### ISSUE TITLE
User muematter has disconnected, reason: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues

### ISSUE THREAD

**Issue by muematter** [ViaVersion/ViaVersion#2388]
i need help

what does this mean and why is it hapening

**Comment by Xernium** [comment]
Please follow the issue template instead of deleting it.

**Comment by muematter** [comment]
wdym xernium

**Comment by Xernium** [comment]
You created an issue that had an issue template already in the text box. You deleted that that to put in your text. Please take the time to go through it and provide the information it asks for as well as try the steps it recommends.
