### ISSUE TITLE
Waterfall reports base as 1.8.x, when it is 1.16.5

### ISSUE THREAD

**Issue by Doregon** [ViaVersion/ViaVersion#2394]
**Describe the bug, provide any errors**
I followed all the steps to run ViaVersion on my Waterfall server, making sure not to install it on each server directly but rather the proxy. **I know 1.16.4 can communicate with 1.16.5, this is just me preparing for 1.17 and making sure all of my stuff is ready.** Simply put: ViaVersion initializes with `[ViaVersion]: ViaVersion detected server version: 1.8.x (47)` when it's actually supporting two 1.16.5 servers, which is stated by adding `754` as the default protocol version number.

**How can we reproduce it?**
1. Install ViaVersion on a Waterfall proxy
2. ~~Profit~~ ViaVersion says it's initialized for 1.8

**Expected behaviour**
It says `[ViaVersion]: ViaVersion detected server version: 1.16.4 (754)`

**ViaVersion Dump**
/viaversion dump -> https://dump.viaversion.com/83a18bbc9692e33a95037e0ca7e5c6ead04c9b252f019dbe2b7e3b4e647067a7
Waterfall log -> https://paste.gg/p/anonymous/70008281487b46ff931402363d9a82ed

**Additional server info**
Waterfall
GeyserMC and Floodgate
ViaVersion
SkinsRestorer
LuckPerms

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
That log line doesn't matter, it just prints it the *lowest* supported version in the case running on a proxy - we might make the message clearer, but it's not a "bug" as is.
