### ISSUE TITLE
i am getting this error when i join my minecraft server because of viaversion this is the issue  Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException

### ISSUE THREAD

**Issue by shubhgehlot** [ViaVersion/ViaVersion#2396]
*Please fill in this template rather than deleting it*

**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?

**How can we reproduce it?**
1. Login on 1.12'
3. The '....' is displayed wrong

**Expected behaviour**

**Screenshots**

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Checklist**
- [ ] I have included a Viaversion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Follow the issue template.
