### ISSUE TITLE
Bug Bug for many player

### ISSUE THREAD

**Issue by Divalo** [ViaVersion/ViaVersion#2397]
*Please fill in this template rather than deleting it*

**Describe the bug, provide any errors**
2/3 players out of the 75 of my server crash as soon as it arrives on the server, I have no idea why, they are using Pactify and AzLauncher.

**How can we reproduce it?**
I dont no

**Expected behaviour**
Some player crash when join the server.

**Screenshots**
https://media.discordapp.net/attachments/762015720137162772/820349858204352532/1viaversionfivesky.PNG?width=1440&height=87

**ViaVersion Dump**
https://dump.viaversion.com/b614630bea5298f5e7d761f0f5c042fdc3dd73660fa48110da30d70784026817

**Additional server info**
I use LightSpigot (Fork of Tuinity) and ViaVersion with ViaBackwards

Thanks

**Comment by KennyTV** [comment]
Please see if this still happens on regular Paper/Tuinity, otherwise we also need the error that's printed in the console. Also make sure not to run Via on both proxy and backend, but only one of them.

**Comment by Divalo** [comment]
> Please see if this still happens on regular Paper/Tuinity, otherwise we also need the error that's printed in the console. Also make sure not to run Via on both proxy and backend, but only one of them.

I use ViaVersion and ViaBackwards only is spigot server, no on velocity.
For the full error : https://paste.helpch.at/isocufemod.md

**Comment by FormallyMyles** [comment]
If you could test this with 4.0.0, otherwise enable debug=true and provide the full error. Quite a bit changed in 4.0.0 so this *fingers crossed* might be fixed. Otherwise, we'll need the error and potentially the NBT for the item that causes it, might be special enchants or something like that as a guess.

Will happily reopen when we can replicate :)
