### ISSUE TITLE
ViaVersion Broken Pipe

### ISSUE THREAD

**Issue by HandyHat** [ViaVersion/ViaVersion#2400]
**Describe the bug, provide any errors**
No issues were noticed as no-one was online but this error appeared in console and said to report: https://paste.gg/p/anonymous/f9f9000a59944147911f8514ce1003f4

**How can we reproduce it?**
Not sure how to reproduce - first time this as happened

**Expected behaviour**
No error to appear

**ViaVersion Dump**
- https://dump.viaversion.com/3bf85bdd1303acf1805041d99aad60dde5d35e52433676eeab33a1247b159d83

**Additional server info**
`This server is running Paper version git-Paper-546 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`

`Plugins (52): AcceptTheRules*, ActionAnnouncer, ActionHealth*, AdvancedReplay*, AntiSeedCracker, ClearLag, ConsoleSpamFix, CoreProtect, DiscordSRV, dynmap*, eZProtector, floodgate-bukkit, Geyser-Spigot, GeyserSkinManager, GeyserUpdater, GSit, GtzDoors, HamsterAPI*, HolographicDisplays, IllegalStack, ImageOnMap, InteractiveChat, InteractiveChatDiscordSRVAddon, Inventory*, InventoryRollback, Lasso, LuckPerms, MagicBucket, Maintenance, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, NoAFKFishing*, OpenInv, PetMaster, PlaceholderAPI, PrivateMessages, ProtocolLib, SAML, Shopkeepers, SkinsRestorer, SuperVanish, TAB, TradeShop, UltimateHealAndFeed*, Vault, ViaBackwards, ViaVersion, WorldEdit, WorldGuard, WorldGuardExtraFlags`

This error appeared overnight and the only thing happening on the server was a dynmap render

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists - cannot do this as not sure how to reproduce 😛

**Comment by KennyTV** [comment]
Someone is sending bad packets, not much we can do about that. ViaVersion un-hides those errors, but we can't fully distinguish between willfully bad data and errors on our part, so we always have to show them.

**Comment by HandyHat** [comment]
Ah ok. Thanks 👍🏾
