### ISSUE TITLE
Support for riding horses on 1.8.9

### ISSUE THREAD

**Issue by Gargant0373** [ViaVersion/ViaVersion#2402]
**Is your feature request related to a problem? Please describe.**
If the server version is 1.9+ horse riding doesn't work for 1.8.9.

**Describe the solution you'd like**
Make it be able to ride horses on 1.8.9.

**Which versions is this for?**
1.8.9

**Comment by KennyTV** [comment]
ViaRewind issue, but not possible without server modifications.
