### ISSUE TITLE
Netherite Armor and tools turned into stone

### ISSUE THREAD

**Issue by lioncraftmc** [ViaVersion/ViaVersion#2404]
I tried Via Version On My 1.13 or 1.12 Version Minecraft Paper Server. I had my server 1.16.5 before but I changed it into 1.12 because I found a lag fix forum and they said in 1.13 many new things came so servers were not optimized. I tried Via Version Plugin on my server and I executed my game on 1.16.5 and I took Netherite armor and tools and they suddenly turned into **Stone**. I dont know if I was doing wrong or this plugin has this bug. So Please If It Is Plugin Issue Then Fix it or If I am doing wrong so please tell me!!!

Thanks,
Universal Gamerz (lioncraftmc)

**Comment by Blocksnmore** [comment]
1. Use the format instead of deleting it.
2. Turning netherite into stone is normal since 1.12/1.13 don't have support for items added in newer versions like 1.16

**Comment by lioncraftmc** [comment]
Than any  other plugin?

**Comment by KennyTV** [comment]
If you want netherite armor, update your server to 1.16

**Comment by lioncraftmc** [comment]
No I want my server to 1.12 because many plugins are out dated but if there is no other solution then its ok.. I wanted NPC plugin its out dated in aternos
