### ISSUE TITLE
Ender pearls doesn't work in 1.16.5

### ISSUE THREAD

**Issue by EfrenB** [ViaVersion/ViaVersion#2405]
**Describe the bug, provide any errors**
ender pearls can't launch in version 1.16.5 maybe other 

**How can we reproduce it?**
1. Login on 1.16.5'
2. create a world
3. launch the ender pearl

**Expected behaviour**
nothing only the ender pearld dont work

**Screenshots**
https://www.youtube.com/watch?v=CtgOvt7PqdY

**ViaVersion Dump**
- https://dump.viaversion.com/836456402a3371fbb0eca799ed7cef8f3ac3624545cb14b2e09d55f83fafda2c

**Additional server info**
paper spigot on this server

**Comment by KennyTV** [comment]
1.8 servers don't allow for ender pearls to be thrown in creative mode, that's a newer feature.
