### ISSUE TITLE
Bungee Java 16 compatibility and injector cleanup

### ISSUE THREAD

**Issue by kennytv** [ViaVersion/ViaVersion#2414]
The Bungee injector has stopped working with Java 16 given final field modification hacks. We need to either somehow inject into th child handler in the `ServerBootstrap` instances or pr a small hack to Bungee/Waterfall for injection without reflection.

In general, all injectors could use a little cleanup. ☠

Check-list:

- [x] 1.16 Compatibility
- [ ] Injector clean-up

**Comment by retrooper** [comment]
fax

**Comment by retrooper** [comment]
Is it only the Bungee injector that stopped working? I thought the Bukkit injector aswell.

**Comment by Proximyst** [comment]
For the sake of tracking, the `final` Java 16 incompatibility is being handled in #2433. This however is in the form of a rather (`sun.misc.`)Unsafe way, and may break at any point in the future as it depends on JRE implementation detail (which is luckily honoured by every major JRE vendor).

A change in Paper and Waterfall to avoid such hacks might be necessary, and would be very helpful no matter what happens in the future with the development of Java. So-called "internal APIs" (read: public implementation detail we [PaperMC] "promise" we'll keep) have a fair chance of being accepted, at least a much higher chance than proper public API.
