### ISSUE TITLE
Bridging in 1.8.8 

### ISSUE THREAD

**Issue by Cryptics1999** [ViaVersion/ViaVersion#2421]
### '/viaversion dump' Output

https://dump.viaversion.com/4bfe1aa76cd262934b16081ef3d145d0508bba9119415862b167961d632227a5

### Bug Description

Hey, If I play on any version above 1.8.8 like 1.9-1.16.* when briding the blocks get placed where the player is

### Steps to Reproduce

Login with a 1.16.5 Client
Play on a 1.8.8 Server with Viaversion
Bridge quickly. Blocks get placed where you stand

### Expected Behavior

Block will be placed on your standing position

### Additional Server Info

I use a proxy, and my server jar is Stellar Spigot. I use no plugin wich will affect this then ViaVersion

### Checklist

Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
I have included a ViaVersion dump.
If applicable, I have included a paste (**not a screenshot**) of the error.
I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
See https://github.com/ViaVersion/ViaVersion/issues/1087
