### ISSUE TITLE
[1.16.5] custom minecart blocks don't work properly

### ISSUE THREAD

**Issue by Miv2nir** [ViaVersion/ViaVersion#2422]
### '/viaversion dump' Output

https://dump.viaversion.com/095411e3bdcdf81e5fe27f60330f80af08f478aca5475a72b9365c1d2aaaf235

### Bug Description

**Describe the bug, provide any errors**
On minecraftonline.com server, in the community server there is a sea lantern riding around and a cake, both are entities. However, when joining with viafabric or viaaas, the lantern turns into red stained glass pane, and the cake appears as a soul torch for some reason. (The cake doesn't appear at all for me with viaaas + geyser)

It happens on both viaFabric and Viaaas

![2021-04-08_15 39 07](https://user-images.githubusercontent.com/70204046/114113746-11005080-98e8-11eb-9341-d3b6c19cada3.png)
![2021-04-08_14 29 54](https://user-images.githubusercontent.com/70204046/114113767-1b224f00-98e8-11eb-8f97-70a4d098c5c1.png)
![Screenshot_20210409-035003_Minecraft](https://user-images.githubusercontent.com/70204046/114113778-21b0c680-98e8-11eb-869c-df27836c0c90.png)
![Screenshot_20210409-035022_Minecraft](https://user-images.githubusercontent.com/70204046/114113796-2d9c8880-98e8-11eb-8284-711f0f0b7ddf.png)

### Steps to Reproduce

1. Login to minecraftonline.com using viaFabric or viaaas'
2. Go through the rules chamber to the spawn area
3. Enter the community center and observe the bugged entities.

### Expected Behavior

There should be a sea lantern riding around the building and a smaller sized cake as an entity near the entrance. Login with 1.12.2 to see how it's meant to be seen

### Checklist

Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
I have included a ViaVersion dump.
If applicable, I have included a paste (**not a screenshot**) of the error.
I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Please try reproducing this on a local testserver, as there's no good way for us to look into such an issue on external servers with possibly magic plugins and software, so we need a way to cleanly reproduce this on our own.

**Comment by creeper123123321** [comment]
Hypothesis: server may be using cake block (id 92) as an item. It isn't present on mapping so it's mapped wrongly

**Comment by creeper123123321** [comment]
Found the entity type: aff['Minecart with Sea Lantern'

**Comment by Miv2nir** [comment]
https://user-images.githubusercontent.com/70204046/114191378-0203b780-9955-11eb-96f2-4527b34fa682.mp4

/summon minecart ~ ~ ~ {CustomDisplayTile:1,DisplayTile:sea_lantern,DisplayOffset:0}
