### ISSUE TITLE
Failed to get 1.13 item for 383

### ISSUE THREAD

**Issue by andreasdc** [ViaVersion/ViaVersion#2423]
### '/viaversion dump' Output

-

### Console Error

-

### Bug Description

Monster eggs are shown as stone, for example on 1.16.5. How to fix that? The newet viaversion, viarewind and viavrewind legacy support. 1.8 server.

### Steps to Reproduce

-

### Expected Behavior

-

### Additional Server Info

BungeeCord

### Checklist

Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
I have included a ViaVersion dump.
If applicable, I have included a paste (**not a screenshot**) of the error.
I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
You likely tried taking an item that doesn't exist in 1.8, that's all I can say from the little info given.

**Comment by andreasdc** [comment]
@KennyTV MONSTER_EGG, I create item using bukkit api.

**Comment by andreasdc** [comment]
@KennyTV there's this item on 1.8: MONSTER_EGG(383, 64, SpawnEgg.class)

**Comment by KennyTV** [comment]
Uh while that data value ""works"" it doesn't correspond to an actual, usable/listed (!) item, even in 1.8.

**Comment by andreasdc** [comment]
@KennyTV how to operate with monster eggs then?

**Comment by KennyTV** [comment]
Easy: Don't create spawn eggs with data values that don't (properly) exist (https://www.minecraftinfo.com/idlist.htm)

**Comment by andreasdc** [comment]
@KennyTV all right, I found the issue. Thanks for help! :)
