### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by samurai-hearts** [ViaVersion/ViaVersion#2425]
### '/viaversion dump' Output

https://dump.viaversion/com/dcc0d424a00badfbcd6f3c46a05a1d6e9923b39f0f65b49ca3bccf25f94784b2

### Console Error

```
https://paste.gg/p/anonymous/975b0d174db0477f98005632f483bb6e
```

### Bug Description

Unknown if there is a bug. This warning appeared in my server console last night and I have no idea what it means. It told me to post the error here so I'm hoping someone will be able to help? (If I'm honest I didn't even know this was a thing, I am new to running a server!) EDIT: Just checked our resource analytics, the server usually uses about 1GB RAM whilst idle but since the 7th it has been using over 2GB whilst idle. Don't know if this is related as the error appeared afterwards

### Steps to Reproduce

Unknown

### Expected Behavior

Unknown

### Additional Server Info

Paper 1.16 (latest) with Geyser and Floodgate

### Checklist

Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
I have included a ViaVersion dump.
If applicable, I have included a paste (**not a screenshot**) of the error.
I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Someone is sending bad ping packets, not much we can do about that.
