### ISSUE TITLE
Custom Inventories on 1.12.2 Spigot Server

### ISSUE THREAD

**Issue by Retr0G28** [ViaVersion/ViaVersion#2427]
### '/viaversion dump' Output

https://dump.viaversion.com/2c4fd6135c699482926e9aec47cdcee1d474aa694bd7fd6c0f818f733faef47c

### Console Error

https://paste.gg/p/anonymous/7d4e8d99d9b141c9acb8b2f5abfdec17

### Bug Description

Opening a custom inventory made by my plugin will cause this issue.

After I try to open it, I get imediattely kicked out of the server.

### Steps to Reproduce

1. Login with a 1.16.5 Client (I'm using Badlion) on a 1.12.2 Server
2. Have a custom inventory made (You can test it on my server if you want)
3. Try to open it and see the magic stuff.

### Expected Behavior

Inventory should get opened without the player getting kicked out.

### Additional Server Info

I'm using BungeeCord, but I don't have ViaVer on it.

### Checklist

Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
I have included a ViaVersion dump.
If applicable, I have included a paste (**not a screenshot**) of the error.
I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Updating to -dev builds from https://ci.viaversion.com/ will likely fix it, otherwise we will reopen this.
