### ISSUE TITLE
Protocol1_13To1_12_2 IN REMAP OF CHAT_MESSAGE (0x0F) Error

### ISSUE THREAD

**Issue by pacebesteu** [ViaVersion/ViaVersion#2428]
### '/viaversion dump' Output

https://dump.viaversion.com/b894fa24260c27b202a7a2477a1b084f90c4a770809118a14a7e05c9b0e3cadf

### Console Error

https://haste.jartexnetwork.com/itoraragihipoqim.yaml

### Bug Description

https://youtu.be/Oy78s_3CSh8

### Steps to Reproduce

If you use an item name with \\\\\ inside it with and if you use show_item in main chat, people in version 1.16 will crash.

### Expected Behavior

.

### Additional Server Info

This issue was created before by the same server, but we have no clue how we could resolve it.

### Checklist

Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
I have included a ViaVersion dump.
If applicable, I have included a paste (**not a screenshot**) of the error.
I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Update to dev builds from https://ci.viaversion.com/
