### ISSUE TITLE
1-16.4 client to 1.13.2 server "Incomplete set of tags"

### ISSUE THREAD

**Issue by nmills3** [ViaVersion/ViaVersion#2435]
### '/viaversion dump' Output

https://dump.viaversion.com/f7ac26580fdc39fe30b74ba2dd56db09a6e6c4534a3feb78d243d4a9c137ec20

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Joining a 1.13.2 server running viaversion ViaVersion-3.2.1 using the 1.16.5 client gives the error "Incomplete set of tags received from server. Please contact server operator." server is running spigot 1.13.2 and the spread 2 map found [here](https://www.minecraftmaps.com/game-maps/spread-2)

### Steps to Reproduce

1. Create a spigot 1.13.2 server
2. Load [this ](https://www.minecraftmaps.com/game-maps/spread-2) map onto the server
3. Join with a 1.16.5 client

### Expected Behavior

You should join the server

### Additional Server Info

only plugin is viaversion 3.2.1, issue happens both with and without bungeecord

### Checklist

Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
I have included a ViaVersion dump.
If applicable, I have included a paste (**not a screenshot**) of the error.
I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
The map likely uses datapacks to replace Vanilla tags, which it shouldn't do without somehow re-filling them.

**Comment by nmills3** [comment]
If it's just an issue with the map then shouldn't it be broken in every version of the game? because joining in any version from before 1.16 using viaversion to 1.13.2 works perfectly. it's only on 1.16+ clients that you get the error

**Comment by KennyTV** [comment]
Mojang started fully enforcing it only a bit later, but they already warned about replacing tags before. So the benefit is rather small vs. the effort required in checking for every single tag added up until 1.13/14

**Comment by nmills3** [comment]
ah ok, thanks for the info
