### ISSUE TITLE
Once again - fence bug...

### ISSUE THREAD

**Issue by kamziksvk** [ViaVersion/ViaVersion#2439]
### '/viaversion dump' Output

https://dump.viaversion.com/e518497773199b16bbee61a7559ba3ae29b2cfb2de49b3f72f5013b9460b58e2

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/66fa119ed05046cbb0b4da8f667d02bd

### Bug Description

Hello, we have decided to resolve long-term bug on our server with connecting fences. We have tried to enable:

serverside-blockconnections: true
reduce-blockstorage-memory: true
flowerstem-when-block-above: false
vine-climb-fix: true

### Steps to Reproduce

Our Survival server runs on 1.16.5 version, but our RPG and lobby server runs on 1.12.2. the problem is when we try to connect to the RPG server with 1.16.5 client we have an error message mentioned above.

### Expected Behavior

Fences on RPG server should be connected on client version 1.16.5, not only in 1.12.2

### Additional Server Info

ViaVersion plugin is running on bungeecord only.

Thank you for your patience and help.

### Checklist

Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
I have included a ViaVersion dump.
If applicable, I have included a paste (**not a screenshot**) of the error.
I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by FormallyMyles** [comment]
If you move ViaVersion from bungee to backend servers does that change anything?

**Comment by kamziksvk** [comment]
Tried, it worked on lobby server, not working on RPG server (1.12.2 server). Better option should be to set it up at the proxy.

**Comment by FormallyMyles** [comment]
Proxy level ViaVersion is always inferior, try block connection method world in the config

**Comment by KennyTV** [comment]
Set `reduce-blockstorage-memory` to false if you want *everything* to properly connect
