### ISSUE TITLE
1.16 Block Placing Glitch

### ISSUE THREAD

**Issue by GamingMichaelTMAA** [ViaVersion/ViaVersion#2443]
### '/viaversion dump' Output

https://dump.viaversion.com/aa55d2d1dead543f9454a45f2c5f11fee7d18a48c556de623f0b33a0329cac6b

### Console Error

Its not in console

### Bug Description

On my server. I run Viaversion on my bungeecord and all my servers run 1.8. If I join on 1.16 and go to build or bridge by holding right click it will click blocks into you.

### Steps to Reproduce

Example:
1. I go onto my server on 1.16
2. I go to build a bridge by holding right click
3. It places blocks through you
Also: 
1. Holding right click on sword on 1.16 slows you down but does not pop up a shield
2. Not that big of a deal but just thought I would mention it
Here Are Two Videos
Me playing On 1.16: https://youtu.be/F0FlpUa3McQ
Me playing on 1.8: https://youtu.be/pNvxXuRpn8E
The glitch doesn't happen on 1.8

### Expected Behavior

The blocks should place normaly and sheild should pop up on 1.9 and above clients

### Additional Server Info

I use bungeecord  with most of my servers being 1.8

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Update to -DEV builds on https://ci.viaversion.com/, otherwise see the pinned issue.

**Comment by GamingMichaelTMAA** [comment]
@KennyTV > Update to -DEV builds on https://ci.viaversion.com/, otherwise see the pinned issue.

I did. I actually clipped it on the dev build.

**Comment by RaphiMC** [comment]
What server software are the 1.8 servers running? PaperSpigot maybe?

**Comment by GamingMichaelTMAA** [comment]
@RaphiMC Yes i run PaperSpigot 1.8.8

**Comment by RaphiMC** [comment]
Then you should put all Via plugins on each backend server and remove them from the bungee.
