### ISSUE TITLE
Spawning custom creature error

### ISSUE THREAD

**Issue by andreasdc** [ViaVersion/ViaVersion#2445]
### '/viaversion dump' Output

not needed

### Console Error

https://pastebin.com/raw/NbM9akkr

### Bug Description

When spawning custom creature like golems, zombies, skeletons, you get error.
Example code:
https://bukkit.org/threads/how-to-spawn-a-custom-entity.117456/
https://bukkit.org/threads/tutorial-how-to-customize-the-behaviour-of-a-mob-or-entity.54547/

### Steps to Reproduce

above

### Expected Behavior

Fixed spawning of custom creatures.

### Additional Server Info

BungeeCord

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
You're sending invalid metadata packets.

**Comment by andreasdc** [comment]
@KennyTV can you look at the example codes? I think I do everything right.

**Comment by KennyTV** [comment]
I can't help you if you don't show me your actual code, as is I can only tell you you're doing *something* wrong.

**Comment by andreasdc** [comment]
@KennyTV 
I'm trying to spawn Golem, but I'm using zombie as a test, because golem wasn't spawning.
`public class CustomIronGolem extends EntityZombie {

    public CustomIronGolem(World world) {
       super(world);
    }

    
    @Override
    public void collide(Entity entity) {
        if (entity instanceof EntityHuman) {
            return;
        }
    }

    public static void patch() {
        try {
            Method a = net.minecraft.server.v1_8_R3.EntityTypes.class.getDeclaredMethod("a", Class.class, String.class, int.class);
            a.setAccessible(true);
            a.invoke(a, CustomIronGolem.class, "CustomIronGolem", 54);
        }
        catch (Exception ignored) {
            // Do some cleanup and error-handling here.
        }
    }

}`

`            CraftWorld handle = (CraftWorld) player.getWorld();
            CustomIronGolem ironGolem = new CustomIronGolem(handle.getHandle());
            final Location spawnAt = event.getClickedBlock().getRelative(event.getBlockFace()).getLocation();
            //IronGolem ironGolem = player.getWorld().spawn(event.getClickedBlock().getRelative(event.getBlockFace()).getLocation(), IronGolem.class);
            //ironGolem.setTarget(null);
            ironGolem.setLocation(spawnAt.getX(), spawnAt.getY(), spawnAt.getZ(), spawnAt.getYaw(), spawnAt.getPitch());
            player.sendMessage("" + handle.getHandle().addEntity(ironGolem, SpawnReason.CUSTOM));`

**Comment by andreasdc** [comment]
@KennyTV did you check it?

**Comment by KennyTV** [comment]
I don't have decompiled 1.8 sources ready, so I can't really look too much deeper into it, sorry. It either has to be the entitiy id or meta ("datawatcher") contents being mismatched.

**Comment by andreasdc** [comment]
@KennyTV I have it, what do you want from it? The code is exactly how I sent to you, I don't think there's something wrong with it.

**Comment by KennyTV** [comment]
You'll have to figure that out yourself if you want to step foot into custom entity territory and take a look at the Vanilla code you're using and extending outside of what the slim/old tutorials there outline, especially on a version like 1.8.

**Comment by andreasdc** [comment]
@KennyTV ye, but you know, I didn't change anything, I just registered custom entity and I tried to spawn it, so I guess it's something wrong with ViaVersion and custom entities.

**Comment by KennyTV** [comment]
What those threads outline aren't really "custom" entities, just existing entities with differently implemented behaviour, which people have done in the past without issues. Again, you will have to figure that out yourself, and it's almost certainly an issue on your side. You also did not follow all steps the tutorial you sent provided, so that *might* be the cause.
