### ISSUE TITLE
Geyser's support issues

### ISSUE THREAD

**Issue by CJYKK** [ViaVersion/ViaVersion#2449]
### '/viaversion dump' Output

https://dump.viaversion.com/88e528eebfdf827289eb183a07df20670b6ff1b75dda08290f89970c3b37ce9c

### Console Error

```
https://paste.gg/p/anonymous/94f8062d3ac8416980b30914c91bb244
```

### Bug Description

Viaversion can't work with Geyser in bungeecord
If you use the bedrock version to enter, players will be kicked out of the game when they cross the server.

### Steps to Reproduce

1.Install Viaversion, Geyser-Bungeecord to Waterfall.
2.Use Bedrock Minecraft join the server.
3.If players cross the server, they will be kicked out.

### Expected Behavior

Players can cross the server and enjoy the server.

### Additional Server Info

I also using Waterfall with LP, Geyser-Bungeecord, AntiAttack, ViaBackwards, ViaRewind and ViaVersion

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [x] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Camotoy** [comment]
Geyser's goal is to emulate a Java client - therefore, if something doesn't work with Geyser, it's Geyser's fault. *If* you know how to replicate this issue, feel free to post it on Geyser's issue tracker - but it would be helpful if the Geyser team knew how to replicate it specifically (provide a world download?).
