### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by andreasdc** [ViaVersion/ViaVersion#2452]
### Problem Description

I noticed sometimes ViaVersion have performance issues.

### Solution Description

You could improve performance, maybe check with Spark?
![image](https://user-images.githubusercontent.com/82218780/116094443-d2b8ae80-a6a7-11eb-8cfd-be8bf5f340d9.png)

**Comment by KennyTV** [comment]
Change the blockconnection method in the config to "packet" to avoid Bukkit API calls (at the cost of lots of caching), but the world method we can't really change without possibly breaking on some versions/platforms.

**Comment by andreasdc** [comment]
@KennyTV didn't "packet" option bugged weird chunks or tnt explosions?

**Comment by andreasdc** [comment]
@KennyTV the issue is pretty general, you can use Spark to find bottlenecks of your code. :)

**Comment by KennyTV** [comment]
I have used proper profilers (like the YK Java Profiler) before to analyze performance and memory usage of Via plugins. Basically all of modern translation goes over pretty smoothly, but due to the nature of changes in older versions, especially 1.8<->1.9, 1.12<->1.13, and 1.13<->1.14, those will obviously require more processing power and caching - and even those aren't *particularly* bad... aside from parts of block connections. That code *could* be improved (even though it's already heavily optimized), specifically in getting/caching the blocks from the server/sent by the server, but noone has deemed it worthy of hours of additionally sinking time into it, given you still somehow have to completely re-implement what legacy servers did, without actually being integrated into the server.

**Comment by andreasdc** [comment]
@KennyTV CraftBlock.getData check if you really have to call this method.

https://github.com/ViaVersion/ViaVersion/blob/0015682fe47f6289e583f9f43dc36db6d5271eb3/bukkit-legacy/src/main/java/us/myles/ViaVersion/bukkit/providers/BukkitBlockConnectionProvider.java#L35
Use faster chunk resolver method.

Bukkit.getPlayer() method is expensive too.

**Comment by KennyTV** [comment]
`World#getChunkAt` loads chunks in if not already loaded, which we do not want.
`Server#getPlayer` is as unexpensive as it gets with a simple map call and a cast, I assume your Spark profile was done over an extremely short timespan / is not representative of a populated, live server - even if it is, we can't store if anywhere but behind a map lookup as well, and cutting down its calls by batching them in explosion/multi block change packets wouldn't make a *considerable* difference either.

**Comment by andreasdc** [comment]
@KennyTV it can be done better, trust me, I already did that. :D

**Comment by tomcraft** [comment]
then contribute ?

**Comment by andreasdc** [comment]
@tomcraft as I see building bug is not fixed, and it's almost 3 years. I think not passing packet when placed block is inside player or something would make it better.

**Comment by tomcraft** [comment]
?? what does it have to do with this "issue" ?
if you think you can do better than every other contributor of this project, go a head and start a pull request.

**Comment by KennyTV** [comment]
If you think you can do it, batch the block get usages in multi block packets and `ConnectionData#updateChunkSectionNeighbours`, but 👀

**Comment by andreasdc** [comment]
@KennyTV fix building bug then we will think about some of my improvements. 😃

**Comment by Proximyst** [comment]
How about you PR or shut up regarding that "so super easy bug"? 😃
The problems you pointed out are not problems in the most remote definition of a problem. This gives fairly good grounds to think you have no idea what you're talking about regarding "your improvements".

**Comment by andreasdc** [comment]
> How about you PR or shut up regarding that "so super easy bug"? 😃
> The problems you pointed out are not problems in the most remote definition of a problem. This gives fairly good grounds to think you have no idea what you're talking about regarding "your improvements".
I just said that you can do it better and that I did this better. Building bug I fixed and my patch is better, but there are still problems with often cancelled placing when bridging etc.

**Comment by Proximyst** [comment]
> 
> 
> > How about you PR or shut up regarding that "so super easy bug"? 😃
> > The problems you pointed out are not problems in the most remote definition of a problem. This gives fairly good grounds to think you have no idea what you're talking about regarding "your improvements".
> 
> I just said that you can do it better and that I did this better. Building bug I fixed and my patch is better, but there are still problems with often cancelled placing when bridging etc.

Let me quote myself:

> How about you PR or shut up regarding that "so super easy bug"? 😃

I see neither of these happening. If your patch works and is great, _contribute it_ instead of whining on the issue tracker of _volunteers_.

**Comment by andreasdc** [comment]
> > > How about you PR or shut up regarding that "so super easy bug"? 😃
> > > The problems you pointed out are not problems in the most remote definition of a problem. This gives fairly good grounds to think you have no idea what you're talking about regarding "your improvements".
> > 
> > 
> > I just said that you can do it better and that I did this better. Building bug I fixed and my patch is better, but there are still problems with often cancelled placing when bridging etc.
> 
> Let me quote myself:
> 
> > How about you PR or shut up regarding that "so super easy bug"? 😃
> 
> I see neither of these happening. If your patch works and is great, _contribute it_ instead of whining on the issue tracker of _volunteers_.

Show me where I talked about "super easy bug".

**Comment by Proximyst** [comment]
> 
> 
> > > > How about you PR or shut up regarding that "so super easy bug"? 😃
> > > > The problems you pointed out are not problems in the most remote definition of a problem. This gives fairly good grounds to think you have no idea what you're talking about regarding "your improvements".
> > > 
> > > 
> > > I just said that you can do it better and that I did this better. Building bug I fixed and my patch is better, but there are still problems with often cancelled placing when bridging etc.
> > 
> > 
> > Let me quote myself:
> > > How about you PR or shut up regarding that "so super easy bug"? 😃
> > 
> > 
> > I see neither of these happening. If your patch works and is great, _contribute it_ instead of whining on the issue tracker of _volunteers_.
> 
> Show me where I talked about "super easy bug". You are just spamming issue tracker.

You already fixed it, and have clearly shown how you are rather incompetent so coming to the conclusion that it's a "super easy bug" is not a farfetched one...

> it can be done better, trust me, I already did that. :D 

Talking about spam, though, this entire issue is completely unnecessary.

If the plugin is slow, they're going to be well aware from both their own experiences and from the support Discord guild, and they even employ a lot of tricks in the code to optimise any part of it they can. There's only so much you can refactor and fix in a day for your free time project when you've got school/uni, work, and whatever else, as all the maintainers do, anyways.
