### ISSUE TITLE
Shulker is going to be a stone

### ISSUE THREAD

**Issue by DeinVokabelheft** [ViaVersion/ViaVersion#2458]
### '/viaversion dump' Output

https://dump.viaversion.com/46d299b6e41ad34967383ce3c843802645d6c0c109397bb5dee08620e8ef7bf6

### Console Error

[11:22:08 WARN]: [ViaVersion] Failed to get 1.12 item for 362
[11:22:08 WARN]: [ViaVersion] Failed to get 1.12 item for 362
[11:23:19 WARN]: [ViaVersion] Failed to get 1.12 item for 362
[11:23:19 WARN]: [ViaVersion] Failed to get 1.12 item for 362

### Bug Description

You cant place shulkers and all new things above 1.12.2 on the 1.16.5

### Steps to Reproduce

1. Login with a 1.16.5 client
2. Taking shulkerbox in the inventory
3. its going to be stone when its placed in the inventory

### Expected Behavior

Shulker would not be a stone

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [x] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by DeinVokabelheft** [comment]
![Screenshot (81)](https://user-images.githubusercontent.com/69401987/116778098-4116bb80-aa70-11eb-8f61-c1f7bf39358f.png)

**Comment by KennyTV** [comment]
"Default" color shulker boxes were only added in 1.13, just pick any of the other ones.

**Comment by DeinVokabelheft** [comment]
But lanterns and all new stuff is going to be stone too

**Comment by DeinVokabelheft** [comment]
So idk

**Comment by KennyTV** [comment]
Yes, because they don't exist in 1.12.
