### ISSUE TITLE
 ViaVersion failed to initialise chunks reflection

### ISSUE THREAD

**Issue by Bluesky-ES** [ViaVersion/ViaVersion#2460]
### '/viaversion dump' Output

https://dump.viaversion.com/d3fd9f4ac0e63fc29243729b3d65a640c710c07a1ea31339886d1142caeeb15f

### Console Error

https://paste.gg/p/anonymous/6afd9a0d83ac452f8bafc08023f6351d

### Bug Description

Versions other than 1.8.9 enter the server and the connection will be aborted.

### Steps to Reproduce

1.Login with a client of a version other than 1.8.9 (Server version Paper1.8.8)
2.Just after entering, it prompts that the connection is aborted

### Expected Behavior

Allow versions other than 1.8.9 to log in to the server normally.

### Additional Server Info

I used Bungeecord.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Bluesky-ES** [comment]
![7D3ES0 2)@1L0EP@DA%@W}L](https://user-images.githubusercontent.com/83530244/116805118-b9f04300-ab56-11eb-8605-fa44c36c0ac4.png)

**Comment by KennyTV** [comment]
Pretty sure someone made a fix in the -dev versions, please try updating to those as the checklist suggests. If it then still happens, we will reopen this.

**Comment by Bluesky-ES** [comment]
> 非常肯定有人在开发版本中做了修复，请尝试更新到那些检查表建议。如果它仍然发生，我们将重新打开这个。

I have tried to update to the development version ViaVersion-3.2.2-SNAPSHOT, but the problem is still unresolved.

**Comment by KennyTV** [comment]
See https://ci.viaversion.com/job/ViaVersion-DEV/

**Comment by Bluesky-ES** [comment]
I updated to ViaVersion4.0.0 to solve the problem, thank you
