### ISSUE TITLE
Opened inventory packet?

### ISSUE THREAD

**Issue by andreasdc** [ViaVersion/ViaVersion#2464]
### '/viaversion dump' Output

ViaVersion 4.0.0-21w16a

### Bug Description

How can I check if player has opened own inventory on 1.16.5 client? I don't see any incoming packets when doing that. Do you ignore some packets or client just doesn't send that anymore? On 1.8 client it works.

### Steps to Reproduce

1. Login on 1.16.5 client.
2. Join 1.8 server.
3. Open own inventory.

### Expected Behavior

Way to read opened own inventory.

### Additional Server Info

BungeeCord

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by tomcraft** [comment]
99% sure client never sent any packet for opening his own inventory

**Comment by andreasdc** [comment]
> 99% sure client never sent any packet for opening his own inventory

100% 1.8 client sends this information.

**Comment by tomcraft** [comment]
what packet ?

**Comment by andreasdc** [comment]
@tomcraft @Camotoy ![image](https://user-images.githubusercontent.com/82218780/117514194-96ccf580-af93-11eb-9be6-d4d3b35fb6c4.png)

**Comment by tomcraft** [comment]
And what ? Where do you see this is sent by the client when oppening their own inventory ?

**Comment by andreasdc** [comment]
> And what ? Where do you see this is sent by the client when oppening their own inventory ?

"taking inventory achievement".

**Comment by tomcraft** [comment]
lmao. Please read what you just sent. 
`This message is not sent anywhere for client opening their own inventory`

**Comment by andreasdc** [comment]
> lmao. Please read what you just sent.
> `This message is not sent anywhere for client opening their own inventory`

That's from 1.16.5. Maybe there is another packet like with advancements or something.

**Comment by Camotoy** [comment]
That packet does send consistently for 1.8, surprisingly enough. I highly doubt that 1.16 has an equivalent - I just checked a packet log, and there's no advancement for it. Plus, as I've been developing for Geyser for a year, I've never heard of a request to detect when a Bedrock player has opened an inventory and map it to Java. So I think you're out of luck. :/

**Comment by andreasdc** [comment]
@Camotoy there isn't packet for advancement about opening inventory by any chance?

**Comment by Camotoy** [comment]
There is no advancement for opening your inventory (according to the Minecraft wiki). Therefore, there's no packet for it.

**Comment by RaphiMC** [comment]
Every version older than 1.12 sends this packet every time the users opens the inventory
