### ISSUE TITLE
Fix Velocity compatibility

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaVersion#2466]
### '/viaversion dump' Output

.

### Bug Description

Latest velocity changes the compression encoder

### Steps to Reproduce

Use latest dev build from velocity

### Expected Behavior

It should work

### Additional Server Info

Velocity

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Target Velocity 2.0.0 since it will likely go through sooner than expected with 1.17
