### ISSUE TITLE
EntityHuman getHeadHeight returns wrong height while sneaking

### ISSUE THREAD

**Issue by andreasdc** [ViaVersion/ViaVersion#2470]
### '/viaversion dump' Output

ViaVersion 4.0.0-21w16a

### Bug Description

When you sneak on 1.16.5 with 1.8 server getHeadHeight on EntityHuman returns wrong height.

### Steps to Reproduce

-

### Expected Behavior

-

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
What value do you get and what do you expect?

**Comment by andreasdc** [comment]
@KennyTV 
change-1_9-hitbox: true
change-1_14-hitbox: true
I think the returned value is wrong.

**Comment by KennyTV** [comment]
... Again, what value do you get and what do you expect?

**Comment by andreasdc** [comment]
@KennyTV normal height: 1.62
sneaking: 1.54
Same on 1.8 and 1.16. I think sneaking height should be lower, because there is desync when interacting.

**Comment by KennyTV** [comment]
No. We don't add features of newer versions unless they explicitly hinder gameplay (especially if they require injecting deeply into the server).
