### ISSUE TITLE
Error converting json text to legacy on interaction with entity

### ISSUE THREAD

**Issue by 4drian3d** [ViaVersion/ViaVersion#2471]
### '/viaversion dump' Output

https://dump.viaversion.com/482a21b0c99e342510d016e34b49a8a0126027241955ac223384232b008b4cbe

### Console Error

```
Put the paste.gg link or text here.
```
On interact with villager(not tested):
https://pastebin.com/dB2s6Wwz
On interact with minecart with chest(tested):
https://pastebin.com/vAffpB0r

### Bug Description

When trying to open a minecart with a chest, it will show an error in console, with client 1.12.2 and server 1.16.5. The error with the villagers may be related, from that error I investigated, but I could not reproduce it, but I managed to find the error with the minecart.

### Steps to Reproduce

1. Login with 1.12.2 client
2. Search for a minecart with a chest
3. Attempt to open it
4. It will open and display the content, but the error message will appear in the console.

### Expected Behavior

No errors are displayed when interacting with certain entities.

### Additional Server Info

INFO This server is running Purpur version git-Purpur-1095 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
INFO You are 7 version(s) behind
INFO Previous version: git-Purpur-1090 (MC: 1.16.5)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Fixed with the latest ViaVersion and ViaBackwards -DEV builds
