### ISSUE TITLE
Kicking players off the server after a bit, who aren't on the native version. (Issue occurs on both master and dev)

### ISSUE THREAD

**Issue by TheProgramm3r** [ViaVersion/ViaVersion#2475]
### '/viaversion dump' Output

https://dump.viaversion.com/5f233909085d736ea54badbd69f46321a661144ae45c6b84f0f5573806532c90

### Console Error

```
https://paste.gg/p/anonymous/67ded67d9b7a48e9803ca3cc7d57d44f
```

### Bug Description

Join the server and after a while I get kicked.

**![viaversionerror](https://user-images.githubusercontent.com/56412202/118365029-01200000-b569-11eb-9efb-9496c3d435f6.PNG)**

### Steps to Reproduce

Join the server and after a while I get kicked.

### Expected Behavior

Expect to be able join and play as usual.

### Additional Server Info

I am running on Spigot 1.16.5 with the following plugins ; ajLeaderboards, ChatFeelings, Citizens, CommandNPC*, ConditionalEvents, CoreProtect, DisplayName*, Essentials, EssentialsChat, EssentialsSpawn, eZProtector, HolographicDisplays, HolographicExtension, LibsDisguises, LuckPerms, Multiverse-Core, MyCommand, PlaceholderAPI, PointsAPI*, ProtocolLib, SAML, ServerListPlus, SimplePets, SuperVanish, TitleManager, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Fixed, but it looks like you have an item around with an invalid attribute tag, you might want to look into that
