### ISSUE TITLE
random console error

### ISSUE THREAD

**Issue by Matthew-MBG** [ViaVersion/ViaVersion#2477]
### '/viaversion dump' Output

https://dump.viaversion.com/08724b1af4d39a77883bf9ffa46e335e3db9df781dca0401f587a8c4af30ac66

### Console Error

https://paste.gg/p/anonymous/85fc5054a80847bca7b6132a4dbf6c82

### Bug Description

no idea still, it just appeared

### Steps to Reproduce

I have no idea, just appeared in console

### Expected Behavior

i still have no idea

### Additional Server Info

I use Paper and my plugins are: ArmorStandEditor, Citizens, ClearLag, CrackShot, CRPGBSP, CustomHeads*, Denizen, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, ExtraBoomerangs, floodgate-bukkit, Geyser-Spigot, GeyserSkinManager, HolographicDisplays, ImageOnMap, ItemEdit, LaggRemover, LibsDisguises, LuckPerms, Multiverse-Core, MythicMobs, OldCombatMechanics, PlaceholderAPI, ProtocolLib, Sentinel, ServerListPlus*, Shopkeepers, SimpleScore, SkBee, Skellett, SkQuery, Skript, skript-reflect*, skript-yaml, skUtilities*, StaffChatReloaded, TAB, TrollBoss, UltimateModeration, Vault, ViaBackwards, ViaRewind, ViaVersion, Vouchers, WorldEdit, WorldGuard

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Someone's sending bad packets to your server, not much we can do about that (and be sure not to reload).
