### ISSUE TITLE
1.8 Forge client with Optifine invisible 

### ISSUE THREAD

**Issue by ludgart** [ViaVersion/ViaVersion#2478]
### '/viaversion dump' Output

 https://dump.viaversion.com/1aa16d93035d6187525956f4199e7dd01183324fc908c7a1aa963548594b938c

### Console Error

No errors in the console

### Bug Description

See "Steps to Reproduce"

### Steps to Reproduce

Login with forge 1.8 with optifine installed
Join the 1.16.5 server with ViaVersion-4.0.0-21w19a, ViaRewind-2.0.0 and ViaBackwards-4.0.0-21w19a
Die from a player
Respawn
NPC, Players and your self are invisible now (it look like that : https://media.discordapp.net/attachments/767315429189222450/843864694989258772/Screenshot_6.png?width=1791&height=875 )
Reconnecting doesnt help. Only a server restart help.

### Expected Behavior

No visible bug

### Additional Server Info

Proxy: Flamecore without any protocol plugin
Server: Paper-1.16.5 - 629
Java 13 (and java 15 tested)

Filtered sent packets https://pastebin.com/BFsM2mBB
It happen only for the player: Betman1234 ( bc of the client )

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Sounds like it's because you use a 5 year old version of Forge and OptiFine :p

**Comment by ludgart** [comment]
Yea I know its the newest client version :D
I reproduce it on a regular proxy setup without any mods in the forge client.
Please move it to ViaRewind if they can help.
