### ISSUE TITLE
ViaVersion - Bad packet id

### ISSUE THREAD

**Issue by DarkyCat** [ViaVersion/ViaVersion#2486]
### '/viaversion dump' Output

https://dump.viaversion.com/56c0d305508bfaa4f0ca0cf97406d2835bcc728820cc4cc75508b691e7576e33

### Console Error

```
https://mcpaste.io/2350c840b4855a82
```

### Bug Description

This happens when the player joins the MineCraft server. This happens randomly and on all versions (tests 1.12.2, 1.8, 1.16.5). Server kernel 1.12.2, latest versions from SpigotMC. The player is kicked from the server completely.

### Steps to Reproduce

    Start the server on 1.12.2 (PaperSpigot).
    Install 2 plugins: ViaVersion and ViaBackWards.
    Enter several times and a kick will happen randomly.

### Expected Behavior

You will be kicked with the reason the server connection was lost (BungeeCord message)

### Additional Server Info

I use BungeeCord latest build.
PaperSpigot 1.12.2 latest version

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
If this happens on the same client as server version (1.12.2), this is highly unlikely to be a ViaVersion issue. If you can reproduce this without other plugins with a Vanilla client, we will reopen this.
