### ISSUE TITLE
ViaVersion ERROR IN Protocol1_11To1_10 IN REMAP OF CHAT_MESSAGE (0x02)

### ISSUE THREAD

**Issue by xiyanx** [ViaVersion/ViaVersion#2487]
### '/viaversion dump' Output

https://dump.viaversion.com/7624e7b769f9ce7a31d64aae09e8ec0fd23352855e15e8cdb3ed7b3746250db0

### Console Error

```
https://paste.gg/p/anonymous/ecfa853313274425850619ffd0cc1e65
```

### Bug Description

 us.myles.ViaVersion.protocols.protocol1_12to1_11_1.Protocol1_12To1_11_1$7 (Anonymous), Packet ID: 4

### Steps to Reproduce

/server bug ctizien

### Expected Behavior

/server bug ctizien

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by sergservis** [comment]
**papper spigot 1.12**
