### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by sergservis** [ViaVersion/ViaVersion#2488]
### '/viaversion dump' Output

https://dump.viaversion.com/0d0ab23eafd6a16be1ff613d52f30077657e7014f36992b8552914a678123cde

### Console Error

```
https://pastebin.com/jxzqe8kR
```

### Bug Description

I do not know why this error occurs in the console

### Steps to Reproduce

papper Spigot 1.12

### Expected Behavior

Correct the mistake

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Update to dev builds.
