### ISSUE TITLE
ERROR IN Protocol1_9To1_8 IN REMAP OF ENTITY_METADATA (0x1C)

### ISSUE THREAD

**Issue by einfachBlu** [ViaVersion/ViaVersion#2491]
### '/viaversion dump' Output

https://dump.viaversion.com/31d2e9b764bd3728357d15329190e7967aac93927ed83bfdce489e7433a23ff1

### Console Error

```
https://pastebin.com/s6d6V54s
```

### Bug Description

When i summon Wither or EnderDragon the player gets kicked and cant rejoin until the enderdragon was removed.

### Steps to Reproduce

1. 1.8 Server
2. ViaVersion
3. 1.16.4 / 1.16.5 Client
4. Join and use /summon EnderDragon ~ ~ ~
5. after it the client crashes

### Expected Behavior

no kick and no error in the console :)

### Additional Server Info

BungeeCord, Viaversion is installed on Paperspigot 1.8 and tested with vanilla client and also MysteryMod 1.16

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Update to -DEV builds here: https://ci.viaversion.com/job/ViaVersion-DEV/

**Comment by einfachBlu** [comment]
Same error with this dev build

**Comment by einfachBlu** [comment]
The error comes with the plugin "Intave stable prod 13.0.7-b6"

**Comment by KennyTV** [comment]
Can you send the new error running on dev builds?

**Comment by einfachBlu** [comment]
its the exact same as i posted above

**Comment by KennyTV** [comment]
Then you didn't update to a build from the link I sent.

**Comment by einfachBlu** [comment]
i did :)

But i can try again later
