### ISSUE TITLE
Needs [stone/iron/diamond] tags left empty

### ISSUE THREAD

**Issue by Camotoy** [ViaVersion/ViaVersion#2493]
### '/viaversion dump' Output

https://dump.viaversion.com/ff6f026a132b853bca80e716b117e05380b7ba1a7ddeee83d93cdea2efd1c4fe

### Bug Description

Attempting to mine a block with a higher tool tier than its base mining tier applies the normal mining speed to the block, resulting in block animation being off (the client thinks it can break the block with its current tool).

### Steps to Reproduce

1. Log in on a pre-1.17 server using 20w20a.
2. Grab iron ore and a wooden pickaxe
3. Attempt to mine it

### Expected Behavior

The client understands it has an invalid tool and slows the block mining animation down.

### Additional Server Info

More fun tag stuff for you to fill in, Kneny. :)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
![thanks](https://tenor.com/view/cat-on-fire-sitting-edited-on-fire-fire-gif-17645117)
