### ISSUE TITLE
 ERROR IN Protocol1_16_1To1_16_2 IN REMAP OF ENTITY_METADATA (0x44)

### ISSUE THREAD

**Issue by tomikcz987** [ViaVersion/ViaVersion#2497]
### '/viaversion dump' Output

https://dump.viaversion.com/bfa684d2de03a880c6d9ddf1ee34acd74b400fc5474d88731c6062baa5c681c7

### Console Error

```
https://paste.gg/p/anonymous/1833db2918124658862574d9250a2d44
```

### Bug Description

When I connect to  1.16.5 server with  lower version it kicks me out

### Steps to Reproduce

1) Connect with  lower version to 1.16.5 server
2) Wait a second for chunks to load
*kicked*

### Expected Behavior

Ability to connect to  server with 1.16.1 and lower 

### Additional Server Info

I connected via Travertine proxy but error should also appear without that

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Fixed in bc89f57088d0b634b04e2ca2ad3ec46699de1a2c
