### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by adiantek** [ViaVersion/ViaVersion#2500]
### Problem Description

https://github.com/ViaVersion/ViaVersion/blob/master/bukkit/src/main/java/us/myles/ViaVersion/bukkit/handlers/BukkitEncodeHandler.java#L49

Why ChannelHandlerContextWrapper is created every "encode"? Couldn't it be cached?
PacketEncoder could be restored if handshake.version=47 and server.version=47. Reflection is done unnecessarily.

### Solution Description

Store ChannelHandlerContextWrapper in class variable and restore decoder/encoder if server version equals to player version

**Comment by FlorianMichael** [comment]
There wasn't any need in ChannelHandlerContextWrapper in the first place, same with the reflection code. Both things are gone for a while now.
