### ISSUE TITLE
remapper & getBlockedProtocols

### ISSUE THREAD

**Issue by adiantek** [ViaVersion/ViaVersion#2505]
### '/viaversion dump' Output

blablabla

### Bug Description

ViaVersionConfig from maven https://repo.viaversion.com/ (4.0.0-21w16a) has:
```java
  public abstract boolean is1_12QuickMoveActionFix();
  
  public abstract us.myles.viaversion.libs.fastutil.ints.IntSet getBlockedProtocols();
  
  public abstract java.lang.String getBlockedDisconnectMsg();
```
and AbstractViaConfig has:
```java
  public boolean is1_12QuickMoveActionFix() {
    return false;
  }
  
  public it.unimi.dsi.fastutil.ints.IntSet getBlockedProtocols() {
    return null;
  }
  
  public java.lang.String getBlockedDisconnectMsg() {
    return null;
  }
```
It makes me unable to use it with custom ViaVersion(Proxy) instances without recompile ViaVersion.
```
The return type is incompatible with ViaVersionConfig.getBlockedProtocols()Java(67109268)
```
or:
```
The return type is incompatible with AbstractViaConfig.getBlockedProtocols()Java(67109268)
```
![image](https://user-images.githubusercontent.com/13407885/120128119-93f3a800-c1c1-11eb-88a5-1f39541d88ed.png)
![image](https://user-images.githubusercontent.com/13407885/120128171-b1c10d00-c1c1-11eb-878e-3dd3e11ed4d3.png)
![image](https://user-images.githubusercontent.com/13407885/120128212-c8fffa80-c1c1-11eb-8a40-c920c6112f27.png)

### Steps to Reproduce

1. Create any maven project
2. Add to dependency:
```
    <dependency>
      <groupId>us.myles</groupId>
      <artifactId>viaversion-common</artifactId>
      <version>4.0.0-21w16a</version>
    </dependency>
```
3. Try to create a class that extends AbstractViaConfig
4. You will see an error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project viaversionproxy: Compilation failure: Compilation failure: 
[ERROR] /home/ubuntu/git/viaversionproxy/src/main/java/viaverproxy/MyAbstractViaConfig.java:[12,17] getBlockedProtocols() in us.myles.ViaVersion.AbstractViaConfig cannot implement getBlockedProtocols() in us.myles.ViaVersion.api.ViaVersionConfig
[ERROR]   return type it.unimi.dsi.fastutil.ints.IntSet is not compatible with us.myles.viaversion.libs.fastutil.ints.IntSet
```

### Expected Behavior

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

### Additional Server Info

custom proxy

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [x] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
There are no `us.myles` packages in 4.0.0 anymore (except for a handfull of the main API classes), so you have some kind of dependency mismatch.

**Comment by adiantek** [comment]
Ok, thanks. I had `viaversion-common` in dependencies, `viaversion` works. Sorry for creating the issue.
