### ISSUE TITLE
Connection lost due to map | 1.17-pre3+

### ISSUE THREAD

**Issue by Aurelien30000** [ViaVersion/ViaVersion#2507]
### '/viaversion dump' Output

https://dump.viaversion.com/801343a15f3cee3183b819e40e2cbfc96f6d35cf6942904d4086a23036fca456

### Console Error

```
Nothing, usual behavior.
```

### Bug Description

Trying to connect with 1.17-pre3+ client, users are disconnected due to **Connection lost**, loading a specific map.

Thus, I would need to pass it on to you, so you can experiment. However, this map is private, please contact me on discord and I will give you a link ``◀ λųгέłɪεŋ ▶#3642``.

Thanks for your future help !

_Since comment field is empty/unreachable, I have to put my screen here, apologies:_
![image](https://user-images.githubusercontent.com/43724816/120615146-42187f80-c458-11eb-92f8-0a8f3207836d.png)

### Steps to Reproduce

1) Run the server on Paper 1.16.5 and the annoying map.
2) Try to connect with 1.17-pre3+.
3) Observe connection lost after a few seconds, loading the map.

### Expected Behavior

User shouldn't be disconnected and able to stay on the server.

### Additional Server Info

Tried without any other plugin, on a basic instance (no proxy, latest Paper and ViaVersion build), issue persists.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Can you test again on pre5 and otherwise look into client logs for errors?

**Comment by Aurelien30000** [comment]
1.17-pre5 fixed the issue or you fixed it in ViaVersion side. Anyways, issue isn't reproducable, thank you :D
