### ISSUE TITLE
1.7.2-1.15.2 not working

### ISSUE THREAD

**Issue by XDRmc** [ViaVersion/ViaVersion#2508]
### '/viaversion dump' Output

https://dump.viaversion.com/62807c69a5b7d72b8df9b588f0adfcb9ef289abea5aac58a9240ccdc6797b21d

### Console Error

```
https://paste.gg/p/anonymous/fdf2962d8d914a7eb389add02a78e9f1/revisions
```

### Bug Description

1.7-1.15 players cant join

### Steps to Reproduce

join with 1.7-1.16 on play.xdrmc.net

### Expected Behavior

join the server with the versions

### Additional Server Info

I use bungeecord with spigot servers connected to theme that each (apart from bungee) have via version installed.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
The logs there don't tell us anything. Otherwise update to -dev builds on https://ci.viaversion.com and make sure your Bungee/Travertine is up to date.
