### ISSUE TITLE
viaversion block placing issue 

### ISSUE THREAD

**Issue by skullgaming22** [ViaVersion/ViaVersion#2511]
### '/viaversion dump' Output

https://dump.viaversion.com/2c6b6145e7c0e7d6c6dddb46e4d04f2ded0fa5bcdd5928077687ec549dfcf0ed

### Console Error

https://pastebin.com/w718CAYF

### Bug Description

it places the blocks twice and glitches the player

### Steps to Reproduce

join from 1.10 or above

### Expected Behavior

it places the blocks twice and glitches the player

### Additional Server Info

using viaversion in spigot

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Not a Via issue, see `com.andrei1058.bedwars.listeners.DamageDeathMove.onDamageByEntity(DamageDeathMove.java:175)`
