### ISSUE TITLE
getProtocol(755).getName() returns "Unknown (755)"

### ISSUE THREAD

**Issue by Bobcat00** [ViaVersion/ViaVersion#2513]
### `/viaversion dump` Output

https://dump.viaversion.com/b334b563e0422759e635e52d426dc9c1a6305841b092b9ba44626af05d8518f8

### Bug Description

Calling `us.myles.ViaVersion.api.protocol.ProtocolVersion.getProtocol(id).getName()` when id=755 returns the string **"Unknown (755)"** instead of a string with 1.17.

### Steps to Reproduce

Run a plugin which calls `us.myles.ViaVersion.api.protocol.ProtocolVersion.getProtocol(id).getName()` with id=755.

### Expected Behavior

The output should be similar to the strings returned for other protocol versions:
```
id=490, getName="1.14.3"
id=498, getName="1.14.4"
id=751, getName="1.16.2"
id=753, getName="1.16.3"
id=754, getName="1.16.4/5"
```
For 755, I'd expect to see:
`id=755, getName="1.17"`
instead, ViaVersion returns:
`id=755, getName="Unknown (755)"`

### Additional Server Info

No BungeeCord.
3091-Spigot-9fb885e-ebe18b9 (MC: 1.16.5)
Java 8
ViaBackwards version 4.0.0
ViaRewind version 2.0.0-SNAPSHOT
ViaVersion version 4.0.0

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by creeper123123321** [comment]
Please use the new API from com.viaversion.api

**Comment by Bobcat00** [comment]
OK, I'm working on it.  Is there a replacement for SERVER_PROTOCOL?
```
@Deprecated
public class ProtocolRegistry {
    @Deprecated
    public static int SERVER_PROTOCOL = -1;
```

**Comment by Bobcat00** [comment]
Looks like I got it all working. Thanks.

**Comment by KennyTV** [comment]
(In case other people see this before the public release:) You can find more direction on how to update depending plugins here https://gist.github.com/KennyTV/3778685985ddc45bd99e003191ff02eb
