### ISSUE TITLE
Remove obnoxious EOL message

### ISSUE THREAD

**Issue by creeperQ7** [ViaVersion/ViaVersion#2516]
### Problem Description

> [20:18:00 WARN]: [ViaVersion] This version of Minecraft is extremely outdated and support for it has reached its end of life. You will still be able to run Via on this Minecraft version, but we are unlikely to provide any further fixes or help with problems specific to legacy Minecraft versions. Please consider updating to give your players a better experience and to avoid issues that have long been fixed.

Absolutely useless message since it counts 1.12, the last stable multiplayer version, as "extremely outdated"

### Solution Description

Remove the message, or at least add a toggle to disable it.

**Comment by KennyTV** [comment]
No
