### ISSUE TITLE
My well-filed issue simply got denied saying "No", without naming a reason at all

### ISSUE THREAD

**Issue by creeperQ7** [ViaVersion/ViaVersion#2517]
No

_Originally posted by @KennyTV in https://github.com/ViaVersion/ViaVersion/issues/2516#issuecomment-856995718_

Like what the hell is this? I file a serious issue and someone just denies it without any reason.

**Comment by Camotoy** [comment]
1.12 is an old version. Via doesn't have any obligation to support it.

**Comment by creeperQ7** [comment]
The point of the plugin is to work on old versions isn't it? 1.12 is the last version suitable for multiplayer so in a way it's the newest version. 

At least thanks for answering my issue.

**Comment by Camotoy** [comment]
The idea of ViaVersion is to support servers that want to support newer players but are stuck on older versions. For example, 1.16 to support 1.17 while Paper is not updated. ViaVersion will still work on older versions - if Via removed support, another fork would re-add it - but they would rather promote updating your server version as you get the newer features and bug fixes.

**Comment by KennyTV** [comment]
^ exactly that, sorry for not making that clear.

**Comment by Blocksnmore** [comment]
> 1.12 is the last version suitable for multiplayer
1.16 is just as stable from my experience as 1.12, if you use a fork like paper

**Comment by creeperQ7** [comment]
> > 1.12 is the last version suitable for multiplayer
> 
> 1.16 is just as stable from my experience as 1.12, if you use a fork like paper

Having more than 50 players online on 1.16 is nearly impossible, paper seems to only make it worse for me

**Comment by roboalex2** [comment]
No
