### ISSUE TITLE
Cannot connect to Velocity with ViaVersion

### ISSUE THREAD

**Issue by j-tai** [ViaVersion/ViaVersion#2518]
### `/viaversion dump` Output

https://dump.viaversion.com/8bfe668c02ce6c460301344f1a55bb913051299f9bd0b42b10d11f338f7e8b6e

### Console Error

No errors. The only log message when I try to join is:
```
[18:28:37 INFO]: [connected player] PLAYERNAME (/127.0.0.1:46848) has connected
```
There is no disconnection message.

### Bug Description

Joining the server doesn't work. The client shows:
![image](https://user-images.githubusercontent.com/45131430/121278515-97ed8d00-c887-11eb-970a-9bca1d34d42b.png)

### Steps to Reproduce

Log into the server

### Expected Behavior

I should be able to log in

### Additional Server Info

* Server version: Paper 1.16.5, no plugins.
* Proxy version: Velocity 1.1.8, only plugin is ViaVersion.
* Client version: 1.17. Same issue occurs with 1.16.5.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Unfortunately, Via does not yet support the new velocity versions. Until support is added, you could move the plugin to your backend server. #2466
