### ISSUE TITLE
Via Version Error

### ISSUE THREAD

**Issue by SKRecreated** [ViaVersion/ViaVersion#2520]
### `/viaversion dump` Output

n/a

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

![image](https://user-images.githubusercontent.com/70330761/121328719-3bd54800-c91d-11eb-8a7b-e60807df3b86.png)
Jello for sigma 5
I cant use sigma five I tried reinstalling

### Steps to Reproduce

Download Sigma
Try to use it after setting version to 1.18

### Expected Behavior

It should work and let me join in 1.8

### Additional Server Info

Literally any server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Follow the issue template / we do not support custom closed sourced clients.
