### ISSUE TITLE
An error occurred with entity metadata handler

### ISSUE THREAD

**Issue by skw359** [ViaVersion/ViaVersion#2521]
### `/viaversion dump` Output

https://dump.viaversion.com/c3810331657263ee956e32bacc97b823efb3d4895e699411628cc24cf2cf4789

### Console Error

```
Put the paste.gg link or text here.
```
https://pastebin.com/6c64fNAp

### Bug Description

So I'm not able to exactly replicate this bug, as it happens at random times when players join/leave. The plugin spams my console and if it's bad enough, it shuts down the server.

### Steps to Reproduce

1. Update ViaVersion to the latest build
2. Players join/leave
3. Errors popup at random times (I don't know what's causing it, it's happened with the player's inventory was empty as well) 

### Expected Behavior

Not to take down the server/spam console 

### Additional Server Info

I use Velocity as my proxy - it has TCPShield, buycraft, LuckPerms, nuvotifier

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Above or below the snippet you send you should be able to find a stacktrace, please include that as well.

**Comment by skw359** [comment]
Here's the stacktrace: https://pastebin.com/W5HpKxM8

Would the "zip file closed" affect just ViaVersion, or other plugin jars?

**Comment by KennyTV** [comment]
The zip file error only affects the plugin that has the broken file, but if it is called/run on the main thread outside of plugin error handling, it might crash that.
Please download https://ci.viaversion.com/job/ViaVersion/510/ and paste the error that appears, I slightly amended the message to be more informative (tho unless you have some sort of console filtering plugin, even the one you sent now should be including something else/the actual error).

**Comment by skw359** [comment]
Sure thing - thank you! 
I'll update here if the error message occurs again and will send the stacktrace accordingly

**Comment by skw359** [comment]
Alrighty, it's causing disconnections on my backend again - here are console logs: https://pastebin.com/Wy8nnFhY. It's spammed with this stacktrace and players are getting this error: https://pastebin.com/uanRD1pD

**Comment by KennyTV** [comment]
Are you sure that's all? There should also be something similar to your old paste as well

**Comment by skw359** [comment]
This is with the new version sent above - nothing else was changed. Would it be helpful if I sent anything else?

**Comment by KennyTV** [comment]
Remove the consolespamfix plugin please, that seems to be suppressing important warnings

**Comment by skw359** [comment]
Sure, it currently doesn't block anything though, it's empty

**Comment by KennyTV** [comment]
Hmm well *something* has to be limiting what you can see wherever you're looking at it - the first one didn't contain any actual stracktrace, and the latest paste doesn't contain the warnings seen in the first (which should always be seen both, printed right after another)

**Comment by skw359** [comment]
I am not so sure what could be limiting it in latest.log - here's another snippet of it: https://pastebin.com/WEEsS0Zk
I agree though it's weird because the errors are completely different. Would it help I sent the whole latest.log? (Warning: it's very big lol)

**Comment by KennyTV** [comment]
Probably not, but I suspect this is due to an npc plugin sending metadata for an untracked npc.

**Comment by skw359** [comment]
Okay, I will try removing anything related to NPCs and see if the errors persist. Should I still stay on this version of ViaVersion?

**Comment by skw359** [comment]
Here's the error log again, seems like nothing has changed: https://pastebin.com/avYmRAfp

**Comment by KennyTV** [comment]
Whoops, try again with the next ViaVersion build (that was an error in error logging 👻).

**Comment by skw359** [comment]
Oh alrighty, I'll try build 512 then!

**Comment by xXkguyXx** [comment]
Looks to be another problem related to the entity metadata handler. (Am currently using the latest dev build (ViaVersion-4.0.1-SNAPSHOT.jar)). This error does not occur on any version I have tested pre-4.0.0.

I get the following error when I join on any client that is not the server's base version (1.8+)

https://pastebin.com/utDBg8cj

**Comment by KennyTV** [comment]
Yours smells like a plugin sending bad metadata

**Comment by xXkguyXx** [comment]
Interesting, will investigate myself, but this issue did not occur before updating to version 4.0.0.

**Comment by KennyTV** [comment]
Before, we allowed data inconsistencies to happen, meaning type/value mismatches. In 4.0.0, sanity checks were added to those... There's a slim chance this actually is an introduced *error*, but pretty sure that shouldn't be the case.

**Comment by SpEeD11** [comment]
Getting the same issue as above after updating to ViaVersion 4.0.0+

https://pastebin.com/E6tKpCB5

For me, it is when a custom boss bar message is sent to a player. The bar still shows but is always at 100% for non base-version clients (bossbar-anti-flicker is off), plus the error spam. This was not an issue in previous versions.

**Comment by xXkguyXx** [comment]
> Getting the same issue as above after updating to ViaVersion 4.0.0+
> 
> https://pastebin.com/E6tKpCB5
> 
> For me, it is when a custom boss bar message is sent to a player. The bar still shows but is always at 100% for non base-version clients (bossbar-anti-flicker is off), plus the error spam. This was not an issue in previous versions.

Same thing occurs on my end.

**Comment by SpEeD11** [comment]
Is the fix only for ViaBackwards? My issue was occurring using ViaVersion only and updating to the latest build hasnt fixed it
