### ISSUE TITLE
ERROR IN Protocol1_13_2To1_14 IN REMAP OF ENTITY_METADATA (0x43)

### ISSUE THREAD

**Issue by amadeusmz** [ViaVersion/ViaVersion#2522]
### `/viaversion dump` Output

https://dump.viaversion.com/7cab752eaa60990741b0d42cfbc40d418aed7f2ceb392e892d4994ab52bf4689

### Console Error

```
https://paste.gg/p/anonymous/f9e76e0fce6a460ca0aaa38e8d7b3fda
```

### Bug Description

Console spam

### Steps to Reproduce

I don't know how to reproduce, I hope the stacktrace will help

### Expected Behavior

Console should not spam

### Additional Server Info

I use Wallterfall, ViaVersion and ViaBackwards is running on backend server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Update to the latest dev build. If a new (but also starting with the first metadata line) error appears, please add it to https://github.com/ViaVersion/ViaVersion/issues/2521
