### ISSUE TITLE
[1.17] PacketPlayInLook + PacketPlayInBlockPlace

### ISSUE THREAD

**Issue by NikV2** [ViaVersion/ViaVersion#2523]
### `/viaversion dump` Output

Not needed

### Bug Description

Holding a material while not looking at a block, And right clicking sends PacketPlayInPositionLook and PacketPlayInBlockPlace in the same tick, Which causes issues with many anticheats and general plugins that depend on those types of packets.

I do not know if this is a minecraft thing due to 1.17 or an issue within ViaVersion.

I believe something needs to be done regarding this since it's quite impossible for anticheats to account for.

### Steps to Reproduce

1. Take a block on your main hand
2. Look in the air and spam right click.

### Expected Behavior

Only PacketPlayInBlockPlace should be sent

### Additional Server Info

Tried on both 1.8 through 1.16.5

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Tecnio** [comment]
> Pretty sure that's normal client behavior in all versions? And what server version are we talking about?

It is not a normal thing do its a normal thing for a 1.17 client

**Comment by NikV2** [comment]
Tried both in 1.8 to 1.16, The only packet that should be sent while doing that is PacketPlayInBlockPlace, The packet also gets sent multiple times if u're moving and doing it.

I can't tell if its a 1.17 client thing or not, So i apologize if i'm wrong for opening an issue.

**Comment by KennyTV** [comment]
No worries, at worst it's just a small, invalid issue, else something we can figure out a solution for. But if it is a 1.17 client thing, I don't think Via can do all that much about it either, unless we wanted to cache every single player position change and cancel look packets if it doesn't change, but that would probably be best done in the anticheat itself (in its own position cache or by using Bukkit API). Also given you more or less have to check for Via anyways for proper client compatibility over the versions, with Via exclusively operating on a packet level.

**Comment by NikV2** [comment]
I believe the rotation or the information the packet sends by itself is empty, Maybe it was a small fix in order to avoid blocking desync? Seems like the only explanation here.

Im not sure what a good solution would be in order to cancel it properly without issues, But nontheless thanks for your response.

Should i close this issue?

**Comment by NikV2** [comment]
Cancelling the packet on the anticheat's end seems to make it more problematic.

**Comment by KennyTV** [comment]
If you or anyone else can think of a way to deal with this in Via, I will reopen the issue, as far as I can see now it's a wont/cant fix (without possibly creating other problems). If a solution outside of Via is made, feel free to comment that here as well. 😛

**Comment by NikV2** [comment]
The only solution i can think of is making a bandaid fix for this by checking the packet order and compensating or adding leniency for the things it affects.

It would still be great if that feature would be configurable (if applicable)! It's going to save time and help a **L O T** of developers, Especially anticheats.

Thanks for your time nontheless!

**Comment by RaphiMC** [comment]
The best solution is to wait for anticheat devs to update their code to account for that instead of relying on packet timings

**Comment by andreasdc** [comment]
Updating code in anticheats is not the best solution. This extra move packets causes many problems with eating, riding entities etc.

**Comment by andreasdc** [comment]
Also if you want anticheats to account for that, cheaters can account for that chek and make bypasses. 😢
