### ISSUE TITLE
Internal Exception: io.netty.handler.codec.DecoderException

### ISSUE THREAD

**Issue by LynxError** [ViaVersion/ViaVersion#2524]
### `/viaversion dump` Output

https://dump.viaversion.com/00cf960784facc7efa5cf02f44c598a82fb89535b8e6478dc2b8576c0ceeb665

### Console Error

Internal Exception: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: Integer, Data: [], Source 0: com.viaversion.viaversion.protocols.protocol1_17to1_16_4.packets.InventoryPackets$4 (Anonymous), Packet ID: -1}
Actual Error: 

### Bug Description

upon login 5 seconds later error & logout

### Steps to Reproduce

upon login 5 seconds later error & logout

### Expected Behavior

upon login 5 seconds later error & logout

### Additional Server Info

upon login 5 seconds later error & logout

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Update to ci builds.

**Comment by LynxError** [comment]
1.17 & 1.12.2 work, 1.16.x does not

**Comment by KennyTV** [comment]
You didn't update ViaBackwards 😛

**Comment by LynxError** [comment]
ViaBackwards-4.0.0-1.17-rc1-SNAPSHOT was the one up there, 1 sec i see there is a new

**Comment by LynxError** [comment]
ViaBackwards-4.0.1-SNAPSHOT.jar on now, working thank you UserError i guess, keep up the great work
