### ISSUE TITLE
Spectator teleport broken on 1.17 with ViaVersion on Waterfall

### ISSUE THREAD

**Issue by fabianmakila** [ViaVersion/ViaVersion#2525]
### `/viaversion dump` Output

https://dump.viaversion.com/1b2478204f436934cd405e34731a5244d71db83867460502b944f0ad1029c131

### Console Error

No errors.

### Bug Description

When trying to teleport to other players in 1.17 using spectator menu it does nothing.

I tested this with Waterfall and Standalone and this only hapens when ViaVersion is installed on Waterfall. I haven't tested other proxies.

Also tested on latest dev version that was available for Via and the issue still persists.

### Steps to Reproduce

1. Install ViaVersion to Waterfall
2. Connect to a 1.16.5 subserver with 1.17 client.
3. Try to teleport to a player using spectator menu
4. Presumably nothing happens :P

### Expected Behavior

When trying to teleport using the spectator menu it would actually teleport.

### Additional Server Info

Proxy: Waterfall 1.17 b435
Subserver: git-Paper-645 (1.16.5)

Plugins on proxy (Other than Via):
 - Advanced Portals
 - AdvancedBan
 - ajQueue
 - Luckperms
 - Maintenance
 - MiniMOTD
 - PremiumVanish
 - TAB Premium
 
 Plugins on subserver:
 `AAC5, AdvancedPortals, ajQueue, ChunkSpawnerLimiter, Chunky, ChunkyBorder, Citizens, CommandPanels, CoreProtect, DiscordSRV, Essentials, EssentialsSpawn, F3NPerm, GriefPrevention, GSit, HolographicDisplays, InventoryRollback, KickFromClaim, LuckPerms, PlaceholderAPI, Plan, PremiumVanish, ProtocolLib, PurpleIRC*, SmoothSleep, SpeedLimiter, TAB-BukkitBridge, TogglePvp*, TradeSystem, Vault, VentureChat, WorldEdit, WorldGuard`

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Seems to be a Bungee/Waterfall bug - I can reproduce the same on a 1.17 Spigot server and 1.17 clients.
