### ISSUE TITLE
Broken LuckPerms output on Paper 1.12.2 using 4.0.0 (With error)

### ISSUE THREAD

**Issue by TomLewis** [ViaVersion/ViaVersion#2529]
### `/viaversion dump` Output

https://dump.viaversion.com/e4a78ef995cf5a293efeedf38ae4fa712b0db0cb8bf6983cbd89c500dee4368e

### Console Error

```
https://gist.github.com/TomLewis/e73e2e276c990857996f36e2d49373ee
```

### Bug Description

/lp no longer works as a player, but the exceptions are thrown in-console by itself without anyone running commands.
When you use /lp in-game nothing happens, no output no error in console, nothing.

But /lp seems to work from the console still.

### Steps to Reproduce

Use paper 1.12.2
Use LuckPerms
Use ViaVersion

### Expected Behavior

For luckperms to work

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Update LuckPerms
