### ISSUE TITLE
Could not pass event PlayerJoinEvent to DiscordSRV & Matrix

### ISSUE THREAD

**Issue by TomLewis** [ViaVersion/ViaVersion#2530]
### `/viaversion dump` Output

https://dump.viaversion.com/e4a78ef995cf5a293efeedf38ae4fa712b0db0cb8bf6983cbd89c500dee4368e

### Console Error

```
https://gist.github.com/TomLewis/e3bbf236a91d14a5cc8ca638e307bed9
```

### Bug Description

CPU is working overtime since updating ViaVersion.
In console I see thousands and thousands of errors ViaVersion is causing with plugins, in this case DiscordSRV & Matrix

### Steps to Reproduce

Use Paper 1.12.2
Use ViaVersion 4.0.0
Use Matrix or DiscordSRV

Get errors/Massive CPU use.

### Expected Behavior

To not spam console/not have a big performance impact.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Those plugins have to update their Via API usage.
