### ISSUE TITLE
Moving items not working properly in 1.17 client

### ISSUE THREAD

**Issue by dbrighthd** [ViaVersion/ViaVersion#2532]
### `/viaversion dump` Output

https://dump.viaversion.com/027381d7f5632d17af8de5a120631b4eb564776d8ef5e9d7e3f8cd7e085bb023

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Double clicking to move all items from chest to inventory (or vice versa) doesnt work when connecting a 1.17 client to a 1.16.5 server. instead of moving all items, it just appeares for a split second.

https://user-images.githubusercontent.com/68525639/121653304-66c0b880-ca51-11eb-94cd-936d757b8b08.mp4

### Steps to Reproduce

Join a 1.16.5 server with a 1.17 client
try double clicking items into a chest

### Expected Behavior

The expected behavior is for all items of the type you are double clicking to move to the containor/inventory. I attatched a video with the expected behavior working with a 1.16.5 client on the same server.

https://user-images.githubusercontent.com/68525639/121653212-4ee93480-ca51-11eb-9abf-129be1ae209f.mp4

### Additional Server Info

papermc 1.16.5, java 16, 

plugins are ChatFormat, CoreProtect, floodgate, Geyser, LuckPerms, PlaceholderAPI, pronouns, Vault, and ViaVersion (tried with both 4.0.0 and the 4.0.1 snapshot)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by RaphiMC** [comment]
Maybe a solution would be to make something like the quick move fix for 1.11. A fix that only works when the plugin is on the spigot server, that way the inventory could be accessed more easily

**Comment by TNTUP** [comment]
Can confirm =X

**Comment by ORIOLESFan02** [comment]
Have something similar where it creates non-existent duplicate items. Except I'm on a 1.17.1 server with a 1.16.5 client.

**Comment by mvrozanti** [comment]
What change introduced this bug?

**Comment by Camotoy** [comment]
I'm not familiar with the specific mechanics causing this bug, but the click window inventory packet got a bit of an overhaul where it now contains a map of every slot changed.

**Comment by ORIOLESFan02** [comment]
> 
> 
> Have something similar where it creates non-existent duplicate items. Except I'm on a 1.17.1 server with a 1.16.5 client. Edit: I even updated to the latest stable version and I still have the same problem

I still have this problem and it's quite annoying imo.

**Comment by Leahcimkrob** [comment]
I use the latest Dev-Build from Viaversion and Viabackward an have this Problem.
