### ISSUE TITLE
disconnected with: EncoderException : com.viaversion.viaversion.exception.InformativeException

### ISSUE THREAD

**Issue by 4o4E** [ViaVersion/ViaVersion#2533]
### `/viaversion dump` Output

https://dump.viaversion.com/7dff9768fbbf722b3351e302045d009c2f4d5d5fae8fb5c7df8ec8ad6f3652d7

### Console Error

https://paste.gg/p/anonymous/be452b707b674c94b1de317ddedb5456

### Bug Description

server: paper 1.16.5 with ViaVersion 4.0.0 & ViaBackwards 4.0.0
bungeecord: waterfall 436(1.17) with ViaVersion 4.0.0 & ViaBackwards 4.0.0
client: 1.16.5

### Steps to Reproduce

just login
and I'll get kicked
This will happen on BungeeCord1.17 and WaterFall1.17
If I use waterfall1.16, it's OK

### Expected Behavior

I shouldn't have been kicked

### Additional Server Info

![image](https://user-images.githubusercontent.com/58851040/121763649-64a14b80-cb70-11eb-9f4c-fde4aa3cbc9a.png)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Update VV and VB to ci builds.
