### ISSUE TITLE
I can't connect to my 1.17 server with an older version

### ISSUE THREAD

**Issue by AkZydro** [ViaVersion/ViaVersion#2534]
### `/viaversion dump` Output

https://dump.viaversion.com/aa03a79c6a27726c2f892d0caf040892ab46cac4d990952cb14b029e5349ba3a

### Console Error

268 | [19:11:35] [Server thread/ERROR]:&nbsp;[ViaVersion] Unable to inject ViaVersion, please post these details on our GitHub and ensure you're using a compatible server version.
269 | [19:11:35] [Server thread/ERROR]:&nbsp;[ViaVersion] ViaVersion failed to inject:
270 | [19:11:35] [Server thread/WARN]:&nbsp;java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.MinecraftServer
271 | [19:11:35] [Server thread/WARN]:&nbsp;at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142)
272 | [19:11:35] [Server thread/WARN]:&nbsp;at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
273 | [19:11:35] [Server thread/WARN]:&nbsp;at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
274 | [19:11:35] [Server thread/WARN]:&nbsp;at java.base/java.lang.Class.forName0(Native Method)
275 | [19:11:35] [Server thread/WARN]:&nbsp;at java.base/java.lang.Class.forName(Class.java:375)
276 | [19:11:35] [Server thread/WARN]:&nbsp;at com.viaversion.viaversion.bukkit.util.NMSUtil.nms(NMSUtil.java:38)
277 | [19:11:35] [Server thread/WARN]:&nbsp;at com.viaversion.viaversion.bukkit.platform.BukkitViaInjector.getServerConnection(BukkitViaInjector.java:262)
278 | [19:11:35] [Server thread/WARN]:&nbsp;at com.viaversion.viaversion.bukkit.platform.BukkitViaInjector.inject(BukkitViaInjector.java:58)
279 | [19:11:35] [Server thread/WARN]:&nbsp;at com.viaversion.viaversion.ViaManagerImpl.init(ViaManagerImpl.java:94)
280 | [19:11:35] [Server thread/WARN]:&nbsp;at com.viaversion.viaversion.ViaVersionPlugin.onEnable(ViaVersionPlugin.java:135)
281 | [19:11:35] [Server thread/WARN]:&nbsp;at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
282 | [19:11:35] [Server thread/WARN]:&nbsp;at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
283 | [19:11:35] [Server thread/WARN]:&nbsp;at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
284 | [19:11:35] [Server thread/WARN]:&nbsp;at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495)
285 | [19:11:35] [Server thread/WARN]:&nbsp;at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409)
286 | [19:11:35] [Server thread/WARN]:&nbsp;at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:607)
287 | [19:11:35] [Server thread/WARN]:&nbsp;at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264)
288 | [19:11:35] [Server thread/WARN]:&nbsp;at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986)
289 | [19:11:35] [Server thread/WARN]:&nbsp;at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
290 | [19:11:35] [Server thread/WARN]:&nbsp;at java.base/java.lang.Thread.run(Thread.java:831)

### Bug Description

When I try to connect on my 1.17 server with an older version, I can't.
There's a message : "Outdated client! Please use 1.17"
It's problematic because 1.17 doesn't work on my computer and there are plugins wisch work only in 1.17, and ViaVersion and ViaBackwards are the only solutions to play on my server....

Can you help me please ? :(

### Steps to Reproduce

1) Login with an older version than 1.17
2) Login in a Spigot Server in 1.17
3) See by yourself..

### Expected Behavior

Connect to a 1.17 server with an older client

### Additional Server Info

I don't use a proxy.
I use the following plugins : 
- EasyRanks
- EssentialsX
- Factions
- Massivecore
- WorldEdit
- WorldGuard
- GeyserMC
- Floodgate

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Update to ci builds.
