### ISSUE TITLE
Reloading/Restarting removes most comments from config

### ISSUE THREAD

**Issue by BrainStone** [ViaVersion/ViaVersion#2536]
### `/viaversion dump` Output

https://dump.viaversion.com/c3246b009b7a3baaac03e0395b6902e5db31e4ae012ed1e1ae2e65b26ed6bc25

### Console Error

No errors.

However here are the config files: https://paste.gg/p/anonymous/ecfe1fba7fc9447bac50e54246423c64

### Bug Description

Reloading the plugin or restarting the server removes all comments from the config after the `block-protocols` setting.

### Steps to Reproduce

1. Use my `config-before.yml` as your `config.yml`
2. Reload the plugin with `/viaver reload` or restart the server
3. Notice all comments after the `block-protocols` setting have vanished.

### Expected Behavior

All comments stay in the file.  
Ideally modified comments remain, but enforcing the default comments would be acceptable as well.

### Additional Server Info

I also use a BungeeCord, though the issues are not player related, so I don't see that being relevant. If needed I'll supply my plugin list here anyways.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Jo0001** [comment]
The problem is the `.` after the linebreak of `block-disconnect-msg` so `xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx x.` works fine as `xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx .x` removes the comments below.

**Comment by BrainStone** [comment]
The message was autoformatted like that.

**Comment by KennyTV** [comment]
Use quotes/proper yaml multi line strings, that should prevent it from happening.

**Comment by BrainStone** [comment]
Single quotes get removed automatically. Will try other methods.  
Regardless the autoformatter should not mess up the file in such a fashion.

**Comment by BrainStone** [comment]
Absolutely not solved. No matter how I configure the string in the config, ViaVersion always reformats the file as shown in my paste, consequently messing up the comments!

**Comment by KennyTV** [comment]
Hmm, I doubt we can easily fix this without bundling our own snakeyaml/expanding further on it, since we depend on what the server platforms bundle (at which point I'd like to just switch to configurate).

**Comment by BrainStone** [comment]
+1 for configurate. Great library, can only recommend!

**Comment by BrainStone** [comment]
Requesting to reopen this again (as I can't and) as this is still an issue on the latest dev version

**Comment by KennyTV** [comment]
Sorry, this is going to be a wont-fix given it is a bit of a ultra corner-case and pretty much a non-issue... At least until we switch configuration libraries.
