### ISSUE TITLE
Does not let me connect with 1.16

### ISSUE THREAD

**Issue by CoderBoyo** [ViaVersion/ViaVersion#2539]
### `/viaversion dump` Output

https://dump.viaversion.com/45ce3dd99e6c3e25d99cd8d34da037b436866b76ba828aa39b4ec6beabf100e6

### Console Error

N/A

### Bug Description

Doesn't let me login with 1.17 client to a 1.16 server.
Have tried all dev versions.

### Steps to Reproduce

1. Get a 1.16 server
2. Try to login with 1.17
3. Doesn't work

### Expected Behavior

It should allow me to login with 1.17

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by FormallyMyles** [comment]
You haven't updated Bungee or whatever proxy you use.

If you don't use bungee, remove plugins and test.

You can use our discord for this kind of support.
