### ISSUE TITLE
Bug with items

### ISSUE THREAD

**Issue by msmanui** [ViaVersion/ViaVersion#2540]
### `/viaversion dump` Output

I dont want to share this.

### Console Error

https://paste.gg/p/anonymous/de3aaa2da744402babdc73dd948be4a5

### Bug Description

It spams the console.
Im using lastest dev builds (13/06/2021)

### Steps to Reproduce

.

1. Just rename items with colors and put in your inventory or hit.
2. 

### Expected Behavior

f

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Follow the issue template.
