### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by coco0325** [ViaVersion/ViaVersion#2541]
### `/viaversion dump` Output

https://dump.viaversion.com/4dcd7134b6bcfa34a289bf8bb5b5cf0237bb0e721262029ca0d0f185d3a4daa6

### Console Error

No error.

### Bug Description

Trying to log into a 1.16.5 tuinity server then get this 
![image](https://user-images.githubusercontent.com/22321097/121826692-b4f0e880-cceb-11eb-9906-09ee440735f7.png)

### Steps to Reproduce

Login with a 1.17 client.

### Expected Behavior

Able to login.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Can you try to reproduce this without other plugins? Also, make sure you are running Via only on either backend or the proxy, not both

**Comment by andrsn0w** [comment]
I have exactly same issue, after updating Waterfall

**Comment by KennyTV** [comment]
What about Waterfall build 436?

**Comment by coco0325** [comment]
> Can you try to reproduce this without other plugins? Also, make sure you are running Via only on either backend or the proxy, not both

I only install Viaversion on waterfall.

**Comment by KennyTV** [comment]
see #2546
