### ISSUE TITLE
Cant Map from 1.16.x to 1.17

### ISSUE THREAD

**Issue by RealMangorage** [ViaVersion/ViaVersion#2542]
### `/viaversion dump` Output

 https://dump.viaversion.com/8f93720c11f44c817147f77104f2feee1e384f566cee3b99ab0d95abebda3f0e

### Console Error

```
Put the paste.gg link or text here.
```
13.06 23:47:38 [Server] Server thread/ERROR [ViaVersion] Unable to inject ViaVersion, please post these details on our GitHub and ensure you're using a compatible server version.
13.06 23:47:38 [Server] Server thread/ERROR [ViaVersion] ViaVersion failed to inject:
13.06 23:47:38 [Server] Server thread/WARN java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.MinecraftServer
13.06 23:47:38 [Server] Server thread/WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142)
13.06 23:47:38 [Server] Server thread/WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
13.06 23:47:38 [Server] Server thread/WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
13.06 23:47:38 [Server] Server thread/WARN at java.base/java.lang.Class.forName0(Native Method)
13.06 23:47:38 [Server] Server thread/WARN at java.base/java.lang.Class.forName(Class.java:375)
13.06 23:47:38 [Server] Server thread/WARN at com.viaversion.viaversion.bukkit.util.NMSUtil.nms(NMSUtil.java:38)
13.06 23:47:38 [Server] Server thread/WARN at com.viaversion.viaversion.bukkit.platform.BukkitViaInjector.getServerConnection(BukkitViaInjector.java:262)
13.06 23:47:38 [Server] Server thread/WARN at com.viaversion.viaversion.bukkit.platform.BukkitViaInjector.inject(BukkitViaInjector.java:58)
13.06 23:47:38 [Server] Server thread/WARN at com.viaversion.viaversion.ViaManagerImpl.init(ViaManagerImpl.java:94)
13.06 23:47:38 [Server] Server thread/WARN at com.viaversion.viaversion.ViaVersionPlugin.onEnable(ViaVersionPlugin.java:135)
13.06 23:47:38 [Server] Server thread/WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
13.06 23:47:38 [Server] Server thread/WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
13.06 23:47:38 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
13.06 23:47:38 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495)
13.06 23:47:38 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409)
13.06 23:47:38 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:608)
13.06 23:47:38 [Server] Server thread/WARN at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264)
13.06 23:47:38 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987)
13.06 23:47:38 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
13.06 23:47:38 [Server] Server thread/WARN at java.base/java.lang.Thread.run(Thread.java:831)
13.06 23:47:38 [Server] Server thread/INFO [ViaBackwards] Enabling ViaBackwards v4.0.0

### Bug Description

Not loading Maps from 1.16.x -> 1.17

### Steps to Reproduce

Just load Via Version and Via Backwards with Spigot 1.17

### Expected Behavior

I excepted that it would load properly

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Camotoy** [comment]
Update to the builds from the CI.
