### ISSUE TITLE
[Protocol1_16_4To1_17] Switching worlds triggers error

### ISSUE THREAD

**Issue by tildearrow** [ViaVersion/ViaVersion#2543]
### `/viaversion dump` Output

https://dump.viaversion.com/1629db4901ad00435d9ee14edeacd40594c069c599a2a55d6f4b629725b17b84

### Console Error

https://paste.gg/p/anonymous/5554dea5119c4666970ea5c0432eefee

### Bug Description

Switching worlds causes the user to be disconnected.

### Steps to Reproduce

1. Log in with 1.16.5 on 1.17 server
2. Switch worlds

### Expected Behavior

Switched to world; no disconnection.

### Additional Server Info

Using BungeeCord with private plugin (the only installed plugin).
This server is running CraftBukkit version 3132-Spigot-66f9d3c-40caacc (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
Using ViaVersion and ViaBackwards compiled from master branch.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
https://github.com/ViaVersion/ViaBackwards/commit/13d27a6f4dd36d7494f878ea3dfe09968539539b
