### ISSUE TITLE
Packet spawned Armorstand doesn't function properly with 1.16.5 server and 1.17 client

### ISSUE THREAD

**Issue by LOOHP** [ViaVersion/ViaVersion#2545]
### `/viaversion dump` Output

https://dump.viaversion.com/6d98ca7b4ebfb11a403e5d04b6937dcedd1928d2c7945389c744c5829e4d2f1a

### Console Error

```
N/A
```

### Bug Description

When spawning invisible armorstands using packets on a 1.16.5 server, they don't appear on a 1.17 client through viaversion as they would on 1.16.

I've created the code below to reproduce the issue:
https://gist.github.com/LOOHP/c662b0776bf683518604589bc602bb83

With that piece of code, when the armorstand is spawned, 
On a 1.16.5 client:
1. If you go into spectator mode, you will be able to see an invisible armorstand.
2. If you place a crafting table between you can the armorstand, you will be able to click through it

On a 1.17 client:
1. If you go into spectator mode, you see nothing
2. If you place a crafting table between you can the armorstand, you can't click through it as if it is obstructed
3. If you place a block inside of the armorstand, you don't have the place block hand swing, probably because the client believes that there is something there

### Steps to Reproduce

Steps to reproduce included in the Bug Description

### Expected Behavior

Clients on 1.17 should behavior the same as 1.16.5 clients

### Additional Server Info

ViaVersion is only installed on backend Paper 1.16.5 server tho it is behind a waterfall proxy.
(ViaVersion is not installed on the proxy)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
You have to use different uuids for the virtual entities.

**Comment by LOOHP** [comment]
Thank you for the quick response. I'm not aware as it worked for so many versions prior.

**Comment by KennyTV** [comment]
Yeah this sanity check was newly introduced in 1.17 clients. Given it's so small of a change for plugins sending virtual entities and would otherwise just mean randomizing duplicate uuids in Via (even if not intended?), it's best to just be done in the plugins sending them.
