### ISSUE TITLE
NPE with boss bar API after upgrading to v4.0.0

### ISSUE THREAD

**Issue by LeonTG** [ViaVersion/ViaVersion#2547]
### `/viaversion dump` Output

https://dump.viaversion.com/c5fda584315905ea5b9557f3c79397dd62e14ead528fbdbc53471b1da4ed14f3

### Console Error

https://paste.gg/p/anonymous/644460c716a04989a77e86040545e690

The paste contains both the 4 NPEs I get and my code from where the errors occurr.

### Bug Description

The code in the paste sometimes causes the errors in the paste, however it does not happen everytime someone joins/leaves/changes world. I have no idea whats causing it or how it doesn't happen everytime

Sometimes when I log on on 1.16.5, I get the boss bar but it's permanently stuck in 1 mode, and sometimes it works without any issues when on the same version.

### Steps to Reproduce

I don't even know how to reproduce it myself, it's very inconsistent and unpredictable, but very frequent despite the majority of our players using 1.8 and the code not doing anything for 1.8 players.

All I know is this was not an issue before I upgraded to 4.0.0 to get 1.17 support.

My theory is that the UserConnection is null for the player I attempt to add/remove from the boss bar, however that only might explain why it happens in the login event, not the logout, change world events or the task updating the boss bar every so often as by then it shouldn't be null anymore, unless I've misunderstood how the code works.

### Expected Behavior

The code should not cause errors on join/leave/world change and it should update properly when ingame like it did before v4.0.0

### Additional Server Info

I do use BungeeCord and the plugin information should all be in the viaversion dump. I only have ViaVersion on the backend servers.

I haven't changed the code logic, the errors I've provided happened even before I updated the imports in the code to the new 4.0.0 classpaths.

I hope all the information I have provided is enough, if not please lmk!

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
We now remove UserConnections from our cached immediately when the channel is closed. Assuming all of this only happens if a player disconnects during any of these events, sanity checks on our end before packet sending should be enough, I'll look into that.
