### ISSUE TITLE
Players are invisible if you are on 1.13+ in ViaVersion 4.0.0

### ISSUE THREAD

**Issue by SkyBoiMC** [ViaVersion/ViaVersion#2548]
### `/viaversion dump` Output

https://dump.viaversion.com/16c8196fa5d176f1e0a115614f149a6dbdb6ff1a544026c580e354fdcc27168f

### Bug Description

Me & another server owner I know both experienced players on 1.13+ not being able to see anyone most or all of the time (can't be sure yet). This only occurs in the latest version of ViaVersion. I'm using 1.12.2 and the other person I mentioned is using 1.8.?. I'd like to support 1.17 so I'd really appreciate this being fixed soon (It also seems like a pretty big issue).

### Steps to Reproduce

Log in on 1.13 - 1.17
Log in on 1.8 - 1.12 at the same time on the same server
If the player on 1.13+ can see the other one, being teleported could be the problem. Try teleporting the 1.13+ account to you and test again.

### Expected Behavior

Being able to see anyone who isn't vanished

### Additional Server Info

I use Spigot 1.12.2, and the latest version of waterfall as my proxy

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Update BungeeTabListPlus

**Comment by SkyBoiMC** [comment]
This isn't fixed, sorry for not saying this sooner, but I was making sure it was still broken.
