### ISSUE TITLE
Kicked from the server for interacting with a villager

### ISSUE THREAD

**Issue by Sikatsu** [ViaVersion/ViaVersion#2551]
### `/viaversion dump` Output

https://dump.viaversion.com/65a1ce552a8c0958fe1cbfa30a985c389ca85ae17b9eeb66db7d5c794e3f36cf

### Console error

https://pastebin.com/jqvxUNbk

### Bug Description

When shift + right clicking on a villager, to find a villager his workstation using the following plugin: https://www.spigotmc.org/resources/villager-workstation-highlights.81498/ it will kick me from the server with a ViaVersion error.

### Steps to Reproduce

1. Login with a 1.17 client
2. Shift + right click a villager, using a setup from the image below
3. Get kicked

![image](https://user-images.githubusercontent.com/5664135/122189616-5b2a2300-ce91-11eb-9463-3259fdb8f2c8.png)

![image](https://user-images.githubusercontent.com/5664135/122189833-8dd41b80-ce91-11eb-8e7a-c906680ab2a3.png)

### Expected Behavior

Not to be kicked from the server

### Additional Server Info

We use bungeecord, Waterfall/Tuinity combination.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by AlecMcQuarrie** [comment]
Same thing happens on my server
Here's a screenshot of the console when stuff like that happens to me
![Screen Shot 2021-06-16 at 11 19 16 AM](https://user-images.githubusercontent.com/42359278/122277112-86256e80-ceb3-11eb-9510-1ccf3c6d0d53.png)

**Comment by AlecMcQuarrie** [comment]
I think it's a bug with viabackwards, so I reported this to the repository there as well. It literally SPAMS my console with this hundreds of times. My server has also been crashing due to other viaversion bugs, so this might be one of them as well.

**Comment by Sikatsu** [comment]
I personally don't use viabackwards, but maybe it's a bug with both plugins.

**Comment by AlecMcQuarrie** [comment]
Well the error may be in viaversion itself, but I did see a warning from viabackwards in the above screenshot. I know viaversion is the main dependency for viabackwards, so I assume it is a problem with viaversion. Hopefully we can get some sort of response soon

**Comment by Ccode-lang** [comment]
Are you using the compatible versions of the game?  I'll read the error and see what is wrong.

**Comment by AlecMcQuarrie** [comment]
I am using purpur at the moment. I am not sure about OP though

**Comment by Sikatsu** [comment]
Tuinity/Waterfall combination.

**Comment by AlecMcQuarrie** [comment]
To add to the discussion, here is a viaversion dump of my own server: https://dump.viaversion.com/f763e44ea9ca66fb87a6a7eac92a2871032e481ec0b031eae1a5e561f5fb6bb4

I get between 40-70 players on at any given time, so I want to get to the bottom of this to have better stability xD

**Comment by Ccode-lang** [comment]
It looks to be a bug with 1.14 villagers changing over to 1.17.  What server version are you using?

**Comment by AlecMcQuarrie** [comment]
git-Purpur-1165 (MC: 1.16.5) for myself. OP mentioned he was using tunity/waterfall

**Comment by Ccode-lang** [comment]
Have you yes

**Comment by Ccode-lang** [comment]
Does this server implement full spigot/bukkit/paper api?

**Comment by AlecMcQuarrie** [comment]
Yes it does.

**Comment by AlecMcQuarrie** [comment]
![Screen Shot 2021-06-16 at 3 27 54 PM](https://user-images.githubusercontent.com/42359278/122280664-6ee88000-ceb7-11eb-8995-93ccc7c5b8f8.png)

**Comment by AlecMcQuarrie** [comment]
Above you can see the server files and the configs they use ^^

**Comment by Ccode-lang** [comment]
Ok 👍

**Comment by Ccode-lang** [comment]
Honestly it could be because of the number of plugins on the server. Another possibility is that there is something wrong with the villager code.

**Comment by AlecMcQuarrie** [comment]
Well multiple users are having the same problem unfortunately. My guess is that it would be something wrong with the code.

**Comment by Ccode-lang** [comment]
That's my guess to, the code is completely new and untested.

**Comment by Ccode-lang** [comment]
We'll have to wait for a maintainer to know exactly what the problem is.

**Comment by Jo0001** [comment]
Vanilla Villagers are working fine (latest 1.16.5-Paper+latest Via* 4.0.1; latest waterfall with latest  Via* 4.0.1 and latest 1.16.5-Paper).
I think its down to Villager Workstation Highlights.
Can you try it on a new testserver with same config but just Via* and Villager Workstation Highlights installed?

**Comment by Sikatsu** [comment]
I tested on a test server with only that plugin installed.

If the test server runs 1.17: 
When shift + right clicking a villager it works and shows me the workstation in chat.

If the test server runs 1.16.5:
When shift + right clicking (or even when aiming /vwh at a villager) I am being kicked from the network.

Note: I can interact with villagers just fine, normal right click for example. Only when doing it in combination with a plugin this issue happens.

**Comment by Sikatsu** [comment]
Oh and ViaVersion is installed on the bungee only.

**Comment by AlecMcQuarrie** [comment]
When will this be fixed? Can you post a dev branch if you get this fixed? It's spamming my console

**Comment by Jo0001** [comment]
Just use the latest Via* builds from the ci 
https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/build/libs/ViaVersion-4.0.1-SNAPSHOT.jar

**Comment by AlecMcQuarrie** [comment]
Does that have the villager fix? I looked at their dev build notes and I didn't see the fix for it

**Comment by Jo0001** [comment]
Kenny fixed this 2 days ago in 5cdaabe
Just look one message above yours

**Comment by AlecMcQuarrie** [comment]
ah okay sick
