### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Porkason** [ViaVersion/ViaVersion#2552]
### `/viaversion dump` Output

https://dump.viaversion.com/104a38c64683fe6a3f5542bdbdb70aa16ea78e5ea5b128ae918a9838839d640f

### Console Error

https://pastebin.com/Leb9WZCy

### Bug Description

No idea tbh just checked console and told me to post this. 

### Steps to Reproduce

1.16.4 client on 1.16.5 server

### Expected Behavior

No idea. 

### Additional Server Info

Waterfall

Purpur 1.16.5

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Someone is sending bad packets, nothing we can do about that.

**Comment by Porkason** [comment]
> 
> 
> Someone is sending bad packets, nothing we can do about that. Via doesn't modify clients on the same protocol as the server (1.16.4=1.16.5). Either update to ci builds, or figure out what else is breaking it.

ok sorry, just thought since it litterally told me to create this i was supposed to.
