### ISSUE TITLE
ViaVersion not starting up on 1.17 server

### ISSUE THREAD

**Issue by TimofeiShep** [ViaVersion/ViaVersion#2554]
### `/viaversion dump` Output

https://dump.viaversion.com/866afe7866c50631a4a48f2bdb17b9d3c5fc579ab4ba2db4212c6c1ce7483482

### Console Error

```
https://paste.gg/p/anonymous/582ba066dd2045d09c393055086e0dcd
```

### Bug Description

When I start the server ViaVersion fails to inject itself I have no idea why

### Steps to Reproduce

1. Start a 1.17 server

### Expected Behavior

ViaVersion to actually launch

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by creeper123123321** [comment]
Use latest from ci.viaversion.com
