### ISSUE TITLE
Class Not Found Exception

### ISSUE THREAD

**Issue by Obliviated** [ViaVersion/ViaVersion#2556]
### `/viaversion dump` Output

https://dump.viaversion.com/39b7d2a25a2d50797aad03b94136bfdc13100bff4b7d1169d0fb9de30c44d63d

### Console Error

When i updated ViaVersion (v3.2.1 -> v4.0.0) my plugins has started error prints. Also i tried latest version (4.0.1-snapshot #522)

An example error stack trace from TuSKe plugin (also SpigotGuard gives too.):
https://pastebin.ubuntu.com/p/KCJVXGpVkc/

### Bug Description

i updated via version from v3.2.1 to 4.0.0 and i tried 4.0.1-snapshot build522

### Steps to Reproduce

update via version.

### Expected Behavior

should be clean log.

### Additional Server Info

![image](https://user-images.githubusercontent.com/36128276/122417485-2fdb2d00-cf92-11eb-88ee-5bcbfdc18f3f.png)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
4.0.0 has major api break which plugins have to update to.

**Comment by Obliviated** [comment]
> 4.0.0 has major api break which plugins have to update to.

thanks so what version you recommended for before api break?

**Comment by KennyTV** [comment]
3.2.1 is the last before it that you can use
