### ISSUE TITLE
Maps have "VarInt" too big error

### ISSUE THREAD

**Issue by bchubbs** [ViaVersion/ViaVersion#2560]
### `/viaversion dump` Output

https://dump.viaversion.com/b96a8f11f14bcd454088cb25c242b7317d4a9d9f9133455580f330ba597720a0

### Console Error

https://paste.gg/p/anonymous/a7f7fe799f2f4ad2a2ae9cd6e227329b

### Bug Description

Our 2FA setup maps seem to be incompatible with 1.17. 
When you run the /setup2fa command, the player is kicked because of some weird packet error. 

https://prnt.sc/15z4xfd

### Steps to Reproduce

I'm not really sure this is possible, we have a custom plugin to support 2FA.
We found this bug logging in with 1.8 on the 1.17 server.

### Expected Behavior

Player should receive a map with a QR code to scan in their 2FA App (Google Auth, Authy, etc) after running /setup2fa.

### Additional Server Info

We use Waterfall 1.17, and Spigot 1.17.

The only free/public plugins we use is ViaVersion, ViaBackwards, ViaRewind, ProtocolLib and WorldEdit. 

To be clear, Krypton (the 2fa plugin in question) is the ONLY plugin that uses/interferes with maps on the server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Use ci builds.
