### ISSUE TITLE
(Was closed and not fixed) Players are invisible if you are on 1.13+ in ViaVersion 4.0.0

### ISSUE THREAD

**Issue by SkyBoiMC** [ViaVersion/ViaVersion#2562]
### `/viaversion dump` Output

https://dump.viaversion.com/81c770ea092fe197643f65e5d1cc9f2c239de3f94018df564220c31f2f15afed

### Bug Description

(This is a duplicate, but you closed it and it wasn't fixed)

Me & two other server owners I know all experienced players on 1.13+ not being able to see anyone. This only occurs in the latest version of ViaVersion. I'm using 1.12.2 and the other people I mentioned are using 1.8.?. I'd like to support 1.17 (which will help the server tremendously), but I can't if this isn't fixed soon. Also, I know last time you said it was BungeeTabListPlus, but I'm the only one out of the 3 of us who uses it, so it can't be.

### Steps to Reproduce

Start a server on 1.12.2 or below (I don't know if it's required, but just to be safe)
Log in on 1.13 - 1.17
Log in on 1.8 - 1.12 at the same time on the same server
If the player on 1.13+ can see the other one, being teleported could be the problem. Try teleporting the 1.13+ account to you and test again.

### Expected Behavior

Being able to see anyone who isn't vanished

### Additional Server Info

I use Spigot 1.12.2, and the latest version of waterfall as my proxy

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Camotoy** [comment]
Have you updated BungeeTabListPlus as Kenny said in the previous issue?

**Comment by SkyBoiMC** [comment]
Yeah I have, I didn't update the spigot hook which is probably what's showing in the dump

**Comment by KennyTV** [comment]
Firstly, update to ci builds. The text is a bit confusing - what client versions don't see other players? And please try to reproduce this without other plugins.

**Comment by SkyBoiMC** [comment]
> Firstly, update to ci builds. The text is a bit confusing - what client versions don't see other players? And please try to reproduce this without other plugins.

1.13+ clients don't see anyone, and I'll do that in a bit

**Comment by SkyBoiMC** [comment]
I can't reproduce with vanilla or with switching worlds in multiverse, so I'll try trial and error and let you know if its fixed  or what's not compatible.

**Comment by SkyBoiMC** [comment]
I've tried with all the plugins and still haven't found the problem, so I'm going to try BungeeCord ViaVersion to see if I can get that to work.

**Comment by SkyBoiMC** [comment]
Seems to have fixed it, no idea what the problem was, but using the proxy version fixed it.
