### ISSUE TITLE
1.13 -> 1.12 Sprint Problem

### ISSUE THREAD

**Issue by JustLonelyy** [ViaVersion/ViaVersion#2563]
### `/viaversion dump` Output

https://dump.viaversion.com/d2323ec5ac336597d7def3f561ab7ad8ae9455657d8780f5cf9dddbd9e0f5568

### Console Error

No Console Errors

### Bug Description

Sometimes you can sprint with low food level on 1.12 and lower

### Steps to Reproduce

No problems in 1.13 client
but in 1.12 and lower sometimes you can sprint with low food level

### Expected Behavior

Shouldn't sprint with low food level

### Additional Server Info

Server Version 1.13
Plugins:
DiscordSRV
LuckPerms
NametagEdit
PlugMan
ProtocolLib
Vault
ViaVersion
ViaBackwards
ViaRewind

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
That's entirely client side.

**Comment by JustLonelyy** [comment]
> That's entirely client side.

Isn't it unfair that players can sprint on 1.12 and lower?
