### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by KolakZ** [ViaVersion/ViaVersion#2564]
### `/viaversion dump` Output

https://dump.viaversion.com/7df8d2105acf37fd34dc28a7fd29c1eb8f28d61f11ad403e69e4e9dff03e2af8

### Console Error

```
https://pastebin.com/mmbgx6EC
```

### Bug Description

I am getting an error in console.

### Steps to Reproduce

Use the latest ViaVersion snapshot.

### Expected Behavior

I should not get an error in console.

### Additional Server Info

I use Waterfall with UltraStaffChat, TCPShield, ServerListPlus, NuVotifier, MultiLobby, LuckPerms, and BuycraftX.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Update ViaBackwards.

**Comment by KolakZ** [comment]
To the latest snapshot or developer build?
