### ISSUE TITLE
When crafting multiple items kicks out of the server

### ISSUE THREAD

**Issue by 1thenikita** [ViaVersion/ViaVersion#2567]
### `/viaversion dump` Output

https://dump.viaversion.com/ae64f902a27bd846da519f72a8dfaa13c9800d28a55f76d65c7d74a0bead38cc

### Console Error

```
https://paste.gg/p/anonymous/ad1a6c4f62bb43f3b6547743d1f34adb
```

### Bug Description

When crafting multiple items kicks out of the server. 1.16.5;
1. Let's get some trees
2. Let's try to Shift to pick them up
3. ![image](https://user-images.githubusercontent.com/35877788/122745203-6fa35c80-d291-11eb-9b12-8bb1d6621231.png)

### Steps to Reproduce

When crafting multiple items kicks out of the server. 1.16.5;
1. Let's get some trees
2. Let's try to Shift to pick them up
3. ![image](https://user-images.githubusercontent.com/35877788/122745203-6fa35c80-d291-11eb-9b12-8bb1d6621231.png)

### Expected Behavior

Not error and kicking from server.

### Additional Server Info

Plugins (24): AdvancedBan, BetterRTP, Chatty, CMI, CMILib, CommandPrompter, ConsoleSpamFix, CoreProtect, DeluxeMenus, eZProtector, HealthBar*, JukeBox, LuckPerms, Multiverse-Core, NametagEdit*, NoteBlockAPI, PlaceholderAPI, ProtocolLib, TitleManager, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldBorder

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Use ci builds.
