### ISSUE TITLE
NoSuchElementException: com.viaversion.viaversion.protocols.protocol1_9to1_8.Protocol1_9To1_8

### ISSUE THREAD

**Issue by hanbings** [ViaVersion/ViaVersion#2568]
### `/viaversion dump` Output

https://dump.viaversion.com/74f28cef4a7ff408ed96973bb7c7ef9f49eea799f6a8782e6f3c3f911954f475

### Console Error

```
Put the paste.gg link or text here.
```
https://pastebin.ubuntu.com/p/6MtnjGcpDT/

### Bug Description

This error occurs when I cross the server from a high version game server (1.16.5) to a low version (1.8.8) game server, and return from a low version game server to the same high version game server

### Steps to Reproduce

1. use 1.12 into 1.16.5 server
2. use /server xxx into 1.8.8 from 1.16.5
3. use /server xxx return 1.16.5 from 1.16.5

### Expected Behavior

I checked the code of ViaVersion once and found that this exception seems to be artificially thrown. It is located in 

**package com.viaversion.viaversion.protocol.packet
class PacketWrapperImpl
line #278**

”// The given protocol is not in the pipeline
  **throw new NoSuchElementException(packetProtocol.getCanonicalName());**"
But in fact the player can play the game normally.
I think this exception was thrown by mistake.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Fixed in https://github.com/ViaVersion/ViaVersion/commit/44d836e2e732e3525de5b8c3958719115f86a6c7
