### ISSUE TITLE
Boss bars error using 4.0.0+

### ISSUE THREAD

**Issue by SpEeD11** [ViaVersion/ViaVersion#2570]
### `/viaversion dump` Output

https://dump.viaversion.com/87688f721837bdfd0451afbabfed658fc31c49ea5de4e84774af402230f3a349

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Followup to https://github.com/ViaVersion/ViaVersion/issues/2521 (refer to the later comments)
Seems like the fix was only for ViaBackwards and the issue occurs with only ViaVersion installed.

To re-iterate the bug:
Boss bars are always showing at 100% for non base-version clients.
When suppress-metadata-errors: false, this spams the console each time a boss bar message is shown: https://pastebin.com/E6tKpCB5
Tested with latest dev build and this is still occurring.

### Steps to Reproduce

1. Use ViaVersion 4.0.0+
2. display a custom boss bar message to any client not using the base server version

### Expected Behavior

the boss bar should not always be at 100% and should not spam errors

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
That's down to your bossbar api plugin sending bad/non-existent metadata. We now ignore that meta since so many people use that plugin and it's been unmaintained for a while, but it is still important to note.
