### ISSUE TITLE
ViaVersion 4.x incompatible with Velocity 1.1.x ?

### ISSUE THREAD

**Issue by x9nico** [ViaVersion/ViaVersion#2573]
### `/viaversion dump` Output

 https://dump.viaversion.com/ba9ebd6f8c602f52c2404b51511653b3ac0575b707762eebf32ae1605a945344

### Console Error

```
Put the paste.gg link or text here.
```
https://pastebin.com/S2bdGwT8

### Bug Description

When I'm starting my server as Velocity proxy, it provides these errors.

### Steps to Reproduce

1. Create a Server with Velocity
2. Set ViaVersion on your server
3. It provides errors

### Expected Behavior

The server should load correctly

### Additional Server Info

Velocity version: 1.1.8
I'm using Modern forwarding.
I tried with latest dev builds of ViaVersion, it does the same thing.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
ViaVersion ci builds are compatible with Velocity 3.0.0, but there won't be 1.1.5+ compat due to missing internal api.
