### ISSUE TITLE
Bug on dev version 4.0.1-SNAPSHOT

### ISSUE THREAD

**Issue by elNino0916** [ViaVersion/ViaVersion#2575]
### `/viaversion dump` Output

https://dump.viaversion.com/1128abeacfbcbe93d5ac931a9b50156c02a97033687a03ca09f4a0e916c23d99

### Console Error

```
https://paste.gg/p/anonymous/dd3720a6501a4550bc284d2371ce3a81
```

### Bug Description

Join with a 1.12.2 client then will shows "Disconnected"

### Steps to Reproduce

1. Login with a 1.12.2 client

### Expected Behavior

That i can join on my mc server with 1.12.2.

### Additional Server Info

Plugins: Essentials,Maintenance,EssentialsChat,Plugman,AdvancedBan,TAB,Viaversion,EssentialsSpawn,ViaBackwards,Multiverse-Core,ViaRewind,Skywars,ViaRewind-Legacy-Support

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Update ViaBackwards and ViaRewind as well.
