### ISSUE TITLE
ViaVersion Error in Protocol

### ISSUE THREAD

**Issue by EinfxchJakob** [ViaVersion/ViaVersion#2576]
### `/viaversion dump` Output

https://dump.viaversion.com/52503c8083f67810e32f48d04df1e076f5a8689a523f0ac7b6e27559fd702df8

### Console Error

```
22:58:08 [WARNING] [ViaVersion] ERROR IN Protocol1_16To1_15_2 IN REMAP OF CHUNK_DATA (0x22)
22:58:08 [WARNING] [Aegis] [EinfxchJakob,/ :62687] <-> InitialHandler - Exception caught! us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Source 0: us.myles.ViaVersion.protocols.protocol1_16to1_15_2.packets.WorldPackets$2 (Anonymous)}
Actual Error: 
```

### Bug Description

If players connect with any version,
they will be kicked for "Connection Lost" and the error will be displayed in the Bungeecord Console.

### Steps to Reproduce

I dont know

### Expected Behavior

Players should be able to join lol

### Additional Server Info

I also use Bungeecord with the fork "Aegis"
and the plugins are: ViaVersion and Yamler-Bungee

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
You are horribly outdated.
