### ISSUE TITLE
EasyNick & ViaVersion bug

### ISSUE THREAD

**Issue by Bulldo344** [ViaVersion/ViaVersion#2577]
### `/viaversion dump` Output

https://dump.viaversion.com/3035ebe6eedb91442e8e4cee8681ebaf87502f8831b9325026bc8815efdc3ad8

### Console Error

https://paste.shockbyte.com/wanizotowunurucapeka

### Bug Description

https://cdn.discordapp.com/attachments/316208160232701955/857738498139488256/unknown.png

ViaVersion, ViaRewind, or ViaBackwards keep on crashing our game, whenever we install a nicking plugin. We've contacted the plugin developer, and he tried to help us and he said it was ViaVersion, ViaRewind, or ViaBackwards faults.,

### Steps to Reproduce

1. Install EasyNick API 
2. Install ViaVersion, ViaRewind, and etc.
3. Launch your minecraft, and join your server.

### Expected Behavior

ViaVersion, ViaRewind, or ViaBackwards keep on crashing our game, whenever we install a nicking plugin. We've contacted the plugin developer, and he tried to help us and he said it was ViaVersion, ViaRewind, or ViaBackwards faults.,

### Additional Server Info

EasyNick API & ViaVersion (or its allies)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Please paste the error to paste.GH

**Comment by KennyTV** [comment]
That nick plugin is going crazy on errors of all kinds, so I'll assume that's its fault.
