### ISSUE TITLE
can't go from survival to survival_nether or world_nether

### ISSUE THREAD

**Issue by LOLEMO** [ViaVersion/ViaVersion#2580]
### `/viaversion dump` Output

https://dump.viaversion.com/44513e3bfbbabd3d7fc8c52b580f7c32c54e7e5419f6bb760ed14c7811718d88

### Console Error

https://paste.gg/p/anonymous/c8a784b163694cb9890dfb5cbb01824d

### Bug Description

i was linking portals from world ro nether with multiverse nether portals but when i use a portal the server kiks me

### Steps to Reproduce

1. login
2. link portals of survival world to portals of survival_nether
3. enter a portal
4. get kiked 
5. 3000 lines of errors on the console

### Expected Behavior

go to the nether and that a portal is generated there to be able to return

### Additional Server Info

i use paper 1.12.2 and this plugins: _ArmorStandTools, BedWars, ChairStairs, ChestCommands, Citizens, CitizensServerSelector, Clans, ClearLag, ColoredSigns, ConsoleSpamFix, DeluxeHub, Essentials, EssentialsChat, Images, LeakParkour, LuckPerms, MessageFilter, MoneyHunters, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, MyCommand, OnePlayerSleep, Orebfuscator, PlaceholderAPI, ProtocolLib, ServerSigns, SimpleScore, SkinsRestorer, TAB, Vault, ViaBackwards, ViaVersion, WorldEdit, WorldGuard_

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Please see if you can reproduce the issue without other plugins (except for Via and maybe Multiverse)
