### ISSUE TITLE
EncoderException error on proxy joining from 1.8.8

### ISSUE THREAD

**Issue by vijaypondini** [ViaVersion/ViaVersion#2582]
### `/viaversion dump` Output

https://dump.viaversion.com/95b471f8e2bb40a82a21d60f26617c80cf83e5b2a593577d5c33ba512b7204f6

### Console Error

```
[13:22:16 WARN] [ViaVersion]: ERROR IN Protocol1_13_1To1_13_2 IN REMAP OF SET_SLOT (0x17)
[13:22:16 INFO]: [QuickestRhyme] disconnected with: EncoderException : com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: Byte, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_13_1to1_13_2.packets.InventoryPackets1_13_2$1 (Anonymous), Packet ID: 23}
Actual Error:  @ io.netty.handler.codec.MessageToMessageEncoder:10
```

### Bug Description

Trying to join my 1.17 server on 1.8.8 is not allowing me, with the console error above. I have viaversion dev build, and normal viabackwards and viarewind ( I used a viaversion dev build because of crossplay joining issues, as stated in geysermc bug tracker - https://github.com/GeyserMC/Geyser/issues/2295

### Steps to Reproduce

Have a waterfall 1.17 server setup
Have a backend server setup to connect to, that is also on the latest version of papermc
Have viaversion 4.0.1 dev build from the jenkins, viabackwards, and viarewind from spigotmc
Try to join on 1.8.8

### Expected Behavior

You should be able to join

### Additional Server Info

N.A

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
If you use release builds, all builds should be release; if you use -dev, all builds should be -dev, and so on.
