### ISSUE TITLE
random disconnects

### ISSUE THREAD

**Issue by NeviskDOBLOCO** [ViaVersion/ViaVersion#2583]
### `/viaversion dump` Output

https://dump.viaversion.com/bc558f7920ba753691b07699c6cc80dec88b03fadb14fd48b68b5c3d212980bd

### Console Error

https://pastebin.com/RwPCqtxs

### Bug Description

When using via version + via backwars to connect 1.16 on the server 1.17 players who are with the client 1.16 are being randomly disconnected and the above error appears on the console.

### Steps to Reproduce

1. Login on server
2. Walk

### Expected Behavior

was not disconnected

### Additional Server Info

waterfall: AdvancedBan, BanAnnouncer*, Citizens, FastAsyncWorldEdit (WorldEdit), GSit, HeadDatabase, HolographicDisplays, HolographicExtension, HubPvP*, LuckPerms, MyCommand, nLogin, OldCombatMechanics, PlaceholderAPI, PlugMan, ProtocolLib, ProtocolSupport, SkinsRestorer, Spicord*, SuperLobby, TAB, WorldGuard

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Do what the checklist says and use ci builds.

**Comment by NeviskDOBLOCO** [comment]
I literally just tested it and gave the same error with CI build, that's why I went ahead to open the issue https://pastebin.com/SK4fGdHN

**Comment by KennyTV** [comment]
You didn't update ViaBackwards
