### ISSUE TITLE
1.16.5 to 1.17 mapping bug

### ISSUE THREAD

**Issue by CocoTheOwner** [ViaVersion/ViaVersion#2585]
### `/viaversion dump` Output

https://dump.viaversion.com/f2fcb6602c54b1e5c2e7c0b607860e78289b9fcd0f7ffdfe8e4be141aecb9922

### Console Error

https://paste.gg/p/anonymous/f3f40ecbb4ed49cbae0277823b176acf

### Bug Description

Unknown behaviour resulting in not being able to join

### Steps to Reproduce

1. Login with a 1.16.5 client
2. This may be caused by some entity effects with Iris World Generator's Object Editing wand
3. Observe a crash

Oh yeah this is definitely due to that wand's particle effects.
Class for this wand can be found here: https://github.com/VolmitSoftware/Iris/blob/master/src/main/java/com/volmit/iris/manager/WandManager.java
This is not due to Iris most likely, as none of its classes can be found in the stacktrace. This makes me think it is only due to the particle effects themselves, in relation to the player percieving them.

### Expected Behavior

Being able to join, clearly.

### Additional Server Info

This server is running Paper version git-Paper-53 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 0ad5526)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Update to ci builds.

**Comment by CocoTheOwner** [comment]
I did, did not work. https://dump.viaversion.com/d00e10d1c31452c8fae3bc03131b386bce3da01ca60bb19726aea8d8e53b830d
Dont do that

**Comment by KennyTV** [comment]
`"git-ViaBackwards-4.0.0:54a979c"` is not updated

**Comment by CocoTheOwner** [comment]
"pluginVersion": "4.0.1-1.17.1-pre1-SNAPSHOT", line 41 in that dump file, sir.

**Comment by CocoTheOwner** [comment]
ah 
nevermind.
Will check back if persists.

**Comment by CocoTheOwner** [comment]
Would like to mention the link to the CI builds is only for via version, not for backwards and rewind. Just saying.

**Comment by CocoTheOwner** [comment]
Issue resolved with ci buids.
Please update the issue format to include explicit mention of the need to update backwards and rewind to ci versions as well to prevent confusion in the future.
