### ISSUE TITLE
Joining issue

### ISSUE THREAD

**Issue by Pace1337** [ViaVersion/ViaVersion#2586]
### `/viaversion dump` Output

https://dump.viaversion.com/fe8e7ed1b5e826d4000a13ff51e4703037fd836edae61f81665726904925d11e

### Console Error

https://haste.jartexnetwork.com/uxemedozegevesuq.yaml

### Bug Description

Certain players on our server have an issue joining the server.

### Steps to Reproduce

1. Try joining the server.
2. You get instantly kicked with this error coming up in console.  https://haste.jartexnetwork.com/uxemedozegevesuq.yaml

### Expected Behavior

Not get kicked

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Use ci builds.
