### ISSUE TITLE
Ignore me

### ISSUE THREAD

**Issue by Jo0001** [ViaVersion/ViaVersion#2588]
### `/viaversion dump` Output

https://dump.viaversion.com/4171fff20372048b23c8345a480ec68092474d96245b7773e687fa44a42ba76e

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

I'm just a test

### Steps to Reproduce

I'm just a test

### Expected Behavior

I'm just a test

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform](https://img.shields.io/badge/Platform-git%3ABungeeCord%20Bootstrap%3A1.17%20R0.1%20SNAPSHOT%3Aad50fc9%3A1585-3498db) <br />![ViaVersion Commits](https://img.shields.io/badge/ViaVersion-23%20commit(s)%20behind%20master-yellow)<br />![ViaBackwards Commits](https://img.shields.io/badge/ViaBackwards-14%20commit(s)%20behind%20master-yellow)
