### ISSUE TITLE
[Paper 1.17] Errors when ViaVersion is loading

### ISSUE THREAD

**Issue by x9nico** [ViaVersion/ViaVersion#2590]
### `/viaversion dump` Output

https://dump.viaversion.com/6016909c348355eed19adbff7aa0aa2274407243b7ae66cd30a7df0512b6b7a8

### Console Error

```
Put the paste.gg link or text here.
```
https://pastebin.com/0LqULzD7

### Bug Description

There is errors when I'm loading ViaVersion plugin

### Steps to Reproduce

1. Upload ViaVersion on your server
2. Start your server

### Expected Behavior

Plugin shouldn't provides errors

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-66 (MC: 1.17)](https://img.shields.io/badge/Platform-git%20Paper%2066%20%28MC%3A%201.17%29-3498db) <br />![ViaVersion: Even with dev](https://img.shields.io/badge/ViaVersion-Even%20with%20dev-brightgreen)<br />![ViaBackwards: 7 commits behind master](https://img.shields.io/badge/ViaBackwards-7%20commit(s)%20behind%20master-yellow)<br />![ViaRewind: 7 commits behind master](https://img.shields.io/badge/ViaRewind-7%20commit(s)%20behind%20master-yellow)

**Comment by kennytv** [comment]
Remove ProtocolSupport...

**Comment by x9nico** [comment]
> Remove ProtocolSupport...

I need it for FastLogin :/

**Comment by kennytv** [comment]
No you don't.

**Comment by antbig** [comment]
> > Remove ProtocolSupport...
> 
> I need it for FastLogin :/
> There is alternatives for FastLogin ?

`Plugin: ProtocolSupport is supported and can be used as an alternative to ProtocolLib`

from the spigot page of the plugin

**Comment by x9nico** [comment]
> > > Remove ProtocolSupport...
> > 
> > 
> > I need it for FastLogin :/
> > There is alternatives for FastLogin ?
> 
> `Plugin: ProtocolSupport is supported and can be used as an alternative to ProtocolLib`
> 
> from the spigot page of the plugin

I tried.
But the plugin are not working without PS.
