### ISSUE TITLE
I can`t join my minecraft server

### ISSUE THREAD

**Issue by zhichengYang-GitHub** [ViaVersion/ViaVersion#2591]
### `/viaversion dump` Output

https://dump.viaversion.com/eb42d76ef8d412a86831b6ea84f7392f1952394cdd35cdbf69920a50d24375bc

### Console Error

```
Put the paste.gg link or text here.
```
b9724d8a62364cc88f18561bd2aa1ff7

https://paste.gg/p/anonymous/92e27b37807140d3af9c2f68b834ae80

### Bug Description

I cannot join my server. With one word "disconnected"

### Steps to Reproduce

1.login with minecraft 1.16.2 & 1.17.
2.go to the "zy" world (Multiverse plugin)
3.quit the server.
4.join the server.
then I cannot join my server. With one word "disconnected"

### Expected Behavior

I could join my server before! I don`t know why...

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-1604 (MC: 1.12.2)](https://img.shields.io/badge/Platform-git%20Paper%201604%20%28MC%3A%201.12.2%29-3498db) <br />![ViaVersion: 23 commits behind master](https://img.shields.io/badge/ViaVersion-23%20commit(s)%20behind%20master-yellow)<br />![ViaRewind: 7 commits behind master](https://img.shields.io/badge/ViaRewind-7%20commit(s)%20behind%20master-yellow)<br />![ViaBackwards: 14 commits behind master](https://img.shields.io/badge/ViaBackwards-14%20commit(s)%20behind%20master-yellow)

**Comment by kennytv** [comment]
Likely due to Slimefun/something else sending bad chunk data.

**Comment by zhichengYang-GitHub** [comment]
Thanks, so what should I do？
Update the plugin？

**Comment by kennytv** [comment]
Try keeping your plugins up to date yeah, otherwise if it still happens, remove plugins until it doesn't happen anymore to see which one is causing it.

**Comment by zhichengYang-GitHub** [comment]
Okay, I will try to remove plugins...

**Comment by zhichengYang-GitHub** [comment]
I have updated all of my plugins. but it doesn`t work...
