### ISSUE TITLE
Riding problem

### ISSUE THREAD

**Issue by NikolasLvl** [ViaVersion/ViaVersion#2592]
### `/viaversion dump` Output

https://dump.viaversion.com/3fc533d6766d1443a9361a85c4813e5e2d42944562cbf62da83aa14402e1c245

### Console Error

```
Put the paste.gg link or text here.
```
No error in the console

### Bug Description

The problem is the following does not allow horse riding or boats in version 1.15 onwards in 1.8.8 if you leave

https://www.youtube.com/watch?v=Vrsw12bhGko

### Steps to Reproduce

enter minecraft
ride a horse or boat and don't let you move

### Expected Behavior

be able to ride the horses or boats

### Additional Server Info

yes me use bungeecord

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Spigot-db6de12-18fbb24 (MC: 1.8.8)](https://img.shields.io/badge/Platform-git%20Spigot%20db6de12%2018fbb24%20%28MC%3A%201.8.8%29-3498db) <br />![ViaVersion: 15 commits behind master](https://img.shields.io/badge/ViaVersion-15%20commit(s)%20behind%20master-yellow)

**Comment by kennytv** [comment]
See https://github.com/ViaVersion/ViaVersion/issues/781
