### ISSUE TITLE
Players can only join the server with 1.8 versions of minecraft

### ISSUE THREAD

**Issue by kamber5** [ViaVersion/ViaVersion#2593]
### `/viaversion dump` Output

https://dump.viaversion.com/a77dea63db87e710f0d79796f89a37c5f5f8dbaa7db3b7142f84df10124d74f5

### Console Error

https://paste.gg/p/anonymous/97c7e1bf62ef4f22a0225d33343f6c1f

### Bug Description

We have a issue with players not being able to join with 1.13.2, 1.16.4/5 and 1.17 even if its allowed with ViaVersion.
When they join the server they instantly get kicked, they can only join with the 1.8 version.

### Steps to Reproduce

1. From the hub join a 1.8 server with these version 1.13.2, 1.16.4/5 and 1.17
2. You will than get kicked to the hub

### Expected Behavior

Player should be able to join the server with 1.13.2, 1.16.4/5 and 1.17 

### Additional Server Info

We are ussing BungeeCord, factions in on Nacho Spigot.

List of plugins: https://hastebin.com/yabixagipo.md

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.8.8 (MC: 1.8.8)](https://img.shields.io/badge/Platform-1.8.8%20%28MC%3A%201.8.8%29-3498db) <br />![ViaVersion: Even with master](https://img.shields.io/badge/ViaVersion-Even%20with%20master-brightgreen)

**Comment by kennytv** [comment]
NachoSpigot is doing wanky things with the Vanilla Pipeline.
