### ISSUE TITLE
Issue with something, only 1.17 can enter the server on 1.17 version, and I have ViaVersion ViaBackward, ViaRewind, and ViaRewind Legacy

### ISSUE THREAD

**Issue by MiniKLK** [ViaVersion/ViaVersion#2595]
### `/viaversion dump` Output

https://dump.viaversion.com/247025b5009e3a0c5d442cb6f7c08ba561a52ea31180f4fa71856aab6fe52abf

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

I really want to know if looking my dump, you can see something i have wrong maybe please I really need help, I can afford money or something for a fix, only 1.17 can enter my server...

### Steps to Reproduce

Always the same mmesage on the screen of all versions (1.8,1.9-1.14,1.15,1.16)
![pal_mini](https://user-images.githubusercontent.com/86431839/124323606-e0941f80-db81-11eb-82e6-43e38ca94786.PNG)

### Expected Behavior

I really want to make all versions can enter...

### Additional Server Info

![Captura](https://user-images.githubusercontent.com/86431839/124323652-f73a7680-db81-11eb-9b4b-f1eaa8f29512.PNG)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3164-Spigot-f773da8-b069f22 (MC: 1.17)](https://img.shields.io/badge/Platform-3164%20Spigot%20f773da8%20b069f22%20%28MC%3A%201.17%29-3498db) <br />![ViaVersion: 23 commits behind master](https://img.shields.io/badge/ViaVersion-23%20commit(s)%20behind%20master-yellow)<br />![ViaRewind: 7 commits behind master](https://img.shields.io/badge/ViaRewind-7%20commit(s)%20behind%20master-yellow)<br />![ViaBackwards: 14 commits behind master](https://img.shields.io/badge/ViaBackwards-14%20commit(s)%20behind%20master-yellow)

**Comment by FormallyMyles** [comment]
Use latest from ci.viaversion.com for the Via plugins.
