### ISSUE TITLE
Double block place sound

### ISSUE THREAD

**Issue by andreasdc** [ViaVersion/ViaVersion#2597]
### `/viaversion dump` Output

-

### Bug Description

After this patch: https://github.com/Electroid/SportPaper/blob/master/patches/server/0192-Fire-block-place-sounds-inside-event-logic-chain.patch
There is double place block sound, for example 1.16.5 client.
Also your code causes place sound firing even when BlockPlaceEvent is cancelled.
Probably caused by:
https://github.com/ViaVersion/ViaVersion/blob/4074352a531cfb0de6fa81e043ee761737748a7a/common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/packets/WorldPackets.java#L384

### Steps to Reproduce

-

### Expected Behavior

-

### Additional Server Info

bungee

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
We don't support behavioral changes to base server versions.

**Comment by andreasdc** [comment]
@kennytv removing this part of code with this patch will fix that?

**Comment by kennytv** [comment]
That will probably have unintended side effects. Your best bet is to remove the server patch.

**Comment by andreasdc** [comment]
@kennytv but I would want pros coming from this patch, is it possible?

**Comment by andreasdc** [comment]
@kennytv also what side effects can it cause?

**Comment by andreasdc** [comment]
Why com.viaversion.viaversion.api.protocol.remapper.ValueCreator is not present in jar?

**Comment by kennytv** [comment]
You'll have to figure that out on your own if you want to use such a horribly outdated version.
