### ISSUE TITLE
OpenNBT in IDE

### ISSUE THREAD

**Issue by andreasdc** [ViaVersion/ViaVersion#2598]
### `/viaversion dump` Output

-

### Console Error

![image](https://user-images.githubusercontent.com/82218780/124352582-5db2a980-dc01-11eb-9dc4-c4d40f33867a.png)
How to fix this error?

### Bug Description

-

### Steps to Reproduce

-

### Expected Behavior

-

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
Invalidate caches in your IDE or reload the gradle config.
