### ISSUE TITLE
1.12.2 server crash

### ISSUE THREAD

**Issue by SladeHazard** [ViaVersion/ViaVersion#2599]
### `/viaversion dump` Output

https://dump.viaversion.com/5be893ac0668d329caf8235ec1ead0719cf6907e9a2f4dc8c9552ff9f249a19c

### Console Error

```
https://pastebin.com/RV1UzTzp
```

### Bug Description

server crashed randomly when player visited a chunk I think

### Steps to Reproduce

Randomly happens many times

### Expected Behavior

Server doesn't crash

### Additional Server Info

1.12.2 server paper
with velocity as proxy

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-33d42c8e (MC: 1.12.2)](https://img.shields.io/badge/Platform-git%20Paper%2033d42c8e%20%28MC%3A%201.12.2%29-3498db) <br />![ViaVersion: 5 commits behind dev](https://img.shields.io/badge/ViaVersion-5%20commit(s)%20behind%20dev-yellow)<br />![ViaRewind: Even with master](https://img.shields.io/badge/ViaRewind-Even%20with%20master-brightgreen)<br />![ViaBackwards: 6 commits behind dev](https://img.shields.io/badge/ViaBackwards-6%20commit(s)%20behind%20dev-yellow)

**Comment by SladeHazard** [comment]
I'm not using the latest via as they prevent 1.8 clients from joining

**Comment by kennytv** [comment]
You have corrupted world data or a plugin is sending bad chunk packets (probably FAWE).

**Comment by tomcraft** [comment]
what are you talking about ?? via does not prevent any 1.8 player to join
