### ISSUE TITLE
Block place sound is played even after place event is cancelled

### ISSUE THREAD

**Issue by andreasdc** [ViaVersion/ViaVersion#2601]
### `/viaversion dump` Output

ViaVersion 4.0.1-1.17.1-rc1-SNAPSHOT

### Bug Description

server plays sound to client after placing so there would be double sound if im not wrong
but there is no double sound when normal placing,
server is not sending sound when cancelling, but there is still the sound (only for newer versions, on 1.8 server 1.8 players dont hear sound)

### Steps to Reproduce

-

### Expected Behavior

-

### Additional Server Info

bungeecord

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Camotoy** [comment]
The block place sound is clientside as of recent modern Minecraft versions (for each player - other players' block place sounds are controlled by the server, but the client's own block placing it controls).

**Comment by andreasdc** [comment]
@Camotoy why there isn't double sound when placing normally?

**Comment by andreasdc** [comment]
@kennytv why there isn't double sound when placing normally?

**Comment by kennytv** [comment]
As we already told you, you'll have to figure that out on your own if you decide to use a custom fork.

The next issue you open regarding such an issue, or an issue without a dump, will be closed without a comment.
