### ISSUE TITLE
 ERROR IN BaseProtocol1_16 IN REMAP OF 0x02->0x02

### ISSUE THREAD

**Issue by EuanM199** [ViaVersion/ViaVersion#2602]
### `/viaversion dump` Output

https://dump.viaversion.com/c5a6d494c98c222870f3f37219ea806d91979f64f28cbd8d2501caf37b436266

### Console Error

```
https://bin.bloom.host/cecivocebi.sql
```

### Bug Description

Users on 1.16 appear to crash the server while joining a 1.17 server

### Steps to Reproduce

Unknown at this point.

### Expected Behavior

No Crashes

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Purpur-1251 (MC: 1.17)](https://img.shields.io/badge/Platform-git--Purpur--1251%20%28MC%3A%201.17%29-3498db?style=flat-square) <br />![ViaVersion (4.0.0): 23 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.0)-23%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.0): 14 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.0)-14%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by EuanM199** [comment]
i thought i was on master, nevermind then, might be fixed in latest

**Comment by kennytv** [comment]
Otherwise you have a plugin sending bad packets, so try without others/make sure you're only running Via on *either* Purpur *or* a proxy.

**Comment by EuanM199** [comment]
happening still on latest, looking like Eglow is the cause
[https://bin.bloom.host/sozawigubu.md](https://bin.bloom.host/sozawigubu.md)

**Comment by Jo0001** [comment]
Works fine with the latest Via + latest eGlow on latest paper 1.17 server with 1.16 client.
If the error still occurs using the latest Via+eGlow+paper (and no other plugins) feel free to open a new issue
