### ISSUE TITLE
serverside-blockconnections spams a lot of errors

### ISSUE THREAD

**Issue by voodootje0** [ViaVersion/ViaVersion#2603]
### `/viaversion dump` Output

https://dump.viaversion.com/d2d9aa81249ead47623662426ba7da1d1b8750a3b5f2603e0d2d12bd54992ce7

### Console Error

https://haste.jartexnetwork.com/fucehavoyasegisu.yaml

### Bug Description

NullPointerException on server side block connectionsserver-side

### Steps to Reproduce

Using a 1.8.9 server with server-side block connections returns NullPointerException

### Expected Behavior

No NullPointerException

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-PaperSpigot-936a21b (MC: 1.8.8)](https://img.shields.io/badge/Platform-git--PaperSpigot--936a21b%20%28MC%3A%201.8.8%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by kennytv** [comment]
Don't reload plugins. Toggling this in the config at runtime may also yield such results.
