### ISSUE TITLE
Don't send extra move packet when right clicking on 1.17

### ISSUE THREAD

**Issue by andreasdc** [ViaVersion/ViaVersion#2604]
### Problem Description

When you run and hold right click while holding an item on 1.17 you send extra move packet, which lead to false positives on anticheat.

### Solution Description

Don't send extra move packet when rightclicking an item.

### Additional Info

1.8 server

**Comment by kennytv** [comment]
See https://github.com/ViaVersion/ViaVersion/issues/2523
