### ISSUE TITLE
ERROR IN Protocol1_13To1_12_2 IN REMAP OF ENTITY_METADATA (0x3C)

### ISSUE THREAD

**Issue by hihihih565** [ViaVersion/ViaVersion#2605]
### `/viaversion dump` Output

https://dump.viaversion.com/3fc9f638e0849f86b7d32e9d325cd76721dfa4a402a4130af5135d043718e900

### Console Error

https://paste.gg/p/anonymous/5f4f210d635c4152869751949d36acf8

### Bug Description

Entity metadata packet crashing players

### Steps to Reproduce

Players are crashing when sent the packet

### Expected Behavior

Players shouldn't crash when its sent, this has only started happening recently

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-7f2538a (MC: 1.12.2)](https://img.shields.io/badge/Platform-git--Paper--7f2538a%20%28MC%3A%201.12.2%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1-SNAPSHOT): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1--SNAPSHOT)-11%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1-SNAPSHOT): 8 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1--SNAPSHOT)-8%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.1-SNAPSHOT): 2 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1--SNAPSHOT)-2%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by kennytv** [comment]
Update, otherwise you have a plugin sending bad metadata packets.
