### ISSUE TITLE
Items visually showing up different when dropped

### ISSUE THREAD

**Issue by CullanP** [ViaVersion/ViaVersion#2610]
### `/viaversion dump` Output

https://dump.viaversion.com/2b9d1e1eb933cb6ccf4cf2fb63afd72425dcda1b3e6e190aa2335bd91a70da59

### Console Error

```
None
```

### Bug Description

This issue only seems to occur on paper 1.16.0-1.16.1, anything past 1.16.2 does not have this problem. This issue also does not occur on viaversion 4.0 using base 1.17 client. Base 1.17 client does have issues on viaversion 4.0.1 using server version 1.16.1. This issue also does not occur on client versions below 1.17

Working paper version: https://papermc.io/api/v2/projects/paper/versions/1.16.2/builds/141/downloads/paper-1.16.2-141.jar
Problematic 1.16.1 version: https://papermc.io/api/v2/projects/paper/versions/1.16.1/builds/138/downloads/paper-1.16.1-138.jar

Video of problem: https://gyazo.com/0e5ff15221fcd6c8f652243989804056

### Steps to Reproduce

1. Use 1.16.1 paper server version
2. Use viaversion 4.0.1
3. Log in on 1.17, give yourself a diamond, drop the item and it will visually show up differently than what it is.

### Expected Behavior

The diamond to visually show a diamond

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-d369e15 (MC: 1.16.1)](https://img.shields.io/badge/Platform-git--Paper--d369e15%20%28MC%3A%201.16.1%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-Even%20with%20master-brightgreen?style=flat-square)
