### ISSUE TITLE
Mount Bug (1.16.5 Client | 1.8.8 Server)

### ISSUE THREAD

**Issue by kybuuu** [ViaVersion/ViaVersion#2611]
### `/viaversion dump` Output

https://dump.viaversion.com/0c724454639e66356efa4d3b31fc843e026e707ef481c67bb2278fff09d290ad

### Bug Description

If you want to mount on any entity  with an 1.16.X Client on an 1.8.X Server, the player is getting mounted to the entity, but he doesn't really "sits" on it. 

For other players it looks normal, like he sits on that entity. But for the player, it looks like he's standing right next to the entity.

For other players (and how it should look like):
![2021-07-07_17 53 09](https://user-images.githubusercontent.com/48190409/124791291-38e56b80-df4c-11eb-970e-5446faccfff0.png)

For the player:
![2021-07-07_17 53 14](https://user-images.githubusercontent.com/48190409/124791301-3b47c580-df4c-11eb-9809-70d206869ae3.png)

It's only buggy on 1.16.X, it works with every other version (even 1.17).
The bug appears since ViaVersion 4.0.0 - in 3.2.1 it works

### Steps to Reproduce

1. Login with an 1.16.X Client on an 1.8.X Server which is using ViaVersion 4.0.0 or higher
2. Mount to any entity

Here's a simple plugin, which is also used in the screenshots above the demonstrate the bug.
[ViaVersionMountBug.zip](https://github.com/ViaVersion/ViaVersion/files/6778630/ViaVersionMountBug.zip)

### Expected Behavior

![2021-07-07_17 55 45](https://user-images.githubusercontent.com/48190409/124791681-911c6d80-df4c-11eb-833a-2209f4e8bd9e.png)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Spigot-db6de12-18fbb24 (MC: 1.8.8)](https://img.shields.io/badge/Platform-git--Spigot--db6de12--18fbb24%20%28MC%3A%201.8.8%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by kennytv** [comment]
That's a client bug we can't fix.
