### ISSUE TITLE
config comments disappear

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaVersion#2614]
### `/viaversion dump` Output

.

### Bug Description

Is it related with yaml lists?
https://github.com/ViaVersion/VIAaaS/issues/168

### Steps to Reproduce

start viaaas

### Expected Behavior

should have comments

### Additional Server Info

viaaas

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by creeper123123321** [comment]
CommentStore https://github.com/ViaVersion/ViaVersion/blob/14cd568e46a6110c7016524b88d9a7873c40f02a/common/src/main/java/com/viaversion/viaversion/util/CommentStore.java#L35

**Comment by kennytv** [comment]
https://github.com/ViaVersion/ViaVersion/issues/2615
