### ISSUE TITLE
Warn in console

### ISSUE THREAD

**Issue by Blox61** [ViaVersion/ViaVersion#2616]
### `/viaversion dump` Output

 We've made a dump with useful information, report your issue and provide this url: https://dump.viaversion.com/5cadda7eee044db0ebda9effe43334a4c35e8aebddffce72b6d214d4735aeb9a

### Console Error

https://pastebin.com/azQ49X9V

### Bug Description

https://pastebin.com/azQ49X9V

### Steps to Reproduce

https://pastebin.com/azQ49X9V

### Expected Behavior

https://pastebin.com/azQ49X9V

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-777 (MC: 1.16.5)](https://img.shields.io/badge/Platform-git--Paper--777%20%28MC%3A%201.16.5%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind-Outdated!-red?style=flat-square)<br />![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards-Outdated!-red?style=flat-square)
