### ISSUE TITLE
io.netty.channel.AbstractChannel

### ISSUE THREAD

**Issue by xEllesi** [ViaVersion/ViaVersion#2618]
### `/viaversion dump` Output

https://dump.viaversion.com/af5a8fe1b581ae425412db753dc820fba2c466c4194c98b35cfc826a698d2cd5

### Console Error

```
Put the paste.gg link or text here.
```
No error

### Bug Description

SOme players cant enter the server they get this error io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: (IP:IP:PORT)

### Steps to Reproduce

try to enter with 1.17 or 1.17.1

### Expected Behavior

players enter without errors

### Additional Server Info

Bungeecord, but i use via version on each server excluding the bungee

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
Unlikely to be a Via issue, probably setup or client related. Join our Discord if you need more help.
