### ISSUE TITLE
Cant join server

### ISSUE THREAD

**Issue by Animationking11** [ViaVersion/ViaVersion#2619]
### `/viaversion dump` Output

https://dump.viaversion.com/df479b077d9d70266aec83b92c618110cbc12269a482b8dc3dfd591052c4a1cd

### Console Error

None

### Bug Description

when I join I get this error 
![image](https://user-images.githubusercontent.com/60802108/125148943-bb0b9680-e0ea-11eb-992f-047377cb9e7e.png)

### Steps to Reproduce

I was on lunar 1.8.9

### Expected Behavior

to join the server

### Additional Server Info

I used bungee cord and had ViaVersion, ViaBackwards and ViaRewind on the proxy and server I was connecting to

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-337 (MC: 1.16.4)](https://img.shields.io/badge/Platform-git--Paper--337%20%28MC%3A%201.16.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)<br />![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind-Outdated!-red?style=flat-square)<br />![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards-Outdated!-red?style=flat-square)

**Comment by Camotoy** [comment]
Looks like you're still using builds from 1.17; please update your builds from https://ci.viaversion.com/. If the issue persists, please create a new issue with *up-to-date* builds. Thank you!
