### ISSUE TITLE
Unable to read type Byte, found Unsigned Byte

### ISSUE THREAD

**Issue by jiggey1** [ViaVersion/ViaVersion#2621]
### `/viaversion dump` Output

https://dump.viaversion.com/f1bef95442ce9226d688540d275aa5cf44f58528a40243295b5418bd3c20a531

### Console Error

https://paste.gg/p/anonymous/a598ed75d97241ddb7130555b01eb948

### Bug Description

Joining my server on any version below 1.14 produces this error. Unsure of why, it happens everytime someone attempts to join. Server is running 1.17 and ViaVersion is v4.0.1 + ViaBackwards 4.0.1 (* ISSUE POSTED HERE AND ON THE VIABACKWARDS ISSUES*)

### Steps to Reproduce

1. Login with any client below 1.14 to a 1.17 spigot server.

### Expected Behavior

The player should be able to join and play as intended.

### Additional Server Info

Custom coded plugins by myself (no errors surrounding this plugin.) 

ViaVersion 4.0.1
ViaBackwards 4.0.1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3164-Spigot-f773da8-b069f22 (MC: 1.17)](https://img.shields.io/badge/Platform-3164--Spigot--f773da8--b069f22%20%28MC%3A%201.17%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind-Outdated!-red?style=flat-square)<br />![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards-Outdated!-red?style=flat-square)
