### ISSUE TITLE
I cant access from 1.8 in 1.17 server

### ISSUE THREAD

**Issue by Jungdrew** [ViaVersion/ViaVersion#2622]
### `/viaversion dump` Output

https://dump.viaversion.com/2029c17c1bf2e837b247b487fb8447a1566ff92a985badb2e922b7b2bbf3b736

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Client outdated when I try to access to a 1.17 server with 1.8.9.

### Steps to Reproduce

Login with to 1.17 server with 1.8.9

### Expected Behavior

I expect I can access from any version above 1.8.9

### Additional Server Info

no

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3170-Spigot-a483d2c-ec116f6 (MC: 1.17)](https://img.shields.io/badge/Platform-3170--Spigot--a483d2c--ec116f6%20%28MC%3A%201.17%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by kennytv** [comment]
You need ViaBackwards and Rewind
