### ISSUE TITLE
Bungee Console Error

### ISSUE THREAD

**Issue by MizukageMaTes** [ViaVersion/ViaVersion#2623]
### `/viaversion dump` Output

https://dump.viaversion.com/9bee02a7eaedb50537a1ed5baae4d850d4c7fbd231b358e32fd48fffee35c7bc

### Console Error

https://paste.gg/p/anonymous/a14b6856bcf2491382999df1bc69cf15

### Bug Description

When some players try to change servers this error occurs and the player is kicked

### Steps to Reproduce

The user was logging into 1.16.5
The server is on 1.17.1
When trying to move from Lobby to Survival this error occurs.

### Expected Behavior

That the error does not occur and that the player is not kicked.

### Additional Server Info

using via version and viabackwards only in Waterfall (Bungee fork)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.17--R0.1--SNAPSHOT%3Ae6526b1%3A445-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by kennytv** [comment]
We need the full error, and please use https://paste.gg to paste it.

**Comment by MizukageMaTes** [comment]
> We need the full error, and please use https://paste.gg to paste it.

here https://paste.gg/p/anonymous/cf56af14e96f4e328e873392b8c81bc4

**Comment by kennytv** [comment]
Either that's not the first occurrence of the error or you have something cutting it. Eitherway, please try reproducing this without other plugins on your Bungee/Spigot to see if it might be something else causing this.

**Comment by MizukageMaTes** [comment]
so far it has only happened with one player... the only difference between him and others is that he was using tlauncher.
Other players are entering normally without any error.

**Comment by MizukageMaTes** [comment]
Now with another player, but this happens when he opens one of his chests and gets kicked and this error occurs...
https://paste.gg/p/anonymous/89180ed8c22f4dfdada91a7bedd93a4f

**Comment by MizukageMaTes** [comment]
Hey @kennytv  I believe I found out what causes the error...
The server is at version 1.17.1
The error occurs when the player is at 1.16.5 and takes an Oak Sapling.
console happens it https://paste.gg/p/anonymous/89180ed8c22f4dfdada91a7bedd93a4f
And the player is kicked!

The problem is serious because it is enough for another player in version 1.17 to hold an Oak Sapling and the next player who is in 1.16.5 is kicked, the same thing if he is inside a chest and extremely serious if by chance the player ends up with the Oak Sapling in inventory...

**Comment by Jo0001** [comment]
I can't reproduce this (no erros nor a kick) using the latest paper 1.17.1, latest Waterfall and latest Via.
