### ISSUE TITLE
player under mc vesion 1.8.9 can't join server

### ISSUE THREAD

**Issue by ghuuz69** [ViaVersion/ViaVersion#2625]
### `/viaversion dump` Output

https://dump.viaversion.com/85f92216edbcd8d76d4171abfede82fb28311667e10ed6de44446361f5ea5b69

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/722560ed91ca47b3bdc35ae6932f290c

### Bug Description

when player join on mincraft version 1.8.9, they got message and can' join the server proxy
![mamank12](https://user-images.githubusercontent.com/78796349/125885332-d4d4d2f6-1983-4710-b243-aea235872bcc.png)

### Steps to Reproduce

player join with 1.8.9
joing to the server
got message

### Expected Behavior

can't joining to the server

### Additional Server Info

I use bungeecord waterfall 1.17.1
plugin on my bungee:
antibot
bungeeshout
CMIBungee
LP Bungee
nuvotifier
SkinRestorer
SlashServer
ViaBackwards 4.0.1
ViaRewind 2.0.0
ViaVersion 4.0.1 or 4.0.2-SNAPSHOT

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.17--R0.1--SNAPSHOT%3Ae6526b1%3A445-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind-Outdated!-red?style=flat-square)

**Comment by Camotoy** [comment]
Please update all of your Via plugins from the download link in the issue you checked off as trying. If the issue persists, please make a new issue. Thank you!
