### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by JustLonelyy** [ViaVersion/ViaVersion#2626]
### `/viaversion dump` Output

https://dump.viaversion.com/67349d4b0573e0bbaaaf230728e4da4184b46d4aa5c030048918131e718363fe

### Console Error

https://paste.md-5.net/fiqafuqeyu.md

### Bug Description

My game crashed when i was joining the server

### Steps to Reproduce

server version 1.13.2

### Expected Behavior

...

### Additional Server Info

....

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-653 (MC: 1.13.2)](https://img.shields.io/badge/Platform-git--Paper--653%20%28MC%3A%201.13.2%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.1): 2 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by kennytv** [comment]
Don't reload.

**Comment by JustLonelyy** [comment]
> Don't reload.

i wasnt reloading

**Comment by kennytv** [comment]
Then you have broken/badly uploaded jars
