### ISSUE TITLE
Visual bug after sending bossbar

### ISSUE THREAD

**Issue by andreasdc** [ViaVersion/ViaVersion#2628]
### `/viaversion dump` Output

Latset builds from jenking

### Bug Description

![image](https://user-images.githubusercontent.com/82218780/126046728-b4504ce7-0a59-47d4-a37c-65aaafa338cd.png)
When bossbar is being sent food and health is getting visual bugged.
Probably only on 1.17 client. 
Tested on 1.8 server.

### Steps to Reproduce

Send bossbar

### Expected Behavior

Not bugged hp and food

### Additional Server Info

BungeeCord
ViaRewind-2.0.2-SNAPSHOT
viarewind-legacy-support-1.4.0
ViaVersion-4.0.2-SNAPSHOT

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
Not a Via issue...

**Comment by andreasdc** [comment]
Why this happens only on 1.17?

**Comment by kennytv** [comment]
You already asked that in the Discord two weeks ago and received a response.
