### ISSUE TITLE
Plugin Tuske not starting when viaversion is installed

### ISSUE THREAD

**Issue by bloggy** [ViaVersion/ViaVersion#2630]
### `/viaversion dump` Output

https://dump.viaversion.com/8366ff9d222114ee47dc9aa2b9243f4598a989f3b96901a54d431bb79ef137b1

### Console Error

https://paste.gg/p/anonymous/519fc9e77a184bd2ab93a3f45e23ff6b/files/2e65c4d6a5084751a105493bb819ccd6/raw

### Bug Description

Another plugin can not be enabled on server start when viaversion is installed. 

### Steps to Reproduce

1.) Install both, tuske (https://github.com/Tuke-Nuke/TuSKe) and viaversion
2.) Start server

### Expected Behavior

Both plugins load without errors.

### Additional Server Info

This server is running Tuinity version git-Tuinity-"f0e91a4" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
Well that's obviously not a Via issue, but of your other plugin. See https://github.com/szumielxd/TuSKe/releases/tag/v1.9.1
