### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by kohlerpop1** [ViaVersion/ViaVersion#2632]
### `/viaversion dump` Output

https://dump.viaversion.com/065124ce29f87d8b541f0c719c468d02e262a81b3c57b1aaf77dc300a43a6714

### Console Error

```
https://paste.gg/p/anonymous/4cc971a9ca0a41ff96cc2ca1b72f1844
```

### Bug Description

Starting paper 1.17.1 java 16 throws the error.

### Steps to Reproduce

Start paper 1.17.1 java 16 and it throws error.

### Expected Behavior

Not throw error on startup

### Additional Server Info

I tried with this https://ci.viaversion.com/job/ViaVersion/ version 4.0.2-SNAPSHOT and it still did not work

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-120 (MC: 1.17.1)](https://img.shields.io/badge/Platform-git--Paper--120%20%28MC%3A%201.17.1%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square)
