### ISSUE TITLE
Server Crash due to player join.

### ISSUE THREAD

**Issue by EuanM199** [ViaVersion/ViaVersion#2634]
### `/viaversion dump` Output

https://dump.viaversion.com/64b635bbbfc29c02812eb46da6285f54d28e42896d5a6b2665be67cffe2e0d3d

### Console Error

```
https://bin.bloom.host/kequvapadu.sql
```

### Bug Description

User joined, then crashed the server.

### Steps to Reproduce

Unknown

### Expected Behavior

Crash to not happen

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-AirplanePurpur-22 (MC: 1.17.1)](https://img.shields.io/badge/Platform-git--AirplanePurpur--22%20%28MC%3A%201.17.1%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-6%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-5%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by PierreSchwang** [comment]
Update your plugins: 
ViaVersion - https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/build/libs/ViaVersion-4.0.2-SNAPSHOT.jar
ViaBackwards - https://ci.viaversion.com/job/ViaBackwards/lastSuccessfulBuild/artifact/build/libs/ViaBackwards-4.0.2-SNAPSHOT.jar

**Comment by kennytv** [comment]
Also to note, that's not a crash.

**Comment by EuanM199** [comment]
> 
> 
> Also to note, that's not a crash.

it stopped the server lol i guess you can call that not a crash
