### ISSUE TITLE
Item Duplicate/Drop Visual Glitch

### ISSUE THREAD

**Issue by Stoiky20** [ViaVersion/ViaVersion#2635]
### `/viaversion dump` Output

https://dump.viaversion.com/aff75569310bca815094c8f91841458e94c7f87e3436208520c1495730145a15

### Console Error

No console error

### Bug Description

Dropping items on versions below 1.17 causes items to glitch
https://www.youtube.com/watch?v=HQZ_pPUOyes&feature=youtu.be

### Steps to Reproduce

https://www.youtube.com/watch?v=HQZ_pPUOyes&feature=youtu.be

### Expected Behavior

Not glitching

### Additional Server Info

This server is running Paper version git-Paper-127 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9a0263e)
You are running the latest version
Previous version: git-Paper-119 (MC: 1.17.1)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-127 (MC: 1.17.1)](https://img.shields.io/badge/Platform-git--Paper--127%20%28MC%3A%201.17.1%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-2%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.2-SNAPSHOT): 5 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-5%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by kennytv** [comment]
That's just Vanilla item merging?

**Comment by Stoiky20** [comment]
It is not

**Comment by kennytv** [comment]
The description was a bit unclear; as mentioned on the Discord, this is a side effect of an already tracked issue. I'll probably attempt a workaround for this specifically soonish.
