### ISSUE TITLE
Title messages not appearing for 1.17.1 clients on 1.16.5 servers

### ISSUE THREAD

**Issue by AoElite** [ViaVersion/ViaVersion#2637]
### `/viaversion dump` Output

https://dump.viaversion.com/da2c9aa59b21f3b83d7b4aa2dcf8bce263abe8783f0f1389d673b67913c152b0

### Bug Description

Title messages do not appear for 1.17.1 clients on 1.16.5 servers.

### Steps to Reproduce

1. Start a 1.16.5 airplane server
2. Join on 1.17.1
3. Run some code: `player.sendTitle("", ChatColor.GREEN + "Test!", 5, 20, 10);`

### Expected Behavior

Title messages are supposed to appear for 1.17 players.

### Additional Server Info

I'm using Velocity but ViaVersion is not installed on there. I'm using a fork of Tuinity called Airplane, and Tuinity is just a fork of paper.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Airplane-9 (MC: 1.16.5)](https://img.shields.io/badge/Platform-git--Airplane--9%20%28MC%3A%201.16.5%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-5%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by kennytv** [comment]
Making an empty title means not having title at all and Via not having any networking info to go off of (unless we started tracking title states everywhere). So the easiest workaround is to just do `player.sendTitle(" ", ...)`.

**Comment by AoElite** [comment]
Alright thanks.
