### ISSUE TITLE
Boss bars don't work on paper 1.12.2 

### ISSUE THREAD

**Issue by rubbergrief** [ViaVersion/ViaVersion#2638]
### `/viaversion dump` Output

https://dump.viaversion.com/3ed943a1475a39061d4d9d6923fc908dacc03d2ba7abdd0f32f59181d1406a01

### Bug Description

Bar don't work on 1.12.2. Displaying the list of bar players is just empty and packet not sent. I checked on the old version (2.0.0), everything was fine.

### Steps to Reproduce

Opened ide and wrote simple listener (AsyncPlayerJoinEvent)
> This is my code:
`BossBar bar = Via.getAPI().createBossBar("test", 0.75F, BossColor.BLUE, BossStyle.SEGMENTED_20);
bar.addPlayer(e.getPlayer().getUniqueId());
bar.show();`

### Expected Behavior

Bar is not displayed

### Additional Server Info

I am have BungeeCord fork (BotFilter https://github.com/Leymooo/BungeeCord). Almost all plugins on the server have their own.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [x] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-1618 (MC: 1.12.2)](https://img.shields.io/badge/Platform-git--Paper--1618%20%28MC%3A%201.12.2%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by Camotoy** [comment]
Please update your ViaVersion from the download link in the issue, and reopen a new issue with an updated dump if the issue still persists. Thank you!

**Comment by kennytv** [comment]
On anything but 1.8 you should use just server API. The Via method is for 1.8 servers wanting to show the bossbar to 1.9+ players.
See https://papermc.io/javadocs/paper/1.12/org/bukkit/Server.html#createBossBar-java.lang.String-org.bukkit.boss.BarColor-org.bukkit.boss.BarStyle-org.bukkit.boss.BarFlag...-
