### ISSUE TITLE
1.17.1 write book disconnect

### ISSUE THREAD

**Issue by disqetow** [ViaVersion/ViaVersion#2640]
### `/viaversion dump` Output

https://dump.viaversion.com/912d4083d9765e728b6af1a7c683ad0a0267f9358b3b907c51e2ae74034d63a0

### Console Error

[16:52:54 INFO]: onermb lost connection: Invalid book data!
[16:52:54 INFO]: onermb left the game
[16:52:54 ERROR]: onermb/InvalidBookSign: Invalid book tag!

### Bug Description

write book and press done, player will disconnect 

### Steps to Reproduce

1. open 1.12.2 server with viaversion
2. use 1.17.1 join server
3. write book and press done

### Expected Behavior

write book success

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-1618 (MC: 1.12.2)](https://img.shields.io/badge/Platform-git--Paper--1618%20%28MC%3A%201.12.2%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square)
