### ISSUE TITLE
geting problem when joining server from 1.8

### ISSUE THREAD

**Issue by JAY200625** [ViaVersion/ViaVersion#2642]
### `/viaversion dump` Output

https://dump.viaversion.com/759e47b650b738fa39cfccb64631f5c091c1146107c267b3bb3cfe837b2944ff

### Console Error

https://paste.gg/p/anonymous/c1d1293c51e14faab1723e49fedfee91

### Bug Description

1.8 clint

### Steps to Reproduce

1.8 clint

### Expected Behavior

https://paste.gg/p/anonymous/c1d1293c51e14faab1723e49fedfee91

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-"77cce8236" (MC: 1.12.2)](https://img.shields.io/badge/Platform-git--Paper--%2277cce8236%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-8%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-5%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.1): 9 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by Jo0001** [comment]
Thats probably due some other plugin and not Via. If this issue still happens with just Via installed feel free to open a new issue (https://github.com/ViaVersion/ViaRewind)

**Comment by JAY200625** [comment]
i have install via all plugin on bungeecord and also in lobby also

**Comment by JAY200625** [comment]
![Screenshot (127)](https://user-images.githubusercontent.com/72148794/127666999-ad6ffa6c-e6ed-4b21-b77d-088b60139476.png)

**Comment by kennytv** [comment]
![a](https://i.imgur.com/M4B6GRv.png)
