### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by RetamrCZ** [ViaVersion/ViaVersion#2643]
### `/viaversion dump` Output

https://dump.viaversion.com/fd1f69b7fe169eaad95730612695e9dfa57eb67d8f872d926fda3b73d2586c5c

### Console Error

https://paste.gg/p/anonymous/1e062621218740c0be41664af3cc5cac

### Bug Description

When i join

### Steps to Reproduce

1. Login with 1.8.9 client to 1.12.2 server
2. Server kicks me.

### Expected Behavior

When i join.

### Additional Server Info

I use only Paper 1.12.2

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-1618 (MC: 1.12.2)](https://img.shields.io/badge/Platform-git--Paper--1618%20%28MC%3A%201.12.2%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-5%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind-Outdated!-red?style=flat-square)

**Comment by RetamrCZ** [comment]
Thanks.
