### ISSUE TITLE
Player cannot join the server. Was working fine before, no longer is able to. 

### ISSUE THREAD

**Issue by TheCommander64** [ViaVersion/ViaVersion#2647]
### `/viaversion dump` Output

https://dump.viaversion.com/b0cf40779340a2dcea424f321acb0c64a33e4d25efc428152d7e8d57f00d93e7

### Console Error

https://paste.gg/p/anonymous/fdb59214cd5e487eb9a023d2178dcbbc

### Bug Description

Player cannot join. Its only 1 specific player, everyone else is able to join just fine

### Steps to Reproduce

I have no clue

### Expected Behavior

Shouldnt give an error, and the player should be able to join

### Additional Server Info

paper 1.16.5
Citizens, Multiverse-Core, PlaceholderAPI, ProtocolLib, SkBee, SkQuery, skRayFall, Skript, SkUniversal*, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-778 (MC: 1.16.5)](https://img.shields.io/badge/Platform-git--Paper--778%20%28MC%3A%201.16.5%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-5%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.1): 9 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by kennytv** [comment]
We need the full error.
