### ISSUE TITLE
Player cant join

### ISSUE THREAD

**Issue by Suqatri** [ViaVersion/ViaVersion#2654]
### `/viaversion dump` Output

https://dump.viaversion.com/5d91ab0f4a8d8c923e9062992fc9cdfc451aad5d3aaf0cdbcdbe1312f42875ce

### Console Error

https://hastebin.de/hitipoweni.properties

### Bug Description

When a player joins the server with a client version lower than 1.17

### Steps to Reproduce

1. Login with a Client (1.8-16.5) 

### Expected Behavior

That the player can join

### Additional Server Info

I am using the latest BungeeCord Build and Minestom 1.17 as the server version. 
Plugins: Viaversion, ViaBackwards, ViaRewind

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git:BungeeCord-Bootstrap:1.17-R0.1-SNAPSHOT:bda1605:1598](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.17--R0.1--SNAPSHOT%3Abda1605%3A1598-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-5%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.1): 9 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by kennytv** [comment]
We don't support Minestom
