### ISSUE TITLE
All players from the same version get kicked when a player chats

### ISSUE THREAD

**Issue by eugeniodevv** [ViaVersion/ViaVersion#2655]
### `/viaversion dump` Output

https://dump.viaversion.com/8c4cbb82d8952d7fa6ef414ad827fcc85c299bb18d8c263eb59348105f671867

### Console Error

https://paste.gg/p/anonymous/cc284b9d7630463388312fbf033105db

### Bug Description

Using ViaVersion in my Velocity proxy. I'm using all the ViaVersions (ViaBackwards, ViaRewind, ViaVersion) but the VR Legacy Support as I run them in my proxy and that's only for bukkit. 

I'm trying to connect from 1.8 to my 1.17 server and it works great, but when I try to chat, it disconnects all the players in that server that are on a version that isn't 1.13+. It doesn't seem to kick the players that are in 1.13+ (I think, only tested on 1.16.5 and there it doesn't kick me and I can chat correctly), but in below versions it does kick me and it generates an error.

### Steps to Reproduce

1. Get a Velocity server with all the Via plugins
2. Get a 1.17 server
3. Join with 1.8 and try to chat

### Expected Behavior

Kicks all players that have a lower version than 1.16.5 (pretty sure that it only kicks versions that are below 1.13 but just tested in that version just in case), but 1.16.5+ clients can see the chat correctly and don't get kicked.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity-3.0.1-SNAPSHOT (git-d3ff6f8e-b54)](https://img.shields.io/badge/Platform-velocity--3.0.1--SNAPSHOT (git--d3ff6f8e--b54)-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)
