### ISSUE TITLE
reload error

### ISSUE THREAD

**Issue by 6test55566** [ViaVersion/ViaVersion#2656]
### `/viaversion dump` Output

https://dump.viaversion.com/c8d422614f87c47904742b0390b7bd2321aeedbc610079c539e1a7fda008282e

### Console Error

https://paste.gg/p/anonymous/8ff8a84d5efa49cbaffc63af8bcbdffd

### Bug Description

login 1.16.4
reload the server

### Steps to Reproduce

login 1.16.4
reload the server
than kick with this error
![image](https://user-images.githubusercontent.com/77003234/128930780-9b354a6d-f6ff-481b-a6d9-758d275f77c2.png)

### Expected Behavior

login 1.16.4
reload the server
than kick with this error
![image](https://user-images.githubusercontent.com/77003234/128930780-9b354a6d-f6ff-481b-a6d9-758d275f77c2.png)

### Additional Server Info

login 1.16.4
reload the server
than kick with this error
![image](https://user-images.githubusercontent.com/77003234/128930780-9b354a6d-f6ff-481b-a6d9-758d275f77c2.png)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3181-Spigot-38e6c03-ed2b91c (MC: 1.17.1)](https://img.shields.io/badge/Platform-3181--Spigot--38e6c03--ed2b91c%20%28MC%3A%201.17.1%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 7 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.1): 9 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by Camotoy** [comment]
Don't reload the server - this is unsupported behavior for many plugins. Additionally, all three of your Via plugins are out of date from the link it asked you to download from first. 

Thanks anyway.

**Comment by 6test55566** [comment]
ok,
i will updata the via plugin
anyway ty!.
