### ISSUE TITLE
i want to use loom to dye banner

### ISSUE THREAD

**Issue by JMO3279** [ViaVersion/ViaVersion#2657]
### Problem Description

before 1.14 i can't use loom so i can't dye any banner and my computer is low-end
so i can only play til 1.12.2

### Solution Description

a gui that can use dye,banner and banner pattern

### Alternatives

i just want to dye banner

### Additional Info

before 1.14

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid%2Fmissing%20dump-red)

**Comment by Camotoy** [comment]
This belongs in the ViaBackwards repository.

This would be an intensive re-implementation, so do not expect such a thing to be done for a while, if ever.

**Comment by kennytv** [comment]
We don't re-implement new features, sorry. If you want to use them, use newer versions.
