### ISSUE TITLE
Signing books with empty pages kicks on 1.12 server

### ISSUE THREAD

**Issue by disqetow** [ViaVersion/ViaVersion#2660]
### `/viaversion dump` Output

https://dump.viaversion.com/7d65818903f6f942cd9c1589a004f95ce3d746c3630336fe5c1fbf0502ec498d

### Console Error

InvalidBookSign: Invalid book tag!

### Bug Description

Dont write anything in book, you will got kick when you done book

### Steps to Reproduce

1. open 1.12.2 server and install viaversion lastest from jekins
1. using 1.16.x、1.15.x、 1.14.x client join server
2. sign blank book, and will kick by server.

### Expected Behavior

write book success

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-1618 (MC: 1.12.2)](https://img.shields.io/badge/Platform-git--Paper--1618%20%28MC%3A%201.12.2%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by kennytv** [comment]
... did you actually test with that new version?

**Comment by disqetow** [comment]
> Did you actually test with that new version, right now?

yes I am sure.
