### ISSUE TITLE
Klicked with EncoderExeption when hitting a pig (???)

### ISSUE THREAD

**Issue by RealScarmo** [ViaVersion/ViaVersion#2664]
### `/viaversion dump` Output

https://dump.viaversion.com/e5fe3cc72522096a17d5586ef2cc742cf6864449328a7cb18f7ea4b39618bbf9

### Console Error

https://paste.gg/p/anonymous/e15a224b472d49848213e542be347236

### Bug Description

Got kicked with

"io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: JsonElement, Data: [Pair{Type|Boolean, false}, Pair{Type|VarInt, 14}, Pair{Type|String, minecraft:adventure/sleep_in_bed}, Pair{Type|Boolean, true}, Pair{Type|String, minecraft:adventure/root}, Pair{Type|Boolean, true}], Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$10 (Anonymous), Packet ID: 98}"

when hitting a pig multiple times, or it could be that i killed it (got kicked right away so i dont know if the pig is dead or not)

### Steps to Reproduce

1. Login with a 1.17.1 client on a Spigot 1.16.5 server
2. Kill a pig (

### Expected Behavior

The pig should die and i should not get kicked from the server

### Additional Server Info

Plugins: **Vault**, **Jobs** (A plugin im developing, really early in development, should not be causing any issues), and **ViaVersion**.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [ ] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3096-Spigot-9fb885e-296df56 (MC: 1.16.5)](https://img.shields.io/badge/Platform-3096--Spigot--9fb885e--296df56%20%28MC%3A%201.16.5%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 14 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-14%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by kennytv** [comment]
You have a badly downloaded/corrupt jar. Redownload it and make sure you aren't reloading plugins.
