### ISSUE TITLE
[Barvalg] Test

### ISSUE THREAD

**Issue by Jo0001** [ViaVersion/ViaVersion#2666]
### `/viaversion dump` Output

https://dump.viaversion.com/2cc4668c59ffbb65abf0d7566d89b8a2aaeeaf769b187ee9701713dcce48fc06

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

This is just a test -please ignore me :)

### Steps to Reproduce

This is just a test -please ignore me :)

### Expected Behavior

This is just a test -please ignore me :)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by Jo0001** [comment]
https://dump.viaversion.com/2cc4668c59ffbb65abf0d7566d89b8a2aaeeaf769b187ee9701713dcce48fc06

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.14.4)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)
