### ISSUE TITLE
Cannot connect to another server via /server

### ISSUE THREAD

**Issue by GamerNoTitle** [ViaVersion/ViaVersion#2668]
### `/viaversion dump` Output

https://dump.viaversion.com/8dbf727aed1f6c3644b79ff464a417998aeba8f63a74436baf5a30c8721adcf0

### Console Error

```
https://paste.gg/p/anonymous/f27fa7705a92498e917b52d8781fd882
```

### Bug Description

When i was trying to connect to another server via /server command, it cannot connect to that server and said that i can't connect to that server and try again later.

### Steps to Reproduce

1. Login into the main server (also the fallback one)
2. try to user `/server` to connect to another server

### Expected Behavior

Cannot connect to that server and showed `We can't connect you to that server, please try again later.`

### Additional Server Info

Velocity: 3.0.0
Viaversion: 4.0.2-SNAPSHOT
Main Server: Minecraft 1.16.4 with fabric 0.6.1.51
Target Server: Minecraft 1.16.4 with fabric 0.6.1.51

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity-3.0.0](https://img.shields.io/badge/Platform-velocity--3.0.0-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by GamerNoTitle** [comment]
1. No, i didnt
2. No, after i upgrading the velocity and viaversion to the latest version.

Thanks for your reply.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
