### ISSUE TITLE
I got kicked telling me to report this bug.

### ISSUE THREAD

**Issue by SlayorPlayz** [ViaVersion/ViaVersion#2674]
### `/viaversion dump` Output

ERROR IN Protocol1_17To1_16_4 IN REMAP OF MULTI_BLOCK_CHANGE (0x3B)

### Console Error

```
https://paste.gg/p/anonymous/a1c3cfecb6844ca98bb85f68659c1b21
```

### Bug Description

I ran a command and my game crashed with a message telling me to report this bug

### Steps to Reproduce

1. Login with 1.17.1
2. Run commmand /chunk claim (simplechunk-v1.3.2)

### Expected Behavior

Claim a chunk

### Additional Server Info

I use purpur for 1.16.5

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid%2Fmissing%20dump-red)

**Comment by SlayorPlayz** [comment]
https://dump.viaversion.com/4950affbdf9ba28c4d35c17a02b477b381d21723dafd70f9ded97fb4b7b727b8
