### ISSUE TITLE
Error while executing a command (/chunk claim)

### ISSUE THREAD

**Issue by SlayorPlayz** [ViaVersion/ViaVersion#2675]
### `/viaversion dump` Output

https://dump.viaversion.com/4950affbdf9ba28c4d35c17a02b477b381d21723dafd70f9ded97fb4b7b727b8

### Console Error

```
https://paste.gg/p/anonymous/a1c3cfecb6844ca98bb85f68659c1b21
```

### Bug Description

ERROR IN Protocol1_17To1_16_4 IN REMAP OF MULTI_BLOCK_CHANGE (0x3B)

### Steps to Reproduce

1. Login with 1.17.1
2. Run command /chunk claim (simplechunk-v1.3.2)

### Expected Behavior

Claim a chunk.

### Additional Server Info

I use purpur for 1.16.5

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Purpur-1171 (MC: 1.16.5)](https://img.shields.io/badge/Platform-git--Purpur--1171%20%28MC%3A%201.16.5%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by kennytv** [comment]
You have a corrupted jar - that could mean the download silently failed, you replaced jars while running, or reloaded the server.
