### ISSUE TITLE
Can't join server since disable package limiter commit

### ISSUE THREAD

**Issue by crafter23456** [ViaVersion/ViaVersion#2676]
### `/viaversion dump` Output

https://dump.viaversion.com/739c86a13dad0108631741f85e8ece23868b4915f50dd7e8fa58db91e979056a

### Console Error

ServerConnector [Server-1] - read timed out
ServerConnector [Server-1] has disconnected

### Bug Description

Since Disable VV packet limiter on 1.17.1+ Paper (commit: a0b1987) I can't join. With a commit before it works.
Tested with only viaversion (and the cloud plugin which doesnt hook into the via api).

### Steps to Reproduce

1. Use latest viaversion
2. Use a paper build post tuinity merge
3. See, you cant join anymore

### Expected Behavior

Normally works like before

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-243 (MC: 1.17.1)](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.17.1%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by kennytv** [comment]
Whoops, fixed. https://github.com/ViaVersion/ViaVersion/commit/f4f7215a6a053f9e744ce54f79142a8ea19a2aa4
