### ISSUE TITLE
On first join

### ISSUE THREAD

**Issue by Cyaeu** [ViaVersion/ViaVersion#2677]
### `/viaversion dump` Output

https://dump.viaversion.com/d7edde236f79c818f8f4ad6304538c185588e5cbae82b66490f78589be72904e

### Console Error

https://paste.gg/p/anonymous/24c271e26ac64dea91e40fc10e6debeb

### Bug Description

Hi, this is showing when i start server and anyone join. (only first player when join)

### Steps to Reproduce

i dont know this error

### Expected Behavior

i dont know this error, so just informating. server: 1.16.5 paper and have plugin viaversion, ViaBackwards, ViaRewind

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-786 (MC: 1.16.5)](https://img.shields.io/badge/Platform-git--Paper--786%20%28MC%3A%201.16.5%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 21 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-21%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 11 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.1): 11 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by kennytv** [comment]
That's some outdated plugin send badly formatted packets with ProtocolLib.
