### ISSUE TITLE
Spamming console

### ISSUE THREAD

**Issue by msmanui** [ViaVersion/ViaVersion#2678]
### `/viaversion dump` Output

https://dump.viaversion.com/5dcf62a2c63a99aa2adfec6f7dd3e5be7b6d6f015a56a8f1b76c7c4395df363d

### Console Error

https://paste.gg/p/anonymous/a141a44b47084ca781fdb5bb298da782

### Bug Description

When Minecraft 1.17 was realase, i did upgrade ViaVersion, ViaBackwars and Rewind. Since then i found this console error. It cant be another plugin's fault because i didnt upgrade none but via. 

I have these settings and still is spamming in the console
suppress-conversion-warnings: true and suppress-metadata-errors: true

This items are the one spamming, the one with lore and names this never happend before but when i upgrade via to 1.17
![unknown](https://user-images.githubusercontent.com/63617395/131905345-f84d985c-da03-4b4b-a702-5c6e849b16bc.png)

### Steps to Reproduce

Like in the photo

### Expected Behavior

Not spamming

### Additional Server Info

no

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Airplane-10 (MC: 1.16.5)](https://img.shields.io/badge/Platform-git--Airplane--10%20%28MC%3A%201.16.5%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): 20 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-20%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.2-SNAPSHOT): 10 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-10%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-9%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by msmanui** [comment]
It happend with any build, i test it on the lastest build already in a test server.

**Comment by kennytv** [comment]
Falls under general parsing issue already tracked on ViaBackwards (related https://github.com/ViaVersion/ViaBackwards/issues/359)
