### ISSUE TITLE
GPL License compatibility 

### ISSUE THREAD

**Issue by SiskooPOG** [ViaVersion/ViaVersion#2679]
### Problem Description

ViaVersion's api appears to be MIT, however the GPL license states that it requires projects that use and link a GPL project to be licensed under the same GPL contract.

### Solution Description

The GPL 3.0 license could be switched to LGPL 3.0, which is exactly the same license, but allows linking for projects with different licenses (Which is the case here)

### Alternatives

Switch the ViaVersion API to GPL 3.0  altogether, this would also make sense

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid%2Fmissing%20dump-red)

**Comment by kennytv** [comment]
You can have code under different licenses in the same repository. Here, it's also clear that API does not touch any GPL code, and that the *full* end-product is still licensed under GPL.
