### ISSUE TITLE
Prevent Collision Player

### ISSUE THREAD

**Issue by gamerjava** [ViaVersion/ViaVersion#2680]
### `/viaversion dump` Output

https://dump.viaversion.com/d3d7b18d86e5ba95b6c814caad6d15f0f4985b8226c51f881cc9ff5edf87b999

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Prevent collision doesnt work. My main server is on 1.16.5 and my second where i want to connect is 1.8.9 and there this feature doesnt work. It only works if i put viaversion to that server this viaversion on bungee doesnt preventing it

### Steps to Reproduce

Create bungee server with 1.16.5 and 1.8.9
Put viaversion to bungee proxy
First server to connect 1.16.5 then switch 1.8.9

### Expected Behavior

I hope prevent collision will work on bungee

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.6.3](https://img.shields.io/badge/Platform-0.6.3-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaRewind(2.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Seanoo1** [comment]
Do not install viaversion on bungeecord if you have 1.8 server. Install only on your all backend(spigot) servers.

**Comment by kennytv** [comment]
We don't support flamecord. But in general, Via performs better on the backend, including feature exclusivity.
