### ISSUE TITLE
ERROR IN Protocol1_8TO1_9 IN REMAP OF TEAMS (0x41)

### ISSUE THREAD

**Issue by alexeses** [ViaVersion/ViaVersion#2681]
### `/viaversion dump` Output

https://dump.viaversion.com/5da587e4e17895d47f591553eb69e61e038463373804c9ed651f5a7fb29d06f8

### Console Error

https://paste.minebox.es/pokokosoko.sql

### Bug Description

When players come in, he sometimes throws them out, as can be seen in the error attached above.

### Steps to Reproduce

1. Player enters a BedWars game
2. No matter the version
3. Enters the game, throws you out directly

### Expected Behavior

Do not send him away! 

### Additional Server Info

Server 1.12

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-1618 (MC: 1.12.2)](https://img.shields.io/badge/Platform-git--Paper--1618%20%28MC%3A%201.12.2%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 23 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-23%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 11 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.1): 11 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by alexeses** [comment]
I have checked it with new versions, updated to the latest one and it is still the same, I don't really understand why.

**Comment by alexeses** [comment]
In case I am rejected for not being on the latest version, I attach proof of the latest version:

> Logs: https://paste.minebox.es/jaxipavofu.sql (Al final podemos ver el fallo, no deja entrar a nadie más)
> https://dump.viaversion.com/3aec486a9f99365bb402096d22cc9468b6515fd34513263467f88a33a675cf19
> ViaVersion config: https://paste.minebox.es/juyonopedu.yaml
> ViaRewind config: https://paste.minebox.es/furepelofa.yaml
> ViaBack config: https://paste.minebox.es/gasoruceva.yaml
> Via-Leg-Sup config: https://paste.minebox.es/qijubupuha.yaml

This happens randomly, the sands work correctly until a point where they stop working and it is necessary to restart it.

Greetings,
Alex.

**Comment by Barvalg** [comment]
![Platform: git-Paper-1618 (MC: 1.12.2)](https://img.shields.io/badge/Platform-git--Paper--1618%20%28MC%3A%201.12.2%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaRewind(2.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by FormallyMyles** [comment]
Can you test without your scoreboard plugin? This is probably not ViaVersion but something sending bad data.

**Comment by alexeses** [comment]
Thank u.

Fixed.
