### ISSUE TITLE
Can't climb ladder with 1.8.9 client on paperspigot 1.16.5 server

### ISSUE THREAD

**Issue by Sckaletz** [ViaVersion/ViaVersion#2682]
### `/viaversion dump` Output

https://dump.viaversion.com/46d98358eb4ae32dad4d764efd0d40b89f47b7b735ff14a0d44cdf147d14f116

### Console Error

Nothing

### Bug Description

We have a Paperspigot 1.16.5 server, where players can't climb ladders if they use client version 1.8 to 1.8.9. It works fine when using version 1.16.5.
https://medal.tv/clips/64169867/d1337nTglyfy

Not sure if you're aware of the problem.

### Steps to Reproduce

Server version 1.16.5 paperspigot and then just join with 1.8.9 and try climbing ladders.

### Expected Behavior

Climbing ladders.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-788 (MC: 1.16.5)](https://img.shields.io/badge/Platform-git--Paper--788%20%28MC%3A%201.16.5%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaRewind(2.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by Camotoy** [comment]
https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ should address your issue.
