### ISSUE TITLE
The plugin told me to report the bugs

### ISSUE THREAD

**Issue by paolosasso** [ViaVersion/ViaVersion#2686]
### `/viaversion dump` Output

https://dump.viaversion.com/17e511aeb3aa7798a08b9d01b39e565aa76b582f710b1842258a62fca0a2c7d6

### Console Error

```
https://paste.gg/p/anonymous/8d630c74df9b412ba9e08e07b2166e8b
c3c3b21ad5a647048211d74c26837037
```

### Bug Description

I crashed when respawned, ViaVersion told me to report it

### Steps to Reproduce

idk

### Expected Behavior

idk

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Tuinity-"935b901" (MC: 1.16.5)](https://img.shields.io/badge/Platform-git--Tuinity--%22935b901%22%20%28MC%3A%201.16.5%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 26 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-26%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 13 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-13%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.1): 12 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1)-12%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by kennytv** [comment]
You have a corrupted jar file/changed jars while running.
