### ISSUE TITLE
Randomly getting kicked.

### ISSUE THREAD

**Issue by Gunfire** [ViaVersion/ViaVersion#2689]
### `/viaversion dump` Output

https://dump.viaversion.com/36ea1370a7dd6a410def164d64511867cec56740b70db4cac13dc909bd682327

### Console Error

https://paste.gg/p/anonymous/8cebf6d84ad74c499756f1044c41cdd5

### Bug Description

Randomly getting kicked from the server on any version above 1.12

### Steps to Reproduce

You don't have to do anything you just get randomly kicked when walking around. 

### Expected Behavior

You no longer get kicked.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-PaperSpigot-ea72d50 (MC: 1.8.8)](https://img.shields.io/badge/Platform-git--PaperSpigot--ea72d50%20%28MC%3A%201.8.8%29-3498db?style=flat-square) <br />![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square)

**Comment by kennytv** [comment]
Ignore the bot; but still invalid, most likely a horribly old plugin sending bad metadata

**Comment by Gunfire** [comment]
Would it be possible to add an option to disable this check? @kennytv Or at least something that stops this from happening.
