### ISSUE TITLE
Cannot connect to server with viaversion

### ISSUE THREAD

**Issue by Sentinelpoweredbytears** [ViaVersion/ViaVersion#2692]
### Console Error

[Netty Client IO #10/WARN]: ERROR IN Protocol1_12_2To1_13 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
[Netty Client IO #10/WARN]: ERROR IN Protocol1_12_2To1_13 IN REMAP OF BLOCK_ENTITY_DATA (0x09)

### Bug Description

I cant connect to a server like cubecraft with viaversion it just instantly kicks me out.

### Steps to Reproduce

Use 1.12.2 base and then just switch to any other version and try to connect to a server and you will get kicked

### Expected Behavior

I should be able to connect. A few days ago this worked fine and i didnt have this problem

### Additional Server Info

![Untitled](https://user-images.githubusercontent.com/87858464/134780738-ce870643-3b3a-4a85-b87f-380d1b3e73aa.png)

### Checklist

- [] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [] I have included a ViaVersion dump.
- [] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid%2Fmissing%20dump-red)

**Comment by kennytv** [comment]
We need the viaversion dump output.

**Comment by Sentinelpoweredbytears** [comment]
how do i do that

**Comment by Jo0001** [comment]
Just run `viaversion dump` in the console and past the link here

**Comment by Sentinelpoweredbytears** [comment]
![image](https://user-images.githubusercontent.com/87858464/134785756-b4522441-05a8-4299-8b35-f408d242ec43.png)
like this because this doesnt work

**Comment by kennytv** [comment]
It literally tells you that you're outdated - and neither is ViaMCP our software.
