### ISSUE TITLE
ERROR IN Protocol1_15_2To1_16 IN REMAP OF ENTITY_EQUIPMENT (0x47)

### ISSUE THREAD

**Issue by YellowZaki** [ViaVersion/ViaVersion#2693]
### `/viaversion dump` Output

https://dump.viaversion.com/ab72d36306031dd522e7b621958be2a1941cf0ce7f2651f5227ba8058434c139

### Console Error

```
https://pastebin.com/q8HeYNBM
```

### Bug Description

It happens on 1.13, 1.14 and 1.15. On 1.16 it doesn't happen.
The player is kicked from the server with the error message.

As far as I know, it happens when a player launches from a launchpad. 

Launchpads works by spawning a falling block:

` FallingBlock fallingBlock = p.getWorld().spawnFallingBlock(teleportPlayer, Material.BARRIER.createBlockData());`

Then it is applied a velocity so the fallingBlock is launched and makes a curve to land:

`getFallingBlock().setVelocity(launchLocation.getDirection().normalize().multiply(power / 15.0));`

And then, while the falling block hasn't touched ground, the player is applied the velocity of the falling block every 1 tick:
```
fallingBlock.setTicksLived(1);
player.setVelocity(fallingBlock.getVelocity())
```

### Steps to Reproduce

It is detailed on the bug description.

### Expected Behavior

Player is not kicked, and no error.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Tuinity-"f32fe9a" (MC: 1.16.5)](https://img.shields.io/badge/Platform-git--Tuinity--%22f32fe9a%22%20%28MC%3A%201.16.5%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 32 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-32%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 13 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-13%20commit(s)%20behind%20master-yellow?style=flat-square)
