### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by LucidAPs** [ViaVersion/ViaVersion#2694]
### `/viaversion dump` Output

https://dump.viaversion.com/86b7fe1847f31df6d7251faf666ab14a8201fe4e1506d66bc178f84aba31d370

### Console Error

https://nekobin.com/caviyokoxu

### Bug Description

Console Error

### Steps to Reproduce

Console Error

### Expected Behavior

No Console Error

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Purpur-1394 (MC: 1.17.1)](https://img.shields.io/badge/Platform-git--Purpur--1394%20%28MC%3A%201.17.1%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by kennytv** [comment]
You're outdated.
