### ISSUE TITLE
Issue with spawning a custom bat

### ISSUE THREAD

**Issue by ThiemoBoven** [ViaVersion/ViaVersion#2697]
### `/viaversion dump` Output

https://dump.viaversion.com/4719c1e4a5246d1be2ce44acd8d0b7750760eee3d5bb4f32ebcb64d401498e13

### Console Error

https://paste.gg/p/anonymous/30fd8f88a33c46e89c4b73eb9aa4c98c

### Bug Description

When spawning a custom-made bat for 1.8.8-R3 it kicks players playing on 1.16-1.17 for an invalid wither skull. Not sure how this happens but the client does not want to see it as a bat.

The bat class; https://paste.gg/p/anonymous/c1d9b279381e48b0b49b6c23ce4860e0
The spawning class: https://paste.gg/p/anonymous/28f0b8717f6342898e7d0c10e4dc08b6
(In here at line 52 the getEntityBatClass is the listed CustomEntityBat class)

### Steps to Reproduce

1. Create a custom bat entity
2. Register the entity
3. Spawn the entity
4. Get kicked on 1.16+

### Expected Behavior

It should properly translate the bat in to a normal behaving entity.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-PaperSpigot-dd43101 (MC: 1.8.8)](https://img.shields.io/badge/Platform-git--PaperSpigot--dd43101%20%28MC%3A%201.8.8%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 37 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-37%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by kennytv** [comment]
Looks like you pasted the wrong text into the stacktrace paste

**Comment by ThiemoBoven** [comment]
Whoops, sorry; here you go: https://paste.gg/p/anonymous/30fd8f88a33c46e89c4b73eb9aa4c98c

**Comment by kennytv** [comment]
Whatever you're doing, you're not spawning the entity correctly (assuming it's actually connected to the code you sent), that's unrelated to Via handling.
