### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Could not find type String at 0

### ISSUE THREAD

**Issue by 4drian3d** [ViaVersion/ViaVersion#2699]
### `/viaversion dump` Output

https://dump.viaversion.com/9b21ce32191d72ce0405a589133316da549fe553883d76652c78a02e8555f7e1

### Console Error

```
Put the paste.gg link or text here.
```
https://pastebin.com/YGaipu13

### Bug Description

**The dump I sent corresponds to a previous version of ViaVersion "https://ci.viaversion.com/job/ViaVersion/559/", since I downgraded the plugin to see if the error was from the latest version, but the error can be reproduced in the latest version.**

Today I upgraded ViaVersion to its latest SNAPSHOT version from https://ci.viaversion.com/job/ViaVersion/ .
When a user of a minor version <1.16.5 logs in to a Paper 1.17.1 server, the above error appears.

### Steps to Reproduce

1. Upgrade ViaVersion to latest SNAPSHOT build
2. Setup a 1.17.1 server with ViaVersion/ViaBackwards
3. Join with <1.16.5 client
4. Error occurs

### Expected Behavior

That no error occurs

### Additional Server Info

Paper 1.17.1 
02.10 13:17:21 [Server] INFO This server is running Paper version git-Paper-279 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6de48db)
02.10 13:17:21 [Server] INFO You are 18 version(s) behind
02.10 13:17:21 [Server] INFO Previous version: git-Paper-266 (MC: 1.17.1)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-279 (MC: 1.17.1)](https://img.shields.io/badge/Platform-git--Paper--279%20%28MC%3A%201.17.1%29-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-4%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by kennytv** [comment]
Outdated
