### ISSUE TITLE
The plugin tol me to report the issue, so here I Am

### ISSUE THREAD

**Issue by BarraR3port** [ViaVersion/ViaVersion#2703]
### `/viaversion dump` Output

https://dump.viaversion.com/48dee0d740ee67efe8806edad915dae3f39036c7322ccc120f2213552f476d81

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/888e7d4c6b0646ddacfbd4e0ad410187

### Bug Description

This exact error had never occurred to me, but the part "IndexOutOfBoundsException : readerIndex(3) + length(203) exceeds writerIndex(9..." is consistently showing up and kicking my players out of the server. 

### Steps to Reproduce

Jus switched through servers and this error came up

### Expected Behavior

Just a normal and smooth switch between servers

### Additional Server Info

I'm using Flamecord bc I were using Waterfall the past days, but the error just keep showing up and up, so I had to try other options, but the error persist.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.6.3](https://img.shields.io/badge/Platform-0.6.3-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 45 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-45%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by kennytv** [comment]
Flamecord is not fully supported by us, otherwise try updating to ci builds found on https://ci.viaversion.com/job/ViaVersion/
