### ISSUE TITLE
i not know the name of this error sorry

### ISSUE THREAD

**Issue by shj10pila** [ViaVersion/ViaVersion#2710]
### `/viaversion dump` Output

i not know what is this i started now in github and i bad on elglish (im blazzilian)

### Console Error

i not have a paste.gg

### Bug Description

i play in mc.skycraft.com.br server and this message apears(more information is steps)  : "Conexão perdida

Internal Exception: io.netty.handler.codec.DecoderException: Please post this
error to https://github.com/ViaVersion/ViaVersion/issues<br/><br/>{Source 0:唯8螂蛊)

Actual Error:"

### Steps to Reproduce

1 login in 1.8-1.16.4
2 play in mc.skycraft.com.br server
3 start a bedwars round
4 teleport to the island and apears this

### Expected Behavior

i go to the island without apears this message and i play the round

### Additional Server Info

i not use plugins and i not know whats is a bungeecord but is mc.skycraft.com.br and i use a hack

### Checklist

- [ ] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [ ] I have included a ViaVersion dump.
- [ ] If applicable, I have included a paste (**not a screenshot**) of the error.
- [ ] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid%2Fmissing%20dump-red)

**Comment by Ccode-lang** [comment]
Run viaversion dump

**Comment by shj10pila** [comment]
> Run viaversion dump

oh i understand now but man if has done with viaversion this is not going to do the same with my version but ok

**Comment by kennytv** [comment]
We can't help you if you don't follow the issue template
