### ISSUE TITLE
Error when player logged with AuthMe

### ISSUE THREAD

**Issue by CJYKK** [ViaVersion/ViaVersion#2713]
### `/viaversion dump` Output

https://dump.viaversion.com/ee7b6d320a2293f129c8e3626c7eb44fded18a5a20455ab7c77591dcbdada183

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/a56b0e389dbf46309b645c8c7ba1b746

### Bug Description

Player logged with AuthMe
Console Warn
Player disconnect with reason "Disconnect"

### Steps to Reproduce

1. Login with 1.17.1 client
2. Enter password
3. Player has been kicked with reason "Disconnect"

### Expected Behavior

Login and play normal

### Additional Server Info

I'm using Paper 1.12.2 last version

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-1618 (MC: 1.12.2)](https://img.shields.io/badge/Platform-git--Paper--1618%20%28MC%3A%201.12.2%29-3498db?style=flat-square) <br />![ViaVersion (4.1.0-21w40a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.1.0--21w40a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square)

**Comment by kennytv** [comment]
You have a broken block entity somewhere (and apparently an outdated or broken AuthMe as well)
