### ISSUE TITLE
Internal Exception

### ISSUE THREAD

**Issue by T0kyoofr** [ViaVersion/ViaVersion#2719]
### `/viaversion dump` Output

https://dump.viaversion.com/e195832f49f75a5df6f829a6d3239f3ecb6ee892ae541f811a5052d06c377f6d

### Console Error

```
https://paste.gg/p/anonymous/cd720ab02d314266acf28e65eb86ab22
```

### Bug Description

When i'm login it send it

### Steps to Reproduce

I just connect to my server

### Expected Behavior

Connect to the server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Spigot-fe3ab0d-162bda9 (MC: 1.13)](https://img.shields.io/badge/Platform-git--Spigot--fe3ab0d--162bda9%20%28MC%3A%201.13%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 56 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-56%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by kennytv** [comment]
We need the full error. But in any case, update to ci builds, and if it happens again, comment with the new, full error log.
