### ISSUE TITLE
ViaVersion?

### ISSUE THREAD

**Issue by kh0mka** [ViaVersion/ViaVersion#2721]
### `/viaversion dump` Output

https://dump.viaversion.com/95844c60a64e5ccd99f126636f6e66d7e83dd106c448c32d3f3dc2537f7b39be

### Console Error

None

### Bug Description

On the server, when logging in from 1.12.2, it writes the name of the newest version over the mobs. How to remove or fix this? For example, since 1.12.2 "Cod" is written above the octopus. But since 1.16.5-1.17.1 its not octopus, but Cod.

### Steps to Reproduce

None

### Expected Behavior

None

### Additional Server Info

Airplane MC 1.16.5
ViaVersion 4.0.1
ViaBackwards Latest

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Airplane--11%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Airplane--11%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.0.1): 57 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-57%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.0.1): 18 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-18%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
How are old clients supposed to know what mob they're actually looking at? Else disable `always-show-original-mob-name`

**Comment by kh0mka** [comment]
> How are old clients supposed to know what mob they're actually looking at? Else disable `always-show-original-mob-name`

thx, it helped
