### ISSUE TITLE
Kick while playing bedwars

### ISSUE THREAD

**Issue by Dawid-I** [ViaVersion/ViaVersion#2722]
### `/viaversion dump` Output

https://dump.viaversion.com/c5daaf4f271a9bbb26bfb78dd8d0f2d0004d1767198f6a0f85bef146a93b77a2

### Console Error

```
https://paste.gg/p/anonymous/44efcca6650c42c69dbb2c4fb7650e43
```

### Bug Description

While playing bedwars using "Screaming BedWars" plugin, player is getting kicked when moving ~10 blocks from his bed. Only occurs on Lunar Client 1.16! Players who are using other launchers don't have this issue.

When joining the server with lunar I noticed error:
[16:05:21 WARN]: [ViaVersion] Invalid dimension id: 10

### Steps to Reproduce

1. Create 1.13.2 paperspigot server
2. Install Screaming bedwars and Viaversion
3. Join server on "Lunar Client 1.16"
3. Join arena and start playing
4. Move ~10 blocks after arena start
5. Get kicked with viaversions error

### Expected Behavior

Player shouldn't be kicked 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--655%20%28MC%3A%201.13.2%29](https://img.shields.io/badge/Platform-git--Paper--655%20%28MC%3A%201.13.2%29-3498db?style=flat-square) </br>![ViaVersion (4.0.1): 57 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-57%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by Jo0001** [comment]
Solved on Discord
