### ISSUE TITLE
Players Invisibility

### ISSUE THREAD

**Issue by minehawker9** [ViaVersion/ViaVersion#2723]
### `/viaversion dump` Output

https://dump.viaversion.com/905317684be920f9c57ccbab3bb17abd12b48388bff74386b2b6d4cf18dc152a

### Console Error

https://dump.viaversion.com/905317684be920f9c57ccbab3bb17abd12b48388bff74386b2b6d4cf18dc152a

### Bug Description

1.8 players can see 1.16 players but 1.16 players cant see 1.8 and others 

### Steps to Reproduce

Login with 1.8
You can see players
Now login with 1.16
then you cannot

### Expected Behavior

https://dump.viaversion.com/905317684be920f9c57ccbab3bb17abd12b48388bff74386b2b6d4cf18dc152a

### Additional Server Info

yes we use bungeecord

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--%224c7641d%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--%224c7641d%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.0.1): 57 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-57%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.0.1): 18 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-18%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
Try without other plugins, otherwise see what exact version this starts happening on (i.e. 1.15, 1.15.2, 1.16, 1.16.4, ...)

**Comment by kennytv** [comment]
Another plugin is most likely spawning virtual entities with uuids of actual players, which 1.16+ clients do not allow. Not something we should fix on our side
