### ISSUE TITLE
Translate packets spawnPacket and EntityMeta packet 

### ISSUE THREAD

**Issue by muntder123** [ViaVersion/ViaVersion#2725]
### `/viaversion dump` Output

https://dump.viaversion.com/3451f88f2481f4cc3a8eef032997885ab657e89701237ead7252a70146e1346f

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.md-5.net/daqoxejage.md

### Bug Description

the problem only happens if i join with a minecraft version bigger than 1.8.8 < i tried 1.8.9 works fine if i join with 1.9.4 or the error happend .. pls if anyone have any idea why its hapening let me know .. + i know the code is maybe bad .. didnt finish it .. + i need 1.8+ and up player's to be able to play

### Steps to Reproduce

1- login with a higher version than 1.8 ,
2- if the server is 1.8.8 spigot

### Expected Behavior

it kick the player out side the server and crash the server

### Additional Server Info

if a player join with 1.8 it works fine 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--%224c7641d%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--%224c7641d%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by muntder123** [comment]
my code for the custom entity is this :
https://paste.md-5.net/nuqahehufu.java

my code to spawn the entity :
https://paste.md-5.net/ocetiyaduy.java 


this is the codes i made

**Comment by kennytv** [comment]
A plugin on your server is sending bad metadata. Sorry, but you'll have to figure that out on your own running on that kind of server version.

**Comment by muntder123** [comment]
its send me this error log and kick player : 
: m_IQ lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.SpawnPackets$5 (Anonymous)}
Actual Error:
