### ISSUE TITLE
Kick for protocollib api not Supported

### ISSUE THREAD

**Issue by danib150** [ViaVersion/ViaVersion#2726]
### `/viaversion dump` Output

https://dump.viaversion.com/ee4e851de72bd20589a3db0d4dec491af34a3cae84cd2ac62fc12452f0f2d53d

### Console Error

No error.

### Bug Description

I have made this event with protocollib: https://www.toptal.com/developers/hastebin/utusiqanux.yaml
When i try to join in the server with another version of the server version (1.8.8) and use this event the client crash with this error:
https://imgur.com/IXOrHRs

### Steps to Reproduce

1. Login with ex. 1.12.2 client
2. Use setInvisibility Event
3. The client crash

### Expected Behavior

The plugin shouldn't kick, but it should make the armor and item the player is holding invisible.

### Additional Server Info

Bungeecord-Flamecord (LATEST) with custom plugins (WarSS), (WarCore), (Parties)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Spigot--21fe707--e1ebe52%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--Spigot--21fe707--e1ebe52%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.0.1): 57 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-57%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.0.1): 18 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-18%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.1): 17 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
The 1.8 client is notorious for accepting plainly false order and content of equipment packets, so very likely what you're sending is incorrect.

**Comment by kennytv** [comment]
See https://github.com/ViaVersion/ViaVersion/blob/master/common/src/main/java/com/viaversion/viaversion/protocols/protocol1_9to1_8/packets/EntityPackets.java#L163 for a hint at that
