### ISSUE TITLE
Non-existent method

### ISSUE THREAD

**Issue by wypixel** [ViaVersion/ViaVersion#2730]
### `/viaversion dump` Output

https://dump.viaversion.com/466ac4b19a072307b3d990512f17d544f4a82ddcbab2ebd63dd43d78866cb5cb

### Console Error
When the server starts this error appears.
```
22:29:49 [SEVERE] java.lang.NoSuchMethodException: net.md_5.bungee.connection.InitialHandler.getRelayMessages()
22:29:49 [SEVERE]     at java.base/java.lang.Class.getDeclaredMethod(Class.java:2675)

22:29:49 [SEVERE]     at com.viaversion.viaversion.bungee.handlers.BungeeServerHandler.<clinit>(BungeeServerHandler.java:71)

22:29:49 [SEVERE]     at com.viaversion.viaversion.bungee.platform.BungeeViaLoader.load(BungeeViaLoader.java:66)

22:29:49 [SEVERE]     at com.viaversion.viaversion.ViaManagerImpl.onServerLoaded(ViaManagerImpl.java:154)

22:29:49 [SEVERE]     at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)

22:29:49 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

22:29:49 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

22:29:49 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:833)

```

### Bug Description

When the player tries to join the server, this error happens and cannot connect.
![cmd_gZByAF9phH](https://user-images.githubusercontent.com/79768336/141664160-99161d4a-b174-46e2-9fdd-47857e05365b.png)

Observation: The getRelayMessages() function no longer exists in Bungeecord.
I just don't use a less updated BungeeCord because I use what I'm programming, which is based on the current BungeeCord :(

### Steps to Reproduce

First log:
1. Download new BungeeCord version
2. Start your server

Disconnect:
1. Join the server

### Expected Behavior

The player is disconnected.

### Additional Server Info

I just use ViaVersion and a private plugin in my BungeeCord.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.17--R0.1--SNAPSHOT%3Ac7b0c3c%3Aunknown](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.17--R0.1--SNAPSHOT%3Ac7b0c3c%3Aunknown-3498db?style=flat-square) </br>![ViaVersion (4.0.1): 58 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-58%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by Camotoy** [comment]
A user in Discord stated this issue existed on the latest dev build. https://github.com/SpigotMC/BungeeCord/commit/c7b0c3cd48c9929c6ba41ff333727adba89b4e07 this commit is the likely culprit.
