### ISSUE TITLE
error when joining server

### ISSUE THREAD

**Issue by DEADLYDEVIL-SPIGOT** [ViaVersion/ViaVersion#2732]
### `/viaversion dump` Output

https://dump.viaversion.com/637d9ab11622ab17bfebe5e4fc3f1649ce471fba637a449d3f38d8b968f0dbd5

### Console Error

```
Put the paste.gg link or text here.
```
https://pastebin.com/YB8rpAhc

### Bug Description

when I try to join the server it joins successfully but I get this long error

### Steps to Reproduce

1. just start waterfall server(viaversion,viabackrewards,viarewind installed) and join with 1.17.1 client

### Expected Behavior

Console should not show this error

### Additional Server Info

Plugins are inside the dump link I sent

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [x] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.17--R0.1--SNAPSHOT%3A5abfefb%3A453](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.17--R0.1--SNAPSHOT%3A5abfefb%3A453-3498db?style=flat-square) </br>![ViaVersion (4.0.1): 58 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-58%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.0.1): 18 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-18%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
Update to https://ci.viaversion.com/job/ViaVersion-DEV/

**Comment by DEADLYDEVIL-SPIGOT** [comment]
> 
> 
> Update to https://ci.viaversion.com/job/ViaVersion-DEV/

Now i can't even join the server

**Comment by kennytv** [comment]
Then you didn't update ViaBackwards as well or have some other error in your setup. If you need more help, I'd suggest joining our support Discord
