### ISSUE TITLE
silent startup console log

### ISSUE THREAD

**Issue by Bruce0203** [ViaVersion/ViaVersion#2734]
### Problem Description

i need silent console logging

### Solution Description

add config.yml silent startup option

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
You can configure your console logging if you need that, I don't really see a use case where this option doesn't add a new level of complexity for solving issues.
