### ISSUE TITLE
ERROR IN Protocol1_13To1_12_2 IN REMAP OF COMBAT_EVENT (0x2D) (1.12 -> 1.16)

### ISSUE THREAD

**Issue by whilein** [ViaVersion/ViaVersion#2736]
### `/viaversion dump` Output

https://dump.viaversion.com/5b850aaf641abb198228507f8950803648fa623ebdccdd759aa9b064da8ea6f7

### Console Error

1) https://paste.gg/p/anonymous/83b7adc1bb37401d816194b9732cc6a3
2) https://paste.gg/p/anonymous/ec866133fcc24066bac4e8e140272705

### Bug Description

When player deaths, he is disconnecting by "Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_13to1_12_2.Protocol1_13To1_12_2$13 (Anonymous)}"

When operator player uses /give command, he is disconnecting by "Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_13to1_12_2.Protocol1_13To1_12_2$5 (Anonymous)}"

### Steps to Reproduce

1)
1. Held a sword
2. Damage a player
3. Kill a player

2)
1. Open chat using T or /
2. Write /give @p stone command
3. Press Enter

### Expected Behavior

1, 2) The player shouldn't be kicked with Internal Exception

### Additional Server Info

I also use BungeeCord without a plugins which affects to minecraft protocol. 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--%2258211345%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--%2258211345%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Fixes in https://github.com/ViaVersion/ViaVersion/commit/1afa441571d1cb5d3a0871bcf4f132e9c6e7e7e5
