### ISSUE TITLE
"io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException" while eating

### ISSUE THREAD

**Issue by EinfachStam** [ViaVersion/ViaVersion#2738]
### `/viaversion dump` Output

https://dump.viaversion.com/430b7d581ed3d5f3a7196a7299e532ca21cea93572dbbd627f9b3baac26fb5b1

### Console Error

https://paste.gg/p/anonymous/e1c7d009eca441539ac1afcc24b89e5f

### Bug Description

Eating in version 1.17.1 with a server on 1.16 causes the game to crash immediately after finishing eating

### Steps to Reproduce

1. Login with a 1.17.1 client on a 1.16.5 server
2. Lose hunger with sprinting/jumping/etc.
3. Eat to regen your hunger

### Expected Behavior

You should just get hunger back and should continue playing normally

### Additional Server Info

- BungeeCord 1.17.1 proxy server
- Paper Server Software

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--778%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--778%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.0.1): 58 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-58%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
You have a corrupted jar file
