### ISSUE TITLE
[Bug] FIXED

### ISSUE THREAD

**Issue by msmanui** [ViaVersion/ViaVersion#2739]
Delete please, found the issue myself!

**Comment by Barvalg** [comment]
![Platform: git--Paper--788%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--788%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.0.2-SNAPSHOT): 13 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-13%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.0.2-SNAPSHOT): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2-SNAPSHOT): 4 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>
