### ISSUE TITLE
Not able to connect

### ISSUE THREAD

**Issue by Deeptanil** [ViaVersion/ViaVersion#2742]
### `/viaversion dump` Output

https://dump.viaversion.com/5090c93547efb64ad18f3eca330e16f91cd573cc06696a49485f3660c8bef490

### Console Error

https://paste.gg/p/anonymous/8cdfc7ed374245b6ab68b51de0d18408

### Bug Description

Can't connect to the server at all. 

### Steps to Reproduce

1.9 (the only version I tested with)

### Expected Behavior

Should connect normally. 

### Additional Server Info

PaperMC 1.17.1

With latest viaversion and viabackward

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--386%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--386%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.0): Even with master](https://img.shields.io/badge/ViaVersion%20(4.1.0)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.1.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.1.0)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Some other plugin is likely sending bad metadata. If you can reproduce without plugins, we'll reopen the issue.

**Comment by Deeptanil** [comment]
You're right. It works without any other plugins.
But any clue which plugin? Yeah this isn't related to via, but this issue is happening since I updated yesterday.
1.9, 1.10, 1.11, 1.12, 1.13, 1.14 does NOT work.
But 1.15+ does work!

**Comment by kennytv** [comment]
Try removing the npc plugin, then Holographicdisplays, or something else that might do virtual entities to find out which it could be caused by, not exactly sure

**Comment by Deeptanil** [comment]
Down grading to viaversion 4.0.1 fixes the issue.

I don't understand-
It works with just viaversion and no other plugins.
But with my plugins it doesn't work... But down grading works.

**Comment by kennytv** [comment]
The issue is now tracked here: https://github.com/ViaVersion/ViaBackwards/issues/412
