### ISSUE TITLE
Distance bug

### ISSUE THREAD

**Issue by msmanui** [ViaVersion/ViaVersion#2743]
### `/viaversion dump` Output

.

### Console Error

Clients with 1.18 has lower distance than any version below. 
My server is 1.16.5
![image](https://user-images.githubusercontent.com/63617395/144221024-bbc685eb-c36d-4775-8649-e0b3af3e5db5.png)
 

### Bug Description

Bug

### Steps to Reproduce

Join with a client 1.18 to a server lower than that version.

### Expected Behavior

To see as usual

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Not a bug, 1.18 clients force the server's view distance in a circular pattern and is intended to make fps less bad. Mods can disable the fog, otherwise we may add a config option to increase the sent server distance soon

**Comment by msmanui** [comment]
> Not a bug, 1.18 clients force the server's view distance in a circular pattern and is intended to make fps less bad. Mods can disable the fog, otherwise we may add a config option to increase the sent server distance soon

Yes adding the config option would be perfect :D

**Comment by kennytv** [comment]
Or we won't; 1.18.1 fixes the issue, it shouldn't be too long before it arrives https://bugs.mojang.com/browse/MC-243216
