### ISSUE TITLE
Chests are invisible in 1.18 when loading chunks

### ISSUE THREAD

**Issue by RoccoDev** [ViaVersion/ViaVersion#2744]
### `/viaversion dump` Output

https://dump.viaversion.com/34a9c9fbf4be735abb8409a64a50e51db26ab4c20368247ad5a49aa26a395e0c

### Bug Description

When you get Chunk Data packets, chests aren't sent properly. They will act like a normal block and have working collision and F3 info, though they won't render. In the case of ender chests, only particles render.
The same applies to double chests. It does not apply to beds.

There are no server or client errors either.

I have made sure that:
* it works in 1.18 singleplayer
* it doesn't work without any plugins (other than ViaVersion)
* it doesn't work on latest Spigot 1.8.8 (with ViaVersion)

Please note that regular block place packets do work, for instance you can place a chest and see it just fine, but when you relog it will be invisible. By the same logic, anything that would send a block place packet also makes it work, for example an adjacent block sending a physics signal to the chest.

Invisible chest example:
![immagine](https://user-images.githubusercontent.com/13873938/144260716-47c983f1-57d5-46fc-a08f-39a1b70ebef7.png)

### Steps to Reproduce

0. 1.18 client, 1.8.8 server
1. Place a chest in the world (ender chests and double chests also work)
2. Unload the chunk client-side by logging out (works every time), or going very far away (not tested)
3. Log back in (or go back to the chunk)

### Expected Behavior

There should be a fully working chest.

### Additional Server Info

Can be reproduced without a proxy. The ViaVersion I used was the beta from some days ago, though it is reproducible on stable 4.1.0 (which is the latest available build atm) as well.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Spigot--db6de12--18fbb24%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--Spigot--db6de12--18fbb24%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.1.0-1.18-rc3-SNAPSHOT): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.0--1.18--rc3--SNAPSHOT)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by Camotoy** [comment]
I'm able to confirm this on Spigot 1.8.8 and the master version of ViaVersion.
