### ISSUE TITLE
Delete please

### ISSUE THREAD

**Issue by NathZen** [ViaVersion/ViaVersion#2747]
Already found out the problem

ignore-long-1_16-channel-names: true

Delete please
thanks

**Comment by Barvalg** [comment]
![Platform: git--Paper--655%20%28MC%3A%201.13.2%29](https://img.shields.io/badge/Platform-git--Paper--655%20%28MC%3A%201.13.2%29-3498db?style=flat-square) </br>![ViaVersion (4.1.0): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.0)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>
