### ISSUE TITLE
Crashing clients in 1.14.4 when clicking on sign text.

### ISSUE THREAD

**Issue by jbreed03** [ViaVersion/ViaVersion#2749]
### `/viaversion dump` Output

https://dump.viaversion.com/c7fb74f40352397ab1031a2ae387c180f312a7589ed5e0369928abb0c87c9247

### Console Error

https://paste.gg/p/anonymous/956ee76b7e0d44f89a2c6836b3f82ba2

### Bug Description

Right clicking a sign used in a custom map within MineCraft version 1.14.4 crashes the client.

### Steps to Reproduce

1. I installed the following map on a 1.14.4 papermc.jar - Slay: https://www.minecraftmaps.com/game-maps/slay
2. I have the following plugins installed
    - ViaVersion 4.1.0
    - ViaRewind 2.0.1
3. Join map, right click any sign and you receive the crash listed above. I apologize I don't have any other 1.14.4 maps to try.

### Expected Behavior

Right click sign and it changed players allowed in the mini game, type of map, map size, units you would like to use.

### Additional Server Info

Yes, this is on a Bungeechord server running Waterfall. The server itself is Papermc 1.14.4. The plugins on the server in question are listed in the steps to produce.

On the Waterfall server I have the following plugins.
  - Bungeeguard
  - AdvancedNMOTD-9.2.0
  - multichat-1.9.6 (legacy plugin)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--243%20%28MC%3A%201.14.4%29](https://img.shields.io/badge/Platform-git--Paper--243%20%28MC%3A%201.14.4%29-3498db?style=flat-square) </br>![ViaVersion (4.1.0): 5 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.0)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.0): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.0)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
Sorry, I don't quite follow. What version did you join what server with and how does 1.17 play into this? 1.14 clients on 1.14 servers will never output the error you provided unless you have a bad or stacked setup; there's no ViaRewind 4.1.0; ProtoclLib is not a Bungee plugin

**Comment by jbreed03** [comment]
Hi Kennytv!

I joined the server with version 1.18. The server in question is a 1.14.4 papermc.jar, the lobby is a 1.17.1 papermc.jar. ViaRewind 2.0.1, sorry I forgot only one of the three isn't 4.1.0 now.

**Comment by kennytv** [comment]
I cannot reproduce. When I join a 1.14.4 Paper server with the Slay map, I can right click all the signs without any errors

**Comment by jbreed03** [comment]
What client version are you joining with? And are you doing it as singleplayer? Asking so I can go try it myself.

**Comment by kennytv** [comment]
A 1.18 client, and as said a 1.14.4 Paper server

**Comment by jbreed03** [comment]
One second I'm going to take this off bungee and try it.

**Comment by jbreed03** [comment]
I think I have a problem with my paper 1.14.4 install then. This might be a stupid question, did you have to force it to use JAVA 13? my Paper 1.14.4 wouldn't load until I installed 13 and put a command in to use it over the current install. That is my only difference on any of the servers.

**Comment by kennytv** [comment]
I used Java 8, but otherwise Paper has a startup flag to disable the Java version check

**Comment by jbreed03** [comment]
You don't happen to know it off the top of your head do you so I can try? I'm scouring the Aikers page and can't find it referenced.

**Comment by jbreed03** [comment]
Sigh I don't know whats going on then. I just can't get it to run. Frustrating since you had absolutely no issues I listed. I'm still getting the entity error.

**Comment by jbreed03** [comment]
So I have a 1.14.4 PaperMC.jar from their site. I'm using the startup script shown below because I wanted sure if a flag was messing it up.

title Slay
"C:\Program Files\Java\jdk1.8.0_311\bin\java.exe" -Xms2G -Xmx2G -jar paper-1.14.4-243.jar nogui

and I have ViaVersion from here - https://www.spigotmc.org/resources/viaversion.19254/
and ViaRewind from here - https://www.spigotmc.org/resources/viarewind.52109/

I don't know what I could possibly be doing wrong.

**Comment by jbreed03** [comment]
Thank you for your help! After all this, buried through a bunch of links I just simply found an updated version of the map. 

https://www.curseforge.com/minecraft/worlds/slay/files

Closing issue.
