### ISSUE TITLE
Can't place signs when on 1.8.9

### ISSUE THREAD

**Issue by DzirDev** [ViaVersion/ViaVersion#2751]
### `/viaversion dump` Output

https://dump.viaversion.com/d3f53a8105e01b327f0b99a02114fd5589edd6c978541a6c40c701d67b4e2ad1

### Console Error

https://paste.gg/p/anonymous/78fdfb009a0f4456ac58f9572166aab9

### Bug Description

When I place signs while on 1.8.9 I get kicked.

### Steps to Reproduce

1. Join server with 1.8.9
2. Place sign.
3. Get kicked.

### Expected Behavior

Placed sign should not kick you.

### Additional Server Info

Server is running paper 1.18

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [x] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--%22057adb0%22%20%28MC%3A%201.18%29](https://img.shields.io/badge/Platform-git--Paper--%22057adb0%22%20%28MC%3A%201.18%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.1.1--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.1.0): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.0)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>
