### ISSUE TITLE
String too big

### ISSUE THREAD

**Issue by disqetow** [ViaVersion/ViaVersion#2754]
### `/viaversion dump` Output

https://dump.viaversion.com/d619ea7bf8c1a034273e0e02c0ad51317dd05ff681e022fa6c5edf13ad5ca5f5

### Console Error

https://pastebin.com/wmy2pxzg

### Bug Description

Player disconnect by this issue.

### Steps to Reproduce

open server with 1.12.2 use viaversion

### Expected Behavior

no disconnect

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--33d42c8e%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--33d42c8e%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.1.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>
