### ISSUE TITLE
No light data found

### ISSUE THREAD

**Issue by powerk123** [ViaVersion/ViaVersion#2755]
### `/viaversion dump` Output

https://dump.viaversion.com/dc4165f75d11461d69cbcc7dd4c771c6b21902fc08baf08245d7859faff51bce

### Console Error

[Netty Epoll Server IO #1/WARN]: [ViaVersion] No light data found for chunk at -398, 186. Chunk was already loaded: false

### Bug Description

When I updated viaversion from 4.0.1 to the latest one, some chunks are dark to players with version 1.17 and above.

### Steps to Reproduce

I dont know exactly...
But maybe you have to start a paper 1.16.5 server and run viaversion 4.1.1 or 4.1.2 dev build and then play on the server with 1.17 or above in order to find a drak chunk.

### Expected Behavior

I expected viewing chunks with light.

### Additional Server Info

I think that all the useful info are in the viaversion dump (above), but I can write again those ones: java version: 16, server version: 1.16.5, paperspigot version: build 790, viaversion: v4.1.1 (also tested v4.1.2 dev).

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--790%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--790%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.1.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
You have a plugin sending chunk data before light data; I'd try figuring out which one it is and report that as bad behavior to the plugin author.

**Comment by powerk123** [comment]
Thx for your reply, but are you sure? I mean that this appeared when I updated viaversion. Btw I may know which plugins has caused it but im not sure... I thinks is orebfuscator. Can you help me using the info of the viaversion dump to find the plugin which causes this issue?

**Comment by Bobcat00** [comment]
I'm seeing the same messages, and I'm running Orebfuscator 5.1.6 on my 1.17.1 server. There's a new version of Orebfuscator out, it might be worth trying.

**Comment by powerk123** [comment]
> I'm seeing the same messages, and I'm running Orebfuscator 5.1.6 on my 1.17.1 server. There's a new version of Orebfuscator out, it might be worth trying. EDIT: Ah, I see you're already running 5.2.0. There is a 5.2.1.

Yeah, I already updated orebfuscator xD. Btw if you find a way to fix this issue, let me know what to do.
(Thx for your reply btw)

**Comment by Bobcat00** [comment]
If you think it's from Orebfuscator, you should open an issue on their Github page.
