### ISSUE TITLE
Error while 1.8 client connects to 1.18 server [BungeeCord]

### ISSUE THREAD

**Issue by LOCNetwork** [ViaVersion/ViaVersion#2756]
### `/viaversion dump` Output

https://dump.viaversion.com/33a3b986a388fd0370c3e9835e73f10002a211c7defbaa7e7a60f260e436ee81

### Console Error

```
https://paste.gg/p/anonymous/a62b24a5c6874cdfa6bad1704a916d56
```

### Bug Description

I have Viaversion, ViaBackwards and ViaRewind in my BungeeCord server. When a 1.8 client tries to connect to a 1.18 server in the network, the error pops up in console and kicks the player from the server.

### Steps to Reproduce

1. Install Viaversion/ViaBackwards/Viarewind in BungeeCord
2. Have a 1.18 server in the network
3. Connect to that server with a 1.8 client
4. The error is shown in console

### Expected Behavior

The 1.8 client is able to connect and play on the 1.18 server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [x] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.18--R0.1--SNAPSHOT%3Aab927be%3A462](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.18--R0.1--SNAPSHOT%3Aab927be%3A462-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.1): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.1): 17 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by Camotoy** [comment]
Update ViaRewind: https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/
