### ISSUE TITLE
Error, propably froze server

### ISSUE THREAD

**Issue by kFxDaKing** [ViaVersion/ViaVersion#2758]
### `/viaversion dump` Output

https://dump.viaversion.com/5cacdd00a1730e2dc352b33a98dec8ba0f1704d3b0d8984f995a3cadba7a91a2

### Console Error

```
[Put the paste.gg link or text here.](https://paste.gg/p/anonymous/3545aea6a098439fa6fd9013d3499db4)
```

### Bug Description

Not sure what happend, something froze 20 tps server.

### Steps to Reproduce

No idea how to reproduce.

### Expected Behavior

Fix that issue

### Additional Server Info

I have proxy, lobby, oneblock, caveblock, it happend on caveblock.

ViaVersion and ViaBackwards are on spigot servers.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Airplane--87%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Airplane--87%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square) </br>![ViaBackwards(4.1.0): 11 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.0)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>
