### ISSUE TITLE
Bungee-Multiple errors connecting with 1.18 in a 1.17 lobby

### ISSUE THREAD

**Issue by Stellrow** [ViaVersion/ViaVersion#2759]
### `/viaversion dump` Output

https://dump.viaversion.com/bb6cb6d617df2f3d4f8d0a9efdbb5e0ece616a62d0443b0b8b26944da5ebd126

### Console Error

Warning received
https://paste.gg/p/anonymous/7c465aeb3ddb408db3a82bc49dc355b8
Error following when joining a 1.18 server
https://paste.gg/p/anonymous/d7a9e28934f04a0cb8d6cd34d1285b2a

### Bug Description

Joining with 1.18 in a 1.17 lobby server

### Steps to Reproduce

1.Have a Bungeecord network setup with a 1.17 lobby
2.Join the bungee using a 1.18 client

### Expected Behavior

No errors/warnings to be shown

### Additional Server Info

We are using Bungeecord with the Aegis protection plugin

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: Aegis%20fork](https://img.shields.io/badge/Platform-Aegis%20fork-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
We don't support Aegis. Your Bungee doesn't support the version ViaVersion is built with.
