### ISSUE TITLE
Kicked in 1.8.9 client on 1.12.2 server

### ISSUE THREAD

**Issue by Twiz0x** [ViaVersion/ViaVersion#2760]
### `/viaversion dump` Output

https://dump.viaversion.com/66de3379b925da1915b24c22159bddc50a992d5f08e640fde7e6d57b44d8bc59

### Console Error

```
[Put the paste.gg link or text here.](https://paste.gg/p/anonymous/6779deaa79384a29a3f65335d790c571)
```

### Bug Description

When I join the 1.12.2 server in 1.8, I got kicked with an error.

### Steps to Reproduce

1. Do a server with paperspigot 1.12.2
2. Put Viaversion, viabackward and viarewind
3. Join in 1.8 (for me 1.8.9 lunarclient)
4. Load a chunk not loaded by walking a bit
5. Get kicked with an error

### Expected Behavior

Playing in 1.8 on 1.12.2 server

### Additional Server Info

FastAsyncWorldEdit only

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1618%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1618%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.1): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.1): 17 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by Twiz0x** [comment]
https://dump.viaversion.com/a3f3b1347c5a12b1ef1d6ee57c3d0ed3ec44692a06e1c605669aa356a4f2db9d

Tested with the last viaversion build, it's the same

**Comment by kennytv** [comment]
https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/

**Comment by Twiz0x** [comment]
thanks
