### ISSUE TITLE
Fix Arm_Animation and "Attack Packet" 's Order

### ISSUE THREAD

**Issue by dianwangwin** [ViaVersion/ViaVersion#2763]
### Problem Description

1.9 + 's packet order is different with 1.8.x's
So i wonder if it can be fixed

### Solution Description

force send an animation packet after attack packet

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Follow the proper issue template.

**Comment by MWHunter** [comment]
please don't change the order of packets - it will cause issues with anticheats that expect packets to arrive in the correct order based on client version.
