### ISSUE TITLE
1.18 Heads

### ISSUE THREAD

**Issue by EvilSlime** [ViaVersion/ViaVersion#2764]
### Problem Description

On my 1.17 server, for 1.18 clients the placed heads are all Alex heads. 

### Solution Description

Not sure?

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
See the issue template.
