### ISSUE TITLE
1.18 world height 

### ISSUE THREAD

**Issue by fulcanelly** [ViaVersion/ViaVersion#2767]
### Problem Description

It's impossible to see what is beyond 0 height in older than 1.17 versions and if you try to walk in there you'll stuck 

### Solution Description

The only solution I see is just lie about actual height: split server height into parts and then based on which part player located in adjust each block position do it fits into 0-256 limit.

#### Example
For simplicity we have two part (-64, 128) and (128, 320)
So, when player is beyond 128 each block height mapped by +128 and when above - vice versa  

#### Problem
Now we should choose between lag and visible blocks 
there more part we get -- the more we can see but more lag we get  

But regardless I think better got something than just bugged void

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
That's not going to happen unless someone has a few weeks of no work and high motivation; see the warning ViaBackwards provides or use newer clients

**Comment by fulcanelly** [comment]
I would try but it's hard to grasp Via's insides 

Is there any contribute guide or explanation how Via arranged ?  

Or the only way to understand it is just read whole code ?
Then what I be better should start of ?

**Comment by kennytv** [comment]
Unless you're already familiar with how teleportation and world state changes work on a packet level, there's not much use in trying. If someone delivers a reasonable concept of such an implementation, we'd consider letting outside contributors do it, but only then. If you need help with the code base, it's best to join our Discord

**Comment by brebathe** [comment]
You could try this, when they reach the height limit for their version, you could try to move the blocks down on their end, or tell the client that they are moving to another world and send the blocks from their height limit to the servers height limit.
