### ISSUE TITLE
Console being spammed by ViaVersion - No light Data issue

### ISSUE THREAD

**Issue by Robotv2** [ViaVersion/ViaVersion#2768]
### `/viaversion dump` Output

https://dump.viaversion.com/42dd90d37204dcef5f1212cfb4e9ac2327f00cfd8a10bd4ab829ee69823ecc0b

### Console Error

```
https://pastebin.com/aXVKqfX4
```

### Bug Description

My server is using PufferFish version 1.17.1

Whenever a player try to connect with a 1.18 client and just walking and enterring in chunks, the console get spammed by the message as follows in the pastebin.com. 

Nothing change apart from that, the server runs normally.
This only happened with 1.18 client on 1.17.1 server. 
This issue also happened when trying with viaversion 4.1.0, 4.1.1 and 4.1.2 latest build. 

### Steps to Reproduce

1. Connect with a 1.18 client on a 1.17.1 server
2. Walk or fly around a little bit
3. Check console

### Expected Behavior

Not getting the console spammed. 

### Additional Server Info

I use WaterFall but with ViaVersion directly on the server and not the proxy. 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--14%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Pufferfish--14%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.1.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
You have a plugin sending chunk data before light data; figure out which one it is and report that as incorrect behavior to them. That's usually oreobfuscation or farther viewdistance plugins.
