### ISSUE TITLE
viaversion bug when connecting with launcher version 1.8 with viarewind

### ISSUE THREAD

**Issue by iSeitan** [ViaVersion/ViaVersion#2769]
### `/viaversion dump` Output

https://dump.viaversion.com/6dc4ce59d87b079e9255064c3c69486773ac4151506941526ba4bd8cd1525bd8

### Console Error

[```
Put the paste.gg link or text here.
```
](https://pastebin.com/rTjPszrg)

### Bug Description

disconnect user and spam an error in console

### Steps to Reproduce

1. use a launcher 1.8
2. use version viabackwards 4.1.1 snapshot
3. use version viarewind 2.0.2 snapshot
3. use version viaversion 4.1.1 snapshot
4. connect and see the disconnect and error

### Expected Behavior

can connect to the server with those plugins and laucher version 1.8

### Additional Server Info

using waterfall on purpur latest version

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1428%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Purpur--1428%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards-Outdated!-red?style=flat-square) </br>
