### ISSUE TITLE
1.12 clients crashing on connect to 1.17 server under proxy

### ISSUE THREAD

**Issue by chrismwiggs** [ViaVersion/ViaVersion#2770]
### `/viaversion dump` Output

https://dump.viaversion.com/16454a6c179b50da564922c0b68b28aaf1445152fc93df2042debea8503ee922

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/1404fc32e96e4393aa1ab4c27f59006c

### Bug Description

When a player tries connecting with 1.12 (to a 1.17 paper/purpur server under waterfall with viabackwards and viaversion on the proxy), they are disconnected this this error. 

### Steps to Reproduce

Open 1.12
Join play.thelastblockbender.com
/warp survival to join the 1.17 survival server

### Expected Behavior

Shouldn't crash, of course!

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A866a450%3A468](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A866a450%3A468-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards-Outdated!-red?style=flat-square) </br>
