### ISSUE TITLE
Protocol1_13_1To1_13_2 IN REMAP OF ENTITY_METADATA (0x3F) 

### ISSUE THREAD

**Issue by Leeeaan** [ViaVersion/ViaVersion#2771]
### `/viaversion dump` Output

https://dump.viaversion.com/8ec48362d8cf731fb201eb0e915f94c4588ef47401bba489ee6e38f46f7c5b61

### Console Error

```
[Put the paste.gg link or text here.](https://paste.gg/p/anonymous/9cfb8c2d8450443ca48e492d4692651c)
```

### Bug Description

playing with a player with a version lower than 1.17 causes them to crash

### Steps to Reproduce

1. Login with a version lower 1.17 client
2. join a game of bedwars
3. wait until the game starts
4. as soon as the game starts, crashes

### Expected Behavior

That users who are in versions 1.8.x-1.17.x can play

### Additional Server Info

AuthMe
ClashWars
ChatLab
ConditionalEvents
Essentials-X
FastLogin
LuckPerms
Multiverse-core
PlaceHoldersAPI
SkinRestorer
TAB
Vault
ViaBackwards
ViaRewind
ViaVersion
WorlEdit
WorlGuard
Znpc-servers

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--391%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--391%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards-Outdated!-red?style=flat-square) </br>![ViaRewind(2.0.2): 2 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>
