### ISSUE TITLE
Viaversion Bungee Kicks 1.18.1 players on 1.17 servers

### ISSUE THREAD

**Issue by diamkil** [ViaVersion/ViaVersion#2772]
### `/viaversion dump` Output

https://dump.viaversion.com/cda5e164f7b057df1b6b8b85ff9f953be46ba5d32cc90822363555169f113d87

### Console Error

https://paste.gg/p/anonymous/10828459d1554bb1a5821ae0efe44fb3

### Bug Description

Players connecting with 1.18 via bungeecord to a 1.17.1 server get kicked out
https://i.dkil.ca/20211215140803.png

### Steps to Reproduce

Install Viaversion/ViaBackward/ViaRewind on bungeecord
Add a 1.17.1 paper server to bungeecord (it does not have ViaVersion installed)
Connect to the server via bungeecord

### Expected Behavior

Should work without a single issue

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A425ee4e%3A1618](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A425ee4e%3A1618-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 3 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.1): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
You have a plugin sending bad metadata.

**Comment by kennytv** [comment]
Or uh, nevermind? Likely setup related, I'd suggest joining our Discord to be able to narrow it down

**Comment by diamkil** [comment]
For anyone finding this, I had forgotten to remove ProtocolSupport from the backend server
