### ISSUE TITLE
ViaVersion cannot resolve versions sometimes

### ISSUE THREAD

**Issue by AoElite** [ViaVersion/ViaVersion#2775]
### `/viaversion dump` Output

https://dump.viaversion.com/4e3879e0274b256c66efef03b461c4026bde73a10890aaa087a1fba90af35805

### Console Error

There's no errors in console.

### Bug Description

Whenever a player joins the server ViaVersion will randomly not resolved their version.

Image: https://a.pomf.cat/sgsxfu.png
Also can confirm with ViaVersion's API as well.

### Steps to Reproduce

1. Login with any version
2. Sometimes ViaVersion cannot resolve your version

### Expected Behavior

ViaVersion should be able to resolve your version.

### Additional Server Info

Velocity with just Luckperms. ViaVersion is NOT running on Velocity.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--%224ac995a%22%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--%224ac995a%22%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.2-SNAPSHOT): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.2--SNAPSHOT)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
We don't support custom server forks, it's likely either related to that or some other plugin scewing data

**Comment by AoElite** [comment]
It's my fork of latest 1.17.1 paper and it changes nothing that could effect this.
