### ISSUE TITLE
Transaction/Pong packet not working for 1.16.5 clients

### ISSUE THREAD

**Issue by AoElite** [ViaVersion/ViaVersion#2776]
### `/viaversion dump` Output

https://dump.viaversion.com/4e3879e0274b256c66efef03b461c4026bde73a10890aaa087a1fba90af35805

### Console Error

No console errors.

### Bug Description

Server is running paper 1.17.1. If try sending a transaction/pong packet to a 1.16.5 player they will not respond with one.

### Steps to Reproduce

1. Start a 1.17.1 server
2. Join on a 1.16.5 client
3. Send a Transactions/Pong packet to a player
4. Client will not respond, but will if you join on a 1.17+ client

### Expected Behavior

Transaction packets should work for 1.16.5 players

### Additional Server Info

Velocity

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--%224ac995a%22%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--%224ac995a%22%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.2-SNAPSHOT): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.2--SNAPSHOT)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
https://github.com/ViaVersion/ViaBackwards/blob/249280312e6926572ff41e55dc74f292b8f0ea80/common/src/main/java/com/viaversion/viabackwards/ViaBackwardsConfig.java#L83
