### ISSUE TITLE
Wall blocks are remapped wrongly

### ISSUE THREAD

**Issue by RaphiMC** [ViaVersion/ViaVersion#2777]
### `/viaversion dump` Output

https://dump.viaversion.com/93f138587b9dbf60acd422c66935117336738b2f4ba62429bc3dd8e2925acd33

### Console Error

No error

### Bug Description

Wall block are remapped wrongly. I think its a 1.16 -> 1.15.2 change.
Here is an image comparing 1.18.1 and 1.12.2. Server version is 1.12.2.
![grafik](https://user-images.githubusercontent.com/50594595/146654713-7bf5925f-3afc-4436-8c74-4958c94ce9a0.png)

### Steps to Reproduce

1. Login with 1.12.2 on spigot 1.12.2 sevrer.
2. Join with 1.18.1 client
3. Place wall blocks and rejoin

### Expected Behavior

Correct wall block mappings (small/low wall blocks instead of tall ones)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Spigot--642f6d2--57ab4cf%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Spigot--642f6d2--57ab4cf%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.1.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Won't fix, new states have been added and a 1 to 1 translation isn't possible/requires blockconnection level hacks
