### ISSUE TITLE
Memory leak i guess

### ISSUE THREAD

**Issue by Askarionn** [ViaVersion/ViaVersion#2778]
### `/viaversion dump` Output

https://dump.viaversion.com/0fac439b75609cc3f9b54b51f130316a5d345c6d797ed0f445a1fa0d0d738e6e

### Console Error

```
https://cdn.discordapp.com/attachments/316208160232701955/922316670104657960/unknown.png
https://cdn.discordapp.com/attachments/316208160232701955/922316728753602691/unknown.png
https://cdn.discordapp.com/attachments/316208160232701955/922316828900991016/unknown.png
```

### Bug Description

-

### Steps to Reproduce

-

### Expected Behavior

-

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--NachoSpigot--%22be07467%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--NachoSpigot--%22be07467%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by MedicOP** [comment]
Got the same problem when using `serverside-blockconnections` on `packet` mode. I'm guessing the connection storage is never cleared so it keeps getting bigger and bigger over time until you run out of memory.

And the `reduce-blockstorage-memory` option disables exactly the blocks that I want to have connected (fences, panes, iron bars)

![Screenshot_1](https://user-images.githubusercontent.com/18251099/149435679-7a398346-4b6e-48b2-b5bc-9668dc3bd51c.png)

**Comment by Askarionn** [comment]
Other heapdump, with 0 players
https://imgur.com/a/mQC63NW

**Comment by Askarionn** [comment]
https://we.tl/t-4UUTYW97dO
