### ISSUE TITLE
Can't use middle clicking on my 1.17.1 server using 1.18/1.18.1 version of minecraft

### ISSUE THREAD

**Issue by tyepavitt** [ViaVersion/ViaVersion#2779]
### `/viaversion dump` Output

https://dump.viaversion.com/e6f142e768de9b33610dbc6cf05330f45a4fbd164a200e8db2138e3a79f68a04

### Bug Description

when I join my 1.17.1 server using minecraft 1.18/1.18.1 and try to use the middle clicking feature for my command panels gui it doesn't register. I tested it out when joining the server on 1.17.1 and it works correctly.

### Steps to Reproduce

1. Have a 1.17.1 server with command panels, viaversion, viarewind and viabackwards installed
2. Create a panel which has a middle clicking tag (Mine runs a command on middle click)
3. Launch minecraft on 1.18 or 1.18.1
4. Join the 1.17.1 server and try to use the middle clicking

### Expected Behavior

Be able to use middle clicking when joining a 1.17.1 server with 1.18/1.18.1.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--402%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--402%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 4 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.1): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by RaphiMC** [comment]
Can confirm, but most likely not fixable, as the mostly 1.18 client does not send middle clicks in survival anymore (as they were not used by anything and are now only sent in creative)

**Comment by kennytv** [comment]
Won't fix, see above and https://bugs.mojang.com/browse/MC-46584
