### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wiktorkush** [ViaVersion/ViaVersion#2780]
### `/viaversion dump` Output

https://dump.viaversion.com/42f9113dc60bc5526a13ccf4ed7e20abb5a653d1e1b379ae15e0467eb1395c8e

### Console Error

```
Put the paste.gg link or text here.
```
18:40:13 [INFO] [wiktorkush] disconnected with: EncoderException : com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template {Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.EntityPackets1_17$2 (Anonymous)} Actual Error:  @ io.netty.handler.codec.MessageToMessageEncoder:104

### Bug Description

18:40:13 [INFO] [wiktorkush] disconnected with: EncoderException : com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template {Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.EntityPackets1_17$2 (Anonymous)} Actual Error:  @ io.netty.handler.codec.MessageToMessageEncoder:104

### Steps to Reproduce

18:40:13 [INFO] [wiktorkush] disconnected with: EncoderException : com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template {Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.EntityPackets1_17$2 (Anonymous)} Actual Error:  @ io.netty.handler.codec.MessageToMessageEncoder:104

### Expected Behavior

18:40:13 [INFO] [wiktorkush] disconnected with: EncoderException : com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template {Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.EntityPackets1_17$2 (Anonymous)} Actual Error:  @ io.netty.handler.codec.MessageToMessageEncoder:104

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A425ee4e%3A1618](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A425ee4e%3A1618-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 4 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.1): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
Update to ci builds. If the error still occurs, paste the *full* error properly
