### ISSUE TITLE
[SUGGESTION] sending a message to players on specific versions

### ISSUE THREAD

**Issue by Minecon724** [ViaVersion/ViaVersion#2781]
### Problem Description

please add an option to send a customized message to players on specific versions
for example when the server is 1.8 and player is using 1.18, we can send a message that they wont get the best pvp experience

### Solution Description

h

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Minecon724** [comment]
feature request ^

**Comment by Jo0001** [comment]
Just use the ViaVersion API https://viaversion.atlassian.net/wiki/spaces/VIAVERSION/pages/54067250/Basic+API+usage
There might be also some 3rd party plugins which already do sth like that

**Comment by FormallyMyles** [comment]
See above, there are plugins like on the lines of ViaCheckConnection which do this

**Comment by Bobcat00** [comment]
Sham less plug for my ViaVersionStatus plugin which does this.
https://www.spigotmc.org/resources/viaversionstatus.66959/

**Comment by Minecon724** [comment]
> Shameless plug for my ViaVersionStatus plugin which does this. https://www.spigotmc.org/resources/viaversionstatus.66959/

thanks!
