### ISSUE TITLE
Java Version

### ISSUE THREAD

**Issue by Snowbelldog** [ViaVersion/ViaVersion#2782]
### `/viaversion dump` Output

https://dump.viaversion.com/4c968ce17c5ca71d4fd5c5ad2769ba1a334bcc3dff9b40690d5adf9bff76e699

### Console Error

[ViaVersion] You are running an outdated Java version, please consider updating it to at least Java 17 (your version is 16). At some point in the future, ViaVersion will no longer be compatible with this version of Java.

### Bug Description

A Paper 1.16.5 server can only run with Java 16. But ViaVersion says, that soon only Java 17 will be supported.

### Steps to Reproduce

1. Put Plugin on 1.16.5 Server
2. Error on Start in Console

### Expected Behavior

If I want to start a 1.16.5 server I cannot use Java 17. I thought ViaVersion noticed that myself.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--794%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--794%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.1): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
That's not an error, and 1.16 can also run using Java 17 using Paper's startup flag to disable the arbitrary Java version check Spigot adds; `-DPaper.IgnoreJavaVersion=true`

**Comment by Kichura** [comment]
> That's not an error, and 1.16 can also run using Java 17 using Paper's startup flag to disable the arbitrary Java version check Spigot adds; `-DPaper.IgnoreJavaVersion=true`

Throwing in an additional comment for this: 

If some plugins will start breaking with this switch enabled then expect unforeseen consequences to happen, otherwise it hopefully should run just fine without too many problems happening at once.

**Comment by Snowbelldog** [comment]
Thank you very much, unfortunately I didn't know that.

**Comment by Bobcat00** [comment]
You are running an outdated Java version... You are running a development version of the plugin... No light data found for chunk...

Myles is becoming quite the nag recently.
