### ISSUE TITLE
NullPointer upon join

### ISSUE THREAD

**Issue by iFlyinq** [ViaVersion/ViaVersion#2786]
### `/viaversion dump` Output

https://dump.viaversion.com/f372f9ea12ef371e495a076564bdd7bec8cabc2400d9df7af1aaf73447fbeb14

### Console Error

https://paste.gg/p/anonymous/416cf5915deb45b8a638524378c30a74

### Bug Description

When a player joins, I get that null pointer each time

### Steps to Reproduce

Join a proxy with the latest via version (beta-build) on it. 

### Expected Behavior

No error at all ;) 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ATravertine--Bootstrap%3A1.16--R0.5--SNAPSHOT%3Afd9bd60%3A191](https://img.shields.io/badge/Platform-git%3ATravertine--Bootstrap%3A1.16--R0.5--SNAPSHOT%3Afd9bd60%3A191-3498db?style=flat-square) </br>![ViaVersion (4.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.1.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Update Bungee

**Comment by iFlyinq** [comment]
> Update Bungee

Can I use ViaRewind with updated Waterfall to support of 1.7?

**Comment by kennytv** [comment]
No, but Velocity is a proxy that supports 1.7-1.18
