### ISSUE TITLE
Error players with 1.8 cant join

### ISSUE THREAD

**Issue by RajFREAKZ** [ViaVersion/ViaVersion#2787]
### `/viaversion dump` Output

https://dump.viaversion.com/ee5b436561297196c5dc7c9bc37aa3e5b63a411b2a57c62e6d93887130af0021

### Console Error

Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viabackwards.protocol.protocol1_13_1to1_13_2.packets.EntityPackets1_13_2$3 (Anonymous)}

### Bug Description

people cant join with 1.8 and 1.7

### Steps to Reproduce

join with 1.8 and get kicked

### Expected Behavior

whenever someone tries to join with 1.8 thsi comes

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--400%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--400%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards-Outdated!-red?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind-Outdated!-red?style=flat-square) </br>

**Comment by Kichura** [comment]
Update your via* plugins to the CI builds as it is doubtful that you have tested it with those versions at all,
If it persists then assuming it is a plugin sending bad metadata.
