### ISSUE TITLE
Can't join on 1.18

### ISSUE THREAD

**Issue by chirpthetwerp** [ViaVersion/ViaVersion#2789]
### `/viaversion dump` Output

https://dump.viaversion.com/865ca5f492200e51240d5082bcae56787944b68aebc4bdeea748d06ae19134c1

### Console Error

```
https://ghostbin.com/yUnQl/raw

Sorry could not use paste.gg as it didn't load
```

### Bug Description

When someone joins on 1.18, the server gives them the error "Disconnected" and does not allow them to join

### Steps to Reproduce

Login to the server with a 1.18 client

### Expected Behavior

Expected the player to be able to join

### Additional Server Info

I use no Proxy. I have 4 Custom Coded plugins but removing them does not fix the issue.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
Either the gravity or parkour plugin is sending bad metadata - causing server to break entirely, disable one or both of them and see if the issue persists.

**Comment by chirpthetwerp** [comment]
> Either the gravity or parkour plugin is sending bad metadata - causing server to break entirely, disable one or both of them and see if the issue persists.

I removed every plugin besides ViaVersion and I'm still getting the issue.

**Comment by Kichura** [comment]
> > Either the gravity or parkour plugin is sending bad metadata - causing server to break entirely, disable one or both of them and see if the issue persists.
> 
> I removed every plugin besides ViaVersion and I'm still getting the issue.

Okay, can you test via* on a clean 1.12.2 (or greater version) server aswell, otherwise this likely needs to be checked further.

**Comment by chirpthetwerp** [comment]
> > > Either the gravity or parkour plugin is sending bad metadata - causing server to break entirely, disable one or both of them and see if the issue persists.
> > 
> > 
> > I removed every plugin besides ViaVersion and I'm still getting the issue.
> 
> Okay, can you test via* on a clean 1.12.2 (or greater version) server aswell, otherwise this likely needs to be checked further.

works fine on 1.12.2

**Comment by kennytv** [comment]
You have a broken mappings file or corrupted jar
