### ISSUE TITLE
Modify outgoing packets

### ISSUE THREAD

**Issue by Rapha149** [ViaVersion/ViaVersion#2790]
### Problem Description

It's not really a feature request, but I didn't know what to choose instead, so here's my problem:
As of the new fog in 1.18 (the view distance is now handled by the server, not by the client) I wrote a plugin that modifies the login packet and sends a higher view distance to the client so that the fog is further away. Now, someone suggested to me to also support older versions so that players with 1.18 clients (which works with ViaVersion obviously) also don't have the fog. My problem is that I couldn't figure out how to modify the packet after ViaVersion modified it. Is there a way to do so? 

### Solution Description

Yeah, as I said, this isn't a feature request so I will just leave this like this.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
You can't without adding your own netty channel handlers, since Via is designed to make the server 100% unaware of the client being on a different version

**Comment by Rapha149** [comment]
Adding handlers to the player's pipeline you mean? Because I'm already doing that but I can't figure out where to add the handlers in order for them to be after Via's handlers and being able to modify the view distance.
