### ISSUE TITLE
Add config item to disable "No light data found..." message

### ISSUE THREAD

**Issue by Bobcat00** [ViaVersion/ViaVersion#2791]
### Problem Description

I got an explanation from the Orebfuscator developers of how they think the light data problem is occurring:

> Problem is that we don't touch the light packets, we only work with chunk packets. But chunk packets are handled async which means they are sent independently of the light packets... What probably happens is the following:
> 1. server sends light
> 2. sever sends chunk
> 3. _orebfuscator starts processing chunk packet_
> 4. server sends unload chunk
> 5. _orebfuscator sends processed chunk packet_
>
> This would cause ViaVersion to store the light data and delete it on chunk unload. Which in turn causes the delayed chunk packet to not contain any light data. Since the chunk is already unloaded this shouldn't cause any problems for your players but the error will remain.

### Solution Description

Add an item in the config file to disable the "No light data found for chunk at... Chunk was already loaded..." warning message.

### Alternatives

The Orebfuscator developers say they would have to delay the chunk unload if a chunk is still processing, which to me sounds like it could cause more problems than it would solve.

Issue on Orebfuscator's Github: https://github.com/Imprex-Development/Orebfuscator/issues/165#issuecomment-1003389772

### Additional Info

Problem occurs with 1.18.x clients on a 1.17.1 server.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Bobcat00** [comment]
> ![Error: Invalid or missing dump](https://camo.githubusercontent.com/d52699b4f8c5e7e91cb92ecd59b5aa5ed2f9eb37e741b87aa9334b5e364c0512/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4572726f722d496e76616c69642f6d697373696e6725323064756d702d7265643f7374796c653d666c61742d737175617265)

This is a feature request.

**Comment by Bobcat00** [comment]
Looking at this further, it seems this could be controlled by the `suppress-conversion-warnings` config entry.
