### ISSUE TITLE
Add BedRock support 

### ISSUE THREAD

**Issue by Gamer101233** [ViaVersion/ViaVersion#2796]
### Problem Description

Everytime me or a friend joins using our new cross support viaversion blocks our connection from coming into the server.

### Solution Description

I would like to see this plugin add bedrock, xbox, PE support so players can join my server using cross platform and join my server with the version that bedrock and other consoles use.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by LegacyGamerHD** [comment]
Use geyser

**Comment by Gamer101233** [comment]
> Use geyser

i am using geyser and floodgate 

all i get disconnected with  is 

Kicked whilst connecting to lobby: Outdated client! Please use 1.18.1

now that is happening both on java and bedrock 

viaversion needs to be redone fully because anything lower than 1.18.1 in java edition wont connect im trying to connect with 1.17.1 this plugin needs to get fully redone

**Comment by Gamer101233** [comment]
nevermind even 1.18.1 kicks me with the same message because viaversion was scripted super horribly

**Comment by Gamer101233** [comment]
never

**Comment by Gamer101233** [comment]
found the issue was outdated on a few plugins
