### ISSUE TITLE
1.18 World Height Workaround

### ISSUE THREAD

**Issue by xIcee** [ViaVersion/ViaVersion#2797]
### Problem Description

As of 1.18, the world height does not fully work with versions 1.16-. I was checking the issues, and saw some requests, but I think I have a _someone_ idea on how to fix this. (hopefully)

### Solution Description

You could change what sections of the world are loaded, like from **0-256** to **-64-192**, or **64-319** through multiple worlds overlapping at parts, and change which worlds the player loads after certain Y levels. For example, if you make it to Y64, it changes your world to the **-64** one, or making it to Y192 changes to **319** world.

### Alternatives

Of course, if this seems too far over you guys' heads, just put a bedrock barrier at Y0 for 1.16- players. The glitched void is really troublesome, especially for more stubborn players, who don't want to change versions.

### Additional Info

I have no clue how hard this would be to implement, but this is just how my brain would try to solve the problem. Thanks for reading this.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Sorry, the effort required wouldn't be worth the trouble, since you would have to remap a lot of other data sent to the now offset world
