### ISSUE TITLE
 Protocol1_13To1_13_1 IN REMAP OF CHUNK_DATA (0x22)

### ISSUE THREAD

**Issue by altzv** [ViaVersion/ViaVersion#2798]
### `/viaversion dump` Output

https://dump.viaversion.com/1a80ecc449397f25bde48c6e60acd8d7b4e3a304d63fa799ebae92b5fe6da6dd

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/5162414cfd004a69bdd3b93c3153d53f

### Bug Description

When a player join the server and he is at spawn, he either instantly crashes or after passing 5 - 10 blocks
Server version - Paper 1.13.2

### Steps to Reproduce

1. Login with versions 1.12.2 - 1.16.5 (not including 1.13.2)
2. Walk 5 - 10 blocks
3. Game crash

Or

1. Login with versions 1.12.2 - 1.16.5 (not including 1.13.2)
2. Game crash

### Expected Behavior

I expect users from 1.12.2 -1.16.5 (not including 1.13.2) can play on the server

### Additional Server Info

AuthMe
LuckPerms
ViaBackwards
ViaVersion
Multiverse-core
PlaceHoldersAPI
SkinRestorer
TAB
Vault
Essentials-X
WorlEdit
WorlGuard
MyCommand
Citizens2
CommandCitizens

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [ ] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--657%20%28MC%3A%201.13.2%29](https://img.shields.io/badge/Platform-git--Paper--657%20%28MC%3A%201.13.2%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 14 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-14%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.1): 8 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by altzv** [comment]
![bug](https://user-images.githubusercontent.com/95023955/149793769-c09c59a4-85f9-4904-a8f3-ae34fb711571.png)

**Comment by kennytv** [comment]
You have a plugin sending bad chunk data - could be because of using plugman, usual culprits are old versions of SkinsRestorer or FAWE.
