### ISSUE TITLE
Buggy Inventory for 1.16.5

### ISSUE THREAD

**Issue by JacksaYT** [ViaVersion/ViaVersion#2799]
### `/viaversion dump` Output

https://dump.viaversion.com/ec8d3326b4169c512001968c3753e4e608860c088870ff4ef27cdfa49962e558

### Console Error

https://ctrlv.tv/zi6h

### Bug Description

Hey there is a big bug with the Inventory on version 1.16.5 Every player has shadow buging Items in the inventory when moving the Items in Inventory. Right now we use 1.17. paper for it.

### Steps to Reproduce

fix

### Expected Behavior

items should not get duplicated 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--%22cc43ba7%22%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--%22cc43ba7%22%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 14 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-14%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.1): 8 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
https://github.com/ViaVersion/ViaBackwards/issues/389
