### ISSUE TITLE
ERROR IN Protocol1_15_2To1_16 IN REMAP OF CHUNK_DATA (0x21)

### ISSUE THREAD

**Issue by Veseon** [ViaVersion/ViaVersion#2801]
### `/viaversion dump` Output

https://dump.viaversion.com/cc29d00980a7f283cbeb553fd888a8a2f20e0e29a9c976df76fb4a12385d5392

### Console Error

```
https://paste.gg/p/anonymous/9fb1d5095fae4ae7af4bf466e65e0792
```

### Bug Description

Logging into a 1.18.1 server using a custom generated world on a 1.8.9 client throws an internal exception and disconnects the player.

### Steps to Reproduce

1. Generate a custom world with world_settings.json or level.dat provided in attachements.
2.  Log in to the server (1.18.1) using a 1.8.9 client.
3. Throws an internal exception and disconnects the player

[level.zip](https://github.com/ViaVersion/ViaVersion/files/7917587/level.zip)
[world_settings.zip](https://github.com/ViaVersion/ViaVersion/files/7917588/world_settings.zip)

### Expected Behavior

No internal exception should occur and the player should successfully connect to the server.

### Additional Server Info

Using Velocity 3.1.2-SNAPSHOT (git-b8f1df44-b110) as a proxy server with BungeeGuard forwarding mode, no plugins.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1522%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-git--Purpur--1522%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.2.0-22w03a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.2.0--22w03a--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>![ViaBackwards(4.2.0-22w03a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.2.0--22w03a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
