### ISSUE TITLE
Error/warn on shutdown of server

### ISSUE THREAD

**Issue by TheJoshue** [ViaVersion/ViaVersion#2802]
### `/viaversion dump` Output

https://dump.viaversion.com/346b544e6c2fcbffedb6809d1e40e289784005131aefb164f8c859f750b277fd

### Console Error

https://paste.gg/p/anonymous/b75e1a5eb3ba427a8fa664a2c7e340dd

### Bug Description

Happens on shutting down PaperMC 1.16.5 (latest build from legacy downloads - build794) server.

### Steps to Reproduce

1. Start server.
2. Do whatever.
3. Stop server.

* Note: This happens only sometimes.

### Expected Behavior

Should not throw this error/warn(?)

### Additional Server Info

ubuntu18.04
java17
paper-1.16.5

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--794%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--794%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 14 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-14%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 5 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.1): 10 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-10%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
Don't replace the jar while the server is running / you have a corrupted jar

**Comment by TheJoshue** [comment]
> ![Platform: git--Paper--794%20%28MC%3A%201.16.5%29](https://camo.githubusercontent.com/6ba6ed39b396f22e67893c32d3ee5fc9101f7a6b2927b0d4f95afde222338bdf/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d50617065722d2d3739342532302532384d43253341253230312e31362e352532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.1.1): 14 commits behind master](https://camo.githubusercontent.com/999bd5dd7a25113f8d831e7b0878b3cd806c1416e63d669eadaf91166c4b3a98/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e312e31292d3134253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaRewind(2.0.2): 5 commits behind master](https://camo.githubusercontent.com/e94bf3664e84f585b1c9ecd165be6c7f2d71c10a8f16a5a48676c9b9fdfad0b7/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f566961526577696e6425323028322e302e32292d35253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaBackwards(4.1.1): 10 commits behind master](https://camo.githubusercontent.com/47568f849fc989f45746c3a99c2291ebb3e4435dad5a4d1b60c799985745a521/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e312e31292d3130253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265)

of course
i tested this with current builds and still happens
i switched to latest dev builds and still happens
i switched to spigot builds and reported here



> Don't replace the jar while the server is running / you have a corrupted jar
i don't ever do this neither use plugin to unload plugins, i do server stop and then update stuff

**Comment by TheJoshue** [comment]
thoughts?
and why closing this so early

**Comment by kennytv** [comment]
I can't tell you why it is broken, but the error you provided means exactly that; your jar file has someone been corrupted and that is for you to solve. Could be short connection losses when uploading/downloading, early aborts, reloads, the server not loading them properly, a bad host

**Comment by TheJoshue** [comment]
ok i have much respect to you for developing this plugin but you're basically saying here that i am either stupid or not careful enough
Would i be able to provide this detailed report if i was not careful and not track down everything this report wanted?
i hope you don't think i'm that much stupid (i don't actually think you want to say that, i just answer to your answer)

i replaced .jar few days ago, this happened again, i don't have errors with any other .jar and i have on avg ~100 plugins (part of them is disabled by renaming `.jarr`) * XX servers (can't say how much but it's 2 digits) and i am having corrupted jar...

Ok thank you for your answer, i'll ignore this and let know if anything bigger happens.

Again, thanks.

**Comment by kennytv** [comment]
I'm not saying you're stupid, I'm not even saying it's really your fault. It could be anything for all I know; the setup, the file system, Paper, or another plugin, there's just no way that we can help you figure out what it actually is. Ofc there's a chance this would somehow be related to Via class loading, but based on previous (or not existing) reports and you getting the error *repeatedly* makes this highly unlikely
