### ISSUE TITLE
Error connecting to Limbo server

### ISSUE THREAD

**Issue by Seceroth** [ViaVersion/ViaVersion#2804]
### `/viaversion dump` Output

https://dump.viaversion.com/801cae00727014c9613712198493c081d9e85ac9bbd92e2041c9c26ae1197b39

### Console Error

https://gist.githubusercontent.com/Seceroth/bf46e3386e9fe6eeb04800f552c0c3e5/raw/6b17016378a8fc10185a882e9a4a824e7eeb1437/Viaversion%2520error

### Bug Description

Trying to connect to a Limbo server running https://github.com/Nan1t/NanoLimbo does not work. I remember it used to work before, but didn't test joining Limbo when updating stuff to 1.18 from 1.17, so not sure what exactly broke, but it seems to be this mod. Upon further inspection, any client 1.16-1.18 can't connect to Limbo and 1.12-1.15 can connect. This could of course also be an error with NanoLimbo. Will report there if that seems to be the problem.

### Steps to Reproduce

Have a backend hub (paper-1.17) and NanoLimbo server running behind Velocity.
Connect with 1.16+ client, get sent to hub.
Try to join the Limbo server, receive error.

### Expected Behavior

Join the Limbo server like normal.

### Additional Server Info

Running Velocity with LEGACY forwarding. Have a 1.12 server attached.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.1](https://img.shields.io/badge/Platform-velocity%203.1.1-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 14 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-14%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.1): 10 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-10%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
The Limbo plugin would have to use Via API to get the real protocol version of the client if Via is present
