### ISSUE TITLE
Console Improvement: no more custom worlds heights errors

### ISSUE THREAD

**Issue by ilfarpro** [ViaVersion/ViaVersion#2805]
### Problem Description

Every time someone joins from outdated minecraft version I get console error:
```
[Sun, 23. Jan 2022 14:08:54 MSK ERROR] Custom worlds heights are NOT SUPPORTED for 1.16 players and older and may lead to errors!
[Sun, 23. Jan 2022 14:08:54 MSK ERROR] You have min/max set to -64/384
```

### Solution Description

Could you, please, make it warning message instead of error message. It's useful when server console is hooked up with discord channel. Helps to track only important errors and get less notification.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by ilfarpro** [comment]
Also maybe there is some kind of solution to this? I've checked plugin's wiki, no information about it.

**Comment by kennytv** [comment]
Nope, and there likely won't be

**Comment by ilfarpro** [comment]
Thanks for thunder fast reply, you are awesome!
