### ISSUE TITLE
Signs going invisible when placing them on chests

### ISSUE THREAD

**Issue by Sanderhgtf** [ViaVersion/ViaVersion#2806]
### `/viaversion dump` Output

https://dump.viaversion.com/c70bf3778c2f59cdc6bf3a164fc8aacfac0923dcd983953444754a458e98f495

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

The server is running on 1.18, the player experiencing the issue is running on a 1.16 version. 

The player is not able to type anything on the sign as well

The attached file is a video of an player encountering this bug

https://user-images.githubusercontent.com/70511934/150811996-fe24fedb-a491-4bef-b43e-c7340afa964e.mov

### Steps to Reproduce

1. Login with 1.16 into a server that's running on 1.18
2. place a sign on the chest while holding shift

### Expected Behavior

The sign is expected to turn the chest into a chest shop

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--%22f86c79e%22%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-git--Paper--%22f86c79e%22%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 14 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-14%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards-Outdated!-red?style=flat-square) </br>
