### ISSUE TITLE
Often Kick 1.12.2 Player

### ISSUE THREAD

**Issue by AYue2021** [ViaVersion/ViaVersion#2808]
### `/viaversion dump` Output

Falied Dump

### Console Error

https://paste.gg/p/anonymous/45d7d2c2a71d47579cdbdc94dceda7ca

### Bug Description

The 1.12.2 Client Often Play Error

### Steps to Reproduce

Start Paper Server 1.16.5
and use Viaversion ViaBack?????
and Its'BungeeCord
if i use so much command
it's will kick 1.12.2 player

### Expected Behavior

I think it's will fixed

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by AYue2021** [comment]
And the client show [

com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template

 com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.BlockItemPackets1_13$7 (Anonymous)}
   @ io.netty.handler.codec.MessageToMessageEncoder:104


]

**Comment by kennytv** [comment]
You have an item with invalid NBT data somewhere
