### ISSUE TITLE
Kicked when you die

### ISSUE THREAD

**Issue by TASG2012** [ViaVersion/ViaVersion#2809]
### `/viaversion dump` Output

https://dump.viaversion.com/479005189ab74b71f564848fccb887db7ebcfd91a71290747e5f10c64ece9173

### Console Error

[11:34:45 INFO]: GrislyJeans8341 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: ADVANCEMENTS, Type: JsonElement, Data: [Pair{Type|Boolean, false}, Pair{Type|VarInt, 18}, Pair{Type|String, minecraft:adventure/root}, Pair{Type|Boolean, false}, Pair{Type|Boolean, true}], Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$13 (Anonymous), Packet ID: 99}

### Bug Description

You get kicked whenever you die. Pretty simple

### Steps to Reproduce

1. Login in 1.18
2. Die
3. Then you get kicked with the same message

### Expected Behavior

You shouldn't get kicked when you die.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--408%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--408%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 14 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-14%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
Update to ci builds, try without other plugins (specifically Geyser), and if the error still occurs, open a new issue with the new dump and the **full** stacktrace from the console
