### ISSUE TITLE
Place blocks into myself

### ISSUE THREAD

**Issue by MrBIO69** [ViaVersion/ViaVersion#2811]
### `/viaversion dump` Output

https://dump.viaversion.com/ddd44f0217b30446f1993fe8a0d6523d2890b8821673ae4274b367ed0c740c5b

### Bug Description

I can place blocks in myself

### Steps to Reproduce

1. Get block and place it under yourself

### Expected Behavior

I can't place blocks into myself

### Additional Server Info

I use bungeecord, other plugins are in dump

### Checklist

- [ ] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [x] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
See https://github.com/ViaVersion/ViaVersion/issues/1087
