### ISSUE TITLE
Kicking players from logging on

### ISSUE THREAD

**Issue by Thefluffypvper1** [ViaVersion/ViaVersion#2812]
### `/viaversion dump` Output

https://dump.viaversion.com/61eccfc4105b5e2827fa1e2f90c7ac7d0538f41cab01afb773b23d088bbc5f8c

### Console Error

```
[Put the paste.gg link or text here.
](https://bin.jamo.tech/elejegoqaresutik.yaml)```


### Bug Description

When a user tries to connect they get instant disconnect messag:

### Steps to Reproduce

Use 1.8.9
Connect to server with newiest version of Viaversion and you get kicked while connecting with message 
![image](https://user-images.githubusercontent.com/74934708/151668985-09149ad4-af3d-43b8-9806-9a3dc93dce91.png)


### Expected Behavior

Not to be fixed from the server

### Additional Server Info

None

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1_8_R3%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-1_8_R3%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.2.0-22w03a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.2.0--22w03a--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>![ViaRewind(2.0.2): 5 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.1): 11 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
Something is sending bad packet data / we don't support closed source Spigot forks
