### ISSUE TITLE
Unknown console spam

### ISSUE THREAD

**Issue by TenReeez** [ViaVersion/ViaVersion#2814]
### `/viaversion dump` Output

https://dump.viaversion.com/e0596288726964229c7f2a5150210ba59b9f43527870f645fa3f63a57e607e12

### Console Error

https://pastebin.com/ED1xBhb2

### Bug Description

Constant spam of an error in console. (Hub)

### Steps to Reproduce

Im not sure. sorry

### Expected Behavior

NO spam in console

### Additional Server Info

Using a waterfall bungee.
Via version, backwards and rewind on spigot servers only.

versions:
paper 1.18.1
viaversion: 4.2.0-22w03a-snap
viabackwards: 4.1.1
viarewind: 2.0.2

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--175%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-git--Paper--175%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.2.0-22w03a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.2.0--22w03a--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>![ViaRewind(2.0.2): 5 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.1): 11 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
Update ViaBackwards to ci builds. If that doesn't fix it, some plugin is sending bad metadata
