### ISSUE TITLE
ERROR IN Protocol1_13To1_12_2 IN REMAP OF CHUNK_DATA (0x20)

### ISSUE THREAD

**Issue by nuno1212s** [ViaVersion/ViaVersion#2815]
### `/viaversion dump` Output

https://dump.viaversion.com/02e9acd22890e861656207ba7fa3d1d36292c63f23031e6bc1fcaae40122661c

### Console Error

```
https://paste.gg/p/anonymous/75f5a9b22432438f8530eade2de9dfe6
```

### Bug Description

Joining the server causes that error message and disconnects the client.

### Steps to Reproduce

Login with a 1.17.1 client onto a 1.12 server running latest version of viaversion. (Some other versions also have this problem)

### Expected Behavior

Player should have joined successfully

### Additional Server Info

I use velocity with Forceresourcepacks, TCPShield, EpicGuard-velocity and nuvotifier.
Running paper 1.12 latest version.
BungeeTabListPlus_BukkitBridge-3.4.4.jar
ChatControl.jar
Citizens-2.0.27-b2133.jar
CommandNPC-1.9.1.jar
DeluxeChat-1.16.2.jar
DisableJoinMessage.jar
GlowAPI_v1.4.6-SNAPSHOT.jar
Holograms-2.13.jar
HolographicDisplays.jar
LibsDisguises-10.0.21-Free.jar
Multiverse-Core-2.5.jar
MyCommand.jar
NoAnvil.jar
PacketListenerAPI_v3.9.9-SNAPSHOT.jar
PlaceholderAPI-2.10.8.jar
PlugMan.jar
PluginHider%2B%205.2.jar
ProtocolLib.jar
TradePlus-3.76.1.jar
Vault.jar
ViaVersion.jar
WorldEdit.jar
floodgate-spigot.jar
nuvotifier-2.5.3.jar
worldguard-bukkit-6.2.2%20%281%29.jar

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Spigot--79a30d7--f4830a1%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Spigot--79a30d7--f4830a1%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.1.2-SNAPSHOT): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.2--SNAPSHOT)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>
