### ISSUE TITLE
I Place a Spanwner

### ISSUE THREAD

**Issue by Q2OD** [ViaVersion/ViaVersion#2816]
### `/viaversion dump` Output

https://dump.viaversion.com/ea281f1e80ccc82a70312668e2765e23d6c8a5c999757c15fe3624755b8aacde

### Console Error

![report](https://user-images.githubusercontent.com/99100452/152660460-ade5b11f-365f-42d8-88f2-ddfbb6388406.PNG)

### Bug Description

I was just going to test a boat spawner with essanitals and I placed the spawner and it crashed my server

ps grammer and spelling not good

### Steps to Reproduce

1. Get Spawner
2. Place Spawner
3. It Crashed

### Expected Behavior

I just crashed

### Additional Server Info

I am using minehut/paper

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [ ] If applicable, I have included a paste (**not a screenshot**) of the error.
- [ ] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--408%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--408%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 15 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-15%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
If possible use ci builds and if it still happens, open a new issue with the full console error. If you can't use ci builds, you'll have to wait for the next release
