### ISSUE TITLE
Error while connecting to a 1.17 server using a 1.17 client with Velocity

### ISSUE THREAD

**Issue by eugeniodevv** [ViaVersion/ViaVersion#2817]
### `/viaversion dump` Output

https://dump.viaversion.com/dbd067f361465badb80706c7b51db56b3e7c84d8bbc71988504587c14308d084

### Console Error

```
https://paste.gg/p/anonymous/14617cf435664513a5e74986df15d8cc
```

### Bug Description

When trying to connect to a 1.17 server using a 1.17 client on Velocity, this error pops up.

### Steps to Reproduce

Connect to a 1.17 server using 1.17 putting ViaVersion on Velocity.

### Expected Behavior

It won't connect you to the server and it will give that error in console.

### Additional Server Info

I also have ViaBackwards. I've tried removing it just in case, but the error is still popping up. I've also tried resetting the configuration files of both plugins, but no luck.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--b8f1df44--b110%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--b8f1df44--b110%29-3498db?style=flat-square) </br>![ViaVersion (4.2.0-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.0--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.2.0-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.2.0--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by eugeniodevv** [comment]
Updating to the latest dev version solved this for whatever reason.
