### ISSUE TITLE
Sheep named jeb_ are not rendered as rainbow on later versions

### ISSUE THREAD

**Issue by imkunet** [ViaVersion/ViaVersion#2821]
### `/viaversion dump` Output

https://dump.viaversion.com/f734d61af89eba9caff224baa28d5e4e9ef5146adcc08e5d9f544f17dc5bf377

### Bug Description

The sheep on 1.18.1 does not appear rainbow as it should (when it is named `jeb_`)

(See attached screenshot)

### Steps to Reproduce

1. Use the current release build or snapshots of VIaVersion on 1.8.9
2. Spawn a sheep and name it `jeb_` on 1.8.9 and observe how the sheep changes colors
3. Log on with 1.18.1 and observe the sheep not changing colors

### Expected Behavior

The sheep should render as rainbow on both versions as it does in the vanilla worlds for each respective version.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by imkunet** [comment]
![image](https://user-images.githubusercontent.com/13318546/153743096-434d2ee9-8d4b-4109-a538-14014d93eb00.png)
*note: the image does not depict this, but the sheep is changing colors on the 1.8.9 client*

**Comment by kennytv** [comment]
Could you test what client version this stops working from?

**Comment by tomcraft** [comment]
I also encountered this without taking much time to debug, it was with 1.16.5 client.

**Comment by imkunet** [comment]
The sheep stops working on any version AFTER 1.12.2 it appears after some testing

**Comment by Kichura** [comment]
Managed to reproduce this issue on ViaVersion 4.1.1 using 1.17.1 client,
[The dump for my dummy server is here.](https://dump.viaversion.com/d44fd75860ddab75733a715fef0578fe517c5c97237258a8b41cfc29dca67176)

![mc](https://user-images.githubusercontent.com/68134602/153762362-dd395776-0f00-4e5c-8074-dd8f35fbff69.png)

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--445%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 15 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-15%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by imkunet** [comment]
After some digging, I was able to find the code which checks the `jeb_` name in the class `net.minecraft.client.renderer.entity.layers.SheepFurLayer` where every time render is called it checks the entity name to see if it equals `jeb_` and if it `hasCustomName`. From this it is possible to deduce the name is not properly being recalled or the client thinks that the sheep does not have a custom name. Hope this information helps!

**Comment by tomcraft** [comment]
I can confirm its working, thank u kenny !
