### ISSUE TITLE
Ladders r broken, i wont be able to present to player why they are.

### ISSUE THREAD

**Issue by swa324** [ViaVersion/ViaVersion#2822]
### `/viaversion dump` Output

https://dump.viaversion.com/a24b3278dc26324d8c00886e0a607a54e37981e1999cc3a0c7ffaebf134d3772

### Console Error

i get none

### Bug Description

Ladders and lilypads are broken. for lilypads i dont really know how but for ladders, especialy on 1.8.9, u cant go up them. it just glitches and keeps u there, pls help.

### Steps to Reproduce

1. login to 1.8.9
2. try to use a ladder
3. u cant climb upwards

### Expected Behavior

Ladders and Lilypads should work normaly like how zonecrafts or hypixels does.

### Additional Server Info

i also use luckperms bungeecord, and ultrastaffchat in my bungeecord plugins.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A9c95d4b%3A1628](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A9c95d4b%3A1628-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards-Outdated!-red?style=flat-square) </br>![ViaRewind(2.0.2): 5 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by Camotoy** [comment]
https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ should solve this.
