### ISSUE TITLE
Random errow which amkes the server crash

### ISSUE THREAD

**Issue by ZayanPlayz** [ViaVersion/ViaVersion#2823]
### `/viaversion dump` Output

not working

### Console Error

```
[Put the paste.gg link or text here.](https://mclo.gs/S8SOTYQ)
```

### Bug Description

Makes server crash

### Steps to Reproduce

Makes server crash

### Expected Behavior

Makes server crash

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by ZayanPlayz** [comment]
https://mclo.gs/S8SOTYQ

**Comment by ZayanPlayz** [comment]
it dosen't work

**Comment by kennytv** [comment]
Not a crash, and you have a broken config file
