### ISSUE TITLE
Blank Signs

### ISSUE THREAD

**Issue by TheGamer3514** [ViaVersion/ViaVersion#2824]
### `/viaversion dump` Output

https://dump.viaversion.com/6acf531a68f4e34288b16877400555dca59a2427be2a7e42fe37e355aacf7fd2

### Bug Description

Placing Signs Does Not Show In Older Versions, It Becomes A Blank Sign.
I Added A Sign In 1.18 And On 1.8.9 The Sign Was Blank, I Then Wrote The Sign In 1.8.9, Left The Server, Rejoined And It Was Blank, Text Was Visible On 1.18 Though.

### Steps to Reproduce

Login With 1.8.9 After Placing A Sign In 1.18.1

### Expected Behavior

Sign Text Appears

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
Use ci builds
