### ISSUE TITLE
Issue with ViaVersion's injector

### ISSUE THREAD

**Issue by retrooper** [ViaVersion/ViaVersion#2825]
### `/viaversion dump` Output

https://dump.viaversion.com/f34803f4498497ce3b5d63c445f8ecbb6b3ce5f586662d643faef3e4aff1c447

### Console Error

Check bug description

### Bug Description

ViaVersion's spigot injector decides to wrap minecraft's vanilla encoder. I'm trying to make my own injector. I want to process buffers, that aren't translated by ViaVersion yet. It would be better if ViaVersion had a separate outgoing handler which were called after the vanilla minecraft encoder. Your handler can expect bytebufs and just translate them like that. Let the vanilla encoder do its job by translating NMS packets to bytebufs for you to process. This would make it so easy for any other packet plugin to just get in between ViaVersion and the vanilla encoder.

Similarly can be said about the decoder. You guys just wrap the minecraft vanilla decoder... I want to process packets right after ViaVersion translates incoming bytebufs. You could simply put ViaVersion's decoder infront of vanilla's decoder. Then I can just get inbetween and process my bytebufs there. ViaVersion isn't the only packet plugin out there, and I've also seen other developers finding making an injector a struggle. I managed to get a "working" decoder, but its really really not great and doesn't work great if you can't predict how many packet projects are running on the server. You'd also be saving yourself redundant reflection calls to vanilla handlers? 

Additionally with what ProtocolLib does, calling "encoder" right after it processes the first NMS object... that just doesn't make making an injector easier.

I just want to know, is there a reason you did not do this? Seems like it would just be easier to handle things like that, worst case scenario if you guys don't want to fix your injector, I could do it.

### Steps to Reproduce

Check  bug description

### Expected Behavior

Check bug description

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>
