### ISSUE TITLE
No sound when placing blocks

### ISSUE THREAD

**Issue by Wizertex** [ViaVersion/ViaVersion#2829]
### `/viaversion dump` Output

https://dump.viaversion.com/977b0110ee08a960597f12cdd23932cdfaa5b6d74b4f92320a839f9e16da2d13

### Console Error

```
/
```

### Bug Description

When playing on 1.8 or 1.8.9 and placing blocks, there's no sound (but it is when breaking blocks as expected).
On 1.9 and 1.18.1, it works properly.

### Steps to Reproduce

1. Play on 1.8 or 1.8.9 (tested on those two only)
2. Place a block

### Expected Behavior

A sound of a placed block should be heard

### Additional Server Info

I don't use BungeeCord,
I also tested with only those 3 plugins (ViaVersion, ViaRewind and ViaBackwards) and the issue is still there.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3442--Spigot--699290c--62d9762%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-3442--Spigot--699290c--62d9762%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.2.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.2.0)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
You need ViaRewindLegacySupport

**Comment by Wizertex** [comment]
Thanks for fast response! Along with these 3 or replace it with ViaRewind?

**Comment by Jo0001** [comment]
Along with the 3 others

**Comment by Wizertex** [comment]
Thanks for the reply.

I tried both versions 1.4.0 and 1.4.1 but the issue still persists except I now get this error in console when I place a block:
https://paste.gg/p/anonymous/ebf840794dae47008225ea011ee5690b
