### ISSUE TITLE
can't join with minecraft 1.18.2

### ISSUE THREAD

**Issue by EdoardLimondi** [ViaVersion/ViaVersion#2830]
### `/viaversion dump` Output

https://dump.viaversion.com/a24a8788c4241402b282a6f0e15e121b02d3834d229750b73a3277c969761131

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

if i join into server using minecraft 1.18.2 say Outdated Server!
![2022-02-28_21 09 44](https://user-images.githubusercontent.com/61433249/156052191-dcdf609d-95c7-4354-bc8e-9d19b1a27706.png)

### Steps to Reproduce

1. open minecraft 1.18.2
2. join into server
3. doesn't work and say Outdated Version

### Expected Behavior

should work with minecraft 1.18.2

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--177%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-git--Paper--177%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by creeper123123321** [comment]
Update bungeecord
