### ISSUE TITLE
Can't log in on a 1.13 server

### ISSUE THREAD

**Issue by QmanRocks** [ViaVersion/ViaVersion#2831]
### `/viaversion dump` Output

https://dump.viaversion.com/c6b38a10c544154ee90c7a1b0ca4e9a692d48d68a23e1d62a11f28e412ee7856

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/903f4dc63308475abeb68acfdaa233e4

### Bug Description

After attempting to sign onto a 1.13 server with ViaVersion, the server kicks me immediately. I get a pretty long error code that has something to do with a crafting recipe(?) and a piston. I tried logging on with a 1.14 client-1.18.1 client and none of them worked.

### Steps to Reproduce

1. Set up a Spigot 1.13 server with Bungeecord
2. Install ViaVersion
3. Connect with version 1.14+

### Expected Behavior

Connect normally without an error.

### Additional Server Info

I have to use a 1.13 server version and the plugin is installed on the server, not on Bungeecord.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Spigot--fe3ab0d--162bda9%20%28MC%3A%201.13%29](https://img.shields.io/badge/Platform-git--Spigot--fe3ab0d--162bda9%20%28MC%3A%201.13%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
We don't support 1.13.0 servers, see https://github.com/ViaVersion/ViaVersion/issues/2383
