### ISSUE TITLE
Certain Signs are invisible when players join with a newer version

### ISSUE THREAD

**Issue by Ijdtm7** [ViaVersion/ViaVersion#2832]
### `/viaversion dump` Output

https://dump.viaversion.com/75acf371b5619b6522f9bb06ed61a6dcd4ea514691e0b94ec66db7321e203013

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Players who have not joined on 1.17.1 before seem to have invisible signs (no text or sign rendering, just hitbox) when they join on 1.18.1

### Steps to Reproduce

1. Join from 1.18.1 viaversion on a server with already existant signs that you have not joined before
2. look at the signs

### Expected Behavior

The signs should render and text should be visible

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--%2208dd6c7%22%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Purpur--%2208dd6c7%22%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square) </br>![ViaRewind(2.0.2): 6 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards-Outdated!-red?style=flat-square) </br>
