### ISSUE TITLE
Updating to 4.2.0 or 4.2.1 causes "Unable to locate sign at ..."

### ISSUE THREAD

**Issue by wmp71** [ViaVersion/ViaVersion#2833]
### `/viaversion dump` Output

https://dump.viaversion.com/8595f6cc2256c8d19b300574cbf49b9c0fe33d9bbf02f008cfb2a489b43e8121

### Console Error

No errors.

### Bug Description

If I go to a world (or load a chunk) that has wall signs, the chat is spammed with "Unable to locate sign at \<coordinates>".

### Steps to Reproduce

1. Open a spigot 1.18.1 server.
2. Log in using 1.8.9 forge
3. go to somewhere that has wall signs.

### Expected Behavior

There shouldn't be "Unable to locate sign at \<coordinates>" messages in the chat.

### Additional Server Info

I have ViaVersion 4.2.1, ViaBackwards 4.2.0, ViaRewind 2.0.3 Snapshot, ViaRewind legacy support 1.4.1 snapshot.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3425--Spigot--7fbc6a1--9dafd10%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-3425--Spigot--7fbc6a1--9dafd10%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.2.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.2.0)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by wmp71** [comment]
EDIT: This happens when there are signs where the y-coordinates are too low. for me it happened in -13 while the ground's y-coordinates was 61.
