### ISSUE TITLE
Race condition on PlayerConnection initialization, causing ViaAPI to report wrong information for connecting players

### ISSUE THREAD

**Issue by Pablete1234** [ViaVersion/ViaVersion#2835]
### `/viaversion dump` Output

https://dump.viaversion.com/c9cc443fbfb4e3133b8f747a589fee15f9bbcd6056df666fc811ee5d4c1c59b0

### Bug Description

`ViaAPI#getPlayerVersion` can return -1 on PlayerJoinEvent, depending on server capacity (it is caused by a race condition)

Relevant codepaths:

`ViaAPI#getPlayerVersion` relies down to `ConnectionManager#getConnectedClient(uuid)`: https://github.com/ViaVersion/ViaVersion/blob/master/bukkit/src/main/java/com/viaversion/viaversion/bukkit/platform/BukkitViaAPI.java#L45
The `ConnectionManager`, will only have a player to return from `getConnectedClient` if `onLoginSuccess` has been called for that user, since that is what adds it to the map:
https://github.com/ViaVersion/ViaVersion/blob/master/common/src/main/java/com/viaversion/viaversion/connection/ConnectionManagerImpl.java#L44

`ConnectionManager#onLoginSuccess` is called when the `GAME_PROFILE` packet is sent to the client:
https://github.com/ViaVersion/ViaVersion/blob/master/common/src/main/java/com/viaversion/viaversion/protocols/base/BaseProtocol1_7.java#L143

However, in the bukkit main thread, what we have is code that sends packets for `PacketPlayOutLogin` (the `GAME_PROFILE` packet), as well as difficulty, location, player abilities, inventory, scoreboard, and calls PlayerJoinEvent, all in the same method and pretty close in timing to eachother

The order is roughly:
 - send `PacketLoginOutSuccess` (the `GAME_PROFILE` packet in via)
 - launch PlayerInitialSpawnEvent
 - spawn entity player in the world
 - launch PlayerSpawnLocationEvent
 - update player gamemode
 - create new PlayerConnection
 - send setup packets (login, custom payload, difficulty, spawn location, abilities, held item, entity status)
 - launch PlayerJoinEvent

This list of items is all executed on the main thread, while the packets being sent are queued on the network thread, meaning if the network thread is stressed enough, you can reach the PlayerJoinEvent and not have the player version available yet.

It is probably easier to test/debug this in PlayerInitialSpawnEvent since it occurs sooner and the race condition is probably easier to spot.

### Steps to Reproduce

- Use a plugin that calls ViaAPI#getPlayerVersion on PlayerJoinEvent and displays it or otherwise acts with it. 
- Run the server with enough players online (stressing the network thread) so that packets are ever so slightly delayed
- You will start to see PlayerJoinEvents with -1 as the player version

### Expected Behavior

ViaApi#getPlayerVersion should return the correct player version on PlayerJoinEvent

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--SportPaper--f557883--P.5b9d4f1--SP.019ba69--CB.e1ebe52%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--SportPaper--f557883--P.5b9d4f1--SP.019ba69--CB.e1ebe52%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind-Outdated!-red?style=flat-square) </br>
