### ISSUE TITLE
Granite doesn't work on 1.8.8 server 

### ISSUE THREAD

**Issue by LIWKK** [ViaVersion/ViaVersion#2836]
### `/viaversion dump` Output

https://dump.viaversion.com/7e45af6c4a49a4f7b272609100cc1afcbafe7adf3a80e579a1ff5a27d3233f0d

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

You can't take Granite to your inventory and if it is placed otherwise it will become normal stone

### Steps to Reproduce

1. Login with any client version
2. Take granite from creative inventory
3. It disappears

### Expected Behavior

Granite shouldn't disappear since it was added in 1.8

### Additional Server Info

I use Waterfall with no ViaVersion there, ViaVersion is on spigot servers

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.8.8--R0.1--SNAPSHOT%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-1.8.8--R0.1--SNAPSHOT%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Can't reproduce this with regular granite and polished granite blocks,
The granite walls and others were first added in 1.14 however so expect those to convert into stone as the IDs don't exist in 1.8.x.

**Comment by kennytv** [comment]
See above, either that or it's a stacked setup/some other plugin interfering
