### ISSUE TITLE
Packet issue with Multi Block Change on 1.16.5 server, 1.18.2 client

### ISSUE THREAD

**Issue by HackersDontWin** [ViaVersion/ViaVersion#2837]
### `/viaversion dump` Output

https://dump.viaversion.com/30578a90215601983b45fdf5e0ca8e6214d167dc5a91824053ca8c953feb85bc

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/39c379c482444e499b5040da5d075b21

### Bug Description

Happened randomly. Was running on a 1.16.5 server and connected with a 1.18.2 client

### Steps to Reproduce

No idea, it randomly happened. 

### Expected Behavior

Nothing at all

### Additional Server Info

This server is running CraftBukkit version 3096a-Spigot-9fb885e-af1a232 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT
![Untitled](https://user-images.githubusercontent.com/31494839/156903287-be17a34c-3ccc-4431-8175-ea6ea1b7dc65.png)
)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3096a--Spigot--9fb885e--af1a232%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-3096a--Spigot--9fb885e--af1a232%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
You have a broken/corrupt jar file
