### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by Restland** [ViaVersion/ViaVersion#2838]
### `/viaversion dump` Output

https://dump.viaversion.com/e904cfbf3d4cfda4d62f7de7ae397d7a5ebb2e355f86b672ba5ebd748ede4431

### Console Error

(https://paste.gg/p/anonymous/463c133ae4d448eea574f080f9dec84e)

### Bug Description

This appears in console, once it crashed the server aswell.

### Steps to Reproduce

I have no idea, this happens when people join from a differt version I guess.

### Expected Behavior

Not to get thsi error.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--177%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-git--Paper--177%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards-Outdated!-red?style=flat-square) </br>
