### ISSUE TITLE
Incompatibility with ProtocolLib v5

### ISSUE THREAD

**Issue by derklaro** [ViaVersion/ViaVersion#2839]
### Problem Description

Hello,

as some might have seen, ProtocolLib recently released the first dev build of v5 which rewrites the whole way how it injects into the channel pipeline of the player. Rather than wrapping the vanilla encoder / decoder it is now a extra handler in the pipeline right after the decoder.
This is were the problem comes in: ViaVersion currently relies on wrapped decoder name (`protocol_lib_decoder`) which no longer exists. This breaks the whole way where the ViaVersion wrappers (decompressor) are inserted into the pipeline and where the messages are fired to after decoding. Removing the protocollib check fixes all these issues (seemingly).

### Solution Description

As already said (sorry) don't inject using the `protocol_lib_decoder` handler name, or only if the ProtocolLib version is < 5 (or the protocol_lib handler is present in the pipeline).

### Alternatives

No real alternative aside from rolling back the ProtocolLib upgrade 🤷 

### Additional Info

Tested on 1.8 using a 1.18.2 client to join. See https://github.com/dmulloy2/ProtocolLib/issues/1531 for context.

**Comment by retrooper** [comment]
Related to https://github.com/ViaVersion/ViaVersion/issues/2826

**Comment by kennytv** [comment]
https://github.com/ViaVersion/ViaVersion/commit/c1b993c01b35c37ce64821a9d75e3734123017a2
