### ISSUE TITLE
ERROR IN Protocol1_8TO1_9 IN REMAP OF SET_SLOT (0x16)

### ISSUE THREAD

**Issue by batebarson** [ViaVersion/ViaVersion#2841]
### `/viaversion dump` Output

https://dump.viaversion.com/246b0ce2345999adbd0e5a91588dfdbfdf4b926b9c9bb1c558b0329f0090714c

### Console Error

ERROR IN Protocol1_8TO1_9 IN REMAP OF SET_SLOT (0x16)
![Lunar Client (1 8 9-3c65641_master) 3_12_2022 10_13_13 AM](https://user-images.githubusercontent.com/101467031/158023873-d0da1e68-7703-4d63-8897-6367768c0026.png)

### Bug Description

ERROR and wont let me join

### Steps to Reproduce

join minecraft error instantly occurs and kicks you

### Expected Behavior

join server shouldnt be disconnected

### Additional Server Info

i only use paper with no other plugins so far

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--244%20%28MC%3A%201.14.4%29](https://img.shields.io/badge/Platform-git--Paper--244%20%28MC%3A%201.14.4%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.2.0): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.2.0)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind-Outdated!-red?style=flat-square) </br>
