### ISSUE TITLE
Server 1.18 crashes 1.13 and 1.14 clients when in the nether/end

### ISSUE THREAD

**Issue by TKwSni** [ViaVersion/ViaVersion#2842]
### `/viaversion dump` Output

https://dump.viaversion.com/b9a36933a27e79135e9e3a4d5144e3be822e19715e09b12a68dbe55b02cf8b87

### Console Error

```
No console errors
```
Here is the client crash if useful 

https://pastebin.com/raw/4KbYi7Yr

### Bug Description

If you join the overworld everything is fine, but as soon as you move to the nether the client crashes.

### Steps to Reproduce

Teleport to the nether or end using clients < 1.16 on a >=1.18 server

### Expected Behavior

Not to crash the client.

### Additional Server Info

I have tried with the newest versions of protocollib/viaversion and 1.18.2 it didnt work, if I use protocolsupport I can join the nether without issues.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1465%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-git--Purpur--1465%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.2.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Can't reproduce. Is that a Vanilla client and do you have any datapacks? Otherwise please also try with a standard Paper

**Comment by kennytv** [comment]
Nevermind, I can

**Comment by kennytv** [comment]
Caused by https://github.com/ViaVersion/ViaVersion/issues/2842
