### ISSUE TITLE
Server kicks player when teleporting

### ISSUE THREAD

**Issue by enels0n** [ViaVersion/ViaVersion#2843]
### `/viaversion dump` Output

https://dump.viaversion.com/0a56af000635d918d3b016b9e9cc1b5ee7da41cdebe921160285da97215563e5

### Console Error

[Console Error](https://pastebin.com/E73jRQQz)

Bungee log:
03:21:36 [INFO] [N1kroll_] disconnected with: [Proxy] Потеряно соединение с сервером.
03:21:36 [INFO] [N1kroll_] <-> DownstreamBridge <-> [grief] has disconnected
03:21:36 [INFO] [N1kroll_] -> UpstreamBridge has disconnected

### Bug Description

Periodically, teleportations lead to a break in the connection between the player and the server.

### Steps to Reproduce

Tested version: 1.12.2, 1.18.1
Just send a teleporting command like /home. But it is not always possible to cause a problem.

### Expected Behavior

1.12.2: I have the error in console, but server doesn't kick me.
1.18.1: Error and kick.

### Additional Server Info

Perhaps this issue is due to the Orebfuscator plugin.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1618%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1618%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 6 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.2.0): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.2.0)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
Not a Via issue
