### ISSUE TITLE
Continously kicks me from the server

### ISSUE THREAD

**Issue by Stqrx** [ViaVersion/ViaVersion#2844]
### `/viaversion dump` Output

https://dump.viaversion.com/68841b13445275b6f37ec52a212f2e37e45a78a4ca4ce60b4762991cddeac678

### Console Error

```
https://paste.gg/p/anonymous/79cf6eb443334017b83af40e0ab1a4e4
```

### Bug Description

whenever i try joining it instantly kicks me out with an error message

### Steps to Reproduce

Go on 1.16.5
Join the server
Get kicked

### Expected Behavior

Go on 1.16.5
Join the server
Play the game

### Additional Server Info

ViaBackwards is in along with world edit plugins

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--232%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Paper--232%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.2.0): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.2.0)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
You probably have a corrupted jar/did a reload, otherwise update to ci builds
