### ISSUE TITLE
Perpetual loading of the territory

### ISSUE THREAD

**Issue by Ciferblood** [ViaVersion/ViaVersion#2845]
### `/viaversion dump` Output

https://dump.viaversion.com/3f15d6faef4a23c86f22d89096fd660b1538865092076e0ca450079a605e339e

### Console Error

Nothing is displayed in the console

### Bug Description

My server is on the 1.18.1 paper core, I installed the viaversion version 4.2.1 plugin so that players can log in from version 1.18.2. When a player on version 1.18.2 dies without being reborn, exits the game, then the next time he enters the game, he will have an eternal loading of the territory.

### Steps to Reproduce

1. The player logs in from version 1.18.2.
2. The player gets killed
3. The player closes the launcher (or a crash occurs)
4. The player enters the server again
![screen](https://user-images.githubusercontent.com/84799898/158046634-c5d76aec-d61d-4637-8bf0-b81305882aa8.png)

### Expected Behavior

[](https://www.translate.ru/)The player can be reborn after re-entry

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--216%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-git--Paper--216%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by Ciferblood** [comment]
I forgot to add, this is corrected by going to version 1.18.1. And after that you can safely go from version 1.18.2.

**Comment by kennytv** [comment]
That's because Paper differs in behavior on 1.18.1, which has been fixed in Paper 1.18.2
