### ISSUE TITLE
JSON cannot parse messages properly

### ISSUE THREAD

**Issue by not9cb** [ViaVersion/ViaVersion#2847]
### `/viaversion dump` Output

https://dump.viaversion.com/38be6664628e9ab8382f12c3d84ffe8d0399838bdbaaecbd87489a64baca1b0b

### Console Error

With color codes:
https://paste.gg/p/anonymous/ce3ec3be5d2048788271a6e5709d7cd9

With empty string:
https://paste.gg/p/anonymous/def3719d81f846458245c47762475b5e

### Bug Description

When trying to spawn a living entity (armorstand) via packets and then setting it's name to either empty or a name with color codes it produces an exception.

### Steps to Reproduce

1. Make a spawn living entity packet with the type of entity being an armorstand
2. Make a entity metadata packet with a datawatcher containing the name
3. Send the packets to a player and it should cause an exception

### Expected Behavior

JSON should be able to parse the given text properly.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--216%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-git--Paper--216%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 6 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.2.0): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.2.0)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
That's not a valid serialized component
