### ISSUE TITLE
Kicked when trying to connect to server

### ISSUE THREAD

**Issue by steak20** [ViaVersion/ViaVersion#2852]
### `/viaversion dump` Output

https://dump.viaversion.com/47c105197999072ee3a9154bea18a1f15bf5c2dc160c2df113e746cf2e193820

### Console Error

[INFO] .... 95.223.71.226 had been firewalled from the proxy!

[INFO] .... [PotFastL] disconnected with: EncoderException : java.lang.NullPointerException @ io.netty.handler.codec.MessageToByteEncoder:125

[WARNING] .... No client connected for pending server!

### Bug Description

I'm using an 1.7 - 1..8 bungeecord and I can connect to the hub with 1.7 and 1.8 with no issues. But if I try to join a proxy server/game server where ViaVersion-4.2.1 and ViaRewind-2.0.2-SNAPSHOT is installed, I am getting kicked. I never had this issue before but now I am having it.

### Steps to Reproduce

Create a bungeecord network with the bungeecord version 1.7 - 1.8 and upload viaversion & viarewind on a proxy/game server.

### Expected Behavior

When connecting to a Proxy server I should not be kicked.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Spigot--21fe707--741a1bd%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--Spigot--21fe707--741a1bd%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 6 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
> Via plugins are only running on EITHER the backend servers (e.g. Paper) OR the proxy (e.g. BungeeCord), not on both.
