### ISSUE TITLE
fix Supported Versions chart en read.md since only support 1.8.8+ server

### ISSUE THREAD

**Issue by HowardZHY** [ViaVersion/ViaVersion#2854]
### Problem Description

Viaver only support 1.8.8+ server now so we need to change Supported Versions chart.

### Solution Description

We should change server version from 1.8.x to 1.8.8 to prevent people try to use VV on 1.8-1.8.7 servers and submit "failed to get server protocol" issues.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by HowardZHY** [comment]
dump.viaversion.com/7bba598c55e67a5da68311c1925e1fec891802598dece494c80a30b8ed32ad6d

PS: My discord was auto-banned and I haven't recived a feedback email for 5 days : (

**Comment by Kichura** [comment]
We would've done this a bit prior but since we use ".x" for every major version (example being 1.15.x), this very likely will not be fixed unless stated otherwise.

**Comment by FormallyMyles** [comment]
See above, not really worth the effort since it's like 0.01% of people (maybe less). It does technically work on less than 1.8.8 just at a proxy level.

**Comment by HowardZHY** [comment]
> See above, not really worth the effort since it's like 0.01% of people (maybe less). It does technically work on less than 1.8.8 just at a proxy level.

the latest build will work on 1.8.0-1.8.7 ?

**Comment by Kichura** [comment]
ViaVersion does not support 1.8.0-1.8.7, You will be advised to use 1.8.8/1.8.9 instead.

**Comment by HowardZHY** [comment]
I know , but there's no bukkit/spigot/paper 1.8.9 , only 1.8.8 and viaver will crash sponge 1.8.9



At 2022-04-08 23:59:22, "Kichura" ***@***.***> wrote:

ViaVersion does not support 1.8.0-1.8.7, You will be advised to use 1.8.8/1.8.9 instead.

**Comment by kennytv** [comment]
> It does technically work on less than 1.8.8 just at a proxy level.
