### ISSUE TITLE
Connecting from 1.12.2 to 1.18 works fine, but when I go past -0, it says outside of the world

### ISSUE THREAD

**Issue by Nicolaco08** [ViaVersion/ViaVersion#2855]
### `/viaversion dump` Output

https://dump.viaversion.com/4ef209ca8bbe4d1b6afeef3b8ee7838c16410ec5d5092f1ee01927ceef0c4d97

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/a8572b8648254850afa785168c495c48

### Bug Description

Going down to -0 on 1.12.2 causes the 'Outside of world' error message, and nothing is rendering

### Steps to Reproduce

1. Login with 1.12.2 on 1.18 server
2. go at y=0
3. see

### Expected Behavior

It should render the world normally

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--66%20%28MC%3A%201.18%29](https://img.shields.io/badge/Platform-git--Paper--66%20%28MC%3A%201.18%29-3498db?style=flat-square) </br>![ViaVersion (4.2.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.2.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.2.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 6 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
See the warning in the console. Also, you're server is heavily outdated
