### ISSUE TITLE
Error when a player join the server

### ISSUE THREAD

**Issue by TypicalShavonne** [ViaVersion/ViaVersion#2856]
### `/viaversion dump` Output

https://dump.viaversion.com/4ea4161ee4494f2ffc5cc889e4282ddb440ed8a593946082663616131432c963

### Console Error

https://paste.gg/p/anonymous/dd8b2a6456414bdf94d49eb89484ef4c

### Bug Description

When a player joined, he got kick with that stacktrace, it just spam the console like crazy

### Steps to Reproduce

1. login with 1.16.4 client
2. get kick

### Expected Behavior

No error

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--%224ff0630%22%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Purpur--%224ff0630%22%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 6 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards-Outdated!-red?style=flat-square) </br>
