### ISSUE TITLE
Random Error appears

### ISSUE THREAD

**Issue by ZeroTwoO2** [ViaVersion/ViaVersion#2857]
### `/viaversion dump` Output

https://dump.viaversion.com/24a4ecc58056ab624e52d1e0cef8015444f82001e32ad28e579a2066b35c54b8

### Console Error

https://paste.gg/p/anonymous/4b75fd37f3d34194a94c917d608dc882

### Bug Description

Errors with chat messages

### Steps to Reproduce

I have no idea. A person on 1.18 joined and then it kicked them for this error

### Expected Behavior

I think he tried to talk in chat so he should've been able to

### Additional Server Info

Yes, i use bungeecord with SkinRestorer , and some other minimal custom plugins

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.8.8--R0.1--SNAPSHOT%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-1.8.8--R0.1--SNAPSHOT%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
Either an issue with the custom server software or another plugin; try a standard Paper/removing half of your plugins until it works again to find out what it might be
