### ISSUE TITLE
ReplayMod recordings from a server running on 1.8.9 don't have skins on player heads

### ISSUE THREAD

**Issue by Thr0nSK** [ViaVersion/ViaVersion#2859]
### `/viaversion dump` Output

nodump

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

ReplayMod recordings form a server running on 1.8.9 don't have skins on player heads placed in the world.

### Steps to Reproduce

1. login with 1.18.1 to a 1.8.9 server with custom player heads placed on the ground
2. record & save a replaymod recording
3. all the heads have steve skins

### Expected Behavior

The player heads should have custom skins like seen while playing.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [x] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>
