### ISSUE TITLE
ERROR IN Protocol1_17To1_16_4 IN REMAP OF MULTI_BLOCK_CHANGE (0x3B)

### ISSUE THREAD

**Issue by Delphind** [ViaVersion/ViaVersion#2861]
### `/viaversion dump` Output

https://dump.viaversion.com/f004a01eeed8526b587b2339ba64611d32ece7079e7260dc37dd131c4f40e5a6

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/d3c3db452a8b40eb9770bd5186bd081a

### Bug Description

I have a 1.16.5 server. I was kicked from my 1.17 client. I didn't really feel like I was doing anything special.

### Steps to Reproduce

1. I login
2. I was testing my own plugin commands
3. I was kicked from the server with an error

### Expected Behavior

It just happened all of a sudden

### Additional Server Info

Im not using Bungeecord. Ive an 1.16.6 Paper server with Viaversion, Mutliverse and a custom plugin for Deathswap, Hitmen and Manhunt

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--794%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--794%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
We need the full error

**Comment by Delphind** [comment]
https://paste.gg/p/anonymous/a15a47752ffc4e56b306a6a5102a6cf6/revisions

This is the full error. I jumped in the lava and i got kicked

**Comment by kennytv** [comment]
Your plugin jar file is broken, please redownload it.
