### ISSUE TITLE
Getting kicked when using a feature of ItemsAdder

### ISSUE THREAD

**Issue by MinecollYT** [ViaVersion/ViaVersion#2862]
### `/viaversion dump` Output

https://dump.viaversion.com/b3159aa101090f0903266fd9fd3cc57ac08ff7502cc2bd183330f1d89d27552c

### Console Error

https://paste.gg/p/anonymous/c902e46a98ae4f1fb4261c9f4351e8a6

### Bug Description

Using the new emote features from itemsadder causes the player to get kicked. I'm not sure if I should report it here, and you get in contact with the developer or the other way around.

> https://www.spigotmc.org/resources/%E2%9C%A8itemsadder%E2%AD%90emotes-mobs-items-armors-hud-gui-emojis-blocks-wings-hats-liquids.73355/update?update=452013

### Steps to Reproduce

1. Login with Fabric 1.18.1
2. Join 1.17.1 Paper Server
3. Using emote feature

### Expected Behavior

Not getting kicked

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A7e47490%3A1633](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A7e47490%3A1633-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by LoneDev6** [comment]
I tested with latest ViaVersion and it works fine.
You might also try the upcoming ItemsAdder 3.1.1 version which might fix issues since I recoded some part of this feature.
