### ISSUE TITLE
ViaVersion/Backwards not working on latest cardboard (server v: 1.18.1)

### ISSUE THREAD

**Issue by Thepokefreek** [ViaVersion/ViaVersion#2863]
### `/viaversion dump` Output

https://dump.viaversion.com/c334a27c01182954824ddb4e416ef83ac339e255b0995a604f869c8f529801d0

### Console Error

```
https://paste.gg/p/anonymous/219c8df0dfff4194b1aa22d121ea712f
```

### Bug Description

ViaVersion/Backwards not working with native java or floodgate bedrock

### Steps to Reproduce

1. Create a 1.18.1 fabric server
2. Install fabric-api 0.46.6
3. Install iCommon-Fabric 1.18
4. Install the latest cardboard mod 1.17-1.18
6. install Geyser-spigot
7. install Floodgate-spigot
8. Install ViaVersion/Backwards 4.3
9. Try to connect with bedrock or java

### Expected Behavior

ViaVersion/Backwards working

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--UNKNOWN%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-git--UNKNOWN%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.3.0-22w14a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.3.0--22w14a--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>![ViaBackwards(4.3.0-22w14a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.3.0--22w14a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by buzzcoding** [comment]
Cardboard is a mod that translates Spigot plugins to Fabric. We do not support Cardboard, and this would be a Cardboard issue, and as they state on their website, it “is still in development and may not support every plugin.” Also, you can just use ViaFabric and ViaBackwards for use on Fabric, and that is officially supported.

**Comment by Thepokefreek** [comment]
Thanks, it hadn't occurred to me that there could be a fabric version of ViaVersion

>Also, you can just use ViaFabric and ViaBackwards for use on Fabric, and that is officially supported.
