### ISSUE TITLE
Kick when using the command

### ISSUE THREAD

**Issue by ledatvn** [ViaVersion/ViaVersion#2864]
### `/viaversion dump` Output

https://dump.viaversion.com/656373a8778393a184e090584c6e665276cc3fbe8c427822d38318f3a7ac508b

### Console Error

When my players /pv 1 they get kicked with an error in the console

```
[07:23:10 INFO]: KD_KuroTV lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$1 (Anonymous)}
```

### Bug Description

When my players /pv 1 they get kicked with an error in the console

### Steps to Reproduce

1. Login with 1.12.2 -> 1.18 Client
2. Using command **/pv 1**
3. Kick by server

### Expected Behavior

Use the command to not get kicked anymore

### Additional Server Info

Bungeecord

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--33d42c8e%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--33d42c8e%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.2.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.2.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.2.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
We need the full error, we also don't know what "pv" is

**Comment by Kichura** [comment]
> We need the full error, we also don't know what "pv" is

Giving you a bit of a heads-up for this one; This command is from "PlayerVaultsX" and is designed to call a customized chest GUI.

**Comment by ledatvn** [comment]
> We need the full error, we also don't know what "pv" is

fixed
