### ISSUE TITLE
Snapshot Client not connection Snapshot Server through Velocity

### ISSUE THREAD

**Issue by 8MiYile** [ViaVersion/ViaVersion#2865]
### `/viaversion dump` Output

https://dump.viaversion.com/96d7574bb7acd3ad86167450ade02db6b5b142119051fd718358eb022fd284a1

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Snapshot Client not connection Snapshot Server through Velocity
Server is Mojang ,so not support viaversion
ViaVersion is Dev-22w11a and installed my Velocity Server

### Steps to Reproduce

Login with C 22w11a connect S 22w11a through my velocity server
while..
visit this
https://github.com/PaperMC/Velocity/issues/687

### Expected Behavior

Snapshot Client can connection Snapshot Server through Velocity
Server is Mojang

### Additional Server Info

Velocity 3.1.2-SnapShot
GameServer 22w11a

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--d59d4505--b133%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--d59d4505--b133%29-3498db?style=flat-square) </br>![ViaVersion (4.3.0-22w14a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.3.0--22w14a--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
You are not using a ViaVersion version that supports 22w11a.

**Comment by 8MiYile** [comment]
while i have use ViaVersion-DEV

**Comment by kennytv** [comment]
Yes, **22w14a**, we only support the very latest snapshot; aside from that, the proxy also needs to support snapshot versions

**Comment by 8MiYile** [comment]
ViaVersion-DEV just installed my Velocity
and Snapshot Server is Mojang not Spigot
