### ISSUE TITLE
ViaVersion Chunk Error and Packet???

### ISSUE THREAD

**Issue by Gijsvdpolmine** [ViaVersion/ViaVersion#2867]
### `/viaversion dump` Output

https://dump.viaversion.com/9905517715aa23f0df640888513ae0230cf5afb570185934893f166f8f4343b6

### Console Error

https://paste.gg/p/anonymous/a8eb0ff113194195b9ac548422c81ad9

### Bug Description

Since we start using WorldEdit this weird error seems to appear and it kicks me out of the server.
All of them are updated to the latest version: ViaBackwards, ViaVersion, ViaRewind
I've been working on a project with another guy and he had the same problem.
Screenshot: https://gyazo.com/6bacaed832fc0dfdd0e27e2cb577d338
Server running on 1.13.2 paper
Logging in with 1.18.2 client.

### Steps to Reproduce

1.13.2 paper
WorldEdit
Use //brush cyl or cuboid any the most radius.
Use all Via's the latest versions expect legacy.

### Expected Behavior

This error shouldn't happening.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--657%20%28MC%3A%201.13.2%29](https://img.shields.io/badge/Platform-git--Paper--657%20%28MC%3A%201.13.2%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.2.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.2.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
You have a plugin sending bad packets/messing up injection, removve half of your other plugins until you find out which one it might be
