### ISSUE TITLE
Bug with 

### ISSUE THREAD

**Issue by NotZer0Two** [ViaVersion/ViaVersion#2868]
### `/viaversion dump` Output

https://dump.viaversion.com/5b8074b94d739f032a73b139e5f86011a98078129f21ddd20694c010bf203d5f

### Console Error

```
[Put the paste.gg link or text here.](https://paste.gg/p/anonymous/a39a353b566c47af82b701b4d11813fd)
```

### Bug Description

i was testing the replay inside the server and then the plugin started acting strange and start kick the player who do the command and start giving this Big error

### Steps to Reproduce

1. Start with the advancereplay a replay and then the plugin start giving this error and kick the user

### Expected Behavior

You should see the replay

### Additional Server Info

I use vulcan as anticheat and as proxy waterfall

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.2.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.2.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 7 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by HowardZHY** [comment]
try latest builds

**Comment by NotZer0Two** [comment]
@HowardZHY they are already latest i downloaded it from SpigotMC

**Comment by HowardZHY** [comment]
latest builds from Jenkins (ci.viaversion.com/job/ViaVersion/)

**Comment by NotZer0Two** [comment]
https://dump.viaversion.com/c2d4e8dca3c2a402b655ba22ed694d91b3182f84354d180cda7e96693643f028

ok now i have a new issues https://paste.gg/p/anonymous/528077b70ad04f73b6d4003cbbaa09a5 now the plugin work but when you start see the replay start a bunch of error and this all the error but then are the same

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.2.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.2.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.2.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
It'll most likely either be the replay doing something bad, using old Via API, or another plugin introducing incompatibility/inconsistency in packet injection

**Comment by NotZer0Two** [comment]
can be the anticheat (vulcan)?

**Comment by NotZer0Two** [comment]
Fixed
