### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lordhadow1** [ViaVersion/ViaVersion#2870]
### `/viaversion dump` Output

Cant, since i cant join the server

### Console Error

https://paste.twerion.net/yuwucevunu.makefile

### Bug Description

Cant join the server

### Steps to Reproduce

idk

### Expected Behavior

no error?

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Either a bad setup or another plugin's incompatibility
