### ISSUE TITLE
Enter permissions for a specific command, not only "viaversion.admin"

### ISSUE THREAD

**Issue by M4xyMC** [ViaVersion/ViaVersion#2872]
### Problem Description

I understand that for bukkit there is permission "viaversion.admin" to grant full use of the plugin.
What I’m looking for and can’t find any solution on the Internet is to grant permissions to a specific command of this plugin, such as the "/viaversion list" command for the exclusive use of certain people who may become staff of a general server.
So far I have not been able to find any particular permission like this, that is why I would like to find some solution

### Solution Description

Implement specific permissions for commands that can be used with the plugin, such as node permissions that carry similar plugins.

Example:
viaversion.admin. *
viaversion.admin.list
viaversion.admin.displayleaks
viaversion.admin.debug
viaversion.admin.reload
viaversion.admin.dump
viaversion.admin.autoteam
viaversion.admin.dontbugme
etc

### Alternatives

You could create a plugin of this plugin that can grant specific permissions of them.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
I have changed the command system to follow this permission scheme:

**viaversion.admin** - Allows to run **/viaversion** and **all sub commands**
**viaversion.command** - Allows the **/viaversion** root command to suggest all sub commands (I deleted the help sub command)
**viaversion.command.<subcmd>** - Allows running **/viaversion <subcmd>**
