### ISSUE TITLE
Error protocol 1.16 to 1.15.2

### ISSUE THREAD

**Issue by ledatvn** [ViaVersion/ViaVersion#2873]
### `/viaversion dump` Output

https://dump.viaversion.com/656373a8778393a184e090584c6e665276cc3fbe8c427822d38318f3a7ac508b

### Console Error

```
[19:28:23 WARN] [ViaVersion]: ERROR IN Protocol1_16To1_15_2 IN REMAP OF ENTITY_EQUIPMENT (0x47)
[19:28:23 INFO]: [belahai] disconnected with: EncoderException : com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_16to1_15_2.packets.InventoryPackets$4 (Anonymous)}
Actual Error:  @ io.netty.handler.codec.MessageToMessageEncoder:104
```

### Bug Description

My server is running at 1.12.2 but when the member enters with 1.16.5 it happens this phenomenon

### Steps to Reproduce

1. Login with 1.16.5 client
2. join the server
3. automatically kicked as soon as you enter

### Expected Behavior

pls fix it

### Additional Server Info

I use Paper 1.12.2: EpicGuard,Viaversion, Viabackwards, viarewind and SkinRestorer, Authme,...

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--33d42c8e%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--33d42c8e%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.2.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.2.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.2.1)-Even%20with%20master-brightgreen?style=flat-square) </br>
