### ISSUE TITLE
ERROR IN Protocol1_13To1_12_2 IN REMAP OF CHUNK_DATA (0x20)

### ISSUE THREAD

**Issue by ismhdez** [ViaVersion/ViaVersion#2874]
### `/viaversion dump` Output

https://dump.viaversion.com/e29db46e49dd0a420a54790db1a3e504bab45bc100e9305b0f6ae519f4c64181

### Console Error

```
[Click here to see the paste document with the crashlog](https://paste.crowtycraft.es/akizafewiv.md)
```

### Bug Description

When you join the server for first time (on fresh start, not only first unique join) maybe you'll get a kick with a CHUNK DATA error on console.

If you try to rejoin after the kick you'll join without any errors. We've updated all Via plugins, even used the snapshot ones on the Jenkins, updated Spigot and none solved the issue.

### Steps to Reproduce

- Start the server
- Join the server
- You'll be kicked on join randomly (sometimes yes, sometimes no)
- After being kicked, you can rejoin normally without any errors (no restart)

### Expected Behavior

You don't have to be kicked on join

### Additional Server Info

We use BungeeCord, but ViaVersion is only on paper servers

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.2.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.2.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.2.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
Set the blockconnection method to packet
