### ISSUE TITLE
Signs are invisible when players join from newer version on 1.17 server

### ISSUE THREAD

**Issue by Ijdtm7** [ViaVersion/ViaVersion#2876]
### `/viaversion dump` Output

https://dump.viaversion.com/fd8d40cd824353415c96ae1b69b4e7027971afee46707529dbbb84a3cbddd3d1

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Players who have not joined on 1.17.1 before seem to have invisible signs (no text or sign rendering, just hitbox) when they join on 1.18.1

### Steps to Reproduce

1.Join from 1.18.1 viaversion on a server with already existant signs that you have not joined before
2.look at the signs
3. signs wont be able to see

### Expected Behavior

Sign should be visible

### Additional Server Info

I use purpur for my server, works perfectly fine on 1.17.1 which is my servers main version which makes me think this is a viaversion issue

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--%2208dd6c7%22%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Purpur--%2208dd6c7%22%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.2.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.2.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 7 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by HowardZHY** [comment]
try latest dev builds and test with a clean server

**Comment by Kichura** [comment]
This issue seems to be caused by purpur 1.17.1 itself, This can be worked around by switching the server software to paper 1.17.1 instead.

**Comment by Ijdtm7** [comment]
Is that the only work around? I need purpur to combat server lag

**Comment by Kichura** [comment]
> Is that the only work around? I need purpur to combat server lag

There are likely other workarounds that will fix signs but this one is considered to have the best options for now.
