### ISSUE TITLE
viaversion error

### ISSUE THREAD

**Issue by COOKIMONSTER94494** [ViaVersion/ViaVersion#2878]
### `/viaversion dump` Output

https://dump.viaversion.com/06f8184342fe23a6bc31b8d58b130e8c0305141cc56c8a5d61314e9d1d5eaec1

### Console Error

```
Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: WINDOW_ITEMS, Type: FlatVarIntItem Array, Data: [Pair{Type|Unsigned Byte, 0}, Pair{Type|VarInt, 1}], Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$2 (Anonymous), Packet ID: 20}
Actual Error: 
```

### Bug Description

i cant join the server anymore

### Steps to Reproduce

i dont know how it happend

### Expected Behavior

wont let me join server

### Additional Server Info

spigot 1.17.1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3284--a--Spigot--3892929--0ab8487%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-3284--a--Spigot--3892929--0ab8487%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
You have a plugin sending bad packets, but in any case we'd need the *full* error
