### ISSUE TITLE
Weird viaversion error

### ISSUE THREAD

**Issue by Justusbr0405** [ViaVersion/ViaVersion#2880]
### `/viaversion dump` Output

https://dump.viaversion.com/016e7d72ea1b3d70b1258739b57fe7d2f8614eb1d36303423e00e21b1ec854a9

### Console Error

```
https://pastebin.com/A0j6myfa
```

### Bug Description

I have absolutely no clue what this error is. It happens really randomly at random times no clue how it gets triggered. It's pretty rare but when it happens it's annoying for my console

### Steps to Reproduce

I have no clue, i'm very sorry. I don't know what triggers this!

### Expected Behavior

No errors in console

### Additional Server Info

![image](https://user-images.githubusercontent.com/97797608/166439721-76192f0b-cc6e-4429-95df-d88732dadb6c.png)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [ ] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--657%20%28MC%3A%201.13.2%29](https://img.shields.io/badge/Platform-git--Paper--657%20%28MC%3A%201.13.2%29-3498db?style=flat-square) </br>![ViaVersion (4.2.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.2.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.2.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
You have a plugin sending bad packets/messing up injection, removve half of your other plugins until you find out which one it might be

**Comment by Justusbr0405** [comment]
Says something about a chunk
