### ISSUE TITLE
Have an option to disable fast 1.13+ swimming for 1.13+ clients on servers bellow 1.13

### ISSUE THREAD

**Issue by paj1s** [ViaVersion/ViaVersion#2881]
### Problem Description

When using viaversion you can use 1.13 new swimming on old servers.

### Solution Description

Have an option in config disabling this behaviour if possible?

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Camotoy** [comment]
Swimming is client-side controlled; the most you can do to stop this behavior is revert the player's position every time it tries to swim, but that's very glitchy (CubeCraft used to have this behavior).
