### ISSUE TITLE
Plugin reloading problem

### ISSUE THREAD

**Issue by Rafalll1** [ViaVersion/ViaVersion#2884]
### `/viaversion dump` Output

https://dump.viaversion.com/55081ae4ee9d9ec26e66d5526e799bc7991f319b063a9aa7ffc17324fb178676

### Console Error

https://pastebin.com/sXkzNCKv

### Bug Description

I try to reload the plugin and it kick me off the server with this error

### Steps to Reproduce

1. I am logging in with version 1.18.2
2. IKtype the command /tab reload
3. kick me 

### Expected Behavior

Plugin reloading

### Additional Server Info

I'm using velocity latest, server is on version 1.8.8 and java 11

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--TacoSpigot--7bb7d3f3%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--TacoSpigot--7bb7d3f3%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.2.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Either your tab plugin or another injector is malforming packets
