### ISSUE TITLE
22w19a Cannot join

### ISSUE THREAD

**Issue by JaTiTV** [ViaVersion/ViaVersion#2886]
### `/viaversion dump` Output

https://dump.viaversion.com/cf0b7ca9a3f023fd00fd86b57abb4c0427d2a99420cb773bceeef9f6b499040c

### Console Error

[14.05.22][03:13:20 INFO]: [/xx.xx.xx.xx:19146] <-> InitialHandler has connected
[14.05.22][03:13:20 WARN] [ViaVersion]: ERROR IN Protocol1_19To1_18_2 IN REMAP OF 0x00->0x00
[14.05.22][03:13:20 WARN]: [/xx.xx.xxx.xxx:19146] <-> InitialHandler - could not decode packet! com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[14.05.22]{Packet Type: null, Type: Boolean, Data: [Pair{Type|String, JaTiTV}], Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.Protocol1_19To1_18_2$10 (Anonymous), Packet ID: 0}
[14.05.22]Actual Error:

### Bug Description

Cannot join with 22w19a

### Steps to Reproduce

1. Login with 22w19a
2. Cannot join

### Expected Behavior

Cannot join

### Additional Server Info

This server is running Waterfall version git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482 by md_5

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A739eda6%3A482](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A739eda6%3A482-3498db?style=flat-square) </br>![ViaVersion (4.3.0-22w19a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.3.0--22w19a--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>![ViaBackwards(4.3.0-22w19a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.3.0--22w19a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
The proxy needs to support the snapshot, too

**Comment by JaTiTV** [comment]
I now have the latest ViaVersion and the latest Waterfall and I get an error in the client again and it crashes. What am I doing wrong?

ViaVersion-4.3.0-1.19-pre1-SNAPSHOT.jar
waterfall-1.18-486.jar

[crash-2022-05-18_21.57.02-client.txt](https://github.com/ViaVersion/ViaVersion/files/8720487/crash-2022-05-18_21.57.02-client.txt)

**Comment by Xernium** [comment]
Again, Waterfall doesnt support snapshots.

**Comment by JaTiTV** [comment]
Then why does it work with all versions up to and including 22w18a and not with 22w19a, PreRelease1?
