### ISSUE TITLE
Scoreboard being disabled using different client version

### ISSUE THREAD

**Issue by winnipeg21** [ViaVersion/ViaVersion#2887]
### `/viaversion dump` Output

https://dump.viaversion.com/368047104cd6ea78fb12b52d0532ae19614aab1414ccf2bc48b307b8a8eaa449

### Console Error

No console errors from any plugin

### Bug Description

I was using [Scoreboard-Revision](https://www.spigotmc.org/resources/scoreboard.14754/) with a scoreboard in my hub & a game server. I updated ViaVersion about a week ago (today is May 14th). I noticed the scoreboard was hidden and did /sb toggle to find it was already on, I did it again and it showed. When moving to other servers on the network than back to hub the board would disappear again. 

The hub is running 1.17 and so is the game server. I'm connected on 1.18. This issue is only new in the past few updates (or more as I haven't updated Via in a long time). I tried switching to [Animated Scoreboard](https://www.spigotmc.org/resources/animatedscoreboard.20848/) to also have the same issues.

### Steps to Reproduce

1. Login with 1.18 on a 1.17 server running Via on the Proxy
2. Notice the scoreboard is broken!

### Expected Behavior

Expected behavior would be the scoreboard not disappearing

### Additional Server Info

Currently running Velocity #137, Purpur #1427 (1.17), logging in with 1.18.2, using Animated Scoreboard 0.2.5.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--aa38d3e5--b137%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--aa38d3e5--b137%29-3498db?style=flat-square) </br>![ViaVersion (4.3.0-22w19a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.3.0--22w19a--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>![ViaBackwards(4.3.0-22w19a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.3.0--22w19a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Can you remove other plugins (except Via and the scoreboard one) and see if the issue still happens?

**Comment by winnipeg21** [comment]
Just tried locally on my PC, it doesn't happen so I guess that rules out Via. Only issue I have rn is what could actually be causing it since I have limited plugins on my proxy. 

![velocity plugin list](https://i.pingu.ga/5rlghk)

**Comment by winnipeg21** [comment]
Only thought it was Via (still could be via + another plugin) because that was the only thing I updated before it broke.
