### ISSUE TITLE
tryed interacting with my skript gui

### ISSUE THREAD

**Issue by gigachad2** [ViaVersion/ViaVersion#2889]
### `/viaversion dump` Output

https://dump.viaversion.com/047e1c3febcfc1969618f0ea97eeb76d87d51937d4175eaf220fbcb16b7d166a

### Console Error

GigaChad6942 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$2 (Anonymous)}

### Bug Description

made a skript for a prisons system and i interact with it then i get kicked by viaversion and says to report it

### Steps to Reproduce

with my skript i:
did the command prefix (/mines)
clicked on the second slot
get kicked by via version

### Expected Behavior

should teleport you to mine b warp 

### Additional Server Info

using bungeecord with worldedit viaversion viabackwards vault skript multiverse luckperms headdatabase fast chink pregen essentials x

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--411%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--411%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.2.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.2.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by gigachad2** [comment]
it only did it the one time but i thought i should report it either way

**Comment by FormallyMyles** [comment]
If you're able to provide steps, we can look into / full error, we can look into further
