### ISSUE TITLE
When using ViaVersion 4.2.1, it allows access to bots.

### ISSUE THREAD

**Issue by MinecraftNight4** [ViaVersion/ViaVersion#2890]
### `/viaversion dump` Output

https://paste.gg/p/anonymous/077b4d6a88544ccc94faede75aec9e18

### Console Error

ViaVersion 4.2.0:
```
Log: https://paste.gg/p/anonymous/231fe8792ebf4dce94c471badaff571b
Timings: https://timings.aikar.co/?id=b922afa5dee148fc8fbedb42fb4e453e
ViaVersion: https://dump.viaversion.com/63cff986088699b2b6df3218e4e8e263621f4154aed7b2fdd9e2fe8b7c435987)
```

ViaVersion 4.2.1:
```
Log: https://paste.gg/p/anonymous/077b4d6a88544ccc94faede75aec9e18
Timings: https://timings.aikar.co/?id=4257f5d542e54addaf60333482981960
ViaVersion: https://dump.viaversion.com/74ef0f260bf4eb57f89495f0e2da6d2da95b600b8d8e2d77ae48e7838eee2c6a
```

### Bug Description

Since a couple of months we have had some bot attacks on the server. We put an anti-bot plugin and update it frequently, to prevent the server from crashing.

But until a few days ago, we noticed that bot attacks were reaching the server, even with the antibots registering that the connections were disabled.

We tested going back to ViaVersion 4.2.0, and noticed that the antibots were able to register the attacks and stop them. But when trying to use ViaVersion 4.2.1, the antibots fail to repel these attacks.

### Steps to Reproduce

N/A

### Expected Behavior

ViaVersion should reject incoming connections, but instead allows bot accounts to enter the server.

### Additional Server Info

**Version:**
- git-Purpur-1428 (MC: 1.17.1)
- Implementing API version 1.17.1-R0.1-SNAPSHOT
- Git: 9beb23b on ver/1.17.1

**Plugins:**
- AuthMe, floodgate, Geyser-Spigot, GeyserHacks, LuckPerms, Multiverse-Core, Multiverse-NetherPortals, nAntiBot, NexEngine, SunLight, SunLight_Economy, Terra, Vault, ViaVersion, VoidGen, WorldEdit, WorldGuard, WorldGuardExtraFlags

_I've been having this problem for several weeks now, and I'm a bit nervous at this point. Any information you request, I will be delivering it as soon as possible._

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1428%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Purpur--1428%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square) </br>

**Comment by MinecraftNight4** [comment]
Yeah, sure... Check it as closed ¬¬

**Comment by Kichura** [comment]
Your via* is outdated, Otherwise the bot incident is not caused by us.

**Comment by MinecraftNight4** [comment]
> Your via* is outdated, Otherwise the bot incident is not caused by us.

And what is the most recent version? I've already tried installing this version and it doesn't solve the problem I'm having.
https://dump.viaversion.com/2f4dbf0a584843d811b8d6ef60b0645d89734f2e8c2f9325a79687489d6f4302

**Comment by kennytv** [comment]
4.2.1 has exactly one changed line of code compared to 4.2.0 (very much unrelated to anything that could possibly cause this), so the observation makes little sense. ViaVersion doesn't allow or disallow clients to connect, or nullifies disconnects or connection listeners, it just transforms packets
