### ISSUE TITLE
Getting kicked when switching servers (1.19 Pre-release 1)

### ISSUE THREAD

**Issue by pinkpig58** [ViaVersion/ViaVersion#2891]
### `/viaversion dump` Output

https://dump.viaversion.com/31342e73ed6a9e32c67ce33a265da0c67b9f09ab0cc7ccfc3a63755abe4ebea3

### Console Error

```
https://paste.gg/p/anonymous/f0297c8b70614e0e823a3737afa5a350
```

### Bug Description

When switching between servers, I used /server <name> <server>, I get kicked with an error.

### Steps to Reproduce

1. Connect to a Bungeecord server running ViaVersion using the latest 1.19 pre-release
2. Use the /server command to switch to another server on the Network
3. Recieve the kick

### Expected Behavior

Players should be moved to the specified server without being kicked.

### Additional Server Info

I'm using the latest version of BungeeCord and ViaVersion-DEV. There are no plugins installed on either the Proxy or the Spigot servers (apart from Via on the Proxy).
![serverswitchingkick](https://user-images.githubusercontent.com/41856020/169262615-f12c4637-8758-4a9e-8934-46043848b1d1.jpg)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A862bb2a%3A1636](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A862bb2a%3A1636-3498db?style=flat-square) </br>![ViaVersion (4.3.0-1.19-pre1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.3.0--1.19--pre1--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Bungeecord does not support snapshots.

**Comment by kennytv** [comment]
Fixed in the latest dev build, https://github.com/ViaVersion/ViaVersion/commit/9aa7f5e879e6defb4456217b7952ddfdee5c546f
