### ISSUE TITLE
Placing painting crashes client (1.19 Pre-release 1)

### ISSUE THREAD

**Issue by pinkpig58** [ViaVersion/ViaVersion#2893]
### `/viaversion dump` Output

https://dump.viaversion.com/31342e73ed6a9e32c67ce33a265da0c67b9f09ab0cc7ccfc3a63755abe4ebea3

### Console Error

```
The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Invalid entity data item type for field 8 on entity bnj['Allay'/2, l='ClientLevel', x=-8.50, y=-58.50, z=-4.50]: old=0(class java.lang.Byte), new=Reference{ResourceKey[minecraft:painting_variant / minecraft:plant]=bps@4eb32d54}(class hc$c)
Exit Code: -1
```

### Bug Description

Placing paintings in the newest pre-release crashes client.
I put the error in the console error section.

### Steps to Reproduce

1) Connect to a server using the newest Pre-release
2) Place a painting
3) Get kicked

### Expected Behavior

Painting should place and not crash client.

### Additional Server Info

I'm using the latest version of BungeeCord and ViaVersion-DEV. There are no plugins installed on either the Proxy or the Spigot servers (apart from Via on the Proxy).

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by pinkpig58** [comment]
Sorry, wrong dump: https://dump.viaversion.com/375d301d6545c56577eb808af67f4f32acc1dd39a786bce4dd4d394dd8f49289

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A862bb2a%3A1636](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A862bb2a%3A1636-3498db?style=flat-square) </br>![ViaVersion (4.3.0-1.19-pre1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.3.0--1.19--pre1--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Thanks, fixed
