### ISSUE TITLE
Switching to a server while being teleported crashes client (1.19 Pre-release 1)

### ISSUE THREAD

**Issue by pinkpig58** [ViaVersion/ViaVersion#2894]
### `/viaversion dump` Output

https://dump.viaversion.com/fe7c3287ab696173159a599bd073bf9a4c58c22505386ba942638a0b71b3050e

### Console Error

```
The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Invalid entity data item type for field 19 on entity ewv['Username'/5, l='ClientLevel', x=0.00, y=31.00, z=0.00]: old=Optional.empty(class java.util.Optional), new={}(class pj)
Exit Code: -1
```

### Bug Description

When switching to a server (using BungeeCord) that sends players to another world on join, it crashes the client.

So, instead of being sent to the default world specified in server.properties, the plugin is redirecting them on PlayerJoinEvent.

**onEnable - the following is ran:**
Bukkit.getServer().createWorld(new WorldCreator("testWorld"));

onJoin - the player is teleported:
Location l = new Location(Bukkit.getWorld("testWorld"), 0, 4, 0);
e.getPlayer().teleport(l);

### Steps to Reproduce

1) Join a Bungeecord server running ViaVersion
2) Connect to a server on the network that sends the player to a different world on join
3) Receive the crash

### Expected Behavior

The player should connect to the server normally, and be teleported to the world the plugin has sent them to.

### Additional Server Info

I'm using the latest version of BungeeCord and ViaVersion-DEV. The Spigot server I'm connecting to when getting this crash is running 1.12.2.

The Proxy is only running ViaVersion.
The Spigot server is running a simple plugin with only the events and methods I put in Bug Description.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A862bb2a%3A1636](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A862bb2a%3A1636-3498db?style=flat-square) </br>![ViaVersion (4.3.0-1.19-pre1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.3.0--1.19--pre1--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>
