### ISSUE TITLE
Entities spawned with no AI have incorrect Pitch (1.19 Pre-release 1)

### ISSUE THREAD

**Issue by pinkpig58** [ViaVersion/ViaVersion#2896]
### `/viaversion dump` Output

https://dump.viaversion.com/2797c894e126e5d06f4ae38f015498973db688e7f3bdcf484005a2b301d50b00

### Console Error

```
No errors.
```

### Bug Description

When spawning an entity on a 1.12.2 server, 1.19 clients don't them with the correct pitch.

Entity spawned with this method:
```
Player p = e.getPlayer();
Entity villager = p.getWorld().spawnEntity(p.getLocation(), EntityType.VILLAGER);
Villager v = (Villager) villager;
v.setAI(false);
```

### Steps to Reproduce

1) Connect using 1.19 pre-release 1
2) Spawn an AI-less entity using the method above
3) See it have the incorrect pitch

### Expected Behavior

1.19 players should be able to see the pitch assigned to an AI-less mob.

### Additional Server Info

I'm using the latest version of BungeeCord and ViaVersion-DEV. The Spigot server is running 1.12.2 with a simple plugin only containing the method in Bug Description.
![villager](https://user-images.githubusercontent.com/41856020/169475805-799e2592-9d52-4933-8c92-ef3fa8f8f549.jpg)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A862bb2a%3A1636](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A862bb2a%3A1636-3498db?style=flat-square) </br>![ViaVersion (4.3.0-1.19-pre1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.3.0--1.19--pre1--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
wow, I looked into this for over 2 hours a week ago, now I found the cause in the first 10 seconds of opening the project

**Comment by kennytv** [comment]
... also, thank you for taking the time to find and report all of these issues in a sane way

**Comment by Kichura** [comment]
It's free real estate.

**Comment by pinkpig58** [comment]
All good, happy to help in anyway I can 🙂
