### ISSUE TITLE
Setting a block in a world makes it invisible (1.19 Pre-release 1)

### ISSUE THREAD

**Issue by pinkpig58** [ViaVersion/ViaVersion#2897]
### `/viaversion dump` Output

https://dump.viaversion.com/4d7568ea590edb689e5677aa7c3e405054731e25863c183464f99bc91483271e

### Console Error

```
No error.
```

### Bug Description

When a block is set in the world, 1.19 players cannot see it which makes them glitch when they go near it.
Reconnecting, however, shows the block as expected.

I ran **e.getBlock().setType(Material.STONE);** on the BlockBreakEvent (even with a delay) to replace any block broken, but it shows invisible to 1.19 players.

### Steps to Reproduce

1) Create a method to set a block in the world
2) Connect to the server
3) See that it's invisible when placed but shows on reconnect

### Expected Behavior

The block should not be invisible.

### Additional Server Info

I'm using the latest version of BungeeCord and ViaVersion-DEV. The Spigot server is running 1.12.2 with a simple plugin only containing the method in Bug Description.

https://user-images.githubusercontent.com/41856020/169482729-cc6002ba-e558-4fea-af24-20a77fc33e41.mp4

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A862bb2a%3A1636](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A862bb2a%3A1636-3498db?style=flat-square) </br>![ViaVersion (4.3.0-1.19-pre1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.3.0--1.19--pre1--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Fixed in https://github.com/ViaVersion/ViaVersion/commit/3d3e09977cfc1e2826ce31689d8ff06a25c62654
