### ISSUE TITLE
Sending a TextComponent message on join crashes client (1.19 Pre-release 1)

### ISSUE THREAD

**Issue by pinkpig58** [ViaVersion/ViaVersion#2898]
### `/viaversion dump` Output

https://dump.viaversion.com/4f0bd42dd3da35b0ef5ee4a4920197faf7517065cac24d372cbe67f68c885cfe

### Console Error

```
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "etj.s()" because "this.g" is null
Exit Code: -1
```

### Bug Description

When sending a message through a BungeeCord plugin using **PostLoginEvent**, the client crashes.

```
@EventHandler
public void onJoin(PostLoginEvent e) {
      TextComponent message = new TextComponent("Hello world");
      e.getPlayer().sendMessage(message);
}
```

### Steps to Reproduce

1) Create a Bungee plugin that sends a message on join
2) Join the BungeeCord server
3) Receive the crash

### Expected Behavior

The client should not crash.

### Additional Server Info

I'm using the latest version of BungeeCord and ViaVersion-DEV. The Spigot server is running 1.12.2 with a simple plugin only containing the method in Bug Description.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A862bb2a%3A1636](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A862bb2a%3A1636-3498db?style=flat-square) </br>![ViaVersion (4.3.0-1.19-pre1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.3.0--1.19--pre1--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>
