### ISSUE TITLE
Unable to connect on newest pre-release (1.19 Pre-release 2)

### ISSUE THREAD

**Issue by pinkpig58** [ViaVersion/ViaVersion#2899]
### `/viaversion dump` Output

https://dump.viaversion.com/f5c5aabbb63f21141fe2b2726a34d59ffca2af05602eaa64f0e923107efa3694

### Console Error

```
No errors are shown in the console.
```

### Bug Description

When attempting to connect to a server running BungeeCord and ViaVersion, I'm unable to connect. 

### Steps to Reproduce

1) Create BungeeCord server with ViaVersion
2) Attempt to connect

### Expected Behavior

You should be able to connect to the server.

### Additional Server Info

I'm using the latest version of BungeeCord and ViaVersion-DEV. I'm attempting to connect to a 1.12.2 server. No other plugins are installed.
![connectError](https://user-images.githubusercontent.com/41856020/169875511-f8257fa2-174a-47f0-aa2b-9861e525be92.jpg)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A862bb2a%3A1636](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A862bb2a%3A1636-3498db?style=flat-square) </br>![ViaVersion (4.3.0-1.19-pre2-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.3.0--1.19--pre2--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>
