### ISSUE TITLE
Error with TCP-Shield and Client-Version 1.19 PRE3

### ISSUE THREAD

**Issue by Minzilein2003** [ViaVersion/ViaVersion#2904]
### `/viaversion dump` Output

https://dump.viaversion.com/939fe8d20e4fc9f4ca0a39207752e9e1a96382b2ca688920415b8053dec00287

### Console Error

```
[30.05.22][03:32:14 INFO]: [/XXXX:54632] <-> InitialHandler has connected
[30.05.22][03:32:14 WARN] [ViaVersion]: ERROR IN Protocol1_19To1_18_2 IN REMAP OF 0x00->0x00
[30.05.22][03:32:14 WARN]: [/XXXXXX:54632] <-> InitialHandler - could not decode packet! com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[30.05.22]{Packet Type: null, Type: Boolean, Data: [Pair{Type|String, Jkobs}], Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.Protocol1_19To1_18_2$10 (Anonymous), Packet ID: 0}
[30.05.22]Actual Error
```

### Bug Description

I am getting this error on join. But this error only occurs in combination with TCP-Shield. Attached is the transcript of the ticket saying that the problem is with ViaVersion.

[https://tickettool.xyz/direct?url=https://cdn.discordapp.com/attachments/818543625477947415/980646933775396944/transcript-ticket-4777.html](https://tickettool.xyz/direct?url=https://cdn.discordapp.com/attachments/818543625477947415/980646933775396944/transcript-ticket-4777.html)

### Steps to Reproduce

1. A TCP-Shield protected MC-Waterfall proxy
2. Login with MC-Client 1.19 PRE 3
3. See Error in Console (Can´t Join)

### Expected Behavior

I want to join with MC client version 1.19 PRE 3

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.18--R0.1--SNAPSHOT%3Ad79d5f1%3A486](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.18--R0.1--SNAPSHOT%3Ad79d5f1%3A486-3498db?style=flat-square) </br>![ViaVersion (4.3.0-1.19-pre3-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.3.0--1.19--pre3--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>![ViaBackwards(4.3.0-1.19-pre2-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.3.0--1.19--pre2--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Either that's because the proxy itself still needs to support 1.19 (since snapshots on proxies are funky), or TCPShield hasn't done the required changes (seeing another TCPShield employee asking questions regarding this somewhere else). Or or some other plugin is messing with protocol, but that'd be for you to find out by removing other plugins
