### ISSUE TITLE
Cannot join server

### ISSUE THREAD

**Issue by GamingcodeYT** [ViaVersion/ViaVersion#2906]
### `/viaversion dump` Output

https://dump.viaversion.com/0c611bafd37769ac70170f75d93bfa683b1905a339d0e0c01cbab5600ca59e51

### Console Error

02.06 08:27:27 [Server] WARN io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
02.06 08:27:27 [Server] INFO {Packet Type: CLIENT_SETTINGS, Type: Unsigned Byte, Data: [Pair{Type|String, en_us}, Pair{Type|Byte, 8}, Pair{Type|VarInt, 0}, Pair{Type|Boolean, true}], Source 0: com.viaversion.viaversion.protocols.protocol1_18to1_17_1.Protocol1_18To1_17_1$1 (Anonymous), Packet ID: 5}
02.06 08:27:27 [Server] INFO Actual Error:
02.06 08:27:27 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480)
02.06 08:27:27 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
02.06 08:27:27 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
02.06 08:27:27 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
02.06 08:27:27 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
02.06 08:27:27 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
02.06 08:27:27 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
02.06 08:27:27 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
02.06 08:27:27 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
02.06 08:27:27 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
02.06 08:27:27 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
02.06 08:27:27 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
02.06 08:27:27 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
02.06 08:27:27 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
02.06 08:27:27 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
02.06 08:27:27 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
02.06 08:27:27 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
02.06 08:27:27 [Server] WARN at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
02.06 08:27:27 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
02.06 08:27:27 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
02.06 08:27:27 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
02.06 08:27:27 [Server] WARN at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
02.06 08:27:27 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
02.06 08:27:27 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
02.06 08:27:27 [Server] WARN at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
02.06 08:27:27 [Server] WARN at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
02.06 08:27:27 [Server] WARN at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
02.06 08:27:27 [Server] WARN at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
02.06 08:27:27 [Server] WARN at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
02.06 08:27:27 [Server] WARN at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
02.06 08:27:27 [Server] WARN at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
02.06 08:27:27 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
02.06 08:27:27 [Server] WARN Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
02.06 08:27:27 [Server] INFO {Packet Type: CLIENT_SETTINGS, Type: Unsigned Byte, Data: [Pair{Type|String, en_us}, Pair{Type|Byte, 8}, Pair{Type|VarInt, 0}, Pair{Type|Boolean, true}], Source 0: com.viaversion.viaversion.protocols.protocol1_18to1_17_1.Protocol1_18To1_17_1$1 (Anonymous), Packet ID: 5}
02.06 08:27:27 [Server] INFO Actual Error:
02.06 08:27:27 [Server] WARN Caused by: java.lang.IndexOutOfBoundsException: readerIndex(10) + length(1) exceeds writerIndex(10): PooledUnsafeDirectByteBuf(ridx: 10, widx: 10, cap: 256)
02.06 08:27:27 [Server] WARN at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
02.06 08:27:27 [Server] WARN at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730)
02.06 08:27:27 [Server] WARN at io.netty.buffer.AbstractByteBuf.readUnsignedByte(AbstractByteBuf.java:744)
02.06 08:27:27 [Server] WARN at com.viaversion.viaversion.api.type.types.UnsignedByteType.read(UnsignedByteType.java:36)
02.06 08:27:27 [Server] WARN at com.viaversion.viaversion.api.type.types.UnsignedByteType.read(UnsignedByteType.java:29)
02.06 08:27:27 [Server] WARN at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135)
02.06 08:27:27 [Server] WARN at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.lambda$map$0(PacketRemapper.java:47)
02.06 08:27:27 [Server] WARN at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
02.06 08:27:27 [Server] WARN at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
02.06 08:27:27 [Server] WARN at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:376)
02.06 08:27:27 [Server] WARN at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
02.06 08:27:27 [Server] WARN at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
02.06 08:27:27 [Server] WARN at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118)
02.06 08:27:27 [Server] WARN at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298)
02.06 08:27:27 [Server] WARN at com.viaversion.viaversion.connection.UserConnectionImpl.transformServerbound(UserConnectionImpl.java:282)
02.06 08:27:27 [Server] WARN at com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:55)
02.06 08:27:27 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
02.06 08:27:27 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
02.06 08:27:27 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
02.06 08:27:27 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
02.06 08:27:27 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

### Bug Description

Cannot join server

### Steps to Reproduce

Login with 1.18.2
Try to join server with the newest viaversion

### Expected Behavior

That i can join?

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--NachoSpigot--%225655b72%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--NachoSpigot--%225655b72%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
Either you have a bad client or one of your plugins is messing with packets... also make sure you don't reload Via, especially not with PlugMan
