### ISSUE TITLE
Support the translation of custom blocks and item tags from 1.8 to 1.12.

### ISSUE THREAD

**Issue by wifi-left** [ViaVersion/ViaVersion#2907]
### Problem Description

Support the translation of custom blocks and item tags from 1.8 to 1.12.
This is a new function supported by datapacks after 1.13. It can be used in `CanPlaceOn` and `CanDestroy` of items, but versions 1.8~1.12 do not support it, causing some problems.
For example,
```
minecraft:stone
minecraft:oak_sign
```
If you define tags in the data package, it can be very convenient to use like `#minecraft:<tag name>`.

### Solution Description

Translation the custom blocks and item tags.

### Alternatives

Support `replace-adventure` like for 1.7.x.

### Additional Info

[Tag - Minecraft Wiki](https://minecraft.fandom.com/wiki/Tag)

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
If you want to use new features, use/only allow new clients. Due to the effort involved, then hacky nature of trying to reimplement completely non-existent features on those older versions, and the fact Via is platform-independent, we don't do that
