### ISSUE TITLE
Server is still on 1.18.2 when joining from 1.19-rc2

### ISSUE THREAD

**Issue by trickypr** [ViaVersion/ViaVersion#2909]
### `/viaversion dump` Output

https://dump.viaversion.com/d12597c216c8b50fb99def7b950cdc39e8e9ce775b7408829a1aebec9228f442

### Console Error

```
```

### Bug Description

When logging in to the server from the latest release candidate (1.19-rc2), the server returns an error:
> Outdated server! I'm still on 1.18.2

This error does not occur on `1.19-rc1`

### Steps to Reproduce

1. Attempt to log on from 1.19-rc2
2. See the error

### Expected Behavior

Should behave the same between `1.19-rc1` and `1.19-rc2`

### Additional Server Info

We do not have a proxy, it is a paper only server. Other plugins include:
- SimpleHomes
- WorldEdit + WorldGuard
- TabTPS
- EssentialsX
- Geyser-spigot + floodgate
- EntityDetection
- TAB

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--371%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Paper--371%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.3.0-1.19-rc1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.3.0--1.19--rc1--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>
