### ISSUE TITLE
Wrong version range for protocol 4

### ISSUE THREAD

**Issue by HowardZHY** [ViaVersion/ViaVersion#2912]
### Problem Description

only 1.7.2-1.7.5 's protocol is 4 and supported.
1.7(.0)-1.7.1's protocol is 3 and it's not supported

### Solution Description

ProtocolVersion.java:50
public static final ProtocolVersion v1_7_2 = register(4, "1.7.2-1.7.5", new VersionRange("1.7", 2, 5));

### Additional Info

little but correct

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by HowardZHY** [comment]
https://github.com/ViaVersion/ViaVersion/pull/3221
