### ISSUE TITLE
Kick when switching world

### ISSUE THREAD

**Issue by iLemon** [ViaVersion/ViaVersion#2914]
### `/viaversion dump` Output

https://dump.viaversion.com/5410a02c129552bedc5a0d4cd9f515d6a45b39cdccddf2d0382780c5bc0a05c0

### Console Error

https://paste.gg/p/anonymous/84310195164d4c429eaf424ec50f64cf/files/30c445129d7247b9a8732cfd1c7afbfe/raw

### Bug Description

I get kicked when switching worlds on 1.19rc2.

I've tested and the kicking doesn't happen on 1.18.2.

### Steps to Reproduce

1. Run Velocity proxy with the same via plugins as in my dump
2. Run backend server with 1.18.2
3. Login with 1.19 Release Candidate 2
4. Switch world
5. Kicked

### Expected Behavior

You should not be kicked.

### Additional Server Info

I'm running via plugins on the velocity proxy instead of the paper servers.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
That's more or less a Velocity issue, tho they're likely to fix that with proper 1.19 support

**Comment by Celophy** [comment]
I have the same error uscing paper
