### ISSUE TITLE
ViaVersion 4.3.0 crashes Velocity with 1.19 client

### ISSUE THREAD

**Issue by seb303** [ViaVersion/ViaVersion#2915]
### `/viaversion dump` Output

https://dump.viaversion.com/1dd847c60a3bfaa7d8045e74ea519f80ed2a01bee8fa1c3cee687ea89ad91c1d

### Console Error

```
Error on join: https://paste.gg/p/anonymous/fd51f19d66204f1290f4f26fb24c4605
Joined ok, error on change world: https://paste.gg/p/anonymous/e6fff895ef624db9940cb3fdff6ac3ed
```

### Bug Description

Sometimes Velocity crashes immediately when a player joins.
Always it happens when changing worlds.
There are no custom dimensions used on the server, despite the error message.  Just the usual 3.

### Steps to Reproduce

1. Install Velocity 3.1.2-SNAPSHOT with ViaVersion 4.3.0 & ViaBackwards 4.3.0
2. Link to 1.17.1 Paper backend
3. Connect with 1.19 client (the problem does not occur with 1.18.2 or 1.17.1 clients)
5. If the error doesn't appear immediately, try changing worlds.

### Expected Behavior

Crash should not happen (the problem does not occur with 1.18.2 or 1.17.1 clients).

### Additional Server Info

Proxy is Velocity 3.1.2-SNAPSHOT
The following plugins were also installed on the proxy when the logs were recorded: Essential-Playerinfo-Plugin-2.0.1, Geyser-Velocity, floodgate-velocity (both latest snapshot), ViaRewind-2.0.3-SNAPSHOT
Note however the the problem happens just the same with all the above plugins removed.

Backend server is 1.17.1 Paper, with Plugins: AntiCooldown, BuildBattle, Citizens, CoreProtect, Denizen, Depenizen, Duels, ExtraSpecialItems, FireBallKnockback, Gen-Splitter, HubBasics, Images, KeepChunks, LuckPerms, MBedwars, MBedwarsTweaks, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, Parkour, PlaceholderAPI, ProtocolLib, SimpleTpa*, Skript, Skywars, Skywars-Extension*, sleep-most, SlimeWorldManager, TAB, TheBridge, TubeTils, WorldEdit, WorldGuard

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--377e6b66--b140%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--377e6b66--b140%29-3498db?style=flat-square) </br>![ViaVersion (4.3.0): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.0)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.3.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Quantum64** [comment]
The cause of this is OpenNBT's use of a `LinkedHashMap ` for storing a CompoundTag's fields.

Via attempts to find a dimension key by looking up the dimension's tag as a map key (hmmmmm).
https://github.com/ViaVersion/ViaVersion/blob/master/common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19to1_18_2/storage/DimensionRegistryStorage.java#L31

But this lookup will fail if the fields in the tag in a different order since OpenNBT's compound tag is ordered.
https://github.com/GeyserMC/OpenNBT/blob/master/src/main/java/com/github/steveice10/opennbt/tag/builtin/CompoundTag.java#L32

There's no reason to expect a compound's fields to be in any specific order, since vanilla represents compounds with a `Object2ObjectOpenHashMap`. This seems like an OpenNBT issue to me.

**Comment by kennytv** [comment]
The reason for that is Velocity completely scrambling the order and adding outdated/wrong fields

**Comment by kennytv** [comment]
Why not? The client used that same logic for looking up certain things and it's not too hard of a thing to just not completely screw up the nbt data

**Comment by Quantum64** [comment]
Well, the client represents the fields in a compound with an unordered map.

![image](https://user-images.githubusercontent.com/3969183/172456731-8b6f8197-09aa-4910-805b-2e38395fcf6f.png)

So this lookup would succeed on the client regardless of the order. Additionally, the order of this type of map is undefined, and could technically change arbitrarily without mutation, although the `Object2ObjectOpenHashMap` does not do that.

**Comment by Quantum64** [comment]
It's still concerning that OpenNBT and vanilla disagree about compound tag equality. That should probably still be fixed.

**Comment by kennytv** [comment]
Yeah sure, I can look into changing that (tho for the poster, noting that it won't fix this issue)

**Comment by kennytv** [comment]
I now actually checked the code, and order does not matter when checking for equality with OpenNBT/LinkedHashMap either, so no action on our end required, this is 100% on Velocity

**Comment by kennytv** [comment]
Should be mitigated with https://github.com/ViaVersion/ViaVersion/commit/12d538fe0d68327cdea3c3d61601b958c8afdfc1 now since Velocity is taking its good time
