### ISSUE TITLE
ViaVersion does not work on Velocity for 1.19

### ISSUE THREAD

**Issue by train21** [ViaVersion/ViaVersion#2917]
### `/viaversion dump` Output

https://dump.viaversion.com/18310e40c65c0d46086580ac38572174ed26e552c25212e3c58d80a91701a56b

### Console Error

[14:43:23 INFO]: [server connection] train21 -> SMP has disconnected
[14:43:23 ERROR]: [connected player] train21 (/0.0.0.0:56228): disconnected while connecting to SMP: multiplayer.disconnect.incompatible
[14:43:23 INFO]: [connected player] train21 (/0.0.0.0:56228) has disconnected: Unable to connect to SMP: multiplayer.disconnect.incompatible

### Bug Description

When you try to join on 1.19 on a Velocity server, it will display the following error to the user.
https://i.imgur.com/6XuASZV.png

### Steps to Reproduce

1. Login with a Minecraft 1.19 Client
2. Connect to a Velocity server that is connected to a Fabric 1.19 server using Fabric Proxy Lite.
3. Error should show up

### Expected Behavior

Allow user to connect

### Additional Server Info

Using latest Velocity Dev Build since they don't officially support 1.19

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--377e6b66--b140%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--377e6b66--b140%29-3498db?style=flat-square) </br>![ViaVersion (4.3.0): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.0)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by Camotoy** [comment]
We are aware of this issue; it's something Velocity ultimate needs to resolve.
Thank you for reporting anyway!
