### ISSUE TITLE
Cannot join 1.8.9 server with ViaVersion 4.3.0 (#610) via Waterfall using 1.19 client

### ISSUE THREAD

**Issue by KaiKikuchi** [ViaVersion/ViaVersion#2918]
### `/viaversion dump` Output

https://dump.viaversion.com/210a7993606d198d2511e869f93a787381a605033ff391345f3bcc2665ffaecf

### Console Error

Spigot console:
```
[19:05:06 INFO]: KaiNoMood[/(redacted):36471] logged in with entity id 119 at ([world]-0.36241415021810264, 83.86360725816661, 1.2227429023362761)
[19:05:06 INFO]: KaiNoMood lost connection: Internal Exception: java.io.IOException: Error while write(...): Broken pipe
```

Waterfall console:
```
[19:05:06 INFO]: [KaiNoMood] disconnected with: Exception Connecting:QuietException : Unexpected packet received during server login process!
4b00
```

While connecting, the client shows this error:
```
QuietException : Unexpected packet received during server login process!
4b00
```

### Bug Description

1.19 clients cannot join <=1.18.2 paper servers using ViaVersion through Waterfall. 

Test server: Paper 1.8.8 server

Using Minecraft 1.19 client:
- The test server can be joined directly
- The test server cannot be joined through the Waterfall proxy

Using Minecraft 1.18.2 client: the test server can be joined both directly or through the proxy

Minecraft 1.19 clients can join a Spigot 1.19 server through Waterfall just fine.

### Steps to Reproduce

1. Clone and build the latest commit of Waterfall (currently https://github.com/PaperMC/Waterfall/commit/9719e25cd71bc1f117fba5c31a1790a7ea509cc7) and put in the "waterfall" folder
2. Download paper-1.8.8-445 (https://papermc.io/legacy) and put in in the "paper" folder
3. Start the paper server, then stop it
4. Set eula to true, and server.properties' "online-mode" to false
5. Put ViaVersion 4.3.0 (build 610) in the plugins folder
6. Start both the paper server and waterfall server
7. Load Minecraft 1.19 client, and join the proxy at localhost:25577

### Expected Behavior

I expected to be able to join the server!

### Additional Server Info

Running Waterfall, no other plugins on both the proxy or the paper server. Same issue happens on BungeeCord. The same error shows with a Paper 1.18.2 server (build 379, currently latest) while connecting with Minecraft 1.19 client, but it works fine with Minecraft 1.18.2 client.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--445%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.3.0): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.0)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by JCAguilera** [comment]
This happened to me when trying to join my PaperMC 1.17.1 server with ViaVersion 4.3.0, using a 1.19 client through waterfall.

**Comment by firewolf8385** [comment]
Having the same issue with the latest version of Bungeecord. Tried with 1.19 connecting to 1.18.2 and 1.19 connecting to 1.8.9

**Comment by Alex1607** [comment]
I am having the same issue, it seems like using ViaVersion just on the proxy instead of the backend servers is a workaround.

**Comment by KaiKikuchi** [comment]
> I am having the same issue, it seems like using ViaVersion just on the proxy instead of the backend servers is a workaround.

Thanks for mentioning that but, on my production server, I need ViaVersion on the backend because it is a dependency of other plugins!

**Comment by KillerGamerPls** [comment]
I have the same problem, I can't connect with the client, I think the problem is due to ViaVersion because removing it works.

**Comment by MrButtersDEV** [comment]
Also happens on 1.16.4 servers when joining with 1.19

**Comment by elkoyofficial** [comment]
> Also happens on 1.16.4 servers when joining with 1.19

1.18.2 as well!
