### ISSUE TITLE
Getting kicked when trying to trade with a villager

### ISSUE THREAD

**Issue by Sombrerian** [ViaVersion/ViaVersion#2919]
### `/viaversion dump` Output

https://dump.viaversion.com/f76b3aebbfcb8108fc03d42c7b80918eff45ac7612b2c914aba334f4ea05eeff

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

If the villager offers you an enchanted book, you will get disconnected with the following error: https://prnt.sc/F1BE46uIpnfw. This only happens on 1.19.

### Steps to Reproduce

1) Spawn a villager
2) Place a lectern next to it and let it get librarian profession
3) Trade until enchanted books appear

### Expected Behavior

Disconnect

### Additional Server Info

The only plugins installed are latest ViaVersion with latest ViaBackwards on latest Paper 1.18.2

This also happens on our Latest WaterfallMC <-> Latest Paper 1.18.2, however; the error is a little different: https://media.discordapp.net/attachments/316208160232701955/983810226920767559/unknown.png?width=982&height=136

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Ibotmealot** [comment]
can replicate, vanilla 1.19 client on a 1.18.2 purpur server. 
![image](https://user-images.githubusercontent.com/42391199/172494134-e30b44df-746d-4ef4-b776-8d65e0c5cc0f.png)

**Comment by SavageCabbage64** [comment]
I am having this issue too the server gets Downstream packet error! Cannot invoke "com.github.steveice10.mc.protocol.data.game.level.event.LevelEvent.ordinal()" because "this.event" is null

the client gets "internal exception io.netty.handler.codec.decoderexception z: loading nbt data"
