### ISSUE TITLE
Bedrock players crashing upon death

### ISSUE THREAD

**Issue by Impactic48** [ViaVersion/ViaVersion#2920]
### `/viaversion dump` Output

https://dump.viaversion.com/8606e03b9ba650c4d6d438e20c970441127b3f9b4a6960d789658be7c8e8d500

### Console Error

```
https://paste.gg/p/anonymous/f15062f9f30c45f297b8073ee995957a
```

### Bug Description

Bedrock players crash when they die and this error pops up on the proxy.

### Steps to Reproduce

1. Login with bedrock
2. Die with your bedrock account (If it doesn't crash, die with an end crystal)
3. It should crash your bedrock client

### Expected Behavior

Bedrock players should not crash upon death.

### Additional Server Info

I use Purpur 1.18.2 on my server.
Plugins: https://gyazo.com/1d40de10b52cea5c85158e0691bd87a7

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--44dc2e7c--b131%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--44dc2e7c--b131%29-3498db?style=flat-square) </br>![ViaVersion (4.3.0): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.0)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.3.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-Even%20with%20master-brightgreen?style=flat-square) </br>
