### ISSUE TITLE
Cannot get ID for packet class net.md_5.bungee.protocol.packet.Chat in phase GAME with direction TO_CLIENT

### ISSUE THREAD

**Issue by andrew121410** [ViaVersion/ViaVersion#2921]
### `/viaversion dump` Output

https://dump.viaversion.com/d9fccf62e922a9b7a22dd54dfe91a4e2c1cd733e88a39fec7517592835ae1ed4

### Console Error

```
https://paste.gg/p/anonymous/8aabf910dacc48daa05b5758ee063243
```

### Bug Description

My servers are running on 1.18.2. ViaVersion is on Waterfall 1.19. This error happens when I try to login into the server

### Steps to Reproduce

Make a 1.18.2 server
Use latest Waterfall 1.19
Download ViaVersion into the plugins directory of Waterfall
Try to login into the server.

### Expected Behavior

Login should just login without throwing exception

### Additional Server Info

(Can be found in the paste.gg)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A0e38b9b%3A490](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A0e38b9b%3A490-3498db?style=flat-square) </br>![ViaVersion (4.3.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by andrew121410** [comment]
Wait a second this might be because of my plugin lol

**Comment by andrew121410** [comment]
Ok going back to `git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488` instead of `git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490` doesn't cause the error to happen. So I'm guessing this is a Waterfall 1.19 issue

**Comment by Random4User** [comment]
https://github.com/SpigotMC/BungeeCord/issues/3317

**Comment by andrew121410** [comment]
https://github.com/PaperMC/Waterfall/commit/59dbd0833d2d681d65403819b0ead83094e18237

Seems to fix it
