### ISSUE TITLE
Protocolize Incompatibility

### ISSUE THREAD

**Issue by CodfishBender** [ViaVersion/ViaVersion#2924]
### `/viaversion dump` Output

https://dump.viaversion.com/44910e3f4d301161f25b41686215f6fbcd18c370b74707dc536760ab55d0a1ff

### Console Error

```
19:02:19 [INFO] [Eroserv,/127.0.0.1:1204] <-> InitialHandler has connected
19:02:19 [INFO] [Eroserv] <-> ServerConnector [hub] has connected
19:02:19 [WARNING] [Eroserv] <-> DownstreamBridge <-> [hub] - bad packet, are mods in use!? Packet GAME:TO_CLIENT/21 (GeneratedWindowPropertyWrapper) larger than expected, extra bytes: 17
19:02:19 [INFO] [Eroserv] disconnected with: DecoderException : net.md_5.bungee.protocol.BadPacketException: Packet GAME:TO_CLIENT/21 (GeneratedWindowPropertyWrapper) larger than expected, extra bytes: 17 @ io.netty.handler.codec.MessageToMessageDecoder:98
19:02:19 [INFO] [Eroserv] -> UpstreamBridge has disconnected
19:02:19 [INFO] [Eroserv] <-> DownstreamBridge <-> [hub] has disconnected
```

### Bug Description

Players with 1.19 clients are unable to join while Protocolize is on the proxy and ViaVersions is on the server.
Removing ViaVersion from the server solves the error.

**Proxy:** BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT 
**Proxy Plugin:** Protocolize version 2.2.0:315 by Exceptionflug

**Server:** git-Paper-283 (MC: 1.18.2)
**Server Plugin:** ViaVersion v4.3.2-SNAPSHOT

### Steps to Reproduce

1. Create a 1.19 BungeeCord proxy that connects to a single 1.18.2 Paper server.
2. Use Protocolize version 2.2.0 plugin with the 1.19 BungeeCord proxy.
3. Use ViaVersion 4.3.2-SNAPSHOT plugin with the 1.18.2 Paper server.
4. Start the BungeeCord proxy.
5. Start the Paper server.
6. Attempt to connect to the proxy and it will display the error.

### Expected Behavior

The player should be able to connect to the network without any error message.

### Additional Server Info

This was occurred on my live network and I was able to reproduce the issue on my local machine with the 2 plugins.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--283%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Paper--283%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
Have you tested without Protocolize? Does the client get disconnected otherwise?
and have you tested without ViaVersion on a 1.19 server?

I highly suspect this isn't a ViaVersion issue

**Comment by CodfishBender** [comment]
This has been confirmed as a Protocolize issue: https://github.com/Exceptionflug/protocolize/issues/130

Thank you for your time.
