### ISSUE TITLE
System messages being sent to the wrong position with a 1.19 client on a 1.18 server

### ISSUE THREAD

**Issue by PancakeCatsss** [ViaVersion/ViaVersion#2926]
### `/viaversion dump` Output

https://dump.viaversion.com/88b7a4b8d11b0dd871bef32141f1a770a5f052a0d77135db4a1d8cccf9f27844

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Connecting to a server running 1.18 with the client on 1.19 system messages such as /alert from bungeecord the messages are sent to the player via an action bar message. https://imgur.com/a/1WTJKAP

I am aware Bungeecord did have an issue with this but that has since been fixed.

### Steps to Reproduce

1)  Have a Bungeecord server with a 1.18 server linked
2) Install the latest ViaVersion onto the 1.18 server
3) login with 1.19 and type /alert test
4) You will see the message not displayed in chat but in an action bar message

### Expected Behavior

System messages to be displayed in chat not as an action bar.

### Additional Server Info

Latest Bungeecord version build #1644
Server version 1.18.2

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
That's a Bungee issue then

**Comment by PancakeCatsss** [comment]
This was already fixed on Bungeecord

**Comment by PancakeCatsss** [comment]
https://github.com/SpigotMC/BungeeCord/issues/3321#issuecomment-1150910267

**Comment by Gerrygames** [comment]
Still BungeeCords fault. Even if md5 doesn’t agree. Velocity is actively working on the issue:
https://github.com/PaperMC/Velocity/pull/734
