### ISSUE TITLE
Unable to join the server

### ISSUE THREAD

**Issue by Xiostest48** [ViaVersion/ViaVersion#2927]
### `/viaversion dump` Output

https://dump.viaversion.com/4742212c0210c52bd52c5cbe39e0f9c6fdfb91a7b95576a61fe25dfe025cadf6

### Console Error

```
https://pastebin.com/rZX7k26a
```

### Bug Description

A bug appears at a random time that prevents the player from joining the server

### Steps to Reproduce

..

### Expected Behavior

...

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Airplane--%2261ec9b1%22%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Airplane--%2261ec9b1%22%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.2): 8 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.3.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.3.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Most like a plugin sending bad player info, or bad plugin reloading - try without other plugins and a proper restart and if it still occurs we'll reopen the issue

**Comment by Xiostest48** [comment]
re after several restarts with the same plugin the error is still there
