### ISSUE TITLE
Digging Kick with 1.19

### ISSUE THREAD

**Issue by Kroko1337** [ViaVersion/ViaVersion#2928]
### `/viaversion dump` Output

https://i.imgur.com/0Z3ngv3.png

### Console Error

https://i.imgur.com/0Z3ngv3.png

### Bug Description

If you try to break something in 1.19 then you get kicked

### Steps to Reproduce

Try to break block

### Expected Behavior

it breaks without kick

### Additional Server Info

1.8.9

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by HowardZHY** [comment]
u need a dump and console error, client disconnect is not enough

**Comment by kennytv** [comment]
^, otherwise see https://github.com/ViaVersion/ViaVersion/issues/2922

**Comment by Kroko1337** [comment]
> u need a dump and console error, client disconnect is not enough

I dont have dump and console error i can send later

**Comment by HowardZHY** [comment]
u'd better send the /viaver dump link



At 2022-06-09 17:49:07, "Kroko" ***@***.***> wrote:

u need a dump and console error, client disconnect is not enough

I dont have dump and console error i can send later
