### ISSUE TITLE
Throws java.lang.nosuchfieldError:typemappings on startup.

### ISSUE THREAD

**Issue by XinSin-top** [ViaVersion/ViaVersion#2930]
### `/viaversion dump` Output

https://dump.viaversion.com/43261c8c9d9122ab5a2613b75ef4052038d1bce89fe53725f436e42469285db2

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/8150d416ec5b43f08f665d883beae354

### Bug Description

An exception is thrown when the server is started, and BungeeCord can be started normally. At this time, when the player enters bc, the following error will be reported.
Player client version is 1.16.5, fabric0.14.3
excption: disconnected with: Kicked whilst connecting to Survival: Outdated client! Please use 1.16.5

### Steps to Reproduce

Direct start on my server environment is like this

### Expected Behavior

No exception is thrown and the player enters normally

### Additional Server Info

BungeeCord，
plugins： BungeeChat-1.0.3\BungeeSafeguard.main\VersionControl-1.3.3\ViaBackwards-4.2.1\ViaVersion-4.3.1\

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Aff5727c%3A1644](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Aff5727c%3A1644-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.2.1)-Outdated!-red?style=flat-square) </br>

**Comment by XinSin-top** [comment]
nonono
I can't understand what you mean
