### ISSUE TITLE
BukkitViaInjector changes

### ISSUE THREAD

**Issue by BeefDev** [ViaVersion/ViaVersion#2931]
### Problem Description

The BukkitViaInjector and any injector require the ServerConnection object to work. However when theu try to find the getServerConnection method of MinecraftServer, they directly check they return type of the method using = . This makes changing the ServerConnection to a different class impossible without breaking via version.

### Solution Description

Use the Class.isAssignable method inside of equals operator to allow devs to use custom ServerConnection.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
Not enough interest for this to be implemented
