### ISSUE TITLE
BungeeCord messages in actionbar Instead of chat

### ISSUE THREAD

**Issue by penguintijn-nl** [ViaVersion/ViaVersion#2932]
### `/viaversion dump` Output

https://dump.viaversion.com/6a7af91b5a49d9d3e9602db251e008789282b79923f7d6732493e9383e1ba48e

### Console Error

Not important, no errors.

### Bug Description

BungeeCord chat messages appear in the actionbar instead of the chat

### Steps to Reproduce

1. Login on a 1.8.8 PaperSpigot server behind a BungeeCord server with a 1.19 client.
2. Execute a BungeeCord command. (for example: /server)
3. The feedback of the command will be put into the actionbar instead of the chat.

### Expected Behavior

The message should be in the chat not in the actionbar.

### Additional Server Info

I'm using the latest BungeeCord & ViaVersion.

Output of /ver on the 1.8.8 PaperSpigot:
```
This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
```

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
See https://github.com/ViaVersion/ViaVersion/issues/2926#issuecomment-1150942562
