### ISSUE TITLE
Issue with general gameplay mechanics

### ISSUE THREAD

**Issue by RediPanda** [ViaVersion/ViaVersion#2933]
### `/viaversion dump` Output

https://dump.viaversion.com/9cb1004b6fd2ddc2989d733b01b3ddf73118ff780adb907162a75eb0b8f02f9d

### Console Error

https://paste.gg/p/anonymous/350b87aa8dcc4f93944369a6de136fce

### Bug Description

(Geyser-based): When moving to new dimensions or simply dying in the world, the player is greeted with the red:
"An internal error occurred in your connection".

### Steps to Reproduce

1. Login with Minecraft Bedrock (1.19.0)
2. Move to a new dimension (nether) or die in the world.
3. Done! You have been kicked from the server.

### Expected Behavior

Simply handle the game session as intended. If I die, I should respawn in the world. 

If I enter the nether, then I should be located in the Nether.

### Additional Server Info

ViaVersion and Geyser is operating on the proxy-level services. We are running the latest for Geyser, and latest from Jenkins for Viaversion. The proxy is Velocity-based and is also running on the latest stable version.

All backend services are running on the latest Purpur software.

Plugins on the Velocity Network includes:
 - Bungeecord-Prometheus-Exporter
 - Floodgate-Velocity.
 - Geyser-Velocity.
 - GeyserSkinManager-Velocity.
 - KauriVPN
 - LuckPerms-Velocity
 - MiniMOTD-Velocity
 - ViaVersion

I have tried to Google this issue myself and searched through the Discord but couldn't find anything relating to my issue, nor any FAQ. I hope this would be the right place to put it.

Just to note, everything was working fine before the 1.19 update rolled out. Most likely had to update ViaVersion and Geyser to support the newer clients from connecting to the network.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--05d19384--b125%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--05d19384--b125%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
That's a Velocity issue until it updates to 1.19

**Comment by RediPanda** [comment]
Ah figured. Thank you for providing me a quick response to the issue.
