### ISSUE TITLE
Cannot using 1.19 to join a 1.16.5 server via Bungeecord

### ISSUE THREAD

**Issue by disymayufei** [ViaVersion/ViaVersion#2936]
### `/viaversion dump` Output

https://dump.viaversion.com/1b95eb8eb6ece94a33f84b8d7594db776eeeba22310800bc5f1e276291343c65

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Cannot using 1.19 to join a 1.16.5 server,showing "Internal Exception:io.netty.handler.codec.DecoderException: Received unexcepted null component" error on the screen

### Steps to Reproduce

1. Running the bungeecord(latest version:#1644)
2. Making the bungeecord point to a 1.16.5 spigot server which has loaded the viaversion plugin V4.3.1 and running on java8
3. Using Minecraft 1.19 to join the bungeecord
4. Then the error:"Internal Exception:io.netty.handler.codec.DecoderException: Received unexcepted null component" will be shown on the screen
5. If changing the Minecraft to any another version（like 1.16.5 or 1.18.2）at the step 3, the problem will NOT occur!

### Expected Behavior

Should join the server successfully

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3096a--Spigot--9fb885e--af1a232%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-3096a--Spigot--9fb885e--af1a232%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
> I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
