### ISSUE TITLE
Internal Exception in Minecraft Client when connecting to 1.16.5 Server

### ISSUE THREAD

**Issue by Tux2** [ViaVersion/ViaVersion#2939]
### `/viaversion dump` Output

https://dump.viaversion.com/cc0a2cc9b3f60f853a4e47ffa8988cdda070fc2ad034b5c4a0495e560a4d6093

### Console Error

```
[Client Log](https://paste.gg/p/anonymous/da8fc8b843524c20bf4d2607aba86795)
```

### Bug Description

When trying to connect to my server which is on Spigot 1.16.5 with Minecraft 1.19 it keeps kicking me with this error in the client:
Connection Lost
Internal Exception: io.netty.handler.codec.DecoderException:
java.io.IOException: Packet 0/60 (va) was larger than I expected, foun 137 bytes extra whilst reading packet 60

### Steps to Reproduce

1. Log in to 1.16.5 server with 1.19 clien
2. Client gets kicked with error message

### Expected Behavior

Client should connect without being kicked

### Additional Server Info

I use bungeecord connecting to the lobby server which is running 1.16.5

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by TDMidkwhatisxd** [comment]
Temporary Fix, Disable any titles in game. It happened to me with BetterRTP and i disable Title. Now it works.

**Comment by 2001zhaozhao** [comment]
Packet 60 (0x3C) is the resource pack send packet in the 1.18 protocol. I got the same error and it was caused by having a BungeeCord resource pack plugin that was not yet updated to 1.19. It's unrelated to viaversion, as I have it installed on Spigot servers. Updating my resource pack plugin solved the issue.

**Comment by FormallyMyles** [comment]
Going to close as it's most likely similar to what 2001zhaozhao stated, ensure your bungee plugins are updated with this specific error.
