### ISSUE TITLE
ViaVersion [Server: 1.18.2 - git-Paper-333, Client: 1.19]

### ISSUE THREAD

**Issue by MrJoinYT** [ViaVersion/ViaVersion#2943]
### `/viaversion dump` Output

https://dump.viaversion.com/69740caaebfefaa3844d554bc909c2f2e9e043855b460caeaaf248d7f27c9393

### Console Error

```
https://paste.gg/p/anonymous/c4bd95952b2249f49f4105e675f8fa1b
```

### Bug Description

The client does get disconnected from the server, with no clientside error, only showing: "Disconnected"
I am using the newest version of Viaversion, Viabackwards and Spigot, as well as the newest version of 1.19.

### Steps to Reproduce

Use a 1.19 Client, use the newest Version of Viaversion, (server running spigot 1.18.2 - git 333)
Using a bungeecord server (Bungeecord: git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:862bb2a:1636)

Start the proxy and the normal server, and connect.
![image](https://user-images.githubusercontent.com/71146533/173180782-82da0f55-2bad-4a8e-9db7-c129822dc6d2.png)

### Expected Behavior

The Player should be able to connect to the network. It is working on all other versions.
(Older ones down to 1.9)

### Additional Server Info

I am using A bungeecord proxy, with: (all on the newest version)
BungeeMotd
BungeeChat
BungeeKickListener

My Lobby is using: (all on the newest version)
Citiziens
DiscordSRV
EssentialsX
LuckPerms
LuckTab
ViaVersion
ViaBackwards
Vault
WorldGuard
FastAsyncWorldEdit

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--333%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Paper--333%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.3.0): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by MrJoinYT** [comment]
I tried both already

**Comment by kennytv** [comment]
Your Bungee is outdated as well

**Comment by MrJoinYT** [comment]
I updated everything (proxy: 488, spigot: 379), still occuring.

**Comment by MrJoinYT** [comment]
[10:57:18 WARN]: [/127.0.0.1:60385] <-> InitialHandler - bad packet, are mods in use!? Couldn't read all bytes from a packet. For more information, launch Waterfall with -Dwaterfall.packet-decode-logging=true

**Comment by Kichura** [comment]
Not the latest bungee, Please see [this build](https://api.papermc.io/v2/projects/waterfall/versions/1.19/builds/493/downloads/waterfall-1.19-493.jar) instead.
