### ISSUE TITLE
Nothing happens when trading with villagers on 1.19 client (server 1.18.2)

### ISSUE THREAD

**Issue by UnitedCraft** [ViaVersion/ViaVersion#2946]
### `/viaversion dump` Output

https://dump.viaversion.com/5f09deb19c475d874140680dee0d4ce43a6f0f68e8e154695fc233ba4391f3a4

### Console Error

```
No errors
```

### Bug Description

The problem is that when trading with villagers nothing happens, items are returned to their inventory as if trading was not possible at all. I have the latest viaversion and viabackwards. This only happens when the player is running version 1.19 (the game engine is at 1.18.2)

### Steps to Reproduce

1. Trade with villagers to get emerald

### Expected Behavior

Complete trade

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1632%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Purpur--1632%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.3.0): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by UnitedCraft** [comment]
https://dump.viaversion.com/5f09deb19c475d874140680dee0d4ce43a6f0f68e8e154695fc233ba4391f3a4

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1632%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Purpur--1632%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.3.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.3.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
That was fixed with ci builds, otherwise it's a plugin issue
