### ISSUE TITLE
Critical bug when changing the world.

### ISSUE THREAD

**Issue by AVuTuVA** [ViaVersion/ViaVersion#2947]
### `/viaversion dump` Output

https://dump.viaversion.com/155176f00866e0710d5937843ed2087cc075dd85076837c3a18c0d6b1467b6e5

### Console Error

There is no error in the console, it just kicks the player..

### Bug Description

Kicks the player!
![image](https://user-images.githubusercontent.com/66278054/173224328-3227dc8f-4184-4a14-8068-b1a6e0cadf74.png)

### Steps to Reproduce

You put ViaVersion on the server 1.18.2 and enter the server from version 1.19 and change the world.

### Expected Behavior

That the world will change, without mistakes

### Additional Server Info

Velocity.
![image](https://user-images.githubusercontent.com/66278054/173224293-fbe0fec3-d974-4b38-b5ea-58185ca97fb0.png)

But add-ons are on the server, not on the proxy.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [x] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PufferfishPlus--18%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--PufferfishPlus--18%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.3.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.3.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
There definitely will be an error in the console, which we need

**Comment by AVuTuVA** [comment]
I solved the problem, it turns out I just had ViaFabric enabled for version 1.18.2, turning it off saved me from this problem.
