### ISSUE TITLE
IOOBE remapping chunk data

### ISSUE THREAD

**Issue by Aurelien30000** [ViaVersion/ViaVersion#2948]
### `/viaversion dump` Output

https://dump.viaversion.com/b6c9cc3241175609d63790997cb32cd9e7d7ca3b4615868c893ce46c8acea7a3

### Console Error

```
https://paste.domicraft.fr/diyokucuri.md
```

### Bug Description

1.19 client is kicked out of the server (1.18.2) if a packet with empty chunk (named buffer) is sent.
This is caused by a special plugin, PlotHider. Since it is a very edge case, no problem if this issue can't be fixed or addressed in fact.

### Steps to Reproduce

- Make the ``buffer`` array of a ``ClientboundLevelChunkPacketData`` packet a new empty array of the same size, using ProtocolLib for example.

### Expected Behavior

No error ;)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--379%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Paper--379%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
This means a byte array of size 0 was set, which, no
