### ISSUE TITLE
Unable to join 1.18.2 Server + Stacktrace

### ISSUE THREAD

**Issue by skw359** [ViaVersion/ViaVersion#2952]
### `/viaversion dump` Output

https://dump.viaversion.com/496fec696aa5e5289ecb84ba7f4dbac046df65ea3a071fa8999c9fd2de793725

### Console Error

```
[01:36:10 INFO]: UUID of player Wizz_ is eba3bdc6-6cf3-4f0c-9f21-50a315d9457f
[01:36:10 INFO]: Wizz_ lost connection: Disconnected
```

### Bug Description

I'm not able to join the server using a Velocity proxy and a 1.18.2 server, running the latest versions of Via* as of 6/13/22

### Steps to Reproduce

1. Login with a 1.18.2. - 1.19 client
2. Setup a Velocity proxy + 1.18.2 server with latest versions of Via* on all servers (including proxy)
3. It probably won't work
4. 4. Stacktraces will appear in console of Velocity

### Expected Behavior

Be able to join the server fine

### Additional Server Info

I use the Velocity Proxy, version 3.1.2-SNAPSHOT

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--2fe50bed--b115%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--2fe50bed--b115%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.3.0)-Outdated!-red?style=flat-square) </br>![ViaBackwards(4.3.0): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)
