### ISSUE TITLE
ViaVersion has not loaded the platform yet

### ISSUE THREAD

**Issue by Stormiestaxis1** [ViaVersion/ViaVersion#2953]
### `/viaversion dump` Output

https://dump.viaversion.com/5d56a2d4ebff1490c9595f922950ef151811006fb684f3248e4e0a4c0f49b30c

### Console Error

```
Put the paste.gg link or text here.
```
17:34:45 [SEVERE] java.lang.IllegalArgumentException: ViaVersion has not loaded the platform yet
17:34:45 [SEVERE]     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
17:34:45 [SEVERE]     at us.myles.ViaVersion.api.Via.getAPI(Via.java:48)
17:34:45 [SEVERE]     at net.hepixia.bungeecord.listeners.PostLoginListener.loadPlayerInfo(PostLoginListener.java:214)
17:34:45 [SEVERE]     at net.hepixia.bungeecord.listeners.PostLoginListener.onPlayerPostLogin(PostLoginListener.java:59)
17:34:45 [SEVERE]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:34:45 [SEVERE]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17:34:45 [SEVERE]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:34:45 [SEVERE]     at java.lang.reflect.Method.invoke(Method.java:498)
17:34:45 [SEVERE]     at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
17:34:45 [SEVERE]     at net.md_5.bungee.event.EventBus.post(EventBus.java:49)
17:34:45 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:412)
17:34:45 [SEVERE]     at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:557)
17:34:45 [SEVERE]     at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
17:34:45 [SEVERE]     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
17:34:45 [SEVERE]     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
17:34:45 [SEVERE]     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
17:34:45 [SEVERE]     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
17:34:45 [SEVERE]     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
17:34:45 [SEVERE]     at java.lang.Thread.run(Thread.java:748)

### Bug Description

ViaVersion send me always "ViaVersion has not loaded the platform yet".

### Steps to Reproduce

In my PlayerJoinEvent class on my bungeecord I put: 
            ViaAPI viaAPI = Via.getAPI();
            Integer version = viaAPI.getPlayerVersion(uuid);
                           (null)

### Expected Behavior

I just would like get the player version and it told me "ViaVersion has not loaded the platform yet".

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Aab3ccb8%3A496](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Aab3ccb8%3A496-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
> us.myles.ViaVersion
That's the wrong package, see com.viaversion...

**Comment by Stormiestaxis1** [comment]
It's work thanks you so much !
