### ISSUE TITLE
ERROR IN Protocol1_19To1_18_2 IN REMAP OF CHAT_MESSAGE (0x0F)

### ISSUE THREAD

**Issue by HappyAreaBean** [ViaVersion/ViaVersion#2955]
### `/viaversion dump` Output

https://dump.viaversion.com/825a19305ee99b13716e7375142ea2b86e17a69305ce676fd117da1bad684743

### Console Error

```
[ViaVersion] ERROR IN Protocol1_19To1_18_2 IN REMAP OF CHAT_MESSAGE (0x0F)
```

### Bug Description

No text or message is displayed when the command is entered

### Steps to Reproduce

1. Install [TabTPS](https://www.spigotmc.org/resources/tabtps-1-8-8-1-18-show-tps-mspt-and-more-in-the-tab-menu.82528/) on a 1.8.8 server with ViaVersion installed
2. Join with 1.19 client
3. Type command `/tabtps`
4. No message was displayed

### Expected Behavior

A message should be displayed 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--445%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
We need the full error

**Comment by HappyAreaBean** [comment]
I only see this one message in the console, no stack trace or any other information is shown. Or is there any possible way to get more details about the error?

**Comment by kennytv** [comment]
That means either your server or a plugin is being bad and suppressing the error

**Comment by HappyAreaBean** [comment]
Okay, I found a way to get the full error message 
https://paste.gg/p/anonymous/11d559f86fce4157a961c5d12d5180b8
