### ISSUE TITLE
Bug error

### ISSUE THREAD

**Issue by Maddox22222** [ViaVersion/ViaVersion#2957]
### `/viaversion dump` Output

https://dump.viaversion.com/695a7a3354ecc6d03941d650d690819ca43f74a538b9306e3af95ff44d17e60b

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

https://imgur.com/a/TYsHvbz

Look at the error i get above.

### Steps to Reproduce

1. Login with minecraft 1.19 with a 1.18.1 server.
2. Then try to join and you would get kicked.
3. Then i installed the prevous version back and it worked.

### Expected Behavior

That i can join my server.

### Additional Server Info

I aslo use bungeecord

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--186%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-git--Paper--186%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.2.1)-Outdated!-red?style=flat-square) </br>![PS and ViaBackwards warning](https://img.shields.io/badge/Do%20not%20use%20ProtocolSupport%20and%20ViaBackwards%20together,%20please%20remove%20one%20of%20them-orange?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.2.1)-Outdated!-red?style=flat-square) </br>![ViaRewind(2.0.2): 8 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Maddox22222** [comment]
I think i know how to fix it!

**Comment by Maddox22222** [comment]
nevermind i still get the same error message
