### ISSUE TITLE
Older clients can't write books on 1.19 servers

### ISSUE THREAD

**Issue by xymb-endcrystalme** [ViaVersion/ViaVersion#2959]
### `/viaversion dump` Output

https://dump.viaversion.com/90d412152993779c857a9a13fe560c77216c243637ba3cdf30f54449d3b7fab0

### Console Error

```
[Put the paste.gg link or text here.](https://paste.gg/p/anonymous/3dcc171d400c4d91a7fd8773ad26eaf8)
```

### Bug Description

Older clients (ex. `1.18.2`) get disconnected when trying to sign a writable_book on a `1.19` server.
A first book on the server succeeds, but any subsequent book writes fail with `Internal Exception`.

Also happens on master.

Commenting out `protocol.registerServerbound(ServerboundPackets1_17.EDIT_BOOK` from `BlockItemPackets1_19.java` seems to make books writable again... So that's the hack I'm using. No idea how correct it is.

### Steps to Reproduce

1. Set up Paper 1.19
2. Install ViaVersion and ViaBackwards
3. Connect with 1.18.2 client
4. Write a book - it will succeed
5. Write a book - the client will get kicked

### Expected Behavior

The book writes correctly.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Radi0o** [comment]
i think that 1.19 packets for books are different from 1.18

**Comment by kennytv** [comment]
https://github.com/ViaVersion/ViaBackwards/commit/a1da3dc11c3db88545f5ffb1d41ee0b259b13cbe

**Comment by xymb-endcrystalme** [comment]
So my hack was correct? Nice to know. :D
