### ISSUE TITLE
it disconect on me while i was playing

### ISSUE THREAD

**Issue by oof289** [ViaVersion/ViaVersion#2961]
### `/viaversion dump` Output

https://dump.viaversion.com/8ef62a003d7e99bf3ad92a2d2efe91fa414e61632a9f7451046008b32cd2772a

### Console Error

```
Put the paste.gg link or text here.
```
{Source 0: com.viaversion.viabackwards.protocol.protocol1_10to1_11.packets.PlayerPackets1_11$2 (Anonymous)}

### Bug Description

when I log in on lunar client 1.8.9 I get to play for a little bit and then it kicks me out of the game

### Steps to Reproduce

login with lunar client select 1.8 run it play the game on a server "like poop4821.aternos.me"

### Expected Behavior

it does not respond to right clicks in honey Missle wars

### Additional Server Info

I use aternos which only lets me use 4.3.1 so I can not for some odd reason

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Spigot--9639cf7--4b9bc9d%20%28MC%3A%201.16.1%29](https://img.shields.io/badge/Platform-git--Spigot--9639cf7--4b9bc9d%20%28MC%3A%201.16.1%29-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.3.0): 8 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 8 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
We can't help you if you don't run ci builds, so you'll have to wait for the next release
