### ISSUE TITLE
Disconnects all 1.19 users on commands and maybe more

### ISSUE THREAD

**Issue by kyzzf** [ViaVersion/ViaVersion#2962]
### `/viaversion dump` Output

https://dump.viaversion.com/50cf884922a49846a64867eacaad950dddb58fdbd81f221e1e339ed8d20d20a2

### Console Error

DownstreamBridge <-> [lobby] - could not decode packet! java.lang.IndexOutOfBoundsException: readerIndex(5) + length(75343) exceeds writerIndex(6): PooledSlicedByteBuf(ridx: 5, widx: 6, cap: 6/6, unwrapped: PooledUnsafeDirectByteBuf(ridx: 13044, widx: 29959, cap: 32768))

and sometimes

https://pastebin.com/SuFD5CWN

### Bug Description

Kicks all 1.19 players after automatic teleportation to spawn or any other plugin's command that interfear with a player. It also kicks the player after a while (no commands or teleportation).

### Steps to Reproduce

Example:
1. Install 1.18.2 PaperSpigot
2. Install EssentialsX and ViaVersions
3. Start server and connect 1.19 client and setup an automatic teleportation on join (skript or whatever)
4. Get kicked 

Otherwise:
1&2 As above.
3. Connect 1.19 client and sometimes get "OpenGL Error: 1282 (Invalid operation)" in chat, then get kicked after a while

### Expected Behavior

To not get kicked on join.

### Additional Server Info

I use latest release of waterfall downloaded a minute ago from the papermc website and the latest 1.18.2 paperspigot.
Plugin is shown in the dump.
I only use the latest viaversion (+viarewind,viabackwards) plugin in the paperspigot server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--375%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Paper--375%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.3.0): 8 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 8 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kyzzf** [comment]
Sorry that was the old dump, while I was wroting the report I tried updating the plugin to snapshot versions, the problem is still here.

**Comment by kennytv** [comment]
Not a Via issue

**Comment by kyzzf** [comment]
it is tho, only affects when I update the via plugin
