### ISSUE TITLE
ViaFabric error

### ISSUE THREAD

**Issue by JadssDev** [ViaVersion/ViaVersion#2966]
### `/viaversion dump` Output

HowAmIMeantToProvideThis.com

### Console Error

```
https://paste.gg/p/anonymous/54907c8f7bd54b91921d5c771b431b0c
```

### Bug Description

Joining server on 1.19 using 1.18.2 protocol KICKS instantly while starting to load terrain.

### Steps to Reproduce

1. Set Client-side protocol to 1.18.2
2. Login to server.
3. Get kicked out of the server. (Note: I used Hypixel as my server to join)

### Expected Behavior

I should be able to join the server without getting kicked.

### Additional Server Info

I am running ViaFabric, the error clearly states for me to post it here, so I'm posting it here, I apologize if I'm a stupid idiot, Thank you.

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Most likely a plugin on the server you're joining sending bad chunk data
