### ISSUE TITLE
collision problem of some blocks

### ISSUE THREAD

**Issue by caoli5288** [ViaVersion/ViaVersion#2967]
### `/viaversion dump` Output

https://dump.viaversion.com/012449660599493df09e9e658a5fd9bf7b5486b59afa22053cf177905cf9adcf

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Players will get stuck in some block somehow and cannot leave

### Steps to Reproduce

1. Place a stained_glass_pane or others
2. Walk over it
3. Get stuck

### Expected Behavior

Players should not get stuck

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--NachoSpigot--5655b72%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--NachoSpigot--5655b72%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
Not fixable without server access and hacks, like https://www.spigotmc.org/resources/viaboundingbox.74252/

**Comment by caoli5288** [comment]
@kennytv Do you know any solutions for 1.12.2 - > 1.8.8？
