### ISSUE TITLE
ViaVersion has not loaded the platform yet

### ISSUE THREAD

**Issue by Irritat0r** [ViaVersion/ViaVersion#2968]
### `/viaversion dump` Output

https://dump.viaversion.com/321e598c8e5f8e26992d951f1c92d9df10586824b8c09ef3c2fc28f36f9e67ae

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/251d833ca24240c4bbb4af0bb18f8f0e

### Bug Description

Trying to use API but get error on loading.

code is:

public void onEnable() {
       api = Via.getAPI();

    }

### Steps to Reproduce

1.start server.

### Expected Behavior

Server start with no errors.

### Additional Server Info

I use bungeecord, viaversion on backend servers.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3526--Spigot--56be6a8--3571ca8%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-3526--Spigot--56be6a8--3571ca8%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.3.0): 8 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 8 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
That means you're either accessing the old package or Via didn't load properly. If you use dev builds, make sure all three plugins are dev builds, not just one of them

**Comment by creeper123123321** [comment]
try adding ``softdepend`` in plugin.yml
