### ISSUE TITLE
Error when 1.19 join 1.8.9

### ISSUE THREAD

**Issue by volxymc** [ViaVersion/ViaVersion#2969]
### `/viaversion dump` Output

https://dump.viaversion.com/ea52a80fdaf971d6d695293481c6fd3b909e77b07805aa19fb339da35b1d2788

### Console Error

https://paste.gg/p/anonymous/0f7ca992aedd447bb241d77655231f74

### Bug Description

1.19 Joining a 1.8.9 Java server

### Steps to Reproduce

Login in to 1.18.9
Join a 1.8 server
It crashes

### Expected Behavior

1.19 users to join the 1.8 server

### Additional Server Info

I se a proxy (waterfall)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Aab3ccb8%3A496](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Aab3ccb8%3A496-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.3.0): 8 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 8 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kyzzf** [comment]
This happens when people use waterfall with paperspigot having via.

**Comment by kennytv** [comment]
Was mitigated at some point
