### ISSUE TITLE
1.16.5 Client can't join 1.9.0 spigot server

### ISSUE THREAD

**Issue by RaphiMC** [ViaVersion/ViaVersion#2970]
### `/viaversion dump` Output

https://dump.viaversion.com/647bb262d8d8d5389f381b3ea59edae36f824af7f8611da8eda178bdfa14cd7d

### Console Error

No console error. Client gets disconnected because a packet was too large.

### Bug Description

Try to join with a 1.16.5 client on a spigot 1.9.0 server with ViaVersion installed.
![image](https://user-images.githubusercontent.com/50594595/174845896-ca2de7ba-f581-4ab9-98e0-7401f9956799.png)

### Steps to Reproduce

Start a spigot 1.9.0 server.
Join with 1.16.5 client.

### Expected Behavior

No disconnect

### Additional Server Info

Plugins (1): ViaVersion

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Spigot--7d15d07--c194444%20%28MC%3A%201.9%29](https://img.shields.io/badge/Platform-git--Spigot--7d15d07--c194444%20%28MC%3A%201.9%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by HowardZHY** [comment]
u can test all the 1.9.1,1.9.2,1.9.3,1.9.4 servers if u have time lol

**Comment by Jo0001** [comment]
Spigot 1.9.2 and 1.9.4 are both working

**Comment by HowardZHY** [comment]
Move this to https://github.com/ViaVersion/ViaVersion/issues/3305
