### ISSUE TITLE
ERROR IN Protocol1_18_2To1_19 IN REMAP OF EDIT_BOOK (0x0B)

### ISSUE THREAD

**Issue by SulpherStaer** [ViaVersion/ViaVersion#2971]
### `/viaversion dump` Output

https://dump.viaversion.com/62aaf52997aba8b2c7b9b8ad0c299fe5580b8ab8971f7ac6c9f896794b80de33

### Console Error

https://paste.gg/p/anonymous/a2f90e9357104d43a462109a89a9207e

### Bug Description

Someone tried to open a book and quill of the Statues datapack whilst in 1.18 with the notEnoughAnimationsmod on their end.

### Steps to Reproduce

1. Server on 1.19 that has VanillaTweaks 'Statues' datapack
2. Connect with 1.18.2 client
3. Open statues book

### Expected Behavior

not get disconnected

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.4.7+6--main](https://img.shields.io/badge/Platform-0.4.7+6--main-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.3.0): 8 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)
