### ISSUE TITLE
Mass Player Kick

### ISSUE THREAD

**Issue by lukemango** [ViaVersion/ViaVersion#2972]
### `/viaversion dump` Output

https://dump.viaversion.com/ff3ee3b647e7e3d86451f6ac4cd5361247bf5c0af91dbaf69d4ce5c437e7d830

### Console Error

```
https://paste.gg/p/anonymous/13aa588c5b7944c29d8cc7cba9df65f3
```
![image](https://user-images.githubusercontent.com/29614155/175011415-b2bfff36-2528-44b7-aace-d7319283b85e.png)

### Bug Description

Unsure of the cause, several people were kicked at once alongside a several ViaVersion errors.

### Steps to Reproduce

Unfortunately I am unsure of the cause, the screenshot from our moderator (in Console Error) requests we report it here.

### Expected Behavior

No errors or players kicked.

### Additional Server Info

We are using Velocity, Geyser & Floodgate.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PufferfishPlus--17%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--PufferfishPlus--17%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
Update to ci builds, otherwise we need the full error
