### ISSUE TITLE
Crash on 1.18.2 client

### ISSUE THREAD

**Issue by svr333** [ViaVersion/ViaVersion#2974]
### `/viaversion dump` Output

https://dump.viaversion.com/33547677aca2aa30bd4382686075f5690ad2e90db214215ac5614160baf7eeb8

### Console Error

```
https://paste.gg/p/anonymous/fc99b9760e324aa7a664772ad75f66f3
```

### Bug Description

User on 1.18.2 fails to join on 1.19 base server, he does stuff for 20 seconds and gets kicked after that.
User says last thing he did was feed a cat, though not every time he crashed that was his last action.
Error told me to report it here.

### Steps to Reproduce

Example:
Login with a 1.18.2 client on a 1.19 server
Do something specific (not sure what though)

### Expected Behavior

Not crashing (its a hasty report but I wanted to report anyway)

### Additional Server Info

Fabric modded server with no real mods, only performance mods, factions

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.4.7+5--main](https://img.shields.io/badge/Platform-0.4.7+5--main-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.3.0)-Outdated!-red?style=flat-square) </br>![ViaBackwards(4.3.0): 8 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)
