### ISSUE TITLE
Spawning ocelots for recent clients from 1.8 server seems to be impossible

### ISSUE THREAD

**Issue by michelcolman** [ViaVersion/ViaVersion#2975]
### Problem Description

On a 1.8.8 server, spawning ocelots with entity ID 98 actually spawns cats on recent clients (starting from 1.14) because cats and ocelots were split up into separate mob types. There currently seems to be no way of spawning actual ocelots across all versions from a 1.8 server.

### Solution Description

I would like some way of spawning ocelots rather than cats for both old and new clients.

### Additional Info

Pre-1.14 server with post-1.14 client

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Ccode-lang** [comment]
Update from 1.8 to somewhere around 1.12.  That should solve your problem.

**Comment by michelcolman** [comment]
We need 1.8 for performance reasons. It would also require rewriting a lot of code. Is there any way we can send a 1.14 packet out from a 1.8 server, specifying ocelot instead of cat?

**Comment by michelcolman** [comment]
I think ocelot should be the default anyway, rather than cat, since this was the original mob.

**Comment by FlorianMichael** [comment]
There is now a new config option (see https://github.com/ViaVersion/ViaVersion/commit/33cc21d6e66596bfeb52987cb8f77181e7dc6e1c) which allows you to disable the ocelot->cat translation, have in mind that tamed ocelots won't be shown correctly (for now).
