### ISSUE TITLE
Bug viaversion

### ISSUE THREAD

**Issue by eki-github** [ViaVersion/ViaVersion#2976]
### `/viaversion dump` Output

https://dump.viaversion.com/a667cd55815612595f0a7d5f8f15ca0e52d63fb85824fdec79cef5518cd2f748

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/fb55a6418400475eb485d9be9dc36bc0

### Bug Description

![image](https://user-images.githubusercontent.com/65031661/175523377-ab909f87-48e2-4672-9058-ba650a25e0b1.png)
![image](https://user-images.githubusercontent.com/65031661/175523391-d5e83a2a-e139-484b-bb57-9e83001897af.png)

### Steps to Reproduce

login 1.17.1 version

### Expected Behavior

.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.19--SNAPSHOT](https://img.shields.io/badge/Platform-1.19--SNAPSHOT-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.3.0): 8 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 8 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
Use a standard Bungee/Waterfall fork, what you're using seems to be breaking something.
