### ISSUE TITLE
The bug that the console asked me to submit

### ISSUE THREAD

**Issue by xiaobao4909** [ViaVersion/ViaVersion#2977]
### `/viaversion dump` Output

.

### Console Error

[21:29:55 WARN]: [/213.226.123.219:64949] <-> InitialHandler - could not decode packet! com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: CLIENT_INTENTION, Type: String, Data: [Pair{Type|VarInt, 0}], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol$1 (Anonymous), Packet ID: 0}
Actual Error:

### Bug Description

Show above errors

### Steps to Reproduce

unknown

### Expected Behavior

freedom from error

### Additional Server Info

![image](https://user-images.githubusercontent.com/92622663/175757847-18276d79-4212-438e-9684-fb2c3272c14c.png)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Follow the issue template.
