### ISSUE TITLE
[BUG] 1.19.1 rc1 , Invalid signature for profile public key

### ISSUE THREAD

**Issue by Tsoccerguy3** [ViaVersion/ViaVersion#2980]
### `/viaversion dump` Output

https://dump.viaversion.com/aa89dda02d0c76233ba53460dfb9601df5ec738f735247a22e9e36526561405c

### Console Error

```
Put the paste.gg link or text here.
```
No error

### Bug Description

There is no error on the server . With viaversion dev for 1.19.1 rc1 can not log onto our server
![2022-06-26_11 35 14](https://user-images.githubusercontent.com/22108822/175822299-36590c20-84cf-40a0-95ed-7a05c4b6902f.png)

### Steps to Reproduce

just add plugin to server

### Expected Behavior

expect normal login

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--39%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Paper--39%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-1.19.1-rc1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.3.2--1.19.1--rc1--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
1.19.1 clients will not be able to join 1.19.0 servers due to a profile signature change we cannot handle in Via
