### ISSUE TITLE
Entering a nether portal will report an internal error and be kicked out of the game in 1.19.

### ISSUE THREAD

**Issue by XiaoHuiHui233** [ViaVersion/ViaVersion#2981]
### `/viaversion dump` Output

https://dump.viaversion.com/ac26cb692332fb9f1836e808957e7570e4796e145e9a52a264549fa8f424b3f1

### Console Error

[paste link](https://paste.gg/p/anonymous/d4acddd11b0d4bd7b2c882ae683a637f)

### Bug Description

Entering nether portals, respawning players, and interacting with villagers in 1.19 will be kicked off the server. An error will be reported in Velocity, as shown in the above link.

### Steps to Reproduce

1. Login in with 1.19 vanilla client.
2. Build a portal to nether and walk in.

### Expected Behavior

You are teleported to the overworld/nether normally instead of being kicked out of the game with an internal error.

### Additional Server Info

Im using Velocity with ViaVersion, ViaBackwards, Geysor and LuckPerms. You can see the version information in the dump above.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.1](https://img.shields.io/badge/Platform-velocity%203.1.1-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.3.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.3.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
See https://github.com/ViaVersion/ViaVersion/issues/2915
