### ISSUE TITLE
Error / Disconnect when executing command

### ISSUE THREAD

**Issue by JaTiTV** [ViaVersion/ViaVersion#2982]
### `/viaversion dump` Output

https://dump.viaversion.com/52679a4fd3bdb4e7548e5d56a37c172ff7760b0768791b9693cc7c7b513844df

### Console Error

disconect

### Bug Description

This error occurs lately again and again when we execute commands.

[https://i.imgur.com/6i3z64y.png](https://i.imgur.com/6i3z64y.png)

Paper 1.18.2 #336
Waterfall 1.19 #496

### Steps to Reproduce

run command with 1.19 client on 1.19 waterfall with 1.18.2 paper

### Expected Behavior

Execute command and do not kick

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
Update to ci builds, otherwise try without other plugins and see if it still happens

**Comment by JaTiTV** [comment]
Just updated. The error still occurs
https://dump.viaversion.com/95dda0a77ff48ec195f5ea7146748881075157271ed8164775bd7f70b899d173
