### ISSUE TITLE
Writing/saving book and quill disconnects client (1.18.2 Client on 1.19 Server)

### ISSUE THREAD

**Issue by AwesomeGenius** [ViaVersion/ViaVersion#2986]
### `/viaversion dump` Output

https://dump.viaversion.com/8060955e4fa79b6f495009e7c5365f9276cde240b3f4454100bfe28a1a2ed25e

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Trying to save a modified book and quill in 1.18.2 client multiplayer 1.19 server disconnects the client.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/108368389/176278064-c39c8c09-0479-4bf7-9d2e-26cf85fbcd2e.png">

### Steps to Reproduce

1. Create or find a server with 1.19 viaversion
2. Log on with a 1.18.2 client
3. Get a new book and quill
4. Write something in it or create new pages
5. Click 'Done'
6. This should disconnect you from the server and show either "Disconnected" or something like this:

{Packet Type: EDIT_BOOK, Type: FlatVarIntItem, Data: [], Source 0:
com.viaversion.viabackwards.protocol.protocol1_18_2to1_19.packets.BlockItemPackets1_19$1 (Anonymous), Packet ID:
13}
Actual Error:

7. The book is not saved

### Expected Behavior

You should be able to save the text in the book and quill, and you should not be disconnected.

### Additional Server Info

I am using ViaFabric

I use some other mods, Here is a list:
Fabric API (dependency)
ViaVersion
ViaBackwards
ViaFabric
Simple Voice Chat

I am using a server host called "Aternos".

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.4.7+5--main](https://img.shields.io/badge/Platform-0.4.7+5--main-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.3.0)-Outdated!-red?style=flat-square) </br>![ViaBackwards(4.3.0): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)
