### ISSUE TITLE
Villager kicked NOTE: Using latest version!

### ISSUE THREAD

**Issue by lbrunton** [ViaVersion/ViaVersion#2988]
### `/viaversion dump` Output

https://dump.viaversion.com/07e9cc66986fee3fd42fca9d70e6147271944660931bbe3f9e137538459a7e4a

### Console Error

no console errors

### Bug Description

When trading with a villager, the player is kicked from the server (in our case, they are kicked to hub).
This occurs on both Lunar client and the normal Minecraft launcher.

Please see the video below:

https://user-images.githubusercontent.com/68839442/176343829-a461c5e4-1e12-4ffd-ba8a-9f93540757f9.mp4

### Steps to Reproduce

Click on a villagers trade

### Expected Behavior

Player is not kicked

### Additional Server Info

This server is running Pufferfish version git-Pufferfish-8 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 8aafc13 on HEAD)
You are on the latest version!

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--8%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Pufferfish--8%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.3.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.3.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Does this client continue to occur on canilla clients?; if not then it's a lunar problem.

If it does, likely caused by another plugin that breaks via*'s compatibility.

**Comment by lbrunton** [comment]
Hello,

I found out the issue is caused by the server jar, because with no plugins installed, the issue still persists. Previously, we had issues with villagers causing crashes, but updating viaversion fixed it, therefore I made an assumption it was from viaversion. However, that is not the case here.

This report can be closed. Apologises for the inconvenience caused.
