### ISSUE TITLE
ViaVersion Error preventing joins

### ISSUE THREAD

**Issue by pacificminer** [ViaVersion/ViaVersion#2989]
### `/viaversion dump` Output

https://dump.viaversion.com/e220904c638c94d5c944d9f5983305bcc9d59ceb6c102b4e926ee74b8b4c0076
https://paste.gg/p/anonymous/4433a9f935164c169e9f4b01042d96d6

### Console Error

```](https://paste.gg/p/anonymous/4433a9f935164c169e9f4b01042d96d6)


### Bug Description

Certain players are unable to connect to the server. They are welcomed with a simple "Disconnect" message when trying. This is the same for both 1.18.2 and 1.19 client version. My server is 1.18.2 natively, using ViaVersion to allow 1.19 clients to join.

### Steps to Reproduce

1. Try and connect to the server

### Expected Behavior

Players should be able to join without problem.

### Additional Server Info

This only happens to a very small fraction of players but still notable enough to where it's an issue as 5 different people have reported this and I've seen the error pop up frequently.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.18--R0.1--SNAPSHOT%3Ad79d5f1%3A486](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.18--R0.1--SNAPSHOT%3Ad79d5f1%3A486-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 9 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Kichura** [comment]
Your proxy is outdated.
