### ISSUE TITLE
High damage weapons cause players to quit forcibly

### ISSUE THREAD

**Issue by VTSTG233** [ViaVersion/ViaVersion#2992]
### `/viaversion dump` Output

https://dump.viaversion.com/51a5fa8f3362271e2f38847eb2d7bfe5b9b26711d8168b9c0189c9af44180a51

### Console Error

f5a9aef53ea94806b1be8a5c909abb0c
https://paste.gg/p/anonymous/3016711caa0d40b29b6dbac296e27c6d

### Bug Description

Player PVP player, the sword in the player's hand has been enchanted. Fighting with the player will force all players on the server to exit, and [proxy] lost connection to server will appear

### Steps to Reproduce

Example:
1.Players hold high enchantment weapons
2.The player kills another player and hits the player once, causing the player to lose blood, and all players will be kicked out
3.And show this phrase:[Proxy] Lost connection to server
4.Players will not lose HP if they can't fight. All players on the server will be fine on the server

### Expected Behavior

Hope to find a solution for me faster

### Additional Server Info

Yes, I use bungeecord and paperspigot1.12.2, and I use the latest version of viaversion. The front is also the latest

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1562%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1562%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.2.1)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)
