### ISSUE TITLE
Error occurred when I tried to join a 1.15.2 server using 1.19 client

### ISSUE THREAD

**Issue by MiKayule** [ViaVersion/ViaVersion#2995]
### `/viaversion dump` Output

https://dump.viaversion.com/6a2ba76a2cb58faf1468b2894219d53ec180e1865019336520fe4bdca9a1d60b

### Console Error

https://paste.gg/p/anonymous/63fbc7e99dde431f97b7ca076f6d3aa5

### Bug Description

Trying to join a 1.15.2 server using 1.19 client cause this error

### Steps to Reproduce

1. Login with a 1.19 vanilla client
2. Join a vanilla server on 1.15.2 through BungeeCord with `/server` command
3. Error occurred

### Expected Behavior

I should join into the server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Ac8e876b%3A1649](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Ac8e876b%3A1649-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by MiKayule** [comment]
Also tried Viaversion-4.3.2-SNAPSHOT, the same problem still exists.

**Comment by MiKayule** [comment]
Also tried to reset the `plugins/ViaVersion/config.yml` file, which wasn't effective as well.

**Comment by MiKayule** [comment]
Upgraded BungeeCord to git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:587fb37:1653 which is the latest build, it didn't help.

**Comment by Kichura** [comment]
This looks like custom dimension data was being sent out to the client which is poorly set up.

**Comment by kennytv** [comment]
Definitely the proxy or a plugin doing something bad

**Comment by MiKayule** [comment]
But there's no custom dimension, they're all completely vanilla server

**Comment by MiKayule** [comment]
> This looks like custom dimension data was being sent out to the client which is poorly set up.

But there's actually no custom dimension, only `minecraft:overworld`, `minecraft:the_nether` and `minecraft:the_end` from Mojang, and all the three servers are completely vanilla servers.

**Comment by MiKayule** [comment]
> Definitely the proxy or a plugin doing something bad/switching to <1.16 servers from a >1.16 server on Bungee is pretty much unsupported; either switch to Velocity or move Via to your backend servers

I'll try to move ViaVersion to my backend server, as long as Fabric Mod Loader is supported by ViaVersion.
