### ISSUE TITLE
Bungeecord messages are shown in actionbar

### ISSUE THREAD

**Issue by FrinshHD** [ViaVersion/ViaVersion#2996]
### `/viaversion dump` Output

https://dump.viaversion.com/6d33b6418374995d5f474559399534c43340e4b29bae809701ad9bc4ca88a132

### Console Error

[```
Put the paste.gg link or text here.
```
]

### Bug Description

If i use the Bungeecord /alert command the message that should be shown in chat is shown in the Actionbar this is only for 1.19 clients

### Steps to Reproduce

Setup a bungeecord network connect with  1.19 and use a bungeecord command that gives chat output

### Expected Behavior

I expect the message to appear in chat like normal

### Additional Server Info

Yeah i use waterfall latest

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--794%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--794%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.3.0): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 8 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by FormallyMyles** [comment]
If this is a proxy command and ViaVersion isn't on the proxy, then it's not down to ViaVersion. Also ensure you use the latest builds when creating issues hence the checklist.
