### ISSUE TITLE
Spam error io.netty.handler.codec.EncoderException

### ISSUE THREAD

**Issue by DimaSergeew** [ViaVersion/ViaVersion#2997]
### `/viaversion dump` Output

https://dump.viaversion.com/47cc8a04fb0c5e6ecb6bccd08fa6bb8ec197f53c979d13ff299b7eef43011c65

### Console Error

```
https://paste.gg/p/anonymous/3ac3e0d772cf4a0cbf3c142baf1e1f37
```

### Bug Description

spam error console

### Steps to Reproduce

spam console

### Expected Behavior

no error

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.3.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.3.1)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by DimaSergeew** [comment]
> ![Platform: velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29](https://camo.githubusercontent.com/83416a8660fb4ff792e46ff68f022501b759e58935d53bf8d60aa99adf812058/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d76656c6f63697479253230332e312e322d2d534e415053484f542532302532386769742d2d65386266366162352d2d623136312532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.3.1): 11 commits behind master](https://camo.githubusercontent.com/a80def3f6508dc8d4c9a6ddc309217506ea4670f54a25554c047c55c13b3340f/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e332e31292d3131253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaBackwards(4.3.1): Even with master](https://camo.githubusercontent.com/97cfbd3fcd3860f870c7da726b7c00d21a12abc81462f1d628d8a91bbd78f56b/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e332e31292d4576656e253230776974682532306d61737465722d627269676874677265656e3f7374796c653d666c61742d737175617265) Please try the **latest** build(s) from https://ci.viaversion.com/

So this happened just because I updated to the latest builds

**Comment by DimaSergeew** [comment]
> ![Platform: velocity%203.1.2--SNAPSHOT%20%28git--e8bf6ab5--b161%29](https://camo.githubusercontent.com/83416a8660fb4ff792e46ff68f022501b759e58935d53bf8d60aa99adf812058/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d76656c6f63697479253230332e312e322d2d534e415053484f542532302532386769742d2d65386266366162352d2d623136312532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.3.1): 11 commits behind master](https://camo.githubusercontent.com/a80def3f6508dc8d4c9a6ddc309217506ea4670f54a25554c047c55c13b3340f/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e332e31292d3131253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaBackwards(4.3.1): Even with master](https://camo.githubusercontent.com/97cfbd3fcd3860f870c7da726b7c00d21a12abc81462f1d628d8a91bbd78f56b/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e332e31292d4576656e253230776974682532306d61737465722d627269676874677265656e3f7374796c653d666c61742d737175617265) Please try the **latest** build(s) from https://ci.viaversion.com/

The problem was in Limbo plugins sorry
