### ISSUE TITLE
Why 1.19.1 won't be supported on 1.19.0

### ISSUE THREAD

**Issue by HowardZHY** [ViaVersion/ViaVersion#2998]
### Problem Description

Tell us which 1.19.0-1.19.1 packet can't be transformed.

### Solution Description

see above

**Comment by Earthcomputer** [comment]
I think they did it specifically to annoy people like you

**Comment by Kichura** [comment]
Can't believe earth just exposed the entire 1.19 community smh.

**Comment by Camotoy** [comment]
While I don't know the specifics, it has something to do with the online mode verification/encryption initialization. I actually tried fixing it myself for giggles and I could not, so if Kenny couldn't figure it out then it might truly be impossible.

**Comment by HowardZHY** [comment]
I'm back now

**Comment by HowardZHY** [comment]
> While I don't know the specifics, it has something to do with the online mode verification/encryption initialization. I actually tried fixing it myself for giggles and I could not, so if Kenny couldn't figure it out then it might truly be impossible.

If the client is 1.19.1 , anyway to join 1.19 ? (if both server y client is offline)

**Comment by Kichura** [comment]
Only if the server is on 1.18.2 or lower, otherwise you are creating an impossible action at this time.

**Comment by HowardZHY** [comment]
> Only if the server is on 1.18.2 or lower, otherwise you are creating an impossible action at this time.

I just thonk is it *really* impossible or not.
