### ISSUE TITLE
error message 

### ISSUE THREAD

**Issue by FlyingCow32** [ViaVersion/ViaVersion#2999]
### `/viaversion dump` Output

https://dump.viaversion.com/da92113bc7ef93eac5030ad8d2296b9eb3e150d0763cf28302b87ca8df102118

### Console Error

```
https://pastebin.com/fHhGecFG
```

### Bug Description

It appeared like that , randomly , didn't do anything and got this message 

### Steps to Reproduce

i don't know , it appeared randomly 

### Expected Behavior

get an explication and maybe a soluce of how to fix it ?

### Additional Server Info

I've got a 1.18.2 server , Spigot/paper/bukkit.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--310%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Paper--310%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.2.1)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.2.1)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)
