### ISSUE TITLE
Viaversion bug

### ISSUE THREAD

**Issue by Gerritjan132** [ViaVersion/ViaVersion#3000]
### `/viaversion dump` Output

https://dump.viaversion.com/37b11947823f2f1c61a894e0d44c0bedcc14f1e0acb60abafdead89ddbb4ffae

### Console Error

 disconnected with: EncoderException : com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viabackwards.protocol.protocol1_18_2to1_19.P

### Bug Description

When you join the server, jou getr kicked.
With the error disconnected with: EncoderException : com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viabackwards.protocol.protocol1_18_2to1_19.P
(this is the console error)
Some command send a feedback with a %s

And some more

### Steps to Reproduce

1. Place the plugin in you server.
2. Start your server.
3. Join your server.
4. Wait some time.
5. Send some commands.
6. You get kickt.

### Expected Behavior

The plugin don't kick me. :D

### Additional Server Info

I use Bungeecord, 
![image](https://user-images.githubusercontent.com/108688139/177194783-3a89fce2-17d3-4896-ad04-9dbe753c119a.png)
And that are my plugins.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A587fb37%3A1653](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A587fb37%3A1653-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)
