### ISSUE TITLE
Cannot write on signs on 1.12.2 server using 1.19.x client

### ISSUE THREAD

**Issue by TeddMC** [ViaVersion/ViaVersion#3001]
### `/viaversion dump` Output

https://dump.viaversion.com/7800f05a1d758562bcce085f456ac12a9fd55a761ca2716bfdacc98d5404e574

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

I know 1.12.2 has reached "EOL" but since it's still a super popular version of Minecraft and indeed the reason why many people use ViaVersion at all, I thought I would still report this bug in the hope there's an easy fix. When I join the 1.12.2 server using my 1.19 client, every time I put down a sign, I am unable to write text on it. It immediately skips the window that should appear allowing me to enter text. I have tried using a 1.18 client and there is no issue, leading me to believe it's a bug.

### Steps to Reproduce

1. Login with a 1.19 client
2. Place a sign
3. There is no option to write text

### Expected Behavior

I should be able to write text on the sign

### Additional Server Info

This is basic PaperMC Minecraft as seen in the dump.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by CnC-Robert** [comment]
This also happens when on a 1.16.5 server from a 1.19 client. After placing a few signs the game crashes and i get this error.  

![afbeelding](https://user-images.githubusercontent.com/72943079/178352924-42d3e969-0196-4dc9-b19f-67abdf12ded7.png)

**Comment by kennytv** [comment]
Will track progress in https://github.com/ViaVersion/ViaVersion/issues/3027
