### ISSUE TITLE
Unable to find id for packet of type com.velocitypowered.proxy.protocol.packet.PluginMessage in SERVERBOUND protocol 1.12.2

### ISSUE THREAD

**Issue by archroot** [ViaVersion/ViaVersion#3002]
### `/viaversion dump` Output

https://dump.viaversion.com/ce4882111de0dcab4476fb7e1a21c9d3c3e7eca4a2bab75c6df9cd56a3a31ed7

### Console Error

```
https://paste.gg/p/anonymous/a92197abef6d4701bd0d815e5cb3dd8a
```

### Bug Description

java.lang.IllegalArgumentException: Unable to find id for packet of type com.velocitypowered.proxy.protocol.packet.PluginMessage in SERVERBOUND protocol 1.12.2

### Steps to Reproduce

player logs in from an unknown client 1.12.2

### Expected Behavior

it should not spam errors into the console

### Additional Server Info

everything is described in the dump
https://dump.viaversion.com/ce4882111de0dcab4476fb7e1a21c9d3c3e7eca4a2bab75c6df9cd56a3a31ed7

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
Probably another plugin doing something unexpected, try without others and find out which one. If none, we'll reopen
