### ISSUE TITLE
Cant connect with 1.12 to my 1.18.2 server

### ISSUE THREAD

**Issue by hacimertgokhan** [ViaVersion/ViaVersion#3004]
### `/viaversion dump` Output

https://dump.viaversion.com/8645c6b324290331e88fbddfd5390c5445c7de9957b11d6f80db290a674c8e2e

### Console Error

:11:22 [WARNING] [ViaBackwards] Ignoring outgoing plugin message with channel: REGISTER
17:11:22 [SEVERE] java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "com.viaversion.viaversion.bungee.handlers.BungeeServerHandler.channelWrapper" is null

17:11:22 [SEVERE]     at com.viaversion.viaversion.bungee.handlers.BungeeServerHandler.checkServerChange(BungeeServerHandler.java:282)

17:11:22 [SEVERE]     at com.viaversion.viaversion.bungee.handlers.BungeeServerHandler.onServerConnected(BungeeServerHandler.java:115)

17:11:22 [SEVERE]     at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)

17:11:22 [SEVERE]     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

17:11:22 [SEVERE]     at java.base/java.lang.reflect.Method.invoke(Method.java:568)

17:11:22 [SEVERE]     at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:24)

17:11:22 [SEVERE]     at net.md_5.bungee.event.EventBus.post(EventBus.java:39)

17:11:22 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:367)

17:11:22 [SEVERE]     at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:168)

17:11:22 [SEVERE]     at net.md_5.bungee.protocol.packet.Login.handle(Login.java:207)

17:11:22 [SEVERE]     at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:107)

17:11:22 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

17:11:22 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

17:11:22 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

17:11:22 [SEVERE]     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)

17:11:22 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

17:11:22 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

17:11:22 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

17:11:22 [SEVERE]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)

17:11:22 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

17:11:22 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

17:11:22 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

17:11:22 [SEVERE]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)

17:11:22 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

17:11:22 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

17:11:22 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

17:11:22 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)

17:11:22 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)

17:11:22 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

17:11:22 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

17:11:22 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

17:11:22 [WARNING] [ViaBackwards] Ignoring outgoing plugin message with channel: MC|Brand
17:11:22 [SEVERE]     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)

17:11:22 [WARNING] [ViaVersion] ERROR IN Protocol1_17_1To1_18 IN REMAP OF BOSSBAR (0x0D)
17:11:22 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

17:11:22 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

17:11:22 [SEVERE]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)

17:11:22 [SEVERE]     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)

17:11:22 [SEVERE]     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)

17:11:22 [SEVERE]     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)

17:11:22 [SEVERE]     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)

17:11:22 [SEVERE]     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)

17:11:22 [SEVERE]     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)

17:11:22 [SEVERE]     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

17:11:22 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:833)

17:11:22 [INFO] [Mixeration] <-> DownstreamBridge <-> [cakmaLobi] has disconnected
17:11:22 [INFO] [Mixeration] disconnected with: EncoderException : com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: BOSSBAR, Type: UUID, Data: [], Source 0: com.viaversion.viaversion.rewriter.ComponentRewriter$2 (Anonymous), Packet ID: 13}
Actual Error:  @ io.netty.handler.codec.MessageToMessageEncoder:104

### Bug Description

When i join the server with 1.12

### Steps to Reproduce

1. Joined with default 1.12
2. And i get that error

### Expected Behavior

Joined the server like everyone

### Additional Server Info

I also use Bungeecord(Aegis) Bungeeperms command4me badlionclientapi bot sentry litebans maintenance pistonmotd

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3Af2ea93a%3Aunknown](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3Af2ea93a%3Aunknown-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 8 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.3.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.3.1)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)
