### ISSUE TITLE
Can't write books using 1.16 on a 1.19 server

### ISSUE THREAD

**Issue by StephenLynx** [ViaVersion/ViaVersion#3005]
### `/viaversion dump` Output

aaaaaaaaaaaaaaaaaaaaaa

### Console Error

aaaaaaaaaaaaaaaaaaa

### Bug Description

Tried to write a normal book, got logged out. Here is the message I got: https://i.imgur.com/tfDc0dH.png

### Steps to Reproduce

aaaaaaaa

### Expected Behavior

aaaaa

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>
