### ISSUE TITLE
Bugs with 1.19 for a 1.16.5 server

### ISSUE THREAD

**Issue by Snike02** [ViaVersion/ViaVersion#3006]
### `/viaversion dump` Output

https://dump.viaversion.com/4b1354ae2deabe71f301184c7215ff01506abc1622353c9b71a693014a0451a9

### Bug Description

Im using a 1.16.5 server and when players join with 1.19 get kicked from random reasons.
They get kicked when trading with villagers
They get kicked when dying in combat or dying to void
Sometimes they get kicked when teleporting to end or nether

### Steps to Reproduce

Join a 1.16.5 server with 1.19
Open trading with villagers
Jump to void to die or pvp
Teleport to nether or end

### Expected Behavior

Not get kicked

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--794%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--794%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)
