### ISSUE TITLE
Crash when editing a book on older versions of the game

### ISSUE THREAD

**Issue by LooneX1997** [ViaVersion/ViaVersion#3008]
### `/viaversion dump` Output

https://dump.viaversion.com/0dc51dd03f9593b5f304b0d13207127f193b5768d6fadff31ad3cb125a338332

### Console Error

https://paste.gg/p/anonymous/f432172b6ac24e8d9cdc7c0265603d78

### Bug Description

When editing a book on the version 1.17.1 (server on 1.19) the player get disconnected.
Log and dump attached!

### Steps to Reproduce

1. Log with a 1.17.1 client
2. Edit a book (book with pen)
3. Save.

### Expected Behavior

The book should be normally saved

### Additional Server Info

Nothing interesting here. Standard PaperMC server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--52%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Paper--52%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)
