### ISSUE TITLE
Could not find TYPE ID

### ISSUE THREAD

**Issue by devendrapoonia** [ViaVersion/ViaVersion#3009]
### `/viaversion dump` Output

https://dump.viaversion.com/ff32cab6fa37f8285b0284159f1fa5e1c53f1d0d556aa9d458b8f1c9bf9a4044

### Console Error

```
 [12:21:26 ERROR]: [ViaVersion] Could not find 1.11 type id -1 isObject=false
 [12:21:26 ERROR]: [ViaVersion] Could not find 1.12 type id -1 isObject=false
```

### Bug Description

No impact on gameplay. Just spams console with errors.

### Steps to Reproduce

1. Login with 1.8.9
2. Console will be spammed with these kinds of errors.

### Expected Behavior

There should be no errors like I above mentioned, in console.

### Additional Server Info

Image of Error
![image](https://user-images.githubusercontent.com/50015986/177991811-b81a39fb-b567-484c-b632-0ca9c482b788.png)

Server version - git-Paper-1618 (MC: 1.12.2)

Viaversion version - latest from Jenkins ([Viaversion Jenkins](https://ci.viaversion.com/))

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1618%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1618%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.3.1-SNAPSHOT)-Outdated!-red?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by devendrapoonia** [comment]
I have latest version.
