### ISSUE TITLE
1.18.2 > 1.19 Book crash

### ISSUE THREAD

**Issue by SammyInMinecraft** [ViaVersion/ViaVersion#3014]
### `/viaversion dump` Output

https://dump.viaversion.com/79ec21a486987081ab328989ad770b731f34e4f47cd5c19ffafdb3ce95cf8573

### Console Error

https://paste.gg/p/anonymous/694e9ddc0065457cbbd53d4f87688bae

### Bug Description

The server will kick me out of the game when I use books to write down any characters and turn it off

### Steps to Reproduce

Use the client of 1.18.2 to log in to the server 
Use books to write down any characters
Then the server will kick out of the game

### Expected Behavior

The server will kick out players

### Additional Server Info

(Paper version git-Paper-40 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT))
No bungeecord 
Plugin CMI 9.1.0.2

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--40%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Paper--40%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)
