### ISSUE TITLE
Error When Operating On Server 1.18.1

### ISSUE THREAD

**Issue by Shinchan0911** [ViaVersion/ViaVersion#3015]
### `/viaversion dump` Output

https://dump.viaversion.com/e7c59889a05478ec6980f8d7a85371a4e42aa59e18e2e5fa95d18541dbd4c298

### Console Error

```
Console Says Nothing
```

### Bug Description

![image](https://user-images.githubusercontent.com/98627396/178197468-1a716327-8de1-4dda-9988-e2d4675dedd8.png)

### Steps to Reproduce

I've Been Using Via Version 4.3.1 And Running On Server 1.18.1, I'm Getting Error As Picture When Using Customized Items Again Put Them In Shopkeeper, When I Click Npc Shopkeeper This Dialog Show

### Expected Behavior

I Hope You Can Fix This Error As Soon As Possible PLS

### Additional Server Info

Do I Use Via On Both The Xcord Server And The Paper Server

### Checklist

- [ ] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [ ] I have included a ViaVersion dump.
- [ ] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--216%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-git--Paper--216%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 8 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.3.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.3.1)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
Update ViaVersion to ci builds, also make sure you only have ot on either Paper or Xcord, not both (ideally just on Paper)
