### ISSUE TITLE
Villager Trading on 1.8 server with 1.14+ clients doesn't work properly.

### ISSUE THREAD

**Issue by jordoncodes** [ViaVersion/ViaVersion#3016]
### `/viaversion dump` Output

https://dump.viaversion.com/01a98b1212b69da70caadbf98840715efb13101c3f3b4c583646189223e08d5e

### Console Error

```
There is none
```

### Bug Description

Using a villager on a 1.8 server doesn't autofill on a 1.14+ client, and therefore it appears as if you can't trade (even though you technically can). I'm aware it's due to this feature not being in 1.8.x, but are there any fixes that could be done for this?

### Steps to Reproduce

1. Login with a 1.14+ client
2. Go to a villager with trades and right click it with the correct items in your inventory
3. Click the button on the left panel to autofill it
4. It will go there for a bit (depending on ping) and will disappear back into the inventory.
5. A way to make villager trading 'work' is to place the items in manually

### Expected Behavior

The trading gui autofills with the correct item.

### Additional Server Info

It *is* running NachoSpigot (a fork based on spigot, this dump is on a minehut server), but I've tested and it does on Paper as well.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--NachoSpigot--%222cefae4%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--NachoSpigot--%222cefae4%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by jordoncodes** [comment]
> ![Platform: git--NachoSpigot--%222cefae4%22%20%28MC%3A%201.8.8%29](https://camo.githubusercontent.com/fc7f715c15b8573bd8aefbeb5c28168f523c43c443a23e3192c7b006a713699b/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d4e6163686f537069676f742d2d253232326365666165342532322532302532384d43253341253230312e382e382532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.3.1): 11 commits behind master](https://camo.githubusercontent.com/a80def3f6508dc8d4c9a6ddc309217506ea4670f54a25554c047c55c13b3340f/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e332e31292d3131253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) Please try the **latest** build(s) from https://ci.viaversion.com/

I have, new dump
https://dump.viaversion.com/eb1dd8548411a13a1ec3cca2ce62228aea7688862150ee9ae275e5877cbb804b

**Comment by kennytv** [comment]
We don't add features of newer versions

**Comment by jordoncodes** [comment]
> We don't add features of newer versions

okay
