### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by RAFAELESPADA** [ViaVersion/ViaVersion#3017]
### `/viaversion dump` Output

https://dump.viaversion.com/b1551380dcd0060a23fab0507217e7ca7b2582bc58bc9d64a1d71ef08903cb78

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/78d85549f84149f5a3cf00cd16e28a4f

### Bug Description

When i attempt to join my lobby server using 1.19 error appear

### Steps to Reproduce

LOGIN WITH 1.19 CLIENT
ERROR POPUP IN LOBBY SERVER CONSOLE

### Expected Behavior

The server allows 1.19 clients to join without issues

### Additional Server Info

i use waterfall latest version.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--%224c7641d%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--%224c7641d%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.4.0-1.19.1-pre4-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.4.0--1.19.1--pre4--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
That means you either have a stacked Via setup or another plugin sending bad entity metadata
