### ISSUE TITLE
Get kicked from server if entity damages me

### ISSUE THREAD

**Issue by gepron1x** [ViaVersion/ViaVersion#3019]
### `/viaversion dump` Output

https://dump.viaversion.com/bc0b507f7c93563b502c6420498cdb64fedaa616b8c2d25366534e95e6ab4c26

### Console Error

https://paste.gg/p/anonymous/e5364839f6f8420a816f75319da8c7c5

### Bug Description

I get kicked if any mob hits me.

### Steps to Reproduce

1. Login to the velocity server on 1.18.2-1.19
2. Spawn a mob
3. Get a hit

### Expected Behavior

Not being kicked after an mob hit

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by FormallyMyles** [comment]
This doesn't seem related to entities and is most likely an outdated velocity plugin, I'd test each and see if it happens. We'll investigate further if you're able to provide ways to replicate without the other plugins.
