### ISSUE TITLE
strange kick when doing things

### ISSUE THREAD

**Issue by kingakis2** [ViaVersion/ViaVersion#3020]
### `/viaversion dump` Output

https://dump.viaversion.com/200299a1df636af9af3e0cbed6598a24fb724c818a0315740beae6ba13681d5c

### Console Error

13.07 13:33:08 [Server] WARN ERROR IN Protocol1_18_2To1_19 IN REMAP OF SYSTEM_CHAT (0x5F)
13.07 13:33:08 [Server] WARN ERROR IN Protocol1_18_2To1_19 IN REMAP OF SYSTEM_CHAT (0x5F)
13.07 13:33:08 [Server] WARN ERROR IN Protocol1_18_2To1_19 IN REMAP OF SYSTEM_CHAT (0x5F)
13.07 13:33:08 [Server] WARN io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
13.07 13:33:08 [Server] WARN {Source 0: com.viaversion.viabackwards.protocol.protocol1_18_2to1_19.Protocol1_18_2To1_19$6 (Anonymous)}
13.07 13:33:08 [Server] WARN Actual Error: 
13.07 13:33:08 [Server] WARN at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
13.07 13:33:08 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
13.07 13:33:08 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
13.07 13:33:08 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
13.07 13:33:08 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
13.07 13:33:08 [Server] WARN at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
13.07 13:33:08 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
13.07 13:33:08 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
13.07 13:33:08 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
13.07 13:33:08 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
13.07 13:33:08 [Server] WARN at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
13.07 13:33:08 [Server] WARN at TAB v3.1.2.jar//me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:91)
13.07 13:33:08 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
13.07 13:33:08 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
13.07 13:33:08 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
13.07 13:33:08 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
13.07 13:33:08 [Server] WARN at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
13.07 13:33:08 [Server] WARN at staffplusplus-core-1.19.4.jar//be.garagepoort.staffplusplus.craftbukkit.common.AbstractPacketHandler.write(AbstractPacketHandler.java:19)
13.07 13:33:08 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
13.07 13:33:08 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
13.07 13:33:08 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
13.07 13:33:08 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
13.07 13:33:08 [Server] WARN at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
13.07 13:33:08 [Server] WARN at TradeSystem_v2.1.2.jar//de.codingair.tradesystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:86)

### Bug Description

it happens when doing random things in general for example, opening a cosmetic in gadgets menu plugin, mining etc.. the kick is instantly and errors appears on console i will leave a screenshot link to see the error who appears in the game https://imgur.com/cypfLu9

### Steps to Reproduce

1. Join server
2. Play
3. Get instantly kicked

### Expected Behavior

Not being kicked for nothing and instantly

### Additional Server Info

Paper 1.19 plugins lists: https://imgur.com/a/mvFr5Uo

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
Most likely another plugin messing with chat packets in a bad way; try removing other plugins to find out which one
