### ISSUE TITLE
A few problems encountered when using Geysermc 

### ISSUE THREAD

**Issue by captainion2119** [ViaVersion/ViaVersion#3021]
### `/viaversion dump` Output

https://dump.viaversion.com/b93f6da0eac2500a77b8fd100449b09fd4851c9971ba93850aff0827b3ba7c5e

### Console Error

```
https://paste.gg/p/anonymous/32a05ba94cf64fb7ae25cffaeb198023
```

### Bug Description

Viaversion has a problem working with Bedrock version 1.19.1 that has been supported by Geysermc.

### Steps to Reproduce

1. start up a Spigot 1.18.2 Minecraft server.
2. use viaversion version `4.3.2-SNAPSHOT`
3. use ViaBackwards version `4.3.0:65afe42`
4. use floodgate version `2.2.0-SNAPSHOT`
5. use geysermc version `2.0.5-SNAPSHOT`
6. try joining the server with Bedrock version 1.19.1

### Expected Behavior

Allows players to join without any problems

### Additional Server Info

This server is running CraftBukkit version 3497-Spigot-b081915-b02801a (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3497--Spigot--b081915--b02801a%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-3497--Spigot--b081915--b02801a%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Camotoy** [comment]
Bedrock 1.19.10 is unrelated to Java supported versions. The latest Geyser version support 1.19.10 Bedrock and 1.19.0 Java.
