### ISSUE TITLE
  Click the villagers to report errors and be kicked out

### ISSUE THREAD

**Issue by shimu-163** [ViaVersion/ViaVersion#3022]
### `/viaversion dump` Output

https://dump.viaversion.com/5c151f3bbb446f45ec576621bb13ae5e87261f700ab70b5c8427a41511388bb5

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

In version 1.18.2, the server player will be kicked out of the server if he clicks the professional villager after entering the village. There is no record in the background of the server, and the client shows that the connection has been lost
![图片](https://user-images.githubusercontent.com/77338572/178953164-a1c7791e-3f76-4fd9-b56e-3135c93b343e.png)

### Steps to Reproduce

Example: 
1 Find the village

2. Find professional villagers

3. If you click it, you will report an error and be kicked out

### Expected Behavior

Users do not cross versions, and should use them normally

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--387%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Paper--387%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.3.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.3.1)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
If this happens on the same client as server version, you've got a stacked setup or something else messing things up. Otherwise, update to ci builds.
