### ISSUE TITLE
Make the same swimming system on 1.12.2 and 1.14+

### ISSUE THREAD

**Issue by Kostya-An** [ViaVersion/ViaVersion#3024]
### Problem Description

Players with 1.14+ can swim faster than those with 1.12.2, which is unfair compared to players with 1.12.2.

### Solution Description

Players with 1.14+ do not know how to swim fast in water, they, like on 1.12.2, seem to bounce over the water.

### Alternatives

I have no alternatives.

**Comment by FormallyMyles** [comment]
Swimming is client controlled, this isn't possible.
