### ISSUE TITLE
server wont connect to minecraft 1.12.2

### ISSUE THREAD

**Issue by glassesglasses8** [ViaVersion/ViaVersion#3026]
### `/viaversion dump` Output

Connection Lost Internal Exception: io.netty.handlercodec.EncoderException: COM.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template Packet Type: CHUNK_DATA, Type: Chunk, Data: (), Source 8: COMviaversion viabackwards.protocol.protocol1_18_2to1_19.packets.BlockItemPackets 1_19$4 CAnonymous, Facket ID: 343 Actual Erron

### Console Error

```
Put the paste.gg link or text here.
```
Connection Lost
Internal Exception: io.netty.handlercodec.EncoderException: COM.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
Packet Type: CHUNK_DATA, Type: Chunk, Data: (), Source 8: COMviaversion viabackwards.protocol.protocol1_18_2to1_19.packets.BlockItemPackets
1_19$4 CAnonymous, Facket ID: 343
Actual Error:

### Bug Description

Connection Lost
Internal Exception: io.netty.handlercodec.EncoderException: COM.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
Packet Type: CHUNK_DATA, Type: Chunk, Data: (), Source 8: COMviaversion viabackwards.protocol.protocol1_18_2to1_19.packets.BlockItemPackets
1_19$4 CAnonymous, Facket ID: 343
Actual Erron

### Steps to Reproduce

1. login minecraft
2. add server kaboom.pw
3. join server
![Capture](https://user-images.githubusercontent.com/109359960/179239455-0ee499b5-d63a-482b-be1c-89bba2482723.PNG)

### Expected Behavior

wont connect to server

### Additional Server Info

server: kaboom.pw

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
Follow the issue template - we can't help you without a dump
