### ISSUE TITLE
Sign editor automatically closes on 1.19 client on old servers

### ISSUE THREAD

**Issue by turnolos** [ViaVersion/ViaVersion#3027]
### `/viaversion dump` Output

https://dump.viaversion.com/3285cbe2c4164e5af9981a0b8a99b5897628972dd46fe9122ec56bf4cf0d07d9

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

I was asked by @kennytv in this existing issue here #2935  to create a new issue regarding the issue of the sign editor automatically closing.

After some testing as you requested, we have determined that the sign editor is broken with Minecraft 1.19 clients on any paper version below 1.17.

The dumps (also as requested) have also been pasted below. Hopefully, this will help debug and fix the problem.

Please let us know if you need anything else.

1.12 - Doesn't work
https://dump.viaversion.com/3285cbe2c4164e5af9981a0b8a99b5897628972dd46fe9122ec56bf4cf0d07d9

1.13 (doesn't work with viaversion)
1.13.1 - Doesn't work
https://dump.viaversion.com/0d64b97bcde34a76e738b0a30e9df2b34d5c52b548093b55560258aad0200e07

1.13.2 - Doesn't work
https://dump.viaversion.com/dced5f2be5d00e6fef67dbfce5dac3297b6f128189d88f87fdef6d0869d765cb

1.14 - Doesn't work
https://dump.viaversion.com/67b14ba01ff7d4ea8f73c41d8f868f56583a37104a3fe37b713950b33cccdf49

1.15 - Doesn't work 
https://dump.viaversion.com/f54bb52d3b15fe2d7665e7d63993c40876247dafc08ee9367571b37acb24e9f8

1.16.1 - Doesn't work
https://dump.viaversion.com/46799a60c62881c7341e848ac25091a9a4873b43982d30735e23cefaa0faf41d

1.16.5 - Doesn't work
https://dump.viaversion.com/472e982cf326abc259f74f0d1b4a5e145ef8e83f805f7efa0c89ddd5bd162d91

1.17 - Works
https://dump.viaversion.com/da14bfdc4889939694d5cb48f42e869c54f09870ba55da91b52e5183b2e1c3c4 #

### Steps to Reproduce

Install latest [Paper 1.16.5 (or versions below) Jar
Install ViaVersion
Join server and place sign

### Expected Behavior

The sign editor should remain open and not close automatically

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Spigot--596221b--9a1fc1e%20%28MC%3A%201.12%29](https://img.shields.io/badge/Platform-git--Spigot--596221b--9a1fc1e%20%28MC%3A%201.12%29-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by turnolos** [comment]
I can confirm the behavior is unchanged in paper 1.12.2 using the latest dev build of viaversion

**Comment by HowardZHY** [comment]
That's probably the reason why there are some empty signs in my 1.8.8 server.

**Comment by kennytv** [comment]
Actually, all the tested versions were invalid because you weren't using 4.3.2-SNAPSHOT builds. This definitely does not affect versions around 1.16 anymore (as long as you're using the snapshots and have Via on the backend)

**Comment by HowardZHY** [comment]
https://dump.viaversion.com/3244e5c8159fb78622f37a106b3f71739e03915988205334f5f58173de120a78
![2022-07-17_22 56 46](https://user-images.githubusercontent.com/96782166/179406410-207cd4b6-9f86-4a36-8c57-f38c08c6b8a3.png)
latest vv , nothing wrong
PS: I had " [Player] tried to change non-editable sign " msg before I update vv.

**Comment by Barvalg** [comment]
![Platform: git--BurritoSpigot--%22700f01e%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--BurritoSpigot--%22700f01e%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.4.0-1.19.1-pre5-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.4.0--1.19.1--pre5--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by turnolos** [comment]
> https://dump.viaversion.com/3244e5c8159fb78622f37a106b3f71739e03915988205334f5f58173de120a78 ![2022-07-17_22 56 46](https://user-images.githubusercontent.com/96782166/179406410-207cd4b6-9f86-4a36-8c57-f38c08c6b8a3.png) latest vv , nothing wrong PS: I had " [Player] tried to change non-editable sign " msg before I update vv.

Yes, but i can confirm it still does not work at least on version 1.12.2. Maybe versions around 1.16.5 are a different story, like i said I only tested 4.3.2-SNAPSHOT against paper 1.12.2

**Comment by Barvalg** [comment]
![Platform: git--BurritoSpigot--%22700f01e%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--BurritoSpigot--%22700f01e%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.4.0-1.19.1-pre5-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.4.0--1.19.1--pre5--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by HowardZHY** [comment]
@turnolos 

4.4.0 SNAPSHOT from vv-DEV, not 4.3.2

PS: 1.19 's fps is reeaallyy bad.

**Comment by turnolos** [comment]
You can see behaviour is very unusual in the latest 4.4.0 SNAPSHOT build while using paper 1.12 and Minecraft client 1.19

Please look at this gif: https://gyazo.com/6f9c3ebfc3d5eee21ce177f2279874c7

You can see that sometimes the sign editor works, sometimes it doesn't. It's very strange.
