### ISSUE TITLE
Lore pop-up windows do not have the height adjusted properly in 1.19 clients

### ISSUE THREAD

**Issue by JHarris12345** [ViaVersion/ViaVersion#3028]
### `/viaversion dump` Output

https://dump.viaversion.com/bfc023f72dfb7e451b435620ea5c970cf1498bf7619b1cb9fecce30e591a8d33

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

If you hover over a GUI item that has a large lore, the window appears too low and therefore goes off the page. In other clients, the window appears higher to ensure none of the lore goes off the page. Screenshot example:

https://gyazo.com/e66417dbc0349bc012c0c5ccce3f9f6f

In that image, there IS more lore below that last visible line

### Steps to Reproduce

1. Use a 1.19 client in any version server
2. Hover over a GUI item with a large lore
3. It will go off the page

### Expected Behavior

The lore window should appear higher so it does not go off the page

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--11%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Pufferfish--11%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.4.0-1.19.1-pre5-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.4.0--1.19.1--pre5--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(2.0.2-SNAPSHOT)-Outdated!-red?style=flat-square) </br>![ViaBackwards(4.4.0-1.19.1-pre5-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.4.0--1.19.1--pre5--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by tomcraft** [comment]
This is not Mojang issue tracker.

**Comment by JHarris12345** [comment]
I thought this would've been a VV issue. My bad. Also, my versions were the latest builds
