### ISSUE TITLE
Large error, half of the server was kicked

### ISSUE THREAD

**Issue by lukemango** [ViaVersion/ViaVersion#3029]
### `/viaversion dump` Output

https://dump.viaversion.com/c6c3ba073780f44fde8a22e82b7f91459f0f4b8b926c6903d67cc2fb2edef668

### Console Error
https://mclo.gs/gzbv0QE

### Bug Description

Half of players online were kicked, massive spam

### Steps to Reproduce

Unsure

### Expected Behavior

Players not to be kicked

### Additional Server Info

Velocity, Geyser + Floodgate, RedisBungee

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [x] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PufferfishPlus--18%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--PufferfishPlus--18%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Most likely a plugin sending bad chunk data
