### ISSUE TITLE
ViaVersion console warning.

### ISSUE THREAD

**Issue by YodaZen** [ViaVersion/ViaVersion#3030]
### `/viaversion dump` Output

https://dump.viaversion.com/f25388a883e9f46aa489d2b03cf1e0b7cdb985cf920e8a2bdf5009921a60ff89

### Console Error

```
https://paste.gg/p/anonymous/69d4758877584d838683b692e3d67888
```

### Bug Description

Idk

### Steps to Reproduce

I just looked at the console and saw this. No idea how to reproduce.
(Was working with DiSKy in skript, tho)

### Expected Behavior

Dont know what the warning does.

### Additional Server Info

Minecraft Version: 1.17.1
ViaVersion: 4.3.1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--411%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--411%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by YodaZen** [comment]
Works!
