### ISSUE TITLE
Weird console Error

### ISSUE THREAD

**Issue by ItzSkyylark** [ViaVersion/ViaVersion#3031]
### `/viaversion dump` Output

https://dump.viaversion.com/60ceb221301dadcadacb1c6ac8fe37c9a525dbf6b88a03099fd0668ef2774285

### Console Error

```
19.07 08:07:55 [Server]  [ViaVersion] ERROR IN Protocol1_19To1_18_2 IN REMAP OF CHAT_MESSAGE (0x0F)
```

### Bug Description

Remapping issue? 

### Steps to Reproduce

Unknown, its whenever I send a command on 1.19 client to 1.12.2 server

### Expected Behavior

convert packet translation correctly

### Additional Server Info

Used on Bungee, viaver on Paper side

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--33d42c8e%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--33d42c8e%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
That's an issue with adventure-platform shaded by one of your plugins, see https://github.com/KyoriPowered/adventure-platform/pull/95
