### ISSUE TITLE
Viaversion on Bungee-Spigot

### ISSUE THREAD

**Issue by JWJUN233233** [ViaVersion/ViaVersion#3032]
### Problem Description

I can't join server when I using Via-version
my server version is 1.16.5 but my client version is 1.16.5 ,too.
the reason is Outdated client Please use 1.16.5
[https://s1.ax1x.com/2022/07/21/jLRgxA.png](url)
but I'm 1.16.5  I don't know the problem
I'm a Chinese ,Maybe I can't speak out it well

### Solution Description

Null

**Comment by kennytv** [comment]
Please use the correct "Bug Report" issue template.

**Comment by HowardZHY** [comment]
更新BC
确保跨版本只装在BC或服务器上,而不是两个都装
