### ISSUE TITLE
kick when message displayed full screen

### ISSUE THREAD

**Issue by DJAMIRSAM** [ViaVersion/ViaVersion#3033]
### `/viaversion dump` Output

https://dump.viaversion.com/a2e2b5a992af0902ce45d995c3e881a84ab41b56b101b0a668dd7b2243bf8820

### Console Error

No error

### Bug Description

![image](https://user-images.githubusercontent.com/78499690/180273445-28082240-f4a0-4697-96fe-6f5860fd873d.png)

Players get kicked upon 
![image](https://user-images.githubusercontent.com/78499690/180277867-23e65e84-6811-471e-8fb2-e73db26142dd.png)
mesasges
(only in 1.19)

### Steps to Reproduce

1. log in with 1.19 game
2. have text that looks like this appear
![image](https://user-images.githubusercontent.com/78499690/180278161-b05097c1-cadd-4f5a-9154-c660965faf5d.png)

### Expected Behavior

player should not get kicked

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3246--Spigot--6c1c1b2--dc764e7%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-3246--Spigot--6c1c1b2--dc764e7%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by DJAMIRSAM** [comment]
Snapshot fixed issue
