### ISSUE TITLE
Error that minehut told me to report to github

### ISSUE THREAD

**Issue by AlexAmination** [ViaVersion/ViaVersion#3034]
### `/viaversion dump` Output

https://dump.viaversion.com/c81d154924cdfe08bf6d7ea3e0825a0fb43ca526c1580ecd0946747eaa636350

### Console Error

```
Put the paste.gg link or text here.
```
io.netty.handler.codec.DecoderException:com.viaversion.viaversion.exception.InformativeException

### Bug Description

i used a skript:

on right click:
	if player is holding a diamond horse armor named "&4Rocket Launcher":
		execute console command "/kittycannon %player%"

that shit kicked me and told me to report it here.

### Steps to Reproduce

I dont fucking know what da hell that shit means

### Expected Behavior

i dont fucking know

### Additional Server Info

fuck no

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--411%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--411%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by HowardZHY** [comment]
u can send the client disconnect screen, and make sure paste the full console error

**Comment by HowardZHY** [comment]
https://github.com/ViaVersion/ViaVersion/issues/3035 might relate?

**Comment by FormallyMyles** [comment]
Missing full info to diagnose
