### ISSUE TITLE
Error when changing entity equipment via packets

### ISSUE THREAD

**Issue by BigBoi320** [ViaVersion/ViaVersion#3035]
### `/viaversion dump` Output

https://dump.viaversion.com/28f4551b217dfef552022d51687a523bb5d73a858596b65834ddf3f63900bf78

### Console Error

https://paste.gg/p/anonymous/abc883442ab14000a65e1b6653ac5439

### Bug Description

Using Skacket and Skript to hide armour kicks every player and spits out an error

### Steps to Reproduce

1. Install Skript and Skacket on a 1.17.2 Minehut server
2. Login to the minehut server with a 1.18.2 client
3. give yourself the permission skript.effectcommands
4. type "!set armour of player to air in slot itemslot.helditem for all players" in chat

### Expected Behavior

it should set the held item of the player to air for all players

### Additional Server Info

I use paper with the following plugins: LuckPerms, Protocollib, Skacket, SkBee, SkDragon, Skore, SkQuerey, Skript, skript-reflect, skript-yaml, Vault, Viaversion and WorldEdit

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--411%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--411%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
That means you're sending packets with bad format/contents or are running a stacked Via setup
