### ISSUE TITLE
[1.19 -> 1.18.2] Chunk read error

### ISSUE THREAD

**Issue by RaphiMC** [ViaVersion/ViaVersion#3036]
### `/viaversion dump` Output

https://dump.viaversion.com/05b3de6e4f6d0f59d82d4d4fe660384403ab0d9aa8f6f70ba6568334d3c3f2aa

### Console Error

https://paste.gg/p/anonymous/1a05149854d3457cbc67b7f78308d7f6

### Bug Description

When joining on hypixel.net using the 1.18.2 protocol all chunks fail to parse. This might affect other servers as well, but only hypixel was tested.

### Steps to Reproduce

1. Set up ViaFabric for 1.19
2. Remove hypixel.net from `client-side-force-disable`.
3. Join hypixel using 1.18.2 protocol

### Expected Behavior

No chunk errors

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.4.7+5--main](https://img.shields.io/badge/Platform-0.4.7+5--main-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.3.0)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)
