### ISSUE TITLE
[1.19 -> 1.18.2] Chunk read error

### ISSUE THREAD

**Issue by RaphiMC** [ViaVersion/ViaVersion#3037]
### `/viaversion dump` Output

https://dump.viaversion.com/d45d2db973e997fdd9798b103eca20bef6d761de2b00b6029e5f5204b8d7c359

### Console Error

https://paste.gg/p/anonymous/1a05149854d3457cbc67b7f78308d7f6

### Bug Description

When joining on hypixel.net using the 1.18.2 (1.17 and 1.19 work, only 1.18 doesn't) protocol all chunks fail to parse. This might affect other servers as well, but only hypixel was tested.

### Steps to Reproduce

1. Set up ViaFabric for 1.19
2. Remove hypixel.net from `client-side-force-disable`.
3. Join hypixel using 1.18.2 protocol

### Expected Behavior

No chunk errors

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.4.7+5--main](https://img.shields.io/badge/Platform-0.4.7+5--main-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by creeper123123321** [comment]
may be related to https://github.com/Earthcomputer/multiconnect/commit/7a511c4ed819f699b0fd364b2c27b9c218267ae0
