### ISSUE TITLE
Viaversion End of stream error

### ISSUE THREAD

**Issue by AirRhyme** [ViaVersion/ViaVersion#3038]
### `/viaversion dump` Output

https://dump.viaversion.com/44c4db002d87ada7c7805e49462b22281f5ee707d45633086bbd7ec9a4abbf3b

### Console Error

https://paste.gg/p/anonymous/d1fe29b3894e4e7cbb337e8a1966dd25

### Bug Description

End of stream error on 1.12.2

### Steps to Reproduce

Login with 1.19(version I am using)
Wait
Get Kcicked

### Expected Behavior

You will be kicked with End of stream error

### Additional Server Info

I am running paper 1.12.2 with a bunch of plugins. I will list all of them
ViaVersion
Total Computers
Skript
PlaceholderAPI
iDisguise
HideAchivements
custom plugin I made to make hex color codes minecraft color codes
Geyser
BuycraftX
BanManagerBukkit
DeluxeTags
CratesReloaded
BossProShop
worldguard
worldedit
voidworld
voidteleport
viarewind
viabackwards
vault
tab
serverlistplus
SBA
QuickBoard
PlaceholderAPI(1.12.2 this time)
OldCombatMechanics
Multiverse Core
LuckPerms
HollographicDisplays
GadgetsMenu
EssentialsXSpawn
EssentialsXChat
DeluxeMenus
Citizens
cEssentialsX
Bedwars-0.2.22
AdvancedPortals

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1618%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1618%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 8 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by AirRhyme** [comment]
As of now, this error just happened again

**Comment by kennytv** [comment]
One or more of your jars are corrupted

**Comment by AirRhyme** [comment]
How am I supposed to figure out which one?
