### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by mayberks** [ViaVersion/ViaVersion#3039]
### `/viaversion dump` Output

https://dump.viaversion.com/57978d914480bfea02ad7dc3b1e889367d6c37d6c3b1be479ba25414fd1aaa07

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/3628826faada4e668e595888477c3e4e

### Bug Description

Players mysteriously drop out of the game. When they try to log in later, they get this error. There was no problem before. It started to form all of a sudden.

### Steps to Reproduce

I can't comment as I don't know what caused the problem.

### Expected Behavior

The server doesn't crash.

### Additional Server Info

I tried to update viaversion. I just sent you a dump with the latest version.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1609%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Purpur--1609%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by mayberks** [comment]
Note: As of now, I have deleted the plugin called Interactive Chat. I also deleted it via bungeecord. I haven't observed any crash issues for an average of 36 minutes. I don't know if it's because of that. Everything seems stable now. However, I wanted to open an issue in case it happens again.

**Comment by FormallyMyles** [comment]
More information is needed in regards to steps to reproduce, testing without plugins is ideal for determining a cause. It sounds likely that this may be down to a proxy plugin sending outdated data as that is a very common cause for these kind of issues. Happy to reopen if you're in need of further help / can provide steps to reproduce.
