### ISSUE TITLE
1.19.1

### ISSUE THREAD

**Issue by Ascol14** [ViaVersion/ViaVersion#3041]
### Problem Description

I would like play with my friends on the bedrock edition but they play on 1.19.1

### Solution Description

I don't know

### Alternatives

I'm going to see if they can rollback the version so I can play.

**Comment by kennytv** [comment]
ViaVersion has nothing to do with Bedrock, you're thinking of Geyser

**Comment by Ascol14** [comment]
But my server is in 1.12.2

Envoyé depuis Yahoo Mail pour Android 
 
  Le dim., juil. 24, 2022 à 15:50, Nassim ***@***.***> a écrit:   


ViaVersion has nothing to do with Bedrock, you're thinking of Geyser
