### ISSUE TITLE
SIGNS ARE EMPTY ON 1.17.1 SERVER WITH CLIENT NEWER HAN 1.17.1

### ISSUE THREAD

**Issue by Maftyyncz** [ViaVersion/ViaVersion#3043]
### `/viaversion dump` Output

https://dump.viaversion.com/8f5b8a563ab1ce23180678244d98f52a288c7840454ba91fba88f580f3dc31dc

### Console Error

```
Put the paste.gg link or text here.
```
no error

### Bug Description

Generated signs via chestshop,quickshop,armrent and similiar plugins are empty even their NBT tag is correct.
This issue persist with 1.17.1 server on for example 1.18/1.19 clients.
The issue does not persist on 1.16.5 server with any clients even with same viaversion so the issue is clearly on 1.17.1 servers.
Please fix.

Screenshot on 1.19 client on 1.17.1 server https://ctrlv.cz/Yh2y
Screenshot on 1.19 client on 1.16.5 server https://ctrlv.cz/mVQ5
Screenshot on 1.17.1 or lower client on 1.17.1 server https://ctrlv.cz/D8c5
Screenshot on 1.17.1 client or lower on 1.16.5 server https://ctrlv.cz/OrqG

### Steps to Reproduce

1. Login on 1.17.1 server with 1.18+
2. Create shop or something where signs are generating
3. The signs are empty.

### Expected Behavior

Text should not dissapear

### Additional Server Info

Using bungeecord.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--8%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Pufferfish--8%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-Outdated!-red?style=flat-square) </br>![ViaRewind(2.0.2): 9 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
That's a 1.17 Paper bug; it is bad nbt data.

**Comment by Maftyyncz** [comment]
So what can i do to prevent this instead updating to 1.18? 
using Platform: git--Pufferfish--8%20%28MC%3A%201.17.1%29

**Comment by kennytv** [comment]
Remove the filtered text part of sign nbt, or update to 1.18

**Comment by Maftyyncz** [comment]
![image](https://user-images.githubusercontent.com/110028650/180985040-975a19a8-8bf0-4b7f-8a99-504d501bde7b.png)
This is the nbt

**Comment by Maftyyncz** [comment]
https://github.com/UltraVanilla/cleanupstupidmojangshit fixed it

**Comment by ItsDronez** [comment]
> 

Just to be clear, this is for the latest paper build of 1.17.1?
