### ISSUE TITLE
1.19 CHAT

### ISSUE THREAD

**Issue by ConnorServers** [ViaVersion/ViaVersion#3044]
### `/viaversion dump` Output

https://dump.viaversion.com/362006a9cc05b291188e481b1368c15ada5aafdfa662a357a198a9e603f68491

### Console Error

[10:40:49 WARN]: [ViaVersion] ERROR IN Protocol1_19To1_18_2 IN REMAP OF CHAT_MESSAGE (0x0F) it is probably due to the clickable content

I HAVE TRIED DEV & LATEST BUILDS. 
Including viaversion 4.4.0-1

### Bug Description

I'm using the plugin DiscordSRV.

When I type /discordsrv link in 1.19 the message doesn't appear and throws ViaVersion error.
When I type /discordsrv link in 1.18.2 or lower, it works fine.

### Steps to Reproduce

Login with 1.19
Install discordsrv or a plugin that produces clickable text content.
If using discordsrv type /discordsrv link
No message will appear, unlike when on 1.18.2 or lower

### Expected Behavior

Sends the message to player

### Additional Server Info

N/A

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--33d42c8e%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--33d42c8e%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.4.0-1.19.1-rc3-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.4.0--1.19.1--rc3--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>![ViaRewind(2.0.2): 9 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.3.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.3.1)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
Update LuckPerms/other plugins using adventure platform

**Comment by ConnorServers** [comment]
> ![Platform: git--Paper--33d42c8e%20%28MC%3A%201.12.2%29](https://camo.githubusercontent.com/4c2f24d984da715082c73d6f758ca837e466704796884dbc40c06ea6215f9658/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d50617065722d2d33336434326338652532302532384d43253341253230312e31322e322532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.4.0-1.19.1-rc3-SNAPSHOT): Even with dev](https://camo.githubusercontent.com/43429995117a6c7a7e1805b0dfb9cef92f32e976e2dfc6630fe5b85404674ae6/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e342e302d2d312e31392e312d2d7263332d2d534e415053484f54292d4576656e253230776974686465762d627269676874677265656e3f7374796c653d666c61742d737175617265) ![ViaRewind(2.0.2): 9 commits behind master](https://camo.githubusercontent.com/573b4e2e6b6c44c8fae3f805501689ef6db1e8362ada13b990510117828f9206/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f566961526577696e6425323028322e302e32292d39253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaBackwards(4.3.1): Even with master](https://camo.githubusercontent.com/97cfbd3fcd3860f870c7da726b7c00d21a12abc81462f1d628d8a91bbd78f56b/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e332e31292d4576656e253230776974682532306d61737465722d627269676874677265656e3f7374796c653d666c61742d737175617265) Please try the **latest** build(s) from https://ci.viaversion.com/

Tried latest-dev and latest stable and latest spigot. None of these 3 versions work.

**Comment by ConnorServers** [comment]
> Update LuckPerms/other plugins using old versions of the adventure platform library

Tried with latest luckperms and just DiscordSRV & Viaversion. Still no solution.

**Comment by ConnorServers** [comment]
Why is this closed. It's not solved?

**Comment by kennytv** [comment]
I told you why. This is not a Via issue.

**Comment by kennytv** [comment]
https://github.com/DiscordSRV/DiscordSRV/blob/master/pom.xml#L568
