### ISSUE TITLE
plugin told and i did

### ISSUE THREAD

**Issue by Aadi-mone** [ViaVersion/ViaVersion#3045]
### `/viaversion dump` Output

https://dump.viaversion.com/7a6e0028990976b417188088ee63e1973138699856d1e8b1c3c20a9bf84bbab4

### Console Error

no errors

### Bug Description

![image](https://user-images.githubusercontent.com/87631878/181303237-5093d9bd-d05c-47b5-ba41-5033e9534c85.png)

### Steps to Reproduce

/mvtp survival

### Expected Behavior

that error messages should not come

### Additional Server Info

yes this is a proxy server with via version installed on both proxy and backend servers

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A866a450%3A468](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A866a450%3A468-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 9 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.3.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.3.1)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Aadi-mone** [comment]
the checklist is kinda messed up, 1st and 3rd are false.

**Comment by PierreSchwang** [comment]
> the checklist is kinda messed up, 1st and 3rd are false. 

The checklist has a reason, all values have to be true.
Follow the checklist (Completely) and create a new issue if the problem persists.
