### ISSUE TITLE
VIA VERSION 4.4.0 RESOURCEPACK BUG

### ISSUE THREAD

**Issue by Maftyyncz** [ViaVersion/ViaVersion#3048]
### `/viaversion dump` Output

https://dump.viaversion.com/d3b8f0881b5e133528021f48ef3a7535e035d4a7c02d6973655c49c3ceb6d6af

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

If client is 1.19.1 then new error happened after updating to viaversion 4.4.0
Dont know what causes that but when i remove forceresourcepack it works.
But i need it to work with resourcepack as it works for every other version.
https://ctrlv.cz/N2mq

### Steps to Reproduce

1. Start 1.19.1 launcher
2. join server

### Expected Behavior

work

### Additional Server Info

Latest bungee latest viaver

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--794%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--794%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.4.0): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.0)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.2): 9 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.4.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.0)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Maftyyncz** [comment]
Doesnt happen if player join with 1.19 client only for 1.19.1

**Comment by JohnS19** [comment]
Occurring to me as well on 1.19.1 with Waterfall build 500 and viaversion 4.4.1.

Waterfall debug mode shows viaversion with the following packet: ResourcePackSendPacket

I have tried the latest build(s) and it has not fixed the issue. The cached pack does not allow me to join on specifically 1.19.1.

**Comment by JohnS19** [comment]
Occurring to me as well on 1.19.1 with Waterfall build 500 and viaversion 4.4.1.

Waterfall debug mode shows viaversion with the following packet: ResourcePackSendPacket

I have tried the latest build(s) and it has not fixed the issue. The cached pack does not allow me to join on specifically 1.19.1.

**Comment by FormallyMyles** [comment]
The error provided doesn't seem to work for me, can you provide a new copy of it.
Otherwise can you confirm if you use proxy software like John?
