### ISSUE TITLE
Unable to log onto 1.19.1 server with 1.19 client

### ISSUE THREAD

**Issue by voigtman** [ViaVersion/ViaVersion#3049]
### `/viaversion dump` Output

https://dump.viaversion.com/c0f92852e1fffc8ddb9233c5d8b15033cdf7fd9a4c85ee0f872d836c7aac64b6

### Console Error

```
[00:22:00] [Netty Worker IO Thread #3/INFO]: [Mister_Jason] disconnected with: Kicked whilst connecting to Lobby: Outdated client! Please use 1.19.1
```

Using Waterfall 499
and Paper 86

No specific error displayed on Paper Server (Lobby)

### Bug Description

Using a 1.19.1 paper server behind Waterfall.

Waterfall 499
Paper 86

Tested on:
ViaVersion 4.4.0 (Spigot download)
ViaBackwards 4.4.0 (Spigot download)
ViaVersion 4.4.0 - build 738
ViaBackwards 4.4.0 - build 416

Players cannot connect to server with consoles older than current 1.19.1 release.

### Steps to Reproduce

Update server to 1.19.1 and update ViaVersion and ViaBackward to 4.4.0 (tested on Paper 83 - 86)
Attempt to log into server with 1.19 client (such as current Optifine) 
Player cannot log into server.

### Expected Behavior

Player should be able to access server as usual.

### Additional Server Info

Connection issue does not appear to be related to proxy (it allows older clients to connect by default.)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--86%20%28MC%3A%201.19.1%29](https://img.shields.io/badge/Platform-git--Paper--86%20%28MC%3A%201.19.1%29-3498db?style=flat-square) </br>![ViaVersion (4.4.0): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.0)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.0): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.4.0)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
Fixed with latest ci builds.
