### ISSUE TITLE
ViaVersion for 1.19.1 and Velocity - Invalid signature for profile public key.

### ISSUE THREAD

**Issue by Tomographix** [ViaVersion/ViaVersion#3050]
### `/viaversion dump` Output

https://dump.viaversion.com/7119863edcee41a6ef2ef397014cca71fd93371d1301aea930ff523802e8b47b

### Console Error

```
No real errors for this unfortunately. 

https://i.imgur.com/flzOPBL.png the error ingame. Yes, we did try restarting the game client.
```

### Bug Description

When using Velocity as a proxy with ViaVersion installed on individual servers, players on 1.19.1 can't join old version servers, such as 1.19.1. I've spoken to a few different people about this today, here is the Velocity discord discussion with @electronicboy on the issue. I can update most of my servers on the proxy to 1.19.1 without any issues, one server needs to be on an older version though, so would really appreciate having ViaVersion work with Velocity.

Tomographix — Today at 20:33
Just trying to clarify the conversation above, so velocity won't / isn't expected to work with 1.19.1 and viaversion?

electroniccat[no-ping] — Today at 20:33
velocity expects to be in a valid state to do its own checks
if something violates said state, it will cause issues
it's 100% on the plugins mangling said state to fix it

Tomographix — Today at 20:34
So that is a no then?

electroniccat[no-ping] — Today at 20:35
correct

Tomographix — Today at 20:35
Ty. 

electroniccat[no-ping] — Today at 20:35
if via breaks state, theres nothing we can do about that, we're not removing our validation

Tomographix — Today at 20:36
I am correct in thinking Waterfall hasn't had the same issue as velocity?

electroniccat[no-ping] — Today at 20:36
bungees support of this stuff is literally bare minimal
md literally removed chat support from 1.19+

### Steps to Reproduce

1. Setup a proxy system running Velocity 
2. Have a backend server running 1.19 (or older)
3. Have that backend server running ViaVersion
4. Try connect

### Expected Behavior

Hopefully you would be able to join a 1.19 server using 1.19.1.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--76%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Paper--76%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.1--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
You can't join servers that enforce secure profiles as 1.19 and 1.19.1 profile keys are not comptible.
