### ISSUE TITLE
Cannot login with any client version except 1.19.1

### ISSUE THREAD

**Issue by MajdT51** [ViaVersion/ViaVersion#3051]
### `/viaversion dump` Output

4.4.0

### Console Error

 no console Error

### Bug Description

Players on my server cannot connect with a client version lower than 1.19.1

We have Paper 1.19.1-86 and ViaBackwards-4.4.0 and I tried with 1.19 and 1.18.2

### Steps to Reproduce

1. update the server from 1.19 to 1.19.1 by Paper 1.19.1-86 , ViaVersion-4.4.0 and ViaBackwards-4.4.0
2. try to login with client 1.18.2 or 1.19

### Expected Behavior

People with clients higher than 1.17 can join 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Follow the issue template.
