### ISSUE TITLE
player can't join server with viaversion. Velocity + 1.19 server

### ISSUE THREAD

**Issue by steveminecraft2** [ViaVersion/ViaVersion#3053]
### `/viaversion dump` Output

https://dump.viaversion.com/c784ddc6ffd30af459ae384494eb8516fdadc658d3ad9d6a005a49b406502750

### Console Error

https://paste.gg/p/anonymous/a3aa96e5a5364057b2c115e25c3d7dd4

### Bug Description

player can't  join to the server when server is created: velocity + 1.19 server. when viaversion is installed, players cannot enter from version 1.19 (the server is set to this version) and 1.19.1

### Steps to Reproduce

1. install velocity and 1.19 server
2. install plugin viaversion to velocity and 1.19 server
3. join to the server

### Expected Behavior

There will be no error, players will be able to enter the server

### Additional Server Info

velocity plugins: BotSentry-9.5.1-THANATOS-SpigotMC 
 LightMOTD-0.1.3.jar	
 LiteBans (6).jar
 LuckPerms-Velocity
 Pl-Hide-Pro-2.5.1 (1).jar	
 SkinsRestorer (8).jar
 ViaVersion-4.4.1.jar	
 protocolize-velocity.jar	

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--6be344d9--b162%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--6be344d9--b162%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Velocity does not support 1.19.1 yet. If you can't join with 1.19 either, that's the fault of another plugin

**Comment by blake-tisbury** [comment]
I don't mean to comment on a closed issue but I figured it would be beneficial to know: I'm having this exact same issue when using the Velocity 1.19.1 dev branch. 

On top of 1.19 players not being able to connect, 1.19.1 players cannot see chat and get kicked with [this error](https://paste.gg/p/anonymous/537eee80534645c0853144f98581ce4d)

This issue is currently limiting players to join on 1.18 only.

**Comment by steveminecraft2** [comment]
> Velocity does not support 1.19.1 yet. If you can't join with 1.19 either, that's the fault of another plugin

only that if I remove viaversion from velocity then normally player 1.19 can already be. The problem is with the plugin, that players even from version 1.19 can't enter

**Comment by kennytv** [comment]
> install plugin viaversion to velocity and 1.19 server
Don't do that, see the checklist you ticked
