### ISSUE TITLE
1.19.1

### ISSUE THREAD

**Issue by dinobossytnew** [ViaVersion/ViaVersion#3054]
### `/viaversion dump` Output

https://dump.viaversion.com/8204ee108bc053399cea871c3354319f3781de6e6d49b6cfa30c0a08648af8d4

### Console Error

https://mcpaste.io/245ec1e5effb33f4

### Bug Description

Remove resonant item from minecraft 1.19 in purpur 1.19.1 bug. it turns to stone.

### Steps to Reproduce

Remove resonant item from creative in 1.19
is replaced by a stone.

### Expected Behavior

null

### Additional Server Info

Purpur 1.19.1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1737%20%28MC%3A%201.19.1%29](https://img.shields.io/badge/Platform-git--Purpur--1737%20%28MC%3A%201.19.1%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.2): 9 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.4.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
1.19 client support on 1.19.1 servers is limited and does a roundtrip from 1.19.1->1.18.2->1.19, that's expected.

**Comment by dinobossytnew** [comment]
jm ok
