### ISSUE TITLE
(found in 4.3.1) 1.19 Recovery Compass doesn't point to the right position

### ISSUE THREAD

**Issue by SSUPII** [ViaVersion/ViaVersion#3056]
### `/viaversion dump` Output

https://dump.viaversion.com/41f6dcca10207849964cefdc7921b68d65b9b63f94f6b0308d5ea6b61c8ea795

### Bug Description

The Recovery Compass (https://minecraft.fandom.com/wiki/Recovery_Compass) is being translated to a Compass in 1.18 clients without changing the original behavior of the latter.

### Steps to Reproduce

Obtain Recovery Compass for 1.18 player (Either by crafting, /give command or from Creative Mode)

### Expected Behavior

The Recovery Compass, while being translated to a Compass, should have its features integrated.

### Additional Server Info

Tested on Purpur 1.19(Unknown build) and Purpur 1.19.1-1741

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1741%20%28MC%3A%201.19.1%29](https://img.shields.io/badge/Platform-git--Purpur--1741%20%28MC%3A%201.19.1%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
We don't/cant add features of newer versions without messing things up in some regard
