### ISSUE TITLE
 ignaty_b lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template {Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$2 (Anonymous)} Actual Error

### ISSUE THREAD

**Issue by ignatyb** [ViaVersion/ViaVersion#3057]
### `/viaversion dump` Output

https://dump.viaversion.com/cfb59dc5a940337d6216828faa9997eddf31564ad6393e6d7f7ebfe470368d26

### Console Error

ignaty_b lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$2 (Anonymous)}
Actual Error: 

### Bug Description

Trying to connect -- getting this error. Everybody else can connect though

### Steps to Reproduce

1. Login with any version
2. Get kicked with error

### Expected Behavior

Enter the server and play

### Additional Server Info

I use Paper 1.19 with EssentialsX, AuthMe, bStats, ChatRadius, FirstJoinSpawn, Geyser-Spigot, LuckPerms, PluginMetrics, QualityArmory, RedProtect, SimpleSit, TradeSystem, Vault, ViaBackwards, ViaVersion, WorldEdit

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--50%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Paper--50%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.3.1)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)
