### ISSUE TITLE
got an error that says me to put it on github

### ISSUE THREAD

**Issue by ignatyb** [ViaVersion/ViaVersion#3058]
### `/viaversion dump` Output

https://dump.viaversion.com/3e3773d8f51bc98789cbde3992a554d7c145b2f237d713e6041cfe85d3a08113

### Console Error

ignaty_b lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$2 (Anonymous)}
Actual Error: 

### Bug Description

Can't connect to my server. Everyone else can though

### Steps to Reproduce

1. try to connect with any version
2. get an error

### Expected Behavior

connect to the server

### Additional Server Info

I use Paper 1.19 with EssentialsX, AuthMe, bStats, ChatRadius, FirstJoinSpawn, Geyser-Spigot, LuckPerms, PluginMetrics, QualityArmory, RedProtect, SimpleSit, TradeSystem, Vault, ViaBackwards, ViaVersion, WorldEdit

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--50%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Paper--50%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
We need the full error.

**Comment by ignatyb** [comment]
> We need the full error, otherwise it's likely an issue with another plugin.

I'm sorry, but it is a full error.

**Comment by ignatyb** [comment]
> We need the full error, otherwise it's likely an issue with another plugin.

Idk what is this, but maybe it will help
https://paste.gg/p/anonymous/acd7f2c815e941a0b826f1bdc6bb2a06

**Comment by kennytv** [comment]
That means either you have duplicated ViaVersion/ViaBackwards plugin files or the ones you have are corrupted

**Comment by ignatyb** [comment]
> That means either you have duplicated ViaVersion/ViaBackwards plugin files or the ones you have are corrupted

just reinstalled both of the plugins and issue still persists. as i said before, other players can play without a problem

**Comment by kennytv** [comment]
Then you have multiple jars of either VV or VB or something else messing up jar loading - definitely not a Via issue though

**Comment by kennytv** [comment]
I misread the error sorry; you have an item with bad NBT data somewhere, where the Lore is a string instead of a listtag

**Comment by ignatyb** [comment]
> I misread the error sorry; you have an item with bad NBT data somewhere, where the Lore is a string instead of a listtag

Oh, ok, np. But how can I fix that?

**Comment by ignatyb** [comment]
> item with bad NBT data

sorry, i'm newbie, i may not know some basic things :) i can solve this issue only by playing on different account, right?

**Comment by ignatyb** [comment]
i've changed my account, but bug appeared again when i've tried to use command
/give @s name_tag{display:[{"name":"nazar"}]}
it kicked me
now i can't join my server again, lol. is this a bug?

**Comment by kennytv** [comment]
That's invalid nbt data. Log in with the same client as server version and delete the bad items. See https://www.gamergeeks.net/apps/minecraft/give-command-generator for example for what the correct data would look like (like `/give @s acacia_boat{display:{Name:'[{"text":"Hi"}]'}} 1`). While *technically* this is an issue with Via in that it does not accept bad NBT data where Vanilla does, it's still bad data
