### ISSUE TITLE
Console spam error

### ISSUE THREAD

**Issue by Rhys00** [ViaVersion/ViaVersion#3060]
### `/viaversion dump` Output

https://dump.viaversion.com/3581b9504af5abd616f1fbee20b1888a6fba8db4b10b4ad40ae7649a6806076e

### Console Error

https://paste.helpch.at/ujidigukip.shell

### Bug Description

I am not sure why the bug is even occurring, it just constantly spams my console . 

### Steps to Reproduce

I have no idea sorry.

### Expected Behavior

N/A

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by KyleTheDev** [comment]
Im getting this exact same error, whenever someone joins from 1.19+ this error spams the console, my server got botted a few days ago and this popped up in the console

**Comment by PureMC** [comment]
Same issue here.

**Comment by FormallyMyles** [comment]
This is potentially safe to ignore if it's not causing issues. Viaversion provides these errors to be useful when there is an actual issue and not invalid data. If you need to prevent attacks I'd suggest looking at firewall limiting / other software.
