### ISSUE TITLE
ViaVersion Console Spam When Bot Attacks

### ISSUE THREAD

**Issue by IAmOarcle** [ViaVersion/ViaVersion#3062]
### `/viaversion dump` Output

https://dump.viaversion.com/451fec2719dafe1e1d56fe8ee20aded585a5fd9ff3f5b4004af5ff0656688f56

### Console Error

https://paste.gg/p/anonymous/e08516394eb24c498aedf33fe26b642d

### Bug Description

don't sure but when using MCStorm Bot Attack 1.19.1 attack on server 1.19 and it has these messages.

### Steps to Reproduce

1. Use https://mcstorm.io/
2. go to bot attacks
3. change version to 1.19.1 and put ip
4. boommmm server crashed with viaversion console spam

### Expected Behavior

-

### Additional Server Info

-

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1732%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Purpur--1732%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
https://github.com/ViaVersion/ViaVersion/issues/3061#issuecomment-1200139177

**Comment by IAmOarcle** [comment]
> [#3061 (comment)](https://github.com/ViaVersion/ViaVersion/issues/3061#issuecomment-1200139177) And the mcbots code is probably outdated and not actually compatible with 1.19.1

Can you fix it?

**Comment by kennytv** [comment]
No, that's not a Via issue.

**Comment by IAmOarcle** [comment]
> No, that's not a Via issue. That's MCBots or whatever upper layer you may have not properly supporting 1.19.1 protocol

How to disable messages? because my server got crashed by console spam.
