### ISSUE TITLE
Hope 1.19 client can join the 1.19.1 server

### ISSUE THREAD

**Issue by disymayufei** [ViaVersion/ViaVersion#3063]
### Problem Description

I'm frustrate with the 1.19 client cannot join the 1.19.1 server with the viaver 4.4.1.Many mods are also stopped with version 1.19, and it cause a large part of players dont want update their version.

### Solution Description

1.19 and the lower version can join the 1.19.1 server with viaversion.

**Comment by kennytv** [comment]
They can; you can join our support Discord if you need any help with setting it up properly.
