### ISSUE TITLE
Can't connect to the server using Bedrock v1.19.0

### ISSUE THREAD

**Issue by r0astPiGGy** [ViaVersion/ViaVersion#3064]
### `/viaversion dump` Output

https://dump.viaversion.com/617017cf12e787cf0ca1231c841946b6cb77878b3f2d2345c8543bc6048deb59

### Console Error

https://paste.gg/p/anonymous/007dcbaf38354718be42498c53a51cc9

### Bug Description

Can't connect to the server using Bedrock v1.19.0

### Steps to Reproduce

1. Login with Minecraft Bedrock 1.19.0
2. Join the server
3. You got kicked from the server: "Connection closed."

### Expected Behavior

The player should have logged into the server normally

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--6be344d9--b162%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--6be344d9--b162%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by Camotoy** [comment]
Bedrock has nothing to do with ViaVersion. Thanks anyway!

**Comment by Camotoy** [comment]
But to your actual issue, Velocity isn't yet updated to 1.19.1. Use this Geyser build until Velocity is updated: https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/1157/
