### ISSUE TITLE
Console spam (bungeecord)

### ISSUE THREAD

**Issue by andriycraft** [ViaVersion/ViaVersion#3065]
### `/viaversion dump` Output

https://dump.viaversion.com/9c71f3439d1db1bb344ff4f0f2261d94b64a04ef81c4957b7c1df0a68cd9b90b

### Console Error

https://paste.gg/p/anonymous/f181b3fd48e349a891d87a7bdf5db803

### Bug Description

joining the server from any client version will cause the error
(bungeecord server)

### Steps to Reproduce

1. Join the server
2. See console error

### Expected Behavior

Do not show the error

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.0.5](https://img.shields.io/badge/Platform-1.0.5-3498db?style=flat-square) </br>![Flamecord is not supported](https://img.shields.io/badge/Unsupported%20Platform%20-%20Please%20use%20Waterfall/Bungee%20instead%20or%20put%20all%20Via*%20plugins%20to%20the%20backend%20servers-orange?style=flat-square) </br>![ViaVersion (4.4.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by andriycraft** [comment]
used ViaVersion-4.4.1

**Comment by andriycraft** [comment]
ok
