### ISSUE TITLE
 [ViaVersion] Failed to get 1.13 item for 383

### ISSUE THREAD

**Issue by haroldrc** [ViaVersion/ViaVersion#3066]
### `/viaversion dump` Output

https://dump.viaversion.com/a2bae5990c01f72c9a8b8e6a4d63811469ad190722b6eeb59f95c28b49fd45d6

### Console Error

 [ViaVersion] Failed to get 1.13 item for 383

### Bug Description

 [ViaVersion] Failed to get 1.13 item for 383

### Steps to Reproduce

login with a 1.18 client

### Expected Behavior

mh

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--NachoSpigot--%2274ed0ea%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--NachoSpigot--%2274ed0ea%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
That means you tried picking an item that doesn't exist on 1.8
