### ISSUE TITLE
1.19 blocks and mobs are not appearing correctly on 1.19 clients

### ISSUE THREAD

**Issue by voigtman** [ViaVersion/ViaVersion#3067]
### `/viaversion dump` Output

https://dump.viaversion.com/34cf624b646e0438443f68a0b8abde2bf890b5807e6ef1c818eba62f3ffcf3c1

### Console Error

```
none
```

### Bug Description

This affects 1.19 clients on a 1.19.1 server.

All 1.19 blocks were previously useable and visible to the player.
Now froglights look like sealanterns
Frog spawn egg looks like a tropical fish spawn egg
reinforced deepslate is obsidian, the warden an iron golem, sculk shrieker an end portal frame .... etc
All look as they might for a 1.18 and earlier player.

Additionally, in creative: when putting an 1.19 mob spawn egg or block in your inventory, it becomes stone.

### Steps to Reproduce

Use a 1.19 client used on 1.19.1 server

### Expected Behavior

1.19 blocks to appear and work as they should

### Additional Server Info

Tested on: 
Paper 1.19.1 builds 86 - 94

ViaVersion 4.4.1 release - 4.4.2 snapshot 629 
ViaBackward 4.4.1 release - 4.4.1 snapshot 279

Clients used: 
Minecraft Vanilla
Optifine

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--94%20%28MC%3A%201.19.1%29](https://img.shields.io/badge/Platform-git--Paper--94%20%28MC%3A%201.19.1%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
See https://github.com/ViaVersion/ViaBackwards/issues/482

**Comment by voigtman** [comment]
Won't fix it eh?

**Comment by ImAnkl3** [comment]
i am experiencing this on my 1.19.1 server, i am on 1.19 and it seems like i'm seeing 1.18 blocks? Mangrove Planks -> Acacia Planks, etc.
