### ISSUE TITLE
ERROR IN Protocol1_19To1_18_2 IN REMAP OF CHAT_MESSAGE (0x0F)

### ISSUE THREAD

**Issue by andrewkm** [ViaVersion/ViaVersion#3070]
### `/viaversion dump` Output

https://dump.viaversion.com/eeaaf33b78ed7f71e49175e9f14d35cf450280a5ec01f225e9c0583c71576ff1

### Console Error

`[Server thread/WARN]: [ViaVersion] ERROR IN Protocol1_19To1_18_2 IN REMAP OF CHAT_MESSAGE (0x0F)`

### Bug Description

When running commands that output colorful text (such as https://github.com/drtshock/PlayerVaults by @mbax) the above error occurs and the text is not shown in chat on a 1.12.2 server (using a 1.19.1 client).

Example of **/pv 1** command on a 1.19.1 server: https://i.imgur.com/lOMe7YH.png
The same command on a 1.12.2 server using the latest ViaVersion (4.4.2 Build 629) displays nothing in chat and instead throws the above warning into console.

### Steps to Reproduce

1. Login with a 1.19.1 client onto a 1.12.2 server
2. Use https://github.com/drtshock/PlayerVaults on the 1.12.2 server
3. Use a command such as /pv 1
4. View error in console

### Expected Behavior

Text is output correctly into chat and no error is displayed.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1619%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1619%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
PlayerVaults is using a version of adventure-platform-bukkit that writes bad packet data with Via API; it needs to use the latest snapshot version of the library, being `4.1.2-SNAPSHOT` (to be changed here https://github.com/drtshock/PlayerVaults/blob/master/pom.xml#L104), that'll fix the issue
