### ISSUE TITLE
ViaVersion 1.4.2 dev treating 1.19 clients as if they were older clients (subsituting 1.19 blocks)

### ISSUE THREAD

**Issue by Anna-Raven** [ViaVersion/ViaVersion#3074]
### `/viaversion dump` Output

https://dump.viaversion.com/33819af3a3ccbe6cf8d4e7a786896476653353499cf3b96fec9863e455b8ab1e

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

When joining a 1.19.1 server with a 1.19 client, blocks such as mangrove logs and sculk blocks are swapped for replacement blocks.

The server is:
[22:06:38 INFO]: This server is running Paper version git-Paper-101 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: ceef4b9)

No other plugins:
[22:07:03 INFO]: Plugins (2): ViaBackwards, ViaVersion

The client is vanialla 1.19 with no mods

Our ViaVersion config file
[ViaVersion - config.yml - .txt](https://github.com/ViaVersion/ViaVersion/files/9238501/ViaVersion.-.config.yml.-.txt)

ViaBackwards config file is not modified

### Steps to Reproduce

Login with a 1.19 Java client.
Examine any block added in 1.19, you will see that it has been substituted for a pre-1.19 block

### Expected Behavior

Blocks should not be substituted.

### Additional Server Info

Test server was stripped down to just ViaVersion and ViaBackwards for verifying that we weren't seeing a plugin conflict.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--101%20%28MC%3A%201.19.1%29](https://img.shields.io/badge/Platform-git--Paper--101%20%28MC%3A%201.19.1%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Camotoy** [comment]
Currently works as intended. https://github.com/ViaVersion/ViaBackwards/issues/482 

Thanks anyway.

**Comment by Anna-Raven** [comment]
Thanks for the link!
