### ISSUE TITLE
Everyone gets booted and cant log backin

### ISSUE THREAD

**Issue by Zaniun** [ViaVersion/ViaVersion#3076]
### `/viaversion dump` Output

https://dump.viaversion.com/a724686e04c3659afec7a78e7e23c8cb2043465e5925a0318b52de426514b5c4

### Console Error

https://paste.gg/p/anonymous/c297e2d8d0154b3788f3cfaa7efb1372

### Bug Description

Server threw off a bunch of players and most werent able to rejoin, even when matching the servers version.
Restarting the server removed the error, however server appears offline for half of our playerbase

### Steps to Reproduce

I do not know how to reproduce this. Happened out of nowhere.

### Expected Behavior

Expected nothing out of the regular. Server was running just fine

### Additional Server Info

AdvancedRegionMarket, AltDetector, AntiCurse, AsyncWorldEdit, BentoBox, ChestShop, CoreProtect, DecentHolograms, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsDiscord, EssentialsSpawn, floodgate, Geyser-Spigot, LuckPerms, MendingEnchant, MobsManager, ProtocolLib, SecondThreadAPI*, spark, Spleef*, SuperVanish, TCPShield, Vault, ViaBackwards, ViaVersion, VillagerOverhaul, VotingPlugin, Vulcan, WorldEdit, WorldGuard, WorldGuardExtraFlags

Server is Paper

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--%22df630a2%22%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Paper--%22df630a2%22%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.4.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
Most likely the fault of another plugin or upper layer not handling login changes properly - try without those first
