### ISSUE TITLE
Cancelling BlockBreakEvent making spawners to turn into pig spawners (visual bug)

### ISSUE THREAD

**Issue by OmerBenGera** [ViaVersion/ViaVersion#3077]
### `/viaversion dump` Output

https://dump.viaversion.com/c0389407a9a96d00dafa2435ea2c9d4211c8c8501189d771e3ac9fd5a51b33a7

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

If you cancel the BlockBreakEvent and break a spawner, it will glitch out and seen as pig spawner, even tho in reality it isn't. By relogging or leaving and entering the chunk it will show correctly again.
This was tested in 1.19 and 1.18, and occurs with recent versions of ViaVersion.
After removing ViaVersion it worked as intended again.

### Steps to Reproduce

1. Get a plugin that cancels BlockBreakEvent (claiming plugin, for example)
2. Break a spawner
3. It will be shown as pig spawner

### Expected Behavior

Spawner should stay the same

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1632%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Purpur--1632%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>
