### ISSUE TITLE
Error and can't connect on 1.18.2

### ISSUE THREAD

**Issue by Ariouz** [ViaVersion/ViaVersion#3081]
### `/viaversion dump` Output

https://dump.viaversion.com/3c5616a874e2aa8be4e0f908aeb66f5c1540479e3831226b50d4ed80632c6157

### Console Error

https://paste.gg/p/anonymous/cd61ea3bde2c4ecb9c652d0b39d21bea

### Bug Description

I'm trying to connect using 1.18 on 1.18.2 server (velocity + paper).
I added viaversion and viabackwards to allow 1.18.(1) to connect and i blocked <1.18.
When i try to log in i get this error.

### Steps to Reproduce

1. Set a velocity proxy on 1.18.2
2. Add a paper server (1.18.2)
3. add viaversion and viabackwards
4. block <1.18
5. try to login

### Expected Behavior

Log into the server

### Additional Server Info

I tried 2 cases:

Velocity 1.18.2 with only viaversion and viabackwards, none for paper 1.18.2 -> "Incompatible client! Please use 1.7.2-1.18"
Velocity 1.18.2 with only viaversion and viabackwards, same plugins for paper 1.18.2 -> Error

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.1](https://img.shields.io/badge/Platform-velocity%203.1.1-3498db?style=flat-square) </br>![ViaVersion (4.4.1): 10 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-10%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.4.1): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Ariouz** [comment]
Solved ! Thanks mr. Bot
