### ISSUE TITLE
Enforces secure chat doesnt affect 1.19.1 client on 1.19 server

### ISSUE THREAD

**Issue by KaspianDev** [ViaVersion/ViaVersion#3082]
### `/viaversion dump` Output

https://dump.viaversion.com/4ee0a34c8b04283cb044fecbee95c04465f56cb9bf3aff2b435212715bd2110d

### Console Error

No errors

### Bug Description

I currently modify Enforces secure chat in SERVER_DATA packet to true.

But, when server is specifically 1.19 and client 1.19.1, setting it to true, does not work, client still thinks it doesnt enforce secure chat.
However, if server is lets say 1.18.2, and client 1.19.1 of course, everything works fine.

so i believe fault is in 1.19->1.19.1

https://github.com/ViaVersion/ViaVersion/blob/master/common/src/main/java/com/viaversion/viaversion/protocols/protocol1_19_1to1_19/Protocol1_19_1To1_19.java#L203
and it could be related to this line, these lines

my goal is to tell client that server enforces secure chat

When i compile via, changing this line
`
                create(Type.BOOLEAN, false); // Enforces secure chat
`
Like so
`
                create(Type.BOOLEAN, true); // Enforces secure chat
`
Everything works correctly, but i know its not a good fix
### Steps to Reproduce

1. Install viaversion
2. In my scenario use packetevents
3. Set `setEnforceSecureChat` to true in `PacketType.Play.Server.SERVER_DATA`

### Expected Behavior

Player should not see the popup, as in other server versions.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--81%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Paper--81%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by Camotoy** [comment]
I don't think this is our issue. It sounds like you need to make sure PacketEvents is handling the packet after Via for your option to work.

**Comment by KaspianDev** [comment]
> I don't think this is our issue. It sounds like you need to make sure PacketEvents is handling the packet after Via for your option to work.

Via loads before PacketEvents (i have it in softdepends)

**Comment by kennytv** [comment]
The plugin load order has nothing to do with packet processing, that's not a Via issue

**Comment by retrooper** [comment]
PacketEvents is handling packets after ViaVersion.

**Comment by retrooper** [comment]
Basically, enforceSecureChat field was added on 1.19.1 servers, so since I listen to packets for the server version (incoming i'm after via, and outgoing i'm before via) so I don't have control over this field. Everything else is fine. I don't know whats going on, but theres for sure no issue on my end.

**Comment by KaspianDev** [comment]
@kennytv could you look back into it?

**Comment by kennytv** [comment]
No.

> so since I listen to packets for the server version (incoming i'm after via, and outgoing i'm before via) so I don't have control over this field

**Comment by kennytv** [comment]
To add to that, on 1.18.2 this obviously ""works"" because the packet doesn't exist at all, so there's also no boolean provided that could even be set to true or false.
