### ISSUE TITLE
VIA 4.4.2 console error occurred

### ISSUE THREAD

**Issue by xuanxuan197068** [ViaVersion/ViaVersion#3083]
### `/viaversion dump` Output

https://dump.viaversion.com/1d57f1840197797e0ee59caa1de080b2b99f587e345b668fda2816e9f069f4e1

### Console Error

```
[Put the paste.gg link or text here.](https://pastebin.com/HtKqqCxi)
```

### Bug Description

I currently use Waterfall and use VIA 4.4.2, I get a series of error in the console while I do version crossing. When I went back from 1.19 to 1.8.8(spigot)，blocks and entities will not load but in the void.

### Steps to Reproduce

1,login with 1.19 client.
2,logging in 1.8.8 hub.
3,u **/server <name>** transferred to 1.19
4,u **/hub** return to 1.8.8 hub.
5,blocks and entities not loaded meanwhile error information occurred in console.

### Expected Behavior

The player should be able to cross versions normally without any errors

### Additional Server Info

waterfall-1.19-500.jar
![`ZX7MYK@(Y(NAL XJMK4W@1](https://user-images.githubusercontent.com/110676332/183088985-e8450480-e59e-4c2c-9c0d-15b28221e1e0.png)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A42d9c68%3A500](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A42d9c68%3A500-3498db?style=flat-square) </br>![ViaVersion (4.4.2-SNAPSHOT): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.2--SNAPSHOT)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.2-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.4.2--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
Switching between post and pre 1.16 servers is broken, that's tracked elswhere. Ideally, please move Via onto your individual backend servers, as you otherwise miss out on important backend info used in protocol translation (especially if client and server version are that far apart)
