### ISSUE TITLE
ERROR in console  "exception encountered" 

### ISSUE THREAD

**Issue by WieszczY85** [ViaVersion/ViaVersion#3084]
### `/viaversion dump` Output

https://dump.viaversion.com/f568d533722fe0ff1ac2e4cab1e4704e4f74b0f29989d563bc1710711c2e4187

### Console Error

```
[https://pastebin.com/dK0NxBQe](https://pastebin.com/dK0NxBQe)
```

### Bug Description

It constantly kicks players out when in contact with a mob or some blocks

### Steps to Reproduce

Tested several times with and without VIA
The problem disappears after removing VIA

### Expected Behavior

Proper functioning of the plugin that allows players to enter from other versions

### Additional Server Info

Velocity 3.1.2-SNAPSHOT (git-0b22985f-b170)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--0b22985f--b170%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--0b22985f--b170%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2-SNAPSHOT): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.2--SNAPSHOT)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.1): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by WieszczY85** [comment]
I have tried, the problem persists

**Comment by FormallyMyles** [comment]
Can you paste your latest dump? And have you tried testing without other plugins on velocity / latest build? Seems related to profiles based on the error not blocks.

**Comment by WieszczY85** [comment]
I tested and the problem occurs in conjunction with LimboFilter + LimboAPI plugins

https://dump.viaversion.com/1baeefe3c1a7649ebc2dee192049933719d12af8e656e72d5c33227062e9b5fb

https://pastebin.com/kFe02k15

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--4b774255--b178%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--4b774255--b178%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.2)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.2): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.2)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by FormallyMyles** [comment]
I would suspect this is something on their side, otherwise, I would suggest moving ViaVersion to your backend servers instead to attempt to avoid the issue as there's not much else we can do from our side.

**Comment by WieszczY85** [comment]
I reported the matter here and to them. Nevertheless, the bug is from your plugin. Separately, LimboFilter works flawlessly, the same as VIA without Limbo. It is only in combination that the player crashes and errors in the console

**Comment by FormallyMyles** [comment]
That is because invalid data is going through the ViaVersion translation layer, ViaVersion can't translate data it can't understand. Hence why you should move it to the backend if you wish to continue with your current setup.

**Comment by WieszczY85** [comment]
So I will. I am surprised, however, that so far everything was ok. I only update VIA and Velocity.
