### ISSUE TITLE
cant connect to server

### ISSUE THREAD

**Issue by glassesglasses8** [ViaVersion/ViaVersion#3085]
### `/viaversion dump` Output

/viaversion dump

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

cant connect to server
![image](https://user-images.githubusercontent.com/109359960/183500750-ac8efb66-5a02-4141-8bcd-ea7afdf60195.png)

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/109359960/183501090-0a5afdbe-57e5-4de6-a14e-a6bb8ebc76e6.png)

### Expected Behavior

wont connect to server

### Additional Server Info

ViaVersion

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
Fill out the issue template fully otherwise we're unable to help.
