### ISSUE TITLE
Bump version to 4.4.2, as 1.19.2 released

### ISSUE THREAD

**Issue by HowardZHY** [ViaVersion/ViaVersion#3086]
### Problem Description

Bump VV y VB's version to 4.4.2

### Solution Description

dump.viaversion.com/e2a4e3b385d7198fa2a114678b799cfa7e5fcb4d4f7f453db1cf07353a134282
*I have to restart my server but not now*

**Comment by Camotoy** [comment]
There's not really a pressing need for this because 1.19.1 and 1.19.2 are protocol-compatible.
