### ISSUE TITLE
1.7.x gets kicked from server (1.18.2)

### ISSUE THREAD

**Issue by poopman97** [ViaVersion/ViaVersion#3087]
### `/viaversion dump` Output

https://dump.viaversion.com/3a794017a7fb22879d1de3ac21876a33824f649daccef9ae99852fa1b9e40c05

### Console Error

```
https://paste.gg/p/anonymous/e328494fe8964ba1af60c30493e7e74c
```

### Bug Description

Entering a 1.18.2 server with minecraft version 1.7.x disconnects the player

### Steps to Reproduce

1. Join the server in 1.7.x
2. Look around or move

### Expected Behavior

1.7.x clients should be able to play on the server

### Additional Server Info

I use pufferfish with --add-modules=jdk.incubator.vector 

Plugins (27): 
BedWars, DBAFI*, DeluxeHub, Duels, Essentials,
KitPvP, LoginSecurity*, Multiverse-Core, Multiverse-Inventories,
OldCombatMechanics, PlaceholderAPI, PowerRanks, SBA,
SecondThreadAPI*, Skinshiestorer, Skywars, Spleef*,
SuperiorSkyblock2, TabTPS, TheBridge, TNTRun_reloaded,
ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion,
WorldEdit, WorldGuard

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--72%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Pufferfish--72%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1): 12 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-12%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 9 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.3.1)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)
