### ISSUE TITLE
joining with 1.12.2 to 1.19.2 server

### ISSUE THREAD

**Issue by PlayTim** [ViaVersion/ViaVersion#3088]
### `/viaversion dump` Output

https://dump.viaversion.com/c12eb27b79d284350add184216384fe4df0196ea585c2fcf0fc961813dae6984

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

I can join on my server (1.19.2) with client version from 1.16.5 to 1.19.2 i have on my velocity proxy viaversion viabackwards and via rewind if i join with versions under 1.16.5 the world doasnt load rigth and some chunks are not loaded in the console one time i get a message i think from viaversion that 1.12.2 clienst maiby hafe some issues. I read in the internet that viaversion kan not fix the hight. can i change the hight or the world so that it works?

### Steps to Reproduce

join with any version under 1.16
chunks load wrong

### Expected Behavior

When i join with 1.16 or lower the map should load right and all chunks are visable

### Additional Server Info

an proxy(velocity), and a lobby(purpur)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--3293f7a9--b142%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--3293f7a9--b142%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by buzzcoding** [comment]
Clients under 1.17 do not support the new world heights and depths, so this cannot be (easily/cleanly) fixed, so you need to use a method listed in https://gist.github.com/Jo0001/4fe96cf5a78c8a00560ea985f3b9eb22
If you choose the datapack option, please note that it will permanently delete the blocks below 0 and above 256 blocks for all players.

**Comment by PlayTim** [comment]
i have put the datapack in it and the problem is still there i have tryed to regen the world with the datapack that doasn't work too.
if it helps on the version 1.15 nothing without the holograms are visible and on all the other versions just a few chunks
