### ISSUE TITLE
1.19.2 clients disconnect on 1.18.2 resourcepack

### ISSUE THREAD

**Issue by Roos-Skywalker** [ViaVersion/ViaVersion#3090]
### `/viaversion dump` Output

https://dump.viaversion.com/b87f4e3fd61d709cbb8ed0eaa3aeb9af1b8680df8a696a35fc250bcaf764245f

### Console Error

```
[19:39:28] [User Authenticator #1/INFO]: UUID of player RoosSkywalker is cf674ec1-d61e-46cb-a449-fcc40fe7953c
[19:39:29] [Server thread/INFO]: RoosSkywalker lost connection: Disconnected
[19:39:30] [Server thread/INFO]: RoosSkywalker left the game
[19:39:31] [Craft Scheduler Thread - 16 - mcMMO/INFO]: [mcMMO] Aborting profile loading recovery for RoosSkywalker - player logged out
```
Full server startup with plugins is here [https://paste.gg/p/anonymous/c808811df48542f78e676f08689babe9](https://paste.gg/p/anonymous/c808811df48542f78e676f08689babe9) Paste destroys itself after 30 days.

### Bug Description

When connecting a 1.19.2 client with my 1.18.2 server with a serversided resourcepack I get this error on connect:
**Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/0 (tg) was larger than expected, found 2 bytes extra whilst reading packet 0**

### Steps to Reproduce

Create a test server version purpur-1.18.2-1632.jar Which is a fork of Paper with ViaVersion-4.4.2-SNAPSHOT.jar or 4.4.1 also has it.
Paste these values in the server.properties:
require-resource-pack=false
resource-pack=https\://www.dl.dropboxusercontent.com/s/i1qh9zeau9kmu9r/Mineculum_resourcepack.zip
resource-pack-prompt=
resource-pack-sha1= 
white-list=true

Now join as a 1.19.2 client. It works when joining as a 1.18.2 client.
The 1.19.2 client can have resourcepacks either Enabled or Prompt, result is the same.

### Expected Behavior

Not get disconnected on join while on a higher client version.

### Additional Server Info

No Bungee, no proxy. IP field in server.properties is empty.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1632%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Purpur--1632%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by TwistedDreams** [comment]
> 

The core shader is the issue.

**Comment by TJJP** [comment]
I am getting the same thing, but I am on a waterfall proxy to a 1.19.2 server. I get the error when connecting with a 1.19.2 client. When connecting with an older version it works fine.

**Comment by Jo0001** [comment]
Works fine for me using the latest Via on latest *paper* 1.18.2. Please test if the issue still exists
