### ISSUE TITLE
Viaversion message handling prevents plugins from being able to override the format and handling.

### ISSUE THREAD

**Issue by Skizzles** [ViaVersion/ViaVersion#3091]
### `/viaversion dump` Output

https://dump.viaversion.com/02d70cb72b33cdad38e7febcc2412c2bd8950e74c2dc8b75fff36a13b2c6519e

### Console Error

Currently no errors

### Bug Description

After the additions of chat signing, Viaversion now has formatting and handling of messages that prevents plugins from being able to edit the format and handle the messages. This happens specifically with ChatControl-Red

### Steps to Reproduce

1. Login with a client below 1.19.2
2. Try and message a user
3. Via format is shown instead of the plugins.

### Expected Behavior

Ideally Via should allow plugins to override the formatting and handle messages.

### Additional Server Info

Bungeecord also has BungeeControl-Red

https://github.com/kangarko/ChatControl-Red/issues/2042

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1748%20%28MC%3A%201.19.1%29](https://img.shields.io/badge/Platform-git--Purpur--1748%20%28MC%3A%201.19.1%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2-SNAPSHOT): 9 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.2--SNAPSHOT)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.2-SNAPSHOT): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.4.2--SNAPSHOT)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)
