### ISSUE TITLE
Connecting in a version cannot get ID for packet class BossBar

### ISSUE THREAD

**Issue by NotZer0Two** [ViaVersion/ViaVersion#3092]
### `/viaversion dump` Output

https://dump.viaversion.com/d0ba949f782f0fa31b0d469c61f733bf2ed12caebc1c33f7c3c5b949e52d25ed

### Console Error

```
EncoderException : java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.BossBar in phase GAME with direction TO_CLIENT @ io.netty.handler.codec.MessageToByteEncoder:125
```

### Bug Description

Joining on the server with 1.8.8 other version have the same problem 

### Steps to Reproduce

1. add to a bungeecord server viaversion and other addons 
2. join on 1.8.8 server spigot

### Expected Behavior

Joining

### Additional Server Info

My bungeecord use "JPremium, Custom Plugin, BReport, Litebans,EnhancedBungeeList, JhAntibot"

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A6963156%3A1658](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A6963156%3A1658-3498db?style=flat-square) </br>![ViaVersion (4.4.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Do you have via* installed on backend servers aswell? (If yes; then this may be your issue) - Otherwise update your plugins such as protocollib.

**Comment by NotZer0Two** [comment]
no i don't have it installed and yes i have protocollib

**Comment by NotZer0Two** [comment]
tried updating it, the error still stand

**Comment by FormallyMyles** [comment]
If you use any plugins with titles can you remove them? I don't believe viaversion guarantees the first packet and this means that other plugins can send packets bungee thinks is invalid too early.

Otherwise going to need a minimal setup to replicate if it's not that.
