### ISSUE TITLE
ViaVersion throws exception on join (preventing the join) of players because of large crafting recipes registered with Bukkit

### ISSUE THREAD

**Issue by MartijnMuijsers** [ViaVersion/ViaVersion#3093]
### `/viaversion dump` Output

 https://dump.viaversion.com/cd3013848d4be4becd7bfaf2fa7c9492756ee13cae70f1756edb546db28350ad

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/18889cb213964b7bb18513bf80544e19

### Bug Description

On a server with sufficient number of custom recipes, the NBT refuses to parse.

The cause of this is https://github.com/ViaVersion/ViaVersion/blob/master/api/src/main/java/com/viaversion/viaversion/api/type/types/minecraft/NBTType.java @ line 44.

This is related to https://bugs.mojang.com/browse/MC-185901?attachmentOrder=desc where Minecraft also imposes a maximum size on the packet.

Adding a relatively small number of recipes can be enough to trigger this already, if using [RecipeChoice.MaterialChoice](https://jd.papermc.io/paper/1.19/org/bukkit/inventory/RecipeChoice.MaterialChoice.html) with a large number of possible types - for example 'everything made out of wood in some way').

### Steps to Reproduce

1. Create a server in 1.19.2 (although this will probably work with any Minecraft version) with ViaVersion and ViaBackwards.
2. Add a plugin that uses Bukkit to register many new recipes, or recipes with many options, so that the recipes packet size will increase significantly (as per the [Mojira bug](https://bugs.mojang.com/browse/MC-185901?attachmentOrder=desc), 500 recipes could trigger it, so 10,000 recipes will almost surely be enough).
3. Join with 1.18.2 (although this will probably work with any Minecraft version different than the server so that ViaVersion will perform parsing of recipe update packet).

The joining immediately fails due to an exception on the NBT parsing when sending the recipes packet.

### Expected Behavior

The packet should be able to send.

It is understandable that there is a size limit to the NBT to be parsed. Adding a configuration option for the maximum size would solve this issue, ideally with a reference to this configuration option in the exception message when the size assertion fails.

### Additional Server Info

The notable information is that there are custom crafting recipes added, notably a few with many material options.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--113%20%28MC%3A%201.19.2%29](https://img.shields.io/badge/Platform-git--Paper--113%20%28MC%3A%201.19.2%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2-SNAPSHOT): Error fetching commit data](https://img.shields.io/badge/ViaVersion%20(4.4.2--SNAPSHOT)-Error%20fetching%20commit%20data-lightgray?style=flat-square) </br>![ViaBackwards(4.4.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by MartijnMuijsers** [comment]
Update: I blatantly commented out the precondition (line [44](https://github.com/ViaVersion/ViaVersion/blob/master/api/src/main/java/com/viaversion/viaversion/api/type/types/minecraft/NBTType.java) as mentioned) and tested in the conditions described in **Steps to Reproduce** that would otherwise throw an exception, and everything seems to work fine, with no errors and all recipes present on the client.

**Comment by kennytv** [comment]
See the linked commit and https://github.com/ViaVersion/OpenNBT/commit/eb96d8bca8407d7bc52d6ae1548aaa6c3615b7b5, should be fixed now
