### ISSUE TITLE
io.netty.util.IllegalReferenceCountException causing a kick from the server on paper 1.18.2 with a 1.19.x client

### ISSUE THREAD

**Issue by Gyztor** [ViaVersion/ViaVersion#3095]
### `/viaversion dump` Output

https://dump.viaversion.com/580a953b82e9172b23976ade385b8e4c44ed59b8019808f3676c7929674563f2

### Console Error

Paper:
```
[18:27:43 INFO]: GyztorMizirath[/{HIDINGANIP}:44560] logged in with entity id 381 at ([world]9.429876689415595, 81.0, 260.4157667596562)
[18:27:48 INFO]: GyztorMizirath lost connection: Disconnected
[18:27:48 INFO]: GyztorMizirath left the game
```
Waterfall:
```
[18:27:48 WARN]: [/{HIDINGANIP}:40522|GyztorMizirath] <-> DownstreamBridge <-> [lobby] - could not decode packet! java.lang.IndexOutOfBoundsException: readerIndex(45) + length(3353) exceeds writerIndex(49): PooledSlicedByteBuf(ridx: 45, widx: 49, cap: 49/49, unwrapped: PooledUnsafeDirectByteBuf(ridx: 50, widx: 50, cap: 4096))
[18:27:48 INFO]: [GyztorMizirath] disconnected with: The server you were previously on went down, you have been connected to a fallback server
[18:27:48 INFO]: [/{HIDINGANIP}:40522|GyztorMizirath] -> UpstreamBridge has disconnected
```

### Bug Description

When attempting to join a server that is 1.18.2 (backend paper server with the latest 1.18.2 build and the most latest build of waterfall) with a 1.19.X client the server will let you join (sometimes it wont though and just will insta kick you) and you can move around but if you fall from a height that would give fall damage whether in creative or survival the server kicks you out of the game.
from what i have noticed this seems to only happen when the viaversion instance is on the paper server and not waterfall.

### Steps to Reproduce

1. Create a waterfall with the latest build (1.19-501 as of writing)
2. Create a 1.18.2 (or earlier) paper server that is behind the waterfall server
3. install viaversion (release or dev) on the paper server
4. join the server.
5. jump off a cliff or just go in creative and fly up than stop flying.
6. get kicked and see error in waterfall.

### Expected Behavior

You can join as if it was native and don't get randomly kicked (or in some cases can join at all)

### Additional Server Info

Waterfall doesnt have anything that really changes packets other than protocolize but has been observed to still break like this with or without it. i have also used TAB and BungeeTabListPlus with and without them and error still occurs. Paper server only had luckperms and viaversion installed

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--387%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Paper--387%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by cloakfox** [comment]
Have the same issue on paper 1.17.1, also happening randomly. Tried updating to latest dev builds for viaversion & viabackwards but that didn't fix it unfortunately.

https://gist.github.com/cloakfox/0f773fe264831b4371291428578c2c1c

**Comment by yeatt** [comment]
Can confirm this is happening on my server as well, big problem for my players on older versions.

**Comment by Gyztor** [comment]
issue still exists as of commit a268d3d298186b31f1d91884beab019833581f79

**Comment by FormallyMyles** [comment]
To be able to solve this, more logs / steps to replicate will probably be needed if anyone would like to help towards solving this (assuming it's actually all the same issue).

**Comment by Gyztor** [comment]
> To be able to solve this, more logs / steps to replicate will probably be needed if anyone would like to help towards solving this (assuming it's actually all the same issue).

i did give steps to reproduce but i will repost them here

>### Steps to Reproduce
>    1. Create a waterfall with the latest build (1.19-501 as of writing)
>    2. Create a 1.18.2 (or earlier) paper server that is behind the waterfall server
>    3. install viaversion (release or dev) on the paper server
>    4. join the server.
>    5. jump off a cliff or just go in creative and fly up than stop flying.
>    6. get kicked and see error in waterfall.

There also are no more logs than what i have given due to the fact it wont print anymore not even in a server dump using a force crash or using spark.

**Comment by FormallyMyles** [comment]
> > To be able to solve this, more logs / steps to replicate will probably be needed if anyone would like to help towards solving this (assuming it's actually all the same issue).
> 
> i did give steps to reproduce but i will repost them here
> 
> > ### Steps to Reproduce
> > 
> > 1. Create a waterfall with the latest build (1.19-501 as of writing)
> > 2. Create a 1.18.2 (or earlier) paper server that is behind the waterfall server
> > 3. install viaversion (release or dev) on the paper server
> > 4. join the server.
> > 5. jump off a cliff or just go in creative and fly up than stop flying.
> > 6. get kicked and see error in waterfall.
> 
> There also are no more logs than what i have given due to the fact it wont print anymore not even in a server dump using a force crash or using spark.

Try with debug=true in the server.properties, otherwise providing the kick message. The message applies to others with the issue as I'm not sure it's the same issue. Does it happen without waterfall?

**Comment by Gyztor** [comment]
no error in paper. and no it doesn't seem to happen without waterfall though let me test real quick

**Comment by Gyztor** [comment]
Alright, found out what i think is the issue. there seemed to be some weird conflict with viaversion with a texturepack plugin called BungeePackFix. this existed on the proxy instance (to somewhat copy my production proxy instance) so i would recommend updating to 1.0.6 or disabling it as that fixed it for me. For some reason this was affecting viaversion's ability to function for some reason but should be fine now
