### ISSUE TITLE
Bot attack crashes server due to protocol error.

### ISSUE THREAD

**Issue by PovilasLT** [ViaVersion/ViaVersion#3097]
### `/viaversion dump` Output

https://dump.viaversion.com/9cf64f7334fc92877491659d3bbda394dc62d10dc6a9ca2fc858a14271d0652a

### Console Error

```
https://paste.gg/p/anonymous/8e307ae98ece42d49c6945bb38dcca7a
```

### Bug Description

Mcstorm bot attack to offline mode server crashed due to ViaVersion errors spam (caused by Protocol1_19_1To1_19 IN REMAP OF 0x00->0x00). EpicGuard defended bots but server became unresponsive.

### Steps to Reproduce

1. Have 1.19 Paper server
2. Receive bots using 1.19.1 version

### Expected Behavior

Server should not crash.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--51%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Paper--51%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1): 18 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-18%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.4.1): 6 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
It's up to the protection layer to filter garbage data, not Via
