### ISSUE TITLE
ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)

### ISSUE THREAD

**Issue by Sasuke-thelast** [ViaVersion/ViaVersion#3098]
### `/viaversion dump` Output

https://dump.viaversion.com/6f12064c33963527a1e1ebc27f60caf2ab77ac1176aa2035eef6260ce6e7fd62

### Console Error

14:30:53 [INFO] [ViaVersion] Loading 1.12 -> 1.13 mappings...
14:30:53 [INFO] [ViaVersion] Loading 1.13 -> 1.13.2 mappings...
14:30:53 [INFO] [ViaVersion] Loading 1.13.2 -> 1.14 mappings...
14:30:53 [INFO] [ViaVersion] Loading 1.14 -> 1.15 mappings...
14:30:53 [INFO] [ViaVersion] Loading 1.15 -> 1.16 mappings...
14:30:54 [INFO] [ViaVersion] Loading 1.16 -> 1.16.2 mappings...
14:30:54 [INFO] [ViaVersion] Loading block connection mappings ...
14:30:54 [INFO] [ViaVersion] Loading 1.16.2 -> 1.17 mappings...
14:30:54 [INFO] [ViaVersion] Loading 1.17 -> 1.18 mappings...
14:30:55 [INFO] [ViaVersion] Loading 1.18 -> 1.19 mappings...
14:30:55 [INFO] [ViaBackwards] Loading translations...
14:30:56 [INFO] [ViaBackwards] Loading 1.10 -> 1.9.4 mappings...
14:30:56 [INFO] [ViaBackwards] Loading 1.11 -> 1.10 mappings...
14:30:56 [INFO] [ViaBackwards] Loading 1.12 -> 1.11 mappings...
14:30:56 [INFO] [ViaBackwards] Loading 1.13 -> 1.12 mappings...
14:30:56 [INFO] [ViaBackwards] Loading 1.13.2 -> 1.13 mappings...
14:30:57 [INFO] [ViaBackwards] Loading 1.14 -> 1.13.2 mappings...
14:30:57 [INFO] [ViaBackwards] Loading 1.15 -> 1.14 mappings...
14:30:57 [INFO] [ViaBackwards] Loading 1.16 -> 1.15 mappings...
14:30:57 [INFO] [ViaBackwards] Loading 1.16.2 -> 1.16 mappings...
14:30:57 [INFO] [ViaBackwards] Loading 1.17 -> 1.16.2 mappings...
14:30:57 [INFO] [ViaBackwards] Loading 1.18 -> 1.17 mappings...
14:30:57 [INFO] [ViaBackwards] Loading 1.19 -> 1.18 mappings...
14:30:57 [INFO] Enabled plugin ViaVersion version 4.4.1 by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv
14:30:57 [INFO] [ViaVersion] ViaVersion detected lowest supported version by the proxy: 1.8.x (47)
14:30:57 [INFO] [ViaVersion] Highest supported version by the proxy: 1.19.1 (760)
14:30:57 [INFO] [ViaVersion] Finished mapping loading, shutting down loader executor!
14:30:58 [INFO] Enabled plugin ViaRewind version 2.0.2 by Gerrygames
14:30:58 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.19-R0.1-SNAPSHOT:78ca16d:1656 by SpigotMC

-ERROR-

14:31:09 [INFO] [zPuerta] <-> ServerConnector [lobby] has connected
14:31:10 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:10 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:10 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:10 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:10 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:10 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:10 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:10 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:11 [WARNING] [ViaVersion] ERROR IN Protocol1_9_1_2To1_9_3_4 IN REMAP OF BLOCK_ENTITY_DATA (0x09)
14:31:13 [INFO] [zPuerta] disconnected with: Â§f[Proxy] Lost connection to server.
14:31:13 [INFO] [zPuerta] <-> DownstreamBridge <-> [lobby] has disconnected
14:31:13 [INFO] [zPuerta] -> UpstreamBridge has disconnected

### Bug Description

enter for a bungee server on the 1.8.x bug

### Steps to Reproduce

1. put the via version,viabackward and via rewind on a plugins folder(bungeecord and lobby)
2. enter with an 1.8.x version (i entered with a 1.8.9 in the salwyrr client)
3. wait.
4. the error is done

### Expected Behavior

can enter and play

### Additional Server Info

I use bungeecord with this plugins
AuthMe-5.6.0-beta2.jar
7.05 MB
LuckPerms-Bungee-5.4.41.jar
1.25 MB
OpenLogin.jar
174.37 KB
ServerListPlus-3.4.8-Universal.jar
388.72 KB
StaffFacilities-5.2.2 (ONLY FOR 1.18+).jar
3.94 MB
ViaBackwards-4.4.1.jar
938.63 KB
ViaRewind-2.0.2.jar
444.59 KB
ViaVersion-4.4.1.jar

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A78ca16d%3A1656](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A78ca16d%3A1656-3498db?style=flat-square) </br>![ViaVersion (4.4.1): 19 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-19%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 9 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.4.1): 6 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by cloakfox** [comment]
Same issue, the error is driving me nuts, it happens randomly too.

Have updated to latest versions multiple times & have not been able to fix it

https://gist.github.com/cloakfox/9f55d3156c40d34b7770f0cbee40f55f

**Comment by FormallyMyles** [comment]
> Same issue, the error is driving me nuts, it happens randomly too.
> 
> Have updated to latest versions multiple times & have not been able to fix it
> 
> https://gist.github.com/cloakfox/9f55d3156c40d34b7770f0cbee40f55f
> 
> Players see this when they try to connect: ![unknown](https://user-images.githubusercontent.com/3696645/186724079-6f43e650-700b-42c8-8b9c-efee59c2ae70.png)

This issue is completely different based on the error.

For both of these issues, use vanilla clients and ensure you test without extra software on the proxy which may be modifying information. Need a full stack trace for the original issue + testing with no other plugins and we can look into it further.
