### ISSUE TITLE
Getting Disconnect but don't know why

### ISSUE THREAD

**Issue by CaoTrongThang** [ViaVersion/ViaVersion#3099]
### `/viaversion dump` Output

https://dump.viaversion.com/149263b0bd1c597d5b4d86adb6ea5def47f2725c95f113e3be5f460a8830a17c

### Console Error

```
[Put the paste.gg link or text here.](https://pastebin.com/VqfZ8Ld5)
```

### Bug Description

I was flying around and got disconnected

### Steps to Reproduce

Login with 1.16.5 client
Flying around and got disconnected

### Expected Behavior

I don't really know

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--794%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--794%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1): 19 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-19%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.4.1): 6 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
You have a corrupt jar

**Comment by CaoTrongThang** [comment]
> 

Fixed it, thanks!
