### ISSUE TITLE
Duplicated header in config.yml after /viaver reload

### ISSUE THREAD

**Issue by Jo0001** [ViaVersion/ViaVersion#3100]
### `/viaversion dump` Output

https://dump.viaversion.com/50b4308766240809d3094d5d2c88fb9178f47c0a560b2455121183054cfbbfc1

### Console Error

```
https://paste.gg/p/anonymous/693e9ad502914861b0a15f1cdb63abcb
```

### Bug Description

Every time you reload ViaVersion (with viaver reload) the header with "# Thanks for downloading ViaVersion..." (line 1 to 12) is reinserted in the config.yml, see the paste for an example.

### Steps to Reproduce

1. Reload Via using `viaver reload`
2. Check the config.yml

### Expected Behavior

No duplicated config header

### Additional Server Info

Also occurs when using via on waterfall
Works fine using https://dump.viaversion.com/da159166ce87c352c61cbae4781d178410a93ab6af5280f99cf90fae2d19c9e7 so its probably related to https://github.com/ViaVersion/ViaVersion/commit/f9bbb5b1a363b3589cad7dc3ae400e599302b5d0

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--132%20%28MC%3A%201.19.2%29](https://img.shields.io/badge/Platform-git--Paper--132%20%28MC%3A%201.19.2%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.2)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.2): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.2)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Fixes itself after a restart so /shrug
