### ISSUE TITLE
Protocol version is "-1"

### ISSUE THREAD

**Issue by wolf0023** [ViaVersion/ViaVersion#3102]
### `/viaversion dump` Output

https://dump.viaversion.com/e6226d2f65fda7170e29b16472dce5206ba7bde6cd9d76100f694cf2da5196b9

### Bug Description

If I add the protocols to `block-protocols: []` in the config.yml, the Protocol Version is -1. 

### Steps to Reproduce

Add the protocols to `block-protocols: []` in the config.yml

### Expected Behavior

Block Protocol option is working except for this bug.

### Additional Server Info

Server Software: paper
Server Version: 1.17.1

I tried to start the server with only viaversion but this issue was not resolved.
And I have not tried this issue in other versions.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--411%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--411%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.4.1)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by wolf0023** [comment]
I have already tried running the server with the latest viaversion, but this did not solve the problem.
