### ISSUE TITLE
Protocol version is "-1"

### ISSUE THREAD

**Issue by wolf0023** [ViaVersion/ViaVersion#3103]
### `/viaversion dump` Output

https://dump.viaversion.com/d4ad19b506fda091ace18696a3a66e31ebbae733f08582748aa70747d315a270

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

If I add the protocols to block-protocols: [] in the config.yml, the Protocol Version is -1.

### Steps to Reproduce

Add the protocols to block-protocols: [] in the config.yml

### Expected Behavior

Block Protocol option is working except for this bug.

### Additional Server Info

Server Software: paper
Server Version: 1.17.1

I have not tried this issue in other versions.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--411%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--411%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.4.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Caused by bad writing to config, if you wanted a simple solution then please try this approach instead:

```yml
block-versions:
- <1.12
block-protocols: []
```

**Comment by wolf0023** [comment]
I have tried that as well, but it did not solve this issue.

**Comment by Kichura** [comment]
Try removing the viaversion config entirely and restart server to regenerate it and see if it manages to persist again without making any changes.

**Comment by wolf0023** [comment]
The protocol version is fine if you do not change anything.

**Comment by Kichura** [comment]
then it is obvious why - it is bad configuration writing and not an issue caused by us specifically.

**Comment by wolf0023** [comment]
How should I write?
I tried writing it like the followings, but protocol version is -1.

block-versions: ["<1.12"]

or

block-protocols: [316, 315, 210, 110, 109, 108, 107, 47, 5, 4]

Also, the Protocol version is 756 without making any changing.

**Comment by Kichura** [comment]
You can try one of them to see what comes out - but usually the example i posted above should've worked fine from beginning.

**Comment by wolf0023** [comment]
Even the above setting does not work fine.
I am checking Protocol version at https://mcsrvstat.us/ .

・config.yml
https://paste.gg/p/anonymous/9d8fb3ffc4254a3c8b4e73845cd544ba
