### ISSUE TITLE
Player dont see each other

### ISSUE THREAD

**Issue by PureGolded** [ViaVersion/ViaVersion#3104]
### `/viaversion dump` Output

https://dump.viaversion.com/6aa12e7246a133b1852d58ba210d25abb5a43a016edd01b333436deea64ee8b9

### Console Error

```
There are no errors.
```

### Bug Description

When the server starts, and there are few players, not doing anything yet, everything is fine. But as soon as somebody teleports to a different world via multiverse or relogs etc. Players can no longer see each other. I made a plugin that specifically tries to unhide all players for all players, however that does not fix anything.

### Steps to Reproduce

In my case, I only find it this way, since you can not do anything else on the server.
1. Login with any version of client
2. Login with second client
3. Both open custom inventory GUI
4. After selecting right items they got teleported via multiverse into a different world (one by one really quickly)
5. From now on, they cannot see each other until server restarts.

### Expected Behavior

Players will see each other all the time, every time.

### Additional Server Info

I use BungeeCord for 1.19 version, with multiverse, worldedit, ultraperms, 1.8 pvp and custom plugins (see picture). Altroug the bungeecord only redirects players, ViaVersion with other Via- plugins is only on this separate server (I have set custom subdomain to redirect directly to the server).
![image](https://user-images.githubusercontent.com/80714825/186004037-dd8467bf-6cf7-465d-9a7b-54a2db2d775b.png)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--34%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Paper--34%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 9 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)
