### ISSUE TITLE
[1.8.8] Could not find UserConnection for logging-in player warn with Protocol Support

### ISSUE THREAD

**Issue by HowardZHY** [ViaVersion/ViaVersion#3105]
### `/viaversion dump` Output

https://dump.viaversion.com/17e2f02bbb2ea63b47b7b075a12b132e0e6d816ecaf25647dbf8857145d1cf42

### Console Error

[ViaVersion] Could not find UserConnection for logging-in player (uuid)

### Bug Description

This never happen before, it shows when a player join.
Seems no client issue.

### Steps to Reproduce

a player join the server

### Expected Behavior

no this msg

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by HowardZHY** [comment]
https://dump.viaversion.com/17e2f02bbb2ea63b47b7b075a12b132e0e6d816ecaf25647dbf8857145d1cf42

**Comment by FormallyMyles** [comment]
Does this show every join? Does viaversion still work otherwise? Can you try with no other plugins apart from Via?

**Comment by HowardZHY** [comment]
Yes, it shows every join and there's only this warn, nothing else was abnormal.
I'll try only via



At 2022-08-27 18:03:51, "Myles" ***@***.***> wrote:

Does this show every join? Does viaversion still work otherwise? Can you try with no other plugins apart from Via?

**Comment by HowardZHY** [comment]
https://dump.viaversion.com/161d4660172ae01abc7a6fd09065cbec541cb4c402fb81785d15466919428cde
No warn only via*.
I think it's caused by clientstats,viaversionstatus,crazycore/loginfilter,or PS

**Comment by Barvalg** [comment]
![Platform: git--BurritoSpigot--%22700f01e%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--BurritoSpigot--%22700f01e%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.4.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by HowardZHY** [comment]
https://dump.viaversion.com/147896a0060a0941041dd44d67f2443b63bde903bbeda9afaf48a42a8049ec11
With these pl., that warn showed again.

**Comment by Barvalg** [comment]
![Platform: git--BurritoSpigot--%22700f01e%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--BurritoSpigot--%22700f01e%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.4.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by HowardZHY** [comment]
https://dump.viaversion.com/c516d301dbbe1b9209ea37923bf1827e6e06ec62326bedbaa2011e5e532432bb
It shows with PS

**Comment by Barvalg** [comment]
![Platform: git--BurritoSpigot--%22700f01e%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--BurritoSpigot--%22700f01e%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.4.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Bobcat00** [comment]
ViaVersion
ViaRewind
ProtocolSupport
BurritoSpigot 1.8.8

I don't think that's a supported combination.

**Comment by HowardZHY** [comment]
https://github.com/ViaVersion/ViaVersion/commit/58fd0bdc9eaa7bdf3e618271041d75cb10662574
