### ISSUE TITLE
Error with nicknames

### ISSUE THREAD

**Issue by ImVortexL** [ViaVersion/ViaVersion#3106]
### `/viaversion dump` Output

ViaVersion 4.4.2

### Console Error

![unknown](https://user-images.githubusercontent.com/108226177/186436270-c6b915d8-1485-4ce3-9468-23b6a5132043.png)

### Bug Description

ViaVersion 4.4.2

### Steps to Reproduce

ViaVersion 4.4.2

### Expected Behavior

ViaVersion 4.4.2

### Additional Server Info

ViaVersion 4.4.2

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Issue template
