### ISSUE TITLE
ERROR IN Protocol1_7_6_10TO1_8 IN REMAP OF CHAT_MESSAGE (0x02)

### ISSUE THREAD

**Issue by TDSTOS** [ViaVersion/ViaVersion#3107]
### `/viaversion dump` Output

https://dump.viaversion.com/0560775456c5b186ece6ddbb309a23b5c3ac72fb8f98e9b8806bccf007e0d945

### Console Error

https://paste.gg/p/anonymous/79989bcc1c894fca94b0fd5b3dc0965a

### Bug Description

The bug appears when a player with version 1.7.x joins

### Steps to Reproduce

1. Login with a 1.7.x client
2. Hit or do anything a normal player would do

### Expected Behavior

Dont know what to write here .-.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--411%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--411%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.2)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 9 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.4.2): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.2)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by FormallyMyles** [comment]
Update your plugins

**Comment by TDSTOS** [comment]
> Update your plugins

I have already tried it with updated plugins

**Comment by FormallyMyles** [comment]
Provide a new dump then, you checked the box saying you did so but the dump states otherwise

**Comment by TDSTOS** [comment]
Here is the new dump, as well as a paste of the same error **with** updated plugins:
https://dump.viaversion.com/cf9f06d1527ce9eada7d488faad051c2650872f8f328292e0691db52e1a86965
https://paste.gg/p/anonymous/7e9f1840d454443b9c3a6ce57f527e5f
