### ISSUE TITLE
[1.19 -> 1.16.5] Got kicked when clicking into a Shopkeeper's NPC 

### ISSUE THREAD

**Issue by tudubucket** [ViaVersion/ViaVersion#3111]
### `/viaversion dump` Output

https://dump.viaversion.com/8eaedfa851ba5c18dcad4d22108e6d11af508c08abb13953935441b95198496c

### Console Error

``` 
No error from console, this is a log from client: https://gist.github.com/tudubucket/c721dc79450be315490dbc2f92f1b8ab
```

### Bug Description

Using version 1.19+ to click into Shopkeepers's NPC in 1.16.5 server cause to server kick with the reason is the Shopkeeper's NPC data

### Steps to Reproduce

1. Login into 1.19 client (im not pretty sure cuz im using client-side viafabric 1.18.2 and via'ed to 1.19)
2. Join to any 1.16.5 server that have a Shopkeepers's NPC
3. Click into that NPC
4. Got kicked

### Expected Behavior

Got kicked from the server with the reason is the Shopkeeper's NPC data

### Additional Server Info

I'm using BungeeCord on proxy, but I install ViaVersion at the backend server (and im using viafabric). I don't have much idea to describe things here.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Patina--ver/1.16.5--%22667fb1b%22%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Patina--ver/1.16.5--%22667fb1b%22%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.4.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Cannot reproduce on 4.9.0-SNAPSHOT with latest shopkeepers plugin, Please check if updating solves your problem.
