### ISSUE TITLE
CHUNK_DATA

### ISSUE THREAD

**Issue by icansc187** [ViaVersion/ViaVersion#3113]
### `/viaversion dump` Output

https://dump.viaversion.com/0d81abd941ea7f848c0d4e167fcea9f45fa345393cfc153409eada843097bace

### Console Error

```
https://pastebin.com/EfnZixjB
```

### Bug Description

movement

### Steps to Reproduce

Login with 1.15.2 client to server 1.13.2

### Expected Behavior

movement

### Additional Server Info

spigot 1.13.2

### Checklist

- [ ] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [ ] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Spigot--1a3504a--06534f2%20%28MC%3A%201.13.2%29](https://img.shields.io/badge/Platform-git--Spigot--1a3504a--06534f2%20%28MC%3A%201.13.2%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.2)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by icansc187** [comment]
![error](https://user-images.githubusercontent.com/38745994/187425347-b3c46a46-1030-4cda-bee2-d9790b73f527.png)

**Comment by Jo0001** [comment]
Please try it with the latest Via* from https://ci.viaversion.com/ 
If the issue persits please reach out on discord or open a new issue and make sure to follow the issue template
