### ISSUE TITLE
Disable load for unused mappings.

### ISSUE THREAD

**Issue by rafalohaki** [ViaVersion/ViaVersion#3114]
### Problem Description

I want to disable load for not used mappings.

### Solution Description

Feature to not load mappings for disabled protocols.
For example enabled protocols only for 1.18-1.19, so mappings with version less than 1.18 would not load

**Comment by kennytv** [comment]
The overhead isn't really worth the effort of saving, you could maybe disable block connections in the config. We don't know if some other plugin might use any of the mappings, two important examples being ViaBackwards and Geyser. We also can't introduce an intent system without breaking every plugin using them atm
