### ISSUE TITLE
Bug in my 1.17.1 Skyblock server

### ISSUE THREAD

**Issue by FuzzyWuzz59** [ViaVersion/ViaVersion#3116]
### `/viaversion dump` Output

https://dump.viaversion.com/28ce7e7bb6988d7c3163bcd9e7cd32e7fe5a094cf1d5fdc3d38f68cd573819e3

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

My server's hosting support tells me that viaversion is causing my server to crash.

They said the timings report showed a wildly large amount of your server resources are going towards ticking your player entity on the server, which is very abnormal.

They then said I should disable viaversion.

### Steps to Reproduce

Not sure what you want here. I log in and after only a few minutes am kicked from the server. Very repeatable.

### Expected Behavior

In all of my other instances of using ViaVersion the server is stable. I need to this one to be as well.

### Additional Server Info

BugeeCord

Not sure of the software, are you talking about my PC or the server type? I have a Paper server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--411%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--411%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.2)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 12 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-12%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.4.2): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.2)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by FormallyMyles** [comment]
Without logs or a timings report, it's not possible for us to investigate this.
