### ISSUE TITLE
players cant use anticraft 

### ISSUE THREAD

**Issue by EvilDevil1175** [ViaVersion/ViaVersion#3117]
### `/viaversion dump` Output

none

### Console Error

EF: BogeyedMouse435 (228ms) failed Packets (25 vls)

### Bug Description

players cant use autocraft in a crafting table I don't know if this is a plugin error or via version

### Steps to Reproduce

crafting in a table craft

### Expected Behavior

items no autocraft or autocomplete

### Additional Server Info

none

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Kichura** [comment]
Follow the issue template checklist - If updating to the CI builds still doesn't help then please send the config contents.
