### ISSUE TITLE
KICKING ON THE CORE 1.8.8 HELP PLESS

### ISSUE THREAD

**Issue by andreqerbaev** [ViaVersion/ViaVersion#3118]
### `/viaversion dump` Output

https://dump.viaversion.com/b3ebbf7bd53e94d17fe0737404f507ee78e9149848b6ad93d5e996e397ccc78b

### Console Error

```
Put the paste.gg link or text here.
```
[09:40:43 INFO]: Player919[/81.23.175.26:49330] logged in with entity id 976 at ([world]-1018.3463093858306, 54.0, -784.5105022061913)
[09:40:43 INFO]: Player919 lost connection: Internal Exception: java.io.IOException: Error while write(...): Broken pipe

### Bug Description

kicks me and the players every other time on spigot 1.8.8 core, but on 1.12.2 everything is fine, everything is fine on older versions of the plugin!

павыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапавпавыпвапвапвапвапавпвапав

### Steps to Reproduce

I logged in from client 1.12.2 to my server spigot 1.8.8 and kicks with the reason:  https://ltdfoto.ru/image/eLgMUV

### Expected Behavior

d

### Additional Server Info

https://ltdfoto.ru/image/eLgMUV - ФОТО ОШИБКИ!

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--%228b18730%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--%228b18730%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.2)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by FormallyMyles** [comment]
Test using the latest builds, and otherwise with no other plugins as there is probably a conflict. Otherwise, provide errors via imgur.
