### ISSUE TITLE
GPL is incompatible with Minecraft

### ISSUE THREAD

**Issue by Nolij** [ViaVersion/ViaVersion#3119]
ViaVersion is partially licensed under GPL-3.0. While this is usually a good thing, in the case of a Minecraft mod it actually restricts the freedom of users due to the linking restrictions (this is why the Quilt template mod default README states that it is incompatible). 

There are 3 solutions to this:
1. Switch to LGPL-3.0. This license is compatible with Minecraft due to the linking restrictions being eased. 
2. Switch to [OSL-3.0](https://choosealicense.com/licenses/osl-3.0/). This license is similar to LGPL-3.0, but it also protects network use, so it acts like a LAGPL (I recommend this option).
3. Switch to [AFL-3.0](https://choosealicense.com/licenses/afl-3.0/), Apache-2.0, or some other "permissive" license (I strongly recommend one of these two though if a "permissive" license is chosen, as these provide more freedom to users than Expat licenses such as MIT or Unlicense by way of providing patent protections). I don't recommend this option, and given this mod is licensed GPL I don't anticipate it will be taken, but I'm anticipating the inevitable "yOu DiDn'T iNcLuDe A pErMiSsIvE oPtIoN" response.

Unfortunately, in order to address this, all 82 of ViaVersion's contributors must to agree on a new license, or the ones that disagree must have their contributions removed/replaced. If all contributors (ie copyright holders) agree on a license change though this will not violate GPL, as each contributor still owns copyright for their contributions.

Yes, I do realize what I have just started. As such, I will be watching with popcorn (and be available to answer questions if needed). Please know it was not with malicious intent. Best of luck!

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
ViaVersion does not inject into Mojang's Minecraft client/server code. Mods using ViaVersion are free to exclusively depend on and link to the API module, being its own piece of software licensed unter the MIT license.

You could *maybe* make the argument on ViaFabric, but even there that seems silly/gray with how mixins work

**Comment by DioEgizio** [comment]
the gpl only counts dependencies at build time. Even if mojang code was in the classpath, you're not distribuiting the combined program

**Comment by Nolij** [comment]
> the gpl only counts dependencies at build time. Even if mojang code was in the classpath, you're not distribuiting the combined program

The licensing incompatibility doesn't come from ViaVersion violating GPL. Licensing something GPL when it's not compatible with it doesn't break the GPL, it just limits the GPL's capabilities. The issue with ViaVersion being licensed GPL is that the freedoms it provides users are contingent on the several restrictions of the GPL, the problematic one being the linking restrictions. Users violate the usage rights GPL usually gives by using ViaVersion as intended (ie linked to Minecraft). If you try to launch the jar directly, what do you get? An error, perhaps? This is because it depends on code in Minecraft. This is linking. It's dynamic linking, so LGPL won't have a problem with it, but GPL disallows this. Regardless, it seems this won't be addressed. I personally will be avoiding ViaVersion as I don't want to open myself to liability.

**Comment by Kichura** [comment]
There is another thing you should take into account; Bukkit's code itself is GPL which specifically forces GPL upon us, this includes everything in velocity outside of the API directory/directories (as it uses a whole bunch of the proxy code here) - And changing licenses to a more comfortable one is going to be tough at the very least in it's own ways.

**Comment by kennytv** [comment]
ViaVersion does not depend on the Minecraft server to be able to operate. It uses a variety of free libraries to inject into the netty pipeline (where the module for Paper servers for example is obviously intended to be run in conjunction with a Paper patched server, but all it actually requires is something implementing its API, including everything used to inject into the pipeline) and otherwise acts as a library itself to function with other software or even as a standalone application; see ViaFabric, ViaAAS. So no, that's not correct.

I'm by no means an expert in this area, nor do I care to be, but all of the above comments (other than kichura's) so far are written with an obviously flawed understanding of how Via works/of the GPL. Since this discussion is unlikely to go anywhere useful and as this isn't a law forum, the issue will be locked.

If you *actually* don't want to step into gray territory, you should stop using mods and patched servers altogether
