### ISSUE TITLE
ViaVersion doesn't work very well with Velocity

### ISSUE THREAD

**Issue by DimaSergeew** [ViaVersion/ViaVersion#3120]
### `/viaversion dump` Output

https://dump.viaversion.com/1ffab8940d08ca074b3ecd2dd58beaa7ff28319b0ed3bc8b9fe1dc4de8e54eef

### Console Error

```
https://paste.gg/p/anonymous/dc430b6948fc4c6f862c20e9f0fe22c8
```

### Bug Description

When I decided to unload the servers and install Viaversion + ViaBackwards, Velocity started spamming errors from Viaversion and started kicking everyone. there was no such problem when he was on the servers.

### Steps to Reproduce

1) install Viaversion + ViaBackwards on Velocity
2) Ask a large number of people to join the server

### Expected Behavior

I expected that by setting Viaversion to velocity I would remove the load on netty streams on the servers, and everything would work without errors

### Additional Server Info

![Screenshot_1](https://user-images.githubusercontent.com/75163645/190103845-bdb9a3a2-0fab-4922-bdc1-20c33718a286.png)
![Screenshot_2](https://user-images.githubusercontent.com/75163645/190103858-e65e0770-9f99-4c88-8d42-8bae1a382d32.png)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--3293f7a9--b172%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--3293f7a9--b172%29-3498db?style=flat-square) </br>![ViaVersion (4.4.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.2): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.2)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
ViaVersion is always recommended for the backend, what you're seeing is invalid data being handled. This is down to an incompatible plugin / outdated velocity / someone sending invalid data which can be ignored otherwise.
