### ISSUE TITLE
Players get kicked when they hit a player who has been playing on1.16.5

### ISSUE THREAD

**Issue by zingeer** [ViaVersion/ViaVersion#3121]
### `/viaversion dump` Output

https://dump.viaversion.com/3e0240a7130dc37eebe5ce1529cb18d68936e2f29ef58dcf0310318d2f932165

### Console Error

https://paste.gg/p/anonymous/49c3ff577b4549c2a569d13b5f7fd0d4

### Bug Description

1.19+ player gets kicked when hit by player on 1.16.5 version

### Steps to Reproduce

1. Login one client on 1.16.5 and other client on 1.19.2
2. Join on server
3. Hit player on 1.19.2 version, hit event will be not cancelled. 
4. Player kicked.

### Expected Behavior

Player not kicked.

### Additional Server Info

my core is velocity-3.1.2-SNAPSHOT-181

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--57ca66de--b181%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--57ca66de--b181%29-3498db?style=flat-square) </br>![ViaVersion (4.4.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.2): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.2)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
Move your plugins to the backend, from previous experience LimboAPI might need updating / may just be incompatible.

Otherwise, if you can replicate with just Via on velocity we can look into further.
