### ISSUE TITLE
1.18 to 1.19 error again

### ISSUE THREAD

**Issue by felixkaung** [ViaVersion/ViaVersion#3123]
### `/viaversion dump` Output

https://dump.viaversion.com/d711e054ddad01e191707bee2fadefc98aaf04ef97236880f020aaf0c15dd059

### Console Error

this message after getting disconnected
[ViaVersion] ERROR IN Protocol1_19To1_18_2 IN REMAP OF MULTI_BLOCK_CHANGE (0x3F)

### Bug Description

reloading causes 1.18 to 1.19 protocol stop working

### Steps to Reproduce

1.run server
2.reload
3.got disconnected and this error code   MULTI_BLOCK_CHANGE, Type: BlockChangeRecord Array, Data: [Pair{Type|Long, 123145241493508}, Pair{Type|Boolean, false}], Source 0: com.viaversion.viaversion.rewriter.BlockRewriter$4 (Anonymous), Packet ID: 61

### Expected Behavior

1.18 to 1.19 protocol should still work after reloading

### Additional Server Info

i use bukkit (spigot) with economy plugins

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3284a--Spigot--3892929--0ab8487%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-3284a--Spigot--3892929--0ab8487%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.4.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.2): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.2)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Reloading is not supported
