### ISSUE TITLE
Locatebiome doesn't work on 1.19.2 on 1.16.5 server

### ISSUE THREAD

**Issue by Roadhog360** [ViaVersion/ViaVersion#3124]
### `/viaversion dump` Output

https://dump.viaversion.com/eb1de5857b46ebedc9a80b51ef84ef223f9c18b99793e5439d8d69b237e21216

### Bug Description

I'm on 1.19.2 on a 1.16.5 server, any /locatebiome attempt gives "commands.locatebiome.success" in chat. Or "commands.locatebiome.notFound" if the biome is too far away or doesn't exist in that dimension. So it's impossible to use the command.

### Steps to Reproduce

Log in a 1.16.5 server as a 1.19.2 player.
Use /locatebiome to find anything
The translation key is displayed instead of the translated message.

### Expected Behavior

I get to see what the actual message is and should get a clickable link to get to the biome.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--794%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--794%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.2)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by Roadhog360** [comment]
I did

**Comment by HowardZHY** [comment]
https://github.com/ViaVersion/ViaBackwards/issues/468

**Comment by Roadhog360** [comment]
This is a VIAVERSION issue, not a VIABACKWARDS issue. This was wrongly transferred, please removed the transferred version of the ticket.

**Comment by Roadhog360** [comment]
@HowardZHY
The referenced issue is for a completely separate bug. The /locate command is the replacement for locatebiome now locating structures, biomes, and more. The issue describes printing a language key when using older versions. That is not what this issue is about at all.

This described behavior, as stated in the ticket very clearly. Is using **/locatebiome** on a 1.16.5 *server*, on a 1.19.2 *client*. In 1.16.5, /locate is for structures and is *not* what the issue is about.

**Comment by kennytv** [comment]
Both are effectively the same issue just the other way around, so they'll likely be fixed at the same time - the VB issue will be enough to track the status of it
