### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by rishireddy1599** [ViaVersion/ViaVersion#3128]
### Problem Description

Update to the new version of bedrock

### Solution Description

make it so updated players can join

**Comment by krusic22** [comment]
ViaVersion doesn't add Bedrock support.

**Comment by Kichura** [comment]
To clarify this one: You need to update geyser + floodgate instead as ViaVersion is not responsible for handling bedrock compatibility whatsoever.

**Comment by minegame-ch** [comment]
Hi why 1.16veraion bug render in -0 height in 1.29version

**Comment by Kichura** [comment]
> Hi why 1.16veraion bug render in -0 height in 1.29version

Please see [this page](https://gist.github.com/Jo0001/4fe96cf5a78c8a00560ea985f3b9eb22) as your answer.
