### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by Mercenarioo** [ViaVersion/ViaVersion#3130]
### Problem Description

I have noticed that ViaVersion is having some big work with the server, can it be improved?
![image](https://user-images.githubusercontent.com/107449914/193067928-e713dab4-4fe7-4eee-a1c7-221121491625.png)
![image](https://user-images.githubusercontent.com/107449914/193067973-6eb43070-28fe-49a4-9b46-1f63331fbf75.png)
![image](https://user-images.githubusercontent.com/107449914/193068100-4caf480c-3f0a-4773-91a5-5182bbde9067.png)
![image](https://user-images.githubusercontent.com/107449914/193069381-8e41aa46-1481-4a81-9b7a-6b173ec59087.png)
![Uploading image.png…]()

### Solution Description

Some optimizations would be great. :)

### Additional Info

I see PacketRemapper.remap() takes a lot, can this be improved a little?
Does it have to be done for every packet? 
![image](https://user-images.githubusercontent.com/107449914/193069082-720fa4f0-a455-429c-b554-99cbe69efb3e.png)

**Comment by HowardZHY** [comment]
u lack a dump

**Comment by kennytv** [comment]
Screenshots of spark profiles are also pretty much useless, we need the full link

**Comment by Kichura** [comment]
> I only have that, as I got it from a server administrator. I only have Auth plugin and Essentials.

Well this isn't really going to be anything for us to work with as it can mean anything in reality - We need more information than just this; without it, we cannot go further.

**Comment by Mercenarioo** [comment]
I don't understand, what happened?

**Comment by kennytv** [comment]
You provided no information that'd help us optimize anything, and neither are the reports from the little info we can take from the screenshots alarming - that's just what happens when you run a 1.8 server and want to allow 1.19 clients

**Comment by Mercenarioo** [comment]
These 2 contains calls for getMotionBlocking() and getNonFullBlocks() are on top of the profiler, maybe they can be replaced with different Sets or reworked? This happens when there are many more 1.8 players than 1.9+, I don't know what more informations I should get.

https://github.com/ViaVersion/ViaVersion/blob/9a34ff2a515b589ef4bd2e47abd78e7d656bac51/common/src/main/java/com/viaversion/viaversion/protocols/protocol1_14to1_13_2/packets/WorldPackets.java#L181

**Comment by Mercenarioo** [comment]
> that's just what happens when you run a 1.8 server and want to allow 1.19 clients

It's sad how arrogant you are.

**Comment by Kichura** [comment]
> These 2 contains calls for getMotionBlocking() and getNonFullBlocks() are on top of the profiler, maybe they can be replaced with different Sets or reworked? This happens when there are many more 1.8 players than 1.9+, I don't know what more informations I should get.
> 
> https://github.com/ViaVersion/ViaVersion/blob/9a34ff2a515b589ef4bd2e47abd78e7d656bac51/common/src/main/java/com/viaversion/viaversion/protocols/protocol1_14to1_13_2/packets/WorldPackets.java#L181

Well the main issue with this is that if we don't have any information such as a spark dump link or a viaversion dump link *(the former being a better option but both are suggested)* - it will be impossible to figure out on why we need to change it in the first place as those """high tick alerts""" can mean anything to us in reality; and having to hide the information from developers such as here isn't really going to make it any better - If you are not pleased with this kind of answer then you are either best off upgrading your server to a newer version that is considered comfortable for it's own needs *(1.16.5 or newer)* or just don't use our plugins if you wish not to share any required infos into this issue.

**Comment by Mercenarioo** [comment]
I checked it and motionBlocking set contains almost 6000 objects. There are multiple states of staits, beds, note blocks, etc. Can this maybe be packed to just the types maybe? This part of the code iterates through all the blocks from the chunk, then for every block it checks if its inside the set with 6000 object.

**Comment by Gerrygames** [comment]
I does not matter that the set contains 6000 elements. A contains check on a hash set is in O(1).

**Comment by Mercenarioo** [comment]
Interesting, I don't have more ideas on how to optimize it.
