### ISSUE TITLE
EncoderException

### ISSUE THREAD

**Issue by craftermcnet** [ViaVersion/ViaVersion#3131]
### `/viaversion dump` Output

https://dump.viaversion.com/8af28ed46fde7cd210ba3d7dfed5204221c538b684ae7914568a2d67fb87deb8

### Console Error

https://paste.gg/p/anonymous/01cdb5d5c6c8465c973400901985c35f
![2022-10-02 16_56_18-Window](https://user-images.githubusercontent.com/96014369/193460730-8abda167-47d0-4bb3-acec-450e47fc7967.png)

### Bug Description

When changing the server with /send you get kicked for an encoderexception.
It only appears when viaversion is installed on the bungeecord and not when installed on both paper servers.

### Steps to Reproduce

1. Bungeecord with 2 paper server, one with 1.19 & one with 1.16.5
2. Install Viaversion on the bungeecord
3. use a vanilla 1.19.2 client and join the 1.19 server and try to connect to the 1.16.5 server with /send

### Expected Behavior

You should be kicked with an encoder exception

### Additional Server Info

This server is running BungeeCord version git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:2d369e8:1664 by md_5
This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A2d369e8%3A1664](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A2d369e8%3A1664-3498db?style=flat-square) </br>![ViaVersion (4.4.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Are you using via* on bungee or the backend servers themselves ?

*(If both / or "proxy" as answer; Please try moving via* to the backend servers only instead)*
*(If "backend" as answer; Likely another plugin is breaking the connectivity, A binary search should be performed)*

**Comment by craftermcnet** [comment]
> Are you using via* on bungee or the backend servers themselves ?
> 
> _(If both / or "proxy" as answer; Please try moving via_ to the backend servers only instead)* _(If "backend" as answer; Likely another plugin is breaking the connectivity, A binary search should be performed)_

As is wrote at the steps to reproduce it's installed on the proxy and not on the paper servers. But I tried it seperatly on the paper servers and there was no error.

**Comment by Kichura** [comment]
Then it's suggested to keep via* on the backend servers as it is morely accurate and reduces the amount of errors.
