### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by ZIIROX77** [ViaVersion/ViaVersion#3137]
### `/viaversion dump` Output

https://dump.viaversion.com/528971d2258c38c32e018abac0eaae09905b9ed13ca957b56ed43a02a95df22f

### Console Error

[21:05:44 ERROR]: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: CLIENT_INTENTION, Type: String, Data: [Pair{Type|VarInt, 0}], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol$1 (Anonymous), Packet ID: 0
[21:05:44 ERROR]: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 96
[21:06:09 ERROR]: java.io.IOException: Error while read(...): Connection reset by peer

### Bug Description

Just error in console

### Steps to Reproduce

Just wait on server

### Expected Behavior

Error in console

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--iSpigot--PaperEdition%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--iSpigot--PaperEdition%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.2)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by FormallyMyles** [comment]
This is usually just random services sending bad data to your server, you can ignore these.
