### ISSUE TITLE
getPlayerVersion returns -1

### ISSUE THREAD

**Issue by Mercenarioo** [ViaVersion/ViaVersion#3140]
### `/viaversion dump` Output

https://dump.viaversion.com/f1ed970c5ca7277e5923803fbb8dda8b06686a67933f5072d8db65ad2b18e4cb

### Console Error

no ereror

### Bug Description

I'm checking player's version through ViaVersionPlugin.getInstance().getApi().getPlayerVersion() in the PlayerJoinEvent normal priority and it often returns -1

### Steps to Reproduce

1. Login with 1.19 client.
2. Your version will be -1.

### Expected Behavior

Normal version.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Spigot--21fe707--e1ebe52%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--Spigot--21fe707--e1ebe52%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.0.0)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by Mercenarioo** [comment]
The issue persists

**Comment by buzzcoding** [comment]
Listen to the bot and the issue template. You are using a version of the plugin that was released over a year before the fix was merged.

**Comment by buzzcoding** [comment]
Latest from Spigot or [https://ci.viaversion.com/](https://ci.viaversion.com/)?

**Comment by buzzcoding** [comment]
Oh
