### ISSUE TITLE
Error in BaseProtocol1_7 In Remap of 0x02->0x02

### ISSUE THREAD

**Issue by Quaintified** [ViaVersion/ViaVersion#3141]
### `/viaversion dump` Output

https://dump.viaversion.com/6debe782ebdc54bc148aff292cc4967a42b8b42430bee03ed8e3dd28d6db54fb

### Console Error

[Hastebin link](https://hastebin.com/kazirakipe.properties)

### Bug Description

Throws the error upon player logins. The players cannot actually login (they get kicked with 'Disconnected' on their screen).

### Steps to Reproduce

1. Download https://ci.viaversion.com/job/ViaVersion-DEV/ (Build #746).
2. Put onto server.
3. Start server.
4. Join server in 1.19.2 (tested only on 1.19.2).
5. Error shows up.

### Expected Behavior

Players can log in without being kicked and without errors in the console.

### Additional Server Info

On Velocity latest with a customization (I coded myself) that disables the kick when chat messages aren't signed.

Plugins:
- CraftingStore
- floodgate-velocity
- Geyser-Velocity
- LiteBans
- LuckPerms-Velocity-5.4.50
- nuvotifier
- Plan-5.5-build-1984
- StreamlineCore-Velocity-2.0.0.12
- ViaBackwards-4.4.3-SNAPSHOT
- ViaVersion-4.5.0-22w42a-SNAPSHOT

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--7d77bfb5--bunknown%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--7d77bfb5--bunknown%29-3498db?style=flat-square) </br>![ViaVersion (4.5.0-22w42a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.5.0--22w42a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Don't use the snapshot dev version unless you also use Velocity and VB with snapshot support

**Comment by Quaintified** [comment]
How do I get VB snapshots then?

**Comment by kennytv** [comment]
It doesn't exist yet
