### ISSUE TITLE
Skin change information not being sent correctly to 1.19 clients

### ISSUE THREAD

**Issue by chandlerpl** [ViaVersion/ViaVersion#3142]
### `/viaversion dump` Output

https://dump.viaversion.com/7d61e3d47bda4790fb656fc69474c743a66c357ff3896bf86014760046a935c7

### Bug Description

Ability to change skins using [NickAPI](https://www.spigotmc.org/resources/nickapi-advanced-nickapi-1-8-1-19.26013/) broken for 1.19 clients on a 1.17 server. You can use [HaoNick](https://www.spigotmc.org/resources/haonick-advanced-nick-plugin-1-8-1-19.81108/) to test this.

### Steps to Reproduce

1. Setup 1.17.1 server with HaoNick and NickAPI installed.
2. Login with 1.19 client
3. Type /haonick:skin [username] and observe the skin doesn't change.
4. Login with 1.18 or 1.17 client
5. Repeat command in Step 3 but observe that the skin does change.

### Expected Behavior

Expected skin to be changed to the skin of the username provided.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by chandlerpl** [comment]
Hello, upon further investigation I have found that this issue is specific to 1.19.1/2 (Protocol 760), and is actually working on 1.19 (protocol 759), I believe the issue comes from the player_info packet

**Comment by FormallyMyles** [comment]
Could you confirm if this happens on the latest ViaVersion?

**Comment by chandlerpl** [comment]
Hello, sorry for the late response, it seems like the bug is fixed in ViaVersion 4.5.1
