### ISSUE TITLE
Ignoring plugin is kicking out of the server

### ISSUE THREAD

**Issue by iTroodon** [ViaVersion/ViaVersion#3143]
### `/viaversion dump` Output

https://dump.viaversion.com/012ef54ee0d4046cc9b0cc04abf792f4e7ae5638eba1c6759ea7df2284c686e7

### Console Error

https://paste.gg/p/anonymous/5753d3a4355e4bbe88f4b5452c632e6e

### Bug Description

I am trying to connect a 1.8 server lobby to a 1.18.2 server roleplay and sometimes it kick a lot of times out of the server and fallback of to the lobby

### Steps to Reproduce

1. Connect to the roleplay
2. Wait a couple of minutes
3. Via version kick us to Lobby

### Expected Behavior

Not kicking out of the server

### Additional Server Info

Bungee: waterfall-1.19-504
Lobby: Flamepaper-1.8.8
Roleplay: paper 1.18.2

Via version running on Lobby and Roleplay servers

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--%22acaf625c%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--%22acaf625c%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.2)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 16 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-16%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by iTroodon** [comment]
> 



> ![Platform: git--PaperSpigot--%22acaf625c%22%20%28MC%3A%201.8.8%29](https://camo.githubusercontent.com/9b1fa400cdd52828343c4c4aeb6ca507d96e15d3bf2dd7c16beb1a05a2f062ad/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d5061706572537069676f742d2d25323261636166363235632532322532302532384d43253341253230312e382e382532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.4.2): 11 commits behind master](https://camo.githubusercontent.com/b77f554458f8c3149f7f57e9c061d321a647fac2e2a337f2a8737735d894bea6/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e342e32292d3131253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaRewind(2.0.2): 16 commits behind master](https://camo.githubusercontent.com/e8431d9f27670b90d632a4d61c4e9ce0bc6a6e2a67ff2c4b90492bdfd8506832/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f566961526577696e6425323028322e302e32292d3136253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) Please try the **latest** build(s) from https://ci.viaversion.com/. In case the issue still persists send the new dump


Sorry I do some mistakes. Via version is only running on lobby not on roleplay and In the lobby I have the latest snapshot ViaVersion-4.4.3-SNAPSHOT.jar

**Comment by FormallyMyles** [comment]
Could you reupload the error to pastebin/mclo.gs? Otherwise testing without other plugins and with latest viaversion to attempt to pinpoint the cause.
