### ISSUE TITLE
Can't Make Bridges With ViaRewind

### ISSUE THREAD

**Issue by joao218623** [ViaVersion/ViaVersion#3149]
### `/viaversion dump` Output

https://dump.viaversion.com/4fc89f6f4ae79df51f439fd196b018cac29d7e63d6081f31c416d0a1e2992e50

### Bug Description

I can't make bridges with viarewind i disable everything the bossbar... but i can't it makes like the block doens't exit. the block selection doens't happer-

### Expected Behavior

Bridges not work

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--81%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Paper--81%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2): 14 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.2)-14%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 17 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.4.2): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.4.2)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by kennytv** [comment]
Wrong repository, it's also very hard to understand what your issue is. Please open a new issue on the ViaRewind repo with a clearer description of the issue
