### ISSUE TITLE
Block protected by Residence will not come back when block break on older MC version.

### ISSUE THREAD

**Issue by CooderSK** [ViaVersion/ViaVersion#3150]
### `/viaversion dump` Output

https://dump.viaversion.com/0e0251970ca81a55714fb11fa353a586930ef4cfa725786547b8cc64760903f4

### Bug Description

When we break the block which is an alternative replacement of a newer unsupported block and is prevented from breaking by the residence plugin, it does not appear back until clicking on the block next to it. It looks like the update is not being sent from the server to the client after the block break cancellation. When I right-click on the empty space block will come back instantly.

### Steps to Reproduce

1. Create shroomlight platform for example 5x5
2. Protect shroomlight platform using residence plugin (prevent block break)
3. Connect to server using 1.15.2 and try to break shroomlight block

### Expected Behavior

Block will not disappear on the client side and come back.

### Additional Server Info

We are using spigot 1.19.2 and the latest bungeecord with ViaVersion and ViaBackwards.
ViaVersion and ViaBackwards are installed only on the bungeecord server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3604--Spigot--1aec3fc--f43634a%20%28MC%3A%201.19.2%29](https://img.shields.io/badge/Platform-3604--Spigot--1aec3fc--f43634a%20%28MC%3A%201.19.2%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2): 14 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.2)-14%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.4.2): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.4.2)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by CooderSK** [comment]
https://dump.viaversion.com/0e0251970ca81a55714fb11fa353a586930ef4cfa725786547b8cc64760903f4

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A2d369e8%3A1664](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A2d369e8%3A1664-3498db?style=flat-square) </br>![ViaVersion (4.4.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Move Via from the proxy to the backend servers

**Comment by CooderSK** [comment]
Hi, I moved both ViaVersion and ViaBackwards to the spigot servers and removed them from the proxy, but I am still facing the same issue.
