### ISSUE TITLE
ERROR IN Protocol1_11_1To1_12 IN REMAP OF CHUNK_DATA (0x20)

### ISSUE THREAD

**Issue by 3154311518** [ViaVersion/ViaVersion#3153]
### `/viaversion dump` Output

https://dump.viaversion.com/7e556eeb8f2a6f96dc88c0e06791489c60d2cab25d90f62779d3a06fc0d2b9c2

### Console Error

![QWE](https://user-images.githubusercontent.com/46740577/201168815-c288d5b6-ccd2-4779-9fdf-890f35a3598c.png)

[01:44:22 INFO] [long_715|/127.0.0.1:59057] <-> ServerConnector [服务器] has connected
[01:44:27 WARN] [ViaVersion] ERROR IN Protocol1_11_1To1_12 IN REMAP OF CHUNK_DATA (0x20)
[01:44:27 INFO] [long_715] disconnected with: EncoderException : com.viaversion.viaversion.exception
.InformativeException: Please report this on the Via support Discord or open an issue on the relevan
t GitHub repository
Packet Type: CHUNK_DATA, Type: Chunk, Data: [], Source 0: com.viaversion.viabackwards.protocol.proto
col1_11_1to1_12.packets.BlockItemPackets1_12$4 (Anonymous), Packet ID: 32 @ io.netty.handler.codec.M
essageToMessageEncoder:104
[01:44:27 INFO] [/127.0.0.1:59057|long_715] -> UpstreamBridge has disconnected
[01:44:27 INFO] [/127.0.0.1:59057|long_715] <-> DownstreamBridge <-> [服务器] has disconnected

### Bug Description

When using the 1.8 client to deliver the world, you will be kicked out of the server
1.12.2 will not be kicked out of the server

### Steps to Reproduce

none

### Expected Behavior

none

### Additional Server Info

BungeeCord
Plugins: ViaVersion4.4.2 ViaRewind2.0.2 ViaBackwards4.4.2

Backend Mohist-1.12.2-321

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: SSCord--1.19--20220706--ac66b20](https://img.shields.io/badge/Platform-SSCord--1.19--20220706--ac66b20-3498db?style=flat-square) </br>![ViaVersion (4.4.2): 14 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.2)-14%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 17 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.4.2): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.4.2)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by kennytv** [comment]
We don't support Mohist
