### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AVuTuVA** [ViaVersion/ViaVersion#3155]
### `/viaversion dump` Output

https://dump.viaversion.com/cc78e66e3ef22de6c4d4d0fb232a3e2e6c869af013f584d7408932112936a7d7

### Console Error
![image](https://user-images.githubusercontent.com/66278054/202556979-285ed24d-4db4-46cd-861a-7897e65697f6.png)

### Bug Description

The error is only with spark, this is not the case with other plugins

### Steps to Reproduce

Start server 1.12.2 and login from 1.19.2

### Expected Behavior

Expected no error

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.5.0-22w46a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.5.0--22w46a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by HowardZHY** [comment]
java19?!

**Comment by kennytv** [comment]
Spark needs to update its adventure platform dependency

**Comment by AVuTuVA** [comment]
> java19?!

and what?
