### ISSUE TITLE
packet 0/75 (client boundsetchunk cache center packet)

### ISSUE THREAD

**Issue by haroldrc** [ViaVersion/ViaVersion#3157]
### `/viaversion dump` Output

https://dump.viaversion.com/f2acdf9becededfe3d1a842633eba9097b96701e6e20bd86f01ba7b6aa10e50b

### Console Error

packet 0/75 (client boundsetchunk cache center packet) was larger than i expected, found 51 bytes extra whilist reading packet 75

![image](https://user-images.githubusercontent.com/29206120/203447648-7458013f-3191-4fad-b6bb-da2fb5c4859f.png)

### Bug Description

when i try to access the server after reboot

### Steps to Reproduce

1 login with a 1.19 (I don't know if it occurs with other versions)

### Expected Behavior

be able to enter

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: WindSpigot%20Release%20v2.1.2%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-WindSpigot%20Release%20v2.1.2%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.4.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by HowardZHY** [comment]
WindSpigot as a Nacho Fork, was known to break something, test with normal paper.

**Comment by haroldrc** [comment]
i have two servers with windspigot, and only one from this problem

**Comment by Jo0001** [comment]
Does the issue still persists with the latest ViaVersion from https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/build/libs/ViaVersion-4.5.1-SNAPSHOT.jar ?

**Comment by FormallyMyles** [comment]
More info is needed like updating to the latest, I suspect this could be a plugin conflict so you'd need to copy your server and test with less plugins.

**Comment by haroldrc** [comment]
i tried with less plugins
