### ISSUE TITLE
[feat.] Resource packs with modern models

### ISSUE THREAD

**Issue by matteoturini** [ViaVersion/ViaVersion#3158]
### Problem Description

Rabbits are named "frogs" to fill the missing mobs, this is not immersive and causes confusion.

### Solution Description

Packing the models into a resource pack, and sending the models to the client. This way, players would see proper animations and textures for the mobs.

### Alternatives

None.

### Additional Info

I don't know if there are any licensing restrictions, but if there are, this packing would have to be done at the server first start up.

This would also not work for older versions without proper custom models.

**Comment by kennytv** [comment]
There's an easy and powerful way to get new models without such confusion: Using new client versions. 😎

People have tried such a feat multiple times, but the effort required to update and maintain such a thing across different client versions is just not worth anything over simply updating the client

**Comment by matteoturini** [comment]
> Using new client versions

Not always possible if a person's computer doesn't meet the minimum OpenGL version, but I understand why this would be a big effort and isn't planned.

**Comment by buzzcoding** [comment]
There is [https://modrinth.com/mod/forcegl20](https://modrinth.com/mod/forcegl20), which allows you to use Minecraft 1.17+ on OpenGL 2.0.

**Comment by matteoturini** [comment]
> There is https://modrinth.com/mod/forcegl20, which allows you to use Minecraft 1.17+ on OpenGL 2.0.

how have i not heard of this tysm

**Comment by buzzcoding** [comment]
You’re welcome 👍
