### ISSUE TITLE
Block Placing bug

### ISSUE THREAD

**Issue by jameshackerbond** [ViaVersion/ViaVersion#3160]
### `/viaversion dump` Output

https://dump.viaversion.com/a1c473d45f1cfbca599647f822fbd57c646f9a5e607711323fa368c0ad91da61

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Hello, On 1.12.2 when I log in thru my waterfall proxy or to even the backend server when I place down at least 3 or more blocks it starts to not place them down. I do not know why this is happening.

### Steps to Reproduce

1. Make sure the server is paper 1.12.2
2. login using 1.19.2 when viaversion is enabled
3. place some blocks down until it starts to desync the blocks

### Expected Behavior

The blocks should be placed down

### Additional Server Info

Server version: 1.12.2
Waterfall version: lastest
I used 1.19.2 for the client

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1618%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1618%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.4.2): 14 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.2)-14%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 17 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.4.2): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.4.2)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by jameshackerbond** [comment]
<img width="875" alt="image" src="https://user-images.githubusercontent.com/82678869/205425428-e5a21017-44e4-42c7-81ea-f79c82de9279.png">
