### ISSUE TITLE
Running the kick or ban command with a reason causes you to get disconnected with a DecoderException

### ISSUE THREAD

**Issue by Jaren8r** [ViaVersion/ViaVersion#3161]
### `/viaversion dump` Output

https://dump.viaversion.com/975efecafa9c387f808c26e350b980cbfe921b25cde2cc99f01d665d3e6653da

### Console Error

```
https://paste.gg/p/anonymous/93959275767a43f58b2acbe1b0827227
```

### Bug Description

Running the kick or ban command with a reason causes a DecoderException.

### Steps to Reproduce

1. Login with a 1.19.3 client on a 1.19.2 server
2. Run /minecraft:kick (username) test
3. Observe

### Expected Behavior

The kick command should run.

### Additional Server Info

This was reproduced on a clean paper server with only ViaVersion

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--307%20%28MC%3A%201.19.2%29](https://img.shields.io/badge/Platform-git--Paper--307%20%28MC%3A%201.19.2%29-3498db?style=flat-square) </br>![ViaVersion (4.5.0): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.0)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by Jaren8r** [comment]
Issue still persists

Dump: https://dump.viaversion.com/da665b85dd05b493f19843bc4a494e18e459af4d8092f2f8c25ad0003b8d9aab

**Comment by Barvalg** [comment]
![Platform: git--Paper--307%20%28MC%3A%201.19.2%29](https://img.shields.io/badge/Platform-git--Paper--307%20%28MC%3A%201.19.2%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
