### ISSUE TITLE
1.19.2 -> 1.19.3 missing profile public key.

### ISSUE THREAD

**Issue by houseofdoggus** [ViaVersion/ViaVersion#3168]
### `/viaversion dump` Output

https://dump.viaversion.com/991d0f8cd6b646829a40860f2b4a722fe7208aa1e00ebda9a029fc6258c498b5

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

A server that I connect to has updated to 1.19.3 and I'm running Forge Client side mods on 1.19.2.

When I connect with 1.19.2 and try to chat, I receive "Chat disabled due to missing profile public key. Please try reconnecting"

When I connect with 1.19.3 chat works as expected.

### Steps to Reproduce

1. Log in via a 1.19.2 client.
2. Try to chat - doesn't work
3. Log in via a 1.19.3 client.
4. Try to chat - should work

### Expected Behavior

When trying to chat on the 1.19.2 client, you should receive a message saying, "Chat disabled due to missing profile public key. Please try reconnecting."

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3624--Spigot--d90018e--ab1586c%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-3624--Spigot--d90018e--ab1586c%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.2): 17 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by Barvalg** [comment]
![Platform: 3624--Spigot--d90018e--ab1586c%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-3624--Spigot--d90018e--ab1586c%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by HowardZHY** [comment]
you MUST disable enforce-secure-profile in server.properties file on every 1.19+ server with Via.

**Comment by houseofdoggus** [comment]
I have done this and it works. However, when this is done, there is a new message that will appear stating that Chat Messages cannot be verified.

**Comment by Kichura** [comment]
By default, You can ignore the "cannot be verified" message as it means chat reporting is disabled on server as whole - But should it continue to annoy you then consult to installing **FreedomChat** plugin into your paper server.

**Comment by HowardZHY** [comment]
use a mod to Ignore it. your minecraft account could be banned if chat msgs 're verified.

**Comment by kennytv** [comment]
I might look into making this work in the future, but for the time being there's the workaround

**Comment by Kichura** [comment]
> > By default, You can ignore the "cannot be verified" message as it means chat reporting is disabled on server as whole - But should it continue to annoy you then consult to installing **FreedomChat** plugin into your paper server.
> 
> This solution still requires the enforce-secure-profile to be set to false. Does this not pose security threats?

This should not cause any security threats but also in practice; it makes the server morely compatible with other plugins such as this one.

**Comment by Bobcat00** [comment]
> By default, You can ignore the "cannot be verified" message as it means chat reporting is disabled on server as whole

I haven't investigated this a lot, but I think the wording of that message is misleading. Instead of "cannot be verified", I think it should say "may not be verified". It appears to me that 1.19.3 players can still report other 1.19.3 players.

In other words, `enforce-secure-profile=false` does not disable chat reporting as a whole.
