### ISSUE TITLE
Chat don't work below 1.19

### ISSUE THREAD

**Issue by MintMissy** [ViaVersion/ViaVersion#3169]
### `/viaversion dump` Output

https://dump.viaversion.com/aae2f68adc873014baffc1609c380ebedaff2e2e7c652c3ac2b9cb5bb3783c27

### Console Error

They're no errors in the console

### Bug Description

Sending chat messages from clients below 1.19 doesn't work.
I've tried the following versions: 1.16.5, 1.17.1, 1.18.2, 1.19, and 1.19.2. The chat worked only on 1.19 and 1.19.2

Send messages on chat doesn't leave any trace - there's no blank line. It looks like they're not send.

If I remember correctly the chat worked fine around a week ago, it all crushed down within last week. Unfortunately I don't remember exactly when. We've updated few plugins in this time.

### Steps to Reproduce

1. Login with a client below 1.19
2. Try to send a message on chat

### Expected Behavior

Message should be send to the server, other players should be able to see it.

### Additional Server Info

We're running via version, via backwards & via rewind on 1.17.1 paper server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--409%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--409%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.2): 17 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by MintMissy** [comment]
https://dump.viaversion.com/6b455b237254d13c2dfeec679835c7911bcd2f9e3462427ab57b2acdb56e84b7

**Comment by Barvalg** [comment]
![Platform: git--Paper--409%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--409%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by MintMissy** [comment]
https://dump.viaversion.com/87d50549539ed949cc7b37b52d8d5be103a392c2a132a8a77d84ffca46bfe64f

**Comment by Barvalg** [comment]
![Platform: git--Paper--409%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--409%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
