### ISSUE TITLE
ViaVersion reported an error in some inexplicable circumstances, and some players were disconnected after the error was reported

### ISSUE THREAD

**Issue by Mc9420** [ViaVersion/ViaVersion#3171]
### `/viaversion dump` Output

https://dump.viaversion.com/5cc716a410631eea95baba10d9d123de394dab14278c005b6819ba2cba1705fb

### Console Error

```
The log file is as follows
```
[latest.log](https://github.com/ViaVersion/ViaVersion/files/10233389/latest.log)

### Bug Description

ViaVersion reported an error in some inexplicable circumstances, and some players were disconnected after the error was reported

### Steps to Reproduce

ViaVersion reported an error in some inexplicable circumstances, and some players were disconnected after the error was reported

### Expected Behavior

ViaVersion reported an error in some inexplicable circumstances, and some players were disconnected after the error was reported

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.4.2)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump
