### ISSUE TITLE
ViaVersion Can't join proxy

### ISSUE THREAD

**Issue by GameHoundInteractive** [ViaVersion/ViaVersion#3173]
### `/viaversion dump` Output

https://dump.viaversion.com/6bd773a365d720d86efc26d4cf6eb93bb8874d2529fade84fdd8198173915022

### Console Error

```
Put the paste.gg link or text here.
https://hastebin.com/xerecahote.md
```

### Bug Description

Anytime i try to join the server it throws that error, i've tried it with all my plugins disabled but viaversion and with viaversion removed. Without viaversion i can join fine with viaversion i cant. 

Tried without network manager and vivecraft as both edit proxy stuff. issue still persisted

1.19.3 Lobby Server, Tried joining with clients 1.19.1 to 1.19.3
Did some basic trouble shooting in discord with someone. 
<img width="1252" alt="Screenshot_73" src="https://user-images.githubusercontent.com/19619093/207868024-fe0aa78c-e634-4495-b00f-84c176432ec4.png">

### Steps to Reproduce

install viaversion and viaback on proxy and lobby servers 1.19.3 servers. 
try to join

### Expected Behavior

Should join game, but instead being kicked.

### Additional Server Info

Bungee cord fork, NullCordX - Basicly waterfall/travertine fork. All 7 other plugins work on it.

Plugins:
ForceResourcepacks
LuckPerms-Bungee-5.4.54
NetworkManager-Bungee-V2.12.8
PartyAndFriends
Vivecraft_bungeecord

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.19--R0.1--SNAPSHOT](https://img.shields.io/badge/Platform-1.19--R0.1--SNAPSHOT-3498db?style=flat-square) </br>![ViaVersion (4.5.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Your fork of Bungee is doing something that breaks Via - we generally don't support anything but standard Bungee/Velocity proxies
