### ISSUE TITLE
Shulker NBT Parsing limits size, Kicking player 1.17.1

### ISSUE THREAD

**Issue by Belceebuh** [ViaVersion/ViaVersion#3174]
### `/viaversion dump` Output

https://dump.viaversion.com/a3c27dc1720810951d42c69815d78cafcb6d7e6c12a1de2bde8fb3a8c732211c

### Console Error

```
https://mclo.gs/jOJl9O8
```

### Bug Description

this error happens because one of my users picks a shulker and it is not the first time it happens to me, how can I deactivate this option so it does not block my users? because in my server we use custom objects and this makes that sometimes it blocks in an unnecessary way.

### Steps to Reproduce

1. Mining Shulker
2. Pick Shulker
3. To be blocked by the server

### Expected Behavior

I was hoping that my players would not be expelled

### Additional Server Info

I only use viaversion and viabackwards, they are on my backend server only.

SevenSpigot is the same as Paper, I only made some changes which should not affect and do not affect any other plugin and even less viaversion.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: SevenSpigot--1.17.1%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-SevenSpigot--1.17.1%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by HowardZHY** [comment]
try with normal spigot or paper. don't use weird forks

**Comment by Belceebuh** [comment]
the fork is private and I know what it has, it has nothing that should affect the operation of viaversion, I just need to know how to remove that limiter that is like an anti-crash.

**Comment by FormallyMyles** [comment]
You would need to modify https://github.com/ViaVersion/ViaVersion/blob/435a986068a80ebe58703d825c09bf17240c3be1/api/src/main/java/com/viaversion/viaversion/api/type/types/minecraft/NBTType.java#L38

I'll close it since you claim it's specific, but if it's possible in vanilla (without lots of weirdness, we'd probably look into an option/increase).
