### ISSUE TITLE
Double Place  sound

### ISSUE THREAD

**Issue by TheDarkSword** [ViaVersion/ViaVersion#3175]
### `/viaversion dump` Output

https://dump.viaversion.com/a8b340c021d60ac80b9f514bc6c2c6fb8f267c8b3a56998bddf169ff9b5f88d2

### Console Error

No Errors

### Bug Description

When a player join with version 1.19.x and place a block then the block place sound is reproduced 2 times.
I have Purpur server and Spigot 1.8 server and it happens with both (viaversion is only on velocity).

That's happen only when a player join with 1.19.x, with lower versions is all ok

### Steps to Reproduce

1. Login with 1.19.x client
2. Place a block

### Expected Behavior

The place sound should be played just one time

### Additional Server Info

I'm using ViaVersion, ViaBackwards and ViaRewind only on velocity. I disabled all plugins and uploaded only ViaVersion and the bug still persist.

If i place ViaVersion directly to Spigot server the bugs does not happen anymore.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--5b1621d3--bunknown%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--5b1621d3--bunknown%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): 2 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.5.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by FormallyMyles** [comment]
Does this occur if you have ViaVersion on your backend instead?

**Comment by TheDarkSword** [comment]
This occours ONLY if ViaVersion is on the Backend server (Velocity last version). 

If I put ViaVersion on a Spigot Server that works correctly and place sound is played only 1 time.

**Comment by FormallyMyles** [comment]
This is unfortunately related to it being on the proxy then and I would advise moving it to your backend (since viaversion will have more data).

**Comment by TheDarkSword** [comment]
I can't place ViaVersion on every single spigot server because is more lightweight to place it on the proxy. By the way, why the place sound is played two times? There are some data that are sent two times in the proxy? Why with ViaVersion in a Spigot Istance the bug does not occour anymore?

**Comment by FormallyMyles** [comment]
> I can't place ViaVersion on every single spigot server because is more lightweight to place it on the proxy. By the way, why the place sound is played two times? There are some data that are sent two times in the proxy? Why with ViaVersion in a Spigot Istance the bug does not occour anymore?

Because the Spigot instance has more information on when the sound should be sent most likely. It is always better to have ViaVersion on the backend for things like this where the proxy doesn't have this data.
