### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by skbeh** [ViaVersion/ViaVersion#3179]
### `/viaversion dump` Output

https://dump.viaversion.com/65e46b47b5a5cf38145285d4835b5b260373dda7dadcfed9d901aa9f0c29e37d

### Console Error

https://paste.debian.net/hidden/2688248d/

### Bug Description

The player can not join.

### Steps to Reproduce

Login with a client.

### Expected Behavior

The player can join.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PandaSpigot--79%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PandaSpigot--79%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by HowardZHY** [comment]
also try to disable ServerSigns

**Comment by HowardZHY** [comment]
The error related with Block NBT. So I was looking for which plugin is related with block data. Otherwise part of you server world might be corrupt.
