### ISSUE TITLE
Hitting a player causes him to get kicked

### ISSUE THREAD

**Issue by GoodGameInfinity** [ViaVersion/ViaVersion#3183]
### `/viaversion dump` Output

https://dump.viaversion.com/8159fefd7f80ac5b8abce3f4ab67fe97661da74ddf16eafd492c3980fc5ce698

### Console Error

```
https://paste.gg/p/anonymous/bbc15be4a471480892353c6368570d2f
```

### Bug Description

Hitting a player causes a kick (of the player that got hit) with reason of "There is an internal error in your connection"

### Steps to Reproduce

1. Install Velocity with Viaversion
2. Install 1.18.2 Fabric server
3. Get a player to hit another player

### Expected Behavior

The player should not get kicked just for being hit

### Additional Server Info

Viaversion dump is irrelevant because then i tried disabling all the plugins and players still got kicked.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--c9e0e14e--b201%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--c9e0e14e--b201%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by FormallyMyles** [comment]
From experience this is a conflict with LimboAPI / Filter, you need to otherwise move the Via plugins to your backend.
