### ISSUE TITLE
Players kicked with console error

### ISSUE THREAD

**Issue by samfces** [ViaVersion/ViaVersion#3185]
### `/viaversion dump` Output

https://dump.viaversion.com/7392a425994376eaa96f9e14b24c2f5c3340e3501492b7f6d07f0cd3c90715a0

### Console Error

```
https://paste.v4guard.io/xuwevayuji.yaml
```

### Bug Description

My players are being kicked for no apparent reason. The bug that appears in the console is the one specified in the previous section

### Steps to Reproduce

Step 1: Login to the server and wait
Step 2: Sooner or later you will get that error in the console and you will be kicked.

### Expected Behavior

Players should not be kicked and console error should not be shown.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by samfces** [comment]
This error is urgent, all my players are complaining as they are being kicked out and are losing their items (combatlog).

**Comment by Braaadley** [comment]
I am also experiencing this on my network as well. It's affecting 1.19.3 client users.

**Comment by FormallyMyles** [comment]
Ideally, you want to replicate this in a duplicated server and remove plugins to diagnose what is happening, for some reason entity equipment isn't being handled properly and I'd suspect it's likely down to another plugin.
