### ISSUE TITLE
ERROR IN Protocol1_9To1_8 IN REMAP OF ENTITY_METADATA (0x1C)

### ISSUE THREAD

**Issue by Smole17** [ViaVersion/ViaVersion#3187]
### `/viaversion dump` Output

https://dump.viaversion.com/192ec4a11e93a61e66c67799050451a4b1c94ff2fd2ad77f858e22545c530023

### Console Error

https://paste.gg/p/anonymous/3a907b88fe0f43fb92db339c0f4ea57c

### Bug Description

When a player connects on 1.9+ client and goes to player with 1.8 client then players got kicked.

### Steps to Reproduce

1. Login with 1.9+ client.
2. Login with 1.8 client.
3. You should have latest netty.

### Expected Behavior

I expected that I will teleport a player and goes to test smth.

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.8.8%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-1.8.8%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by Smole17** [comment]
Here is 4.5.1, but I have dumped on 4.5.2. Damn.
https://dump.viaversion.com/73388c5e15c1eb0bb0750412b2db26271c0f7eceb56970de018f525f8acec14f

**Comment by Barvalg** [comment]
![Platform: 1.8.8%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-1.8.8%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
Is this reproduceable without other plugins? I'd suspect something is sending bad entity data.
