### ISSUE TITLE
disconnected with Encoder Exception

### ISSUE THREAD

**Issue by kfitzgerald** [ViaVersion/ViaVersion#3188]
### `/viaversion dump` Output

https://dump.viaversion.com/ccc1256b29143775214f3112faf844873a6184bb2d118fb1fbe0f1f456cb4c8e

### Console Error

Error paste:
https://paste.gg/p/anonymous/3d67dce3133641aeaf0ce34a1186a0b0

Short version for searching:
```
Packet Type: SPAWN_ENTITY, Type: VarInt, Data: [Pair{Type|VarInt, 1}, Pair{Type|UUID, d5cd3b76-2597-4062-9c30-6a356c6a1121}], Source 0: com.viaversion.viaversion.rewriter.EntityRewriter$2 (Anonymous), Packet ID: 0 @ io.netty.handler.codec.MessageToMessageEncoder:107tt
```

### Bug Description

1.19.3 client connecting via proxy to 1.16.5 server causes exception and disconnect

### Steps to Reproduce

1. Login with 1.19.3 client
2. Connect to a 1.16.5 server behind bungee/viaversion
3. Exception ensues 

### Expected Behavior

Every client version prior to 1.19.3, 1.16.5 servers were accessible with ViaVersion

### Additional Server Info

Plugins all updated to latest available versions / snapshots where applicable.

BungeeTabListPlus is notoriously flakey, I'd suspect they may have a role in this, but unsure.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A13085b9%3A510](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A13085b9%3A510-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by kfitzgerald** [comment]
could have sworn i used the latest snapshot...
https://dump.viaversion.com/0e8f97b41ddfb72c6155a1668b38cf6a41818216a1b597254f44abb743879596

Updated but problem still persists

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A13085b9%3A510](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A13085b9%3A510-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kfitzgerald** [comment]
![image](https://user-images.githubusercontent.com/250021/209759205-6b4ad192-556e-4db3-8461-76d760e3b5f8.png)

Client error screenshot

**Comment by FormallyMyles** [comment]
Are you able to try with the Via plugins on the backend servers instead? Otherwise testing without any plugins would be a good indicator, could be a plugin sending bad data / something going wrong proxy level.
