### ISSUE TITLE
Players get randomly disconnected

### ISSUE THREAD

**Issue by jonesdevelopment** [ViaVersion/ViaVersion#3192]
### `/viaversion dump` Output

https://dump.viaversion.com/1b5d41da854cca4ccd681da377b34f5b1ae95b65675b9e79d4060e25763b6d71

### Console Error

```
Put the paste.gg link or text here.
```
[01:07:39 INFO]: MeepIsBeast lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NoClassDefFoundError: com/viaversion/viaversion/libs/kyori/adventure/text/serializer/gson/GsonComponentSerializer

### Bug Description

1.19.2 clients on 1.19.3 servers are randomly (?) being disconnected from the server.
I am using ViaBackwards and ViaVersion but it seems like this error is caused by ViaVersion.

### Steps to Reproduce

1. Login with 1.19.2 client on a 1.19.3 server
2. Exist and maybe type in chat?

### Expected Behavior

You shouldn't randomly be kicked.

### Additional Server Info

I am using BungeeCord but ViaVersion is only on the Spigot (Purpur) server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1880%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Purpur--1880%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.5.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by Kichura** [comment]
Either your TagsAPI or KitPvP plugin is causing issues with via* itself, Please check your plugin scripts to see what causes the missing class error to fail.
