### ISSUE TITLE
ERROR IN Protocol1_19_3To1_19_1 IN REMAP OF CHUNK_DATA (0x21)

### ISSUE THREAD

**Issue by Shadoworks** [ViaVersion/ViaVersion#3196]
### `/viaversion dump` Output

https://dump.viaversion.com/c257944738bed963877238be5958c7098e9d52be726210dbae0fe6efd3251a70

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/70ef759d6c004ba1a27e878fbbf8589f

### Bug Description

Player issued server command: /home
In console is the error message is shown (find in paste.gg)
After this the player was kicked automaticly from the server

### Steps to Reproduce

I don't now whats happend.

### Expected Behavior

All players on my server use /home. But no one produce this error message.

### Additional Server Info

Server runs on Paper 1.19.2

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PufferfishPlus--33%20%28MC%3A%201.19.2%29](https://img.shields.io/badge/Platform-git--PufferfishPlus--33%20%28MC%3A%201.19.2%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.5.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump
