### ISSUE TITLE
ERROR IN Protocol1_19_1To1_19_3 IN REMAP OF CHUNK_DATA (0x20)

### ISSUE THREAD

**Issue by Shadoworks** [ViaVersion/ViaVersion#3197]
### `/viaversion dump` Output

https://dump.viaversion.com/d7cb888d69dd1f5da5038c9443510defed4647eb3b981c43579cb0dc8dc4c0bb

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/5e1e1adc3b24475fa9774979c9ca2509

### Bug Description

Player issued server command: /home
In console is the error message is shown (find in paste.gg)
After this the player was kicked automaticly from the server

### Steps to Reproduce

I don't now whats happend.

### Expected Behavior

All players on my server use /home. But no one produce this error message.

### Additional Server Info

Server runs on Paper 1.19.3

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PufferfishPlus--38%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--PufferfishPlus--38%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.5.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by Shadoworks** [comment]
https://dump.viaversion.com/8a24ab844c0ef10b084f8e841dc7f2121f0a367bb2a3e1e285dd1c3e3a6f86a2

**Comment by Barvalg** [comment]
![Platform: git--PufferfishPlus--38%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--PufferfishPlus--38%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Bobcat00** [comment]
This occurred on my newly-updated Paper 1.19.3 server today. It happened when a player running 1.19.1/2 used the /home command.

https://dump.viaversion.com/5d57058ba93d850ea55f3e753c2f1f66e5c07646bd5f17803860c3a08728c806

**Comment by Barvalg** [comment]
![Platform: git--Paper--372%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Paper--372%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.5.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by PedroMPagani** [comment]
One thing in common that everyone in here is, you`re all using ProtocolLib, I recommend trying without PLIB before mainly accusing ViaVersion

**Comment by F3F5** [comment]
BUMP! I HAVE LAG https://timings.aikar.co/dev/?id=68557f313abe44de9bf81a17402df2ca

**Comment by FormallyMyles** [comment]
> BUMP! I HAVE LAG https://timings.aikar.co/dev/?id=68557f313abe44de9bf81a17402df2ca

whatever you're trying to link has no evidence of being caused by ViaVersion

**Comment by Yomamaeatstoes** [comment]
So you are saying it is protocollib?

**Comment by Yomamaeatstoes** [comment]
So should we refer back to them?

**Comment by Yomamaeatstoes** [comment]
I have a suspicion, I think what we may all have in common is packet data being manipulated by third party plugins, let me explain. A long time ago as in around Aug 24, 2022 22:41 I downloaded a plugin called https://www.spigotmc.org/resources/orebfuscator-anti-x-ray.82710/ which of course manipulates packets to make blocks appear as another block. I recently enabled paper anti x ray a few days ago, and I started to receive some errors like what I showed you. When I enabled paper anti x ray I didn't delete https://www.spigotmc.org/resources/orebfuscator-anti-x-ray.82710/ which also relies on protocol lib. I am guessing that since paper anti x ray was overriding packets and https://www.spigotmc.org/resources/orebfuscator-anti-x-ray.82710/ it made some massive errors that appeared in the console and generated massive lag. As for now I have disabled https://www.spigotmc.org/resources/orebfuscator-anti-x-ray.82710/ and just kept paper anti x ray and so far at least for now I have not received any errors anymore. Hopefully this comment helps out!

**Comment by Yomamaeatstoes** [comment]
plugins - BanItem*, BedWars, BetterEconomy, BetterRTP, BisectHosting, ChatFilter, Chunky, ClansLite, ClientDetector, CommandBlockAsPlayer, DisableBreeding, DiscordSRV, dynmap, ElytraSpeed, floodgate, Geyser-Spigot, GlobalTrackedMaps, HarmonyScoreboard, HolographicDisplays, LuckPerms, Multiverse-Core, NoCheatPlus, NoteBlockAPI, Parkour, PL-Hide, PlaceholderAPI, PlayerKits, PlugManX (PlugMan), ProtocolLib, racing, ScoreboardChatShop, SecondThreadAPI*, SilkySpawnersLITE, Skywars, spark, Spleef*, StackMob, StormerAntiNetherRoof, StormerAntiSpam, StormerHomes, StormerTPA, StormerWarps, SuperVanish, Themis, TNTRun_reloaded, Vault, VaultToVanilla, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, WorldEdit, WorldGuard

**Comment by PedroMPagani** [comment]
> So you are saying it is protocollib?

No, you should remove Plugins 1 by 1 and confirm the issue first.

Disable ProtocolLib to start with.

**Comment by Yomamaeatstoes** [comment]
Disabling stats with protocol lib seemed to help lag as well, but disable protocollib? I would like to understand your thinking behind doing this.

**Comment by PedroMPagani** [comment]
> Disabling stats with protocol lib seemed to help lag as well, but disable protocollib? I would like to understand your thinking behind doing this.

ProtocolLib is the plugin thats used as A Library to handle packet listening, cancelling etc. It could be potentially a huge cause of lag if miss used by another developers, its also known not to be that STABLE in the newer versions, thats where my concept of lag comes from.

**Comment by bobhenl** [comment]
https://github.com/GeyserMC/Floodgate/issues/420 Seems it's the floodgate issue, I've tried mentioned solution & it helps

**Comment by HowardZHY** [comment]
Close as outdated, I don't think this can be reproduced anymore
