### ISSUE TITLE
Via Version Error when teleporting to one world to another

### ISSUE THREAD

**Issue by Yomamaeatstoes** [ViaVersion/ViaVersion#3199]
### `/viaversion dump` Output

https://dump.viaversion.com/1cd210f889dcc7aad8d45aca6cff757b48e3f5d9023b87c2ecd8a25b88b2be34

### Console Error

```

Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/9da4477479064bb39c1f8ab3e2c77b0e

### Bug Description

Hello, I am using the snapshot version of via version on the latest version for my server which is also on the latest version of paper on 1.19.2, but my minecraft version I am using to log in is 1.19.3 on the latest version. When going to the end to the over world, and vise versa I got this error. 

### Steps to Reproduce

I believe all you need to do is teleport to one dimension to another.

### Expected Behavior

No error in logs

### Additional Server Info

[INFO] Plugins (51): BanItem*, BedWars, BetterEconomy, BetterRTP, BisectHosting, ChatFilter, Chunky, ClansLite, CommandBlockAsPlayer, DisableBreeding, DiscordSRV, dynmap, floodgate, Geyser-Spigot, HarmonyScoreboard, HolographicDisplays, HungerGames, LuckPerms, Multiverse-Core, NoCheatPlus, NoteBlockAPI, Orebfuscator, Parkour, PL-Hide, PlaceholderAPI, PlayerKits, PlugManX (PlugMan), ProtocolLib, racing, ScoreboardChatShop, SecondThreadAPI*, SilkySpawnersLITE, Skywars, spark, Spleef*, StormerAntiNetherRoof, StormerAntiSpam, StormerHomes, StormerTPA, StormerWarps, Themis, TNTRun_reloaded, Vault, VaultToVanilla, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, WorldEdit, WorldGuard

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--307%20%28MC%3A%201.19.2%29](https://img.shields.io/badge/Platform-git--Paper--307%20%28MC%3A%201.19.2%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by Yomamaeatstoes** [comment]
Seems to have been fixed in the newest updates

**Comment by Yomamaeatstoes** [comment]
!close
