### ISSUE TITLE
ViaVersion Geysermc error

### ISSUE THREAD

**Issue by PrevikYT** [ViaVersion/ViaVersion#3200]
### `/viaversion dump` Output

https://dump.viaversion.com/571246b6ddc5dc79d551c7c512dca16397608daeb371f0de8deb53b4ca1dca56

### Console Error

```
https://paste.gg/p/anonymous/82af81b006fa41aca4ecae1f2ca9e3c2
```

### Bug Description

Can't login into server through bedrock using geysermc

### Steps to Reproduce

Connecting to server from 1.19
Getting an error "Failed connect to server" and error in console

### Expected Behavior

Kicked from server and have an error in console

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--d9ee34fe--b219%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--d9ee34fe--b219%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.5.1): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by PrevikYT** [comment]
https://dump.viaversion.com/571246b6ddc5dc79d551c7c512dca16397608daeb371f0de8deb53b4ca1dca56

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--d9ee34fe--b219%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--d9ee34fe--b219%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Please try moving via* to your backend servers only to see if the issue happens again, If it does then you very likely have bad third-party plugins on either the proxy or backend itself.
