### ISSUE TITLE
Error connecting 1.19.2 to 1.19.3: Velocity Server

### ISSUE THREAD

**Issue by EpicBirb** [ViaVersion/ViaVersion#3201]
### `/viaversion dump` Output

https://dump.viaversion.com/ccb74e0278e23964321b85744cbffe8a06b890dcab9389db887e20fa9d1c39c0

### Console Error

https://paste.gg/p/anonymous/b9b3dbf568794dfbb4ee66dcfcf0ed36

### Bug Description

Cannot connect to backend server using 1.19.2

### Steps to Reproduce

1. block protocols
- 758
- 757
- 756
- 755
- 754
- 753
- 751
- 736
- 735
- 578
- 575
- 573
- 498
- 490
- 485
- 480
- 477
- 404
- 401
- 393
- 340
- 338
- 335
- 316
- 315
- 210
- 110
- 109
- 108
- 107
- 47
- 5
- 4

2. start velocity server
3. connect

### Expected Behavior

Should be able to connect to the backend server with no problem

### Additional Server Info

Viaversion is installed on the proxy (Velocity)
Geyser and Floodgate is also installed on the proxy

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--8a048f05--b220%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--8a048f05--b220%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by EpicBirb** [comment]
I have already switched to the 4.5.2 snapshot and it still doesn't work

**Comment by EpicBirb** [comment]
https://dump.viaversion.com/fb4092188440918312afb374eceec3913e30e018db9b755c7f171eb00f84a22e

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--8a048f05--b220%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--8a048f05--b220%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
You are very likely missing viabackwards entirely from your proxy, Please install that and see if it happens again; If it does then please move via* to your backend servers only instead of velocity.

**Comment by EpicBirb** [comment]
> You are very likely missing viabackwards entirely from your proxy, Please install that and see if it happens again; If it does then please move via* to your backend servers only instead of velocity.

installing viabackwards on the proxy works, tyvm
