### ISSUE TITLE
Console Error - REMAP OF SPAWN_ENTITY

### ISSUE THREAD

**Issue by Serial1990** [ViaVersion/ViaVersion#3203]
### `/viaversion dump` Output

https://dump.viaversion.com/d72cc9c7a86c4c9b425edfc34175387d3fc2110ef824001c4078da5610b4ffde

### Console Error

https://paste.gg/p/anonymous/a4970ff4f79c470092cb6a4adfbcbf29/files/d4c425b799264d08a57942ffd93e5e2e/raw

### Bug Description

ViaVersion tells me to report this error. :D 

### Steps to Reproduce

Login with 1.19.3 i mean.

### Expected Behavior

idk what.

### Additional Server Info

i also use Waterfall with Geysir and Floodgate.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A13085b9%3A510](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A13085b9%3A510-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
