### ISSUE TITLE
Minor version not blocked in right way

### ISSUE THREAD

**Issue by BlockyTheDev** [ViaVersion/ViaVersion#3204]
### `/viaversion dump` Output

https://dump.viaversion.com/4bb4f4b533a36d2f524ae0fbe286e991982771896bd1f54bc3274ab51024072e

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

On a 1.19.3 server with installed ViaVersion and ViaBackwards and `block-versions` set to `["<1.19.2"]`, 1.19.1 clients should not be able to join the server.

### Steps to Reproduce

1. Set `block-versions` to `["<1.19.2"]`
2. Join the server with client version 1.19.1

### Expected Behavior

The 1.19.1 client should not be able to join the 1.19.3 server.

### Additional Server Info

ViaBackwards version 4.5.1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--381%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Paper--381%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.5.1): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by BlockyTheDev** [comment]
> ![Platform: git--Paper--381%20%28MC%3A%201.19.3%29](https://camo.githubusercontent.com/b5cd9810df84426c38af3b9cfc16b3368bc8752c51b5a8a911c1852e65fcf0b5/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d50617065722d2d3338312532302532384d43253341253230312e31392e332532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.5.1): 7 commits behind master](https://camo.githubusercontent.com/3cfc3a44ef0da3043ce387a4acd31fdf2dfbf97b0d7cf8d88c9717acbea74f21/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e352e31292d37253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaBackwards(4.5.1): 3 commits behind master](https://camo.githubusercontent.com/30b043dd122eb65b3581d6a064915e713e517a4703fd99e748adf7f787dd0cf5/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e352e31292d33253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) Please try the **latest** build(s) from https://ci.viaversion.com/. In case the issue still persists send the new dump

Already tried, same behaviour.

**Comment by FormallyMyles** [comment]
1.19.1 is the same protocol as 1.19.2

**Comment by BlockyTheDev** [comment]
> 1.19.1 is the same protocol as 1.19.2

Excuse me, I missed that.
