### ISSUE TITLE
1.19.3 server bugs

### ISSUE THREAD

**Issue by kooyhee** [ViaVersion/ViaVersion#3205]
### `/viaversion dump` Output

https://dump.viaversion.com/55abe6e6d3eb99b746fe5082b6a4e1a18a5c0855bf62e348dc290fb17ebc14c4

### Bug Description

![image](https://user-images.githubusercontent.com/113105789/213908773-d73e21de-700d-4bb5-bc14-7547153882db.png)
1. fence glitch
2. water and lava doesn't drain
3. door broken
4. doesn't work redstone ( include level, button too )
5. etc.....

### Steps to Reproduce

just place in world.
nothing more

### Expected Behavior

just place.and bug happen
nothing additional behavior

### Additional Server Info

I use waterfall for bungeecord but there's nothing happen in 1.12.2 server ( another server )
and there's no viaversion plugin in bungeecord.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1900%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Purpur--1900%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
The only way this possibly could be related to viaversion is if you're using it on both bungee and purpur. Which if you are, remove it from bungee. Otherwise it's down to your other plugins.
