### ISSUE TITLE
World to World Teleport - Player gets kicked

### ISSUE THREAD

**Issue by AtomixCM** [ViaVersion/ViaVersion#3206]
### `/viaversion dump` Output

https://dump.viaversion.com/ad88ecafc012196fc98992879bc3f73eba58d0b4152c4d86e03428b68383abf6

### Console Error

https://paste.gg/p/anonymous/fd37deee4ce8404499cf8622ecea7bd4/files/32083e8a43d54524b88a91a07493a8d6/raw

### Bug Description

When teleporting from one world to another (say going from the overworld to the end) the player gets kicked from the server.
![image](https://user-images.githubusercontent.com/29317588/214842264-e4e1300a-1046-4fb2-a1b8-e8956d752d7e.png)

### Steps to Reproduce

Log in with 1.19.3
Teleport to a different world
Get kicked

### Expected Behavior

A player should be able to teleport to a new world with no issue. It's not going from server to server that's the issue, it's going world to world. This does not happen on 1.19.2 clients

### Additional Server Info

We use BungeeCord

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--72%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Pufferfish--72%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.5.0)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by AtomixCM** [comment]
https://dump.viaversion.com/1c678fceece07d711e6cc11772c638e705b8729a489c452432300b44bd15a295

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--72%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Pufferfish--72%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
A few questions for this one:

1. Is via* installed on the backend servers only? (because if it's also on proxy; don't do that)
2. Does the problem persist with purpur 1.18.2?
3. If second question is yes then please try doing a binary search to see what causes it to break.

**Comment by AtomixCM** [comment]
@Kichura problem resolved with Latest Snapshot of Via + Purpur 1.18.2!
