### ISSUE TITLE
Problem with joining the server

### ISSUE THREAD

**Issue by KamlaXPL** [ViaVersion/ViaVersion#3208]
### `/viaversion dump` Output

https://dump.viaversion.com/c49042169336f626422675a95f6a5ba4f3061a7ed31758c2957e7b3b7f2805e7

### Console Error

No error displays

### Bug Description

Sometimes an error pops up with entering the server.

![image](https://user-images.githubusercontent.com/40739398/215350572-fbae6571-2794-40ca-8d62-7d1b4bda5983.png)

The error started to appear after updating from version 4.4.1 to the latest with support 1.19.3
On any version it can appear and it's random, either it will appear or it won't. If it does appear, you sometimes have to enter up to 3 times for the error to disappear.

### Steps to Reproduce

1. Join server

### Expected Behavior

The player should enter the server normally.

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--%22929db95%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--%22929db95%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.6.0-23w03a-SNAPSHOT): 1 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.6.0--23w03a--SNAPSHOT)-1%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by haroldrc** [comment]
same

**Comment by FormallyMyles** [comment]
Do you still get this error? Do you run BungeeCord or a proxy on top? If so can you provide plugins + ensure you only have ViaVersion on the backend.
