### ISSUE TITLE
EncoderException

### ISSUE THREAD

**Issue by CDY-pei** [ViaVersion/ViaVersion#3209]
### `/viaversion dump` Output

I I am not allowed to use this command!

### Console Error

![Snipaste_2023-02-01_10-21-06](https://user-images.githubusercontent.com/98030816/215930979-4980f054-9745-4c40-aaa4-00388547a852.jpg)

### Bug Description

Using selectors crashes on servers that can only be accessed with 1.12.2 clients

### Steps to Reproduce

1.I used Viaversion to switch the version from 1.8.9 to 1.12.2, on the Feather client
2.I used the (1.12.2) client to go to the server that only the 1.12.2 client, opened the selector (similar to Hypixel's game selection), and selected a game
3.During the process of entering the game, for some reason my client popped up Connection Lost, I was sure that there was nothing wrong with my network, and he reported an error(My system time is correct)
![Snipaste_2023-02-01_10-21-06](https://user-images.githubusercontent.com/98030816/215929522-a8f73b14-5591-4af5-8ad0-5044e762b7d2.jpg)

### Expected Behavior

The Connection should not lost

### Additional Server Info

I Used PachetFix ;Viaforge;Optfine;Chinese InputFix;Fix the sound when place block

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
We don't support ViaForge officially nor do we support older versions of our plugin
