### ISSUE TITLE
Error on Join | ViaVersion Velocity

### ISSUE THREAD

**Issue by LUPLUV** [ViaVersion/ViaVersion#3211]
### `/viaversion dump` Output

https://dump.viaversion.com/73ffb0c32b250898926e1170c2f24292992b2e9ffa87be3fe02f62ca95bb376b

### Console Error

```
[Put the paste.gg link or text here.](https://paste.gg/p/anonymous/4fe82108e1254ad99bb49ac81bdc7f55)
```

### Bug Description

Whenever i join theres this error in console and then it disconnects me

### Steps to Reproduce

1. Use Velocity as Proxy
2. Put ViaVersion on it
3. Try to join

### Expected Behavior

It should just let me join ._.

### Additional Server Info

I use a Velocity Proxy with ViaVersion and i also got viaversion on my subservers which are running paper 1.19.2
If i only do it on my subservers it tells me im using the wrong version, im joining with 1.19.2
If i only do it on my proxy it tells me im using the wrong version as well

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.1](https://img.shields.io/badge/Platform-velocity%203.1.1-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by Kichura** [comment]
Update your proxy, If it fails then please try moving via* to the backend servers only instead.

**Comment by LUPLUV** [comment]
Bruh, i figured it out...
