### ISSUE TITLE
Get player version returns -1

### ISSUE THREAD

**Issue by Mercenarioo** [ViaVersion/ViaVersion#3212]
### `/viaversion dump` Output

https://dump.viaversion.com/9e3a0565d5526bda3d30afdef18954ce3b9242221453df2709c239773e11b406

### Console Error

no error

### Bug Description

On PlayerJoinEvent get player version api often returns -1. I use the newest ViaVersion.

### Steps to Reproduce

1. Join with any version.
2. Sometimes api returns -1 version.

### Expected Behavior

Proper version returns.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--petal--%22cc69154%22%20%28MC%3A%201.19.2%29](https://img.shields.io/badge/Platform-git--petal--%22cc69154%22%20%28MC%3A%201.19.2%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): 3 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by Mercenarioo** [comment]
Yes I tried it, it's the same.

**Comment by MWHunter** [comment]
https://github.com/retrooper/packetevents/blob/24e8ff4fb438dfb01d03b15a2401ff5ebba42b50/spigot/src/main/java/io/github/retrooper/packetevents/util/viaversion/ViaVersionUtil.java#L67

Yeah, this is what packetevents does to hack around this.  It's annoying this is required

**Comment by MWHunter** [comment]
I've made an issue https://github.com/ViaVersion/ViaVersion/issues/3162 for this

**Comment by Camotoy** [comment]
Will close.
