### ISSUE TITLE
Problem when player Minecraft 1.7.10 join on server 1.19.3

### ISSUE THREAD

**Issue by Adrian5063** [ViaVersion/ViaVersion#3213]
### `/viaversion dump` Output

https://dump.viaversion.com/30c95839b1c81e13ed0deeaa7cf7d309bb585ab10a922e376687d1f283d5ccc6

### Console Error

https://paste.gg/p/anonymous/745d24675bf34246895273a447418e01

### Bug Description

Run Paper server version 1.19.3 and try join from client 1.7.10

### Steps to Reproduce

1. Run Paper server version 1.19.3 (Latest build)
2. Install ViaVersion, ViaBackwards and ViaRewind
3. Launch Minecraft version 1.7.10 and try join to the server

### Expected Behavior

Players 1.7.10 cannot join and error in the console

### Additional Server Info

Paper 1.19.3
ViaVersion, ViaBackwards and ViaRewind

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--384%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Paper--384%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.5.1): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 21 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-21%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by kennytv** [comment]
Update to ci builds
