### ISSUE TITLE
Client does not load chunks

### ISSUE THREAD

**Issue by caoli5288** [ViaVersion/ViaVersion#3214]
### `/viaversion dump` Output

https://dump.viaversion.com/6c2c11c32b2fb2b1f8d818d01dcd77bcd3360cd8ebae48aacbe2d8e6ec8fe3e1

### Console Error

errors not exists

### Bug Description

![screenshot_2023-02-09_12-15-43](https://user-images.githubusercontent.com/3120587/217716595-05f49326-89b0-4e1a-bce2-265bb3f559c7.png)

The client does not load the block and displays "waiting for chunk" in debug infos

### Steps to Reproduce

1. Join with pure 1.12.2(forge installed but not any mods or optifine)
2. Move
3. With any luck, you will see this bug.

### Expected Behavior

Client should load chunk

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--93e1e90%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--93e1e90%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Jo0001** [comment]
I can't reproduce this on a fresh server with just the latest ViaVersion installed
