### ISSUE TITLE
Can't login to minecraft server since version 1.7.10

### ISSUE THREAD

**Issue by Jajaja22** [ViaVersion/ViaVersion#3215]
### `/viaversion dump` Output

https://dump.viaversion.com/8703a0efa0d059171b4e51b6cf1a3b19593665a18e3b168d141e859d14ac6b06

### Console Error

```
Put the paste.gg link or text here.
```
(https://paste.gg/p/anonymous/72e3368723494222a94f9d0ba785f6b7/files/0e2b615c515b4d97978b832fc440e360/raw)

### Bug Description

When I try to log in to the minecraft server, I get the following error:
Internal Exception: io.netty.handler.codec.Encoderexception: com.view version.via version.expansion.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: PLAYER INFD, Type: Boolean, Data: (, Source de.germany
Ind. protocol.c protocol 11_7_6_10 to 1_8.packets.F layer Packets#10 (Anonymous), Packet ID: 55

### Steps to Reproduce

-

### Expected Behavior

The server should go

### Additional Server Info

version 1.19 trying to login from 1.7.10

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3563--Spigot--2183145--1e3bf58%20%28MC%3A%201.19.1%29](https://img.shields.io/badge/Platform-3563--Spigot--2183145--1e3bf58%20%28MC%3A%201.19.1%29-3498db?style=flat-square) </br>![ViaVersion (4.6.0-23w06a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.6.0--23w06a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.1): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 22 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-22%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by Jajaja22** [comment]
Why

сб, 11 февр. 2023 г., 01:04 Nassim Jahnke ***@***.***>:

**Comment by kennytv** [comment]
> Please try the latest build(s) from https://ci.viaversion.com/.
