### ISSUE TITLE
Error when running spark tps command from the game

### ISSUE THREAD

**Issue by daniel-skopek** [ViaVersion/ViaVersion#3217]
### `/viaversion dump` Output

https://dump.viaversion.com/23b3d4fe0b48e45513e3835cf864f8102312678714526f850ac2f11d352fba5c

### Console Error

https://paste.gg/p/anonymous/a9d6a89ee3ee458c80196fac81866033/files/3b4e288388c44d7b89a05257da0b8121/raw

### Bug Description

The error will appear after executing /tps command in the game. No error is sent for the player. The error will appear in the console. 

### Steps to Reproduce

1. Join to the server
2. Execute /tps command
3. The error appear in the console

### Expected Behavior

The command should work.

### Additional Server Info

I've tried it with Paper and also the latest build of ViaVersion but it didn't worked.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PandaSpigot--82%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PandaSpigot--82%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump
