### ISSUE TITLE
ViaVersion cause lag

### ISSUE THREAD

**Issue by F3F5** [ViaVersion/ViaVersion#3219]
### `/viaversion dump` Output

https://dump.viaversion.com/01f041c546a9e3a645e7b92a5a27629cc4b2936cbd7bba0f584d580a84b69961

### Console Error

.

### Bug Description

tested with no dev version, same problem
i have lags with viaversion
timings https://timings.aikar.co/dev/?id=183bedcdbe7a4083a5ec1a0cea2c1446

tested with paper normal, same issues
![image](https://user-images.githubusercontent.com/108226177/219969550-4e97760f-93ab-4e76-b5c7-5250f8c877ea.png)

### Steps to Reproduce

.

### Expected Behavior

.

### Additional Server Info

.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Dionysus--%2242ce9ca%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Dionysus--%2242ce9ca%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
Please consider educating yourself on how to read timings. This is a single task that has run twice.
