### ISSUE TITLE
Don't know how to turn {} into a Component

### ISSUE THREAD

**Issue by x1p** [ViaVersion/ViaVersion#3220]
### `/viaversion dump` Output

https://dump.viaversion.com/0b2985ddb5c1117c7ede505be4da1ec15bb98c3e8b0e83445e61d93f188cc393

### Console Error

```
No error on the console
```

### Bug Description

Since Viaversion dev build 780, the client gets rejected with this error:
![Screenshot 2023-02-22 193746](https://user-images.githubusercontent.com/28690790/220732012-fd633cde-c414-4561-adfc-b5dca57bfa50.png)

### Steps to Reproduce

1. Proxy: Waterfall build 511 with:
- Viaversion 1.19.4-pre1 build 786 (latest on this moment)
- Viabackwards 1.19.4-pre1 build 445 (latest on this moment)
4. Paper server running 1.19.3
5. Client 1.19.4pre1 tries to join
6. Gets kicked with error (see screenshot above)

Tested with different snapshot clients + appropriate via/via combinations.
1.19.3 client works fine and can join the proxy just fine.

### Expected Behavior

Join without issues

### Additional Server Info

Tested with BungeeCord, Waterfall and Paper server, all without any plugins

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Adca72c2%3A511](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Adca72c2%3A511-3498db?style=flat-square) </br>![ViaVersion (4.6.0-1.19.4-pre1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.6.0--1.19.4--pre1--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.0-1.19.4-pre1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.6.0--1.19.4--pre1--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by x1p** [comment]
https://ci.viaversion.com/job/ViaVersion-DEV/809/ Solved it for me. Hopefully it will remain so. :)
