### ISSUE TITLE
Sometimes an 'Invalid token' is thrown from the user connection

### ISSUE THREAD

**Issue by MrJoshuaT** [ViaVersion/ViaVersion#3224]
### `/viaversion dump` Output

https://dump.viaversion.com/4e4d941da541f888207618290d0293dacdc153c13e70e157ffe567bca83cbdfc

### Console Error

```
[Put the paste.gg link or text here.](https://paste.gg/p/anonymous/15f07e7895c24bffbe56bd90ffdf0406)
```

### Bug Description

Randomly a user will get disconnected from the server, with an error thrown from the UserConnectionImpl about an Invalid Token. It would seem the `passthroughTokens` is attempting to get removed more than once causing the explicit exception being thrown

### Steps to Reproduce

1. Setup ViaVersion on a Velocity server (we use 3.2.0-SNAPSHOT (git-8761d02d-b225))
2. Connect to a backend Paper server, with builders tools like FAWE and FAVS, etc (we use Paper 1.19.3)
3. Keep running commands, at some point without any specific commands, a users connection will die because of the explicit 'Invalid Token' exception

### Expected Behavior

User connection should not die randomly if a clientbound message sends multiple PASSTHROUGH_ID.

### Additional Server Info

We use Velocity proxy and all Paper backend servers. I am not sure what other details would be helpful, we have a not very complex network and have only one proxy.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--8761d02d--b225%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--8761d02d--b225%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Impactic48** [comment]
I'm getting the same issue
https://dump.viaversion.com/96199954a059d3a1820db3b0f19284b14106e57357c7cbb7883bb8fac6ab77ce
Error: https://mclo.gs/kCIVtWi

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--7da4f260--b231%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--7da4f260--b231%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.5.1): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by Impactic48** [comment]
Using latest builds:
https://dump.viaversion.com/a2ec882db0912c476055588f3a1314ffd7980f7e857975152076ccce29ababb8
Error: https://mclo.gs/4OwNNNY

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--7da4f260--b231%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--7da4f260--b231%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
I would suspect this is down to Limbo since you both have that and it's known to have conflicts with ViaVersion. I'd move ViaVersion to the backend servers instead or remove Limbo.
