### ISSUE TITLE
When a player join with the version 1.7.10 on my server 1.17.1 i have this error on my console and he kick him.

### ISSUE THREAD

**Issue by Souipi** [ViaVersion/ViaVersion#3225]
### `/viaversion dump` Output

https://paste.gg/p/anonymous/9af6bc1b0dda494c91a3d42f5e4e9d60

### Console Error

```
https://paste.gg/p/anonymous/46026464ea65476ca0b81d3083ae9e51
```

### Bug Description

I can't join.

### Steps to Reproduce

Start a server on 1.17.1
Allow all version
Start minecraft 1.7.10
And join 

### Expected Behavior

Can join ?

### Additional Server Info

Yes i have an bungeecord and i have a server before the 1.17.1 server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>
