### ISSUE TITLE
Items with "AttributeModifiers" in their NBTData get stuck in clients cursor and are not being displayed properly on Bedrock

### ISSUE THREAD

**Issue by madmobhunter** [ViaVersion/ViaVersion#3226]
### `/viaversion dump` Output

https://dump.viaversion.com/b48e6fc82d52029930a290a9be89946a16fe335fb69c413d701c57b1943d36e6

### Console Error

```
None
```

### Bug Description

Moving items with "AttributeModifiers" in their NBTData causes them to get stuck in the clients cursor.
You can only drop the item or close the inventory.
When pressing on the item to view its lore, the damage value from the "AttributeModifiers" is not being displayed properly, it only shows the vanilla value.

I also posted on geyser https://github.com/GeyserMC/Geyser/issues/3580

### Steps to Reproduce

1. Connect to the server using Minecraft Pocket Edition

2. Use the command:
`give @a diamond_axe 1 0 {AttributeModifiers:[{Slot:"mainhand", AttributeName:"generic.attack_damage", Name:"generic.attack_damage", Amount:20.0, Operation:0, UUID:[I; -192596, -61963, -161679, -10288428]}]}`
in the console to obtain an item with "AttributeModifiers"

4. Press the item to view its lore. It will not display the correct damage only the vanilla. (+6 should be +20)

5. Move item from one slot to another.

6. Item will be stuck in cursor.

After a bit of testing I found that the packet `PacketPlayInWindowClick` is sent two times when moving a item on Bedrock PE.
The first one fires `InventoryClickEvent` with `InventoryAction.PICKUP_ALL` and `ClickType.LEFT`
The second one fires `InventoryClickEvent` with `InventoryAction.PLACE_ALL` and `ClickType.LEFT`

If the item has "AttributeModifiers" the server will receive both `PacketPlayInWindowClick` packets.
The first one fires `InventoryClickEvent` `PICKUP_ALL` and picks up the item.
The second one does not fire `InventoryClickEvent` `PLACE_ALL` causing it to get stuck in the cursor.

### Expected Behavior

Items with "AttributeModifiers" should move between slots without getting stuck in the clients cursor, like ones that do not have "AttributeModifiers". They should also fire the event `InventoryClickEvent` with `InventoryAction.PLACE_ALL` and `ClickType.LEFT` when the item is placed.

Also, when pressing a item to view its lore it should display the correct damage/data from its "AttributeModifiers".

### Additional Server Info

For the proxy server:
**waterfall-1.19-511**
`Geyser-BungeeCord#1310`
`floodgate-bungee#74`

For the lobby server:
**paper-1.12.2-1620**
`ViaVersion 4.5.1` also tested with `ViaVersion-4.6.0-1.19.4-pre1-SNAPSHOT` and get same result.

No plugins other than Geyser/Floodgate on the front end, and ViaVersion on the back end.

I tested a few other version, none of the versions are displaying the correct damage value from the "AttributeModifiers".
**Versions that can move the item:**
paper-1.19.3-424
paper-1.18.2-388
paper-1.17.1-411
paper-1.16.5-794

**Versions that can NOT move the item:**
paper-1.15.2-393
paper-1.14.4-245
paper-1.13.2-657
paper-1.12.2-1620
paper-1.8.8-445

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.6.0-1.19.4-pre1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.6.0--1.19.4--pre1--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by Camotoy** [comment]
If the issue occurs only for Bedrock players and not Java 1.19.3 players, then the fault is not on ViaVersion (it doesn't know if a player is from Bedrock). Thanks for reporting anyway.
