### ISSUE TITLE
packet 0/75 (client boundsetchunk cache center packet)

### ISSUE THREAD

**Issue by haroldrc** [ViaVersion/ViaVersion#3227]
### `/viaversion dump` Output

https://dump.viaversion.com/3b70ad267facc113daef7e4b154fa8d8b16ad8a0bf517b49ff57207560c6ca2c

### Console Error

```
packet 0/75 (client boundsetchunk cache center packet) was larger than i expected, found 51 bytes extra whilist reading packet 75


```

### Bug Description

Netty update breaks the support for larger packets that aren't allowed by the server
and ViaVersion doesn't account for that and still pushes

### Steps to Reproduce

server 1.8.8
client 1.19

### Expected Behavior

be able to enter

### Additional Server Info

i also use bungeecord

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: WindSpigot%20Release%20v2.1.2%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-WindSpigot%20Release%20v2.1.2%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.6.0-1.19.4-pre2-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.6.0--1.19.4--pre2--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
Can you replicate with no plugins? I doubt this is ViaVersion related.

**Comment by HowardZHY** [comment]
Are you sure Via plugins are only running on backend servers?
