### ISSUE TITLE
Slab lighting bug was re-introduced in a recent commit

### ISSUE THREAD

**Issue by Pablete1234** [ViaVersion/ViaVersion#3229]
### `/viaversion dump` Output

https://dump.viaversion.com/f066ce3dbee83a6bc35e62d58ee8d871884e897f55b06ee98a23bf1505fc0b66

### Bug Description

The issue is the same as originally reported in #1280, which simply has come back due to recent changes, in commit https://github.com/ViaVersion/ViaVersion/commit/51d4e11b5f5b142fb99cc0267fb2e0383f45488d 

![image](https://user-images.githubusercontent.com/11789291/222936256-cdaec6d3-8212-44fc-831a-4d8c262ecb4d.png)

### Steps to Reproduce

Join with a 1.18 client on a 1.13 or below server, any slabs present will show as 0 light value.

### Expected Behavior

Slabs should be properly lit

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--SportPaper--7f91051--P.50ea0ac--SP.7b100af--CB.e1ebe52%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--SportPaper--7f91051--P.50ea0ac--SP.7b100af--CB.e1ebe52%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.6.0-23w07a-SNAPSHOT): 4 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.6.0--23w07a--SNAPSHOT)-4%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by Pablete1234** [comment]
https://dump.viaversion.com/60f0ec715cc0514f80cf10d176f9492f09a1196ad7f2c39ecb1fdeb03ebe30ce

**Comment by Barvalg** [comment]
![Platform: git--SportPaper--7f91051--P.50ea0ac--SP.7b100af--CB.e1ebe52%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--SportPaper--7f91051--P.50ea0ac--SP.7b100af--CB.e1ebe52%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.6.0-23w07a-SNAPSHOT): 4 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.6.0--23w07a--SNAPSHOT)-4%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by kennytv** [comment]
Thanks, fixed with https://github.com/ViaVersion/Mappings/commit/e7a4ace020d4aecb9f72abe21db337bd94e442ea
