### ISSUE TITLE
world_nether is not loaded

### ISSUE THREAD

**Issue by notikj** [ViaVersion/ViaVersion#3232]
### `/viaversion dump` Output

https://dump.viaversion.com/71d28cec567f31dd3223fcaff61b205441b2546c9c2db81925fe7dad453d941d

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

I have a server on version 1.12.2, via version 4.5.1
And bungeecord is enabled (this is important!)

And when I log into nether and log out of the server, and then I log on to it again, then the world just doesn't load for me. This is if on version 1.12.2.
If you go with 1.13.2, then minecraft crashes altogether.

From 1.14.4 and 1.15.2, the world is being loaded, but instead of the sky of "hell", the ordinary sky from the world with its sun shines. 

Starting from 1.16.5, everything works stably.

### Steps to Reproduce

1. Log in to the server from version 1.12.2 or 1.13.2
2. Log in to world_nether
3. Log out of the server
4. Log in to the server again

### Expected Behavior

The world does not load

### Additional Server Info

I use BungeeCord, it only works with him!

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
Try with a regular Paper server and without SkinsRestorer

**Comment by notikj** [comment]
> Try with a regular Paper server and without SkinsRestorer

If without BungeeCord then everything works fine

**Comment by Jo0001** [comment]
Do you have Via* also installed on bungee? If yes remove it from there

**Comment by notikj** [comment]
> Do you have Via* also installed on bungee? If yes remove it from there

not installed.

**Comment by Kichura** [comment]
Caused by the faulty server software, Please check if latest build of it fixes it or use normal paper.
