### ISSUE TITLE
ERROR IN Protocol1_19To1_18_2 IN REMAP OF CHAT_MESSAGE (0x0F)

### ISSUE THREAD

**Issue by corhoede** [ViaVersion/ViaVersion#3233]
### `/viaversion dump` Output

https://dump.viaversion.com/9e962de8142e8fe50ab38a1e4a1b7b1112df09b538df54e7701847593bfe6d41

### Console Error

```
lolcor33 issued server command: /sb score
[ViaVersion] ERROR IN Protocol1_19To1_18_2 IN REMAP OF CHAT_MESSAGE (0x0F)
```

### Bug Description

does not show messages from SpeedBridge v2 plugin, on the minecraft clients 1.19 and above.

### Steps to Reproduce

1. login with 1.19.2 client
2. I use the command /sb score, nothing shows up in chat.
3. appears in console: [ViaVersion] ERROR IN Protocol1_19To1_18_2 IN REMAP OF CHAT_MESSAGE (0x0F)

### Expected Behavior

Must also show Speed ​​Bridge v2 messages to 1.19 users.

### Additional Server Info

I am using git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) . 
With the following plugins:

WorldEdit version 6.1.3;7a097ca

SpeedBridge2 version 1.0.12

ViaVersion version 4.6.0-1.19.4-pre4-SNAPSHOT (I first used 4.5.2 there I had the same problem)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--445%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.6.0-1.19.4-pre4-SNAPSHOT): 5 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.6.0--1.19.4--pre4--SNAPSHOT)-5%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by FormallyMyles** [comment]
I would ensure your other plugins are up to date, I would suspect adventure is out of date in SpeedBridge
