### ISSUE TITLE
ERROR IN Protocol1_11_1To1_12 IN REMAP OF CHUNK_DATA (0x20)

### ISSUE THREAD

**Issue by 3154311518** [ViaVersion/ViaVersion#3235]
### `/viaversion dump` Output

https://dump.viaversion.com/e54051e66e5d69eaa8a8b9aeb8d86954958a61b5dbde2cb4e0fbae657f42a0f2

### Console Error

[05:40:52 WARN] [ViaVersion] ERROR IN Protocol1_11_1To1_12 IN REMAP OF CHUNK_DATA (0x20)
[05:40:52 INFO] [long_715] disconnected with: EncoderException : com.viaversion.viaversion.exception.InformativeException: Please
report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: CHUNK_DATA, Type: Chunk, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_11_1to1_12.packets.BlockI
temPackets1_12$4 (Anonymous), Packet ID: 32 @ io.netty.handler.codec.MessageToMessageEncoder:104

### Bug Description

[05:40:52 WARN] [ViaVersion] ERROR IN Protocol1_11_1To1_12 IN REMAP OF CHUNK_DATA (0x20)
[05:40:52 INFO] [long_715] disconnected with: EncoderException : com.viaversion.viaversion.exception.InformativeException: Please
report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: CHUNK_DATA, Type: Chunk, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_11_1to1_12.packets.BlockI
temPackets1_12$4 (Anonymous), Packet ID: 32 @ io.netty.handler.codec.MessageToMessageEncoder:104

### Steps to Reproduce

Using the 1.8.X client to join the Forge 1.12.2 server and entering other worlds you will be kicked out of the game, and you will not be kicked out of the Overworld

### Expected Behavior

Using a 1.8.X client to join the Forge 1.12.2 server and entering other worlds should not be kicked out of the game

### Additional Server Info

I tested the spongeforge catserver mohist as long as it is the forge server, the console will report an error

proxy: BungeeCord
plugins: ViaVersion ViaRewind ViaBackwards

Without any mods and plugins
server: spongeforge
server: catserver
server: mohist

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by FormallyMyles** [comment]
We don't support modded instances nor Mohist or Catserver.
