### ISSUE TITLE
ERROR IN Protocol1_19_1To1_19_3 IN REMAP OF SYSTEM_CHAT (0x60)

### ISSUE THREAD

**Issue by SrBedrock** [ViaVersion/ViaVersion#3237]
### `/viaversion dump` Output

https://dump.viaversion.com/6481a85b36f0630ad7e6de673268e2927ddad4a6f47a4b85d3594bded5409785

### Console Error

https://mclo.gs/UwqQ9DZ

### Bug Description

Player sends a message in the chat via the VentureChat plugin and all players are kicked off the server.

### Steps to Reproduce

1. log into server version 1.19.3
2. Install the VentureChat and InteractiveChat plugin
2. Send message in chat using version 1.19.1

### Expected Behavior

No errors occur and no players are kicked from the server

### Additional Server Info

To mitigate the problem I added version 1.19.1 in block-protocols and the error no longer occurred.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1916%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Purpur--1916%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.6.0-1.19.4-rc3-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.6.0--1.19.4--rc3--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.0-1.19.4-pre4-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.6.0--1.19.4--pre4--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by SrBedrock** [comment]
I identified the problem, how to reproduce the error:

1. Create any placeholder, for example `%placeholder_clanName%` that has the value `"clanName"` when passed through the PlaceholderAPI.
2. Use this placeholder in the chat system using VentureChat or any chat system that supports PlaceholderAPI
3. When sending the message containing this placeholder all players are kciked, it is as if ViaVersion identified the placeholder quotes as a JSON format

**Comment by kennytv** [comment]
Another plugin (most likely VentureChat) isn't applying the placeholder correctly and is procuding invalid json components
