### ISSUE TITLE
Bungeecoord error on latest

### ISSUE THREAD

**Issue by JHarris12345** [ViaVersion/ViaVersion#3238]
### `/viaversion dump` Output

https://dump.viaversion.com/d81086375a8ef62eb721fcbe33f814bd97b1e168c77a1bf86fb853e5ed0a4d54

### Console Error

```
[Put the paste.gg link or text here.](https://paste.gg/p/anonymous/9f4b1701b4154ecfbf00888b457553cf)
```

### Bug Description

When putting the latest VV on the bungee proxy, this error appears when switching servers

### Steps to Reproduce

1. Put it on a bungee server
2. Switch servers

### Expected Behavior

It shouldnt have the error

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.3.6](https://img.shields.io/badge/Platform-1.3.6-3498db?style=flat-square) </br>![Flamecord is not supported](https://img.shields.io/badge/Unsupported%20Platform%20-%20Please%20use%20Waterfall/Bungee%20instead%20or%20put%20all%20Via*%20plugins%20to%20the%20backend%20servers-orange?style=flat-square) </br>![ViaVersion (4.6.0): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.0)-Even%20with%20master-brightgreen?style=flat-square) </br>
