### ISSUE TITLE
NoSuchMethodError on startup with Paper 1.15.2

### ISSUE THREAD

**Issue by acrylic-style** [ViaVersion/ViaVersion#3239]
### `/viaversion dump` Output

N/A

### Console Error

https://paste.gg/p/anonymous/050d4edbc19a4f94829b08d1c643a226

### Bug Description

ViaVersion throws NoSuchMethodError when running on Paper 1.15.2 (as shown in <https://paste.gg/p/anonymous/050d4edbc19a4f94829b08d1c643a226>)

I also tested with Paper 1.14.4 and 1.16.5, but both are unaffected and seem to work perfectly.

### Steps to Reproduce

1. Download paper 1.15.2
2. Put ViaVersion-4.6.0.jar into the plugins folder
3. Start the server

### Expected Behavior

Load the plugin without an error

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Jo0001** [comment]
Can confirm on all 1.15.x versions

**Comment by lixfel** [comment]
Does not affect Spigot/Paper <= 1.12.2 (1.13-1.14 untested), 1.15.2 Spigot/Paper affected (1.16-1.18 untested), 1.19.3 unaffected.

**Comment by Kichura** [comment]
> Does not affect Spigot/Paper <= 1.12.2 (1.13-1.14 untested), 1.15.2 Spigot/Paper affected (1.16-1.18 untested), 1.19.3 unaffected.

I cannot produce this issue on Paper/Tuinity 1.16.5 whatsoever, Wonder if 1.16.x managed to patch this?

**Comment by lixfel** [comment]
A hacky solution of mine (try catch NoSuchMethodError) showed me that using `Yaml1Compat` instead of `Yaml2Compat` solves the issue for 1.15.2 servers.

**Comment by Kichura** [comment]
> A hacky solution of mine (try catch NoSuchMethodError) showed me that using `Yaml1Compat` instead of `Yaml2Compat` solves the issue for 1.15.2 servers.

Make a pull request then whenever possible.
