### ISSUE TITLE
1.19.4 client hotbar armor/elytra swapping applies visually only

### ISSUE THREAD

**Issue by Tisawesomeness** [ViaVersion/ViaVersion#3240]
### `/viaversion dump` Output

https://dump.viaversion.com/0cbd540217b7612a769784b8fc756035f553e6ee027309aee322e5cac6777bf9

### Bug Description

When a 1.19.4 client swaps the equipped armor with the in-hand armor by interacting, the player's inventory updates visually client-side, but the player functions as if the old armor was still equipped:

- When a falling player swaps a chestplate with an elytra and presses the jump key to fly, the player keeps falling instead of flying as expected. (see the attached video)
- When a player who is flying with an elytra swaps to a chestplate, the player keeps flying instead of falling to the ground as expected.
- When a player swaps from one chestplate to another and then relogs, the player will be wearing the original chestplate instead of the new chestplate as expected.

https://user-images.githubusercontent.com/17386338/225116982-3f681a82-d9be-4287-b2d2-45ee47d2ab0a.mp4

### Steps to Reproduce

1. Log in with a vanilla 1.19.4 client on a 1.19.3 server.
2. Clear the inventory.
3. Drag a diamond chestplate into the chestplate armor slot (slot 102).
4. Drag an elytra into the leftmost hotbar slot (slot 0).
5. Run `/data get entity @p Inventory` and notice that the output NBT is:

```
[{Slot: 0b, id: "minecraft:elytra", tag: {Damage: 0}, Count: 1b}, {Slot: 102b, id: "minecraft:diamond_chestplate", tag: {Damage: 0}, Count: 1b}]
```

6. Swap the elytra and diamond chestplate by interacting with the elytra in the hotbar.
7. Run `/data get entity @p Inventory` and notice that the output NBT is the same as before.

### Expected Behavior

Expected the elytra and diamond chestplate slots to be reversed, like below:
```
[{Slot: 0b, id: "minecraft:diamond_chestplate", tag: {Damage: 0}, Count: 1b}, {Slot: 102b, id: "minecraft:elytra", tag: {Damage: 0}, Count: 1b}]
```

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--448%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Paper--448%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.6.0): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.0)-Even%20with%20master-brightgreen?style=flat-square) </br>
