### ISSUE TITLE
ViaVersion failed to get the server protocol!

### ISSUE THREAD

**Issue by thunderlight411** [ViaVersion/ViaVersion#3241]
### `/viaversion dump` Output

https://dump.viaversion.com/4aea9fce4070ef6c43e345aa0c84c9275edb792d8a977200360a823f40f84856

### Console Error

```
https://paste.gg/p/anonymous/94ecfeb7daff4fa68aaa6606dd142b4f
```

### Bug Description

When starting the server There is a bug report that the server protocol is not recogized

### Steps to Reproduce

start server with spigot 1.19.4
Install viaVersion 

### Expected Behavior

Correct version detection

### Additional Server Info

[20:32:42] [Server thread/INFO]: This server is running CraftBukkit version 3673-Spigot-41150f3-703575f (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT)
[20:32:42] [Server thread/INFO]: Checking version, please wait...
[20:32:43] [Thread-10/INFO]: You are running the latest version

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3673--Spigot--41150f3--703575f%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-3673--Spigot--41150f3--703575f%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.6.0): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.0)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.0): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.0)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by unimatrixgit** [comment]
latest spigot build & latest viaversion & viabackwards , error persists. + console spam

**Comment by thunderlight411** [comment]
Latests spigot build gives the same error

15.03 09:10:44 [Server] Server thread/INFO This server is running CraftBukkit version 3677-Spigot-41150f3-e1fc95c (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT)
15.03 09:10:44 [Server] Server thread/INFO Checking version, please wait...
15.03 09:10:45 [Server] Thread-10/INFO You are running the latest version
