### ISSUE TITLE
Clients on 1.19.2 cannot join servers with ViaVersion 4.6.0

### ISSUE THREAD

**Issue by TheKrafter** [ViaVersion/ViaVersion#3243]
### `/viaversion dump` Output

https://dump.viaversion.com/6e258483d984aee4d97ff3f0164e6b343bac2d0657035d1ed4427c795cdd2d6b

### Bug Description

1.19.2 clients cannot join a 1.19.3 server with ViaVersion 4.6.0 installed, as well as ViaBackwards.

Tested both on Paper (git-paper-388) and Purpur (git-Purpur-1905). 

### Steps to Reproduce

1. Install ViaVersion 4.6.0 on a 1.19.x server
2. Attempt to join with a 1.19.2 client
3. Cannot Join: outdated client!

### Expected Behavior

1.19.2 clients can join 1.19.x servers with ViaBackwards, as they previously could when ViaVersion 4.5.1 was installed

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--388%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Paper--388%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.6.0): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.0)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by SinkWashy** [comment]
Am a player on a server with via, i get sent to a fallback server rather then the main server while using 1.19.2 and latest version of via

**Comment by FormallyMyles** [comment]
ViaBackwards isn't installed or isn't loading, check your console

**Comment by TheKrafter** [comment]
@FormallyMyles we have not changed our server version (in either instance), and the only thing that was changed was ViaVersion. How could ViaBackwards be at fault when it hasnt changed?
