### ISSUE TITLE
Can't join server with newest ViaVersion

### ISSUE THREAD

**Issue by Xayanix** [ViaVersion/ViaVersion#3245]
### `/viaversion dump` Output

https://dump.viaversion.com/c38aa2bf7c9c0fb1e6597b86423fbde77787963f6fd1e3ede5d23d4794795ca1

### Console Error

Error comes in BungeeCord:
```[09:38:36] [Netty Worker IO Thread #7/WARN]: [/37.225.41.82:11285|UnixejPL] <-> DownstreamBridge <-> [BoxPvP] - could not decode packet! java.lang.IllegalArgumentException: No provider for argument necraft:nbt_path
 �
	objectiveminecraft:objective�+�+�+�+�+�+pathminecraft:nbt_path�&�+destinatio```

### Bug Description

Can't join server

### Steps to Reproduce

Join on 1.16.5 

### Expected Behavior

-

### Additional Server Info

-

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--790%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--790%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.6.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Outdated!-red?style=flat-square) </br>![ViaBackwards(4.6.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.6.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump
