### ISSUE TITLE
1.19.4 commands packet mapping from 1.18.2 server

### ISSUE THREAD

**Issue by Dablakbandit** [ViaVersion/ViaVersion#3246]
### `/viaversion dump` Output

https://dump.viaversion.com/c604df854cce96122be4cc19750fa49e851bb7e0bef6ff09488fc7a4b266efed

### Console Error

[23:54:02 WARN]: [/127.0.0.1:40916|Dablakbandit] <-> DownstreamBridge <-> [lobby] - could not decode packet! java.lang.IllegalArgumentException: No provider for argument ☺�♠targets▬minecr
[23:54:02 INFO]: [Dablakbandit] disconnected with: The server you were previously on went down, you have been connected to a fallback server

### Bug Description

Joining latest paper 1.18.2 server with latest waterfall, fails with the error above.

Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)
 

### Steps to Reproduce

1. Setup Latest Waterfall + Viaversion Proxy
2. Setup Paper 1.18.2 Server
3. Attempt join with 1.19.4 client
4. Unable to join

### Expected Behavior

Be able to join the server and receive a commands packet.

### Additional Server Info

I have tracked it down the the commands packet, and might have something to do with the time argument somewhere, seems to be reading the wrong amount of bytes which messes up the next key in the command parsing.

Through some modifications to a waterfall build I got this as the output from the key printout (note the commands map had been modified with a plugin for these examples, but the error still persists without any plugins):

...
[16:51:39 INFO]: destination
[16:51:39 INFO]: location
[16:51:39 INFO]: message
[16:51:39 INFO]: time
[16:51:39 INFO]: urce_location§minecraft:all_recipes♠☻?▬?§♦timeminecraft:time☻☺?▬       objective►brigadier:string☻☻?▬?▬        objective‼m

Then another time:
could not decode packet! java.lang.IllegalArgumentException: Unhandled node type 103

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Dablakbandit** [comment]
Forgot to update dump:
https://dump.viaversion.com/0a28dd98405c290839dd6cd5f3856fde7e91968f683fd038519322fb0322ac8e

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Ab19e570%3A514](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Ab19e570%3A514-3498db?style=flat-square) </br>![ViaVersion (4.6.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
That's a Waterfall issue
