### ISSUE TITLE
1.19.4 clients can't join 1.18.2 server

### ISSUE THREAD

**Issue by Dakotaa** [ViaVersion/ViaVersion#3251]
### `/viaversion dump` Output

https://dump.viaversion.com/51c326f0f63be7297e8243480b4ec525576be9e6c94cd3ce4a31d711f8959be0

### Bug Description

1.18.2 server running the latest dev build, when 1.19.4 clients try to join, they get "Loading Terrain" for ~30s and then load into an empty world with a default skin , where proxy commands seem to work but actual server commands don't work. This was on a server where ViaVersion was the only plugin installed. console shows the player as disconnected.

Clients up to 1.19.3 can join without issue.

### Steps to Reproduce

1. 1.18.2 server
2. Try to connect with 1.19.4 client

### Expected Behavior

Being able to connect without issue

### Additional Server Info

BungeeCord proxy

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1632%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Purpur--1632%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.6.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
Would you be able to test with an actual 1.19.4 server and see if it also happens? (Setting up a new one with similar configuration to this one)

**Comment by Dakotaa** [comment]
After further testing I've found it to be an issue caused by the BungeeTabListPlus proxy plugin, which the latest dev build of that plugin fixed.

**Comment by Sakuraiina** [comment]
I updated it to version 3.6.1, but still unable to connect when using geyser(latest version).
