### ISSUE TITLE
An error occurred in metadata handler EntityPackets for untracked entity type: Metadata{id=6, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@32050906, value=0}

### ISSUE THREAD

**Issue by Overwrite987** [ViaVersion/ViaVersion#3253]
### `/viaversion dump` Output

https://dump.viaversion.com/92e4ca1c4a65c8f45a4e9d7e0effd6991a61b521d45e56e4be78c3c13d0ab066

### Console Error

https://paste.gg/p/anonymous/f8c4330e0be24d9792492f836aefdb04

### Bug Description

on the server version 1.12.2, I came across the fact that when a player logs in from version 1.19.4, a lot of errors start popping up in the console.
apparently, the main problem causing the error was the ZNPCS plugin, which creates NPCs so that it causes errors. I tried using both release and dev builds, but the result is unchanged. the new version still has this problem.
however, the plugin itself does not cause any problems when the viavershn sends multiple errors to the log, after which the server crashes from their number

### Steps to Reproduce

1) setup 1.12.2 server
2) install ZNPCs & ViaVersion
3) Create NPC with /znpcs create
4) Here ya go!

### Expected Behavior

the server should not send billions of errors С_с

### Additional Server Info

I'm using Velocity (witn bungeeguard forwarding mode)
proxy plugins:
commandwhitelist, fastmotd, hglabor_restart, limboapi, limboauth, limboauth-social-addon, limbofilter, luckperms, serverutils, skinsrestorer, velocity_tools

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Dionysus--%2242ce9ca%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Dionysus--%2242ce9ca%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.6.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.6.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Could you send an example create command where this error occurs? Please also try on a regulat Paper server

**Comment by Overwrite987** [comment]
> Could you send an example create command where this error occurs? Please also try on a regulat Paper server

I can even send a video 
here: https://drive.google.com/file/d/15hPkGemwvZ6yIhWgZNUV2FA7SWdzcYjC/view?usp=sharing
the problem turned out to be a little more serious... the problem occurs not only with the client version 1.19.4, but also with 1.19.3
With 1.18.2 everything is already becoming normal
as it turned out, you also need to hide the hologram of the NPC so that errors appear

**Comment by kennytv** [comment]
Nothing we can do here I believe, that's the plugin sending (or rather excessively spamming for some reason) metadata for untracked entities/bad metadata
