### ISSUE TITLE
Block change packets on grass are being blocked by block connections

### ISSUE THREAD

**Issue by Mercenarioo** [ViaVersion/ViaVersion#3254]
### `/viaversion dump` Output

https://dump.viaversion.com/51c326f0f63be7297e8243480b4ec525576be9e6c94cd3ce4a31d711f8959be0

### Console Error

-

### Bug Description

When you send block change packet to the grass block, block connections will update the block, even when there is no snow or no block connections to be made.

### Steps to Reproduce

Send 2 block change packets at 2 colliding grass blocks, 2nd one being sent will disappear.

### Expected Behavior

Properly working block change packets on grass.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1632%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Purpur--1632%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.6.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Your server dump is 1.18.2? Please send a dump from the server this actually happens on and from what version this behavior starts occurring

**Comment by Mercenarioo** [comment]
I think it's for all versions other than the server version, if block connections are sent to the client, the issue appears.

**Comment by FormallyMyles** [comment]
That's not very useful, providing actual information would help, e.g:
- The dump
- The version it starts happening on
- The version it stops happening on
- A video with code to show what you're doing
