### ISSUE TITLE
[Critical] The newest VV breaks servers

### ISSUE THREAD

**Issue by Mercenarioo** [ViaVersion/ViaVersion#3255]
### `/viaversion dump` Output

https://dump.viaversion.com/51c326f0f63be7297e8243480b4ec525576be9e6c94cd3ce4a31d711f8959be0

### Console Error

https://paste.gg/p/anonymous/7a5b173c439f433a86a7517a25b7ca87/files/2a82713d9bd34c2c8775b7329c010b45/raw

### Bug Description

It creates huge errors in the console and also prints weird stuff. You need to restart proxy and servers to get it fixed again. On the previous version it works normally. Also 1.19.3 and 1.19.4 players can't join the server at all.

### Steps to Reproduce

It happens on 1.8 server with any player version, happens during switching servers.

### Expected Behavior

Server working properly, please help.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1632%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Purpur--1632%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.6.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Not a Via issue

**Comment by Mercenarioo** [comment]
It is Via issue, when you upload the latest ViaVersion it happens, you need to restart proxy and put previous ViaVersion then there is no such issue.
