### ISSUE TITLE
Issue with joining

### ISSUE THREAD

**Issue by Xayanix** [ViaVersion/ViaVersion#3256]
### `/viaversion dump` Output

https://dump.viaversion.com/550f3285b8f55f38f54118adc98421899d6a8e5390ba1079c4462d26e0af6276

### Console Error

Error comes in BungeeCord:
```
[09:38:36] [Netty Worker IO Thread https://github.com/ViaVersion/ViaVersion/issues/7/WARN]: [/37.225.41.82:11285|xxx] <-> DownstreamBridge <-> [BoxPvP] - could not decode packet! java.lang.IllegalArgumentException: No provider for argument necraft:nbt_path
�
objective�minecraft:objective���+�+�+�+�+�+�path�minecraft:nbt_path���&�+�destinatio
```

### Bug Description

Joining server makes me instantly get kicked, for some reason it happens only with OP players

### Steps to Reproduce

Join with 1.16.4 

### Expected Behavior

-

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
That's a Bungee issue, update it
