### ISSUE TITLE
Can't connect to a 1.19.2 server on 1.19.2 client

### ISSUE THREAD

**Issue by Imzxhir** [ViaVersion/ViaVersion#3257]
### `/viaversion dump` Output

Not possible since I can't connect to the actual server

### Console Error

```
https://mclo.gs/Aon8Uh0
```

### Bug Description

I keep getting this error message when trying to connect to a 1.19.2 server on 1.19.2 which is weird since it should work without having to disable ViaFabric, ViaVersion and ViaBackwards.

Screenshot: 
![image](https://user-images.githubusercontent.com/98621617/225752262-9d9272da-261f-40e4-a3da-36823218a6ab.png)

### Steps to Reproduce

1. Download and launch the game with ViaFabric 0.4.9+21-main, ViaVersion 4.6.1 and ViaBackwards 4.6.1 on 1.19.2
2. Try joining a 1.19.2 server
3. You've found the bug!

### Expected Behavior

The expected behaviour is that it should allow me to join the server without issues but it doesn't for some reason. I can connect to the sever when I have: ViaFabric 0.4.9+21-main, ViaVersion 4.5.1 and ViaBackwards 4.5.1 on 1.19.2

### Additional Server Info

The server is using Purpur 1.19.2 as the server software but with no plugins.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Kichura** [comment]
> ![Error: Invalid or missing dump](https://camo.githubusercontent.com/d52699b4f8c5e7e91cb92ecd59b5aa5ed2f9eb37e741b87aa9334b5e364c0512/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4572726f722d496e76616c69642f6d697373696e6725323064756d702d7265643f7374796c653d666c61742d737175617265)

Manually checked the versions:

Both ViaBackwards and ViaVersion are on 4.6.1 - Client is Quilt 1.19.2.

**Comment by kennytv** [comment]
Most likely one of your other mods doing something bad
