### ISSUE TITLE
1.19.3. kicking from server

### ISSUE THREAD

**Issue by OlmiPl** [ViaVersion/ViaVersion#3258]
### `/viaversion dump` Output

https://dump.viaversion.com/a6408d2340404022fc6f0182c53c9688206e6aecfc2f9a08628cfc34bd91652e

### Console Error

It's dosn't say anything in console!

### Bug Description

Kicking when i try to join with 1.19.3

### Steps to Reproduce

Login with 1.19.3 dosn't work 
![obraz](https://user-images.githubusercontent.com/117110989/225753283-0ca3e695-b433-4aca-8804-425f1f3373c4.png)

### Expected Behavior

It's kicked from server 
![obraz](https://user-images.githubusercontent.com/117110989/225753335-d98ff559-a56f-4038-9552-d5fd77151bba.png)

### Additional Server Info

I use bungeecord but it's working good because i don't have viaversion on bungeecord

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--285%20%28MC%3A%201.19.2%29](https://img.shields.io/badge/Platform-git--Paper--285%20%28MC%3A%201.19.2%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.6.0)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.6.0)-Outdated!-red?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(2.0.2)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump
