### ISSUE TITLE
Kicking from 1.19.3

### ISSUE THREAD

**Issue by OlmiPl** [ViaVersion/ViaVersion#3259]
### `/viaversion dump` Output

https://dump.viaversion.com/1dbfd994f28d7b6388a94e76b12f32e3ba4eb77c6ac2cf93602689052968cfd4

### Console Error

[21:14:50 INFO]: UUID of player OLMI_PL is *
[21:14:50 INFO]: OLMI_PL has joined with olmi.pl1*[{"name".
[21:14:50 INFO]: + OLMI_PL
[21:14:50 INFO]: OLMI_PL[*] logged in with entity id 102 at ([world]-2207.5, 57.0, -325.5)
[21:14:50 INFO]: OLMI_PL lost connection: Disconnected
[21:14:50 INFO]: - OLMI_PL

### Bug Description

It's kicking when i join to server!

### Steps to Reproduce

login with 1.19.3 

### Expected Behavior

I join to server and it's kick me from it!

### Additional Server Info

I use bungeecord all informations is in ticket #3258 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--285%20%28MC%3A%201.19.2%29](https://img.shields.io/badge/Platform-git--Paper--285%20%28MC%3A%201.19.2%29-3498db?style=flat-square) </br>![ViaVersion (4.6.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by OlmiPl** [comment]
And yes i instelled new version 4.6.1 from 2 hours ago!

**Comment by OlmiPl** [comment]
It's only kicking from Feather Client

**Comment by kennytv** [comment]
Most likely featherclient doing something stupid then
