### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by ytnoos** [ViaVersion/ViaVersion#3260]
### `/viaversion dump` Output

https://dump.viaversion.com/8df5fd75635884ae61ef2490f34476caa045bb418176b6b2df7992832f3a1560

### Console Error

```
https://paste.gg/p/anonymous/6e41d88300bb4647af85188e26fb3e86
```

### Bug Description

Probably caused on interact in 1.19.4

### Steps to Reproduce

I don't know

### Expected Behavior

No error in console

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--NachoSpigot--%221e3f1c9%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--NachoSpigot--%221e3f1c9%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.6.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by AVuTuVA** [comment]
@kennytv 
![image](https://user-images.githubusercontent.com/66278054/226038729-73b71610-df06-49b7-9338-0390c1ae5cee.png)
