### ISSUE TITLE
1.19.4 clients cannot swap armor

### ISSUE THREAD

**Issue by Tisawesomeness** [ViaVersion/ViaVersion#3261]
### `/viaversion dump` Output

https://dump.viaversion.com/808f98befa6e36c0607631d5ff5c51dcf4c20a5fed2aee1b0e8db219c9434f19

### Bug Description

1.19.4 clients cannot swap armor.

https://user-images.githubusercontent.com/17386338/225930016-ac186383-00e7-4bdf-adc9-8b75d234370b.mp4

### Steps to Reproduce

1. Log in with a vanilla 1.19.4 client on a 1.19.3 server
2. Drag and drop a diamond chestplate into the chestplate slot
3. Put an elytra into your main hand
4. Try to swap the elytra and chestplate by interacting with the elytra

### Expected Behavior

Expected the diamond chestplate and elytra to swap

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
Armor swapping is a 1.19.4 feature, so it does not work on 1.19.3 servers.
