### ISSUE TITLE
Unable to connect to subserver on Velocity

### ISSUE THREAD

**Issue by LittleChest** [ViaVersion/ViaVersion#3262]
### `/viaversion dump` Output

https://dump.viaversion.com/6d41d9baaad31b7a6b90c9329a4ee607a9d161b228781661494b34040f49bf9e

### Console Error

```
https://paste.gg/p/anonymous/606808088eec4584a3056ddb4ee5a122
```

### Bug Description

When using a later version client connection, you cannot connect to the subserver.

### Steps to Reproduce

1. Install ViaVersion on Velocity
2. Connect to it
3. An error occurs on the Velocity Console and cannot connect to the subserver

### Expected Behavior

Connect normally and then enjoy the game

### Additional Server Info

Velocity version: 3.2.0
ViaVersion: 4.6.1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--01f1e1a9--b243%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--01f1e1a9--b243%29-3498db?style=flat-square) </br>![ViaVersion (4.6.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.6.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by LittleChest** [comment]
> ![Platform: velocity%203.2.0--SNAPSHOT%20%28git--01f1e1a9--b243%29](https://camo.githubusercontent.com/ab87cbe68648301ec55289a600e4134ea25479d99595170c8dd4d471ea25342a/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d76656c6f63697479253230332e322e302d2d534e415053484f542532302532386769742d2d30316631653161392d2d623234332532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.6.1): 4 commits behind master](https://camo.githubusercontent.com/019f0062e5f970897a34165bec32f804639b643e579cee104a372598cb41864a/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e362e31292d34253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaBackwards(4.6.1): Even with master](https://camo.githubusercontent.com/f0606946983faf7f0a9d54f4680c1bac7aea0dc6b7255128a8873a0717a061c1/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e362e31292d4576656e253230776974682532306d61737465722d627269676874677265656e3f7374796c653d666c61742d737175617265) Please try the **latest** build(s) from https://ci.viaversion.com/. In case the issue still persists send the new dump

It still happens on 4.6.2.
https://dump.viaversion.com/848ac9796440d16a32a21dedc028ec9ab066b5d1eaf4f8f7bdd3155266f12dc2

**Comment by Kichura** [comment]
Please check if the software continues to break on backend servers only instead.

**Comment by LittleChest** [comment]
The problem has been solved, thanks!
