### ISSUE TITLE
ViaVersion (4.6.x) completely bricks itself on Spigot 1.19.3 and lower.

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaVersion#3263]
### `/viaversion dump` Output

https://dump.viaversion.com/8994687711e3e57ed4066311f5260ccb8a04ad01685fd18150b6b301e1c7edba

### Console Error

*(No console errors, however the protocol ID shown in console is very abnormal)*

### Bug Description

When using spigot 1.19.3 or lower to run viaversion 4.6.x on the server, the protocol detection system is completely bricked and uses the chunk version instead as protocol.

### Steps to Reproduce

1. Get a copy of Spigot 1.19.3 and lower,
2. Install ViaVersion 4.6.1 onto the plugins folder,
3. Start up the server and check the detected protocol.

### Expected Behavior

Spigot 1.19.3 and lower are expected to run properly.

### Additional Server Info

Using paper instead of spigot is known to resolve this issue as a whole and doesn't cause the protocol issue. *(also; Damn you MD_5!)*

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3670--Spigot--454acb7--bd29f41%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-3670--Spigot--454acb7--bd29f41%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.6.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-Even%20with%20master-brightgreen?style=flat-square) </br>
