### ISSUE TITLE
Spigot 1.18.1 servers can't be joined for clients versions above it

### ISSUE THREAD

**Issue by Theguyhere0** [ViaVersion/ViaVersion#3264]
### `/viaversion dump` Output

https://dump.viaversion.com/ecaee13585bbdcccca939997a83946d42d2b453ecefcce8b0605e29493a7a719

### Console Error

none

### Bug Description

Clients above 1.18.1 cannot join Spigot 1.18.1 server.

### Steps to Reproduce

1. Start a Spigot 1.18.1 server with ViaVersion
2. Login with a client above 1.18.1
3. Try to join the server

### Expected Behavior

Clients above 1.18.1 should be able to join the server with ViaVersion

### Additional Server Info

I was using ViaVersion 4.5.1 when running the dump, but I tried this with 4.6.1 and it had the same issue.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3443--Spigot--699290c--2c1e499%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-3443--Spigot--699290c--2c1e499%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.5.1)-Outdated!-red?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump
