### ISSUE TITLE
Spigot 1.18.1 servers can't be joined for clients versions above it

### ISSUE THREAD

**Issue by Theguyhere0** [ViaVersion/ViaVersion#3265]
### `/viaversion dump` Output

https://dump.viaversion.com/900822f70c21af2b8f6d0732be7a09609f59e53d6d47d20d4c03e79fb232a5c7

### Console Error

None

### Bug Description

Clients above 1.18.1 cannot join Spigot 1.18.1 server.

### Steps to Reproduce

1. Start a Spigot 1.18.1 server with ViaVersion
2. Login with a client above 1.18.1
3. Try to join the server

### Expected Behavior

Clients above 1.18.1 should be able to join the server with ViaVersion

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3443--Spigot--699290c--2c1e499%20%28MC%3A%201.18.1%29](https://img.shields.io/badge/Platform-3443--Spigot--699290c--2c1e499%20%28MC%3A%201.18.1%29-3498db?style=flat-square) </br>![ViaVersion (4.6.1): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.1)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by Kichura** [comment]
Update to CI builds.

**Comment by Theguyhere0** [comment]
Ah my bad, it's good from the CI build.
