### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by ImYenil** [ViaVersion/ViaVersion#3268]
### `/viaversion dump` Output

https://pastebin.com/GSY0pL2Z

### Console Error

```
Put the paste.gg link or text here.
```
https://pastebin.com/GSY0pL2Z

### Bug Description

Error when using /viaversion dump command

### Steps to Reproduce

use /viaversion dump
and get issue

### Expected Behavior

X

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Update to ViaVersion from https://ci.viaversion.com/
