### ISSUE TITLE
Glass Pane Blockconnections not working on MC 1.12.2 or 1.8.9 servers since VV 4.6.0 update

### ISSUE THREAD

**Issue by IgnitingIce** [ViaVersion/ViaVersion#3269]
### `/viaversion dump` Output

https://dump.viaversion.com/1b88e6ba7759dae6cf3ff4a330987ca831946eb3ad0a8b811134df9869da9449

### Console Error

N/A

### Bug Description

Block connections of glass panes and iron bars no longer work as expected.
Tested on paper 1.12.2 and 1.8.9 using any client version 1.13 or above.

In both screenshots, the configuration is the same as the dump:
- serverside-blockconnections: true
- blockconnection-method: packet
- reduce-blockstorage-memory: false

**ViaVersion 4.6.2 on MC 1.19.4**
![vv 4 6 2](https://user-images.githubusercontent.com/15795294/226213788-6080a269-3e81-436e-8e13-1f903cdbc2cd.png)

### Steps to Reproduce

1. Run latest ViaVersion on an MC 1.8 or 1.12 server.
2. Login on any client 1.13 or above.
3. Place varied types of panes and bars together.
4. Observe block connections behaving erratically / incorrectly.

### Expected Behavior

Panes and bars should connect properly as they did on ViaVersion 4.5.1.

**ViaVersion 4.5.1 on MC 1.19.3**
![vv 4 5 1](https://user-images.githubusercontent.com/15795294/226213885-222b626e-5440-4946-8b64-ce3bbd02fdbb.png)

### Additional Server Info

Running a minimal Velocity proxy w/ Votifier and a core plugin for punishments, friends, etc.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--%224b4e8f191%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--%224b4e8f191%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.6.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.6.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
