### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by DexterSK** [ViaVersion/ViaVersion#3270]
### `/viaversion dump` Output

https://dump.viaversion.com/cb8bfcecae558db75271a087c4bf627469584e2108bbf9545db02a2124a29898

### Console Error

[06:39:23 ERROR]: [ViaVersion] An error occurred in metadata handler EntityPackets1_18 for untracked entity type: Metadata{id=19, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@1d907d94, value=3}
[06:39:23 ERROR]: [ViaVersion] Full metadata: Metadata{id=2, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@70436e37, value={"italic":false,"color":"white","text":"Fungi Bulb"}}
Metadata{id=4, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@6e176b69, value=true}
Metadata{id=9, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@47d09c6d, value=1098.9}
Metadata{id=19, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@1d907d94, value=3}
[06:39:23 WARN]: java.lang.ArrayIndexOutOfBoundsException

### Bug Description

Idk but i know user uses 1.16

### Steps to Reproduce

idk

### Expected Behavior

idk

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1894%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Purpur--1894%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.6.1): 10 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.1)-10%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.6.0)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
