### ISSUE TITLE
1.19.4 client cannot join 1.19.4 server

### ISSUE THREAD

**Issue by NetheriteTree** [ViaVersion/ViaVersion#3271]
### `/viaversion dump` Output

https://dump.viaversion.com/c418c1f98ed9cef0b0a2380ab5d36ef803e9ac831e5e94ac9db0920ba1fe1ff5

### Console Error

no error

### Bug Description

1.19.4 clients cannot join 1.19.4 servers, while 1.19.3 and lower can join normally
and the client shows this:
![image](https://user-images.githubusercontent.com/47891648/226643311-ee07eb84-46b4-4528-af5a-01c24e7c38d1.png)

### Steps to Reproduce

1. install Viaversion on paper 1.19.4
2. login in with 1.19.4 client

### Expected Behavior

1.19.4 client can join 1.19.4 server normally

### Additional Server Info

via plugins are only on backend servers
paper 1.19.4 #466

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--466%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--466%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.6.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.6.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
