### ISSUE TITLE
Cannot to connect server

### ISSUE THREAD

**Issue by kevin126ckw** [ViaVersion/ViaVersion#3274]
### `/viaversion dump` Output

[21:58:33 INFO]: Unknown command. Type "help" for help.[m

### Console Error

![a_big_bug](https://user-images.githubusercontent.com/108781948/227721828-872c763b-5fd6-4b00-86f0-009d5a575d4d.png)

### Bug Description

![a_big_bug](https://user-images.githubusercontent.com/108781948/227721856-fd81edc7-58cd-4b5f-81dd-0951e50dee5b.png)

### Steps to Reproduce

Use the Minecraft 1.19.3 client (with a forge that doesn't add any mods) to the server using mohist without adding any mods. 
2. Prompt errors in screenshots

### Expected Behavior

The client should not prompt an error。

### Additional Server Info

The server has Plugins used: full line of EssentialsX, ColorMOTD, Geyser-spigot, SkinsRestorer, full line of ViaVersion, worldedit.
The server is not a Villana server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Mohist isn't supported

**Comment by kevin126ckw** [comment]
Thank you members of the ViaVersion team, I followed your approach to solve this problem.
