### ISSUE TITLE
1.19 in 1.8 server block interaction problems

### ISSUE THREAD

**Issue by Coquettishpig** [ViaVersion/ViaVersion#3275]
### `/viaversion dump` Output

https://dump.viaversion.com/eb8813546c0e38555362eb73f052ca2e303cd02a984c7a6caee7e8562b16aaf5

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

I mean placing the square in front of yourself, not at your feet, right-clicking and then pressing space to place it quickly will result in placing a square on your head, and if you click fast enough, it will even turn into a swimming stance.
![image](https://user-images.githubusercontent.com/107100449/227767957-291085b0-a313-44c0-af94-8a1e382a736b.png)
https://cdn.discordapp.com/attachments/316208160232701955/1089485133805015090/1679823884859.mp4

### Steps to Reproduce

1.use 1.19 client in 1.8 server
2.fast place block

### Expected Behavior

none

### Additional Server Info

 * MultiWorld [5.2.6]
 * FastAsyncWorldEdit [21.03.26-5ff3a9b-1286-22.3.9]
 * PlaceholderAPI [2.11.3]
 * ServerTeleport [1.3.0]
 * ViaVersion [4.6.2]
 * ServersNPC [4.0]
 * ProtocolLib [5.0.0-SNAPSHOT-b616]
 * TheBridge [1.1.4-dev6]
 * LuckPerms [5.4.67]
 * WorldEdit [6.1.7;dd00bb1]
 * DecentHolograms [2.8.1]
 * TAB [3.3.1]
 * LiteBans [2.11.1]

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: MoeCore--95ee73c%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-MoeCore--95ee73c%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.6.2): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.2)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
https://github.com/ViaVersion/ViaVersion/issues/1087

**Comment by Coquettishpig** [comment]
> #1087

I don't think the problem is the same

**Comment by Coquettishpig** [comment]
> #1087

Please check out my video, first.
