### ISSUE TITLE
Error occurred in metadata handler EntityPackets for untracked entity type

### ISSUE THREAD

**Issue by andrewkm** [ViaVersion/ViaVersion#3277]
### `/viaversion dump` Output

https://dump.viaversion.com/abb6900b8d6957f1be1abbd77ebf0f462660db11dcfbf9f9fe88fea16dd41f05

### Console Error

https://pastebin.com/XDEvJZy2

### Bug Description

Errors happen on 1.12.2 server.

### Steps to Reproduce

Errors happen on 1.12.2 server.

### Expected Behavior

No error.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0-23w12a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.7.0--23w12a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.0-23w12a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.7.0--23w12a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by andrewkm** [comment]
Still getting this constantly, quite heavily as well.

**Comment by Kichura** [comment]
A third-party plugin is sending bad metadata to the server, please perform a binary search on what causes via* to panic.

**Comment by notikj** [comment]
Exactly the same problem

**Comment by andrewkm** [comment]
> A third-party plugin is sending bad metadata to the server, please perform a binary search on what causes via* to panic.

Not necessarily possible easily due to no immediate reproduction steps, and the fact it's random, heavy at times, other times not so much.

**Comment by FormallyMyles** [comment]
Basically the answer Kichura wrote, you can ignore this but viaversion can't translate entity data that doesn't have a spawn entity packet.
