### ISSUE TITLE
ERROR IN Protocol1_19_3To1_19_4 IN REMAP OF JOIN_GAME (0x28)

### ISSUE THREAD

**Issue by KioProject123** [ViaVersion/ViaVersion#3278]
### `/viaversion dump` Output

https://dump.viaversion.com/bda9a30a26f1b613c57f7399bb4d01eda9fc8854b53a8aca868a33ee4625694d

### Console Error

```
https://paste.gg/p/anonymous/bb4378ba40e64d89b8a3dee69a7c2459
```

### Bug Description

Send players to the NanoLimbo server during the PlayerChooseInitialServerEvent stage.
The player was not sent to the NanoLimbo server, but was sent to the default server.

There were no errors using the 1.19.4 client, but this error occurred on the 1.19.3 client.

### Steps to Reproduce

1. Using 1.19.3 client.
2. Use the following code in the Velocity plugin to send players to the NanoLimbo server
```
    @Subscribe(order = PostOrder.FIRST)
    public void onPlayerChooseInitialServer(final PlayerChooseInitialServerEvent e) {
        MyPlugin.server.getServer("limbo").ifPresent(server -> e.setInitialServer(server));
    }
```

### Expected Behavior

Players are sent to the NanoLimbo server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--c7ba5255--b244%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--c7ba5255--b244%29-3498db?style=flat-square) </br>![Proxy is 1 builds behind](https://img.shields.io/badge/Your%20proxy%20is%201%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.6.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.6.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by KioProject123** [comment]
This is fixed when register-userconnections-on-join is set to true
