### ISSUE TITLE
Internal Exception: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template {Sourse 0: com.viaversion.viabackwards.protocol.protocol1_15_2to1_16.packets.blockItemPackets1_16$4 (Anonymous)} Actual Error

### ISSUE THREAD

**Issue by awweqq** [ViaVersion/ViaVersion#3279]
### `/viaversion dump` Output

1

### Console Error

```
Put the paste.gg link or text here.
```
1

### Bug Description

1

### Steps to Reproduce

1

### Expected Behavior

2

### Additional Server Info

1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
0
