### ISSUE TITLE
Write is being transformed into writeAndFlush

### ISSUE THREAD

**Issue by michaello01** [ViaVersion/ViaVersion#3282]
### `/viaversion dump` Output

https://dump.viaversion.com/71d28cec567f31dd3223fcaff61b205441b2546c9c2db81925fe7dad453d941d

### Console Error

Method io.netty.channel.AbstractChannel.write() is transformed into io.netty.channel.AbstractChannelHandlerContext.writeAndFlush()
from com.viaversion.viaversion.connection.UserConnectionImpl.sendRawPacket()
I think it would be good to keep the original behaviour, is it possible?

### Bug Description

.

### Steps to Reproduce

.

### Expected Behavior

.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Dionysus--%22933534d%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Dionysus--%22933534d%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.5.1)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
