### ISSUE TITLE
Death message on chat not localized when joining 1.12 server with 1.13+ client in 4.6.2

### ISSUE THREAD

**Issue by sandtechnology** [ViaVersion/ViaVersion#3284]
### `/viaversion dump` Output

https://dump.viaversion.com/e72218743e9c3a4fefee492078646e05bb09eb37293c5a20c36f63da5e8a810e

### Bug Description

When joining 1.12.2 server with 1.13+ clients, the death message on chat was always stick on en_us instead of current client language, and rolling back to 4.6.1 seems fine.
![image](https://user-images.githubusercontent.com/20417547/229267628-358227a9-ba08-4ea4-b931-3b0193026033.png)
It seems caused by https://github.com/ViaVersion/ViaVersion/commit/9ccc3aed3086118cc0b6a01bf0c33753fc42b11d I think?

### Steps to Reproduce

1.Login to 1.12 server with 1.13+ client using language other than en_us
2.Making something that will cause death
3.See the death message on chat not localized.

### Expected Behavior

The death message on chat was localized based on client language.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.6.2): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.2)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by sandtechnology** [comment]
> ![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://camo.githubusercontent.com/8846153c539ab6590c2121e5fb32c7ff693a1cf35b9dc9562b3b8621c588d142/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d50617065722d2d313632302532302532384d43253341253230312e31322e322532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.6.2): 3 commits behind master](https://camo.githubusercontent.com/a76c138680f56a811d82fdf0a02af91243d2d11c51ea6c58404ea874eb7619ae/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e362e32292d33253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265)
> ### Please try the **latest** build(s) from https://ci.viaversion.com/. In case the issue still persists send the new dump

https://dump.viaversion.com/e72218743e9c3a4fefee492078646e05bb09eb37293c5a20c36f63da5e8a810e
Still persist
![image](https://user-images.githubusercontent.com/20417547/229267903-f1e3f4a7-8fad-44ca-9238-662f6403aa66.png)

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.6.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
