### ISSUE TITLE
Players on versions lower than 1.18 cannot join to a server that has engine version (paper spigot)  1.19.4 and the latest via package.

### ISSUE THREAD

**Issue by ZanderPL** [ViaVersion/ViaVersion#3285]
### `/viaversion dump` Output

No able. The network is close for connections with outside.

### Console Error

https://paste.gg/p/anonymous/4bee43b8138449e981b131b3726dba72

### Bug Description

The problem with joining to 1.19.4 server with versions below 1.18etc.. All connections are rejected.

### Steps to Reproduce

1. The player is trying to join the server in the lobby using example 1.16 version (Probably all versions under 1.18)
2. When the player is trying to join the server his connection is dropped with the title: "The server you were previosuly on went down you have been connected to a fallback server.

### Expected Behavior

fix the issue.

### Additional Server Info

The network with waterfall. The server is running on the newest paper spigot version and the newest pack of via family...

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
We cannot help you without a server dump. If you need any further assistance, join our Discord.
