### ISSUE TITLE
Viaversion sometimes hangs when disable

### ISSUE THREAD

**Issue by aaa8881** [ViaVersion/ViaVersion#3288]
### `/viaversion dump` Output

-

### Console Error

`/viaversion dump`` fails due to java.net.unknownHostException
-> probably because current Host blocks foreign ip except whitelisted ones. 

### Bug Description

```
[06:00:23] [Server thread/INFO]: [ViaVersion] Disabling ViaVersion v4.6.2
[06:00:23] [Server thread/INFO]: [ViaVersion] ViaVersion is disabling, if this is a reload and you experience issues consider rebooting.

and hangs forever
```

update checker is disabled.

jstack thread dump when hung.
https://pastebin.com/m5ycVde0

### Steps to Reproduce

not sure. sometimes happen

### Expected Behavior

disable plugin correctly 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
Are you sure this is actually viaversion related as surely one of the waiting threads would be related to the plugin?

**Comment by aaa8881** [comment]
1. no I'm not sure, it's viaversion. what is sure is it happened around 10 times so far from 4.6.1 , and it always hung with this as last line
```
[Server thread/INFO]: [ViaVersion] ViaVersion is disabling, if this is a reload and you experience issues consider rebooting.
```
no exception.


2. yes I'm sure it is hung , not just waiting for other plugins. first time I found this out is it hung for 5 hours . not different in other times as well.

**Comment by FormallyMyles** [comment]
That message unfortunately isn't an indicator of it being the cause, it just means viaversion called the disable method. I can't see any references to via in your dump (and we do name our task schedulers).

I would first downgrade viaversion if you're able to and test whether it is indeed a regression, because I'd put more on it being down to either world related saving or one of your db threads.

Attaching a profiler to debug while it is stuck might also be useful to see if you can run deadlock detection

**Comment by aaa8881** [comment]
probably can't downgrade. 
How do I attach profiler? What should I use?

**Comment by aaa8881** [comment]
this is from mysql holds leaked connection , and were investigating. 
not sure which plugins are causing, but issue is obvious.
closing. not relevant to Viaversion sorry.
