### ISSUE TITLE
Server returns an error once I join then kicks me off

### ISSUE THREAD

**Issue by senorkal** [ViaVersion/ViaVersion#3290]
### `/viaversion dump` Output

https://dump.viaversion.com/618086c2bd8124e52fc82021dbebdac9fdf23c2987b5f50d56ee8848cb136dce

### Console Error

[Logs after joining](https://mclo.gs/3GGM5QC)

### Bug Description

Once I get loaded into the server, I get kicked off back to the lobby, and a shortened version of the error appears in chat. It started when I teleported 'item' entities to myself, it kicked me and gave me the error.

### Steps to Reproduce

- Contact Minehut to stop re-installing ViaVersion in their servers.
- Provide a fix by updating the code somehow
- Provide me with other information that I wouldn't be able to know

### Expected Behavior

I should be able to join the server like everytime

### Additional Server Info

Server is run by Minehut, I am aware Minehut re-installs their own ViaVersion but I just need to know if this is an issue you can fix or if I need to contact Minehut themselves about this issue. Otherwise, I don't use a proxy and here are the current plugins:
- [Inventory Rollback Plus](https://www.spigotmc.org/resources/inventory-rollback-plus-1-8-1-19-x.85811/)
- [Invsee++](https://www.spigotmc.org/resources/invsee.82342/)
- [Vault](https://dev.bukkit.org/projects/vault)
- ViaBackwards (Tried 4.6.1 and 4.6.2)

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--466%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--466%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.6.2): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.2)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.6.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.6.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
You have an item with bad metadata, but fixed here anyways: https://github.com/ViaVersion/ViaBackwards/commit/483920b7293a4ecf4c75d708b80a571f9ed863f0
