### ISSUE TITLE
Error when connecting with geysermc

### ISSUE THREAD

**Issue by BainBan** [ViaVersion/ViaVersion#3291]
### `/viaversion dump` Output

https://dump.viaversion.com/033a868711abcb6d06a58e3f72e50b0b8df5a00cbe58826e87d1d7bf87faa9b2

### Console Error

```
com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.packets.EntityPackets$6 (Anonymous), Source 1: com.viaversion.viaversion.protocols.protocol1_14to1_13_2.packets.WorldPackets$9 (Anonymous) @ io.netty.handler.codec.MessageToMessageEncoder:107
```

### Bug Description

when trying to join with geysermc this happens. However on Java it's fine

### Steps to Reproduce

1. Login with bedrock 1.19.60
2. Join server

### Expected Behavior

Connect me on the server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Ae0a029e%3A520](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Ae0a029e%3A520-3498db?style=flat-square) </br>![ViaVersion (4.7.0-23w14a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.7.0--23w14a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
Have you tried without other bungee plugins? (Excluding geyser ones)
