### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by WarnDa** [ViaVersion/ViaVersion#3292]
### `/viaversion dump` Output

https://dump.viaversion.com/bbe4269e2d88e938d885a2120060369f5cd08fc17c3a98a7eeaf3769749738a8

### Console Error

https://paste.gg/p/anonymous/a5e326c5ae1b42b6b4075c4973ca9977

### Bug Description

I just saw this in logs, idk what happened before

### Steps to Reproduce

/

### Expected Behavior

/

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PufferfishPlus--44%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--PufferfishPlus--44%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0-23w13a-SNAPSHOT): 1 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.7.0--23w13a--SNAPSHOT)-1%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards(4.7.0-23w13a-SNAPSHOT): 1 commits behind dev](https://img.shields.io/badge/ViaBackwards%20(4.7.0--23w13a--SNAPSHOT)-1%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by WarnDa** [comment]
Latest commit just add new snapshot compatibility, useless in my case

**Comment by Jo0001** [comment]
Does the error still occur with the latest 4.7.1-Snapshot builds?

**Comment by WarnDa** [comment]
> Does the error still occur with the latest 4.7.1-Snapshot builds?

Nop I saw the error only once, so it can be closed if you can't find the reason
