### ISSUE TITLE
Head disappears when placing it in WorldGuard region

### ISSUE THREAD

**Issue by PapiCapi** [ViaVersion/ViaVersion#3293]
### `/viaversion dump` Output

https://dump.viaversion.com/0505298c8fb38348b4413a75cb0a5acc05a7816ba2201a6cd7a8289abc0fcc76

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

On a 1.19.3 server (running paper) if a player in 1.19.4 tries to place a head in a region where he can't build, the head will not go back to his inventory and will simply disappear.
A player on 1.19.3 does not have this issue.

### Steps to Reproduce

- Create a server with WorldGuard and ViaVersion in 1.19.3
- Create a region where you can't build
- Try to place a custom head, for example : 
`minecraft:player_head{AttributeModifiers:[{Amount:3.0d,AttributeName:"minecraft:generic.armor",Name:"generic.armor",Operation:0,Slot:"head",UUID:[I;-1283794754,1453672504,-1838490771,-344182106]}],Enchantments:[{id:"minecraft:protection",lvl:2s}],SkullOwner:{Id:[I;-210731296,698174069,-1539971553,-1760668898],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTM1ODIzMzcxMDgxODIxMmMwMTNhMTEwMzk4NTI0MjUzYzVkOTQ5ZjUwZmIwOTljOTUxZDBjYjNiNDEwZWRmZiJ9fX0="}]}},display:{Lore:['{"text":"Poussin aujourd\'hui, mais poulet demain !","color":"#FF4DE7","italic":false}','{"text":"Des oeufs à volonté à portée de main !","color":"#FF4DE7","italic":false}','{"text":"Event Pâques 2021","color":"green","italic":false}','[{"text":""},{"text":"» Regeneration ","color":"gray","italic":false},{"text":"» ","color":"gray","italic":false},{"text":"I","color":"red","italic":false}]'],Name:'{"text":"Mon p\'tit poussin ❤","color":"#FFEF0F","italic":false}'}}`

- The placement should be cancelled 
- Using a 1.19.3 client, you get the head back in your inventory but not in 1.19.4

### Expected Behavior

The head placed should go back on the player's inventory.

### Additional Server Info

The server is behind a waterfall proxy.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--393%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Paper--393%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.6.2): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.2)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.6.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by PapiCapi** [comment]
Just re-tested with the newer builds ( https://dump.viaversion.com/ab3ee09c593efd765bddcf9465051d72344cfdbd5c22c0a79a0f39eb1f58e2a4 ) and i have exactly the same issue

**Comment by Barvalg** [comment]
![Platform: git--Paper--393%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Paper--393%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.6.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.6.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by SuprexDE** [comment]
Hey, i have the same issue but we not use worldguard

**Comment by Kichura** [comment]
Cannot reproduce, this is likely caused by a third-party plugin cancelling out head returnings to inventories.
