### ISSUE TITLE
metadata handler EntityPackets for untracked entity

### ISSUE THREAD

**Issue by F3F5** [ViaVersion/ViaVersion#3294]
### `/viaversion dump` Output

https://dump.viaversion.com/5f4b55079feaa15dac0c7f724283cc550e8f88c5c8e39ee10bb6402563cc7b0f

### Console Error

https://pastes.dev/Qb5MQeLJyb

### Bug Description

https://pastes.dev/Qb5MQeLJyb

### Steps to Reproduce

.

### Expected Behavior

.

### Additional Server Info

.

### Checklist

- [ ] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [ ] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Dionysus--a87ca7a%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Dionysus--a87ca7a%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.6.2): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.2)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3): 2 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.3)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.6.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by FormallyMyles** [comment]
Likely a hologram or manually spawned entity being sent without spawn data. I'd test through your plugins.

**Comment by F3F5** [comment]
> Likely a hologram or manually spawned entity being sent without spawn data. I'd test through your plugins.

i tested with a test server.only have protocollib and via

**Comment by FormallyMyles** [comment]
> > Likely a hologram or manually spawned entity being sent without spawn data. I'd test through your plugins.
> 
> i tested with a test server.only have protocollib and via

Have you tried without protocollib and with normal Paper?

**Comment by F3F5** [comment]
> > > Likely a hologram or manually spawned entity being sent without spawn data. I'd test through your plugins.
> > 
> > 
> > i tested with a test server.only have protocollib and via
> 
> Have you tried without protocollib and with normal Paper?

yes. and tested on other hosting too(server.pro)

**Comment by FormallyMyles** [comment]
> > > > Likely a hologram or manually spawned entity being sent without spawn data. I'd test through your plugins.
> > > 
> > > 
> > > i tested with a test server.only have protocollib and via
> > 
> > 
> > Have you tried without protocollib and with normal Paper?
> 
> yes. and tested on other hosting too(server.pro)

Do you have steps for replication? If so can you add them to the original issue.

**Comment by FormallyMyles** [comment]
Can you also add the error + the dump for a server with no plugins so we have that for tracking.

**Comment by F3F5** [comment]
> Can you also add the error + the dump for a server with no plugins so we have that for tracking.

error only when adding protocollib. papermc 1.12.2 and last on spigot via,protocol

**Comment by FormallyMyles** [comment]
> > Can you also add the error + the dump for a server with no plugins so we have that for tracking.
> 
> error only when adding protocollib. papermc 1.12.2 and last on spigot via,protocol

If it happens with protocollib it is unlikely a viaversion issue, you can ignore the error. ViaVersion can't translate entities when the data arrives with no spawn packet to determine the type.

**Comment by F3F5** [comment]
> > > Can you also add the error + the dump for a server with no plugins so we have that for tracking.
> > 
> > 
> > error only when adding protocollib. papermc 1.12.2 and last on spigot via,protocol
> 
> If it happens with protocollib it is unlikely a viaversion issue, you can ignore the error. ViaVersion can't translate entities when the data arrives with no spawn packet to determine the type.

maybe you can test?

**Comment by F3F5** [comment]
version via 4.6.1 works with protocollib

**Comment by F3F5** [comment]
> > > Can you also add the error + the dump for a server with no plugins so we have that for tracking.
> > 
> > 
> > error only when adding protocollib. papermc 1.12.2 and last on spigot via,protocol
> 
> If it happens with protocollib it is unlikely a viaversion issue, you can ignore the error. ViaVersion can't translate entities when the data arrives with no spawn packet to determine the type.

https://paste.gg/p/anonymous/fba5187f8d31461eaaa5f4a2ae4682f0
