### ISSUE TITLE
hex color not working!

### ISSUE THREAD

**Issue by OlmiPl** [ViaVersion/ViaVersion#3297]
### `/viaversion dump` Output

https://dump.viaversion.com/0f68ba36b2c0c9f5d852d4de1e362fbeab3cc51452f3c3b8fccf942a61e50d1a

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Hex colors not working is set to white!

### Steps to Reproduce

Look at the tab-scoreboard

### Expected Behavior

Hex colors not working is set to white!

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--182%20%28MC%3A%201.19.2%29](https://img.shields.io/badge/Platform-git--Paper--182%20%28MC%3A%201.19.2%29-3498db?style=flat-square) </br>![ViaVersion (4.6.2): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.2)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3): 2 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.3)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.6.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
Hex colors don't exist in older versions
