### ISSUE TITLE
WHEN I JOIN MY SERVER THEN THAT SHOW

### ISSUE THREAD

**Issue by 90507** [ViaVersion/ViaVersion#3300]
### Problem Description

![Screenshot_20230419-152610](https://user-images.githubusercontent.com/131257892/233050803-cf0b40b4-ab32-4f5e-8d87-3a95c57fb4b0.png)

### Solution Description

Plss fix it

**Comment by FormallyMyles** [comment]
Fill in the bug report template https://github.com/ViaVersion/ViaVersion/issues/new?assignees=&labels=Unconfirmed&template=bug_report.yml
