### ISSUE TITLE
1.9 Protocol doesn't work at all

### ISSUE THREAD

**Issue by FlorianMichael** [ViaVersion/ViaVersion#3305]
### `/viaversion dump` Output

https://dump.viaversion.com/9053ef4899496a52a5bddeb1abe86f24d2cc47b8268683c1114be59229910fa0

### Console Error

```
https://paste.gg/p/anonymous/72738676b20745b78e9ff6d4b0504c64
```
Message on the client:
![2023-04-24_17 10 55](https://user-images.githubusercontent.com/60033407/234039106-23e6c7e6-b39f-4f35-bcbc-8916c942e192.png)

### Bug Description

Joining an 1.9 Server using any Clientside ViaVersion implementation (Tested with ViaFabric, ViaFabricPlus and ViaProxy) will cause this exception from above.
See also: https://github.com/FlorianMichael/ViaFabricPlus/issues/67

### Steps to Reproduce

1. Install ViaFabric or any other Via Impl for clients
2. Join a 1.9 server
3. You will get the crash message

### Expected Behavior

Joining should work

### Additional Server Info

ServerSoftware: Vanilla Server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.4.10+33--dev](https://img.shields.io/badge/Platform-0.4.10+33--dev-3498db?style=flat-square) </br>![ViaVersion (4.7.0-23w14a-SNAPSHOT): 10 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.7.0--23w14a--SNAPSHOT)-10%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by FlorianMichael** [comment]
https://dump.viaversion.com/80e9067a9b92c6804d8ab549a5d02ae56b844a257ba7b720d0665c8cde6137de

**Comment by Barvalg** [comment]
![Platform: 0.4.10+33--dev](https://img.shields.io/badge/Platform-0.4.10+33--dev-3498db?style=flat-square) </br>![ViaVersion (4.7.0-23w16a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.7.0--23w16a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
It still happens

**Comment by Kichura** [comment]
Yeah 1.9.x, 1.10.x, 1.11.x and 1.13.x all four are known for causing weird things when using viafabric to join them from newer client, But using 1.12.x and 1.14.x does resolve the problem to some extent.

**Comment by FlorianMichael** [comment]
![image](https://user-images.githubusercontent.com/60033407/234058411-17ab1a7d-5bb5-4360-98c5-ca7abdc463c2.png)
Minecraft changed a read call in the DataTracker from 1.9 (Unsigned Byte) to 1.9.1 (Var Int)

**Comment by FlorianMichael** [comment]
Fixed with https://github.com/ViaVersion/ViaVersion/pull/3495
