### ISSUE TITLE
music discs don't stop playing

### ISSUE THREAD

**Issue by onebeastchris** [ViaVersion/ViaVersion#3307]
### `/viaversion dump` Output

 https://dump.viaversion.com/b83522fe604a2c5d1a45745eb198cd28c26a63ba8451b3ea9c233b219e1ead6c

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Hey!
With 1.19.3 (or older) backend servers, music discs in jukeboxes dont stop playing after they are ejected for 1.19.4 clients.

reason: since 1.19.4, the music disc playing stop is a dedicated LevelEvent, instead of the hacky workaround with sending a disk that sent a SoundEvent.STOP_RECORD.

### Steps to Reproduce

1. use 1.19.3 (or older) server
2. join with 1.19.4 using vv
3. let a music disc play
4. remove disc from jukebox, music doesn't stop

### Expected Behavior

please do stop the music

### Additional Server Info

velocity + fabric backends, via being on the proxy

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--e364e2c7--b250%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--e364e2c7--b250%29-3498db?style=flat-square) </br>![Proxy is 2 builds behind](https://img.shields.io/badge/Your%20proxy%20is%202%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.6.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>
