### ISSUE TITLE
java.lang.UnsupportedOperationException: null in Folia 1.19.4

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [ViaVersion/ViaVersion#3312]
### `/viaversion dump` Output

ViaVersion v4.6.2

### Console Error

```
https://paste.ubuntu.com/p/Qw9y5NJzNm/
```

### Bug Description

in folia 1.19.4, viaVersion cannot work on it

### Steps to Reproduce

1.turn on your server
2.boom!

### Expected Behavior

Via should work on it

### Additional Server Info

none

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Update to ci builds
