### ISSUE TITLE
Can't enter JE 1.16.5 Fabric Server(Velocity Proxied) Using BE v1.19.81 with latest Velocity, Geyser, and ViaVersion SNAPSHOTs

### ISSUE THREAD

**Issue by Na3MnO4** [ViaVersion/ViaVersion#3313]
### `/viaversion dump` Output

https://dump.viaversion.com/5122f2a16948086b363aed6a347f622ac07c6b32f53adfc29d81fa6ccf283176

### Console Error

```
https://paste.gg/p/anonymous/2ce31e37d5d547a7aa444cdca792d96d
and below there are still much more similar lines, I'd ignore it for its too long
![image](https://user-images.githubusercontent.com/69727714/236544139-ddad6df2-d7c5-4f06-bdb0-5b7e2df2b5da.png)
https://paste.gg/p/anonymous/8631301d8692410293a62304c9c3be53
```

### Bug Description

immediately after signing in the geyser, the error occurred, for in the log, it said "[02:35:54] [Netty NIO Worker #24/ERROR] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] AmethystineENDzZ -> lobby: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@4aafd12e
io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository", I came here to report this issue, hope it could be fixed.

### Steps to Reproduce

1. Put geyser 2.1.0-SNAPSHOT, viaversion 4.6.3-SNAPSHOT, viabackwards 4.6.2-SNAPSHOT, viarewind 2.0.4-SNAPSHOT in the plugin dictionary of Velocity 3.2.0-SNAPSHOT(or in fabric mod dictionary, also crash for the same reason)
2. Login Geyser in a server with Bedrock Edition v1.19.81(lastest)
3. Be kicked out of the server with warning "Your connection to lobby encountered a problem."

### Expected Behavior

Successfully enter the Jave Edition server.

### Additional Server Info

Fabric Mod List:
![image](https://user-images.githubusercontent.com/69727714/236546504-e69fb8c3-05bd-4e66-abbb-9970e63dc12a.png)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--7f776abf--b252%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--7f776abf--b252%29-3498db?style=flat-square) </br>![ViaVersion (4.6.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.6.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Na3MnO4** [comment]
Original log file:
[latest.log](https://github.com/ViaVersion/ViaVersion/files/11409373/latest.log)

**Comment by Kichura** [comment]
Please remove via* from velocity and attempt to install latest viafabric onto the 1.16.5 fabric server to see if issues continue to happen, if it does then it's a third-party mod sending the massive messages as kick result.
