### ISSUE TITLE
{PLAYER} CLIENTBOUND/SERVERBOUND PLAY console spam

### ISSUE THREAD

**Issue by iinquisitor** [ViaVersion/ViaVersion#3314]
### `/viaversion dump` Output

https://dump.viaversion.com/95d0c55b6ae54700adc6fea8e772919b129045dead38c493afffcb2056790077

### Console Error

```
[paste.gg Logs](https://paste.gg/p/anonymous/52bb78762fba435eaac55784fab76d93)
```

### Bug Description

When a player is on the server, displays these logs constantly, without stopping, spamming literally in 0.01 seconds. As soon as the player is kicked, the logs stop spamming, if the player himself left, the logs continue to spam, and the player is still on the server, despite the fact that he is already climbing in the server lists on the Minecraft main menu

### Steps to Reproduce

1. Logged into the server
2. Get logs from ViaVersion

### Expected Behavior

Do not receive such logs on the server. Before, everything was fine. Did not do anything.

### Additional Server Info

Purpur 1.17
ViaVersion 4.5.1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1428%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Purpur--1428%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.5.1)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by iinquisitor** [comment]
on version 1.18.2 there is no such error in the console.

**Comment by Kichura** [comment]
Update your via* copies as bot as described it, otherwise if it persists even after updating then it is a third-party plugin causing problems.

**Comment by iinquisitor** [comment]
I updated to the latest, however I still see these logs.
https://dump.viaversion.com/edb90712572281850b49faac582cc86192f69c9d4194089ba22ddb34592dd0f6

## Console error
[Paste.gg console spam](https://paste.gg/p/anonymous/c29e0de5a1b44f26818bf73e1f07e691)

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1428%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Purpur--1428%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.6.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>
