### ISSUE TITLE
Folia - Error

### ISSUE THREAD

**Issue by Yomamaeatstoes** [ViaVersion/ViaVersion#3316]
### `/viaversion dump` Output

https://dump.viaversion.com/0aaa8dbe8f80a539b63fd3693923a5e952ae022f2b4f62a498a6c490735fc205

### Console Error

https://mclo.gs/yGtGFz8

### Bug Description

On startup or something

### Steps to Reproduce

Start the server up

### Expected Behavior

No errors

### Additional Server Info

Newest version of Folia

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Folia--%2247105ea%22%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Folia--%2247105ea%22%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0-23w18a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.7.0--23w18a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.0-23w18a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.7.0--23w18a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(2.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
You have multiple plugins that don't support folia, Switch back to paper to resolve it as folia is unfinished and can causes problems with plugins at the moment.
