### ISSUE TITLE
Login errors

### ISSUE THREAD

**Issue by xF3d33** [ViaVersion/ViaVersion#3318]
### `/viaversion dump` Output

https://dump.viaversion.com/d029f67ff71026bca43f923a36062cdbb45a720134903c3957cd1c6cb893df67

### Console Error

```
Put the paste.gg link or text here.
```
https://mclo.gs/kHkh0HO
https://mclo.gs/vpldSpT

### Bug Description

some player get disconnected when they try to connect

### Steps to Reproduce

login with 1.19.2 i think

### Expected Behavior

no errors

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--68%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Pufferfish--68%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.6.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.6.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Something is sending a large pile of garbage of JSON code to the server, Please perform a binary search to see what is causing all of that happen which makes via* panic too in process.
