### ISSUE TITLE
1.8.9 client kicked on 1.19.4 server

### ISSUE THREAD

**Issue by J4im3x0** [ViaVersion/ViaVersion#3322]
### `/viaversion dump` Output

https://dump.viaversion.com/a1e247c3a9d0837ab6664673ee07fc8dc5410481c352f2b75297b6781c972e5e

### Console Error

```
https://paste.gg/p/anonymous/b96a9cf00e6340a283d0a3865c8ddcbe
```

### Bug Description

Players connected in 1.8.9 (lunar client) getting kicked when tries to equip armor

### Steps to Reproduce

1. Join with 1.8.9 client on 1.19.4 server w/ viaversion
2. Try to equip an armor
3. You will get kicked

### Expected Behavior

Not getting kicked, apparently (as everything in VV) is a packet translation error

### Additional Server Info

This server is running Pufferfish version git-Pufferfish-69 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 19a70d2 on HEAD)                                                       |
You are on the latest version!
Previous version: git-Pufferfish-68 (MC: 1.19.4)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--69%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Pufferfish--69%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.6.3-SNAPSHOT): 5 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.3--SNAPSHOT)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3): 4 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.3)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.6.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
Not a Via issue: > me.levansj01.verus.util.viaversion.V1_17Remapper
