### ISSUE TITLE
Cracked players have problem to connect to the server

### ISSUE THREAD

**Issue by idepato** [ViaVersion/ViaVersion#3326]
### `/viaversion dump` Output

https://dump.viaversion.com/51180ec8fc0651e4f157b825c753158c46b8866c1379e298d5da268e17ccde09

### Console Error

```
[20:21:29 WARN] [ViaVersion]: ERROR IN Protocol1_19To1_18_2 IN REMAP OF RESPAWN (0x3D)
[20:21:29 WARN] [ViaVersion]: ERROR IN Protocol1_14To1_13_2 IN REMAP OF RESPAWN (0x38)
[20:21:29 INFO]: [Chicken12] disconnected with: EncoderException : com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.packets.EntityPackets$6 (Anonymous), Source 1: com.viaversion.viaversion.protocols.protocol1_14to1_13_2.packets.WorldPackets$9 (Anonymous) @ io.netty.handler.codec.MessageToMessageEncoder:107
[20:21:29 WARN]: No client connected for pending server!
```

### Bug Description

When cracked player want to join to the server. They must connect 3 times when everything working fine. First have problem viac Minecraft.net, then after first join go to limbo and register then give this error and then after secound disconnect they can join server correctly. IDK where is a problem. Premium player doesn't have a this problem

### Steps to Reproduce

1. Cracked player join to the server
2. They got Minecraft.net error
3. Then they connected to limbo and register
4. They disconnected from server and got a error message
5. After error message they can join to the server correctly

### Expected Behavior

I want to player with cracked minecraft connect correctly

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A3df3a27%3A526](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A3df3a27%3A526-3498db?style=flat-square) </br>![ViaVersion (4.6.2): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.2)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3): 4 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.3)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.6.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by idepato** [comment]
https://dump.viaversion.com/4181232471493cdaa8e9d4c05884a6968d32d1855576ac18e610bb12bc5c396c

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A3df3a27%3A526](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A3df3a27%3A526-3498db?style=flat-square) </br>![ViaVersion (4.7.0-1.20-pre5-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.7.0--1.20--pre5--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3): 4 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.3)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.6.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by idepato** [comment]
https://dump.viaversion.com/6b76a20c8271cf7f7e5f8161862ab80233360319d9a928d92ab1e36a34850b8e

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A3df3a27%3A526](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A3df3a27%3A526-3498db?style=flat-square) </br>![ViaVersion (4.7.0-1.20-pre5-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.7.0--1.20--pre5--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.0-1.20-pre5-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.7.0--1.20--pre5--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(2.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by idepato** [comment]
Still got this problem

**Comment by FormallyMyles** [comment]
You have conflicting proxy plugins
