### ISSUE TITLE
Head disappear

### ISSUE THREAD

**Issue by SuprexDE** [ViaVersion/ViaVersion#3328]
### `/viaversion dump` Output

https://dump.viaversion.com/a22ac07ef8601c3cb9450b2eb0a2a6c87ac51297f4e12c503850f35c90d03a0a

### Console Error

no errors or warnings

### Bug Description

1.19.4 Players lose heads when attempting to place heads in a region when they are not allowed to. All players under MC version 1.19.3 do not have this error.

The one with WorldGuard is an example. We also have the problem on our actual Minecraft server, although we do not use WorldGuard.

Video: https://suprexde.de/img/Vove1/hoqOhOrU78.mp4

### Steps to Reproduce

1. Join with version 1.19.4
2. Place any head type in a WorldGuard region where you cannot build.

### Expected Behavior

The head should not disappear from inventory when the player tries to place the head.

### Additional Server Info

On this test server I use Waterfall, WorldGuard, WorldEdit and all Via version plugins.
All plugins are up to date. The server runs on Minecraft version 1.19.3.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--448%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Paper--448%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.6.2): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.2)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3): 4 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.3)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.6.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by SuprexDE** [comment]
https://dump.viaversion.com/d35cd76da70b5973a7aa971ac2d5d37afa1b354cdfafb3a594df9dacf26839a1

**Comment by Barvalg** [comment]
![Platform: git--Paper--448%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Paper--448%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.6.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.6.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by SuprexDE** [comment]
ah it works with the newest dev version :)

**Comment by Kichura** [comment]
Cannot reproduce, Possibly an issue with waterfall plugins being present or worldguard is badly configured.

**Comment by SuprexDE** [comment]
I also tested it without Waterfall and the error was there. It was also the default Worldguard configuration.

**Comment by Kichura** [comment]
Can you test with vanilla 1.19.4? *(This was i used during testing)*
