### ISSUE TITLE
ERROR IN Protocol1_13To1_12_2 IN REMAP OF CHUNK_DATA (0x20)

### ISSUE THREAD

**Issue by shark01d** [ViaVersion/ViaVersion#3330]
### `/viaversion dump` Output

https://dump.viaversion.com/871aa42c6527379e0679e9266af494202344f5972f0513c71c6f577f7fa3eaf4

### Console Error

https://paste.gg/p/anonymous/41fb55a3bd2147788068feb7b1e90872

### Bug Description

Loading some chunks causes client disconnect.

### Steps to Reproduce

1. Connect to 1.12.2 server with ViaVersion and ProtocolLib with 1.19.4 client.
2. Fly around to load some chunks.
3. You can see "Disconnected" on your client.

### Expected Behavior

Chunk loading should be normal.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0-1.20-pre6-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.7.0--1.20--pre6--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by shark01d** [comment]
Looks like some plugin breaks chunks, because even without ViaVersion, some chunks are not loading
