### ISSUE TITLE
Bugs with world rendering, destroying, building and attacking.

### ISSUE THREAD

**Issue by dbakowskid** [ViaVersion/ViaVersion#3333]
### `/viaversion dump` Output

https://dump.viaversion.com/6f70c2b76f1d4751a9573751a401f9c92fcd4e5d29e74b4f698192d59ae1a7f1

### Console Error

No errors in the console.

### Bug Description

The server was launched on version 1.19.
With the ViaVersion plugin version 4.7.0

After joining a user on version 1.19.3, the player is unable to destroy blocks, place blocks, hit opponents, and chunks do not load.

No error is visible in the console.

(After changing the server version to 1.16.4 and staying on the same minecraft client version. The problem occurs the same.)

### Steps to Reproduce

1. Launching the server version 1.19 (PaperSpigot)
2. Upload ViaVersion 4.7.0
3. Launching the minecraft 1.19.3 client
4. Joining the server
5. Occurrence of the following build, destroy, attack, and world render errors.

### Expected Behavior

Correct functioning of the server on versions 1.19.X

### Additional Server Info

Server information:
- Engine: PaperSpigot 1.19
- Java: 18
- RAM: 16GB

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--81%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Paper--81%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0-1.20-rc1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.7.0--1.20--rc1--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Update to paper 1.19.4 and see if the issue continues to happen.

**Comment by dbakowskid** [comment]
The problem is the same, but solving it would then defeat the purpose.
Because the goal is to achieve the game on version 1.19.X

**Comment by FormallyMyles** [comment]
Are there any further errors / have you tried with a fresh world?
