### ISSUE TITLE
viaversion breaks plugins (like protocollib)

### ISSUE THREAD

**Issue by F3F5** [ViaVersion/ViaVersion#3336]
### `/viaversion dump` Output

https://dump.viaversion.com/4dddd52bf1032f8a861814035fd2ab62fac8502a234785e2c6230240d4cb6e3b

### Console Error

https://paste.gg/p/anonymous/fba5187f8d31461eaaa5f4a2ae4682f0

### Bug Description

plugin breaked after adding some plugins like protocollib

### Steps to Reproduce

install paper 1.12.2, protocollib, viaversion 

### Expected Behavior

.

### Additional Server Info

.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
The error isn't ViaVersion related
