### ISSUE TITLE
ViaVersion fails to initialize 

### ISSUE THREAD

**Issue by Eris7090** [ViaVersion/ViaVersion#3340]
### `/viaversion dump` Output

Unknown command 

### Console Error

https://paste.gg/p/anonymous/442888ecc2864a9093d8633403645172

### Bug Description

ViaVersion fails to initialize 

### Steps to Reproduce

1. Download current version (4.7.0)
2. Place it in plugins folder 
3. Start server 

### Expected Behavior

Plugin should initialize 

### Additional Server Info

I'm using purpur not paper on version 1.19.4. I have mcMMO, ViaRewind, and ViaBackwards as well. 
Edit: I forgot I also have geyser and floodgate

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Kichura** [comment]
Update from CI.
