### ISSUE TITLE
Player heads losing NBT data

### ISSUE THREAD

**Issue by abhisantos** [ViaVersion/ViaVersion#3343]
### `/viaversion dump` Output

https://dump.viaversion.com/ee360357d18cb8fc38fd6ba76cabab733d6ba30a1a4c19b33d104e956e840e45

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

When players place a "machine", lets say, from slimefun, which are player_heads with NBT data, or break them, it loses its original plugin NBT and become a regular head block.

This started since Viaversion 4.7.0

Spigot/Paper 1.19.4

### Steps to Reproduce

Login to server, place or break a player_head item with nbt data.

### Expected Behavior

it loses its original plugin NBT and become a regular head block.
better test without OP
teste more than one time

### Additional Server Info

Viaversion only installed on spigot backends

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--448%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Paper--448%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3): 4 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.3)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by HowardZHY** [comment]
https://github.com/ViaVersion/ViaBackwards/issues/551

**Comment by abhisantos** [comment]
> ![Platform: git--Paper--448%20%28MC%3A%201.19.3%29](https://camo.githubusercontent.com/420a43564cf42dbc724c53502d430f0d3a2976960c6effb96e37431cbdc61179/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d50617065722d2d3434382532302532384d43253341253230312e31392e332532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.7.0): 1 commits behind master](https://camo.githubusercontent.com/6d480ca4c9b6c66b2517fa7e16f3421f96d9c5cfe4f2b6282aed224072a0e66a/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e372e30292d31253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaRewind(2.0.3): 4 commits behind master](https://camo.githubusercontent.com/ef8135779f35b12ae44a73d5b9c4f133dba806392a48d5eb6602311f2cd5eafe/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f566961526577696e6425323028322e302e33292d34253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaBackwards(4.7.0): Even with master](https://camo.githubusercontent.com/f088932a7343777f32efece8780ea93e7d8d2c6799304a9aa0b35ca3b3ad0206/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e372e30292d4576656e253230776974682532306d61737465722d627269676874677265656e3f7374796c653d666c61742d737175617265)
> 
> ### Please try the **latest** build(s) from https://ci.viaversion.com/. In case the issue still persists send the new dump

Just testes with the new version and the issue persists.
Dump: https://dump.viaversion.com/788635cdf70ae4a679f90525252268e8c397aed2dc3338d42db0e31c714ce7df

**Comment by WarnDa** [comment]
So that's exactly the problem I get since I allowed 1.19.4 players on 1.19.3 server !
But as it didn't work each time I thought it was on my side.
But for you the issue is with player in OLDER or NEWER version than your server ?

**Comment by WarnDa** [comment]
> Duplicate of 551.

Not the same issue, here it's in viaversion, not viabackward.
It's for players connecting in 1.20 on 1.19.3 server for example.
