### ISSUE TITLE
[Purpur 1.20] "Packet 0/67 (xh) was larger than I expected" upon join

### ISSUE THREAD

**Issue by babburjs** [ViaVersion/ViaVersion#3345]
### `/viaversion dump` Output

https://dump.viaversion.com/3b87a77b3a8b6dbb02ffa5f793c09f9dbdf0de6569813758a8780208ab335cd5

### Console Error

There was no console output.

### Bug Description

Joining a Purpur 1.20 server with ViaVersion 4.7.0 on Minecraft 1.20 causes a disconnection with packet 0/67 being larger than expected

### Steps to Reproduce

1. Login with 1.20 client
2. Connect to 1.20 server (Maybe Purpur only?) with ViaVersion 4.7.0 OR 4.7.1
3. Get kicked

### Expected Behavior

The player should be able to join and play normally.

### Additional Server Info

Note: I am migrating from a 1.18.2 server over to a 1.20 server, and I understand that 1.20 is experimental, just wanted to get this issue out there if it's not known.

The server is running on Purpur, Java 17 with the following plugins:
```
[04:53:24 INFO]: Bukkit Plugins: (24):
[04:53:24 INFO]:  - DecentHolograms, FastAsyncWorldEdit, GrimAC, Images, LuckPerms, ModelEngine, *MongoSK, Multiverse-Core, MythicMobs, PlotSquared
[04:53:24 INFO]:  PowerCamera, ProtocolLib, SkBee, skDragon, SkJade, Skript, skript-reflect, *skUtilities, spark, TAB
[04:53:24 INFO]:  Vault, ViaVersion, ViaVersion, WorldGuard```
```
I am in the process of updating many of these plugins as they are not functional in this version (Images, ModelEngine, MythicMobs, PlotSquared and WorldGuard)

![image](https://github.com/ViaVersion/ViaVersion/assets/79817320/8e8a2c4c-68a2-4100-b880-4d63d75f4cc1)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1987%20%28MC%3A%201.20%29](https://img.shields.io/badge/Platform-git--Purpur--1987%20%28MC%3A%201.20%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by babburjs** [comment]
The new dump: https://dump.viaversion.com/dc0ff4c5b0b0c9c143efef2a0ee4751536385480abf8a223e784acde46f0e536

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1987%20%28MC%3A%201.20%29](https://img.shields.io/badge/Platform-git--Purpur--1987%20%28MC%3A%201.20%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by FormallyMyles** [comment]
ViaVersion doesn't translate data for the same server version as client. Unless you've incorrectly got it installed on proxy and server (which remove it from your bungee/velocity if so). This will be down to another plugin.
