### ISSUE TITLE
Smithing table not work in bedrock client 1.20

### ISSUE THREAD

**Issue by raphaelfasilva** [ViaVersion/ViaVersion#3348]
### `/viaversion dump` Output

https://dump.viaversion.com/956f63c9c21246f3d595f4ad790b0c013417aa37ee698052d76ec35f0003393f

### Console Error

Not Aplicate 

### Bug Description

After fix smithing table throgh of issue #3338 in java 1.20 client stayed ok smithing table are work but how i use geyser on bed rock client 1.20 not work not accept netherite on bottom square.

### Steps to Reproduce

1 . started paper server 1.19.4
2 . log on the server
3. i put smithing table on the floor 
4. i opened smithing table(upgrade gear on implementation)
5. i tried upgrade diamond pickaxe to netherite
6. i cant put netherite bottom square not accept

### Expected Behavior

expected is upgrade diamond tools in netherite.

### Additional Server Info

nothing

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--545%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--545%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Chenyu550** [comment]
> This is a Geyser issue. ViaVersion can't do anything to fix it. Thanks though.

So when will Geyser fix it?
