### ISSUE TITLE
ViaVersion incorrectly detects server version

### ISSUE THREAD

**Issue by BestMark** [ViaVersion/ViaVersion#3350]
### `/viaversion dump` Output

https://dump.viaversion.com/160dbb3a86d092f19a51813d2ed378603f03f89a6884398013d1aea70176e16c

### Console Error

```
[04:00:46] [Server thread/INFO]: [ViaVersion] ViaVersion detected server version: 1.7.2-1.7.5 (4)
[04:00:46] [Server thread/WARN]: [ViaVersion] ViaVersion does not have any compatible versions for this server version!
```

### Bug Description

This sometimes happens when restarting the server. When the server is turned on, players from versions 1.12.2 and higher cannot join it.
I tried to hardcode server version in BukkitViaInjector and compile ViaVersion, but it did not help too.
![image](https://github.com/ViaVersion/ViaVersion/assets/18399104/4a416a7f-54ab-465c-b469-b524c4c6d24c)
Server still starts with the error.

### Steps to Reproduce

1. Restart the server.
2. Sometimes ViaVersion will detect server version 1.7.2-1.7.5 (4).

### Expected Behavior

Players cannot join the server with 1.13+.

### Additional Server Info

I also use ProtocolSupport, but it does not modify server version.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--77cce823%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--77cce823%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Kichura** [comment]
1. ProtocolSupport requires the use of paper 1.18.2 and therefore doesn't work properly,

2. You very likely have third party plugins that intentionally brick viaversion's version check list entieely,

3. (assumed): You likely have a bad proxy aswell,

4. Hard-codinf the server version is much worse than using vanilla viaversion and also avoidinf the use of crappy plugins.

**Comment by BestMark** [comment]
> * ProtocolSupport requires the use of paper 1.18.2 and therefore doesn't work properly,
> * You very likely have third party plugins that intentionally brick viaversion's version check list entirely,
> * (assumed): You likely have a bad proxy aswell,
> * Hard-coding the server version is much worse than using vanilla viaversion and also avoidinf the use of crappy plugins.

1. The problem was also with ViaRewind.
2. No, I don’t use such plugins.
3. Proxy? ViaVersion incorrectly detects Paper version. Paper is not proxy.
4. So what can I do?
5. Please reopen the issue because you did not resolve the problem at all.

**Comment by Kichura** [comment]
> > * ProtocolSupport requires the use of paper 1.18.2 and therefore doesn't work properly,
> > * You very likely have third party plugins that intentionally brick viaversion's version check list entirely,
> > * (assumed): You likely have a bad proxy aswell,
> > * Hard-coding the server version is much worse than using vanilla viaversion and also avoidinf the use of crappy plugins.
> 
> 1. The problem was also with ViaRewind.
> 2. No, I don’t use such plugins.
> 3. Proxy? ViaVersion incorrectly detects Paper version. Paper is not proxy.
> 4. So what can I do?
> 5. Please reopen the issue because you did not resolve the problem at all.

Please consider doing a binary search to see what *really* causes viaversion to suddenly fail on purpose as there is no way this behavior is intentionally caused by us.

**Comment by BestMark** [comment]
> > > * ProtocolSupport requires the use of paper 1.18.2 and therefore doesn't work properly,
> > > * You very likely have third party plugins that intentionally brick viaversion's version check list entirely,
> > > * (assumed): You likely have a bad proxy aswell,
> > > * Hard-coding the server version is much worse than using vanilla viaversion and also avoidinf the use of crappy plugins.
> > 
> > 
> > 
> > 1. The problem was also with ViaRewind.
> > 2. No, I don’t use such plugins.
> > 3. Proxy? ViaVersion incorrectly detects Paper version. Paper is not proxy.
> > 4. So what can I do?
> > 5. Please reopen the issue because you did not resolve the problem at all.
> 
> Please consider doing a binary search to see what _really_ causes viaversion to suddenly fail on purpose as there is no way this behavior is intentionally caused by us.

Where can I find code that detects server version in ViaVersion? I have already hardcoded server version 1.12.2, but it did not help.

**Comment by Kichura** [comment]
> > > > * ProtocolSupport requires the use of paper 1.18.2 and therefore doesn't work properly,
> > > > * You very likely have third party plugins that intentionally brick viaversion's version check list entirely,
> > > > * (assumed): You likely have a bad proxy aswell,
> > > > * Hard-coding the server version is much worse than using vanilla viaversion and also avoidinf the use of crappy plugins.
> > > 
> > > 
> > > 
> > > 1. The problem was also with ViaRewind.
> > > 2. No, I don’t use such plugins.
> > > 3. Proxy? ViaVersion incorrectly detects Paper version. Paper is not proxy.
> > > 4. So what can I do?
> > > 5. Please reopen the issue because you did not resolve the problem at all.
> > 
> > 
> > Please consider doing a binary search to see what _really_ causes viaversion to suddenly fail on purpose as there is no way this behavior is intentionally caused by us.
> 
> Where can I find code that detects server version in ViaVersion? I have already hardcoded server version 1.12.2, but it did not help.

Have a look at [this](https://github.com/ViaVersion/ViaVersion/blob/20a4ae3e4bfebb061e793cf899f5d12bd47ba05c/common/src/main/java/com/viaversion/viaversion/ViaManagerImpl.java#L124), you might wanna consider just using viaversion's API instead of hard-coding instead.

**Comment by BestMark** [comment]
But why ViaVersion 4.6.0 detects server version correctly, while 4.6.1 does not?

**Comment by Kichura** [comment]
> But why ViaVersion 4.6.0 detects server version correctly, while 4.6.1 does not?

Mostly the case of plugins that are poorly designed and end up bricking viaversion on purpose.

**Comment by BestMark** [comment]
> > But why ViaVersion 4.6.0 detects server version correctly, while 4.6.1 does not?
> 
> Mostly the case of plugins that are poorly designed and end up bricking viaversion on purpose.

https://github.com/ViaVersion/ViaVersion/commit/4e844a00953c772f9ed45ab61181521aef39bc41
