### ISSUE TITLE
The display item entity rotation yaw flip is incorrect

### ISSUE THREAD

**Issue by bergerkiller** [ViaVersion/ViaVersion#3354]
### `/viaversion dump` Output

https://dump.viaversion.com/e12c410369af82e1213d6782bc41928ac32f4902daed0e06c1cfe909b0173f83

### Bug Description

This PR https://github.com/ViaVersion/ViaVersion/pull/3342 attempted to fix it so that 1.20 clients can see correct display item entity yaw when connecting using viaversion to a 1.19.4 server. However, that fix is wrong. The yaw should be applied to the LEFT/RIGHT rotation fields, NOT the entity yaw. This causes rotation of display entities to break when they pitch up and down.

How it should look:
![Screenshot_20230618_150406](https://github.com/ViaVersion/ViaVersion/assets/957601/433b3437-f179-4d66-8b48-354774294370)

How it instead looks:
![Screenshot_20230618_150533](https://github.com/ViaVersion/ViaVersion/assets/957601/eac90825-edb0-44dc-a885-e63475b26b72)

### Steps to Reproduce

1. Create a 1.19.4 server with BKCommonLib and TrainCarts and Viaversion
2. Connect with a 1.19.4 client
3. Create a simple track with a hill/slope
4. Create a train using `/train chest https://paste.traincarts.net/fahovulari` and spawning with it. The train looks tilted sideways, thats on purpose.
5. Give it a push so its moving forwards (furnace front is front)
6. Now reconnect with a 1.20 client and notice how it looks fine on the flat part, but as it pitches vertically to go up the hill it rotates all wrong.

https://github.com/ViaVersion/ViaVersion/assets/957601/815a9870-6dfc-429e-9415-822b9ac0a377

### Expected Behavior

Display item entities look correct on 1.19.4 and 1.20 clients

### Additional Info

I discovered this because I had applied the same 'fix' in traincarts, which broke 1.19.4 clients. Ive had to revert that as a result. https://github.com/bergerhealer/TrainCarts/commit/65bc73012b83e29d4ff0eec7a8fd8d5510f6f95c

There is no viaversion-specific code in traincarts to account for 1.19.4->1.20 rotation.

If you need to know how to flip a quaternion, see <https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/math/Quaternion.java#L404>

Plugin downloads can be found here (still in dev) https://ci.mg-dev.eu/

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--545%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--545%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.0): 6 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
Thank you for the detailled report, fixed
