### ISSUE TITLE
Knockback bug

### ISSUE THREAD

**Issue by xsorencoolx** [ViaVersion/ViaVersion#3356]
### `/viaversion dump` Output

https://dump.viaversion.com/2bb63be0b7770f25fb69d34ecc05e1ecde24d04fed9ac884e7388a60e4bd41cb

### Console Error

no error on console

### Bug Description

soo most of my server player are not getting knockback when they use lunar client or tlauncher or etc and this cause me some problems my anti cheat kicking people for velocity i thought it was my anti cheat and i use old version but still got same problem

### Steps to Reproduce

its pretty random and after user relaunch there game it gonna be ok

### Expected Behavior

.

### Additional Server Info

i only use it on backend server and after i update to last version of via version this bug happend

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--445%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--445%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
Does it happen on 1.8.8? What versions does it happen on?

**Comment by FormallyMyles** [comment]
This isn't related to viaversion then, we don't modify data for the server version.
