### ISSUE TITLE
Smithing tables with furnance menu is unusable for GeyserMC

### ISSUE THREAD

**Issue by roggy666** [ViaVersion/ViaVersion#3358]
### `/viaversion dump` Output

https://dump.viaversion.com/fe7d73aa17757d2b0c9b67720d7ae9249b56543c2709e2a6472892622daa370f

### Console Error

```
Put the paste.gg link or text here.
```
No errors.

### Bug Description

![image](https://github.com/ViaVersion/ViaVersion/assets/59109355/d45969af-cdf2-49ee-b9bd-d54281917620)
You can't use smithing table on 1.20 Client (Bedrock) and put not melting items to furnance

### Steps to Reproduce

1. Use new ST (Smithing Table) GUI, with barrier in one of the slots
?  Use old GUI (it did not deleted in bedrock textures) ?
? Use Chest-Minecart with barriers - separators ?

### Expected Behavior

Bedrock players can make Netherite items

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1428%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Purpur--1428%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>
