### ISSUE TITLE
Player heads issues when placing

### ISSUE THREAD

**Issue by WarnDa** [ViaVersion/ViaVersion#3361]
### `/viaversion dump` Output

https://dump.viaversion.com/0072b511aaf55e34c98949353118fd7fb7982f7b7aefc8507f130bec849db905

### Bug Description

Connecting on 1.19.4/1.20(.1) on an 1.19.**3** server create an issue on head that can make his NBT not working again
I use a plugin with custom head that place structure when you put them on the floor, but players in 1.19.4/1.20 are just placing vanilla head, it does nothing.

### Steps to Reproduce

- Login with 1.19.4 or 1.20 on a 1.19.3 server
- Give the custom head to the player (not OPPED)
- Disconnect/reconnect (or restart server)
- Try to place the head, the structure will not appear

### Expected Behavior

It should place the structure.

### Additional Server Info

The NBT doesn't seems to disappear from the item, but it might just ignore the NBT when placing the head, it doesn't happen 100% of the time, for example I tried 3 times, and 1 time the head placed well with the structure.

- Same issue as : https://github.com/ViaVersion/ViaVersion/issues/3343 and the author is also in 1.19.3, and explained that the issue isn't fixed for him.
- It's not the same issue as https://github.com/ViaVersion/ViaBackwards/issues/551 so don't close it please.
- Maybe it's not the NBT that is checked when placing the head but the lore/name, can't be sure.
### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--61%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Pufferfish--61%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by WarnDa** [comment]
I used a plugin that store NBT to show the two heads : https://pastebin.com/ZUBmuQCv
Maybe it's not the NBT that aren't checked on block place but the LORE. I don't remember if the plugin check lore, NBT, name :/

**Comment by Sefiraat** [comment]
When wearing a helmet with just viaversion and the plug-in with ‘custom’ heads on the server the ItemStack in the players hand during the BlockPlaceEvent will be one count lower than it was during placement. This will result in a AIR ItemStack when there is only one left in the stack, resulting in plugins like this not being able to check for the presence of their item(s) and looking like loss of data as they aren’t able to persist the relevant information. 

When the player doesn’t wear a helmet, this issue doesn’t occur. Neither does it occur if the ItemStack is a count of 2 or more. 

We have an issue on our repo here: https://github.com/Slimefun/Slimefun4/issues/3840

**Comment by kennytv** [comment]
https://github.com/ViaVersion/ViaVersion/commit/4971eeab6a4967ae25a80246436a12547224cccb
