### ISSUE TITLE
lost connection: Internal Exception: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException

### ISSUE THREAD

**Issue by razenxc** [ViaVersion/ViaVersion#3362]
### `/viaversion dump` Output

https://dump.viaversion.com/74e09d18891734a22efc5870ee47e73be1f218782d2f3e5bbcae81bb753d3ab6

### Console Error

```
[08:26:54 INFO]: /176.58.106.79:55350 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: null, Type: UUID, Index: 3, Data: [{String: cuute}, {ProfileKey: null}], Source 0: com.viaversion.viaversion.protocols.protocol1_19_1to1_19.Protocol1_19_1To1_19$7 (Anonymous), Packet ID: 0
```

### Bug Description

I went to the server console today and saw that in my console spamming the warnings that I wrote in the error paragraph. And here it is written to create an issues, well, I've created it. How to fix it? And IPs in the loss of connection writes some unknown to me, on my server there are no players with such IPs. Via Version installed latest release version 4.7.0. After a restart it happens again.
Console screenshot: https://prnt.sc/pH6Bwf8ZEXsR

### Steps to Reproduce

It happens on its own so it's impossible to describe

### Expected Behavior

I expect that I will not have warnings in the console

### Additional Server Info

Core: purpur-1.17.1-1428
Plugins: ArmorStandTools, AuthMe, BetterReports, Chairs, Chatty, CoreProtect, dynmap, Essentials, EssentialsAntiBuild, EssentialsGeoIP, EssentialsProtect, floodgate, Geyser-Spigot, ImageOnMap, LaggRemover, LuckPerms, MOTD, ProtocolLib, SkinsRestorer, TabList, UltimateAntiBot, Vault, ViaVersion, voicechat

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1428%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Purpur--1428%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 12 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-12%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by razenxc** [comment]
> ![Platform: git--Purpur--1428%20%28MC%3A%201.17.1%29](https://camo.githubusercontent.com/755b483aa25302530431372310ac2a849dc462093266c3f3689e7a66cbc6b860/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d5075727075722d2d313432382532302532384d43253341253230312e31372e312532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.7.0): 12 commits behind master](https://camo.githubusercontent.com/866c689caec55ec40e025fc26220c0f0b880a99fbf92ab9b80aba17f4dd6d151/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e372e30292d3132253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265)
> 
> ### Please try the **latest** build(s) from https://ci.viaversion.com/. In case the issue still persists send the new dump

Warnings still persist on 4.7.1-Snapshot:
https://dump.viaversion.com/3b2b7d76c696790df2532c43077ad3d23ad48868bdbbd61e3c0ef1ff8641c0ec

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1428%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Purpur--1428%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
Likely someone sending bad data to your server and can be ignored
