### ISSUE TITLE
Soul speed don't work

### ISSUE THREAD

**Issue by Chenyu550** [ViaVersion/ViaVersion#3364]
### Problem Description

I actually don't know if it's the plugin's problem. But I don't know when, Soul speed no longer works, no matter I use a higher or lower game version than the server. And the corresponding text on the boots has become italic，like this:
![image](https://github.com/ViaVersion/ViaVersion/assets/114039435/06d41bf8-de55-4fc8-a58e-1944843bc06b)
Currently using this version: https://github.com/ViaVersion/ViaVersion/actions/runs/5246372217
So if this is not a Viaversion issue, sorry to bother you guys

### Solution Description

If it can be reproduced, fix it

**Comment by Jo0001** [comment]
Works fine for me on 1.19.4 server and a 1.20.1 & 1.18.1 client with latest Via*.
If you think its a Via issue please open a new issue (as Bugreport and not as feature request)

**Comment by Chenyu550** [comment]
> Works fine for me on 1.19.4 server and a 1.20.1 & 1.18.1 client with latest Via*. If you think its a Via issue please open a new issue (as Bugreport and not as feature request)

This seems to be my server's data problem, and after I re-add this enchantment with the command "/enchant", it contiune working, now it has two soul speeds now. I don't have a clue. But thank you anyway.
![image](https://github.com/ViaVersion/ViaVersion/assets/114039435/cd49525e-dee5-404f-9ff9-ed215710cce1)
