### ISSUE TITLE
ViaVersion not working

### ISSUE THREAD

**Issue by CBRoCraft** [ViaVersion/ViaVersion#3365]
### `/viaversion dump` Output

https://dump.viaversion.com/e5d483a775513c02b1b99a457c40b5bcf0d0c951ade8867a9a37f39d27fc8088

### Console Error

https://paste.gg/p/anonymous/cdb5b28d97f54216a4d75a5f3461f406/files/fbde362003764df08f41069e113678a1/raw

### Bug Description

Viaversion wont work

### Steps to Reproduce

Viaversion wont work

### Expected Behavior

Viaversion wont work

### Additional Server Info

server version: paper 1.19.4

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--549%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--549%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Camotoy** [comment]
As the bot says.

**Comment by CBRoCraft** [comment]
thx

**Comment by CBRoCraft** [comment]
But I can't update viaversion cuz I'm using minehut hosting. so i can't update viaversion only viabackwards

**Comment by Camotoy** [comment]
Doing so will likely address your particular issue then.

**Comment by CBRoCraft** [comment]
anyways ty

**Comment by CBRoCraft** [comment]
no errors while loading the server

**Comment by CBRoCraft** [comment]
i updated viabackwards
