### ISSUE TITLE
NettyIO Error

### ISSUE THREAD

**Issue by mehboss** [ViaVersion/ViaVersion#3367]
### `/viaversion dump` Output

https://dump.viaversion.com/9bf5071d7317ebb5748cdf9835f6d577db2b713fb22ffe8a3bfb8ba34567dfea

### Console Error

```
[Put the paste.gg link or text here.](https://paste.gg/p/anonymous/7d3e6e03d7d84f98882e4590870a7946)
```

### Bug Description

Kicked with error

### Steps to Reproduce

1. Login with 1.20.1 MC client
2. Sit afk while you do things
3. Come back to computer with error

:)

### Expected Behavior

Probably resolved, just doing as the error says.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3762--Spigot--7d7b241--2270366%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-3762--Spigot--7d7b241--2270366%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 15 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-15%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.0): 6 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
Your jar is broken, redownload it
