### ISSUE TITLE
Ping and number of players is always shown as incompatible when client and server version are the same.

### ISSUE THREAD

**Issue by xFilioo** [ViaVersion/ViaVersion#3370]
### `/viaversion dump` Output

https://dump.viaversion.com/8f07a2e32a92b7ff5039afda4f095aab0a119f7d91e4c912449cb1ee323f0b5a

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

It's as in the title ping and player count always show as incompatible when client and server versions are the same. For example, I have a server on version 1.19.4 in the plugin I have it set that you can enter from 1.19 to 1.19.4, but when I enter even 1.19.4 it is written in the menu that it is the wrong version and you can only enter 1.19.4 (but it is only written in the menu, you can enter the server normally) and I also apologize for my ability to speak English
![image](https://github.com/ViaVersion/ViaVersion/assets/137171306/67f8cddd-e147-4301-9999-4ce15af95f3b)
![image](https://github.com/ViaVersion/ViaVersion/assets/137171306/b2d9efe8-5288-43d1-b85d-afbcd0d428bf)
![image](https://github.com/ViaVersion/ViaVersion/assets/137171306/3891a3c9-ffb2-4e95-9cf9-a000024d0b0d)

### Steps to Reproduce

1. Enter minecraft
2. Enter the server list
3. Add a server
4. I see an error

### Expected Behavior

Number of players and ping

### Additional Server Info

Paper 1.19.4 (paper 1.19.4 509), I also use ViaBackwards

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--509%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--509%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.0): 6 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by xFilioo** [comment]
The dump is the latest version from this site

**Comment by Kichura** [comment]
Update ViaBackwards to CI build and also test with vanilla client instead of lunar as lunar is known for causing problems with connectivity.

**Comment by xFilioo** [comment]
This error is there all the time. I also tested on 1.19.2 and 1.19.4 on vanilla client and on lunar client

**Comment by Kichura** [comment]
> This error is there all the time. I also tested on 1.19.2 and 1.19.4 on vanilla client and on lunar client

Then it's likely to be a third-party plugin causing it - What you could try is updating viaversion and viabackwards to latest CI builds and then start doing a binary search to see which third-party plugin is changing the ping result to incompatible version as this does not look like to be viaversion's fault whatsoever.

**Comment by LaughNgamez** [comment]
@xFilioo Did you find out what caused this?
