### ISSUE TITLE
1.13 can't connect to server

### ISSUE THREAD

**Issue by FuriousBird** [ViaVersion/ViaVersion#3372]
### `/viaversion dump` Output

https://dump.viaversion.com/32471deefafe6ec15877d29eae71b2db4f6501c7b3f8d1ddca0c7fb6850d61eb

### Console Error

![image](https://github.com/ViaVersion/ViaVersion/assets/44238459/edde2a5e-9cae-45ff-9bf7-b93c4bfa588b)

### Bug Description

when loggin ito 1.13 server

### Steps to Reproduce

login with 1.13 client
get the error when joining a server

### Expected Behavior

i should be able to login

### Additional Server Info

no idea

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 2.2.5](https://img.shields.io/badge/Platform-2.2.5-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by HowardZHY** [comment]
Dumplicate of https://github.com/ViaVersion/ViaVersion/issues/2383
PS: ViaFabricPlus unlikely to have more updates for old versions.

**Comment by Jo0001** [comment]
We don't support 1.13.0 servers, see https://github.com/ViaVersion/ViaVersion/issues/2383
