### ISSUE TITLE
04:13:44 WARN]: [ViaVersion] ERROR IN Protocol1_19To1_18_2 IN REMAP OF PLAYER_DIGGING (0x1C)

### ISSUE THREAD

**Issue by f3f5-dev** [ViaVersion/ViaVersion#3373]
### `/viaversion dump` Output

https://dump.viaversion.com/6f010f0901c372d3252c13c3e7fda55f4e23171d5feb2cc6845595dd67d8f6fd

### Console Error

https://pastes.dev/JlaPvkhapZ

### Bug Description

disabling server

### Steps to Reproduce

.

### Expected Behavior

.

### Additional Server Info

.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Reaper--%2208ebad8%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Reaper--%2208ebad8%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 15 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-15%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3): 12 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.3)-12%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.0): 6 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>
