### ISSUE TITLE
1.20+ players cannot use smithing table at 1.19.4 server

### ISSUE THREAD

**Issue by kayozelke** [ViaVersion/ViaVersion#3375]
### `/viaversion dump` Output

https://dump.viaversion.com/b9f7917f976e056a6319be4621b989bb2ee8c9dae89fbfba36adb66c3706b362

### Console Error

```
There is no output error
```

### Bug Description

The problem occurs when client with game version 1.20 is right clicking at minecraft:smithing_table block. 
For server engines with versions of game 1.20.1, smithing gui is showed properly.
![image](https://github.com/ViaVersion/ViaVersion/assets/116091384/d9bb6647-5359-48a7-9086-6d84b2c00228)

However for purpur server with version 1.19.4 and player using 1.20 there is nothing showing up for him. Nothing happens at all. Just the typical "move" of player hand when interacting. This hand motion is visible to the other players. 
![image](https://github.com/ViaVersion/ViaVersion/assets/116091384/abe621a7-a027-4940-9887-dff4e1501df3)

Important: If the client changes its game version to 1.19.4, he can use smithing table properly on both server versions.

### Steps to Reproduce

1. Set bungeecord proxy - waterfall-1.20-536.
3. Set spigot server with newest 1.19.4 version available - git-Purpur-1985 (MC: 1.19.4).
5. Get into the server when using 1.20 client and place smithing table. 
7. Right click on smithing table.

### Expected Behavior

Smithing table GUI should be shown for the player.

### Additional Server Info

All tests were performed when attached to bungeecord server - version: waterfall-1.20-536.jar. No viaversion plugin installed there.

Spigot servers:
server version with occuring bug: git-Purpur-1985 (MC: 1.19.4)
server version without bug: git-Purpur-2005 (MC: 1.20.1)

Plugins should not be a problem, I've reduced their count for the tests to as low as I could.
![image](https://github.com/ViaVersion/ViaVersion/assets/116091384/fd37d2df-698b-40ce-b2af-1a32b3be9873)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1985%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Purpur--1985%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 17 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.0): 6 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Kichura** [comment]
Update to CI builds of viaversion and viabackwards.
