### ISSUE TITLE
Smithing table

### ISSUE THREAD

**Issue by Z-BaneJil** [ViaVersion/ViaVersion#3377]
### `/viaversion dump` Output

I made a dump on the local server with the configs of the main server. https://dump.viaversion.com/b94066b43ecb723e2fb671e45cfb753025560efb6d1ed2f48478447dff9c87ef

### Console Error

```
No errors
```

### Bug Description

Maybe that's my problem. But smithing table does not open GUI on 1.20. As I understand it is because of new update with templates. If you log in from a client with a lower version, everything works.
I'm sorry if there are any inaccuracies. I used a translator.

### Steps to Reproduce

1. Enter from 1.20
2. Put smithing table
3. Open the smithing table GUI
4. Make sure GUI doesn't work

### Expected Behavior

The smithing table click opens the gui

### Additional Server Info

Purpur 1.16.5

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1171%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Purpur--1171%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 17 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Kichura** [comment]
Update to CI builds.

**Comment by Z-BaneJil** [comment]
Sorry, I thought the latest build from `https://www.spigotmc.org/resources/viaversion.19254/`. I think you could use the GUI smithing table instead of the furnace GUI. I think you have tried.
