### ISSUE TITLE
Plugin crashes when either block-protocols or block-versions are listed as null in config.yml

### ISSUE THREAD

**Issue by Zjaun** [ViaVersion/ViaVersion#3380]
### `/viaversion dump` Output

cannot, the plugin is disabled

### Console Error

```
https://paste.gg/p/anonymous/a8e4c1b394ab4af3b0e24fbfce240103
```

### Bug Description

NullPointerException when either block-versions or block-protocols are set as null, causing the plugin to disable

### Steps to Reproduce

1. Set either block-versions or block-protocols in config.yml as null
2. Run server

### Expected Behavior

If block-versions or block-protocols has a value of null, it should be an empty array

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
Don't set it as null, use an empty list: []
