### ISSUE TITLE
MAP_DATA packet disconnects players

### ISSUE THREAD

**Issue by TheXplore** [ViaVersion/ViaVersion#3382]
### `/viaversion dump` Output

https://dump.viaversion.com/28fad87dc1b72299c45fcef89d58cbfcd319ec280a37573fb7c4d9a5b06fd120

### Bug Description

Player gets kicked with message "Internal Exception: io.netty.handler.codex.DecoderException: Received unexpected null component" after receiving a MAP with custom cursors.

This only happens if the map contains cursors set via mapCanvas.setCursors().

After further investigation it seems like the field "Icon Count" may not be set.

![image](https://github.com/ViaVersion/ViaVersion/assets/26611093/88f882a2-abca-458d-b0a3-87606a0579de)

Thank you for your time 🙂

### Steps to Reproduce

1. Setup 1.17.1 server with viaverion 4.7.1-snapshot (build 715)
2. Log in with 1.20.1 client
3. Give player a custom map (Full code paste: https://paste.gg/p/anonymous/310b107182a742f2b9f6cc446965311b)
```
@Override
public void render(MapView map, MapCanvas canvas, Player player) {
      byte x = 100;
      byte z = 100;
      byte orientation = 10;
      
      MapCursorCollection cursors = new MapCursorCollection();
      cursors.addCursor(new MapCursor(x, z, orientation, Type.RED_POINTER, true));
      canvas.setCursors(cursors);
}
```
4. Player gets kicked with the message "Internal Exception: io.netty.handler.codex.DecoderException: Received unexpected null component"

### Expected Behavior

The player should not get kicked and see a map which contains the cursors.

### Additional Server Info

We do use bungeecord, but viaversion is installed on backend servers

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--408%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--408%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
