### ISSUE TITLE
Text displays have wrong rotation on 1.19.4 server with 1.20.1 client

### ISSUE THREAD

**Issue by Gennario** [ViaVersion/ViaVersion#3383]
### `/viaversion dump` Output

https://dump.viaversion.com/1a5543365e8c9fc73efa7b12f1fd03d4283af1e14769bf1db442e5c3c99e8cdb

### Console Error

no errors

### Bug Description

Text displays placed on 1.19.4 servers is rotated by additional 180 degrees to 1.20.1 clients

### Steps to Reproduce

1. Create Text display entity on 1.19.4 miencraft server and set facing to 0 yaw and 0 pitch
2. Login-in with 1.20.1 client and the text display will be rotated by 180 degrees sooo yaw 180 pitch 0

### Expected Behavior

The yaw should be same, bcs item displays has already solved this problem with latest devbuild

### Additional Server Info

Fork: Purpur 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [x] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1985%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Purpur--1985%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Jo0001** [comment]
I can reproduce this with a 1.20(.1) client using the following command on a clean paper server
`/summon minecraft:text_display ~ ~1 ~ {text:'{"text":"ViaVersion"}',yaw: 0, pitch:0}`
