### ISSUE TITLE
Kick from server after change dimensions

### ISSUE THREAD

**Issue by VanyaNexus** [ViaVersion/ViaVersion#3384]
### `/viaversion dump` Output

https://dump.viaversion.com/2b03783ba9cabf8c2e8ca1d5833ba5491b8ed482c455501d581073baed5cf569

### Console Error

https://pastebin.com/sC2EHMDb

### Bug Description

When I teleport from the end world to the normal world, I get kicked from the server.

### Steps to Reproduce

1) Launching the server 1.19.2, I have a multipaper modification, but I don’t think it has much effect
2) Login with client 1.16.5
3) Go to the end portal
4) I teleport to the normal world with the /spawn command (I checked teleports to different positions, the result is the same)
5) I was kicked from the server

### Expected Behavior

I didn't get kicked

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--MultiPaper--%22effb4f0%22%20%28MC%3A%201.19.2%29](https://img.shields.io/badge/Platform-git--MultiPaper--%22effb4f0%22%20%28MC%3A%201.19.2%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 19 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-19%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.0): 8 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by VanyaNexus** [comment]
I tried it, the result is the same
https://dump.viaversion.com/575e6740b8e6386d3850993c47b08c9d3bf42dc87cba894c81f308841e67982a

**Comment by Barvalg** [comment]
![Platform: git--MultiPaper--%22effb4f0%22%20%28MC%3A%201.19.2%29](https://img.shields.io/badge/Platform-git--MultiPaper--%22effb4f0%22%20%28MC%3A%201.19.2%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.0): 8 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by VanyaNexus** [comment]
I try https://pastebin.com/5iJPEJ8b
https://dump.viaversion.com/f68a490f0a889cf14fa6a2324d2eb8daa71ea895f2d0080deddfc6b3eb2278c6

**Comment by Barvalg** [comment]
![Platform: git--MultiPaper--%22effb4f0%22%20%28MC%3A%201.19.2%29](https://img.shields.io/badge/Platform-git--MultiPaper--%22effb4f0%22%20%28MC%3A%201.19.2%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
You have a third-party plugin that is causing problems with chunk data entirely, this is likely to be caused by hCore or something else - a binary search would be suggested from here on out.

**Comment by VanyaNexus** [comment]
You were right, the orebfuscator plugin was to blame
