### ISSUE TITLE
Minecraft Bedrock crash

### ISSUE THREAD

**Issue by daniel-skopek** [ViaVersion/ViaVersion#3385]
### `/viaversion dump` Output

https://dump.viaversion.com/15fb000b15d3f80838caf512568823fb77346f64e0b90f3fd65b94834a092c3e

### Bug Description

If Bedrock edition players type "/" in chat, it will crash their entire Minecraft. It only happens on Bedrock edition, for example on Windows 10 (11) edition and maybe on Xbox. It works fine on the mobile Bedrock edition.

### Steps to Reproduce

1. Type „/” in chat
2. Minecraft crashed

### Expected Behavior

The Minecraft should not crash

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--15%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Pufferfish--15%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
ViaVersion doesn't do anything Bedrock related, ask Geyser if you use that.
