### ISSUE TITLE
1.19.4+ client can't join server

### ISSUE THREAD

**Issue by juzijun233** [ViaVersion/ViaVersion#3387]
### `/viaversion dump` Output

https://dump.viaversion.com/6bbeab99298a9962dc1774c4926d8b000b0d68ab5f8de37af84df44fa61b395d

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

1.19.4 & later (1.20.1) cannot log servers, they prompt link broken or login: null or the server you were previously on went down, you have been connected to a fallbakc server
1.19.2\1.18\1.17 can be entered normally, waterfall is the latest version, and the backend server is 1.17.1 purpur

### Steps to Reproduce

login in with 1.19.4/1.20.1 client

### Expected Behavior

1.19.4/1.20.1 should be able to join normally

### Additional Server Info

waterfall 1.20 #536

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1428%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Purpur--1428%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 19 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-19%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.0): 8 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Kichura** [comment]
Update to CI builds, also cloudnet is known to not work properly with our plugins.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1428%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Purpur--1428%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.0): 8 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1428%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Purpur--1428%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by 0utplay** [comment]
> Update to CI builds, also cloudnet is known to not work properly with our plugins.

What exactly makes viaversion not work with cloudnet?

**Comment by Kichura** [comment]
> > Update to CI builds, also cloudnet is known to not work properly with our plugins.
> 
> What exactly makes viaversion not work with cloudnet?

Cloudnet for some reason is not cooperating with our plugins properly and causes the translation systems to fail entirely. *(This issue has existed since 2017 from what's believed and likely is overriding the compatibility list)*

**Comment by 0utplay** [comment]
> > > Update to CI builds, also cloudnet is known to not work properly with our plugins.
> > 
> > What exactly makes viaversion not work with cloudnet?
> 
> Cloudnet for some reason is not cooperating with our plugins properly and causes the translation systems to fail entirely. *(This issue has existed since 2017 from what's believed and likely is overriding the compatibility list)*

I can't really grasp that as cloudnet v2 (2017) and cloudnet v3 are completely different applications that dont share anything in common. Furthermore viaversion seems to work partly for the user up to 1.19.4

**Comment by Kichura** [comment]
> > > > Update to CI builds, also cloudnet is known to not work properly with our plugins.
> > > 
> > > 
> > > What exactly makes viaversion not work with cloudnet?
> > 
> > 
> > Cloudnet for some reason is not cooperating with our plugins properly and causes the translation systems to fail entirely. _(This issue has existed since 2017 from what's believed and likely is overriding the compatibility list)_
> 
> I can't really grasp that as cloudnet v2 (2017) and cloudnet v3 are completely different applications that dont share anything in common. Furthermore viaversion seems to work partly for the user up to 1.19.4

So basically cloudnet is incompatible with 1.20/1.20.1 at this time or what is the current conclusion?

**Comment by 0utplay** [comment]
CloudNet v3 (3.4.5-RELEASE) supports servers up to 1.19.2. The v3 snapshot and cloudnet v4 support up 1.20.1 but how does that change the fact that he is running 1.17.1 and has problems when using a client above 1.19.3

**Comment by Kichura** [comment]
> CloudNet v3 (3.4.5-RELEASE) supports servers up to 1.19.2. The v3 snapshot and cloudnet v4 support up 1.20.1 but how does that change the fact that he is running 1.17.1 and has problems when using a client above 1.19.3

The thing is we already supported 1.19.3 and up since day one of their release, so i'm guessing the server owner has forgotten to update cloudnet to latest snapshot - unless it already is then something else seems to be causing this root problem entirely.

**Comment by 0utplay** [comment]
> > CloudNet v3 (3.4.5-RELEASE) supports servers up to 1.19.2. The v3 snapshot and cloudnet v4 support up 1.20.1 but how does that change the fact that he is running 1.17.1 and has problems when using a client above 1.19.3
> 
> The thing is we already supported 1.19.3 and up since day one of their release, so i'm guessing the server owner has forgotten to update cloudnet to latest snapshot - unless it already is then something else seems to be causing this root problem entirely.

I hardly believe that the support for a server version changes anything for the client support viaversion is offering but I will try to reproduce this asap

**Comment by kennytv** [comment]
That message alone isn't enough for us to diagnose anything, we need either a client error or the backend error
