### ISSUE TITLE
Unable to move when joining a server.

### ISSUE THREAD

**Issue by tjzzzzzz** [ViaVersion/ViaVersion#3388]
### `/viaversion dump` Output

https://youtu.be/1u8oWMreqDs

### Console Error

```
Put the paste.gg link or text here.
```
https://youtu.be/1u8oWMreqDs
We'll it isn't a console error so.

### Bug Description

https://youtu.be/1u8oWMreqDs
When joining this server for example, you're unable to move.

### Steps to Reproduce

https://youtu.be/1u8oWMreqDs

### Expected Behavior

I'd be able to move.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Jo0001** [comment]
1. Use a normal vanilla client and try to reproduce it on that
2. Follow the issue template when opening a new issue!
