### ISSUE TITLE
Compatibility with Damage Tilt mod

### ISSUE THREAD

**Issue by JoyousCreeper1059** [ViaVersion/ViaVersion#3389]
### Problem Description

in 1.19.4+ they fixed the damage tilt to go in the direction of the damage source, but it is still broken in earlier versions

### Solution Description

have a plug or something with [Damage Tilt](https://legacy.curseforge.com/minecraft/mc-mods/damage-tilt) so that the fixed damage tilt can be on older versions

### Additional Info

1.19.3 and below only

**Comment by Kichura** [comment]
Since this was an actual bug that lasted from MC 1.3.x - 1.19.3 and because viaversion doesn't touch on vanilla features in any way, the answer is simple;

We can't and we won't fix it.
