### ISSUE TITLE
Cannot invoke "io.netty.channel.Channel.isOpen()" because "channel" is null

### ISSUE THREAD

**Issue by Paulem79** [ViaVersion/ViaVersion#3390]
### `/viaversion dump` Output

https://dump.viaversion.com/b8efa8f9682e372604e196c715fc815f6f898239effbbda41123f0242e03a518

### Console Error

```
[Put the paste.gg link or text here.](https://paste.gg/p/anonymous/b5ec4c3f97c54162af801f1d7e2dee34)
```

### Bug Description

I my plugin code, I have this part
```java
PlayerJoinEvent event = new PlayerJoinEvent(herobrine.getHerobrine(), ChatColor.YELLOW + herobrine.getHerobrine().getName() + " joined the game");
Bukkit.getPluginManager().callEvent(event);
```
It makes a fake join message for a [ServerPlayer](https://mappings.cephx.dev/1.20.1/net/minecraft/server/level/ServerPlayer.html) (NMS)

Same issue with the latest dev release
https://paste.gg/p/anonymous/1adeae31d3d04fa79d074b62bed01cbf

### Steps to Reproduce

When executing this code, there is the ViaVersion's error

### Expected Behavior

I thought this will not happen

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--411%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--411%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 20 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-20%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Paulem79** [comment]
I mentioned it : 
Same issue with the latest dev release
https://paste.gg/p/anonymous/1adeae31d3d04fa79d074b62bed01cbf

**Comment by Paulem79** [comment]
https://dump.viaversion.com/f59e87bdb0d0f5b2761443283a6599c4c7fae4aedb9830224361b9b4532aa05b

**Comment by Barvalg** [comment]
![Platform: git--Paper--411%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--411%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Does this problem persist on 4.9.3-snapshot ?

**Comment by kennytv** [comment]
Fixed, but you *really* shouldn't be calling a player join for a non-player
