### ISSUE TITLE
Block breaking animation bug

### ISSUE THREAD

**Issue by LOCNetwork** [ViaVersion/ViaVersion#3392]
### `/viaversion dump` Output

https://dump.viaversion.com/0bf558195e1de5a9d715242bcb70585d570315d7312b91116fa25c586d874047

### Console Error

No error in Console

### Bug Description

If you have the server in 1.8 with the latest ViaVersion, when breaking blocks the breaking animation is kind of strange (from newer clients like 1.20 [Can also happen with a 1.8 client but rarely]). Using WindSpigot 1.8.8 server jar.

Video: https://youtu.be/l0BMu8wdCWk

### Steps to Reproduce

1. Start a server in 1.8.8 with ViaVersion.
2. Join with a client like 1.20.
3. Break a block

**NOTE:** I have noticed two players (one with a 1.20 client and the other with a 1.8 client) need to be in the same server at the same time.

### Expected Behavior

The breaking animation should be just like in Vanilla.

### Additional Server Info

I use a proxy (NullCordX) and TCPShield.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: WindSpigot%20Release%20v2.1.2%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-WindSpigot%20Release%20v2.1.2%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 20 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-20%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by LOCNetwork** [comment]
New dump: https://dump.viaversion.com/39a44271620ddcb259259abd2030781f66d70ccaf56a1c7f9b06ffc26df45e6e.

The issue still persists.

**Comment by Barvalg** [comment]
![Platform: WindSpigot%20Release%20v2.1.2%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-WindSpigot%20Release%20v2.1.2%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Cannot reproduce, This is very likely caused by a third-party plugin delaying animation ticks.
