### ISSUE TITLE
Packet Type: SET_SLOT, Type: FlatVarIntItem, Index: 4, Data: [{Unsigned Byte: 0}, {VarInt: 5}, {Short: 36}], Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$5 (Anonymous), Packet ID: 18

### ISSUE THREAD

**Issue by Overwrite987** [ViaVersion/ViaVersion#3394]
### `/viaversion dump` Output

dump.viaversion.com/b59ca25dfd6ae78aae236adba75db7c655f59bd3a7e73c878b3503056f18a0bb

### Console Error

```
https://paste.gg/p/anonymous/6182132100a94ca28433b6f702dd3252
```

### Bug Description

As the injured player describes, he broke the shalker, after which he began to kick. This error now occurs all the time when trying to log in. Both from new versions and from old ones.
Player getting this error if joining with 1.20 or 1.16 (via viaback)
![image](https://github.com/ViaVersion/ViaVersion/assets/92237090/0d45d343-1497-411f-beea-275482206e46)
And this error with 1.19.4 (server version)
![image](https://github.com/ViaVersion/ViaVersion/assets/92237090/473a848c-ff6d-4510-9247-16b3faf9c592)

### Steps to Reproduce

1) Download this saved items https://drive.google.com/file/d/1xfZ0T1N4mc22xNOkQZ1rMPHxGZ1eCjDk/view?usp=sharing
2) Place saved shulkerbox 
3) Breakit and pick it up in survival mode! (works only in survival)
4) You're kicked

### Expected Behavior

The player should not be kicked from the server

### Additional Server Info

Also server is using velocity with this plugins:
commandsync, commandwhitelist, fastmotd, floodgate, geyser, limboapi, limboauth, limboauth-social-addon, limbofilter, luckperms, matrixbungee, serverutils, skinsrestorer, velocity_tools

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Kichura** [comment]
Looks like a third party plugin is sending packets that are too large for server to handle or shulker has bad NBT data, and since the native server version is also affected; this essentially means it has nothing to do with us - therefore a binary search would be considered.
