### ISSUE TITLE
PLAYER_INFO DecoderException

### ISSUE THREAD

**Issue by anhcraft** [ViaVersion/ViaVersion#3397]
### `/viaversion dump` Output

https://dump.viaversion.com/0b40f53623d43b626b4c431e5d543fede11976005e0f218a5eea04d991c4959e

### Console Error

My network encountered this issue for a long time. We have tried to update ViaVersion/ViaBackwards to the latest development builds. But it seems the issue has not been fixed.

Logs: https://paste.md-5.net/ukubehupuz.cs

### Bug Description

- At first, players can join the server normally for days.
- Then, the issue occurs randomly
- Exception threw in Velocity console and since then, no one in the server can join

### Steps to Reproduce

Idk what caused this

### Expected Behavior

The players should join normally and if any error occurs, the player related to that problem is kicked, instead of spreading the error to everyone on the server

### Additional Server Info

I install ViaVersion/ViaBackward in the latest version Velocity proxy.
Two 1.16.5 sub-servers without ViaVersion/ViaBackward installed.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--bda1430d--b259%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--bda1430d--b259%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
Do you use Geyser / Floodgate?

**Comment by anhcraft** [comment]
> Do you use Geyser / Floodgate?

I used Geyser before and got this issue along with https://github.com/ViaVersion/ViaBackwards/issues/512
Then I tried to uninstall Geyser, and this issue still occurs.

**Comment by FormallyMyles** [comment]
This issue is likely Geyser related if you're using that but otherwise down to another plugin. I'd advise moving the Via plugins to your backend servers and removing from Velocity.
