### ISSUE TITLE
Bug when switching servers

### ISSUE THREAD

**Issue by MikkelHebel** [ViaVersion/ViaVersion#3401]
### `/viaversion dump` Output

https://dump.viaversion.com/29b2bf3a28963caf74717718f2019ec9d7cd4ccab1316f0a26b67d8b4e052ddf

### Console Error

No errors but my friend got this on her screen:
![viaver](https://github.com/ViaVersion/ViaVersion/assets/88710599/9e027b79-188e-41f5-90c4-bce10e1cb490)

### Bug Description

I'm hosting a server network running different versions.

**Servers:**
Bungeecord (Waterfall): Waterfall version git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536 by md_5
Lobby: git-Paper-381 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 42fecd0)
Skywars: git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

My friend had connected to the bungeecord and tried to switch from Lobby to Skywars and then got the error message above.
She's using 1.19.4 vanilla.

### Steps to Reproduce

1. Login to mc.blockhub.gg using 1.19.4
2. Try joining skywars.

### Expected Behavior

Should be able to join.

### Additional Server Info

I have the following plugins installed on my BungeeCord server: ACNotify, AntiPopup-Via-1, BungeeGuard, Litebans, nuvotifier, Geyser-BungeeCord, HubMagic-0.2.6, Plan, ViaBackwards-4.7.0, ViaRewind-2.03, Viaverison-4.7.0, VotingPlugin, ZulfBungee.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.20--R0.1--SNAPSHOT%3Aec41547%3A536](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.20--R0.1--SNAPSHOT%3Aec41547%3A536-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 22 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-22%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.0): 10 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-10%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3): 17 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.3)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by FormallyMyles** [comment]
Move viaversion to your backend servers, otherwise this issue is unfortunately a known one #2895
