### ISSUE TITLE
Paper 1.12.2 NAMED_ENTITY_SPAWN Packet Error

### ISSUE THREAD

**Issue by Ayouuuu** [ViaVersion/ViaVersion#3405]
### `/viaversion dump` Output

https://dump.viaversion.com/db94ba1fd87a0ef18ab72267d441f20549786b1677295eb41656fc0ff6cce4df

### Console Error

https://paste.gg/p/anonymous/8376b725223447ddb430a6b2d9977bd9

### Bug Description

Minecraft Client Version: `1.18.2`
Minecraft Server Version: `Paper version git-Paper-ci-16 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`
When I send a packet to a player using this code below, he will disconnect.
This code was 1.18.2.
```java
public static void spawnBot(Player p, int entityID, Location location, UUID value) {
        PacketContainer spawnContainer = new PacketContainer(PacketType.Play.Server.NAMED_ENTITY_SPAWN);
        spawnContainer.getIntegers().write(0, entityID);
        spawnContainer.getDoubles().write(0, location.getX()).write(1, location.getY()).write(2, location.getZ());
        spawnContainer.getUUIDs().write(0, value);

        sendPacket(p, spawnContainer);
    }
```

### Steps to Reproduce

1. Login with a 1.18.2 Client
2. Code a `spawnBot` plugin on `Minecraft 1.18.2`
3. Run with a `Paper 1.12.2 Server`
4. Test yourself with `spawnBot` 

### Expected Behavior

Disconnect.

### Additional Server Info

no

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--ci--16%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--ci--16%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 22 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-22%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.0): 12 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-12%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
That's not a valid spawn packet, vanilla is also erroring
