### ISSUE TITLE
Problems with the smithing table

### ISSUE THREAD

**Issue by moderator10000078** [ViaVersion/ViaVersion#3406]
### `/viaversion dump` Output

https://dump.viaversion.com/c46d3b73d4257e0ee3e90cfe47d1a88700e1cbc1de056a67c6ce1c1ff6418f02

### Bug Description

If you upgrade to client 1.20.1 the blacksmith table will not work, I also checked on the latest DEV build and I had the GUI from the furnace open, but you can already improve items on the blacksmith table.

### Steps to Reproduce

1 Login with 1.20.1 client
2 Try open smithing table

### Expected Behavior

on version 4.7.0 smithing table just won't open, on the latest DEV build the furnace GUI will open

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1632%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Purpur--1632%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 22 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-22%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.0): 12 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-12%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by FormallyMyles** [comment]
https://github.com/ViaVersion/ViaVersion/issues/3338
