### ISSUE TITLE
EntityPackets1_19_3$$Lambda$6364/0x00007fef6527ac90, Packet ID: 55

### ISSUE THREAD

**Issue by ttt0** [ViaVersion/ViaVersion#3409]
### `/viaversion dump` Output

https://dump.viaversion.com/2fc96f4ee03687ed01021a5360de03fa8b0143492ac94d478d60933156168baa

### Console Error

https://paste.gg/p/anonymous/a461634f0cb2442a9d9895ab0172d610

### Bug Description

https://paste.gg/p/anonymous/a461634f0cb2442a9d9895ab0172d610

### Steps to Reproduce

server start

### Expected Behavior

fixed

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1933%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Purpur--1933%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 22 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-22%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.0): 12 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-12%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by FormallyMyles** [comment]
This isn't a ViaVersion issue https://github.com/ViaVersion/ViaVersion/issues/3207
