### ISSUE TITLE
Via Version 1.20 Clients can't join correctly

### ISSUE THREAD

**Issue by ErzenXz** [ViaVersion/ViaVersion#3412]
### `/viaversion dump` Output

https://dump.viaversion.com/b75a8825bc9e1ae07dd4d1819b115023d161b383787a8f556ac91d3b26f30cf7

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/ae7b7021cc4d427296f59d3442ea2c25

### Bug Description

A lot of errors when using 1.20 on a server running 1.8 Paper.

First when i try to join my server using 1.20 even on 1.20 servers i get some errors that kick me out after 5-6 times it would let me in.
Second i have a bedwars server and in here if i place blocks too fast i would get stucked in blocks and sometimes fall, the only way to play is to put blocks slowly.

### Steps to Reproduce

1. Login with 1.20.x client into my server play.erzen.games
2. Go in Survival
3. After 4-5 kick errors i can join the server!

### Expected Behavior

Join the server without kicking me out!

### Additional Server Info

I am using Waterfall latest version and all the other versions work fine expect 1.20.x

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.20--R0.1--SNAPSHOT%3Aec41547%3A536](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.20--R0.1--SNAPSHOT%3Aec41547%3A536-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 22 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-22%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Kichura** [comment]
Likely a third-party plugin from the other side is causing viaversion to fail outright, Please consider doing a binary search or move viaversion to spigot/paper instead.

**Comment by ErzenXz** [comment]
Hello, i have to give you an update, i updated thr via version to the latest dev build, and there seem to be no errors.
There was probably a bug in the via version 4.7 and the later builds have probably fixed it. Thanks for the suggestion.  I keep you updated if i encounter any bugs.
