### ISSUE TITLE
Improper book view

### ISSUE THREAD

**Issue by road2react** [ViaVersion/ViaVersion#3413]
### General Information

ViaFabricPlus, Fabric API

### Bug Description

Books with non-plain text shows incorrectly

![image](https://github.com/ViaVersion/ViaFabricPlus/assets/93143714/6ad10778-a911-4ef9-b950-3e3755b59627)

Image from https://github.com/ViaVersion/ViaFabricPlus/issues/95#issuecomment-1546806631, and I get the same issue. Posted here to show the different issue separately.

### Steps to Reproduce

1. Log into Hypixel using 1.8.9.
2. Join Turbo Kart Racers without enabling the resource pack
3. Follow this message
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/93143714/586bfdb7-a54c-41df-b367-69c170fa31d1)

### Expected Behavior

This appears
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/93143714/ffe99b6a-d3ca-45bf-9113-611e65d897c0)

instead of a proper book.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Barvalg** [comment]
![Platform: 2.2.9--SNAPSHOT](https://img.shields.io/badge/Platform-2.2.9--SNAPSHOT-3498db?style=flat-square) </br>![ViaVersion (4.8.0-23w33a-SNAPSHOT): 14 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.8.0--23w33a--SNAPSHOT)-14%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards(4.8.0-23w33a-SNAPSHOT): 10 commits behind dev](https://img.shields.io/badge/ViaBackwards%20(4.8.0--23w33a--SNAPSHOT)-10%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by FlorianMichael** [comment]
Will be fixed in the next ViaFabricPlus release.
