### ISSUE TITLE
Cannot connect when ViaVersion is installed on Velocity 3.2

### ISSUE THREAD

**Issue by Alexciao** [ViaVersion/ViaVersion#3414]
### `/viaversion dump` Output

https://dump.viaversion.com/318541c1cde5bad070448e13899cb927d20696ce1dee5268568018f0f14da255

### Console Error

https://paste.gg/p/anonymous/6516d5cfccb3469c813cad7089f202c7

### Bug Description

When logging in with Velocity 3.2, I cannot connect.
I tried ViaBackwards and ViaVersion v4.7.0 and v4.7.1, both don't work.

### Steps to Reproduce

- Login with Minecraft 1.20.1
- Cannot join

### Expected Behavior

Be able to join.

### Additional Server Info

Velocity 3.2.0
Plugins:
- LibertyBans
- LastLoginAPI
- LimboAPI
- LimboAuth
- LimboReconnect
- LuckPerms
- MiniMotd
- Parties
- Send
- SkinsRestorer
- SlashHub
- TCPShield
- VelocityStaffChat
- ViaBackwards
- ViaVersion

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--be9ecf75--b261%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--be9ecf75--b261%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 22 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-22%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.0): 12 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-12%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by FormallyMyles** [comment]
ViaVersion isn't compatible with Limbo on velocity.

**Comment by Alexciao** [comment]
> ViaVersion isn't compatible with Limbo on velocity.

Is it compatible if I put it on all my backend servers?
