### ISSUE TITLE
[1.8s - 1.16+c] Attack speed attribute

### ISSUE THREAD

**Issue by ManInMyVan** [ViaVersion/ViaVersion#3419]
### Problem Description

I think the attack indicator showing up for a little bit looks a bit weird.

### Solution Description

If possible, add an option for when a 1.16+ (or whenever attributes were added) client connects to a 1.8.x server, to tell the 1.16 client that their attack speed attribute is very high (about 100 (or just make this option configurable)). If you give a player an attack speed attribute, the attack indicator doesn't show up for them (mostly, it still does for a brief time when switching items).

**Comment by Roadhog360** [comment]
The attack speed attribute could actually be set to 24 and that would completely stop the indicator from showing up.

**Comment by enqorman** [comment]
bump

**Comment by FlorianMichael** [comment]
Should be fixed in latest builds

**Comment by lowercasebtw** [comment]
lol I fixed this I think didn't I

**Comment by lowercasebtw** [comment]
pull request #4006
