### ISSUE TITLE
Error 1.20.2 rc1

### ISSUE THREAD

**Issue by Tsoccerguy3** [ViaVersion/ViaVersion#3422]
### `/viaversion dump` Output

https://dump.viaversion.com/2c4d1be471b2f36b87545f98f4b6de4d99f9bcc5e3eacd3f8ec2731e7270b265

### Console Error

```
Put the paste.gg link or text here.
```
https://mclo.gs/Hd5BPhl

### Bug Description

Logon with 1.20.2 rc1 client causes connection to fail. might be related to jukebox record being played
![2023-09-15_22 50 47](https://github.com/ViaVersion/ViaVersion/assets/22108822/5a96be51-7c92-4036-b1e8-6543a2e210ac)

### Steps to Reproduce

Logon with 1.20.2 rc1

### Expected Behavior

not crash

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--183%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--183%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.8.0-1.20.2-rc1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.8.0--1.20.2--rc1--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Thanks, fixed
