### ISSUE TITLE
Error while switching servers: Non [a-z0-9_.-] character in namespace of location: {\"text\":\"\"}

### ISSUE THREAD

**Issue by HippieBeak** [ViaVersion/ViaVersion#3424]
### `/viaversion dump` Output

https://dump.viaversion.com/23c0be4b1354a51f74b84b42840d17e6f396f579435fa38d3cc48a1d11da1b5e

### Console Error

```
[14:50:55 INFO]: HippieBeak joined the game
[14:50:55 INFO]: HippieBeak[/<REDACTED>] logged in with entity id 8414 at ([bedrock]19942.02192310543, 80.7245725186679, 7793.323600024131)
[14:50:55 INFO]: HippieBeak lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/0 (PacketPlayInTeleportAccept) was larger than I expected, found 34 bytes extra whilst reading packet 0
```

### Bug Description

Switching servers causes the following error to appear: https://cdn.discordapp.com/attachments/389139709429022721/1154489916982567033/Screen_Shot_2023-09-21_at_2.png

### Steps to Reproduce

1. Update to Waterfall 1.20.2 (build #537) 
2. Use 1.20.1 on the backend servers.
3. Install ViaVersion 4.8.0 on the backend servers.
4. Login to the server, and attempt to switch to any server.

### Expected Behavior

Players should be able to successfully connect without issues.

### Additional Server Info

We use Waterfall as our proxy, and ViaVersion on the backends. 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--25%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Pufferfish--25%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.8.0): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.0)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by xBengie** [comment]
Got the same problem but then immediately when trying to connect to server.

**Comment by Lewes** [comment]
We're also experiencing the same issue - we are also on Waterfall.

`Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: z: Non [a-z0-9_.-] character in namespace of location: {\"extra\":[{\"text\":\" \"},{\"color\":\"gray\",\"text\":\"You \"},{\"color\":\"gray\",\"text\":\"have \"},{\"color\":\"gray\",\"text\":\"friend \"},{\"color\":\"gray\",\"text\":\"requests \"},{\"color\":\"gray\",\"text\":\"from: \"},{\"color\":\"yellow\",\"text\":\"Jxson\"},{\"color\":\"gray\",\"text\":\"\"}],\"text\":\"\"}`

This is a generic chat message sent via ProxiedPlayer#sendMessage. This method is called async if that is of any help.

We're testing with BungeeCord instead of Waterfall now.

**Comment by Lewes** [comment]
We have now tested with BungeeCord. When switching server, they receive this error message instead:

```
Client disconnected with reason: EncoderException : java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.SystemChat in phase CONFIGURATION with direction TO_CLIENT @ io.netty.handler.codec.MessageToByteEncoder:125
```

**Comment by mrfloris** [comment]
Only paper here, no proxy. can't connect, already gave kenny some info over discord.

**Comment by gre3x** [comment]
In looking on the Discord it seems to be happening to many people. Are there any known work arounds for this?

**Comment by kennytv** [comment]
All of the above but what Floris mentioned are most likely Waterfall/Bungee issues
