### ISSUE TITLE
Spigot 1.19.2 -> Client 1.20.2

### ISSUE THREAD

**Issue by Will33ELS** [ViaVersion/ViaVersion#3427]
### `/viaversion dump` Output

https://dump.viaversion.com/d985ea653f4f3f025dfc21fab63ae908d8e93ba83abe130248e2c1d47fbefc60

### Console Error

No server error.
Client error
```
[10:13:48] [Render thread/WARN]: Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: net.minecraft.class_151: Non [a-z0-9_.-] character in namespace of location: {\"text\":\"\u00A78\u00A7l[\u00A79\u00A7lH\u00A78\u00A7l]\u00A7r \u00A76Connexion sous compte premium effectu\u00E9e.\"}
```

### Bug Description

Hello, I'm encountering an issue with players on version 1.20.2. They are getting disconnected instantly upon joining.

### Steps to Reproduce

1. Login with 1.20.2 client on Paper git-Paper-263 (MC: 1.19.2)

### Expected Behavior

So that the player can connect.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--263%20%28MC%3A%201.19.2%29](https://img.shields.io/badge/Platform-git--Paper--263%20%28MC%3A%201.19.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.0): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.0)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
That's a Bungee issue.
