### ISSUE TITLE
Lastest Version Viaversion Crash

### ISSUE THREAD

**Issue by SrathYT** [ViaVersion/ViaVersion#3429]
### `/viaversion dump` Output

https://dump.viaversion.com/5c6f0a09d4b6c4650cba9e05c14da30201446df560e13277966d773c5b29bc8b

### Console Error

https://pastebin.com/me6ytrj2

### Bug Description

Crashing on panel only 1.20.1 can join other version can't join

### Steps to Reproduce

1. crashing at panel
2. only can join at 1.20.1
3. can't join at other version
4. Viaversion, Viarewind, Viabackward disabled

### Expected Behavior

1.20.1 Can Join But others version can't join

### Additional Server Info

i use many plugins 62 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--194%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--194%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.8.0): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.0)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-Outdated!-red?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(2.0.3)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by SrathYT** [comment]
Barvalg Version Dev or normal?

**Comment by Jo0001** [comment]
Normal
