### ISSUE TITLE
1.20.2 does not work on bungeecord

### ISSUE THREAD

**Issue by ThrowerWay** [ViaVersion/ViaVersion#3431]
### `/viaversion dump` Output

N/A

### Console Error

Internal Exception: io.netty.handler.codec.DecoderException:
java lang.Indexoutofboundsexception: Index 23 out of bounds for length

(clientside)

### Bug Description

1.20.2 doesn't work at all on bungeecord, multiple people have this problem.

### Steps to Reproduce

Try logging into latest bungee server with viaversion on it on 1.20.2 vanilla

### Expected Behavior

Should work like every other previous update.

### Additional Server Info

N/A using waterfall if that matters.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Fill in the template properly
