### ISSUE TITLE
1.20.2 Players unable to join 1.20.1 server

### ISSUE THREAD

**Issue by mrunningmasterc** [ViaVersion/ViaVersion#3432]
### `/viaversion dump` Output

https://dump.viaversion.com/9d6b9a70c2af84490779761bc9c433a8fba72414b46c7caf1164ea848b88b225

### Console Error

```
 [TAB] ViaVersion returned unknown protocol version 764 for player TKDMonster1. This may result in plugin not working correctly for them.

 TKDMonster1 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 116
```

### Bug Description

I join on a 1.20.1 server with a 1.20.2 client with the newest via version installed.

### Steps to Reproduce

1. Login with a 1.20.2 client
2. Join 1.20.1 server with newest via version
3. Will be unable to log in

### Expected Behavior

Should be able to join a 1.20.1 server with a 1.20.2 client

### Additional Server Info

Players go through a proxy which on the backend servers has the via version, backwards, and rewind

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2060%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Purpur--2060%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.8.0): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.0)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
Update TAB, although note that there are issues with Bungee at the moment anyways.
