### ISSUE TITLE
1.20.2 Clients can see signs

### ISSUE THREAD

**Issue by markheaps** [ViaVersion/ViaVersion#3433]
### `/viaversion dump` Output

https://dump.viaversion.com/fc799c88548a5bb294fab8a88187bc785437a8e5cbfbfb8b65583e3b65f70f69

### Console Error

```

```

### Bug Description

I am running a 1.19.3 Server with the newest version of Viaverson with the client on 1.20.2.

When I place a sign, type 'Test', and then exit the menu, no text is displayed on the sign.

Already placed down signs are also all blank for the client.

### Steps to Reproduce

1. Login on 1.20.2
2. Place a sign
3. Enter some text
4. No text is shown

1. Login on 1.20.2
2. Look at a sign (will be blank)

### Expected Behavior

The sign's text should be displayed

### Additional Server Info

I use Bungee Cord and this happens on all my servers 1.19, 1.19.3, 1.17.1, 1.18.2

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--307%20%28MC%3A%201.19.2%29](https://img.shields.io/badge/Platform-git--Paper--307%20%28MC%3A%201.19.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.0): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.0)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by SpEeD11** [comment]
also getting this issue, cant see text on signs in 1.20.2
tried using latest official and dev build

**Comment by kennytv** [comment]
Can't reproduce
