### ISSUE TITLE
State Handling ain't right

### ISSUE THREAD

**Issue by sugisaru** [ViaVersion/ViaVersion#3435]
### `/viaversion dump` Output

https://dump.viaversion.com/6585a01ffbd2d6bff86a9d6966f3654b54244bf1d69ae4ef76193d71a096e616

### Console Error

```log
[18:32:17] [Netty Epoll Client IO #0/WARN]: Ignoring plugin channel in outgoing REGISTER: PERMISSIONREPL
--
2 | [18:32:17] [Netty Epoll Client IO #0/WARN]: Ignoring plugin channel in outgoing REGISTER: wdl\|init
3 | [18:32:17] [Netty Epoll Client IO #0/WARN]: ERROR IN Protocol1_9To1_8 IN REMAP OF TEAMS (0x3E)
4 | [18:32:17] [Netty Epoll Client IO #0/WARN]: ERROR IN Protocol1_9To1_8 IN REMAP OF TEAMS (0x3E)
5 | [18:32:17] [Netty Epoll Client IO #0/WARN]: ERROR IN Protocol1_9To1_8 IN REMAP OF SET_SLOT (0x2F)
6 | [18:32:17] [Netty Epoll Client IO #0/WARN]: ERROR IN Protocol1_9To1_8 IN REMAP OF SET_SLOT (0x2F)
7 | [18:32:17] [Netty Epoll Client IO #0/WARN]: ERROR IN Protocol1_9To1_8 IN REMAP OF SET_SLOT (0x2F)
8 | [18:32:17] [Netty Epoll Client IO #0/WARN]: ERROR IN Protocol1_9To1_8 IN REMAP OF SET_SLOT (0x2F)
9 | [18:32:17] [Netty Epoll Client IO #0/WARN]: ERROR IN Protocol1_9To1_8 IN REMAP OF SET_SLOT (0x2F)
10 | [18:32:17] [Netty Epoll Client IO #0/WARN]: ERROR IN Protocol1_9To1_8 IN REMAP OF SET_SLOT (0x2F)
11 | [18:32:17] [Netty Epoll Client IO #0/WARN]: ERROR IN Protocol1_9To1_8 IN REMAP OF SET_SLOT (0x2F)
12 | [18:32:17] [Netty Epoll Client IO #0/WARN]: ERROR IN Protocol1_9To1_8 IN REMAP OF SET_SLOT (0x2F)
13 | [18:32:17] [Netty Epoll Client IO #0/WARN]: ERROR IN Protocol1_9To1_8 IN REMAP OF SET_SLOT (0x2F)
14 | [18:32:17] [Netty Epoll Client IO #0/WARN]: ERROR IN Protocol1_9To1_8 IN REMAP OF SET_SLOT (0x2F)
15 | [18:32:17] [Netty Epoll Client IO #0/WARN]: ERROR IN Protocol1_9To1_8 IN REMAP OF SET_SLOT (0x2F)
16 | [18:32:17] [Render thread/WARN]: Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet play/24 (class_2658) was larger than I expected, found 11 bytes extra whilst reading packet 24
```

### Bug Description

<details align="left">
<summary>Screenshots</summary>
<img src="https://github.com/ViaVersion/ViaVersion/assets/54220441/298e9d32-1798-44b0-9cad-5f03ce77c4b5"></img>
<img src="https://github.com/ViaVersion/ViaVersion/assets/54220441/8e7167ac-4f41-478b-af29-600f88108c4c"></img>
</details>
Platform: Fabric - ViaFabricPlus-2.9.0 [1.20.2]<br>
Selected Protocol: 1.8.x<br>
Tested Server: esta.land<br><br>
Why is it an ViaVersion related issue?<br>
Well, the connection states are wrong iirc (FlorianMichael told me). (1.7.10 smh. works tho)

### Steps to Reproduce

- Install Fabric 1.20.2 [0.14.22]
- Install Fabric Api
- Install ViaFabricPlus 2.9.0
- Launch with JDK-17+
- Select Protocol 1.8.x
- Join `esta.land`
- Done ✔️ (yippeee)

### Expected Behavior

Not getting kicked?

### Additional Server Info

BungeeCord-1.19
PaperSpigot (prolly 1.8.9)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 2.2.9](https://img.shields.io/badge/Platform-2.2.9-3498db?style=flat-square) </br>![ViaVersion (4.8.0): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.0)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
That's not state related

**Comment by kennytv** [comment]
Hotfixed in https://github.com/ViaVersion/ViaVersion/commit/8a0e1876212fbd1371376476cd0ae44943467fa0
