### ISSUE TITLE
Chat error message

### ISSUE THREAD

**Issue by BicigliKepu** [ViaVersion/ViaVersion#3438]
### `/viaversion dump` Output

https://dump.viaversion.com/82846e490167681afdf28b316987f4cc04779bc39c3a1e35c3782dd315d8e5a0

### Console Error

It's only in the client-side logs

[14:50:03] [Render thread/INFO]: [System] [CHAT] BicigliKepu joined the game
[14:50:03] [Render thread/INFO]: [System] [CHAT] Can't deliver chat message, check server logs: BicigliKepu joined the game

### Bug Description

Using ViaVersion on a 1.20.1 server and connecting to it with 1.20.2 will result in a chat error message on join like this: 
![image](https://github.com/ViaVersion/ViaVersion/assets/145910739/a61e7fb8-8a5a-4a79-a60f-0d0a2924d86e)

I tried with Paper and Spigot, on Spigot it's the same message on 1st join but after that it doesn't happen (?), meanwhile on Paper it happens on every join

### Steps to Reproduce

1. 1.20.1 Paper server
2. ViaVersion 4.8.0
3. Join the server with 1.20.2 Minecraft

### Expected Behavior

No error message on chat

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--196%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--196%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by HippieBeak** [comment]
I'm also experiencing this issue, seems to happen for the first few messages for me - is this confirmed to be a via version issue? Can't find anything reported elsewhere.
<img width="653" alt="Screenshot 2023-09-30 at 9 22 19 PM" src="https://github.com/ViaVersion/ViaVersion/assets/15806196/86a3285d-5d76-414a-9f79-d662f9eea1e1">

**Comment by Kas-tle** [comment]
I guess this implies there is a mismatch between what the server thinks ChatVisibility is and what the client has it set to? There is now a Client Information packet sent from the client for config phase, but maybe this is not being interpreted correctly. I don't see anything weird on the client side that would force this to hidden during the config phase.

**Comment by Ghost-chu** [comment]
I can also confirm this issue, I don't have installed ChatVisibility, but it to happen for the first few messages for me on every single backend server that installed ViaVersion + ViaBackwards.

**Comment by kennytv** [comment]
Does this still happen with 4.9.x?

**Comment by HippieBeak** [comment]
Yes, it is still happening on the latest version.

**Comment by NotAlexNoyle** [comment]
I can reproduce this with the latest ViaVersion on a 1.19.4 server and a 1.20.2 client. LAN.

**Comment by Tokkeno** [comment]
> ### `/viaversion dump` Output
> https://dump.viaversion.com/82846e490167681afdf28b316987f4cc04779bc39c3a1e35c3782dd315d8e5a0
> 
> ### Console Error
> It's only in the client-side logs
> 
> [14:50:03] [Render thread/INFO]: [System] [CHAT] BicigliKepu joined the game [14:50:03] [Render thread/INFO]: [System] [CHAT] Can't deliver chat message, check server logs: BicigliKepu joined the game
> 
> ### Bug Description
> Using ViaVersion on a 1.20.1 server and connecting to it with 1.20.2 will result in a chat error message on join like this: ![image](https://private-user-images.githubusercontent.com/145910739/270165215-a61e7fb8-8a5a-4a79-a60f-0d0a2924d86e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4OTQ2NzcsIm5iZiI6MTcwMzg5NDM3NywicGF0aCI6Ii8xNDU5MTA3MzkvMjcwMTY1MjE1LWE2MWU3ZmI4LThhNWEtNGE3OS1hNjBmLTBkMGEyOTI0ZDg2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOVQyMzU5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjY2YjE1ZTg0YTZiOWMzMDI2OTk0OTBlMDU1M2I4YzE1MmViODdjN2Y0YjYyYjcwM2VlYWU2ZmYwZTA5Mjc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DhshIoyk_yxJ_mS7P8GBxxXYx6Lf7P_NYhu4aGK66mY)
> 
> I tried with Paper and Spigot, on Spigot it's the same message on 1st join but after that it doesn't happen (?), meanwhile on Paper it happens on every join
> 
> ### Steps to Reproduce
> 1. 1.20.1 Paper server
> 2. ViaVersion 4.8.0
> 3. Join the server with 1.20.2 Minecraft
> 
> ### Expected Behavior
> No error message on chat
> 
> ### Additional Server Info
> _No response_
> 
> ### Checklist
> * [x]  Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
> * [x]  I have included a ViaVersion dump.
> * [x]  If applicable, I have included a paste (**not a screenshot**) of the error.
> * [x]  I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

Can reproduce this with any client version higher than 1.19.4 while server being on 1.19.4, doesn't happen with versions lower than 1.19.4.

**Comment by Barvalg** [comment]
![Platform: git--Paper--196%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--196%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.8.1--SNAPSHOT)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by UnitedCraft** [comment]
That issue still exists on latest versions

**Comment by FlorianMichael** [comment]
Can't reproduce with latest ViaVersion, if the issue still exists, create a new issue.

**Comment by Kichura** [comment]
Still can reproduce this on Paper 1.19.4 and ViaVersion 4.9.3.

**Comment by AntoninoScordino** [comment]
> Still can reproduce this on Paper 1.19.4 and ViaVersion 4.9.3.

Same here, but on server being 1.20.1 (`git-Paper-196`) and client being 1.20.4.

**Comment by FlorianMichael** [comment]
Looks like the issue only appears when running a cracked server (or a bungee/velocity sub server)

**Comment by AntoninoScordino** [comment]
> running a cracked server

Not in my case, I'm using `online-mode: true`.
 * Dump: [link](https://dump.viaversion.com/aa5a1657bde27b77eb797ca6a0a99c20eedd93109a92b22fbf625cbeac096756
)

**Comment by Barvalg** [comment]
![Platform: git--Paper--196%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--196%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Brasil150** [comment]
It's still happening in 1.19.4

**Comment by llokS** [comment]
This is still happening on the latest 4.10.3 snapshot.

https://dump.viaversion.com/b786287a2dae23f77a51c18e7f0d7344527e375416cb5a9302a98cec8feb8ea6

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2062%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Purpur--2062%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.10.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Outfluencer** [comment]
BUMP

**Comment by Incluuu** [comment]
![image](https://github.com/ViaVersion/ViaVersion/assets/67196311/0060e838-38ab-4472-9b75-8ad9c71b2ac8)
This error appears in minecraft client above 1.20.1, for versions below 1.20.1 there is no error in chat.
