### ISSUE TITLE
Auto-updater

### ISSUE THREAD

**Issue by chelminski** [ViaVersion/ViaVersion#3439]
### Problem Description

I don't see any point in checking every time for a new version of ViaVersion and updating it manually on each server and proxy.

### Solution Description

Adding to config.yml
auto-update: true/false
interval: 86400 #in minutes, in case of "0" value this is disabled
version: stable/dev
auto-restart: true/false #in case of new version found

Additional context

If true in config, the server would check whether a new version of ViaVersion is available during startup (or according to the charmonogram), and the version would be downloaded. Depending on the value of auto-restart, the new version would be loaded.

**Comment by Jo0001** [comment]
No, see https://github.com/ViaVersion/ViaVersion/issues/317#issuecomment-211128526
+I wouldn't personally update via every few days, I'd just update it when you run into issues / every month or so
