### ISSUE TITLE
Client error: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: Index 23 out of bounds for length 9

### ISSUE THREAD

**Issue by LoyalPineapple** [ViaVersion/ViaVersion#3441]
when joining world

Client error:
Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: Index 23 out of bounds for length 9

### Steps to Reproduce

721 viaversion 
323 viabackwards
1.20.1 paper server
1.20.2 waterfall
1.20.2 client

### Expected Behavior

join the world

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Follow the issue template
