### ISSUE TITLE
[1.20.2] Skin layers disappear on server switch

### ISSUE THREAD

**Issue by clrxbl** [ViaVersion/ViaVersion#3442]
### `/viaversion dump` Output

https://dump.viaversion.com/516367db302c455bff0cb3331b44d61570d6c1984a4d899ac80f4e5f5a79aabc

### Bug Description

Skin layers disappear on server switch when translating from 1.20.1 to 1.20.2 (tested on 1.19.4 to 1.20.2 aswell).
Client sometimes logs the following warning:
`Signature is missing from Property textures`

### Steps to Reproduce

1. Login with 1.20.2 client
2. Switch to another server on the same proxy

### Expected Behavior

Skin layers should not disappear on server switch

### Additional Server Info

Running https://github.com/ViaVersion/ViaVersion/commit/840770a350bfae0f3d839d62969407ba87d5ed61 on Velocity 3.2.0-b265. No plugins other than ViaVersion on the proxy; backend servers are stock Paper without plugins.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--19abb909--b265%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--19abb909--b265%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by LaserSlime** [comment]
This is still happening for me on the latest version.

**Comment by clrxbl** [comment]
Can confirm that while the commit initially fixes it (tested it myself with server switching), this still appears to be an issue albeit more sporadic now.

**Comment by LaserSlime** [comment]
This happens very consistently for me. Like I don't think there has ever been a time where I switched servers and it didnt happen.

**Comment by clrxbl** [comment]
Downgraded to https://github.com/ViaVersion/ViaVersion/commit/cabb95a3a4817a899db4902dcf1821c6c8627d4a for now

**Comment by LaserSlime** [comment]
> Downgraded to [cabb95a](https://github.com/ViaVersion/ViaVersion/commit/cabb95a3a4817a899db4902dcf1821c6c8627d4a) for now

Does that fix it?
