### ISSUE TITLE
On player with 1.7.10 join error appear on console

### ISSUE THREAD

**Issue by EURedBoy** [ViaVersion/ViaVersion#3444]
### `/viaversion dump` Output

https://dump.viaversion.com/0d902b58ab92887f42003feb568c82b2ed73e4d9acfaad3f5f47c7fa7076cf78

### Console Error

```
[Put the paste.gg link or text here.](https://paste.gg/p/anonymous/26cf6f71e5254d9bb9d80ec0ca9a8839)
```

### Bug Description

When a player join using 1.7.10 this error appears and his client crash

I also use this code on player join (before updating it was working):

![image](https://github.com/ViaVersion/ViaVersion/assets/69308679/389a4f33-9e7a-4c68-b00c-cb7d740a365f)
![image](https://github.com/ViaVersion/ViaVersion/assets/69308679/004f7809-90ca-454b-9415-ef01ae07615d)

### Steps to Reproduce

1. Login with an 1.7.10 client

### Expected Behavior

The client should join

### Additional Server Info

I use velocity and nachospigot
These are on my nachospigot server
![image](https://github.com/ViaVersion/ViaVersion/assets/69308679/bc689c4b-3507-40ab-8b14-251688516ca1)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--NachoSpigot--%221e3f1c9%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--NachoSpigot--%221e3f1c9%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by EURedBoy** [comment]
I'm already using the latest version

New dump: https://dump.viaversion.com/0d902b58ab92887f42003feb568c82b2ed73e4d9acfaad3f5f47c7fa7076cf78

**Comment by Barvalg** [comment]
![Platform: git--NachoSpigot--%221e3f1c9%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--NachoSpigot--%221e3f1c9%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Jo0001** [comment]
Works fine for me on a fresh testserver. A plugin is sending invalid meta data. To out which do a binary plugin search:

1. Remove half of the existing plugins and put them aside for now,
2. Run the server again,
3. Is it still creating errors from there?

(If yes; Repeat from step 1 with current items)
(If not; Swap out the current plugins with the ones set aside and repeat from step 1)

4. Repeat process until problematic plugin/s are found.
