### ISSUE TITLE
Custom potion effects aren't shown (easily reproducible)

### ISSUE THREAD

**Issue by realriccio** [ViaVersion/ViaVersion#3448]
### `/viaversion dump` Output

not needed

### Console Error

no console errors

### Bug Description

Creating any potion with a couple custom effects makes them invisible in 1.20.2 on a 1.20.1 server.
1.20.1:
![1 20 1](https://github.com/ViaVersion/ViaVersion/assets/53489044/bc389a32-e114-4914-a129-a097f6272be0)
1.20.2:
![1 20 2](https://github.com/ViaVersion/ViaVersion/assets/53489044/35a62a38-8220-49b9-a297-7d3dd7add065)

### Steps to Reproduce

Example command to create a potion: /give @s minecraft:potion{Potion:"minecraft:uncraftable",CustomPotionEffects:[{Id:10,Amplifier:5,Duration:100000,Ambient:1b},{Id:21,Amplifier:5,Duration:100000,Ambient:1b},{Id:29,Duration:100000,Ambient:1b}]}
To reproduce just put your mouse on the potion on 1.20.2 with viaversion installed on a 1.20.1 server.

### Expected Behavior

The effects should be visible on all versions.

### Additional Server Info

I'm using PaperMC and ViaVersion (latest DEV build) without any other plugins or modifications on stock config.

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [ ] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>
