### ISSUE TITLE
Players can't join in 1.20.2

### ISSUE THREAD

**Issue by Ferogreywolf7** [ViaVersion/ViaVersion#3449]
### `/viaversion dump` Output

https://dump.viaversion.com/a4cb100eb0dc77cd7c47815c4f363d74dadcfbefa4763db4ff27e644a1531a3f

### Console Error

Console error message when the player attempts to join - https://paste.gg/p/anonymous/cce53d0572fe4009975ad31a9a8a3f69
General error https://paste.gg/p/anonymous/bca50ca1caab41838a32f6114dd982a7

### Bug Description

Player sees an error message that the packet size is bigger than expected

### Steps to Reproduce

Log in with 1.20.2 client

Long error messages in console

### Expected Behavior

Player should log in normally

### Additional Server Info

Aternos paper server, no other plugins apart from via-backwards
Have a few world gen datapacks which all use vanilla blocks
Was able to use the server the other day weirdly and removed anything that was changed

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--202%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--202%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.0): 14 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.0)-14%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by 4L0N50asd** [comment]
I'm having this issue too, just tried version ViaVersion-4.8.1 Build 729,
Viaversion Dump: https://dump.viaversion.com/2f44fa8a6553f25b46a945bfbe3446104722f378b45651bad1e5ad49a7d9a275
Console error: https://paste.gg/p/anonymous/735dc29e7d414f698db0be995d4316e2/files/a150d4eca1c74d90a57aa1f3c3f5fc5b/raw

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Af486a25%3A1737](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Af486a25%3A1737-3498db?style=flat-square) </br>![Proxy is 11 builds behind](https://img.shields.io/badge/Your%20proxy%20is%2011%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.8.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.8.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
If you're on 4.8.1, you will definitely see a different error. Please open a new issue with it
