### ISSUE TITLE
1.12.1 and below clients kicked when multiple players are joining concurrently

### ISSUE THREAD

**Issue by Packsolite** [ViaVersion/ViaVersion#3450]
### `/viaversion dump` Output

https://dump.viaversion.com/0f56ccabdb8ef8ce540eed1a5a090ffb230465395e20cf6e7d83bc02378ebd30

### Console Error

https://haste.smashmc.eu/jixogoyahu

### Bug Description

As of ViaVersion 4.8 we get many different exceptions in our logs. Most common is a NullPointerException when accessing the inventory or entity tracker.
```
[21:11:59] [epollEventLoopGroup-3-14/WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "com.viaversion.viaversion.protocols.protocol1_9to1_8.storage.InventoryTracker.getInventory()" because "inventoryTracker" is null
[21:11:59] [epollEventLoopGroup-3-14/WARN]: 	at com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.InventoryPackets$3.lambda$register$1(InventoryPackets.java:128)
```

Players are kicked from the server for:

![image](https://github.com/ViaVersion/ViaVersion/assets/102829507/5d35479f-6c56-46aa-aa1f-e5293b06ae68)

Edit: It seems like only 1.20.1 and below clients are affected, never got kicked with a 1.20.2 client.

### Steps to Reproduce

Run latest ViaVersion 4.8.1-SNAPSHOT on an 1.8 paper server with a few players.
Seems to occur when multiple 1.20.1 players are joining at the same time, e.g. when a game server went offline and a bunch of players are sent to the lobby. It is not always reproducable, but the chance seems to increase relative to the amount of players connected.

### Expected Behavior

To not spam the logs.

### Additional Server Info

We're running the server behind a waterfall proxy. ViaVersion is installed on the backend servers only.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--CurrySpigot--unknown%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--CurrySpigot--unknown%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Are you using BungeeCord?

**Comment by Packsolite** [comment]
> Are you using BungeeCord?

As clearly stated in the bug report: yes, we're running bungeecord (waterfall to be precise) and have viaversion installed on the backend servers (paper).

**Comment by kennytv** [comment]
Most likely caused by either the Spigot fork or another plugin

**Comment by Packsolite** [comment]
We can reproduce this on paper 1.19 aswell. Should we create an issue on paper site?
