### ISSUE TITLE
Can't connect to server with 1.20.2

### ISSUE THREAD

**Issue by SiriHackYT** [ViaVersion/ViaVersion#3451]
### `/viaversion dump` Output

https://dump.viaversion.com/168f03c2785c50d22582b01fbee573bc6c57e4e531993e7ca02ad36f7fce0f34

### Console Error

[Put the paste.gg link or text here.](https://paste.gg/p/anonymous/e905104f8c2d45c093eb1526fd80cf43)

### Bug Description

Connect on Velocity and error DecoderException
![image](https://github.com/ViaVersion/ViaVersion/assets/49961233/2f3af33f-cb16-45a8-ac6a-cbc2878ad947)

### Steps to Reproduce

Login on Velocity with 1.20.2 client

### Expected Behavior

Connect on the spigot and just play

### Additional Server Info

Velocity with LimboAPI maybe (There is only the plugin I don't go through any limbo of this plugin)
Viaverision is on Proxy and Backend spigot
(Because velocity doesn't work with 1.20.2)

### Checklist

- [ ] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--37fedf50--b260%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--37fedf50--b260%29-3498db?style=flat-square) </br>![Proxy is 5 builds behind](https://img.shields.io/badge/Your%20proxy%20is%205%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.8.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Remove ViaVersion from thep roxy
