### ISSUE TITLE
Error when connecting to NanoLimbo with ViaVersion on Velocity

### ISSUE THREAD

**Issue by vixtordev** [ViaVersion/ViaVersion#3452]
### `/viaversion dump` Output

https://dump.viaversion.com/582ccd6cabb99a735a8055157b94932c34f8393a9d370d3eac4b69f5be7fbf4e

### Console Error

https://paste.gg/p/anonymous/730fe532187749e2a92c68b25293f90c

### Bug Description

I try to connect to NanoLimbo v1.5.2 but it doesn't work 

Source:
https://github.com/nan1t/NanoLimbo

### Steps to Reproduce

1. Join the server
2. Try to go to the limbo server

### Expected Behavior

Should send me to the server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--19abb909--b265%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--19abb909--b265%29-3498db?style=flat-square) </br>![ViaVersion (4.8.0): 16 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.0)-16%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Kichura** [comment]
ViaVersion is not compatible with limbo, Move it to the backend servers instead. *(+ Velocity at time of writing this is currently not 1.20.2 compatible)*

**Comment by vixtordev** [comment]
Thanks 👍
