### ISSUE TITLE
Kick upon setting beacon's secondary power

### ISSUE THREAD

**Issue by Yive** [ViaVersion/ViaVersion#3455]
### `/viaversion dump` Output

https://dump.viaversion.com/abec80799d6c5a461f96deed346c77ef3a9f503776308164fc5dfad77e962440

### Console Error

https://paste.gg/p/anonymous/7a29f72eaade434c91bb88099783ac69

### Bug Description

Setting the secondary power to the 2nd level of the primary power will cause the client to get kicked.

### Steps to Reproduce

1. Login with 1.20.2
2. Build a full beacon
3. Set the primary power to Speed
4. Set the secondary power to Speed II
5. Get kicked for NullPointerException

### Expected Behavior

Secondary power applies and the user doesn't get kicked.

### Additional Server Info

No proxy was used, just a newly created paper server with only ViaVersion installed.

Note: A private fork of pufferfish was used to force the server to print out the error in the paste link.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--196%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--196%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
