### ISSUE TITLE
[1.12.2 -> 1.20.2] doesn't work

### ISSUE THREAD

**Issue by andrew121410** [ViaVersion/ViaVersion#3456]
### `/viaversion dump` Output

https://dump.viaversion.com/0d6949cbf03bb0326e0b2400686f67d3e8fc5e2e6255966166ac691158c6d5c6

### Console Error

```
https://mclo.gs/G0maaYv
```

### Bug Description

Just when joining the server, it doesn't work.

### Steps to Reproduce

I haven't tested without any plugins, but I'm guessing it doesn't matter though maybe?

1. Make 1.12.2 server
2. Install ViaVersion
3. Try joining the server on 1.20.2

### Expected Behavior

Be able to join the server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by andrew121410** [comment]
Ok, I made a paper 1.12.2 server, without any plugins except for ViaVersion and the issue still is present, but a different error?
https://mclo.gs/RnEyJqL

**Comment by kennytv** [comment]
Should maybe be fixed with https://github.com/ViaVersion/ViaVersion/commit/429e4f0bff9ff389ad5e3c1923fa15256aedd82c, otherwise if you're running Bungee, that could be the problem

**Comment by andrew121410** [comment]
Yep that fixed it, Thank you!
