### ISSUE TITLE
"Non character in namespace of location" - Joining with 1.20.2 client

### ISSUE THREAD

**Issue by freak-dk** [ViaVersion/ViaVersion#3458]
### `/viaversion dump` Output

https://dump.viaversion.com/7f7efc1b97e522102d0592726e1067224229524560372a5ddaef9f9bcd62e982

### Console Error

```
[Put the paste.gg link or text here.](https://paste.gg/p/anonymous/eeb92bb1007f403fb88c3924c814e1bf)
```

### Bug Description

1.20.2 clients are unable to join my 1.8.8 server, error in the log upon joining.

### Steps to Reproduce

Latest 1.8.8 PaperSpigot
Latest ViaVer dev build / or stable, tried both.

I've made sure to remove all plugins possible in the error log.

### Expected Behavior

Seeing this kick error upon joining: https://gyazo.com/8431c2b3fb58c35bd1b82d3299cf4130

Client log says the same thing, nothing more:
[09:44:00] [Render thread/WARN]: Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: z: Non [a-z0-9_.-] character in namespace of location: {\"text\":\"\"}

### Additional Server Info

I use Bungeecord, (Waterfall).
Minimal plugins, Worldguard+Worldeidt, Vault, Luckperms and Viaversion.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--%228b18730%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--%228b18730%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1-SNAPSHOT): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1--SNAPSHOT)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
Update
