### ISSUE TITLE
cant join my 1.20.2 server

### ISSUE THREAD

**Issue by RedstoneGyerek** [ViaVersion/ViaVersion#3459]
### `/viaversion dump` Output

https://dump.viaversion.com/cbcc44c8005004d50683ba7e74b80c7743206433b0cb031e92b47aa14a4547c2

### Console Error

conosle log: https://mclo.gs/5bAQGaf

### Bug Description

i have a 1.20.2 server with the latest version of viaversion
it throws a 'packet too large' error at me when i try to join with 1.20

### Steps to Reproduce

start the server
wait for it to start
try to join with a 1.20 fabric client
seeing tons of warning in the console and gets the packet error in game

### Expected Behavior

it should let me in and let me be

### Additional Server Info

![Képernyőkép 2023-09-29 154829](https://github.com/ViaVersion/ViaVersion/assets/46848050/83538024-e5e2-4373-bcb9-84bba37df68a)
![Képernyőkép 2023-09-29 155825](https://github.com/ViaVersion/ViaVersion/assets/46848050/3e073fa7-1439-444d-8fe3-b995b8adaa9b)

Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 2/0 (class_2090) was larger than I expected, found 7 bytes extra whilst reading packet 0

running spigot/bukkit on aternos with these plugins:
SimpleTpa,
WorldEdit,
BetterCommandSpy,
Join-Leave,
RHLeafDecay,
ClearLag,
AuthMe,
CrackShot,
NoChatReports,
ViaVersion,
SuperVanish,
Tablist,
InvSeePlusPlus,
floodgate,
ViaBackwards,
WorldGuard,
ViaRewind,
SkinsRestorer,
DeadlyDisasters,
InvSeePlusPlus_Clear,
InvSeePlusPlus_Give,
Geyser-Spigot,
SmoothTimber

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3897--Spigot--a0f3d48--99aafc2%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-3897--Spigot--a0f3d48--99aafc2%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.0): 18 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.0)-18%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Halhadus** [comment]
Same error, ViaProxy dump: https://dump.viaversion.com/e2740b4f8aad1424cdd0ff0e3ed30482982f45ac307b6a558a5264f317a54e08

**Comment by Barvalg** [comment]
![Platform: 2.2.11--SNAPSHOT](https://img.shields.io/badge/Platform-2.2.11--SNAPSHOT-3498db?style=flat-square) </br>![ViaVersion (4.9.0-1.20.3-pre4-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--1.20.3--pre4--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-1.20.3-pre3-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--1.20.3--pre3--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(3.0.4-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(3.0.4--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>
