### ISSUE TITLE
[1.12.2 -> 1.20.2] doesn't work

### ISSUE THREAD

**Issue by Incluuu** [ViaVersion/ViaVersion#3460]
### `/viaversion dump` Output

https://dump.viaversion.com/2223366c45ed7ffcc3942859942136394b7c2c4a7e03b398940a19b88156dbbf

### Console Error

![image](https://github.com/ViaVersion/ViaVersion/assets/67196311/5676158d-1f79-4d08-9d04-74fb346736ab)

### Bug Description

Just when joining the server, it doesn't work.

### Steps to Reproduce

1. Make 1.12.2 server 
2. Install ViaVersion, ViaBackWards and rewind
3. Try joining the server on 1.20.2

### Expected Behavior

Be able to join the server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1618%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1618%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.8.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Incluuu** [comment]
https://pastebin.com/V3UXbQFr

**Comment by SunshroomChan** [comment]
> https://pastebin.com/V3UXbQFr

I got the same issue maybe both on Backends server or turned off bungeemode set to false its the same issue as you

**Comment by qhoeger** [comment]
Having this issue as well, what sucks is that via version is required to get geyser working to have bedrock players play on server versions 1.20.1 and earlier...

**Comment by kennytv** [comment]
Update to -dev builds, but note that BungeeCord currently is not supported with 1.20.2 clients
