### ISSUE TITLE
Viaversion bungee still doesn't work

### ISSUE THREAD

**Issue by ThrowerWay** [ViaVersion/ViaVersion#3461]
### `/viaversion dump` Output

https://dump.viaversion.com/...

### Console Error

IllegalArgumentException: can't parse argument number

### Bug Description

Viaversion on bungeecord is still non functional, on latest viaversion dev on latest waterfall build, all plugins updated.

### Steps to Reproduce

Log in with 1.20.2 client to 1.20.1 server

### Expected Behavior

It should work, worked before always.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Follow the issue template
