### ISSUE TITLE
Players still can't join with 1.20.2

### ISSUE THREAD

**Issue by MATRIX-feather** [ViaVersion/ViaVersion#3464]
### `/viaversion dump` Output

https://dump.viaversion.com/6ae802d9eafd97cfd12a76fdb0ff04bbae04cc4ae8250d4dfcbc11fc3c880898

### Bug Description

Backend servers kick player with "outdated server" message

### Steps to Reproduce

1. Setup waterfall and an 1.20.1 server
2. Join with 1.20.2
3. Server kicks player with "outdated server"

### Expected Behavior

Players can join with 1.20.2 clients

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A4d5746a%3A544](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A4d5746a%3A544-3498db?style=flat-square) </br>![ViaVersion (4.8.1-SNAPSHOT): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1--SNAPSHOT)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
Update Waterfall, make sure you have Via on only Waterfall OR the backend servers (preferably, move Via away from Waterfall to the backend servers instead)
