### ISSUE TITLE
Release 4.8.1 causes Client Disconnect on Bungee

### ISSUE THREAD

**Issue by Trenly** [ViaVersion/ViaVersion#3465]
### `/viaversion dump` Output

https://dump.viaversion.com/1c83a04252d35fa4f91c5ee29196b443d570ffd37ac1bb47a104fc8ceb99d211

### Console Error

```
08:54:57 [SEVERE] [ViaVersion] Error initializing BungeeServerHandler, try updating BungeeCord or ViaVersion!
08:54:57 [SEVERE] java.lang.NoSuchMethodException: net.md_5.bungee.connection.InitialHandler.getRegisteredChannels()
08:54:57 [SEVERE] 	at java.lang.Class.getDeclaredMethod(Class.java:2130)
08:54:57 [SEVERE] 	at com.viaversion.viaversion.bungee.handlers.BungeeServerHandler.<clinit>(BungeeServerHandler.java:69)
08:54:57 [SEVERE] 	at com.viaversion.viaversion.bungee.platform.BungeeViaLoader.load(BungeeViaLoader.java:61)
08:54:57 [SEVERE] 	at com.viaversion.viaversion.ViaManagerImpl.onServerLoaded(ViaManagerImpl.java:156)
08:54:57 [SEVERE] 	at com.viaversion.viaversion.BungeePlugin.onEnable(BungeePlugin.java:90)
08:54:57 [SEVERE] 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
08:54:57 [SEVERE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:287)
08:54:57 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
08:54:57 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
08:54:57 [INFO] Enabled plugin ViaVersion version 4.8.1 by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv
```
and 

https://paste.gg/p/anonymous/dbb84d7f74ac4573bcb753730454024d

### Bug Description

Updating from 4.7.0 to 4.8.1 causes clients to no longer be able to connect.

### Steps to Reproduce

Update plugin on Bungee server from 4.7.0 to 4.8.1

### Expected Behavior

Players are able to connect with the latest few versions of Minecraft

### Additional Server Info

![image](https://github.com/ViaVersion/ViaVersion/assets/12611259/c33a372b-536c-423c-a5d3-366a9d2e41d3)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.17--R0.1--SNAPSHOT%3Abda1605%3A1598](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.17--R0.1--SNAPSHOT%3Abda1605%3A1598-3498db?style=flat-square) </br>![Proxy is 156 builds behind](https://img.shields.io/badge/Your%20proxy%20is%20156%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Update Bungee
