### ISSUE TITLE
[1.20.2] Clients receive SetPlayerTeam packets during reconfiguration resulting in an NPE

### ISSUE THREAD

**Issue by tomwmth** [ViaVersion/ViaVersion#3470]
### `/viaversion dump` Output

https://dump.viaversion.com/62cafe068a8ae4ee6e6b89c2af05762279aad9503b87080d23a732b1c543d248

### Console Error

```
https://paste.gg/p/anonymous/4853e63b56db45ea91c2003c56d0c022
```

This stacktrace is from the client side, captured in an unobfuscated development environment using official Mojang mappings. The issue does occur on a strictly vanilla client, however the produced stacktrace is obfuscated and not of much use here. There is no server-side error.

### Bug Description

When connecting to a 1.20.1 or earlier server running ViaVersion with a 1.20.2 client I will be flooded with `SetPlayerTeam` packets before the world has actually finished being sent to my client. This results in an NPE on the client side and the data contained in those packets to be lost. It seems to be related to the new "Reconfiguring" screen which makes me believe this is a protocol issue. 

While it seems plausible that this could be either a Bungee or tab/scoreboard plugin issue, I lack the necessary expertise to properly tell what is at fault here.

I have noticed that the incidence of this issue is related to the stability and latency of your connection. As an Australian who regularly connects to American and European servers, I can reproduce it 99% of the time. After having people with better connections to the same servers test the issue, it appears to be significantly harder for them to reproduce it.

### Steps to Reproduce

1. Have unstable connection to the server (optional, but recommended)
2. Connect with a 1.20.2 client
3. Trigger a reconfigure (I achieve this by switching between servers on a proxy)
4. Receive `SetPlayerTeam` packets before the client has finished reconfiguring

### Expected Behavior

The sending of these packets should be slightly delayed for users on 1.20.2 to allow time for reconfiguration to complete, thus avoiding the NPE.

### Additional Server Info

We use BungeeCord as a proxy with ViaVersion running on each individual server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Sakura--%220aa64a7%22%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Sakura--%220aa64a7%22%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.0): 7 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.0)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.8.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
Bungee is broken atm. Try updating to Via -dev builds, but otherwise we already queue packets correctly
