### ISSUE TITLE
[1.12.2] ERROR IN Protocol1_8To1_9 IN REMAP OF ENTITY_EQUIPMENT (0x3C)

### ISSUE THREAD

**Issue by Carbonn9** [ViaVersion/ViaVersion#3475]
### `/viaversion dump` Output

https://dump.viaversion.com/ce237d0afb7ec9e83ac74afa3943076fe6b15c06b7ddf52c88dddb70abc3c3c6

### Console Error

https://pastebin.com/vsUceVzY

### Bug Description

It randomly occurs with this error in console before kicking me off of the server every time. And this is happening very frequently. Sometimes it won't let me even join the server because of it. This needs to be fixed immediately.

### Steps to Reproduce

1. Login with 1.8 on a 1.12.2 server that's waterfall bungeecord with viaversion, viabackwards & viarewind.

### Expected Behavior

For me to be able to play without any errors on 1.8 on 1.12.2 server.

### Additional Server Info

Keeps randomly kicking me with message, proxy lost connection to server. I am using Waterfall bungeecord.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
Update everything to -dev builds
