### ISSUE TITLE
[1.20.1] Smithing Table Issues

### ISSUE THREAD

**Issue by Coswics** [ViaVersion/ViaVersion#3477]
### `/viaversion dump` Output

https://dump.viaversion.com/7e9338e992ee12457ce43d6c44b3477dfe9d5bcdf18e35c437c4fb362b33f0da

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Trying to open smithing table on 1.20.1 server on 1.19.4 (and below) client doesnt work at all

### Steps to Reproduce

1. Login with a client below 1.20.1 (using 1.19.4 in this case)
2. Try to open smithing table; doesnt work
3. Opening on 1.20.1 client works fine
Blast Furnace Fix doesnt work at all that ive seen in other reports

### Expected Behavior

Smithing table should open with the blast furnace gui; or with the old gui and not require the netherite upgrade

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--27%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Pufferfish--27%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Coswics** [comment]
https://dump.viaversion.com/81eba9f14fc2afdb59844517e1db8e200078d1db78822274fdeaa036cec75a32

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--27%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Pufferfish--27%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Coswics** [comment]
https://dump.viaversion.com/81eba9f14fc2afdb59844517e1db8e200078d1db78822274fdeaa036cec75a32

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--27%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Pufferfish--27%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Kichura** [comment]
Check #3338.

**Comment by Coswics** [comment]
> Check #3338.

even with the latest ver/dev builds it doesnt present the furnace gui or old smithing template gui to those on lower versions. it doesnt open at all.
