### ISSUE TITLE
I get this error when I try to teleport to the Nether. And I was kicked out of the game.

### ISSUE THREAD

**Issue by ABlock11222** [ViaVersion/ViaVersion#3481]
### `/viaversion dump` Output

https://dump.viaversion.com/24d1accae43b369067db58815c88b416623bbd7a00f97ba02c4283be1eb08ae5

### Console Error

[```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/e5661a332a924fdab942d6ba72785fc7

### Bug Description

When I try to teleport to the Nether it gives this error. The base version of my server is 1.20.2, I log in from 1.20.1.

### Steps to Reproduce

1. I log in to the server with 1.20.1.
2. I enter the portal.
3. I get kicked from the game and I get this error.

### Expected Behavior

I got kicked out of the game.

### Additional Server Info

I'm using the base version of my server, 1.20.2 Paper. As plugins, there are fawe, viaversion, viabackwards, spark, setspawn plugins.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--234%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--234%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
You have a corrupt jar

**Comment by ABlock11222** [comment]
> You have a corrupt jar

Fork? Or Plugin jar?
