### ISSUE TITLE
[1.14 -> 1.13] Caused by: java.lang.NullPointerException: This packet does not have an input buffer

### ISSUE THREAD

**Issue by Fallen-Breath** [ViaVersion/ViaVersion#3482]
### `/viaversion dump` Output

https://dump.viaversion.com/200d4f172242817787123189b706601e1906f95fe6a48d6b980e3620f22ceedd

### Console Error

https://pastebin.com/pNU5CyHE

### Bug Description

The player gets kicked with no message, and an exception stack trace dumps in the console

![image](https://github.com/ViaVersion/ViaVersion/assets/28978806/23bcd4e1-339d-4fca-b80a-ff0276b49d12)

Installing viaversion on the backend mc servers is not a choice, cuz those mc servers are vanilla servers

### Steps to Reproduce

1. Use 1.15.2 client without viaversion mods to join the bungeecord
2. Join mc server in 1.13.2
3. Switch to mc server in 1.15.2 (via bungee's `/server` command)
4. Switch to mc server in 1.13.2 (via bungee's `/server` command)
5. Get disconnected, errors dumps in console

### Expected Behavior

Switching server doesn't kicks the player

### Additional Server Info

Platform:
- Bungeecord where viaversion plugins are installed
- Backend: vanilla Minecraft servers in offline mode

Plugin versions (with this issue):
- ViaVersion-4.8.1.jar, ViaBackwards-4.8.1.jar, ViaRewind-3.0.1-SNAPSHOT.jar, with issue
- ViaVersion-4.9.0-23w41a-SNAPSHOT.jar, ViaBackwards-4.9.0-23w41a-SNAPSHOT.jar, ViaRewind-3.0.3-SNAPSHOT.jar

Plugin versions (without this issue):
- ViaVersion-4.7.1-SNAPSHOT.jar, ViaBackwards-4.7.1-SNAPSHOT.jar, ViaRewind-2.0.4-SNAPSHOT.jar, works fine

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Abc32a4b%3Aunknown](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Abc32a4b%3Aunknown-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w41a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w41a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-23w41a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w41a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(3.0.3-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(3.0.3--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Try moving Via to the backend servers, it doesn't work well with Bungee at the moment

**Comment by Fallen-Breath** [comment]
> Try moving Via to the backend servers, it doesn't work well with Bungee at the moment

I have mentioned in the issue, "Installing viaversion on the backend mc servers is not a choice, cuz those mc servers are vanilla servers"

**Comment by kennytv** [comment]
Other alternatives are moving to Velocity or also using ViaProxy, but as far as we know issues on Bungee are from Bungee plugins that need updating or Bungee not handling the configuration switch safely

**Comment by Fallen-Breath** [comment]
> moving to Velocity or also using ViaProxy

Velocity does not provide good support with `player-info-forwarding-mode = "none"` which is required in my usecase, e.g. no player list item rewrites

Also velocity is lack of useful plugins and I need to port everything to velocity

For ViaProxy, it's too costly and not easy-to-maintain if I setup ViaProxy for each backend Minecraft server, and double proxy seems unstable for Minecraft

> are from Bungee plugins that need updating

The issue is reproduce-able with only via* present

> Bungee not handling the configuration

Any related codes / issues? If this is the cause, I think it's one of what ViaVersion should fix, or at least there should be an issue on bungeecord

**Comment by kennytv** [comment]
If it's reproducible without any plugins, that sounds more like an issue with your fork of Bungee

**Comment by Fallen-Breath** [comment]
> that sounds more like an issue with your fork of Bungee

The issue is reproduce-able with official bungee. Here's an example environment and related logs

Environment:

- [Bungeecord build 1763](https://ci.md-5.net/job/BungeeCord/1763/)
- ViaVersion-4.9.0-23w43a-SNAPSHOT
- ViaBackwards-4.9.0-23w43a-SNAPSHOT
- ViaRewind-3.0.4-SNAPSHOT

bungee log: https://pastebin.com/8uHPxciB

viaversion dump: https://dump.viaversion.com/0e6086daddb40f048ad1ed8f1d284751c56911d6a9b0b2d64f37b65c853d1362

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Ac92581d%3A1763](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Ac92581d%3A1763-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w43a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w43a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(3.0.4-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(3.0.4--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-23w43a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w43a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by Fallen-Breath** [comment]
> noone else has reported before lol

I think it's just that, there are too few people use a via on bungee + vanilla Minecraft backend servers like me. If you want, there's a lot more viaversion issues I can report on my setup, and here is just one of the most critical ones

**Comment by Fallen-Breath** [comment]
> with Paper servers and a standard Bungee

In my usecase, I'm using vanilla server as the backend. If via* do require some extra protocol between the backend server and bungee (e.g. whatever feature enabled after setting `bungeecord: true` in spigot etc.), I'll suggest to leave a note about it somewhere. Although I think dropping support for vanilla is not a good choice

Also, via* on velocity doesn't have the issue (at least from my quick test) with `player-info-forwarding-mode = "none"`, which means the extra bungee-spigot protocol thing mentioned above is not necessary

**Comment by kennytv** [comment]
Can't reproduce on a clean setup, even with vanilla servers. We know that there are other version combinations that definitely will error, maybe this is one of those as some kind of edge case, but in general those are very unlikely to be fixed unless Bungee adds API for injection points and the VV injection on Bungee is rewritten to be more like Velocity's (even then, not sure it work as well)

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Ac92581d%3A1763](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Ac92581d%3A1763-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w43a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w43a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(3.0.4-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(3.0.4--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-23w43a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w43a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Thank you! The printed error was a red herring with the actual one suppressed, should be fixed with https://github.com/ViaVersion/ViaVersion/commit/dccac81286f7f6c18e03d903901f430766565cde
