### ISSUE TITLE
Can't connect: 1.20.1 client, 1.20.2 Server, g-portal

### ISSUE THREAD

**Issue by Kathezel** [ViaVersion/ViaVersion#3484]
### `/viaversion dump` Output

https://dump.viaversion.com/a1f7167892c2d6e685d8ac52c4872419a02f8333e28b44f319756d5a4690f2d2

### Bug Description

I'm using a 1.20.1 Modded Client and a 1.20.2 Server (G-Portal)

Tested everything locally and it worked, after moving it onto G-Portal it spot working.

![image](https://github.com/ViaVersion/ViaVersion/assets/145993790/ac30da1a-b81e-47dc-893e-9f24165bdf85)

### Steps to Reproduce

I have no idea how. It worked locally not on public server.

### Expected Behavior

I can join

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--241%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--241%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Kathezel** [comment]
**I found the Problem!**

If the server has a resource pack enabled it will cause this error. I needed to disable the R-pack to join.
this was the only thing different, did thought this would make a problem.

Maybe now would be a topic chance to: *Having a resource pack enabled on the server is causing an error while joining.*

**Comment by Kichura** [comment]
Update to dev builds.
