### ISSUE TITLE
1.7 Bugs

### ISSUE THREAD

**Issue by overkidding** [ViaVersion/ViaVersion#3486]
### `/viaversion dump` Output

https://dump.viaversion.com/7922513dbda5f88d56b56737152700af6f5a8b8d2b01c02ff15c76043b082de6

### Console Error

[```
Put the paste.gg link or text here.
```
]
(https://paste.gg/p/anonymous/285b027764404d1ba8ff36cbcb80f137)

### Bug Description

I'm not able to join the server with 1.7 while there are armor stands in it.
WaterFall with 1.7.x patch and viaversion on spigot servers.

### Steps to Reproduce

1. Holograms
2. 1.7 Waterfall (like travertine i think)
3. ViaVersion on spigot
4. Join with 1.7

### Expected Behavior

Not getting any error and should be able to join instead of getting kicked for "Disconnected from server"

### Additional Server Info

_No response_

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: HeroSpigot%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-HeroSpigot%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.0): 7 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.0)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by overkidding** [comment]
https://paste.gg/p/anonymous/f3d464750e5848af8dcee2c586d95644

Debug of when i get disconnected

**Comment by FlorianMichael** [comment]
Try to update ViaVersion and ViaRewind to latest dev branch, this might solve your issue

**Comment by overkidding** [comment]
Tried but still happening
