### ISSUE TITLE
Error while remapping DECLARE_RECIPES & UNLOCK_RECIPES

### ISSUE THREAD

**Issue by andrewkm** [ViaVersion/ViaVersion#3489]
### `/viaversion dump` Output

https://dump.viaversion.com/647528efac765082189b28203e084c54f63a6d14e9c2d9e6dd26ac29f33361df

### Console Error

https://pastebin.com/raw/SN1GZu9x

### Bug Description

Logging into 1.12.2 server with 1.20.2 causes this error, and disconnects client.
Previous working environment:
ViaVersion-Dev: Jenkins 921
ViaBackwards-Dev: Jenkins 523

### Steps to Reproduce

1. Login to 1.12.2 server with 1.20.2 client and above setup.

### Expected Behavior

To log in...

### Additional Server Info

On request.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w42a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w42a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-23w42a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w42a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
[Fixed a](https://github.com/ViaVersion/ViaVersion/commit/815e0820da9d6d7fea9f0da49c8fc525644a3da8)
