### ISSUE TITLE
In the latest Velocity, it will stay waiting for configuration until timeout when loading.

### ISSUE THREAD

**Issue by BingYanchi** [ViaVersion/ViaVersion#3491]
### `/viaversion dump` Output

https://dump.viaversion.com/ee7af0558afa7f697138104c540448b59cb06132eacea2979a37146184fd254a

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/f19b68b5241944c6b4459069357b67b0
https://paste.gg/p/anonymous/5f88effe5b9142e19b3d752e1d21d1a5

### Bug Description

This issue has been present since Velocity 266 1.20.2 Support (1088).

I tried using 1.20.2 to get into a pre-1.20.2 server and it would get stuck in the waiting server configuration stage until disconnected due to a timeout.

### Steps to Reproduce

1. Use any Spigot server lower than 1.20.2.
2. Use the latest Velocity.
3. Connect using Minecraft client 1.20.2.
4. Wait for timeout.

### Expected Behavior

Enter correctly

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--81b183ac--b276%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--81b183ac--b276%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
1. Can you swap the spigot server software with paper?
2. Can you update via* to dev builds?
3. If the first two steps fail then it's either windows having broken configurations or you have to attempt moving via* to backend servers.

**Comment by BingYanchi** [comment]
> 1. Can you swap the spigot server software with paper?
> 2. Can you update via* to dev builds?
> 3. If the first two steps fail then it's either windows having broken configurations or you have to attempt moving via* to backend servers.

He has nothing to do with Spigot and still has this problem with Paper. However, this problem did not occur when updating to the development version of viaversion.
