### ISSUE TITLE
ERROR IN Protocol1_20To1_20_2 IN REMAP OF CHUNK_DATA

### ISSUE THREAD

**Issue by d3adwolf** [ViaVersion/ViaVersion#3506]
### `/viaversion dump` Output

https://dump.viaversion.com/7bea3b8442cdb9d19618a31d6066322c7151850d88dda36556d3c9b58b35ad33

### Console Error

[Pastebin](https://pastebin.com/CfidXszc)

### Bug Description

The error occurs when logging into the server.

### Steps to Reproduce

1. Login with 1.20.2 client

### Expected Behavior

Error-free operation.

### Additional Server Info

`This server is running Pufferfish version git-Pufferfish-28 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 06262c1 on HEAD)`

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--29%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Pufferfish--29%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
Try updating to ci builds, otherwise you have a plugin sending bad chunk data
