### ISSUE TITLE
Random disconnects.

### ISSUE THREAD

**Issue by MikkelHebel** [ViaVersion/ViaVersion#3509]
### `/viaversion dump` Output

https://dump.viaversion.com/dd3e23dc73f7e6df392f5b0d41a4fe90fc7da16d84f97b3abf1cc807d544f431

### Console Error

```
[Paste.gg Link](https://paste.gg/p/anonymous/dae6d9a890cc4fc68736670003bf3df4)
```

### Bug Description

Executing commands some times causes random disconnects on a 1.8.8 server when using 1.20.2

### Steps to Reproduce

1. Login to server with 1.20.2.
2. Join 1.8.8 server.
3. Write some commands.
4. Get kicked.

### Expected Behavior

Should not get kicked. This happens randomly and it's random on which commands and when.

### Additional Server Info

The server is running Waterfall version git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0407ef5:537.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--445%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.0): 7 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.0)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
Update to ci builds, also update LuckPerms
