### ISSUE TITLE
1.20.40 Bedrock client crashing on join to 1.20.1 Java Paper Geyser Server

### ISSUE THREAD

**Issue by CheeseManFuu** [ViaVersion/ViaVersion#3512]
### `/viaversion dump` Output

https://dump.viaversion.com/10f69213e90105b9a716918f803547d8251ef57e787a2497b7bc58b21a939619

### Console Error

```
[16:42:00 INFO]: /192.168.1.240:59657 tried to connect!
[16:42:01 INFO]: Player connected with username CheeseManFu
[16:42:01 INFO]: CheeseManFu (logged in as: CheeseManFu) has connected to the Java server
[16:42:02 INFO]: UUID of player .CheeseManFu is 00000000-0000-0000-0009-01f412a28e98
[16:42:02 INFO]: Floodgate player logged in as .CheeseManFu joined (UUID: 00000000-0000-0000-0009-01f412a28e98)
[16:42:02 INFO]: .CheeseManFu joined the game
[16:42:02 INFO]: .CheeseManFu[/192.168.1.240:0] logged in with entity id 332 at ([TenshiServerWorld]10.115781, 73.0, 905.7859)
[16:42:12 INFO]: We've made a dump with useful information, report your issue and provide this url: https://dump.viaversion.com/10f69213e90105b9a716918f803547d8251ef57e787a2497b7bc58b21a939619
[16:42:13 INFO]: CheeseManFu has disconnected from the Java server because of Bedrock client timed out
[16:42:13 INFO]: Floodgate player logged in as .CheeseManFu disconnected
[16:42:13 INFO]: .CheeseManFu lost connection: Disconnected
[16:42:13 INFO]: .CheeseManFu left the game
```

### Bug Description

Players on Bedrock clients on latest 1.20.40 version crash upon logging into the server.

Server runs on Paper on 1.20.1, have experienced crash with several plugins and with just Geyser, Floodgate, and ViaVersion.

### Steps to Reproduce

1. Open Minecraft Pocket Edition or Minecraft Windows 10 Version
2. Load onto server (either through Public IP or local IP)
3. Game hard crashes either on loading screen or barely a second into logging in.

### Expected Behavior

Players on latest Bedrock version should be able to connect to server.

### Additional Server Info

Server is self-host, uses Paper for Java 1.20.1 on Debian Linux.

Full plugins:
[AppleSkinSpigot 1.2.0](https://github.com/jmattingley23/AppleSkinSpigot)
[Dynmap 3.7 beta 2](https://www.spigotmc.org/resources/dynmap%C2%AE.274/)
[EssentialsX-2.20.1](https://essentialsx.net/)
[Floodgate Spigot Build 85](https://geysermc.org/download)
[Geyser Spigot Build 339](https://geysermc.org/download)
[ItemKillCounter Version 1.1](https://www.spigotmc.org/resources/%E2%84%B9%EF%B8%8F-item-kill-counter-%E2%9A%94%EF%B8%8F-1-14-1-19.101728/)
[PlayerKits 2.27.1](https://www.spigotmc.org/resources/playerkits-2-fully-configurable-kits-1-8-1-20-2.112616/)
[SkinsRestorer 15.0.1](https://www.spigotmc.org/resources/skinsrestorer.2124/) (yes I HAVE tried removing this alone since it's in the FAQ)
[TabTPS Spigot 1.3.21](https://modrinth.com/plugin/tabtps)
[ViaVersion 4.8.1](https://www.spigotmc.org/resources/viaversion.19254/updates)
[Simple Voice Chat Bukkit 2.4.24](https://modrinth.com/plugin/simple-voice-chat/versions?l=bukkit)

Above dump file only uses:
Floodgate Spigot Build 85
Geyser Spigot Build 339
ViaVersion 4.8.1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [x] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--82%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--82%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
ViaVersion has nothing to do with Bedrock support, that's Geyser

**Comment by Camotoy** [comment]
Please update to Geyser build 340. This may help with crashing, but we are still working on fixing all instances of crashing.

**Comment by CheeseManFuu** [comment]
> Please update to Geyser build 340. This may help with crashing, but we are still working on fixing all instances of crashing.

Thanks for responding, saves me the couple minutes I was going to take going to the Geyser git. I'll get to that in just a second.
