### ISSUE TITLE
[1.8.8] Console errors when 1.13+ player disconnect

### ISSUE THREAD

**Issue by HowardZHY** [ViaVersion/ViaVersion#3514]
### `/viaversion dump` Output

https://dump.viaversion.com/706f32a350cea17737d993945f765827f73ce11db2eb43374643e15da9f7e543

### Console Error

https://mclo.gs/BIDlZBX

### Bug Description

When ?-1.16.5+ clients disconnect, the console sometimes throw huge errors.
This seems didn't affect gameplay.

### Steps to Reproduce

1. Paper 1.8.8, latest dev build
2. 1.16.5 client, join on localhost and quit the server very quickly after joined server
3. Try multiple times
4. Errors randomly happen

### Expected Behavior

No errors

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--445%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w43a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w43a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
This is a server issue not handling disconnects properly

**Comment by HowardZHY** [comment]
> This is a server issue not handling disconnects properly

Most these disconnects can't be handled properly, it happens more often with ppl with really bad internet or kicked by flying is not enabled on the server.

**Comment by kennytv** [comment]
The problem is that the server still tries to send packets to an already closed connection. This was fixed in vanilla years ago

**Comment by HowardZHY** [comment]
> The problem is that the server still tries to send packets to an already closed connection. This was fixed in vanilla years ago

Can Via prevent it or the server's code must be edited?
