### ISSUE TITLE
error's and warnings in console on 1.12.2 server

### ISSUE THREAD

**Issue by ICodeMonster** [ViaVersion/ViaVersion#3517]
### `/viaversion dump` Output

https://dump.viaversion.com/73280f21273eb6e678c8c8532e2019fcbd519716fe2a17d24c4b914f838c228f

### Console Error

https://logpaste.com/iRJyBtZy
OR 
https://logpaste.com/2O26RP1M (i use dev build plugin)

### Bug Description

if you take  an item that appeared after 1.12.2 - console give error or/and warn
server paper 1.12.2.  

### Steps to Reproduce

1. enter on server 1.12.2 on client version latest,
2. take take an item that appeared after 1.12.2
OR
1. enter on server 1.12.2 on client version latest (i use dev build plugin)
2. place block that appeared after 1.12.2

### Expected Behavior

correct work plugin without errors and warns in console

### Additional Server Info

i use velocity (Velocity 3.2.0-SNAPSHOT), 
velocity plugins: antivelocitycrash, commandwhitelist, limboapi, limboauth, limbofilter, luckperms, skinsrestorer, velocity_tools

and i use paper 1.12.2 (latest version), plugins: 
AdvancedBan, ajLeaderboards, ajParkour, antiRedstoneClock, ArmorStandTools, AuctionHouse, BannerMaker, BKCommonLib, BungeeGuard, Chatty, ChestCommands, ClearLag, CombatTagPlus, CompatNoCheatPlus, DecentHolograms, DiscordSRV, EasySetSpawn, Essentials, FastAsyncWorldEdit, FunctionalClans, GrimAC, IllegalStack, InteractiveChat, InteractiveChatDiscordSrvAddon, IRandomTeleport, LightCleaner, Log4jFix, LuckPerms, MoneyFromMobs, NBTAPI, NoCheatPlus, Orebfuscator, PlaceholderAPI, PlugMan, PlugManX, ProtectionStones, ProtocolLib, ResourcePackDownloader, SimplePortals, SimpleRename, SkinsRestorer, TAB, UltimateServerProtector, Vault, ViaVersion, WorldEdit, WorldGuard, ZNPCsPlus

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by ICodeMonster** [comment]
dump dev build plugin: https://dump.viaversion.com/a59b614bc486f101e5c4f727452a9f42e5badad813cb54e0072f0ae72b82ea93

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w44a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w44a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by youguo233** [comment]
https://dump.viaversion.com/8d8dd1ade8f7e9c98f042ab7eb6b204330917801e40d74b5dff42300aa19c012

**Comment by Barvalg** [comment]
![Platform: git--Spigot--db6de12--18fbb24%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--Spigot--db6de12--18fbb24%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w44a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w44a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Something is sending bad metadata to the server which is likely to be znpcsplus or another third-party plugin, consider doing a binary search to see what causes that to happen.

**Comment by ICodeMonster** [comment]
how do binary search?

**Comment by Kichura** [comment]
Grabbed from discord support channel but this is how:

![discord](https://github.com/ViaVersion/ViaVersion/assets/68134602/c9535978-7121-4623-9048-69e770cc54a0)

**Comment by ICodeMonster** [comment]
![image](https://github.com/ViaVersion/ViaVersion/assets/137718036/e6b87aae-6cee-4b23-a774-3dde1097be1a)
when I put on the turtle shell, I am given 9 seconds of underwater breathing, although this version does not have the shell. The effect remains even after removing the turtle shell. The problem with the error in the console was indeed in znpsсPlus, thank you. The following warnings appear when you pick up or attempt to use certain items:
[19:05:54 WARN]: [ViaVersion] Failed to get item 1.12 for 454
[19:06:04 WARN]: [ViaVersion] Failed to get item 1.12 for 465

and sorry for my english. translated by google translate.

**Comment by Kichura** [comment]
The effect is normal and will expire when shell is removed from helmet slot, as for the "failed to get item 1.12 for X" - this sounds like something is trying to obtain an item but the IDs are invalid.

**Comment by ICodeMonster** [comment]
for the "failed to get item 1.12 for X" -  I just took it and threw it away or put inventory items in the slots. The effect is still not gone 
![image](https://github.com/ViaVersion/ViaVersion/assets/137718036/f28f03d5-91cd-44ed-8778-da477aeaca74)

**Comment by Kichura** [comment]
Does the effect also remain when drinking milk / logging in with an 1.13 client?

**Comment by ICodeMonster** [comment]
milk does not help on 1.13. I don’t have command blocks that could leave effects, I just drank the potion and the effect from it disappeared, but the effect from the turtle helmet remained and it still confuses me that when put on it gives 9 seconds of effect (if you put on the helmet, the effect resumes , but also does not disappear). and i think what its turtle helmet - [19:29:43 WARN]: [ViaVersion] Failed to get 1.12 item for 465

**Comment by Kichura** [comment]
Can you try disabling all plugins except viaversion to see if it manages to recover at all?

**Comment by ICodeMonster** [comment]
mushroom_stem - [19:34:50 WARN]: [ViaVersion] Failed to get 1.12 item for 205

**Comment by ICodeMonster** [comment]
![image](https://github.com/ViaVersion/ViaVersion/assets/137718036/3707616a-077f-4116-98d9-f81ed054bed5)

**Comment by Kichura** [comment]
Hmm interesting, will check if i can reproduce this.

**Comment by Kichura** [comment]
Cannot reproduce on 1.13+ server, also the water breathing effect in 1.12.2 is fake and doesn't actually work.

**Comment by ICodeMonster** [comment]
1.12.2 server, bro

**Comment by ICodeMonster** [comment]
that is, despite the fact that it appeared at 9 seconds - is it fake?

**Comment by Kichura** [comment]
> that is, despite the fact that it appeared at 9 seconds - is it fake?

correct as what the server actually sees is that it was a stone block in the inventory slot and nothing else, therefore spam-spawning it into the HUD and placing the fake turtle helmet into helmet slot will just spawn a fake effect which in reality the player can still drown.

**Comment by ICodeMonster** [comment]
thank you for your work. you helped me a lot
