### ISSUE TITLE
Console spam 

### ISSUE THREAD

**Issue by Lerphie** [ViaVersion/ViaVersion#3522]
### `/viaversion dump` Output

https://dump.viaversion.com/b9263d425af01be7fffaa87ed1672af32c14bd0b91bccafe51e51877c6875772

### Console Error

![image](https://github.com/ViaVersion/ViaVersion/assets/66962762/61b2605c-9cb0-4ac2-9ef8-46bcff1e1df2)

### Bug Description

There is a lot of spam in the server console. Maybe the problem is in ModelEngine 3

### Steps to Reproduce

I don't know how to cause this error

### Expected Behavior

*

### Additional Server Info

I use Velocity in conjunction with Skinrestorer

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Airplane--%22e37fa86%22%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Airplane--%22e37fa86%22%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Kichura** [comment]
ModelEngine is not supported.

**Comment by Lerphie** [comment]
> ModelEngine is not supported.

why? its most popularity plugin

**Comment by Lerphie** [comment]
please give me advice on what to do in this situation

**Comment by Kichura** [comment]
Because it uses a heavy resource pack that viaversion can not handle properly and therefore it is nearly impossible to make it compatible + modelengine has no source code available which makes it extra difficult to troubleshoot.

**Comment by Lerphie** [comment]
> Because it uses a heavy resource pack that viaversion can not handle properly and therefore it is nearly impossible to make it compatible + modelengine has no source code available which makes it extra difficult to troubleshoot.

Have you tried writing to the developer? He's very friendly. I'm sure he'll help to resolve the situation
