### ISSUE TITLE
Internal Exception: io.netty.handler.codec.decoderexception: java.lang.index.outofboundsexception:index 35 out of bounds for length 5 while joining

### ISSUE THREAD

**Issue by kacperc99** [ViaVersion/ViaVersion#3525]
### `/viaversion dump` Output

https://dump.viaversion.com/3302ee317849825bab9e1304c17d02983d95a0dabbb6cc95cf5295740e03b6cc

### Console Error

Internal Exception: io.netty.handler.codec.decoderexception: java.lang.index.outofboundsexception:index 35 out of bounds for length 5 (for some reason logs do not show anything else)

### Bug Description

People can't join 1.20.2 aternos server while being on 1.20.1 client.

### Steps to Reproduce

1. Login with 1.20.1 client.
2. Try to join the server.

### Expected Behavior

Well, you should be able to join, right?

### Additional Server Info

I use Aternos server on Fabric 1.20.2

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
Since this issue is a reference to [ViaFabric's #275](https://github.com/ViaVersion/ViaFabric/issues/275) due to Fabric API breaking viabackwards, marking this as duplicate.

**Comment by Kichura** [comment]
> @Kichura I have this same issue not using ViaFabric. I run ViaVersion and ViaBackwards on Waterfall (build 554) and 1.20.1 clients can't join. EDIT: Should have clarified. The message is different, but the issue of 1.20.1 clients is the same.

Have you tried putting via* to the spigot/paper servers since bungee/waterfall tends to cause dumb behavior with proxy-related plugins, also velocity is recommended for use instead.

**Comment by bobbyl140** [comment]
> Have you tried putting via* to the spigot/paper servers since bungee/waterfall tends to cause dumb behavior with proxy-related plugins, also velocity is recommended for use instead.

Yeah, I have ViaVersion and ViaBackwards on both Waterfall and the Paper servers. And yeah I really should use Velocity, I originally had my server running BungeeCord and everything is therefore built around it.

**Comment by Kichura** [comment]
> > Have you tried putting via* to the spigot/paper servers since bungee/waterfall tends to cause dumb behavior with proxy-related plugins, also velocity is recommended for use instead.
> 
> Yeah, I have ViaVersion and ViaBackwards on both Waterfall and the Paper servers. And yeah I really should use Velocity, I originally had my server running BungeeCord and everything is therefore built around it.

Please remove viaversion and viabackwards from waterfall then if you have it on paper already as you are clearly stacking. *(and stacking is the worst thing you can do to your server)*

**Comment by bobbyl140** [comment]
Except in doing that, won't actual clients not be able to use versions other than that of the proxy?

**Comment by bobbyl140** [comment]
I think where my setup is diverging from most is that I have an up-to-date Waterfall, but my backend servers are on 1.20.1 and my clients also may be on 1.20.1. So I need ViaVersion functionality both client <-> proxy and proxy <-> backend. Is this not possible anymore in practice? (It did *used to* work)

**Comment by Kichura** [comment]
> I think where my setup is diverging from most is that I have an up-to-date Waterfall, but my backend servers are on 1.20.1 and my clients also may be on 1.20.1. So I need ViaVersion functionality both client <-> proxy and proxy <-> backend. Is this not possible anymore in practice? (It did _used to_ work)

This is not how it works in practice as you will just ask the proxy and backend to translate twice which can go wrong in multiple ways, therefore run the via* plugins on the backend servers instead and if older clients are required deploy viabackwards *(and optionally viarewind)* to the backend servers too.

**Comment by bobbyl140** [comment]
But if ViaBackwards is only installed on the backends, the proxy won't accept the 1.20.1 connections anymore, no?

**Comment by Kichura** [comment]
> But if ViaBackwards is only installed on the backends, the proxy won't accept the 1.20.1 connections anymore, no? That does make sense though.

Incorrect, The proxy can pick up any client that is on 1.8.x - 1.20.2 *(applies to mostly all proxies by the way)* and then let's the main backend server decide if this version is supported - if it is, then the proxy let's them through.

**Comment by bobbyl140** [comment]
Ah, so I misunderstood. Thank you for clarifying. I just tested and it works perfectly, so thank you again!
