### ISSUE TITLE
ERROR IN Protocol1_19To1_18_2

### ISSUE THREAD

**Issue by mralberston** [ViaVersion/ViaVersion#3527]
### `/viaversion dump` Output

https://dump.viaversion.com/5c2c89328f62285b519c8618f3d9e48f20580655446e39852278e15195ade1c7

### Console Error

```
(https://paste.gg/p/anonymous/93a48cb5e35b49f8b772732ec3dfc157)
```

### Bug Description

I got an error, please fix it

### Steps to Reproduce

I got an error, please fix it

### Expected Behavior

no

### Additional Server Info

paper 1.16.5

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--794%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--794%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Kichura** [comment]
Caused by third-party plugin(s), please perform a binary search to see what causes viaversion to complain about it.
