### ISSUE TITLE
Error when i try to take an egg of entity

### ISSUE THREAD

**Issue by danib150** [ViaVersion/ViaVersion#3529]
### `/viaversion dump` Output

https://dump.viaversion.com/20421d73423e592c602fd6c049f784d8102dbfddc95147d060c9a5c868a93add

### Console Error

```
Put the paste.gg link or text here.
```
https://hastebin.com/share/iwanafipeb.csharp

### Bug Description

taking an entity egg with mouse wheel causes this error 

### Steps to Reproduce

1. Login with 1.8.8 Client in 1.20.2 server
2. take an entity egg with mouse wheel
3. kick with the error

### Expected Behavior

I shouldn't be kicked

### Additional Server Info

Velocity 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--291%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--291%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
Please use paste.gg, the linked hastebin expired
