### ISSUE TITLE
CMI new Holgrams dont work when using ViaVersion

### ISSUE THREAD

**Issue by MCAdventureCraft** [ViaVersion/ViaVersion#3530]
### `/viaversion dump` Output

https://dump.viaversion.com/bf70088152c018cc700af7d64e457635f081952c2a01996d57712ffda66c0044

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

CMI has newer holograms where you can position them and scale them differently. this however will make them invisible when using viaversion/viabackwards.

Any idea how to fix this issue?

Here is the report on CMIs Github which may have more information pertaining this issue
https://github.com/Zrips/CMI/issues/8212

### Steps to Reproduce

Use Viaversion/Viabackwards
Use CMI + CMILib
Create Hologram

### Expected Behavior

Hologram being shown

### Additional Server Info

Paper 1.20.2

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--280%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--280%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>
