### ISSUE TITLE
 resource pack Error

### ISSUE THREAD

**Issue by AydenC77** [ViaVersion/ViaVersion#3537]
### `/viaversion dump` Output

https://dump.viaversion.com/96af3dfdef5be1934c00b6956e00e78b6815ddd9273a554860e57759f6f5583b

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/4657a9eb6b13462b915001587e08f23e

### Bug Description

hello im getting this error if i have a resource pack when im not on the servers main vairsion and

![image](https://github.com/ViaVersion/ViaVersion/assets/64756450/f49abe29-bf54-4f23-81c7-b96788a105d0)

### Steps to Reproduce

add a resource pack  to a 1.20.2 paper server
add via vorsion and via rewind and via backwerds
join server on 1.20.1

### Expected Behavior

ok join you should get this console error and this kick error
![image](https://github.com/ViaVersion/ViaVersion/assets/64756450/021ef85e-c563-486c-a09b-0981920a064a)

https://paste.gg/p/anonymous/4657a9eb6b13462b915001587e08f23e

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--299%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--299%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.0): 7 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.0)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by AydenC77** [comment]
i alrady have it thats the vorsion im useing
