### ISSUE TITLE
1.20.1- cannot join to the server of fabric 1.20.2+

### ISSUE THREAD

**Issue by 404XiaoTuHao** [ViaVersion/ViaVersion#3544]
### `/viaversion dump` Output

https://dump.viaversion.com/5bc3c1027ec18c71db4eaccb3db73b3cf98d54f9260bb3246480678c3f666949

### Console Error

No error output

### Bug Description

![CAU5Y5E 6(7C )C(I~DQL](https://github.com/ViaVersion/ViaVersion/assets/82070627/a7209f57-9cac-4091-a5a0-81fd17c85b0e)
![3W~9LCVI3}P}8} {SV}TSDA](https://github.com/ViaVersion/ViaVersion/assets/82070627/e24c9b69-9335-47c0-9af3-db1bad458d83)
The latest version of Viaversion has been used but still cannot be resolved

### Steps to Reproduce

1、Login to server 1.20.2 using 1.20.1, unable to join game, prompt connection interruption
2、Switching from server 1.20.1 to server 1.20.2, unable to join server 1.20.2 without any error message. When switching for the second time, it will prompt "You are already trying to connect to the server"

### Expected Behavior

The use of clients 1.20.1 and below should allow normal access to the 1.20.2 server

### Additional Server Info

![S2S OZ~B${2026VT3 8D4{L](https://github.com/ViaVersion/ViaVersion/assets/82070627/3707795c-ce2e-467d-8c6a-e3f4bd8fa59f)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--8dcc7ee3--b294%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--8dcc7ee3--b294%29-3498db?style=flat-square) </br>![Proxy is 2 builds behind](https://img.shields.io/badge/Your%20proxy%20is%202%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.9.0-1.20.3-pre4-SNAPSHOT): 7 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--1.20.3--pre4--SNAPSHOT)-7%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards(4.9.0-1.20.3-pre3-SNAPSHOT): 6 commits behind dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--1.20.3--pre3--SNAPSHOT)-6%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by 404XiaoTuHao** [comment]
Using the latest version still cannot solve the problem of 1.20.1 not being able to add 1.20.2，Using the vanilla client

**Comment by Kichura** [comment]
Update your proxy to latest version and also via* to latest dev builds aswell, if this doesn't work - please try moving viaversion to the spigot/paper servers instead.

**Comment by kennytv** [comment]
Try updating to ci builds again, make sure your other plugins like Geyser are up to date

**Comment by 404XiaoTuHao** [comment]
All plugins have been updated, 1.20.1 client still cannot be join to 1.20.2+
