### ISSUE TITLE
1.20.3 clients crashing when joining server

### ISSUE THREAD

**Issue by turnolos** [ViaVersion/ViaVersion#3545]
### `/viaversion dump` Output

https://dump.viaversion.com/68713d0f85ec58753e9894c1dbd52afe642a869a4a3d4f91a402fc1c117ae2d2

### Console Error

```
https://mclo.gs/PmEUo74
```

### Bug Description

On the latest viaversion/viabackwards/viarewind on my minecraft 1.12.2 paper server, 1.20.3 clients get disconnected upon joining. I have provided the console error.

### Steps to Reproduce

1. Login with 1.20.3 client on 1.12.2 server
2. get disconnected

### Expected Behavior

should not disconnect

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--%22662261c1%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--%22662261c1%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.5): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.0)-Even%20with%20master-brightgreen?style=flat-square) </br>
