### ISSUE TITLE
1.20.3 clients are getting kicked.

### ISSUE THREAD

**Issue by SirKillian** [ViaVersion/ViaVersion#3546]
### `/viaversion dump` Output

https://dump.viaversion.com/c9f8950fcb7d1df5b6d0d1201ebbb783d1471790d5ee1d3b630919919603bcc3

### Console Error

```
https://paste.gg/p/anonymous/37b23cd65e014b1eaf299f32ed7dce14
```

### Bug Description

When certain text hits the chat, 1.20.3 clients are getting kicked. with the following error;

https://sirkillian.gg/i/6ftff9m5maafdxdt.png

### Steps to Reproduce

It depends on how plugins are sending a message chat. so not sure how to replicate it without specific plugins.

### Expected Behavior

players shouldn't get kicked

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--2aaf702a--b263%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--2aaf702a--b263%29-3498db?style=flat-square) </br>![Proxy is 33 builds behind](https://img.shields.io/badge/Your%20proxy%20is%2033%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.9.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Velocity is not 1.20.3 ready yet.

**Comment by turnolos** [comment]
We arent using velocity or bungee, just paper spigot.

**Comment by turnolos** [comment]
> Velocity is not 1.20.3 ready yet.

We arent using velocity or bungee, just paper spigot.

**Comment by turnolos** [comment]
> Velocity is not 1.20.3 ready yet.

you have closed this falsely. we arent using velocity or bungee, just paper spigot

**Comment by mrfloris** [comment]
We do not use velocity if that matters, but we can repeat this. A player died by ender pearl and all 1.20.3 players in the same world disconnected.
<img width="1014" alt="Screenshot 2023-12-05 at 20 54 56" src="https://github.com/ViaVersion/ViaVersion/assets/28841349/a8ea286d-9825-48b8-a2a6-1ed1067fcafe">
![image](https://github.com/ViaVersion/ViaVersion/assets/28841349/a2753b5a-f885-4e25-b4f7-6861facf7c81)

**Comment by Kichura** [comment]
Gave it a test and it's confirmed - issue will remain open.

**Comment by kennytv** [comment]
The screenshot and the console log are two different things

**Comment by SirKillian** [comment]
> The screenshot and the console log are two different things, the screenshot is definitely a valid bug, not sure about the Velocity one

This could be possible. +-25 players were disconnected but only 1 player had that missing packet error. Perhaps the velocity error was just coincidentally happening right before players were kicked.

**Comment by Kichura** [comment]
Here, i can actually die just fine with pearls but giving myself items using commands will yeet the 1.20.3 client. *(1.20.2 is unaffected)*

**Comment by mrfloris** [comment]
> Here, i can actually die just fine with pearls but giving myself items using commands will yeet the 1.20.3 client. _(1.20.1/1.20.2 is unaffected for some reason)_

The servers i am on that this happens on all have custom death msgs, if that matters.

**Comment by Kichura** [comment]
> > Here, i can actually die just fine with pearls but giving myself items using commands will yeet the 1.20.3 client. _(1.20.1/1.20.2 is unaffected for some reason)_
> 
> The servers i am on that this happens on all have custom death msgs, if that matters. (different plugins)

Seems like it does for every message it's trying to broadcast except certain vanilla-based variants.

**Comment by kennytv** [comment]
More screenshots of different components are appreciated, even better if the actual/simpler json is available

**Comment by Kichura** [comment]
![a](https://github.com/ViaVersion/ViaVersion/assets/68134602/0d1c0142-767d-411d-9897-c03e6f149d88)

Well this is what i got when giving myself items on 1.20.3 client, The 1.20.1 client on left can read it without problems.
