### ISSUE TITLE
Can't join with 1.20.1 on 1.20.2 server

### ISSUE THREAD

**Issue by gamingcodedev** [ViaVersion/ViaVersion#3547]
### `/viaversion dump` Output

https://dump.viaversion.com/a1a1ef57f067428dd5aed6e5fc69156bacecdd7cc8f19e3807ee89f1db93ba67

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

Get kicked for outdated client. if i try to join with 1.20.1 on 1.20.2

### Steps to Reproduce

1. Server 1.20.2
2. Newest Version 4.9.1
3. Try to join with 1.20.1

### Expected Behavior

Accept join

### Additional Server Info

I use paper

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
You dont have ViaBackwars installed

**Comment by gamingcodedev** [comment]
i have

**Comment by gamingcodedev** [comment]
![image](https://github.com/ViaVersion/ViaVersion/assets/45319070/3dbf7265-4f1f-46be-9ddf-237e06ea069c)

**Comment by kennytv** [comment]
That's outdated

**Comment by gamingcodedev** [comment]
There is no newer version on spigotmc

**Comment by gamingcodedev** [comment]
https://www.spigotmc.org/resources/viabackwards.27448/

**Comment by Kichura** [comment]
> [spigotmc.org/resources/viabackwards.27448](https://www.spigotmc.org/resources/viabackwards.27448/)

Use hangarmc or modrinth instead as an alternative.
