### ISSUE TITLE
bedrock players getting kicked

### ISSUE THREAD

**Issue by tanzbr** [ViaVersion/ViaVersion#3548]
### `/viaversion dump` Output

https://dump.viaversion.com/0840083531d458d6b8ce354fc5825959a9acd203cdb1c18d2b07af147326631f

### Console Error

https://paste.gg/p/anonymous/fecd96accf354174b568683e6ab1067e

### Bug Description

bedrock players get disconnected when joining the server, the error occurs on the lobby server (geyser is in the proxy)

### Steps to Reproduce

1. Login with any bedrock version
2. You get disconnected

### Expected Behavior

Shouldn't be disconnected

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1966%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Purpur--1966%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.5): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by PyroFT** [comment]
currently having the same issue as well. Everything is up to date.

**Comment by tanzbr** [comment]
downgrading viaversion worked for me for now

**Comment by PyroFT** [comment]
Also, this is not happening on all devices. Most of my reports are on Xbox and Android tablets. Some can connect and some cant connect.

**Geyser dump**: https://mclo.gs/QfErlK4
**Client-side**: "Proxy lost connection to server"
**Viaversion dump**: https://dump.viaversion.com/7c62ae2dd3e8a35ca141e83b6654366fedfe35c799fc5f8fda80e427788c764a (tried different versions as well jar wise)
**Error displayed on hub**: "lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 10"
**Waterfall Version**: This server is running Waterfall version git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:00122d2:555 by md_5

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1428%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Purpur--1428%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.5): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kas-tle** [comment]
I have isolated it to this change https://github.com/ViaVersion/ViaVersion/commit/45d08e9066802e5ae478b9efe97df73443005f77#diff-cc9af48232f8b745ee0a4d9bc8073480f40eb137d8c8d85db58732cd6d1446c1R153-R156

**Comment by kennytv** [comment]
This sounds more like an issue in Geyser setting the client state change too late

**Comment by Kas-tle** [comment]
Hi Kenny, while we (Geyser) are certainly open to this being our issue, I am having a hard time understanding how that could be the case here. As far as I can tell, based on the name of the message channel, this is being caused by custom payload packets that are being originated by the another plugin on the proxy on behalf of the player, not sent by Geyser directly. 

In terms of staying in the config phase for too long, Geyser should exit the config phase relatively quickly once we receive the packet from the server notifying us that we can. This is handled in MCProtocolLib and it's basically as soon as we get the packet allowing us to exit the config phase that we acknowledge it: https://github.com/GeyserMC/MCProtocolLib/blob/master/src/main/java/com/github/steveice10/mc/protocol/ClientListener.java#L126. I've noticed that this issue only seems to happen with a remote Geyser instance. When I run one locally (with Bungee still remote) we don't encounter this issue. But moving Geyser closer or the Bedrock client should, increase the amount of time we are in the config phase, since it introduces a delay between us getting the packet that allows us to exit config and acknowledging it.

**Comment by onebeastchris** [comment]
I can reproduce the issue with a clean 1.20.3 Vanilla Minecraft Java client and a 1.19.4 paper server. 

Full log: https://mclo.gs/akO6q10
Viaversion dump: https://dump.viaversion.com/b47e7927f3f29f798bda23b07488a6e1bc6bdc87cd30370caedc0c0e05565492
Debug messages that adds a few debug prints: https://github.com/ViaVersion/ViaVersion/compare/master...onebeastchris:ViaVersion:master

It looks like this issue isn't related to Geyser specifically :/

**Comment by Barvalg** [comment]
![Platform: git--Paper--550%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--550%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Please try with the now latest ci build, I reverted a change (though I don't see why it would cause that without anything else interfering) until I have time to properly look into this

**Comment by onebeastchris** [comment]
you're welcome :)
Works just fine now. Is the fix available in the dev build, or the master one? Just so we know what to tell affected Geyser users

**Comment by kennytv** [comment]
Master, dev is dormant until a new snapshot with protocol changes releases. Usually (except for the last version), fixes to the last release will also always go into mater first
