### ISSUE TITLE
Certain blocks break very slowly on 1.20.3 client (1.20.2 server)

### ISSUE THREAD

**Issue by andrewkm** [ViaVersion/ViaVersion#3549]
### `/viaversion dump` Output

https://dump.viaversion.com/1f0d9cc18a9d55c686d00b3e1004dbd0a84cf001327c9a0e00fb0089af0a1b35

### Console Error

No visible console errors/abnormalities.

### Bug Description

Certain blocks such as cobbled deepslate break very slowly while using a 1.20.3 client via a 1.20.2 server.
If this is **not** a ViaVersion bug my apologies, just kind of figured it may be related.

Cannot reproduce when using a 1.20.2 client on 1.20.2 server.
Video: https://www.youtube.com/watch?v=5M91dtrmrmg

### Steps to Reproduce

1. Login with 1.20.3 client (running 1.20.2 server)
2. Place some cobbled deepslate.
3. Grab an efficiency 5 diamond pickaxe.
4. Observe the days go by endlessly while you fail block game miserably.

### Expected Behavior

Break at regular speeds.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--318%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--318%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by ethanlaj** [comment]
I have the same issue.

**Comment by Brokkonaut** [comment]
Those blocks have the incorrect tag set, with F3 you can see that in 1.20.3 client on 1.20.2 server it is "#minecraft:mineable/axe" while it should be "#minecraft:mineable/pickaxe". Same for stone bricks.

**Comment by mrfloris** [comment]
I had a whole bug report submit page open and filled out, and fall asleep only to wake up to seeing someone posting it and someone else fixing it. Thank you all for the hard work.
