### ISSUE TITLE
Isolates players who log into the server with the Bedrock edition.

### ISSUE THREAD

**Issue by GITamdegor** [ViaVersion/ViaVersion#3555]
### `/viaversion dump` Output

https://dump.viaversion.com/3f6c405ba4cf42f9181d82192864db7f5c8c901f23632b041b7b292a3f3b82d9

### Console Error

```
https://paste.gg/p/anonymous/29526e9672eb4a42b5da906ea8f9f79d
```

### Bug Description

A player who enters the server using the Bedrock edition of Minecraft is simply disconnected from the server.

### Steps to Reproduce

Login to the server 

### Expected Behavior

The player must enter and play normally 

### Additional Server Info

I'm using Paper.jar

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--196%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--196%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.9.1): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.1)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>
