### ISSUE TITLE
1.20.3 players sometimes disconnected on join on 1.20.1 servers

### ISSUE THREAD

**Issue by realriccio** [ViaVersion/ViaVersion#3557]
### `/viaversion dump` Output

https://dump.viaversion.com/a2b082572f50ef50e220f8e0694ff71e359e8ff913ca9a9be219768cb2eb0f36

### Console Error

UUID of player *player* is *uuid*
*player* lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 13
*player* left the game

### Bug Description

About 40% of the times a 1.20.3 player joins a 1.20.1 server he gets kicked with the console error specified.
The error is only visible in the server's console, to him only "Disconnected" is shown as soon as he joins.

### Steps to Reproduce

1. Create a 1.20.1 Paper server.
2. Add the latest ViaVersion plugin.
3. Join repeatedly with a 1.20.3 client until the error occurs.

### Expected Behavior

The player should be able to join normally every time.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Kas-tle** [comment]
Could you please send a viaversion dump (run `viaversion dump` in console on the server you have with the viaversion plugin. Also could you confirm that these are Java players and not Bedrock players (if you run Geyser)?

**Comment by realriccio** [comment]
They are unmodded java players. No other plugin is added. Adding a dump in an hour.

**Comment by Rockin21** [comment]
I'm also having this problem

**Comment by onebeastchris** [comment]
I can reproduce the issue with a clean 1.19.4 paper server + latest viaversion, and then a 1.20.3 vanilla java client. Doesn't happen every time, but fairly reliably

Logs: https://mclo.gs/GXQPGgK

**Comment by kennytv** [comment]
Please try with the now latest ci build, I reverted a change (though I don't see why it would cause that without anything else interfering) until I have time to properly look into this

**Comment by onebeastchris** [comment]
That does seem to resolve the issue! (For both 1.20.2/1.20.3 vanilla, and Geyser). Thanks for the quick fix :)
