### ISSUE TITLE
io.netty.handler.codec.DecoderException: java.io.IOException: Packet login/0 (afr) was larger than I expected, found 318 bytes extra whilst reading packet 0

### ISSUE THREAD

**Issue by gre3x** [ViaVersion/ViaVersion#3558]
### `/viaversion dump` Output

https://dump.viaversion.com/487aa04d48c3e4324c10a9950d7dd8980ab40917b2a8f6d1bf5174959b30b2fc

### Console Error

https://mclo.gs/M1Sorvc

### Bug Description

When joining my Hub/Lobby server, 1.20.3 clients get kicked with the below message. It also sends many errors in console (see console error above). This did not happen prior to 1.20.3 update. I am using latest Waterfall and ViaVersion as of writing this.

```io.netty.handler.codec.DecoderException: java.io.IOException: Packet login/0 (afr) was larger than I expected, found 318 bytes extra whilst reading packet 0```

![image](https://github.com/ViaVersion/ViaVersion/assets/123699236/762f83f2-b5a3-4831-9792-f811a67319a2)

### Steps to Reproduce

1. Connect with 1.20.3 client

### Expected Behavior

I should be able to connect with no errors

### Additional Server Info

Hub/Lobby server: Paper-1620 (MC: 1.12.2)
Proxy: Waterfall-556 (1.20.3)
ViaVersion is running on the backend servers: git-ViaVersion-4.9.2-SNAPSHOT:1ad65d1bb

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.5): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by gre3x** [comment]
I have discovered that removing BadlionClientModAPI from the proxy does fix this for the backend servers. Feel free to close this if that is good enough for you lol

I already raised an issue with the BadlionClientModAPI plugin: https://github.com/BadlionClient/BadlionClientModAPI/issues/38
