### ISSUE TITLE
chat issues on older server version

### ISSUE THREAD

**Issue by SpEeD11** [ViaVersion/ViaVersion#3563]
### `/viaversion dump` Output

https://dump.viaversion.com/92162091f201d7a801ca5452dc49d172b769b2aa141c915238163ea89fb0ea99

### Bug Description

Same issue as #3551 #3552 #3560 , but for 1.8.8 servers

Tested with Paper 1.20.2 and the issue is indeed fixed, but there are still issues on older versions.
For example. /say test results in [%s] %s being shown in chat. Many json messages in chat are also messed up or partly invisible
![image](https://github.com/ViaVersion/ViaVersion/assets/17742256/a0d47d67-361b-49af-954e-f3146c03e9a7)
![image](https://github.com/ViaVersion/ViaVersion/assets/17742256/fa7122bb-8e30-4676-8b5b-611b8103103b)
When on a bungee/waterfall network, the player is kicked when any of these messages are sent

I understand 1.8.8 is no longer supported, but if its an easy fix I would greatly appreciate this being fixed instead of having to look for workarounds.

### Steps to Reproduce

1. use 1.20.3 client on 1.8.8 server
2. /say test in console, or display a custom json message in chat
3. message doesnt show correctly and/or player is kicked

### Expected Behavior

text should display correctly and player should not be kicked

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by ks-hl** [comment]
Paper 1.20.2 with Waterfall and Venturechat. ViaVersion 4.9.2. Same issue.

**Comment by 404XiaoTuHao** [comment]
Vanilla 1.20.3 join fabric 1.17.1 server also has this issue

**Comment by kennytv** [comment]
https://github.com/ViaVersion/ViaVersion/commit/cf5f5ed4bb30d5a66f3a9f03a1699602b3007d11

**Comment by SpEeD11** [comment]
Hi, thanks for the fix.

Still a small issue, Not sure if intended but messages now have quotation marks added

![image](https://github.com/ViaVersion/ViaVersion/assets/17742256/742ddd7d-4b24-4936-b4e8-a50f62aed2b5)
