### ISSUE TITLE
Teams with a specific prefix make Bungee(Waterfall) to error

### ISSUE THREAD

**Issue by MATRIX-feather** [ViaVersion/ViaVersion#3564]
### `/viaversion dump` Output

https://dump.viaversion.com/54fbdda3825517132ffa7078d0e58799a3f6a9dbf94abee2a9ada8131203b743

### Console Error

Error on the proxy: https://paste.gg/p/anonymous/68dec44d7a774cf8bae37355447f1e88

The backend server didn't print any error.

### Bug Description

Teams with a translatable prefix with string and JSON elements combined inside would make Bungee(Waterfall) error and kick players with >= 1.20.3 clients from 1.20.2/1.20.1 backends all the time。

### Steps to Reproduce

- Create a team with `/team create test`
- Modify its prefix with `/team modify test prefix {"translate":"%1$s%3427655$s", "with":["", {"text":"1"}]}`
    - If you replace the first element with "test2", the error message on the proxy will later change to `Not a JSON Object: ["test2"]`
- Kicked with `The server you were previously on went down, you have been connected to a fallback server`

### Expected Behavior

A command feedback with the team prefix `%1$s%3427655$s` should be displayed on the client and not kicking the player

### Additional Server Info

Used Waterfall build `#556` with default config and no plugins

(The same issue was also reported to BungeeCord: https://github.com/SpigotMC/BungeeCord/issues/3570)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--318%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--318%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Bungee issue, but should be avoided with https://github.com/ViaVersion/ViaVersion/commit/cf5f5ed4bb30d5a66f3a9f03a1699602b3007d11
