### ISSUE TITLE
Different "ERROR IN Protocol" errors caused by NullPointerException

### ISSUE THREAD

**Issue by KeppLex** [ViaVersion/ViaVersion#3566]
### `/viaversion dump` Output

https://dump.viaversion.com/c7284bb9b5be1fbe072bd97fce7a0f52ffd285af0920f81f17c844364c2025af

### Console Error

[Error(s) link](https://paste.gg/p/anonymous/b82e1aa4a4ed445fbff72972c5d011b3)

### Bug Description

Different of our servers are displaying the errors shown before for different packets (ENTITY_METADATA, ENTITY_PROPERTIES, PLAYER_POSITION, ENTITY_TELEPORT, etc).
They appear at random, for different versions and different clients, including vanilla.
These errors were not present before ViaVersion 4.8.0. and started showing up after updating to 4.8.x. Although the dump was run in ViaVersion 4.9.2 these are also present in latest dev builds.
I understand these errors might be caused by a different plugin, but we find it odd that they were not present before 4.8.0 (e.g. 4.7.0) and the plugins did not change since then.
Thank you.

### Steps to Reproduce

There are no specific steps to reproduce these errors as they appear at random.

### Expected Behavior

No errors present.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--TacoSpigot--%2295870a93%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--TacoSpigot--%2295870a93%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by HowardZHY** [comment]
https://github.com/ViaVersion/ViaVersion/issues/3514
