### ISSUE TITLE
Sending resourcepack from server 1.20.2 to 1.20.3

### ISSUE THREAD

**Issue by DxrkCat** [ViaVersion/ViaVersion#3567]
### `/viaversion dump` Output

https://dump.viaversion.com/4e1f8d07a19f2b4e30456a95da08d694be8cfc7f5b91ee9f9690b1c2b40b2d95

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

If I login from Fabric 1.20.3 with only ViaFabricPlus and FabricAPI, to a 1.20.3 server with ViaVersion + ViaBackWards, no resourcepack is sent to me. If I log in with 1.20.2, the resourcepack is sent. The server is under Velocity build 296.

### Steps to Reproduce

If I login from Fabric 1.20.3 with only ViaFabricPlus and FabricAPI, to a 1.20.3 server with ViaVersion + ViaBackWards, no resourcepack is sent to me. If I log in with 1.20.2, the resourcepack is sent. The server is under Velocity build 296.

### Expected Behavior

The resourcepack should be sent

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2094%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Purpur--2094%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
