### ISSUE TITLE
IllegalStateException with >1.20.2 clients on Waterfall

### ISSUE THREAD

**Issue by mercurialmusic** [ViaVersion/ViaVersion#3568]
### `/viaversion dump` Output

https://gist.github.com/mercurialmusic/dcf597bee6317dae6dbd86adee3efc5e

### Console Error

https://gist.github.com/mercurialmusic/4da51fb572ee4e4b689d09cfcd11128e

### Bug Description

I'm not sure if this is a VentureChat or a ViaVersion or a Waterfall thing so I'm putting it everywhere to see if it sticks, but looks like there may be a couple related issues already. Starting a new one since the use case is at least slightly different.

Using anything newer than a 1.20.2 client, players are being kicked from the network on any global chat events on bungee-wide channels with the above error.

### Steps to Reproduce

Login with a >1.20.2 client.
Weep when you're kicked when anyone says anything in chat.

### Expected Behavior

No kicks on chat.

### Additional Server Info

I'm using VentureChat 3.6.0 on git-Paper-318 (MC: 1.20.2)/git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:d85fe36:556 with ViaVersion-4.9.3-SNAPSHOT-b750 on the Paper servers only.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Bungee issue, but should no longer happen with https://github.com/ViaVersion/ViaVersion/commit/cf5f5ed4bb30d5a66f3a9f03a1699602b3007d11

**Comment by mercurialmusic** [comment]
The attempt is appreciated, but the issue has only morphed. Now instead of being kicked on any chat event, the player is kicked when they themselves chat. No errors in Bungee or backend consoles but the client gets kicked with a face full of what looks like json that can't be dismissed (have to force-close the game). 

Error from client logs:
https://gist.github.com/mercurialmusic/c0c5c326f79b606cd9259310df3c596c
