### ISSUE TITLE
Player's getting kicked with JSON error

### ISSUE THREAD

**Issue by Sckaletz** [ViaVersion/ViaVersion#3569]
### `/viaversion dump` Output

https://dump.viaversion.com/4d6cad5719bb8d048869d08f46da5ea6d12e8e03343e1bcd42e3b8440fecae97

### Console Error

```
https://paste.gg/p/anonymous/a5ef4957a56b4fffbc075fd27e8cf1c1
https://paste.gg/p/anonymous/7abc5a864c9b4988afa21be0b4f3660b (without any Bungeecord plugins)
```

### Bug Description

Problem is there when trying to join with 1.20.2, 1.20.3 and 1.20.4. We have also tried the Bungeecord without any plugins and the problem is the same.

https://paste.gg/p/anonymous/a5ef4957a56b4fffbc075fd27e8cf1c1
https://paste.gg/p/anonymous/7abc5a864c9b4988afa21be0b4f3660b (without any Bungeecord plugins)

When connecting to the server without Bungeecord, it connects fine. But through Bungeecord the player can't connect and is kicked.

The server is a PaperSpigot 1.8.8 with [ViaVersion-4.9.3-SNAPSHOT.jar](https://ci.viaversion.com/job/ViaVersion/750/artifact/build/libs/ViaVersion-4.9.3-SNAPSHOT.jar)

Bungeecord build https://github.com/SpigotMC/BungeeCord/issues/1777.

According to both the Spigot and Paper team, this is a Viaversion issue.

### Steps to Reproduce

Join with 1.20.2+ on the latest Bungeecord version and with a 1.8.8 server.

### Expected Behavior

For players to be able to join.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--445%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Sckaletz** [comment]
I just tried with Viaversion #740 on my PaperSpigot 1.8.8 server. With that versions 1.20.2 can join, but 1.20.3 and 1.20.4 can't.

**Comment by kennytv** [comment]
This is a Bungee issue, but should happen less often with https://github.com/ViaVersion/ViaVersion/commit/cf5f5ed4bb30d5a66f3a9f03a1699602b3007d11
