### ISSUE TITLE
quotation marks around strings after json array fix

### ISSUE THREAD

**Issue by SpEeD11** [ViaVersion/ViaVersion#3570]
### `/viaversion dump` Output

https://dump.viaversion.com/92162091f201d7a801ca5452dc49d172b769b2aa141c915238163ea89fb0ea99

### Bug Description

Continuation of #3563 

issue is fixed but still a small problem, messages now have quotation marks added, not sure if intended

![image](https://github.com/ViaVersion/ViaVersion/assets/17742256/82ae6298-8a5f-40ef-8695-df62f3e61b60)

### Steps to Reproduce

show a json message in chat

### Expected Behavior

text should not have quotation marks

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--445%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 5 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Jo0001** [comment]
Works fine for me with the latest ViaVersion https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/build/libs/ViaVersion-4.9.3-SNAPSHOT.jar and a 1.20.4 Client
