### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Tioplaya** [ViaVersion/ViaVersion#3571]

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 5 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>
