### ISSUE TITLE
quotation marks in text after fix for #3563 (1.8.8 server, 1.20.4 client)

### ISSUE THREAD

**Issue by SpEeD11** [ViaVersion/ViaVersion#3572]
### `/viaversion dump` Output

https://dump.viaversion.com/9471a8d38bd8af6c6a228d0835f9a18ee7d83e484922445647f21cc5a352f1a9

### Bug Description

continuation of #3563 

Running 1.8.8 paper server with latest viaversion, client version 1.20.4
after the fix for #3563, a lot of text contains quotation marks. example below, note it should say [Server] test, not ["Server"] test
![image](https://github.com/ViaVersion/ViaVersion/assets/17742256/c3f4251c-5a7c-46b1-a668-0c43274d354a)

this affects other messages too such as json chat messages etc

not sure if this only happens for 1.8.8 server version, but a fix would be appreciated

### Steps to Reproduce

use 1.20.4 or 1.20.3 client on 1.8.8 server
do /say test in console
message displays with quotation marks

### Expected Behavior

text should not contain quotation marks

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--445%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
