### ISSUE TITLE
1.20.3 short_grass

### ISSUE THREAD

**Issue by TheKidThatCodes** [ViaVersion/ViaVersion#3574]
### `/viaversion dump` Output

https://dump.viaversion.com/ffa1048747ecf6906e3048b4f4bd5d3aee7b51f9bb3fc1b60ebab9e396ff7769

### Console Error

error on client
```
[Render thread/INFO]: Connecting to localhost, 25565
[Render thread/WARN]: Unknown custom packet payload: polymer:hello
[Render thread/ERROR]: Received unknown remote registry entries from server
[Render thread/ERROR]: Registry entry (minecraft:grass) is missing from local registry (minecraft:item)
[Render thread/ERROR]: Registry entry (minecraft:grass) is missing from local registry (minecraft:block)
[Render thread/ERROR]: Registry remapping failed!
java.util.concurrent.CompletionException: net.fabricmc.fabric.impl.registry.sync.RemapException: Received 2 registry entries that are unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related: minecraft
```
(timestamps removed and semi edited for readability, don't worry i just removed whitespace i didn't remove important things)

### Bug Description

1.20.4/1.20.3 client with vfp cant join velocity with vv and vb cant connect to 1.20.2 fabric server

### Steps to Reproduce

make velocity instance with vv and put a 1.20.2 fabric server behind it (with the proxy accept mod dont forget that otherwise player info forwarding is weird)
join with a 1.20.4 client (fabric with vfp)

### Expected Behavior

can connect and doesent give an error screen when connecting

### Additional Server Info

the dump says it all
velocity 3.3.0 snapshot
fabric 15.1 server with proxy accepter mod whatever it is
fabric 1.20.4 client (vfp? i dont think its needed tho)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--b270206d--b301%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--b270206d--b301%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.1): 7 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by TheKidThatCodes** [comment]
https://dump.viaversion.com/d7a08c16ec2c2dac5b19c01e24d5fd4bccb53333702b90932e7f848ef44afa1c

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--b270206d--b301%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--b270206d--b301%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--9b2ba535%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--9b2ba535%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
