### ISSUE TITLE
Problems with chat on 1.20.3/1.20.4

### ISSUE THREAD

**Issue by Xayanix** [ViaVersion/ViaVersion#3575]
### `/viaversion dump` Output

https://dump.viaversion.com/43fd16e429134d9eb12c2a456f2781510ed632f3978bb5ff3e9391d9f365c697

### Console Error

```
[Put the paste.gg link or text here.](https://paste.gg/p/anonymous/3a269be777074dbb93dbf24a8285128a)
```

### Bug Description

Chat is not working correctly on 1.20.3 and 1.20.4.
Tried with bungeecord and without it too.

### Steps to Reproduce

Create 1.8.9 server with ViaVersion.
Use Waterfall proxy to connect to it.

Send for example this message to player:
```player.sendMessage("                           §6§lNETHER§e§lSTORM");```

You got exception

### Expected Behavior

obvious

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--%224c7641d%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--%224c7641d%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 9 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Xayanix** [comment]
Nvm, fixed in dev build
