### ISSUE TITLE
Books being wierd

### ISSUE THREAD

**Issue by agoniaprivat** [ViaVersion/ViaVersion#3579]
### `/viaversion dump` Output

https://dump.viaversion.com/6faec20570d53e224edd3ca77a64621bcb1f0c77c801892cb885aea65296892b

### Console Error

No errors.

### Bug Description

Books with customized text does not work on 1.20.4.

### Steps to Reproduce

Make a book with like https://minecraft.tools/en/book.php and spawn it in. It will look different on 1.20.4 compared to 1.20.1. See pictures. 
Book on 1.20.1 (the servers real version)
Please note: I was able to reproduce the same thing without being on featherclient. Screenshot was sent by a player.
![bookon1 20 1](https://github.com/ViaVersion/ViaVersion/assets/50961682/e0538b90-b08f-4dda-9ba6-5356698b4ee1)

Book on 1.20.4
![bookon1 20 4](https://github.com/ViaVersion/ViaVersion/assets/50961682/b3bee844-b042-4ab5-87e8-949dcf57dbe9)

### Expected Behavior

See above.

### Additional Server Info

Velocity

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--b270206d--b301%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--b270206d--b301%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Jo0001** [comment]
I can reproduce this, same issue also on a pure paper server. Seems to only affact 1.20.3/4 as 1.20.2 is also fine

**Comment by kennytv** [comment]
This should presumably be fixed now
