### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SkirmisLTU** [ViaVersion/ViaVersion#3580]
### `/viaversion dump` Output

https://dump.viaversion.com/8a31f24fbcc43de3a2de5a0aaec2015f846b3754f0f5896f6602674ff307d936

### Console Error

```
Put the paste.gg link or text here.
```
https://pastebin.com/dhSu8rkL

### Bug Description

I get this error in console. It 

### Steps to Reproduce

1. Create 1.20.2 server
2. Install ViaVersion
3. Let people join with idk what versions
4. Get the error in console

### Expected Behavior

No error in console

### Additional Server Info

I use bungeecord and viabackwards

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2094%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Purpur--2094%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards (4.9.2-SNAPSHOT+polar-fix): Error fetching commit data](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT+polar--fix)-Error%20fetching%20commit%20data-lightgray?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Kichura** [comment]
1. You are a fork of viaversion which may contain code that could break the translation system,
2. If using the actual latest CI builds of viaversion does not work either then it's a third party plugin causing viaversion to fail.
