### ISSUE TITLE
1.20.1 does not allow players on 1.20.2 or higher to connect

### ISSUE THREAD

**Issue by T14D3** [ViaVersion/ViaVersion#3583]
### `/viaversion dump` Output

https://dump.viaversion.com/7e76fb8cfcfa216ebf0c96f980a913119f6cc502c104eaa7084a5526b26efc45

### Console Error

No console error, client disconnect message:
```
Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet play/24 (vh) was larger than I expected, found 199 bytes extra whilst reading packet 24
```

### Bug Description

Logging in with vanilla 1.20.2 client with basically no plugins (see dump output) causes the client to immediately disconnect

### Steps to Reproduce

1. Login with 1.20.2+ client on 1.20.1 Server
2. Get Disconnected

### Expected Behavior

To not get disconnected?

### Additional Server Info

Latest Waterfall, ViaVersion installed on backend (not on proxy), Backend is running pufferfish (can try with vanilla paper if needed), only plugins are Luckperms, Vault, Protocollib and ViaVersion

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--19%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Pufferfish--19%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Does this persist with pufferfish 1.20.2? If yes; something is screwing up the play packet.

**Comment by CoryBorek** [comment]
I tested on paperfix 1.20.1 and paper 1.20.2. It seems to disconnect when using a 1.20.1 with the same error, but works as intended when using a regular paper 1.20.2 instance. Haven't tested pufferfish, so I can't say much there.

**Comment by Kichura** [comment]
Decided to give pufferfish 1.20.4 a test run and i could not reproduce it so either the 1.20.2 version was busted or a sudden bad world save was in place without knowledge.
