### ISSUE TITLE
ViaVersion on 1.20.2 doesn't allow older versions to connect

### ISSUE THREAD

**Issue by uiytt** [ViaVersion/ViaVersion#3584]
### `/viaversion dump` Output

https://dump.viaversion.com/eaa5bf4a12786b9b2cf7b7b684aa358479ebbb98e050ab09a6744c0b5d253d5c

### Console Error

With `/viaversion debug`
```
14:27:59 INFO]: [ViaVersion] SERVERBOUND HANDSHAKE: 0 (0x00) -> 0 (0x00) [-1] PacketWrapper{type=null, id=0, values=[], readable=[]}
[14:27:59 INFO]: [ViaVersion] User connected with protocol: 761 and serverProtocol: 764
[14:27:59 INFO]: [ViaVersion] Protocol pipeline: [Protocol:BaseProtocol, Protocol:BaseProtocol1_16]
[14:27:59 INFO]: [ViaVersion] Client state changed from HANDSHAKE to LOGIN for null
[14:27:59 INFO]: [ViaVersion] Server state changed from HANDSHAKE to LOGIN for null
[14:27:59 INFO]: [ViaVersion] CLIENTBOUND LOGIN: 0 (0x00) -> 0 (0x00) [761] PacketWrapper{type=null, id=0, values=[], readable=[]}
```

### Bug Description

ViaVersion is installed on a 1.20.2 paper server. It activates just fine, there is no error in the console. All viaversions commands works fine. I can connect without problem with a 1.20.2 client
But if I try to connect with a 1.19.x version. I receive "Outdated Client"
Using 3.9.2 version of ViaVersion doesn't solve the problem.

### Steps to Reproduce

1. Login with an old version on an 1.20 server

### Expected Behavior

Correct logging.

### Additional Server Info

I don't use a Proxy.
I'm on paper Paper #318

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--318%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--318%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
You are missing viabackwards. *(+ if you needed 1.8.9 support, deploy viarewind aswell)*
