### ISSUE TITLE
ERROR IN Protocol1_13To1_12_2 IN REMAP OF CHUNK_DATA (0x20)

### ISSUE THREAD

**Issue by F3F5** [ViaVersion/ViaVersion#3585]
### `/viaversion dump` Output

https://dump.viaversion.com/159e1ed01337669cde279d55ca347a7dbfc11d40bce87dcc07cd014a7a37fc9d

### Console Error

https://paste.gg/p/anonymous/e6f4c5a69087450088bd90579c983323

### Bug Description

player joined

### Steps to Reproduce

i dont know

### Expected Behavior

.

### Additional Server Info

.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Reaper--%22fff830c%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Reaper--%22fff830c%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.5): 1 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.9.0)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by F3F5** [comment]
https://dump.viaversion.com/b4158c5e8fded78e72d7e782ba4aed35a087266c2d295f4cee919e81dd6359bc

**Comment by Barvalg** [comment]
![Platform: git--Reaper--%22fff830c%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Reaper--%22fff830c%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
This is very likely caused by a third-party plugin sending bad chunk data, please perform a binary search to see what causes viaversion to complain about it.

**Comment by F3F5** [comment]
> This is very likely caused by a third-party plugin sending bad chunk data, please perform a binary search to see what causes viaversion to complain about it.

none plugins sending chunk data

**Comment by Kichura** [comment]
> > This is very likely caused by a third-party plugin sending bad chunk data, please perform a binary search to see what causes viaversion to complain about it.
> 
> none plugins sending chunk data

Can you test with just viaversion active to see if it recovers? *(although i may suspect the reaper software to cause problems instead if it still persists)*

**Comment by F3F5** [comment]
> > > This is very likely caused by a third-party plugin sending bad chunk data, please perform a binary search to see what causes viaversion to complain about it.
> > 
> > 
> > none plugins sending chunk data
> 
> Can you test with just viaversion active to see if it recovers? _(although i may suspect the reaper software to cause problems instead if it still persists)_

i dont know how to cause this error

**Comment by F3F5** [comment]
but sometimes appears

**Comment by F3F5** [comment]
Core: https://github.com/ruViolence/Reaper (from actions)

**Comment by Kichura** [comment]
yeah this definitely is a paper fork problem then rather than ours.

**Comment by F3F5** [comment]
> yeah this definitely is a paper fork problem then rather than ours.

why

**Comment by Raraph84** [comment]
Same error here on Spigot 1.12.2 and 1.16.5 :/

**Comment by F3F5** [comment]
> Same error here on Spigot 1.12.2 and 1.16.5 :/ And no plugins sending world packets

@Kichura

**Comment by Kichura** [comment]
Could not reproduce your problem at all,

Paper 1.16.5 with 1.12.2 client:
![a](https://github.com/ViaVersion/ViaVersion/assets/68134602/bbd9b335-a254-4ba1-8989-4cb8d380ecd3)

Paper 1.12.2 with 1.13.2 client:
![b](https://github.com/ViaVersion/ViaVersion/assets/68134602/0f34ad63-7376-48cd-bd2f-1a56e3671f96)

**Comment by Raraph84** [comment]
It is very random, I will try to find the exact way to reproduce this and I recomment here when I find

**Comment by Raraph84** [comment]
Okay I have this setup :
Spigot 1.12.2 with ViaVersion, ViaBackwards and ViaRewind, all latest version on SpigotMC (i can try the latest versions on Jenkins if you want)
I am connecting to the server and leaving the server as soon as possible and it throws the error
I tried 1.8.9, 1.12.2, 1.13.2 and 1.16.5 clients and the errors throws only on 1.8.9 and 1.16.5
My Spigot is behind BungeeCord (latest version on the SpigotMC Jenkins), I didn't tried to connect directly to the Spigot
Tell me if you want more informations

**Comment by Raraph84** [comment]
Edit :
I tried direct connection to Spigot 1.12.2 with only ViaVersion and from 1.16.5 client and I was able to reproduce the bug
I also tried the latest version of ViaVersion on the Jenkins and I have the errors

**Comment by Kichura** [comment]
> Edit : I tried direct connection to Spigot 1.12.2 with only ViaVersion and from 1.16.5 client and I was able to reproduce the bug I also tried the latest version of ViaVersion on the Jenkins and I have the errors

from what i know, spigot in general is known for running quite poorly compared to paper in terms of fixes - can you test with that instead?

**Comment by Raraph84** [comment]
> > Edit : I tried direct connection to Spigot 1.12.2 with only ViaVersion and from 1.16.5 client and I was able to reproduce the bug I also tried the latest version of ViaVersion on the Jenkins and I have the errors
> 
> from what i know, spigot in general is known for running quite poorly compared to paper in terms of fixes - can you test with that instead?

I just tried and it doesn't seem to throw the error

**Comment by Raraph84** [comment]
> > Edit : I tried direct connection to Spigot 1.12.2 with only ViaVersion and from 1.16.5 client and I was able to reproduce the bug I also tried the latest version of ViaVersion on the Jenkins and I have the errors
> 
> from what i know, spigot in general is known for running quite poorly compared to paper in terms of fixes - can you test with that instead?

Okay I sent that I was not able to reproduce the bug with paper but after another try I was able to reproduce it, it is very random or I am not fast enough to leave the server

**Comment by F3F5** [comment]
> > Edit : I tried direct connection to Spigot 1.12.2 with only ViaVersion and from 1.16.5 client and I was able to reproduce the bug I also tried the latest version of ViaVersion on the Jenkins and I have the errors
> 
> from what i know, spigot in general is known for running quite poorly compared to paper in terms of fixes - can you test with that instead?

what i know old versions of via i dont see this problem

**Comment by F3F5** [comment]
nice ignore

**Comment by Raraph84** [comment]
Any news?
