### ISSUE TITLE
a got a bug with packets

### ISSUE THREAD

**Issue by Cyberillc** [ViaVersion/ViaVersion#3590]
### `/viaversion dump` Output

dump.viaversion.com/c0ea7f8f6b6c9963a4f6f59bb65cc388cb766447b7ec2a2566895b6de1448ddf

### Console Error

Packet Type: UPDATE_SCORE, Type: VarInt, Index: 1, Data: [{StringType: 6d7b87a7-1824-4ebc-8d04-362633afe181}], Source 0: com.viaversion.viabackwards.protocol.protocol1_17_1to1_18.Protocol1_17_1To1_18$5 (Anonymous), Packet ID: 86

<img width="907" alt="Screenshot 2023-12-20 at 9 50 17 PM" src="https://github.com/ViaVersion/ViaVersion/assets/142674955/6536d728-6c3b-4a94-bc45-0f2d0d4a72db">

### Bug Description

Packet Type: UPDATE_SCORE, Type: VarInt, Index: 1, Data: [{StringType: 6d7b87a7-1824-4ebc-8d04-362633afe181}], Source 0: com.viaversion.viabackwards.protocol.protocol1_17_1to1_18.Protocol1_17_1To1_18$5 (Anonymous), Packet ID: 86

### Steps to Reproduce

load 1.16.5
load the plugins
join 
kicked

### Expected Behavior

should not kick player

### Additional Server Info

i used purpur with these plugins viaversion essentialsX fast leaf decay 1.0.0 let me despawn playitgg chunky antilag bluemap chunky border spark clearlag

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Cyberillc** [comment]
<img width="1066" alt="Screenshot 2023-12-20 at 9 52 39 PM" src="https://github.com/ViaVersion/ViaVersion/assets/142674955/f17a81f1-7a54-48ab-91da-256977997cc0">

**Comment by kennytv** [comment]
>  I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
Please don't tick what you haven't done
