### ISSUE TITLE
Unable to join 1.19.3 server using 1.20.4 Client

### ISSUE THREAD

**Issue by Tux2** [ViaVersion/ViaVersion#3592]
### `/viaversion dump` Output

https://dump.viaversion.com/2b4c9e5801a9215f3846547c3021259f7bc4f75880a913e75c51b5bc7ef0f8d4

### Console Error

```
https://paste.gg/p/anonymous/840c7569faff44078bec80ba6d0861d5
```

### Bug Description

Trying to log in to the server kicks you back out. Unable to log in.

### Steps to Reproduce

1. Log in to a 1.19.3 server using a 1.20.4 client.
2. Unable to reconnect

### Expected Behavior

You should be able to log in

### Additional Server Info

I use BungeeCord version BungeeCord-Bootstrap:1.20-R0.2-SNAPSHOT:b711e40:1782 by md_5
Using plugins:
BungeeResourcepacks
BuycraftX
DynamicBungee (Custom Plugin)
EasyStaffChat
PartyAndFriends
RPermissions (Custom Plugin)
RSMVMutesPAFAddOn (Custom Plugin)
Yamler-Bungee-2.4.0-SNAPSHOT
Floodgate

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3645--Spigot--19641c7--7cd3244%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-3645--Spigot--19641c7--7cd3244%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.1): 11 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Tux2** [comment]
```
https://dump.viaversion.com/e9c75697600728332d0256fdba7985360c4497677d647644ba5383c10a75df72 
```
New Dump

**Comment by Barvalg** [comment]
![Platform: 3645--Spigot--19641c7--7cd3244%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-3645--Spigot--19641c7--7cd3244%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
This is likely caused by a third-party plugin causing player info updates not to be sent correctly, Please perform a binary search to see what's causing viaversion to fail.

**Comment by Tux2** [comment]
Can be marked as resolved. BungeeCord updated and it doesn't kick me to the lobby now when trying to join.
