### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by SkirmisLTU** [ViaVersion/ViaVersion#3593]
### `/viaversion dump` Output

https://dump.viaversion.com/f580bc9f70a06d001f03f6fd58a896deb7f58ca36f9a36815d4c2dd12edf6904

### Console Error

https://paste.gg/p/anonymous/77cb728cc6834d0f8c177262433cb5fe

### Bug Description

We were playing, and server just crashed. It says *Please report this on the Via support Discord or open an issue on the relevant GitHub repository* in error, and it looks like ViaVersion error

### Steps to Reproduce

Unknown. 
All I know that the player was on 1.18.2 client (Server is on 1.8.8). We are using bungee (XCord 1.56)

### Expected Behavior

No crash

### Additional Server Info

Plugins are provided in the dump. We are using bungeecord (XCord 1.56)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: WindSpigot%20Release%20v2.1.2%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-WindSpigot%20Release%20v2.1.2%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 18 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-18%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by SkirmisLTU** [comment]
The result is the same, this time a bit different error (I don't know why, but error varies from time to time)
Error: https://paste.gg/p/anonymous/40bd89201ca44873bbfa7d8e19caabf7
Dump: https://dump.viaversion.com/6fee78b74964aad53cf90d0df4cdb957d840b35fee697502303fac3227c4a6a6

**Comment by Barvalg** [comment]
![Platform: WindSpigot%20Release%20v2.1.2%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-WindSpigot%20Release%20v2.1.2%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Either caused by the weird fork you are using or a third-party plugin that is suddenly causing both viaversion and the server to fail.
