### ISSUE TITLE
1.16 arent able to join on 1.20.4 server, and the plugin told me to report here

### ISSUE THREAD

**Issue by Rator123** [ViaVersion/ViaVersion#3594]
### `/viaversion dump` Output

We've made a dump with useful information, report your issue and provide this url:  https://dump.viaversion.com/562197fed57ae58d6f859dd8efa217384c6221e9878a636f0a4f82494b67a4b2

### Console Error

https://paste.gg/p/anonymous/cdb4bba30aad4d0ebd7433747d18f7bd

### Bug Description

Players with 1.16 can't join on my server, He is using 1.16.5 (i allowed <1.16.4 to join), but i got this console error message

### Steps to Reproduce

Upgrading the plugin, either viaversion or viabackwards that it allows 1.16 to join

### Expected Behavior

Them allowed to be join after that! :)

### Additional Server Info

i use aternos

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--339%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--339%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 18 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-18%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 11 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
>  I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Rator123** [comment]
The issue is still here, its not working, it just made all the players not able to join all of a sudden.
