### ISSUE TITLE
Can't Connect on 1.8.9

### ISSUE THREAD

**Issue by ysflkc** [ViaVersion/ViaVersion#3596]
### `/viaversion dump` Output

https://dump.viaversion.com/68379f39b361ac555f3e49f923f9a14fd510d8ef268334c628037a645059e3b8

### Console Error

```
https://paste.gg/p/anonymous/76beefb0999d45d08ccb5136e4d9aff1
```

### Bug Description

On connect with -1.8.x Clients ```Disconnected``` Message

### Steps to Reproduce

Login with 1.8.9 Client
Seeing a ```Disconnected``` or a ```Internal Exeption: java.ioExeption: Connection reset by peer```Message

### Expected Behavior

Log without errors into the server

### Additional Server Info

I use Velocity and switched form proxy to backend viaversion
**I only have viaversion on my Backends Now**

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--241%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--241%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 18 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-18%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.5): 3 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 11 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Kichura** [comment]
Please do not randomly check things you haven't done yet.
