### ISSUE TITLE
ERROR IN Protocol1_15_2To1_16 IN REMAP OF CHUNK_DATA

### ISSUE THREAD

**Issue by JustNanix** [ViaVersion/ViaVersion#3597]
### `/viaversion dump` Output

https://paste.gg/p/anonymous/b501c6653cb84e3cb98a08603a7442df

### Console Error

https://paste.gg/p/anonymous/b501c6653cb84e3cb98a08603a7442df

### Bug Description

Getting this chunk data error while bot filter checking on server mc.reallyworld.ru

### Steps to Reproduce

1. Login with 1.12.2 client
2. Change version to 1.16.5
3. Connect to mc.reallyworld.ru

### Expected Behavior

Correctly loaded chunk data

### Additional Server Info

i use my custom proxy (like bungeecord) with this viaversion wrapper https://github.com/ViaVersionMCP/ViaMCP, also same exception while connecting with viaforge (https://www.curseforge.com/minecraft/mc-mods/viaforge)
using latest dev build 4.9.3

i dont know how to make dump programmatically, Via.getPlatform().getDump() returns {"members":{}}

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [ ] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Kichura** [comment]
Without the viaversion dump, we cannot help with this one sadly.

**Comment by Kichura** [comment]
Is that viafabricplus or something? because the platform name seems to reference something from enza.

**Comment by Kichura** [comment]
Since this is an add-on of viaversion, move this issue to them to see if it can be solved there - otherwise enza can reopen this if needed.

**Comment by TurboKoT1** [comment]
радк

**Comment by Kichura** [comment]
Took a look at it and it seems like viafabric is failing too although in the play packet 59 instead, although i kinda expected this outcome since that server uses a limbo-antibot system in place which makes viaversion easily confused.

**Comment by Kichura** [comment]
> so there wont be a fix?

unlikely since limbo is unsupported and therefore nearly impossible to resolve.

**Comment by kennytv** [comment]
I can fix this particular case anyways, but there will 1000 different ways of kicking ViaVersion clients by sending otherwise invalid data still

**Comment by kennytv** [comment]
That's not quite right, the invalid tags just have to be ignored. It's intentionally bad data
