### ISSUE TITLE
Smithing Tables Gui Menu Looks Like Furnance One!!

### ISSUE THREAD

**Issue by powerk123** [ViaVersion/ViaVersion#3600]
### `/viaversion dump` Output

https://dump.viaversion.com/8efac0ac44c588b46f004911abaa6cf2f39cb7772cbd96e833debad10c942b8a

### Console Error

No console error!

### Bug Description

My server is running on 1.19.4 and when a player join with higher version such as 1.20.3 and interracts with a smithing table, it appears to his screen the FURNANCE gui!

### Steps to Reproduce

1. Join with a higher version
2. Place down a smithing table
3. Right click the smithing table
4. Now you are viewing the furnance gui

### Expected Behavior

When you right-click the smithing table, you should see the smithing table gui!

### Additional Server Info

I use the latest build (550) of PaperMC version 1.19.4.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--550%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--550%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 18 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-18%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Kichura** [comment]
Intentional because 1.19.4 by default is not subscribed to the 1.20 datapack *(which means older smithing table is used)*, and if the new smithing table was enabled then older clients cannot interact with it properly which requires seperate translation.

**Comment by powerk123** [comment]
Oh ok! Thank you for the answer! I really appreciate it!

Is there any possibility of adding the "seperate translation" feature on the future?

**Comment by Kichura** [comment]
> Oh ok! Thank you for the answer! I really appreciate it!
> 
> Is there any possibility of adding the "seperate translation" feature on the future?

If your server was subscribed to the smithing table or updated to 1.20.x then you must install axsmithing to allow older clients to interact with the new smithing table.
