### ISSUE TITLE
Player with version lower than 1.20.4 can't connect

### ISSUE THREAD

**Issue by CptGummiball** [ViaVersion/ViaVersion#3601]
### `/viaversion dump` Output

https://dump.viaversion.com/6ddf4d0dff706bdede9aaf2f472d9fe10da9e16847c713a30ca444cfd5fc3b6c

### Console Error

```
https://paste.gg/p/anonymous/3ec550b96b6246df90742d642fb3273e
```

### Bug Description

Players with Client Version lower than 1.20.4 can't connect to Server. There is a warning in the console but i don't know if it has something to do with our problem here.

### Steps to Reproduce

1. Install ViaVersion and ViaBackwards
2. Set blocked clients to <1.19
3. Try to loggin with client lower than 1.20.4
4. get kicked

### Expected Behavior

not gettin kicked

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--344%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--344%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><details><summary></summary></details>

**Comment by CptGummiball** [comment]
Error just happened now. Current data:
https://dump.viaversion.com/5e2a2c5d667131e59765c4e3a0216907c0d1a2e1dbf6142942cb712b80620e62
https://paste.gg/p/anonymous/4ff82cb48a334513ae8155d7648bd842

![image](https://github.com/ViaVersion/ViaVersion/assets/151415484/7b1ad553-88df-4b43-8301-a96cfe0e7eba)

**Comment by Barvalg** [comment]
![Platform: git--Paper--346%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--346%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by CptGummiball** [comment]
I have now tested different versions of ViaVersion and ViaBackwards (also DEV) and none of them work. I also reset the configs, that didn't help either. Is there any solution to this problem or is a fix on the way? A short feedback on this would be very nice

**Comment by Kichura** [comment]
Cannot reproduce, This is either caused by a third-party plugin or a faulty world save/resource pack - Could you perform a binary search to see what's boiling it down to?

**Comment by CptGummiball** [comment]
I tried same world, same plugins, same data and resourcepack with 4.9.3 Viaversion and 4.9.2 Via Backwards on 1.20.2 and everything works fine. On 1.20.4 i get a base64 code for minecaft skins as error + the picture i send earlier. i dont think it has something to do with plugins or resourcepacks. it could be the papermc build or viaversion/viabackwards.

**Comment by CptGummiball** [comment]
on 1.20.4 i get an error for protocollib and anti popup, i can disable anti popup but i need protocollib. everything else is caused by viaversion or viabackwards.

**Comment by CptGummiball** [comment]
ViaVersion-4.10.0-23w51b-SNAPSHOT.jar
ViaBackwards-4.10.0-23w51b-SNAPSHOT.jar

Source of error: com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.Protocol1_20To1_20_2$$Lambda/0x00000175c70fd570

Caused by: java.io.IOException: Unable to read type CompoundTagType, found StringType

without any plugin the error also occurs. 

i will disable Via Plugins and try it again in a few days or weeks when u fixed this. im not the only one with this bug^^

**Comment by Kichura** [comment]
Contacted kenny about it, issue has been resolved.
