### ISSUE TITLE
Unable to connect 1.20.4 server with 1.20.2 client

### ISSUE THREAD

**Issue by anar4732** [ViaVersion/ViaVersion#3602]
### `/viaversion dump` Output

https://dump.viaversion.com/2d3e468f70a6654ee6631d9a806336580e4832e6e6c501ea38845a12861f5bf0

### Console Error

7:53:33 WARN]: [ViaVersion] You are running a development version of the plugin, please report any bugs to GitHub.
[07:54:09 INFO]: UUID of player anar4732 is *******
[07:54:10 INFO]: anar4732 lost connection: Disconnected

Client log:
[12:02:25] [Render thread/INFO]: Connecting to 135.125.4.23, 25554
[12:02:26] [Render thread/WARN]: Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: net.minecraft.class_148: Loading NBT data

### Bug Description

Unable to connect 1.20.4 server with 1.20.2 client. no error on the server but client.

![image](https://github.com/ViaVersion/ViaVersion/assets/10792085/5be9ab6b-926d-4ced-8053-a810f3b3b07e)

### Steps to Reproduce

1. start 1.20.4 server with ViaVersion
2. join with 1.20.2

### Expected Behavior

You should able to join and play as normal

### Additional Server Info

Just a simple paper server with a few plugins 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--346%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--346%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><details><summary></summary></details>

**Comment by BuggyAl** [comment]
I'm experiencing the same issue. Removing the server resource pack seems to fix the issue for me. The resource pack is made for 1.20.4.

**Comment by Kichura** [comment]
> I'm experiencing the same issue. Removing the server resource pack seems to fix the issue for me. The resource pack is made for 1.20.4.

Have you ever updated to CI builds?

**Comment by Kichura** [comment]
Speaking of Loading NBT data, This is mostly caused by a bad world save or bad third-party plugin.

**Comment by anar4732** [comment]
> Speaking of Loading NBT data, This is mostly caused by a bad world save or bad third-party plugin.

I can join the server as normal without this plugin.

**Comment by anar4732** [comment]
@BuggyAl @Kichura I can confirm It's about the server resource pack somehow.

**Comment by lewmilburn** [comment]
Hi, I had this issue but it was fixed upon removing the server resource pack.

**Comment by anar4732** [comment]
> Hi, I had this issue but it was fixed upon removing the server resource pack.

@Kichura

**Comment by lewmilburn** [comment]
Update: I’ve been able to get resource pack working by removing resource-pack-sha1, resource-pack-id, the prompt, and updating to the latest viaversion. I haven’t had time to go through and figure out exactly what it is atm.

**Comment by FrostBird347** [comment]
I can also confirm that this occurs on 1.20.4 servers with a resource pack and doesn't appear to have anything to do with the world or player data being corrupt.
Considering the assumption that this is caused by a corrupt world has proven wrong, I believe that this issue should be reopened @Kichura.

**Comment by Kichura** [comment]
> I can also confirm that this occurs on 1.20.4 servers with a resource pack when a 1.20.2 client connects and doesn't appear to have anything to do with the world or player data being corrupt. Considering the assumption that this is caused by a corrupt world has been proven wrong, I believe that this issue should be reopened @Kichura.

Cannot reproduce on my end other than the progress percentage glitching out.

**Comment by BuggyAl** [comment]
The issue is resolved in the latest releases (ViaVersion 4.9.3 and ViaBackwards 4.9.2). The issue was fixed at some point during dev builds.
