### ISSUE TITLE
Doesn't let into the server with error in console

### ISSUE THREAD

**Issue by VictimOfPing** [ViaVersion/ViaVersion#3603]
### `/viaversion dump` Output

https://dump.viaversion.com/7261b1d9d6898072ebff0d72697ee66d03b873b0c3600cdc4ef480d6fe32917d

### Console Error

https://paste.gg/p/anonymous/0b71ee3e4be3494d81c1e3038b961774

### Bug Description

when I enter the mode I get this screen: 
![Screenshot 2023-12-26 130847](https://github.com/ViaVersion/ViaVersion/assets/120317607/bd10e938-e71f-4649-a9a1-4641818383f4)

And in the console it gives me that error linked above

### Steps to Reproduce

1. I enter the lobby
2. I click on the npc of the mode in question
3. I get that screen and it makes me exit the server

### Expected Behavior

I expected it to let me enter the mode without any problem

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--445%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.1): 11 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3><br><details><summary></summary>tab_warn</details>

**Comment by VictimOfPing** [comment]
> ![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://camo.githubusercontent.com/f6bdbcfeba88a2d560eae8b47a07d79e584d27e37a346cc448aeb3d27694e840/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d5061706572537069676f742d2d3434352532302532384d43253341253230312e382e382532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://camo.githubusercontent.com/12502a11c2d6968b04dd6cf8c39fe18e7bb6395979811e9ec691bff84e9c0f7e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e392e332d2d534e415053484f54292d4576656e253230776974682532306d61737465722d627269676874677265656e3f7374796c653d666c61742d737175617265) ![ViaBackwards(4.9.1): 11 commits behind master](https://camo.githubusercontent.com/6b714af640802b70e5331be756843e18f2fad0c8e63f54c0f9d6d13c363d716b/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e392e31292d3131253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265)
> 
> ### Please try the **latest** build(s) from https://ci.viaversion.com/. In case the issue still persists send the new dump
> 
> tab_warn

I already tried using the latest build but nothing

**Comment by Kichura** [comment]
You did not update viabackwards.
