### ISSUE TITLE
Error that soflocks all java players from joining until the server is restarted

### ISSUE THREAD

**Issue by AdaptableRuben** [ViaVersion/ViaVersion#3606]
### `/viaversion dump` Output

https://dump.viaversion.com/cc09aac472b485689383a8db19e47bbc6cabf6e9c1734f706c1dc86535866a36

### Console Error

```
console error:
https://paste.gg/p/anonymous/b8c6ef9fcf6d4acbb1c69d61a2e57ec5
```

### Bug Description

This error for some reason happened and it blocks all java players from joining until I restart the whole server manually which fixes it automatically.

### Steps to Reproduce

I have like cero idea how to recreate it because it was working fine and suddenly it happened meaning the error is likely luck based or happens for some weird reason, I only know that the first player to report it was digging dirt to flatten a piece of land and he suddenly got discconected and havent been able to join back until I restarted the server.

The only other possible cause could be a certain plugin I recently installed, which was WolfyUtilities and Customcrafting because after installing these. this error started happening altrough not immediatly meaning that is likely to not be the case especially because after restarting the error went away.

### Expected Behavior

players should be able to join without being kicked because of that.

### Additional Server Info

Plugin list, paste from console

27.12 21:30:15 [Server] [INFO] Server Plugins (43):
27.12 21:30:15 [Server] [INFO] Paper Plugins:
27.12 21:30:15 [Server] [INFO] - EconomyShopGUI, WolfyUtilities
27.12 21:30:15 [Server] [INFO] Bukkit Plugins:
27.12 21:30:15 [Server] [INFO] - AuctionHouse, BedrockPlayerManager, BetterRTP, BlockLocker, CMILib, CoreProtect, CustomCrafting, Essentials, EssentialsChat, EssentialsProtect
27.12 21:30:15 [Server] [INFO] EssentialsSpawn, ExcellentEnchants, floodgate, Geyser-Spigot, Graves, GravityControl, GSit, HsRails, InteractiveChat, Jobs
27.12 21:30:15 [Server] [INFO] LuckPerms, NametagEdit, NexEngine, nLogin, OreAnnouncer, PlaceholderAPI, ProtocolLib, PvPManager, SkinsRestorer, Skoice
27.12 21:30:15 [Server] [INFO] spark, SternalBoard, TabList, Towny, TownyChat, UltimateAutoRestart, Vault, ViaBackwards, ViaVersion, WorldEdit
27.12 21:30:15 [Server] [INFO] WorldGuard

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--196%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--196%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 24 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-24%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.9.0)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary></details>
