### ISSUE TITLE
"Can't deliver chat message" When joining on a higher version.

### ISSUE THREAD

**Issue by Tokkeno** [ViaVersion/ViaVersion#3608]
### `/viaversion dump` Output

https://dump.viaversion.com/4dde7231047e12e7a902d99c47ff36d28f6182fca611c5c8751ac75d2d6684a5

### Console Error

No error in console.

### Bug Description

![java_z4InTwVmkb](https://github.com/ViaVersion/ViaVersion/assets/153781013/d76e360c-1a73-4467-9dc0-b61707072d06)

Only tried on paper, only happens when joining a server (PlayerJoinEvent) and it's annoying because it fills up chat and basically acts as a duplicate message.

### Steps to Reproduce

1. Make a minecraft server on 1.19.4 or higher. (Did not try lower versions than 1.19.4, only higher.)
2. Install ViaVersion 4.9.3 SNAPSHOT
3. Join the server on a newer version.

### Expected Behavior

There shouldn't be a error message in chat.

### Additional Server Info

The server is on latest waterfall, tried it with only ViaVersion 4.9.3 too.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--550%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--550%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.1): 15 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-15%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Tokkeno** [comment]
> ![Platform: git--Paper--550%20%28MC%3A%201.19.4%29](https://camo.githubusercontent.com/3fb12d6886c455cbbb052daf5cba9b9b3ef5bee553af1099f4dfdeba1bc091b6/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d50617065722d2d3535302532302532384d43253341253230312e31392e342532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://camo.githubusercontent.com/a5989d75368161e997f5ce4affc9914bddf91e1feb42a05643886346363f371a/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e392e332d2d534e415053484f54292d4576656e253230776974682532306d61737465722d627269676874677265656e3f7374796c653d666c61742d737175617265) ![ViaBackwards(4.9.1): 15 commits behind master](https://camo.githubusercontent.com/1aa244c15de816bd3b14b9af0863fa0cc870c1ed29cad6431dbe83d8a9437115/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e392e31292d3135253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265)
> 
> ### Please update **all** Via* plugins from https://ci.viaversion.com/. In case the issue still persists send the new dump and the issue will be reopened

I have the latest Via plugin, issue still persists.

**Comment by Kichura** [comment]
Duplicate of #3438.
