### ISSUE TITLE
PLAYERS WITH LOWER VERSIONS BEING MASS KICKED WHEN 1 LAY ON BED

### ISSUE THREAD

**Issue by trazodana** [ViaVersion/ViaVersion#3610]
### `/viaversion dump` Output

https://dump.viaversion.com/061b78d85cdb9f1367e649ef92b975af808cc8373725172ac12f841f084f5e90

### Console Error

Full console error: https://mclo.gs/5W9wAAW

### Bug Description

Basically, if the player is on a lower version than the one the server has by default, and he lies down in bed, he will be crashed and will also crash all other players with lower versions. Players using the same version of the server are not affected and can play normally without generating an error on the console

### Steps to Reproduce

Open Minecraft on a lower version of viaback*

lie in bed

### Expected Behavior

That players wouldn't crash when lying in bed

### Additional Server Info

Spigot base plugins, I use the plugins on each server separately instead of using the proxy.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2111%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--2111%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by opera2398** [comment]
also have this problem, something isnt okay

**Comment by Xenfo** [comment]
I've got the same issue, another example is running `/kill @e`. All my 1.20.2 clients are crashed but my 1.20.4 one isn't.

Dump: https://dump.viaversion.com/3405b510951aad00a50f290e8374f34bad7217d95442dd126dc881176fa01a2e

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2111%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--2111%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by kennytv** [comment]
Fixed in ci builds
