### ISSUE TITLE
Version 1.20.2 cannot access the server

### ISSUE THREAD

**Issue by MCZQ** [ViaVersion/ViaVersion#3611]
### `/viaversion dump` Output

https://dump.viaversion.com/db35e36799b4e535da5167b334863031b65c10ab45ad9d0016a4548709a226ab

### Console Error

![image](https://github.com/ViaVersion/ViaVersion/assets/56064852/578e90f9-5d5e-4c7d-9316-e3db91fb770b)

### Bug Description

I have installed ViaVersion on Waterfall, but when players use clients other than 1.20.1 to access the server, they are unable to do so. Max pps is set to -1 and tracking period is also set to -1. How should I resolve this issue?

### Steps to Reproduce

Using clients other than 1.20.2 to enter the server

### Expected Behavior

Entering the server

### Additional Server Info

BungeeCord、Itemsadder

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Ae927093%3A560](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Ae927093%3A560-3498db?style=flat-square) </br>![ViaVersion (4.10.0-23w51b-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--23w51b--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(3.0.5): 9 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.0-23w51b-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.10.0--23w51b--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by MCZQ** [comment]
https://dump.viaversion.com/f86cdd300111b49b8235d1067af1eab2ccdcd5ace224de3a492aa726272a95f0

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Ae927093%3A560](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Ae927093%3A560-3498db?style=flat-square) </br>![ViaVersion (4.10.0-23w51b-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--23w51b--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(3.0.5): 9 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.0-23w51b-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.10.0--23w51b--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by MCZQ** [comment]
I just downloaded the latest DEV version last night

**Comment by MCZQ** [comment]
![image](https://github.com/ViaVersion/ViaVersion/assets/56064852/67de76a6-387c-4045-a4e3-2f407e0d9364)
