### ISSUE TITLE
Error & Kick when player joins for first time to server (Server: 1.13.2, Client: 1.20.4)

### ISSUE THREAD

**Issue by MorkaZ** [ViaVersion/ViaVersion#3612]
### `/viaversion dump` Output

https://dump.viaversion.com/4400bc756e583014c27250373bb2bc0bed405c7d288bea2032e84607375c21e0

### Console Error

```
Paper-Spigot: https://paste.gg/p/anonymous/8673a6be425e412f98dfc4da688b0d01
Bungeecord: https://paste.gg/p/anonymous/df1aaac161cd4a0f969a477675136dbb
```

### Bug Description

When player joins for first time to the server with 1.20.4 version, he gets kicked and console is spammed with errors.

### Steps to Reproduce

1. Login with 1.20.4 minecraft version for the first time on server (tested on 1.13.2 server). Tested with nickname "testowybob3_"
2. Kick & Console spam happens

### Expected Behavior

No errors & no kicks for first join.

### Additional Server Info

Flamecord, paper spigot (1.13.2). Plugin is installed on server. 
Tested also without plugins and problem still happened.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--655%20%28MC%3A%201.13.2%29](https://img.shields.io/badge/Platform-git--Paper--655%20%28MC%3A%201.13.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><details><summary></summary>tab_warn</details>

**Comment by Kichura** [comment]
Either TAB or another third-party plugin is sending bad scoreboard objective packets to server, please perform a binary search to see what causes viaversion to complain about it.

**Comment by MorkaZ** [comment]
Actually it throws error in many things, even in `[ViaVersion] ERROR IN Protocol1_14To1_13_2 IN REMAP OF CHUNK_DATA (0x22)` if you scroll down which is not even related with scoreboard
