### ISSUE TITLE
Problem encountered when switching from 1.12.2 server to 1.20.2 server using Waterfall

### ISSUE THREAD

**Issue by BiliRumble** [ViaVersion/ViaVersion#3613]
### `/viaversion dump` Output

https://dump.viaversion.com/5cfaaf297c8f1ce0f0a42d11af6e11b370a2e01b9c41168bc0a4ad3c8dec1354

### Console Error

```
[Put the paste.gg link or text here.](https://paste.gg/p/anonymous/154fb264941340d28b1fa2e81ca81dc4)
```

### Bug Description

The player was kicked out when switching from server 1.12.2 to server 1.20.2 using the Bunge branch

### Steps to Reproduce

1. Install ViaVersion, ViaRewind, and ViaBackwards on the Bungee server
2. Use Bungee to enter sub server 1 normally, then enter sub server 2

### Expected Behavior

Normal entry into sub server 2

### Additional Server Info

I also use Waterfall with the following plugins: AuthMeBungee-2.2.0-beta1, FallBackServer-3.2.0-Beta1,FastBungeeReport,floodgate-bungee,Geyser-BungeeCord,LiteBans-2.13.3,LuckPerms-5.4.104,MiniMotd,SkinsRestorer-15.0.4,TrChat-2.0.9,ViaBackwards-4.9.2-SNAPSHOT,ViaRewind-3.0.6-SNAPSHOT,ViaVersion-4.9.3-SNAPSHOT

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Ac856f2d%3Aunknown](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Ac856f2d%3Aunknown-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
