### ISSUE TITLE
Error on Geyser Players login

### ISSUE THREAD

**Issue by LenyzDev** [ViaVersion/ViaVersion#3619]
### `/viaversion dump` Output

https://dump.viaversion.com/d34b5c2795a8ca75a8e6f7c433c8c6a95cb8636586143fe198dde2722a32100f

### Console Error

```
[Put the paste.gg link or text here.](https://paste.gg/p/anonymous/5b2ea669cd4849e3aebb757a3c3b4253/files/4b086173cd1a4a6ea2f10b1d11d76971/raw)
```

### Bug Description

Error on Geyser Players login

### Steps to Reproduce

Login with Geyser

### Expected Behavior

Dont disconnect player

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--4fdb0141%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--4fdb0141%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Not caused by geyser nor viaversion - this is mostly a fault caused by a faulty third-party plugin / bad world save.
