### ISSUE TITLE
1.8.x and below can't join on 1.20.4 server

### ISSUE THREAD

**Issue by SlimeBluKing** [ViaVersion/ViaVersion#3622]
### `/viaversion dump` Output

https://dump.viaversion.com/654cce86e89165a62f56d8b53caa434ff5068b86ec46c91643807d544bd6005d

### Console Error

https://paste.gg/p/anonymous/8087685afb1c4cdb8a439730d0c68d57

### Bug Description

Just join the server

### Steps to Reproduce

1.20.4 server and a 1.8.x or below client

### Expected Behavior

.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--37%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Pufferfish--37%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 30 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-30%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.5): 13 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-13%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 17 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>tab_warn</details>
