### ISSUE TITLE
Ghosts players on higher versions

### ISSUE THREAD

**Issue by frescomaty** [ViaVersion/ViaVersion#3624]
### `/viaversion dump` Output

https://dump.viaversion.com/ccba92abec379de73bb2f9ee3082c11ca34319dc7aea87d6188866eb6f6ef7f7

### Bug Description

I have an issue with players on higher versions not being able to see each other. They go into a "Ghost" ("invisible") state, the server is 1.12.2. I was on the game version 1.19.2 and my friend was on 1.20.2 when this happened. However, I believe it's any version after 1.19 when I join with 1.8 I can see him but he can't see me. 

SIDE NOTES:
Server Version 1.12.2
Player displays on /glist and able to message the player
I tried many versions 1.16 players are shown. Higher versions aren't
Sometimes happens, sometimes not.

### Steps to Reproduce

1. Log in 1.20 or similar into a 1.12.2 server

### Expected Behavior

Players are vanished.

### Additional Server Info

I tried running the server with no plugins, still happened.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.9.1)-Outdated!-red?style=flat-square) </br>![ViaRewind(3.0.5): 13 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-13%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.9.0)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
