### ISSUE TITLE
Not join 1.8.9 server is 1.9.4 Join(1.13 is UP) is not tested 1.7.10

### ISSUE THREAD

**Issue by gustavo-blacknaut** [ViaVersion/ViaVersion#3627]
### `/viaversion dump` Output

https://dump.viaversion.com/f53f4000d452bde2a29e8fea4e6ccd49ac5b1be1609f18e88956bbd30ca19e5c

### Console Error

```
https://paste.gg/p/anonymous/2ae78b24ce4043b2857d3a946f439dff
```

### Bug Description

is not join 1.8.8

tested 1.8.8, 1.20.2 (Joined)
server is: 1.9.4 Paper Spigot

### Steps to Reproduce

vazio

### Expected Behavior

vazio

### Additional Server Info

BungeCord waterfall 1.20
PaperSpigot 1.8.9
ViaVersions
ViaBack
ViaRewinds
all update all

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--775%20%28MC%3A%201.9.4%29](https://img.shields.io/badge/Platform-git--Paper--775%20%28MC%3A%201.9.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 30 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-30%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
