### ISSUE TITLE
Unable to connect 1.20.4 server with 1.20.1 client 

### ISSUE THREAD

**Issue by Lemon4ik6484** [ViaVersion/ViaVersion#3629]
### `/viaversion dump` Output

https://dump.viaversion.com/166f645184c2102fd7f1b3c20eac96992eb4cf58cbcbebbec685cb5582d7eb0f

### Console Error

```
Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: null, Type: CompoundTagType, Index: 3, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.Protocol1_20 To1_20_2$$Lambda$7303/0x00007fc0a5e23368, Packet ID: -1
```

### Bug Description

Unable to connect to server

### Steps to Reproduce

Connect with 1.20.1 fabric client

### Expected Behavior

Should connect to server

### Additional Server Info

I use Aternos hosting

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 4003--Spigot--828f059--6902782%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-4003--Spigot--828f059--6902782%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 30 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-30%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 17 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
