### ISSUE TITLE
Error while trying to join bedwars game.

### ISSUE THREAD

**Issue by gfj126** [ViaVersion/ViaVersion#3632]
### `/viaversion dump` Output

https://dump.viaversion.com/0f210ef8260712f43f668b9170f94b49699dca6c38d8d6791adcdb9805340f91

### Console Error

```
[https://paste.gg/p/anonymous/c489f43db6f8425c9d0bfa2f8ba8e89f]
```

### Bug Description

I have set up my server with screaming bedwars plugin. To join the game i have to right click a sign. But when I right click on the sign, it kicks me out of the server saying either "Disconnected" or "An existing connection was forcibly closed by the remote host". But the console shows some texts about an error of viaversion.

### Steps to Reproduce

1. Join the server.
2. Right click on the sign.

### Expected Behavior

I will join the bedwars matchmaking and I will be able to choose my team.

### Additional Server Info

I use Paper 1.20.4 and I have ViaVersion-4.9.2, ViaBackwards-4.9.1, ViaRewind-3.0.6-SNAPSHOT, GeyserMC plugins installed to the aternos server. I use Minecraft 1.16.5 to join my server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--379%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--379%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 30 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-30%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.1): 17 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by gfj126** [comment]
Aternos only have ViaVersion-4.9.2.

**Comment by Kichura** [comment]
Not correct, Aternos also has an hangarmc variant which does contain pre-releases instead of just spigot - Please consider using that instead of the other.

**Comment by gfj126** [comment]
Now Minecraft is showing me that I am using outdated client and tells me to use 1.20.4

**Comment by Kichura** [comment]
Did you update viabackwards too? if yes; Something is cancelling out viabackwards then.

**Comment by gfj126** [comment]
I updated every Via plugins. ViaVersion, ViaRewind and ViaBackwards too.

**Comment by Kichura** [comment]
Can't reproduce on my end.

**Comment by gfj126** [comment]
Then what should I do. Should I delete and make my server again?

**Comment by Kichura** [comment]
> Then what should I do. Should I delete and make my server again?

Either you mixed viaversion 4.9.3-snapshot with viabackwards 4.9.1 or the other way around.

**Comment by gfj126** [comment]
I have viaversion-4.9.3-SNAPSHOT, viabackwards-4.10.0-23w51b-SNAPSHOT, viarewind-3.0.6-SNAPSHOT

**Comment by Kichura** [comment]
ViaBackwards 4.10.0 is not compatible with viaversion 4.9.3-snapshot, please downgrade viabackwards to 4.9.2-snapshot.

**Comment by gfj126** [comment]
Thanks for helping. I had to downgrade viabackwards to 4.9.2. It fixed everything. Thanks, again.
