### ISSUE TITLE
Console Spam bug

### ISSUE THREAD

**Issue by LOCNetwork** [ViaVersion/ViaVersion#3633]
### `/viaversion dump` Output

https://dump.viaversion.com/8ff6c5f67ced66f4a90ceb7b1d10ffe81053e6e0079e4876293ac67472a23a4a

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/be6198fb812046fe8b2457d2a19a8206

### Bug Description

Apparently, doing commands, just moving around, interacting with inventories or chatting can cause that issue. I can't reproduce it everytime.

### Steps to Reproduce

1. Login with a 1.19.4+ client on a 1.8.8 server
2. Do things such as described in the Bug Description

### Expected Behavior

1. The error is not shown on console
2. Sometimes commands are not executed and that error is thrown

### Additional Server Info

Using BurritoSpigot 1.8.8 and connected with a 1.19.4 Client. Only happens with newer client versions.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--BurritoSpigot--%22cb667b1%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--BurritoSpigot--%22cb667b1%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 30 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-30%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>tab_warn</details>

**Comment by kennytv** [comment]
Presumably not a Via issue anyway, but a plugin sending bad metadata

**Comment by LOCNetwork** [comment]
So, why would it only happen with 1.19.4+ clients?
