### ISSUE TITLE
Broken Hex Colors on 1.8 server after mcstructs commit

### ISSUE THREAD

**Issue by Drizz1** [ViaVersion/ViaVersion#3634]
### `/viaversion dump` Output

https://dump.viaversion.com/7acb839d1dbf3c41302dabf7756a2edb8fc3c074b197d8932e3a9c41be12861d

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

After mcstructs commit, players on new versions like 1.18 or 1.20 see ugly colors instead of hex colors on 1.8 server.

I use legacy colors formatting like: §x§0§0§F§F§E§0 

### Steps to Reproduce

1. Make text with legacy colors formatting like: §x§0§0§F§F§E§0 on 1.8 server.
2. Login on 1.18 client.
3. You will see old colors instead of RGB.

### Expected Behavior

Could you fix it?

Before commit: 
![wfrwfrwg](https://github.com/ViaVersion/ViaVersion/assets/42066318/5c2ef695-2bd1-4cef-9ee9-566e57b29f45)

After commit: 
![earewrfwef](https://github.com/ViaVersion/ViaVersion/assets/42066318/4646d76e-74c3-47a6-8735-1444f8c4220b)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--f9b7675%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--f9b7675%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
This might have coincidentally worked previously, but is not supported, as Via does not re-implement new features on old servers. Also given it's an awful, non-standard format
