### ISSUE TITLE
I have error

### ISSUE THREAD

**Issue by GGLOLGGTAKE** [ViaVersion/ViaVersion#3636]
### `/viaversion dump` Output

i dont have

### Bug Description

it dont let me play

### Steps to Reproduce

![image](https://github.com/ViaVersion/ViaVersion/assets/139041752/24aa6443-1a30-4457-835c-d755475f234c)

### Expected Behavior

in server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Kichura** [comment]
Update via* from CI website instead of just checking everything that you haven't done.
