### ISSUE TITLE
 ERROR IN Protocol1_20_3To1_20_2 IN REMAP OF COMBAT_KILL (0x3A)

### ISSUE THREAD

**Issue by Packsolite** [ViaVersion/ViaVersion#3640]
### `/viaversion dump` Output

https://dump.viaversion.com/5e172c9a4c0ed6b0c51c9bac7d4da83cccb23519eeb81c7a0e8740af66813720

### Console Error

https://pastebin.com/RXT0BgZN

### Bug Description

This exception randomly appeared in logs. Seems to be triggered by some 1.20.3 players.

### Steps to Reproduce

Not quite sure as i couldn't reproduce it myself. But it definitely only occurs since the 1.20.3 update.

### Expected Behavior

To not error?

### Additional Server Info

Running behind a waterfall proxy.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--CurrySpigot--13ae952%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--CurrySpigot--13ae952%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
This sounds like a third-party plugin or something else is sending a faulty resource pack to the server which viaversion does not like and therefore complains about it, Could you perform a binary search to see what causes it to happen?

**Comment by Packsolite** [comment]
> This sounds like a third-party plugin or something else is sending a faulty resource pack to the server which viaversion does not like and therefore complains about it, Could you perform a binary search to see what causes it to happen?

Sorry, on what should i perform a binary search and what should i search for?

**Comment by Packsolite** [comment]
> > > This sounds like a third-party plugin or something else is sending a faulty resource pack to the server which viaversion does not like and therefore complains about it, Could you perform a binary search to see what causes it to happen?
> > 
> > 
> > Sorry, on what should i perform a binary search and what should i search for?
> 
> Start by checking if server can recover with just viaversion active, if it doesn't then check the configs next to see if a server resource pack was ever deployed.

We don't force resourcce packs from the server and there is nothing alike in our plugins.

**Comment by shooutz** [comment]
Sorry, but did this error cause some kind of spam? I'm having a similar problem, but it causes absurd spam on the server (log with 147k lines in 1 hour of active server, I barely reach 10k, imagine 147K)
besides this error is also affecting version 1.8, which is the native version of my server
the error is disconnecting each and every player immediately upon entering the server, after a while of trying, I managed to log in using 1.8, but any other attempt causes disconnection

https://dump.viaversion.com/42c7d5c34c2cd14f62c8a951026ffee334916acd35a8cf01b2886cbc797599fa

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--445%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 37 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-37%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by shooutz** [comment]
> ![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://camo.githubusercontent.com/efa6d8c7b0507a879d4d0eb3f2a23b8d7b7cb70bec42872350c19efae02b8dbf/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d5061706572537069676f742d2d3434352532302532384d43253341253230312e382e382532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.9.2): 37 commits behind master](https://camo.githubusercontent.com/4df01aa7696bd8156dff3e7f294f13d4df2b00b7b8a4a23ac935b3b19953467c/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e392e32292d3337253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265)
> 
> ### Please try the **latest** build(s) from https://ci.viaversion.com/. In case the issue still persists send the new dump

4.9.3 fixed the disconnection issue
https://mclo.gs/ed6cMx4
https://dump.viaversion.com/7eb6d38924db3f76714a37a25fff82216da7ab785b147cb06e7e5b1ff9affe8b

I ended up forgetting to put the log in the previous message: https://mclo.gs/CFDQY28

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--445%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
This sounds like a third-party plugin is causing viaversion to complain so much that the server has a chance to explode which is something unexpected, Please perform a binary search to see what's causing all of that mess.

**Comment by leothawne** [comment]
Hello! I'm with the same problem and I already disabled/removed all of the plugins that were installed and I still cannot join the server
![image](https://github.com/ViaVersion/ViaVersion/assets/31146142/daa1a637-9edf-4287-9f35-ac69ae6ff120)
![image](https://github.com/ViaVersion/ViaVersion/assets/31146142/80763315-621e-4f94-afbf-ea7aab47ad90)

**Comment by hideko-dev** [comment]
up

**Comment by kennytv** [comment]
The original issue should no longer happen, everything else should go into a new issue/onto Discord for support
