### ISSUE TITLE
Textures rendering different items on itemframes/ground

### ISSUE THREAD

**Issue by srleojaco** [ViaVersion/ViaVersion#3645]
### `/viaversion dump` Output

https://dump.viaversion.com/2c8700c6032e4e7df9990f42938d85d26f4a7a96e7cf0a1ccbc92e5c346cce0b https://dump.viaversion.com/fe7ef1f8edcd4585a1e08417166ba4cc11f9dff29d713a6681a30206bf2bd246

### Console Error

Nothing

### Bug Description

Textures are rendering different items on itemframes and on ground entities. When picked they are ok.
Server base 1.8. Also on 1.12.
Clients tested affected: 1.19.4, 1.20.4, probably more
Clients tested not affected: 1.15.2

Noticed after updating from spigot published one to latest version on CI.

![image](https://github.com/ViaVersion/ViaVersion/assets/16531305/aa892d47-56d3-4944-9073-77156e9c66cf)
![image](https://github.com/ViaVersion/ViaVersion/assets/16531305/1c7b6d80-e27d-42aa-a933-f720ee2a1619)

### Steps to Reproduce

1. Server base 1.8.9. Tested also with server 1.12
2. ViaVersion last build from CI 777
3. Place item frames with items like diamond or bread (on 1.8/1.12 client)
4. GroundItems / framedItems are rendered as stairs or acacia doors on affected versions
5. When picked on inventory they're shown ok

### Expected Behavior

Items rendered ok on affected versions

### Additional Server Info

Bug found on production (bungeecord), tested on local server with only Viaversion without any proxy.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--%228b18730%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--%228b18730%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by srleojaco** [comment]
build 773 ok
build 774 bug present

**Comment by srleojaco** [comment]
working, thanks for the quick fix :)
