### ISSUE TITLE
[ViaVersion] Error initializing plugin. (Build 988)

### ISSUE THREAD

**Issue by andrewkm** [ViaVersion/ViaVersion#3646]
### `/viaversion dump` Output

https://dump.viaversion.com/6cb01e060a18ca6774d1f3e9aa3c63ec8b8fe24f671f92450c52b458515da110

### Console Error

```
[Put the paste.gg link or text here.](https://paste.gg/p/anonymous/f51741e8f68c4421b686c3623960f9fd)
```

### Bug Description

Plugin won't initialize.

### Steps to Reproduce

No work.

### Expected Behavior

Work.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--385%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--385%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.0-23w51b-SNAPSHOT): 10 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--23w51b--SNAPSHOT)-10%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.0-23w51b-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.10.0--23w51b--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by andrewkm** [comment]
Can't really update to latest dev since it won't initialize.
@kennytv
