### ISSUE TITLE
Can't join on a 1.20.4 server on a 1.20.1 client

### ISSUE THREAD

**Issue by ParaliyzedEvo** [ViaVersion/ViaVersion#3652]
### `/viaversion dump` Output

https://dump.viaversion.com/6a64b1f6acd73e94ff73b681c7637506741997b3666b33a59723d39b3ee17d0c

### Console Error

https://pastebin.com/GfTZnfLx

### Bug Description

The server just kicks me out when trying to join on a 1.20.4 server when I'm trying to join on a 1.20.1 version. I wouldn't be putting this issue in as I could just play on 1.20.4 but since I have client side mods that are only updated to 1.20.1, I'm forced to play on 1.20.1.

### Steps to Reproduce

1. Have a server running Spigot/Paper 1.20.4
2. Have ViaVersion, ViaBackwards, ViaRewind on latest versions
3. Launch mc with any launcher in 1.20.1 (in my case I used feather)
4. Join the server with the version 1.20.4
5. Get kicked with the error in the ss below 
![image](https://github.com/ViaVersion/ViaVersion/assets/107338855/20bf8ff2-65a1-45ce-8fa2-07c3de33cca9)

### Expected Behavior

Being able to join my 1.20.4 server when I'm playing on 1.20.1

### Additional Server Info

When using the latest snapshots, I get this message
![image](https://github.com/ViaVersion/ViaVersion/assets/107338855/76fa25ee-ec00-479e-834c-0a1e4597b2dd)
The client side mods I'm using are listed [here](https://pastebin.com/KDyvrDNk). Im pretty sure the plugins are listed in the dump (hopefully?) but if you need a list, I'll make a pastebin with a list of my plugins. 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 4019--Spigot--864e4ac--c8b4da8%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-4019--Spigot--864e4ac--c8b4da8%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 39 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-39%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.1): 20 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-20%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by ParaliyzedEvo** [comment]
I updated the dump file with the new snapshots so reopen please

**Comment by ParaliyzedEvo** [comment]
https://dump.viaversion.com/6a64b1f6acd73e94ff73b681c7637506741997b3666b33a59723d39b3ee17d0c

**Comment by Barvalg** [comment]
![Platform: 4019--Spigot--864e4ac--c8b4da8%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-4019--Spigot--864e4ac--c8b4da8%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
The invalid payload register is caused by a third-party mod. also because you use jdk 21.0.1 to run the 1.20.4 server, paper is recommended over spigot.

**Comment by ParaliyzedEvo** [comment]
Alr thanks, also im using spigot over paper as i need the chunk bans that i use to work but thanks!

**Comment by mateuscolli** [comment]
I have the same problem, but I use Waterfall proxy, PandaSpigot lobby and Purpur server, all on the latest version. But with client 1.20.x there is a version error.

When trying to go from the lobby to the server (which is on 1.20.4) I get this error. I've already tried using ViaBackward, ViaRewind, VersionControl... everything...
![image](https://github.com/ViaVersion/ViaVersion/assets/81497108/71a91e36-a3dc-4d14-9a4f-6f2ea6f07cb3)

**Comment by Kichura** [comment]
@mateuscolli this is an bungeecord-related issue but is currently being addressed by PR #3534.

**Comment by mateuscolli** [comment]
So in my case, it's something with Waterfall right?

**Comment by Kichura** [comment]
> So in my case, it's something with Waterfall right?

yes, you can attempt to solve it by running viaversion on proxy itself or by moving to velocity.

**Comment by mateuscolli** [comment]
viaversion is already in my proxy... I'll try to switch to velocity then
