### ISSUE TITLE
Support 1.20.x

### ISSUE THREAD

**Issue by joaopinto14** [ViaVersion/ViaVersion#3654]
### `/viaversion dump` Output

 https://dump.viaversion.com/ae0446dd1dd55a135f5c0c54e5bddd99f450afc7a402088d30b7170b856d9c51

### Bug Description

Does 1.20.x support not support 1.20, 1.20.1, 1.20.2, 1.20.3 and 1.20.4?
I have the server on version 1.20.4 and the client trying to access version 1.20 and cannot access it.

BungeeCord is in the latest version and the lobby is created in version 1.20.4.

Is it necessary to install another plugin to make this work or does this one work?

### Steps to Reproduce

I have the server on version 1.20.4 and the client trying to access version 1.20 and cannot access it.

### Expected Behavior

I have the server on version 1.20.4 and the client trying to access version 1.20 and cannot access it.

### Additional Server Info

BungeeCord (ultima versão disponivel)
Lobby (1.20.4)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A19918c6%3A1788](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A19918c6%3A1788-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Jo0001** [comment]
You also need ViaBackwards (and ViaRewind). For details see https://viaversion.com/setup

**Comment by Kichura** [comment]
You are missing viabackwards 4.9.2-snapshot.
