### ISSUE TITLE
Kick if you return from end

### ISSUE THREAD

**Issue by Scorbunny10** [ViaVersion/ViaVersion#3657]
### `/viaversion dump` Output

We've made a dump with useful information, report your issue and provide this url: https://dump.viaversion.com/86a04495e13726e88d97b06eac1f263ffa2737d0a86433e3367028380cfffbfa

### Console Error

[```
Put the paste.gg link or text here.
```
](https://paste.gg/p/anonymous/12837c2d478c4937accd42a9b63e0a9e)

### Bug Description

![javaw_rS3NnB8hxA](https://github.com/ViaVersion/ViaVersion/assets/100584937/68e12e0d-0f1a-41b2-807a-c41b618000b6)


### Steps to Reproduce

1.Go to end using command (I use /warp end) (terrain is not loading, you need to rejoin to load)
2.return to overworld using command (I use /warp spawn)

### Expected Behavior

![javaw_rS3NnB8hxA](https://github.com/ViaVersion/ViaVersion/assets/100584937/68e12e0d-0f1a-41b2-807a-c41b618000b6)


### Additional Server Info

_No response_

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3871--Spigot--d2eba2c--3f9263b%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-3871--Spigot--d2eba2c--3f9263b%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 39 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-39%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 20 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-20%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Scorbunny10** [comment]
https://dump.viaversion.com/9c6a713136b2507b01c30946766e49fb8b817a859e457346f3706b9f25ede2b0

**Comment by Barvalg** [comment]
![Platform: 3871--Spigot--d2eba2c--3f9263b%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-3871--Spigot--d2eba2c--3f9263b%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Scorbunny10** [comment]
problem is  orefuscator not viaversion
