### ISSUE TITLE
ERROR IN Protocol1_13To1_13_1 IN REMAP OF SPAWN_PARTICLE

### ISSUE THREAD

**Issue by nklklcuzdfuh** [ViaVersion/ViaVersion#3658]
### `/viaversion dump` Output

https://dump.viaversion.com/4823b4ceb44dc2513d9d96fc6861d6e00432ba5b3068fa6ac1dd49a583d6578d

### Console Error

```
https://paste.gg/p/anonymous/06c327f4ba3041cdad4a927b8a55d55d
```
![image (1)](https://github.com/ViaVersion/ViaVersion/assets/148728845/e7bbb1f0-ee2a-4ca7-91c1-22af54ecb3c4)

### Bug Description

Players Arent Able T Join Sometimes

### Steps to Reproduce

It Happens Unexpectedly

### Expected Behavior

It Should Let Player Join

### Additional Server Info

I Use Velocity And This Problem Only Happens WIth My Lobby Server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--UniverseSpigot--%224cb60ef%22%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--UniverseSpigot--%224cb60ef%22%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 39 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-39%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.5): 18 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-18%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 20 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-20%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>tab_warn</details>

**Comment by yfdmc** [comment]
I've been having the same issue with my server. No one can join at the moment because of viaversion/viabackwards.

Console image: 
![image](https://github.com/ViaVersion/ViaVersion/assets/138078606/0bd78ec3-3de9-4e40-826a-2163cd7252ab)

Disconnect messages:
![image](https://github.com/ViaVersion/ViaVersion/assets/138078606/d59672d8-30e3-4c12-bcb7-541fbca48f81)
![image](https://github.com/ViaVersion/ViaVersion/assets/138078606/2b7c5026-16cd-46a7-8e9c-c3295bbec05c)

**Comment by GBNodes** [comment]
The latest ViaRewind Not Letting 1.8 Players Join The Server too

**Comment by yfdmc** [comment]
I tested every major release of minecraft and none worked

**Comment by Kichura** [comment]
have you ever updated to CI builds before saying "me too" ?

**Comment by yfdmc** [comment]
YES!!

**Comment by Kichura** [comment]
> YES!!

Then it's a third-party plugin causing problems with viaversion, to which a binary search is suggested for this.
