### ISSUE TITLE
Shutdown blocked

### ISSUE THREAD

**Issue by bridgelol** [ViaVersion/ViaVersion#3661]
### `/viaversion dump` Output

https://dump.viaversion.com/01d776a0594df8c79dee81e3dc5359221c66832ba2a010df8aab0b10be26c7a1

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

![image](https://github.com/ViaVersion/ViaVersion/assets/29434554/dcf0a888-86f5-4333-992c-aa4d42885ed1)

Upon reboot after long uptime, on random occasions the server freezes with the above via version console log.

### Steps to Reproduce

Reboot the server

### Expected Behavior

Server shouldn't freeze

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Axolotl--%2256b706f%22%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Axolotl--%2256b706f%22%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 40 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-40%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.9.1--SNAPSHOT)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by bridgelol** [comment]
![image](https://github.com/ViaVersion/ViaVersion/assets/29434554/f3e166de-81cd-4057-befb-ed5ed47dacfb)
Still happening on latest

**Comment by FormallyMyles** [comment]
You will need to remove plugins and test what causes this to happen, also provide a new dump with updated plugins.
