### ISSUE TITLE
PLS FIX THIS IT IS ANOYING!

### ISSUE THREAD

**Issue by adminiget** [ViaVersion/ViaVersion#3663]
### `/viaversion dump` Output

https://dump.viaversion.com/2b565493185100e806715ca7650ab19d4c95c65f80700d036c41af981d206012

### Console Error

what??

### Bug Description

the writable books are not working correctly.

### Steps to Reproduce

If u play on 1.13.2 optifine on a 1.20.1 server, and make a book, u write mamma mia
u close it using the "done" Button open it back, and tthe text is fuked up.PLS FIX THIS.... I want Books

### Expected Behavior

is needs to work , the text needs to stay my mamma mia , not change to "mamma mia". (and there are a lot o of "n//n//n/")

### Additional Server Info

i use paperMC aternos.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--196%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--196%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): 10 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-10%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): 7 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by adminiget** [comment]
i am sorry but i cant update from that site cause i have an aternos server. So... Pls update it on aternos too

**Comment by adminiget** [comment]
what do you mean??

**Comment by Kichura** [comment]
> what do you mean??

You can find the latest viaversion from aternos [here](https://aternos.org/addons/a/hangar/ViaVersion) and latest viabackwards from [here](https://aternos.org/addons/a/hangar/ViaBackwards) - Just don't use the 4.10.0 builds as they can be unstable.

**Comment by adminiget** [comment]
i do not get it. can you tell me : Will you fix the bug ?
tysm
