### ISSUE TITLE
Lighting Lag

### ISSUE THREAD

**Issue by Coswics** [ViaVersion/ViaVersion#3664]
### `/viaversion dump` Output

https://dump.viaversion.com/96d21e2729697f814676004248c9179e71f183a6b893b7efe6bbb3082e015a5b

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

On Pre 1.20 Versions Whenever Lighting Updates en masse (in this specific case its a lava rises minigame) it causes a massive lag spike on the older clients, whereas the newer ones handle it just fine. (lava replacing air blocks, similar to how updating a void world block can cause lag that way, i think); Server Version is Pufferfish 1.20.1; If the server version is 1.20 or higher, the lag occurs for players on the lower versions, if the server version is 1.19.4 or lower the lag occurs on the higher versioned clients. The current fix we found for it was replacing air with light blocks; cant update lighting if everything is the same light level already and downgrading to 1.19.4. We do want to update the server to provide new features to the minigame but its a tad annoying being restricted like this. 
[Video of Bug](https://youtu.be/CSLUHxX5WWY)

### Steps to Reproduce

Create Paper/Pufferfish Server, 1.20 or higher
Set commands/plugin to increase lava level over area over time
watch lag as it replaces air and/or light blocks

### Expected Behavior

No Lag Should Happen. 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Coswics** [comment]
https://dump.viaversion.com/4a36938e393bce8e567ef883e79e123d7d96195a63e36b2afeec1890eb523bf1

**Comment by Barvalg** [comment]
![Platform: git--Paper--182%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--182%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Update TAB and protocollib too, but otherwise this performance problem is caused by server not being properly optimized in terms of configs.
