### ISSUE TITLE
Client 1.20.1 cannot join server 1.20.4

### ISSUE THREAD

**Issue by mateuscolli** [ViaVersion/ViaVersion#3665]
### `/viaversion dump` Output

https://dump.viaversion.com/d457f5a3a217e031cc32c004bf750d4d7dd2056fb26c224fb84f98822e380258

### Console Error

No console errors.

### Bug Description

Clients on version 1.20.1 (and I believe previous versions too), are unable to join the 1.20.4 server. I'm using a Waterfall proxy with a Lobby on version 1.8 and the main server on 1.20.4 with Purpur.

### Steps to Reproduce

1. Create a Waterfall v1.20-562 proxy server
2. Create a Purpur v1.20.4-2127 server
3. Try to join and fail.

### Expected Behavior

I hope I can join with any version of 1.20

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A92b5149%3A562](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A92b5149%3A562-3498db?style=flat-square) </br>![ViaVersion (4.10.0-24w03b-SNAPSHOT): 2 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--24w03b--SNAPSHOT)-2%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards(4.10.0-24w03a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.10.0--24w03a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by mateuscolli** [comment]
Everything is now updated, but the error persists.

**Comment by mateuscolli** [comment]
The error persists.
https://dump.viaversion.com/7be0be5669d4b267cff04642904ac0619bc728fdb1341d88946898268db1d98f

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A92b5149%3A562](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A92b5149%3A562-3498db?style=flat-square) </br>![ViaVersion (4.10.0-24w03b-SNAPSHOT): 2 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--24w03b--SNAPSHOT)-2%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by mateuscolli** [comment]
I've already updated and it's still the same error.
