### ISSUE TITLE
GeyserMC error for 1.8.8 server

### ISSUE THREAD

**Issue by trisout78** [ViaVersion/ViaVersion#3667]
### `/viaversion dump` Output

ERROR IN Protocol1_9To1_8 IN REMAP OF TEAMS (0x3E)

### Console Error

```
https://paste.gg/p/anonymous/5b5dd24c8e7748cfb677f5370b3b76ac
```

### Bug Description

When another player join a spigot server on bungee network with already a bedrock player connected, the bedrock client is kicked

### Steps to Reproduce

1. Login a bedrock player on a 1.8.8 server on a bungeecord network with Geyser
2. Login a java player

### Expected Behavior

That the bedrock player does not get kicked

### Additional Server Info

I use GeyserMC
Viaversion in on Backend (Paper or spigot)
GeyserMC support said it's a viaversion problem

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by trisout78** [comment]
https://dump.viaversion.com/6183f4b643043d50861ce9af327aba2b7375d30bfaaf4adcd3fdabb7576fdd3f

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--445%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 40 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-40%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by trisout78** [comment]
https://dump.viaversion.com/20fd5ea51bfd21b673239870bc620eff8fe8b02d857b447dd39254ba60db1f41

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--445%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.10.0-24w04a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--24w04a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by trisout78** [comment]
https://paste.gg/p/anonymous/71a2a7c39d3443d1b00070d8477ab085

**Comment by kennytv** [comment]
That error log is not from the latest ci build - but generally, if an error only affects Bedrock players, it's a Geyser issue
