### ISSUE TITLE
ViaVersion kicking all players when Bedrock user is Joining

### ISSUE THREAD

**Issue by Hyronymos1337** [ViaVersion/ViaVersion#3670]
### `/viaversion dump` Output

https://dump.viaversion.com/48df58e6637aa43e886731815e1964ab0fe994c6a9c2b24b740c4a3f264d7f4a

### Console Error

https://paste.twerion.net/nukecawuwi.makefile

### Bug Description

Hi there, we have the problem that when a Bedrock player joins the server, all players on the server (except the Bedrock player) get kicked.

XXL ViaVersion errors are printed, can you please have a look at the error? I'm not sure if it's a Floodgate or Via problem.

We are using the latest Floodgate version and ViaVersion 4.9.2.

### Steps to Reproduce

1. latest geyser standalone and floodgate
2. viaverion 4.9.2 on 1.8.8 spigot server
3. join with java as a bedrock user
4. java user gets kicked and cannot join temporarily

### Expected Behavior

No kicks.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--NachoSpigot--%225655b72%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--NachoSpigot--%225655b72%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 42 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-42%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Hyronymos1337** [comment]
this happens with latest dev build of viaversion too

**Comment by Kichura** [comment]
Geyser does not officially support 1.8.9 servers by default, and also you did not set a prefix for floodgate whatsoever - will be down to a bad third-party plugin.
