### ISSUE TITLE
Kicking people from 1.20.4 server for what seems like NBT issue

### ISSUE THREAD

**Issue by Poodleschool** [ViaVersion/ViaVersion#3671]
### `/viaversion dump` Output

https://dump.viaversion.com/eb9ac1a31d970de4edeeee03a634055bab8a94ec0ea54e622286c7ed323fbdc3

### Console Error

``
samslacks lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NoSuchMethodError: 'com.viaversion.viaversion.libs.gson.JsonElement com.viaversion.viaversion.protocols.protocol1_20_3to1_20_2.Protocol1_20_3To1_20_2.tagComponentToJson(com.viaversion.viaversion.libs.opennbt.tag.builtin.Tag)'
``

### Bug Description

It kicks players using other versions for what seems like a nbt error

### Steps to Reproduce

1. Join a 1.20.4 server on 1.20.1
2. you should be kicked and it says the server "Went down"
3. check console and you should see the error

### Expected Behavior

it should kick you

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--388%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--388%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): 31 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-31%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 22 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-22%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Poodleschool** [comment]
Done

**Comment by FlorianMichael** [comment]
Does it work now?

**Comment by Poodleschool** [comment]
> Does it work now?

no

**Comment by FlorianMichael** [comment]
Please send a new dump then

**Comment by Poodleschool** [comment]
I did, I edited the main post

> Please send a new dump then
