### ISSUE TITLE
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository

### ISSUE THREAD

**Issue by RushCN** [ViaVersion/ViaVersion#3678]
### `/viaversion dump` Output

https://dump.viaversion.com/7690c6515a39ba54cdea85b5a04cf54a3f0a88325764ca35b4a7b6d16f24c924

### Console Error

https://paste.gg/p/anonymous/b11bbdf4602e44fd967c247834b78326

### Bug Description

I can't get into the 1.16.5 server, the server shows: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutofBoundsException: Index:25,Size:5 

### Steps to Reproduce

1. Log in to the 1.16.5 server
2. Unable to enter and display: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutofBoundsException: Index:25,Size:5 

### Expected Behavior

I want to get into the server

### Additional Server Info

I use the server of the paper branch, not BungeeCord, and I remove all plugins except viaversion
I also tried the latest versions of viaversion (ViaVersion-4.10.0-24w05a-SNAPSHOT and ViaVersion-4.9.3-SNAPSHOT)

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.16.5--1215%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-1.16.5--1215%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![Mohist is not supported](https://img.shields.io/badge/Mohist%20is%20not%20supported-orange?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>proxy_limbo</details>

**Comment by RushCN** [comment]
https://dump.viaversion.com/1bdb36fad9ba89d3485c98c4a4176e83b7a07cf0f35303476f0bcdf4edbf00fb

**Comment by Barvalg** [comment]
![Platform: 1.16.5--1215%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-1.16.5--1215%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![Mohist is not supported](https://img.shields.io/badge/Mohist%20is%20not%20supported-orange?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
