### ISSUE TITLE
The player cannot enter server on 1.8.8 version from client version 1.20.4

### ISSUE THREAD

**Issue by Barpadzik** [ViaVersion/ViaVersion#3679]
### `/viaversion dump` Output

https://dump.viaversion.com/07dd9f1a613787cfdbd7f36da40bc1676de6d161ca1e3a08467ac8e81b28f4b6

### Console Error

https://paste.gg/p/anonymous/28d3b78174fd4774b13f6b9a643e5769

### Bug Description

Joining from higher versions to server 1.8.8 poses a problem.

### Steps to Reproduce

1. Join 1.8.8 Server on 1.20.4 Client
2. Check Console
3. You will spawn on void
4. Player Freeze

### Expected Behavior

Join and play :|

### Additional Server Info

I also use XCord on latest version *don't have Via on proxy*
I use fork of 1.8.8 - Imanity Premium
The problem still occurs on the last dev build

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--iSpigot--PaperEdition%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--iSpigot--PaperEdition%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Not a Via issue, that's something importerly constructing packets with ProtocolLib, or down to your Spigot fork
