### ISSUE TITLE
not supported 1.20.4

### ISSUE THREAD

**Issue by kraken6ix** [ViaVersion/ViaVersion#3680]
### `/viaversion dump` Output

https://dump.viaversion.com/2eed9f438cc3bb88d37a0f21b753ed679a0ba05a5e4626b8c3b5a81906223e67

### Console Error

https://pastebin.com/RKSMT4y1

### Bug Description

every other time allows access to the server from version 1.20.4
error: 
![image](https://github.com/ViaVersion/ViaVersion/assets/71073032/e356e699-ed8a-4e7b-ac7d-90fc3d64c5f3)

### Steps to Reproduce

every other time allows access to the server from version 1.20.4

### Expected Behavior

Everywhere there is the latest version of the plugin, but it still won’t let me in, the proxy server has support for 1.20.4

### Additional Server Info

I'm using NullCordX

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1618%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1618%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 46 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-46%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): 11 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 28 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-28%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>tab_warn</details>
