### ISSUE TITLE
com.mojang.authlib.GameProfile@dadfd41[id=aafb02ef-b890-34ae-8331-0707c3f1491b,name=KindCora_YTB,properties={textures=[com.mojang.authlib.properties.Property@7a474791]},legacy=false]

### ISSUE THREAD

**Issue by kindcora** [ViaVersion/ViaVersion#3681]
### `/viaversion dump` Output

https://dump.viaversion.com/afe17261e218766effef6be73dd2d8af5c44218fdcf4b26817cf0aa770825413

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

![image](https://github.com/ViaVersion/ViaVersion/assets/79559300/030d7666-0d0a-4d09-8cfe-8331fdaaa820)

### Steps to Reproduce

1.20.2 join server got issue 

### Expected Behavior

![image](https://github.com/ViaVersion/ViaVersion/assets/79559300/475b5982-d89d-4bc8-939a-b6699a87c80c)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--196%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--196%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
This game profile error seems to reference velocity, if you have put viaversion on there then please remove it from there and also update velocity if possible.
