### ISSUE TITLE
lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NoClassDefFoundError: com/viaversion/viaversion/libs/opennbt/tag/io/NBTIO

### ISSUE THREAD

**Issue by ohemilyy** [ViaVersion/ViaVersion#3682]
### `/viaversion dump` Output

https://dump.viaversion.com/cee0c9bf5530204540c5ba570b463c8eeda367b8872b1916cb507aa8173bfcda

### Console Error

NONE

### Bug Description

I am joining on 1.7.10 to a 1.8.8 server with ViaVersion and ViaRewind and when I do i get disconnected with lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NoClassDefFoundError: com/viaversion/viaversion/libs/opennbt/tag/io/NBTIO and in game it just says Disconnected. NOTE: 1.8 users can join just fine without being kicked.

### Steps to Reproduce

Login with 1.7.10
Thats pretty much it you cant join the server

### Expected Behavior

The user should be able to join the server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Carbon--1438e7bf%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--Carbon--1438e7bf%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 46 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-46%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
