### ISSUE TITLE
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException

### ISSUE THREAD

**Issue by AbeAzka** [ViaVersion/ViaVersion#3684]
### `/viaversion dump` Output

https://dump.viaversion.com/34e7a2b6bca05b717f9d3ff49f6f29ec83f24403cb4f8e6dad9b0c5e1eade0c2

### Console Error

https://paste.gg/p/AbeAzka/c25fd56d23034c2e81b6be6094cbaa04

### Bug Description

Error while joining using Minecraft version that older than 1.20+

### Steps to Reproduce

1. Join using MC version 1.17.1
2. After that I got kicked from server with message "Disconnected"

### Expected Behavior

Can't join server using Minecraft below 1.20_ version

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--385%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--385%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 46 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-46%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.5): 20 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-20%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 28 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-28%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>tab_warn</details>
