### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 63

### ISSUE THREAD

**Issue by gre3x** [ViaVersion/ViaVersion#3686]
### `/viaversion dump` Output

https://dump.viaversion.com/08588726e91c47e8b8d623b8a3786103aa74cc76cb94575af2ac82c474c9c73e

### Console Error

https://paste.gg/p/anonymous/99f8a921c8f74d529fefa3b0803a6b67

### Bug Description

My server crashes and sends a ton of console errors when 10+ people join it at the same time. This did not happen before I updated ViaVersion to support 1.20.4. I made no other changes to the server to cause this issue other than updating ViaVersion. This has happened many times over the last 1.5 months (about once per day)

### Steps to Reproduce

1. Have 10+ players connect to the server at about the same time
2. Observe console errors and crash

### Expected Behavior

Server does not crash and there are no console errrors

### Additional Server Info

Paper 1.12
Waterfall 1.20-582
ViaVersion on the backend

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by gre3x** [comment]
Full error logs:
[2024-02-11-1.zip](https://github.com/ViaVersion/ViaVersion/files/14231006/2024-02-11-1.zip)

**Comment by gre3x** [comment]
This is continuing to happen daily. Is there anything I can do to help resolve this or get this reviewed?

**Comment by Kichura** [comment]
Either vulcan_ae or another third-party plugin is pushing out bad entity metadata to server which makes viaversion complain about it.
