### ISSUE TITLE
crash fabric 1.20.1

### ISSUE THREAD

**Issue by kittenvr** [ViaVersion/ViaVersion#3687]
### `/viaversion dump` Output

cannot give since it crashes before i can run commands

### Console Error

```
[Put the paste.gg link or text here.](https://paste.gg/p/anonymous/fcadd6d187c241bb893ff3f1c045e820)
```

### Bug Description

while launching

### Steps to Reproduce

launch with the mod activated on 1.20.1

### Expected Behavior

doesnt crash

### Additional Server Info

fabric

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Unsupported version/VV combination

**Comment by kittenvr** [comment]
> Unsupported version/VV combination

@kennytv how do i fix this?

**Comment by kennytv** [comment]
I don't know, you can join our Discord for further help, but generally 1.20.1 is no longer a supported VF version
