### ISSUE TITLE
Problem with Texturepack.

### ISSUE THREAD

**Issue by SliderKP** [ViaVersion/ViaVersion#3689]
### `/viaversion dump` Output

https://dump.viaversion.com/0d4ea7b9cbd79ed60bcd1efebcd8b22e42b7db79134ba08fba96bf6b3931236f

### Console Error

[[```
Put the paste.gg link or text here.
```
](https://paste.gg/p/anonymous/4d57d1b048d8406baa879894be0bec00)](https://paste.gg/p/anonymous/4d57d1b048d8406baa879894be0bec00)

### Bug Description

cant join to server with texturepack

### Steps to Reproduce

login with 1.17 or old versions to a 1.20.4 velocity server with paperspigot(pufferfish) in latestversion

### Expected Behavior

can join

### Additional Server Info

>....[01:52:22 INFO]: Velocity 3.3.0-SNAPSHOT (git-15897c52-b357)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--44%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Pufferfish--44%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.5): 20 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-20%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by SliderKP** [comment]
i using all the lastest version bro T_T you can see in the dump!
        "platformName": "Pufferfish",
        "platformVersion": "git-Pufferfish-44 (MC: 1.20.4)",
        "pluginVersion": "4.9.3-SNAPSHOT",
        "implementationVersion": "git-ViaVersion-4.9.3-SNAPSHOT:cfc048ba5",
        "subPlatforms": [
            "git-viarewind-common-3.0.5:8892110",
            "git-ViaBackwards-4.9.2-SNAPSHOT:b6046429"

**Comment by FlorianMichael** [comment]
No, your ViaRewind is quite outdated

**Comment by SliderKP** [comment]
> No, your ViaRewind is quite outdated

but the problem is not with via rewind, using or not via rewind the problem persist, i added via rewind to test if i get any difference but not.

**Comment by SliderKP** [comment]
> No, your ViaRewind is quite outdated
i removed Via rewind from the server... can you reopen '

from viaversion they tell me that it is a problem between viaversion and itemsadder, with the scoreboard

And indeed if I remove any of those plugins it works again.

**Comment by kennytv** [comment]
The error means that you either weren't using ci builds, or that the plugins are using Via API with the wrong packet type. Presumably the first one though.

**Comment by SliderKP** [comment]
> The error means that you either weren't using ci builds, or that the plugins are using Via API with the wrong packet type. Presumably the first one though.

in the latest dump im using all the latestversion for viaversion and viabackwards (ci versions), viarewind, i only add to test, but now im removed viarewind and still continue the error.

**Comment by kennytv** [comment]
Send a new dump and error log please

**Comment by SliderKP** [comment]
> Send a new dump and error log please

At the same time that I communicated with you, I also made a ticket with the people at itemsadder and there they gave me a solution, apparently with the next version of itemsadder it would be fixed, I thank you very much for your time and dedication in the development of viaversion, I hope you have a excellent 2024
