### ISSUE TITLE
ERROR IN Protocol1_17_1To1_18 IN REMAP OF UPDATE_SCORE (0x56)

### ISSUE THREAD

**Issue by immersivesky** [ViaVersion/ViaVersion#3700]
### `/viaversion dump` Output

https://dump.viaversion.com/32dbf40cdea812d96cfcf67a6827c3632408d9efaf78ef9a324cf21799026dd2

### Console Error

```
[Put the paste.gg link or text here.](https://paste.gg/p/anonymous/f744fce76cb247c09b5a32f87f21dca2)
```

### Bug Description

Problem if I have a plugin TAB. If I remove TAB, it works.
Trying to log in from version 1.13.2 OptiFine to the server on version 1.20.4 Folia.
On version 1.20.4 it works.

![javaw_xBXDjHklnn](https://github.com/ViaVersion/ViaVersion/assets/104167738/c5cae5b1-b924-4ba8-9004-0afa2cdd6e2b)
![javaw_Yr4mYjlutR](https://github.com/ViaVersion/ViaVersion/assets/104167738/9177eddd-6be6-4e81-87de-422e60aa3807)

### Steps to Reproduce

1. Moved the TAB plugin
2. Logged in to the server from version 1.13.2 (OptiFine)
3. ERROR
4. Logged in to the server from version 1.20.4 (OptiFine)
5. WORKS

### Expected Behavior

Work with TAB!!!

### Additional Server Info

Windows 11 Pro
23H2
22631.3007
x64
plugins are listed in dump
only use folia

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Folia--%228939611%22%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Folia--%228939611%22%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 50 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-50%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 31 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-31%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>tab_warn</details>
