### ISSUE TITLE
help how to fix this 

### ISSUE THREAD

**Issue by shihoGGE** [ViaVersion/ViaVersion#3703]
### `/viaversion dump` Output

https://dump.viaversion.com/4eb51253f6fdf2a9b13de9ebf12743036166daafa7a45fbc6d08ebb1fad4be5a

### Console Error

https://paste.gg/p/anonymous/7d02a25efae94f4e8ce00a4568f1735b

### Bug Description

I entered server and was disconnected 

### Steps to Reproduce

I entered server and was disconnected 

### Expected Behavior

I entered server and was disconnected 

### Additional Server Info

no

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--426%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--426%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 50 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-50%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 31 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-31%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
