### ISSUE TITLE
Players are kicked with trading with villagers

### ISSUE THREAD

**Issue by DextralityNetwork** [ViaVersion/ViaVersion#3707]
### `/viaversion dump` Output

https://dump.viaversion.com/a956ad677aa1470fa681815199fdb4e1f21e0cb01ddb056537f840e18c764467

### Console Error

```
Put the mclo.gs link or text here.
```
https://mclo.gs/ghOMst7

### Bug Description

Players when they want to trade with villagers are kicked out of the server, this happens on my server 1.17 only happens with certain versions, for example I'm on 1.20.4 and it doesn't happen but users with version 1.19 click and they are kicked out.

### Steps to Reproduce

1. Join the server with an "incompatible" version like 1.19
2. trade with a villager

### Expected Behavior

This works normally, but when I interact with the villagers I get this message: (if not kicked me) https://prnt.sc/PSpC0A0U_J6i

### Additional Server Info

Pufferfish 1.17

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--22%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Pufferfish--22%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><details><summary></summary>tab_warn</details>

**Comment by kennytv** [comment]
You have a plugin setting invalid component data
