### ISSUE TITLE
error viaversion. Player in version 1.12.2->1.16 can't join server got error

### ISSUE THREAD

**Issue by quocn9043** [ViaVersion/ViaVersion#3708]
### `/viaversion dump` Output

https://dump.viaversion.com/5b37d46b1489f04803ac862a78647c84e381a0c660584190f51a8d7201222111

### Console Error

 https://pastebin.com/2fQA4661

### Bug Description

Player in version 1.12.2->1.16 can't join server got error

### Steps to Reproduce

can't know

### Expected Behavior

Player in version 1.12.2->1.16 can't join server got error

### Additional Server Info

Backend Server Pufferfish 1.20.4

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--45%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Pufferfish--45%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 51 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-51%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 32 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-32%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>tab_warn</details>
