### ISSUE TITLE
io.netty.handler.codec.EncoderException

### ISSUE THREAD

**Issue by ChickChuck2** [ViaVersion/ViaVersion#3715]
### `/viaversion dump` Output

https://dump.viaversion.com/001a067d9f9e14fbd7ea1b848909d10f0894cde40dcdd93293a0b98f5ee788ad

### Console Error

```
[18:02:50 INFO]: Shepster1234 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: UPDATE_SCORE, Type: VarInt, Index: 2, Data: [{StringType: GabrielBek}], Source 0: com.viaversion.viabackwards.protocol.protocol1_17_1to1_18.Protocol1_17_1To1_18$5 (Anonymous), Packet ID: 86
```

### Bug Description

login with a 1.8 client in a purpur server 1.20.4

### Steps to Reproduce

1. Log-in in a server with a 1.8 client

### Expected Behavior

log-in in server

### Additional Server Info

purpur server with ViaVersion, ViaBackwards, ViaRewards LATEST STABLE VERSION

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2151%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--2151%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 51 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-51%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.5): 31 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-31%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 32 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-32%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by ChickChuck2** [comment]
https://dump.viaversion.com/001a067d9f9e14fbd7ea1b848909d10f0894cde40dcdd93293a0b98f5ee788ad

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2151%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--2151%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 51 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-51%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.5): 31 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-31%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 32 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-32%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by ChickChuck2** [comment]
> ![Platform: git--Purpur--2151%20%28MC%3A%201.20.4%29](https://camo.githubusercontent.com/489f2873e195103ab005feb1be7a0b2d9214c8744517de6ea4aba52f915c50bf/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d5075727075722d2d323135312532302532384d43253341253230312e32302e342532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.9.2): 51 commits behind master](https://camo.githubusercontent.com/7bd44db9a8ae192b60072da3164a2d25e378dc533299b1b4f52033ac5dfaaa9b/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e392e32292d3531253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaRewind(3.0.5): 31 commits behind master](https://camo.githubusercontent.com/f7410cc87f9a6b99c4c693b0903a803f1c2e4b27883fce2469075cff59042606/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f566961526577696e6425323028332e302e35292d3331253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaBackwards(4.9.1): 32 commits behind master](https://camo.githubusercontent.com/4f17823cfbb89b8df91c805d1de0f55988882b9b55333a80130af61798ec3411/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e392e31292d3332253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265)
> 
> ### Please update **all** Via* plugins from https://ci.viaversion.com/. In case the issue still persists send the new dump and the issue will be reopened

bruh

**Comment by ChickChuck2** [comment]
> ![Platform: git--Purpur--2151%20%28MC%3A%201.20.4%29](https://camo.githubusercontent.com/489f2873e195103ab005feb1be7a0b2d9214c8744517de6ea4aba52f915c50bf/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d5075727075722d2d323135312532302532384d43253341253230312e32302e342532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.9.2): 51 commits behind master](https://camo.githubusercontent.com/7bd44db9a8ae192b60072da3164a2d25e378dc533299b1b4f52033ac5dfaaa9b/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e392e32292d3531253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaRewind(3.0.5): 31 commits behind master](https://camo.githubusercontent.com/f7410cc87f9a6b99c4c693b0903a803f1c2e4b27883fce2469075cff59042606/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f566961526577696e6425323028332e302e35292d3331253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaBackwards(4.9.1): 32 commits behind master](https://camo.githubusercontent.com/4f17823cfbb89b8df91c805d1de0f55988882b9b55333a80130af61798ec3411/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e392e31292d3332253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265)
> 
> ### Please update **all** Via* plugins from https://ci.viaversion.com/. In case the issue still persists send the new dump and the issue will be reopened

https://dump.viaversion.com/001a067d9f9e14fbd7ea1b848909d10f0894cde40dcdd93293a0b98f5ee788ad

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2151%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--2151%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 51 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-51%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.5): 31 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-31%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 32 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-32%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
