### ISSUE TITLE
ERROR IN Protocol1_10To1_11 IN REMAP OF SET_SLOT (0x16)

### ISSUE THREAD

**Issue by KneesDev** [ViaVersion/ViaVersion#3717]
### `/viaversion dump` Output

https://dump.viaversion.com/bcd5515d0c5e11b99862081008f9ebf61ac9261d60f738618f40794ee3edd016

### Console Error

```
https://mclo.gs/p0Rhibh
```

### Bug Description

Screaming BedWars & SBA on 1.12.2 with ViaVersion 1.8 client will kick the player or crash the server once the game starts.

### Steps to Reproduce

1. Login to an owned Minecraft 1.12.2 server using 1.8.9 client
2. Start the game using `/bw cheat startemptygame` or wait for players to join.
3. You'll be kicked or the server will crash.

### Expected Behavior

The game should just.. _work_. It shouldn't kick the player, nor crash the server.

### Additional Server Info

I use BungeeCord. The plugins can be seen in the dump.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Outdated!-red?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(3.0.0)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>tab_warn</details>

**Comment by KneesDev** [comment]
The issue still persists, [new dump](https://dump.viaversion.com/a0004b76833f30802bc8563d2c06168245b92632dd25b0f754fced76a925d854).

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 51 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-51%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.5): 31 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-31%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 32 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-32%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
