### ISSUE TITLE
Unable to Connect on Older Version

### ISSUE THREAD

**Issue by GrumpyCatJen** [ViaVersion/ViaVersion#3718]
### `/viaversion dump` Output

https://dump.viaversion.com/b72869fdd9ebb2fe2e3146c414e718fa8875649437ae5da8c0569860f69da6db

### Console Error

```
https://mclo.gs/qN71Jp2
```

### Bug Description

We have a server that was updated to 1.20.4.  We had been noticing that new players will join our server and shortly after leave the server.  Our console was showing issues with ViaVersion.  I tested it out by trying to connect in older versions like 1.8, 1.16, 1.17, 1.18.  The only versions I am able to connect with are 1.18 to 1.20.4.  We have also tried different launchers such as Badlion and Forge, and I also tried without Optifine, but the only issue seems to be connected to the version.  I have seen the same/similar issue reported and the only answer provided was to update to a master/dev build.  I tried 4.9.3-SNAPSHOT, but it made it worse by preventing players from connecting even in 1.20.1.  Then, I tried updating to 4.10.0-24w07a-SNAPSHOT.  We still had issues connecting with old versions AND we had a new error start spamming chat even when zero players were on the server: "[ClientDetector] [STDOUT] Unable to grab ViaVersion client version for player!"  What else can we try?

### Steps to Reproduce

In launcher, login using older version of Minecraft.  Go to Multiplayer and select our server.  It either freezes the launcher or gives a proxy error or says the server went down unexpectedly (when it did not).  From our end, player will show as connected but then disconnected shortly after.

### Expected Behavior

In launcher, login using older version of Minecraft.  Go to Multiplayer and select our server.  Connect and play without issue.

### Additional Server Info

We have Waterfall, BungeeCord, Geyser, Floodgate, ViaBackwards-4.9.1, ViaRewind-3.0.5, ViaVersion-4.9.2, and several other plugins (including but not limited to): Essesntials, ClientDetector, FastAsyncWorldEdit, GriefPreventionData, GSit, InfiniteAnnouncements, InfiniteScoreboard, JetsAntiAFKPro, JoinDelay, LTItemMail, Placeholder API, Multiverse-Core, PluginManager, VentureChat, WorldGuard, VotingPlugin.....

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--431%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--431%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 51 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-51%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.5): 31 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-31%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 32 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-32%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by GrumpyCatJen** [comment]
I already tried updating ViaVersion... that link only shows ViaVersion.. I looked for updates to ViaBackwards and ViaRewind and I have the latest ones.

**Comment by GrumpyCatJen** [comment]
I'm guessing I need to update to these?  If so, would be nice if it was in the link.. https://hangar.papermc.io/ViaVersion/ViaRewind/versions/3.0.6-SNAPSHOT+89   https://hangar.papermc.io/ViaVersion/ViaBackwards/versions/4.9.2-SNAPSHOT+138       https://hangar.papermc.io/ViaVersion/ViaVersion/versions/4.10.0-24w07a-SNAPSHOT+247

**Comment by GrumpyCatJen** [comment]
I updated to all of these and it would not allow players to connect in 1.20.1.  The ClientDetector was also giving a different output when other players did connect, which was very weird. 
![image](https://github.com/ViaVersion/ViaVersion/assets/159399955/92a7ce5e-5df1-452e-a1a9-ab6eea5ddb29)
So, I reverted back to the old ViaVersion I had.  After restarting the server, players still could not connect to 1.20.1.  So I reverted ViaRewind.  The only one that seems to have updated without issue is ViaRewind...

**Comment by GrumpyCatJen** [comment]
I tried connecting again in 1.8, 1.15, 1.17, 1.18.. and I was only able to connect 1.18 or later.  
![image](https://github.com/ViaVersion/ViaVersion/assets/159399955/f59f22b7-5263-420c-9997-2ca378a7c00b)

**Comment by Kichura** [comment]
> I updated to all of these and it would not allow players to connect in 1.20.1. The ClientDetector was also giving a different output when other players did connect, which was very weird. ![image](https://private-user-images.githubusercontent.com/159399955/308036032-92a7ce5e-5df1-452e-a1a9-ab6eea5ddb29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTA1MTUsIm5iZiI6MTcwOTAxMDIxNSwicGF0aCI6Ii8xNTkzOTk5NTUvMzA4MDM2MDMyLTkyYTdjZTVlLTVkZjEtNDUyZS1hMWE5LWFiNmVlYTVkZGIyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QwNTAzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjJhODA1YzZlNzc3NzdlYTAxZTUzZTQ5ZTYxZjBjZjEzNWE0YjJmMDEwMWZiYWM5ZGE4MmYyNDBhNWY0NTA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gBHl6JXhoKRFP3SCS-f3IaPXJudsgLnPMALmqF7Hid8) So, I reverted back to the old ViaVersion I had. After restarting the server, players still could not connect to 1.20.1. So I reverted ViaRewind. The only one that seems to have updated without issue is ViaRewind...

This is because your third party plugins are still trying to use the old viaversion when the internal classes have changed to use mcstructs for example, as for the screenshot - the update score was fixed a while ago in 4.9.3-snapshot.
