### ISSUE TITLE
nternal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository Packet Type: UPDATE_SCORE, Type: VarInt, Index: 2, Data: [{StringType: §0§2§r}], Source 0: com.viaversion.viabackwards.protocol.protocol1_17_1to1_18.Protocol1_17_1To1_18$5 (Anonymous), Packet ID: 86

### ISSUE THREAD

**Issue by ShoelessTom** [ViaVersion/ViaVersion#3730]
### `/viaversion dump` Output

https://dump.viaversion.com/c0db3ee2cea752c597255dd8d56b93585840dc48bba2b00c0873691f629cf865

### Console Error

```
(https://mclo.gs/Ad4E4hY)
```

### Bug Description

1.8 client joining 1.20.4 server gets kicked with reason proxy lost connection to server

### Steps to Reproduce

1. login with 1.8 client and join 1.20.4 server, get kicked for proxy lost connection to server

### Expected Behavior

Should not get kicked

### Additional Server Info

My via plugins are in my backend spigot servers instead of the bungee 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Leaf--%22a5953c0%22%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Leaf--%22a5953c0%22%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 51 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-51%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.5): 31 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-31%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 32 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-32%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>tab_warn</details>
