### ISSUE TITLE
1.8.9 Client kick on a 1.20.4 server when invoking .createExplosion() from "org.bukkit.World"

### ISSUE THREAD

**Issue by SrZafkiell** [ViaVersion/ViaVersion#3732]
### `/viaversion dump` Output

https://dump.viaversion.com/75cd12b3de65a67f403c77b76fb47eb2e28275024d437efa9f8c7a17e45ce8a0

### Console Error

```
https://mclo.gs/z4HLtFy
```

### Bug Description

When using the "createExplosion()" from the packet "org.bukkit.World" the player gets kicked:
![image](https://github.com/ViaVersion/ViaVersion/assets/75232612/75c037da-1236-423b-8049-a9a6c87aebbe)

### Steps to Reproduce

Line of code executed: event.getRightClicked().getWorld().createExplosion(event.getRightClicked().getLocation(), 5);
When the event gets executed the player gets kicked.
Reproducing it: https://youtu.be/Rxxd2eBlDrk 

### Expected Behavior

The function that detonates the mob is the following:
```
@EventHandler
public void onRightClick(PlayerInteractEntityEvent event) {
    if (event.getRightClicked().getType() == EntityType.ZOMBIE)
        event.getRightClicked().getWorld().createExplosion(event.getRightClicked().getLocation(), 5);
}
```
After executing the event, the player gets kicked.
What should happen is a simple explosion without a kick.

### Additional Server Info

Every plugin in the viaversion dump is in the last version for 1.20.4 and the only plugin not available is the "SimpleSpawnpoints" and it only has the test function listed before.
Tried using the last build "ViaVersion-4.9.3-SNAPSHOT" but I was not able to join the server. I'm using the 1.8.9. When using version 1.20.4 works as expected with no kick not console error: https://youtu.be/u08eYwGhgtE

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--436%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--436%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 53 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-53%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.5): 31 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-31%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 34 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-34%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
