### ISSUE TITLE
1.20.4 paper server kicks 1.20.1 fabric client

### ISSUE THREAD

**Issue by PetarMc1** [ViaVersion/ViaVersion#3734]
### `/viaversion dump` Output

I get this: https://mclo.gs/K4wHUBB when i try to do /viaversion dump

### Console Error

https://mclo.gs/SDqMeRA

### Bug Description

![image](https://github.com/ViaVersion/ViaVersion/assets/160483025/b4d27132-143c-4027-bf3f-66c6b7545a8e)

### Steps to Reproduce

1. Login on 1.20.1
2. try to join a 1.20.4 paper server with viaversion and ViaBackwards
3. You will get this error
![image](https://github.com/ViaVersion/ViaVersion/assets/160483025/2f11469b-eb38-4aa3-8869-b739ee614a69)

### Expected Behavior

i expected just to join

### Additional Server Info

paper server with a lot of plugins

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [ ] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Jo0001** [comment]
Hi, please update Via* to the latest builds (see below), in case the problem still persits I recommend that you join our discord (https://viaversion.com/discord )
https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/4.9.3-SNAPSHOT%2B264/PAPER/ViaVersion-4.9.3-SNAPSHOT.jar
https://hangarcdn.papermc.io/plugins/ViaVersion/ViaBackwards/versions/4.9.2-SNAPSHOT%2B140/PAPER/ViaBackwards-4.9.2-SNAPSHOT.jar
