### ISSUE TITLE
Couldn't pass ProxyInitializeEvent to viaversion

### ISSUE THREAD

**Issue by ThePolishLemon** [ViaVersion/ViaVersion#3736]
### `/viaversion dump` Output

https://dump.viaversion.com/2303fdc0f8d28621bfb7a1031f8584c509c23a1a00ff1d47e0c20a7b887c1025

### Console Error

https://mclo.gs/Uf8TQ2q

### Bug Description

Throws an error, doesnt allow you to join the server with versions other than native

### Steps to Reproduce

1. Install latest Velocity and viaversion
2. Watch the plugin throw an error and be unable to join the server from other versions than its native version

### Expected Behavior

Working ViaVersion, be able to join the server

### Additional Server Info

I use the latest version of Velocity with the following plugins:
ajqueue
ViaVersion
ViaRewind
ViaBackwards
EnchancedVelocity
EpicGuardVelocity
Geyser
Libertybans
Limboapi
Limboauth
Limbofilter
Luckperms
Skinsrestorer
VelocityVanish
SignedVelocity
VelocityReport

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
Your viabackwards is not on the latest dev build.

**Comment by ThePolishLemon** [comment]
> Your viabackwards is not on the latest dev build.

Tried that already too, just didn't have the time to respond with the new dump yet
