### ISSUE TITLE
Chat is broken for 1.8.8 Server (1.19+ client)

### ISSUE THREAD

**Issue by maxplayz2746** [ViaVersion/ViaVersion#3743]
### `/viaversion dump` Output

https://dump.viaversion.com/9a376685b0ba75a49d795c4c4020cbd3164b2f091e942c18c1966ff98bb3ea11

### Console Error

```
Put the mclo.gs link or text here.
```
didnt have one

### Bug Description

Chat on 1.19+ client 1.8.8 server WITH essentials x is completely broken! it just says [Maxplayz7566⭐] [Maxplayz7566⭐] no message

### Steps to Reproduce

1.19 client on 1.8.8 server WITH essentials

### Expected Behavior

The chat appears

### Additional Server Info

im also using a velocity with geyser and geyser also same issue

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--445%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.9.2)-Outdated!-red?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(3.0.5)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
