### ISSUE TITLE
1.16.5 client kicks on 1.20.4 server when using trident

### ISSUE THREAD

**Issue by Dreeam-qwq** [ViaVersion/ViaVersion#3744]
### `/viaversion dump` Output

https://dump.viaversion.com/951015bd76ee3e59ba672cb9fc65396a6c30eec8280270cbb281c31ffe0c5e25

### Console Error

```
https://mclo.gs/2eNJtp2
```

### Bug Description

1.16.5 client kicks when throwing a trident on 1.20.4 server

### Steps to Reproduce

1. Use 1.16.5 client
2. Join 1.20.4 server
3. use give command to get a trident
4. throw it then get kick and see errors in console

### Expected Behavior

Player can use trident without error with lower version client on 1.20.4 server

### Additional Server Info

Server: git-Paper-450 (MC: 1.20.4)
Plugins: [ViaBackwards](https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/583/), [ViaVersion](https://ci.viaversion.com/job/ViaVersion-DEV/1052/)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--450%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--450%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.0-24w09a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--24w09a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.0-24w09a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.10.0--24w09a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>
