### ISSUE TITLE
NullPointerException when converting components.

### ISSUE THREAD

**Issue by Fabelz** [ViaVersion/ViaVersion#3745]
### `/viaversion dump` Output

https://dump.viaversion.com/17a7ef180297d4858a020ea26582894dc40e8e300018e71f1e75d5c1bbe3f85e

### Console Error

https://mclo.gs/J9TdlTT

### Bug Description

At times, this error will be displayed in the console regardless of whether we use the stable or dev builds.

I have tried debugging this to no avail, it doesn't particularly appear to make much sense, as the ComponentUtil#jsonToTag method appears to catch and return null for null elements, so this shouldn't be getting thrown at all.

It's important to note that this only appears for clients on 1.20.2 or above. We also have issues with join messages for servers not appearing for clients above 1.20.2 on servers below 1.20.2 (we have servers ranging from 1.8 > 1.20.4).

I'm probably just be doing something dumb here, just thought I'd post this incase it was a genuinely mass replicatable issue that may help with something (and I'd love for it to stop appearing haha).

<img width="454" alt="image" src="https://github.com/ViaVersion/ViaVersion/assets/15955937/7decc6c2-bb67-4da3-a984-2930132b1b56">
<img width="494" alt="image" src="https://github.com/ViaVersion/ViaVersion/assets/15955937/39b4ab39-830c-45dd-99ff-cec123ae0bb8">

### Steps to Reproduce

Unfortunately it's hard to reproduce so I can't exactly provide steps, but I've managed to get it to appear at times by sending a message on join, although I'm 90% sure it can occur outside of it.

### Expected Behavior

The exception to not occur, as I believe that this would probably prevent components from being sent.

### Additional Server Info

We use a velocity proxy with plugins to dynamically add and remove servers, as well as other network-related utilities. No plugin on the velocity end messes with packets, but some of our in-house plugins on the spigot server's end are known to send version-specific packets to ensure a higher quality playing experience across versions (i.e RGB support for 1.20 clients on 1.8 servers). Right now however, there is no specialized support built in for 1.20.2 clients or above, so there should be nothing messing with these packets.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: main/084280b%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-main/084280b%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3): 5 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.7-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.7--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Fabelz** [comment]
https://dump.viaversion.com/94bef74eca81202f80443f4f68aa25814f7c97bb6e54abf36b3171d849c2e728

**Comment by Barvalg** [comment]
![Platform: main/084280b%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-main/084280b%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.10.0-24w09a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--24w09a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(3.0.7-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.7--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.0-24w09a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.10.0--24w09a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>
