### ISSUE TITLE
Protocol Errors messages when I'm running /stop command 

### ISSUE THREAD

**Issue by x9nico** [ViaVersion/ViaVersion#3746]
### `/viaversion dump` Output

https://dump.viaversion.com/c8b9e86e18d7fb73af9b869113990f6d4c5c06dff3b503504506e9ca86177e9a

### Console Error

https://mclo.gs/wG303Hy

### Bug Description

When I'm stopping my Server with Players connected on old versions like 1.9.4 on Paper 1.20.4, it produces errors messages when I'm stopping my server with /stop (see Console Error link).

### Steps to Reproduce

1. Login with 1.9.4 client on Paper 1.20.4
2. Make a /stop
3. And you have the error.

### Expected Behavior

It shouldn't have any error message...

### Additional Server Info

I'm running Paper 1.20.4 build number 454.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--454%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--454%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.2): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.2)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>broken_jar</details>

**Comment by x9nico** [comment]
https://dump.viaversion.com/f84a2a5d0a42d4a33add7601900ca333a44c9fd8430b1745342fc528baec90a3

**Comment by Barvalg** [comment]
![Platform: git--Paper--454%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--454%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.7-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.7--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
You either had broken jars or replaced them while the server was running; don't do that
