### ISSUE TITLE
Error spam in the console. Please how to fix this?

### ISSUE THREAD

**Issue by TheFaik** [ViaVersion/ViaVersion#3747]
### `/viaversion dump` Output

https://dump.viaversion.com/763adf8e2aac09aac7aa1c8f91f5c8a4ad385c069df0c070dd168d3b62c3298f

### Console Error

https://pastebin.com/TwfQRd30

### Bug Description

I don't no...

### Steps to Reproduce

I don't no...

### Expected Behavior

I don't no...

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2158%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--2158%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.3-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.3--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
