### ISSUE TITLE
DragonCraft64 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository Packet Type: UPDATE_SCORE, Type: VarInt, Index: 2, Data: [{StringType: 1 §r§f§1§b§n§e§4}], Source 0: com.viaversion.viabackwards.protocol.protocol1_17_1to1_18.Protocol1_17_1To1_18$5 (Anonymous), Packet ID: 86

### ISSUE THREAD

**Issue by Nerd10000** [ViaVersion/ViaVersion#3748]
### `/viaversion dump` Output

https://dump.viaversion.com/7678b2d9351da66325901c67e12add1b87ecdccc62eb779e43c4359b9f0d83cd

### Console Error

```
DragonCraft64 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: UPDATE_SCORE, Type: VarInt, Index: 2, Data: [{StringType: 1 §r§f§1§b§n§e§4}], Source 0: com.viaversion.viabackwards.protocol.protocol1_17_1to1_18.Protocol1_17_1To1_18$5 (Anonymous), Packet ID: 86
```

### Bug Description

Kick the player when it Joins,

### Steps to Reproduce

1.Download the Viaversion 4.93
2.Launch 1.16.5 version.
3.And join

### Expected Behavior

Able to join to the game.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--408%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--408%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.9.2)-Outdated!-red?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(3.0.5)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
