### ISSUE TITLE
Randomly disconnect when joining

### ISSUE THREAD

**Issue by PixelEast** [ViaVersion/ViaVersion#3749]
### `/viaversion dump` Output

https://dump.viaversion.com/cb2e2dcf0c4fa4a1075801e7c3f60660d8977420300c6af3feef5002abb1d080

### Console Error

https://pastebin.com/7EUijgCe

### Bug Description

When a player joins the server, a console error occurs and the player is randomly asked to disconnect

### Steps to Reproduce

Using the 1.20.4 client and joining the 1.12.2 Paper server

### Expected Behavior

Should join normally without any errors or disconnection

### Additional Server Info

I am using bungeecord, but viaversion is only installed on the backend server
![image](https://github.com/ViaVersion/ViaVersion/assets/30312760/62c76836-5ec8-4890-9cb3-b6f19e17230c)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.7-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.7--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
