### ISSUE TITLE
[packetevents] Unable to grab ViaVersion client version for player!

### ISSUE THREAD

**Issue by Barpadzik** [ViaVersion/ViaVersion#3750]
### `/viaversion dump` Output

https://dump.viaversion.com/201a97e96b364f2183dd8c552566bf9c48cd273eb9a19560cfa8a52f9488c4d9

### Console Error

![obraz_2024-03-20_200113475](https://github.com/ViaVersion/ViaVersion/assets/132010826/86567c3d-1e6b-48f4-9841-aa80e31fbcf9)
[Netty Epoll Server IO #1/INFO]: [packetevents] Unable to grab ViaVersion client version for player!

### Bug Description

When I enter the server and move, write messages or simply stand still, the message given above is displayed

### Steps to Reproduce

Join the server

### Expected Behavior

No message

### Additional Server Info

![image](https://github.com/ViaVersion/ViaVersion/assets/132010826/79182ad6-07ef-42f1-86af-28c03cdeea01)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2159%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--2159%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.0-24w09a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--24w09a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.0-24w09a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.10.0--24w09a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Please update your packet events to the latest development version: https://github.com/retrooper/packetevents/actions/runs/8305751353

**Comment by Barpadzik** [comment]
> Please update your packet events to the latest development version: https://github.com/retrooper/packetevents/actions/runs/8305751353

How? Some tutorial?

**Comment by FlorianMichael** [comment]
By deleting the old plugin jar file and replacing it with the new one from the Artifacts.zip file

**Comment by Barpadzik** [comment]
> By deleting the old plugin jar file and replacing it with the new one from the Artifacts.zip file

Can you give me direct link to download Artifacts.zip?

**Comment by FlorianMichael** [comment]
You can download them here: https://ci.codemc.io/job/retrooper/job/packetevents/

**Comment by Barpadzik** [comment]
> You can download them here: https://ci.codemc.io/job/retrooper/job/packetevents/

Didn't help

**Comment by FlorianMichael** [comment]
Are you still getting these warnings?

**Comment by Barpadzik** [comment]
> Are you still getting these warnings?

Yes

**Comment by FlorianMichael** [comment]
I didn't saw you were using AntiCheats depending on packetevents, you have to update Vulcan/wait for them to push an update with the latest packetevents version (same for GrimAC)

**Comment by Barpadzik** [comment]
> I didn't saw you were using AntiCheats depending on packetevents, you have to update Vulcan/wait for them to push an update with the latest packetevents version (same for GrimAC)

While I had this viaversion build I couldn't even move because grime reported me without any interruptions but it was probably fixed in the new grima update
