### ISSUE TITLE
Internal Exception

### ISSUE THREAD

**Issue by daniel-skopek** [ViaVersion/ViaVersion#3752]
### `/viaversion dump` Output

https://dump.viaversion.com/7b1b3be9cded668d700ed59d53f6cf3a82eb9c6341061bd159f7d5499d207602

### Console Error

https://api.mclo.gs/1/raw/JGdrvw1

### Bug Description

I don't know what is causing this error. But probably opening (BattlePass) GUI?

### Steps to Reproduce

Open GUI

### Expected Behavior

The error should be fixed.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--UniverseSpigot--%2203a74ad%22%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--UniverseSpigot--%2203a74ad%22%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.2): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.2)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
