### ISSUE TITLE
Internal Exception

### ISSUE THREAD

**Issue by daniel-skopek** [ViaVersion/ViaVersion#3753]
### `/viaversion dump` Output

https://dump.viaversion.com/d5eb3d5c6a7b3e005c4554deb4e63b23d8a44abfde8edd1e435726da53451b3d

### Console Error

https://api.mclo.gs/1/raw/JGdrvw1

### Bug Description

When hovering on PLAYER_HEAD in chat

### Steps to Reproduce

1. Hold PLAYER_HEAD in hand
2. Type [item]
3. Error is in the console and players are kicked from the server.

Using ChatItem plugin to show item in chat.

### Expected Behavior

The error should be fixed.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--UniverseSpigot--%2203a74ad%22%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--UniverseSpigot--%2203a74ad%22%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Are you sure you actually tested this with ci builds

**Comment by kennytv** [comment]
Please send the new error then, it will look different

**Comment by kennytv** [comment]
This might be fixed using the latest release/ci builds, if not we'll reopen
