### ISSUE TITLE
connection failed

### ISSUE THREAD

**Issue by Perets2207** [ViaVersion/ViaVersion#3759]
### `/viaversion dump` Output

https://dump.viaversion.com/25407bd270acd4b4023c4243e160befa25c1a133021d8de4f758fa2785e24d72

### Console Error

https://mclo.gs/07LuTOJ

### Bug Description

Connection failed

### Steps to Reproduce

install 1.20.4 purpur and velocity git-75d6dcc1-b371
login with 1.20.1 client
have an error

### Expected Behavior

Connection failed

### Additional Server Info

1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Perets2207** [comment]
заработало

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--75d6dcc1--b371%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--75d6dcc1--b371%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.2): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.2)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>proxy_limbo</details>

**Comment by Perets2207** [comment]
bro i tried this before instal outdated builds :/

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--75d6dcc1--b371%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--75d6dcc1--b371%29-3498db?style=flat-square) </br>![ViaVersion (4.10.0-24w09a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.10.0--24w09a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.0-24w09a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.10.0--24w09a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by Perets2207** [comment]
я запустил сервер только с via плагинами и все заработало, но всё равно непонимаю почему не работало
