### ISSUE TITLE
help me with a mistake I can't fix.

### ISSUE THREAD

**Issue by snellnn** [ViaVersion/ViaVersion#3760]
### `/viaversion dump` Output

https://dump.viaversion.com/ea4ce817dd278874d6c3a09239519666d19051eb6d983a25b8faf537dbb11ff7

### Console Error

https://api.mclo.gs/1/raw/u1MuDXg
![photo_2024-03-26_14-41-36](https://github.com/ViaVersion/ViaVersion/assets/131030266/8c6a500f-2473-462b-8bd7-bc445ed345bd)
![image_2024-03-26_14-45-41](https://github.com/ViaVersion/ViaVersion/assets/131030266/624e92c3-11cc-4c3a-bcb5-d23e00e7484c)

### Bug Description

I am creating a Bed Wars game mode server. When players enter the lobby, after 30 seconds of waiting, when the game starts, there is spam in the console!

BedWars1058 plugin

### Steps to Reproduce

The mini-game starts.

### Expected Behavior

I'd like some kind of tutorial on how to fix it because I can't fix it.

### Additional Server Info

no

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.2): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.2)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Jo0001** [comment]
Seems like some plugin is sending invalid data. To find out which plugin do a binary plugin search, starting with the bedwars plugin

**Comment by snellnn** [comment]
how to do it?

**Comment by snellnn** [comment]
![12](https://github.com/ViaVersion/ViaVersion/assets/131030266/e52a5612-a56f-4a9b-bbb3-4b7ede37a99a)

**Comment by snellnn** [comment]
![PlaceholderAPI-2 11](https://github.com/ViaVersion/ViaVersion/assets/131030266/b51d93a2-e13a-4bb2-b7f3-f4cfcd9be17b)

**Comment by Perets2207** [comment]
какой-то плагин или что-то другое отправляет то что не может преобразовать viaversion как я понял

**Comment by snellnn** [comment]
спасибо я понимаю ну что имено ето ?

**Comment by snellnn** [comment]
when you log in from version 1.12.2 everything works well

**Comment by Kichura** [comment]
It's because viaversion will not do anything if the client matches server version, that's the reality.

**Comment by snellnn** [comment]
I found an older version of the plugins and it worked
![Uploading photo_2024-03-26_22-22-52.jpg…]()

**Comment by snellnn** [comment]
[00:21:51 INFO]: ViaVersion version 4.7.0
[00:21:51 INFO]: Allow newer clients to join older server versions.
[00:21:51 INFO]: Authors: _MylesC, creeper123123321, Gerrygames, kennytv and Matsv
version ViaBackwards
[00:22:11 INFO]: ViaBackwards version 4.7.0
[00:22:11 INFO]: Allow older Minecraft versions to connect to a newer server version.
[00:22:11 INFO]: Website: https://github.com/ViaVersion/ViaBackwards
[00:22:11 INFO]: Authors: Matsv, kennytv, Gerrygames, creeper123123321 and ForceUpdate1

**Comment by Kichura** [comment]
Caused by bedwars1058 plugin, although it has issues of it's own when viaversion isn't present such as enemies being invisible in 1.8.8 servers.

**Comment by snellnn** [comment]
only restrictions on versions 1.20.1

**Comment by snellnn** [comment]
but I'm going to update the server to high versions, I would like this to be fixed as soon as possible, I hope they notice me

**Comment by snellnn** [comment]
https://github.com/ViaVersion/ViaVersion/issues/3760#:~:text=%D0%BD%D0%B0%20%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B8%201.20.1-,%D0%9A%D0%B8%D1%87%D1%83%D1%80%D0%B0,-%D1%83%D0%BF%D0%BE%D0%BC%D1%8F%D0%BD%D1%83%D0%BB%20%D0%BE%D0%B1%20%D1%8D%D1%82%D0%BE%D0%BC и что ты мне етим хочеш сказать ?

**Comment by snellnn** [comment]
Кучура я непонимаю что ты мне етим хочеш сказать ?

**Comment by snellnn** [comment]
but I'm going to update the server to high versions, I would like this to be fixed as soon as possible, I hope they notice me

**Comment by snellnn** [comment]
> Вызвано плагином bedwars1058, хотя у него есть свои проблемы, когда viaversion отсутствует, например, враги становятся невидимыми на серверах 1.8.8.

and what should I understand from this

**Comment by snellnn** [comment]
https://dump.viaversion.com/6e571d19a60d4da4161707eb27eab88f41ed52a946d52fe6b1a5372486b6f7e7

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.7.0)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by snellnn** [comment]
https://dump.viaversion.com/b32f0029bb6ab6a1e237a0dc0ac908bed0b686aacfa9ddaeb17360160da5265d

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by snellnn** [comment]
> Caused by bedwars1058 plugin, although it has issues of it's own when viaversion isn't present such as enemies being invisible in 1.8.8 servers.

If you are a developer, please help
