### ISSUE TITLE
Kick due to map 

### ISSUE THREAD

**Issue by lDoomerl** [ViaVersion/ViaVersion#3764]
### `/viaversion dump` Output

https://dump.viaversion.com/85eb35b416f1d347a9690238a02a332c9285df287d5920e9a8dddf6af93d636c

### Console Error

```
https://api.mclo.gs/1/raw/lnidYRg
```

### Bug Description

Map in hand causes kick from the server on the version 1.12.2. Server ver 1.20.2

### Steps to Reproduce

1. Login with 1.12.2 client
2. Find a map
3 Try to look at the map

### Expected Behavior

Player shouldn't be kicked 

### Additional Server Info

BungeeCord

Server Plugins (22):
Bukkit Plugins:
 - Chunky, CMI, CMILib, CordeCheck, CordeJoin, CordeOpBlocker, CoreProtect, DiscordSRV, FastAsyncWorldEdit, *FGApi,  FGBansProvider, floodgate, LuckPerms, PlaceholderAPI, PlasmoVoice, ProtocolLib, RayTraceAntiXray, TAB, Vault, ViaBackwards,  ViaVersion, Vulcan

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--35%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Pufferfish--35%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.9.2)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
