### ISSUE TITLE
Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository Packet Type: PLAYER_INFO, Type: OptionalComponentType, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$$Lambda$8275/0x0000025733072320, Packet ID: 55

### ISSUE THREAD

**Issue by ProBlox42R** [ViaVersion/ViaVersion#3776]
### `/viaversion dump` Output

https://dump.viaversion.com/cfe410ca9d04b6735834e86c83c25791e285a3ec20ce03c63935e75c1c63eac5

### Console Error

Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: PLAYER_INFO, Type: OptionalComponentType, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$$Lambda$8275/0x0000025733072320, Packet ID: 55
It appears when i join the server with 1.8.9

### Bug Description

Joining in older versions causes this error

### Steps to Reproduce

1. Join the server in 1.8.9
2. This appeares

### Expected Behavior

I should be in the server (not be kicked)

### Additional Server Info

I use Waterfall proxy.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--463%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--463%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.6): 13 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.6)-13%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.2): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.2)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
