### ISSUE TITLE
my native version is paper 1.20.2 when I enter the 1.8.8 it ejects me from the server and I get this error

### ISSUE THREAD

**Issue by ponchins** [ViaVersion/ViaVersion#3784]
### `/viaversion dump` Output

https://dump.viaversion.com/d69f16244df4f3fc76f500ed1bedc5ff5ba0cc7bb9a459b826ace1e35b569249

### Console Error

```
https://mclo.gs/Ktr0GRM
```

### Bug Description

I get kicked out because I have custom spawners from 1.20.2 and when I enter 1.8.8 I get kicked out of the server. spawners created with gamergeek

### Steps to Reproduce

When I enter the server, I get kicked out of the server, and I get the error mentioned above because I have spawners in that world, if I change world I don't get kicked out.

### Expected Behavior

not kicked

### Additional Server Info

do not use bungeecord, is an individual server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--318%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--318%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.7-SNAPSHOT): 7 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.7--SNAPSHOT)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.2): 6 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.2)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
