### ISSUE TITLE
Cannot Log into Server with Viaversion

### ISSUE THREAD

**Issue by RealBeadle** [ViaVersion/ViaVersion#3798]
### `/viaversion dump` Output

https://dump.viaversion.com/b5c441722ce0516b53fa670ab59ba8a0414724c37e3e7d190951c7fc8b5b2b71

### Console Error

https://mclo.gs/5dT0KLW

### Bug Description

I cannot log in, I get this error message which says to report on Github: 
https://gyazo.com/0c3de98370981aea709a33db288b552e

### Steps to Reproduce

Log in, it was working before adding plugins but I am not sure what plugin it would be and why?

### Expected Behavior

I expected to log in

### Additional Server Info

viaversion dump
[19:37:50 INFO]: We've made a dump with useful information, report your issue and provide this url: https://dump.viaversion.com/b5c441722ce0516b53fa670ab59ba8a0414724c37e3e7d190951c7fc8b5b2b71

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--489%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--489%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.6): 14 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.6)-14%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.2): 6 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.2)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Kichura** [comment]
Update GrimAC, if this fails then a binary search would be needed.

**Comment by RealBeadle** [comment]
Removed grimac and eglow and I can connect. It has nothing to do with via version I don't think. Please delete this issue as it is not via versions fault!

**Comment by Kichura** [comment]
> Removed grimac and eglow and I can connect. It has nothing to do with via version I don't think. Please delete this issue as it is not via versions fault!

I'm sorry RealBeadle, I'm afraid I can't do that.
*(Space odyssey reference but i actually can't delete issues cuz not a maintainer)*
