### ISSUE TITLE
Cannot connect to 1.8.8 server from 1.12 client

### ISSUE THREAD

**Issue by catfoolyou** [ViaVersion/ViaVersion#3803]
### `/viaversion dump` Output

 https://dump.viaversion.com/852603c72309e4d21165ff51fd4e5c10f0b493b64d29fba70a094ded778415ad

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

After installing ViaVersion my server still says "Outdated server. I'm still on 1.8.8" despite the fact that I have Viaversion installed and  configured to work with the correct versions.

### Steps to Reproduce

Using this client [here](https://github.com/catfoolyou/Eaglercraft-1.12-Desktop-Runtime) and this server [here](https://github.com/Proofr/EaglercraftX-Server) the above described error happen when trying to connect.

### Expected Behavior

Client should connect to server as expected.

### Additional Server Info

I am using BungeeCord and EaglerXBungee of the latest versions

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Af6069e2%3A513](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Af6069e2%3A513-3498db?style=flat-square) </br>![Proxy is 999 builds behind](https://img.shields.io/badge/Your%20proxy%20is%20999%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.9.3): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by catfoolyou** [comment]
Updated to latest snapshot, dump here:  https://dump.viaversion.com/0ab8737f55dcc283f723372891d6034afec777703bd1b8cc9aded9e7c11b5176

**Comment by Kichura** [comment]
Your waterfall proxy is extremely old and must be updated.
