### ISSUE TITLE
Client fails to decode level_chunk_with_light packet on 1.20.5

### ISSUE THREAD

**Issue by Patbox** [ViaVersion/ViaVersion#3804]
### `/viaversion dump` Output

https://dump.viaversion.com/0ab40e50044bcb7d5c69fb17c9d664c3560b3f679a12047bc42a9479d7d3862d

### Console Error

No logs.

### Bug Description

Try to connect to the server with ViaVersion on velocity proxy.
Get disconnected with.
![image](https://github.com/ViaVersion/ViaVersion/assets/39821509/5e1ddbf4-f0ef-4fc5-92d4-df6ed221833c)

### Steps to Reproduce

1. Try to join the server with 1.20.5 client.
2. See the disconnect screen.

### Expected Behavior

This issue not happening

### Additional Server Info

Backend server runs on 1.20.4 with Fabric, without any issues when connecting with vanilla 1.20.4 client. Server is running with polymer, it which keeps modded block entities within chunk data, as it doesn't cause issues on vanilla 1.20.4 clients (and allows for client-optional mods to work with it).

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--a9a31f69--b385%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--a9a31f69--b385%29-3498db?style=flat-square) </br>![ViaVersion (4.10.0): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.0)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by D1SR3G4RD** [comment]
Having the same issue with 1.20.5/6 vanilla clients when using limbo software replicating 1.20.1

**Comment by Adamsmashem** [comment]
It seems setting `"always_remove_polymer_block_entities": true` fixes this (or at least helps), though I dont know how this affects how polymer works. I still get a `clientbound/minecraft:block_entity_data` error when **placing** a computer or it seems anything from Polymer Patch for CC when on 1.20.6 connecting to a 1.20.4 server. However I can relog and everything seems to work

**Comment by kennytv** [comment]
The fix in ViaVersion would do the exact same by just removing unknown block entities. 1.20.5 clients no longer accept these at all

**Comment by SenkJu** [comment]
Just wanted to let you know that this issue is making ViaFabricPlus almost useless at the moment. I don't think marking this as a 'low priority' issue is appropriate.
