### ISSUE TITLE
NoClassDefFound Exception

### ISSUE THREAD

**Issue by ChefMC** [ViaVersion/ViaVersion#3805]
### `/viaversion dump` Output

Seems like in Jenkins snapshots problem is fixed ✅. 
But official (PUBLIC RELEASE) version is broken. You should turn working snapshot into public release.
Releases should not be broken, otherwise it isn't release and it will cause running problem (which people will post here).

### Console Error

https://mclo.gs/uGRDbQV

### Bug Description

Via\* plugins:

![image](https://github.com/ViaVersion/ViaVersion/assets/3519015/a336cb82-3670-47c3-8d21-0e5f1fa104f1)

Error:

![image](https://github.com/ViaVersion/ViaVersion/assets/3519015/3672962a-3a2b-4b96-942f-48b2ae942dbd)

### Steps to Reproduce

1. Install the plugins
![image](https://github.com/ViaVersion/ViaVersion/assets/3519015/07cd31ff-da92-4f2c-b8f8-0907fcd1ef26)

2. Start server and view console

### Expected Behavior

Plugin should be enabled

### Additional Server Info

I also use Velocity 3.3.0-385 (I **don't** have Via\* plugins on it)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
See https://hangar.papermc.io/ViaVersion/ViaBackwards
