### ISSUE TITLE
CommandWriter fails to convert on Fabric 1.20.4 server to 1.20.5 client

### ISSUE THREAD

**Issue by Patbox** [ViaVersion/ViaVersion#3806]
### `/viaversion dump` Output

https://dump.viaversion.com/84d3aef36b7ef26581108713855eb051207c1f41f9fb0195bf8b176a87d4b44e

### Console Error

https://mclo.gs/rFA3zlS

### Bug Description

![image](https://github.com/ViaVersion/ViaVersion/assets/39821509/b655b4da-7261-482d-a065-79cc886513e6)

### Steps to Reproduce

1. Try to join
2. Fail miserably

### Expected Behavior

Being able to connect

### Additional Server Info

Server is running on 1.20.4 Fabric with Polymer and PolyMc mods. It is fully playable and compatible with 1.20.4 vanilla clients.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.4.14+67--main](https://img.shields.io/badge/Platform-0.4.14+67--main-3498db?style=flat-square) </br>![ViaVersion (4.10.1-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.1--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Patbox** [comment]
https://dump.viaversion.com/84d3aef36b7ef26581108713855eb051207c1f41f9fb0195bf8b176a87d4b44e

**Comment by Barvalg** [comment]
![Platform: 0.4.14+67--main](https://img.shields.io/badge/Platform-0.4.14+67--main-3498db?style=flat-square) </br>![ViaVersion (4.10.1-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.1--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by kennytv** [comment]
ViaVersion cannot process modified registries it doesn't know about. This would either need Fabric specific platform handling or modifying the mapping files <https://github.com/ViaVersion/Mappings>

**Comment by Patbox** [comment]
ViaVersion shouldn't really require that, as packet data sent to the client is already filtered out / fully compatible with vanilla clients. Is this case of ViaFabric using registries directly and passing them to ViaVersion?

**Comment by kennytv** [comment]
Okay I didn't know the client ignored invalid ids. Though ids shift and have to be mapped, so without knowing the actual mappings, the best we could do is shift the unknown id relative to where it was out of bounds. That would assume your custom ones are still added to the tail in the exact same order still with nothing new inbetween

**Comment by kennytv** [comment]
Please see whether the linked commit fixes it once built

**Comment by Patbox** [comment]
Yep this solved the issue. Thanks!
