### ISSUE TITLE
ViaVersion Raised Two Errors When Using With Geyser and Failed the Connection

### ISSUE THREAD

**Issue by Na3MnO4** [ViaVersion/ViaVersion#3807]
### `/viaversion dump` Output

https://dump.viaversion.com/4e23375cf5ac4b0692304ebac4418d5f4d4307aa0c4c976b7b9d02c0e87aa6c0

### Console Error

[latest.log](https://github.com/ViaVersion/ViaVersion/files/15137982/latest.log)
Too long to paste into https://mclo.gs/ I think.

### Bug Description

These days I'm trying to use Geyser for support of BE Client. But immediately after the player click done on the geyser verification screen and began connecting to the server, massive error log displayed on the velocity console, and the player failed to connect with the error "Your connection to lobby encountered a problem."

I have tried all the latest things (Velocity, Via*, Geyser, BE Client), which are:
Velocity 385
Geyser 2.3.3
Via* 4.10.0+3.1.0

The log told me to report the bug here, here is the incomplete excerpt:
```
[19:05:01] [Netty NIO Worker #10/ERROR] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] AmethystineENDzZ -> lobby: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@6bf2b90d
io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
```

### Steps to Reproduce

1. Start a latest Velocity  with latest Via* and latest Geyser
2. Connect the Velocity to a JE Fabric 1.16.5 Server
3. Attempt to join the server with the latest BE Client
4. Failed to connect

### Expected Behavior

Successfully connected.

### Additional Server Info

![image](https://github.com/ViaVersion/ViaVersion/assets/69727714/970b7ca4-b32f-4461-8127-cb1e05104c57)
Fabric mod on the server side as additional infomation.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--a9a31f69--b385%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--a9a31f69--b385%29-3498db?style=flat-square) </br>![ViaVersion (4.10.0): 5 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.0)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.0)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.1.0): 2 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.1.0)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Kichura** [comment]
Carpet and Syncmatica are unsupported, Use ViaVanillaPlus to try and resolve it. *(although the latter of which only works with 1.20.2 - 1.20.4 fabric servers atm)*
