### ISSUE TITLE
Placing brick stairs is not possible

### ISSUE THREAD

**Issue by paaulhier** [ViaVersion/ViaVersion#3809]
### `/viaversion dump` Output

https://dump.viaversion.com/03ee4e19b35fba0b0ca797b277b58925f6c99eff76ad70e937aea578f2983b19

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

If you are playing with the minecraft version 1.20.1 on a 1.20.3/1.20.4 server, it is not possible to place brick stairs.

### Steps to Reproduce

Login with a 1.20.1 client
take brick stairs out of the inventory
place the brick stairs

### Expected Behavior

Blocks should be placed

### Additional Server Info

Joining via Velocity 3.3.0-SNAPSHOT (git-9e42049a-b376)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--49%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Pufferfish--49%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.0): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.0)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.0): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.0)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
