### ISSUE TITLE
Unable to grab viaversion client version

### ISSUE THREAD

**Issue by EquipableMC** [ViaVersion/ViaVersion#3810]
### `/viaversion dump` Output

returns incorrect argument

### Console Error

```
[packetevents] Unable to grab ViaVersion client version for player!
```

### Bug Description

just spams it in console

### Steps to Reproduce

1. use 1.19.4 purpur
2. use viaversion 4.10.0 & viabackwards 4.10.0
3. start the server
4. it should send a message every so often saying that

### Expected Behavior

not spam this message at all

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by EquipableMC** [comment]
![image](https://github.com/ViaVersion/ViaVersion/assets/66171067/2126cba9-cbe4-4562-a51e-156c74d4485b)

**Comment by Kichura** [comment]
Caused by third-party plugins having outdated packetevents library active, meaning this is not a viaversion issue.

**Comment by EquipableMC** [comment]
I dont know WHAT 3rd party packevents cause it. None I use should cause it

**Comment by EquipableMC** [comment]
> Caused by third-party plugins having outdated packetevents library active, meaning this is not a viaversion issue.

worked fine before I updated.

**Comment by Kichura** [comment]
In case you are not sure which plugin is causing the problem, You can scan your plugins folder by either running [this powershell script](https://pastebin.com/raw/h6DqTzxB) on Windows or [this bash script](https://pastebin.com/raw/WZWjimgM) on macOS/Linux instead.

**Comment by EquipableMC** [comment]
> In case you are not sure which plugin is causing the problem, You can scan your plugins folder by either running [this powershell script](https://pastebin.com/raw/h6DqTzxB) on Windows or [this bash script](https://pastebin.com/raw/WZWjimgM) on macOS/Linux instead.

i dont got access to my friends machine, and it isnt localhost.

**Comment by Kichura** [comment]
> > In case you are not sure which plugin is causing the problem, You can scan your plugins folder by either running [this powershell script](https://pastebin.com/raw/h6DqTzxB) on Windows or [this bash script](https://pastebin.com/raw/WZWjimgM) on macOS/Linux instead.
> 
> i dont got access to my friends machine, and it isnt localhost.

Then you will have to ask your friend to scan the plugins for you - If it outputs nothing after running one of the two scripts in the plugins folder then the plugins don't have it or have the library relocated to something not identifiable. *(latter of which would be ugly)*
