### ISSUE TITLE
[packetevents] Unable to grab ViaVersion client version for player!

### ISSUE THREAD

**Issue by smscentras** [ViaVersion/ViaVersion#3813]
### `/viaversion dump` Output

ViaVersion-4.10.1-SNAPSHOT

### Console Error

```
https://mclo.gs/ebOhTD5
```

### Bug Description

All have this problem, all internet talking about that..

### Steps to Reproduce

Allways same error - in every 10 second..

### Expected Behavior

Allways same error - in every 10 second..

### Additional Server Info

No BungeeCord, just latest PurPur.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
This is a packetevents issue, update your plugins. Join our Discord if you need further assistance
