### ISSUE TITLE
Players unable to login

### ISSUE THREAD

**Issue by jurohn** [ViaVersion/ViaVersion#3815]
### `/viaversion dump` Output

https://dump.viaversion.com/5cfbb6df6a49dbb67bfd4ce845731dee8fb319ad44e5d4854ebd1dea9669e97e

### Console Error

[[(https://mclo.gs/N68T12j)](https://mclo.gs/N68T12j)](https://mclo.gs/N68T12j)

### Bug Description

Players can not login to my minecraft server

### Steps to Reproduce

1. Login with 1.20.4 fabric to a paper 1.20.6 dev version (newest)

### Expected Behavior

It should be working?

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--28%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-git--Paper--28%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (4.10.1-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.1--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.1-SNAPSHOT): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.1--SNAPSHOT)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
