### ISSUE TITLE
Players are unable to login

### ISSUE THREAD

**Issue by jurohn** [ViaVersion/ViaVersion#3816]
### `/viaversion dump` Output

https://dump.viaversion.com/6b03797cfcd019ff8a81150d0ddb18fae16b5b7e11842fc3fb797e30dbd80a73

### Console Error

(https://mclo.gs/G8kpPQN)](https://mclo.gs/G8kpPQN)

### Bug Description

Players can not login to my paper server

### Steps to Reproduce

1. Login with fabric 1.20.4 on my server.
Paper 1.20.6 latest dev.

### Expected Behavior

To let it work

### Additional Server Info

User error:
https://imgur.com/a/1rZFddT

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--28%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-git--Paper--28%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (4.10.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by jurohn** [comment]
@kennytv You are such a great programmer. Great respect.
