### ISSUE TITLE
[1.8.8] Failed to send death message

### ISSUE THREAD

**Issue by HowardZHY** [ViaVersion/ViaVersion#3817]
### `/viaversion dump` Output

[ViaVersion] Failed to capture further info java.net.ConnectException: Connection timed out: connect

### Console Error

https://mclo.gs/rLs4rl2

### Bug Description

Player death on Paper 1.8.8 caused console errors.

### Steps to Reproduce

Latest Via 4.10.1-Snapshot, Paper 1.8.8, no other plugins
Join the game
/kill
error on console

### Expected Behavior

no error message

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by HowardZHY** [comment]
https://dump.viaversion.com/c92b933772b60cce6a19dd8f6114ce26e67f3dab8463ff6dcecabbc5f2c3789d

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--445%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.10.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
