### ISSUE TITLE
Don't connection for server 1.20.1 version

### ISSUE THREAD

**Issue by Freddereck** [ViaVersion/ViaVersion#3818]
### `/viaversion dump` Output

https://dump.viaversion.com/daabd1ba4ca323bde1311df48f268ad075509c95db741cbbe94766fe3d50d48f

### Console Error

[[```
[[Put the mclo.gs link or text here.](https://mclo.gs/bMPdpCY)]
```
]

### Bug Description

Connect to server 

### Steps to Reproduce

Login 1.20.1
connect server
error

### Expected Behavior

connect to the server from minecraft version 1.20.1

### Additional Server Info

velocity 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--75d6dcc1--b371%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--75d6dcc1--b371%29-3498db?style=flat-square) </br>![Proxy is 15 builds behind](https://img.shields.io/badge/Your%20proxy%20is%2015%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.10.0): 16 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.0)-16%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.0): 11 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.0)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>proxy_limbo</details>
