### ISSUE TITLE
shulker tooltip

### ISSUE THREAD

**Issue by ahshqhir** [ViaVersion/ViaVersion#3822]
### `/viaversion dump` Output

https://dump.viaversion.com/615f030c0fb7e80bfbd00867679a51c4ad07dedd1815e62e73793c786a88fe21

### Bug Description

1.20.6 server doesn't send shulker contents nbt data to older versions
also "/viaversion dump" still not working in fabric

### Steps to Reproduce

1.join a 1.20.6 server with 1.20.1 client
2.fill a shulker box with some items
3.get the shulker box into your invenrtory
4.check it's tooltip

### Expected Behavior

shulkerbox tooltip must contain list of contents

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 4141--Spigot--e2c1eee--66fd943%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-4141--Spigot--e2c1eee--66fd943%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (4.10.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.1-SNAPSHOT): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.1--SNAPSHOT)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by kennytv** [comment]
This is known but will take some time, as with all other hovers
