### ISSUE TITLE
Entity Sound Pakage Error

### ISSUE THREAD

**Issue by Slime1207** [ViaVersion/ViaVersion#3824]
### `/viaversion dump` Output

https://dump.viaversion.com/cba428751a0fb8a0e3743c5c84366043016c5b559c8ce6c3de95ae42a70f1db6

### Console Error

https://mclo.gs/N0F1dAO

### Bug Description

Go to a new chunk (Maybe) or join the server.

### Steps to Reproduce

1. When I use rtp to teleport to a place
2. Disconnected because of this
3. Re-joining server
4. Cannot join becouse of the Same error

### Expected Behavior

Being kicked

### Additional Server Info

No Bungeecord.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Leaves--%22847357b%22%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Leaves--%22847357b%22%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.10.0--24w09a--SNAPSHOT)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.10.0--24w09a--SNAPSHOT)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
