### ISSUE TITLE
1.20.5 to 1.20.4 server connection error

### ISSUE THREAD

**Issue by blackdllx** [ViaVersion/ViaVersion#3826]
### `/viaversion dump` Output

https://dump.viaversion.com/d31ef738eec885d17a1b764dec237a91fc19f299dda8e31ecc98cceb2d87b0c5

### Console Error

```
[Put the mclo.gs link or text here.](https://mclo.gs/BI8HMM0)
```

### Bug Description

Error while connecting to 1.20.4 server throw velocity proxy(plugin is install on both proxy and server) from 1.20.5 client. Got some errors in proxy console and error on client Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:game_profile'
![Снимок экрана 2024-05-04 235342](https://github.com/ViaVersion/ViaVersion/assets/80413107/55f10a6f-9391-462f-9893-b5d5a3f275ed)

### Steps to Reproduce

1. Setup velocity proxy with viaVesion plugin and paper 1.20.4 server
2. Join from 1.20.5 client

### Expected Behavior

Player with 1.20.5 client should connect normaly

### Additional Server Info

Velocity plugins:
- LuckPerms-Velocity-5.4.122.jar 
- MCKotlinVelocity-1.4.0-k1.9.21.jar 
- ViaVersion-4.10.1-SNAPSHOT.jar 
- limboapi-1.1.22.jar 
- limboauth-1.1.14-SNAPSHOT.jar
- voicechat-velocity-2.5.12.jar 
Paper server plugins:
- AxiomPaper-1.5.9.jar 
- SimplePortals-1.7.5.jar
- SkinsRestorer.jar
- voicechat-bukkit-2.5.10.jar
- worldedit-bukkit-7.3.0.jar 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--9e42049a--b376%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--9e42049a--b376%29-3498db?style=flat-square) </br>![Proxy is 13 builds behind](https://img.shields.io/badge/Your%20proxy%20is%2013%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.10.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
ViaVersion does not support limbo-related plugins, Please move them to the spigot/paper servers instead.
