### ISSUE TITLE
Network Protocol Error

### ISSUE THREAD

**Issue by Xayanix** [ViaVersion/ViaVersion#3828]
### `/viaversion dump` Output

https://dump.viaversion.com/a26e57de31be31a4f92497c70df7aa6fb52687a35bef60872e2ccaff45f55317

### Console Error

No errors in console.

### Bug Description

Sometimes (quite often) i got kicked from server with this error:
![image](https://github.com/ViaVersion/ViaVersion/assets/12672902/72c73181-f3d6-446f-82a9-aaf2866c7ae1)

It happens only on 1.20.5 - 1.20.6

### Steps to Reproduce

Happens randomly

### Expected Behavior

Obv

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--UniverseSpigot--%22f777766%22%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--UniverseSpigot--%22f777766%22%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.10.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.1.1): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by kennytv** [comment]
Update tab

**Comment by Xayanix** [comment]
> Update tab

Thanks :)

**Comment by Xayanix** [comment]
meh, updated it and it still kicks

**Comment by k-jiang** [comment]
We have encountered the same issue when joining 1.20.1 with 1.20.5/6.

This issue only happens on certain area of the map. When `/tp` to those area, the client disconnected instantly with "Network Protocol Error". Perhaps it is due to some entities / blocks?

Tested with:
ViaVersion - 4.10.3 build 846
ViaBackward - 5.0.0 build 615

**Comment by kennytv** [comment]
Don't mix dev and non-dev versions. In general, that error means you've got a plugin sending bad entity or scoreboard data, you'd have to remove plugins until it doesn't happen anymore to see which one it is
