### ISSUE TITLE
Network Protocol Error

### ISSUE THREAD

**Issue by Xayanix** [ViaVersion/ViaVersion#3829]
### `/viaversion dump` Output

https://dump.viaversion.com/7db8bf1558644b2d0eebff69d6d77320f145e351038f8372d17d1cfefb604f16

### Console Error

No errors in console.

### Bug Description

Sometimes (quite often) i got kicked from server with this error:
![image](https://github.com/ViaVersion/ViaVersion/assets/12672902/12d34a38-ca5b-4e1e-a02d-642cbc2db1c6)
It happens only on 1.20.5 - 1.20.6

### Steps to Reproduce

Happens randomly

### Expected Behavior

Obv

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--UniverseSpigot--%22f777766%22%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--UniverseSpigot--%22f777766%22%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.1.1): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Check your other plugins as well, this means you have a scoreboard/tab plugin sending bad data

**Comment by DropExitJoin** [comment]
I also noticed issue that on my 1.20.4 server players from 1.20.6 get kicked when they lose potion effect
