### ISSUE TITLE
Since #831 there are black entity effect particles after world change

### ISSUE THREAD

**Issue by MrKinau** [ViaVersion/ViaVersion#3832]
### `/viaversion dump` Output

https://paste.cytooxien.de/aguxawojen.json

### Bug Description

After changing the world (e.g. walking through a nether portal), you'll get black entity effect particles (using 1.20.6 on 1.20.3/4 server)

### Steps to Reproduce

1. Go through a nether portal
2. See you have entity effect particles with black color

### Expected Behavior

There shouldn't be any entity effect particles at your player, unless you have effects applied.

### Additional Server Info

This bug appears since build [#831](https://ci.viaversion.com/job/ViaVersion/831/)
ig, this commit introduced this https://github.com/ViaVersion/ViaVersion/commit/a8d7ab62e3ae0498e10d3637dc8bb55572e5ec2d

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by MrKinau** [comment]
![image](https://github.com/ViaVersion/ViaVersion/assets/13185260/5102761f-46af-4dd6-a39f-ad7d4d29005c)
I took a picture of me, in front of a nether portal with this black entity effect particles :)
