### ISSUE TITLE
Sculk Shrieker glitch

### ISSUE THREAD

**Issue by Envqu** [ViaVersion/ViaVersion#3833]
### `/viaversion dump` Output

https://dump.viaversion.com/2a3fcba41d0fd529ff57c8e11eaf363a2e357b56e1ddcef59eda4d7f5bdca8c6

### Bug Description

It is possible to change Sculk Shrieker hitbox to any slab instead end portal frame? Because end portal is a bit higher and players glitching and triggering antycheat. There is no problem with Sculk Sensor changed into slab. 

### Steps to Reproduce

Stand on Sculk Shrieker

### Expected Behavior

Sculk Shrieker should be changed into any slab instead portal frame because portal frame has bigger hitbox.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1985%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Purpur--1985%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.9.3)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.9.2)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
