### ISSUE TITLE
1.20.6 Players cannot interact with fireballs on 1.20.4 server

### ISSUE THREAD

**Issue by hraponssi** [ViaVersion/ViaVersion#3839]
### `/viaversion dump` Output

https://dump.viaversion.com/fa4aa59409ef771eaf5d2b284868204d6f780cab2555777b069ae05f74aa3524

### Bug Description

Players on 1.20.6 cannot punch fireballs on a 1.20.4 server. 1.20.4 players have no issues punching the fireballs, but a 1.20.6 player just punches through them.

### Steps to Reproduce

1. Set up a 1.20.4 server with viaversion
2. Log on with a 1.20.6 client
3. Summon a fireball with /summon minecraft:fireball ~ ~ ~
4. Try to punch the fireball
5. The fireball is not punched, and does not react

### Expected Behavior

The fireball should be punched, sending it flying.

### Additional Server Info

My test server has a waterfall proxy with just some command plugins, and the backend server is using paper. The server has minimal plugins for testing this.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--496%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--496%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.2)-Even%20with%20master-brightgreen?style=flat-square) </br>
