### ISSUE TITLE
ERROR IN Protocol1_20_3To1_20_2 IN REMAP OF TAB_COMPLETE (0x10)

### ISSUE THREAD

**Issue by bieelsiurr** [ViaVersion/ViaVersion#3840]
### `/viaversion dump` Output

https://dump.viaversion.com/6fcc83aff0efd8cd8de3eb8c2f3718b73f9c67ce6c9cbda7f49756447f403b2d

### Console Error

```
[Put the mclo.gs link or text here.](https://mclo.gs/yE6XXlc)
```

### Bug Description

Sometimes when a player join, server kicks him for "Can't serialize unregistered packets", and the console only throws 1 error and a warn from ViaVersion

```
[12:41:01 ERROR]: [ViaVersion] Error when trying to parse json:``
[12:41:01 WARN]: [ViaVersion] ERROR IN Protocol1_20_3To1_20_2 IN REMAP OF TAB_COMPLETE (0x10)
```

### Steps to Reproduce

1. Connect the server
2. Player gets kicked

### Expected Behavior

The player should not be kicked

### Additional Server Info

I also use a Velocity proxy. Server that I'm getting kicked is a lobby server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--196%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--196%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.2)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
From the discord: I have test-ran both paper 1.20.1 with and without velocity active and with the same plugins active on the paper server *(excluding timocloud and spigotcore)* and the issue could not be reproduced. This is most likely caused by misconfigured server itself or a bad third-party plugin of some sort.
