### ISSUE TITLE
Error Console

### ISSUE THREAD

**Issue by TylorTurner** [ViaVersion/ViaVersion#3845]
### `/viaversion dump` Output

https://dump.viaversion.com/6cd639062efa30d365330cd15c2554dc1d4d847675b05a483f6ef98505312fe4

### Console Error

(https://mclo.gs/VsMW7Vm)
```


### Bug Description

![image](https://github.com/ViaVersion/ViaVersion/assets/133236597/a8f9fed8-c1b4-450f-ab1b-694321e0942c)
![image](https://github.com/ViaVersion/ViaVersion/assets/133236597/d54f43d7-caec-4c26-946e-dcf3b346a628)


### Steps to Reproduce

idk

### Expected Behavior

idk

### Additional Server Info

_No response_

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2176%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--2176%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.2)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by kennytv** [comment]
You most likely have a plugin sending bad entity data
