### ISSUE TITLE
Minecraft is bugging in version 1.8

### ISSUE THREAD

**Issue by DanRubMaster** [ViaVersion/ViaVersion#3848]
### `/viaversion dump` Output

https://dump.viaversion.com/af3ae3d431f04b27260789f79c8231df1268817684782b652165f9b19e6ff835

### Console Error

```
https://mclo.gs/pGCL08I
```
(I know about the bungeeonlinetime error, i just forgot to removed it, but its really not because of it.)

### Bug Description

I have a 1.19.4 server and everytime when i join with version from 1.8 to 1.8.9 everything works fine UNTIL player dies, when player dies for the first time since player connect to the server, the minecraft is really bugging and its hardly playble. There you have 2 videos about the bugging. You can see that im bugging at the edges of blocks, when im placing blocks to "me" the block is placing but then remove immediately, also you can see that the blocks are removing from the inventory, but then when i place the block right to empty space, the blocks are given to me right away.. There is many bugs like this..
VIDEO 1: https://medal.tv/games/minecraft/clips/2bsjUp-KlL21hC/d13374AcMKzh?invite=cr-MSxJNVIsMTc0Njc4MDIyLA
VIDEO 2: https://medal.tv/games/minecraft/clips/2cXngcj3m4cXMZ/d13375XIeYEJ?invite=cr-MSxvUHAsMTc0Njc4MDIyLA

### Steps to Reproduce

1. Login with minecraft version from 1.8 - 1.8.9
2. Die (in minecraft)
3. and that should be it, its all i have done

### Expected Behavior

The edges should not be bugging, block should work normally and minecraft should be playable.

### Additional Server Info

Im using Proxy - Velocity
Plugins: advancedserverlist, cleanstaffchat, craftingstore, easycommandblocker, enhancedvelocity, fastlogin, litebans, logger-velocity, luckperms, maintenance, miniplaceholders, premiumvanish, protocolize, protocolizelegacysupport, send, skinsrestorer, slashhub

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--550%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--550%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.2)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.1.2): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.2)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by kennytv** [comment]
Also the wrong repo
