### ISSUE TITLE
1.20 server shows up as a void on clients older than 1.16.5

### ISSUE THREAD

**Issue by Clyde-Timonera** [ViaVersion/ViaVersion#3857]
### `/viaversion dump` Output

https://dump.viaversion.com/53a54a23c48baa901f660c72bec9526ff29d28edaff160cfba11062f031ce6b0

### Console Error

No Errors related to ViaVersion and all Warnings are all about Geyser Prefix warnings.

### Bug Description

On Older clients like 1.16.5, the player gets stuck in a void and cannot move but entities, some structures, and other players are visible.
![image](https://github.com/ViaVersion/ViaVersion/assets/78290310/d8a22e2f-a7b9-4221-834b-87561043a33c)
![image](https://github.com/ViaVersion/ViaVersion/assets/78290310/dfdec93b-c0e1-4f76-98a7-e5023c25a353)

### Steps to Reproduce

1. Login with a client lower than version 1.16.5
2. Try to move
3. Client refuses to function correctly.

### Expected Behavior

World should be not empty and free to explore for the player.

### Additional Server Info

I use Playit.gg with paper and the following plugins are active: Atollo, Chunky, CoreProtect, CrazyEnchantments, FAWE, Floodgate, Geyser, TPA, ViaVersion, ViaRewind, ViaBackwards, ViaRewind-Legacy-Support, 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--496%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--496%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.1.2): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.2)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Kichura** [comment]
Not fixable. Either upgrade your client to 1.17+ or put your server back to 1.17.1. *(in case the world save is temporarily)*
