### ISSUE TITLE
1.20.6 Unpaired Lodestone Compass bug

### ISSUE THREAD

**Issue by Pantera07** [ViaVersion/ViaVersion#3861]
### `/viaversion dump` Output

https://dump.viaversion.com/4b74e8cdc353b2ffe34a94f836a2ab79cc1a863af58d28d0259617497929be15

### Console Error

none

### Bug Description

Unpaired Lodestone Compass is displayed as a regular compass.

**1.20.4 Server** & 1.20.6 Client **(Issue)**:
![image](https://github.com/ViaVersion/ViaVersion/assets/89838384/a16bbea1-647e-436a-87e5-c0f55cb7b632)

**1.20.6 Server** & 1.20.6 Client:
![image](https://github.com/ViaVersion/ViaVersion/assets/89838384/7629bcd5-eab9-4f92-a02d-c986c34aa110)

### Steps to Reproduce

1. Server Join (1.20.4 Server & 1.20.6 Client)
2. Place Lodestone
3. Pairing Compass
4. Break Lodestone

### Expected Behavior

Lodestone Compass should be well displayed.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--496%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--496%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Checkout https://github.com/ViaVersion/ViaVersion/pull/3862
