### ISSUE TITLE
1.20.6 clients kicked from 1.20.4 server for network protocol error (packets)

### ISSUE THREAD

**Issue by Projecki** [ViaVersion/ViaVersion#3863]
### `/viaversion dump` Output

https://dump.viaversion.com/81811642c9bff302235f6598115429328677443612f48d53066e82f9ed47796c

### Console Error

none

### Bug Description

A player is being kicked for "Network Protocol Error" when visiting our spawn warp

### Steps to Reproduce

1. Log in with 1.20.6 client
2. Go to our /spawn
3. kicked for Network Protocol Error

### Expected Behavior

Can play without kick

### Additional Server Info

[2024-05-18-7.log](https://github.com/ViaVersion/ViaVersion/files/15366728/2024-05-18-7.log)
Client logs from user experiencing the issue
I believe this is the relevant packet: https://wagyourtail.xyz/Projects/MinecraftMappingViewer/App?version=1.20.6&mapping=MOJMAP&search=afn

Relevant log?: 
Invalid entity data item type for field 17 on entity cfv['Ocelot'/270, l='ClientLevel', x=-9.27, y=84.00, z=-31.75]: old=false(class java.lang.Boolean), new=1(class java.lang.Byte)

Failed to handle packet afn[id=270, packedItems=[c[id=17, serializer=akl$$Lambda/0x000000010077efe0@e4e39a0, value=1], c[id=6, serializer=akl$$Lambda/0x000000010077efe0@1b10963a, value=CROAKING]]]

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Axolotl--%22f6ab75f%22%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Axolotl--%22f6ab75f%22%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by FlorianMichael** [comment]
Seems to be related to wrong entity data (metadata).

**Comment by kennytv** [comment]
Most likely the fault of another plugin

**Comment by Projecki** [comment]
can confirm zNPCsPlus build #200 pushed yesterday fixed this issue, just tried it out

Was a few builds behind, was trying to diagnose this issue the past couple days.

Thank you guys 

https://ci.pyr.lol/job/ZNPCsPlus/200/

**Comment by Projecki** [comment]
Oh man I glance away for one second, nope got kicked again same packet.

I'll keep digging but continue this with zNPCPlus guys
