### ISSUE TITLE
Item tags for enchantments are not filled in properly for < 1.20.5 servers

### ISSUE THREAD

**Issue by Earthcomputer** [ViaVersion/ViaVersion#3865]
### `/viaversion dump` Output

com.viaversion.viaversion.util.DumpUtil$DumpException: Please wait before creating another dump

### Bug Description

Item tags that enchantments rely on to test their applicability on items are not properly sent to the client, resulting in any `Enchantment.canApply` call on the client to return false, which breaks client-side mods that may rely on this check.

### Steps to Reproduce

1. Install clientcommands and ViaFabricPlus
2. Open a world and try `/cenchant golden_sword with sharpness 5`
3. Observe an error message saying incompatible enchantment.

### Expected Behavior

Item tags should be properly sent to the client resulting in `Enchantment.canApply` working as expected.

### Additional Server Info

CarpetMod 1.12.2 server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by RaphiMC** [comment]
Fixed by https://github.com/ViaVersion/ViaVersion/commit/91f31b578f6f2a49eb3b85dd51282c473cbd151e
