### ISSUE TITLE
Sweeping edge is missing from item enchantment list

### ISSUE THREAD

**Issue by Earthcomputer** [ViaVersion/ViaVersion#3867]
### `/viaversion dump` Output

https://dump.viaversion.com/1fb1a939e171940b8fa3489a535f9ccf5441af6c66d34d77f23cc712531b5ece

### Bug Description

Sweeping edge swords don't display their enchantment on 1.20.5+ clients. This is likely because `minecraft:sweeping` was renamed to `minecraft:sweeping_edge`.

![image](https://github.com/ViaVersion/ViaVersion/assets/13084089/9c975683-f9c1-413a-b1df-8e4531223800)

### Steps to Reproduce

1. Login to a 1.12 server with a 1.20.6 client with VFP
2. Obtain a sword with sweeping edge
3. Observe that the sword visually doesn't have the sweeping edge enchant.

### Expected Behavior

The sword should properly display the sweeping edge enchantment when it has sweeping edge.

### Additional Server Info

Vanilla 1.12.1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3.0.0--SNAPSHOT](https://img.shields.io/badge/Platform-3.0.0--SNAPSHOT-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): 3 commits behind dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-3%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): 1 commits behind dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-1%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by kennytv** [comment]
Can't reproduce with Via on a server

**Comment by Earthcomputer** [comment]
Seems to be a VFP-only issue.

**Comment by FlorianMichael** [comment]
Fix provided in https://github.com/ViaVersion/ViaFabricPlus/commit/458b4daf15f86cf5afd475dba81116d2223a6220
