### ISSUE TITLE
Players on latest version(s?) don't fall off of a block when crouching on the edge

### ISSUE THREAD

**Issue by Censorr** [ViaVersion/ViaVersion#3870]
### `/viaversion dump` Output

https://dump.viaversion.com/800e69d5c993260dba746cd6b8b3b990d2ac80fb15587e000f83f7e3624cddb9

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

If a player is logged into the latest version(s?) of minecraft and then crouch on the edge of the block, hitting them causes them to not fall off the block.

### Steps to Reproduce

1. Log in with a 1.20.4+ (or possibly lower versions too) client
2. Crouch on the very edge of a block
3. Have another player punch you

https://github.com/ViaVersion/ViaVersion/assets/70301020/34f764e8-3696-40f3-b86a-d5bbada27f2e

### Expected Behavior

Player should be pushed off the block. Normal behavior can be viewed in lower versions such as 1.8.8 or while standing not on the very edge of a block.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--e39995d21%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--e39995d21%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.10.1--SNAPSHOT)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.10.1--SNAPSHOT)-Outdated!-red?style=flat-square) </br>![ViaRewind(3.1.2): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.2)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
