### ISSUE TITLE
MC 1.20.1 Server Kicks 1.8.9 Player, Times Out, or Crashes When Respawning After Falling in Void in Bed Wars Minigame

### ISSUE THREAD

**Issue by itsDevBlaze** [ViaVersion/ViaVersion#3872]
### `/viaversion dump` Output

https://dump.viaversion.com/b7c52b1102393ae42894690644bd18d0a76eb6f7a5fe55b61ff778291aed8a34

### Console Error

Example 1 of 1.20.1 server kicking 1.8.9 player after respawning in minigame using Master build: https://mclo.gs/Vt2AlcW
Example 2 of 1.20.1 server kicking 1.8.9 player after respawning in minigame using Master build: https://mclo.gs/XIiewP1

Example 1 of 1.20.1 server kicking 1.8.9 player after respawning in minigame using Dev build: https://mclo.gs/ttrpe7s
(The `/viaversion dump` was retrieved from this instance of the bug.)
Example 2 of 1.20.1 server kicking 1.8.9 player after respawning in minigame using Dev build: https://mclo.gs/0bPXX8K
Example 3 of 1.20.1 server kicking 1.8.9 player after respawning in minigame using Dev build: https://mclo.gs/a5mf8Hj

Example 1 of 1.20.1 server timing out after player respawned in minigame using Master build: https://mclo.gs/eK0ldxS
Example 2 of 1.20.1 server timing out after player respawned in minigame using Master build: https://mclo.gs/Q9lYi7D

Example of 1.20.1 server crashing after player respawned in minigame using Master build: https://mclo.gs/qq4eoX1

(Do note that some of these logs were copied directly from the console instead of the server log file.)

### Bug Description

Respawning in a Bed Wars minigame after falling into the void may cause the player's Minecraft 1.8.9 client to either get kicked, or for the MC 1.20.1 server to time out and crash. This bug could not be reproduced during standard PvP interactions in the minigame.

### Steps to Reproduce

1. Create a Bed Wars Paper 1.20.1 server using BedWars (ScreamingSandals), SBA (pronze, boiscljo), VoidSpawn (tcvs), and the three ViaVersion plugins. Some additional plugins may be needed, but those are likely the minimum ones required to reproduce this bug. Do note that this bug occurs both with and without VoidSpawn.
2. Connect to the server using a Minecraft 1.8.9 client and start the minigame - you can force the game to start with one person by setting `enable-cheat-command-for-admins` to `true` in BedWars's `config.yml`, and then running `/bw cheat startemptygame`.
3. Repeatedly fall into the void - one of three things will happen. Either the server will time out and crash the first time you fall into the void and respawn, or it will kick you after three void deaths, or it will take a random number of times to kick you (typically less than ten void deaths). Also, the armor slots appear to be misaligned client-side on older clients upon respawning (tested on Minecraft 1.8.9), but gets fixed when any slot (empty or not) is clicked on in the inventory - this is probably unrelated to the bug in question, and I don't intend to add two different bugs in one issue, but I figured I'd mention it in case it's related to or caused by this bug.

### Expected Behavior

The player should respawn after falling into the void without being kicked, or timing out and crashing the entire server.

### Additional Server Info

Everything currently runs in multiple worlds with Multiverse on one server (meaning that if the Bed Wars minigame causes ViaVersion to crash the server, the entire server goes down) - no proxy is in use at this time. The server runs Paper version git-Paper-196 (MC: 1.20.1), and the list of plugins is below:

BedWars, BetterInvisibility, BlueSlimeCore, Citizens, CommandItems, CooldownsX, DeluxeHub, *GodMode, *HealAll, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, LibsDisguises, MiniMOTD, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, NametagEdit, OldCombatMechanics, PowerRanks, ProtocolLib, SBA, *ServerChatMuter, *Spawn, SuperVanish, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, VoidSpawn, WorldBorder, WorldEdit, WorldEditTickSpreader

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--196%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--196%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(4.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(4.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>
