### ISSUE TITLE
[Dupe] Players are experiencing item delays.

### ISSUE THREAD

**Issue by caiobarnes** [ViaVersion/ViaVersion#3875]
### `/viaversion dump` Output

https://dump.viaversion.com/3a6b61ac218ce17092d058b263ef6a79850f9ba269e3b4a262abbcf091453987

### Console Error

No error in console.

### Bug Description

I use the SyncInv plugin which is multiserver with redis. my server is 1.20.4 and the plugin is compatible. however, when a player enters version 1.20.5 1.20.6 the player ends up experiencing a delay. I said dupe, because it rolls back items, not saving from one server to another. In other words, he can go to server 1 and give the items to his friend and then go to server 2 and duplicate them.

https://youtu.be/x0H6L0Ci9yQ

### Steps to Reproduce

So far there is no correct step, in principle it goes from one server to another.

### Expected Behavior

this doesn `t happen ;3

### Additional Server Info

I use bungeecord and redis system.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2176%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--2176%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.1.2): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.2)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
