### ISSUE TITLE
Fail to connect on older Velocity server with ViaVersion

### ISSUE THREAD

**Issue by rayhandestian** [ViaVersion/ViaVersion#3878]
### `/viaversion dump` Output

https://dump.viaversion.com/a789f768b65abd91d791b07bc1a92d47f29ff816aa15b0389c90bbcde16e7e17

### Console Error

```
[23:15:17 INFO]: [connected player] 1chikawa (/my-ip) has connected
[23:15:17 INFO]: [connected player] 1chikawa (/my-ip) has disconnected
```
![Screenshot 2024-05-26 221639](https://github.com/ViaVersion/ViaVersion/assets/120387648/64da8d9e-39da-4710-a935-65f37dce77c8)

### Bug Description

I cannot join on my older Velocity server with ViaVersion version `5.0.0-SNAPSHOT`, the same with `4.10.3-SNAPSHOT` and `4.10.2` (full release). The same with ViaBackwards, all obtained from hangar.papermc.io website. Velocity version is `3.3.0-SNAPSHOT-376` and I'm joining with Minecraft 1.20.6.

While using Minecraft 1.20.4 or lower does not have any issue at all.

It sends an error message on the client:
"Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:game_profile'"

The backend servers that player must go through are 3 servers, load balancer chose between these:
- Lobby-1 (1.18.2)
- Lobby-2 (1.18.2)
- Limbo (1.13.2)
But from the log I'm sure it did not connect me to any backend servers, just connected then disconnected.

### Steps to Reproduce

1. Start the Velocity server with the version I mentioned before, also the ViaVersion, with the rest of the plugins list can be seen at the dump link
2. Join the server with Minecraft 1.20.6

### Expected Behavior

Player using Minecraft 1.20.6 should be able to join.

### Additional Server Info

There are other plugins in the Velocity server, list can be seen at the dump link

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--9e42049a--b376%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--9e42049a--b376%29-3498db?style=flat-square) </br>![Proxy is 17 builds behind](https://img.shields.io/badge/Your%20proxy%20is%2017%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): 1 commits behind dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-1%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by rayhandestian** [comment]
Like I said, I did use the latest release version of the plugin, and then changed to the snapshots.

**Comment by Jo0001** [comment]
Please
- update your proxy itself
- provide the full error message (console)

Also what loadbalencer do you use?

**Comment by kennytv** [comment]
You most likely have another plugin sending a bad packet, likely on the proxy. Try updating your plugins (e.g. skinsrestorer) and otherwise do binary search on what is causing it

**Comment by rayhandestian** [comment]
I tried to update Velocity to the latest build (snapshot) from https://papermc.io/downloads/velocity , but I'm not sure why it won't let players connect to the proxy, there's probably some conflict with the plugins or something, so I decide to just use the previous Velocity version that worked.

There are no error message on the console, just this log like this:
```
[23:44:03 INFO]: [server connection] <other player> -> Lobby-Locke has connected
[23:44:03 INFO]: [server connection] <other player> -> Limbo has disconnected
[23:44:11 INFO]: [connected player] 1chikawa (/my ip) has connected
[23:44:11 INFO]: [connected player] 1chikawa (/my ip) has disconnected
[23:44:13 INFO]: [server connection] <other player> -> Survival has connected
[23:44:14 INFO]: [server connection] <other player> -> Lobby-Locke has disconnected
```
Nothing else in the log. And it's not just me, other players that tried to join the server with MC 1.20.6 as well.
And I'm afraid I can not provide the whole log file because it's a public server and have a lot of players currently.

The load balancer is just a plugin called FallbackServerVelocity

**Comment by rayhandestian** [comment]
> You most likely have another plugin sending a bad packet, likely on the proxy. Try updating your plugins (e.g. skinsrestorer) and otherwise do binary search on what is causing it

Ah, how did I not realise that, I'll try updating the plugins then, thank you.
