### ISSUE TITLE
Container set slot remapping is broken? 1.20.5->1.20.3

### ISSUE THREAD

**Issue by FlorianMichael** [ViaVersion/ViaVersion#3881]
### `/viaversion dump` Output

https://dump.viaversion.com/cdd2c3a5e3d228bd7370487df15bc63e6ab00d7ed2b379bc6fd69fed99e024b5

### Console Error

```
https://mclo.gs/Brevr9u
```

### Bug Description

Joining the server doesn't work because item rewriting is broken, see log files where more detailed errors are printed (Already deobfuscated MC Stacktraces, it's the item id itself being invalid)

### Steps to Reproduce

1. Run ViaFabricPlus or some other clientside/proxy Via platform with latest components
2. Select 1.20.4 or lower
3. Join eu.loyisa.cn (it's probably some item in my inventory, no idea)

### Expected Behavior

Joining should work

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3.0.0--SNAPSHOT](https://img.shields.io/badge/Platform-3.0.0--SNAPSHOT-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): Error fetching commit data](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-Error%20fetching%20commit%20data-lightgray?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>
