### ISSUE TITLE
Wrong ItemStack amounts shown in custom inventories [1.20.4 -> 1.20.6]

### ISSUE THREAD

**Issue by AoElite** [ViaVersion/ViaVersion#3882]
### `/viaversion dump` Output

https://dump.viaversion.com/b6a295b7588a29f49a46fb64f0f310cddbfb6e2ee4343e62f98a9af2c3048717

### Console Error

N/A

### Bug Description

When using a vanilla 1.20.6 client on a 1.20.4 server; ItemStacks that have more than it's max amount displays as it's vanilla max when set in a custom inventory. **Note that this does not happen when giving an item in a player's inventory just custom inventories it appears.**

![image](https://github.com/ViaVersion/ViaVersion/assets/20812471/531983aa-547d-45c9-a302-60fa6a63438a)

### Steps to Reproduce

1. Run a 1.20.4 server
2. Join on a 1.20.6 client
3. Use the code below
```java
        Player player = // get via command sender or something
        ItemStack itemStack = new ItemStack(Material.IRON_SWORD);
        itemStack.setAmount(64);
        Inventory inventory = Bukkit.createInventory(null, 54);
        inventory.setItem(1, itemStack);
        player.openInventory(inventory);
```

Outcome: ItemStack is rendered as 1 in the custom inventory

### Expected Behavior

![image](https://github.com/ViaVersion/ViaVersion/assets/20812471/785ae9a7-5104-4622-9548-4e828bfa246d)

ItemStack should be rendered as 64 when using the code above.

### Additional Server Info

Using paper 1.20.4 with 1.20.6 vanilla. Tried with both master/dev branches of via.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--496%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--496%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Problem seems to be that 1.20.4 accepts invalid data and still renders the item correctly while 1.20.5 validates for MAX_STACK_SIZE, I am thinking of just setting MAX_STACK_SIZE to the item amount to prevent that, unsure if it would break inventory actions (yet have to check how they even act in 1.20.4).
