### ISSUE TITLE
Trading with villagers that have Air as buyable/sellable item kicks player

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaVersion#3885]
### `/viaversion dump` Output

https://dump.viaversion.com/bf5a180b1ebff29cbd46e8cd312325cb09c6e86f4a4f9a5e6fad2189f2e97740

### Console Error

The kick logs can be found [here](https://pastebin.com/raw/EDr2X55B).

### Bug Description

When attempting to trade with any villager that buys or sells the item "Air" which is ID 0, the player will get kicked unlike 1.20.4 which displays the trading UI properly somehow.

### Steps to Reproduce

1. Make a new world in 1.20.4 paper,
2. Join the server with an 1.20.6 client,
3. Summon a new villager that either buys or sells Air as item,
4. Attempt to interact with the summoned villager,
5. Get kicked.

### Expected Behavior

The trading UI should open like in 1.20.4.

### Additional Server Info

1. This server uses velocity as proxy,
2. ViaVersion & ViaBackwards 5.0.0-SNAPSHOT, and ViaRewind 4.0.0-SNAPSHOT,
3. No third-party plugins have been used.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--42d42883--b393%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--42d42883--b393%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(4.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(4.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>
