### ISSUE TITLE
Signs from some plugins (for example Bedwars, SkyWars and other minigames) are broken

### ISSUE THREAD

**Issue by pixkk** [ViaVersion/ViaVersion#3891]
### `/viaversion dump` Output

https://dump.viaversion.com/6cf1aa9b05a819f3ad767368e504e817a6495814d70aea8842b79ac6b39ca398

### Console Error

- no errors

### Bug Description

Server core - 1.17.1, installed viaversion 5.0.0 and viabackwards 5.0.0, java 17. 

Player on 1.16.5 see signs normally ("waiting" state, right screenshot). Player on 1.20.6 version see "arena disabled" (left screenshot).
![image](https://github.com/ViaVersion/ViaVersion/assets/30828435/ac9aa194-5f47-4753-baf5-0a40e1d88d20)

Also in another minigame plugin problem occurs ("вимкнена" - disabled):
![image](https://github.com/ViaVersion/ViaVersion/assets/30828435/5551d1a4-0fe1-4dbd-b5c7-899aca08c532)

### Steps to Reproduce

1. Join to the server
2. See on sign from 1.20.6 version

### Expected Behavior

Signs are normally working

### Additional Server Info

Flamecord 2.1.0

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1428%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Purpur--1428%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): 1 commits behind dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-1%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by pixkk** [comment]
https://dump.viaversion.com/b147ddf94aeb79ca882221a588c1d0d88efe13ed7bf3f2a79bcf78a105099f64

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1428%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Purpur--1428%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by pixkk** [comment]
> Can you test with paper 1.17.1 to see if signs are still broken?

I use purpur 1.17.1. Anyway, try using paper?

**Comment by Kichura** [comment]
yes.

**Comment by pixkk** [comment]
> yes.

![image](https://github.com/ViaVersion/ViaVersion/assets/30828435/074b10ee-191b-4b67-a7e7-fc2904cca9c7)
Everything works fine on paper

**Comment by Kichura** [comment]
Then i suggest remaining on Paper 1.17.1 as anything older than 1.18.2 in Purpur is known to cause absurd problems.
