### ISSUE TITLE
Unable to join on Sponge 1.20.5+

### ISSUE THREAD

**Issue by avaruus1** [ViaVersion/ViaVersion#3895]
### `/viaversion dump` Output

https://dump.viaversion.com/2d6a3e5828082d306240d959fbfe7292804f33ac9ecee254939ac6c9f4359739

### Console Error

https://mclo.gs/r68FhbK

### Bug Description

The server cannot be joined when ViaVersion is present. [This commit](https://github.com/ViaVersion/ViaVersion/commit/35a00d0b9580681ff2f7e8dcc67d0b718c001f72) seems to include the change required to fix this for the Bukkit module, but it doesn't appear to be quite as simple for Sponge module.

### Steps to Reproduce

1. Attempt to join the server
2. See console

### Expected Behavior

One can join the server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--11.0.0--RC1633](https://img.shields.io/badge/Platform-1.20.6--11.0.0--RC1633-3498db?style=flat-square) </br>![ViaVersion (4.10.3-SNAPSHOT): Error fetching commit data](https://img.shields.io/badge/ViaVersion%20(4.10.3--SNAPSHOT)-Error%20fetching%20commit%20data-lightgray?style=flat-square) </br>

**Comment by avaruus1** [comment]
See https://github.com/ViaVersion/ViaSponge/issues/1
