### ISSUE TITLE
When under < 1.19 client join 1.20.6, respawning disconnect the player : io.netty.handler.codec.EncoderException

### ISSUE THREAD

**Issue by Neutrino2019** [ViaVersion/ViaVersion#3899]
### `/viaversion dump` Output

https://dump.viaversion.com/2544937236b61da41f98bbd69c29c4155f922ea4da586a689da7f72e7549d4c2

### Console Error

```
https://mclo.gs/nIzlJmi
```

### Bug Description

When a client (1.12 - 1.18) is dead and click on respawn button, he is disconnected from the server 1.20.6. 
![image](https://github.com/ViaVersion/ViaVersion/assets/51799154/bfdd77c0-9f7b-4a67-9a34-2ada2bd973c6)

### Steps to Reproduce

Have the `ViaBackwards-4.10.2` and `ViaVersion-4.10.2` Without changing the config file
Have the server on 1.20.6 Paper
Connect to the server with client version 1.12 - 1.18
Kill yourself
Click on respawn button

### Expected Behavior

Server Error page will be displayed with disconnection
![image](https://github.com/ViaVersion/ViaVersion/assets/51799154/bfdd77c0-9f7b-4a67-9a34-2ada2bd973c6)

### Additional Server Info

I use Docker itgz/minecraft image.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--129--0513374%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--129--0513374%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by FlorianMichael** [comment]
This issue has already been fixed with dev builds

**Comment by Neutrino2019** [comment]
> This issue has already been fixed with dev builds

How to i need to fix it?

**Comment by FlorianMichael** [comment]
ViaVersion - https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/build/libs/ViaVersion-4.10.3-SNAPSHOT.jar
ViaBackwards - https://ci.viaversion.com/job/ViaBackwards/lastSuccessfulBuild/artifact/build/libs/ViaBackwards-4.10.3-SNAPSHOT.jar
