### ISSUE TITLE
Shulker box contents.

### ISSUE THREAD

**Issue by BridgingNoob** [ViaVersion/ViaVersion#3903]
### `/viaversion dump` Output

https://dump.viaversion.com/5cbb2aa3aa9d6acc28bd68088057760698644ea84763bab168c78d429fe4634d

### Console Error

No errors.

### Bug Description

Shulker boxes lose their content when in creative mode and doing a few things.
 - When duplicating it by dragging or clicking the mouse wheel.
 - When moving any shulker box in the inventory (Does not have to be related)

**Bonus**
Shuker box content is not shown in the tool tooltip

### Steps to Reproduce

- Login with version 1.20.4 or down on a 1.20.6 paper server.
- Go in creative mode.
- Place a shulker box.
- Put something into it.
- Break it and pick it up.
- Move the item or do anything with it from the description.

**Bonus:**
- Login with version 1.20.4 or down on a 1.20.6 paper server.
- Place a shulker box.
- Put something into it.
- Break it and pick it up.
- Open the inventory and hover over the item.

### Expected Behavior

The items in the shulker boxes should not disappear.

**Bonus:** It should show the amount and name of the first 5 items and "and n more..."

### Additional Server Info

**Server-Type:** Paper
**Server-Version:** 1.20.6
**Tested-Version:** 1.20.4
**Plugin-Types:** Via-Versions & Via-Backwards
**Plugins:** Tested with no additional.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--130--5d8e53d%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--130--5d8e53d%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by BridgingNoob** [comment]
https://dump.viaversion.com/5cbb2aa3aa9d6acc28bd68088057760698644ea84763bab168c78d429fe4634d

**Comment by Barvalg** [comment]
![Platform: 1.20.6--130--5d8e53d%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--130--5d8e53d%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (4.10.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Goinging** [comment]
Yep to elaborate on the shulker box tooltip issue, basically it only shows what the item in the last slot where there is an item is. So if cyan dye was in slot 27 it would show only cyan dye as being the thing inside the shulker however if it was in slot 2 and there was nothing else in the shulker it would show it instead.

**Comment by Leahcimkrob** [comment]
Same issue with Client 1.20.1
It doesn't matter which slot contains items or which slot contains the Shulker Chest.

https://dump.viaversion.com/b075cfae421a4402b54e80d932ecf958aa72ac735fb2f6b623bdbc236d61a827

**Comment by Barvalg** [comment]
![Platform: 1.20.6--146--122c9d3%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--146--122c9d3%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
