### ISSUE TITLE
Health must be between 0 and 1. Input: NaN

### ISSUE THREAD

**Issue by daniel-skopek** [ViaVersion/ViaVersion#3905]
### `/viaversion dump` Output

https://dump.viaversion.com/fff2b757f489460c5a34dae49f0ede32867a54b587e39bc7a4484a796eee7f4f

### Console Error

```
https://api.mclo.gs/1/raw/jDiS4hO
```

### Bug Description

Spawning wither using Bukkit API causes to kick player.

Code:
`location.getWorld().spawnEntity(location, EntityType.WITHER);`

### Steps to Reproduce

1. Spawn Wither using Spigot API
2. Use 1.20.1 client
3. Server version: 1.20.4

### Expected Behavior

The user should not be kicked.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--NachoSpigot--%221a1455f%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--NachoSpigot--%221a1455f%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>
