### ISSUE TITLE
Armor Trims don't show up on 1.20.4 when the server 1.20.6

### ISSUE THREAD

**Issue by Goinging** [ViaVersion/ViaVersion#3907]
### `/viaversion dump` Output

https://dump.viaversion.com/f1c8d7dea3424ac06ad52e467621863f5257e95742523a4a930f37007c97f864

### Bug Description

Armor trims disappear on 1.20.4 when the server version is on 1.20.6. They don't show up on items at all or even show the text saying they are on an item. Armor trims item wise are the same between 1.20.4 and 1.20.6 so there should be a way to translate them between both versions.

### Steps to Reproduce

1. Put an armor trim on armor on 1.20.4 or have any armor with armor trim on it.
2. It is not visible.

### Expected Behavior

1. Armor trims should be visible

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--130--5d8e53d%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--130--5d8e53d%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (4.10.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Fixed in -dev builds, see https://ci.viaversion.com/job/ViaVersion-DEV/ and https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/

**Comment by Goinging** [comment]
This has not been fixed in dev builds

**Comment by Goinging** [comment]
https://dump.viaversion.com/c19df3fb09a0aba764e4e2393cadea09def241e17ff8c4a4cbade56088056a53

**Comment by Barvalg** [comment]
![Platform: 1.20.6--130--5d8e53d%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--130--5d8e53d%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Looks fine to me ![trims](https://i.imgur.com/fcnWzbD.png)

**Comment by Kichura** [comment]
The trim on item itself is missing it seems except the tags, the entity variant has it tho.
