### ISSUE TITLE
Banner Patterns don't show up correctly on shields when on 1.20.4 and server is on 1.20.6

### ISSUE THREAD

**Issue by Goinging** [ViaVersion/ViaVersion#3908]
### `/viaversion dump` Output

https://dump.viaversion.com/f1c8d7dea3424ac06ad52e467621863f5257e95742523a4a930f37007c97f864

### Bug Description

![Shield](https://github.com/ViaVersion/ViaVersion/assets/146245761/35836288-82ff-42e5-aba6-446330cf9ce4)
The background color for banner patterns on shields is always white no matter what if you join on 1.20.4 and the server is on 1.20.6. The two banners patterns are the same in the image.

### Steps to Reproduce

1. Login with a 1.20.4 client 
2. Make or get a banner with a background color that isn't white. 
3. Put it on a shield and it is white
4. Even banners already on shields are white as well.

### Expected Behavior

The banner shouldn't show white in the background every time.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--130--5d8e53d%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--130--5d8e53d%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (4.10.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Goinging** [comment]
For some reason it was still showing up incorrectly on my test server with the dev builds. But the lastest dev build fixes this.
