### ISSUE TITLE
Snowball animation not playing when thrown

### ISSUE THREAD

**Issue by pinkpig58** [ViaVersion/ViaVersion#3910]
### `/viaversion dump` Output

https://dump.viaversion.com/27ec40f6084f2eef01d31dbb2dafbadc4894cb458a6306d96d59a5579c8e7dbb

### Console Error

No console error

### Bug Description

Throwing a snowball on 1.20.6 on a 1.19 server doesn't display an animation when the snowball should be in the air

### Steps to Reproduce

Connect to a 1.19 server with VV using 1.20.6
Throw a snowball

### Expected Behavior

There should be an animation when the snowball is in the air

### Additional Server Info

No other plugins, running Paper 1.19

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--81%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Paper--81%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>
