### ISSUE TITLE
Can't redirect Ghast Fireball

### ISSUE THREAD

**Issue by MrKinau** [ViaVersion/ViaVersion#3911]
### `/viaversion dump` Output

https://dump.viaversion.com/eff7162cfa887bc7391138db09e060021dd948a198ee8a38b93f7532d55a2be0

### Bug Description

When trying to redirect a ghast fireball in 1.20.6 on a 1.20.4 server with your fist, it does not work. Redirecting it with a projectile (e.g. arrow) works.

### Steps to Reproduce

1. Find a ghast
2. Wait for it shooting a fireball at you
3. Try to redirect the fireball with your fist (press attack key while looking at the fireball)

### Expected Behavior

The ghast fireball should be redirected.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--497%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--497%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Try dev versions, I believe we have already fixed it.

**Comment by MrKinau** [comment]
> Try dev versions, I believe we have already fixed it.

Alright, just tested with 5.0.0-SNAPSHOT and redirecting ghast fireballs is working, thx for the hint.
