### ISSUE TITLE
Chat error

### ISSUE THREAD

**Issue by blackowlzz** [ViaVersion/ViaVersion#3914]
### `/viaversion dump` Output

https://dump.viaversion.com/ff79ba35c1115db6709f2ab77b7a89db5290545698d5dc2a4e34b07692d1fc1b

### Console Error

[[```
[Put the mclo.gs link or text here.](https://mclo.gs/5gOssTP)
```]

### Bug Description

Every time a plugin sends a link in chat via version spams errors in console and outputs <error> in game chat.

### Steps to Reproduce

Login with 1.20.6, use paper 1.20.1 server and just have any plugin to send a link in chat.

### Expected Behavior

A link should show up, not <error>

### Additional Server Info

_No response_

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--196%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--196%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.1.2): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.2)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>broken_jar</details>

**Comment by kennytv** [comment]
Your jar is broken
