### ISSUE TITLE
Constant client crashing

### ISSUE THREAD

**Issue by JHarris12345** [ViaVersion/ViaVersion#3916]
### `/viaversion dump` Output

https://dump.viaversion.com/857ea676b201e6e0349ca8662eb23846a9020f45093fb19ebbe8181f237a8194

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

My client is consistently crashing with the error:

```
The game crashed whilst rendering particle
Error: java.lang.NullPointerException: Cannot invoke "org.joml.Vector3f.x()" because "$$7[0]" is null```

I am on default 1.20.4 and 1.20.6 I have tried. All the same. Server versions I crash on are 1.20.2 and 1.17.1 (not tested others).

This is since updating VV

### Steps to Reproduce

No clue to be honest. I dont know what causes it

### Expected Behavior

No crash

### Additional Server Info

_No response_

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--22%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Pufferfish--22%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.10.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.1.2): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.2)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by JHarris12345** [comment]
Issue still persists. Client crashed for:

![image](https://github.com/ViaVersion/ViaVersion/assets/46936647/4bf50f12-f159-40e0-824e-d565883b893f)

**Comment by kennytv** [comment]
Can you send the crash logs?
