### ISSUE TITLE
1.8.8 Server 1.20.6 Player join Issue

### ISSUE THREAD

**Issue by BadPackage** [ViaVersion/ViaVersion#3918]
### `/viaversion dump` Output

https://dump.viaversion.com/0a99da0c85f4f5bc25ba65bd40654239f0f8a1f16b88e949bc44d8f392cce084

### Console Error

[Lobby-1][12:53:45 INFO]: obvFreddy[/ip] logged in with entity id 15 at ([world]-3.5, 65.0, 2.5)
[Lobby-1][12:53:46 ERROR]: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.v1_8_R3.EnumParticle.c()" because "this.a" is null
[Lobby-1][12:53:46 WARN]: [ViaVersion] ERROR IN Protocol1_12_2To1_13 IN REMAP OF LEVEL_PARTICLES (0x22)
[Lobby-1][12:53:46 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[Lobby-1]Packet Type: LEVEL_PARTICLES, Type: IntType, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.v1_12_2to1_13.rewriter.WorldPacketRewriter1_13$9 (Anonymous), Packet ID: 36
[Lobby-1][12:53:46 WARN]:       at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[Lobby-1][12:53:46 WARN]:       at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[Lobby-1][12:53:46 WARN]:       at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[Lobby-1][12:53:46 WARN]:       at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210)
[Lobby-1][12:53:46 WARN]:       at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199)
[Lobby-1][12:53:46 WARN]:       at net.minecraft.server.v1_8_R3.NetworkManager.lambda$writePacket$5(NetworkManager.java:375)
[Lobby-1][12:53:46 WARN]:       at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[Lobby-1][12:53:46 WARN]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[Lobby-1][12:53:46 WARN]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[Lobby-1][12:53:46 WARN]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[Lobby-1][12:53:46 WARN]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[Lobby-1][12:53:46 WARN]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[Lobby-1][12:53:46 WARN]:       at java.base/java.lang.Thread.run(Thread.java:840)
[Lobby-1][12:53:46 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[Lobby-1]Packet Type: LEVEL_PARTICLES, Type: IntType, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.v1_12_2to1_13.rewriter.WorldPacketRewriter1_13$9 (Anonymous), Packet ID: 36
[Lobby-1][12:53:46 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(4) exceeds writerIndex(1): PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 256)
[Lobby-1][12:53:46 WARN]:       at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[Lobby-1][12:53:46 WARN]:       at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:809)
[Lobby-1][12:53:46 WARN]:       at com.viaversion.viaversion.api.type.types.IntType.read(IntType.java:36)
[Lobby-1][12:53:46 WARN]:       at com.viaversion.viaversion.api.type.types.IntType.read(IntType.java:29)
[Lobby-1][12:53:46 WARN]:       at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:140)
[Lobby-1][12:53:46 WARN]:       at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.lambda$map$0(PacketHandlers.java:57)
[Lobby-1][12:53:46 WARN]:       at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:179)
[Lobby-1][12:53:46 WARN]:       at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:405)
[Lobby-1][12:53:46 WARN]:       at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:369)
[Lobby-1][12:53:46 WARN]:       at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122)
[Lobby-1][12:53:46 WARN]:       at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:337)
[Lobby-1][12:53:46 WARN]:       at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:313)
[Lobby-1][12:53:46 WARN]:       at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[Lobby-1][12:53:46 WARN]:       at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[Lobby-1][12:53:46 WARN]:       at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[Lobby-1][12:53:46 WARN]:       at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[Lobby-1][12:53:46 WARN]:       at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[Lobby-1][12:53:46 WARN]:       at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210)
[Lobby-1][12:53:46 WARN]:       at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199)
[Lobby-1][12:53:46 WARN]:       at net.minecraft.server.v1_8_R3.NetworkManager.lambda$writePacket$5(NetworkManager.java:375)
[Lobby-1][12:53:46 WARN]:       at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[Lobby-1][12:53:46 WARN]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[Lobby-1][12:53:46 WARN]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[Lobby-1][12:53:46 WARN]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[Lobby-1][12:53:46 WARN]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[Lobby-1][12:53:46 WARN]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[Lobby-1][12:53:46 WARN]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[Lobby-1][12:53:46 WARN]:       at java.base/java.lang.Thread.run(Thread.java:840)
[Lobby-1][12:53:46 INFO]: obvFreddy lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[Lobby-1]Packet Type: LEVEL_PARTICLES, Type: IntType, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.v1_12_2to1_13.rewriter.WorldPacketRewriter1_13$9 (Anonymous), Packet ID: 36
[Lobby-1][12:53:47 INFO]: UUID of player obvFreddy is b2776065-6a77-4ff4-9652-4753cefc9af7
[Lobby-1][12:53:47 INFO]: obvFreddy[/ip] logged in with entity id 16 at ([world]-3.5, 65.0, 2.5)
[Lobby-1][12:53:47 WARN]: [ViaVersion] (1.15.2->1.16) Ignoring serverbound plugin channel register of 'fabric-screen-handler-api-v1:open_screen', as it is longer than 32 characters

### Bug Description

When I join my 1.8.8 server with Lunar-Fabric 1.20.6, I encounter an exception. However, when I try to relog, it works, and I only receive the following warning:
```
[Lobby-1][12:53:47 WARN]: [ViaVersion] (1.15.2->1.16) Ignoring serverbound plugin channel register of 'fabric-screen-handler-api-v1:open_screen', as it is longer than 32 characters
```

Client Mods:
- essential_1-3-2-5_fabric_1-20-6.jar
- fabric-api-0.99.4+1.20.6.jar
- indium-1.0.30+mc1.20.4.jar
- iris-1.7.0+mc1.20.6.jar
- lithium-fabric-mc1.20.6-0.12.3.jar
- memoryleakfix-forge-1.17+-1.1.5.jar
- sodium-extra-0.5.5+mc1.20.6-build.118.jar
- sodium-fabric-0.5.8+mc1.20.6.jar

### Steps to Reproduce

1. Setup 1.8.8 Server with Viaversion
2. Join with 1.20.6 Client

### Expected Behavior

No exceptions should occur when joining the server.

### Additional Server Info

Velocity latest; PandaSpigot 1.8.8

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PandaSpigot--%22df48c6e%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PandaSpigot--%22df48c6e%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by HowardZHY** [comment]
Does it happen with normal PaperSpigot or happen with only ViaVersion?

**Comment by BadPackage** [comment]
I can't test that because Paper 1.8.8 does not really support the required Java 17 version for ViaVersion.

**Comment by Jo0001** [comment]
Try those special j8 builds https://ci.viaversion.com/job/ViaVersion-Java8/

**Comment by BadPackage** [comment]
Seem to work with that. The Exception does not occur with this build. Thank you.
