### ISSUE TITLE
Kicks for many things

### ISSUE THREAD

**Issue by JHarris12345** [ViaVersion/ViaVersion#3922]
### `/viaversion dump` Output

https://dump.viaversion.com/4adc90e0f7773340b5272ae6e1d8ba5efa67451204c3cdadea7c48c5b310b8f0

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

Players get disconnected for long strings of text when doing certain things. This image is an error after removing an item from an item frame (client ver 1.20.6 but might occur on 1.20.5)
![73304e1ea31c50ec82a0a2add60e8809](https://github.com/ViaVersion/ViaVersion/assets/46936647/8922b42f-1bd3-4ced-9bab-9b7c98d50bd5)

### Steps to Reproduce

Use 1.20.6 (or 1.20.5)
Remove an item from an item frame

### Expected Behavior

No kick

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Axolotl--%22f699bcf%22%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Axolotl--%22f699bcf%22%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): 2 commits behind dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-2%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaRewind(4.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(4.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): 1 commits behind dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-1%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
