### ISSUE TITLE
VIAVERSION DOES NOT WORK IF I JOIN A SPECIFIC MC SERVER!!!!

### ISSUE THREAD

**Issue by Troll1Pope** [ViaVersion/ViaVersion#3925]
### `/viaversion dump` Output

I am a player, not a server owner.

### Console Error

Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository Packet Type: null, Type: CompoundTagType, Index: 3, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.Protocol1_20To1_20_2$$ Lambda/0x00007f48dd00cec0, Packet ID: -1 

### Bug Description

Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository Packet Type: null, Type: CompoundTagType, Index: 3, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.Protocol1_20To1_20_2$$ Lambda/0x00007f48dd00cec0, Packet ID: -1

### Steps to Reproduce

I dont know...

### Expected Behavior

It does not work with any versions
I occasionally log in, but with 0 ping, the world does not load in / chunks, animals/mobs dont move, I can not break blocks, but i can place blocks, but those placed blocks reset after crashing

But mainly I just get that error code..

### Additional Server Info

I use windows, I tried using mc version 1.20.1 & 1.20.4 in the server, its discord is https://discord.gg/SQVM546H btw

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
You should ask the server owner to do this, unfortunately we can't really help otherwise as it may just be they need to update their plugins.
