### ISSUE TITLE
1.20.4 -> 1.20.6: `SPELL_MOB` particles not colored

### ISSUE THREAD

**Issue by datatags** [ViaVersion/ViaVersion#3927]
### `/viaversion dump` Output

https://dump.viaversion.com/4151ac15c8ddec428a643e2e5fb6bbb7c754156d511ee05f9b2517ebc3bd746a

### Console Error

N/A

### Bug Description

When on 1.20.4 or lower, and using a 1.20.6 client, the color of `minecraft:entity_effect` particles (formerly known as `SPELL_MOB`) are not translated for the newer client, and are instead random colors, like when spawned with no color data.

### Steps to Reproduce

1. Install ViaVersion on a Paper 1.20.4 server (or lower)
2. Start the server and join the game with a 1.20.6 client
3. Look east (positive X) and run `/particle minecraft:entity_effect ~1 ~1 ~ 1 0 0 1 0` (the 1.20.6 client will complain that it is invalid, but it's proper syntax for 1.20.4). The effect is best observed when run in a repeating command block, but executing it several times manually will also suffice.
4. ❌ Observe that the particles are random colors each time the command is run.

### Expected Behavior

The particles created by that command should be red, and a 1.20.4 client will see them as red.

This seems to be due to color data for that particular particle changing in 1.20.6. Previously (i.e. 1.20.4), the color of this particle was determined by the same fields as those normally used for particle random offsets, but in 1.20.6 this has been changed so the `entity_effect` particle now has a data field for its color.

### Additional Server Info

1.20.6 client is on the left, 1.20.4 on the right
![demo](https://github.com/ViaVersion/ViaVersion/assets/17661376/3b1aca48-019c-44ac-86a8-2705d2fab66e)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--496%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--496%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>
