### ISSUE TITLE
paper1.19.4-server Incompetence

### ISSUE THREAD

**Issue by codejack2004** [ViaVersion/ViaVersion#3928]
### `/viaversion dump` Output

none

### Console Error

![微信截图_20240611160255](https://github.com/ViaVersion/ViaVersion/assets/161008492/acc966ac-9d32-4263-952e-f8620886ae17)

### Bug Description

The display version of the connection server is too old

### Steps to Reproduce

In the picture

### Expected Behavior

The display version of the connection server is too old

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Install ViaBackwards

**Comment by codejack2004** [comment]
> ViaBackwards
Oh my god, how did you reply so quickly? Thanks
I'll try it
