### ISSUE TITLE
when respawning

### ISSUE THREAD

**Issue by stpv221** [ViaVersion/ViaVersion#3938]
### `/viaversion dump` Output

 https://dump.viaversion.com/26dc232b52d670ef17404052c156dee5c082147ff13e6a427254893dfd5e7cad

### Console Error

https://github.com/ViaVersion/ViaVersion/assets/167645243/1f348233-f472-4ced-900a-a133be08bb08

### Bug Description

I'm hosting a 1.20.6 server, and am joining on 1.8.8, and when I try to respawn, I get this error

### Steps to Reproduce

Join server, die, respawn

### Expected Behavior

Respawn into game and not get kicked

### Additional Server Info

I use nexAuth, hosted on paper 1.20.6

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--138--906df69%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--138--906df69%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.1.2): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.2)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
