### ISSUE TITLE
Failed to validate message acknowledgements

### ISSUE THREAD

**Issue by MajdT51** [ViaVersion/ViaVersion#3940]
### `/viaversion dump` Output

https://dump.viaversion.com/c7556e94f9c820f8698f959afe6f3965e7b69b5085992208fb6d0d1ec12662ee

### Console Error

https://mclo.gs/7mePk6U

### Bug Description

Players with old client version are getting sometimes a "Failed to validate message acknowledgements from" error. This happened after the Update to 1.20.6 and the latest ViaVersion version. 
Could be related to this https://www.spigotmc.org/resources/viaversion.19254/update?update=72944

### Steps to Reproduce

Join the server 1.20.6 with older client version. 
Send messages, it is random there is no pattern. However, one of the player think that it happens mostly when you try to chat after running any command

### Expected Behavior

player send message without getting kicked

### Additional Server Info

we use ViaVersion and ViaBackwards.
Tested with latest version of ViaVersion

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--138--906df69%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--138--906df69%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by MajdT51** [comment]
https://dump.viaversion.com/c7556e94f9c820f8698f959afe6f3965e7b69b5085992208fb6d0d1ec12662ee

**Comment by Barvalg** [comment]
![Platform: 1.20.6--145--fe7043e%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--145--fe7043e%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Does this issue continue with `enforce-secure-profile` set to off + freedomchat installed on server?

**Comment by MajdT51** [comment]
> Does this issue continue with `enforce-secure-profile` set to off + freedomchat installed on server?

enforce-secure-profile ist set to false. We are not using freedomchat. 

After installing FreedomChat, I no longer get kicked. Is there a better solution, or could the issue be resolved without the new plugin? We aim to remain compliant with Minecraft's rules :).

**Comment by kennytv** [comment]
This will happen if a player has their chat disabled and reenables it, or has another player blocked. there might be fix coming at some point, but not for the next release yet

**Comment by MajdT51** [comment]
> This will happen if a player has their chat disabled and reenables it, or has another player blocked. there might be fix coming at some point, but not for the next release yet

great, thank you for the information :) hope it gets sorted out at some point in the near future.

**Comment by MajdT51** [comment]
Hi,

Thank you for working on the problem. I update the plugin to the latest version [5.0.2 - Bug fixes], enforce-secure-profile=false, and removed freedomchat plugin. The problem occurred again. A player joined with 1.20.4 and wrote a command and after that tried to write a chat message 
 
´´´
! [Thu 09:52:05 WARN  Server/ServerGamePacketListenerImpl] Failed to validate message acknowledgements from XXXXX
[Thu 09:52:05 INFO  Server/ServerGamePacketListenerImpl] XXXX lost connection: Chat message validation failure
´´´

**Comment by TwiceBit** [comment]
Hi,

I have the same problem. To reproduce execute an invalid command and then send a message. You will be kicked with the reason:  „Chat message validation failure“

I also tryed to disable enforce-secure-chat on the proxy (ViaVersion config) and the backend server.


Reproduce:
/minecraft:gamemode foo
(chat) hello world
[KICK]




Velocity 3.3.0-SNAPSHOT (git-a4476253-b411)
Purpur 1.20.6-2225-a52426c (MC: 1.20.6)*
Client Version: 1.20.1
https://dump.viaversion.com/fa4882ac129fd25a251ab2aa874e4027957b85a0ad0f7b0ee01a5a2d7b52ca21

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--a4476253--b411%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--a4476253--b411%29-3498db?style=flat-square) </br>![Proxy is 2 builds behind](https://img.shields.io/badge/Your%20proxy%20is%202%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (5.0.2): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.2): 6 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.2)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump </h3>

**Comment by TwiceBit** [comment]
https://dump.viaversion.com/4d0d359d2f4b7ddef1fecb4e924d82b93b50700180aca0d5a4a323e3041b8a82

Velocity 3.3.0-SNAPSHOT (git-09f687e5-b413)
Purpur 1.20.6-2225-a52426c (MC: 1.20.6)*

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--09f687e5--b413%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--09f687e5--b413%29-3498db?style=flat-square) </br>![ViaVersion (5.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
@TwiceBit Please open an issue on the ViaBackwards issue tracker (and before you do, please try with Via plugins moved to the backend instead of the proxy)
