### ISSUE TITLE
No player can enter the server unless it matches the server version

### ISSUE THREAD

**Issue by chy8952** [ViaVersion/ViaVersion#3942]
### `/viaversion dump` Output

https://dump.viaversion.com/bc307684df0e9b0298f5d8f3ef0ea4fabda52381543ce9523ee803fb60b3f827

### Console Error

![屏幕截图 2024-06-17 011942](https://github.com/ViaVersion/ViaVersion/assets/128957670/57b0bdf8-190e-477f-afe5-37394ec36765)

### Bug Description

No player can enter the server unless it matches the server version

### Steps to Reproduce

1. Logging in with a client that has a lower version than the server

### Expected Behavior

Should can be join in but it shows cant.

### Additional Server Info

Already used ViaBackwards 4.10.2.
My ViaVersion is 5.0.0.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--145--fe7043e%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--145--fe7043e%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.0)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Your viabackwards is too old.

**Comment by chy8952** [comment]
how do i get the latest one?spigot's latest is 4.10.2???
