### ISSUE TITLE
Login error with Hardcore Mode enabled

### ISSUE THREAD

**Issue by LeonTG** [ViaVersion/ViaVersion#3944]
### `/viaversion dump` Output

https://dump.viaversion.com/55f1e7cda473148cc991af4588190c56ee5f63981ee60a122f0c25b14fcfbada

### Console Error

https://mclo.gs/7nd25xw

### Bug Description

Since the hardcore boolean is encoded into the gamemode id byte (1.8 NMS: https://gyazo.com/8ee87d97ce5bf5d657ba113878f736fb, the `b` boolean is if its hardcore mode) and the ViaVersion rewriter does not take this into account (ViaVersion gamemode parsing code: https://gyazo.com/e14070fdf56f4cc66ae8ee2be74314fc), it errors when the gamemode id isn't recognized, in my case it returns value 10, which ViaVersion now doesn't know what to do with

Before 5.0.0 it would just return null, but not it throws an error instead

### Steps to Reproduce

1. Login to a 1.8 server that has hardcore mode enabled
2. You should not be able to join, you get the error I provided and get kicked

### Expected Behavior

I expect to be able to login without any errors and not get kicked.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Arctic--%2207d11b5%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--Arctic--%2207d11b5%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.0)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by LeonTG** [comment]
I cloned the repo and added this to the ViaVersion gamemode class to solve the issue on my end
![image](https://github.com/ViaVersion/ViaVersion/assets/8997490/2e6bf7e9-5a21-4ad1-ad65-a758b41e8982), but I figure ViaVersion wants a more proper fix than what I have done

**Comment by kennytv** [comment]
That looks fine, you can PR it if you want (though maybe as &= 7)

**Comment by LeonTG** [comment]
> That looks fine, you can PR it if you want (though maybe as &= 7)

I just chose that cuz thats what the vanilla 1.8 client does to parse the packet
![image](https://github.com/ViaVersion/ViaVersion/assets/8997490/fd5e4c05-05ff-4bfd-aa09-a5553d2d649b)

but yeah I can PR that change with `&= 7`

**Comment by kennytv** [comment]
Ah well -9 is alright then
