### ISSUE TITLE
Breaking blocks on 1.21 feels slow on a 1.8 backend

### ISSUE THREAD

**Issue by alexmarkey** [ViaVersion/ViaVersion#3951]
### `/viaversion dump` Output

https://dump.viaversion.com/72b9f2b75e074b8904e433033c3faaca6a15ec60c5766b6cbe2de95eefdaad69

### Bug Description

There seems to be an issue with 1.21 clients on 1.8 servers in regards to mining blocks (more noticable when using high levels of efficiency). For the sake of this test, I am using a high level of efficiency (level 100) so the bug is more clear, but I believe this might be a bug in general with breaking blocks?

Server Backend = 1.8.8
Client = 1.21

1.21 client = https://gyazo.com/e13efa1c02dd9bd02f34912354b8b4fc
1.20.1 client = https://gyazo.com/683d7972eeb7a9b0959931700e011a4f

From the above gifs you can see that the blocks do not seem to be breaking properly on the client when using 1.21. They are still breakign correctly but there is no break animation on the client, and feels very delayed (I have 200ms ping on the server I am testing)

### Steps to Reproduce

- Login to a 1.8.8 server with a 1.21 client
- Give yourself a pickaxe with a high level of efficiency (a pickaxe that will essentially insta-break a block)
- Break a piece of stone with this pickaxe
- The client will not see the break instantly (assuming you're not on a local server)
- I have a 200ms ping (Australia) so I see the blocks break on my client 200ms later

### Expected Behavior

Blocks should break instantly on my client, not 200ms later

### Additional Server Info

We're using Velocity

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--TacoSpigot--bf023c7d%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--TacoSpigot--bf023c7d%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Aides123** [comment]
same issue

**Comment by shaijana** [comment]
Same issue with an 1.20.6 server (velocity backend).

**Comment by kennytv** [comment]
For newer servers, move ViaVersion to the backend for the fix

**Comment by gre3x** [comment]
I have the same issue on my 1.17.1 server. Is 1.17.1 considered legacy?

**Comment by EddyboyGames** [comment]
@kennytv how do I do this backend fix?

Basically I have worked it out, Enchantments on certain tools don't work at all like efficiency on axes and pickaxes making tool with any level of efficiency incredibly slow even with efficiency 5.

Server is paper 1.17.1, client is 1.21 and tools are slow with enchants, however if I switch to client 1.20.x its completely fine, plugin version 5.0.1

**Comment by gratatah** [comment]
Yep same thing here, 1.20.4 backend. Every version up to 1.20.6 it's fine but once I'm on 1.21, slow.

**Comment by tomaszpro99** [comment]
Spigot server 1.12.2, player with client 1.21 pickaxe with efficiency of 1/2/3/4/5 copies blocks the same
