### ISSUE TITLE
Enchantment Functionality Issue on 1.21 via ViaVersion

### ISSUE THREAD

**Issue by DarkChromaMC** [ViaVersion/ViaVersion#3954]
### `/viaversion dump` Output

https://dump.viaversion.com/6aefe1b5f670ab99e47f59725e1fb6aa9c4fcafb8b8a255f5a9d7d65cc380f7c

### Console Error

None

### Bug Description

Players using the client version 1.21 experience problems with certain enchantments not functioning correctly, including 'Efficiency' on tools and 'Swift Sneak' on leggings. These issues are not present when players are on older client versions (i.e., 1.20.1). This suggests a compatibility or implementation issue with enchantments in 1.21 when running ViaVersion on the Velocity proxy.

### Steps to Reproduce

1. Connect to the server using a client on version 1.21.
2. Apply the 'Efficiency' enchantment to any tool or 'Swift Sneak' to leggings.
3. Attempt to use the enchanted items in their respective contexts (e.g., mining for Efficiency, sneaking for Swift Sneak).
4. Observe that the enchantments do not perform as expected.

### Expected Behavior

Enchantments such as 'Efficiency' and 'Swift Sneak' should function identically to how they do in client versions prior to 1.21, providing their respective speed boosts and abilities.

### Additional Server Info

This issue seems isolated to the 1.21 client version when running through ViaVersion on the specified Velocity proxy setup. Lower client versions do not exhibit this problem, suggesting a version-specific compatibility issue with the enchantments.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--350ea7f3--b398%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--350ea7f3--b398%29-3498db?style=flat-square) </br>![Proxy is 1 builds behind](https://img.shields.io/badge/Your%20proxy%20is%201%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.1-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.1--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by kennytv** [comment]
For these, you need to run ViaVersion on your backend servers

**Comment by DarkChromaMC** [comment]
Thank you for the fast response! Should I remove ViaVersion and Viabackwards from the proxy? Or leave them as is

**Comment by kennytv** [comment]
You should remove them, so they are only on the backend servers
