### ISSUE TITLE
error kick players

### ISSUE THREAD

**Issue by xDeveloping** [ViaVersion/ViaVersion#3956]
### `/viaversion dump` Output

https://dump.viaversion.com/7757bd3b1308ef3edbee40365f74e37b1faa93e97ca0e58179dd3d0428fbdb2d

### Console Error

.CoastalTuna5776 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: CONTAINER_CLICK, Type: ItemType1_20_5, Index: 8, Data: [{Unsigned Byte: 15}, {VarInt: 122}, {ShortType: 16}, {ByteType: 0}, {VarInt: 0}, {VarInt: 1}, {ShortType: 16}], Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$10 (Anonymous), Packet ID: 13

### Bug Description

when players open a virtual backpack with many renamed items inside it, it kicks them out.

### Steps to Reproduce

when players open a virtual backpack with many renamed items inside it, it kicks them out.

### Expected Behavior

when players open a virtual backpack with many renamed items inside it, it kicks them out.

### Additional Server Info

when players open a virtual backpack with many renamed items inside it, it kicks them out.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--UniverseSpigot--%221518617%22%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--UniverseSpigot--%221518617%22%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0): 10 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.0)-10%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.0): 10 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.0)-10%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
