### ISSUE TITLE
error on 1.20.6 server

### ISSUE THREAD

**Issue by Dinos3396** [ViaVersion/ViaVersion#3958]
### `/viaversion dump` Output

https://dump.viaversion.com/707eb118422d1f325f4bf81e34c1b9a1e2462eda1c5e7e2e32833a7429882a84

### Console Error

[```
Put the mclo.gs link or text here.
```
](https://mclo.gs/iIrmuFg)

### Bug Description

error

### Steps to Reproduce

error

### Expected Behavior

no error

### Additional Server Info

_No response_

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--DEV--b4b5d0c%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--DEV--b4b5d0c%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.1-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.1--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
