### ISSUE TITLE
Movement Based Enchants Don't Work When Server is on 1.20.6 and the Player Version is 1.21

### ISSUE THREAD

**Issue by Goinging** [ViaVersion/ViaVersion#3960]
### `/viaversion dump` Output

https://dump.viaversion.com/6870ad8bd588b59608a9d294baae6db4f2e8f2a0d5aeea14127521a85aa701a5

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

The following enchants don't work when a client is on 1.21 and the server is on 1.20.6,
Depth Strider
Soul Speed
Swift Sneak 

### Steps to Reproduce

1. Login with a 1.21 client
2. Try and use existing armor with any of these three enchants on it or create new ones.
3. They display correctly as being on the armor 
4. They don't work at all.

### Expected Behavior

The enchantments function 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--145--fe7043e%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--145--fe7043e%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0): 10 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.0)-10%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.0): 10 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.0)-10%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Goinging** [comment]
https://dump.viaversion.com/f574f67124ac357887f821a96625005f2a874d5484a3fe01c2d12deffa373314
Also confirmed that soul soil works with soul speed, just soul sand doesn't work.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--145--fe7043e%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--145--fe7043e%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.1-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.1--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Goinging** [comment]
bruh

**Comment by Goinging** [comment]
Soul Sand doesn't work at all for soul speed still btw. Idk if this is something that can be fixed or not.

**Comment by kennytv** [comment]
The fix of that will depend on whether/how mojang fixes https://bugs.mojang.com/browse/MC-272517
