### ISSUE TITLE
[1.20.5->1.21] Movement enchantment bug

### ISSUE THREAD

**Issue by Pantera07** [ViaVersion/ViaVersion#3962]
### `/viaversion dump` Output

https://dump.viaversion.com/76c50718cc987770644b58acdbea1a4c1ddc290a1e9a225464ff046385f707a7

### Console Error

```
none
```

### Bug Description

Movement enchantments are applied without checking conditions.
Example: Soul Speed ​​makes players everywhere faster. (This also triggers anti-cheat detection.)

Cause commit: https://github.com/ViaVersion/ViaVersion/commit/77d702bc9be1e9a05ef33dc5039df953ad61dd18

### Steps to Reproduce

https://youtu.be/E2cg2Ql2mrU

1.20.5 Server / 1.21 Client

### Expected Behavior

Movement enchantments must work according to the conditions.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--147--e41d44f%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--147--e41d44f%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Barvalg** [comment]
![Platform: 1.20.6--147--e41d44f%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--147--e41d44f%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
