### ISSUE TITLE
Player disconnected, when creating stone brick

### ISSUE THREAD

**Issue by LOURENT4462** [ViaVersion/ViaVersion#3963]
### `/viaversion dump` Output

https://dump.viaversion.com/a9c37e674bf58cde2b48492021a7ee1a124bd50458e6e39140e9ad346ffec1bd

### Console Error

[Put the mclo.gs link or text here.](https://mclo.gs/ThIXbQy)

### Bug Description

When players craft stone bricks they disconnect from the server

### Steps to Reproduce

1. login to server
2. craft stone brick
3. disconnected

https://github.com/ViaVersion/ViaVersion/assets/99059205/79d4760a-9f8c-4d33-8109-684cc65b4420

(please see the video I attached)

### Expected Behavior

Players do not disconnect while crafting stone bricks

### Additional Server Info

I use velocity proxy and papermc

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--450%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--450%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0): 16 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.0)-16%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.0): 13 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.0)-13%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
