### ISSUE TITLE
Visual bug when selecting territories with WE/FAWE

### ISSUE THREAD

**Issue by RtvTry** [ViaVersion/ViaVersion#3967]
### `/viaversion dump` Output

https://dump.viaversion.com/2f7795ab2c6ba8c2127d925eca815e39ef481c6a8fb40132f3f6780d6dc448db

### Console Error

Absent

### Bug Description

I have a FAWE plugin on my server, when I log into the server with versions < 1.19, I get a bug when selecting blocks with an axe. For example: I selected a block with the left mouse button and it visually disappeared, tested on all versions below 1.19.
My server is on version: 1.20.4. ViaVersion: 5.0.0, ViaBackwards 5.0.0

### Steps to Reproduce

1. Login with versions < 1.19
2. You take an axe in your hands to mark out the territory
3. After selecting with the left mouse button, the block disappears visually

### Expected Behavior

When you left-click the block should disappear for 1 ms and then appear. This happens in phenomena without the bug.

### Additional Server Info

Don't use.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Leaf--%22dd62783%22%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Leaf--%22dd62783%22%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0): 13 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.0)-13%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by RtvTry** [comment]
> ### `/viaversion dump` Вывод
> https://dump.viaversion.com/2f7795ab2c6ba8c2127d925eca815e39ef481c6a8fb40132f3f6780d6dc448db
> 
> ### Ошибка консоли
> Отсутствует
> 
> ### Описание ошибки
> У меня есть плагин FAWE на моем сервере, когда я захожу на сервер с версиями < 1.19, я получаю ошибку при выборе блоков топором. Например: я выделил блок левой кнопкой мыши, и он визуально исчез, протестировано на всех версиях ниже 1.19. Мой сервер находится на версии 1.20.4. Изменение версии: 5.0.0, в обратном направлении 5.0.0
> 
> ### Шаги по воспроизведению
> 1. Войдите в систему с версиями < 1.19
> 2. Вы берете в руки топор, чтобы разметить территорию
> 3. После выбора левой кнопкой мыши блок визуально исчезает
> 
> ### Ожидаемое поведение
> При щелчке левой кнопкой мыши блок должен исчезнуть на 1 мс, а затем появиться. Это происходит в явлениях без ошибки.
> 
> ### Дополнительная информация о сервере
> None
> 
> ### Контрольный список
> * [x]  Плагины Via работают только на **ЛИБО** внутренних серверах (например, Paper) **или** прокси (например, Velocity), **не на обоих**.
> * [x]  Я включил дамп изменения.
> * [x]  Если применимо, я включил вставку (**не скриншот**) ошибки.
> * [x]  Я попробовал последнюю сборку (ы) из https://ci.viaversion.com/ и проблема по-прежнему сохраняется.

**Comment by Barvalg** [comment]
![Platform: git--Leaf--%22dd62783%22%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Leaf--%22dd62783%22%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0): 13 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.0)-13%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by RtvTry** [comment]
> ### `/viaversion dump` Output
> https://dump.viaversion.com/755178227f9e236324d43473721ecd38fb9ab57393ac86363ca72631d5feb33a
> 
> ### Console Error
> Absent
> 
> ### Bug Description
> I have a FAWE plugin on my server, when I log into the server with versions < 1.19, I get a bug when selecting blocks with an axe. For example: I selected a block with the left mouse button and it visually disappeared, tested on all versions below 1.19. My server is on version: 1.20.4. ViaVersion: 5.0.0, ViaBackwards 5.0.0
> 
> ### Steps to Reproduce
> 1. Login with versions < 1.19
> 2. You take an axe in your hands to mark out the territory
> 3. After selecting with the left mouse button, the block disappears visually
> 
> ### Expected Behavior
> When you left-click the block should disappear for 1 ms and then appear. This happens in phenomena without the bug.
> 
> ### Additional Server Info
> Don't use.
> 
> ### Checklist
> * [x]  Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
> * [x]  I have included a ViaVersion dump.
> * [x]  If applicable, I have included a paste (**not a screenshot**) of the error.
> * [x]  I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Leaf--%22dd62783%22%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Leaf--%22dd62783%22%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0): 13 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.0)-13%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by RtvTry** [comment]
https://dump.viaversion.com/755178227f9e236324d43473721ecd38fb9ab57393ac86363ca72631d5feb33a

**Comment by Barvalg** [comment]
![Platform: git--Leaf--%22dd62783%22%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Leaf--%22dd62783%22%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0): 13 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.0)-13%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
