### ISSUE TITLE
Failed to decode packet 'clientbound/minecraft:system_chat'

### ISSUE THREAD

**Issue by ghost** [ViaVersion/ViaVersion#3968]
### `/viaversion dump` Output

https://pastebin.com/hHCsVpeb

### Console Error

Client Error

---- Minecraft Network Protocol Error Report ----
https://pastebin.com/X6reuP0M

### Bug Description

NBT conversion from 1.20.4 -> 1.20.5+ has an issue

Failed to decode: No key id in MapLike

### Steps to Reproduce

Embed specific nbt from an itemstack into a chat message?

### Expected Behavior

Should not cause error

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
Provide a proper dump and also follow the checklist and update to builds from ci.

**Comment by Kichura** [comment]
Update ViaVersion to latest CI build, otherwise try moving it to spigot/paper instead to see if it chsnges anything.

Also you just embedded the entire dump into a pastebin instead of putting the viaversion dump link into your issue meaning this technically fails to meet to meet the template.

**Comment by Kichura** [comment]
> > Also you just embedded the entire dump into a pastebin instead of putting the viaversion dump link into your issue meaning this technically fails to meet the template.
> 
> Understood, however there is a valid reason for this.
> 
> > Also the dump is exactly same as real except with some sensitive info removed

this part doesn't really make any sense. if you intentionally hide details from the dump then it makes your issue more difficult to diagnose in the long-term.

**Comment by Kichura** [comment]
> > > > Also you just embedded the entire dump into a pastebin instead of putting the viaversion dump link into your issue meaning this technically fails to meet the template.
> > > 
> > > 
> > > Understood, however there is a valid reason for this.
> > > > Also the dump is exactly same as real except with some sensitive info removed
> > 
> > 
> > this part doesn't really make any sense. if you intentionally hide details from the dump then it makes your issue more difficult to diagnose in the long-term.
> 
> Rest assured, the issue is viaversion not converting nbt properly, the hidden info isn't relevant to the bug, now to stay on topic, would using latest CI build in production be risky?

The answer is no. And using dev builds normally works fine too unless there are edge-cases where it's meant to be tested upon.

**Comment by FlorianMichael** [comment]
Is it possible for you to provide the item / the chat message which is causing the kicks?
