### ISSUE TITLE
java.lang.NoSuchFieldError: blockMappings

### ISSUE THREAD

**Issue by SCP2609** [ViaVersion/ViaVersion#3971]
### `/viaversion dump` Output

https://dump.viaversion.com/309eea128de76ba5e28e1be066fd42398b3114779a26c1bf567f73bcfe730df5

### Console Error

```
> [10:29:31] [Server thread/INFO]: SCP2609 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NoSuchFieldError: blockMappings

> [10:29:31] [Server thread/INFO]: SCP2609 left the game

> [10:29:31] [Server thread/WARN]: handleDisconnection() called twice
```

### Bug Description

join 1.16.5 client on 1.17.1 server

### Steps to Reproduce

1. start minecraft 1.16.5
2. join on 1.17.1 server with viabackwards

### Expected Behavior

normal connection to the server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3284a--Spigot--3892929--0ab8487%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-3284a--Spigot--3892929--0ab8487%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(5.0.0)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
