### ISSUE TITLE
[1.20.5->1.21] Stops running when wearing enchanted equipment/tool.

### ISSUE THREAD

**Issue by Pantera07** [ViaVersion/ViaVersion#3973]
### `/viaversion dump` Output

https://dump.viaversion.com/d9881fa0d31b7f97fb7b89a5c06eee2f07933aad7f86d2f2b252c53606fd5dd4

### Console Error

```
none
```

### Bug Description

Running stops when holding an efficiency tool or wearing enchantment equipment.

1.20.6 Server, 1.21 Cleint: https://youtu.be/RKQ7tfTpAX8
1.21 Server, 1.21 Cleint: https://youtu.be/PTal1pAPqiU

### Steps to Reproduce

1. Open 1.20.6 or lower server
2. Join 1.21 Client
3. Wear enchanted equipment while running. (Efficiency, SwiftSneak, AquaAffinity, DepthStrider)

### Expected Behavior

Wearing enchantment equipment or holding an efficiency tool in the main hand should not stop a player from running.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--147--e41d44f%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--147--e41d44f%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.1)-Even%20with%20master-brightgreen?style=flat-square) </br>
