### ISSUE TITLE
Error with plugin

### ISSUE THREAD

**Issue by TheTruePerson** [ViaVersion/ViaVersion#3974]
### `/viaversion dump` Output

https://dump.viaversion.com/48f393ecfc79e706e1c56f5a6faa807705330014ff26e6e6fc2aaca74b112df2

### Console Error

```
(https://mclo.gs/kc8vx5x)
```

### Bug Description

Running Viaversion 5.0.1 on a Paper 1.21 server does not work

### Steps to Reproduce

Create a Paper 1.21 server. Add ViaVersion 5.0.1. Look at the output.

### Expected Behavior

It should be able to start properly, instead of creating an error and not starting.

### Additional Server Info

no

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--28--812701d%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--28--812701d%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1)-Even%20with%20master-brightgreen?style=flat-square) </br><br><details><summary></summary>broken_config</details>
