### ISSUE TITLE
Viaverion Error

### ISSUE THREAD

**Issue by DRNUGGET69** [ViaVersion/ViaVersion#3975]
### `/viaversion dump` Output

https://dump.viaversion.com/bda8d7402b94355ad9825ae2b2b16ebb9d30323366499f1167de36727cfd89b8

### Console Error

```
https://mclo.gs/CwCC5ec
```

### Bug Description

Plugin keeps spamming error messages

### Steps to Reproduce

Make a 1.21 server
Install the plugins
Done

### Expected Behavior

Don’t spam error messages

### Additional Server Info

No

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--35--b99d071%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--35--b99d071%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.0): 5 commits behind master](https://img.shields.io/badge/ViaRewind%20(4.0.0)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
