### ISSUE TITLE
 The Viaversion plugin is reporting an error when it is on the Velocity side

### ISSUE THREAD

**Issue by xiaozhi9658** [ViaVersion/ViaVersion#3977]
### `/viaversion dump` Output

https://dump.viaversion.com/364829961ab1e136937e1849c86710ff1d14baface56f73fa6f43f98e1346ec8

### Console Error

https://[api.mclo.gs/1/raw/bl6RLvg](https://api.mclo.gs/1/raw/bl6RLvg)

### Bug Description

When a player logs in to the latest version of the server with version 1.20.1, an error is reported in the background and the player is unable to log in

### Steps to Reproduce

1.Players used 1.20.1version to log in.
2.Player are not able to log in.
3.At the same time, an error will be reported in the background.

### Expected Behavior

The plugin does not report errors when installed in velocity, and players can play normally.

### Additional Server Info

I used velocity and didn't install any other plugins.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--afd8b55f--b390%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--afd8b55f--b390%29-3498db?style=flat-square) </br>![Proxy is 10 builds behind](https://img.shields.io/badge/Your%20proxy%20is%2010%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (5.0.1): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.0): 5 commits behind master](https://img.shields.io/badge/ViaRewind%20(4.0.0)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
