### ISSUE TITLE
Accessing horse inventory will shift items around your inventory

### ISSUE THREAD

**Issue by FaultyFunctions** [ViaVersion/ViaVersion#3978]
### `/viaversion dump` Output

https://dump.viaversion.com/dad5f1e1a9d026136f42633fd2476cc6f951548e58f41fa135db483b0ca04d62

### Console Error

N/A

### Bug Description

Accessing horse inventory will shift items around your inventory. They also have 3 extra slots in their UI. This is a visual glitch only.
Before accessing horse inventory:
![image](https://github.com/ViaVersion/ViaVersion/assets/6508045/cb0a3e69-8a37-4888-a148-187a361cfa3a)
After:
![image](https://github.com/ViaVersion/ViaVersion/assets/6508045/9014048f-5608-410f-901c-f6f6aab58c30)

### Steps to Reproduce

1. Login with 1.21 client.
2. Have items in inventory
3. Access horse inventory
4. Notice items are moved around + there are extra 3 slots to the right of the horse

### Expected Behavior

Items should not be moved around and horses should not have those extra 3 slots.

### Additional Server Info

Server is running Purpur 1.20.4 v2176. Viaversion config is default.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2176%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--2176%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1)-Even%20with%20master-brightgreen?style=flat-square) </br>
