### ISSUE TITLE
1.21 Join Error

### ISSUE THREAD

**Issue by 510208** [ViaVersion/ViaVersion#3982]
### `/viaversion dump` Output

https://dump.viaversion.com/46079a7f993eb9ecacf82060b0b1dc04e9b6d247e927561bd8963fe6424e3b5f

### Console Error

```
[21:12:26 INFO]: 玩家 Sam510208 跳進了雲羽生存服!
[21:12:26 INFO]: Sam510208[/61.63.193.125:14437] logged in with entity id 3296573 at ([world]690.7453828172319, 63.5, -3246.981470191722)
[21:12:27 INFO]: Sam510208 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: unable to fit 3778114 into 3
[21:12:27 INFO]: 玩家 Sam510208 道別了雲羽生存服!
```

### Bug Description

If my Minecraft Version over than 1.20.4(1.20.4 and 1.21), when I want join, the game will print an expection and break my connection. That message like this:
```
Internal Exception: io.netty.handler.codec.EncoderException: unable to fit 3778133 into 3
```
Some screenshot like this:
![image](https://github.com/ViaVersion/ViaVersion/assets/107909497/9eda11dc-cd5e-4f51-a67d-a378143ac48c)

### Steps to Reproduce

1. Login with 1.21 client
2. It will happend

### Expected Behavior

Player can join

### Additional Server Info

- I use `git-Purpur-2158 (MC: 1.20.4)*`
- Viaversion, ViaBackwind are both latest release

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2158%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--2158%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.1)-Even%20with%20master-brightgreen?style=flat-square) </br>
