### ISSUE TITLE
cant join with viaversion

### ISSUE THREAD

**Issue by MoonShadow1o** [ViaVersion/ViaVersion#3984]
### `/viaversion dump` Output

https://dump.viaversion.com/b8785c30621d7d35f43d429faee90222b127aa7cbcbeb2f0f98b132effb9db18

### Console Error

not error on console

### Bug Description

When this plugin is in my server, I can't log in and it gives an error
Intenal Exception: io.netty.handler.codec.Decoder.Exception: java.lang.indexOutOfBoundsException: readerIndex(29) + length(8)
exceeds writerIndex(33): PooledUnsafeDirectByteBuf(ridx: 29, widx: 33, cap:33)

### Steps to Reproduce

1 Put the plugin in the file server
2. Run the server
3 clicks on the server 
4 and finally the error and being kicked out of the server

### Expected Behavior

I can log in with any version

### Additional Server Info

I use paper and I haven't put a plugin in the server for now

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1618%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1618%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Jo0001** [comment]
Works fine for me.
Please provide more information:
- which client version is not working
- do you use a proxy and which
