### ISSUE TITLE
Why does swift sneak working require paper

### ISSUE THREAD

**Issue by IssueDescription** [ViaVersion/ViaVersion#3991]
### `/viaversion dump` Output

a

### Bug Description

I want to use viaversion on proxy only, but swift sneak is broken

### Steps to Reproduce

use swift sneak on 1.21 on 1.20.4 server

### Expected Behavior

Fix swift sneak

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>
