### ISSUE TITLE
Out-of-order Chat Packet received

### ISSUE THREAD

**Issue by Sukram28** [ViaVersion/ViaVersion#3992]
### `/viaversion dump` Output

https://dump.viaversion.com/555edfb230feb15f09ffe93d05dfe7b626759d36161a52d1f93c5fcb11577b4f

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

Im having some problems with viaversion since I upgrated to the 1.19.4 (papermc latest).
If a player (with a client version of 1.20.5, 1.20.6 or 1.21), uses chat commands they get kicked with the notification:

Out-of-Order Chat Packet received. Did your system time changed?

It doesnt occure always but with a round about 85% chance when using a command.
Clients using 1.20.4 and lower are fine. Furthermore it only occures if player writes it in chat.
But when plugins are calling player.performCommand("...") they wont get kicked. I couldnt find anything about it, but I cannot be the only one having this issure.

Hope this is fixable, because noone can play on the newest versions on the Server due to this bug.
Thank you really much for the awesome work.
Kind regards
Markus

### Steps to Reproduce

1. Login with an 1.20.5-1.21 Client
2. White a command (plugin unspecific. Works with everything)
3. There is a round about 85% change of beeing kicked for "Out-of-Order Chat Packet received. Did your system time changed?"
4. I havent tested it without all plugins but Im quite sure that it works even without any plugins.

### Expected Behavior

Players shouldnt be kicked when using commands.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--550%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--550%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1): 12 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.1)-12%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Kichura** [comment]
There is an existing workaround for this one:

1. Ensure your server is on pufferfish/purpur or similar fork,
2. Ensure that `disable-out-of-order-chat` is set to true in the pufferfish.yml file.

If this is not an option for you then this seems to be caused by a bizarre race condition with chat. *(Usually caused by bad third-party plugin(s) in this case)*

**Comment by FlorianMichael** [comment]
Try with latest Via* plugins again

**Comment by kennytv** [comment]
Are you sure this doesn't already occur with 1.20.2-1.20.4? Also, do you use Bungee/Velocity as a proxy?

**Comment by Hunter99011** [comment]
I have the same issue, the server is running Paper 1.20.2 (version 307), just updated ViaVersion and AxiomPaperPlugin ( I'm running the server for building ), and then got my first Out-of-order Chat packet kick within a few hours.

**Comment by FlorianMichael** [comment]
Are you sure you have latest dev build Via plugins?

**Comment by Hunter99011** [comment]
Yea, I just downloaded ViaVersion 5.0.1 yesterday

**Comment by Jo0001** [comment]
Thats not latest! See
https://hangar.papermc.io/ViaVersion/ViaVersion/versions?channel=Snapshot
https://hangar.papermc.io/ViaVersion/ViaBackwards/versions?channel=Snapshot

**Comment by Hunter99011** [comment]
Alright, I'll give both an update for the latest 5.0.2 snapshot, thanks ❤️

**Comment by kennytv** [comment]
And if you're using Velocity, make sure that's up to date as well. If you're using Bungee, who knows

**Comment by Hunter99011** [comment]
I'm not using Bungee or Velocity, its just a normal Paper server

**Comment by zylstra1313** [comment]
Did this ever get resolved?

**Comment by kennytv** [comment]
Yes, the latest release and also ci builds fixed issues here, same goes for (Velocity and Paper 1.21.1)

**Comment by kFxDaKing** [comment]
Having same problem with ViaVersion 5.0.3.

https://dump.viaversion.com/22183786b8e40788183fb3be4ccdbbdcec55076a0c2ca25d47db96107b70be0a

**Comment by Barvalg** [comment]
![Platform: git--Paper--196%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--196%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (5.0.3): 43 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.3)-43%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.3): 25 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.3)-25%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump </h3>
