### ISSUE TITLE
Glow outlines have the wrong colours on 1.21 clients

### ISSUE THREAD

**Issue by md5nake** [ViaVersion/ViaVersion#3993]
### `/viaversion dump` Output

https://dump.viaversion.com/b49e80473143e95925b740a88c721c5397c4fb3baea3a598e5cee64897c7f003

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

Block displays (and possibly other entities) glow yellow on 1.21 clients, whilst they glow aqua as intended on other versions.

### Steps to Reproduce

1. Spawn a block display using `Bukkit.getWorlds().get(0).spawn(SOME_POSITION, BlockDisplay.class).setGlowColorOverride(Color.AQUA);`
2. It should glow aqua on all versions except for 1.21, on which it is yellow.

### Expected Behavior

The glow outline should be aqua, not yellow.

### Additional Server Info

We also use Velocity 3.3.0

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2176%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--2176%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1): 14 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.1)-14%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.1): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(4.0.1): 5 commits behind master](https://img.shields.io/badge/ViaRewind%20(4.0.1)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by kennytv** [comment]
This is/was a sodium bug
