### ISSUE TITLE
Enchant Switft sneak not working

### ISSUE THREAD

**Issue by nicolube** [ViaVersion/ViaVersion#3994]
### `/viaversion dump` Output

https://dump.viaversion.com/fce060f570ead0676641f36ce3dab203bd127a2d198730852e42b8fb5b0bb80e

### Console Error

```
Put the mclo.gs link or text here.
```
None

### Bug Description

MC Client 1.21
PaperMC 1.20.2
Vecocity Proxy with ViaVersions 5.0.1-SNAPSHOT

The effect of the enchant snift sneak does not get applied to the player. 

### Steps to Reproduce

1. Use Setup descriped adrove
2. Connect with 1.21 Client
3. Enchant legins with Swit Sneak 3
4. Start moving while sneaking
5. Equip leggins and keep moving while sneaking

No noticable speed change....

### Expected Behavior

Enchant  Working giving speed

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--e60e2063--b399%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--e60e2063--b399%29-3498db?style=flat-square) </br>![Proxy is 1 builds behind](https://img.shields.io/badge/Your%20proxy%20is%201%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (5.0.1): 14 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.1)-14%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.1): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by FlorianMichael** [comment]
Move Via* to the backend servers as enchantments are only there supported.

**Comment by nicolube** [comment]
Seems do be the same issue as #3973

**Comment by R00tB33rMan** [comment]
> Move Via* to the backend servers as enchantments are only there supported.

I use the latest development builds of ViaVersion & ViaBackwards on our backend servers and cannot properly use depth strider & swift sneak when on versions 1.20.5 - 1.21 on a 1.20.4 server.

Dump: https://dump.viaversion.com/3e5252a4254dea698cd0c3db2680bb039371004a5d4aafc43a31906aa2b6c6eb

**Comment by Barvalg** [comment]
![Platform: git--UniverseSpigot--%225a79b26%22%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--UniverseSpigot--%225a79b26%22%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.3-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.3--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump </h3>
