### ISSUE TITLE
Item Display Bug on Clients Under 1.20.6

### ISSUE THREAD

**Issue by Goinging** [ViaVersion/ViaVersion#3996]
### `/viaversion dump` Output

https://dump.viaversion.com/2afd6dc0872d8e1cfccdb52bcc797470d6cc5eaf418bd5f93c74d8c1064ca57c

### Bug Description

Items in chat are displayed wrong on 1.20.4 or under clients when the server version is on 1.20.6.
![image](https://github.com/ViaVersion/ViaVersion/assets/146245761/207de15c-1584-4b46-a4ab-f98c5960be58)
![image](https://github.com/ViaVersion/ViaVersion/assets/146245761/0bb9b08d-0098-4add-ac75-9aa0ed1a0330)

### Steps to Reproduce

Login with a 1.20.4 client on a 1.20.6 server
Display an item in chat like by killing someone with it or with plugins that display items in chat.
It shows the item without any enchants or any attributes as if it is unmodified when you hover over it in chat.

### Expected Behavior

The item displays correctly when hovering over it.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--145--fe7043e%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--145--fe7043e%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
