### ISSUE TITLE
Failed to handle idle packet

### ISSUE THREAD

**Issue by Xayanix** [ViaVersion/ViaVersion#3998]
### `/viaversion dump` Output

https://dump.viaversion.com/0efa0af14e49033ef858ea4592de8b1ee92f02f60fffd533121585abb3f6b45a

### Console Error

```
[Put the mclo.gs link or text here.](https://mclo.gs/Nxj2Q0z)
```

### Bug Description

Joining on 1.21 client to 1.8 server causes this

### Steps to Reproduce

Joining on 1.21 client to 1.8 server causes this

### Expected Behavior

-

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--iSpigot--PaperEdition%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--iSpigot--PaperEdition%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Xayanix** [comment]
Looks like problem is on my side
