### ISSUE TITLE
[ViaVersion] ERROR IN Protocol1_21To1_20_5 IN REMAP OF LEVEL_CHUNK_WITH_LIGHT (0x27)

### ISSUE THREAD

**Issue by xiao-k233** [ViaVersion/ViaVersion#3999]
### `/viaversion dump` Output

https://dump.viaversion.com/ab0e1de869c5e88e0576e387ccca648eced12f17dcaeb446a9aecce1c1c16475

### Console Error

[mclogs](https://mclo.gs/WHANdzI)

### Bug Description

Leaves（A fork of paper)1.21(newest action build )
Just cross the End Portal because the beat of Snow Golem
then I disconneted

### Steps to Reproduce

Just cross the End Portal because the beat of Snow Golem

### Expected Behavior

Not disconnect

### Additional Server Info

Leaves（A fork of paper)1.21(newest action build )
with:
’‘’
[07:10:03 INFO]: Server Plugins (32):
[07:10:03 INFO]: Bukkit Plugins:
[07:10:03 INFO]:  - Chunky, ChunkyBorder, CoreProtect, Dominion, Essentials, EssentialsChat, EssentialsSpawn, EvenMoreFish, FreedomChat, Geyser-Spigot
[07:10:03 INFO]:  GroupManager, GSit, HoloMobHealth, ImageFrame, Kryptonite, MC_QQ, MiniMOTD, Multiverse-Core, PetBlocks, PlaceholderAPI
[07:10:03 INFO]:  ProtocolLib, RealisticSeasons, Shopkeepers, spark, Spartan, squaremap, sRTP, TAB, Vault, ViaBackwards
[07:10:03 INFO]:  ViaVersion, WorldEdit
‘’‘

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--DEV--ce443a4%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--DEV--ce443a4%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1): 17 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.1)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.1): 7 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
