### ISSUE TITLE
Soooo many java.lang.NullPointerException

### ISSUE THREAD

**Issue by xiao-k233** [ViaVersion/ViaVersion#4000]
### `/viaversion dump` Output

https://dump.viaversion.com/2f7910f440504961e48a614f1e28a5065a3def535a197dd1974a103f09c8ef75

### Console Error

[mclogs](https://mclo.gs/9avjpda)](https://mclo.gs/9avjpda)

### Bug Description

one player using viaversion
I don't what happend,but console printing warn messages crazily

### Steps to Reproduce

Just Start the server
wait a player connect via viabackwards

### Expected Behavior

No much messages

### Additional Server Info

Leaves(a fork of paper) 1.21 newest commit
plugins:
 Bukkit Plugins:
[19:32:42 INFO]:  - Chunky, ChunkyBorder, CoreProtect, Dominion, Essentials, EssentialsChat, EssentialsSpawn, EvenMoreFish, FreedomChat, Geyser-Spigot
[19:32:42 INFO]:  GroupManager, GSit, HoloMobHealth, ImageFrame, Kryptonite, MC_QQ, MiniMOTD, Multiverse-Core, PetBlocks, PlaceholderAPI
[19:32:42 INFO]:  ProtocolLib, RealisticSeasons, Shopkeepers, spark, Spartan, squaremap, sRTP, TAB, Vault, ViaBackwards
[19:32:42 INFO]:  ViaVersion, WorldEdit

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--DEV--ce443a4%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--DEV--ce443a4%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Not a ViaVersion issue

**Comment by xiao-k233** [comment]
Sorry, It's my wrong
viaversion made many errors a few hours ago,so I think......
I'm very sorry,thank you !
