### ISSUE TITLE
Console Spam: An error occurred in entity data handler EntityPacketRewriter1_19_3 for untracked entity type:

### ISSUE THREAD

**Issue by bed-dev** [ViaVersion/ViaVersion#4004]
### `/viaversion dump` Output

https://dump.viaversion.com/4ef1ba07d79414892f3d39b9de891c51c30562bc638865873dc4819906f97187

### Console Error

```
[03:45:20 ERROR]: [ViaVersion] (1.19.3->1.19.1) An error occurred in entity data handler EntityPacketRewriter1_19_3 for untracked entity type: Metadata{id=11, metaType=EntityDataType{typeId=26, type=Vector3fType}, value=Vector3f[x=0.25, y=0.25, z=1.0]}
[03:45:20 ERROR]: [ViaVersion] (1.19.3->1.19.1) Full entity data: Metadata{id=10, metaType=EntityDataType{typeId=26, type=Vector3fType}, value=Vector3f[x=0.0, y=0.79999995, z=0.0]}
Metadata{id=11, metaType=EntityDataType{typeId=26, type=Vector3fType}, value=Vector3f[x=0.25, y=0.25, z=1.0]}
Metadata{id=14, metaType=EntityDataType{typeId=0, type=ByteType}, value=1}
Metadata{id=16, metaType=EntityDataType{typeId=2, type=FloatType}, value=32.0}
Metadata{id=22, metaType=EntityDataType{typeId=4, type=ComponentType}, value={"extra":[{"text":" "},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"تلقا دايموند مدلي "}],"text":""}}
Metadata{id=23, metaType=EntityDataType{typeId=1, type=VarInt}, value=255}
Metadata{id=24, metaType=EntityDataType{typeId=1, type=VarInt}, value=520093696}
Metadata{id=25, metaType=EntityDataType{typeId=0, type=ByteType}, value=63}
Metadata{id=26, metaType=EntityDataType{typeId=0, type=ByteType}, value=1}
[03:45:20 ERROR]: [ViaVersion] (1.19.3->1.19.1) Error:
java.lang.ArrayIndexOutOfBoundsException: null
[03:45:20 ERROR]: [ViaVersion] (1.19.3->1.19.1) An error occurred in entity data handler EntityPacketRewriter1_19_3 for untracked entity type: Metadata{id=10, metaType=EntityDataType{typeId=26, type=Vector3fType}, value=Vector3f[x=0.0, y=0.79999995, z=0.0]}
[03:45:20 ERROR]: [ViaVersion] (1.19.3->1.19.1) Full entity data: Metadata{id=10, metaType=EntityDataType{typeId=26, type=Vector3fType}, value=Vector3f[x=0.0, y=0.79999995, z=0.0]}
Metadata{id=14, metaType=EntityDataType{typeId=0, type=ByteType}, value=1}
Metadata{id=16, metaType=EntityDataType{typeId=2, type=FloatType}, value=32.0}
Metadata{id=22, metaType=EntityDataType{typeId=4, type=ComponentType}, value={"extra":[{"text":" "},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"تلقا دايموند مدلي "}],"text":""}}
Metadata{id=23, metaType=EntityDataType{typeId=1, type=VarInt}, value=255}
Metadata{id=24, metaType=EntityDataType{typeId=1, type=VarInt}, value=520093696}
Metadata{id=25, metaType=EntityDataType{typeId=0, type=ByteType}, value=63}
Metadata{id=26, metaType=EntityDataType{typeId=0, type=ByteType}, value=1}
[03:45:20 ERROR]: [ViaVersion] (1.19.3->1.19.1) Error:
java.lang.ArrayIndexOutOfBoundsException: null
[03:45:38 ERROR]: [ViaVersion] (1.19.3->1.19.1) An error occurred in entity data handler EntityPacketRewriter1_19_3 for untracked entity type: Metadata{id=11, metaType=EntityDataType{typeId=26, type=Vector3fType}, value=Vector3f[x=0.25, y=0.25, z=1.0]}
[03:45:38 ERROR]: [ViaVersion] (1.19.3->1.19.1) Full entity data: Metadata{id=10, metaType=EntityDataType{typeId=26, type=Vector3fType}, value=Vector3f[x=0.0, y=0.79999995, z=0.0]}
Metadata{id=11, metaType=EntityDataType{typeId=26, type=Vector3fType}, value=Vector3f[x=0.25, y=0.25, z=1.0]}
Metadata{id=14, metaType=EntityDataType{typeId=0, type=ByteType}, value=1}
Metadata{id=16, metaType=EntityDataType{typeId=2, type=FloatType}, value=32.0}
Metadata{id=22, metaType=EntityDataType{typeId=4, type=ComponentType}, value={"extra":[{"text":" "},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"كي نجيب اكثر من 5 "}],"text":""}}
Metadata{id=23, metaType=EntityDataType{typeId=1, type=VarInt}, value=255}
Metadata{id=24, metaType=EntityDataType{typeId=1, type=VarInt}, value=520093696}
Metadata{id=25, metaType=EntityDataType{typeId=0, type=ByteType}, value=63}
Metadata{id=26, metaType=EntityDataType{typeId=0, type=ByteType}, value=1}
[03:45:38 ERROR]: [ViaVersion] (1.19.3->1.19.1) Error:
java.lang.ArrayIndexOutOfBoundsException: null
[03:45:38 ERROR]: [ViaVersion] (1.19.3->1.19.1) An error occurred in entity data handler EntityPacketRewriter1_19_3 for untracked entity type: Metadata{id=10, metaType=EntityDataType{typeId=26, type=Vector3fType}, value=Vector3f[x=0.0, y=0.79999995, z=0.0]}
[03:45:38 ERROR]: [ViaVersion] (1.19.3->1.19.1) Full entity data: Metadata{id=10, metaType=EntityDataType{typeId=26, type=Vector3fType}, value=Vector3f[x=0.0, y=0.79999995, z=0.0]}
Metadata{id=14, metaType=EntityDataType{typeId=0, type=ByteType}, value=1}
Metadata{id=16, metaType=EntityDataType{typeId=2, type=FloatType}, value=32.0}
Metadata{id=22, metaType=EntityDataType{typeId=4, type=ComponentType}, value={"extra":[{"text":" "},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"كي نجيب اكثر من 5 "}],"text":""}}
Metadata{id=23, metaType=EntityDataType{typeId=1, type=VarInt}, value=255}
Metadata{id=24, metaType=EntityDataType{typeId=1, type=VarInt}, value=520093696}
Metadata{id=25, metaType=EntityDataType{typeId=0, type=ByteType}, value=63}
Metadata{id=26, metaType=EntityDataType{typeId=0, type=ByteType}, value=1}
[03:45:38 ERROR]: [ViaVersion] (1.19.3->1.19.1) Error:
java.lang.ArrayIndexOutOfBoundsException: null```


### Bug Description

Getting this error for no appearent reason, cause my server to lag 

### Steps to Reproduce

1. Make a 1.20 Server
2. Allow 1.16 with ViaVersion and ViaBackwards

### Expected Behavior

no error

### Additional Server Info

causes server to get killed when high on players

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--17%20%28MC%3A%201.20%29](https://img.shields.io/badge/Platform-git--Paper--17%20%28MC%3A%201.20%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1): 17 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.1)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by bed-dev** [comment]
https://dump.viaversion.com/43bc90b38a167b78e6f5b3b9334b7f836ef989d898c1807db4735c8af8a79db1

**Comment by Barvalg** [comment]
![Platform: git--Paper--17%20%28MC%3A%201.20%29](https://img.shields.io/badge/Platform-git--Paper--17%20%28MC%3A%201.20%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by bed-dev** [comment]
I did update them

https://dump.viaversion.com/43bc90b38a167b78e6f5b3b9334b7f836ef989d898c1807db4735c8af8a79db1

**Comment by Barvalg** [comment]
![Platform: git--Paper--17%20%28MC%3A%201.20%29](https://img.shields.io/badge/Platform-git--Paper--17%20%28MC%3A%201.20%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by bobhenl** [comment]
Why it got closed? I get the error too :(
https://dump.viaversion.com/c880b1aa0f84721f3841ab9f494378d705f5a3e0e71d4ceb3cc3454988eb7917

**Comment by Barvalg** [comment]
![Platform: 1.21--2284--4e55e26%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--2284--4e55e26%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.4-SNAPSHOT): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.4--SNAPSHOT)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump </h3>

**Comment by bobhenl** [comment]
Doesn't look like it was fixed in the devs of ViaBackwards

**Comment by FlorianMichael** [comment]
There is most likely nothing to fix, you have some plugin sending bad data.
