### ISSUE TITLE
The attribute name does not display correctly on 1.21 clients

### ISSUE THREAD

**Issue by kolderz** [ViaVersion/ViaVersion#4005]
### `/viaversion dump` Output

https://dump.viaversion.com/8b9d75919392f5d237f3c98baebf81c1155fffeac3d9eed1cdefe0b0a2d4015a

### Console Error

```
No errors
```

### Bug Description

The attribute name does not display correctly on 1.21 clients

### Steps to Reproduce

1. Login with 1.21 clients.
2. Hover to a modified attribute item.

### Expected Behavior

The attribute name should be displayed correctly.

### Additional Server Info

**1.20.4:**
![javaw_vK9CxTWan5](https://github.com/ViaVersion/ViaVersion/assets/10612667/f3c9c1a1-6b5c-4e35-9bd4-b713e2608653)
**1.21:**
![javaw_M88d6NSVSE](https://github.com/ViaVersion/ViaVersion/assets/10612667/e540a07d-d681-4858-9d3d-016f922cb769)

Item NBT:
```
{AttributeModifiers:[{Amount:10.0d,AttributeName:"minecraft:generic.attack_damage",Name:"minecraft:generic.attack_damage",Operation:0,Slot:"mainhand",UUID:[I;-208144461,2122793620,-1431113012,1708301860]},{Amount:2.0d,AttributeName:"minecraft:generic.attack_speed",Name:"minecraft:generic.attack_speed",Operation:0,Slot:"mainhand",UUID:[I;-1914627948,1409369325,-1259528422,1071465362]},{Amount:10.0d,AttributeName:"minecraft:generic.max_health",Name:"minecraft:generic.max_health",Operation:0,Slot:"mainhand",UUID:[I;-1860416135,-2065480721,-1076678235,88262164]},{Amount:1.0d,AttributeName:"minecraft:generic.movement_speed",Name:"minecraft:generic.movement_speed",Operation:0,Slot:"mainhand",UUID:[I;-1794929302,1716406631,-2084817793,1662071154]}],Damage:0,display:{Name:'{"text":"","extra":[{"text":"Test Sword","italic":false,"color":"aqua"}]}'}}
```

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2176%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--2176%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by PEKKAMC** [comment]
This also happens to me

**Comment by emanondev** [comment]
Confirmed 

My tests showed that Attribute Speed is displayed as Max Absorption when client is 1.21 and server is 1.20.1 or 1.20.4 (spigot/paper/purpur)

I also logged in on 1.20.4 server with 1.20.4 client and the translation issue was fixed
