### ISSUE TITLE
[ViaVersion 1.21] Inventory related disconnections

### ISSUE THREAD

**Issue by ThatMG393** [ViaVersion/ViaVersion#4012]
### `/viaversion dump` Output

https://dump.viaversion.com/c8c978cc4496b01c00516314df9e3aea698ef231c9345ef8fc7ed7453711e9e4

### Console Error

https://mclo.gs/lKbVbGg

### Bug Description

Inventory related disconnection (your game crashes instead when you have ViaVersion & ViaBackwards 
 5.0.2-SNAPSHOT installed instead of the server)

### Steps to Reproduce

1. Login to a MC 1.21 Server with a 1.20.4 (never tested on older clients)
2. Creative: just open your inventory.
    Survival: open your inventory and click an item.
3. Disconnected

### Expected Behavior

I can drag my item to any other inventory spot.

### Additional Server Info

ViaFabric Version: 0.14.4+main74
ViaBackwards Version: 5.0.2-SNAPSHOT

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.4.14+74--main](https://img.shields.io/badge/Platform-0.4.14+74--main-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): 12 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-12%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).<br>Put the jars into the mod folder.<br>In case the issue still persists send the new dump and the issue will be reopened</h3>
