### ISSUE TITLE
Internal Exception : io.netty.handler.codec.DecoderException: java.io.IOException: Packet configuration/0 (class_2658) was larger than I expected, found 229 bytes extra whilst relading packet 0

### ISSUE THREAD

**Issue by ServertheLord** [ViaVersion/ViaVersion#4016]
### `/viaversion dump` Output

https: //dump.viaversion.com/7fbf66e13ce4f3328516fe64845f653269719ce06c8154dcc54a97fd99c66c7c

### Console Error

在1.20.1以上版本是进入游戏时会显示错误信息，如题

### Bug Description

用1.20.1以上的版本进入使用Via5.0.1版本的服务器

### Steps to Reproduce

1.用1.20.1以上的版本进入使用Via5.0.1版本的服务器

### Expected Behavior

在什么版本都应该进入服务器

### Additional Server Info

我使用的时VIA,VR和VB三件套，如果在客户端上加入Kr这个Mod就可以进入服务器

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Also bug reports only in english
