### ISSUE TITLE
Can't join with 1.20.4 client to 1.12.2 server

### ISSUE THREAD

**Issue by JULJERYT** [ViaVersion/ViaVersion#4017]
### `/viaversion dump` Output

https://dump.viaversion.com/696b54aaa2861be739dbc78ae499ae01edaca3b783e240d88de0727c2d21687e

### Console Error

```
https://mclo.gs/WpMc167
```

### Bug Description

Can't join with 1.20.4 client to 1.12.2 server

### Steps to Reproduce

1. Create 1.12.2 server 
2. Install newest ViaVersion
3. Join with 1.20.4 client
4. And you cant join with reason: Disconnected or Internal server error

### Expected Behavior

I should join to server without any problems

### Additional Server Info

I use 1.12.2 server on PaperBin with plugins: BedWars1058, Citizens, GrimAC, LuckPerms, PlaceholderAPI, ProtocolLib, SlimeWorldManager, ViaVersion, WorldEdit

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Jo0001** [comment]
This is caused by one of your plugins (works fine for me with just Via installed)

**Comment by JULJERYT** [comment]
kk i'll check

**Comment by JULJERYT** [comment]
it was protocol lib btw

**Comment by JULJERYT** [comment]
i just checked and it was protocol lib. thanks for help @Jo0001 

> This is caused by one of your plugins
