### ISSUE TITLE
Internal Exception : io.netty.handler.codec.DecoderException: java.io.IOException: Packet configuration/0 (class_2658) was larger than I expected, found 229 bytes extra whilst relading packet 0

### ISSUE THREAD

**Issue by ServertheLord** [ViaVersion/ViaVersion#4019]
### `/viaversion dump` Output

https: //dump.viaversion.com/7fbf66e13ce4f3328516fe64845f653269719ce06c8154dcc54a97fd99c66c7c

### Console Error

In versions 1.20.1 and above, an error message will be displayed when entering the game, such as the question

### Bug Description

Use version 1.20.1 or later to enter a server using Via 5.0.2

### Steps to Reproduce

1. Use version 1.20.1 or later to enter the server using Via 5.0.2

### Expected Behavior

In what version should go into the server

### Additional Server Info

I use a three-piece set of VIA, VR and VB, and if I add Kr as a mod on the client, I can enter the server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Please fill out the issue template correctly, you need to provide full error logs and also using dev builds.
