### ISSUE TITLE
Error in protocol, in remap of combat kill

### ISSUE THREAD

**Issue by Sulphinx** [ViaVersion/ViaVersion#4021]
### `/viaversion dump` Output

https://dump.viaversion.com/58546348e3f81530d6759903762dd78b878909e8e2a2f67c36ec424ce8e487b6

### Console Error

```
https://mclo.gs/0KEh7Lf
```

### Bug Description

I have no idea how it happened to be honest. Might have been a player killing a mob

### Steps to Reproduce

Like i said above.

### Expected Behavior

This not spamming my console.

### Additional Server Info

I use via, viabackwards, viarewind and protocollib on 1.8 with a 1.20.4 client
VIAVERSION 4.9.2, due to the java compiling of the newer versions not being compatible with paper 1.8(java 8)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--445%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.9.2)-Outdated!-red?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(3.1.2)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
