### ISSUE TITLE
Unsupported class file major version 61 with Java 17

### ISSUE THREAD

**Issue by kutu-dev** [ViaVersion/ViaVersion#4022]
### `/viaversion dump` Output

https://dump.viaversion.com/902369a52ae62234305206b3e875bb41fbb79acffe872a59876fc1433aaf59a7

### Console Error

Multiple stacktrace errors on lots of CLASS file when starting the server, in the lines of:

```
[00:19:45 ERROR]: Fatal error trying to convert ViaVersion v5.0.2-SNAPSHOT:com/viaversion/viaversion/util/ArrayUtil.class
java.lang.IllegalArgumentException: Unsupported class file major version 61.
```
****

### Bug Description

The log is filled with lots of stacktrace errors about not be able to use CLASS files from the plugin but the plugin is still able to run without any issue beside this one. 

### Steps to Reproduce

1. Start a Paper 1.13.2 server with Java 17 and the `Paper.IgnoreJavaVersion` flag set to true to allow versions bigger than Java 11.
2. Wait for the plugin to be loaded.

### Expected Behavior

The log be clear and free of Java version errors.

### Additional Server Info

Velocity proxy is being used. No other plugins are loaded on the Paper server instance.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--657%20%28MC%3A%201.13.2%29](https://img.shields.io/badge/Platform-git--Paper--657%20%28MC%3A%201.13.2%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Not a ViaVersion bug, This is caused by server software not properly utilizing java 17. *(also 1.16.5 works best with flag)*

**Comment by SnowSakuraKo** [comment]
I got the same issue on Paper 1.15.2 and Viaversion 5.2.1. Any solutions?

![Image](https://github.com/user-attachments/assets/a9e8eb8c-09ee-4bdf-bf4f-17ce23d36468)

**Comment by HowardZHY** [comment]
> I got the same issue on Paper 1.15.2 and Viaversion 5.2.1. Any solutions? ![Image](https://github.com/user-attachments/assets/a9e8eb8c-09ee-4bdf-bf4f-17ce23d36468)
> 
> java version ![Image](https://github.com/user-attachments/assets/62f27f88-75ab-4744-aaed-19cc823cd546)
> 
> Added 'Paper.IgnoreJavaVersion=true' as well ![Image](https://github.com/user-attachments/assets/e5ac5e52-69d1-41e4-8222-6ebbe16a7f52)

https://ci.viaversion.com/job/ViaVersion-Java8/

**Comment by SnowSakuraKo** [comment]
> > I got the same issue on Paper 1.15.2 and Viaversion 5.2.1. Any solutions? ![Image](https://github.com/user-attachments/assets/a9e8eb8c-09ee-4bdf-bf4f-17ce23d36468)
> > java version ![Image](https://github.com/user-attachments/assets/62f27f88-75ab-4744-aaed-19cc823cd546)
> > Added 'Paper.IgnoreJavaVersion=true' as well ![Image](https://github.com/user-attachments/assets/e5ac5e52-69d1-41e4-8222-6ebbe16a7f52)
> 
> 1.15.2 Paper doesn't support J17, use https://ci.viaversion.com/job/ViaVersion-Java8/

Oh god that works, thx! You saved me.
![Image](https://github.com/user-attachments/assets/07cfaf31-4214-4403-aaa7-4b827dcca229)

No errors now.
![Image](https://github.com/user-attachments/assets/505e57d1-dc56-4cc5-bfa6-94e8fbca6a87)
