### ISSUE TITLE
Free shulkerban 

### ISSUE THREAD

**Issue by NinjaLegendmc** [ViaVersion/ViaVersion#4023]
### `/viaversion dump` Output

https://dump.viaversion.com/aa56d623f3936fb8f0de0d2887eb15df7a29daaa2dc92e1920982ffb430eee85

### Console Error

???????????

### Bug Description

Hi so my issue that when update Minecraft server to 1.21 and update viaversion and viabackwords than after join the game and open inventory with a shulkerbox that's has normal items than server just kick with this message 
![Screenshot_20240716_122930_net kdt pojavlaunch](https://github.com/user-attachments/assets/420ef2ba-4833-4c28-aa2c-c65c0d2994e4)
And also I join viaversion discord for help and in their steps I had do and looks like viabackwords issue 

### Steps to Reproduce

1.Login in server with 1.20.4 client
2.open inventory with a shulkerbox that's has some normal Armor
3.server kick with this message 
![Screenshot_20240716_122930_net kdt pojavlaunch](https://github.com/user-attachments/assets/6e857788-c050-40f8-ab86-85e9ae35dbdc)

### Expected Behavior

Server kick me after update server version to 1.21 and update viaversion and viabackwords both than if I join with 1.20.4 or others client version than server kick me if I open inventory with a shulkerbox that's have some normal items 

### Additional Server Info

I had even Remove all plugin expect viaversion and viabackwords 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--81--ceeb8c1%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--81--ceeb8c1%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by NinjaLegendmc** [comment]
> ![Platform: 1.21--81--ceeb8c1%20%28MC%3A%201.21%29](https://camo.githubusercontent.com/c20d75d7bc87ea7f0809f65390b316a8600cd101b4ca04c0acb879e91d505381/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d312e32312d2d38312d2d636565623863312532302532384d43253341253230312e32312532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://camo.githubusercontent.com/2c8547fdcf5aa141cef34724b329983c4d5a5275e0b876392b8d42065df11cf0/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028352e302e322d2d534e415053484f54292d4576656e253230776974682532306d61737465722d627269676874677265656e3f7374796c653d666c61742d737175617265) ![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://camo.githubusercontent.com/45039efeb98c17d1393cb2a12081ec85ef0f105f3b615682595dcd2bd8727310/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028352e302e322d2d534e415053484f54292d4576656e253230776974682532306d61737465722d627269676874677265656e3f7374796c653d666c61742d737175617265)

What?

**Comment by kennytv** [comment]
Fixed

**Comment by NinjaLegendmc** [comment]
> Fixed

Thx
