### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by yeying-xingchen** [ViaVersion/ViaVersion#4027]
### `/viaversion dump` Output

Cannot execute because unable to join the server

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

Error.
![Uploading Image_1721393613528.png…]()

### Steps to Reproduce

Go to Server.

### Expected Behavior

Go to server.

### Additional Server Info

Velocity

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>
