### ISSUE TITLE
Protocol error with ItemDisplay and ArmorTrim, from 1.19.4 with feature enabled to 1.21

### ISSUE THREAD

**Issue by TerraMiner** [ViaVersion/ViaVersion#4028]
### `/viaversion dump` Output

https://dump.viaversion.com/d50eee59bb61814da634d12cf0bec15b50a57bf72405b2c2d55468a173d8f921

### Console Error

no server side error, but exist client side
https://mclo.gs/O2T63JG - with item display
https://mclo.gs/qL2krq6 - equip armor with ward trim

### Bug Description

Disconnecting when switching to armor with the Ward pattern on version 1.19.4 with the datapack feature enabled. Also, disconnects after summoning an item display with specific item data on index 8.

### Steps to Reproduce

1. Just create a server on version 1.19.4, enabling features to reproduce 1.20 features. Then, run the client on version 1.21 and try looking at a body that changes its equipment to armor with the Ward trim.

2. Also, summon an item display with an item on the same 1.19.4 version.

### Expected Behavior

I think its obviously

### Additional Server Info

The same problem can be seen on the release version of the plugin, 5.0.1. 
I'm using 5.0.2 alpha because I hoped that the problem would be solved.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--SlimeWorldManager--15060%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--SlimeWorldManager--15060%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Error fetching commit data](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Error%20fetching%20commit%20data-lightgray?style=flat-square) </br>

**Comment by kennytv** [comment]
Please try again with the latest ci build
