### ISSUE TITLE
ConsoleSpam

### ISSUE THREAD

**Issue by tncc2k** [ViaVersion/ViaVersion#4031]
### `/viaversion dump` Output

https://dump.viaversion.com/93b44f4e495bbcd4c618cc8c6f9d1f3ea3a07b6b2d8e3319fce5fcbe7fef6e9e

### Console Error

https://mclo.gs/UoWQZbc

### Bug Description

![image](https://github.com/user-attachments/assets/bf4c8f0c-598e-472a-abb4-d3b91a9d3e50)

### Steps to Reproduce

I used version 1.12.2 to test hacking
And spam results on console

### Expected Behavior

Why does the hack cause viaversion spam on the console?
I hope this is fixed

### Additional Server Info

paper-1.20.6-148
ViaBackwards-5.0.1
ViaRewind-4.0.1
ViaVersion-5.0.1
ProtocolLib DEV
All settings are default

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--148--20f5165%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--148--20f5165%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1): 34 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.1)-34%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.1): 20 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.1)-20%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(4.0.1): 13 commits behind master](https://img.shields.io/badge/ViaRewind%20(4.0.1)-13%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
