### ISSUE TITLE
ERROR IN Protocol1_21To1_20_5 IN REMAP OF CONTAINER_SET_CONTENT (0x13)

### ISSUE THREAD

**Issue by addpromax** [ViaVersion/ViaVersion#4039]
### `/viaversion dump` Output

https://dump.viaversion.com/7e786cf21f04a252df9132ec8b0819bad0fb3f19bf3141bfb20842d2bdf6b3c6

### Console Error

```
Put the mclo.gs link or text here.
```
https://mclo.gs/lq0zl5q

### Bug Description

Join server will 
![QQ_1721707407447](https://github.com/user-attachments/assets/9bab3815-4f92-4a74-994b-c1192fc2807c)

### Steps to Reproduce

1.Join with 1.20.4
2.Can't join

### Expected Behavior

Join server success

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--2272--b2d1fea%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--2272--b2d1fea%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
