### ISSUE TITLE
ERROR IN Protocol1_20_3To1_20_5 IN REMAP OF CHAT (0x06)

### ISSUE THREAD

**Issue by Waterman1001** [ViaVersion/ViaVersion#4040]
### `/viaversion dump` Output

https://dump.viaversion.com/89277d05b1cc28d4c41265fb7adb1d9a3208b2dd33a50d39b0b2266a6c7a0297

### Console Error

```
https://mclo.gs/G2fwcMy
```

### Bug Description

On certain players joining the server, they get kicked immediately on chat and I receive above error in the console.
It states: [ViaVersion] ERROR IN Protocol1_20_3To1_20_5 IN REMAP OF CHAT (0x06)

### Steps to Reproduce

1. Join the server
2. Type something in chat
3. Get kicked

### Expected Behavior

I expected to not get kicked

### Additional Server Info

No, I am using Paper 1.20.4 with ViaVersion 5.0.1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Waterman1001** [comment]
I tried the latest DevBuild now, but the issue still persists.
This is the latest log: https://mclo.gs/xCcDrHA
This is the new dump: https://dump.viaversion.com/bbd32710dae1368fc1b7643ed7d9a9475ff3b4c0c4bd872c3c2fbd16bbb9fd49

**Comment by Barvalg** [comment]
![Platform: git--Paper--497%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--497%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
I can't reproduce this issue, try to remove plugins until it works / try a server without any plugins except ViaVersion.

**Comment by Waterman1001** [comment]
It turns out it occurs for players joining the server using EnderChat
application. Perhaps there is the problem?

Op wo 24 jul. 2024 16:42 schreef EnZaXD ***@***.***>:

**Comment by FlorianMichael** [comment]
Most likely EnderChat is sending invalid data, does it work on vanilla servers?
