### ISSUE TITLE
[1.20.1->1.21] Cant join 1.21 server from 1.20.1 client

### ISSUE THREAD

**Issue by Rozbiynk** [ViaVersion/ViaVersion#4041]
### `/viaversion dump` Output

https://dump.viaversion.com/7bac4863fdf930a83b2edd2ffe0f5f12000792eb076c790ad1a15612ea4e1f22

### Console Error

```
Put the mclo.gs link or text here.
```
https://mclo.gs/OrvrcdE

### Bug Description

Cant join from 1.20.1 using viaFabric and ViaBackwards

### Steps to Reproduce

1. Download ViaFabric 0.4.14
2. Download ViaBackwards 5.0.2
3. Start 1.21 server
4. Join from 1.20.1 client
5. See error

### Expected Behavior

I can join to 1.21 from 1.20.1 using ViaBackwards

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.4.14+74--main](https://img.shields.io/badge/Platform-0.4.14+74--main-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): 32 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-32%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).<br>Put the jars into the mod folder.<br>In case the issue still persists send the new dump and the issue will be reopened</h3>
