### ISSUE TITLE
Falied to decode packet 'clientbound/minecraft:set_entity_data'

### ISSUE THREAD

**Issue by KxttyKxt** [ViaVersion/ViaVersion#4042]
### `/viaversion dump` Output

https://dump.viaversion.com/92156de62baad93755e9d90c8af882736e53c908b976b40c42dfa7fda19828cf

### Console Error

```
https://mclo.gs/yQJsIAR
```

### Bug Description

| Software | Version |
| ---------- | -------- |
| Prism Launcher | 8.4 |
| Minecraft | 1.21.0 |
| Fabric Loader | 0.16.0 |
| Fabric API | 0.100.7+1.21 |
| ViaFabricPlus | 3.4.3 |
| VFP CI Build | Latest, #591 |

Connecting to `server.playmonumenta.com` with any compatible server version (1.19.4 - 1.20.2) causes a near-instant disconnect with the message:
`Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:set_entity_data'`

Using the latest build of ViaFabricPlus from the CI site [[build #591]](https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/lastBuild/) did not fix this issue.

![image](https://github.com/user-attachments/assets/d9038d38-585b-45ac-a9e2-1ae6287a3ac3)
![image](https://github.com/user-attachments/assets/943d641d-5818-4fad-b260-eeaad8c0ee7f)
![image](https://github.com/user-attachments/assets/318f45c3-42aa-4abe-95a5-2c449ca3139d)

### Steps to Reproduce

1. Open a modpack with ViaFabricPlus on Minecraft 1.21.
2. Add the server `server.playmonumenta.com` to your server list.
3. In the edit menu for that server listing, press the version button in the top right.
4. Change it to any version between 1.19.4 and 1.20.2 (inclusive).
5. You may be able to get through the tutorial just fine, but immediately after finishing the tutorial and teleporting elsewhere, you will disconnect and _always_ disconnect with the previously mentioned message.

### Expected Behavior

On step 5, instead of disconnecting, the client should stay connected to the server as intended.

### Additional Server Info

I do not own the server on which I was playing. From [what I can tell](https://minecraft-mp.com/server-s204292) Monumenta runs on Spigot with Bungeecord as a proxy.
Monumenta does have a custom texture pack, sound pack, [website](https://playmonumenta.com/), and [wiki](https://monumenta.wiki.gg/wiki/Monumenta_Wiki), all of which can be found on [PlanetMinecraft](https://www.planetminecraft.com/server/monumenta/).

I use a modified version of Fabulously Optimized 6.0.0-beta2 with some mods added for clientside or hud tweaks.
In my F3 menu, these mods appear:
- Sodium
- Iris
- EntityCulling
- ViaFabricPlus
- Presence Footsteps
- ModernFix
- Dynamic FPS

Other mods that may affect server connectivity/packets:
- [Bad Packets](https://modrinth.com/mod/badpackets)
- [Disconnect Packet Fix](https://modrinth.com/mod/disconnect-packet-fix), which does fix a similar issue on the server side.
- [No Chat Reports](https://modrinth.com/mod/no-chat-reports)
- [No Telemetry](https://modrinth.com/mod/no-telemetry)
- [Packet Exception Logger](https://modrinth.com/mod/packet-exception-logger)

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kripypastishka** [comment]
the same problem, how can I fix it?

**Comment by florianreuth** [comment]
Update ViaFabric & ViaVersion, if you still have issues make a new issue or join our discord server.
