### ISSUE TITLE
(1.20.4) 1.20.5+ players can't swim or use boats, some report lava looks like water.

### ISSUE THREAD

**Issue by Valorless** [ViaVersion/ViaVersion#4044]
### `/viaversion dump` Output

https://dump.viaversion.com/0a89b484eb6e5bd3c09aa7e2b9493411435fd820cf26a8d0b34c6a5c2af9fabf

### Console Error

N/A

### Bug Description

Clients 1.20.5 -> 1.21 Are unable to swim but still drown. (This includes lava, and the vignette/fog is gone)
If they use boats, it falls to the ocean floor when they move.
In addition, some players report that lava looks like water. (Unable to replicate this myself)

Server running 1.20.4.

### Steps to Reproduce

Join the 1.20.4 server with ViaVersion 5.0.0 or higher, using a client 1.20.5 or higher.
Go into water.
Drown.

### Expected Behavior

Swim

## Paper Plugins:
- FancyHolograms
- MarriageMaster
## Bukkit Plugins:
- AdvancedBan, 
- AdvancedEnchantments, 
- AdvancedMobArena, 
- AdvancedSpyInventory, 
- AlonsoTags, 
- ArmorStandEditor, 
- ArtMap, 
- Autorank, 
- Citizens, 
- ClearLag, 
- ClearLagTimer, 
- CMILib, 
- Condense, 
- ConsoleSpamFix, 
- CoreProtect, 
- CreativeGates, 
- CustomCommands, 
- DeathRoll, 
- DecentHolograms, 
- DeluxeMenus, 
- DiscordBans, 
- DiscordChatMonitor, 
- DoorsReloaded, 
- dynmap, 
- Dynmap-GriefPrevention, 
- EpicRename, 
- Essentials, 
- EssentialsChat, 
- EssentialsSpawn, 
- ExcellentCrates, 
- FarmControl, 
- FastAsyncWorldEdit, 
- *Garbage_Collector, 
- GCore, Graves, 
- GriefPrevention, 
- GSit, 
- Harbor, 
- HavenBags, 
- HavenDisplays, 
- HavenElytra, 
- HavenFlight, 
- HavenHats, 
- HavenLeaderboards, 
- HavenMessages, 
- HavenPack, 
- HavenRecipes, 
- HavenSkies, 
- HavenStatTrackers, 
- HavenTransmog, 
- HavenTweaks, 
- HeadDB, 
- HiberniaDiscord, 
- InteractionVisualizer, 
- InteractiveChat, 
- InventoryRollbackPlus, 
- InventoryTooltips, 
- ItemEdit, 
- JakesRTP, 
- Jobs, 
- LuckPerms, 
- MassiveCore, 
- *MaterialDynmap, 
- mcMMO, 
- MendingEnchant, 
- MobArena, 
- Multiverse-Core, 
- Multiverse-NetherPortals, 
- Multiverse-Portals, 
- NBTAPI, 
- NexEngine, 
- nightcore, 
- Not-Too-Expensive,
- Oraxen, 
- *PixelMOTD, 
- PlaceholderAPI, 
- PlayerBiomes, 
- PlayerKits2,
- PlayerStats, 
- PlayerWarps, 
- PlugManX,
- ProtocolLib, 
- QuickShop, 
- RavenGM, 
- ReFrame, 
- RHLeafDecay, 
- Sentinel, 
- Shopkeepers, 
- ShopkeepersAddon, 
- SilkSpawners_v2, 
- spark, 
- Statz, 
- TAB, 
- ValorlessUpdateChecker, 
- ValorlessUtils, 
- Vault, 
- ViaBackwards, 
- ViaVersion, 
- ViaVersionStatus, 
- VoidGen, 
- Votifier, 
- VotingPlugin, 
- Vulcan, 
- *WebServer, 
- WorldBorder, 
- WorldGuard, 
- XPBoost

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--497%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--497%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Can't reproduce. This is either caused by third-party plugins on your server or bad third-party clients. *(most likely both in this case)*
