### ISSUE TITLE
Failed to decode packet 'clientbound/minecraft:game_profile' #3852

### ISSUE THREAD

**Issue by f4ursev7n** [ViaVersion/ViaVersion#4045]
### `/viaversion dump` Output

https://dump.viaversion.com/700e857b50f733fced3f535579a8597fb09739ea526dfbbb7d8d41725a4636ee

### Console Error

[```
Put the mclo.gs link or text here.
```
](https://mclo.gs/i5RwAS2)

### Bug Description

Logging in with 1.8.x says Failed to decode packet 'clientbound/minecraft:game_profile' #3852 but with new versions it works perfectly 

### Steps to Reproduce

Login with a 1.8.x client
Create 1.8.8 spigot server with ViaVersion
Join 


### Expected Behavior

users join with 1.8.x and up

### Additional Server Info

Bungee with no plugins

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Spigot--6c9b0a1--de5c261%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--Spigot--6c9b0a1--de5c261%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(5.0.0)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
