### ISSUE TITLE
Duplication bug through horse

### ISSUE THREAD

**Issue by EagL3-GIT** [ViaVersion/ViaVersion#4046]
### `/viaversion dump` Output

-

### Console Error

-

### Bug Description

You can duplicate items with horse using 1.21 client on 1.20.4 (actually just lower version than 1.21) server.

### Steps to Reproduce

0. Run paper server with lower version than 1.21 (1.20.4 in my case)
1. Mount on tamed horse on 1.21 client version
2. Open his inventory
3: Shift + click items to his inventory from yours and back, again and again
4. Leave the horse and u should have duplicates in your inventory, some are fake items
but some are real duplicated items

### Expected Behavior

U shouldnt be able to put items there cause those slots in horse doesnt exist in lower versions than 1.21

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Kichura** [comment]
This issue does not have any viaversion dumps provided, therefore this cannot be investigated properly.

**Comment by EagL3-GIT** [comment]
I am not gonna upload that dump containing my whole list of plugins. Take it or leave it;)
// ViaBackwards and ViaVersion version is 5.0.1

**Comment by Kichura** [comment]
cannot reproduce.

**Comment by FlorianMichael** [comment]
Try if you can also reproduce this on a clean installation just with ViaVersion installed.
