### ISSUE TITLE
DecoderException occurs when trying to log in to 1.20.5=>1.18.2

### ISSUE THREAD

**Issue by snowpegeon** [ViaVersion/ViaVersion#4047]
### `/viaversion dump` Output

https://dump.viaversion.com/64e7d8a762516dfa258a2e0103efbe7048540f1fff0306ddaa49ca6782e86128

### Console Error

[21:00:33] [Server thread/INFO]: 【userId】lost connection: Internal Exception: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.api.protocol.remapper.PacketHandler$$Lambda$5836/0x000001f881c40450, Source 2: com.viaversion.viaversion.protocols.v1_20to1_20_2.Protocol1_20To1_20_2$$Lambda$5652/0x000001f881c120e0, Source 1: com.viaversion.viaversion.protocols.v1_20_2to1_20_3.rewriter.EntityPacketRewriter1_20_3$2 (Anonymous)

### Bug Description

DecoderException occurs when trying to log in to 1.20.5=>1.18.2 server.
If you use 1.20.4 or earlier, you can log in without any problems.

error message on client
![image](https://github.com/user-attachments/assets/4629fe1a-c08a-45a4-8850-701e4da6b3a0)

### Steps to Reproduce

Login to 1.20.5=>1.18.2.

### Expected Behavior

Users can log in to the target server.

### Additional Server Info

・ViaVersion　5.0.1
・paper-1.18.2-386

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--386%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Paper--386%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by snowpegeon** [comment]
https://ci.viaversion.com/ 
https://hangar.papermc.io/ViaVersion/ViaVersion/versions
↑＋478 used
I tried using the jar obtained from the above site, but the same problem occurs.
The first dump you paste will be the one obtained from Jenkins.

Here is the dump executed at +478.
https://dump.viaversion.com/2da64436c7dd08bf767ce4f6145679ea4ea473eaa28f718add70423cf449b4a6

**Comment by Barvalg** [comment]
![Platform: git--Paper--386%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Paper--386%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Please provide the full log file and not only parts of it.

**Comment by snowpegeon** [comment]
Oh, I'm sorry. Apparently this problem was caused by some other plugin doing something wrong.
I was able to solve it myself. Thank you for participating in the survey.
