### ISSUE TITLE
Bug: Llama carpets not showing up

### ISSUE THREAD

**Issue by onebeastchris** [ViaVersion/ViaVersion#4048]
### `/viaversion dump` Output

 https://dump.viaversion.com/9ebebbc99d1d5d42d000e3b44034faa960c72eff9cc8272bc2f9ca35b6ed9dcf

### Console Error

No console errors, purely visual

### Bug Description

Carpets on Llamas don't show up unless you interact with them
![image](https://github.com/user-attachments/assets/3ad20141-bd71-47e3-a808-50ff93d97d20)
![image](https://github.com/user-attachments/assets/c9325942-8a3c-4b20-8a0c-bfbbcfa57353)

### Steps to Reproduce

1. Login with a 1.21 Java client
2. Spawn/Find a Llama, tame it, equip a carpet
3. Disconnect
4. Upon reconnect: observe that no carpet seems to be equipped

### Expected Behavior

Carpet should be visible

### Additional Server Info

Paper 1.20.4, also happens without other plugins. Originally discovered in https://github.com/GeyserMC/Geyser/issues/4896

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--484%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--484%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
