### ISSUE TITLE
Console spam 1.8

### ISSUE THREAD

**Issue by Henriiig** [ViaVersion/ViaVersion#4055]
### `/viaversion dump` Output

https://dump.viaversion.com/21fed46d958de7ba4724ef4ac211c719bd862c44d01f7c6f6e2a0f6872b27967

### Console Error

https://pastebin.com/NepL1g8y

### Bug Description

Console spam

### Steps to Reproduce

use flamepaper 1.8.8 on java 21 and have newest version of viaversion. Don't know whats exactly causing the spam.

### Expected Behavior

No spam

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--cbe632ca%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--cbe632ca%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1): 48 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.1)-48%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Henriiig** [comment]
https://dump.viaversion.com/af1ac780d1a17aea8f0825428293d2ba7a7368e543a97bef0a856e4c3fe878b6

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--cbe632ca%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--cbe632ca%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1): 48 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.1)-48%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Henriiig** [comment]
I am using viaversion 5.01 and it is the newest version wtf?
