### ISSUE TITLE
Protocols?

### ISSUE THREAD

**Issue by TrixzyMc** [ViaVersion/ViaVersion#4056]
### `/viaversion dump` Output

https://dump.viaversion.com/b7446789c0093e970600371cedd6dabeeaadd2b87244777449400b5aa65d9bad

### Console Error

https://mclo.gs/C3fvdKv

### Bug Description

Got kicked for sum

### Steps to Reproduce

/reload confirm, Creeper exploded

### Expected Behavior

Creeper exploded

### Additional Server Info

Paper Serv

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--496%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--496%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.1): 48 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.1)-48%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>broken_jar</details>

**Comment by Kichura** [comment]
`/reload confirm` is not supported and never will be, please consider restarting your server next time instead.
