### ISSUE TITLE
Error at other version

### ISSUE THREAD

**Issue by DemoVPS69420** [ViaVersion/ViaVersion#4057]
### `/viaversion dump` Output

https://dump.viaversion.com/23a0b1a23526c1c7c8052319470538ad6bb704ddcb71ef1b197541da31eedd9e

### Console Error

Nothing happened, only error for client-side

### Bug Description

Everyone will got kick out if they using other version (not 1.20.6)

### Steps to Reproduce

Just go to the nether and and the bug will happened

### Expected Behavior

![Screenshot_2024-07-28_171908](https://github.com/user-attachments/assets/bcde22e0-b188-4b74-8efb-51e2333ec939)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--2233--0d6766e%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--2233--0d6766e%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.2): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Provide the server log please

**Comment by DemoVPS69420** [comment]
> Provide the server log please

https://mclo.gs/FJUH18Q

**Comment by Kichura** [comment]
Cannot reproduce:
![a](https://github.com/user-attachments/assets/4668433e-3d5f-463a-bfcf-03ff812177c6)

Please check which third-party plugin is causing the nether transition to fail and also check your server for any bad world saves.

**Comment by kennytv** [comment]
[4057](https://github.com/ViaVersion/ViaBackwards/commit/b4a4b540cc4c9227855b16e8106d6f82a29ed61b)
