### ISSUE TITLE
internal exception: io.netty.handler.codec.decoderexception:java.io.io.ioexception:packet configuration/clientbound/minecraft:custom_payload(class_2658) was larger than i expected, found 229 bytes extra whilst reading packet clitbound/minecraft:custom_payload

### ISSUE THREAD

**Issue by ServertheLord** [ViaVersion/ViaVersion#4058]
### `/viaversion dump` Output

https://dump.viaversion.com/645cdfb2ce6da313863fd5c0d26f7dd8d1733bc74a6e04d0919c298222e331de

### Console Error

UUID of player WERTYUS11 is a47ed900-4505-3436-8555-a2bd2e20226f
[15:49:02 INFO]: com.mojang.authlib.GameProfile@273ce1b5[id=a47ed900-4505-3436-8555-a2bd2e20226f,name=WERTYUS11,properties={textures=[Property[name=textures, value=
ewogICJ0aW1lc3RhbXAiIDogMTcxNTQ4NzEzMzgwMiwKICAicHJvZmlsZUlkIiA6ICIxMmM5NWJmZjVjYzI0Mjc1OWVjYTJmOWQwMjcwOTRjNyIsCiAgInByb2ZpbGVOYW1lIiA6ICJXRVJUWVVTMTEiLAogICJzaWdu
YXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmQ4ZWU3YjQxZjVlNGRi
Y2E2YTNlZDQ2YWVkNGQ1ODUzYjdmNjRjMWM0YTQxMjA4ZTRmY2VlYmU3ZjgyNzYxYiIKICAgIH0KICB9Cn0=, signature=Vd5yJUtnYfEzi6d88BonMEfrpio09ei/ya8sUUfJ3VSSve43xjAchMa5HosVeipTkd/w
6fPZDaw/MMMyriAcfs65EtyND6dsWAtmCbGosLC22tAFlsIWpdTLHj62LboTpRMs8bci2OVaCWFvhE4HLtrjUdf4xI66Zv1qyOLo8zpb5Bupz0Zv23eNAvUSYc1OxEmIUBvmSWeBtmsvayUk6U0utNRFrXY53QbIqMVe
euUsg0apaBorOyZ2/r1Lq/+CC1uK+i8yrikNRTG+1tAR1THQzFQxPE58915175Urtg/ikrdezOIkgWvYj6JtnSn1oaibAPm+xV+B7B87nJHwtMmMZ7URiCK08T/pCHHilMd117GUkSkCJ7XvX2tY0H69F2k+7SFKm2Tx
QVWNbG3qyd8nTSYUxAqaTLQ/4e7tzoyH1Jq+KdSFqTFIqybDNaI6/CaXHVeL7vA+3YUIXOLYvv1Ds2wEBhku76CKaJCxJra0xUtjSrNsZYEnCyO9MHIMz0VQ8cSl43uj0KMSn67QvC3iwok1sL4dhsxCHD4jHsMIA3Cy
7LCFiZkR3kB1CmFYtudpfoS3ebVcCN4GYPh/EN9B6dZL7mMu7LtZtx0Dt5+P7XJUXauNNqs7up093gHEOSm2gLTCmgqBA5S2M8KBxSALph0RDyv+8Jni/nL/iFU=]]}] lost connection: Disconnected

### Bug Description

internal exception: io.netty.handler.codec.decoderexception:java.io.io.ioexception:packet configuration/clientbound/minecraft:custom_payload(class_2658) was larger than i expected, found 229 bytes extra whilst reading packet clitbound/minecraft:custom_payload

### Steps to Reproduce

Enter the game when using versions 1.20.6 and 1.21

### Expected Behavior

Enter the game normally

### Additional Server Info

1.BungeeCord and via vb vr

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--423%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--423%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.2): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.2): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.2)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by dshimen** [comment]
I can confirm this bug is present i latest version and wasn't present in build 285 for example. 

Players on 1.20.4 are getting kicked. (My server version in purpur 1.21 build 2276)

**Comment by kennytv** [comment]
Try with the latest releases and make sure you only have Via plugins on the backend, not the proxy as well. Otherwise you most likely have another plugin sending bad packets
