### ISSUE TITLE
Players can't teleport to another world with error

### ISSUE THREAD

**Issue by Shanshui2024** [ViaVersion/ViaVersion#4061]
### `/viaversion dump` Output

https://dump.viaversion.com/705b613edae89d5f26a7c46e57e7276b2a5a985789e1fbfbb358409c11f16c22

### Console Error

```
https://mclo.gs/vSaGYCP
```

### Bug Description

When I tried to teleport to a world named "NewMainCity" and based on Muiltiverse, I got an error message and been kicked.

### Steps to Reproduce

1.create a world with Muitiverse
2.(I'm not sure) Put some light_block in this world with 1.19.4 client
3.teleport to another world and back the world

### Expected Behavior

I want to make sure that players won't be kicked because of this error

### Additional Server Info

I use BungeeCord with these plugins:AntiFakePlayer, Luckperms, ServerListPlus, SkinsRestorer and TrChat.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3498--Spigot--b081915--10ba1be%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-3498--Spigot--b081915--10ba1be%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(5.0.1)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(5.0.1)-Outdated!-red?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(4.0.1)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
