### ISSUE TITLE
ConsoleSpam warning

### ISSUE THREAD

**Issue by tncc2k** [ViaVersion/ViaVersion#4063]
### `/viaversion dump` Output

https://dump.viaversion.com/b47f7aa72b060609597bcf9b9e3ac604497283fefc84f06edce08aa436900367

### Console Error

https://mclo.gs/jqOVMR0

### Bug Description

I use a hack that has ConsoleSpam functionality

### Steps to Reproduce

I use a hack that has ConsoleSpam functionality

### Expected Behavior

There will be no more 92 warning rows on Console

### Additional Server Info

I use paper 1.16.5
ProtocolLib
ViaVersion-5.0.2
ViaRewind-4.0.2
ViaBackwards-5.0.3-SNAPSHOT
I just installed all the latest versions to report

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--794%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--794%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.2): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.2)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by tncc2k** [comment]
I just installed ViaBackwards #465 no more Spam warnings fixed
