### ISSUE TITLE
ViaVersion Spam Console

### ISSUE THREAD

**Issue by tncc2k** [ViaVersion/ViaVersion#4066]
### `/viaversion dump` Output

https://dump.viaversion.com/f75c156f7355610f6f82371f283f9ddf3455294e28fe4080c65b674ea6b915b9

### Console Error

https://mclo.gs/AG4diR8

### Bug Description

I install a hack on the internet (ConsoleSpam) + use a mod ViaForge-Mod-Forge-1.12.2.jar
Enter the game and use ConsoleSpam, Viaversion will give 92 warning lines on the console
I think it is related to the mod (ViaForge-Mod-Forge-1.12.2.jar)
Why can client-side mods cause server warning spam

### Steps to Reproduce

Run a server with viaversion installed and use the ConsoleSpam hack

### Expected Behavior

I expect no more 92 rows of warnings on the server dashboard

### Additional Server Info

I don't use velocity
I run a normal default paper server for fastest bug reporting

![1b](https://github.com/user-attachments/assets/a5bfd937-f47e-4988-8d9d-bb71b9b6c03d)
![2b](https://github.com/user-attachments/assets/6f422640-fd06-48a1-85c4-36ba53bf44d6)
![3b](https://github.com/user-attachments/assets/f30f67e6-96d2-4878-888c-f8f630f6e5f7)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--794%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--794%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (5.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.2): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.2)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by tncc2k** [comment]
I just removed the client side ViaForge-Mod-Forge-1.12.2.jar mod and there are no more warnings on the server console
Info:
I think it ViaVersion and ViaForge-Mod-Forge have something to do with each other

**Comment by tncc2k** [comment]
Fixed
