### ISSUE TITLE
sculk_sensor

### ISSUE THREAD

**Issue by appipinopi** [ViaVersion/ViaVersion#4067]
### `/viaversion dump` Output

?

### Console Error

```
Put the mclo.gs link or text here.
```
The Skulk Sensor introduced in Minecraft 1.19 is available in servers running Minecraft 1.18.

### Bug Description

The Skulk Sensor introduced in Minecraft 1.19 is available in servers running Minecraft 1.18.

### Steps to Reproduce

?

### Expected Behavior

?

### Additional Server Info

spigot server and Bungeeserver

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Follow the issue template
