### ISSUE TITLE
Equipping certain enchants resets sprint

### ISSUE THREAD

**Issue by Jyguy** [ViaVersion/ViaVersion#4068]
### `/viaversion dump` Output

https://dump.viaversion.com/acb347c44955065ba382f18f88656ad6c0c52f8e19180c1012702dcb53313735

### Bug Description

Equipping certain enchants (e.g. putting an efficiency pickaxe into the hand) resets the sprint of the player when using a 1.21 client on a 1.20.6 server. This does not happen with a 1.20.6 client.

### Steps to Reproduce

1. Get an item enchanted with efficiency, depth strider, aqua affinity, or swift sneak (any that are in https://github.com/ViaVersion/ViaVersion/blob/master/bukkit/src/main/java/com/viaversion/viaversion/bukkit/listeners/v1_20_5to1_21/PlayerChangeItemListener.java#L76)
2. Start sprinting and equip the item (if efficiency, switch to the slot with the item; otherwise, right-click on the armour piece to equip it)
3. Observe that the sprint is reset.

### Expected Behavior

The sprint should not be reset when these items are equipped.

This does not happen with items that are not enchanted with these 4 enchantments.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--148--20f5165%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--148--20f5165%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
