### ISSUE TITLE
Error spaming in console

### ISSUE THREAD

**Issue by lijualun** [ViaVersion/ViaVersion#4075]
### `/viaversion dump` Output

https://dump.viaversion.com/f2091bd7bb3469e18dc9e3e97a7d189d73ae1b37017ff9b5e8f3e164a7e8339c

### Console Error

https://mclo.gs/rzWNQZW

### Bug Description

please fix this error

### Steps to Reproduce

i need to know what causes this error

### Expected Behavior

i need a clean and error free console.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by FlorianMichael** [comment]
You also need to provide the full server log, try with a normal spigot and explain us how to reproduce the issue (if possible).
