### ISSUE TITLE
Client fails to decode level_chunk_with_light packet on 1.21

### ISSUE THREAD

**Issue by Z3r0xh** [ViaVersion/ViaVersion#4077]
### `/viaversion dump` Output

https://dump.viaversion.com/9c2b3678dea741021abe88e7b3bb4eb70dfb3983d0a752a1367d031fa767373f

### Console Error

no errors in console

### Bug Description

Some users experience these two errors while playing, sometimes it takes more or less time to appear
![image](https://github.com/user-attachments/assets/7e16e2a2-4498-4547-9dbd-f9b4fa1c86da)

![image](https://github.com/user-attachments/assets/f05f5378-8e03-4a0b-ad83-743cb6aa0d46)

### Steps to Reproduce

Try to join the server with 1.21 client.
See the disconnect screen.

### Expected Behavior

.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--DEV--71accd7%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--DEV--71accd7%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
ViaVersion doesn't do anything for 1.21 clients on 1.21 servers, so this will be down to another plugin sending bad data/having bad packet processing or you using Via plugins on multiple platforms at the same time

**Comment by Z3r0xh** [comment]
> ViaVersion doesn't do anything for 1.21 clients on 1.21 servers, so this will be down to another plugin sending bad data/having bad packet processing or you using Via plugins on multiple platforms at the same time

Are you referring to, for example, if in the lobby I use viaversion being in 1.8 and in the modalities I am in 1.21 and 1.20?
