### ISSUE TITLE
Display item hover event causes crash on 1.20.6 and below clients on 1.21 server

### ISSUE THREAD

**Issue by JerichoTorrent** [ViaVersion/ViaVersion#4078]
### `/viaversion dump` Output

https://dump.viaversion.com/de4e74fc20872dabbbffe56bcad6402ed7be7a62a27090fc32c9734be70ceb7f

### Console Error

None. This is client side only.

### Bug Description

When using the display item hover event on a 1.21 server on the latest CI build of ViaVersion and ViaBackwards, clients on 1.20.6 and below get instantly crashed. I’ve only been able to reproduce this by displaying one of the new music disks. Maces, copper blocks, tuff blocks, etc don’t do this. It seems NBT is a factor.
Please see: https://github.com/kangarko/ChatControl-Red/issues/2780
I thought this was caused by the plugin displaying the item itself, but they only pass the native itemstack NBT tag, or so I’m told.

### Steps to Reproduce

1. Log in with a 1.20.6 or below client on a 1.21 server.
2. Another player displays the music disk precipice with a chat plugin like ChatControl.
3. Your client will instantly crash.

### Expected Behavior

The item is displayed as normal, at least as whatever it can be displayed as to an outdated client. On my other servers on the network that are 1.20.4, it comes up as stone.

### Additional Server Info

I use velocity and have 4 servers on 1.21 and 2 servers on 1.20.4, waiting to update.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--124--df3b654%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--124--df3b654%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.3-SNAPSHOT): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.3--SNAPSHOT)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.3-SNAPSHOT): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.3--SNAPSHOT)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by JerichoTorrent** [comment]
I didn’t realize a new build would be out within the day I did this but hell, sure. Will be back later.
