### ISSUE TITLE
[Server thread/WARN]: [ViaVersion] ERROR IN Protocol1_17To1_16_4 IN REMAP OF REMOVE_ENTITY (0x3A)

### ISSUE THREAD

**Issue by dechebt** [ViaVersion/ViaVersion#4083]
### `/viaversion dump` Output

 https://dump.viaversion.com/c54d14f9b7f5ed2f715206f9270268a58afac690796fc7b71fdd15f471f104e7

### Console Error

```
https://mclo.gs/maU7hx1
```

### Bug Description

I have a velocity server. some players get kicked. Have bedwars Screaming and znpcplus for bedwars.

### Steps to Reproduce

player click on npc to join bedwars arena. after the game is finished he is kicked from the server.

### Expected Behavior

??

### Additional Server Info

velocity
Plugins that could be important for the issue: 
beddwars screaming, bedwars screming sba addon, znpcplus, oreannouncer, Skinrestorer

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--2233--0d6766e%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--2233--0d6766e%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.3): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.3)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.3): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.3)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
