### ISSUE TITLE
Failed to decode packet 'clientbound/minecraft:system_chat'

### ISSUE THREAD

**Issue by skbeh** [ViaVersion/ViaVersion#4089]
### `/viaversion dump` Output

https://dump.viaversion.com/1c00fd0b07d97d734e2df47d7f36fe66b30fb04e4820c169d65877e94cf2ec6f

### Console Error

```
https://mclo.gs/Gk7l4wY
```

### Bug Description

When the `Duels` plugin send specific message to the client, the client disconnects.

### Steps to Reproduce

1. Install `Duels` plugin on a 1.8 server and join via a 1.21 client.
2. Start a duel and end it.
3. When the duel result message it sent to the client, the client fails to decode the message.

### Expected Behavior

The message can be correctly decoded by the client.

### Additional Server Info

Formatted SNBT:
```snbt
{
    translate: "death.attack.mob.item",
    with: [
        {
            clickEvent: {
                action: "suggest_command",
                value: "/msg foo "
            },
            hoverEvent: {
                action: "show_entity",
                contents: {
                    id: [I; (removed)],
                    name: "foo",
                    type: "pig"
                }
            },
            insertion: "foo",
            text: "§4§lCombat §ffoo"
        },
        {
            clickEvent: {
                action: "suggest_command",
                value: "/msg bar "
            },
            hoverEvent: {
                action: "show_entity",
                contents: {
                    id: [I; (removed)],
                    name: "bar",
                    type: "pig"
                }
            },
            insertion: "bar",
            text: "§4§lCombat §fbar"
        },
        {
            color: "aqua",
            extra: [
                {
                    italic: 1b,
                    text: "Sword"
                },
                {
                    "": "]"
                }
            ],
            hoverEvent: {
                action: "show_item",
                contents: {
                    components: {
                        custom_data: {
                            DuelsKitContent: "true",
                            Enchantments: [
                                {
                                    id: "unbreaking",
                                    lvl: 3s
                                }
                            ],
                            "VV|Protocol1_12_2To1_13": 40,
                            "VV|Protocol1_20_3To1_20_5": 1b,
                            display: {
                                Name: '{"text":"Sword"}',
                                "VV|Protocol1_12_2To1_13|Name": "Sword"
                            }
                        },
                        custom_name: '"Sword"',
                        enchantments: {
                            levels: {
                                unbreaking: 3
                            }
                        },
                        food: {
                            can_always_eat: 1b,
                            eat_seconds: 3600f,
                            nutrition: 0,
                            saturation_modifier: 0f
                        }
                    },
                    count: 0,
                    id: "minecraft:diamond_sword"
                }
            },
            text: "["
        }
    ]
}
```

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PandaSpigot--%220764ac6%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PandaSpigot--%220764ac6%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.3): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.3)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Try again with the latest releases which had some fixes with chat handling, if it still happens we'll reopen the issue
