### ISSUE TITLE
i got this error

### ISSUE THREAD

**Issue by dzsivokado** [ViaVersion/ViaVersion#4090]
### `/viaversion dump` Output

https://dump.viaversion.com/01bf8010879a139f2d32b69648f6c411623c7d94175c2fa4e3f65b83a44630f1

### Console Error

```
https://mclo.gs/Xr5r5y2
```

### Bug Description

Just randomly got the error and the server disconected

### Steps to Reproduce

1. server 1.20.4
2. login whit 1.18.2 
3. yust play (idk wait idk how it hapened)

### Expected Behavior

show te error and disconects you

### Additional Server Info

paper 1.20.4 LPC, plugins: LuckPerms, ViaBackwards, ViaVersion and a few of my coustume plugins

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--398%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--398%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.3): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.3)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(5.0.1)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>broken_jar</details>
