### ISSUE TITLE
An error occurred in entity data handler

### ISSUE THREAD

**Issue by Kainzo** [ViaVersion/ViaVersion#4091]
### `/viaversion dump` Output

https://dump.viaversion.com/079ce6451d9ff8e90dc63024cda5f721e4133c22c200c9a7ce2da37574ac87d7

### Console Error

```
[Put the mclo.gs link or text here.](https://mclo.gs/b53j2Ut)
```

### Bug Description

Server Out of Memory due to errors, I am UNABLE To give a viaversion dump.

### Steps to Reproduce

I am on 1.20.4 but I allow multiple clients with Viaversion

### Expected Behavior

Having custom models from ModelEngine

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--52%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Pufferfish--52%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(5.0.1)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(5.0.1)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>modelengine_warn,mythic_warn</details>
