### ISSUE TITLE
[1.20.5->1.20.4] Translated components not being removed from items copied on creative mode.

### ISSUE THREAD

**Issue by SzczurekYT** [ViaVersion/ViaVersion#4092]
### `/viaversion dump` Output

https://dump.viaversion.com/9dc14bfb4e8a66f156f4a12bb1a5c382f69c703c8787d2870e748a598a4d1225

### Console Error

Command output, formatted for you convenience
```
data get entity TheBugReporter SelectedItem
TheBugReporter has the following entity data:
{
id: "minecraft:anvil",
count: 1,
components: {
    "minecraft:custom_name": '"tnt"',
    "minecraft:custom_data": {display: {Name: '"tnt"'}} <- WHAT?
    }
}
```

### Bug Description

When you copy an item using middle click on creative mode, and the item has some components, then the resulting item will also have those components stored as custom data in the old format.

### Steps to Reproduce

1. Start a server on 1.20.5 or higher.
2. Join with a client before 1.20.5.
3. Create an item that has some components. For example let's rename an item in anvil.
4. Go to creative mode and copy the item with middle click.
5. Inspect the item's data from the console or a 1.20.5+ client using the /data command.
6. See that it has both a `custom_name` component, and a `custom_data` component containing the old display.Name tag generated by vv for the older client.
7. (See Console Error section for example data)

### Expected Behavior

Item shouldn't have the data generated by viaversion for older clients.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--148--20f5165%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--148--20f5165%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.3): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.3)-Even%20with%20master-brightgreen?style=flat-square) </br>
