### ISSUE TITLE
Packet too big (is 9012972, should be less than 8388608)

### ISSUE THREAD

**Issue by hseermc** [ViaVersion/ViaVersion#4100]
### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

when i use 1.21 client join 1.21 server ,  it says: 
MCfffffff lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Packet too big (is 9012972, should be less than 8388608)

### Steps to Reproduce

1. Use a client version lower than version 1.21 join 1.21 server

### Expected Behavior

join successfully

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--46--c19e742%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--46--c19e742%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Kichura** [comment]
Caused by third-party plugins sending too many packets at once than allowed.
