### ISSUE TITLE
Outdated version

### ISSUE THREAD

**Issue by literallydamianwayneonb** [ViaVersion/ViaVersion#4102]
### `/viaversion dump` Output

invalid command

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

Connecting to 1.8.8 server with viaversion on 1.21 causes it to say outdated server

### Steps to Reproduce

launch minecraft 1.21
join a paper 1.8.8 server with viaversion installed

### Expected Behavior

game should not say "outdated server! I'm still on 1.8.8"

### Additional Server Info

idk what a proxy is but i use a bunch of plugins on the main server including multiversecore, luckperms, and some others. But i tested this in another paper server with no plugins except viaversion and it still says outdated server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by literallydamianwayneonb** [comment]
> ![Error: Invalid or missing dump](https://camo.githubusercontent.com/7b5e5f80a2824a1bc1a4f504d61a8f91362791850f864896b1ac9c6c0f77a463/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4572726f722d496e76616c69642f6d697373696e6725323064756d702d7265643f7374796c653d666c61742d737175617265)

it said invalid command

**Comment by Kichura** [comment]
Your current ViaVersion JAR is not compatible with your server software, Use the [Java 8 variant](https://ci.viaversion.com/job/ViaVersion-Java8) instead.

**Comment by literallydamianwayneonb** [comment]
> Your current ViaVersion JAR is not compatible with your server software, Use the [Java 8 variant](https://ci.viaversion.com/job/ViaVersion-Java8) instead.

Thank you so much, this worked!
