### ISSUE TITLE
Disable Collision is not working

### ISSUE THREAD

**Issue by TheWylot** [ViaVersion/ViaVersion#4109]
### `/viaversion dump` Output

didn't make link - i cant send in public due to NDA of our company

### Console Error

no error

### Bug Description

Enabling prevent-collision doesn't work on CarbonSpigot/Spigot 1.8.9

### Steps to Reproduce

Open config.yml
set prevent-collision to true and restart the server,
still 1.9+ players has collision

### Expected Behavior

It should disable the collision mode on +1.9 Clients

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by TheWylot** [comment]
due to Stalkers, i can share it in Discord DM `my id: thewylot`

**Comment by Kichura** [comment]
This is either caused by third-party plugins on your server or a seperate team is present on the player(s) which caused the collision mode to be overridden, Also because your issue states that the viaversion dump cannot be shared - this cannot be properly diagnosed.
