### ISSUE TITLE
[viaversion]: ERROR IN ClientboundBaseProtocol1_7 IN REMAP OF GAME_PROFILE (0x02)

### ISSUE THREAD

**Issue by BeholdIsLost** [ViaVersion/ViaVersion#4120]
### `/viaversion dump` Output

https://dump.viaversion.com/78cb8bbc8a09c7eb7f5a1846ae387ce8f388597758d8cba0984f8194120442a1

### Console Error

https://mclo.gs/7BVdS81

### Bug Description

People cannot join the server from the IP, Tho on Lunar client it works completly fine

### Steps to Reproduce

Unknown at this point.

### Expected Behavior

People go to Captcha, to do the captcha, after it finnishes, people should be automatically redricted to Survival

### Additional Server Info

Velocity

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--6100e675--b416%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--6100e675--b416%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by CertifiedGlowie** [comment]
same thing:
https://dump.viaversion.com/7dc52131a9744bd2dff5d39e13197a57614ae2de9121a5ce042509ff8e7e00a5

**Comment by Barvalg** [comment]
![Platform: velocity%203.4.0--SNAPSHOT%20%28git--b66aa3fb--b437%29](https://img.shields.io/badge/Platform-velocity%203.4.0--SNAPSHOT%20%28git--b66aa3fb--b437%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by HowardZHY** [comment]
Limbo API is not supported on Proxy, move Via* plugins to backend servers instead
