### ISSUE TITLE
1.8 Console error 

### ISSUE THREAD

**Issue by Henriiig** [ViaVersion/ViaVersion#4121]
### `/viaversion dump` Output

https://dump.viaversion.com/db9f9b2585eb9ab1bc75996919582afac895664e6e69304fb59e018f47589ca0

### Console Error

https://pastebin.com/Cwpx7D2s

### Bug Description

Console error

### Steps to Reproduce

...

### Expected Behavior

...

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--cbe632ca%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--cbe632ca%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (5.0.3): 23 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.3)-23%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by madnessman666** [comment]
I got this error too and update not works for me
