### ISSUE TITLE
Unable to grab ViaVersion client version for player

### ISSUE THREAD

**Issue by CptGummiball** [ViaVersion/ViaVersion#4123]
### `/viaversion dump` Output

https://dump.viaversion.com/b43ec1749d4c2c9e4248f15eb8860f8b28ec820293ede58c9b15c4b490575715

### Console Error

``````
[10:57:33] [Netty Epoll Server IO #1/INFO]: Unable to grab ViaVersion client version for player!
``````

### Bug Description

Console keep spamming this every second.
Connecting players still work its just the spamming thats weird.

### Steps to Reproduce

Install Viaversion on the server
Start the server

### Expected Behavior

Console not spamming?

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3976--Spigot--06d602e--b3b43a6%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-3976--Spigot--06d602e--b3b43a6%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.3): 26 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.3)-26%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>bad_packetevents</details>

**Comment by CptGummiball** [comment]
New Viaversion Dump:

https://dump.viaversion.com/d92683ff98a0257a225d97e2d0bacfc72b6ad50ad6a19f79aa9fc9fc22c9d12c

**Comment by FlorianMichael** [comment]
This is caused by the packetevents library, update it and all plugins that include it.
You can use this program to find all plugins containing the library: https://github.com/Jo0001/FindPacketevents

**Comment by CptGummiball** [comment]
Thx,
its fixes. Nice to know for further updates!
