### ISSUE TITLE
Plugin prevented everyone from connecting the underlying server

### ISSUE THREAD

**Issue by SNWCreations** [ViaVersion/ViaVersion#4124]
### `/viaversion dump` Output

https://dump.viaversion.com/14ded490a376e407ca0d5cbc651ae8a4100e5ef252d76dba0f7a4871dcd608f3

### Console Error

[01:04:04 ERROR]: [connected player] SNWCreations (/106.8.149.248:4219): disconnected while connecting to lobby: Outdated client! Please use 1.20.1

### Bug Description

Everyone can't connect to underlying server even their Minecraft version exactly matches to them.
The plugin made the proxy did not work correctly at all.

### Steps to Reproduce

1. Run a velocity proxy with latest snapshot (version mentioned in dump)
2. Join the server through proxy using a Minecraft version exactly matches the underlying server
3. You will not be able to join

### Expected Behavior

Players should join correctly.

### Additional Server Info

We are using Velocity. Other plugins on the proxy are: SkinsRestorer, LuckPerms
Via(Version/Backwards/Rewind) are all installed on the proxy.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--00ed2284--b415%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--00ed2284--b415%29-3498db?style=flat-square) </br>![Proxy is 1 builds behind](https://img.shields.io/badge/Your%20proxy%20is%201%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by SNWCreations** [comment]
Updated to latest velocity. Issue still persists.

**Comment by kennytv** [comment]
Please join the Discord for support, this generally means *something* in the setup is wrong (e.g. make sure you're not having Via on both backend and proxy)
