### ISSUE TITLE
Error initializing plugin 'ViaVersion-5.0.3.jar' in folder 'plugins' (Is it up to date?) java.lang.NoSuchMethodError: 'com.viaversion.viaversion.api.protocol.remapper.PacketHandler 

### ISSUE THREAD

**Issue by sky-3311** [ViaVersion/ViaVersion#4127]
### `/viaversion dump` Output

 https://dump.viaversion.com/2baccf9cf44a807dfafae06f0e260103169bbb47f8588163165c1942a285e84f

### Console Error

```
https://mclo.gs/Gq8dVgn#L773
```

### Bug Description

abzxc joined the game
--
853 | [01:42:09] [Server thread/INFO]: abzxc[/**.**.**.**:6027] logged in with entity id 98 at ([world]-51.12518005363009, 63.0, 9.97217282765658)
854 | [01:42:10] [Server thread/INFO]: abzxc lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NoSuchFieldError: Class com.viaversion.viabackwards.api.data.BackwardsMappingData does not have member field 'com.viaversion.viaversion.api.data.Mappings attributeMappings'
855 | [01:42:10] [Server thread/INFO]: abzxc left the game

### Steps to Reproduce

1.更新paper至1.21.1-51 a5d4b979808d889c5fa5512142cc903224d5dacb15ca17c1665e2833acd4468b
2.更新ViaVersion至5.0.3
3.重启服务器

### Expected Behavior

ViaVersion能够正常加载并玩家能够进入游戏

### Additional Server Info

Bukkit Plugins:
AllMusic3, AuthMe, BedWars, Citizens, CMILib, ColoredEnderChests, CommandAPI, CrystamaeHistoria, Cultivation, DriveBackupV2 ,DyedBackpacks, DynaTech, EClean, eco, EcoEnchants, EcoPower, ElectricSpawners, Essentials, ExoticGarden, ExtraGear ,fakeplayer, floodgate, FlowerPower, fmenu_for_1.21, FNAmplifications, FoxyMachines, Gastronomicon, Geyser-Spigot, GSit, GuizhanLibPlugin ,HotbarPets, InfinityExpansion, libreforge, LiteSignIn, LiteXpansion, LuckPerms, MiniMOTD, MobCapturer, Multiverse-Core, Multiverse-Inventories ,nightcore, NoPlugins, Not-Too-Expensive, PlaceholderAPI, *PlayerJoinCommand, PlugManX, PowerBoard, ProtocolLib, RealisticSeasons, Residence ,SimpleStorage, SimpleTpa, SkinsRestorer, Slimefun, SlimefunLuckyBlocks, SlimefunOreChunks, SlimeGlue, SlimyTreeTaps, SpiritsUnchained, SuperHarvest ,Supreme, Themis, TranscEndence, Vault, ViaBackwards, ViaRewind, ViaVersion, Wildernether, WorldEdit, WorldGuard, XConomy, YukiNoaAPI

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.1--52--e08e667%20%28MC%3A%201.21.1%29](https://img.shields.io/badge/Platform-1.21.1--52--e08e667%20%28MC%3A%201.21.1%29-3498db?style=flat-square) </br>![ViaVersion (5.0.3): 30 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.3)-30%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(5.0.1)-Outdated!-red?style=flat-square) </br>![ViaRewind(4.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>json_warn,mixed_via</details>
