### ISSUE TITLE
 ERROR IN Protocol1_21To1_20_5 IN REMAP OF SET_EQUIPMENT (0x5B)

### ISSUE THREAD

**Issue by lDoomerl** [ViaVersion/ViaVersion#4132]
### `/viaversion dump` Output

https://dump.viaversion.com/e9dfaaf9e753a3ebeacbb0e7ec71e6be68b5d221705893e68d9ea4192486ab5b

### Console Error

```
 ERROR IN Protocol1_21To1_20_5 IN REMAP OF SET_EQUIPMENT (0x5B)
 ```

### Bug Description

This error caused player kicks. 

### Steps to Reproduce

Put two players with different versions (from the error) near and make them do some things in inventory, or pvp, or smth. 

### Expected Behavior

No errors:)

### Additional Server Info

Im using BungeeCord with NullcordX, but Via plugins are only on backend servers. 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.1--2299--5c0d2f7%20%28MC%3A%201.21.1%29](https://img.shields.io/badge/Platform-1.21.1--2299--5c0d2f7%20%28MC%3A%201.21.1%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.4-SNAPSHOT): 6 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.4--SNAPSHOT)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by lDoomerl** [comment]
I did the update to the latest build and causes kicks all players on the versions earlier then 1.21.
