### ISSUE TITLE
Internal Exception

### ISSUE THREAD

**Issue by Spectre-dev-tf** [ViaVersion/ViaVersion#4138]
### `/viaversion dump` Output

https://dump.viaversion.com/49871f2567cf09ce75fa08469db330a618c3140dfd3fb42e9ecfdbd9f9e006d8

### Console Error

io.netty.handler.codec.EncoderException:
com.viaversion.exception.InformativeException:Please report this on the via support discord ir open an issue on the relevant GitHub repostery
Source 0:com.viaversion.rewriter.CommandRewriter$$Lambda/0x00007ff32afe5108

### Bug Description

When I enter an older server than the one I use, (1.20 and below) it kicks me out of the server using version 1.16.5. I use aternos.org to make servers, I make another because the bot closed my issue

### Steps to Reproduce

1.Enter on minecraft(version 1.16.5 or in an older version) 
2.connect to the server(idk if I Need to put this:suizaqqq.aternos.me:45533 this server is for My Friends) 

### Expected Behavior

when I enter the server it takes me out

### Additional Server Info

IDK if aternos is a proxy, but I usé that for My server and I use this plugins:
"Viaversion
Vía Rewind
Viabackwards
DiscordSRV
GeyserMc
Floodgate"
The software is PaperMC

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.1--57--b483da4%20%28MC%3A%201.21.1%29](https://img.shields.io/badge/Platform-1.21.1--57--b483da4%20%28MC%3A%201.21.1%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Spectre-dev-tf** [comment]
But, I Can't upload files in aternos

**Comment by Jo0001** [comment]
Links to the Via* plugins on aternos
https://aternos.org/addons/a/hangar/ViaVersion - ViaVersion
https://aternos.org/addons/a/hangar/ViaBackwards - ViaBackwards
https://aternos.org/addons/a/hangar/ViaRewind - ViaRewind
