### ISSUE TITLE
Spamming: An error occurred in entity data handler EntityPacketRewriter1_19_3 for untracked entity type: EntityData{id=12, dataType=EntityDataTypeImpl{typeId=26, type=Vector3fType}, value=Vector3f[x=1.54, y=1.54, z=1.0]}

### ISSUE THREAD

**Issue by roggy666** [ViaVersion/ViaVersion#4145]
### `/viaversion dump` Output

https://dump.viaversion.com/6f6cbdfece78b2d58dd01b25301be2227305186141da3bdb8acaaa73d8c8915b

### Console Error

[18:48:49 ERROR]: [ViaVersion] (1.19.3->1.19.1) An error occurred in entity data handler EntityPacketRewriter1_19_3 for untracked entity type: EntityData{id=12, dataType=EntityDataTypeImpl{typeId=26, type=Vector3fType}, value=Vector3f[x=1.29, y=1.29, z=1.0]}
[18:48:49 ERROR]: [ViaVersion] (1.19.3->1.19.1) Full entity data: EntityData{id=12, dataType=EntityDataTypeImpl{typeId=26, type=Vector3fType}, value=Vector3f[x=1.29, y=1.29, z=1.0]}
EntityData{id=15, dataType=EntityDataTypeImpl{typeId=0, type=ByteType}, value=3}
EntityData{id=16, dataType=EntityDataTypeImpl{typeId=1, type=VarInt}, value=15728880}
EntityData{id=17, dataType=EntityDataTypeImpl{typeId=3, type=FloatType}, value=128.0}
EntityData{id=23, dataType=EntityDataTypeImpl{typeId=5, type=ComponentType}, value={"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"⚔0.13"}],"text":""}}
EntityData{id=24, dataType=EntityDataTypeImpl{typeId=1, type=VarInt}, value=1000}
EntityData{id=25, dataType=EntityDataTypeImpl{typeId=1, type=VarInt}, value=0}
EntityData{id=26, dataType=EntityDataTypeImpl{typeId=0, type=ByteType}, value=-26}
[18:48:49 ERROR]: [ViaVersion] (1.19.3->1.19.1) Error: 
java.lang.ArrayIndexOutOfBoundsException: null
[18:48:49 ERROR]: [ViaVersion] (1.19.3->1.19.1) An error occurred in entity data handler EntityPacketRewriter1_19_3 for untracked entity type: EntityData{id=12, dataType=EntityDataTypeImpl{typeId=26, type=Vector3fType}, value=Vector3f[x=1.22, y=1.22, z=1.0]}
[18:48:49 ERROR]: [ViaVersion] (1.19.3->1.19.1) Full entity data: EntityData{id=12, dataType=EntityDataTypeImpl{typeId=26, type=Vector3fType}, value=Vector3f[x=1.22, y=1.22, z=1.0]}
EntityData{id=15, dataType=EntityDataTypeImpl{typeId=0, type=ByteType}, value=3}
EntityData{id=16, dataType=EntityDataTypeImpl{typeId=1, type=VarInt}, value=15728880}
EntityData{id=17, dataType=EntityDataTypeImpl{typeId=3, type=FloatType}, value=128.0}
EntityData{id=23, dataType=EntityDataTypeImpl{typeId=5, type=ComponentType}, value={"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"⚔0.19"}],"text":""}}
EntityData{id=24, dataType=EntityDataTypeImpl{typeId=1, type=VarInt}, value=1000}
EntityData{id=25, dataType=EntityDataTypeImpl{typeId=1, type=VarInt}, value=0}
EntityData{id=26, dataType=EntityDataTypeImpl{typeId=0, type=ByteType}, value=-26}
[18:48:49 ERROR]: [ViaVersion] (1.19.3->1.19.1) Error: 
java.lang.ArrayIndexOutOfBoundsException: null

### Bug Description

A lot of spamming in console

### Steps to Reproduce

Idk, I have purpur 1.21.1 and plugins that in dump

### Expected Behavior

No console spamming

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.1--2305--fdfc12e%20%28MC%3A%201.21.1%29](https://img.shields.io/badge/Platform-1.21.1--2305--fdfc12e%20%28MC%3A%201.21.1%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by roggy666** [comment]
> ![Platform: 1.21.1--2305--fdfc12e%20%28MC%3A%201.21.1%29](https://camo.githubusercontent.com/04c4ea6a18cec3df7383036ec51d9938e28c1e4ddb7cf9b52d8ff86046454c2b/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d312e32312e312d2d323330352d2d666466633132652532302532384d43253341253230312e32312e312532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (5.0.4-SNAPSHOT): 1 commits behind master](https://camo.githubusercontent.com/407cb83ccc35fc6b487c7b60fbe92bfd6af654d8131146f3fc65e1b590a76eb8/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028352e302e342d2d534e415053484f54292d31253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaBackwards(5.0.4-SNAPSHOT): Even with master](https://camo.githubusercontent.com/05d77e8408e0c5e4c3b964d955c048ced8d9a78bca3c008380cb8a0b2608febe/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028352e302e342d2d534e415053484f54292d4576656e253230776974682532306d61737465722d627269676874677265656e3f7374796c653d666c61742d737175617265)
> 
> ### Please update **all** Via* plugins from https://ci.viaversion.com/.In case the issue still persists send the new dump and the issue will be reopened

https://dump.viaversion.com/6dbf33125ec564f368962250fc0b7f3e674ca839ef108e76c6ac50c304347ca6

**Comment by Barvalg** [comment]
![Platform: 1.21.1--2305--fdfc12e%20%28MC%3A%201.21.1%29](https://img.shields.io/badge/Platform-1.21.1--2305--fdfc12e%20%28MC%3A%201.21.1%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by roggy666** [comment]
https://dump.viaversion.com/f50b6bfb3af1a4f88522756108a6843e1da1ef7c2745c3bd6b3b4cfeacb237fc

**Comment by Barvalg** [comment]
![Platform: 1.21.1--2305--fdfc12e%20%28MC%3A%201.21.1%29](https://img.shields.io/badge/Platform-1.21.1--2305--fdfc12e%20%28MC%3A%201.21.1%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.4-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.4--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by roggy666** [comment]
https://dump.viaversion.com/c10dc424d5347851ed555386504a1d397ef664c73cd3a5faca08e02e64280192

**Comment by Barvalg** [comment]
![Platform: 1.21.1--2305--fdfc12e%20%28MC%3A%201.21.1%29](https://img.shields.io/badge/Platform-1.21.1--2305--fdfc12e%20%28MC%3A%201.21.1%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by roggy666** [comment]
It is text from CMI

**Comment by FlorianMichael** [comment]
This is most likely caused by another plugin sending bad data, try to remove plugins from your server until the errors stops happening or alternatively enable the "suppress-metadata-errors" option in the ViaVersion config file.
