### ISSUE TITLE
ERROR IN Protocol1_20_5To1_21 IN REMAP OF UPDATE_RECIPES (0x77)

### ISSUE THREAD

**Issue by JayLucky** [ViaVersion/ViaVersion#4150]
### `/viaversion dump` Output

https://dump.viaversion.com/ec5a2d076f4ce0243be541bcea6451ee140512704933e0c196b4b0fd8cacf284

### Console Error

```
https://mclo.gs/YMn7NPJ
```

### Bug Description

Attempting to load into a Fabric 1.20.1 server with Lucky Block 1.20.1 installed from latest Bedrock client and get immediately kicked with an error.

### Steps to Reproduce

1. Attempt to connect using latest Bedrock client
2. Get kicked from server with "Internal Exception: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository" error message

### Expected Behavior

Client connection succeeds and world loads for use.

### Additional Server Info

Using Velocity to connect from a Bedrock Client with Geyser-Velocity, floodgate-velocity.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.4.15+81--main](https://img.shields.io/badge/Platform-0.4.15+81--main-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Please try if this also happens with a 1.21.1 Minecraft Java Edition client
