### ISSUE TITLE
ViaVersion and ItemsAdder attributes bug per version

### ISSUE THREAD

**Issue by SliderKP** [ViaVersion/ViaVersion#4151]
### `/viaversion dump` Output

https://dump.viaversion.com/12ec279eb2fd9264b2035575589ed943b263a4b3dc5c1abc260c490a44199e6d

### Console Error

```
Put the mclo.gs link or text here.
```
No console errors

### Bug Description

bugs occours when a user join with different version at 1.21.1, for example if u join with 1.20.4, durability of armors created by itemsadder goes to default (like leather item) but if u join with 1.21.1 the durability defined by itemsadders works fine: 
1.211 item:
![image](https://github.com/user-attachments/assets/a456f876-4cfa-46a0-9dc4-59b56f55bcd1)

SAME item on 1.20.4:
![image](https://github.com/user-attachments/assets/c2a29644-4e95-47af-81bc-be91b7e2ab95)

maybe you going to tell me "the durability looks different but works fine" but that is not correctly, in 1.20.4 the armor only has 50  hits to broke, and in 1.21.1 resists 407 hits.

i reported this to itemsadder developer but considers the problem are with ViaVersion or ViaBackwards.

### Steps to Reproduce

1- Join with 1.21.1 and use an armor of itemsadder (works fine)
2- join with 1.20.4 and use the same armor and has the default durability of leather, not only the durability is broken, the "armor level" too

### Expected Behavior

the armors have the same durability and attributes on all versions

### Additional Server Info

im using PufferFish 1.21.1 build 16

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.1--16--a9e9d99%20%28MC%3A%201.21.1%29](https://img.shields.io/badge/Platform-1.21.1--16--a9e9d99%20%28MC%3A%201.21.1%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.4-SNAPSHOT): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.4--SNAPSHOT)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by LoneDev6** [comment]
This happens because 1.20.4 and lower doesn't have custom vanilla durability tags built in.
This is a bug of ViaVersion and they should address it.
Any other custom durability plugin will have this issue if they use the new max durability component of modern itemstacks.

https://github.com/PluginBugs/Issues-ItemsAdder/issues/4194#issuecomment-2523432694
