### ISSUE TITLE
[Bug] 1.21 client cannot connect to a 1.21 fabric server through a velocity with viaversion

### ISSUE THREAD

**Issue by GLDYM** [ViaVersion/ViaVersion#4155]
### `/viaversion dump` Output

https://dump.viaversion.com/ea11e08978970914b5fd43006c560f6efe2407c0f01bcbe33493ce8fcc5c6d9d

### Console Error

No console error.

### Bug Description

1.21 client cannot connect to a 1.21 fabric server through a velocity with viaversion, and client get a error "incompatible client, please use 1.21".

### Steps to Reproduce

1. Set up a velocity server and install viaversion on it.
2. Set up a 1.21 fabric server and install fabric-api and [FabricProxy-Lite](https://modrinth.com/mod/fabricproxy-lite/version/v2.9.0) on it, connecting it to the velocity.
3. Use a 1.21 client to connect velocity.

### Expected Behavior

The client should connect to the fabric server through a velocity with viaversion,

### Additional Server Info

The client cannot connect to the fabric server through a velocity with viaversion, and client get a error "incompatible client, please use 1.21".

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.4.0--SNAPSHOT%20%28git--b66aa3fb--b437%29](https://img.shields.io/badge/Platform-velocity%203.4.0--SNAPSHOT%20%28git--b66aa3fb--b437%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
