### ISSUE TITLE
disconnection when trying to connect via velocity and without it server 1.20.1 client 1.21.1

### ISSUE THREAD

**Issue by Damir00109** [ViaVersion/ViaVersion#4160]
### `/viaversion dump` Output

https://dump.viaversion.com/5487b3e61adb127fad685131fe602ee29c5424597fb7d479a095708166b2ca45

### Console Error

[18:23:15 INFO]: Damir00109 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: LOGIN, Type: VarInt, Index: 18, Data: [{IntType: 189}, {BooleanType: false}, {StringType Array: [Ljava.lang.String;@31c26463}, {VarInt: 20}, {VarInt: 10}, {VarInt: 10}, {BooleanType: false}, {BooleanType: true}, {BooleanType: false}, {VarInt: 0}, {StringType: minecraft:overworld}, {LongType: -2372572047892158413}, {ByteType: 2}, {ByteType: 0}, {BooleanType: false}, {BooleanType: false}, {OptionalGlobalPositionType: null}], Source 0: com.viaversion.viaversion.protocols.v1_20_3to1_20_5.rewriter.EntityPacketRewriter1_20_5$1 (Anonymous), Packet ID: 43, Source 2: com.viaversion.viaversion.protocols.v1_20to1_20_2.Protocol1_20To1_20_2$$Lambda/0x000000b801d60ae0, Source 1: com.viaversion.viaversion.protocols.v1_20_2to1_20_3.rewriter.EntityPacketRewriter1_20_3$2 (Anonymous)

### Bug Description

I tried to connect to the purple server both through Velocity and just via only to purple

### Steps to Reproduce

I tried to connect to the purple server both through Velocity and just via only to purple

### Expected Behavior

I tried to connect to the purple server both through Velocity and just via only to purple

### Additional Server Info

I tried to connect to the purple server both through Velocity and just via only to purple

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2062%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Purpur--2062%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Fill out the issue template and provide full server logs
