### ISSUE TITLE
use item packet desync [client 1.21 server 1.20.6]

### ISSUE THREAD

**Issue by lolo45654** [ViaVersion/ViaVersion#4165]
### `/viaversion dump` Output

https://dump.viaversion.com/9be681c51371d7268e21d163d547017ec5b1772d6ea4c176ced2d13cea02b27d

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

the use item packet experiences yaw/pitch desync in a way that the client places a water bucket but the server still has an old yaw/pitch, so the water bucket gets placed elsewhere.

https://github.com/user-attachments/assets/56d21196-a164-4f7d-87a1-5d43660ac6c5

notice how the water bucket first appears in one spot, but then moves to another.

this is a disadvantage for 1.21 clients in pvp. from what i understand, the 1.20.6 client used to send a rotation packet before use item, but in 1.21 yaw & pitch were added to the use item packet as a field. should just require sending an extra rotation packet with the yaw & pitch from use item.

### Steps to Reproduce

1. Join with a 1.21 client
2. Get a water bucket
3. Move your mouse fast (similar to the video)
4. Place the water bucket while still moving your mouse
5. Water moves to an earlier spot

### Expected Behavior

water bucket should not move; yaw / pitch should not desync.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--150--e61b73f%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--150--e61b73f%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
The latest [dev builds](https://ci.viaversion.com/job/ViaVersion/) now contain a setting in the `plugins/ViaVersion/config.yml` called `fix-1_21-placement-rotation` which can be set to `true` (if it doesn't exist, delete the config file and restart).

Thanks for reporting
