### ISSUE TITLE
1.7.10 Players get disconnected as soon as they enter the vicinity of signs

### ISSUE THREAD

**Issue by tn-lorenz** [ViaVersion/ViaVersion#4167]
### `/viaversion dump` Output

https://dump.viaversion.com/4842b9015a9adbffc2c6550f6558bbe554dbd5aaf1dd239fbf40e48b990cc38e

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

_Xypheli lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NoClassDefFoundError: xyz/wagyourtail/jvmdg/j15/stub/java_base/J_L_CharSequence

### Steps to Reproduce

1. Login
2. place a sign

### Expected Behavior

I shouldn't get kicked.

### Additional Server Info

I use spigot 1.8.8 and the Downgraded java 8 version of ViaVersion, ViaBackward and ViaRewind. Contrarily to how I understood what I read in the plugin descriptions, I had to use all three of those, such that the server doesn't appear to be on a incompatible version, as viewed from my 1.7.10 client.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Spigot--21fe707--e1ebe52%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--Spigot--21fe707--e1ebe52%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (5.0.3): 56 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.3)-56%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.3): 31 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.3)-31%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(4.0.2): 20 commits behind master](https://img.shields.io/badge/ViaRewind%20(4.0.2)-20%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
