### ISSUE TITLE
NoFall caused by 1.21 rotation placement fix

### ISSUE THREAD

**Issue by Cyramek** [ViaVersion/ViaVersion#4168]
### `/viaversion dump` Output

not needed

### Bug Description

So you can basically disable fall damage by just spamming right click with bucket in hand.
It's caused by https://github.com/ViaVersion/ViaVersion/commit/9674c617ca1cc399dc78b9f5114db97d1a3c2a00
by line:
```java
playerRotation.write(Types.BOOLEAN, true); // On Ground
````

we need to send last onGround status sent by client

### Steps to Reproduce

1. login with 1.21 client on older server (such as 1.18 for example)
2. jump from some hill (beyond 3.0 blocks)
3. spam right click with water bucket in hand
4. done - basically 0 fall damage taken

https://youtu.be/PlVkIr4-miY

### Expected Behavior

not being able to cancel fall damage

### Additional Server Info

also I don't think this option should work for 1.8 servers, as you can use it as regen cheat, because of way 1.8 server calculates how many ticks passed based on client movement packets

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>
