### ISSUE TITLE
ERROR IN Protocol1_20To1_20_2 IN REMAP OF UPDATE_RECIPES (0x6D)

### ISSUE THREAD

**Issue by nma-ro** [ViaVersion/ViaVersion#4171]
### `/viaversion dump` Output

https://dump.viaversion.com/15c1421be1f0eb10054050f007e26b329148d944a68558e4815facb96a87edcb

### Console Error

```
https://mclo.gs/Q7tGilA
```

### Bug Description

Attempting to load into a Fabric 1.20.1 server with Create 1.20.1 installed from latest Bedrock 1.20 client (1.20.81.01) and get immediately kicked with an error.
ViaVersion is installed on Velocity proxy.

### Steps to Reproduce

1. Attempt to connect using latest Bedrock 1.20 client
2. Get kicked from server with "io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository" ... "Caused by: java.lang.IndexOutOfBoundsException: readerIndex(275721) + length(109) exceeds writerIndex(275769): PooledUnsafeDirectByteBuf(ridx: 275721, widx: 275769, cap: 524288)"

### Expected Behavior

Client connection succeeds and world loads for use.

### Additional Server Info

Using Velocity to connect from a Bedrock Client with Geyser-Velocity, floodgate-velocity.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.4.0--SNAPSHOT%20%28git--99aaf3ce--b439%29](https://img.shields.io/badge/Platform-velocity%203.4.0--SNAPSHOT%20%28git--99aaf3ce--b439%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by nma-ro** [comment]
Connection works flawlessly with following Java clients:
- 1.21.1 without Create installed
- 1.20.1 with Create installed

**Comment by FlorianMichael** [comment]
Joining servers with mods installed isn't supported, does this issue also appear when the Fabric server doesn't have any mods installed?

**Comment by nma-ro** [comment]
> does this issue also appear when the Fabric server doesn't have any mods installed?

No. Issue does not appear on unmodded fabric server.

**Comment by FlorianMichael** [comment]
Then this is down to networking changes in the Fabric API (and the create mod) and cannot be fixed by us.
