### ISSUE TITLE
Sidebar line styling broken on 1.12.2- servers with 1.13+ clients

### ISSUE THREAD

**Issue by vytskalt** [ViaVersion/ViaVersion#4179]
### `/viaversion dump` Output

https://dump.viaversion.com/1586d9943d03359a56ae2379fb17dc7e2d8b001a46c4b7993d35fa32f002d4ad

### Bug Description

Looks like sidebar lines are incorrectly translated when on a 1.12.2- server with 1.13+ clients

### Steps to Reproduce

This is a minimal reproduction plugin using [scoreboard-library](https://github.com/MegavexNetwork/scoreboard-library):
```java
public class SidebarBug extends JavaPlugin implements Listener {
  private ScoreboardLibrary library;
  private Sidebar sidebar;

  @Override
  public void onEnable() {
    try {
      this.library = ScoreboardLibrary.loadScoreboardLibrary(this);
    } catch (NoPacketAdapterAvailableException e) {
      getServer().getPluginManager().disablePlugin(this);
      return;
    }

    this.sidebar = library.createSidebar();
    final Style decoration = Style.style(NamedTextColor.AQUA, TextDecoration.BOLD);
    this.sidebar.line(0, Component.text("AAAAAAAAAAAAAAAAAAAAAAAAAAA123", decoration));

    getServer().getPluginManager().registerEvents(this, this);
  }

  @Override
  public void onDisable() {
    if (this.library != null) {
      this.sidebar.close();
      this.library.close();
    }
  }

  @EventHandler
  public void onJoin(PlayerJoinEvent event) {
    this.sidebar.addPlayer(event.getPlayer());
  }

  @EventHandler
  public void onQuit(PlayerQuitEvent event) {
    this.sidebar.removePlayer(event.getPlayer());
  }
}
```

build.gradle.kts:
```kotlin
plugins {
  id("java")
  id("com.gradleup.shadow") version "8.3.3"
}

group = "net.megavex"
version = "2.0.0"

repositories {
  mavenCentral()
  maven("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
  maven("https://oss.sonatype.org/content/repositories/snapshots")
}

java {
  sourceCompatibility = JavaVersion.VERSION_1_8
  targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.build {
  dependsOn(tasks.shadowJar)
}

dependencies {
  compileOnly("org.spigotmc:spigot-api:1.8.8-R0.1-SNAPSHOT")
  implementation("net.kyori:adventure-platform-bukkit:4.1.2")

  val scoreboardLibraryVersion = "2.1.12"
  implementation("net.megavex:scoreboard-library-api:$scoreboardLibraryVersion")
  runtimeOnly("net.megavex:scoreboard-library-implementation:$scoreboardLibraryVersion")
  runtimeOnly("net.megavex:scoreboard-library-v1_8_R3:$scoreboardLibraryVersion")
}
```

(I am the author of the library so I can change anything if needed.)

How it looks like on a 1.8.9 client (correct):
![image](https://github.com/user-attachments/assets/e648d488-3105-4174-978f-38ce856b87e9)

And 1.20.4 client (incorrect):
![image](https://github.com/user-attachments/assets/b2f82c37-5473-4503-9ce3-24da773677b0)

### Expected Behavior

The line should not lose its bold styling on 1.13+ clients

### Additional Server Info

1.8 [SportPaper](https://github.com/Electroid/SportPaper) server. No other plugins than ViaVersion and the test plugin.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--SportPaper--833e90a--P.dcea720--SP.771451c--CB.e1ebe52%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--SportPaper--833e90a--P.dcea720--SP.771451c--CB.e1ebe52%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (5.0.3): 65 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.3)-65%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Barvalg** [comment]
![Platform: git--SportPaper--833e90a--P.dcea720--SP.771451c--CB.e1ebe52%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--SportPaper--833e90a--P.dcea720--SP.771451c--CB.e1ebe52%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by vytskalt** [comment]
Worked around it in the library
