### ISSUE TITLE
Mining is way slower on v5.0.4

### ISSUE THREAD

**Issue by jensjeflensje** [ViaVersion/ViaVersion#4182]
### `/viaversion dump` Output

https://dump.viaversion.com/812204f1f33f2c35074a98d13d0446b021cc34e0e71365d5b8b9049c8ad5152d

### Bug Description

Mining stone with pickaxes is way slower than usual when running ViaVersion v5.0.4 and using a 1.21.1 client.

### Steps to Reproduce

1. Create a paper 1.20.4 server with ViaVersion v5.0.4
2. Join with a Minecraft 1.21.1 client in survival
3. Grab any pickaxe (I tried wooden and diamond) and try to mine stone

### Expected Behavior

The block breaking should be quicker. A stone block should be broken in 2-3 seconds with a wooden pickaxe, but it takes way longer (9-10 seconds)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--497%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--497%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.4)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by michaello01** [comment]
@kennytv issue still active on the latest update, latest working version is ViaVersion-5.0.4-SNAPSHOT.

**Comment by Kichura** [comment]
make a new issue with your own steps instead of replying to this one please.

**Comment by michaello01** [comment]
> make a new issue with your own steps instead of replying to this one please.

I will probably get rejected on the dump part
