### ISSUE TITLE
Potions Broken 1.8

### ISSUE THREAD

**Issue by iFireBl4ze** [ViaVersion/ViaVersion#4183]
### `/viaversion dump` Output

https://dump.viaversion.com/020327b98be1ac1599b9641430213d6d431749a56879f4ee9591082d08d22a0d

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

While using 1.8, potions are broken how can this be fixed ? I want to use the old potions.

https://www.youtube.com/watch?v=7HAbpeC0Vuw

### Steps to Reproduce

Use ViaVersion / Rewind / Backwards 1.20.6 Jar Java 21 Launch minecraft version 1.8 try using potions

### Expected Behavior

Potions to work on all versions or an option to enable old potions or effects.

### Additional Server Info

I use a host java 21 1.20.6 jar

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--DEV--e61b73f%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--DEV--e61b73f%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.5-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.5--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.4): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.4)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.3): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.3)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
See https://github.com/ViaVersionAddons/ViaPotions

**Comment by iFireBl4ze** [comment]
already tried that and it did not work
