### ISSUE TITLE
velocitypowered.proxy.connection.backend.BackendPlay

### ISSUE THREAD

**Issue by hieudieu393** [ViaVersion/ViaVersion#4185]
### `/viaversion dump` Output

https://dump.viaversion.com/e1fa994432191e70a8562f7919913d40be60a576ebc9ddf945a84a623b0300e0

### Console Error

https://mclo.gs/Yjtzq7J

### Bug Description

Using older versions will not be able to join the server

### Steps to Reproduce

1 login with a old version (>=1.13)
2. Join server
3. error occurred

### Expected Behavior

Join the server as usual

### Additional Server Info

I am using velocity
Plugins in dump

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
Make sure you are only running Via on either the proxy or backend, not both. Otherwise this is likely to be another plugin messing with packets, try removing other proxy and backend plugins to see which one it might be or follow the instructions from the Velocity error message to get more info
