### ISSUE TITLE
Ingame Error chat

### ISSUE THREAD

**Issue by SterlyQu** [ViaVersion/ViaVersion#4187]
### `/viaversion dump` Output

java.lang.NoClassDefFoundError.com/viaversion/api/Via

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

A user for a minecraft server tell me he have a crash ingame after he join in the server, in the chat give this error ''Has sido echado del servidor: Internal Exception: java.lang.NoClassDefFoundError.com/viaversion/api/Via'' idk how make work this

### Steps to Reproduce

Login whit a 1.20 client
Try to login into the server
Give error ''Has sido echado del servidor: Internal Exception: java.lang.NoClassDefFoundError.com/viaversion/api/Via
has sido echado de survival. Se ha producido un error interno en la conexion al servidor''
and crash

### Expected Behavior

Give TP to spawn or last place of Disconnection

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Kichura** [comment]
Your plugins are outdated.
