### ISSUE TITLE
world limit bug

### ISSUE THREAD

**Issue by Leompio82** [ViaVersion/ViaVersion#4188]
### `/viaversion dump` Output

https://dump.viaversion.com/7d4eaf14aa126714c028bf0baad3b16e1ca3a86a0d8156feeaef13dbe515fd3b

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

if you join in an older version of minecraft, the build limit is 255, but if you join with a newer version is 355. So if you join with an older version you can't build over 255 but if somebody join with a newer version can build over 319 blocks. Another limit build bug: If you join with an older version of minecraft the minium build limit is 0, but with a newer version is -60. So if you join with an older version and you find a cave that go past y 0, the game will start to bug, you can't move and you will die.

### Steps to Reproduce

if you join in an older version of minecraft, the build limit is 255, but if you join with a newer version is 355. So if you join with an older version you can't build over 255 but if somebody join with a newer version can build over 319 blocks. If you join with an older version of minecraft the miniumbluid limit is 0, but with a newer version is -60. So if you join with an older version and you find a cave that go past y 0, the game will start to bug, you can't move and you will die.

### Expected Behavior

if you join in an older version of minecraft, the build limit is 255, but if you join with a newer version is 355. So if you join with an older version you can't build over 255 but if somebody join with a newer version can build over 319 blocks. If you join with an older version of minecraft the miniumbluid limit is 0, but with a newer version is -60. So if you join with an older version and you find a cave that go past y 0, the game will start to bug, you can't move and you will die.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.1--120--57c75a4%20%28MC%3A%201.21.1%29](https://img.shields.io/badge/Platform-1.21.1--120--57c75a4%20%28MC%3A%201.21.1%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(5.0.3)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(5.0.3)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by kennytv** [comment]
This isn't fixable unfortunately, it's just a hard limit for the old client.

**Comment by Leompio82** [comment]
i updated viaversion but the bug persists
