### ISSUE TITLE
RANDOM KICKS FROM THE SERVER

### ISSUE THREAD

**Issue by Aides123** [ViaVersion/ViaVersion#4190]
### `/viaversion dump` Output

https://dump.viaversion.com/4bb82fbc7e8c0acc1b3b11eca40c71d6088e81ece1ea69631d56671a983339de

### Console Error

```
https://mclo.gs/HmywRV8
```

### Bug Description

Players are kicked off the server, I don't know what the reason is.

### Steps to Reproduce

I don't know. It knocks out different players in different situations.

### Expected Behavior

I don't know. It knocks out different players in different situations

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.1--19--8abd47b%20%28MC%3A%201.21.1%29](https://img.shields.io/badge/Platform-1.21.1--19--8abd47b%20%28MC%3A%201.21.1%29-3498db?style=flat-square) </br>![ViaVersion (5.0.5): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.5)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.4): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.4)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Caused by third-party plugins sending bad container changes to your server which viaversion itself doesn't understand about.

**Comment by Aides123** [comment]
Is there any way to find which plugin causes this?

**Comment by Kichura** [comment]
Perform a binary search by first checking to see if the server can recover from it with only viaversion + viabackwards active, if it does then check your third-party plugins next.

**Comment by FlorianMichael** [comment]
Closing as stale, we'll reopen the issue if you provide new information
