### ISSUE TITLE
Possible memory leak in UserConnectionImpl

### ISSUE THREAD

**Issue by Packsolite** [ViaVersion/ViaVersion#4191]
### `/viaversion dump` Output

https://dump.viaversion.com/ae7b54e2173ab6866408bda39d6019b81ce82e6b15be0839f27e8200cc2723c2

### Console Error

none

### Bug Description

ConnectionManagerImpl is holding instances of UserConnectionImpl that have a lightchunk storage of 12mb+ **per player**.
This is causing viaversion to consume about 40% of the entire servers memory.

![image](https://github.com/user-attachments/assets/cdbdcd2a-241f-4c18-81df-22ec4c7288fb)
![image](https://github.com/user-attachments/assets/203f2bcc-cb52-4f7b-8967-81ca61e54341)

### Steps to Reproduce

1. Install on a server with many players (lobby servers)
2. See how your memory rises
3. Create a heap dump

### Expected Behavior

To free UserConnectionImpl/light cache when no longer necessary.

### Additional Server Info

Paper 1.8.8

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--CurrySpigot--%2212af132%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--CurrySpigot--%2212af132%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (5.0.5): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.5)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
We need the full `jstack` dump and not just screenshots as otherwise, this would've been questionable.

**Comment by Packsolite** [comment]
> We need the full `jstack` dump and not just screenshots as otherwise, this would've been questionable.

Not sure if i can post it here, as it probably contains production secrets. If you really need it, can i send it to you in private?

**Comment by kennytv** [comment]
It's just the cost of translating 10 year old protocol, it's just light data for visible chunks for a render distance above 6 or 7. But you can probably disable the `cache-1_17-light` config option to help that
