### ISSUE TITLE
Version 5.0.5 not working

### ISSUE THREAD

**Issue by Geitenijs** [ViaVersion/ViaVersion#4192]
### `/viaversion dump` Output

https://dump.viaversion.com/be0fa0edcf16cb67cfbeff70be1dfec627483c833473b296639cb47d81d21e7f

### Console Error

https://mclo.gs/L8gMm1S

### Bug Description

After updating from 5.0.3 to 5.0.5, ViaVersion is no longer working. Nobody is able to join the server, no errors in the console besides the error on startup.

### Steps to Reproduce

Update to 5.0.5 and see

### Expected Behavior

Should work like it always did

### Additional Server Info

Velocity 3.4.0-SNAPSHOT (git-2c8ce219-b442)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.4.0--SNAPSHOT%20%28git--2c8ce219--b442%29](https://img.shields.io/badge/Platform-velocity%203.4.0--SNAPSHOT%20%28git--2c8ce219--b442%29-3498db?style=flat-square) </br>![ViaVersion (5.0.5): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.5)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(5.0.2)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>mixed_via</details>
