### ISSUE TITLE
Sponsor tier - API access

### ISSUE THREAD

**Issue by kangarko** [ViaVersion/ViaVersion#4195]
Hello!

I am developing a backend for a network with a custom launcher, we'd like to ask if Sponsors could get access to an API endpoint from which we can get the latest build programmatically, similar to how [the free CI json endpoint works](https://ci.viaversion.com/job/ViaVersion/api/json)?

Or, please let me know a viable solution for this case.

@clrxbl pinging you too for discussion since you are in our slack channel

Many thanks and appreciated the fast 1.21.2 update!

Matej

**Comment by kennytv** [comment]
That'd require some good amount of effort to make sure it's secured right on both sides, so at least for now it's not worth the trouble - for the few days of delay you can also instead compile them in your own ci/pipeline through the repository access and PATs (though the public release is later today anyway)

**Comment by kangarko** [comment]
Makes sense! Thanks for the headsup, and appreciated the hard work on the software.
