### ISSUE TITLE
Mining is still slow on 5.0.5

### ISSUE THREAD

**Issue by michaello01** [ViaVersion/ViaVersion#4197]
### `/viaversion dump` Output

https://dump.viaversion.com/3b77f51ca661a87f1640933cddb6845db1b14ad8d9c930b7d7f848bf62462930

### Console Error

-

### Bug Description

Mining is still slow. Same as https://github.com/ViaVersion/ViaVersion/issues/4182
latest working version is ViaVersion-5.0.4-SNAPSHOT.

### Steps to Reproduce

    Create a paper 1.20.4 server with ViaVersion v5.0.4
    Join with a Minecraft 1.21.1 client in survival
    Grab any pickaxe (I tried wooden and diamond) and try to mine stone

### Expected Behavior

Normal mining speed

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PandaSpigot--130%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PandaSpigot--130%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (5.0.5): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.5)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
You were banned from the org for posting bogus issues containing false dumps and copy pasted descriptions that don't make sense in the context of the rest of the issue. All this does is save you a miniscule amount of effort while wasting our time much more than that
