### ISSUE TITLE
The ViaBackwards plugin together with ViaVersion breaks the GSit plugin

### ISSUE THREAD

**Issue by Ayoree** [ViaVersion/ViaVersion#4198]
### `/viaversion dump` Output

none

### Bug Description

The server is running on Paper 1.21.1 with ViaVersion, ViaBackwards, and GSit installed. I connected using version 1.20.1, and when trying to execute the /sit command or use right-click on a block, a bug occurs where the player gets teleported half a block higher than it would happen without ViaVersion and ViaBackwards.

https://github.com/user-attachments/assets/6518921e-eef5-4425-821f-569626cd3aec

### Steps to Reproduce

1. Install the latest version of Paper.
2. Add the ViaVersion, ViaBackwards, and GSit plugins.
3. Connect using version 1.20.1 (the bug may appear on any version. idk).
4. Type the /sit command.

### Expected Behavior

When using the /sit command or right-clicking on a block, the player should NOT be moved half a block up.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [ ] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Kichura** [comment]
Closing this in favor of [ViaBackwards' 898](https://github.com/ViaVersion/ViaBackwards/issues/898) as OP did not make a viaversion dump for this issue, also this issue was made in wrong repo.
