### ISSUE TITLE
[1.21->1.21.2] chest boat causes disconnection

### ISSUE THREAD

**Issue by Pantera07** [ViaVersion/ViaVersion#4199]
### `/viaversion dump` Output

https://dump.viaversion.com/ad2f1f3b07b117df48fb8c26af72a22dc9583693263d9ddb0807d7b4694dd453

### Console Error

![image](https://github.com/user-attachments/assets/873dfdf7-3719-4928-8ffb-7e21cd80f209)

### Bug Description

Get on the chest boat and press the e key.

### Steps to Reproduce

1. Open 1.21.1 server.
2. Connect to 1.21.3 client.
3. Get on the chest boat and press the e key.

### Expected Behavior

no disconnection.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.1--128--d348cb8%20%28MC%3A%201.21.1%29](https://img.shields.io/badge/Platform-1.21.1--128--d348cb8%20%28MC%3A%201.21.1%29-3498db?style=flat-square) </br>![ViaVersion (5.1.0): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.0)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.0)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Can reproduce, This is likely a bug in where the chest UI in boats isn't displaying properly.
