### ISSUE TITLE
1.21 client versions (likely other versions too) behave abnormally when getting levitation 128-255 on older versions

### ISSUE THREAD

**Issue by birdevent** [ViaVersion/ViaVersion#4204]
### `/viaversion dump` Output

https://dump.viaversion.com/ca83328359e7c38bcb9ab1d59371db5e3a3afdc738ff4d00a0c2b0bb124e67c4

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

levitation 128-255 instead of acting as an inverse levitation causes clients 1.21 (only test I've done) to levitate upwards instead. [1.19.4] server

### Steps to Reproduce

just give them levitation 128-255 lmao [1.19.4] server, probably applies to other versions

### Expected Behavior

should be consistent with behavior from the 1.19.4 (or other version) levitation effects

### Additional Server Info

git-Paper-550 1.19.4

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--550%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--550%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (5.1.0): 5 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.1.0)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by kennytv** [comment]
We generally don't unfix client bugs - but even then, any change we'd do on a protocol level would still be different from the old behavior
