### ISSUE TITLE
Network Protocol Error (1.21)

### ISSUE THREAD

**Issue by lowercasebtw** [ViaVersion/ViaVersion#4206]
### `/viaversion dump` Output

_

### Console Error

```
Put the mclo.gs link or text here.
```
https://mclo.gs/jKkIBq9

### Bug Description

Cannot join 1.21/1.21.1 servers from 1.21.2/3

### Steps to Reproduce

Join raphimc.net:25564 from 1.21.3
Network Protocol error

### Expected Behavior

Join fine

### Additional Server Info

rk01's server, happens on others
I am using VFP but was told to report here
Using latest dev VFP/VV build

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Should work now
