### ISSUE TITLE
New client end tick packet could be passed to the server

### ISSUE THREAD

**Issue by Cyramek** [ViaVersion/ViaVersion#4209]
### Problem Description

1.21.2 introduces new client tick end packet, this could be useful for servers, especially for anticheats

### Solution Description

first thing is rewriting this packet for movement idle packet, but this could lead to some unknown issues (packet order etc.),
so the only thing that comes to my mind is to rewrite this packet to some sort of custom payload "viaversion:client_end_tick"

**Comment by FlorianMichael** [comment]
Hello, thank you very much for your suggestion!

We have some security concerns regarding this, such an API would allow players to send and manipulate these custom payloads themselves, also some plugins like anti crashers could kick players for sending too many custom payloads (for spamming/bad packets).

On the other hand, the ViaVersion API allows overriding packet handlers using viaversion-common, so GrimAC can implement it on their side without much effort.
This example code can be used as reference on how to modify packet handler in ViaVersion:

```
final Protocol1_21To1_21_2 protocol = Via.getManager().getProtocolManager().getProtocol(Protocol1_21To1_21_2.class);
protocol.registerServerbound(ServerboundPackets1_21_2.CLIENT_TICK_END, null, wrapper -> {
    wrapper.cancel();

    // Send your custom payload/custom handling in here
}, true);
```
