### ISSUE TITLE
Network Protocol Error when killing glowsquid

### ISSUE THREAD

**Issue by Projecki** [ViaVersion/ViaVersion#4216]
### `/viaversion dump` Output

https://dump.viaversion.com/9166106f19ee9a7e7c796739662f45696f3585e3418f4b0b4286baa84dee4edd

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

When a user on client version 1.21.2 or 1.21.3 kills a glowsquid, they are kicked for Network Protocol Error

### Steps to Reproduce

1. Log in with 1.21.2+
2. Kill glowsquid

### Expected Behavior

They should not be kicked

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--UniverseSpigot--%223e1e308%22%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--UniverseSpigot--%223e1e308%22%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(5.1.0--SNAPSHOT)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(5.1.0--SNAPSHOT)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
