### ISSUE TITLE
ViaVersion 5.10 does not work with spygot 1.21.3 by client 1.21.41

### ISSUE THREAD

**Issue by max-sgt** [ViaVersion/ViaVersion#4219]
### `/viaversion dump` Output

no dump

### Console Error

[20:25:10] [localSession-7-2/INFO]: [Geyser-Spigot] USER has disconnected from the Java server because of Outdated client! Please use 1.21.3

### Bug Description

ViaVersion 5.10 does not work on the Spigot 1.21.3 server when connecting clients from 1.21.41(Android, Nintendo).

### Steps to Reproduce

Login with a 1.21.41 client to Spigot 1.21.3(Geyser-Spigot)

### Expected Behavior

I expect to see a solution to the problem.

### Additional Server Info

Spigot 1.21.3 with Geyser-Spigot, ViaVersion 5.10

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
Geyser does Bedrock support, not ViaVersion. You're probably outdated
