### ISSUE TITLE
ViaVersion bug/error

### ISSUE THREAD

**Issue by xProMDFKx** [ViaVersion/ViaVersion#4226]
### `/viaversion dump` Output

https://dump.viaversion.com/24c70be2ece6fd0d034f47f6a1e5e67465fa6d59a0aa0daf9f6dafcccbe618d3

### Console Error

```
Put the mclo.gs link or text here.
```
https://mclo.gs/Iu35z67

### Bug Description

It shows a lot of errors

### Steps to Reproduce

Dont know surely

### Expected Behavior

Should not show the error

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Carbon--5eb59fa3%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--Carbon--5eb59fa3%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (5.1.0): 28 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.1.0)-28%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by xProMDFKx** [comment]
It still happens

**Comment by Kichura** [comment]
Caused by third-party plugins on your server sending bad maps that have bulked chunks in them, as for the server stopping itself - that is not caused by us.
