### ISSUE TITLE
Custom paintings kick client on 1.21.1

### ISSUE THREAD

**Issue by ICY105** [ViaVersion/ViaVersion#4227]
### `/viaversion dump` Output

https://dump.viaversion.com/428677ced6cf1ea5bccac917717d2cdb446a7b0158835d4f4d3848389f259cbd

### Bug Description

Connecting to a server running 1.21.1 with a custom painting added via datapack using a client running 1.21.3 will kick the client. Clients running 1.21.1 can connect ok.

### Steps to Reproduce

Place a custom painting

### Expected Behavior

Custom paintings do not kick clients.

### Additional Server Info

Tested on both fabric backend and velocity frontend.

Attached is a simple datapack that adds a custom painting. Give yourself the custom painting with:

 `/give @s minecraft:painting[minecraft:entity_data={id:"minecraft:painting",variant:{"asset_id":"painting:test",height:1,width:1}}]`

[datapack.zip](https://github.com/user-attachments/files/17579911/datapack.zip)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.4.15+84--main](https://img.shields.io/badge/Platform-0.4.15+84--main-3498db?style=flat-square) </br>![ViaVersion (5.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
