### ISSUE TITLE
Error Viaversion

### ISSUE THREAD

**Issue by Xstream0** [ViaVersion/ViaVersion#4231]
### `/viaversion dump` Output

https://dump.viaversion.com/9c119aacc5ed40c607e7954e4e300027e435ccd36231ce3884ff415f5f349486

### Console Error

![Screenshot 2024-11-01 135937](https://github.com/user-attachments/assets/700c103c-014c-4cbb-80bd-54ddf5f92310)

### Bug Description

Hi, when I enter my Minecraft server created with Aternos and having inserted viaversion, viabackwards and viarewind it gives me the following error:
![Screenshot 2024-11-01 135042](https://github.com/user-attachments/assets/5196e158-eb25-4098-917e-0c195fb31d9a)
The server is in 1.20.4 paper/bukkit and and i tried 1.8.9. How do I solve it?

### Steps to Reproduce

I think you understand

### Expected Behavior

I expected to log into the server normally

### Additional Server Info

I use aternos

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
1. Switch from Spigot to Paper in terms of server recommendation,
2. Update the plugins from the plugins search page,
3. Remove the old JARs from files page -> plugins folder.

**Comment by Xstream0** [comment]
Yes but if I put the paper I lost all the plugins and their configs

**Comment by Kichura** [comment]
> Yes but if I put the paper I lost all the plugins and their configs

that's not correct as spigot<->paper transition is compatible, same rule applies to purpur.

**Comment by Xstream0** [comment]
You have discord? I want to test with you

**Comment by Kichura** [comment]
Join the [ViaVersion discord](https://discord.gg/ViaVersion) if you have to, but please don't request for private support or in this case, private messaging.

**Comment by Xstream0** [comment]
Ok sorry

**Comment by Xstream0** [comment]
![immagine_2024-11-01_144015067](https://github.com/user-attachments/assets/1df6e6d3-6644-4fa1-ab32-c35ac11c7abe)
So at this point do I have to click on the paper/bukkit?

**Comment by Kichura** [comment]
Tap the Paper/Bukkit button and then select the version you need. *(in this case, yours is 1.20.4)*

**Comment by Xstream0** [comment]
Ok

**Comment by Xstream0** [comment]
Ok i do it now i test to enter with 1.8.9?

**Comment by Kichura** [comment]
> Ok i do it now i test to enter with 1.8.9?

No, once you migrated to paper; begin updating ViaVersion, ViaBackwards, ViaRewind and TAB through the plugins search list, but before deploying - double check if the search results mention `modrinth.com` or `hangar.papermc.io` as `spigotmc` does not contain the latest builds.

**Comment by Xstream0** [comment]
Ok now i do it wait a few second

**Comment by Kichura** [comment]
> Only tab or all plugins?

Reread my answer, i mentioned all four.

**Comment by Xstream0** [comment]
Do I mean all the plugins on my server or just the 4?

**Comment by Kichura** [comment]
just the four, the rest don't matter right now.

**Comment by Xstream0** [comment]
I mean what should I do now?

**Comment by Kichura** [comment]
As for the plugin sources *(in case you are lost in aternos)*, Tap the blue texts to get to them quickly:

[ViaVersion](https://aternos.org/addons/a/hangar/ViaVersion),
[ViaBackwards](https://aternos.org/addons/a/hangar/ViaBackwards),
[ViaRewind](https://aternos.org/addons/a/hangar/ViaRewind),
[TAB](https://aternos.org/addons/a/modrinthbukkit/gG7VFbG0).

Once updated, Verify the old JARs are removed in files page -> plugins folder and then reboot.

**Comment by Xstream0** [comment]
Yes, I have already downloaded the ones you sent me

**Comment by Xstream0** [comment]
Now?

**Comment by Kichura** [comment]
Once rebooted, connect with 1.8.9 and observe any errors that are viaversion related.

**Comment by Xstream0** [comment]
Ok now i test

**Comment by Xstream0** [comment]
ok now it works thank you very much for the assistance, goodbye
