### ISSUE TITLE
Players can't join my 1.20.4 server with version 1.20.1

### ISSUE THREAD

**Issue by laurenslaurensly** [ViaVersion/ViaVersion#4234]
### `/viaversion dump` Output

https://dump.viaversion.com/64ecea36d0203b856352fcbac80c7bfe87a81e00669aa6f49cf20ae2b15c6758

### Console Error

```
lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NoSuchMethodError: 'com.viaversion.viaversion.api.protocol.remapper.PacketHandler com.viaversion.viaversion.rewriter.TagRewriter.getGenericHandler()'
```

### Bug Description

Players can't join my 1.20.4 server with version 1.20.1

### Steps to Reproduce

Launch 1.20.1 client
Join undeaddupe.minehut.gg

### Expected Behavior

Players should be able to join from any 1.20 version.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--499%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--499%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(5.0.5)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(5.0.0)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>mixed_via</details>
