### ISSUE TITLE
Efficiency is too easy to desync

### ISSUE THREAD

**Issue by Pablete1234** [ViaVersion/ViaVersion#4235]
### `/viaversion dump` Output

https://dump.viaversion.com/4811191c9ece2273c9d268581078a3937a930e2b8dfc21ef06d897ede6eeed45

### Bug Description

Related to https://github.com/ViaVersion/ViaVersion/pull/4060/files#diff-bddbbce71dc4ad767a0aa0ae4037a037505e51083cfbd135297a0849090f6ae8

For older servers (1.8) given the lack of a `PlayerInventorySlotChangeEvent` efficiency desyncs way too easily.

### Steps to Reproduce

Efficiency is only applied if you switch what your held item slot is, meaning a bunch of ways of getting efficiency end up with your pickaxe doing no efficiency unless you switch selected slot.

Some ways i've stumbled across which were annoying:
- Picking up a pickaxe directly in your held slot
- Moving an item in your inventory to your held slot (it be by clicks, or clicking the hotbar key to swap the item in)
- If a command or plugin modifies the item in your held slot (eg: /replaceitem )

### Expected Behavior

Enchantments (mainly, efficiency) should promptly apply whenever the item changes, in any way.

On legacy you should either listen to a bunch of events (item pickup, item destroy, inventory click), or, maybe better, do this at protocol level: whenever an item inventory change packet is sent, if it's for the held slot, update the attributes alongside it.
Is there any reason this can't be done at item remap level? ie: if an item has efficiency send it as having an attribute modifier for mining speed to the client.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--SportPaper--9e59d7a--P.1d22073--SP.699dc76--CB.e1ebe52%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--SportPaper--9e59d7a--P.1d22073--SP.699dc76--CB.e1ebe52%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (5.1.1): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.1)-Even%20with%20master-brightgreen?style=flat-square) </br>
