### ISSUE TITLE
Security alert / crash / spam logs / timed out players

### ISSUE THREAD

**Issue by Incluuu** [ViaVersion/ViaVersion#4237]
### `/viaversion dump` Output

https://dump.viaversion.com/4680f2d1a76fcae8e25dfa67553366b49e5c34d4b5c5a049ea40dcd308c10743

### Console Error

```
[Put the mclo.gs link or text here.](https://mclo.gs/B3Rzfu3)
```

### Bug Description

Xynis client

### Steps to Reproduce

Xynis client, idk

### Expected Behavior

stop spam logs - 2 milions lines, timed out players

### Additional Server Info

Velocity + paper 1.21.1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.1--131--84281ce%20%28MC%3A%201.21.1%29](https://img.shields.io/badge/Platform-1.21.1--131--84281ce%20%28MC%3A%201.21.1%29-3498db?style=flat-square) </br>![ViaVersion (5.1.1): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Fixed with the next build
