### ISSUE TITLE
ERROR IN Protocol1_17To1_16_4 IN REMAP OF LEVEL_CHUNK (0x22)

### ISSUE THREAD

**Issue by y11t0** [ViaVersion/ViaVersion#4239]
### `/viaversion dump` Output

https://dump.viaversion.com/56e19b4f59e73b9119e93235378eb9224664707493396c5a7ffb4affb173e514

### Console Error

https://mclo.gs/8pwMwzX

### Bug Description

I can't connect 1.20.6 server with 1.16.4

### Steps to Reproduce

1. Login with a 1.16.4 client
2. "An internal error occured in your connection."

### Expected Behavior

The map should load normally

### Additional Server Info

I tried all backend and velocity servers without plugins.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.4.0--SNAPSHOT%20%28git--08a42b37--b449%29](https://img.shields.io/badge/Platform-velocity%203.4.0--SNAPSHOT%20%28git--08a42b37--b449%29-3498db?style=flat-square) </br>![ViaVersion (5.1.1): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.1.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.1.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.1)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Kichura** [comment]
Limbo is not supported, Move viaversion to the backend servers or remove limbo.

**Comment by y11t0** [comment]
I tried without limbo and the result was the same

**Comment by Kichura** [comment]
can you move viaversion to the spigot/paper server then?

**Comment by y11t0** [comment]
Sorry, I tried it now without limbo and it worked normally. I don't know why it didn't work before.Thanks!
