### ISSUE TITLE
I am using Velocity 3.4.0 #build449 and PurPur 1.2.1 #bulid2329 with viaversion 5.1.1 and viabackwards5.1.1. However, I cannot connect from vanilla clients 1.21.2 and 1.21.3.(same issue snapshots)

### ISSUE THREAD

**Issue by mifjpn** [ViaVersion/ViaVersion#4243]
### `/viaversion dump` Output

https://dump.viaversion.com/94ed17eb3a018a72326331cffeba0795ef05c4668814cf73ca3193d1709c3b6f

### Console Error

[00:27:44 ERROR]: [server connection] .fairy_nakata -> server1: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@40e83c91
com.velocitypowered.proxy.util.except.QuietRuntimeException: A packet did not decode successfully (invalid data). For more information, launch Velocity with -Dvelocity.packet-decode-logging=true to see more.
[00:27:44 INFO]: [server connection] .fairy_nakata -> server1 has disconnected
[00:27:44 INFO]: [connected player] .fairy_nakata (/192.168.0.1:0) has disconnected: server1 との接続に問題が発生しました。

### Bug Description

I'm using the latest Velocity (#429) with the latest Geyser and Floodgate, and the latest PurPur 1.21.1 snapshot version (2024/11/6 JST), which should be the first to connect, but the Bedrock client can't connect.

Vanilla Java clients 1.21.2 and 1.21.3 can't connect

### Steps to Reproduce

1.Prepair Velocity 3.4.0 #build449,Geyser #706,floodgate #113
2.Prepair PurPur 1.2.1 #bulid2329
3.viaversion 5.1.1 and viabackwards5.1.1.(and Discord #link snapshot) setting above there.(Velocity and purpur)
 However, I cannot connect from vanilla clients 1.21.2 and 1.21.3

### Expected Behavior

Connect 1.21.2,1.21.3
Connect Bedrock client

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.4.0--SNAPSHOT%20%28git--08a42b37--b449%29](https://img.shields.io/badge/Platform-velocity%203.4.0--SNAPSHOT%20%28git--08a42b37--b449%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by mifjpn** [comment]
I use [5.1.2-SNAPSHOT+608 , 1.21.2 client connect 30sec.and can't connect anymore...

**Comment by mifjpn** [comment]
#1025 I can connect client 1.21.2.
https://dump.viaversion.com/f41a714343f6228757b108b4338564f6d9ef8db1a4ebcbd62a8c994f06cc68b5

**Comment by Barvalg** [comment]
![Platform: velocity%203.4.0--SNAPSHOT%20%28git--08a42b37--b449%29](https://img.shields.io/badge/Platform-velocity%203.4.0--SNAPSHOT%20%28git--08a42b37--b449%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
