### ISSUE TITLE
Custom Armor Trims broken on latest version (again)

### ISSUE THREAD

**Issue by AlphaHydra** [ViaVersion/ViaVersion#4246]
### `/viaversion dump` Output

https://dump.viaversion.com/e1546e7c5b4b95f3a4869dc50a5197e5ce6ec6bfbaae5af1d73309cda6731084

### Bug Description

Like before, Custom Armor trim patterns no longer display on the latest versions of MC, this is highly detrimental to any and all servers who are trying to make any servers with custom resource packs and makes public servers look highly unprofessional.

![image](https://github.com/user-attachments/assets/97e17d6b-4c65-4887-a664-b5ac851e52e1)
![image](https://github.com/user-attachments/assets/33235a6e-8c6b-403f-9caa-70f269f56f46)

Strangely, when making a new armor piece, it doesn't even display the "trim" icon, regardless, it makes it custom armor, cosmetics, etc, completely worthless and immersion breaking.
![image](https://github.com/user-attachments/assets/c334d085-b5f1-47ef-98fb-edfcdf133b71)

### Steps to Reproduce

1. Get a resource pack that adds new armor trims (A test file is provided below)
2. Add to server
3. Run command to gain armor trim, for example:

`give @p diamond_chestplate{Trim:{material:"minecraft:emerald",pattern:"minecraft:azothbend"}} 1`

Here is a test file with new armor trims.
[testfile.zip](https://github.com/user-attachments/files/17639453/testfile.zip)

### Expected Behavior

Like when this bug was initially fixed, it would simply display the correct armor trims.
![image](https://github.com/user-attachments/assets/b101ce12-4d41-4ca8-bda2-9ca609d6d61b)

### Additional Server Info

- No Proxy
- Paper 1.20.1

Plugin list:
![image](https://github.com/user-attachments/assets/41385067-742e-4662-8462-25969dde3f08)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--196%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--196%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Closing as stale, please make sure that your resourcepack is compatible with 1.21.2. If you can provide more information, we'll reopen the issue
