### ISSUE TITLE
Kicks when enchanted at the enchantment table and in the anvil.

### ISSUE THREAD

**Issue by shiksyt** [ViaVersion/ViaVersion#4247]
### `/viaversion dump` Output

 https://dump.viaversion.com/42d97ce5dda39917233a38356551595a4067ed84e220d0cd269da939dcba81e9

### Console Error

```
Put the mclo.gs link or text here.
```
https://mclo.gs/JQHgPnm

### Bug Description

Kicks when enchanted at the enchantment table and in the anvil.

### Steps to Reproduce

1. Login to the 1.21.3 server from 1.21.1
2. Place an anvil and an enchantment table
3. Try to enchant in it.

### Expected Behavior

To make a thing enchanted

### Additional Server Info

I use velocity

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.3--13--42a1901%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--13--42a1901%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by shiksyt** [comment]
![image](https://github.com/user-attachments/assets/fdd728a8-4b13-47ad-bc28-89769093b9d2)
Error from the player

**Comment by kennytv** [comment]
Fixed by https://github.com/ViaVersion/ViaBackwards/commit/3a67be7fe5add592cc5d2bf8be23307ba430f94e
