### ISSUE TITLE
Minecraft Server 1.19.4 Doesn't Work With Latest ViaVersion

### ISSUE THREAD

**Issue by stumper66** [ViaVersion/ViaVersion#4250]
### `/viaversion dump` Output

https://dump.viaversion.com/3a2e5c82f53112ca75fcbc4bdd995be939dd980cb3245452ba52b9712b87bb22

### Console Error

```
[10:08:58] [Netty Server IO #1/WARN]: [ViaVersion] ERROR IN Protocol1_20_3To1_20_5 IN REMAP OF UPDATE_MOB_EFFECT (0x72)
```

### Bug Description

When I try to join the server with my Minecraft 1.21.1 client it will immediately fail to join and show error "Network Protocol Error".
Client error log is attached.

[disconnect-2024-11-07_10.08.58-client.txt](https://github.com/user-attachments/files/17665670/disconnect-2024-11-07_10.08.58-client.txt)

### Steps to Reproduce

Install ViaVersion and ViaBackwards versions 5.1.1 on a Spigot or Paper server 1.19.4 version. Boot up Minecraft 1.21.1 client and attempt to connect.

### Expected Behavior

Join server without error.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3763--Spigot--7d7b241--5a5e43e%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-3763--Spigot--7d7b241--5a5e43e%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (5.1.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.1.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.1.1): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.1.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by stumper66** [comment]
It will happens with latest dev builds. New dump:
https://dump.viaversion.com/b17cbb0b2e098f5c1286b23db8932e77431a9639f8964f4e4534b001fa0a1d9e

**Comment by Barvalg** [comment]
![Platform: git--Paper--550%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--550%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (5.1.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.1.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.1.1): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.1.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by stumper66** [comment]
It still happens with latest dev builds. New dump:
https://dump.viaversion.com/c0f4c75454688df70bd4ed57846a092ddbdc7361e12be4b842e2ba5a702df8b9

**Comment by Barvalg** [comment]
![Platform: 3763--Spigot--7d7b241--5a5e43e%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-3763--Spigot--7d7b241--5a5e43e%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
This looks like a nochatreports issue
