### ISSUE TITLE
Enchanting kick bug

### ISSUE THREAD

**Issue by AlexaKood** [ViaVersion/ViaVersion#4251]
### `/viaversion dump` Output

https://dump.viaversion.com/e239df63896d9f00786b3d15b923727eaa9c4fc237c82f87cf7b0e1f2c153f1c

### Console Error

Console error:
```
lost connection: Disconnected
... left the game
```
Client Error:
```
Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:container_set_slot'
```

### Bug Description

Trying to enchant Sharpness V to diamond sword that has the following enchantments:
- Bane of arthropods IV
- Fire Aspect II
- Looting III

Causes the client to get kicked from the server with the following message:
![image](https://github.com/user-attachments/assets/47cd4b11-d0d5-4753-8f0f-891e986dbdc8)

### Steps to Reproduce

1. Install ViaVersion and ViaBackwards 5.1.1
2. Go to 1.21.3 server with a Fabric 1.21.1 client
3. Try to make the enchantment mentioned above
4. Notice that you can't and try to close out from the enchant menu
5. Get kicked from the server
6. Profit???

### Expected Behavior

I thought that I could enchant my sword, but turns out since I have Bane of arthropods I shouldn't be able to do it, but it still shouldn't get kicked

### Additional Server Info

Paper 1.21.3 server with the following plugins:
- AuthMe,
- BlueMap, 
- Essentials, 
- EssentialsChat, 
- LuckPerms, 
- PlaceholderAPI, 
- SkinsRestorer, 
- TAB, 
- Vault, 
- ViaBackwards 
- ViaVersion

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.3--11--a6df4c8%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--11--a6df4c8%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.1.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.1.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.1.1): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.1.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Barvalg** [comment]
![Platform: 1.21.3--11--a6df4c8%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--11--a6df4c8%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Fixed by https://github.com/ViaVersion/ViaBackwards/commit/3a67be7fe5add592cc5d2bf8be23307ba430f94e

**Comment by FrancescoJacovo** [comment]
we have the same issues but with custom enchant created by TokenEnchant plugin

https://mclo.gs/k1f7XPP
