### ISSUE TITLE
Sunlight scoreboard dosent work with viaversion

### ISSUE THREAD

**Issue by Target9** [ViaVersion/ViaVersion#4252]
### `/viaversion dump` Output

https://dump.viaversion.com/2916d9a3a40e89440697234a4426a4cbfa0e46f24bf67e00442d77db70de6b8c

### Console Error

Theres no console error when connecting.

### Bug Description

When i connect on a 1.20 to my 1.21 server the scoreboard dosent wrok
![image2](https://github.com/user-attachments/assets/3a15450f-b409-4b00-b4f5-22a16245f1ad)
![image](https://github.com/user-attachments/assets/ec8168ce-7d4e-4593-8f27-945b5043737c)

### Steps to Reproduce

Run a server on 1.21 using paper with sunlight nightcore pacetevents and placeholder api.

### Expected Behavior

The scoreboard should work

### Additional Server Info

I use a velocity.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.1--128--d348cb8%20%28MC%3A%201.21.1%29](https://img.shields.io/badge/Platform-1.21.1--128--d348cb8%20%28MC%3A%201.21.1%29-3498db?style=flat-square) </br>![ViaVersion (5.1.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.1.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.1.1): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.1.1)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(4.0.2)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
