### ISSUE TITLE
 lost connection: Internal Exception

### ISSUE THREAD

**Issue by lootfarmig** [ViaVersion/ViaVersion#4253]
### `/viaversion dump` Output

https://dump.viaversion.com/8de6ba2761842a54fc114e0e026063116f65e586bdcdab3a3f1f632bd376a3be

### Console Error

Server: Dionysus 1.12.2
I've been logging in since version 1.12.2 and above - everything works
Login from version 1.8 is not available
The player writes "Disconnected"
In the console, "<nick> lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NoSuchMethodError: 'void com.viaversion.viaversion.api.minecraft.ClientWorld.setEnvironment(int)'"

### Bug Description

no

### Steps to Reproduce

1. The player turns on version 1.8 and launches minecraft
2. Clicks on the multiplayer mode
3. clicks on the server and join
4. The server is writing Disconnected

### Expected Behavior

A player from version 1.8 logged into the server

### Additional Server Info

![изображение](https://github.com/user-attachments/assets/4b14fcb3-c5de-4298-a84d-6c1216a83940)
![изображение](https://github.com/user-attachments/assets/e4a87460-3e7d-4118-a936-50d1a7302f96)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Dionysus--%228d3095e%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Dionysus--%228d3095e%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (5.1.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.1.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(4.0.2)-Outdated!-red?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>mixed_via</details>

**Comment by lootfarmig** [comment]
https://dump.viaversion.com/c31fb6cd0ad5b4eabd997c4a0190f0f7d51717f9b97902faaa7e932100a7d120

**Comment by Barvalg** [comment]
![Platform: git--Dionysus--%228d3095e%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Dionysus--%228d3095e%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(4.0.2)-Outdated!-red?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by lootfarmig** [comment]
https://dump.viaversion.com/c31fb6cd0ad5b4eabd997c4a0190f0f7d51717f9b97902faaa7e932100a7d120

**Comment by Barvalg** [comment]
![Platform: git--Dionysus--%228d3095e%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Dionysus--%228d3095e%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(4.0.2)-Outdated!-red?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Kichura** [comment]
Update ViaRewind, 4.0.2 is not latest.

**Comment by lootfarmig** [comment]
https://dump.viaversion.com/d4689830cd551fe2bd4256e03f377543025dae12e0cc5c4c6bfae1fd6b2badf6
![изображение](https://github.com/user-attachments/assets/2b4a96ba-8c96-46bc-97b0-8d4ed4a331dc)

**Comment by Barvalg** [comment]
![Platform: git--Reaper--%221454595%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Reaper--%221454595%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (5.1.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.1.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(4.0.2)-Outdated!-red?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
