### ISSUE TITLE
com.viaversion.viaversion.api.minecraft.ClientWorld.setEnvironment(int)

### ISSUE THREAD

**Issue by lootfarmig** [ViaVersion/ViaVersion#4254]
### `/viaversion dump` Output

https://dump.viaversion.com/d4689830cd551fe2bd4256e03f377543025dae12e0cc5c4c6bfae1fd6b2badf6

### Console Error

Quasienn lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NoSuchMethodError: 'void com.viaversion.viaversion.api.minecraft.ClientWorld.setEnvironment(int)'

### Bug Description

The player sees "Disconnected", and in the console "io.netty.handler.codec.EncoderException: java.lang.NoSuchMethodError: 'void com.viaversion.viaversion.api.minecraft.ClientWorld.setEnvironment(int)'"

### Steps to Reproduce

1.     The player turns on version 1.8 and launches minecraft
2.     Clicks on the multiplayer mode
3.     clicks on the server and join
4.     The server is writing Disconnected

### Expected Behavior

A player from version 1.8 logged into the server

### Additional Server Info

![изображение](https://github.com/user-attachments/assets/4cbe9c2f-f2fb-4310-b36c-e26e9e81b330)
![изображение](https://github.com/user-attachments/assets/18d6f4a9-fa5c-461d-a006-528bf36933a5)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Reaper--%221454595%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Reaper--%221454595%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (5.1.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.1.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind%20(4.0.2)-Outdated!-red?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>mixed_via</details>

**Comment by Kichura** [comment]
You still didn't update viarewind to 4.0.4-SNAPSHOT.

**Comment by kennytv** [comment]
Please stop opening new issues, you were already told how to fix it
