### ISSUE TITLE
1.20.2 players unaffected by water, vines, and ladders since 5.0.4

### ISSUE THREAD

**Issue by calcastor** [ViaVersion/ViaVersion#4258]
### `/viaversion dump` Output

https://dump.viaversion.com/a4e215dc50c2dfea4711d9cf5ed9546a14b71be106b249e53f704dd8a8681da8

### Console Error

None

### Bug Description

This issue is bisected to 50084c112db07979653af91464e51de44df476d2

Logging onto a 1.8.8 server with a 1.20.2 client initially results in the player on 1.20.2 being able to walk through water as if it is not there. It also prevents such players from climbing ladders or vines. If the player joins a different world, the issue stops occurring but the issue occurs again if the player logs out and logs back in.

### Steps to Reproduce

1. Use current latest ViaVersion on a 1.8.8 server
2. Log on with a 1.20.2 client
3. Enter water, and observe walking through it as though it were air. Observe not being able to climb vines or ladders.

### Expected Behavior

Water behaves like water for a 1.20.2 client, vines and ladders are climbable

### Additional Server Info

The test environment uses Velocity, with some proprietary plugins and some things like LuckPerms and Tebex. 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--SportPaper--09062d3--P.1c3019f--SP.3ea7314--CB.e1ebe52%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--SportPaper--09062d3--P.1c3019f--SP.3ea7314--CB.e1ebe52%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by calcastor** [comment]
Confirming and closing as such
