### ISSUE TITLE
Minecraft Network Protocol Error

### ISSUE THREAD

**Issue by cloakfox** [ViaVersion/ViaVersion#4259]
### `/viaversion dump` Output

https://dump.viaversion.com/3e56305df804e2f72c3e43140e3a435a749c767b46579f29800c4becf0a30874

### Console Error

No console errors are observed

### Bug Description

Players that teleport to a specific players warp are instantly getting kicked/disconnected from the server with a "Network Protocol Error"

Client logs show this:
https://gist.github.com/cloakfox/54b85b463bd5adfa9534a610ba85244d

Seems to be related to bundles maybe?

### Steps to Reproduce

Join IP: play.foxcraft.net, join oneblock gamemode, use /pwarp go Zephriah -> get disconnected

### Expected Behavior

To be able to walk around the players warp/shop

### Additional Server Info

We use waterfall (with latest upstream Bungeecord merged, up until Oct. 22nd)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.1--DEV--164e116%20%28MC%3A%201.21.1%29](https://img.shields.io/badge/Platform-1.21.1--DEV--164e116%20%28MC%3A%201.21.1%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
It says "The welcome sign is currently locked." when I try warping there

**Comment by cloakfox** [comment]
> It says "The welcome sign is currently locked." when I try warping there

Frick, my bad, let me unlock it xd

**Comment by cloakfox** [comment]
> It says "The welcome sign is currently locked." when I try warping there

It should now be unlocked!

**Comment by kennytv** [comment]
From a quick look I don't think this would be on Via, but possibly your pets plugin sending bad entity data, specifically for foxes

**Comment by cloakfox** [comment]
> From a quick look I don't think this would be on Via, but possibly your pets plugin sending bad entity data, specifically for foxes

I noticed that it's possible to teleport & walk around the players pwarp location when on a lower version like 1.20.1

**Comment by kennytv** [comment]
Bad OOB data was previously ignored, but it's still bad data that the plugin would have to fix in any case. The server there is 1.21.1 just to confirm, right?

**Comment by kennytv** [comment]
For reference, you can find the correct values here https://kennytv.github.io/ViaUtilities/entitydata/1.21.html#fox - on your server I got data at indexes 21 and 22

**Comment by cloakfox** [comment]
![2024-11-14_12 11 54](https://github.com/user-attachments/assets/b9f23855-9eb8-4ccb-888d-ef4e6b61b801)
Found the bad data Fox at the pwarp, im 100% sure it's the TamableFoxes plugin we use.

Thanks for the insights :)

**Comment by kennytv** [comment]
Alright cool, glad it's been resolved 👍
