### ISSUE TITLE
1.20.1 client can't join in 1.20.4 server

### ISSUE THREAD

**Issue by aaa8881** [ViaVersion/ViaVersion#4260]
### `/viaversion dump` Output

https://dump.viaversion.com/0de6b289c544b310aff4fddbc66fbf2e297973819bc8e8e5c5504c798f45dfad

### Console Error

no console error

### Bug Description

1.20.1 client can not join server , saying outdated version 1.20.4 

### Steps to Reproduce

1. install latest viaversion (build 1030) and latest viabackward (build 648) in 1.20.4 paper server. 
2. connect with 1.20.1 client

### Expected Behavior

enable 1.20.1 client

### Additional Server Info

viaversion 5.1.0 works with 1.20.1 client. 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--398%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--398%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(5.0.0)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
