### ISSUE TITLE
Viaversion getting wrong client version

### ISSUE THREAD

**Issue by karu724** [ViaVersion/ViaVersion#4262]
### `/viaversion dump` Output

https://dump.viaversion.com/0c0b6d655eeba5ef7c188304190fb5cb5f7ac93be921bd6981c8253ac9bce1f8

### Console Error

![image](https://github.com/user-attachments/assets/73bbd2af-1ec5-407a-8a2d-ed151aca3d14)
![image](https://github.com/user-attachments/assets/2ef4e873-4e0b-4920-bb49-5e13605c55fc)

### Bug Description

When viaversion get player's client version, it is different with player's version.

### Steps to Reproduce

Server Version: 1.20.4
Player Version: 1.8.9

### Expected Behavior

i can't use api

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2176%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--2176%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Cannot reproduce. This will most likely be caused by your third-party plugins, also TAB is outdated on your end.

**Comment by karu724** [comment]
![image](https://github.com/user-attachments/assets/ba5b54b8-0188-4052-b0f9-4607acdf49e7)
not a third-part plugins problem

**Comment by Kichura** [comment]
Well this is what my output displays show:

![a](https://github.com/user-attachments/assets/3bb4d483-b00d-434e-b21c-4e5511b7600b)
*(ALT. Text: Reads `1.8.x` in `viaversion list` instead of the native server version)*

**Comment by karu724** [comment]
![2024-11-16_00 27 34](https://github.com/user-attachments/assets/7c431c45-2327-4658-811e-fd579a9d78ca)
![image](https://github.com/user-attachments/assets/cbc8331f-e7b4-443d-81ae-66e6899dd638)

**Comment by karu724** [comment]
i also changed purpur to paper but it still happens

**Comment by karu724** [comment]
is it affected by velocity?

**Comment by Kichura** [comment]
are you using viaversion on bungee/velocity too? if yes, don't do that as that causes translation conflicts.

**Comment by karu724** [comment]
is there a way to fix this?
