### ISSUE TITLE
Viaversion getting wrong client version

### ISSUE THREAD

**Issue by karu724** [ViaVersion/ViaVersion#4263]
### `/viaversion dump` Output

https://dump.viaversion.com/30d817abc7bb09440074a2feb2ba06437298d16d8ebb79772a15bcacd199edd9

### Console Error

```
Put the mclo.gs link or text here.
```

### Bug Description

#4262 

### Steps to Reproduce

#

### Expected Behavior

#

### Additional Server Info

i double-checked but it doesn't look like third-party plugin problem. please check it again.
![image](https://github.com/user-attachments/assets/1a235804-0929-44ba-9598-c4db40bbe903)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2176%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Purpur--2176%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Please do not make duplicate issues as a reopen.
