### ISSUE TITLE
holding or placing an armor stand causes 1.21.2-1.21.3 clients to get kicked

### ISSUE THREAD

**Issue by Shelly333-2** [ViaVersion/ViaVersion#4270]
### `/viaversion dump` Output

https://dump.viaversion.com/2505d41c6269f3b975f5fe3a4df17b93384cb5cd9c05f3f35de2c6f7960e08f1

### Console Error

no console error

### Bug Description

if another player holds an armor stand or places an armor stand the user on 1.21.2-1.21.3 client gets kicked

### Steps to Reproduce

log on the server using 2 game clients one on version 1.21.2-1.21.3 and another one any version below it hold an armor stand or place it 

### Expected Behavior

armor stands should not kick players

### Additional Server Info

plugin list is in the viaversion dump

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Leaf--%221ab7813%22%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Leaf--%221ab7813%22%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.1.1): 20 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.1.1)-20%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(4.0.3): 5 commits behind master](https://img.shields.io/badge/ViaRewind%20(4.0.3)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.1.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.1.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Shelly333-2** [comment]
https://dump.viaversion.com/fbde174a80aa852f80654f9704507f3e8340f0328e954a12c7fc6b5548b8e0f5

**Comment by Barvalg** [comment]
![Platform: git--Leaf--%221ab7813%22%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Leaf--%221ab7813%22%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.3): 5 commits behind master](https://img.shields.io/badge/ViaRewind%20(4.0.3)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
