### ISSUE TITLE
holding or placing an armor stand causes 1.21.2-1.21.3 clients to get kicked

### ISSUE THREAD

**Issue by Shelly333-2** [ViaVersion/ViaVersion#4271]
### `/viaversion dump` Output

https://dump.viaversion.com/5034d066930af990a6a44f8ddf4223ab25478e8433560a964cfdf0929e985b6a

### Console Error

no console error

### Bug Description

if another player holds an armor stand or places an armor stand the user on 1.21.2-1.21.3 client gets kicked

### Steps to Reproduce

log on the server using 2 game clients one on version 1.21.2-1.21.3 and another one any version below it hold an armor stand or place it

### Expected Behavior

armor stands should not kick players

### Additional Server Info

i use velocity via plugins are installed only on backend

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Leaf--%221ab7813%22%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Leaf--%221ab7813%22%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Leaf is not supported, please try with a regular Paper server and also see if you can reproduce it without other plugins

**Comment by Shelly333-2** [comment]
some weird proxy issue this thread can be closed maybe since removing almsost all plugins on proxy fixed the issue

**Comment by Shelly333-2** [comment]
![Screenshot_2024-11-19-09-28-55-096](https://github.com/user-attachments/assets/690d84f3-7594-4735-9686-15443a4c4387)
One of the plugins is the issue and i use velocity proxy with legacy forwarding

**Comment by Shelly333-2** [comment]
fix is updating velocity tab to 1.7.2
