### ISSUE TITLE
Unable to connect in version 1.21.3

### ISSUE THREAD

**Issue by SkyfoxGM** [ViaVersion/ViaVersion#4272]
### `/viaversion dump` Output

https://dump.viaversion.com/2324dcc4990561b09994e40b499ec6b1e65a354ac2a89aabf36df57c789506e0

### Console Error

.

### Bug Description

I use bungee cord 

purpur server 1.21.1

It is not possible to connect players in versions 1.21.3

from 1.9 to 1.21.1 it works normally
![imagem_2024-11-18_122502391](https://github.com/user-attachments/assets/134c2bb5-4d63-49f9-b55c-895d85644c8a)

### Steps to Reproduce

.

### Expected Behavior

.

### Additional Server Info

.

### Checklist

- [ ] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [ ] I have included a ViaVersion dump.
- [ ] If applicable, I have included a paste (**not a screenshot**) of the error.
- [ ] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--2284--4e55e26%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--2284--4e55e26%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Update your proxy
