### ISSUE TITLE
Certain item components kick 1.21.3 players

### ISSUE THREAD

**Issue by Remynfv** [ViaVersion/ViaVersion#4280]
### `/viaversion dump` Output

https://dump.viaversion.com/5ff76ed60e4bf635c8ee2843e22fde0fcaacf711604fdf3a16a8f2f2c7907df1

### Console Error

```
16:29:34.780
o
Netty Client IO #2
Negative index in crash report handler (46/50)
16:29:34.840
gfh
Render thread
Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:set_entity_data'
```

### Bug Description

When certain items appear to a 1.21.3 client on a 1.21 server, the player is kicked with a packet encoding error. This happens when the item is seen in an item frame, in an inventory, or anywhere else. Tested on ViaVersionBukkit 1.

### Steps to Reproduce

1. Log in with a 1.21.3 client to a 1.21 server.
2. Run the following command to get an item that kicks you.
```
/give @p allium[custom_name='{"bold":true,"color":"#983DFF","text":"Lollypop"}',unbreakable={},hide_additional_tooltip={},rarity="rare",enchantment_glint_override=true,food={nutrition:18,saturation:46,can_always_eat:true,eat_seconds:50,effects:[{effect:{id:"minecraft:absorption",amplifier:2,duration:2400,show_particles:0b,show_icon:0b},probability:1},{effect:{id:"minecraft:hunger",amplifier:50,duration:6000,show_particles:1b,show_icon:1b},probability:.25},{effect:{id:"minecraft:infested",amplifier:255,duration:6000,show_particles:1b,show_icon:1b},probability:.01},{effect:{id:"minecraft:regeneration",amplifier:3,duration:40,show_particles:0b,show_icon:0b},probability:1},{effect:{id:"minecraft:resistance",amplifier:2,duration:300,show_particles:0b,show_icon:1b},probability:.5}],using_converts_to:{id:"minecraft:stick",count:1,components:{"minecraft:item_name":'{"italic":false,"text":"Lollypop Stick"}',"minecraft:hide_additional_tooltip":{},"minecraft:rarity":"common","minecraft:food":{nutrition:1,saturation:0,can_always_eat:true,eat_seconds:3,effects:[{effect:{id:"minecraft:blindness",amplifier:2,duration:40,show_particles:1b,show_icon:0b},probability:1},{effect:{id:"minecraft:unluck",amplifier:10,duration:6000,show_particles:1b,show_icon:1b},probability:1}]}}}}] 1
```

### Expected Behavior

Player should not be kicked from the server for seeing an item.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.1--132--b48403b%20%28MC%3A%201.21.1%29](https://img.shields.io/badge/Platform-1.21.1--132--b48403b%20%28MC%3A%201.21.1%29-3498db?style=flat-square) </br>![ViaVersion (5.1.1): 24 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.1.1)-24%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
