### ISSUE TITLE
Netty error when connecting on lower versions.

### ISSUE THREAD

**Issue by qvipin** [ViaVersion/ViaVersion#4281]
### `/viaversion dump` Output

https://dump.viaversion.com/36fa11814df92c1c85c25dd8ef4cadef87718764ea10eb23ff19dd0dd1ba25ce

### Console Error

https://mclo.gs/mPq4jLC

### Bug Description

I'm having issues with ViaBackwards (my server is on 1.21.3). When connecting with 1.21.1 or lower, it works the first time, but if I reconnect or restart the client, I get the error shown in the image. This happens to all players on my SMP—when they connect for the first time, it works, but later, they encounter this Netty error.

![image](https://github.com/user-attachments/assets/9b79fc8d-0200-4ec9-8ba4-16e9101098cc)

The attached console error is one of the many.

### Steps to Reproduce

I don't know how reproduceable this is but start off by installing all the mods in the via version dump.

1. Connect with any client other than 1.21.3.
2. See the netty error.

### Expected Behavior

No error and I should be able to connect.

### Additional Server Info

I use NGINX as a proxy with fabric and these mods: AntiXray, banhammer, Chunky, fabric-api, fabric lang kotlin, ledger, luckperms, noEnd, spark, tab, vanish, viabackwards, viafabric, viaversion, world edit.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.4.16+85--main](https://img.shields.io/badge/Platform-0.4.16+85--main-3498db?style=flat-square) </br>![ViaVersion (5.1.1): 24 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.1.1)-24%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.1.1): 12 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.1.1)-12%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).<br>Put the jars into the mod folder.<br>In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by qvipin** [comment]
It is the latest???
