### ISSUE TITLE
1.21.3 Freezes with Hologram plugins

### ISSUE THREAD

**Issue by danieliustt** [ViaVersion/ViaVersion#4283]
### `/viaversion dump` Output

Latest

### Console Error

In general, I’ve noticed one thing—maybe you’ve heard about it. When you use hologram plugins and have holograms in the game, walking through them quickly causes freezing. It seems like something related to hologram loading, as some performance adjustments were made in the update. Perhaps there's a mistake there—review it. But this only happens if you’re playing on a version lower than 1.21.3.

### Bug Description

In general, I’ve noticed one thing—maybe you’ve heard about it. When you use hologram plugins and have holograms in the game, walking through them quickly causes freezing. It seems like something related to hologram loading, as some performance adjustments were made in the update. Perhaps there's a mistake there—review it. But this only happens if you’re playing on a version lower than 1.21.3.

### Steps to Reproduce

In general, I’ve noticed one thing—maybe you’ve heard about it. When you use hologram plugins and have holograms in the game, walking through them quickly causes freezing. It seems like something related to hologram loading, as some performance adjustments were made in the update. Perhaps there's a mistake there—review it. But this only happens if you’re playing on a version lower than 1.21.3.

### Expected Behavior

In general, I’ve noticed one thing—maybe you’ve heard about it. When you use hologram plugins and have holograms in the game, walking through them quickly causes freezing. It seems like something related to hologram loading, as some performance adjustments were made in the update. Perhaps there's a mistake there—review it. But this only happens if you’re playing on a version lower than 1.21.3.

### Additional Server Info

In general, I’ve noticed one thing—maybe you’ve heard about it. When you use hologram plugins and have holograms in the game, walking through them quickly causes freezing. It seems like something related to hologram loading, as some performance adjustments were made in the update. Perhaps there's a mistake there—review it. But this only happens if you’re playing on a version lower than 1.21.3.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
Properly fill out the issue template
