### ISSUE TITLE
Missing Block Connection (Fence)

### ISSUE THREAD

**Issue by lowercasebtw** [ViaVersion/ViaVersion#4289]
### `/viaversion dump` Output

None

### Console Error

None

### Bug Description

![image](https://github.com/user-attachments/assets/17b8ad20-c2b2-46e9-8f0f-1801bddaae53)

grass block with snow on it, 1.8.x server, I’m using VFP

### Steps to Reproduce

Join 1.8.x server
Put snow grass and fence next to each other 

### Expected Behavior

They connect 

### Additional Server Info

Enza server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>
