### ISSUE TITLE
Item attributes get cleared when joining with an older version (Critical bug for servers using custom items)

### ISSUE THREAD

**Issue by Adrenalinbox** [ViaVersion/ViaVersion#4293]
### `/viaversion dump` Output

https://dump.viaversion.com/1d5a6f35e4311d7dfae96f84065427fa431446751b813f1b70861b85adfa6368

### Bug Description

I'm having trouble with the ViaVersion and ViaBackwards plugins in a 1.21.3 server.

If i have an item with attributes like attack damage, and go to my inventory, the attributes disappear completely from the item.
This happens only if i'm using minecraft client version lower than the server version (i'm using 1.20.4 to test this). This also only happens if i'm on creative mode.

This is a critical bug for anyone who has custom items in the server, and i'm hoping this will get fixed soon.

### Steps to Reproduce

1. Have a server on 1.21.3, with most recent ViaVersion and ViaBackwards. (5.1.1 or dev version).
2. Log in with 1.20.4
3. Get an item with attack damage attribute (For this you could use a plugin called ItemEdit)
4. Make sure you are in creative mode
5. Go to you inventory. Item does an animation, and the attributes are gone.

### Expected Behavior

The attributes should not disappear.

### Additional Server Info

I use Velocity, and i got a bunch of plugins on the server. I have tested this with only ViaVersion and ViaBackwards plugins, and the issue persisted.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.1--21--cfa3c61%20%28MC%3A%201.21.1%29](https://img.shields.io/badge/Platform-1.21.1--21--cfa3c61%20%28MC%3A%201.21.1%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Cannot reproduce. There is *an* issue where the id is changed, but the attributes remain just fine for me

**Comment by Adrenalinbox** [comment]
Can confirm that the bug is now fixed! Thank you for the dev for fixing this so quickly.
