### ISSUE TITLE
i can't conection

### ISSUE THREAD

**Issue by kkk2z** [ViaVersion/ViaVersion#4295]
### `/viaversion dump` Output

https://dump.viaversion.com/dfe9ad5024e21756af6bf20f54620a777c11f59af8ab98dbc951d97d9d2720bb

### Console Error

(bungee error )
```
 Kicked whilst connecting to lobby: Outdated client! Please use 1.21.1
```

### Bug Description

If we link bungeecord and papermc with online_mode off, and then introduce viaversion (backwards /rewind) in papermc and run the server with the settings for all versions and connect 1.8 clients...
I get an error. (It happens in bungee and disconnects.)
In bungeecord, viabungee is installed and the version of paper is,
````
 1.21.1-52-master@e08e667 (2024-08-26T18:02:06Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT
````
is.

Translated with DeepL.com (free version)

### Steps to Reproduce

It occurs when I link bungeecord and papermc, turn off both online_mode, set ip_fowaerding to true, set viaver to support all versions, and connect to bungeecord with 1.8.

### Expected Behavior

1.8 (1.8.9) to papermc1.21 via bungeecord.

### proxy server
bungeecord
plugins..
not 
### mainserver
 1.21.1-52-master@e08e667 (2024-08-26T18:02:06Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT
plugins...
viaversion,viarewind,viabackward

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.1--52--e08e667%20%28MC%3A%201.21.1%29](https://img.shields.io/badge/Platform-1.21.1--52--e08e667%20%28MC%3A%201.21.1%29-3498db?style=flat-square) </br>![ViaVersion (5.1.1): 34 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.1.1)-34%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(5.0.3)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
