### ISSUE TITLE
underlined text doesn't work in books

### ISSUE THREAD

**Issue by SergioK29** [ViaVersion/ViaVersion#4300]
### `/viaversion dump` Output

N/A

### Bug Description

1.21.4 client on 1.21.1 server, book with underlined component is no longer underlined

was not an issue using viaversion on 1.21.1 and having a 1.21.3 client on, so 1.21.4 related probably

### Steps to Reproduce

book with underlined component, might be in other places aswell, idk

### Expected Behavior

underlined component

### Additional Server Info

paper latest 1.21.1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Follow the issue template
