### ISSUE TITLE
underlined text doesn't work in books

### ISSUE THREAD

**Issue by SergioK29** [ViaVersion/ViaVersion#4302]
### `/viaversion dump` Output

https://dump.viaversion.com/cd540a1be8a822e38218486ce5624287ed9c6f4584f1c6ce4f76e180d940eb71

### Bug Description

1.21.4 client on 1.21.1 server, book with underlined component is no longer underlined

was not an issue using viaversion on 1.21.1 and having a 1.21.3 client on, so 1.21.4 related probably

### Steps to Reproduce

book with underlined component, might be in other places aswell, idk

### Expected Behavior

underlined component

### Additional Server Info

paper latest 1.21.1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3950--Spigot--2888990--d485cde%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-3950--Spigot--2888990--d485cde%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
