### ISSUE TITLE
Some kind of exeption that gets spammed.

### ISSUE THREAD

**Issue by nicolube** [ViaVersion/ViaVersion#4310]
### `/viaversion dump` Output

https://dump.viaversion.com/9fdc83fea0d3dccd439750c7a6cb779274dbe8b4f6dcbb760eebd1469dc91601

### Server/Client Error

```
[Put the mclo.gs link or text here.](https://mclo.gs/DATxwQT)
```

### Bug Description

I do not rly know what happend, but it seems a few user could not join for a while.

### Steps to Reproduce

Well Joining thse server

### Expected Behavior

Users can join, regardles of what is happening

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.3--81--da71382%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--81--da71382%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.2.0): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.2.0)-Even%20with%20master-brightgreen?style=flat-square) </br><br><details><summary></summary>modelengine_warn</details>

**Comment by kennytv** [comment]
You most likely have another plugin sending bad data. There's also some other issue about an issue with floodgate causing these player profile errors
