### ISSUE TITLE
Pick block not working client 1.12.4 velocity

### ISSUE THREAD

**Issue by OMGGamiing11** [ViaVersion/ViaVersion#4316]
### `/viaversion dump` Output

https://dump.viaversion.com/a892f9354b51e44d7ab0ef2bd4f59a76d30a8fda4ef34b796cc73e4cd7df26d5

### Bug Description

I am using via version on my Velocity server, I only have it on the proxy not on the backend servers. Past updating to 5.2 players joining on 1.21.4 cannot use the pick block function in creative or survival. This is a network wide issue, it does work however on players joining with any over version.

### Steps to Reproduce

1. Setup a velocity server with the latest viaversion and viabackwards releases. (My backend servers are older versions than 1.21.4, not sure if that makes a difference)
2. Log on with a 1.21.4 client
3. Try to pick a block

### Expected Behavior

The pick block function should not work.

### Additional Server Info

I use velocity, My backend servers are on 1.21.3 and 1.21.1 I use a bunch of plugins on each. All the plugins on my proxy server are Geyser/Floodgate, Maintenance, MIniMOTD, and Viaversion and Viabackwards.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.4.0--SNAPSHOT%20%28git--4aa9ee77--b455%29](https://img.shields.io/badge/Platform-velocity%203.4.0--SNAPSHOT%20%28git--4aa9ee77--b455%29-3498db?style=flat-square) </br>![ViaVersion (5.2.0): 13 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.2.0)-13%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.2.0): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.2.0)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by OMGGamiing11** [comment]
The issue still persists here is the new dump https://dump.viaversion.com/15412c305144651af76217e038db26eedb534ed24ce6bd43b4247aa6514e595a

**Comment by Barvalg** [comment]
![Platform: velocity%203.4.0--SNAPSHOT%20%28git--4aa9ee77--b455%29](https://img.shields.io/badge/Platform-velocity%203.4.0--SNAPSHOT%20%28git--4aa9ee77--b455%29-3498db?style=flat-square) </br>![ViaVersion (5.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
As stated in the additional notes of the [last release](https://github.com/ViaVersion/ViaVersion/releases/tag/5.2.0), block picking is generally only supported when ViaVersion is installed on the backend (Paper) servers. Support for block picking on velocity is not planned anytime soon.

**Comment by OMGGamiing11** [comment]
Thanks, I shifted the plugins to my backend servers and it works great now.
