### ISSUE TITLE
Item Kick

### ISSUE THREAD

**Issue by dv888** [ViaVersion/ViaVersion#4319]
### `/viaversion dump` Output

https://dump.viaversion.com/c50ef42f2526185036c4ed6a0b2dec5a86b6f6d03b0b6aa22b8680c50b0f8549

### Server/Client Error

```
Put the mclo.gs link or text here.
[latest.log](https://github.com/user-attachments/files/18169142/latest.log)

```

### Bug Description

lost connection: Internal Exception: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository

### Steps to Reproduce

1. Get the nbt spawn egg
2. immediately get kick with viaversion error

### Expected Behavior

Without getting kick and viaversion error showing

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
Wrong repo, fixed by https://github.com/ViaVersion/ViaBackwards/commit/da75e1957fa32abb367ce19b874f921823574a81
