### ISSUE TITLE
Biome with id minecraft:pale_garden has no legacy biome mapping

### ISSUE THREAD

**Issue by andrewkm** [ViaVersion/ViaVersion#4320]
### `/viaversion dump` Output

https://dump.viaversion.com/7e7236add0bd47fb8ea5c9b8c0c863217b7e45338690d584762e0aa855d06492

### Server/Client Error

`(1.16.2->1.16.1) Biome with id minecraft:pale_garden has no legacy biome mapping (custom datapack?)`

### Bug Description

Console warning above.

### Steps to Reproduce

Unsure.

### Expected Behavior

No console warning.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.4--15--bb76819%20%28MC%3A%201.21.4%29](https://img.shields.io/badge/Platform-1.21.4--15--bb76819%20%28MC%3A%201.21.4%29-3498db?style=flat-square) </br>![ViaVersion (5.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.5-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.5--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
That definitely isn't from the latest build, or you have an outdated biome-mappings file

**Comment by andrewkm** [comment]
Oh my bad, I should've checked VB commits.
