### ISSUE TITLE
viaversion packet/netty issue warning/error

### ISSUE THREAD

**Issue by hellmatic** [ViaVersion/ViaVersion#4321]
### `/viaversion dump` Output

https://dump.viaversion.com/76a82b08c175b6b64d83c8e2216d802d8704cd3c9ecd0ae36a431bfa7eb453fd

### Server/Client Error

```
https://mclo.gs/3aPlsgC
```

### Bug Description

Not sure, console gets filled with warning/errors all the time, on packets and causing disconnects all the time, not sure what the cause is

### Steps to Reproduce

No idea, no one been on today or yesterday and one tried to start to connect and instant disconnect so unsure 

### Expected Behavior

not sure

### Additional Server Info

its purpurmc server fork of paper

plugins:

chatfeelings
luckperms
essentialsX
redprotect
coreprotect
mobstoeggs-which works fine without or with it installed same issue
Gsit
phantomworlds
plugmanX
minepacks
PCFG_plugin
protocollib
silk spawners
themis
vault
viaversion
viabackwards
viarewind
placeholder API 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.4--2371--4a204f1%20%28MC%3A%201.21.4%29](https://img.shields.io/badge/Platform-1.21.4--2371--4a204f1%20%28MC%3A%201.21.4%29-3498db?style=flat-square) </br>![ViaVersion (5.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.2.1-SNAPSHOT): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.2.1--SNAPSHOT)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(4.0.5-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.5--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by hellmatic** [comment]
mate i am running the latest versions, i deleted and redownloaded those exact versions and redid all the folders along with it. i wouldnt be giving u these errors etc if im using the old stuff on 1.21.4 purpur server

**Comment by FlorianMichael** [comment]
Try to update ProtocolLib and to remove other plugins from the server

**Comment by hellmatic** [comment]
done all that, only happens when viaversion,viabackwards and viarewind are used, ive been at this problem for weeks trying to figure it out

**Comment by hellmatic** [comment]
i cant replicate, it since its not me or my mates connecting, some random weird crap going on, idk what to do about it, i want to use it so im not limited to players only on the latest version

**Comment by hellmatic** [comment]
protocollib is at the latest current available download i can get

**Comment by FlorianMichael** [comment]
Does it only happen with Via* plugins installed and nothing else? Can you also send the full server log file?
