### ISSUE TITLE
Disguise caused kick and error in 1.21.3 client on 1.12.2 server.

### ISSUE THREAD

**Issue by DreamVoid** [ViaVersion/ViaVersion#4322]
### `/viaversion dump` Output

https://dump.viaversion.com/c8e27023d85f1fbf050ead2b9520deba448d90cb217a710a344fe76dc38a7255

### Server/Client Error

```
https://mclo.gs/zhD52Ui
```

### Bug Description

Being kicked from the server when using the 1.21.3 client to transform into a blaze on a 1.12.2 server

### Steps to Reproduce

In server:
1. Prepare 1.12.2 dionysus (Paper-fork)
2. Install ViaVersion-5.2.1, LibsDisguises-10.0.29-Free, GadgetsMenu and other necessary plugins.

In client:
1. Login using 1.21.3 vanilla client
2. Choose Blaze disguise in GadgetsMenu
3. Error and kick happened.

### Expected Behavior

Players should play normally

### Additional Server Info

Using Velocity 3.4.0
Using Java 21
Using https://github.com/nopjmp/Dionysus
Using latest dev ViaVersion build 1059

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Dionysus--%228d3095e%22%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Dionysus--%228d3095e%22%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (5.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
That's not a Via issue
