### ISSUE TITLE
ViaVersion Update and AntiCheat Problems

### ISSUE THREAD

**Issue by SentorCraft** [ViaVersion/ViaVersion#4326]
### `/viaversion dump` Output

https://dump.viaversion.com/bba68797ce2d7c17764ec8529e9a507ab322801f9bc776e389307de361b5ebe3

### Bug Description

After upgrading Viaversion from 5.0.2 to 5.2.0, GrimAC starts to give too much false detections.

### Steps to Reproduce

Upgrade ViaVersion from 5.0.2 to 5.2.0
Join the game
Place block
Shoot arrow
Hit mobs

### Expected Behavior

GrimAC 2.3.68 should not give false detection to legit players too much.
Place block - Aim
Shooting Arrow - Timer
Hitting - Aim

### Additional Server Info

GrimAC 2.3.68
ViaVersion 5.2.0

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1171%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Purpur--1171%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (5.2.0): 17 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.2.0)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
