### ISSUE TITLE
1.21.2+ Stuck on respawn screen

### ISSUE THREAD

**Issue by lowercasebtw** [ViaVersion/ViaVersion#4330]
### `/viaversion dump` Output

e

### Server/Client Error

```
none
```

### Bug Description

On 1.21.2+, on Loyisa server, when dying you get stuck on Respawn screen.
![image](https://github.com/user-attachments/assets/d6592a6d-0733-4fc5-81ca-66de5666a5f0)

### Steps to Reproduce

Join eu.loyisa.cn with 1.21.2+
Die
Get stuck on respawn screen

### Expected Behavior

You respawn normally

### Additional Server Info

ViaVersion 5.2.1-SNAPSHOT

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Please don't open issues without dumps and test these on clean setups first, I cannot reproduce this with ViaProxy

**Comment by lowercasebtw** [comment]
I was told to report this by EnzaXD

**Comment by lowercasebtw** [comment]
Turns out it was caused by your mod
