### ISSUE TITLE
[CANNOT JOIN SERVER] Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException

### ISSUE THREAD

**Issue by leothawne** [ViaVersion/ViaVersion#4332]
### `/viaversion dump` Output

https://dump.viaversion.com/e0a367fb8dce7f458b811dc4a39f5e8d614c533e53e78fcf624724ce820a9071

### Server/Client Error

```
https://mclo.gs/VSoEe7j
```

### Bug Description

I cant join my own server
![image](https://github.com/user-attachments/assets/48bfb8ec-ff74-43bb-a7e1-7fc8623086e7)

### Steps to Reproduce

1. An invasion naturally started
2. I tried to kill a witch
3. I got instantly kicked from the server and cannot join back

### Expected Behavior

Enter my server

### Additional Server Info

![image](https://github.com/user-attachments/assets/0479791b-7580-4ae7-b9ee-5a1cdf604032)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.3--2358--16ce24a%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--2358--16ce24a%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.2.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.2.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by leothawne** [comment]
I was trying to join with MC 1.21.1. I switched to MC 1.21.3 and now I got this error:
![image](https://github.com/user-attachments/assets/a1b2c6d4-cf4b-40f4-8410-d75da0a8d6ab)

**Comment by kennytv** [comment]
One of your other plugins is sending bad packet data. For clients on the same version as the server, Via doesn't do anything
