### ISSUE TITLE
Longer commands/chat messages

### ISSUE THREAD

**Issue by HydroTekZ** [ViaVersion/ViaVersion#692]
I was hoping you could add support for longer commands and chat messages (which was added in MC 1.11).

**Comment by ysl3000** [comment]
Like automatically splitting the incoming message if it's longer than 100 characters?!

**Comment by MylesIsCool** [comment]
We currently limit the chat message length to stop it kicking you, we don't send 2 messages as that would trigger most spam filters (as they would be instantly after each other)

If there's enough want for a feature like this, I guess it could be implemented. It's worth noting that there's no easy way to increase the internal limit and it will probably break any chat packet plugins if we workaround it.

**Comment by Brokkonaut** [comment]
If this can be added it would be great :)

**Comment by HydroTekZ** [comment]
Some 1.12 players feel trolled when half of their messages just disappars :P

**Comment by Brokkonaut** [comment]
Why did you close this?

**Comment by HydroTekZ** [comment]
Never mind

**Comment by TheIntelloBox** [comment]
Add this ! :)

**Comment by Inuun** [comment]
sending two messages can be enabled only for players with permission
for commands I don't know, but the command packet cannot be "hacked" to accept more characters?

**Comment by Starjon** [comment]
Would really love this!

**Comment by Rida94** [comment]
Maybe at least add a message to be sent as a warning saying that their message have been cancelled due to it being considered spam?

**Comment by zedwick** [comment]
I, too, would like to see support for longer messages added.

Could a second message be sent after a configurable delay? We server owners would of course know the necessary delay required, if needed. (I handle my chat filtering bungee-side, so would likely not need to avoid issues bukkit-side by adding a delay).

**Comment by raidmax21** [comment]
> We currently limit the chat message length to stop it kicking you, we don't send 2 messages as that would trigger most spam filters (as they would be instantly after each other)
> 
> If there's enough want for a feature like this, I guess it could be implemented. It's worth noting that there's no easy way to increase the internal limit and it will probably break any chat packet plugins if we workaround it.

Add an option in the config to enable it. That way, if they have a chat filter that could have a conflict, they can just keep this feature on false.

**Comment by k0l0r3k99** [comment]
I've modified spigot version, so it isn't problem for me to allow longer messages, but anyway ViaVersion cutting it. I think it should be setting for this.

**Comment by MylesIsCool** [comment]
I'm gonna close this, there's a PR with the changes which if someone in the future finds this and wishes to tidy it up so that it works better we'll pull it in.

Otherwise I suggest modifying Spigot etc.

**Comment by Packsolite** [comment]
> I'm gonna close this, there's a PR with the changes which if someone in the future finds this and wishes to tidy it up so that it works better we'll pull it in.
> 

Any chance the PR still exists somewhere? I would love implementing it for my server.

**Comment by FlorianMichael** [comment]
I believe this was the original PR: https://github.com/ViaVersion/ViaVersion/pull/835

Though that is quite old and won't compile against latest Via*; You can install https://www.spigotmc.org/resources/viachatfixer.61955/ as solution I believe.
