### ISSUE TITLE
Hand Bug (Report Complete)

### ISSUE THREAD

**Issue by zBoringDrop** [ViaVersion/ViaVersion#798]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/9683bffb95d584eb1a0661362ce3c309

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No, only BungeeCord.

### How does this error happen? login? Using an item? 
Sorry for my bad english.
I use the 1.3.0 viaversion version installed only in bungeecord.
The problem is when i switch from a 1.8 server to a 1.9x server that happen the hand bug. I already tested with 0 plugin and from 0 config, but none, the bug on bungee stills why not if i use viaversion on each server.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

No

**Comment by TheIntelloBox** [comment]
Did you try maybe a snapshot ? https://ci.viaversion.com/job/ViaVersion-DEV/changes

**Comment by zBoringDrop** [comment]
I tried now with dev 75 but none, the bug stills

**Comment by zBoringDrop** [comment]
Can someone test this?

**Comment by TheIntelloBox** [comment]
Could you try with the latest version maybe ? :D https://ci.viaversion.com/job/ViaVersion-DEV/changes

**Comment by zBoringDrop** [comment]
none, i switched to use viaversion on single server to fix this :\

**Comment by krusic22** [comment]
This happens if you use ViaVersion on both Bungee and Spigot.

**Comment by jack-theripper** [comment]
@Matsv , @MylesIsCool , @Gerrygames 

Video file. Reproduce bug. 
[https://mega.nz/#!S6pEDAbA!9uBKfjlmeaZ_Skz-cv-zlyRH6aeoejsmHnHzicb4JCw](https://mega.nz/#!S6pEDAbA!9uBKfjlmeaZ_Skz-cv-zlyRH6aeoejsmHnHzicb4JCw)

**Comment by MylesIsCool** [comment]
I'm unable to replicate, but this should be fixed - https://github.com/ViaVersion/ViaVersion/commit/12b45d95e0364e740d96aa57e4f4b6c8faf06fbf

(In builds from ci.viaversion.com)
