### ISSUE TITLE
HoverEvent showing an Item is not working correctly for players using 1.12

### ISSUE THREAD

**Issue by ghost** [ViaVersion/ViaVersion#799]
### What is the output link of /viaversion dump? 
Don't really want to share all of that information in public. However, all of the Spigot servers are running 1.10.2 and BungeeCord is the latest version. Running ViaVersion on BungeeCord only. Also ViaVersion is the latest build from your jenkins(build 190)

Also forgot to mention: ""chat-nbt-fix": true,"

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well) 
Yes, BungeeCord. Also a custom chat plugin on BungeeCord.

### How does this error happen? login? Using an item? 
When showing the player's item in their hotbar in chat, for users on 1.12+ it will display "Invalid Item!"
I read that this issue was fixed here: https://github.com/MylesIsCool/ViaVersion/issues/712 However, it does not seem to be fixed for me. The way I am sending chat messages to the player is:
`ProxiedPlayer player = ...;`
`player.sendMessage(BaseComponent[] components);`

The hover event works fine for all other versions(client side) except 1.12. I'm not sure if the fix for issue 712 was spigot sided only or not, just hoping to get some info.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No

**Comment by MylesIsCool** [comment]
Could you provide the full json of the message your sending?

(Specifically the item part)

**Comment by Fridgey** [comment]
These are some examples of the full json of the item that goes into the HoverEvent: 
`{id:"minecraft:diamond_chestplate",Count:1b,tag:{ench:[0:{lvl:4
s,id:0s}]},Damage:0s}`
`{id:"minecraft:grass",Count:6b,Damage:0s}`
`{id:"minecraft:cooked_beef",Count:55b,tag:{ench:[0:{lvl:1s,id:3
4s}],HideFlags:1,display:{Name:"Cooked Beef"}},Damage:0s}`

Once the Spigot side of the plugin get's the json, it sends it over to bungee and then I insert it into a BaseComponent array, using ComponentBuilder I set the HoverEvent, and send it to the player with ProxiedPlayer.sendMessage.

Hope this is what you wanted. If you need anything else let me know.

**Comment by caoli5288** [comment]
Same issues. Hope fix quick.

**Comment by raidmax21** [comment]
Any progress on this bug?

**Comment by MylesIsCool** [comment]
@Fridgey Would you be able to provide the full JSON of an invalid message? (eg. https://github.com/SpigotMC/BungeeCord/blob/master/chat/src/main/java/net/md_5/bungee/chat/ComponentSerializer.java#L42) 

The issue is in 1.12 they changed their Mojang NBT JSON format which leads to some issues, from what I can see the patch should apply to the JSON you've provided but maybe it's in relation to how you show the item.

**Comment by Fridgey** [comment]
This is the entire output of: System.out.println(ComponentSerializer.toString(component));

{"extra":[{"text":"§8["},{"color":"dark_aqua","text":"T"},{"text":"§8▪"},{"text":""},{"color":"dark_aqua","text":"S"},{"text":"§8]§7|"},{"text":"§8["},{"text":""},{"color":"blue","text":"-"},{"text":""},{"color":"blue","text":"SquishySquish"},{"text":""},{"text":"§8]§7|"},{"text":""},{"text":"§8[§6Admin§8]§7|"},{"text":"§8["},{"color":"green","text":"Refrigerbater"},{"text":"§8] "},{"color":"dark_aqua","text":""},{"color":"dark_aqua","text":"this is my slot 1item: "},{"color":"dark_aqua","italic":true,"hoverEvent":{"action":"show_item","value":[{"text":"{id:\"minecraft:cooked_beef\",Count:26b,tag:{ench:[0:{lvl:1s,id:34s}],HideFlags:1,display:{Name:\"§6Cooked Beef\"}},Damage:0s}"}]},"text":"[Cooked Beef] "},{"color":"dark_aqua","text":""},{"color":"dark_aqua","text":"derp "}],"text":""}

**Comment by MylesIsCool** [comment]
Can you show the code you use to add the hover event? The output provided is definitely not a format we're expecting.

**Comment by Fridgey** [comment]
I use the ComponentBuilder class to make it easier in putting all of the chat parts together. This is where I add the hover event for the itemstack. "builder" is the ComponentBuilder instance. "itemJson" is a list of Pair<String, String> objects, the Pair#getRight() is the JSON code of the itemstack itself. 

`BaseComponent[] theActualJson = new BaseComponent[1];`
`theActualJson[0] = new TextComponent(itemJson.get(slot).getRight());`
`HoverEvent hoverEvent = new HoverEvent(Action.SHOW_ITEM, theActualJson);`

`// "StringUtil.strip(itemJson.get(slot).getLeft())" <- Applies a new component and this is the text`
`// of it(the itemstack name)`
`builder.append("[" + StringUtil.strip(itemJson.get(slot).getLeft()) + "] ");`
`builder.color(channel.getColor());`
`builder.italic(true);`
`builder.event(hoverEvent);`

This is the class used to get the JSON from the itemstack, which then gets sent to Bungee to process and add into the chat message in the hover event above: https://gist.github.com/Fridgey/cd3f9c1537face97d30ce133ce5bc10c

**Comment by raidmax21** [comment]
Any update on this?

**Comment by EnderGriefeur99** [comment]
this is not patch

**Comment by Matocolotoe** [comment]
Any news on this @MylesIsCool ?

**Comment by EnderGriefeur99** [comment]
any one works on a patch ?
