### ISSUE TITLE
Client crash + scoreboard team bug

### ISSUE THREAD

**Issue by kennytv** [ViaVersion/ViaVersion#859]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/569fffcc59a673a10ffc4244dd92817d51c0d1ce0be96f7d6370f39f6a9d2ebf

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord with ViaVersion + Spigot Server with ViaVersion

### How does this error happen? login? Using an item? 
Joining on a used 1.8 Freebuild server crashes the client in a specific case (dunno what exactly, check the crash log below :p)

(Second problem, unrelated to everything else here besides VV on Bungee+Spigot:
All scoreboard teams/messages turn white after a certain amount of characters https://prnt.sc/k830mm)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Client crash-log: https://hastebin.com/igixaduyac.coffeescript

**Comment by Matsv** [comment]
Could you try the latest official release for the crash issue?

**Comment by Gerrygames** [comment]
The client crash is still happening on the latest version:
https://gist.github.com/Gerrygames/71f439f108a4385b164bdf188be8f90b
https://dump.viaversion.com/ed58e1fa3c6fce9278a16265cdd8e0fe0db4b0ddd460eae01221711d498b127e

**Comment by KennyTV** [comment]
For me the crash has been fixed, the scoreboard team name is still existent

**Comment by KennyTV** [comment]
Scoreboard team colors still not fixed, even though the new option "team-colour-fix" is enabled
