### ISSUE TITLE
Players Cannot Swim

### ISSUE THREAD

**Issue by MacTh3Mac** [ViaVersion/ViaVersion#872]
### What is the output link of /viaversion dump? 

https://dump.viaversion.com/8df1c2ea8c5197b88b4122ebcde1ad7a1961aed8e1da496c110fedb618fffc02

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Bungeecord Latest,  PaperSpigot Latest

### How does this error happen? login? Using an item? 

Players cannot swim in water,   they just drop to the bottom of the ocean

### Is there an error in the console? Use pastebin.com. Is there a kick message?

None

**Comment by MacTh3Mac** [comment]
Additionally even boats drop straight to floor!

**Comment by MinecraftAdmin** [comment]
Not having either swim or boat issues on 1.4.0

**Comment by Pokechu22** [comment]
Someone else also reported this same issue, and additionally that lava looked like water and glass was treated as permeable (water/lava above it caused dripping effects).  My guess is that it's a tags issue, since all of those behaviors are caused by tags.  However, I don't know how to reproduce and haven't attempted to reproduce myself.

**Comment by PureGero** [comment]
Can be reproduced by having a BungeeCord with Viaversion 1.40 connected to a Spigot server with a survival world. All water is rendered as water, but acts like air (can walk/fall through it as if nothing's there). All lava is also rendered as water (but you can still catch fire by stepping in it).

**Comment by cfr** [comment]
I also experience this on survival server (though water is ok on creative).
@MinecraftAdmin can you please list you bungee and survival spigot plugins?

**Comment by InfinityAspire** [comment]
Can confirm I am experiencing this as well.
Using ViaVersion 1.4.2 on Bungee

**Comment by Seshpenguin** [comment]
This bug is also affecting my server (BungeeCord/Waterfall connecting to 1.12.2 MC Server).

**Comment by MylesIsCool** [comment]
Going to close:
Should be fixed in latest version otherwise if someone can provide a .zip of a server to replicate this :)
