### ISSUE TITLE
Players frequently losing connection on new ViaVersion (when 1.13 support was added)

### ISSUE THREAD

**Issue by cheetohead** [ViaVersion/ViaVersion#954]
### What is the output link of /viaversion dump? 

https://dump.viaversion.com/4a5a170c4dbc46c857295d323134f3e3657cb1a9ad17ec168c73abc294922382

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Error does not happen on ViaVersion 1.3.0 or lower, but happens on any more recent version, it's happening on the latest build of ViaVersion and ViaVersion-DEV, the server is also using the latest ViaBackwards-DEV and it was happening on the non dev version too. Its happened on Spigot 1.12, Spigot 1.12.2, and PaperSpigot 1.12.2, This also happens when only ViaVersion is used without ViaBackwards. Plugins: https://pastebin.com/uBS7UvQ2

(Note: This is happening to all players on all versions 1.10-1.13, not just on 1.13)

### How does this error happen? login? Using an item? 
Happens a lot Login or randomly

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/dvJWHnjj
https://pastebin.com/H85AbJck
https://pastebin.com/tRhE0AQA

**Comment by MylesIsCool** [comment]
What is the ping of players to your server?

Are you able to replicate this by yourself? (You say all players? Does everyone experience this or could it be based on latency?)

**Comment by cheetohead** [comment]
Most players have a 5-10ms ping, however when I use the newer ViaVersion with 1.13 support a lot of people have been getting poor connections and only get 1 bar in tab. And Yes I'm able to replicate it myself, I've timed out a fair amount of times aswell (Usually when my game is minimized, not sure if that has anything to do with it)

**Comment by KennyTV** [comment]
Same problem here, rare but apparently random disconnects on executing (vanilla and other) commands, doesn't seem to matter which (gamemode, ..., any other command from another plugin). I haven't realy looked at the circumstances, but it seems random

**Comment by MylesIsCool** [comment]
We've never been able to replicate this, I've fixed a possible deadlock in latest build. Otherwise it's case of if you can build a .zip which can replicate this i'll happily look into it further (ensure it works on other machines). Otherwise i'm convinced this might be down to something else.
