### ISSUE TITLE
Gui menu not clickable with Viaversion (Holograms)

### ISSUE THREAD

**Issue by Kirrasio** [ViaVersion/ViaVersion#972]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/ea8c63eccbc7c26fc895f21084d2960b596e625f53e908200b8f267df65e0a2e

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
We are currently using bungeecord, in bungeecord we have:
Bungeeadmintools
bungeecontrolbridge
depenizenbungee
empbungee
luckperms
nuvotifier
viaversion
yamler
Bungee Version: 1.13-snapshot:715ec07:1348
Spigot version: 1.12.2 
Plugins:
luckperms
placeholderapi
worldborder
generallib
votifier
openterraingenerator
votingplugin
fawe
fav
bountyhunter
signshop
zhorse
protocollib
citizens
cmi
combatlogx
denizen
chatcontrol
holographic displays
worldguard
mythicmobs
holographic menus 
jobs
kingdoms
depenizen
projectkorra

### How does this error happen? login? Using an item? 
When we use our gui holographic menus it will not allow us to click anything on it with viaversion plugin in.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No error message, once removed it goes back to full functionality.
I've attempted enabling hologram-patch: true

**Comment by MylesIsCool** [comment]
Due to the complexities on how holograms are handled in regards to clicking them, it's not something that going to have a simple solution. I'll happily accept any PRs implementing this though.
